[Azure] Application Gateway WAF: add event.reason
elastic/integrations pull request #10007
Opened 2024-05-29 13:52 UTC by jH-

## Proposed commit message
Update Azure Application Gateway pipeline to parse & include values from the `json.properties.details.data` key, renamed to the common schema field `event.reason`.

This field provides action context by logging the specific data found in requests that matched a rule.

_Excludes field if `json.properties.details.message` contains values indicating missing headers, content etc., in which case the field contains unecessary/duplicate data._

## Checklist
- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have added an entry to my package's `changelog.yml` file.

## How to test this PR locally
```
elastic-package stack up -v -d

# check that the updated integration version is included (https://localhost:8080/search?package=azure)

elastic-package test pipeline

elastic-package stack down
```

2024-05-30 11:34 UTC, jH- commented
> ❌ Author of the following commits did not sign a [Contributor Agreement](https://www.elastic.co/contributor-agreement): [cbccc91](https://github.com/elastic/integrations/commit/cbccc9179fa72a9dfbbb69c6c234494e3c37dc9d), [b0c3043](https://github.com/elastic/integrations/commit/b0c3043cb1834f8d144a1c0f25ba63edc788e4a2), [15b7361](https://github.com/elastic/integrations/commit/15b73611eb122ae89a237ad77542685fbe898a24), [d9f0ebd](https://github.com/elastic/integrations/commit/d9f0ebd6ced3e4365768425360691f7a1969ebef), [57b5d96](https://github.com/elastic/integrations/commit/57b5d96873f2616a96720aadd7dd7e4b99fe9bcf), [2037f9a](https://github.com/elastic/integrations/commit/2037f9a4b1baf270273d03081b6af7eddafc2a77)
> 
> Please, read and sign the above mentioned agreement if you want to contribute to this project

Signed.

2024-07-03 08:21 UTC, elasticmachine commented
Pinging @elastic/security-service-integrations (Team:Security-Service Integrations)

2024-07-05 07:32 UTC, kcreddy commented
/test

2024-07-05 07:46 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-07-05 07:47 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13283)
* Commit: 2037f9a4b1baf270273d03081b6af7eddafc2a77

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13283","number":13283,"commit":"2037f9a4b1baf270273d03081b6af7eddafc2a77"}],"number":13283}
buildkite-pr-comment-->

2024-07-05 08:15 UTC, zmoog commented on packages/azure/changelog.yml
> +      link: ""
Link to this PR, used in docs.

```suggestion
      link: https://github.com/elastic/integrations/pull/10007
```

2024-07-05 08:43 UTC, kcreddy commented on packages/azure/changelog.yml
> +- version: "1.11.5"
```suggestion
- version: "1.12.0"
```
You can bump minor since its an enhancement adding new field.

2024-07-05 08:43 UTC, kcreddy commented on packages/azure/manifest.yml
> +version: 1.11.5
```suggestion
version: 1.12.0
```

2024-07-05 08:43 UTC, kcreddy commented on packages/azure/data_stream/application_gateway/_dev/test/pipeline/test-application-gateway-raw.log-expected.json
> +                "reason": "127.0.0.1"
This value for `event.reason` doesn't seem to be right.

2024-08-05 07:56 UTC, zmoog commented
@jH- There are some minor changes; let us know if you need anything from us!

2024-08-07 07:42 UTC, jH- commented on packages/azure/data_stream/application_gateway/_dev/test/pipeline/test-application-gateway-raw.log-expected.json
> +                "reason": "127.0.0.1"
The data for this particular test log entry is based on MS's own example, [found here](https://learn.microsoft.com/en-us/azure/web-application-firewall/ag/web-application-firewall-logs#firewall-log) (Resource logs for Azure Web Application Firewall).

I agree that the value _appears_ to be missing some text to provide more context, but for this rule it would be correct (according to the documentation).

2024-08-09 19:15 UTC, andrewkroh commented on packages/azure/data_stream/application_gateway/elasticsearch/ingest_pipeline/default.yml
> +      if: 'ctx.json?.properties?.details?.data != null && !(ctx.json?.properties?.details?.message.contains("Equal 0")) && !(ctx.json?.properties?.details?.message.contains("EQ matched 0"))'
For readability I would remove the single-quotes and unnecessary parens. Plus for null safety it should have a null-check for the `json.properties.details.message` (using the null-safe operator with a method isn't safe).

```
     if: ctx.json?.properties?.details?.data != null &&
       ctx.json?.properties?.details?.message != null &&
       !ctx.json.properties.details.message.contains("Equal 0") &&
       !ctx.json.properties.details.message.contains("EQ matched 0")
```

But I wonder if you meant to write it like this, because with `ignore_missing: true` the null check for `json.properties.details.data` is not strictly necessary.

```
     if: ctx.json?.properties?.details?.message != null &&
       !ctx.json.properties.details.message.contains("Equal 0") &&
       !ctx.json.properties.details.message.contains("EQ matched 0")
```

2024-08-09 19:20 UTC, andrewkroh commented
@jH- , can you please sign the [Contributor Agreement](https://www.elastic.co/contributor-agreement)?

NOTE that this PR contains commits from two different email addresses so you may be need amend those commits to use the same email that you use to sign the CLA.

2024-08-14 06:51 UTC, jH- commented on packages/azure/data_stream/application_gateway/elasticsearch/ingest_pipeline/default.yml
> +      if: 'ctx.json?.properties?.details?.data != null && !(ctx.json?.properties?.details?.message.contains("Equal 0")) && !(ctx.json?.properties?.details?.message.contains("EQ matched 0"))'
Thanks, updated as per your suggestion.

2024-08-14 06:56 UTC, jH- commented
> @jH- , can you please sign the [Contributor Agreement](https://www.elastic.co/contributor-agreement)?
> 
> NOTE that this PR contains commits from two different email addresses so you may be need amend those commits to use the same email that you use to sign the CLA.

Signed.

2024-08-15 17:51 UTC, andrewkroh approved these changes

2024-08-22 09:54 UTC, kcreddy commented
/test

2024-08-22 10:43 UTC, kcreddy commented
@jH- could you please fix the merge conflicts?

2024-08-23 09:20 UTC, zmoog approved these changes

2024-08-23 10:27 UTC, kcreddy approved these changes

2024-08-23 12:07 UTC, kcreddy commented
/test

2024-08-23 12:23 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14965)
* Commit: a2b7ebb63fdacdaf94d0fe417b375226cf7a5edd

### Failed CI Steps
* [Check integrations azure](https://buildkite.com/elastic/integrations/builds/14965#01917f28-473b-46ec-a2bd-34b473732669)

### History
* :broken_heart: [Build #14893](https://buildkite.com/elastic/integrations/builds/14893) failed af7f7f8b18126f9fb36a75d03781660cc916b33e
* :green_heart: [Build #13283](https://buildkite.com/elastic/integrations/builds/13283) succeeded 2037f9a4b1baf270273d03081b6af7eddafc2a77

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14965","number":14965,"commit":"a2b7ebb63fdacdaf94d0fe417b375226cf7a5edd"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14893","number":14893,"commit":"af7f7f8b18126f9fb36a75d03781660cc916b33e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13283","number":13283,"commit":"2037f9a4b1baf270273d03081b6af7eddafc2a77"}],"number":14965}
buildkite-pr-comment-->

2024-08-23 12:30 UTC, andrewkroh requested changes
There are a bunch of changes outside of the packages/azure directory that need to undone. I think they were the result of merge issue.

2024-09-09 13:08 UTC, jH- reviewed
_deleted_

2024-09-25 17:48 UTC, andrewkroh commented
/test

2024-09-25 18:09 UTC, merged

2024-09-25 18:09 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16422)
* Commit: d5c9a821e0c9c1cc9497897543b73a74e5b8bb2a

### History
* :broken_heart: [Build #14965](https://buildkite.com/elastic/integrations/builds/14965) failed a2b7ebb63fdacdaf94d0fe417b375226cf7a5edd
* :broken_heart: [Build #14893](https://buildkite.com/elastic/integrations/builds/14893) failed af7f7f8b18126f9fb36a75d03781660cc916b33e
* :green_heart: [Build #13283](https://buildkite.com/elastic/integrations/builds/13283) succeeded 2037f9a4b1baf270273d03081b6af7eddafc2a77

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16422","number":16422,"commit":"d5c9a821e0c9c1cc9497897543b73a74e5b8bb2a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14965","number":14965,"commit":"a2b7ebb63fdacdaf94d0fe417b375226cf7a5edd"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14893","number":14893,"commit":"af7f7f8b18126f9fb36a75d03781660cc916b33e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13283","number":13283,"commit":"2037f9a4b1baf270273d03081b6af7eddafc2a77"}],"number":16422}
buildkite-pr-comment-->