[Apache Tomcat] Add JDBC Connection Pool maxActive on Ingestion Pipeline
elastic/integrations pull request #10038
Opened 2024-05-31 01:36 UTC by MatheusGelinskiPires

## Type

- Enhancement

## Proposed commit message

Extract the maxActive field from the Apache Tomcat connection pool using the ingest pipeline.

This data could be used to identify the usage of a JBDC pool.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [x] Tested in a real case adding this change to the default ingest pipeline.

## How to test this PR locally

1. Install elastic-agent
2. Add the Apache Tomcat integration

## Related issues

- Closes #10037

## Screenshots

None

2024-05-31 02:01 UTC, MatheusGelinskiPires commented
Please label the PR as an enhancement as I have no permissions to set labels.

2024-05-31 02:02 UTC, MatheusGelinskiPires commented
> ❌ Author of the following commits did not sign a [Contributor Agreement](https://www.elastic.co/contributor-agreement): [67441af](https://github.com/elastic/integrations/commit/67441aff1647a3b03b683de7329a897f264c0592), [f888953](https://github.com/elastic/integrations/commit/f888953468e028f300b5ded08b106ac1a63f44d7), [48bdfe5](https://github.com/elastic/integrations/commit/48bdfe56da51ef836e1a09a31337a72d7be95adc)
> 
> Please, read and sign the above mentioned agreement if you want to contribute to this project

already done

2024-05-31 04:51 UTC, aliabbas-elastic requested changes
After doing these changes please run once `elastic-package build` so that the new metric introduced is displayed in `README`

2024-05-31 04:51 UTC, aliabbas-elastic commented on packages/apache_tomcat/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/10037
```suggestion
      link: https://github.com/elastic/integrations/pull/10038
```

2024-05-31 04:51 UTC, aliabbas-elastic commented on packages/apache_tomcat/changelog.yml
> +- version: "1.5.2"
Please update this same version in `packages/apache_tomcat/manifest.yml`

2024-05-31 04:52 UTC, aliabbas-elastic commented
Also, as you're introducing a new metric to the data stream, it's better to update the pipeline and system tests

2024-05-31 05:22 UTC, shmsr commented on packages/apache_tomcat/data_stream/connection_pool/fields/fields.yml
> +              description: Maximum active of connection pool.
The description sounds incomplete. Not just this one but for fields like `total`.

>  The maximum number of active connections that can be allocated from this pool at the same time.

^^ I got it from the doc itselfl.

2024-06-03 18:34 UTC, MatheusGelinskiPires commented
> Also, as you're introducing a new metric to the data stream, it's better to update the pipeline and system tests

the maxActive is already on the [ context.xml](https://github.com/elastic/integrations/blob/main/packages/apache_tomcat/_dev/deploy/docker/configs/context.xml#L14) file but I didn't found the maxTotal in there.

2024-06-03 18:34 UTC, MatheusGelinskiPires commented
> After doing these changes please run once `elastic-package build` so that the new metric introduced is displayed in `README`

done

2024-06-04 05:48 UTC, aliabbas-elastic commented
> the maxActive is already on the [context.xml](https://github.com/elastic/integrations/blob/main/packages/apache_tomcat/_dev/deploy/docker/configs/context.xml#L14) file but I didn't found the maxTotal in there.

You need to basically add the metric that you are getting in live response [here](https://github.com/elastic/integrations/blob/main/packages/apache_tomcat/data_stream/connection_pool/_dev/test/pipeline/test-conection-pool-metrics.json). And then run `elastic-package test pipeline -v -g` which would test the changes done. After that passes, please also run `elastic-package test system -v -d connection_pool -g` which would run the system tests and update the `sample_event.json`

2024-06-04 18:45 UTC, MatheusGelinskiPires commented
> > the maxActive is already on the [context.xml](https://github.com/elastic/integrations/blob/main/packages/apache_tomcat/_dev/deploy/docker/configs/context.xml#L14) file but I didn't found the maxTotal in there.
> 
> You need to basically add the metric that you are getting in live response [here](https://github.com/elastic/integrations/blob/main/packages/apache_tomcat/data_stream/connection_pool/_dev/test/pipeline/test-conection-pool-metrics.json). And then run `elastic-package test pipeline -v -g` which would test the changes done. After that passes, please also run `elastic-package test system -v -d connection_pool -g` which would run the system tests and update the `sample_event.json`

got it!

I will do it and also create another PR to fix the CLA issues.

2024-06-04 18:54 UTC, shmsr requested changes

2024-06-04 18:54 UTC, shmsr commented on packages/apache_tomcat/changelog.yml
> +    - description: Add JDBC Connection Pool maxActive on Ingestion Pipeline.
```suggestion
    - description: Add JDBC Connection Pool's `maxActive` in the ingest pipeline.
```

2024-06-04 18:54 UTC, shmsr commented on packages/apache_tomcat/changelog.yml
> +- version: "1.5.2"
With a patch upgrade, we should not really do field modifications. This is at least a minor upgrade IMO i.e., 1.6.0

2024-06-04 20:36 UTC, MatheusGelinskiPires commented
Closing this PR because it was replace by the #10069

2024-06-04 20:36 UTC, closed without merging