[watchguard_firebox] Initial release of the WatchGuard Firebox
elastic/integrations pull request #10110
Opened 2024-06-08 18:58 UTC by brijesh-elastic

## Proposed commit message

Create New integration package watchguard_firebox.

- Added a log data stream.
- Added data collection logic for log data stream.
- Added the ingest pipeline for log data stream.
- Mapped fields according to the ECS schema and added Fields metadata in the appropriate yml files.
- Added dashboards and visualizations.
- Added test for pipeline for log data stream.
- Added system test cases for log data stream.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally

- Clone integrations repo.
- Install elastic package locally.
- Start elastic stack using elastic-package.
- Move to integrations/packages/watchguard_firebox directory.
- Run the following command to run tests.
> elastic-package test
```
--- Test results for package: watchguard_firebox - START ---
╭────────────────────┬─────────────┬───────────┬─────────────────────────────────────────────────────────────────────────────┬────────┬──────────────╮
│ PACKAGE            │ DATA STREAM │ TEST TYPE │ TEST NAME                                                                   │ RESULT │ TIME ELAPSED │
├────────────────────┼─────────────┼───────────┼─────────────────────────────────────────────────────────────────────────────┼────────┼──────────────┤
│ watchguard_firebox │             │ asset     │ dashboard watchguard_firebox-5fb58f2b-8720-4b57-89b6-0f727f0d260f is loaded │ PASS   │        882ns │
│ watchguard_firebox │             │ asset     │ search watchguard_firebox-0c03afcf-e39d-484a-8575-0630b7bb892a is loaded    │ PASS   │        308ns │
│ watchguard_firebox │             │ asset     │ search watchguard_firebox-19e90429-51c9-4f47-8889-baf56bdc7735 is loaded    │ PASS   │        237ns │
│ watchguard_firebox │             │ asset     │ search watchguard_firebox-5cbe635b-9d2e-4d14-b2d4-e7146c421eaf is loaded    │ PASS   │        195ns │
│ watchguard_firebox │             │ asset     │ search watchguard_firebox-9173ff94-4af2-4f6d-86bc-7123d0f335f5 is loaded    │ PASS   │        216ns │
│ watchguard_firebox │ log         │ asset     │ index_template logs-watchguard_firebox.log is loaded                        │ PASS   │        184ns │
│ watchguard_firebox │ log         │ asset     │ ingest_pipeline logs-watchguard_firebox.log-0.1.0 is loaded                 │ PASS   │        162ns │
╰────────────────────┴─────────────┴───────────┴─────────────────────────────────────────────────────────────────────────────┴────────┴──────────────╯
--- Test results for package: watchguard_firebox - END   ---
Done
--- Test results for package: watchguard_firebox - START ---
╭────────────────────┬─────────────┬───────────┬────────────────────────────┬────────┬──────────────╮
│ PACKAGE            │ DATA STREAM │ TEST TYPE │ TEST NAME                  │ RESULT │ TIME ELAPSED │
├────────────────────┼─────────────┼───────────┼────────────────────────────┼────────┼──────────────┤
│ watchguard_firebox │ log         │ pipeline  │ test-alarm.log             │ PASS   │  62.374853ms │
│ watchguard_firebox │ log         │ pipeline  │ test-diagnostic.log        │ PASS   │ 284.010886ms │
│ watchguard_firebox │ log         │ pipeline  │ test-event.log             │ PASS   │  153.26417ms │
│ watchguard_firebox │ log         │ pipeline  │ test-traffic.log           │ PASS   │ 230.823811ms │
│ watchguard_firebox │ log         │ pipeline  │ (ingest pipeline warnings) │ PASS   │ 264.588415ms │
╰────────────────────┴─────────────┴───────────┴────────────────────────────┴────────┴──────────────╯
--- Test results for package: watchguard_firebox - END   ---
Done
--- Test results for package: watchguard_firebox - START ---
╭────────────────────┬─────────────┬───────────┬──────────────────────────┬────────┬──────────────╮
│ PACKAGE            │ DATA STREAM │ TEST TYPE │ TEST NAME                │ RESULT │ TIME ELAPSED │
├────────────────────┼─────────────┼───────────┼──────────────────────────┼────────┼──────────────┤
│ watchguard_firebox │ log         │ static    │ Verify sample_event.json │ PASS   │ 134.419749ms │
╰────────────────────┴─────────────┴───────────┴──────────────────────────┴────────┴──────────────╯
--- Test results for package: watchguard_firebox - END   ---
Done
--- Test results for package: watchguard_firebox - START ---
╭────────────────────┬─────────────┬───────────┬───────────┬────────┬──────────────╮
│ PACKAGE            │ DATA STREAM │ TEST TYPE │ TEST NAME │ RESULT │ TIME ELAPSED │
├────────────────────┼─────────────┼───────────┼───────────┼────────┼──────────────┤
│ watchguard_firebox │ log         │ system    │ udp       │ PASS   │ 39.83772453s │
╰────────────────────┴─────────────┴───────────┴───────────┴────────┴──────────────╯
--- Test results for package: watchguard_firebox - END   ---
Done
```

## Related issues

- Closes #1203 

## Screenshots

![Integration Page](https://github.com/elastic/integrations/assets/123942796/31c3f9e7-6412-4fb3-bbaa-601d984e833f)
![Overview Page](https://github.com/elastic/integrations/assets/123942796/4809622d-30ce-415f-8bd3-39d6fd89b10d)

2024-06-08 19:02 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12396)
* Commit: 99acff91fe5962161a21efccdf2e9c15bc274d5c

### Failed CI Steps
* [:white_check_mark: Check go sources](https://buildkite.com/elastic/integrations/builds/12396#018ff939-4657-42e0-b3ab-cf2f1f41f798)

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12396","number":12396,"commit":"99acff91fe5962161a21efccdf2e9c15bc274d5c"}],"number":12396}
buildkite-pr-comment-->

2024-06-08 19:20 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-06-08 19:21 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12397)
* Commit: 288760ef050daf8ea7d92db782b1df951b569508

### History
* :broken_heart: [Build #12396](https://buildkite.com/elastic/integrations/builds/12396) failed 99acff91fe5962161a21efccdf2e9c15bc274d5c

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12397","number":12397,"commit":"288760ef050daf8ea7d92db782b1df951b569508"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12396","number":12396,"commit":"99acff91fe5962161a21efccdf2e9c15bc274d5c"}],"number":12397}
buildkite-pr-comment-->

2024-06-11 06:00 UTC, elasticmachine commented
Pinging @elastic/security-service-integrations (Team:Security-Service Integrations)

2024-06-11 07:51 UTC, kcreddy commented on packages/watchguard_firebox/data_stream/log/_dev/test/pipeline/test-diagnostic.log-expected.json
> +            "message": "Cannot relearn system MAC address, possible loop or MAC spoofing, ip=192.168.111.10, mac=00:50:da:c7:90:5d, interface=5",
For `3000012E`, the doc describes the mac as observer mac address. We could copy this into `observer.mac`

2024-06-11 07:51 UTC, kcreddy commented on packages/watchguard_firebox/data_stream/log/_dev/test/pipeline/test-diagnostic.log-expected.json
> +            "message": "[eth0] Sending interface status event, logical=up link=up ip=10.0.0.1 mask=81.2.69.144",
Could add mask to `related.ip`

2024-06-11 07:51 UTC, kcreddy commented on packages/watchguard_firebox/data_stream/log/_dev/test/pipeline/test-diagnostic.log-expected.json
> +                ]
Can you also add [`dns.type:answer`](https://www.elastic.co/guide/en/ecs/8.11/ecs-dns.html#:~:text=DNS%20events%20should%20either%20represent%20a%20single%20DNS%20query%20prior%20to%20getting%20answers%20(dns.type%3Aquery)%20or%20they%20should%20represent%20a%20full%20exchange%20and%20contain%20the%20query%20details%20as%20well%20as%20all%20of%20the%20answers%20that%20were%20provided%20for%20this%20query%20(dns.type%3Aanswer).)

2024-06-11 07:51 UTC, kcreddy commented on packages/watchguard_firebox/data_stream/log/_dev/test/pipeline/test-diagnostic.log-expected.json
> +            "message": "Received reply: HTTP/1.1 200 OK Date: Tue, 27 Nov 2012 17:14:57 GMT Server: Apache Content-Type: text/plain Connection: close good 192.168.53.88",
Can you parse them into http.* fields?

2024-06-11 07:51 UTC, kcreddy commented on packages/watchguard_firebox/data_stream/log/_dev/test/pipeline/test-diagnostic.log-expected.json
> +            "message": "Received reply: HTTP/1.1 200 OK Date: Tue, 27 Nov 2012 17:14:57 GMT Server: Apache Content-Type: text/plain Connection: close good 192.168.53.88",
Add IP address to `related.ip`

2024-06-11 07:51 UTC, kcreddy commented on packages/watchguard_firebox/data_stream/log/_dev/test/pipeline/test-diagnostic.log-expected.json
> +                "name": "\"FTP-00\""
Can you remove escape characters

2024-06-11 08:45 UTC, jamiehynds commented on .github/CODEOWNERS
> +/packages/watchguard_firebox @elastic/security-service-integrations
This integration will actually be owned by the @elastic/sec-deployment-and-devices team - can we ensure that's reflected in the codeowners please.

2024-06-11 13:53 UTC, taylor-swanson requested changes
For performance and maintainability reasons, the large groks should be split out into individual processors for each log type.

- Log types that extract back out to the same field need no additional processing (`3000-0006` from `pipeline_diagnostic`, for example)
- Use `dissect` first. It is faster than grok and in most cases can handle the patterns I see without issue
- If `dissect` is not flexible enough, then `grok` can be used.

2024-06-11 13:53 UTC, taylor-swanson commented on packages/watchguard_firebox/data_stream/log/elasticsearch/ingest_pipeline/pipeline_alarm.yml
> +  - grok:
These groks are unfortunately too complex. From my experience in the past (both in my own testing and issues filed by customers), groks with a large number of patterns tend to perform poorly.

Indeed, I ran the pipeline tests and these groks are going to be an issue.

```
--- Benchmark results for package: watchguard_firebox - START ---
╭─────────────────────────╮
│ parameters              │
├──────────────────┬──────┤
│ source_doc_count │  626 │
│ doc_count        │ 1000 │
╰──────────────────┴──────╯
╭───────────────────────────╮
│ pipeline_performance      │
├─────────────────┬─────────┤
│ processing_time │   0.19s │
│ eps             │ 5291.01 │
╰─────────────────┴─────────╯
╭────────────────────────────────────────────╮
│ procs_by_total_time                        │
├───────────────────────────────────┬────────┤
│ grok @ pipeline_diagnostic.yml:76 │ 22.75% │
│ grok @ default.yml:21             │  2.12% │
│ date @ default.yml:69             │  2.12% │
│ grok @ pipeline_traffic.yml:4     │  1.06% │
│ grok @ pipeline_event.yml:82      │  1.06% │
│ kv @ pipeline_traffic.yml:13      │  0.53% │
│ grok @ pipeline_event.yml:30      │  0.53% │
│ script @ default.yml:4695         │  0.53% │
│ script @ default.yml:113          │  0.53% │
│ grok @ default.yml:102            │  0.53% │
╰───────────────────────────────────┴────────╯
╭────────────────────────────────────────────────╮
│ procs_by_avg_time_per_doc                      │
├────────────────────────────────────┬───────────┤
│ grok @ pipeline_diagnostic.yml:76  │ 217.171µs │
│ grok @ pipeline_event.yml:82       │  15.037µs │
│ grok @ pipeline_event.yml:30       │  11.111µs │
│ grok @ pipeline_traffic.yml:4      │   9.345µs │
│ remove @ pipeline_traffic.yml:1111 │   4.672µs │
│ kv @ pipeline_traffic.yml:13       │   4.672µs │
│ grok @ default.yml:21              │       4µs │
│ date @ default.yml:69              │       4µs │
│ remove @ pipeline_event.yml:494    │   2.604µs │
│ script @ default.yml:4695          │       1µs │
╰────────────────────────────────────┴───────────╯
```

Looking at most of these patterns, I think many of them can be turned into dissect processors. Only in cases where there are optional fields, multiple patterns for the same log type, or some other complicated situation, do I think a grok should be used. Dissect also has the benefit of being faster than grok given the same pattern.

Additionally, we should not being doing something like this:

```
  - grok:
      field: watchguard_firebox.log.body
      patterns:
      ...
        - '^%{GREEDYDATA:watchguard_firebox.log.body}$'
```

This is effectively a no-op, but it still carries a cost. Since the catch-all pattern is at the end of the list, all of the other patterns have to fail first before it reaches this one. Only to set the field to the same value. Any message that uses this pattern can be skipped entirely, we don't need a dissect or grok.

2024-06-26 13:00 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12925)
* Commit: 813ea3a92fcd66922996e20b16b4b75f64192973

### Failed CI Steps
* [:white_check_mark: Check go sources](https://buildkite.com/elastic/integrations/builds/12925#019054a1-5eea-4282-b804-2e43e88a99da)

### History
* :green_heart: [Build #12397](https://buildkite.com/elastic/integrations/builds/12397) succeeded 288760ef050daf8ea7d92db782b1df951b569508
* :broken_heart: [Build #12396](https://buildkite.com/elastic/integrations/builds/12396) failed 99acff91fe5962161a21efccdf2e9c15bc274d5c

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12925","number":12925,"commit":"813ea3a92fcd66922996e20b16b4b75f64192973"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12397","number":12397,"commit":"288760ef050daf8ea7d92db782b1df951b569508"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12396","number":12396,"commit":"99acff91fe5962161a21efccdf2e9c15bc274d5c"}],"number":12925}
buildkite-pr-comment-->

2024-06-26 13:22 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12927)
* Commit: f48fba74987a2faab914e1ddcde7cf789b981136

### History
* :broken_heart: [Build #12925](https://buildkite.com/elastic/integrations/builds/12925) failed 813ea3a92fcd66922996e20b16b4b75f64192973
* :green_heart: [Build #12397](https://buildkite.com/elastic/integrations/builds/12397) succeeded 288760ef050daf8ea7d92db782b1df951b569508
* :broken_heart: [Build #12396](https://buildkite.com/elastic/integrations/builds/12396) failed 99acff91fe5962161a21efccdf2e9c15bc274d5c

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12927","number":12927,"commit":"f48fba74987a2faab914e1ddcde7cf789b981136"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12925","number":12925,"commit":"813ea3a92fcd66922996e20b16b4b75f64192973"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12397","number":12397,"commit":"288760ef050daf8ea7d92db782b1df951b569508"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12396","number":12396,"commit":"99acff91fe5962161a21efccdf2e9c15bc274d5c"}],"number":12927}
buildkite-pr-comment-->

2024-06-26 17:47 UTC, taylor-swanson reviewed
I'm still reviewing, but wanted to get some comments out in the mean time.

Also, please add the file `kibana/tags.yml` with the following contents:

```yaml
- text: Security Solution
  asset_types:
    - dashboard
    - search
```

For example: https://github.com/elastic/integrations/blob/main/packages/cisco_asa/kibana/tags.yml

2024-06-26 17:47 UTC, taylor-swanson commented on packages/watchguard_firebox/data_stream/log/elasticsearch/ingest_pipeline/default.yml
> +        hm.forEach((k, v) -> {
```suggestion
        params.get(ctx.watchguard_firebox.log.msg_id).forEach((k, v) -> {
```

This can be simplified down, no need to make a copy of the map in params.

2024-06-27 05:54 UTC, brijesh-elastic commented on packages/watchguard_firebox/manifest.yml
> +    size: 600x600
We can split into multiple images.

2024-06-27 08:55 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12947)
* Commit: fd21f31635032c0cd74b4907c3200fc86b90d928

### History
* :green_heart: [Build #12927](https://buildkite.com/elastic/integrations/builds/12927) succeeded f48fba74987a2faab914e1ddcde7cf789b981136
* :broken_heart: [Build #12925](https://buildkite.com/elastic/integrations/builds/12925) failed 813ea3a92fcd66922996e20b16b4b75f64192973
* :green_heart: [Build #12397](https://buildkite.com/elastic/integrations/builds/12397) succeeded 288760ef050daf8ea7d92db782b1df951b569508
* :broken_heart: [Build #12396](https://buildkite.com/elastic/integrations/builds/12396) failed 99acff91fe5962161a21efccdf2e9c15bc274d5c

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12947","number":12947,"commit":"fd21f31635032c0cd74b4907c3200fc86b90d928"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12927","number":12927,"commit":"f48fba74987a2faab914e1ddcde7cf789b981136"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12925","number":12925,"commit":"813ea3a92fcd66922996e20b16b4b75f64192973"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12397","number":12397,"commit":"288760ef050daf8ea7d92db782b1df951b569508"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12396","number":12396,"commit":"99acff91fe5962161a21efccdf2e9c15bc274d5c"}],"number":12947}
buildkite-pr-comment-->

2024-07-01 12:40 UTC, kcreddy approved these changes
LGTM (for my comments) 👍🏼

2024-07-01 14:34 UTC, taylor-swanson reviewed
Just the message/event.original comment, otherwise everything else LGTM

2024-07-01 14:34 UTC, taylor-swanson commented on packages/watchguard_firebox/data_stream/log/elasticsearch/ingest_pipeline/default.yml
> +      description: Renames the original `message` field to `event.original` to store a copy of the original message. The `event.original` field is not touched if the document already has one; it may
This is still outstanding.

2024-07-01 16:34 UTC, taylor-swanson approved these changes
LGTM

2024-07-01 16:52 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13062)
* Commit: ca515f9ccce8db2632ceaf8e4f3f49182d9aaf4b

### History
* :green_heart: [Build #12947](https://buildkite.com/elastic/integrations/builds/12947) succeeded fd21f31635032c0cd74b4907c3200fc86b90d928
* :green_heart: [Build #12927](https://buildkite.com/elastic/integrations/builds/12927) succeeded f48fba74987a2faab914e1ddcde7cf789b981136
* :broken_heart: [Build #12925](https://buildkite.com/elastic/integrations/builds/12925) failed 813ea3a92fcd66922996e20b16b4b75f64192973
* :green_heart: [Build #12397](https://buildkite.com/elastic/integrations/builds/12397) succeeded 288760ef050daf8ea7d92db782b1df951b569508
* :broken_heart: [Build #12396](https://buildkite.com/elastic/integrations/builds/12396) failed 99acff91fe5962161a21efccdf2e9c15bc274d5c

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13062","number":13062,"commit":"ca515f9ccce8db2632ceaf8e4f3f49182d9aaf4b"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12947","number":12947,"commit":"fd21f31635032c0cd74b4907c3200fc86b90d928"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12927","number":12927,"commit":"f48fba74987a2faab914e1ddcde7cf789b981136"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12925","number":12925,"commit":"813ea3a92fcd66922996e20b16b4b75f64192973"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12397","number":12397,"commit":"288760ef050daf8ea7d92db782b1df951b569508"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12396","number":12396,"commit":"99acff91fe5962161a21efccdf2e9c15bc274d5c"}],"number":13062}
buildkite-pr-comment-->

2024-07-10 10:43 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13478)
* Commit: 4d6f52ea25161d19dcb9c194127fb50d5a972ef1

### History
* :green_heart: [Build #13062](https://buildkite.com/elastic/integrations/builds/13062) succeeded ca515f9ccce8db2632ceaf8e4f3f49182d9aaf4b
* :green_heart: [Build #12947](https://buildkite.com/elastic/integrations/builds/12947) succeeded fd21f31635032c0cd74b4907c3200fc86b90d928
* :green_heart: [Build #12927](https://buildkite.com/elastic/integrations/builds/12927) succeeded f48fba74987a2faab914e1ddcde7cf789b981136
* :broken_heart: [Build #12925](https://buildkite.com/elastic/integrations/builds/12925) failed 813ea3a92fcd66922996e20b16b4b75f64192973
* :green_heart: [Build #12397](https://buildkite.com/elastic/integrations/builds/12397) succeeded 288760ef050daf8ea7d92db782b1df951b569508
* :broken_heart: [Build #12396](https://buildkite.com/elastic/integrations/builds/12396) failed 99acff91fe5962161a21efccdf2e9c15bc274d5c

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13478","number":13478,"commit":"4d6f52ea25161d19dcb9c194127fb50d5a972ef1"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13062","number":13062,"commit":"ca515f9ccce8db2632ceaf8e4f3f49182d9aaf4b"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12947","number":12947,"commit":"fd21f31635032c0cd74b4907c3200fc86b90d928"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12927","number":12927,"commit":"f48fba74987a2faab914e1ddcde7cf789b981136"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12925","number":12925,"commit":"813ea3a92fcd66922996e20b16b4b75f64192973"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12397","number":12397,"commit":"288760ef050daf8ea7d92db782b1df951b569508"}],"number":13478}
buildkite-pr-comment-->

2024-07-11 15:08 UTC, merged

2024-07-11 15:30 UTC, elasticmachine commented
Package watchguard_firebox - 0.1.0 containing this change is available at https://epr.elastic.co/search?package=watchguard_firebox