Add AWSHealth Integration
elastic/integrations pull request #10119
Opened 2024-06-11 06:50 UTC by agithomas

## Type of change

- Enhancement

## Proposed commit message

Create AWS Health Integration. 
AWS health metrics provide insights into the health of your AWS environment by monitoring various aspects such as open issues, scheduled maintenance events, etc.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## How to test this PR locally

- elastic-package build
- elastic-package stack up -v -d --services package-registry
- Configure the AWS Health Integration.
- Verify the dashboard data
- Validate using Discover interface

## Related issues

- Relates  https://github.com/elastic/integrations/issues/8907

## Screenshots

<img width="1727" alt="Screenshot 2024-06-10 at 8 20 53 AM" src="https://github.com/elastic/integrations/assets/101976829/1e3e4f19-0e3b-4768-8272-3496bf7d61a5">

2024-06-11 07:02 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12425)
* Commit: 77623501996c82f8cc8be2df018b5e24255da548

### Failed CI Steps
* [Check integrations aws](https://buildkite.com/elastic/integrations/builds/12425#01900612-f605-4c18-9be2-93218a1437de)

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12425","number":12425,"commit":"77623501996c82f8cc8be2df018b5e24255da548"}],"number":12425}
buildkite-pr-comment-->

2024-07-05 15:41 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13330)
* Commit: 7c544fdc17f475161ac959816db91b5853142f2a

### Failed CI Steps
* [Check integrations aws](https://buildkite.com/elastic/integrations/builds/13330#01908342-c957-427d-a02a-30ea4cac306f)

### History
* :broken_heart: [Build #12438](https://buildkite.com/elastic/integrations/builds/12438) failed 1417dd1e3e72e1403e1215fc4fa710997d6a0f8e
* :broken_heart: [Build #12425](https://buildkite.com/elastic/integrations/builds/12425) failed 77623501996c82f8cc8be2df018b5e24255da548

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13330","number":13330,"commit":"7c544fdc17f475161ac959816db91b5853142f2a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12438","number":12438,"commit":"1417dd1e3e72e1403e1215fc4fa710997d6a0f8e"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12425","number":12425,"commit":"77623501996c82f8cc8be2df018b5e24255da548"}],"number":13330}
buildkite-pr-comment-->

2024-07-06 02:50 UTC, agithomas commented
The PR is blocked because of the issue : https://github.com/elastic/integrations/issues/10400

2024-07-07 08:55 UTC, agithomas commented
/test

2024-07-07 10:26 UTC, elasticmachine commented
### :rocket: Benchmarks report


#### Package `aws` :&#43;1:(7) :green_heart:(1) :broken_heart:(9)
<details>
<summary>Expand to view</summary>

Data stream | Previous EPS | New EPS | Diff (%) | Result
----------- | ------------ | ------- | -------- | ------
`inspector` | 1923.08 | 1545.6 | -377.48 (-19.63%) | :broken_heart:
`route53_public_logs` | 17241.38 | 14492.75 | -2748.63 (-15.94%) | :broken_heart:
`waf` | 6493.51 | 4761.9 | -1731.61 (-26.67%) | :broken_heart:
`apigateway_logs` | 12195.12 | 9708.74 | -2486.38 (-20.39%) | :broken_heart:
`cloudfront_logs` | 3215.43 | 2392.34 | -823.09 (-25.6%) | :broken_heart:
`cloudwatch_logs` | 500000 | 250000 | -250000 (-50%) | :broken_heart:
`ec2_logs` | 33333.33 | 24390.24 | -8943.09 (-26.83%) | :broken_heart:
`elb_logs` | 7142.86 | 3731.34 | -3411.52 (-47.76%) | :broken_heart:
`firewall_logs` | 3134.8 | 2659.57 | -475.23 (-15.16%) | :broken_heart:
</details>


To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-07-07 10:28 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13341)
* Commit: 7c544fdc17f475161ac959816db91b5853142f2a

### History
* :broken_heart: [Build #13330](https://buildkite.com/elastic/integrations/builds/13330) failed 7c544fdc17f475161ac959816db91b5853142f2a
* :broken_heart: [Build #12438](https://buildkite.com/elastic/integrations/builds/12438) failed 1417dd1e3e72e1403e1215fc4fa710997d6a0f8e
* :broken_heart: [Build #12425](https://buildkite.com/elastic/integrations/builds/12425) failed 77623501996c82f8cc8be2df018b5e24255da548

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13341","number":13341,"commit":"7c544fdc17f475161ac959816db91b5853142f2a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13330","number":13330,"commit":"7c544fdc17f475161ac959816db91b5853142f2a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12438","number":12438,"commit":"1417dd1e3e72e1403e1215fc4fa710997d6a0f8e"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12425","number":12425,"commit":"77623501996c82f8cc8be2df018b5e24255da548"}],"number":13341}
buildkite-pr-comment-->

2024-07-08 03:13 UTC, agithomas commented on packages/aws/data_stream/awshealth/elasticsearch/ingest_pipeline/default.yml
> +    field: aws.awshealth.end_time
This is a very good suggestion. Modified as suggested.

2024-07-08 03:49 UTC, ishleenk17 commented on packages/aws/data_stream/awshealth/fields/ecs.yml
> +  name: cloud.region
Please follow the ecs@mappings template.

2024-07-08 03:49 UTC, ishleenk17 commented on packages/aws/data_stream/awshealth/fields/fields.yml
> +        - name: affected_entities_others
Can we have a more descriptive name:
Maybe: 
```suggestion
        - name: affected_entities_unverified
```

2024-07-08 03:49 UTC, ishleenk17 commented on packages/aws/data_stream/awshealth/fields/fields.yml
> +
We can group the affected_entities_pending, resolved, others here. WDYT ?

2024-07-08 03:49 UTC, ishleenk17 commented on packages/aws/data_stream/awshealth/agent/stream/stream.yml.hbs
> +{{/if}}
Can we add processors as well?
As that is a sort-after UI option to give flexibility to the users.

2024-07-08 04:46 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13346)
* Commit: 9551350dfa38bd6677155e27ca12ae8a1d2dff21

### History
* :green_heart: [Build #13341](https://buildkite.com/elastic/integrations/builds/13341) succeeded 7c544fdc17f475161ac959816db91b5853142f2a
* :broken_heart: [Build #13330](https://buildkite.com/elastic/integrations/builds/13330) failed 7c544fdc17f475161ac959816db91b5853142f2a
* :broken_heart: [Build #12438](https://buildkite.com/elastic/integrations/builds/12438) failed 1417dd1e3e72e1403e1215fc4fa710997d6a0f8e
* :broken_heart: [Build #12425](https://buildkite.com/elastic/integrations/builds/12425) failed 77623501996c82f8cc8be2df018b5e24255da548

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13346","number":13346,"commit":"9551350dfa38bd6677155e27ca12ae8a1d2dff21"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13341","number":13341,"commit":"7c544fdc17f475161ac959816db91b5853142f2a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13330","number":13330,"commit":"7c544fdc17f475161ac959816db91b5853142f2a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12438","number":12438,"commit":"1417dd1e3e72e1403e1215fc4fa710997d6a0f8e"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12425","number":12425,"commit":"77623501996c82f8cc8be2df018b5e24255da548"}],"number":13346}
buildkite-pr-comment-->

2024-07-08 04:54 UTC, muthu-mps commented on packages/aws/data_stream/awshealth/sample_event.json
> +                    "status_code": ""
Are these expected values? If we get empty values we could drop them.

2024-07-08 04:54 UTC, muthu-mps commented on packages/aws/data_stream/awshealth/fields/fields.yml
> +                The most recent status of affected entities. Possible values are open, closed, and upcoming.
The possible value for `status_code` inside the `affected_entities` are different. Please check the API [reference](https://docs.aws.amazon.com/health/latest/APIReference/API_AffectedEntity.html#:~:text=by%20the%20event.-,The,-possible%20values%20are).

2024-07-08 04:54 UTC, muthu-mps commented on packages/aws/data_stream/awshealth/fields/fields.yml
> +            - name: affected_entities.last_updated_time
```suggestion
            - name: last_updated_time
```

2024-07-08 04:56 UTC, muthu-mps commented
The metrics include the `status_code` which is more useful for monitoring. Can we include a visualisation which breaks down metrics by `status_code`.

2024-07-08 05:14 UTC, muthu-mps commented on packages/aws/data_stream/awshealth/fields/fields.yml
> +          description: "This parameter specifies whether the Health event is a public Amazon Web Service event or an account-specific event. Allowed values are PUBLIC, ACCOUNT_SPECIFIC, or NONE. \n"
```suggestion
          description: This parameter specifies whether the Health event is a public Amazon Web Service event or an account-specific event. Allowed values are PUBLIC, ACCOUNT_SPECIFIC, or NONE.
```
Also please keep the space between the fields consistent.

2024-07-08 06:08 UTC, shmsr requested changes

2024-07-08 06:08 UTC, shmsr commented on packages/aws/data_stream/awshealth/manifest.yml
> +        description: When include_linked_accounts is set to true, CloudWatch metrics will be collected from both linked accounts and the monitoring account. Default is true.
```suggestion
        description: When "Include Linked Accounts" is set to true, CloudWatch metrics will be collected from both linked accounts and the monitoring account. The default is true.
```

2024-07-08 06:08 UTC, shmsr commented on packages/aws/data_stream/awshealth/fields/fields.yml
> +            The event type category code. Possible values are issue, accountNotification, or scheduledChange.
Is this an exact string match (even the case)?

- issue
- accountNotification
- scheduledChange

If yes, make sure it is indicated here properly.

2024-07-08 06:08 UTC, shmsr commented on packages/aws/data_stream/awshealth/fields/fields.yml
> +            The most recent status of the event. Possible values are open, closed, and upcoming.
```suggestion
            The most recent status of the event. Possible values are "open", "closed", and "upcoming".
```

2024-07-08 06:08 UTC, shmsr commented on packages/aws/data_stream/awshealth/fields/fields.yml
> +            The event type category code. Possible values are issue, accountNotification, or scheduledChange.
```suggestion
            The event type category code. Possible values are "issue", "accountNotification", or "scheduledChange".
```

2024-07-08 06:08 UTC, shmsr commented on packages/aws/data_stream/awshealth/fields/fields.yml
> +                The IDs of the affected entities.
IDs or ID?

2024-07-08 06:08 UTC, shmsr commented on packages/aws/data_stream/awshealth/fields/package-fields.yml
> +        Tag key value pairs from aws resources.
```suggestion
        Tag key-value pairs from AWS resources.
```

2024-07-08 08:11 UTC, zmoog reviewed
@agithomas, should we also set up the `.github/CODEOWNERS` file for this integration?

2024-07-08 09:26 UTC, agithomas commented on packages/aws/data_stream/awshealth/fields/package-fields.yml
> +        Tag key value pairs from aws resources.
@shmsr , across the AWS datastreams, the same description is used. Can we keep the same description to retain consistency?

2024-07-08 09:28 UTC, shmsr commented on packages/aws/data_stream/awshealth/fields/package-fields.yml
> +        Tag key value pairs from aws resources.
Yeah, then it is fine. Else, it would be a lot of work to maintain consistency. Marking it resolved.

2024-07-08 10:35 UTC, agithomas commented on packages/aws/data_stream/awshealth/fields/fields.yml
> +        - name: affected_entities_others
Kindly look at the screenshot, below. There are three states you can see in the AWS console - Pending, Resolved, Unknown. 


<img width="575" alt="image" src="https://github.com/elastic/integrations/assets/101976829/9e36313d-cfba-46f4-b6f7-bd270fef23c7">

Instead of `Unknown`, `Others` is considered as part of this PR to accommodate changes in AWS around Enum value `EntityStatusCode`. Kindly refer to [this](https://github.com/elastic/beats/pull/38370#discussion_r1565494482) comment for more details. 

Also, using the same name helps to be aligned with the metricbeat field names.

2024-07-08 10:46 UTC, agithomas commented on packages/aws/data_stream/awshealth/fields/fields.yml
> +            The event type category code. Possible values are issue, accountNotification, or scheduledChange.
Yes, please refer here. 

https://docs.aws.amazon.com/health/latest/APIReference/API_EventType.html

I have just added `investigation` to the list.

2024-07-08 12:08 UTC, agithomas commented on packages/aws/data_stream/awshealth/fields/fields.yml
> +                The most recent status of affected entities. Possible values are open, closed, and upcoming.
Good catch. 

I see that AWS is constantly expanding the allowed values with SDK upgrades.

From 
 `IMPAIRED`, `UNIMPAIRED`, `UNKNOWN`

To
`IMPAIRED`, `UNIMPAIRED`, `UNKNOWN`, `PENDING`, `RESOLVED`.

2024-07-09 01:43 UTC, agithomas commented on packages/aws/data_stream/awshealth/fields/fields.yml
> +            - name: affected_entities.last_updated_time
There exist two fields 
- affected_entities.last_updated_time (corresponds to the last updated time of the entity)
- last_updated_time (corresponds to the last updated time of the event)

2024-07-09 01:50 UTC, agithomas commented on packages/aws/data_stream/awshealth/manifest.yml
> +        description: When include_linked_accounts is set to true, CloudWatch metrics will be collected from both linked accounts and the monitoring account. Default is true.
I agree. This is written in this manner to retain consistency with other AWS packages. 

Created https://github.com/elastic/integrations/issues/10420 for tracking

2024-07-09 02:02 UTC, agithomas commented on packages/aws/data_stream/awshealth/fields/fields.yml
> +            - name: affected_entities.last_updated_time
I understood now what you meant. I would address this.

2024-07-09 02:15 UTC, agithomas commented
> The metrics include the `status_code` which is more useful for monitoring. Can we include a visualisation which breaks down metrics by `status_code`.

This already exists. Snippet from the screenshot. The metrics are broken down into Status & Regionwise. `Status + Region` would be more usable and hence this approach is followed

![image](https://github.com/elastic/integrations/assets/101976829/aefa9ca8-dc30-48f8-9e51-c4be2f8ae899)

2024-07-09 02:42 UTC, agithomas commented on packages/aws/data_stream/awshealth/fields/fields.yml
> +
The field mapping looks as below, presently. The affected_entities is like an array (multiple entities for a given event).

The summarized count is kept at the event level. This helps in easier understanding. 

Secondly, the above document schema is maintained in the metricbeat as well. So, it would be ideal to continue the same schema, i believe.
 



![image](https://github.com/elastic/integrations/assets/101976829/89917588-4706-4639-ac4d-c4524d160dc4)

2024-07-09 03:58 UTC, agithomas commented
> @agithomas, should we also set up the `.github/CODEOWNERS` file for this integration?

Thanks for pointing it out. Added the entry.

2024-07-09 03:59 UTC, agithomas commented on packages/aws/data_stream/awshealth/fields/fields.yml
> +                The IDs of the affected entities.
Addressed the suggestion.

2024-07-09 03:59 UTC, agithomas commented on packages/aws/data_stream/awshealth/fields/fields.yml
> +            The event type category code. Possible values are issue, accountNotification, or scheduledChange.
Addressed the suggestion.

2024-07-09 03:59 UTC, agithomas commented on packages/aws/data_stream/awshealth/fields/fields.yml
> +            The most recent status of the event. Possible values are open, closed, and upcoming.
Addressed the suggestion using backticks.

2024-07-09 04:01 UTC, agithomas commented on packages/aws/data_stream/awshealth/agent/stream/stream.yml.hbs
> +{{/if}}
Added the processor.

2024-07-09 04:02 UTC, agithomas commented on packages/aws/data_stream/awshealth/sample_event.json
> +                    "status_code": ""
This was already addressed, but the sample_event file did not reflect this. I have updated the sample_event.json

2024-07-09 04:02 UTC, agithomas commented on packages/aws/data_stream/awshealth/fields/fields.yml
> +          description: "This parameter specifies whether the Health event is a public Amazon Web Service event or an account-specific event. Allowed values are PUBLIC, ACCOUNT_SPECIFIC, or NONE. \n"
Addressed.

2024-07-09 04:04 UTC, agithomas commented on packages/aws/data_stream/awshealth/fields/fields.yml
> +            The event type category code. Possible values are issue, accountNotification, or scheduledChange.
Yes, the values are correct. I have updated the readme by enclosing these keywords between backticks.

2024-07-09 04:05 UTC, agithomas commented on packages/aws/data_stream/awshealth/fields/fields.yml
> +            - name: affected_entities.last_updated_time
Reworked on field mapping in `fields.yml` to correct the mistake.

2024-07-09 04:09 UTC, agithomas commented on packages/aws/data_stream/awshealth/fields/ecs.yml
> +  name: cloud.region
Removed non-dimension fields from `ecs.yml` file

2024-07-09 04:25 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13388)
* Commit: 56850316feb6847615b6de7cea1a28b89dbf2211

### History
* :green_heart: [Build #13346](https://buildkite.com/elastic/integrations/builds/13346) succeeded 9551350dfa38bd6677155e27ca12ae8a1d2dff21
* :green_heart: [Build #13341](https://buildkite.com/elastic/integrations/builds/13341) succeeded 7c544fdc17f475161ac959816db91b5853142f2a
* :broken_heart: [Build #13330](https://buildkite.com/elastic/integrations/builds/13330) failed 7c544fdc17f475161ac959816db91b5853142f2a
* :broken_heart: [Build #12438](https://buildkite.com/elastic/integrations/builds/12438) failed 1417dd1e3e72e1403e1215fc4fa710997d6a0f8e
* :broken_heart: [Build #12425](https://buildkite.com/elastic/integrations/builds/12425) failed 77623501996c82f8cc8be2df018b5e24255da548

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13388","number":13388,"commit":"56850316feb6847615b6de7cea1a28b89dbf2211"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13346","number":13346,"commit":"9551350dfa38bd6677155e27ca12ae8a1d2dff21"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13341","number":13341,"commit":"7c544fdc17f475161ac959816db91b5853142f2a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13330","number":13330,"commit":"7c544fdc17f475161ac959816db91b5853142f2a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12438","number":12438,"commit":"1417dd1e3e72e1403e1215fc4fa710997d6a0f8e"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12425","number":12425,"commit":"77623501996c82f8cc8be2df018b5e24255da548"}],"number":13388}
buildkite-pr-comment-->

2024-07-09 05:24 UTC, muthu-mps commented on packages/aws/_dev/build/docs/awshealth.md
> +Use this integration if you only need to collect billing data from AWS.
This line seems to be left over from the template used. Can we remove as it is for billing integration?

2024-07-09 06:51 UTC, agithomas commented on packages/aws/_dev/build/docs/awshealth.md
> +Use this integration if you only need to collect billing data from AWS.
This line is removed now. Thanks for highlighting.

2024-07-09 08:21 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13396)
* Commit: 5172fb5c58af9a39287d1a478600c64ed0ae8f1f

### History
* :green_heart: [Build #13388](https://buildkite.com/elastic/integrations/builds/13388) succeeded 56850316feb6847615b6de7cea1a28b89dbf2211
* :green_heart: [Build #13346](https://buildkite.com/elastic/integrations/builds/13346) succeeded 9551350dfa38bd6677155e27ca12ae8a1d2dff21
* :green_heart: [Build #13341](https://buildkite.com/elastic/integrations/builds/13341) succeeded 7c544fdc17f475161ac959816db91b5853142f2a
* :broken_heart: [Build #13330](https://buildkite.com/elastic/integrations/builds/13330) failed 7c544fdc17f475161ac959816db91b5853142f2a
* :broken_heart: [Build #12438](https://buildkite.com/elastic/integrations/builds/12438) failed 1417dd1e3e72e1403e1215fc4fa710997d6a0f8e
* :broken_heart: [Build #12425](https://buildkite.com/elastic/integrations/builds/12425) failed 77623501996c82f8cc8be2df018b5e24255da548

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13396","number":13396,"commit":"5172fb5c58af9a39287d1a478600c64ed0ae8f1f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13388","number":13388,"commit":"56850316feb6847615b6de7cea1a28b89dbf2211"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13346","number":13346,"commit":"9551350dfa38bd6677155e27ca12ae8a1d2dff21"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13341","number":13341,"commit":"7c544fdc17f475161ac959816db91b5853142f2a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13330","number":13330,"commit":"7c544fdc17f475161ac959816db91b5853142f2a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12438","number":12438,"commit":"1417dd1e3e72e1403e1215fc4fa710997d6a0f8e"}],"number":13396}
buildkite-pr-comment-->

2024-07-09 08:53 UTC, muthu-mps commented on packages/aws/docs/awshealth.md
> +An example event for `awshealth` looks as following:
Just wondering why does the text appears twice in the README file which is not present in the `_dev/build/docs README`. Please check whether you need to run the build command to eliminate the redundant text here.

2024-07-09 10:17 UTC, agithomas commented on packages/aws/docs/awshealth.md
> +An example event for `awshealth` looks as following:
Addressed the problem.

2024-07-09 10:44 UTC, shmsr requested changes
Also, see this patch:

Makes small adjustments to make all descriptions consistent.

```diff
diff --git a/packages/aws/data_stream/awshealth/fields/fields.yml b/packages/aws/data_stream/awshealth/fields/fields.yml
index 14795aa42..260f40da1 100644
--- a/packages/aws/data_stream/awshealth/fields/fields.yml
+++ b/packages/aws/data_stream/awshealth/fields/fields.yml
@@ -4,7 +4,7 @@
     - name: awshealth
       type: group
       description: >
-        AWS Health metrics
+        AWS Health metrics.
       fields:
         - name: affected_entities_others
           type: float
@@ -33,12 +33,12 @@
           type: keyword
           dimension: true
           description: >
-            The unique identifier for the event. The event ARN has the format `arn:aws:health:<event-region>::event/<SERVICE>/<EVENT_TYPE_CODE>/<EVENT_TYPE_PLUS_ID>`. For example, `arn:aws:health:us-east-1::event/EC2/EC2_INSTANCE_RETIREMENT_SCHEDULED/EC2_INSTANCE_RETIREMENT_SCHEDULED_ABC123-DEF456`
+            The unique identifier for the event. The event ARN has the format `arn:aws:health:<event-region>::event/<SERVICE>/<EVENT_TYPE_CODE>/<EVENT_TYPE_PLUS_ID>`. For example, `arn:aws:health:us-east-1::event/EC2/EC2_INSTANCE_RETIREMENT_SCHEDULED/EC2_INSTANCE_RETIREMENT_SCHEDULED_ABC123-DEF456`.
 
         - name: event_scope_code
           type: keyword
           description: >
-            This parameter specifies whether the Health event is a public Amazon Web Service event or an account-specific event. Allowed values are `PUBLIC`, `ACCOUNT_SPECIFIC`, or `NONE`."
+            The parameter that specifies whether the Health event is a public Amazon Web Service event or an account-specific event. Allowed values are `PUBLIC`, `ACCOUNT_SPECIFIC`, or `NONE`.
 
         - name: event_type_category
           type: keyword
@@ -85,7 +85,7 @@
           object_type: keyword
           object_type_mapping_type: "*"
           description: >
-            Details of the affected entities related to the event.
+            The details of the affected entities related to the event.
 
         - name: affected_entities.aws_account_id
           type: keyword
@@ -105,7 +105,7 @@
         - name: affected_entities.last_updated_time
           type: date
           description: >
-            The last updated time of entity.
+            The last updated time of the entity.
 
         - name: affected_entities.status_code
           type: keyword
```

I have a couple of suggestions for package-fields.yml but from our earlier discussion, you want to keep it as it in data_streams for consistency; so skipping those nitpicks.

2024-07-09 10:44 UTC, shmsr commented on packages/aws/data_stream/awshealth/manifest.yml
> +      - name: tags_filter
Add description for `tags_filter`, `region`, `period` and `data_granularity`.

2024-07-09 11:45 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13413)
* Commit: 21b93e6c241cabcfdf206e8f7d1c8358ce54ea01

### History
* :green_heart: [Build #13396](https://buildkite.com/elastic/integrations/builds/13396) succeeded 5172fb5c58af9a39287d1a478600c64ed0ae8f1f
* :green_heart: [Build #13388](https://buildkite.com/elastic/integrations/builds/13388) succeeded 56850316feb6847615b6de7cea1a28b89dbf2211
* :green_heart: [Build #13346](https://buildkite.com/elastic/integrations/builds/13346) succeeded 9551350dfa38bd6677155e27ca12ae8a1d2dff21
* :green_heart: [Build #13341](https://buildkite.com/elastic/integrations/builds/13341) succeeded 7c544fdc17f475161ac959816db91b5853142f2a
* :broken_heart: [Build #13330](https://buildkite.com/elastic/integrations/builds/13330) failed 7c544fdc17f475161ac959816db91b5853142f2a
* :broken_heart: [Build #12438](https://buildkite.com/elastic/integrations/builds/12438) failed 1417dd1e3e72e1403e1215fc4fa710997d6a0f8e

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13413","number":13413,"commit":"21b93e6c241cabcfdf206e8f7d1c8358ce54ea01"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13396","number":13396,"commit":"5172fb5c58af9a39287d1a478600c64ed0ae8f1f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13388","number":13388,"commit":"56850316feb6847615b6de7cea1a28b89dbf2211"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13346","number":13346,"commit":"9551350dfa38bd6677155e27ca12ae8a1d2dff21"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13341","number":13341,"commit":"7c544fdc17f475161ac959816db91b5853142f2a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13330","number":13330,"commit":"7c544fdc17f475161ac959816db91b5853142f2a"}],"number":13413}
buildkite-pr-comment-->

2024-07-11 07:13 UTC, agithomas commented
> Makes small adjustments to make all descriptions consistent.

Addressed the suggestions.

2024-07-11 07:45 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13518)
* Commit: 17317daa159cbdd0a11bf59295fa7063604a038a

### History
* :green_heart: [Build #13413](https://buildkite.com/elastic/integrations/builds/13413) succeeded 21b93e6c241cabcfdf206e8f7d1c8358ce54ea01
* :green_heart: [Build #13396](https://buildkite.com/elastic/integrations/builds/13396) succeeded 5172fb5c58af9a39287d1a478600c64ed0ae8f1f
* :green_heart: [Build #13388](https://buildkite.com/elastic/integrations/builds/13388) succeeded 56850316feb6847615b6de7cea1a28b89dbf2211
* :green_heart: [Build #13346](https://buildkite.com/elastic/integrations/builds/13346) succeeded 9551350dfa38bd6677155e27ca12ae8a1d2dff21
* :green_heart: [Build #13341](https://buildkite.com/elastic/integrations/builds/13341) succeeded 7c544fdc17f475161ac959816db91b5853142f2a
* :broken_heart: [Build #13330](https://buildkite.com/elastic/integrations/builds/13330) failed 7c544fdc17f475161ac959816db91b5853142f2a

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13518","number":13518,"commit":"17317daa159cbdd0a11bf59295fa7063604a038a"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13413","number":13413,"commit":"21b93e6c241cabcfdf206e8f7d1c8358ce54ea01"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13396","number":13396,"commit":"5172fb5c58af9a39287d1a478600c64ed0ae8f1f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13388","number":13388,"commit":"56850316feb6847615b6de7cea1a28b89dbf2211"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13346","number":13346,"commit":"9551350dfa38bd6677155e27ca12ae8a1d2dff21"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13341","number":13341,"commit":"7c544fdc17f475161ac959816db91b5853142f2a"}],"number":13518}
buildkite-pr-comment-->

2024-07-11 07:52 UTC, shmsr approved these changes

2024-07-11 08:48 UTC, zmoog approved these changes
LGTM!

I only left a comment to remind us that we may need to revisit the definitions of the `data_stream.*` and `@timestamp` fields in the future.

2024-07-11 08:48 UTC, zmoog commented on packages/aws/data_stream/awshealth/fields/base-fields.yml
> +  description: Event timestamp.
IIRC, ECS includes definitions for the `data_stream.*` and `@timestamp` fields, so we may not need to include these ones.

Base
https://www.elastic.co/guide/en/ecs/current/ecs-base.html

Data Stream
https://www.elastic.co/guide/en/ecs/current/ecs-data_stream.html

However, I just noticed that `elastic-package` [explicitly checks](https://github.com/elastic/package-spec/blob/7aa453907fb0406e32dca37e296e0a2199416487/code/go/internal/validator/semantic/validate_required_fields.go#L14-L25) for these fields, so removing them is not an option until we update `elastic-package`.

I'll leave this comment as a reminder we may need to remove these field definitions in the future.

2024-07-11 08:50 UTC, gpop63 approved these changes

2024-07-11 09:26 UTC, ishleenk17 commented on packages/aws/data_stream/awshealth/fields/base-fields.yml
> +  description: Event timestamp.
@zmoog : Please see [this](https://github.com/elastic/observability-dev/issues/3279#issuecomment-2185767189)

2024-07-11 10:26 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13535)
* Commit: b9bf787f61ff918365d9b6bdd63bccc640567ab9

### History
* :green_heart: [Build #13518](https://buildkite.com/elastic/integrations/builds/13518) succeeded 17317daa159cbdd0a11bf59295fa7063604a038a
* :green_heart: [Build #13413](https://buildkite.com/elastic/integrations/builds/13413) succeeded 21b93e6c241cabcfdf206e8f7d1c8358ce54ea01
* :green_heart: [Build #13396](https://buildkite.com/elastic/integrations/builds/13396) succeeded 5172fb5c58af9a39287d1a478600c64ed0ae8f1f
* :green_heart: [Build #13388](https://buildkite.com/elastic/integrations/builds/13388) succeeded 56850316feb6847615b6de7cea1a28b89dbf2211
* :green_heart: [Build #13346](https://buildkite.com/elastic/integrations/builds/13346) succeeded 9551350dfa38bd6677155e27ca12ae8a1d2dff21
* :green_heart: [Build #13341](https://buildkite.com/elastic/integrations/builds/13341) succeeded 7c544fdc17f475161ac959816db91b5853142f2a

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13535","number":13535,"commit":"b9bf787f61ff918365d9b6bdd63bccc640567ab9"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13518","number":13518,"commit":"17317daa159cbdd0a11bf59295fa7063604a038a"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13413","number":13413,"commit":"21b93e6c241cabcfdf206e8f7d1c8358ce54ea01"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13396","number":13396,"commit":"5172fb5c58af9a39287d1a478600c64ed0ae8f1f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13388","number":13388,"commit":"56850316feb6847615b6de7cea1a28b89dbf2211"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13346","number":13346,"commit":"9551350dfa38bd6677155e27ca12ae8a1d2dff21"}],"number":13535}
buildkite-pr-comment-->

2024-07-12 05:11 UTC, merged

2024-07-12 05:28 UTC, elasticmachine commented
Package aws - 2.18.0 containing this change is available at https://epr.elastic.co/search?package=aws