Add support for processors on vsphere datastore, host and virtualmach…
elastic/integrations pull request #10123
Opened 2024-06-11 13:52 UTC by bene-dt0

## Proposed commit message

Adds processor support for the datastore, host and virtual machine metrics data stream within the vSphere integration.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

2024-06-13 16:02 UTC, bene-dt0 commented
The contributor agreement was signed by me 2 days ago. Anything else to do?

2024-06-19 12:40 UTC, aliabbas-elastic requested changes

2024-06-19 12:40 UTC, aliabbas-elastic commented on packages/vsphere/data_stream/host/manifest.yml
> +          Processors are used to reduce the number of fields in the exported event or to enhance the event with metadata. This executes in the agent before the logs are parsed. See [Processors](https
```suggestion
          Processors are used to reduce the number of fields in the exported event or to enhance the event with metadata. This executes in the agent before the events are shipped. See [Processors](https://www.elastic.co/guide/en/fleet/current/elastic-agent-processor-configuration.html) for details.
```

Applicable to rest

2024-07-05 04:47 UTC, aliabbas-elastic commented
@bene-dt0 Can you try raising this PR again and signing the contributor agreement too as I think the CLA issue is not getting solved.

2024-07-31 07:54 UTC, closed without merging