akamai: handle input leniently
elastic/integrations pull request #10158
Opened 2024-06-17 05:54 UTC by efd6

## Proposed commit message

See title.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## How to test this PR locally

## Related issues

- Closes #10084

## Screenshots

2024-06-17 05:57 UTC, efd6 commented on packages/akamai/data_stream/siem/elasticsearch/ingest_pipeline/default.yml
> +                // Do nothing.
The alternative here is to stash them somewhere; I don't think that is worth it since they original data is still in the `event.original`.

2024-06-17 06:10 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-06-17 06:10 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12555)
* Commit: 7a0e61e47be0d1528563a9c97d4daf293bcb8d87

cc @efd6

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12555","number":12555,"commit":"7a0e61e47be0d1528563a9c97d4daf293bcb8d87"}],"number":12555}
buildkite-pr-comment-->

2024-06-20 08:57 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12673)
* Commit: 3de0e0f037b357c5918afa9062ee734574809ba5

### History
* :green_heart: [Build #12555](https://buildkite.com/elastic/integrations/builds/12555) succeeded 7a0e61e47be0d1528563a9c97d4daf293bcb8d87

cc @efd6

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12673","number":12673,"commit":"3de0e0f037b357c5918afa9062ee734574809ba5"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12555","number":12555,"commit":"7a0e61e47be0d1528563a9c97d4daf293bcb8d87"}],"number":12673}
buildkite-pr-comment-->

2024-06-23 20:51 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12736)
* Commit: b444b0dcbf1e6927b93a2d0565e4a0f6bb184a3a

### History
* :green_heart: [Build #12673](https://buildkite.com/elastic/integrations/builds/12673) succeeded 3de0e0f037b357c5918afa9062ee734574809ba5
* :green_heart: [Build #12555](https://buildkite.com/elastic/integrations/builds/12555) succeeded 7a0e61e47be0d1528563a9c97d4daf293bcb8d87

cc @efd6

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12736","number":12736,"commit":"b444b0dcbf1e6927b93a2d0565e4a0f6bb184a3a"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12673","number":12673,"commit":"3de0e0f037b357c5918afa9062ee734574809ba5"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12555","number":12555,"commit":"7a0e61e47be0d1528563a9c97d4daf293bcb8d87"}],"number":12736}
buildkite-pr-comment-->

2024-10-10 02:27 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16985)
* Commit: 18537e742d7d5f522bbbf9aa1ab8b4a490a0da6d

### History
* :green_heart: [Build #12736](https://buildkite.com/elastic/integrations/builds/12736) succeeded b444b0dcbf1e6927b93a2d0565e4a0f6bb184a3a
* :green_heart: [Build #12673](https://buildkite.com/elastic/integrations/builds/12673) succeeded 3de0e0f037b357c5918afa9062ee734574809ba5
* :green_heart: [Build #12555](https://buildkite.com/elastic/integrations/builds/12555) succeeded 7a0e61e47be0d1528563a9c97d4daf293bcb8d87

cc @efd6

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16985","number":16985,"commit":"18537e742d7d5f522bbbf9aa1ab8b4a490a0da6d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12736","number":12736,"commit":"b444b0dcbf1e6927b93a2d0565e4a0f6bb184a3a"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12673","number":12673,"commit":"3de0e0f037b357c5918afa9062ee734574809ba5"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12555","number":12555,"commit":"7a0e61e47be0d1528563a9c97d4daf293bcb8d87"}],"number":16985}
buildkite-pr-comment-->

2024-11-04 20:05 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17872)
* Commit: 38d980bd52298667ea51a44ddddabf87999b9e3d

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/17872#0192f8c7-7d93-4ab8-a532-a541e4f62995)

### History
* :green_heart: [Build #16985](https://buildkite.com/elastic/integrations/builds/16985) succeeded 18537e742d7d5f522bbbf9aa1ab8b4a490a0da6d
* :green_heart: [Build #12736](https://buildkite.com/elastic/integrations/builds/12736) succeeded b444b0dcbf1e6927b93a2d0565e4a0f6bb184a3a
* :green_heart: [Build #12673](https://buildkite.com/elastic/integrations/builds/12673) succeeded 3de0e0f037b357c5918afa9062ee734574809ba5
* :green_heart: [Build #12555](https://buildkite.com/elastic/integrations/builds/12555) succeeded 7a0e61e47be0d1528563a9c97d4daf293bcb8d87

cc @efd6

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"running","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17872","number":17872,"commit":"38d980bd52298667ea51a44ddddabf87999b9e3d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16985","number":16985,"commit":"18537e742d7d5f522bbbf9aa1ab8b4a490a0da6d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12736","number":12736,"commit":"b444b0dcbf1e6927b93a2d0565e4a0f6bb184a3a"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12673","number":12673,"commit":"3de0e0f037b357c5918afa9062ee734574809ba5"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12555","number":12555,"commit":"7a0e61e47be0d1528563a9c97d4daf293bcb8d87"}],"number":17872}
buildkite-pr-comment-->

2024-11-04 20:25 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17873)
* Commit: 6614a25548a20127394c47c853753f6c0344cca3

### History
* :broken_heart: [Build #17872](https://buildkite.com/elastic/integrations/builds/17872) failed 38d980bd52298667ea51a44ddddabf87999b9e3d
* :green_heart: [Build #16985](https://buildkite.com/elastic/integrations/builds/16985) succeeded 18537e742d7d5f522bbbf9aa1ab8b4a490a0da6d
* :green_heart: [Build #12736](https://buildkite.com/elastic/integrations/builds/12736) succeeded b444b0dcbf1e6927b93a2d0565e4a0f6bb184a3a
* :green_heart: [Build #12673](https://buildkite.com/elastic/integrations/builds/12673) succeeded 3de0e0f037b357c5918afa9062ee734574809ba5
* :green_heart: [Build #12555](https://buildkite.com/elastic/integrations/builds/12555) succeeded 7a0e61e47be0d1528563a9c97d4daf293bcb8d87

cc @efd6

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17873","number":17873,"commit":"6614a25548a20127394c47c853753f6c0344cca3"},{"buildStatus":{"state":"running","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17872","number":17872,"commit":"38d980bd52298667ea51a44ddddabf87999b9e3d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16985","number":16985,"commit":"18537e742d7d5f522bbbf9aa1ab8b4a490a0da6d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12736","number":12736,"commit":"b444b0dcbf1e6927b93a2d0565e4a0f6bb184a3a"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12673","number":12673,"commit":"3de0e0f037b357c5918afa9062ee734574809ba5"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12555","number":12555,"commit":"7a0e61e47be0d1528563a9c97d4daf293bcb8d87"}],"number":17873}
buildkite-pr-comment-->

2024-11-04 20:48 UTC, elasticmachine commented
Pinging @elastic/security-service-integrations (Team:Security-Service Integrations)

2024-11-05 15:52 UTC, chrisberkhout requested changes
Just minor comments

2024-11-05 15:52 UTC, chrisberkhout commented on packages/akamai/data_stream/siem/elasticsearch/ingest_pipeline/default.yml
> +                // Do nothing.
maybe add `error.message: "exception during base64 decoding"`?

2024-11-10 21:46 UTC, efd6 commented on packages/akamai/data_stream/siem/elasticsearch/ingest_pipeline/default.yml
> +          }
I prefer vertical space to horizontal space, so I will leave this if that's OK.

2024-11-10 22:16 UTC, efd6 commented on packages/akamai/data_stream/siem/elasticsearch/ingest_pipeline/default.yml
> +                // Do nothing.
This would cause the tests to fail. I've added a place-holder.

2024-11-10 22:45 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/18101)
* Commit: 2abfaac03941167376e142df3f45aa931a7615ed

### History
* :green_heart: [Build #17873](https://buildkite.com/elastic/integrations/builds/17873) succeeded 6614a25548a20127394c47c853753f6c0344cca3
* :broken_heart: [Build #17872](https://buildkite.com/elastic/integrations/builds/17872) failed 38d980bd52298667ea51a44ddddabf87999b9e3d
* :green_heart: [Build #16985](https://buildkite.com/elastic/integrations/builds/16985) succeeded 18537e742d7d5f522bbbf9aa1ab8b4a490a0da6d
* :green_heart: [Build #12736](https://buildkite.com/elastic/integrations/builds/12736) succeeded b444b0dcbf1e6927b93a2d0565e4a0f6bb184a3a
* :green_heart: [Build #12673](https://buildkite.com/elastic/integrations/builds/12673) succeeded 3de0e0f037b357c5918afa9062ee734574809ba5
* :green_heart: [Build #12555](https://buildkite.com/elastic/integrations/builds/12555) succeeded 7a0e61e47be0d1528563a9c97d4daf293bcb8d87

cc @efd6

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18101","number":18101,"commit":"2abfaac03941167376e142df3f45aa931a7615ed"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17873","number":17873,"commit":"6614a25548a20127394c47c853753f6c0344cca3"},{"buildStatus":{"state":"running","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17872","number":17872,"commit":"38d980bd52298667ea51a44ddddabf87999b9e3d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16985","number":16985,"commit":"18537e742d7d5f522bbbf9aa1ab8b4a490a0da6d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12736","number":12736,"commit":"b444b0dcbf1e6927b93a2d0565e4a0f6bb184a3a"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12673","number":12673,"commit":"3de0e0f037b357c5918afa9062ee734574809ba5"}],"number":18101}
buildkite-pr-comment-->

2024-11-11 08:37 UTC, chrisberkhout approved these changes

2024-11-11 21:57 UTC, merged