[O11y] Migrate infraobs packages to ecs@mappings
elastic/integrations pull request #10162
Opened 2024-06-17 13:04 UTC by harnish-elastic

- Enhancement

## Proposed commit message

```
Migration performed using ecs-update.

  go run github.com/andrewkroh/go-examples/ecs-update@f7c19f8f3fa105fe1d869ed34f4d6c76c75bce2c \
    -ecs-version=8.11.0 \
    -ecs-git-ref=v8.11.0 \
    -fields-yml-drop-ecs \
    -kibana-version=^8.13.0 \
    -drop-import-mappings \
    -pr=10135 \
    -owner=elastic/security-service-integrations \
    packages/*
```

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

2024-06-17 13:12 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12561)
* Commit: c26636b5c6694c4cf4ed9345c2eacb3df5a7dbea

### Failed CI Steps
* [Check integrations airflow](https://buildkite.com/elastic/integrations/builds/12561#01902650-1757-4428-9605-8aa6e058854c)
* [Check integrations azure_application_insights](https://buildkite.com/elastic/integrations/builds/12561#01902650-1766-4764-bf34-5649cf42eb3c)
* [Check integrations azure_functions](https://buildkite.com/elastic/integrations/builds/12561#01902650-176b-4c93-b9d8-a3fc60b4bed8)
* [Check integrations influxdb](https://buildkite.com/elastic/integrations/builds/12561#01902650-1790-40d0-a258-5b25c0d508df)
* [Check integrations jolokia_input](https://buildkite.com/elastic/integrations/builds/12561#01902650-1792-4a39-9de3-b4d24b191591)
* [Check integrations mongodb](https://buildkite.com/elastic/integrations/builds/12561#01902650-179f-4296-acb3-8ed3b6e639ae)
* [Check integrations postgresql](https://buildkite.com/elastic/integrations/builds/12561#01902650-17b3-45fd-86c2-b2d250283a5d)

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12561","number":12561,"commit":"c26636b5c6694c4cf4ed9345c2eacb3df5a7dbea"}],"number":12561}
buildkite-pr-comment-->

2024-06-17 13:48 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12563)
* Commit: 960f1d404cc7386555071b92254f88b66da75577

### Failed CI Steps
* [Check integrations apache](https://buildkite.com/elastic/integrations/builds/12563#01902670-e4ec-4ade-8638-d4f67432562c)
* [Check integrations azure_app_service](https://buildkite.com/elastic/integrations/builds/12563#01902670-e4f7-40ca-86d3-f6179a6e8f0a)
* [Check integrations haproxy](https://buildkite.com/elastic/integrations/builds/12563#01902670-e51c-4bd2-9cd0-0b1e107dd638)
* [Check integrations influxdb](https://buildkite.com/elastic/integrations/builds/12563#01902670-e524-4f69-85d9-03487830dbba)
* [Check integrations memcached](https://buildkite.com/elastic/integrations/builds/12563#01902670-e52f-4733-a338-f2701fa9ed9e)
* [Check integrations zookeeper](https://buildkite.com/elastic/integrations/builds/12563#01902670-e561-42f1-8794-17ee5a108309)

### History
* :broken_heart: [Build #12561](https://buildkite.com/elastic/integrations/builds/12561) failed c26636b5c6694c4cf4ed9345c2eacb3df5a7dbea

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12563","number":12563,"commit":"960f1d404cc7386555071b92254f88b66da75577"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12561","number":12561,"commit":"c26636b5c6694c4cf4ed9345c2eacb3df5a7dbea"}],"number":12563}
buildkite-pr-comment-->

2024-06-18 05:26 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12592)
* Commit: c1ac46826559790bf0f0b5999467beb3d6f843fe

### Failed CI Steps
* [Check integrations azure_application_insights](https://buildkite.com/elastic/integrations/builds/12592#019029c8-ef0b-49eb-b905-c2c0bad46461)
* [Check integrations memcached](https://buildkite.com/elastic/integrations/builds/12592#019029c8-ef37-4fc4-a240-de93945c4836)

### History
* :broken_heart: [Build #12563](https://buildkite.com/elastic/integrations/builds/12563) failed 960f1d404cc7386555071b92254f88b66da75577
* :broken_heart: [Build #12561](https://buildkite.com/elastic/integrations/builds/12561) failed c26636b5c6694c4cf4ed9345c2eacb3df5a7dbea

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12592","number":12592,"commit":"c1ac46826559790bf0f0b5999467beb3d6f843fe"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12563","number":12563,"commit":"960f1d404cc7386555071b92254f88b66da75577"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12561","number":12561,"commit":"c26636b5c6694c4cf4ed9345c2eacb3df5a7dbea"}],"number":12592}
buildkite-pr-comment-->

2024-06-18 06:06 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12596)
* Commit: ab80f0cb8597534ea3b08b094a8ef83d167aa790

### Failed CI Steps
* [Check integrations azure_application_insights](https://buildkite.com/elastic/integrations/builds/12596#019029ed-b905-406d-a26f-a19f29c52737)
* [Check integrations cockroachdb](https://buildkite.com/elastic/integrations/builds/12596#019029ed-b911-4847-8ff6-e2dd8682a7da)

### History
* :broken_heart: [Build #12592](https://buildkite.com/elastic/integrations/builds/12592) failed c1ac46826559790bf0f0b5999467beb3d6f843fe
* :broken_heart: [Build #12563](https://buildkite.com/elastic/integrations/builds/12563) failed 960f1d404cc7386555071b92254f88b66da75577
* :broken_heart: [Build #12561](https://buildkite.com/elastic/integrations/builds/12561) failed c26636b5c6694c4cf4ed9345c2eacb3df5a7dbea

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12596","number":12596,"commit":"ab80f0cb8597534ea3b08b094a8ef83d167aa790"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12592","number":12592,"commit":"c1ac46826559790bf0f0b5999467beb3d6f843fe"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12563","number":12563,"commit":"960f1d404cc7386555071b92254f88b66da75577"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12561","number":12561,"commit":"c26636b5c6694c4cf4ed9345c2eacb3df5a7dbea"}],"number":12596}
buildkite-pr-comment-->

2024-06-18 10:20 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12611)
* Commit: 12638fb04bee34f95f96bdc506d57c0446bc94e9

### Failed CI Steps
* [Check integrations couchdb](https://buildkite.com/elastic/integrations/builds/12611#01902ad6-5e69-48ee-9eba-fbebf7117e3b)
* [Check integrations hadoop](https://buildkite.com/elastic/integrations/builds/12611#01902ad6-5e72-46d8-abf5-a8e3f6058d27)

### History
* :broken_heart: [Build #12596](https://buildkite.com/elastic/integrations/builds/12596) failed ab80f0cb8597534ea3b08b094a8ef83d167aa790
* :broken_heart: [Build #12592](https://buildkite.com/elastic/integrations/builds/12592) failed c1ac46826559790bf0f0b5999467beb3d6f843fe
* :broken_heart: [Build #12563](https://buildkite.com/elastic/integrations/builds/12563) failed 960f1d404cc7386555071b92254f88b66da75577
* :broken_heart: [Build #12561](https://buildkite.com/elastic/integrations/builds/12561) failed c26636b5c6694c4cf4ed9345c2eacb3df5a7dbea

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12611","number":12611,"commit":"12638fb04bee34f95f96bdc506d57c0446bc94e9"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12596","number":12596,"commit":"ab80f0cb8597534ea3b08b094a8ef83d167aa790"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12592","number":12592,"commit":"c1ac46826559790bf0f0b5999467beb3d6f843fe"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12563","number":12563,"commit":"960f1d404cc7386555071b92254f88b66da75577"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12561","number":12561,"commit":"c26636b5c6694c4cf4ed9345c2eacb3df5a7dbea"}],"number":12611}
buildkite-pr-comment-->

2024-06-18 12:30 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12618)
* Commit: 3ac3f7edb68ffacb82d12aa08fa9cedfe6c899d6

### Failed CI Steps
* [Check integrations couchbase](https://buildkite.com/elastic/integrations/builds/12618#01902b3f-069b-43b0-a955-1f5feb886a7d)

### History
* :broken_heart: [Build #12611](https://buildkite.com/elastic/integrations/builds/12611) failed 12638fb04bee34f95f96bdc506d57c0446bc94e9
* :broken_heart: [Build #12596](https://buildkite.com/elastic/integrations/builds/12596) failed ab80f0cb8597534ea3b08b094a8ef83d167aa790
* :broken_heart: [Build #12592](https://buildkite.com/elastic/integrations/builds/12592) failed c1ac46826559790bf0f0b5999467beb3d6f843fe
* :broken_heart: [Build #12563](https://buildkite.com/elastic/integrations/builds/12563) failed 960f1d404cc7386555071b92254f88b66da75577
* :broken_heart: [Build #12561](https://buildkite.com/elastic/integrations/builds/12561) failed c26636b5c6694c4cf4ed9345c2eacb3df5a7dbea

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12618","number":12618,"commit":"3ac3f7edb68ffacb82d12aa08fa9cedfe6c899d6"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12611","number":12611,"commit":"12638fb04bee34f95f96bdc506d57c0446bc94e9"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12596","number":12596,"commit":"ab80f0cb8597534ea3b08b094a8ef83d167aa790"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12592","number":12592,"commit":"c1ac46826559790bf0f0b5999467beb3d6f843fe"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12563","number":12563,"commit":"960f1d404cc7386555071b92254f88b66da75577"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12561","number":12561,"commit":"c26636b5c6694c4cf4ed9345c2eacb3df5a7dbea"}],"number":12618}
buildkite-pr-comment-->

2024-06-19 05:33 UTC, harnish-elastic commented
/test

2024-06-19 06:12 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12654)
* Commit: 3ac3f7edb68ffacb82d12aa08fa9cedfe6c899d6

### History
* :broken_heart: [Build #12618](https://buildkite.com/elastic/integrations/builds/12618) failed 3ac3f7edb68ffacb82d12aa08fa9cedfe6c899d6
* :broken_heart: [Build #12611](https://buildkite.com/elastic/integrations/builds/12611) failed 12638fb04bee34f95f96bdc506d57c0446bc94e9
* :broken_heart: [Build #12596](https://buildkite.com/elastic/integrations/builds/12596) failed ab80f0cb8597534ea3b08b094a8ef83d167aa790
* :broken_heart: [Build #12592](https://buildkite.com/elastic/integrations/builds/12592) failed c1ac46826559790bf0f0b5999467beb3d6f843fe
* :broken_heart: [Build #12563](https://buildkite.com/elastic/integrations/builds/12563) failed 960f1d404cc7386555071b92254f88b66da75577

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12654","number":12654,"commit":"3ac3f7edb68ffacb82d12aa08fa9cedfe6c899d6"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12618","number":12618,"commit":"3ac3f7edb68ffacb82d12aa08fa9cedfe6c899d6"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12611","number":12611,"commit":"12638fb04bee34f95f96bdc506d57c0446bc94e9"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12596","number":12596,"commit":"ab80f0cb8597534ea3b08b094a8ef83d167aa790"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12592","number":12592,"commit":"c1ac46826559790bf0f0b5999467beb3d6f843fe"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12563","number":12563,"commit":"960f1d404cc7386555071b92254f88b66da75577"}],"number":12654}
buildkite-pr-comment-->

2024-06-20 10:13 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12674)
* Commit: a84f04a336e42e652c8948385ccb5b4fe1947957

### Failed CI Steps
* [Check integrations couchbase](https://buildkite.com/elastic/integrations/builds/12674#0190350f-3b53-43fc-8cb3-2bc0918c51c9)

### History
* :green_heart: [Build #12654](https://buildkite.com/elastic/integrations/builds/12654) succeeded 3ac3f7edb68ffacb82d12aa08fa9cedfe6c899d6
* :broken_heart: [Build #12618](https://buildkite.com/elastic/integrations/builds/12618) failed 3ac3f7edb68ffacb82d12aa08fa9cedfe6c899d6
* :broken_heart: [Build #12611](https://buildkite.com/elastic/integrations/builds/12611) failed 12638fb04bee34f95f96bdc506d57c0446bc94e9
* :broken_heart: [Build #12596](https://buildkite.com/elastic/integrations/builds/12596) failed ab80f0cb8597534ea3b08b094a8ef83d167aa790
* :broken_heart: [Build #12592](https://buildkite.com/elastic/integrations/builds/12592) failed c1ac46826559790bf0f0b5999467beb3d6f843fe
* :broken_heart: [Build #12563](https://buildkite.com/elastic/integrations/builds/12563) failed 960f1d404cc7386555071b92254f88b66da75577

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12674","number":12674,"commit":"a84f04a336e42e652c8948385ccb5b4fe1947957"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12654","number":12654,"commit":"3ac3f7edb68ffacb82d12aa08fa9cedfe6c899d6"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12618","number":12618,"commit":"3ac3f7edb68ffacb82d12aa08fa9cedfe6c899d6"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12611","number":12611,"commit":"12638fb04bee34f95f96bdc506d57c0446bc94e9"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12596","number":12596,"commit":"ab80f0cb8597534ea3b08b094a8ef83d167aa790"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12592","number":12592,"commit":"c1ac46826559790bf0f0b5999467beb3d6f843fe"}],"number":12674}
buildkite-pr-comment-->

2024-06-20 10:14 UTC, harnish-elastic commented
/test

2024-06-24 07:02 UTC, ishleenk17 commented
The link to ECS documentation is not added in these ?
@harnish-elastic

2024-06-24 07:06 UTC, harnish-elastic commented
> The link to ECS documentation is not added in these ? @harnish-elastic

@ishleenk17 The changes are in progress! I will open this PR once that changes done.

2024-06-24 07:12 UTC, ishleenk17 commented
Lets also perform TSDB testing on some of the integrations, to ensure this doesn't break anything.

2024-06-24 09:50 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12762)
* Commit: bd35cdb46b400a30e6da73714848d3ebc62a7575

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/12762#019049a6-1942-4474-ba0c-7c145f6f9f0a)

### History
* :green_heart: [Build #12676](https://buildkite.com/elastic/integrations/builds/12676) succeeded a84f04a336e42e652c8948385ccb5b4fe1947957
* :broken_heart: [Build #12674](https://buildkite.com/elastic/integrations/builds/12674) failed a84f04a336e42e652c8948385ccb5b4fe1947957
* :green_heart: [Build #12654](https://buildkite.com/elastic/integrations/builds/12654) succeeded 3ac3f7edb68ffacb82d12aa08fa9cedfe6c899d6
* :broken_heart: [Build #12618](https://buildkite.com/elastic/integrations/builds/12618) failed 3ac3f7edb68ffacb82d12aa08fa9cedfe6c899d6
* :broken_heart: [Build #12611](https://buildkite.com/elastic/integrations/builds/12611) failed 12638fb04bee34f95f96bdc506d57c0446bc94e9
* :broken_heart: [Build #12596](https://buildkite.com/elastic/integrations/builds/12596) failed ab80f0cb8597534ea3b08b094a8ef83d167aa790

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12762","number":12762,"commit":"bd35cdb46b400a30e6da73714848d3ebc62a7575"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12676","number":12676,"commit":"a84f04a336e42e652c8948385ccb5b4fe1947957"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12674","number":12674,"commit":"a84f04a336e42e652c8948385ccb5b4fe1947957"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12654","number":12654,"commit":"3ac3f7edb68ffacb82d12aa08fa9cedfe6c899d6"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12618","number":12618,"commit":"3ac3f7edb68ffacb82d12aa08fa9cedfe6c899d6"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12611","number":12611,"commit":"12638fb04bee34f95f96bdc506d57c0446bc94e9"}],"number":12762}
buildkite-pr-comment-->

2024-06-24 14:15 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12782)
* Commit: 6c7f31df3cb6ee91ce74bd074c5277989d38cb29

### Failed CI Steps
* [Check integrations apache](https://buildkite.com/elastic/integrations/builds/12782#01904a78-7f6c-485e-a4f0-65482815e370)

### History
* :broken_heart: [Build #12762](https://buildkite.com/elastic/integrations/builds/12762) failed bd35cdb46b400a30e6da73714848d3ebc62a7575
* :green_heart: [Build #12676](https://buildkite.com/elastic/integrations/builds/12676) succeeded a84f04a336e42e652c8948385ccb5b4fe1947957
* :broken_heart: [Build #12674](https://buildkite.com/elastic/integrations/builds/12674) failed a84f04a336e42e652c8948385ccb5b4fe1947957
* :green_heart: [Build #12654](https://buildkite.com/elastic/integrations/builds/12654) succeeded 3ac3f7edb68ffacb82d12aa08fa9cedfe6c899d6
* :broken_heart: [Build #12618](https://buildkite.com/elastic/integrations/builds/12618) failed 3ac3f7edb68ffacb82d12aa08fa9cedfe6c899d6
* :broken_heart: [Build #12611](https://buildkite.com/elastic/integrations/builds/12611) failed 12638fb04bee34f95f96bdc506d57c0446bc94e9

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12782","number":12782,"commit":"6c7f31df3cb6ee91ce74bd074c5277989d38cb29"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12762","number":12762,"commit":"bd35cdb46b400a30e6da73714848d3ebc62a7575"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12676","number":12676,"commit":"a84f04a336e42e652c8948385ccb5b4fe1947957"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12674","number":12674,"commit":"a84f04a336e42e652c8948385ccb5b4fe1947957"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12654","number":12654,"commit":"3ac3f7edb68ffacb82d12aa08fa9cedfe6c899d6"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12618","number":12618,"commit":"3ac3f7edb68ffacb82d12aa08fa9cedfe6c899d6"}],"number":12782}
buildkite-pr-comment-->

2024-06-25 07:09 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12799)
* Commit: 4d557a196e9bf48582ac381903a2454d1da17926

### Failed CI Steps
* [Check integrations couchbase](https://buildkite.com/elastic/integrations/builds/12799#01904e24-2d9e-4095-9301-26a2f8c7f2c3)

### History
* :broken_heart: [Build #12782](https://buildkite.com/elastic/integrations/builds/12782) failed 6c7f31df3cb6ee91ce74bd074c5277989d38cb29
* :broken_heart: [Build #12762](https://buildkite.com/elastic/integrations/builds/12762) failed bd35cdb46b400a30e6da73714848d3ebc62a7575
* :green_heart: [Build #12676](https://buildkite.com/elastic/integrations/builds/12676) succeeded a84f04a336e42e652c8948385ccb5b4fe1947957
* :broken_heart: [Build #12674](https://buildkite.com/elastic/integrations/builds/12674) failed a84f04a336e42e652c8948385ccb5b4fe1947957
* :green_heart: [Build #12654](https://buildkite.com/elastic/integrations/builds/12654) succeeded 3ac3f7edb68ffacb82d12aa08fa9cedfe6c899d6
* :broken_heart: [Build #12618](https://buildkite.com/elastic/integrations/builds/12618) failed 3ac3f7edb68ffacb82d12aa08fa9cedfe6c899d6

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12799","number":12799,"commit":"4d557a196e9bf48582ac381903a2454d1da17926"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12782","number":12782,"commit":"6c7f31df3cb6ee91ce74bd074c5277989d38cb29"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12762","number":12762,"commit":"bd35cdb46b400a30e6da73714848d3ebc62a7575"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12676","number":12676,"commit":"a84f04a336e42e652c8948385ccb5b4fe1947957"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12674","number":12674,"commit":"a84f04a336e42e652c8948385ccb5b4fe1947957"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12654","number":12654,"commit":"3ac3f7edb68ffacb82d12aa08fa9cedfe6c899d6"}],"number":12799}
buildkite-pr-comment-->

2024-06-25 07:11 UTC, harnish-elastic commented
/test

2024-06-25 07:19 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12807)
* Commit: ac731a63871c3e267d9d741557b177f444b6cf0b

### Failed CI Steps
* [Check integrations etcd](https://buildkite.com/elastic/integrations/builds/12807#01904e40-59d5-4b72-b8fe-c037c0c6c019)

### History
* :broken_heart: [Build #12799](https://buildkite.com/elastic/integrations/builds/12799) failed 4d557a196e9bf48582ac381903a2454d1da17926
* :broken_heart: [Build #12782](https://buildkite.com/elastic/integrations/builds/12782) failed 6c7f31df3cb6ee91ce74bd074c5277989d38cb29
* :broken_heart: [Build #12762](https://buildkite.com/elastic/integrations/builds/12762) failed bd35cdb46b400a30e6da73714848d3ebc62a7575
* :green_heart: [Build #12676](https://buildkite.com/elastic/integrations/builds/12676) succeeded a84f04a336e42e652c8948385ccb5b4fe1947957
* :broken_heart: [Build #12674](https://buildkite.com/elastic/integrations/builds/12674) failed a84f04a336e42e652c8948385ccb5b4fe1947957
* :green_heart: [Build #12654](https://buildkite.com/elastic/integrations/builds/12654) succeeded 3ac3f7edb68ffacb82d12aa08fa9cedfe6c899d6

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12807","number":12807,"commit":"ac731a63871c3e267d9d741557b177f444b6cf0b"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12799","number":12799,"commit":"4d557a196e9bf48582ac381903a2454d1da17926"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12782","number":12782,"commit":"6c7f31df3cb6ee91ce74bd074c5277989d38cb29"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12762","number":12762,"commit":"bd35cdb46b400a30e6da73714848d3ebc62a7575"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12676","number":12676,"commit":"a84f04a336e42e652c8948385ccb5b4fe1947957"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12674","number":12674,"commit":"a84f04a336e42e652c8948385ccb5b4fe1947957"}],"number":12807}
buildkite-pr-comment-->

2024-06-25 10:34 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12821)
* Commit: f637e29f052329798f6a0453865084ecdbc2e2ab

### History
* :broken_heart: [Build #12807](https://buildkite.com/elastic/integrations/builds/12807) failed ac731a63871c3e267d9d741557b177f444b6cf0b
* :broken_heart: [Build #12799](https://buildkite.com/elastic/integrations/builds/12799) failed 4d557a196e9bf48582ac381903a2454d1da17926
* :broken_heart: [Build #12782](https://buildkite.com/elastic/integrations/builds/12782) failed 6c7f31df3cb6ee91ce74bd074c5277989d38cb29
* :broken_heart: [Build #12762](https://buildkite.com/elastic/integrations/builds/12762) failed bd35cdb46b400a30e6da73714848d3ebc62a7575
* :green_heart: [Build #12676](https://buildkite.com/elastic/integrations/builds/12676) succeeded a84f04a336e42e652c8948385ccb5b4fe1947957

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12821","number":12821,"commit":"f637e29f052329798f6a0453865084ecdbc2e2ab"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12807","number":12807,"commit":"ac731a63871c3e267d9d741557b177f444b6cf0b"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12799","number":12799,"commit":"4d557a196e9bf48582ac381903a2454d1da17926"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12782","number":12782,"commit":"6c7f31df3cb6ee91ce74bd074c5277989d38cb29"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12762","number":12762,"commit":"bd35cdb46b400a30e6da73714848d3ebc62a7575"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12676","number":12676,"commit":"a84f04a336e42e652c8948385ccb5b4fe1947957"}],"number":12821}
buildkite-pr-comment-->

2024-06-26 07:32 UTC, niraj-elastic requested changes

2024-06-26 11:28 UTC, harnish-elastic commented on packages/azure_app_service/data_stream/app_service_logs/fields/ecs.yml
>  - name: dns.response_code
Seems like previously, there is `external: ecs` was missing from `- name: dns.response_code`. I have checked this is [ecs field](https://www.elastic.co/guide/en/ecs/current/ecs-dns.html#field-dns-response-code) and removed it from ecs.yml file! Thanks.

2024-06-26 11:37 UTC, harnish-elastic commented on packages/azure_app_service/data_stream/app_service_logs/fields/ecs.yml
>  - name: dns.response_code
Found same issue in azure firewall_logs data stream. I have resolved there as well! https://github.com/elastic/integrations/pull/10224/commits/f452d01e28fed6bb894dc21adeea08bb739b106d#diff-5eb7abc19af779ea0192e0b787b943a5cfa71aee0377e78a81b9c3e5c89d1fd8

2024-06-26 12:03 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12918)
* Commit: b590918d11f5887f48edad155903329931a1e120

### History
* :green_heart: [Build #12821](https://buildkite.com/elastic/integrations/builds/12821) succeeded f637e29f052329798f6a0453865084ecdbc2e2ab
* :broken_heart: [Build #12807](https://buildkite.com/elastic/integrations/builds/12807) failed ac731a63871c3e267d9d741557b177f444b6cf0b
* :broken_heart: [Build #12799](https://buildkite.com/elastic/integrations/builds/12799) failed 4d557a196e9bf48582ac381903a2454d1da17926
* :broken_heart: [Build #12782](https://buildkite.com/elastic/integrations/builds/12782) failed 6c7f31df3cb6ee91ce74bd074c5277989d38cb29
* :broken_heart: [Build #12762](https://buildkite.com/elastic/integrations/builds/12762) failed bd35cdb46b400a30e6da73714848d3ebc62a7575
* :green_heart: [Build #12676](https://buildkite.com/elastic/integrations/builds/12676) succeeded a84f04a336e42e652c8948385ccb5b4fe1947957

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12918","number":12918,"commit":"b590918d11f5887f48edad155903329931a1e120"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12821","number":12821,"commit":"f637e29f052329798f6a0453865084ecdbc2e2ab"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12807","number":12807,"commit":"ac731a63871c3e267d9d741557b177f444b6cf0b"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12799","number":12799,"commit":"4d557a196e9bf48582ac381903a2454d1da17926"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12782","number":12782,"commit":"6c7f31df3cb6ee91ce74bd074c5277989d38cb29"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12762","number":12762,"commit":"bd35cdb46b400a30e6da73714848d3ebc62a7575"}],"number":12918}
buildkite-pr-comment-->

2024-06-26 12:25 UTC, niraj-elastic approved these changes
LGTM

2024-07-03 05:48 UTC, ishleenk17 commented on packages/activemq/data_stream/audit/fields/agent.yml
>    type: group
Do we need a greoup here ?
Since now its a single field ?

2024-07-03 05:48 UTC, ishleenk17 commented on packages/airflow/data_stream/statsd/fields/ecs.yml
>  - name: host
This is not an ecs field.
Can we check what is this field and if it was added here unintentionally?

2024-07-03 05:48 UTC, ishleenk17 commented on packages/awsfargate/data_stream/task_stats/fields/ecs.yml
>  - external: ecs
There is no such field in ECS. Pls check why is this here ?

2024-07-03 05:48 UTC, ishleenk17 commented on packages/awsfargate/data_stream/task_stats/fields/ecs.yml
>    name: container
Same holds true for this. 
Can you verify why are these here ? They don't have any external ECS reference.

2024-07-03 05:48 UTC, ishleenk17 commented on packages/awsfargate/data_stream/task_stats/fields/ecs.yml
>  - name: container.labels.com_amazonaws_ecs_cluster
Should this go to fields.yml ?

2024-07-03 05:48 UTC, ishleenk17 commented on packages/azure_application_insights/data_stream/app_insights/fields/ecs.yml
>  - name: host
Same as above shared reviews for this field.

2024-07-03 06:18 UTC, harnish-elastic commented on packages/awsfargate/data_stream/task_stats/fields/ecs.yml
>  - name: container.labels.com_amazonaws_ecs_cluster
Please refer this ecs reference. https://www.elastic.co/guide/en/ecs/current/ecs-container.html#field-container-labels

The container.labels is an ecs field with object type. The changes are made in [this](https://github.com/elastic/integrations/pull/2971/files#diff-953181fc93b5fd95532f6f3e6c37526356708b1612fc6dd6559c7c8a8e2481e1R39-R53) PR by @zmoog.

@zmoog Can you confirm if we can move this fields to fields.yml file or we can keep this as it is?

2024-07-03 06:53 UTC, harnish-elastic commented on packages/activemq/data_stream/audit/fields/agent.yml
>    type: group
Yes, we need this hierarchy as there are two descriptions currently present. One related to `cloud` and other related to `cloud.image.id`

2024-07-03 07:02 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13163)
* Commit: f02f223159d853b5226bf1168e22e0998132b88d

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/13163#01907765-9abf-46e5-b6e4-115933491c51)

### History
* :green_heart: [Build #12918](https://buildkite.com/elastic/integrations/builds/12918) succeeded b590918d11f5887f48edad155903329931a1e120
* :green_heart: [Build #12821](https://buildkite.com/elastic/integrations/builds/12821) succeeded f637e29f052329798f6a0453865084ecdbc2e2ab
* :broken_heart: [Build #12807](https://buildkite.com/elastic/integrations/builds/12807) failed ac731a63871c3e267d9d741557b177f444b6cf0b
* :broken_heart: [Build #12799](https://buildkite.com/elastic/integrations/builds/12799) failed 4d557a196e9bf48582ac381903a2454d1da17926
* :broken_heart: [Build #12782](https://buildkite.com/elastic/integrations/builds/12782) failed 6c7f31df3cb6ee91ce74bd074c5277989d38cb29
* :broken_heart: [Build #12762](https://buildkite.com/elastic/integrations/builds/12762) failed bd35cdb46b400a30e6da73714848d3ebc62a7575

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13163","number":13163,"commit":"f02f223159d853b5226bf1168e22e0998132b88d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12918","number":12918,"commit":"b590918d11f5887f48edad155903329931a1e120"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12821","number":12821,"commit":"f637e29f052329798f6a0453865084ecdbc2e2ab"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12807","number":12807,"commit":"ac731a63871c3e267d9d741557b177f444b6cf0b"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12799","number":12799,"commit":"4d557a196e9bf48582ac381903a2454d1da17926"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12782","number":12782,"commit":"6c7f31df3cb6ee91ce74bd074c5277989d38cb29"}],"number":13163}
buildkite-pr-comment-->

2024-07-03 07:15 UTC, harnish-elastic commented on packages/awsfargate/data_stream/task_stats/fields/ecs.yml
>    name: container
Updated thanks!

2024-07-03 07:15 UTC, harnish-elastic commented on packages/azure_application_insights/data_stream/app_insights/fields/ecs.yml
>  - name: host
Updated thanks!

2024-07-03 07:16 UTC, harnish-elastic commented on packages/awsfargate/data_stream/task_stats/fields/ecs.yml
>  - external: ecs
Updated thanks!

2024-07-03 07:16 UTC, harnish-elastic commented on packages/airflow/data_stream/statsd/fields/ecs.yml
>  - name: host
Updated thanks!

2024-07-03 07:41 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13164)
* Commit: 6396f10d4566e0c765128440755c1a985ac103d8

### Failed CI Steps
* [Check integrations hadoop](https://buildkite.com/elastic/integrations/builds/13164#01907777-e24c-46e8-855b-c502f2776f3e)

### History
* :broken_heart: [Build #13163](https://buildkite.com/elastic/integrations/builds/13163) failed f02f223159d853b5226bf1168e22e0998132b88d
* :green_heart: [Build #12918](https://buildkite.com/elastic/integrations/builds/12918) succeeded b590918d11f5887f48edad155903329931a1e120
* :green_heart: [Build #12821](https://buildkite.com/elastic/integrations/builds/12821) succeeded f637e29f052329798f6a0453865084ecdbc2e2ab
* :broken_heart: [Build #12807](https://buildkite.com/elastic/integrations/builds/12807) failed ac731a63871c3e267d9d741557b177f444b6cf0b
* :broken_heart: [Build #12799](https://buildkite.com/elastic/integrations/builds/12799) failed 4d557a196e9bf48582ac381903a2454d1da17926
* :broken_heart: [Build #12782](https://buildkite.com/elastic/integrations/builds/12782) failed 6c7f31df3cb6ee91ce74bd074c5277989d38cb29

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13164","number":13164,"commit":"6396f10d4566e0c765128440755c1a985ac103d8"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13163","number":13163,"commit":"f02f223159d853b5226bf1168e22e0998132b88d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12918","number":12918,"commit":"b590918d11f5887f48edad155903329931a1e120"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12821","number":12821,"commit":"f637e29f052329798f6a0453865084ecdbc2e2ab"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12807","number":12807,"commit":"ac731a63871c3e267d9d741557b177f444b6cf0b"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12799","number":12799,"commit":"4d557a196e9bf48582ac381903a2454d1da17926"}],"number":13164}
buildkite-pr-comment-->

2024-07-03 07:43 UTC, harnish-elastic commented
/test

2024-07-03 08:07 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13167)
* Commit: 6396f10d4566e0c765128440755c1a985ac103d8

### Failed CI Steps
* [Check integrations hadoop](https://buildkite.com/elastic/integrations/builds/13167#0190778f-cccf-4212-a65a-4f87c5cce0a7)

### History
* :broken_heart: [Build #13164](https://buildkite.com/elastic/integrations/builds/13164) failed 6396f10d4566e0c765128440755c1a985ac103d8
* :broken_heart: [Build #13163](https://buildkite.com/elastic/integrations/builds/13163) failed f02f223159d853b5226bf1168e22e0998132b88d
* :green_heart: [Build #12918](https://buildkite.com/elastic/integrations/builds/12918) succeeded b590918d11f5887f48edad155903329931a1e120
* :green_heart: [Build #12821](https://buildkite.com/elastic/integrations/builds/12821) succeeded f637e29f052329798f6a0453865084ecdbc2e2ab
* :broken_heart: [Build #12807](https://buildkite.com/elastic/integrations/builds/12807) failed ac731a63871c3e267d9d741557b177f444b6cf0b
* :broken_heart: [Build #12799](https://buildkite.com/elastic/integrations/builds/12799) failed 4d557a196e9bf48582ac381903a2454d1da17926

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13167","number":13167,"commit":"6396f10d4566e0c765128440755c1a985ac103d8"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13164","number":13164,"commit":"6396f10d4566e0c765128440755c1a985ac103d8"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13163","number":13163,"commit":"f02f223159d853b5226bf1168e22e0998132b88d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12918","number":12918,"commit":"b590918d11f5887f48edad155903329931a1e120"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12821","number":12821,"commit":"f637e29f052329798f6a0453865084ecdbc2e2ab"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12807","number":12807,"commit":"ac731a63871c3e267d9d741557b177f444b6cf0b"}],"number":13167}
buildkite-pr-comment-->

2024-07-03 10:01 UTC, harnish-elastic commented
/test

2024-07-03 10:27 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13183)
* Commit: 6396f10d4566e0c765128440755c1a985ac103d8

### Failed CI Steps
* [Check integrations hadoop](https://buildkite.com/elastic/integrations/builds/13183#01907810-4b0c-452c-a582-fb88ca016ce9)

### History
* :broken_heart: [Build #13167](https://buildkite.com/elastic/integrations/builds/13167) failed 6396f10d4566e0c765128440755c1a985ac103d8
* :broken_heart: [Build #13164](https://buildkite.com/elastic/integrations/builds/13164) failed 6396f10d4566e0c765128440755c1a985ac103d8
* :broken_heart: [Build #13163](https://buildkite.com/elastic/integrations/builds/13163) failed f02f223159d853b5226bf1168e22e0998132b88d
* :green_heart: [Build #12918](https://buildkite.com/elastic/integrations/builds/12918) succeeded b590918d11f5887f48edad155903329931a1e120
* :green_heart: [Build #12821](https://buildkite.com/elastic/integrations/builds/12821) succeeded f637e29f052329798f6a0453865084ecdbc2e2ab

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13183","number":13183,"commit":"6396f10d4566e0c765128440755c1a985ac103d8"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13167","number":13167,"commit":"6396f10d4566e0c765128440755c1a985ac103d8"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13164","number":13164,"commit":"6396f10d4566e0c765128440755c1a985ac103d8"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13163","number":13163,"commit":"f02f223159d853b5226bf1168e22e0998132b88d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12918","number":12918,"commit":"b590918d11f5887f48edad155903329931a1e120"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12821","number":12821,"commit":"f637e29f052329798f6a0453865084ecdbc2e2ab"}],"number":13183}
buildkite-pr-comment-->

2024-07-04 06:27 UTC, harnish-elastic commented
/test

2024-07-04 06:50 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13227)
* Commit: 6396f10d4566e0c765128440755c1a985ac103d8

### Failed CI Steps
* [Check integrations hadoop](https://buildkite.com/elastic/integrations/builds/13227#01907c6f-c9eb-4f53-ba47-f5f0c9db7f0e)

### History
* :broken_heart: [Build #13183](https://buildkite.com/elastic/integrations/builds/13183) failed 6396f10d4566e0c765128440755c1a985ac103d8
* :broken_heart: [Build #13167](https://buildkite.com/elastic/integrations/builds/13167) failed 6396f10d4566e0c765128440755c1a985ac103d8
* :broken_heart: [Build #13164](https://buildkite.com/elastic/integrations/builds/13164) failed 6396f10d4566e0c765128440755c1a985ac103d8
* :broken_heart: [Build #13163](https://buildkite.com/elastic/integrations/builds/13163) failed f02f223159d853b5226bf1168e22e0998132b88d
* :green_heart: [Build #12918](https://buildkite.com/elastic/integrations/builds/12918) succeeded b590918d11f5887f48edad155903329931a1e120

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13227","number":13227,"commit":"6396f10d4566e0c765128440755c1a985ac103d8"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13183","number":13183,"commit":"6396f10d4566e0c765128440755c1a985ac103d8"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13167","number":13167,"commit":"6396f10d4566e0c765128440755c1a985ac103d8"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13164","number":13164,"commit":"6396f10d4566e0c765128440755c1a985ac103d8"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13163","number":13163,"commit":"f02f223159d853b5226bf1168e22e0998132b88d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12918","number":12918,"commit":"b590918d11f5887f48edad155903329931a1e120"}],"number":13227}
buildkite-pr-comment-->

2024-07-04 06:52 UTC, harnish-elastic commented
/test

2024-07-04 07:17 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13230)
* Commit: 6396f10d4566e0c765128440755c1a985ac103d8

### Failed CI Steps
* [Check integrations hadoop](https://buildkite.com/elastic/integrations/builds/13230#01907c87-fb84-4c1d-b775-450488f1cc29)

### History
* :broken_heart: [Build #13227](https://buildkite.com/elastic/integrations/builds/13227) failed 6396f10d4566e0c765128440755c1a985ac103d8
* :broken_heart: [Build #13183](https://buildkite.com/elastic/integrations/builds/13183) failed 6396f10d4566e0c765128440755c1a985ac103d8
* :broken_heart: [Build #13167](https://buildkite.com/elastic/integrations/builds/13167) failed 6396f10d4566e0c765128440755c1a985ac103d8
* :broken_heart: [Build #13164](https://buildkite.com/elastic/integrations/builds/13164) failed 6396f10d4566e0c765128440755c1a985ac103d8
* :broken_heart: [Build #13163](https://buildkite.com/elastic/integrations/builds/13163) failed f02f223159d853b5226bf1168e22e0998132b88d
* :green_heart: [Build #12918](https://buildkite.com/elastic/integrations/builds/12918) succeeded b590918d11f5887f48edad155903329931a1e120

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13230","number":13230,"commit":"6396f10d4566e0c765128440755c1a985ac103d8"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13227","number":13227,"commit":"6396f10d4566e0c765128440755c1a985ac103d8"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13183","number":13183,"commit":"6396f10d4566e0c765128440755c1a985ac103d8"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13167","number":13167,"commit":"6396f10d4566e0c765128440755c1a985ac103d8"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13164","number":13164,"commit":"6396f10d4566e0c765128440755c1a985ac103d8"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13163","number":13163,"commit":"f02f223159d853b5226bf1168e22e0998132b88d"}],"number":13230}
buildkite-pr-comment-->

2024-07-05 04:02 UTC, ishleenk17 commented
@harnish-elastic : The unwanted fields in ecs are still there in many Integrations. Eg: 
- name: host
   ecs: external
   
Can you please check it holistically for all integrations and take care of them

2024-07-05 08:12 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13286)
* Commit: 2a7dfbbe1793dc7dfabb46ae742961c9325c8987

### Failed CI Steps
* [Check integrations hadoop](https://buildkite.com/elastic/integrations/builds/13286#019081e0-64d1-4756-b289-0d5b4c2ca0fd)

### History
* :broken_heart: [Build #13230](https://buildkite.com/elastic/integrations/builds/13230) failed 6396f10d4566e0c765128440755c1a985ac103d8
* :broken_heart: [Build #13227](https://buildkite.com/elastic/integrations/builds/13227) failed 6396f10d4566e0c765128440755c1a985ac103d8
* :broken_heart: [Build #13183](https://buildkite.com/elastic/integrations/builds/13183) failed 6396f10d4566e0c765128440755c1a985ac103d8
* :broken_heart: [Build #13167](https://buildkite.com/elastic/integrations/builds/13167) failed 6396f10d4566e0c765128440755c1a985ac103d8
* :broken_heart: [Build #13164](https://buildkite.com/elastic/integrations/builds/13164) failed 6396f10d4566e0c765128440755c1a985ac103d8

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13286","number":13286,"commit":"2a7dfbbe1793dc7dfabb46ae742961c9325c8987"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13230","number":13230,"commit":"6396f10d4566e0c765128440755c1a985ac103d8"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13227","number":13227,"commit":"6396f10d4566e0c765128440755c1a985ac103d8"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13183","number":13183,"commit":"6396f10d4566e0c765128440755c1a985ac103d8"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13167","number":13167,"commit":"6396f10d4566e0c765128440755c1a985ac103d8"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13164","number":13164,"commit":"6396f10d4566e0c765128440755c1a985ac103d8"}],"number":13286}
buildkite-pr-comment-->

2024-07-08 04:26 UTC, harnish-elastic commented
/test

2024-07-08 04:42 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13347)
* Commit: 2a7dfbbe1793dc7dfabb46ae742961c9325c8987

### Failed CI Steps
* [Check integrations couchbase](https://buildkite.com/elastic/integrations/builds/13347#0190909a-ee6e-4a60-a91b-0c6256e03ebb)

### History
* :broken_heart: [Build #13286](https://buildkite.com/elastic/integrations/builds/13286) failed 2a7dfbbe1793dc7dfabb46ae742961c9325c8987
* :broken_heart: [Build #13230](https://buildkite.com/elastic/integrations/builds/13230) failed 6396f10d4566e0c765128440755c1a985ac103d8
* :broken_heart: [Build #13227](https://buildkite.com/elastic/integrations/builds/13227) failed 6396f10d4566e0c765128440755c1a985ac103d8
* :broken_heart: [Build #13183](https://buildkite.com/elastic/integrations/builds/13183) failed 6396f10d4566e0c765128440755c1a985ac103d8
* :broken_heart: [Build #13167](https://buildkite.com/elastic/integrations/builds/13167) failed 6396f10d4566e0c765128440755c1a985ac103d8

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13347","number":13347,"commit":"2a7dfbbe1793dc7dfabb46ae742961c9325c8987"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13286","number":13286,"commit":"2a7dfbbe1793dc7dfabb46ae742961c9325c8987"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13230","number":13230,"commit":"6396f10d4566e0c765128440755c1a985ac103d8"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13227","number":13227,"commit":"6396f10d4566e0c765128440755c1a985ac103d8"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13183","number":13183,"commit":"6396f10d4566e0c765128440755c1a985ac103d8"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13167","number":13167,"commit":"6396f10d4566e0c765128440755c1a985ac103d8"}],"number":13347}
buildkite-pr-comment-->

2024-07-08 05:07 UTC, harnish-elastic commented
> @harnish-elastic : The unwanted fields in ecs are still there in many Integrations. Eg:
> 
> * name: host
>   ecs: external
> 
> Can you please check it holistically for all integrations and take care of them

Checked all packages and updated. Thanks!

2024-07-08 09:38 UTC, harnish-elastic commented
Reverted changes for Hadoop package due to system tests failure. Raised separate [PR](https://github.com/elastic/integrations/pull/10407) for Hadoop.

2024-07-08 10:01 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13354)
* Commit: dd18efbc60228963ca93fbcbadb89b36eeac0f6c

### History
* :broken_heart: [Build #13347](https://buildkite.com/elastic/integrations/builds/13347) failed 2a7dfbbe1793dc7dfabb46ae742961c9325c8987
* :broken_heart: [Build #13286](https://buildkite.com/elastic/integrations/builds/13286) failed 2a7dfbbe1793dc7dfabb46ae742961c9325c8987
* :broken_heart: [Build #13230](https://buildkite.com/elastic/integrations/builds/13230) failed 6396f10d4566e0c765128440755c1a985ac103d8
* :broken_heart: [Build #13227](https://buildkite.com/elastic/integrations/builds/13227) failed 6396f10d4566e0c765128440755c1a985ac103d8
* :broken_heart: [Build #13183](https://buildkite.com/elastic/integrations/builds/13183) failed 6396f10d4566e0c765128440755c1a985ac103d8

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13354","number":13354,"commit":"dd18efbc60228963ca93fbcbadb89b36eeac0f6c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13347","number":13347,"commit":"2a7dfbbe1793dc7dfabb46ae742961c9325c8987"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13286","number":13286,"commit":"2a7dfbbe1793dc7dfabb46ae742961c9325c8987"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13230","number":13230,"commit":"6396f10d4566e0c765128440755c1a985ac103d8"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13227","number":13227,"commit":"6396f10d4566e0c765128440755c1a985ac103d8"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13183","number":13183,"commit":"6396f10d4566e0c765128440755c1a985ac103d8"}],"number":13354}
buildkite-pr-comment-->

2024-07-08 16:37 UTC, ishleenk17 approved these changes
Looks good!

2024-07-09 05:08 UTC, harnish-elastic commented
> Looks good! Please resolve the conflict, we can merge then.

Resolved!

2024-07-09 05:19 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13391)
* Commit: 0efb54258091c4f32f386605a9433aad2097e558

### Failed CI Steps
* [Check integrations couchbase](https://buildkite.com/elastic/integrations/builds/13391#019095e6-1f92-413a-a98f-4018c1f33673)

### History
* :green_heart: [Build #13354](https://buildkite.com/elastic/integrations/builds/13354) succeeded dd18efbc60228963ca93fbcbadb89b36eeac0f6c
* :broken_heart: [Build #13347](https://buildkite.com/elastic/integrations/builds/13347) failed 2a7dfbbe1793dc7dfabb46ae742961c9325c8987
* :broken_heart: [Build #13286](https://buildkite.com/elastic/integrations/builds/13286) failed 2a7dfbbe1793dc7dfabb46ae742961c9325c8987
* :broken_heart: [Build #13230](https://buildkite.com/elastic/integrations/builds/13230) failed 6396f10d4566e0c765128440755c1a985ac103d8
* :broken_heart: [Build #13227](https://buildkite.com/elastic/integrations/builds/13227) failed 6396f10d4566e0c765128440755c1a985ac103d8
* :broken_heart: [Build #13183](https://buildkite.com/elastic/integrations/builds/13183) failed 6396f10d4566e0c765128440755c1a985ac103d8

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13391","number":13391,"commit":"0efb54258091c4f32f386605a9433aad2097e558"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13354","number":13354,"commit":"dd18efbc60228963ca93fbcbadb89b36eeac0f6c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13347","number":13347,"commit":"2a7dfbbe1793dc7dfabb46ae742961c9325c8987"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13286","number":13286,"commit":"2a7dfbbe1793dc7dfabb46ae742961c9325c8987"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13230","number":13230,"commit":"6396f10d4566e0c765128440755c1a985ac103d8"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13227","number":13227,"commit":"6396f10d4566e0c765128440755c1a985ac103d8"}],"number":13391}
buildkite-pr-comment-->

2024-07-09 05:23 UTC, harnish-elastic commented
/test

2024-07-09 06:03 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13392)
* Commit: 0efb54258091c4f32f386605a9433aad2097e558

### History
* :broken_heart: [Build #13391](https://buildkite.com/elastic/integrations/builds/13391) failed 0efb54258091c4f32f386605a9433aad2097e558
* :green_heart: [Build #13354](https://buildkite.com/elastic/integrations/builds/13354) succeeded dd18efbc60228963ca93fbcbadb89b36eeac0f6c
* :broken_heart: [Build #13347](https://buildkite.com/elastic/integrations/builds/13347) failed 2a7dfbbe1793dc7dfabb46ae742961c9325c8987
* :broken_heart: [Build #13286](https://buildkite.com/elastic/integrations/builds/13286) failed 2a7dfbbe1793dc7dfabb46ae742961c9325c8987
* :broken_heart: [Build #13230](https://buildkite.com/elastic/integrations/builds/13230) failed 6396f10d4566e0c765128440755c1a985ac103d8
* :broken_heart: [Build #13227](https://buildkite.com/elastic/integrations/builds/13227) failed 6396f10d4566e0c765128440755c1a985ac103d8

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13392","number":13392,"commit":"0efb54258091c4f32f386605a9433aad2097e558"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13391","number":13391,"commit":"0efb54258091c4f32f386605a9433aad2097e558"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13354","number":13354,"commit":"dd18efbc60228963ca93fbcbadb89b36eeac0f6c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13347","number":13347,"commit":"2a7dfbbe1793dc7dfabb46ae742961c9325c8987"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13286","number":13286,"commit":"2a7dfbbe1793dc7dfabb46ae742961c9325c8987"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13230","number":13230,"commit":"6396f10d4566e0c765128440755c1a985ac103d8"}],"number":13392}
buildkite-pr-comment-->

2024-07-09 06:43 UTC, ishleenk17 commented
@elastic/sec-linux-platform @elastic/sec-windows-platform : Waiting for the code owner approvals here. Please check

2024-07-09 11:18 UTC, intxgo approved these changes
LGTM, though I'm not 100% sure if I reviewed all what I should have reviewed. The PR is too big to load on GitHub. The only way to review it was through VS Code.

2024-07-09 11:37 UTC, merged

2024-07-09 11:56 UTC, elasticmachine commented
Package activemq - 1.4.0 containing this change is available at https://epr.elastic.co/search?package=activemq

2024-07-09 11:56 UTC, elasticmachine commented
Package airflow - 0.9.0 containing this change is available at https://epr.elastic.co/search?package=airflow

2024-07-09 11:56 UTC, elasticmachine commented
Package apache_spark - 1.2.0 containing this change is available at https://epr.elastic.co/search?package=apache_spark

2024-07-09 11:56 UTC, elasticmachine commented
Package apache_tomcat - 1.7.0 containing this change is available at https://epr.elastic.co/search?package=apache_tomcat

2024-07-09 11:57 UTC, elasticmachine commented
Package awsfargate - 1.1.0 containing this change is available at https://epr.elastic.co/search?package=awsfargate

2024-07-09 11:57 UTC, elasticmachine commented
Package azure_app_service - 0.4.0 containing this change is available at https://epr.elastic.co/search?package=azure_app_service

2024-07-09 11:57 UTC, elasticmachine commented
Package azure_application_insights - 1.6.0 containing this change is available at https://epr.elastic.co/search?package=azure_application_insights

2024-07-09 11:57 UTC, elasticmachine commented
Package azure_billing - 1.6.0 containing this change is available at https://epr.elastic.co/search?package=azure_billing

2024-07-09 11:57 UTC, elasticmachine commented
Package azure_functions - 0.6.0 containing this change is available at https://epr.elastic.co/search?package=azure_functions

2024-07-09 11:57 UTC, elasticmachine commented
Package azure_openai - 1.1.0 containing this change is available at https://epr.elastic.co/search?package=azure_openai

2024-07-09 11:57 UTC, elasticmachine commented
Package ceph - 1.6.0 containing this change is available at https://epr.elastic.co/search?package=ceph

2024-07-09 11:57 UTC, elasticmachine commented
Package citrix_adc - 1.7.0 containing this change is available at https://epr.elastic.co/search?package=citrix_adc

2024-07-09 11:57 UTC, elasticmachine commented
Package coredns - 0.8.0 containing this change is available at https://epr.elastic.co/search?package=coredns

2024-07-09 11:57 UTC, elasticmachine commented
Package couchbase - 1.7.0 containing this change is available at https://epr.elastic.co/search?package=couchbase

2024-07-09 11:57 UTC, elasticmachine commented
Package couchdb - 1.3.0 containing this change is available at https://epr.elastic.co/search?package=couchdb

2024-07-09 11:57 UTC, elasticmachine commented
Package etcd - 1.2.0 containing this change is available at https://epr.elastic.co/search?package=etcd

2024-07-09 11:57 UTC, elasticmachine commented
Package golang - 1.6.0 containing this change is available at https://epr.elastic.co/search?package=golang

2024-07-09 11:57 UTC, elasticmachine commented
Package haproxy - 1.13.0 containing this change is available at https://epr.elastic.co/search?package=haproxy

2024-07-09 11:57 UTC, elasticmachine commented
Package ibmmq - 1.4.0 containing this change is available at https://epr.elastic.co/search?package=ibmmq

2024-07-09 11:57 UTC, elasticmachine commented
Package iis - 1.20.0 containing this change is available at https://epr.elastic.co/search?package=iis

2024-07-09 11:57 UTC, elasticmachine commented
Package influxdb - 0.9.0 containing this change is available at https://epr.elastic.co/search?package=influxdb

2024-07-09 11:57 UTC, elasticmachine commented
Package jolokia - 0.5.0 containing this change is available at https://epr.elastic.co/search?package=jolokia

2024-07-09 11:57 UTC, elasticmachine commented
Package kafka - 1.15.0 containing this change is available at https://epr.elastic.co/search?package=kafka

2024-07-09 11:57 UTC, elasticmachine commented
Package kafka_log - 1.7.0 containing this change is available at https://epr.elastic.co/search?package=kafka_log

2024-07-09 11:57 UTC, elasticmachine commented
Package microsoft_sqlserver - 2.7.0 containing this change is available at https://epr.elastic.co/search?package=microsoft_sqlserver

2024-07-09 11:57 UTC, elasticmachine commented
Package mongodb - 1.15.0 containing this change is available at https://epr.elastic.co/search?package=mongodb

2024-07-09 11:57 UTC, elasticmachine commented
Package mysql - 1.22.0 containing this change is available at https://epr.elastic.co/search?package=mysql

2024-07-09 11:57 UTC, elasticmachine commented
Package nagios_xi - 1.4.0 containing this change is available at https://epr.elastic.co/search?package=nagios_xi

2024-07-09 11:57 UTC, elasticmachine commented
Package nginx - 1.22.0 containing this change is available at https://epr.elastic.co/search?package=nginx

2024-07-09 11:57 UTC, elasticmachine commented
Package oracle - 1.27.0 containing this change is available at https://epr.elastic.co/search?package=oracle

2024-07-09 11:57 UTC, elasticmachine commented
Package php_fpm - 1.4.0 containing this change is available at https://epr.elastic.co/search?package=php_fpm

2024-07-09 11:57 UTC, elasticmachine commented
Package postgresql - 1.22.0 containing this change is available at https://epr.elastic.co/search?package=postgresql

2024-07-09 11:57 UTC, elasticmachine commented
Package prometheus_input - 0.5.0 containing this change is available at https://epr.elastic.co/search?package=prometheus_input

2024-07-09 11:57 UTC, elasticmachine commented
Package redis - 1.17.0 containing this change is available at https://epr.elastic.co/search?package=redis

2024-07-09 11:57 UTC, elasticmachine commented
Package redisenterprise - 0.10.0 containing this change is available at https://epr.elastic.co/search?package=redisenterprise

2024-07-09 11:57 UTC, elasticmachine commented
Package system - 1.59.0 containing this change is available at https://epr.elastic.co/search?package=system

2024-07-09 11:57 UTC, elasticmachine commented
Package tomcat - 1.11.0 containing this change is available at https://epr.elastic.co/search?package=tomcat

2024-07-09 11:57 UTC, elasticmachine commented
Package traefik - 2.2.0 containing this change is available at https://epr.elastic.co/search?package=traefik

2024-07-09 11:57 UTC, elasticmachine commented
Package vsphere - 1.13.0 containing this change is available at https://epr.elastic.co/search?package=vsphere

2024-07-09 11:57 UTC, elasticmachine commented
Package websphere_application_server - 1.5.0 containing this change is available at https://epr.elastic.co/search?package=websphere_application_server

2024-07-09 11:57 UTC, elasticmachine commented
Package zookeeper - 1.12.0 containing this change is available at https://epr.elastic.co/search?package=zookeeper