[O11y] Migrate infraobs packages to ecs@mappings
elastic/integrations pull request #10171
Opened 2024-06-18 05:32 UTC by harnish-elastic

- Enhancement

## Proposed commit message

Migration performed using ecs-update. Minor manual changes are performed.
- event.category or event.type is expecting value as an array instead of string. Hence provided the value as an array. 
- generated pipeline and system tests.
- If the package is containing kibana version configuration as below,

  ```
  conditions:
  kibana.version: "^8.10.0"
  ```
  Updated these configuration to, 
  ```
  conditions:
  kibana:
    version: "^8.10.0"
  ```

Command

```
  go run github.com/andrewkroh/go-examples/ecs-update@f7c19f8f3fa105fe1d869ed34f4d6c76c75bce2c \
    -ecs-version=8.11.0 \
    -ecs-git-ref=v8.11.0 \
    -fields-yml-drop-ecs \
    -kibana-version=^8.13.0 \
    -drop-import-mappings \
    -pr=10135 \
    -owner=elastic/security-service-integrations \
    packages/*
```

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

2024-06-18 05:36 UTC, efd6 commented
s/10135/10171/ in PR description. Also suggest using sha 014b35dfe4c9832b51e7c909a39a48257d6a005d for the tool; f7c19f8f3fa105fe1d869ed34f4d6c76c75bce2c is out of date with some fixes.

2024-06-18 05:42 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12594)
* Commit: 3a341f26017ab4dd24c520ec65dd5dae9ea8e9c7

### Failed CI Steps
* [Check integrations stan](https://buildkite.com/elastic/integrations/builds/12594#019029d9-e5ce-4647-9680-51a08aec43c5)

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12594","number":12594,"commit":"3a341f26017ab4dd24c520ec65dd5dae9ea8e9c7"}],"number":12594}
buildkite-pr-comment-->

2024-06-18 05:45 UTC, harnish-elastic commented
> s/10135/10171/ in PR description. Also suggest using sha 014b35dfe4c9832b51e7c909a39a48257d6a005d for the tool; f7c19f8f3fa105fe1d869ed34f4d6c76c75bce2c is out of date with some fixes.
> 
> To fix up issues the best thing to do is reset --hard origin/main and re-run the command with the correct values, rather than polishing the PR.

Cool, let me do that. Thanks!

2024-06-18 06:02 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-06-18 06:45 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12597)
* Commit: c98e090029768d0f6c287cbcc83652b16d2f7243

### Failed CI Steps
* [Check integrations stan](https://buildkite.com/elastic/integrations/builds/12597#01902a14-05cf-4fbc-9295-46ee01b3fc1d)

### History
* :broken_heart: [Build #12594](https://buildkite.com/elastic/integrations/builds/12594) failed 3a341f26017ab4dd24c520ec65dd5dae9ea8e9c7

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12597","number":12597,"commit":"c98e090029768d0f6c287cbcc83652b16d2f7243"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12594","number":12594,"commit":"3a341f26017ab4dd24c520ec65dd5dae9ea8e9c7"}],"number":12597}
buildkite-pr-comment-->

2024-06-18 07:01 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12599)
* Commit: 53365dc1ef2aaeab0176733741159803e46ac519

### Failed CI Steps
* [Check integrations stan](https://buildkite.com/elastic/integrations/builds/12599#01902a22-f50e-45dd-a28d-894377ac966f)

### History
* :broken_heart: [Build #12597](https://buildkite.com/elastic/integrations/builds/12597) failed c98e090029768d0f6c287cbcc83652b16d2f7243
* :broken_heart: [Build #12594](https://buildkite.com/elastic/integrations/builds/12594) failed 3a341f26017ab4dd24c520ec65dd5dae9ea8e9c7

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12599","number":12599,"commit":"53365dc1ef2aaeab0176733741159803e46ac519"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12597","number":12597,"commit":"c98e090029768d0f6c287cbcc83652b16d2f7243"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12594","number":12594,"commit":"3a341f26017ab4dd24c520ec65dd5dae9ea8e9c7"}],"number":12599}
buildkite-pr-comment-->

2024-06-18 07:31 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12603)
* Commit: dc6585f89177ae09248bb5a665564f434612274f

### Failed CI Steps
* [Check integrations stan](https://buildkite.com/elastic/integrations/builds/12603#01902a3d-f0ed-460d-b964-fbc849e4b9ab)

### History
* :broken_heart: [Build #12599](https://buildkite.com/elastic/integrations/builds/12599) failed 53365dc1ef2aaeab0176733741159803e46ac519
* :broken_heart: [Build #12597](https://buildkite.com/elastic/integrations/builds/12597) failed c98e090029768d0f6c287cbcc83652b16d2f7243
* :broken_heart: [Build #12594](https://buildkite.com/elastic/integrations/builds/12594) failed 3a341f26017ab4dd24c520ec65dd5dae9ea8e9c7

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12603","number":12603,"commit":"dc6585f89177ae09248bb5a665564f434612274f"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12599","number":12599,"commit":"53365dc1ef2aaeab0176733741159803e46ac519"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12597","number":12597,"commit":"c98e090029768d0f6c287cbcc83652b16d2f7243"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12594","number":12594,"commit":"3a341f26017ab4dd24c520ec65dd5dae9ea8e9c7"}],"number":12603}
buildkite-pr-comment-->

2024-06-18 10:23 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12612)
* Commit: fc903e7cac090a6af38aed9c829b55bde62179f8

### Failed CI Steps
* [Check integrations stan](https://buildkite.com/elastic/integrations/builds/12612#01902ad8-8367-4871-8a85-bc4a441575fc)

### History
* :broken_heart: [Build #12603](https://buildkite.com/elastic/integrations/builds/12603) failed dc6585f89177ae09248bb5a665564f434612274f
* :broken_heart: [Build #12599](https://buildkite.com/elastic/integrations/builds/12599) failed 53365dc1ef2aaeab0176733741159803e46ac519
* :broken_heart: [Build #12597](https://buildkite.com/elastic/integrations/builds/12597) failed c98e090029768d0f6c287cbcc83652b16d2f7243
* :broken_heart: [Build #12594](https://buildkite.com/elastic/integrations/builds/12594) failed 3a341f26017ab4dd24c520ec65dd5dae9ea8e9c7

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12612","number":12612,"commit":"fc903e7cac090a6af38aed9c829b55bde62179f8"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12603","number":12603,"commit":"dc6585f89177ae09248bb5a665564f434612274f"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12599","number":12599,"commit":"53365dc1ef2aaeab0176733741159803e46ac519"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12597","number":12597,"commit":"c98e090029768d0f6c287cbcc83652b16d2f7243"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12594","number":12594,"commit":"3a341f26017ab4dd24c520ec65dd5dae9ea8e9c7"}],"number":12612}
buildkite-pr-comment-->

2024-06-18 11:19 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12616)
* Commit: 2a437daca312b134ecc0f786c64d728f4d9d1720

### History
* :broken_heart: [Build #12612](https://buildkite.com/elastic/integrations/builds/12612) failed fc903e7cac090a6af38aed9c829b55bde62179f8
* :broken_heart: [Build #12603](https://buildkite.com/elastic/integrations/builds/12603) failed dc6585f89177ae09248bb5a665564f434612274f
* :broken_heart: [Build #12599](https://buildkite.com/elastic/integrations/builds/12599) failed 53365dc1ef2aaeab0176733741159803e46ac519
* :broken_heart: [Build #12597](https://buildkite.com/elastic/integrations/builds/12597) failed c98e090029768d0f6c287cbcc83652b16d2f7243
* :broken_heart: [Build #12594](https://buildkite.com/elastic/integrations/builds/12594) failed 3a341f26017ab4dd24c520ec65dd5dae9ea8e9c7

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12616","number":12616,"commit":"2a437daca312b134ecc0f786c64d728f4d9d1720"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12612","number":12612,"commit":"fc903e7cac090a6af38aed9c829b55bde62179f8"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12603","number":12603,"commit":"dc6585f89177ae09248bb5a665564f434612274f"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12599","number":12599,"commit":"53365dc1ef2aaeab0176733741159803e46ac519"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12597","number":12597,"commit":"c98e090029768d0f6c287cbcc83652b16d2f7243"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12594","number":12594,"commit":"3a341f26017ab4dd24c520ec65dd5dae9ea8e9c7"}],"number":12616}
buildkite-pr-comment-->

2024-06-19 06:59 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12656)
* Commit: d62e037f36b257d4882a6910aa08ed29f48d1f32

### History
* :green_heart: [Build #12616](https://buildkite.com/elastic/integrations/builds/12616) succeeded 2a437daca312b134ecc0f786c64d728f4d9d1720
* :broken_heart: [Build #12612](https://buildkite.com/elastic/integrations/builds/12612) failed fc903e7cac090a6af38aed9c829b55bde62179f8
* :broken_heart: [Build #12603](https://buildkite.com/elastic/integrations/builds/12603) failed dc6585f89177ae09248bb5a665564f434612274f
* :broken_heart: [Build #12599](https://buildkite.com/elastic/integrations/builds/12599) failed 53365dc1ef2aaeab0176733741159803e46ac519
* :broken_heart: [Build #12597](https://buildkite.com/elastic/integrations/builds/12597) failed c98e090029768d0f6c287cbcc83652b16d2f7243
* :broken_heart: [Build #12594](https://buildkite.com/elastic/integrations/builds/12594) failed 3a341f26017ab4dd24c520ec65dd5dae9ea8e9c7

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12656","number":12656,"commit":"d62e037f36b257d4882a6910aa08ed29f48d1f32"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12616","number":12616,"commit":"2a437daca312b134ecc0f786c64d728f4d9d1720"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12612","number":12612,"commit":"fc903e7cac090a6af38aed9c829b55bde62179f8"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12603","number":12603,"commit":"dc6585f89177ae09248bb5a665564f434612274f"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12599","number":12599,"commit":"53365dc1ef2aaeab0176733741159803e46ac519"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12597","number":12597,"commit":"c98e090029768d0f6c287cbcc83652b16d2f7243"}],"number":12656}
buildkite-pr-comment-->

2024-06-20 10:24 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12675)
* Commit: 917295be8d0e95e142d4d575321b69c8163a7b34

### History
* :green_heart: [Build #12656](https://buildkite.com/elastic/integrations/builds/12656) succeeded d62e037f36b257d4882a6910aa08ed29f48d1f32
* :green_heart: [Build #12616](https://buildkite.com/elastic/integrations/builds/12616) succeeded 2a437daca312b134ecc0f786c64d728f4d9d1720
* :broken_heart: [Build #12612](https://buildkite.com/elastic/integrations/builds/12612) failed fc903e7cac090a6af38aed9c829b55bde62179f8
* :broken_heart: [Build #12603](https://buildkite.com/elastic/integrations/builds/12603) failed dc6585f89177ae09248bb5a665564f434612274f
* :broken_heart: [Build #12599](https://buildkite.com/elastic/integrations/builds/12599) failed 53365dc1ef2aaeab0176733741159803e46ac519
* :broken_heart: [Build #12597](https://buildkite.com/elastic/integrations/builds/12597) failed c98e090029768d0f6c287cbcc83652b16d2f7243

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12675","number":12675,"commit":"917295be8d0e95e142d4d575321b69c8163a7b34"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12656","number":12656,"commit":"d62e037f36b257d4882a6910aa08ed29f48d1f32"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12616","number":12616,"commit":"2a437daca312b134ecc0f786c64d728f4d9d1720"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12612","number":12612,"commit":"fc903e7cac090a6af38aed9c829b55bde62179f8"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12603","number":12603,"commit":"dc6585f89177ae09248bb5a665564f434612274f"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12599","number":12599,"commit":"53365dc1ef2aaeab0176733741159803e46ac519"}],"number":12675}
buildkite-pr-comment-->

2024-06-24 11:32 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12764)
* Commit: 8570eadc421ecce624a98c5e57544b190a153335

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/12764#01904a03-d67d-4192-a274-d6d6403b18c8)

### History
* :green_heart: [Build #12675](https://buildkite.com/elastic/integrations/builds/12675) succeeded 917295be8d0e95e142d4d575321b69c8163a7b34
* :green_heart: [Build #12656](https://buildkite.com/elastic/integrations/builds/12656) succeeded d62e037f36b257d4882a6910aa08ed29f48d1f32
* :green_heart: [Build #12616](https://buildkite.com/elastic/integrations/builds/12616) succeeded 2a437daca312b134ecc0f786c64d728f4d9d1720
* :broken_heart: [Build #12612](https://buildkite.com/elastic/integrations/builds/12612) failed fc903e7cac090a6af38aed9c829b55bde62179f8
* :broken_heart: [Build #12603](https://buildkite.com/elastic/integrations/builds/12603) failed dc6585f89177ae09248bb5a665564f434612274f
* :broken_heart: [Build #12599](https://buildkite.com/elastic/integrations/builds/12599) failed 53365dc1ef2aaeab0176733741159803e46ac519

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12764","number":12764,"commit":"8570eadc421ecce624a98c5e57544b190a153335"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12675","number":12675,"commit":"917295be8d0e95e142d4d575321b69c8163a7b34"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12656","number":12656,"commit":"d62e037f36b257d4882a6910aa08ed29f48d1f32"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12616","number":12616,"commit":"2a437daca312b134ecc0f786c64d728f4d9d1720"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12612","number":12612,"commit":"fc903e7cac090a6af38aed9c829b55bde62179f8"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12603","number":12603,"commit":"dc6585f89177ae09248bb5a665564f434612274f"}],"number":12764}
buildkite-pr-comment-->

2024-06-24 12:39 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12768)
* Commit: 3701399383b0356324c8eb7451062010ed213cbb

### History
* :broken_heart: [Build #12764](https://buildkite.com/elastic/integrations/builds/12764) failed 8570eadc421ecce624a98c5e57544b190a153335
* :green_heart: [Build #12675](https://buildkite.com/elastic/integrations/builds/12675) succeeded 917295be8d0e95e142d4d575321b69c8163a7b34
* :green_heart: [Build #12656](https://buildkite.com/elastic/integrations/builds/12656) succeeded d62e037f36b257d4882a6910aa08ed29f48d1f32
* :green_heart: [Build #12616](https://buildkite.com/elastic/integrations/builds/12616) succeeded 2a437daca312b134ecc0f786c64d728f4d9d1720
* :broken_heart: [Build #12612](https://buildkite.com/elastic/integrations/builds/12612) failed fc903e7cac090a6af38aed9c829b55bde62179f8
* :broken_heart: [Build #12603](https://buildkite.com/elastic/integrations/builds/12603) failed dc6585f89177ae09248bb5a665564f434612274f

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12768","number":12768,"commit":"3701399383b0356324c8eb7451062010ed213cbb"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12764","number":12764,"commit":"8570eadc421ecce624a98c5e57544b190a153335"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12675","number":12675,"commit":"917295be8d0e95e142d4d575321b69c8163a7b34"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12656","number":12656,"commit":"d62e037f36b257d4882a6910aa08ed29f48d1f32"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12616","number":12616,"commit":"2a437daca312b134ecc0f786c64d728f4d9d1720"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12612","number":12612,"commit":"fc903e7cac090a6af38aed9c829b55bde62179f8"}],"number":12768}
buildkite-pr-comment-->

2024-06-25 07:18 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12805)
* Commit: 7eac098b7f7a1690f546e39c6fce52bc4c830627

### Failed CI Steps
* [Check integrations oracle_weblogic](https://buildkite.com/elastic/integrations/builds/12805#01904e3e-f144-4612-b94e-53e7b4de5822)

### History
* :green_heart: [Build #12768](https://buildkite.com/elastic/integrations/builds/12768) succeeded 3701399383b0356324c8eb7451062010ed213cbb
* :broken_heart: [Build #12764](https://buildkite.com/elastic/integrations/builds/12764) failed 8570eadc421ecce624a98c5e57544b190a153335
* :green_heart: [Build #12675](https://buildkite.com/elastic/integrations/builds/12675) succeeded 917295be8d0e95e142d4d575321b69c8163a7b34
* :green_heart: [Build #12656](https://buildkite.com/elastic/integrations/builds/12656) succeeded d62e037f36b257d4882a6910aa08ed29f48d1f32
* :green_heart: [Build #12616](https://buildkite.com/elastic/integrations/builds/12616) succeeded 2a437daca312b134ecc0f786c64d728f4d9d1720
* :broken_heart: [Build #12612](https://buildkite.com/elastic/integrations/builds/12612) failed fc903e7cac090a6af38aed9c829b55bde62179f8

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12805","number":12805,"commit":"7eac098b7f7a1690f546e39c6fce52bc4c830627"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12768","number":12768,"commit":"3701399383b0356324c8eb7451062010ed213cbb"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12764","number":12764,"commit":"8570eadc421ecce624a98c5e57544b190a153335"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12675","number":12675,"commit":"917295be8d0e95e142d4d575321b69c8163a7b34"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12656","number":12656,"commit":"d62e037f36b257d4882a6910aa08ed29f48d1f32"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12616","number":12616,"commit":"2a437daca312b134ecc0f786c64d728f4d9d1720"}],"number":12805}
buildkite-pr-comment-->

2024-06-25 09:55 UTC, harnish-elastic commented
/test

2024-06-25 10:25 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12822)
* Commit: 7eac098b7f7a1690f546e39c6fce52bc4c830627

### History
* :broken_heart: [Build #12805](https://buildkite.com/elastic/integrations/builds/12805) failed 7eac098b7f7a1690f546e39c6fce52bc4c830627
* :green_heart: [Build #12768](https://buildkite.com/elastic/integrations/builds/12768) succeeded 3701399383b0356324c8eb7451062010ed213cbb
* :broken_heart: [Build #12764](https://buildkite.com/elastic/integrations/builds/12764) failed 8570eadc421ecce624a98c5e57544b190a153335
* :green_heart: [Build #12675](https://buildkite.com/elastic/integrations/builds/12675) succeeded 917295be8d0e95e142d4d575321b69c8163a7b34
* :green_heart: [Build #12656](https://buildkite.com/elastic/integrations/builds/12656) succeeded d62e037f36b257d4882a6910aa08ed29f48d1f32

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12822","number":12822,"commit":"7eac098b7f7a1690f546e39c6fce52bc4c830627"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12805","number":12805,"commit":"7eac098b7f7a1690f546e39c6fce52bc4c830627"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12768","number":12768,"commit":"3701399383b0356324c8eb7451062010ed213cbb"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12764","number":12764,"commit":"8570eadc421ecce624a98c5e57544b190a153335"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12675","number":12675,"commit":"917295be8d0e95e142d4d575321b69c8163a7b34"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12656","number":12656,"commit":"d62e037f36b257d4882a6910aa08ed29f48d1f32"}],"number":12822}
buildkite-pr-comment-->

2024-06-26 12:01 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12919)
* Commit: 982c0cea6b4640a816164ca3870484b3281c1560

### History
* :green_heart: [Build #12822](https://buildkite.com/elastic/integrations/builds/12822) succeeded 7eac098b7f7a1690f546e39c6fce52bc4c830627
* :broken_heart: [Build #12805](https://buildkite.com/elastic/integrations/builds/12805) failed 7eac098b7f7a1690f546e39c6fce52bc4c830627
* :green_heart: [Build #12768](https://buildkite.com/elastic/integrations/builds/12768) succeeded 3701399383b0356324c8eb7451062010ed213cbb
* :broken_heart: [Build #12764](https://buildkite.com/elastic/integrations/builds/12764) failed 8570eadc421ecce624a98c5e57544b190a153335
* :green_heart: [Build #12675](https://buildkite.com/elastic/integrations/builds/12675) succeeded 917295be8d0e95e142d4d575321b69c8163a7b34
* :green_heart: [Build #12656](https://buildkite.com/elastic/integrations/builds/12656) succeeded d62e037f36b257d4882a6910aa08ed29f48d1f32

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12919","number":12919,"commit":"982c0cea6b4640a816164ca3870484b3281c1560"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12822","number":12822,"commit":"7eac098b7f7a1690f546e39c6fce52bc4c830627"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12805","number":12805,"commit":"7eac098b7f7a1690f546e39c6fce52bc4c830627"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12768","number":12768,"commit":"3701399383b0356324c8eb7451062010ed213cbb"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12764","number":12764,"commit":"8570eadc421ecce624a98c5e57544b190a153335"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12675","number":12675,"commit":"917295be8d0e95e142d4d575321b69c8163a7b34"}],"number":12919}
buildkite-pr-comment-->

2024-06-27 06:44 UTC, milan-elastic commented
@harnish-elastic Have we done the rigorous testing for a few of the TSDB packages to make sure there are no other issues we are running into?
Otherwise it looks good to me!

2024-06-27 06:48 UTC, harnish-elastic commented
> @harnish-elastic Have we done the rigorous testing for a few of the TSDB packages to make sure there are no other issues we are running into? Otherwise it looks good to me!

@milan-elastic Yes, we have done that. Let me attach testing in the PR!

2024-06-27 08:03 UTC, milan-elastic approved these changes

2024-07-02 10:23 UTC, niraj-elastic requested changes

2024-07-02 10:23 UTC, niraj-elastic commented on packages/oracle_weblogic/data_stream/access/elasticsearch/ingest_pipeline/default.yml
> +    value: ["network"]
@harnish-elastic Can you please explain this change?

2024-07-02 10:47 UTC, harnish-elastic commented on packages/oracle_weblogic/data_stream/access/elasticsearch/ingest_pipeline/default.yml
> +    value: ["network"]
The change was related to event.category will not be longer support the value `log`. So based on data stream's logs, the `network` value suits. Hence updated the value!

2024-07-05 04:15 UTC, ishleenk17 commented on packages/oracle_weblogic/data_stream/access/elasticsearch/ingest_pipeline/default.yml
> +    value: ["network"]
Can you share what the exact error here and since when has this category been removed ?

2024-07-05 04:15 UTC, ishleenk17 commented on packages/rabbitmq/data_stream/exchange/fields/ecs.yml
>    name: user
Is this a valid field ?

2024-07-05 04:43 UTC, harnish-elastic commented on packages/rabbitmq/data_stream/exchange/fields/ecs.yml
>    name: user
Nope, this is not a valid field. Let me remove from all the PRs!

2024-07-05 05:06 UTC, harnish-elastic commented on packages/oracle_weblogic/data_stream/access/elasticsearch/ingest_pipeline/default.yml
> +    value: ["network"]
oracle_weblogic/access test-access.log:
[0] parsing field value failed: field "event.category"'s value "log" is not one of the allowed values (api, authentication, configuration, database, driver, email, file, host, iam, intrusion_detection, library, malware, network, package, process, registry, session, threat, vulnerability, web)

2024-07-05 05:23 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13274)
* Commit: 21ba3c976d3ddf43cc522ad958f02206eb3c4574

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/13274#01908157-dbb1-47fa-84c1-2d3d6ed703a8)

### History
* :green_heart: [Build #12919](https://buildkite.com/elastic/integrations/builds/12919) succeeded 982c0cea6b4640a816164ca3870484b3281c1560
* :green_heart: [Build #12822](https://buildkite.com/elastic/integrations/builds/12822) succeeded 7eac098b7f7a1690f546e39c6fce52bc4c830627
* :broken_heart: [Build #12805](https://buildkite.com/elastic/integrations/builds/12805) failed 7eac098b7f7a1690f546e39c6fce52bc4c830627
* :green_heart: [Build #12768](https://buildkite.com/elastic/integrations/builds/12768) succeeded 3701399383b0356324c8eb7451062010ed213cbb
* :broken_heart: [Build #12764](https://buildkite.com/elastic/integrations/builds/12764) failed 8570eadc421ecce624a98c5e57544b190a153335
* :green_heart: [Build #12675](https://buildkite.com/elastic/integrations/builds/12675) succeeded 917295be8d0e95e142d4d575321b69c8163a7b34

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13274","number":13274,"commit":"21ba3c976d3ddf43cc522ad958f02206eb3c4574"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12919","number":12919,"commit":"982c0cea6b4640a816164ca3870484b3281c1560"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12822","number":12822,"commit":"7eac098b7f7a1690f546e39c6fce52bc4c830627"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12805","number":12805,"commit":"7eac098b7f7a1690f546e39c6fce52bc4c830627"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12768","number":12768,"commit":"3701399383b0356324c8eb7451062010ed213cbb"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12764","number":12764,"commit":"8570eadc421ecce624a98c5e57544b190a153335"}],"number":13274}
buildkite-pr-comment-->

2024-07-05 05:57 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13276)
* Commit: 2236426e2a9eee943577610a427bfdecb9882016

### History
* :broken_heart: [Build #13274](https://buildkite.com/elastic/integrations/builds/13274) failed 21ba3c976d3ddf43cc522ad958f02206eb3c4574
* :green_heart: [Build #12919](https://buildkite.com/elastic/integrations/builds/12919) succeeded 982c0cea6b4640a816164ca3870484b3281c1560
* :green_heart: [Build #12822](https://buildkite.com/elastic/integrations/builds/12822) succeeded 7eac098b7f7a1690f546e39c6fce52bc4c830627
* :broken_heart: [Build #12805](https://buildkite.com/elastic/integrations/builds/12805) failed 7eac098b7f7a1690f546e39c6fce52bc4c830627
* :green_heart: [Build #12768](https://buildkite.com/elastic/integrations/builds/12768) succeeded 3701399383b0356324c8eb7451062010ed213cbb
* :broken_heart: [Build #12764](https://buildkite.com/elastic/integrations/builds/12764) failed 8570eadc421ecce624a98c5e57544b190a153335

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13276","number":13276,"commit":"2236426e2a9eee943577610a427bfdecb9882016"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13274","number":13274,"commit":"21ba3c976d3ddf43cc522ad958f02206eb3c4574"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12919","number":12919,"commit":"982c0cea6b4640a816164ca3870484b3281c1560"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12822","number":12822,"commit":"7eac098b7f7a1690f546e39c6fce52bc4c830627"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12805","number":12805,"commit":"7eac098b7f7a1690f546e39c6fce52bc4c830627"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12768","number":12768,"commit":"3701399383b0356324c8eb7451062010ed213cbb"}],"number":13276}
buildkite-pr-comment-->

2024-07-05 12:52 UTC, agithomas commented on packages/oracle_weblogic/data_stream/admin_server/elasticsearch/ingest_pipeline/default.yml
> +    value: ["iam"]
When i look at the attached screenshot of this [PR](https://github.com/elastic/integrations/pull/3066), i do not think that we must limit the event.category to `iam` only.

2024-07-05 14:07 UTC, zmoog approved these changes

2024-07-05 14:19 UTC, tetianakravchenko approved these changes
prometheus.remote_write - LGTM!

2024-07-08 03:56 UTC, ishleenk17 commented on packages/oracle_weblogic/data_stream/admin_server/elasticsearch/ingest_pipeline/default.yml
> +    value: ["iam"]
To unblock this PR, lets keep in "iam" for now.
If we come to a consensus that we need to add more categories, we can do that later as we are appending here.

2024-07-08 03:56 UTC, ishleenk17 approved these changes
Looks good!

2024-07-08 06:38 UTC, niraj-elastic approved these changes
LGTM

2024-07-08 10:03 UTC, merged

2024-07-08 10:18 UTC, elasticmachine commented
Package cassandra - 1.14.0 containing this change is available at https://epr.elastic.co/search?package=cassandra

2024-07-08 10:18 UTC, elasticmachine commented
Package nats - 1.7.0 containing this change is available at https://epr.elastic.co/search?package=nats

2024-07-08 10:18 UTC, elasticmachine commented
Package oracle_weblogic - 1.7.0 containing this change is available at https://epr.elastic.co/search?package=oracle_weblogic

2024-07-08 10:18 UTC, elasticmachine commented
Package prometheus - 1.18.0 containing this change is available at https://epr.elastic.co/search?package=prometheus

2024-07-08 10:18 UTC, elasticmachine commented
Package rabbitmq - 1.15.0 containing this change is available at https://epr.elastic.co/search?package=rabbitmq

2024-07-08 10:18 UTC, elasticmachine commented
Package spring_boot - 1.6.0 containing this change is available at https://epr.elastic.co/search?package=spring_boot

2024-07-08 10:18 UTC, elasticmachine commented
Package sql - 0.5.0 containing this change is available at https://epr.elastic.co/search?package=sql

2024-07-08 10:18 UTC, elasticmachine commented
Package stan - 1.7.0 containing this change is available at https://epr.elastic.co/search?package=stan

2024-07-08 10:18 UTC, elasticmachine commented
Package statsd_input - 0.4.0 containing this change is available at https://epr.elastic.co/search?package=statsd_input