[windows] windows_defender_intial - draft
elastic/integrations pull request #10207
Opened 2024-06-21 01:59 UTC by nicpenning

- Enhancement

Add Windows Defender data stream - more details to come.
## Proposed commit message

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## How to test this PR locally

## Related issues

- 

## Screenshots

2024-06-21 08:52 UTC, nicpenning commented
Have about 28 of these: /integrations/build/packages/windows-1.46.0.zip/data_stream/windows_defender/fields/winlog.yml" is invalid: field 0.fields.4.fields.111.name: Does not match pattern '^[\-*_\/@A-Za-z0-9]+(\.[\-*_\/@A-Za-z0-9]+)*$'

Since there are quite a few fields with spaces. Pipelines will need to be created to handle these since you cannot have spaces in field names for an integration, even though you can have spaces in fields names in Elasticsearch in general.

![image](https://github.com/elastic/integrations/assets/5582679/0bd6cfe5-1424-463e-bf61-031bc22666bb)

2024-06-21 08:54 UTC, elasticmachine commented
Pinging @elastic/sec-windows-platform (Team:Security-Windows Platform)

2024-06-21 08:56 UTC, nicpenning commented
If anyone knows how to rename a field in a pipeline with spaces I would gladly hear it.

I would like to do something like this, but unsure if it will work.
```
- rename:
  field: "winlog.eventdata.AS security intelligence creation time"
  target_field: "winlog.eventdata.AS_security_intelligence_creation_time"
  ignore_failure: true
  ignore_missing: true
  if: "winlog.eventdata.AS security intelligence creation time" != null
```
Please advise, as this is nearly ready for testing - The spaces in field names is the remaining cleanup item before tests can begin.

2024-06-21 09:47 UTC, elasticmachine commented
Pinging @elastic/elastic-agent-data-plane (Team:Elastic-Agent-Data-Plane)

2024-06-21 13:21 UTC, nicpenning commented
Replaced spaces with _ for field names, and looks good.

Ready to test!

2024-06-21 14:14 UTC, belimawr approved these changes
LGMT.

Regarding remove the spaces from field names, you can also use the [script processor](https://www.elastic.co/guide/en/elasticsearch/reference/current/script-processor.html) that allows you to freely manipulate the data and have a generic solution instead of hardcoding all field names.

Filebeat also has got a [script processor](https://www.elastic.co/guide/en/beats/filebeat/current/processor-script.html) in case you want that done by Filebeat instead of ES.

2024-06-21 14:52 UTC, leehinman requested changes

2024-06-21 14:52 UTC, leehinman commented on packages/windows/data_stream/windows_defender/elasticsearch/ingest_pipeline/default.yml
> +  - rename:
How sure are we that every field that has a " " in the name is listed?  I'd much rather see a javascript processor that does it for every field or a change to the xml decoding so we know that it will happen for every field.

2024-06-21 14:52 UTC, leehinman commented on packages/windows/data_stream/windows_defender/agent/stream/winlog.yml.hbs
> +{{else}}
does this else match the `#if tags.length` or the `#if preserve_original_event`?  Is there anything we can do to clarify?

2024-06-21 17:12 UTC, nicpenning commented on packages/windows/data_stream/windows_defender/elasticsearch/ingest_pipeline/default.yml
> +  - rename:
Not sure at all :)

Any script that can do this would be great.  A real pain to have all of these rename processors. If a anyone has an example I can use, I will add it in.

2024-06-21 17:14 UTC, nicpenning commented on packages/windows/data_stream/windows_defender/agent/stream/winlog.yml.hbs
> +{{else}}
Great questions. I am unsure because I replicated all of the other windows integrations to do this. It works but I don't understand the code without any spacing.

Open to ideas?

I have 2 other PRs that correct all of these do they actually work.  (Preserve Original Event PRs).

2024-06-21 17:56 UTC, nicpenning commented
@leehinman , @belimawr 

Maybe something like this? Works, but unsure if efficient.

Script processor for ingest pipeline. Doing this at the agent level would be more efficient, but unsure how to bake this into the integration on the filebeat side (the context of how this code operates).
```
if (ctx.winlog?.event_data != null) {
  Map eventData = ctx.winlog.event_data;
  Map newEventData = new HashMap();
  for (entry in eventData.entrySet()) {
    String newKey = entry.getKey().replace(" ", "_");
    newEventData.put(newKey, entry.getValue());
  }
  ctx.winlog.event_data = newEventData;
}
```
With this conditional as well
![image](https://github.com/elastic/integrations/assets/5582679/f9d73f45-24a3-4093-b899-10d5b9cd5eaa)

2024-06-21 21:42 UTC, nicpenning commented on packages/windows/data_stream/windows_defender/elasticsearch/ingest_pipeline/default.yml
> +  - rename:
I think I figured it out, please advise. Went ahead and made this client side.

2024-06-21 21:43 UTC, nicpenning commented
Moved processing to client side, please review!

2024-06-22 16:04 UTC, nicpenning commented on packages/windows/data_stream/windows_defender/agent/stream/winlog.yml.hbs
> +{{else}}
For example: https://github.com/elastic/integrations/pull/10197

Please take a look at that PR as it uses the same technique for preserve original event that is based off of this PR: https://github.com/elastic/integrations/pull/9426

2024-06-24 15:30 UTC, belimawr reviewed
LGTM.

@nicpenning is there an easy way to test this PR? How can I generate the necessary data to test it?

I really would like to test this JS script, just to be on the safe side.

2024-06-24 17:48 UTC, nicpenning commented
I tested locally on my device and it seemed to work.

I do dev on Windows so I exposed my containerized stack to my localhost and installed an agent on my windows host and pointed to fleet:8220 using 127.0.0.1:8220 in the fleet settings (new fleet server) and elasticsearch:9200 using 127.0.0.1:9200 (new elasticsearch output) in the output options

2024-06-25 20:54 UTC, leehinman commented on packages/windows/data_stream/windows_defender/agent/stream/winlog.yml.hbs
> +{{else}}
running this around in my head.  This should avoid the ambiguous else statement, but I haven't tested it.  I really wish handlebars supported && and ||.

```
# if we have tags defined add the tags object
{{#if tags.length}}
tags:
{{/if}}

# if tags aren't defined but preserver original is, add tags object
{{#unless tags.length}}
{{#if preserve_original_event}}
tags:
{{/if}}
{{/unless}}

# if tags are defined, add them
{{#if tags.length}}
{{#each tags as |tag|}}
  - {{tag}}
{{/each}}
{{/if}}

# if preserver original event is defined add that tag
{{#if preserve_original_event}}
  - preserve_original_event
{{/if}}

```

2024-06-25 21:02 UTC, leehinman commented on packages/windows/data_stream/windows_defender/agent/stream/winlog.yml.hbs
> +          event.Put("winlog.event_data", newEventData);
That should work, but it allocates a whole new object and copies all the data.  Have you tried mutating the object in place?

2024-06-25 22:15 UTC, nicpenning commented on packages/windows/data_stream/windows_defender/agent/stream/winlog.yml.hbs
> +{{else}}
I will give it a go!

2024-06-26 00:35 UTC, nicpenning commented on packages/windows/data_stream/windows_defender/agent/stream/winlog.yml.hbs
> +          event.Put("winlog.event_data", newEventData);
It does work. I am not sure what it looks like mutating in place.  ChatGPT assisted here. If you have a more efficient way to do this then I can happily test.

2024-06-26 02:11 UTC, nicpenning commented
Had to rebase. Ready for tests here. All tests passed locally. I added in @leehinman code snippet above.

2024-06-26 02:12 UTC, nicpenning commented on packages/windows/data_stream/windows_defender/agent/stream/winlog.yml.hbs
> +{{else}}
Added.  Please test.

2024-06-26 15:11 UTC, leehinman approved these changes
If the javascript processing on the `event_data` ends up being an issue, I think we should move to go code, so lets leave the javascript processor as is for now.

2024-06-26 15:12 UTC, leehinman commented on packages/windows/data_stream/windows_defender/agent/stream/winlog.yml.hbs
> +{{else}}
worked in my testing.

2024-06-26 18:36 UTC, nicpenning commented
Anything else you would like to test at this point?

2024-06-28 02:09 UTC, nicpenning commented
So I did a manual test and @leehinman's code for the preserve original event did not work. I reverted back to what the other Windows datastreams had and it is now functioning. Please advise!

2024-07-01 13:44 UTC, leehinman commented
> So I did a manual test and @leehinman's code for the preserve original event did not work. I reverted back to what the other Windows datastreams had and it is now functioning. Please advise!

What was the test, and how did it fail?  I did check what you had merged and at least at the policy level it looked like the tags were being added correctly.

2024-07-01 14:06 UTC, nicpenning commented
I deployed the agent on my Windows workstation manually with those settings and the event.original was not being added to the event.

2024-07-01 19:10 UTC, leehinman commented
> I deployed the agent on my Windows workstation manually with those settings and the event.original was not being added to the event.

When you added the suggestion, you removed this section:

```
{{if preserve_original_event}}
include_xml: true
{{/if}}
```

without that, the winlog input won't give you the original event.  The tags part is so that the default ingest pipeline doesn't delete it.

2024-07-02 00:17 UTC, nicpenning commented
Whoops! I will give it go as soon as I can! Sorry about that!

2024-07-02 02:12 UTC, nicpenning commented
Is this what I need for the entirety of the file then? Looks like my tests had this:

```
name: Microsoft-Windows-Windows Defender/Operational
condition: ${host.platform} == 'windows'
{{#if event_id}}
event_id: {{event_id}}
{{/if}}
{{#if ignore_older}}
ignore_older: {{ignore_older}}
{{/if}}
{{#if language}}
language: {{language}}
{{/if}}

{{#if tags.length}}
tags:
{{#each tags as |tag|}}
  - {{tag}}
{{/each}}
{{#if preserve_original_event}}
  - preserve_original_event
{{/if}}
{{else}}
{{#if preserve_original_event}}
tags:
  - preserve_original_event
{{/if}}
{{/if}}
{{#if preserve_original_event}}
include_xml: true
{{/if}}
processors:
- translate_sid:
    field: winlog.event_data.MemberSid
    account_name_target: winlog.event_data._MemberUserName
    domain_target: winlog.event_data._MemberDomain
    account_type_target: winlog.event_data._MemberAccountType
    ignore_missing: true
    ignore_failure: true
- script:
    lang: javascript
    id: rename_fields_in_winlog_event_data_that_have_spaces
    source: >
      function process(event) {
        var eventData = event.Get("winlog.event_data");
        if (eventData !== null) {
          var newEventData = {};
          for (var key in eventData) {
            if (eventData.hasOwnProperty(key)) {
              var newKey = key.replace(/ /g, "_");
              newEventData[newKey] = eventData[key];
            }
          }
          event.Put("winlog.event_data", newEventData);
        }
      }
{{#if processors.length}}
{{processors}}
{{/if}}
{{custom}}
```

2024-07-02 13:41 UTC, leehinman commented
> Is this what I need for the entirety of the file then? Looks like my tests had this:
> 

Sorry, I meant when you tests the code using `unless` that removed the ambiguous else statements.
Here is the snippet before the `processors` part of the file

```
name: Microsoft-Windows-Windows Defender/Operational
condition: ${host.platform} == 'windows'
{{#if event_id}}
event_id: {{event_id}}
{{/if}}
{{#if ignore_older}}
ignore_older: {{ignore_older}}
{{/if}}
{{#if language}}
language: {{language}}
{{/if}}

{{#if preserve_original_event}}
include_xml: true
{{/if}}

# if we have tags defined add the tags object
{{#if tags.length}}
tags:
{{/if}}

# if tags aren't defined but preserver original is, add tags object
{{#unless tags.length}}
{{#if preserve_original_event}}
tags:
{{/if}}
{{/unless}}

# if tags are defined, add them
{{#if tags.length}}
{{#each tags as |tag|}}
  - {{tag}}
{{/each}}
{{/if}}

# if preserve original event is defined add that tag
{{#if preserve_original_event}}
  - preserve_original_event
{{/if}}
```

2024-07-02 19:55 UTC, nicpenning commented
Re-added code. Will test later this evening. If you have a chance to give it a go again and validate the code looks good that would be great.

2024-07-03 02:51 UTC, nicpenning commented
Local tests look good. I can't get my manual tests to work. I am good to ship it as is with the built in tests passing.

2024-07-08 20:59 UTC, nicpenning commented
@leehinman - Any other updates needed here?

Keep in mind that I did mark this data stream as Beta. Can take another run at it with any issues/fixes before dropping that flag.

2024-07-08 21:51 UTC, leehinman commented
> @leehinman - Any other updates needed here?
> 
> Keep in mind that I did mark this data stream as Beta. Can take another run at it with any issues/fixes before dropping that flag on a future PR.

Not from me, I "approved".  I think you need someone from "sec-windows-platform" to review since they are codeowners.

2024-07-08 22:07 UTC, nicpenning commented
@efd6 - Is this your team?

2024-07-09 06:24 UTC, pierrehilbert commented
Hey @nfritts, could we have someone from your team to review here?

2024-07-12 08:33 UTC, marc-gr approved these changes

2024-07-12 08:33 UTC, marc-gr commented
/test

2024-07-12 08:37 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13589)
* Commit: 8cbfe17583d1dcb5c38b1ce9b101227cde55e7ac

### Failed CI Steps
* [:white_check_mark: Check go sources](https://buildkite.com/elastic/integrations/builds/13589#0190a614-9883-4b37-9e43-ec0246680606)

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13589","number":13589,"commit":"8cbfe17583d1dcb5c38b1ce9b101227cde55e7ac"}],"number":13589}
buildkite-pr-comment-->

2024-07-12 09:14 UTC, marc-gr commented
/test

2024-07-12 09:52 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-07-12 09:52 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13594)
* Commit: f7cc903e19a9181b0d769255b44e5fc0305ae275

### History
* :broken_heart: [Build #13589](https://buildkite.com/elastic/integrations/builds/13589) failed 8cbfe17583d1dcb5c38b1ce9b101227cde55e7ac

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13594","number":13594,"commit":"f7cc903e19a9181b0d769255b44e5fc0305ae275"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13589","number":13589,"commit":"8cbfe17583d1dcb5c38b1ce9b101227cde55e7ac"}],"number":13594}
buildkite-pr-comment-->

2024-07-12 09:54 UTC, merged

2024-07-12 10:12 UTC, elasticmachine commented
Package windows - 1.46.0 containing this change is available at https://epr.elastic.co/search?package=windows