[GCP] Migrate ECS version to git@v8.11.0
elastic/integrations pull request #10225
Opened 2024-06-24 12:34 UTC by harnish-elastic

- Enhancement

## Proposed commit message

Migration performed using ecs-update. Minor manual changes are performed.
- event.category or event.type is expecting value as an array instead of string. Hence provided the value as an array. 
- generated pipeline and system tests.

Command

```
go run github.com/andrewkroh/go-examples/ecs-update@014b35dfe4c9832b51e7c909a39a48257d6a005d \
  -ecs-version=8.11.0 \
  -ecs-git-ref=v8.11.0 \
  -fields-yml-drop-ecs \
  -kibana-version=^8.13.0 \
  -drop-import-mappings \
  -owner=elastic/obs-ds-hosted-services \
  packages/gcp
```

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

2024-06-24 12:48 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12772)
* Commit: ae82f384bbb327880086c4576795db6b83a053f8

### Failed CI Steps
* [Check integrations gcp](https://buildkite.com/elastic/integrations/builds/12772#01904a42-14dc-4a14-9635-15a6cef22ce0)

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12772","number":12772,"commit":"ae82f384bbb327880086c4576795db6b83a053f8"}],"number":12772}
buildkite-pr-comment-->

2024-06-24 13:26 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-06-24 13:26 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12779)
* Commit: 2bb0ed96f1842dfa04918f9cd24c853641cedd55

### History
* :broken_heart: [Build #12772](https://buildkite.com/elastic/integrations/builds/12772) failed ae82f384bbb327880086c4576795db6b83a053f8

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12779","number":12779,"commit":"2bb0ed96f1842dfa04918f9cd24c853641cedd55"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12772","number":12772,"commit":"ae82f384bbb327880086c4576795db6b83a053f8"}],"number":12779}
buildkite-pr-comment-->

2024-06-25 07:25 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12802)
* Commit: c005d95f96447ce90b30f1ebdcae21633aa1e4d1

### History
* :green_heart: [Build #12779](https://buildkite.com/elastic/integrations/builds/12779) succeeded 2bb0ed96f1842dfa04918f9cd24c853641cedd55
* :broken_heart: [Build #12772](https://buildkite.com/elastic/integrations/builds/12772) failed ae82f384bbb327880086c4576795db6b83a053f8

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12802","number":12802,"commit":"c005d95f96447ce90b30f1ebdcae21633aa1e4d1"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12779","number":12779,"commit":"2bb0ed96f1842dfa04918f9cd24c853641cedd55"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12772","number":12772,"commit":"ae82f384bbb327880086c4576795db6b83a053f8"}],"number":12802}
buildkite-pr-comment-->

2024-07-02 09:49 UTC, niraj-elastic requested changes

2024-07-02 09:49 UTC, niraj-elastic commented on packages/gcp/data_stream/billing/fields/ecs.yml
>    name: error
I think this is mistake, there is no such field error and cloud. I guess we can remove this field. Please make sure that no value is added to this field in pipeline.

2024-07-02 10:00 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13110)
* Commit: 2499cd8b7d5625dd76518daedc5a5aec9d7097fd

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/13110#019072e1-afe6-4185-9442-fe4f108b9c85)

### History
* :green_heart: [Build #12802](https://buildkite.com/elastic/integrations/builds/12802) succeeded c005d95f96447ce90b30f1ebdcae21633aa1e4d1
* :green_heart: [Build #12779](https://buildkite.com/elastic/integrations/builds/12779) succeeded 2bb0ed96f1842dfa04918f9cd24c853641cedd55
* :broken_heart: [Build #12772](https://buildkite.com/elastic/integrations/builds/12772) failed ae82f384bbb327880086c4576795db6b83a053f8

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13110","number":13110,"commit":"2499cd8b7d5625dd76518daedc5a5aec9d7097fd"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12802","number":12802,"commit":"c005d95f96447ce90b30f1ebdcae21633aa1e4d1"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12779","number":12779,"commit":"2bb0ed96f1842dfa04918f9cd24c853641cedd55"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12772","number":12772,"commit":"ae82f384bbb327880086c4576795db6b83a053f8"}],"number":13110}
buildkite-pr-comment-->

2024-07-02 10:22 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13111)
* Commit: c05b0090e1cd608eb550a533c40d8108f4ccf0f9

### History
* :broken_heart: [Build #13110](https://buildkite.com/elastic/integrations/builds/13110) failed 2499cd8b7d5625dd76518daedc5a5aec9d7097fd
* :green_heart: [Build #12802](https://buildkite.com/elastic/integrations/builds/12802) succeeded c005d95f96447ce90b30f1ebdcae21633aa1e4d1
* :green_heart: [Build #12779](https://buildkite.com/elastic/integrations/builds/12779) succeeded 2bb0ed96f1842dfa04918f9cd24c853641cedd55
* :broken_heart: [Build #12772](https://buildkite.com/elastic/integrations/builds/12772) failed ae82f384bbb327880086c4576795db6b83a053f8

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13111","number":13111,"commit":"c05b0090e1cd608eb550a533c40d8108f4ccf0f9"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13110","number":13110,"commit":"2499cd8b7d5625dd76518daedc5a5aec9d7097fd"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12802","number":12802,"commit":"c005d95f96447ce90b30f1ebdcae21633aa1e4d1"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12779","number":12779,"commit":"2bb0ed96f1842dfa04918f9cd24c853641cedd55"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12772","number":12772,"commit":"ae82f384bbb327880086c4576795db6b83a053f8"}],"number":13111}
buildkite-pr-comment-->

2024-07-05 04:29 UTC, ishleenk17 commented on packages/gcp/data_stream/firestore/fields/ecs.yml
>    name: error
Is this valid ?

2024-07-05 04:40 UTC, harnish-elastic commented on packages/gcp/data_stream/firestore/fields/ecs.yml
>    name: error
Nope, let me remove these fields as well from all the PRs!

2024-07-05 05:11 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13272)
* Commit: f5077c380490edb1c25d74b422174c8fecba691c

### History
* :green_heart: [Build #13111](https://buildkite.com/elastic/integrations/builds/13111) succeeded c05b0090e1cd608eb550a533c40d8108f4ccf0f9
* :broken_heart: [Build #13110](https://buildkite.com/elastic/integrations/builds/13110) failed 2499cd8b7d5625dd76518daedc5a5aec9d7097fd
* :green_heart: [Build #12802](https://buildkite.com/elastic/integrations/builds/12802) succeeded c005d95f96447ce90b30f1ebdcae21633aa1e4d1
* :green_heart: [Build #12779](https://buildkite.com/elastic/integrations/builds/12779) succeeded 2bb0ed96f1842dfa04918f9cd24c853641cedd55
* :broken_heart: [Build #12772](https://buildkite.com/elastic/integrations/builds/12772) failed ae82f384bbb327880086c4576795db6b83a053f8

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13272","number":13272,"commit":"f5077c380490edb1c25d74b422174c8fecba691c"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13111","number":13111,"commit":"c05b0090e1cd608eb550a533c40d8108f4ccf0f9"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13110","number":13110,"commit":"2499cd8b7d5625dd76518daedc5a5aec9d7097fd"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12802","number":12802,"commit":"c005d95f96447ce90b30f1ebdcae21633aa1e4d1"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12779","number":12779,"commit":"2bb0ed96f1842dfa04918f9cd24c853641cedd55"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12772","number":12772,"commit":"ae82f384bbb327880086c4576795db6b83a053f8"}],"number":13272}
buildkite-pr-comment-->

2024-07-05 09:18 UTC, ishleenk17 commented
@mrodm : As discussed over slack, I see these failures after just the last [commit](https://github.com/elastic/integrations/pull/10225/commits/f5077c380490edb1c25d74b422174c8fecba691c). What has changed here ?
These coverage checks are useful, but it would hinder these bulk merges? Please suggest

2024-07-05 09:26 UTC, mrodm commented
> @mrodm : As discussed over slack, I see these failures after just the last [commit](https://github.com/elastic/integrations/pull/10225/commits/f5077c380490edb1c25d74b422174c8fecba691c). What has changed here ? These coverage checks are useful, but it would hinder these bulk merges? Please suggest

@ishleenk17 there were some changes related to how `elastic-package` creates the coverage reports in this PR: https://github.com/elastic/elastic-package/pull/1915 

Now there are more files marked as covered/uncovered, and it is likely that the coverage is decreased (see https://github.com/elastic/elastic-package/pull/1915#discussion_r1662359216).
There is still pending to add more files as part of the coverage in this other PR https://github.com/elastic/integrations/pull/10385 (to be checked if that would decreased the coverage (%) too). 

I think this PR could be merged even if that coverage analysis from sonar step is failing.

cc @jsoriano

2024-07-05 09:37 UTC, ishleenk17 approved these changes
Looks good!

2024-07-05 10:35 UTC, zmoog approved these changes

2024-07-05 10:38 UTC, ShourieG approved these changes

2024-07-05 10:42 UTC, kcreddy approved these changes
Minor suggestion.
LGTM 👍🏼

2024-07-05 10:42 UTC, kcreddy commented on packages/gcp/data_stream/loadbalancing_logs/elasticsearch/ingest_pipeline/default.yml
> +      value: ["info"]
Suggest using `append` processor with `allow_duplicates: false` in case data preprocessing done at Logstash before ingest node.

2024-07-05 10:45 UTC, niraj-elastic approved these changes
LGTM

2024-07-05 11:06 UTC, harnish-elastic commented on packages/gcp/data_stream/loadbalancing_logs/elasticsearch/ingest_pipeline/default.yml
> +      value: ["info"]
Updated, thanks!

2024-07-05 11:26 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13304)
* Commit: b3b71dc35181b458b86f468ec19c031f11fd77a6

### History
* :green_heart: [Build #13272](https://buildkite.com/elastic/integrations/builds/13272) succeeded f5077c380490edb1c25d74b422174c8fecba691c
* :green_heart: [Build #13111](https://buildkite.com/elastic/integrations/builds/13111) succeeded c05b0090e1cd608eb550a533c40d8108f4ccf0f9
* :broken_heart: [Build #13110](https://buildkite.com/elastic/integrations/builds/13110) failed 2499cd8b7d5625dd76518daedc5a5aec9d7097fd
* :green_heart: [Build #12802](https://buildkite.com/elastic/integrations/builds/12802) succeeded c005d95f96447ce90b30f1ebdcae21633aa1e4d1
* :green_heart: [Build #12779](https://buildkite.com/elastic/integrations/builds/12779) succeeded 2bb0ed96f1842dfa04918f9cd24c853641cedd55
* :broken_heart: [Build #12772](https://buildkite.com/elastic/integrations/builds/12772) failed ae82f384bbb327880086c4576795db6b83a053f8

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13304","number":13304,"commit":"b3b71dc35181b458b86f468ec19c031f11fd77a6"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13272","number":13272,"commit":"f5077c380490edb1c25d74b422174c8fecba691c"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13111","number":13111,"commit":"c05b0090e1cd608eb550a533c40d8108f4ccf0f9"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13110","number":13110,"commit":"2499cd8b7d5625dd76518daedc5a5aec9d7097fd"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12802","number":12802,"commit":"c005d95f96447ce90b30f1ebdcae21633aa1e4d1"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12779","number":12779,"commit":"2bb0ed96f1842dfa04918f9cd24c853641cedd55"}],"number":13304}
buildkite-pr-comment-->

2024-07-05 11:27 UTC, ishleenk17 commented
As per the comment [here](https://github.com/elastic/integrations/pull/10225#issuecomment-2210528698), we are ignoring the sonarqube error and merging the code

2024-07-05 11:27 UTC, merged

2024-07-05 11:42 UTC, elasticmachine commented
Package gcp - 2.35.0 containing this change is available at https://epr.elastic.co/search?package=gcp