[Nginx] Add SLO's with Nginx Package
elastic/integrations pull request #10269
Opened 2024-06-26 12:41 UTC by muthu-mps

- Enhancement

Adds new SLO to be shipped with the integration package.

- Created a simple request includes the create_slo API request input. 
- This is the basic version to test the SLO's with the integration package. Subject to change.
- Updated the `package spec` version in the integration to 3.3.0 (pre-release version) as suggested by @jsoriano

2024-06-26 12:43 UTC, muthu-mps commented on packages/nginx/manifest.yml
> +format_version: "3.3.0"
@jsoriano - I have updated the version to 3.3.0 to test the behaviour and I am getting this error.

`Error: building package failed: invalid content found in built zip package: could not load specification for version [3.3.0]: spec version "3.3.0" not found`

Can you suggest on how to test this change with the pre-release version?

2024-06-26 12:50 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12924)
* Commit: fc23f399c72307609b332475812ee242c10ced74

### Failed CI Steps
* [Check integrations nginx](https://buildkite.com/elastic/integrations/builds/12924#01905494-4e6e-4956-9793-dd058c966754)

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12924","number":12924,"commit":"fc23f399c72307609b332475812ee242c10ced74"}],"number":12924}
buildkite-pr-comment-->

2024-06-26 13:13 UTC, jsoriano commented on packages/nginx/manifest.yml
> +format_version: "3.3.0"
No released version of package spec contains this spec version, you will need to add a replace in the meantime, something like this:
```
go mod edit -replace github.com/elastic/package-spec/v3=github.com/elastic/package-spec/v3@main
go mod tidy
```

2024-06-26 14:37 UTC, jsoriano commented on packages/nginx/manifest.yml
> +format_version: "3.3.0"
> What is the `format_version` that we could use for testing the package?

`format_version: 3.3.0`

2024-06-26 15:08 UTC, muthu-mps commented on packages/nginx/manifest.yml
> +format_version: "3.3.0"
@jsoriano - Tried the above step and with the `format_version:3.3.0` we are still getting the same error.

2024-06-26 15:28 UTC, jsoriano commented on packages/nginx/manifest.yml
> +format_version: "3.3.0"
Have you added the replace to the go.mod? with the commands mentioned in https://github.com/elastic/integrations/pull/10269#discussion_r1654807954?

2024-06-26 15:42 UTC, muthu-mps commented on packages/nginx/manifest.yml
> +format_version: "3.3.0"
While running the command this is what I get in the go.mod file, Is this the expected value?

`replace github.com/elastic/package-spec/v3 => github.com/elastic/package-spec/v3 v3.2.1-0.20240626070810-2758f3ed9689`

2024-06-26 16:09 UTC, jsoriano commented on packages/nginx/manifest.yml
> +format_version: "3.3.0"
Looks good, yes, this should be enough for CI.

If you want to use elastic-package with this dependency you can run it as `go run github.com/elastic/elastic-package` from the integrations repository.

2024-06-27 03:53 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12940)
* Commit: 68f1f18d5debee16ddcf2e91897954442869613a

### Failed CI Steps
* [Check integrations nginx](https://buildkite.com/elastic/integrations/builds/12940#019057cf-7fff-4f90-bea9-5c419e74d93d)

### History
* :broken_heart: [Build #12924](https://buildkite.com/elastic/integrations/builds/12924) failed fc23f399c72307609b332475812ee242c10ced74

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12940","number":12940,"commit":"68f1f18d5debee16ddcf2e91897954442869613a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12924","number":12924,"commit":"fc23f399c72307609b332475812ee242c10ced74"}],"number":12940}
buildkite-pr-comment-->

2024-06-27 04:34 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12941)
* Commit: ac5e3901a87f01bb945fcba6f8a7be1c35e6758d

### Failed CI Steps
* [Check integrations azure_blob_storage](https://buildkite.com/elastic/integrations/builds/12941#019057f4-8009-4970-b9fb-4b3aaa6f6df3)

### History
* :broken_heart: [Build #12940](https://buildkite.com/elastic/integrations/builds/12940) failed 68f1f18d5debee16ddcf2e91897954442869613a
* :broken_heart: [Build #12924](https://buildkite.com/elastic/integrations/builds/12924) failed fc23f399c72307609b332475812ee242c10ced74

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12941","number":12941,"commit":"ac5e3901a87f01bb945fcba6f8a7be1c35e6758d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12940","number":12940,"commit":"68f1f18d5debee16ddcf2e91897954442869613a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12924","number":12924,"commit":"fc23f399c72307609b332475812ee242c10ced74"}],"number":12941}
buildkite-pr-comment-->

2024-06-27 04:49 UTC, muthu-mps commented on packages/nginx/manifest.yml
> +format_version: "3.3.0"
Thanks @jsoriano!
 - We are getting few validation errors in different package, I am skipping those for now as those are not related.

2024-06-27 04:58 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12942)
* Commit: 30161febf89c2238a014027b98dae7e196ff506e

### Failed CI Steps
* [Check integrations aws_logs](https://buildkite.com/elastic/integrations/builds/12942#01905806-1a38-4e99-8237-bfd407f71b84)

### History
* :broken_heart: [Build #12941](https://buildkite.com/elastic/integrations/builds/12941) failed ac5e3901a87f01bb945fcba6f8a7be1c35e6758d
* :broken_heart: [Build #12940](https://buildkite.com/elastic/integrations/builds/12940) failed 68f1f18d5debee16ddcf2e91897954442869613a
* :broken_heart: [Build #12924](https://buildkite.com/elastic/integrations/builds/12924) failed fc23f399c72307609b332475812ee242c10ced74

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12942","number":12942,"commit":"30161febf89c2238a014027b98dae7e196ff506e"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12941","number":12941,"commit":"ac5e3901a87f01bb945fcba6f8a7be1c35e6758d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12940","number":12940,"commit":"68f1f18d5debee16ddcf2e91897954442869613a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12924","number":12924,"commit":"fc23f399c72307609b332475812ee242c10ced74"}],"number":12942}
buildkite-pr-comment-->

2024-06-27 05:28 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12943)
* Commit: 029e7e5b8158aed696595b25d1cd379028c249a2

### Failed CI Steps
* [Check integrations azure_blob_storage](https://buildkite.com/elastic/integrations/builds/12943#01905826-b73f-4e05-8de6-0f6204230e42)

### History
* :broken_heart: [Build #12942](https://buildkite.com/elastic/integrations/builds/12942) failed 30161febf89c2238a014027b98dae7e196ff506e
* :broken_heart: [Build #12941](https://buildkite.com/elastic/integrations/builds/12941) failed ac5e3901a87f01bb945fcba6f8a7be1c35e6758d
* :broken_heart: [Build #12940](https://buildkite.com/elastic/integrations/builds/12940) failed 68f1f18d5debee16ddcf2e91897954442869613a
* :broken_heart: [Build #12924](https://buildkite.com/elastic/integrations/builds/12924) failed fc23f399c72307609b332475812ee242c10ced74

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12943","number":12943,"commit":"029e7e5b8158aed696595b25d1cd379028c249a2"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12942","number":12942,"commit":"30161febf89c2238a014027b98dae7e196ff506e"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12941","number":12941,"commit":"ac5e3901a87f01bb945fcba6f8a7be1c35e6758d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12940","number":12940,"commit":"68f1f18d5debee16ddcf2e91897954442869613a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12924","number":12924,"commit":"fc23f399c72307609b332475812ee242c10ced74"}],"number":12943}
buildkite-pr-comment-->

2024-06-27 08:08 UTC, elasticmachine commented
### :rocket: Benchmarks report






































































































































































































































































































































































































































To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-06-27 09:10 UTC, jsoriano commented on packages/nginx/manifest.yml
> +format_version: "3.3.0"
Yeah, after updating go.mod all tests are executed, but you can ignore the ones not related to your package.

2024-06-27 09:16 UTC, mgiota commented on packages/nginx/manifest.yml
> +format_version: "3.3.0"
> No released version of package spec contains this spec version

@jsoriano When is the next release of the package spec?

2024-06-27 09:20 UTC, mgiota commented on go.mod
> +replace github.com/elastic/package-spec/v3 => github.com/elastic/package-spec/v3 v3.2.1-0.20240626070810-2758f3ed9689
@muthu-mps I just to verify if this version is correct `v3.2.1-0.20240626070810-2758f3ed9689`

2024-06-27 09:29 UTC, mgiota commented on go.mod
> +replace github.com/elastic/package-spec/v3 => github.com/elastic/package-spec/v3 v3.2.1-0.20240626070810-2758f3ed9689
@jsoriano If I understand correctly, this commit is temporary? I mean once the next package-spec is released, do we still need this change? Maybe we should exclude this change from git and just rely on running ` go run github.com/elastic/elastic-package build` locally to be able to test it?

2024-06-27 09:38 UTC, muthu-mps commented on go.mod
> +replace github.com/elastic/package-spec/v3 => github.com/elastic/package-spec/v3 v3.2.1-0.20240626070810-2758f3ed9689
> @muthu-mps I just want to verify if this version is correct `v3.2.1-0.20240626070810-2758f3ed9689`

Yes, With this version I am able to build the integrations successfully by adding SLO's. That means it is using the `package-spec` change to add slo's.

2024-06-27 10:42 UTC, mgiota commented
Changes LGTM! I leave a comment here, regarding updating the README file of the Ngnix integration to include the SLO asset addition.

2024-06-27 10:51 UTC, mgiota commented on packages/nginx/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/1
@muthu-mps Shouldn't you reference here your own PR https://github.com/elastic/integrations/pull/10269 ?

2024-06-27 10:53 UTC, mgiota requested changes

2024-06-27 10:53 UTC, mgiota commented on packages/nginx/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/1
```suggestion
      link: https://github.com/elastic/integrations/pull/10269
```

2024-06-27 11:05 UTC, mgiota commented
I found similar commit, where `ML modules` were added to the README. I am adding it here for [reference](https://github.com/elastic/integrations/commit/1f2658c1ed72567a7bd2bdea3cade232617712cc)

2024-06-27 11:10 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12956)
* Commit: d84e352b0d56c34084a60c48cf095ba48bd4cf52

### Failed CI Steps
* [Check integrations azure_blob_storage](https://buildkite.com/elastic/integrations/builds/12956#01905960-3cec-43d9-b416-91d743c8092a)

### History
* :broken_heart: [Build #12943](https://buildkite.com/elastic/integrations/builds/12943) failed 029e7e5b8158aed696595b25d1cd379028c249a2
* :broken_heart: [Build #12942](https://buildkite.com/elastic/integrations/builds/12942) failed 30161febf89c2238a014027b98dae7e196ff506e
* :broken_heart: [Build #12941](https://buildkite.com/elastic/integrations/builds/12941) failed ac5e3901a87f01bb945fcba6f8a7be1c35e6758d
* :broken_heart: [Build #12940](https://buildkite.com/elastic/integrations/builds/12940) failed 68f1f18d5debee16ddcf2e91897954442869613a
* :broken_heart: [Build #12924](https://buildkite.com/elastic/integrations/builds/12924) failed fc23f399c72307609b332475812ee242c10ced74

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12956","number":12956,"commit":"d84e352b0d56c34084a60c48cf095ba48bd4cf52"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12943","number":12943,"commit":"029e7e5b8158aed696595b25d1cd379028c249a2"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12942","number":12942,"commit":"30161febf89c2238a014027b98dae7e196ff506e"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12941","number":12941,"commit":"ac5e3901a87f01bb945fcba6f8a7be1c35e6758d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12940","number":12940,"commit":"68f1f18d5debee16ddcf2e91897954442869613a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12924","number":12924,"commit":"fc23f399c72307609b332475812ee242c10ced74"}],"number":12956}
buildkite-pr-comment-->

2024-06-27 13:18 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12962)
* Commit: 0603c97a660a6369a695ef43a301aa12a5e2b29d

### Failed CI Steps
* [Check integrations azure_blob_storage](https://buildkite.com/elastic/integrations/builds/12962#019059d5-3990-4d3e-b801-22bb20a1b2c0)

### History
* :broken_heart: [Build #12956](https://buildkite.com/elastic/integrations/builds/12956) failed d84e352b0d56c34084a60c48cf095ba48bd4cf52
* :broken_heart: [Build #12943](https://buildkite.com/elastic/integrations/builds/12943) failed 029e7e5b8158aed696595b25d1cd379028c249a2
* :broken_heart: [Build #12942](https://buildkite.com/elastic/integrations/builds/12942) failed 30161febf89c2238a014027b98dae7e196ff506e
* :broken_heart: [Build #12941](https://buildkite.com/elastic/integrations/builds/12941) failed ac5e3901a87f01bb945fcba6f8a7be1c35e6758d
* :broken_heart: [Build #12940](https://buildkite.com/elastic/integrations/builds/12940) failed 68f1f18d5debee16ddcf2e91897954442869613a

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12962","number":12962,"commit":"0603c97a660a6369a695ef43a301aa12a5e2b29d"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12956","number":12956,"commit":"d84e352b0d56c34084a60c48cf095ba48bd4cf52"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12943","number":12943,"commit":"029e7e5b8158aed696595b25d1cd379028c249a2"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12942","number":12942,"commit":"30161febf89c2238a014027b98dae7e196ff506e"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12941","number":12941,"commit":"ac5e3901a87f01bb945fcba6f8a7be1c35e6758d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12940","number":12940,"commit":"68f1f18d5debee16ddcf2e91897954442869613a"}],"number":12962}
buildkite-pr-comment-->

2024-06-27 13:28 UTC, mgiota commented on packages/nginx/_dev/build/docs/README.md
> +You can use the Nginx integration to measure the availability of the Nginx service. The SLOs gets created automatically during the installation of the integration. The user can view the created SLOs
@muthu-mps Nice! I took your changes and I was able to see the README changes in the UI!

<img width="1286" alt="Screenshot 2024-06-27 at 15 21 26" src="https://github.com/elastic/integrations/assets/2852703/7d763ba2-66c9-4863-991f-dce50cebf590">

I have one correction regarding this text `in the Kibana dashboard panel`. You should change that, since user can see the automatically generated SLOs under the Observability SLOs page.

I was checking the [Kibana SLO documentation page](https://www.elastic.co/guide/en/observability/current/slo-create.html) and they reference the SLOs page page like this `Observability -> SLOs`. 

So feel free to change to: `The user can view the created SLOs in the Observability -> SLOs page.`

2024-06-27 14:05 UTC, jsoriano commented on packages/nginx/manifest.yml
> +format_version: "3.3.0"
> @jsoriano When is the next release of the package spec?

We release more or less on demand, and we have just released 3.2.1. Maybe we can release 3.2.2 soon with a couple of bugfixes. This release would also include 3.3.0 prerelease, what will allow to use SLOs in prerelease packages.

2024-06-27 14:07 UTC, jsoriano commented on go.mod
> +replace github.com/elastic/package-spec/v3 => github.com/elastic/package-spec/v3 v3.2.1-0.20240626070810-2758f3ed9689
> @jsoriano If I understand correctly, this addition is temporary? I mean once the next package-spec is released, do we still need this change? Maybe we should exclude this change from git and just rely on running ` go run github.com/elastic/elastic-package build` locally to be able to test it?

Yes, this is temporary to allow to run in CI till 3.3.0 is available. This PR cannot be merged till then.

2024-06-27 14:22 UTC, muthu-mps commented on packages/nginx/_dev/build/docs/README.md
> +You can use the Nginx integration to measure the availability of the Nginx service. The SLOs gets created automatically during the installation of the integration. The user can view the created SLOs
Thanks! I have updated the README file.

2024-06-27 14:31 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12963)
* Commit: 9c323797849f5d0c4de53dc2133a8065268f4433

### Failed CI Steps
* [Check integrations azure_blob_storage](https://buildkite.com/elastic/integrations/builds/12963#01905a16-997a-4e63-9ac4-ef881d0cb93a)

### History
* :broken_heart: [Build #12962](https://buildkite.com/elastic/integrations/builds/12962) failed 0603c97a660a6369a695ef43a301aa12a5e2b29d
* :broken_heart: [Build #12956](https://buildkite.com/elastic/integrations/builds/12956) failed d84e352b0d56c34084a60c48cf095ba48bd4cf52
* :broken_heart: [Build #12943](https://buildkite.com/elastic/integrations/builds/12943) failed 029e7e5b8158aed696595b25d1cd379028c249a2
* :broken_heart: [Build #12942](https://buildkite.com/elastic/integrations/builds/12942) failed 30161febf89c2238a014027b98dae7e196ff506e
* :broken_heart: [Build #12941](https://buildkite.com/elastic/integrations/builds/12941) failed ac5e3901a87f01bb945fcba6f8a7be1c35e6758d

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12963","number":12963,"commit":"9c323797849f5d0c4de53dc2133a8065268f4433"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12962","number":12962,"commit":"0603c97a660a6369a695ef43a301aa12a5e2b29d"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12956","number":12956,"commit":"d84e352b0d56c34084a60c48cf095ba48bd4cf52"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12943","number":12943,"commit":"029e7e5b8158aed696595b25d1cd379028c249a2"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12942","number":12942,"commit":"30161febf89c2238a014027b98dae7e196ff506e"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12941","number":12941,"commit":"ac5e3901a87f01bb945fcba6f8a7be1c35e6758d"}],"number":12963}
buildkite-pr-comment-->

2024-07-04 14:58 UTC, jsoriano commented on go.mod
> +replace github.com/elastic/package-spec/v3 => github.com/elastic/package-spec/v3 v3.2.1-0.20240626070810-2758f3ed9689
This replace can be removed now, we have just released a version of `elastic-package` that includes the technical preview of 3.3.0.

2024-07-24 07:15 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13903)
* Commit: 2f311c8612feccbf1aeaea57721c79d66e15f62f

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/13903#0190e397-9534-4c4a-b71d-9a59b7d3e488)

### History
* :broken_heart: [Build #12963](https://buildkite.com/elastic/integrations/builds/12963) failed 9c323797849f5d0c4de53dc2133a8065268f4433
* :broken_heart: [Build #12962](https://buildkite.com/elastic/integrations/builds/12962) failed 0603c97a660a6369a695ef43a301aa12a5e2b29d
* :broken_heart: [Build #12956](https://buildkite.com/elastic/integrations/builds/12956) failed d84e352b0d56c34084a60c48cf095ba48bd4cf52
* :broken_heart: [Build #12943](https://buildkite.com/elastic/integrations/builds/12943) failed 029e7e5b8158aed696595b25d1cd379028c249a2
* :broken_heart: [Build #12942](https://buildkite.com/elastic/integrations/builds/12942) failed 30161febf89c2238a014027b98dae7e196ff506e

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13903","number":13903,"commit":"2f311c8612feccbf1aeaea57721c79d66e15f62f"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12963","number":12963,"commit":"9c323797849f5d0c4de53dc2133a8065268f4433"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12962","number":12962,"commit":"0603c97a660a6369a695ef43a301aa12a5e2b29d"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12956","number":12956,"commit":"d84e352b0d56c34084a60c48cf095ba48bd4cf52"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12943","number":12943,"commit":"029e7e5b8158aed696595b25d1cd379028c249a2"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12942","number":12942,"commit":"30161febf89c2238a014027b98dae7e196ff506e"}],"number":13903}
buildkite-pr-comment-->

2024-07-24 07:23 UTC, harnish-elastic requested changes
As per offline discussion, need to update the following things!

- Need to use index logs-* instead of logs-nginx-*
- Need to add data_stream.dataset query since the field that has been used is ecs and if the user having multiple packages, SLO will also be generated from that field!

2024-07-24 07:28 UTC, muthu-mps commented
> As per offline discussion, need to update the following things!
> 
> * Need to use index logs-* instead of logs-nginx-*
> * Need to add data_stream.dataset query since the field that has been used is ecs and if the user having multiple packages, SLO/alerts will also be generated from that field!

Yes Harnish, The issue here is that the default dataview is only supported here. I have already captured it [here](https://github.com/elastic/integrations/issues/10467#:~:text=Please%20find%20my%20observations%20while%20installing%20the%20SLO%20from%20the%20integration%2C).

2024-07-24 07:41 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13904)
* Commit: 4ecfa70577edf794971f5608d6c1a026d383f51f

### History
* :broken_heart: [Build #13903](https://buildkite.com/elastic/integrations/builds/13903) failed 2f311c8612feccbf1aeaea57721c79d66e15f62f
* :broken_heart: [Build #12963](https://buildkite.com/elastic/integrations/builds/12963) failed 9c323797849f5d0c4de53dc2133a8065268f4433
* :broken_heart: [Build #12962](https://buildkite.com/elastic/integrations/builds/12962) failed 0603c97a660a6369a695ef43a301aa12a5e2b29d
* :broken_heart: [Build #12956](https://buildkite.com/elastic/integrations/builds/12956) failed d84e352b0d56c34084a60c48cf095ba48bd4cf52
* :broken_heart: [Build #12943](https://buildkite.com/elastic/integrations/builds/12943) failed 029e7e5b8158aed696595b25d1cd379028c249a2
* :broken_heart: [Build #12942](https://buildkite.com/elastic/integrations/builds/12942) failed 30161febf89c2238a014027b98dae7e196ff506e

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13904","number":13904,"commit":"4ecfa70577edf794971f5608d6c1a026d383f51f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13903","number":13903,"commit":"2f311c8612feccbf1aeaea57721c79d66e15f62f"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12963","number":12963,"commit":"9c323797849f5d0c4de53dc2133a8065268f4433"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12962","number":12962,"commit":"0603c97a660a6369a695ef43a301aa12a5e2b29d"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12956","number":12956,"commit":"d84e352b0d56c34084a60c48cf095ba48bd4cf52"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12943","number":12943,"commit":"029e7e5b8158aed696595b25d1cd379028c249a2"}],"number":13904}
buildkite-pr-comment-->

2024-07-24 09:01 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13909)
* Commit: d1ba63049691a1b945064706091fee9fb6c901e4

### History
* :green_heart: [Build #13904](https://buildkite.com/elastic/integrations/builds/13904) succeeded 4ecfa70577edf794971f5608d6c1a026d383f51f
* :broken_heart: [Build #13903](https://buildkite.com/elastic/integrations/builds/13903) failed 2f311c8612feccbf1aeaea57721c79d66e15f62f
* :broken_heart: [Build #12963](https://buildkite.com/elastic/integrations/builds/12963) failed 9c323797849f5d0c4de53dc2133a8065268f4433
* :broken_heart: [Build #12962](https://buildkite.com/elastic/integrations/builds/12962) failed 0603c97a660a6369a695ef43a301aa12a5e2b29d
* :broken_heart: [Build #12956](https://buildkite.com/elastic/integrations/builds/12956) failed d84e352b0d56c34084a60c48cf095ba48bd4cf52
* :broken_heart: [Build #12943](https://buildkite.com/elastic/integrations/builds/12943) failed 029e7e5b8158aed696595b25d1cd379028c249a2

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13909","number":13909,"commit":"d1ba63049691a1b945064706091fee9fb6c901e4"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13904","number":13904,"commit":"4ecfa70577edf794971f5608d6c1a026d383f51f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13903","number":13903,"commit":"2f311c8612feccbf1aeaea57721c79d66e15f62f"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12963","number":12963,"commit":"9c323797849f5d0c4de53dc2133a8065268f4433"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12962","number":12962,"commit":"0603c97a660a6369a695ef43a301aa12a5e2b29d"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12956","number":12956,"commit":"d84e352b0d56c34084a60c48cf095ba48bd4cf52"}],"number":13909}
buildkite-pr-comment-->

2024-10-18 21:29 UTC, closed without merging