packages/salesforce: add dashboards
elastic/integrations pull request #10341
Opened 2024-07-03 04:07 UTC by kush-elastic

## Description

This PR introduces a new dashboards for the below mentioned datastream in Salesforce Integration:
- Login
- Logout
- Apex
- Setup Audit Trail

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Relates https://github.com/elastic/obs-infraobs-team/issues/1248

2024-07-03 04:15 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13157)
* Commit: e96c350819448b1b948b76a0199867fde0376d16

### Failed CI Steps
* [Check integrations salesforce](https://buildkite.com/elastic/integrations/builds/13157#019076ca-665d-4524-8426-d5818cd0074e)

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13157","number":13157,"commit":"e96c350819448b1b948b76a0199867fde0376d16"}],"number":13157}
buildkite-pr-comment-->

2024-07-03 05:55 UTC, kush-elastic commented
/test

2024-07-03 05:59 UTC, milan-elastic commented on packages/salesforce/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/1 #Update
```suggestion
      link: https://github.com/elastic/integrations/pull/10341
```

2024-07-03 06:13 UTC, elasticmachine commented
### :rocket: Benchmarks report


#### Package `salesforce` :&#43;1:(3) :green_heart:(0) :broken_heart:(1)
<details>
<summary>Expand to view</summary>

Data stream | Previous EPS | New EPS | Diff (%) | Result
----------- | ------------ | ------- | -------- | ------
`logout` | 37037.04 | 31250 | -5787.04 (-15.63%) | :broken_heart:
</details>


To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-07-03 06:15 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13158)
* Commit: e96c350819448b1b948b76a0199867fde0376d16

### History
* :broken_heart: [Build #13157](https://buildkite.com/elastic/integrations/builds/13157) failed e96c350819448b1b948b76a0199867fde0376d16

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13158","number":13158,"commit":"e96c350819448b1b948b76a0199867fde0376d16"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13157","number":13157,"commit":"e96c350819448b1b948b76a0199867fde0376d16"}],"number":13158}
buildkite-pr-comment-->

2024-07-03 06:37 UTC, shmsr commented
All dashboards done?

2024-07-03 08:24 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13170)
* Commit: 241744381cd3801f3fe42217be538697bcd4189d

### History
* :green_heart: [Build #13158](https://buildkite.com/elastic/integrations/builds/13158) succeeded e96c350819448b1b948b76a0199867fde0376d16
* :broken_heart: [Build #13157](https://buildkite.com/elastic/integrations/builds/13157) failed e96c350819448b1b948b76a0199867fde0376d16

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13170","number":13170,"commit":"241744381cd3801f3fe42217be538697bcd4189d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13158","number":13158,"commit":"e96c350819448b1b948b76a0199867fde0376d16"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13157","number":13157,"commit":"e96c350819448b1b948b76a0199867fde0376d16"}],"number":13170}
buildkite-pr-comment-->

2024-07-03 08:54 UTC, shmsr commented
Fixed user_initiated_logout's type when I noticed this:

```
kql='salesforce.logout.user_initiated_logout : \"1\" ')/count()"
```

See 1 is escaped as it is a keyword.

2024-07-03 08:59 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13172)
* Commit: 52059b5f09fc0493cdc20e35c2d82dbf69e2fa3e

### Failed CI Steps
* [Check integrations salesforce](https://buildkite.com/elastic/integrations/builds/13172#019077ce-62b8-40c0-a519-195464d01f92)

### History
* :green_heart: [Build #13170](https://buildkite.com/elastic/integrations/builds/13170) succeeded 241744381cd3801f3fe42217be538697bcd4189d
* :green_heart: [Build #13158](https://buildkite.com/elastic/integrations/builds/13158) succeeded e96c350819448b1b948b76a0199867fde0376d16
* :broken_heart: [Build #13157](https://buildkite.com/elastic/integrations/builds/13157) failed e96c350819448b1b948b76a0199867fde0376d16

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13172","number":13172,"commit":"52059b5f09fc0493cdc20e35c2d82dbf69e2fa3e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13170","number":13170,"commit":"241744381cd3801f3fe42217be538697bcd4189d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13158","number":13158,"commit":"e96c350819448b1b948b76a0199867fde0376d16"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13157","number":13157,"commit":"e96c350819448b1b948b76a0199867fde0376d16"}],"number":13172}
buildkite-pr-comment-->

2024-07-04 06:23 UTC, harnish-elastic commented on packages/salesforce/data_stream/logout/elasticsearch/ingest_pipeline/eventlogfile.yml
> +  - script:
Instead of using script, we can use set processor to do the same thing.

https://github.com/elastic/integrations/blob/main/packages/apache_tomcat/data_stream/connection_pool/elasticsearch/ingest_pipeline/default.yml#L35-L38

2024-07-04 09:15 UTC, shmsr commented on packages/salesforce/data_stream/logout/elasticsearch/ingest_pipeline/eventlogfile.yml
> +  - script:
Ya, good point. I'll make the change; thanks!

2024-07-04 09:29 UTC, shmsr commented on packages/salesforce/data_stream/logout/elasticsearch/ingest_pipeline/eventlogfile.yml
> +  - script:
Done.

By default, set to `false`, and set to `true` by checking the conditions. Had to add another set to do the default.

Also, @harnish-elastic the example that you shared, null check for last field is not done properly. See [this](https://www.elastic.co/guide/en/elasticsearch/reference/current/ingest.html#conditionally-run-processor:~:text=include%20an%20explicit%20null%20check).

2024-07-04 10:01 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13245)
* Commit: 9a1405f925300171939d804aa7a4eca3f8ec4de3

### History
* :green_heart: [Build #13181](https://buildkite.com/elastic/integrations/builds/13181) succeeded 8414fc2b71c48c16333de8f8224872be35a99223
* :broken_heart: [Build #13175](https://buildkite.com/elastic/integrations/builds/13175) failed f701bab35a7b548e39f495b9a1b0c0833714e727
* :broken_heart: [Build #13172](https://buildkite.com/elastic/integrations/builds/13172) failed 52059b5f09fc0493cdc20e35c2d82dbf69e2fa3e
* :green_heart: [Build #13170](https://buildkite.com/elastic/integrations/builds/13170) succeeded 241744381cd3801f3fe42217be538697bcd4189d
* :green_heart: [Build #13158](https://buildkite.com/elastic/integrations/builds/13158) succeeded e96c350819448b1b948b76a0199867fde0376d16
* :broken_heart: [Build #13157](https://buildkite.com/elastic/integrations/builds/13157) failed e96c350819448b1b948b76a0199867fde0376d16

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13245","number":13245,"commit":"9a1405f925300171939d804aa7a4eca3f8ec4de3"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13181","number":13181,"commit":"8414fc2b71c48c16333de8f8224872be35a99223"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13175","number":13175,"commit":"f701bab35a7b548e39f495b9a1b0c0833714e727"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13172","number":13172,"commit":"52059b5f09fc0493cdc20e35c2d82dbf69e2fa3e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13170","number":13170,"commit":"241744381cd3801f3fe42217be538697bcd4189d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13158","number":13158,"commit":"e96c350819448b1b948b76a0199867fde0376d16"}],"number":13245}
buildkite-pr-comment-->

2024-07-05 06:26 UTC, harnish-elastic approved these changes
LGTM!

2024-07-05 09:15 UTC, aliabbas-elastic commented on packages/salesforce/data_stream/logout/elasticsearch/ingest_pipeline/eventlogfile.yml
> +      field: salesforce.logout.user_initiated_logout
@shmsr I am thinking of a case when the `USER_INITIATED_LOGOUT` value would be empty and not `0`. Still in that case this would be set to false. I am not sure that we would receive `USER_INITIATED_LOGOUT` values always as `0` or `1` in every record but would it be good to keep a condition here as well?

2024-07-05 10:30 UTC, aliabbas-elastic commented
I just re exported the dashboards and there were changes in the SetupAuditTrail and Login dashboards control panels length which are now made consistent with the other dashboards.

2024-07-05 10:47 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13298)
* Commit: 4ad94a58466a8516fdd969692593eb6d8fc5015e

### History
* :green_heart: [Build #13245](https://buildkite.com/elastic/integrations/builds/13245) succeeded 9a1405f925300171939d804aa7a4eca3f8ec4de3
* :green_heart: [Build #13181](https://buildkite.com/elastic/integrations/builds/13181) succeeded 8414fc2b71c48c16333de8f8224872be35a99223
* :broken_heart: [Build #13175](https://buildkite.com/elastic/integrations/builds/13175) failed f701bab35a7b548e39f495b9a1b0c0833714e727
* :broken_heart: [Build #13172](https://buildkite.com/elastic/integrations/builds/13172) failed 52059b5f09fc0493cdc20e35c2d82dbf69e2fa3e
* :green_heart: [Build #13170](https://buildkite.com/elastic/integrations/builds/13170) succeeded 241744381cd3801f3fe42217be538697bcd4189d
* :green_heart: [Build #13158](https://buildkite.com/elastic/integrations/builds/13158) succeeded e96c350819448b1b948b76a0199867fde0376d16

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13298","number":13298,"commit":"4ad94a58466a8516fdd969692593eb6d8fc5015e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13245","number":13245,"commit":"9a1405f925300171939d804aa7a4eca3f8ec4de3"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13181","number":13181,"commit":"8414fc2b71c48c16333de8f8224872be35a99223"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13175","number":13175,"commit":"f701bab35a7b548e39f495b9a1b0c0833714e727"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13172","number":13172,"commit":"52059b5f09fc0493cdc20e35c2d82dbf69e2fa3e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13170","number":13170,"commit":"241744381cd3801f3fe42217be538697bcd4189d"}],"number":13298}
buildkite-pr-comment-->

2024-07-05 11:30 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13305)
* Commit: abda16f3a6f7b903294356473f83c976b9a48062

### History
* :green_heart: [Build #13298](https://buildkite.com/elastic/integrations/builds/13298) succeeded 4ad94a58466a8516fdd969692593eb6d8fc5015e
* :green_heart: [Build #13245](https://buildkite.com/elastic/integrations/builds/13245) succeeded 9a1405f925300171939d804aa7a4eca3f8ec4de3
* :green_heart: [Build #13181](https://buildkite.com/elastic/integrations/builds/13181) succeeded 8414fc2b71c48c16333de8f8224872be35a99223
* :broken_heart: [Build #13175](https://buildkite.com/elastic/integrations/builds/13175) failed f701bab35a7b548e39f495b9a1b0c0833714e727
* :broken_heart: [Build #13172](https://buildkite.com/elastic/integrations/builds/13172) failed 52059b5f09fc0493cdc20e35c2d82dbf69e2fa3e
* :green_heart: [Build #13170](https://buildkite.com/elastic/integrations/builds/13170) succeeded 241744381cd3801f3fe42217be538697bcd4189d

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13305","number":13305,"commit":"abda16f3a6f7b903294356473f83c976b9a48062"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13298","number":13298,"commit":"4ad94a58466a8516fdd969692593eb6d8fc5015e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13245","number":13245,"commit":"9a1405f925300171939d804aa7a4eca3f8ec4de3"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13181","number":13181,"commit":"8414fc2b71c48c16333de8f8224872be35a99223"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13175","number":13175,"commit":"f701bab35a7b548e39f495b9a1b0c0833714e727"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13172","number":13172,"commit":"52059b5f09fc0493cdc20e35c2d82dbf69e2fa3e"}],"number":13305}
buildkite-pr-comment-->

2024-07-05 11:48 UTC, shmsr commented on packages/salesforce/data_stream/logout/elasticsearch/ingest_pipeline/eventlogfile.yml
> +      field: salesforce.logout.user_initiated_logout
https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_eventlogfile_logout.htm#:~:text=USER_INITIATED_LOGOUT

As the type of `USER_INITIATED_LOGOUT` is boolean, I expect it to be `0` or `1` as defined in the link. That's why I also changed it to boolean.

2024-07-05 11:48 UTC, shmsr commented on packages/salesforce/data_stream/logout/elasticsearch/ingest_pipeline/eventlogfile.yml
> +      field: salesforce.logout.user_initiated_logout
What do you think?

2024-07-06 07:41 UTC, aliabbas-elastic commented on packages/salesforce/data_stream/logout/elasticsearch/ingest_pipeline/eventlogfile.yml
> +      field: salesforce.logout.user_initiated_logout
Ok makes sense from the documentation that the values would be 0 or 1 but as I was encountering empty values in other fields so thought of similar here as well.

2024-07-09 07:41 UTC, shmsr approved these changes
LGTM. Waiting for @aliabbas-elastic's approval if we found something during dashboard testing.

2024-07-09 07:41 UTC, shmsr commented
@kush-elastic We also have to update the documentation to tell users about the breaking changes in 0.15.0. It should be clear in docs.

2024-07-09 07:45 UTC, harnish-elastic commented
> @kush-elastic We also have to update the documentation to tell users about the breaking changes in 0.15.0. It should be clear in docs.

@shmsr @kush-elastic Please [refer](https://github.com/elastic/integrations/pull/10224#issuecomment-2205829251) to this changelog.yml entry. You can use `type: breaking-change` in your changelog.yml file to tell users about it. We have done this thing in Azure package.

```
- version: "0.4.0"
  changes:
    - description: added anonymous auth config, replaced some RUM config
      type: breaking-change
      link: https://github.com/elastic/apm-server/pull/5623
```

2024-07-09 10:32 UTC, shmsr commented
> > @kush-elastic We also have to update the documentation to tell users about the breaking changes in 0.15.0. It should be clear in docs.
> 
> @shmsr @kush-elastic Please [refer](https://github.com/elastic/integrations/pull/10224#issuecomment-2205829251) to this changelog.yml entry. You can use `type: breaking-change` in your changelog.yml file to tell users about it. We have done this thing in Azure package.
> 
> ```
> - version: "0.4.0"
>   changes:
>     - description: added anonymous auth config, replaced some RUM config
>       type: breaking-change
>       link: https://github.com/elastic/apm-server/pull/5623
> ```

TIL. Thanks, Harnish. I also verified that this is a valid type in the [spec](https://github.com/elastic/package-spec/blob/7aa453907fb0406e32dca37e296e0a2199416487/spec/integration/changelog.spec.yml#L30).

Let's do this.

2024-07-10 06:33 UTC, shmsr requested changes

2024-07-10 06:33 UTC, shmsr commented on packages/salesforce/changelog.yml
>        type: enhancement
```suggestion
      type: breaking-change
```

2024-07-10 06:33 UTC, shmsr commented on packages/salesforce/changelog.yml
> +      type: enhancement
```suggestion
      type: breaking-change
```

2024-07-10 06:34 UTC, shmsr commented on packages/salesforce/changelog.yml
> +    - description: Add dashboards for the salesforce integration.
```suggestion
    - description: Add dashboards for the Salesforce integration.
```

2024-07-10 06:40 UTC, aliabbas-elastic commented
> LGTM. Waiting for @aliabbas-elastic's approval if we found something during dashboard testing.

@shmsr Dashboards are working fine. One minor bug I found while testing was related to the Login `Object` data collection. I am receiving the following error

![image](https://github.com/elastic/integrations/assets/124054599/7875a5a7-af86-4135-8900-ba6f991c7206)

The log corresponding to this error message is as:
```
{ "ApiType": "N/A", "ApiVersion": "N/A", "Application": "testing_salesforce", "Browser": "Unknown", "CipherSuite": "TLS_AES_256_GCM_SHA384", "ClientVersion": "N/A", "CreatedDate": "2024-07-08T07:26:22.128+0000", "EvaluationTime": 0, "EventDate": "2024-07-08T07:26:18.239+0000", "EventIdentifier": "95eeec6d-1e93-46c1-882b-88bd28f7f8de", "HttpMethod": "POST", "Id": "000000000000000AAA", "LoginHistoryId": "0YaJ400000H0kYoKAJ", "LoginKey": "Qv1P3iAGDrGQxSmN", "LoginType": "Remote Access 2.0", "LoginUrl": "devtestin-dev-ed.develop.my.salesforce.com", "Platform": "Unknown", "SessionLevel": "STANDARD", "SourceIp": "89.160.20.112", "Status": "Failed: Missing Consumer Key Parameter", "TlsProtocol": "TLS 1.3", "UserId": "0055j00000AT6I1AAL", "UserType": "Standard", "Username": "salesforceinstance@devtest.in" }
```

I have pinged @kush-elastic for the same and he'll be updating the same. Basically something wrong in the `geo` processor.

2024-07-10 06:52 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13465)
* Commit: ef80c3d0c113be95cdde7431e0dc91b69be22e6c

### History
* :green_heart: [Build #13305](https://buildkite.com/elastic/integrations/builds/13305) succeeded abda16f3a6f7b903294356473f83c976b9a48062
* :green_heart: [Build #13298](https://buildkite.com/elastic/integrations/builds/13298) succeeded 4ad94a58466a8516fdd969692593eb6d8fc5015e
* :green_heart: [Build #13245](https://buildkite.com/elastic/integrations/builds/13245) succeeded 9a1405f925300171939d804aa7a4eca3f8ec4de3
* :green_heart: [Build #13181](https://buildkite.com/elastic/integrations/builds/13181) succeeded 8414fc2b71c48c16333de8f8224872be35a99223
* :broken_heart: [Build #13175](https://buildkite.com/elastic/integrations/builds/13175) failed f701bab35a7b548e39f495b9a1b0c0833714e727
* :broken_heart: [Build #13172](https://buildkite.com/elastic/integrations/builds/13172) failed 52059b5f09fc0493cdc20e35c2d82dbf69e2fa3e

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13465","number":13465,"commit":"ef80c3d0c113be95cdde7431e0dc91b69be22e6c"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13305","number":13305,"commit":"abda16f3a6f7b903294356473f83c976b9a48062"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13298","number":13298,"commit":"4ad94a58466a8516fdd969692593eb6d8fc5015e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13245","number":13245,"commit":"9a1405f925300171939d804aa7a4eca3f8ec4de3"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13181","number":13181,"commit":"8414fc2b71c48c16333de8f8224872be35a99223"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13175","number":13175,"commit":"f701bab35a7b548e39f495b9a1b0c0833714e727"}],"number":13465}
buildkite-pr-comment-->

2024-07-10 09:49 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13476)
* Commit: f6b278e88c9057d413e54b4a0e274071868ae85f

### History
* :green_heart: [Build #13465](https://buildkite.com/elastic/integrations/builds/13465) succeeded ef80c3d0c113be95cdde7431e0dc91b69be22e6c
* :green_heart: [Build #13305](https://buildkite.com/elastic/integrations/builds/13305) succeeded abda16f3a6f7b903294356473f83c976b9a48062
* :green_heart: [Build #13298](https://buildkite.com/elastic/integrations/builds/13298) succeeded 4ad94a58466a8516fdd969692593eb6d8fc5015e
* :green_heart: [Build #13245](https://buildkite.com/elastic/integrations/builds/13245) succeeded 9a1405f925300171939d804aa7a4eca3f8ec4de3
* :green_heart: [Build #13181](https://buildkite.com/elastic/integrations/builds/13181) succeeded 8414fc2b71c48c16333de8f8224872be35a99223
* :broken_heart: [Build #13175](https://buildkite.com/elastic/integrations/builds/13175) failed f701bab35a7b548e39f495b9a1b0c0833714e727

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13476","number":13476,"commit":"f6b278e88c9057d413e54b4a0e274071868ae85f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13465","number":13465,"commit":"ef80c3d0c113be95cdde7431e0dc91b69be22e6c"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13305","number":13305,"commit":"abda16f3a6f7b903294356473f83c976b9a48062"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13298","number":13298,"commit":"4ad94a58466a8516fdd969692593eb6d8fc5015e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13245","number":13245,"commit":"9a1405f925300171939d804aa7a4eca3f8ec4de3"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13181","number":13181,"commit":"8414fc2b71c48c16333de8f8224872be35a99223"}],"number":13476}
buildkite-pr-comment-->

2024-07-10 11:48 UTC, shmsr commented
> > LGTM. Waiting for @aliabbas-elastic's approval if we found something during dashboard testing.
> 
> @shmsr Dashboards are working fine. One minor bug I found while testing was related to the Login `Object` data collection. I am receiving the following error
> 
> ![image](https://private-user-images.githubusercontent.com/124054599/347284854-7875a5a7-af86-4135-8900-ba6f991c7206.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTI0MTgsIm5iZiI6MTcyMDYxMjExOCwicGF0aCI6Ii8xMjQwNTQ1OTkvMzQ3Mjg0ODU0LTc4NzVhNWE3LWFmODYtNDEzNS04OTAwLWJhNmY5OTFjNzIwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQxMTQ4MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDU3Y2U0NDg0Y2NiZmMzMmE3YzhhMmQzNWY2NGJjNmE3YTQ5OTA4ZGY5YWRiZGIyYTE5OTQyZjYzYzAzZjliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1bAEUKJ50m4lfBn_QXIDqL2L0X80y0uNo7XKU3dceFI)
> 
> The log corresponding to this error message is as:
> 
> ```
> { "ApiType": "N/A", "ApiVersion": "N/A", "Application": "testing_salesforce", "Browser": "Unknown", "CipherSuite": "TLS_AES_256_GCM_SHA384", "ClientVersion": "N/A", "CreatedDate": "2024-07-08T07:26:22.128+0000", "EvaluationTime": 0, "EventDate": "2024-07-08T07:26:18.239+0000", "EventIdentifier": "95eeec6d-1e93-46c1-882b-88bd28f7f8de", "HttpMethod": "POST", "Id": "000000000000000AAA", "LoginHistoryId": "0YaJ400000H0kYoKAJ", "LoginKey": "Qv1P3iAGDrGQxSmN", "LoginType": "Remote Access 2.0", "LoginUrl": "devtestin-dev-ed.develop.my.salesforce.com", "Platform": "Unknown", "SessionLevel": "STANDARD", "SourceIp": "89.160.20.112", "Status": "Failed: Missing Consumer Key Parameter", "TlsProtocol": "TLS 1.3", "UserId": "0055j00000AT6I1AAL", "UserType": "Standard", "Username": "salesforceinstance@devtest.in" }
> ```
> 
> I have pinged @kush-elastic for the same and he'll be updating it. Basically something wrong in the `geo` processor.

@kush-elastic You found the issue?

2024-07-10 11:57 UTC, shmsr commented
Posting two feedbacks we received from Anna (I posted this in the internal meta issue) but I will repost here:

- Once it's GA, a concrete list of supported versions of Salesforce would be highly appreciated - SAs and Support often get the question for production monitoring use-cases. Similarly for the [Filebeat module](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-salesforce.html), it would be appreciated if Salesforce version compatibility would be mentioned - even if it's not a requirement.
- There is a mention of breaking changes to the [Filebeat module](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-salesforce.html), but not what those actually are. Is there a release note to link to for more details?

cc: @kush-elastic

2024-07-10 12:27 UTC, kush-elastic commented
> @kush-elastic You found the issue?

Yes, I also have fixed it in last commit.

2024-07-10 12:46 UTC, harnish-elastic approved these changes
LGTM! 🚀

2024-07-10 13:16 UTC, milan-elastic approved these changes

2024-07-10 18:26 UTC, shmsr approved these changes
Let's GO 🚀

2024-07-11 07:59 UTC, harnish-elastic commented on packages/salesforce/_dev/build/docs/README.md
> +### Key benefits of Salesforce Integration:
Minor suggestion to remove `:`

2024-07-11 08:00 UTC, harnish-elastic commented on packages/salesforce/_dev/build/docs/README.md
> +The Salesforce integration comes with the following data streams:
```suggestion
The Salesforce integration provides the following data streams:
```

2024-07-11 08:02 UTC, shmsr commented on packages/salesforce/_dev/build/docs/README.md
> +### Key benefits of Salesforce Integration:
thanks! done.

2024-07-11 08:02 UTC, shmsr commented on packages/salesforce/_dev/build/docs/README.md
> +The Salesforce integration comes with the following data streams:
thanks! done.

2024-07-11 08:13 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13527)
* Commit: b56e7951dd2b46dead6e5147ec31e96bddfbf3bb

### Failed CI Steps
* [Check integrations salesforce](https://buildkite.com/elastic/integrations/builds/13527#0190a0d6-6543-47e7-b2d2-4a5dae01c2a5)

### History
* :green_heart: [Build #13522](https://buildkite.com/elastic/integrations/builds/13522) succeeded 1e8d322eaee02eefc6ae228fd7f2aaa619708632
* :green_heart: [Build #13476](https://buildkite.com/elastic/integrations/builds/13476) succeeded f6b278e88c9057d413e54b4a0e274071868ae85f
* :green_heart: [Build #13465](https://buildkite.com/elastic/integrations/builds/13465) succeeded ef80c3d0c113be95cdde7431e0dc91b69be22e6c
* :green_heart: [Build #13305](https://buildkite.com/elastic/integrations/builds/13305) succeeded abda16f3a6f7b903294356473f83c976b9a48062
* :green_heart: [Build #13298](https://buildkite.com/elastic/integrations/builds/13298) succeeded 4ad94a58466a8516fdd969692593eb6d8fc5015e
* :green_heart: [Build #13245](https://buildkite.com/elastic/integrations/builds/13245) succeeded 9a1405f925300171939d804aa7a4eca3f8ec4de3

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13527","number":13527,"commit":"b56e7951dd2b46dead6e5147ec31e96bddfbf3bb"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13522","number":13522,"commit":"1e8d322eaee02eefc6ae228fd7f2aaa619708632"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13476","number":13476,"commit":"f6b278e88c9057d413e54b4a0e274071868ae85f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13465","number":13465,"commit":"ef80c3d0c113be95cdde7431e0dc91b69be22e6c"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13305","number":13305,"commit":"abda16f3a6f7b903294356473f83c976b9a48062"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13298","number":13298,"commit":"4ad94a58466a8516fdd969692593eb6d8fc5015e"}],"number":13527}
buildkite-pr-comment-->

2024-07-11 08:14 UTC, harnish-elastic approved these changes
LGTM! 🚀

Minor suggestions given.

2024-07-11 08:14 UTC, harnish-elastic commented on packages/salesforce/_dev/build/docs/README.md
> +- **Salesforce Classic**: For an example URL `https://na9.salesforce.com/home/home.jsp`, the Salesforce Instance URL is `https://na9.salesforce.com`.
```suggestion
- **Salesforce Classic**: Given the example URL `https://na9.salesforce.com/home/home.jsp`, the Salesforce Instance URL is extracted as `https://na9.salesforce.com`.
```

2024-07-11 08:28 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13529)
* Commit: 4c13317c15dd1d5bd6dde9e0960579cf87d9b970

### Failed CI Steps
* [Check integrations salesforce](https://buildkite.com/elastic/integrations/builds/13529#0190a0e4-c53f-4d79-bd4f-3957740b8b9d)

### History
* :broken_heart: [Build #13527](https://buildkite.com/elastic/integrations/builds/13527) failed b56e7951dd2b46dead6e5147ec31e96bddfbf3bb
* :green_heart: [Build #13522](https://buildkite.com/elastic/integrations/builds/13522) succeeded 1e8d322eaee02eefc6ae228fd7f2aaa619708632
* :green_heart: [Build #13476](https://buildkite.com/elastic/integrations/builds/13476) succeeded f6b278e88c9057d413e54b4a0e274071868ae85f
* :green_heart: [Build #13465](https://buildkite.com/elastic/integrations/builds/13465) succeeded ef80c3d0c113be95cdde7431e0dc91b69be22e6c
* :green_heart: [Build #13305](https://buildkite.com/elastic/integrations/builds/13305) succeeded abda16f3a6f7b903294356473f83c976b9a48062

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13529","number":13529,"commit":"4c13317c15dd1d5bd6dde9e0960579cf87d9b970"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13527","number":13527,"commit":"b56e7951dd2b46dead6e5147ec31e96bddfbf3bb"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13522","number":13522,"commit":"1e8d322eaee02eefc6ae228fd7f2aaa619708632"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13476","number":13476,"commit":"f6b278e88c9057d413e54b4a0e274071868ae85f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13465","number":13465,"commit":"ef80c3d0c113be95cdde7431e0dc91b69be22e6c"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13305","number":13305,"commit":"abda16f3a6f7b903294356473f83c976b9a48062"}],"number":13529}
buildkite-pr-comment-->

2024-07-11 09:32 UTC, aliabbas-elastic commented on packages/salesforce/kibana/dashboard/salesforce-31f56373-0faf-4bf9-8741-3c560bb69f82.json
> +                        "visualizationType": "lnsDatatable"
I have updated this

2024-07-11 09:55 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13543)
* Commit: 7f0be0f9d334b6ce52fca523264a463c46e40213

### History
* :broken_heart: [Build #13529](https://buildkite.com/elastic/integrations/builds/13529) failed 4c13317c15dd1d5bd6dde9e0960579cf87d9b970
* :broken_heart: [Build #13527](https://buildkite.com/elastic/integrations/builds/13527) failed b56e7951dd2b46dead6e5147ec31e96bddfbf3bb
* :green_heart: [Build #13522](https://buildkite.com/elastic/integrations/builds/13522) succeeded 1e8d322eaee02eefc6ae228fd7f2aaa619708632
* :green_heart: [Build #13476](https://buildkite.com/elastic/integrations/builds/13476) succeeded f6b278e88c9057d413e54b4a0e274071868ae85f
* :green_heart: [Build #13465](https://buildkite.com/elastic/integrations/builds/13465) succeeded ef80c3d0c113be95cdde7431e0dc91b69be22e6c

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13543","number":13543,"commit":"7f0be0f9d334b6ce52fca523264a463c46e40213"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13529","number":13529,"commit":"4c13317c15dd1d5bd6dde9e0960579cf87d9b970"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13527","number":13527,"commit":"b56e7951dd2b46dead6e5147ec31e96bddfbf3bb"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13522","number":13522,"commit":"1e8d322eaee02eefc6ae228fd7f2aaa619708632"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13476","number":13476,"commit":"f6b278e88c9057d413e54b4a0e274071868ae85f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13465","number":13465,"commit":"ef80c3d0c113be95cdde7431e0dc91b69be22e6c"}],"number":13543}
buildkite-pr-comment-->

2024-07-11 09:58 UTC, shmsr approved these changes

2024-07-11 10:06 UTC, aliabbas-elastic approved these changes
LGTM

2024-07-11 10:29 UTC, milan-elastic approved these changes

2024-07-11 10:31 UTC, merged

2024-07-11 10:47 UTC, elasticmachine commented
Package salesforce - 0.15.0 containing this change is available at https://epr.elastic.co/search?package=salesforce