docs: remove duplicate message in aws billing integration page
elastic/integrations pull request #10382
Opened 2024-07-04 14:09 UTC by OrekiYuta

## What does this PR do?

Removed duplicate message in aws billing integration description page
https://www.elastic.co/docs/current/integrations/aws/billing

## Checklist

- [x]  I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x]  I have verified that all data streams collect metrics or logs.
- [x]  I have added an entry to my package's changelog.yml file.
- [x]  I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally

- Clone integrations repo.
- Install elastic-package locally.
- Start elastic stack using elastic-package.
- Move to integrations/packages/mysql) directory.
- Run the following command to run tests. elastic-package test

## Screenshots
https://www.elastic.co/docs/current/integrations/aws/billing#metrics-reference
![image](https://github.com/elastic/integrations/assets/45684547/a1ef58cc-d5e3-44de-9a01-0eef27c9f866)

2024-07-05 04:35 UTC, aliabbas-elastic requested changes

2024-07-05 04:35 UTC, aliabbas-elastic commented on packages/aws/_dev/build/docs/billing.md
> -An example event for `billing` looks as following:
You also need to run `elastic-package build` after doing this change

2024-07-05 04:35 UTC, aliabbas-elastic commented on packages/aws/changelog.yml
> +- version: "2.16.1"
Please update the same version in manifest.yml

2024-07-05 04:35 UTC, aliabbas-elastic commented on packages/aws/changelog.yml
> +      type: enhancement
Lets treat it as a bugfix and not an enhancement

2024-07-05 04:35 UTC, aliabbas-elastic commented on packages/aws/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/10382/
```suggestion
      link: https://github.com/elastic/integrations/pull/10382
```

2024-07-05 11:28 UTC, OrekiYuta commented on packages/aws/_dev/build/docs/billing.md
> -An example event for `billing` looks as following:
already run the commond testing in local

2024-07-05 11:28 UTC, OrekiYuta commented on packages/aws/changelog.yml
> +- version: "2.16.1"
updated

2024-07-05 11:28 UTC, OrekiYuta commented on packages/aws/changelog.yml
> +      type: enhancement
updated

2024-07-06 23:41 UTC, OrekiYuta reviewed
requested change

2024-07-08 08:34 UTC, aliabbas-elastic commented on packages/aws/changelog.yml
> +    - description: Fix AWS Billing Metrics reference description
```suggestion
    - description: Fix AWS Billing Metrics reference description.
```

2024-07-08 08:35 UTC, aliabbas-elastic commented
/test

2024-07-08 09:59 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-07-08 10:00 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13352)
* Commit: dadf76f5b5f1e97258923b12ee5e8a51db280bc0

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13352","number":13352,"commit":"dadf76f5b5f1e97258923b12ee5e8a51db280bc0"}],"number":13352}
buildkite-pr-comment-->

2024-07-11 06:42 UTC, aliabbas-elastic approved these changes
LGTM

2024-10-18 21:29 UTC, closed without merging