Add Processor Support
elastic/integrations pull request #10409
Opened 2024-07-08 12:52 UTC by Linu-Elias

## Proposed commit message
Adding Processor Support for the following Packages

- ActiveMQ
- Apache
- Apache Spark
- AWSFargate
- Azure Application Insights
- Azure Billing
- Azure Functions
- Azure OpenAI
- Cassandra
- CockroachDB

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## How to test this PR locally

## Related issues

- Relates #10393 

## Screenshots

2024-07-08 13:00 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13368)
* Commit: 7496f014f848a4b3e2931d6e5311219fa012d3ad

### Failed CI Steps
* [Check integrations azure_application_insights](https://buildkite.com/elastic/integrations/builds/13368#0190926a-92f2-4ad2-8509-faa490c296c3)

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13368","number":13368,"commit":"7496f014f848a4b3e2931d6e5311219fa012d3ad"}],"number":13368}
buildkite-pr-comment-->

2024-07-08 13:12 UTC, elasticmachine commented
### :rocket: Benchmarks report


#### Package `activemq` :&#43;1:(3) :green_heart:(0) :broken_heart:(2)
<details>
<summary>Expand to view</summary>

Data stream | Previous EPS | New EPS | Diff (%) | Result
----------- | ------------ | ------- | -------- | ------
`broker` | 100000 | 66666.67 | -33333.33 (-33.33%) | :broken_heart:
`queue` | 125000 | 76923.08 | -48076.92 (-38.46%) | :broken_heart:
</details>


#### Package `apache` :&#43;1:(1) :green_heart:(0) :broken_heart:(1)
<details>
<summary>Expand to view</summary>

Data stream | Previous EPS | New EPS | Diff (%) | Result
----------- | ------------ | ------- | -------- | ------
`access` | 5434.78 | 2747.25 | -2687.53 (-49.45%) | :broken_heart:
</details>




#### Package `azure_openai` :&#43;1:(1) :green_heart:(0) :broken_heart:(1)
<details>
<summary>Expand to view</summary>

Data stream | Previous EPS | New EPS | Diff (%) | Result
----------- | ------------ | ------- | -------- | ------
`metrics` | 250000 | 166666.67 | -83333.33 (-33.33%) | :broken_heart:
</details>




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-07-08 13:27 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13373)
* Commit: 77948240747927e2054ad56f16cb0c82d2be3ccc

### Failed CI Steps
* [Check integrations apache](https://buildkite.com/elastic/integrations/builds/13373#01909282-f39a-494e-97e5-fbbd38705d74)

### History
* :broken_heart: [Build #13368](https://buildkite.com/elastic/integrations/builds/13368) failed 7496f014f848a4b3e2931d6e5311219fa012d3ad

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13373","number":13373,"commit":"77948240747927e2054ad56f16cb0c82d2be3ccc"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13368","number":13368,"commit":"7496f014f848a4b3e2931d6e5311219fa012d3ad"}],"number":13373}
buildkite-pr-comment-->

2024-07-08 13:42 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13376)
* Commit: e1ac24fab8263b7b29a2f01cd4ffb39c842e112c

### Failed CI Steps
* [Check integrations azure_application_insights](https://buildkite.com/elastic/integrations/builds/13376#01909291-3a02-414a-830c-cbce5c2ec905)

### History
* :broken_heart: [Build #13373](https://buildkite.com/elastic/integrations/builds/13373) failed 77948240747927e2054ad56f16cb0c82d2be3ccc
* :broken_heart: [Build #13368](https://buildkite.com/elastic/integrations/builds/13368) failed 7496f014f848a4b3e2931d6e5311219fa012d3ad

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13376","number":13376,"commit":"e1ac24fab8263b7b29a2f01cd4ffb39c842e112c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13373","number":13373,"commit":"77948240747927e2054ad56f16cb0c82d2be3ccc"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13368","number":13368,"commit":"7496f014f848a4b3e2931d6e5311219fa012d3ad"}],"number":13376}
buildkite-pr-comment-->

2024-07-09 04:53 UTC, Linu-Elias commented
/test

2024-07-09 05:00 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13390)
* Commit: e1ac24fab8263b7b29a2f01cd4ffb39c842e112c

### Failed CI Steps
* [Check integrations azure_application_insights](https://buildkite.com/elastic/integrations/builds/13390#019095d9-df2f-460d-b2f5-ddd32449dc97)

### History
* :broken_heart: [Build #13376](https://buildkite.com/elastic/integrations/builds/13376) failed e1ac24fab8263b7b29a2f01cd4ffb39c842e112c
* :broken_heart: [Build #13373](https://buildkite.com/elastic/integrations/builds/13373) failed 77948240747927e2054ad56f16cb0c82d2be3ccc
* :broken_heart: [Build #13368](https://buildkite.com/elastic/integrations/builds/13368) failed 7496f014f848a4b3e2931d6e5311219fa012d3ad

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13390","number":13390,"commit":"e1ac24fab8263b7b29a2f01cd4ffb39c842e112c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13376","number":13376,"commit":"e1ac24fab8263b7b29a2f01cd4ffb39c842e112c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13373","number":13373,"commit":"77948240747927e2054ad56f16cb0c82d2be3ccc"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13368","number":13368,"commit":"7496f014f848a4b3e2931d6e5311219fa012d3ad"}],"number":13390}
buildkite-pr-comment-->

2024-07-09 06:03 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13394)
* Commit: 71680bc23ba9f8cdae33eba216c1c74067300f35

### History
* :broken_heart: [Build #13390](https://buildkite.com/elastic/integrations/builds/13390) failed e1ac24fab8263b7b29a2f01cd4ffb39c842e112c
* :broken_heart: [Build #13376](https://buildkite.com/elastic/integrations/builds/13376) failed e1ac24fab8263b7b29a2f01cd4ffb39c842e112c
* :broken_heart: [Build #13373](https://buildkite.com/elastic/integrations/builds/13373) failed 77948240747927e2054ad56f16cb0c82d2be3ccc
* :broken_heart: [Build #13368](https://buildkite.com/elastic/integrations/builds/13368) failed 7496f014f848a4b3e2931d6e5311219fa012d3ad

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13394","number":13394,"commit":"71680bc23ba9f8cdae33eba216c1c74067300f35"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13390","number":13390,"commit":"e1ac24fab8263b7b29a2f01cd4ffb39c842e112c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13376","number":13376,"commit":"e1ac24fab8263b7b29a2f01cd4ffb39c842e112c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13373","number":13373,"commit":"77948240747927e2054ad56f16cb0c82d2be3ccc"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13368","number":13368,"commit":"7496f014f848a4b3e2931d6e5311219fa012d3ad"}],"number":13394}
buildkite-pr-comment-->

2024-07-09 07:15 UTC, harnish-elastic requested changes

2024-07-09 07:15 UTC, harnish-elastic commented on packages/activemq/changelog.yml
> +      type: bugfix
This should be an enhancement and not a bugfix. As well the minor version should be bump up. That means from `1.3.0` to `1.4.0`.

2024-07-09 07:19 UTC, harnish-elastic requested changes

2024-07-09 07:19 UTC, harnish-elastic commented on packages/apache_spark/data_stream/application/agent/stream/stream.yml.hbs
> +{{#if processors}}
Can we move this block before `jmx.mappings:` for better readability? If yes please do for all the packages those containing `jmx.mappings:`

2024-07-09 07:25 UTC, harnish-elastic commented on packages/activemq/changelog.yml
> +    - description: Add processor support for ActiveMQ broker, queue and topic.
Do we really need package names in the changelog.yml? Can we update the description as per below for all the packages?

`Add processor support for broker, queue and topic data streams.`

2024-07-09 07:33 UTC, Linu-Elias commented on packages/activemq/changelog.yml
> +      type: bugfix
we have an issue raised for this - #10393

2024-07-09 07:38 UTC, harnish-elastic commented on packages/activemq/changelog.yml
> +      type: bugfix
Yes I have checked that. Also please refer the similar PR changelog.yml https://github.com/elastic/integrations/pull/10068/files#diff-00f3cf7e7bdc77301b85e76a90835694b3cf5490056f5ec891b4086a1376ad92R2-R6

2024-07-09 08:15 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13400)
* Commit: e0a09cac62d5bb80cf7f41730580e4615383dfbf

### Failed CI Steps
* [Check integrations cockroachdb](https://buildkite.com/elastic/integrations/builds/13400#0190968c-4d0b-412c-8add-1f55abc6fd89)

### History
* :green_heart: [Build #13394](https://buildkite.com/elastic/integrations/builds/13394) succeeded 71680bc23ba9f8cdae33eba216c1c74067300f35
* :broken_heart: [Build #13390](https://buildkite.com/elastic/integrations/builds/13390) failed e1ac24fab8263b7b29a2f01cd4ffb39c842e112c
* :broken_heart: [Build #13376](https://buildkite.com/elastic/integrations/builds/13376) failed e1ac24fab8263b7b29a2f01cd4ffb39c842e112c
* :broken_heart: [Build #13373](https://buildkite.com/elastic/integrations/builds/13373) failed 77948240747927e2054ad56f16cb0c82d2be3ccc
* :broken_heart: [Build #13368](https://buildkite.com/elastic/integrations/builds/13368) failed 7496f014f848a4b3e2931d6e5311219fa012d3ad

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13400","number":13400,"commit":"e0a09cac62d5bb80cf7f41730580e4615383dfbf"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13394","number":13394,"commit":"71680bc23ba9f8cdae33eba216c1c74067300f35"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13390","number":13390,"commit":"e1ac24fab8263b7b29a2f01cd4ffb39c842e112c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13376","number":13376,"commit":"e1ac24fab8263b7b29a2f01cd4ffb39c842e112c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13373","number":13373,"commit":"77948240747927e2054ad56f16cb0c82d2be3ccc"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13368","number":13368,"commit":"7496f014f848a4b3e2931d6e5311219fa012d3ad"}],"number":13400}
buildkite-pr-comment-->

2024-07-09 08:54 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13402)
* Commit: a96fcc25e86aac7d879a17894298a1fec2e0fc65

### History
* :broken_heart: [Build #13400](https://buildkite.com/elastic/integrations/builds/13400) failed e0a09cac62d5bb80cf7f41730580e4615383dfbf
* :green_heart: [Build #13394](https://buildkite.com/elastic/integrations/builds/13394) succeeded 71680bc23ba9f8cdae33eba216c1c74067300f35
* :broken_heart: [Build #13390](https://buildkite.com/elastic/integrations/builds/13390) failed e1ac24fab8263b7b29a2f01cd4ffb39c842e112c
* :broken_heart: [Build #13376](https://buildkite.com/elastic/integrations/builds/13376) failed e1ac24fab8263b7b29a2f01cd4ffb39c842e112c
* :broken_heart: [Build #13373](https://buildkite.com/elastic/integrations/builds/13373) failed 77948240747927e2054ad56f16cb0c82d2be3ccc

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13402","number":13402,"commit":"a96fcc25e86aac7d879a17894298a1fec2e0fc65"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13400","number":13400,"commit":"e0a09cac62d5bb80cf7f41730580e4615383dfbf"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13394","number":13394,"commit":"71680bc23ba9f8cdae33eba216c1c74067300f35"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13390","number":13390,"commit":"e1ac24fab8263b7b29a2f01cd4ffb39c842e112c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13376","number":13376,"commit":"e1ac24fab8263b7b29a2f01cd4ffb39c842e112c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13373","number":13373,"commit":"77948240747927e2054ad56f16cb0c82d2be3ccc"}],"number":13402}
buildkite-pr-comment-->

2024-07-09 10:04 UTC, Linu-Elias commented on packages/activemq/changelog.yml
> +    - description: Add processor support for ActiveMQ broker, queue and topic.
Done

2024-07-09 10:04 UTC, Linu-Elias commented on packages/apache_spark/data_stream/application/agent/stream/stream.yml.hbs
> +{{#if processors}}
Done

2024-07-09 10:04 UTC, Linu-Elias commented on packages/activemq/changelog.yml
> +      type: bugfix
Done

2024-07-09 11:08 UTC, harnish-elastic approved these changes
LGTM! 🚀

2024-07-10 06:14 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13461)
* Commit: 9add968262a8019e77adaba51148bc1a410ba142

### Failed CI Steps
* [Check integrations apache_spark](https://buildkite.com/elastic/integrations/builds/13461#01909b43-36d4-4224-bfd7-5bdec97ccd86)
* [Check integrations cassandra](https://buildkite.com/elastic/integrations/builds/13461#01909b43-36df-44e5-be8b-7d8a9a28d895)

### History
* :green_heart: [Build #13402](https://buildkite.com/elastic/integrations/builds/13402) succeeded a96fcc25e86aac7d879a17894298a1fec2e0fc65
* :broken_heart: [Build #13400](https://buildkite.com/elastic/integrations/builds/13400) failed e0a09cac62d5bb80cf7f41730580e4615383dfbf
* :green_heart: [Build #13394](https://buildkite.com/elastic/integrations/builds/13394) succeeded 71680bc23ba9f8cdae33eba216c1c74067300f35
* :broken_heart: [Build #13390](https://buildkite.com/elastic/integrations/builds/13390) failed e1ac24fab8263b7b29a2f01cd4ffb39c842e112c
* :broken_heart: [Build #13376](https://buildkite.com/elastic/integrations/builds/13376) failed e1ac24fab8263b7b29a2f01cd4ffb39c842e112c
* :broken_heart: [Build #13373](https://buildkite.com/elastic/integrations/builds/13373) failed 77948240747927e2054ad56f16cb0c82d2be3ccc

cc @Linu-Elias

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13461","number":13461,"commit":"9add968262a8019e77adaba51148bc1a410ba142"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13402","number":13402,"commit":"a96fcc25e86aac7d879a17894298a1fec2e0fc65"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13400","number":13400,"commit":"e0a09cac62d5bb80cf7f41730580e4615383dfbf"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13394","number":13394,"commit":"71680bc23ba9f8cdae33eba216c1c74067300f35"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13390","number":13390,"commit":"e1ac24fab8263b7b29a2f01cd4ffb39c842e112c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13376","number":13376,"commit":"e1ac24fab8263b7b29a2f01cd4ffb39c842e112c"}],"number":13461}
buildkite-pr-comment-->

2024-07-10 06:41 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13462)
* Commit: 867e4bcb6a4a9700d146887b435722893f63133d

### History
* :broken_heart: [Build #13461](https://buildkite.com/elastic/integrations/builds/13461) failed 9add968262a8019e77adaba51148bc1a410ba142
* :green_heart: [Build #13402](https://buildkite.com/elastic/integrations/builds/13402) succeeded a96fcc25e86aac7d879a17894298a1fec2e0fc65
* :broken_heart: [Build #13400](https://buildkite.com/elastic/integrations/builds/13400) failed e0a09cac62d5bb80cf7f41730580e4615383dfbf
* :green_heart: [Build #13394](https://buildkite.com/elastic/integrations/builds/13394) succeeded 71680bc23ba9f8cdae33eba216c1c74067300f35
* :broken_heart: [Build #13390](https://buildkite.com/elastic/integrations/builds/13390) failed e1ac24fab8263b7b29a2f01cd4ffb39c842e112c

cc @Linu-Elias

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13462","number":13462,"commit":"867e4bcb6a4a9700d146887b435722893f63133d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13461","number":13461,"commit":"9add968262a8019e77adaba51148bc1a410ba142"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13402","number":13402,"commit":"a96fcc25e86aac7d879a17894298a1fec2e0fc65"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13400","number":13400,"commit":"e0a09cac62d5bb80cf7f41730580e4615383dfbf"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13394","number":13394,"commit":"71680bc23ba9f8cdae33eba216c1c74067300f35"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13390","number":13390,"commit":"e1ac24fab8263b7b29a2f01cd4ffb39c842e112c"}],"number":13462}
buildkite-pr-comment-->

2024-07-15 05:32 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13651)
* Commit: c2d43725fdea25857a3b4e21902b6eb2bc2a15cd

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/13651#0190b4df-a171-4a1b-83ce-b665e2003941)

### History
* :green_heart: [Build #13462](https://buildkite.com/elastic/integrations/builds/13462) succeeded 867e4bcb6a4a9700d146887b435722893f63133d
* :broken_heart: [Build #13461](https://buildkite.com/elastic/integrations/builds/13461) failed 9add968262a8019e77adaba51148bc1a410ba142
* :green_heart: [Build #13402](https://buildkite.com/elastic/integrations/builds/13402) succeeded a96fcc25e86aac7d879a17894298a1fec2e0fc65
* :broken_heart: [Build #13400](https://buildkite.com/elastic/integrations/builds/13400) failed e0a09cac62d5bb80cf7f41730580e4615383dfbf
* :green_heart: [Build #13394](https://buildkite.com/elastic/integrations/builds/13394) succeeded 71680bc23ba9f8cdae33eba216c1c74067300f35
* :broken_heart: [Build #13390](https://buildkite.com/elastic/integrations/builds/13390) failed e1ac24fab8263b7b29a2f01cd4ffb39c842e112c

cc @Linu-Elias

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13651","number":13651,"commit":"c2d43725fdea25857a3b4e21902b6eb2bc2a15cd"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13462","number":13462,"commit":"867e4bcb6a4a9700d146887b435722893f63133d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13461","number":13461,"commit":"9add968262a8019e77adaba51148bc1a410ba142"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13402","number":13402,"commit":"a96fcc25e86aac7d879a17894298a1fec2e0fc65"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13400","number":13400,"commit":"e0a09cac62d5bb80cf7f41730580e4615383dfbf"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13394","number":13394,"commit":"71680bc23ba9f8cdae33eba216c1c74067300f35"}],"number":13651}
buildkite-pr-comment-->

2024-07-15 07:03 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13652)
* Commit: 5598d3bd1982ee738449247a88f64aed6e41496b

### History
* :broken_heart: [Build #13651](https://buildkite.com/elastic/integrations/builds/13651) failed c2d43725fdea25857a3b4e21902b6eb2bc2a15cd
* :green_heart: [Build #13462](https://buildkite.com/elastic/integrations/builds/13462) succeeded 867e4bcb6a4a9700d146887b435722893f63133d
* :broken_heart: [Build #13461](https://buildkite.com/elastic/integrations/builds/13461) failed 9add968262a8019e77adaba51148bc1a410ba142
* :green_heart: [Build #13402](https://buildkite.com/elastic/integrations/builds/13402) succeeded a96fcc25e86aac7d879a17894298a1fec2e0fc65
* :broken_heart: [Build #13400](https://buildkite.com/elastic/integrations/builds/13400) failed e0a09cac62d5bb80cf7f41730580e4615383dfbf
* :green_heart: [Build #13394](https://buildkite.com/elastic/integrations/builds/13394) succeeded 71680bc23ba9f8cdae33eba216c1c74067300f35

cc @Linu-Elias

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13652","number":13652,"commit":"5598d3bd1982ee738449247a88f64aed6e41496b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13651","number":13651,"commit":"c2d43725fdea25857a3b4e21902b6eb2bc2a15cd"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13462","number":13462,"commit":"867e4bcb6a4a9700d146887b435722893f63133d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13461","number":13461,"commit":"9add968262a8019e77adaba51148bc1a410ba142"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13402","number":13402,"commit":"a96fcc25e86aac7d879a17894298a1fec2e0fc65"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13400","number":13400,"commit":"e0a09cac62d5bb80cf7f41730580e4615383dfbf"}],"number":13652}
buildkite-pr-comment-->

2024-07-17 06:14 UTC, Linu-Elias commented
@elastic/obs-infraobs-integrations hey, could someone take a look at this PR please?

2024-07-19 07:39 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13789)
* Commit: dc1e223609b775a35ddcc49a5038a429a0e17c22

### History
* :green_heart: [Build #13652](https://buildkite.com/elastic/integrations/builds/13652) succeeded 5598d3bd1982ee738449247a88f64aed6e41496b
* :broken_heart: [Build #13651](https://buildkite.com/elastic/integrations/builds/13651) failed c2d43725fdea25857a3b4e21902b6eb2bc2a15cd
* :green_heart: [Build #13462](https://buildkite.com/elastic/integrations/builds/13462) succeeded 867e4bcb6a4a9700d146887b435722893f63133d
* :broken_heart: [Build #13461](https://buildkite.com/elastic/integrations/builds/13461) failed 9add968262a8019e77adaba51148bc1a410ba142
* :green_heart: [Build #13402](https://buildkite.com/elastic/integrations/builds/13402) succeeded a96fcc25e86aac7d879a17894298a1fec2e0fc65
* :broken_heart: [Build #13400](https://buildkite.com/elastic/integrations/builds/13400) failed e0a09cac62d5bb80cf7f41730580e4615383dfbf

cc @Linu-Elias

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13789","number":13789,"commit":"dc1e223609b775a35ddcc49a5038a429a0e17c22"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13652","number":13652,"commit":"5598d3bd1982ee738449247a88f64aed6e41496b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13651","number":13651,"commit":"c2d43725fdea25857a3b4e21902b6eb2bc2a15cd"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13462","number":13462,"commit":"867e4bcb6a4a9700d146887b435722893f63133d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13461","number":13461,"commit":"9add968262a8019e77adaba51148bc1a410ba142"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13402","number":13402,"commit":"a96fcc25e86aac7d879a17894298a1fec2e0fc65"}],"number":13789}
buildkite-pr-comment-->

2024-07-19 08:13 UTC, devamanv approved these changes

2024-07-19 10:14 UTC, merged

2024-07-19 10:29 UTC, elasticmachine commented
Package activemq - 1.5.0 containing this change is available at https://epr.elastic.co/search?package=activemq

2024-07-19 10:29 UTC, elasticmachine commented
Package apache - 1.22.0 containing this change is available at https://epr.elastic.co/search?package=apache

2024-07-19 10:29 UTC, elasticmachine commented
Package apache_spark - 1.3.0 containing this change is available at https://epr.elastic.co/search?package=apache_spark

2024-07-19 10:29 UTC, elasticmachine commented
Package awsfargate - 1.2.0 containing this change is available at https://epr.elastic.co/search?package=awsfargate

2024-07-19 10:29 UTC, elasticmachine commented
Package azure_application_insights - 1.7.0 containing this change is available at https://epr.elastic.co/search?package=azure_application_insights

2024-07-19 10:29 UTC, elasticmachine commented
Package azure_billing - 1.7.0 containing this change is available at https://epr.elastic.co/search?package=azure_billing

2024-07-19 10:29 UTC, elasticmachine commented
Package azure_functions - 0.7.0 containing this change is available at https://epr.elastic.co/search?package=azure_functions

2024-07-19 10:29 UTC, elasticmachine commented
Package azure_openai - 1.3.0 containing this change is available at https://epr.elastic.co/search?package=azure_openai

2024-07-19 10:29 UTC, elasticmachine commented
Package cassandra - 1.15.0 containing this change is available at https://epr.elastic.co/search?package=cassandra

2024-07-19 10:29 UTC, elasticmachine commented
Package cockroachdb - 1.12.0 containing this change is available at https://epr.elastic.co/search?package=cockroachdb