[Amazon Security Lake] - OCSF v1.1 update with adding support for dynamic template and mappings
elastic/integrations pull request #10405
Opened 2024-07-08 08:20 UTC by ShourieG

## Type of change
- Enhancement

## Proposed commit message
With the upgrade of OCSF schemas, we are enhancing our support to meet compatibility requirements for OCSF v1.1. We are also reworking the ingest pipeline to incorporate dynamic templates and mappings to enable faster OCSF upgrades in future.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist
- [x] Added support for User Inventory Info class events.
- [x] Added Terraform based system tests ([requires elastic package change to work](https://github.com/elastic/elastic-package/issues/1917))
- [ ] Rework ingestion pipelines to incorporate dynamic templates and dynamic mappings.
- [ ] Add support for more event classes introduced in OCSF v1.1.
- [ ] Deprecate mappings no longer used.
- [ ] Update dashboards wherever required.
- [ ] Update documentation

## How to test this PR locally

## Related issues

- Closes #9607, #10219, #10266
- Relates #9607

## Screenshots

2024-07-08 08:33 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13350)
* Commit: 64f285b8c2cbaf32281d247c15c5ccf02eb0cc28

### Failed CI Steps
* [Check integrations amazon_security_lake](https://buildkite.com/elastic/integrations/builds/13350#01909172-1682-486f-8339-dfb9e5eb97de)

cc @ShourieG

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13350","number":13350,"commit":"64f285b8c2cbaf32281d247c15c5ccf02eb0cc28"}],"number":13350}
buildkite-pr-comment-->

2024-07-10 08:49 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13471)
* Commit: 118b2d2e7781686e3f11a1a4c5b8ea3d49f6b32e

### Failed CI Steps
* [Check integrations amazon_security_lake](https://buildkite.com/elastic/integrations/builds/13471#01909bce-7114-4576-8d3d-3f8b0c6de7ad)

### History
* :broken_heart: [Build #13350](https://buildkite.com/elastic/integrations/builds/13350) failed 64f285b8c2cbaf32281d247c15c5ccf02eb0cc28

cc @ShourieG

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13471","number":13471,"commit":"118b2d2e7781686e3f11a1a4c5b8ea3d49f6b32e"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13350","number":13350,"commit":"64f285b8c2cbaf32281d247c15c5ccf02eb0cc28"}],"number":13471}
buildkite-pr-comment-->

2024-07-12 12:43 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13612)
* Commit: 42822257dbfe8da222cd33b5c1db029aa6f8df9d

### Failed CI Steps
* [Check integrations amazon_security_lake](https://buildkite.com/elastic/integrations/builds/13612#0190a6f0-8751-4dff-a067-67cba66ea6ad)

### History
* :broken_heart: [Build #13471](https://buildkite.com/elastic/integrations/builds/13471) failed 118b2d2e7781686e3f11a1a4c5b8ea3d49f6b32e
* :broken_heart: [Build #13350](https://buildkite.com/elastic/integrations/builds/13350) failed 64f285b8c2cbaf32281d247c15c5ccf02eb0cc28

cc @ShourieG

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13612","number":13612,"commit":"42822257dbfe8da222cd33b5c1db029aa6f8df9d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13471","number":13471,"commit":"118b2d2e7781686e3f11a1a4c5b8ea3d49f6b32e"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13350","number":13350,"commit":"64f285b8c2cbaf32281d247c15c5ccf02eb0cc28"}],"number":13612}
buildkite-pr-comment-->

2024-07-30 14:43 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14143)
* Commit: 0656284100ca585bb62ae4726e4e740c7cf97dce

### Failed CI Steps
* [Check integrations amazon_security_lake](https://buildkite.com/elastic/integrations/builds/14143#01910414-353a-48c4-96bc-1aa4ab261c84)

### History
* :broken_heart: [Build #13612](https://buildkite.com/elastic/integrations/builds/13612) failed 42822257dbfe8da222cd33b5c1db029aa6f8df9d
* :broken_heart: [Build #13471](https://buildkite.com/elastic/integrations/builds/13471) failed 118b2d2e7781686e3f11a1a4c5b8ea3d49f6b32e
* :broken_heart: [Build #13350](https://buildkite.com/elastic/integrations/builds/13350) failed 64f285b8c2cbaf32281d247c15c5ccf02eb0cc28

cc @ShourieG

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14143","number":14143,"commit":"0656284100ca585bb62ae4726e4e740c7cf97dce"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13612","number":13612,"commit":"42822257dbfe8da222cd33b5c1db029aa6f8df9d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13471","number":13471,"commit":"118b2d2e7781686e3f11a1a4c5b8ea3d49f6b32e"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13350","number":13350,"commit":"64f285b8c2cbaf32281d247c15c5ccf02eb0cc28"}],"number":14143}
buildkite-pr-comment-->

2024-08-01 14:53 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14231)
* Commit: 8f7122dbfbc62f2f532563c8b559d17337401512

### Failed CI Steps
* [Check integrations amazon_security_lake](https://buildkite.com/elastic/integrations/builds/14231#01910e66-0486-42fb-9394-397318ff6361)

### History
* :broken_heart: [Build #14143](https://buildkite.com/elastic/integrations/builds/14143) failed 0656284100ca585bb62ae4726e4e740c7cf97dce
* :broken_heart: [Build #13612](https://buildkite.com/elastic/integrations/builds/13612) failed 42822257dbfe8da222cd33b5c1db029aa6f8df9d
* :broken_heart: [Build #13471](https://buildkite.com/elastic/integrations/builds/13471) failed 118b2d2e7781686e3f11a1a4c5b8ea3d49f6b32e
* :broken_heart: [Build #13350](https://buildkite.com/elastic/integrations/builds/13350) failed 64f285b8c2cbaf32281d247c15c5ccf02eb0cc28

cc @ShourieG

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14231","number":14231,"commit":"8f7122dbfbc62f2f532563c8b559d17337401512"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14143","number":14143,"commit":"0656284100ca585bb62ae4726e4e740c7cf97dce"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13612","number":13612,"commit":"42822257dbfe8da222cd33b5c1db029aa6f8df9d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13471","number":13471,"commit":"118b2d2e7781686e3f11a1a4c5b8ea3d49f6b32e"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13350","number":13350,"commit":"64f285b8c2cbaf32281d247c15c5ccf02eb0cc28"}],"number":14231}
buildkite-pr-comment-->

2024-08-02 12:19 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14268)
* Commit: 5352aac9fbe000e6d43ccf0fb215996a1f8fe4ae

### Failed CI Steps
* [Check integrations amazon_security_lake](https://buildkite.com/elastic/integrations/builds/14268#019112ff-695b-43ec-9631-c939210de008)

### History
* :broken_heart: [Build #14231](https://buildkite.com/elastic/integrations/builds/14231) failed 8f7122dbfbc62f2f532563c8b559d17337401512
* :broken_heart: [Build #14143](https://buildkite.com/elastic/integrations/builds/14143) failed 0656284100ca585bb62ae4726e4e740c7cf97dce
* :broken_heart: [Build #13612](https://buildkite.com/elastic/integrations/builds/13612) failed 42822257dbfe8da222cd33b5c1db029aa6f8df9d
* :broken_heart: [Build #13471](https://buildkite.com/elastic/integrations/builds/13471) failed 118b2d2e7781686e3f11a1a4c5b8ea3d49f6b32e
* :broken_heart: [Build #13350](https://buildkite.com/elastic/integrations/builds/13350) failed 64f285b8c2cbaf32281d247c15c5ccf02eb0cc28

cc @ShourieG

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14268","number":14268,"commit":"5352aac9fbe000e6d43ccf0fb215996a1f8fe4ae"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14231","number":14231,"commit":"8f7122dbfbc62f2f532563c8b559d17337401512"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14143","number":14143,"commit":"0656284100ca585bb62ae4726e4e740c7cf97dce"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13612","number":13612,"commit":"42822257dbfe8da222cd33b5c1db029aa6f8df9d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13471","number":13471,"commit":"118b2d2e7781686e3f11a1a4c5b8ea3d49f6b32e"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13350","number":13350,"commit":"64f285b8c2cbaf32281d247c15c5ccf02eb0cc28"}],"number":14268}
buildkite-pr-comment-->

2024-08-06 13:24 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14355)
* Commit: ac66e6ef08b9f5c74530276c97175f8aaaafed18

### Failed CI Steps
* [Check integrations amazon_security_lake](https://buildkite.com/elastic/integrations/builds/14355#019127d4-3642-42d3-9b1c-1a8a4e97bdec)

### History
* :broken_heart: [Build #14268](https://buildkite.com/elastic/integrations/builds/14268) failed 5352aac9fbe000e6d43ccf0fb215996a1f8fe4ae
* :broken_heart: [Build #14231](https://buildkite.com/elastic/integrations/builds/14231) failed 8f7122dbfbc62f2f532563c8b559d17337401512
* :broken_heart: [Build #14143](https://buildkite.com/elastic/integrations/builds/14143) failed 0656284100ca585bb62ae4726e4e740c7cf97dce
* :broken_heart: [Build #13612](https://buildkite.com/elastic/integrations/builds/13612) failed 42822257dbfe8da222cd33b5c1db029aa6f8df9d
* :broken_heart: [Build #13471](https://buildkite.com/elastic/integrations/builds/13471) failed 118b2d2e7781686e3f11a1a4c5b8ea3d49f6b32e

cc @ShourieG

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14355","number":14355,"commit":"ac66e6ef08b9f5c74530276c97175f8aaaafed18"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14268","number":14268,"commit":"5352aac9fbe000e6d43ccf0fb215996a1f8fe4ae"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14231","number":14231,"commit":"8f7122dbfbc62f2f532563c8b559d17337401512"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14143","number":14143,"commit":"0656284100ca585bb62ae4726e4e740c7cf97dce"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13612","number":13612,"commit":"42822257dbfe8da222cd33b5c1db029aa6f8df9d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13471","number":13471,"commit":"118b2d2e7781686e3f11a1a4c5b8ea3d49f6b32e"}],"number":14355}
buildkite-pr-comment-->

2024-08-06 14:50 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14369)
* Commit: 73b7be8c4a2416b0f934f85628f54681ea8bf02a

### Failed CI Steps
* [Check integrations amazon_security_lake](https://buildkite.com/elastic/integrations/builds/14369#01912823-5a24-4311-b744-38461789b5c9)

### History
* :broken_heart: [Build #14355](https://buildkite.com/elastic/integrations/builds/14355) failed ac66e6ef08b9f5c74530276c97175f8aaaafed18
* :broken_heart: [Build #14268](https://buildkite.com/elastic/integrations/builds/14268) failed 5352aac9fbe000e6d43ccf0fb215996a1f8fe4ae
* :broken_heart: [Build #14231](https://buildkite.com/elastic/integrations/builds/14231) failed 8f7122dbfbc62f2f532563c8b559d17337401512
* :broken_heart: [Build #14143](https://buildkite.com/elastic/integrations/builds/14143) failed 0656284100ca585bb62ae4726e4e740c7cf97dce
* :broken_heart: [Build #13612](https://buildkite.com/elastic/integrations/builds/13612) failed 42822257dbfe8da222cd33b5c1db029aa6f8df9d

cc @ShourieG

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14369","number":14369,"commit":"73b7be8c4a2416b0f934f85628f54681ea8bf02a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14355","number":14355,"commit":"ac66e6ef08b9f5c74530276c97175f8aaaafed18"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14268","number":14268,"commit":"5352aac9fbe000e6d43ccf0fb215996a1f8fe4ae"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14231","number":14231,"commit":"8f7122dbfbc62f2f532563c8b559d17337401512"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14143","number":14143,"commit":"0656284100ca585bb62ae4726e4e740c7cf97dce"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13612","number":13612,"commit":"42822257dbfe8da222cd33b5c1db029aa6f8df9d"}],"number":14369}
buildkite-pr-comment-->

2024-08-07 08:11 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14404)
* Commit: 1236584d0508b914523c00f1423ba838b1c19c72

### Failed CI Steps
* [Check integrations amazon_security_lake](https://buildkite.com/elastic/integrations/builds/14404#01912bdc-31df-4cee-903e-854c788ff1ac)

### History
* :broken_heart: [Build #14369](https://buildkite.com/elastic/integrations/builds/14369) failed 73b7be8c4a2416b0f934f85628f54681ea8bf02a
* :broken_heart: [Build #14355](https://buildkite.com/elastic/integrations/builds/14355) failed ac66e6ef08b9f5c74530276c97175f8aaaafed18
* :broken_heart: [Build #14268](https://buildkite.com/elastic/integrations/builds/14268) failed 5352aac9fbe000e6d43ccf0fb215996a1f8fe4ae
* :broken_heart: [Build #14231](https://buildkite.com/elastic/integrations/builds/14231) failed 8f7122dbfbc62f2f532563c8b559d17337401512
* :broken_heart: [Build #14143](https://buildkite.com/elastic/integrations/builds/14143) failed 0656284100ca585bb62ae4726e4e740c7cf97dce

cc @ShourieG

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14404","number":14404,"commit":"1236584d0508b914523c00f1423ba838b1c19c72"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14369","number":14369,"commit":"73b7be8c4a2416b0f934f85628f54681ea8bf02a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14355","number":14355,"commit":"ac66e6ef08b9f5c74530276c97175f8aaaafed18"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14268","number":14268,"commit":"5352aac9fbe000e6d43ccf0fb215996a1f8fe4ae"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14231","number":14231,"commit":"8f7122dbfbc62f2f532563c8b559d17337401512"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14143","number":14143,"commit":"0656284100ca585bb62ae4726e4e740c7cf97dce"}],"number":14404}
buildkite-pr-comment-->

2024-08-07 12:49 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14420)
* Commit: 03b509912c38455a1e26683de6c1f4ddec5d83da

### Failed CI Steps
* [Check integrations amazon_security_lake](https://buildkite.com/elastic/integrations/builds/14420#01912cda-7fa3-494c-acaf-d81391052ff9)

### History
* :broken_heart: [Build #14404](https://buildkite.com/elastic/integrations/builds/14404) failed 1236584d0508b914523c00f1423ba838b1c19c72
* :broken_heart: [Build #14369](https://buildkite.com/elastic/integrations/builds/14369) failed 73b7be8c4a2416b0f934f85628f54681ea8bf02a
* :broken_heart: [Build #14355](https://buildkite.com/elastic/integrations/builds/14355) failed ac66e6ef08b9f5c74530276c97175f8aaaafed18
* :broken_heart: [Build #14268](https://buildkite.com/elastic/integrations/builds/14268) failed 5352aac9fbe000e6d43ccf0fb215996a1f8fe4ae
* :broken_heart: [Build #14231](https://buildkite.com/elastic/integrations/builds/14231) failed 8f7122dbfbc62f2f532563c8b559d17337401512

cc @ShourieG

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14420","number":14420,"commit":"03b509912c38455a1e26683de6c1f4ddec5d83da"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14404","number":14404,"commit":"1236584d0508b914523c00f1423ba838b1c19c72"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14369","number":14369,"commit":"73b7be8c4a2416b0f934f85628f54681ea8bf02a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14355","number":14355,"commit":"ac66e6ef08b9f5c74530276c97175f8aaaafed18"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14268","number":14268,"commit":"5352aac9fbe000e6d43ccf0fb215996a1f8fe4ae"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14231","number":14231,"commit":"8f7122dbfbc62f2f532563c8b559d17337401512"}],"number":14420}
buildkite-pr-comment-->

2024-08-08 09:09 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14465)
* Commit: e99119c3110222fc1bda8476b6638a8a74bb24fe

### Failed CI Steps
* [Check integrations amazon_security_lake](https://buildkite.com/elastic/integrations/builds/14465#01913138-07ff-43bf-9c15-c2b6e8350a23)

### History
* :broken_heart: [Build #14420](https://buildkite.com/elastic/integrations/builds/14420) failed 03b509912c38455a1e26683de6c1f4ddec5d83da
* :broken_heart: [Build #14404](https://buildkite.com/elastic/integrations/builds/14404) failed 1236584d0508b914523c00f1423ba838b1c19c72
* :broken_heart: [Build #14369](https://buildkite.com/elastic/integrations/builds/14369) failed 73b7be8c4a2416b0f934f85628f54681ea8bf02a
* :broken_heart: [Build #14355](https://buildkite.com/elastic/integrations/builds/14355) failed ac66e6ef08b9f5c74530276c97175f8aaaafed18
* :broken_heart: [Build #14268](https://buildkite.com/elastic/integrations/builds/14268) failed 5352aac9fbe000e6d43ccf0fb215996a1f8fe4ae

cc @ShourieG

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14465","number":14465,"commit":"e99119c3110222fc1bda8476b6638a8a74bb24fe"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14420","number":14420,"commit":"03b509912c38455a1e26683de6c1f4ddec5d83da"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14404","number":14404,"commit":"1236584d0508b914523c00f1423ba838b1c19c72"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14369","number":14369,"commit":"73b7be8c4a2416b0f934f85628f54681ea8bf02a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14355","number":14355,"commit":"ac66e6ef08b9f5c74530276c97175f8aaaafed18"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14268","number":14268,"commit":"5352aac9fbe000e6d43ccf0fb215996a1f8fe4ae"}],"number":14465}
buildkite-pr-comment-->

2024-08-08 10:26 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14469)
* Commit: 7e5f687665c88ab5f6e9e14e50161143ac5f75ae

### Failed CI Steps
* [Check integrations amazon_security_lake](https://buildkite.com/elastic/integrations/builds/14469#0191317e-a49c-4492-94c7-5926c842b365)

### History
* :broken_heart: [Build #14465](https://buildkite.com/elastic/integrations/builds/14465) failed e99119c3110222fc1bda8476b6638a8a74bb24fe
* :broken_heart: [Build #14420](https://buildkite.com/elastic/integrations/builds/14420) failed 03b509912c38455a1e26683de6c1f4ddec5d83da
* :broken_heart: [Build #14404](https://buildkite.com/elastic/integrations/builds/14404) failed 1236584d0508b914523c00f1423ba838b1c19c72
* :broken_heart: [Build #14369](https://buildkite.com/elastic/integrations/builds/14369) failed 73b7be8c4a2416b0f934f85628f54681ea8bf02a
* :broken_heart: [Build #14355](https://buildkite.com/elastic/integrations/builds/14355) failed ac66e6ef08b9f5c74530276c97175f8aaaafed18

cc @ShourieG

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14469","number":14469,"commit":"7e5f687665c88ab5f6e9e14e50161143ac5f75ae"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14465","number":14465,"commit":"e99119c3110222fc1bda8476b6638a8a74bb24fe"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14420","number":14420,"commit":"03b509912c38455a1e26683de6c1f4ddec5d83da"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14404","number":14404,"commit":"1236584d0508b914523c00f1423ba838b1c19c72"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14369","number":14369,"commit":"73b7be8c4a2416b0f934f85628f54681ea8bf02a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14355","number":14355,"commit":"ac66e6ef08b9f5c74530276c97175f8aaaafed18"}],"number":14469}
buildkite-pr-comment-->

2024-08-08 11:55 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14472)
* Commit: 516b63b0d1d12feac4c2569a15222a4dea192d07

### Failed CI Steps
* [Check integrations amazon_security_lake](https://buildkite.com/elastic/integrations/builds/14472#019131d0-5e38-4a49-9dcf-cb1fb0ef511c)

### History
* :broken_heart: [Build #14469](https://buildkite.com/elastic/integrations/builds/14469) failed 7e5f687665c88ab5f6e9e14e50161143ac5f75ae
* :broken_heart: [Build #14465](https://buildkite.com/elastic/integrations/builds/14465) failed e99119c3110222fc1bda8476b6638a8a74bb24fe
* :broken_heart: [Build #14420](https://buildkite.com/elastic/integrations/builds/14420) failed 03b509912c38455a1e26683de6c1f4ddec5d83da
* :broken_heart: [Build #14404](https://buildkite.com/elastic/integrations/builds/14404) failed 1236584d0508b914523c00f1423ba838b1c19c72
* :broken_heart: [Build #14369](https://buildkite.com/elastic/integrations/builds/14369) failed 73b7be8c4a2416b0f934f85628f54681ea8bf02a

cc @ShourieG

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14472","number":14472,"commit":"516b63b0d1d12feac4c2569a15222a4dea192d07"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14469","number":14469,"commit":"7e5f687665c88ab5f6e9e14e50161143ac5f75ae"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14465","number":14465,"commit":"e99119c3110222fc1bda8476b6638a8a74bb24fe"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14420","number":14420,"commit":"03b509912c38455a1e26683de6c1f4ddec5d83da"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14404","number":14404,"commit":"1236584d0508b914523c00f1423ba838b1c19c72"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14369","number":14369,"commit":"73b7be8c4a2416b0f934f85628f54681ea8bf02a"}],"number":14472}
buildkite-pr-comment-->

2024-08-08 12:22 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14473)
* Commit: bf779a542ff6f3b2bbdf6a08070e654db7568886

### Failed CI Steps
* [Check integrations amazon_security_lake](https://buildkite.com/elastic/integrations/builds/14473#019131e7-d958-4294-a346-163db094a4f6)

### History
* :broken_heart: [Build #14472](https://buildkite.com/elastic/integrations/builds/14472) failed 516b63b0d1d12feac4c2569a15222a4dea192d07
* :broken_heart: [Build #14469](https://buildkite.com/elastic/integrations/builds/14469) failed 7e5f687665c88ab5f6e9e14e50161143ac5f75ae
* :broken_heart: [Build #14465](https://buildkite.com/elastic/integrations/builds/14465) failed e99119c3110222fc1bda8476b6638a8a74bb24fe
* :broken_heart: [Build #14420](https://buildkite.com/elastic/integrations/builds/14420) failed 03b509912c38455a1e26683de6c1f4ddec5d83da
* :broken_heart: [Build #14404](https://buildkite.com/elastic/integrations/builds/14404) failed 1236584d0508b914523c00f1423ba838b1c19c72

cc @ShourieG

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14473","number":14473,"commit":"bf779a542ff6f3b2bbdf6a08070e654db7568886"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14472","number":14472,"commit":"516b63b0d1d12feac4c2569a15222a4dea192d07"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14469","number":14469,"commit":"7e5f687665c88ab5f6e9e14e50161143ac5f75ae"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14465","number":14465,"commit":"e99119c3110222fc1bda8476b6638a8a74bb24fe"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14420","number":14420,"commit":"03b509912c38455a1e26683de6c1f4ddec5d83da"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14404","number":14404,"commit":"1236584d0508b914523c00f1423ba838b1c19c72"}],"number":14473}
buildkite-pr-comment-->

2024-08-08 12:40 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14475)
* Commit: 97459f5e8b2de504a47daa1b9559c65b9fb24d4e

### Failed CI Steps
* [Check integrations amazon_security_lake](https://buildkite.com/elastic/integrations/builds/14475#019131f8-c000-4904-9ba3-9064abd8dafb)

### History
* :broken_heart: [Build #14473](https://buildkite.com/elastic/integrations/builds/14473) failed bf779a542ff6f3b2bbdf6a08070e654db7568886
* :broken_heart: [Build #14472](https://buildkite.com/elastic/integrations/builds/14472) failed 516b63b0d1d12feac4c2569a15222a4dea192d07
* :broken_heart: [Build #14469](https://buildkite.com/elastic/integrations/builds/14469) failed 7e5f687665c88ab5f6e9e14e50161143ac5f75ae
* :broken_heart: [Build #14465](https://buildkite.com/elastic/integrations/builds/14465) failed e99119c3110222fc1bda8476b6638a8a74bb24fe
* :broken_heart: [Build #14420](https://buildkite.com/elastic/integrations/builds/14420) failed 03b509912c38455a1e26683de6c1f4ddec5d83da

cc @ShourieG

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14475","number":14475,"commit":"97459f5e8b2de504a47daa1b9559c65b9fb24d4e"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14473","number":14473,"commit":"bf779a542ff6f3b2bbdf6a08070e654db7568886"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14472","number":14472,"commit":"516b63b0d1d12feac4c2569a15222a4dea192d07"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14469","number":14469,"commit":"7e5f687665c88ab5f6e9e14e50161143ac5f75ae"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14465","number":14465,"commit":"e99119c3110222fc1bda8476b6638a8a74bb24fe"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14420","number":14420,"commit":"03b509912c38455a1e26683de6c1f4ddec5d83da"}],"number":14475}
buildkite-pr-comment-->

2024-08-08 13:04 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14478)
* Commit: bb88d570c4f7626b4297a7d0310648db299fc01d

### Failed CI Steps
* [Check integrations amazon_security_lake](https://buildkite.com/elastic/integrations/builds/14478#0191320f-508f-44ac-9a8c-23ba09327ab9)

### History
* :broken_heart: [Build #14475](https://buildkite.com/elastic/integrations/builds/14475) failed 97459f5e8b2de504a47daa1b9559c65b9fb24d4e
* :broken_heart: [Build #14473](https://buildkite.com/elastic/integrations/builds/14473) failed bf779a542ff6f3b2bbdf6a08070e654db7568886
* :broken_heart: [Build #14472](https://buildkite.com/elastic/integrations/builds/14472) failed 516b63b0d1d12feac4c2569a15222a4dea192d07
* :broken_heart: [Build #14469](https://buildkite.com/elastic/integrations/builds/14469) failed 7e5f687665c88ab5f6e9e14e50161143ac5f75ae
* :broken_heart: [Build #14465](https://buildkite.com/elastic/integrations/builds/14465) failed e99119c3110222fc1bda8476b6638a8a74bb24fe

cc @ShourieG

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14478","number":14478,"commit":"bb88d570c4f7626b4297a7d0310648db299fc01d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14475","number":14475,"commit":"97459f5e8b2de504a47daa1b9559c65b9fb24d4e"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14473","number":14473,"commit":"bf779a542ff6f3b2bbdf6a08070e654db7568886"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14472","number":14472,"commit":"516b63b0d1d12feac4c2569a15222a4dea192d07"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14469","number":14469,"commit":"7e5f687665c88ab5f6e9e14e50161143ac5f75ae"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14465","number":14465,"commit":"e99119c3110222fc1bda8476b6638a8a74bb24fe"}],"number":14478}
buildkite-pr-comment-->

2024-08-09 16:30 UTC, elasticmachine commented
Pinging @elastic/security-service-integrations (Team:Security-Service Integrations)

2024-08-09 16:42 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14525)
* Commit: 19ffbf7897fde115f81388e653008bfa506cd737

### Failed CI Steps
* [Check integrations amazon_security_lake](https://buildkite.com/elastic/integrations/builds/14525#019137fc-e9f5-4d96-8e96-eea17dcd706a)

### History
* :broken_heart: [Build #14478](https://buildkite.com/elastic/integrations/builds/14478) failed bb88d570c4f7626b4297a7d0310648db299fc01d
* :broken_heart: [Build #14475](https://buildkite.com/elastic/integrations/builds/14475) failed 97459f5e8b2de504a47daa1b9559c65b9fb24d4e
* :broken_heart: [Build #14473](https://buildkite.com/elastic/integrations/builds/14473) failed bf779a542ff6f3b2bbdf6a08070e654db7568886
* :broken_heart: [Build #14472](https://buildkite.com/elastic/integrations/builds/14472) failed 516b63b0d1d12feac4c2569a15222a4dea192d07
* :broken_heart: [Build #14469](https://buildkite.com/elastic/integrations/builds/14469) failed 7e5f687665c88ab5f6e9e14e50161143ac5f75ae

cc @ShourieG

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14525","number":14525,"commit":"19ffbf7897fde115f81388e653008bfa506cd737"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14478","number":14478,"commit":"bb88d570c4f7626b4297a7d0310648db299fc01d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14475","number":14475,"commit":"97459f5e8b2de504a47daa1b9559c65b9fb24d4e"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14473","number":14473,"commit":"bf779a542ff6f3b2bbdf6a08070e654db7568886"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14472","number":14472,"commit":"516b63b0d1d12feac4c2569a15222a4dea192d07"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14469","number":14469,"commit":"7e5f687665c88ab5f6e9e14e50161143ac5f75ae"}],"number":14525}
buildkite-pr-comment-->

2024-08-13 19:22 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14630)
* Commit: dd90df2d7ab685aead26fb4e87985644d7422fa7

### Failed CI Steps
* [Check integrations amazon_security_lake](https://buildkite.com/elastic/integrations/builds/14630#01914d29-6d20-499c-bccf-5da76e2f384d)

### History
* :broken_heart: [Build #14525](https://buildkite.com/elastic/integrations/builds/14525) failed 19ffbf7897fde115f81388e653008bfa506cd737
* :broken_heart: [Build #14478](https://buildkite.com/elastic/integrations/builds/14478) failed bb88d570c4f7626b4297a7d0310648db299fc01d
* :broken_heart: [Build #14475](https://buildkite.com/elastic/integrations/builds/14475) failed 97459f5e8b2de504a47daa1b9559c65b9fb24d4e
* :broken_heart: [Build #14473](https://buildkite.com/elastic/integrations/builds/14473) failed bf779a542ff6f3b2bbdf6a08070e654db7568886
* :broken_heart: [Build #14472](https://buildkite.com/elastic/integrations/builds/14472) failed 516b63b0d1d12feac4c2569a15222a4dea192d07

cc @ShourieG

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14630","number":14630,"commit":"dd90df2d7ab685aead26fb4e87985644d7422fa7"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14525","number":14525,"commit":"19ffbf7897fde115f81388e653008bfa506cd737"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14478","number":14478,"commit":"bb88d570c4f7626b4297a7d0310648db299fc01d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14475","number":14475,"commit":"97459f5e8b2de504a47daa1b9559c65b9fb24d4e"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14473","number":14473,"commit":"bf779a542ff6f3b2bbdf6a08070e654db7568886"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14472","number":14472,"commit":"516b63b0d1d12feac4c2569a15222a4dea192d07"}],"number":14630}
buildkite-pr-comment-->

2024-08-14 06:32 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14641)
* Commit: 360c3d8ecc9fc17e8f0205aef174e060442389b7

### Failed CI Steps
* [Check integrations amazon_security_lake](https://buildkite.com/elastic/integrations/builds/14641#01914f8e-5a28-4d17-ae35-4a77ebb7b04e)

### History
* :broken_heart: [Build #14630](https://buildkite.com/elastic/integrations/builds/14630) failed dd90df2d7ab685aead26fb4e87985644d7422fa7
* :broken_heart: [Build #14525](https://buildkite.com/elastic/integrations/builds/14525) failed 19ffbf7897fde115f81388e653008bfa506cd737
* :broken_heart: [Build #14478](https://buildkite.com/elastic/integrations/builds/14478) failed bb88d570c4f7626b4297a7d0310648db299fc01d
* :broken_heart: [Build #14475](https://buildkite.com/elastic/integrations/builds/14475) failed 97459f5e8b2de504a47daa1b9559c65b9fb24d4e
* :broken_heart: [Build #14473](https://buildkite.com/elastic/integrations/builds/14473) failed bf779a542ff6f3b2bbdf6a08070e654db7568886

cc @ShourieG

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14641","number":14641,"commit":"360c3d8ecc9fc17e8f0205aef174e060442389b7"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14630","number":14630,"commit":"dd90df2d7ab685aead26fb4e87985644d7422fa7"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14525","number":14525,"commit":"19ffbf7897fde115f81388e653008bfa506cd737"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14478","number":14478,"commit":"bb88d570c4f7626b4297a7d0310648db299fc01d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14475","number":14475,"commit":"97459f5e8b2de504a47daa1b9559c65b9fb24d4e"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14473","number":14473,"commit":"bf779a542ff6f3b2bbdf6a08070e654db7568886"}],"number":14641}
buildkite-pr-comment-->

2024-08-19 08:31 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-08-19 08:31 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14728)
* Commit: 22614312f73ad61f91b3479d39ed9e8c4b6a51d1

### History
* :broken_heart: [Build #14641](https://buildkite.com/elastic/integrations/builds/14641) failed 360c3d8ecc9fc17e8f0205aef174e060442389b7
* :broken_heart: [Build #14630](https://buildkite.com/elastic/integrations/builds/14630) failed dd90df2d7ab685aead26fb4e87985644d7422fa7
* :broken_heart: [Build #14525](https://buildkite.com/elastic/integrations/builds/14525) failed 19ffbf7897fde115f81388e653008bfa506cd737
* :broken_heart: [Build #14478](https://buildkite.com/elastic/integrations/builds/14478) failed bb88d570c4f7626b4297a7d0310648db299fc01d
* :broken_heart: [Build #14475](https://buildkite.com/elastic/integrations/builds/14475) failed 97459f5e8b2de504a47daa1b9559c65b9fb24d4e

cc @ShourieG

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14728","number":14728,"commit":"22614312f73ad61f91b3479d39ed9e8c4b6a51d1"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14641","number":14641,"commit":"360c3d8ecc9fc17e8f0205aef174e060442389b7"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14630","number":14630,"commit":"dd90df2d7ab685aead26fb4e87985644d7422fa7"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14525","number":14525,"commit":"19ffbf7897fde115f81388e653008bfa506cd737"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14478","number":14478,"commit":"bb88d570c4f7626b4297a7d0310648db299fc01d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14475","number":14475,"commit":"97459f5e8b2de504a47daa1b9559c65b9fb24d4e"}],"number":14728}
buildkite-pr-comment-->

2024-08-26 09:58 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15019)
* Commit: 5794401cbdd19c06ab9771621fa2409875a0de1f

### History
* :green_heart: [Build #14728](https://buildkite.com/elastic/integrations/builds/14728) succeeded 22614312f73ad61f91b3479d39ed9e8c4b6a51d1
* :broken_heart: [Build #14641](https://buildkite.com/elastic/integrations/builds/14641) failed 360c3d8ecc9fc17e8f0205aef174e060442389b7
* :broken_heart: [Build #14630](https://buildkite.com/elastic/integrations/builds/14630) failed dd90df2d7ab685aead26fb4e87985644d7422fa7
* :broken_heart: [Build #14525](https://buildkite.com/elastic/integrations/builds/14525) failed 19ffbf7897fde115f81388e653008bfa506cd737
* :broken_heart: [Build #14478](https://buildkite.com/elastic/integrations/builds/14478) failed bb88d570c4f7626b4297a7d0310648db299fc01d
* :broken_heart: [Build #14475](https://buildkite.com/elastic/integrations/builds/14475) failed 97459f5e8b2de504a47daa1b9559c65b9fb24d4e

cc @ShourieG

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15019","number":15019,"commit":"5794401cbdd19c06ab9771621fa2409875a0de1f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14728","number":14728,"commit":"22614312f73ad61f91b3479d39ed9e8c4b6a51d1"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14641","number":14641,"commit":"360c3d8ecc9fc17e8f0205aef174e060442389b7"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14630","number":14630,"commit":"dd90df2d7ab685aead26fb4e87985644d7422fa7"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14525","number":14525,"commit":"19ffbf7897fde115f81388e653008bfa506cd737"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14478","number":14478,"commit":"bb88d570c4f7626b4297a7d0310648db299fc01d"}],"number":15019}
buildkite-pr-comment-->

2024-09-25 08:55 UTC, chrisberkhout reviewed
Couple of general comments.

I looked at the README and dashboard diffs.

2024-09-26 02:32 UTC, efd6 reviewed
There is a lot of colour and movement in this change which makes it difficult to be confident of the review. I have looked at:
- [updated root org templates](https://github.com/elastic/integrations/pull/10405/commits/f784e757cfbcd01a858542584c9e5a048064a149)
- [reworked 'org' object mapping as tynamic template for all data streams](https://github.com/elastic/integrations/pull/10405/commits/42822257dbfe8da222cd33b5c1db029aa6f8df9d)
- [segregated process fields in 'findings', added 'actor' fields for new class support, ignore \_dev folder](https://github.com/elastic/integrations/pull/10405/commits/32ed1027968d41eda13e9dbb2604a085002ecee1)
- [added fulnerability findings support and segregated 'resource' group into it's own file](https://github.com/elastic/integrations/pull/10405/commits/78c1ea2ab6450bbab7a46da77e9b00b41ecf8876)
- [added ntp activity event class, deprecated proxy event class, aded proxy_endpoint field, uupdated network activity class and segregated endpoint event mappings into separate files across all data streams. updated ocsf object as necessary across respective data streams](https://github.com/elastic/integrations/pull/10405/commits/8f7122dbfbc62f2f532563c8b559d17337401512)
- [added os patch state event class, segregated device fields across all data streams, added new fields to support newly added event class](https://github.com/elastic/integrations/pull/10405/commits/5352aac9fbe000e6d43ccf0fb215996a1f8fe4ae)
- [added datastore activity event class, segregated actor, user & metadata fields across all data streams, flattened ldap fields in event data stream to make room for more fields](https://github.com/elastic/integrations/pull/10405/commits/ac66e6ef08b9f5c74530276c97175f8aaaafed18)
- [added support for detection finding event class, segregated and mapped finding_info in findings data stream](https://github.com/elastic/integrations/pull/10405/commits/73b7be8c4a2416b0f934f85628f54681ea8bf02a)
- [added support of compliance finding event class, segregated and updated resources object group, added new objects as required](https://github.com/elastic/integrations/pull/10405/commits/1236584d0508b914523c00f1423ba838b1c19c72)
- [segregated and expanded api object across all data streams, added support for incitent findings event class](https://github.com/elastic/integrations/pull/10405/commits/03b509912c38455a1e26683de6c1f4ddec5d83da)
- [added support for Device Config State Change event class, updated schema version in comment and dashboard links to 1.1.0](https://github.com/elastic/integrations/pull/10405/commits/e99119c3110222fc1bda8476b6638a8a74bb24fe)
- [added support for scan activity event class](https://github.com/elastic/integrations/pull/10405/commits/7e5f687665c88ab5f6e9e14e50161143ac5f75ae)
- [segregated file fields across required data streams, added support for file hosting activity class](https://github.com/elastic/integrations/pull/10405/commits/516b63b0d1d12feac4c2569a15222a4dea192d07)
- [added cwe & epss objects as flattened to cve object](https://github.com/elastic/integrations/pull/10405/commits/bf779a542ff6f3b2bbdf6a08070e654db7568886)
- [converted feature object to follow dynamic mapping rules across all data streams](https://github.com/elastic/integrations/pull/10405/commits/97459f5e8b2de504a47daa1b9559c65b9fb24d4e)
- [converted feature object to follow dynamic mapping rules across all data streams](https://github.com/elastic/integrations/pull/10405/commits/97459f5e8b2de504a47daa1b9559c65b9fb24d4e)
- [added some missing fields after locally running system tests for discovery datastream](https://github.com/elastic/integrations/pull/10405/commits/f0fdc329e76fd6f3f2f25e681bc4b9d91b342159)
- [reworked terrform deployer to support multi-bucket based system tests](https://github.com/elastic/integrations/pull/10405/commits/0b356dc9944cace73cdd5bb519f21bcea2c765c9)
- [updated docs and changelog](https://github.com/elastic/integrations/pull/10405/commits/19ffbf7897fde115f81388e653008bfa506cd737)
- [fixed timestamp issues across all data streams, added all system tests and updated missing mappings accorgingly](https://github.com/elastic/integrations/pull/10405/commits/dd90df2d7ab685aead26fb4e87985644d7422fa7)

There are a variety of comments and suggestions. I'll take another look again tomorrow.

2024-09-26 02:32 UTC, efd6 commented on packages/amazon_security_lake/data_stream/event/elasticsearch/ingest_pipeline/default.yml
> +                  return timestamp * 1000;  // Convert seconds to milliseconds
This is more expensive than necessary.
```
        def convertToMilliseconds(long timestamp) {
              if ((long)1e19 - 1 < timestamp) {
                  throw new IllegalArgumentException("Timestamp format not recognized: " + timestamp);
              } else if ((long)1e16 - 1 < timestamp) {
                  return timestamp / 1000000;  // Convert nanoseconds to milliseconds
              } else if ((long)1e13 - 1 < timestamp) {
                  return timestamp / 1000;  // Convert microseconds to milliseconds
              } else if ((long)1e10 - 1 < timestamp) {
                  return timestamp;  // Already in milliseconds, no conversion needed
              } else {
                  return timestamp * 1000;  // Convert seconds to milliseconds
              }
        }
```
or alternatively (and cleaner IMO)
```
        def convertToMilliseconds(long timestamp) {
              if (timestamp < (long)1e10) {
                  return timestamp * (long)1e3;  // Convert seconds to milliseconds
              }
              long t = timestamp;
              // Find first milli-, micro- or nano second-sane value in multiple-steps
              // of 1000.
              for (int i = 0; i < 3; i++) {
                  if ((long)1e13 - 1  < t) {
                      return t;
                  }
                  t /= (long)1e3
              }
              throw new IllegalArgumentException("Timestamp format not recognized: " + timestamp);
        }
```

2024-09-26 05:50 UTC, ShourieG commented on packages/amazon_security_lake/data_stream/discovery/fields/user-fields.yml
> +              type: integer
OCSF schema defines type_id as an integer, if we define it as keyword we need to convert manually from int to string on our end.

2024-09-26 06:02 UTC, ShourieG commented on packages/amazon_security_lake/data_stream/event/elasticsearch/ingest_pipeline/default.yml
> +      if: ctx.ocsf?.class_uid != null && ['2001', '2002','2003','2004'].contains(ctx.ocsf.class_uid)
no point in having tests for separate classes unless the system tests are activated, currently pipeline tests are by category and if we add more pipeline tests the central event data stream fields will go out of bounds since it will require those mappings to be defined and we are already at field limits with that. It's all defined for the actual data streams but we need system tests to work before we add these tests. I have tested with sample data locally though and it was a success.

2024-09-26 06:06 UTC, ShourieG commented on packages/amazon_security_lake/data_stream/event/fields/fields.yml
> +            - name: kb_article_list
It's an array of objects - https://schema.ocsf.io/1.1.0/objects/kb_article?extensions=linux,win

2024-09-26 06:09 UTC, ShourieG commented on packages/amazon_security_lake/data_stream/event/fields/fields.yml
> +          type: keyword
It's defined as an array though, sample response: 
```json
{"desc":"distinguished supervision stewart","kb_articles":["mentioned devon backgrounds","bmw destroyed pot"]}
```

2024-09-26 06:11 UTC, ShourieG commented on packages/amazon_security_lake/data_stream/application_activity/fields/fields.yml
> +    - name: num_*
yup this works

2024-09-26 06:13 UTC, efd6 commented on packages/amazon_security_lake/data_stream/discovery/fields/user-fields.yml
> +              type: integer
Keywords can be numeric.

2024-09-26 06:14 UTC, efd6 commented on packages/amazon_security_lake/data_stream/event/elasticsearch/ingest_pipeline/default.yml
> +      if: ctx.ocsf?.class_uid != null && ['2001', '2002','2003','2004'].contains(ctx.ocsf.class_uid)
OK

2024-09-26 06:15 UTC, efd6 commented on packages/amazon_security_lake/data_stream/event/fields/fields.yml
> +            - name: kb_article_list
The references are strings from that second link.

2024-09-26 06:16 UTC, ShourieG commented on packages/amazon_security_lake/data_stream/findings/fields/_dev/fields.yml
which line?

2024-09-26 06:16 UTC, efd6 commented on packages/amazon_security_lake/data_stream/event/fields/fields.yml
> +          type: keyword
The references are noted as strings in the spec.

2024-09-26 06:18 UTC, efd6 commented on packages/amazon_security_lake/data_stream/findings/fields/_dev/fields.yml
OK

2024-09-26 06:21 UTC, ShourieG commented on packages/amazon_security_lake/data_stream/discovery/fields/user-fields.yml
> +              type: integer
I remember having it as a keyword in the beginning and then encountered type errors while running tests. I'll revisit once again and check.

2024-09-26 06:25 UTC, ShourieG commented on packages/amazon_security_lake/data_stream/event/fields/fields.yml
> +          type: keyword
Yes the spec says so but I've seen it's not honoured always, the generator they have in the sample data generates actual objects. I'm guessing they have a live schema behind that is doing this work, not sure so this is a tricky one.

2024-09-26 06:26 UTC, ShourieG commented on packages/amazon_security_lake/data_stream/event/fields/fields.yml
> +            - name: kb_article_list
The generator they have in the sample data generates actual objects. I'm guessing they have a live schema behind that is doing this work, not sure so this is a tricky one.

2024-09-26 06:33 UTC, ShourieG commented on packages/amazon_security_lake/data_stream/event/fields/fields.yml
> +          type: keyword
So a keyword should handle the string array. At least from from my testing it seems to.

2024-09-26 06:34 UTC, ShourieG commented on packages/amazon_security_lake/data_stream/event/fields/fields.yml
> +            - name: kb_article_list
type:keyword seems to be handling the string arrays

2024-09-26 06:57 UTC, efd6 commented on packages/amazon_security_lake/data_stream/discovery/fields/user-fields.yml
> +              type: integer
You will need to annotate the fields in `numeric_keyword_fields` in the test configs.

2024-10-21 06:51 UTC, ShourieG commented on packages/amazon_security_lake/data_stream/event/elasticsearch/ingest_pipeline/default.yml
> +                  return timestamp * 1000;  // Convert seconds to milliseconds
@efd6, so the alternative version here has some issues and is throwing **Timestamp format not recognized:** in most of the scenarios, so going with the initial suggested one.

2024-10-21 07:28 UTC, ShourieG commented
@efd6, I've updated the PR with the suggested changes

2024-10-21 07:41 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17391)
* Commit: 06209ba02a64ae39f7c68be8d0cf63662b82c5ba

### History
* :green_heart: [Build #15019](https://buildkite.com/elastic/integrations/builds/15019) succeeded 5794401cbdd19c06ab9771621fa2409875a0de1f
* :green_heart: [Build #14728](https://buildkite.com/elastic/integrations/builds/14728) succeeded 22614312f73ad61f91b3479d39ed9e8c4b6a51d1
* :broken_heart: [Build #14641](https://buildkite.com/elastic/integrations/builds/14641) failed 360c3d8ecc9fc17e8f0205aef174e060442389b7
* :broken_heart: [Build #14630](https://buildkite.com/elastic/integrations/builds/14630) failed dd90df2d7ab685aead26fb4e87985644d7422fa7
* :broken_heart: [Build #14525](https://buildkite.com/elastic/integrations/builds/14525) failed 19ffbf7897fde115f81388e653008bfa506cd737
* :broken_heart: [Build #14478](https://buildkite.com/elastic/integrations/builds/14478) failed bb88d570c4f7626b4297a7d0310648db299fc01d

cc @ShourieG

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17391","number":17391,"commit":"06209ba02a64ae39f7c68be8d0cf63662b82c5ba"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15019","number":15019,"commit":"5794401cbdd19c06ab9771621fa2409875a0de1f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14728","number":14728,"commit":"22614312f73ad61f91b3479d39ed9e8c4b6a51d1"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14641","number":14641,"commit":"360c3d8ecc9fc17e8f0205aef174e060442389b7"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14630","number":14630,"commit":"dd90df2d7ab685aead26fb4e87985644d7422fa7"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14525","number":14525,"commit":"19ffbf7897fde115f81388e653008bfa506cd737"}],"number":17391}
buildkite-pr-comment-->

2024-10-21 08:41 UTC, efd6 commented on packages/amazon_security_lake/data_stream/event/elasticsearch/ingest_pipeline/default.yml
> +                  return timestamp * 1000;  // Convert seconds to milliseconds
They can be made logically equivalent. The first one is by far the uglier of the two.

2024-10-21 08:52 UTC, efd6 approved these changes
LGTM but please wait for @chrisberkhout

2024-10-21 12:24 UTC, chrisberkhout commented on packages/amazon_security_lake/data_stream/event/elasticsearch/ingest_pipeline/default.yml
> +                  return timestamp * 1000;  // Convert seconds to milliseconds
I think this has the wrong comparison operator: `if ((long)1e13 - 1  < t)`.
The loop is shrinking `t`, but the exit condition is checking for `t` being larger than `1e13`.

I see the elegance of the second version, but the first version is easier to read.

2024-10-21 16:13 UTC, chrisberkhout requested changes
I checked over the things I raised when I started a review earlier, and Dan's comments, and had a quick look at everything else, focusing on the field definition files, the testing setup and just checking the general structure of things.

No big issues. Please feel free to disagree with me on points I've raised. This seems pretty done.

2024-10-21 16:13 UTC, chrisberkhout commented on packages/amazon_security_lake/data_stream/event/_dev/deploy/tf/env.yml
> +version: '2.3'
I'm a bit confused about the use of the deploy setup because I don't see any system tests at the moment. Is this for use by system tests that will be added in the future?

I know about the changes planned in https://github.com/elastic/elastic-package/issues/2109, but in the mean time I think you can have a system test for the `event` data stream. If no events are supposed to actually go there you assert that and then it'll still show that routing rules are sending them somewhere.

At least that's what I was able to do for this other draft PR https://github.com/elastic/integrations/pull/11478.

2024-10-21 16:13 UTC, chrisberkhout commented on packages/amazon_security_lake/data_stream/event/elasticsearch/ingest_pipeline/default.yml
> +        - aws
Is removal of `aws` just general cleanup?

If so, I think it should be moved to a separate remove processor, since this one has the condition `if: ctx.tags == null || !(ctx.tags.contains('preserve_duplicate_custom_fields'))`, so it's job is to remove things that were mapped to ECS.

2024-10-21 16:13 UTC, chrisberkhout commented on packages/amazon_security_lake/data_stream/event/elasticsearch/ingest_pipeline/default.yml
> +        - aws
I don't see `aws` used elsewhere in the pipeline or in the agent config. Where does it come from?

2024-10-22 12:56 UTC, ShourieG commented on packages/amazon_security_lake/data_stream/application_activity/manifest.yml
> +  dynamic_namespace: true
according to the info I could find, if we are using dynamic mapping/templates in any data streams we need to set dynamic_dataset: true, and this seems to be specific to data streams.

What I found searching online: 
dynamic_dataset: true -> The dataset is dynamically determined based on the data, allowing for flexible data categorization.

dynamic_namespace: true -> The namespace is dynamically determined, allowing for flexible grouping of data into different namespaces based on the data's context.

dynamic_namespace: true allows us to map to indices like {{type}}-*-* dynamically based on the {{type}} defined in the manifest. Having this in gives us a lot of flexibility so that if a specific data stream needs to go in a different name space or if we for some reason want to change the namespace, we could do that by just changing the "type" in the manifest.

2024-10-22 13:11 UTC, ShourieG commented on packages/amazon_security_lake/data_stream/event/_dev/deploy/tf/env.yml
> +version: '2.3'
So the terraform files are a placeholder for future system tests which are to be implemented. I initially had the tests in place but had to remove them cause of elastic-package limitations. Assertions don't work with the reroute processor, I've tried this and the there are no hit's recorded in the event data stream cause of the routing. Hence system tests were removed, but this has been preserved for a future implementation.

2024-10-22 13:36 UTC, ShourieG commented on packages/amazon_security_lake/data_stream/event/_dev/test/pipeline/test-iam.log-expected.json
> +                        "type_id": 99,
So I saw there are some existing pipeline logic blocks that explicitly convert type_id to string, I'm not sure about the reasoning behind it though. I'll have to catchup with Crest on this to understand why this was done. I personally don't see any reason for this we are defining it as a keyword.

2024-10-22 13:39 UTC, ShourieG commented on packages/amazon_security_lake/data_stream/event/fields/actor-fields.yml
why rename actor-fields.yml -> actor-fields-flattened.yml ? It's not all flattened atm, only at some levels.

2024-10-22 13:52 UTC, chrisberkhout commented on packages/amazon_security_lake/data_stream/event/fields/actor-fields.yml
The idea is to just rename the one `actor-fields.yml` that is different from the others:
```bash
find -name actor-fields.yml | xargs md5sum | sort
```
```
d3be39838874f52be40b1866ab1841dd  ./data_stream/event/fields/actor-fields.yml
e8fb7cc36a8b0dc19a8a20aacf767031  ./data_stream/application_activity/fields/actor-fields.yml
e8fb7cc36a8b0dc19a8a20aacf767031  ./data_stream/discovery/fields/actor-fields.yml
e8fb7cc36a8b0dc19a8a20aacf767031  ./data_stream/findings/fields/actor-fields.yml
e8fb7cc36a8b0dc19a8a20aacf767031  ./data_stream/iam/fields/actor-fields.yml
e8fb7cc36a8b0dc19a8a20aacf767031  ./data_stream/network_activity/fields/actor-fields.yml
e8fb7cc36a8b0dc19a8a20aacf767031  ./data_stream/system_activity/fields/actor-fields.yml
```

2024-10-22 13:57 UTC, chrisberkhout commented on packages/amazon_security_lake/data_stream/event/_dev/test/pipeline/test-iam.log-expected.json
> +                        "type_id": 99,
Okay. 
I think it's important that the incoming data is compatible with the OCSF schema (so they're valid OCSF documents).
The indexing choices discussed earlier seem fine. If no conversion is necessary for that, then I wouldn't do any, even if the pipeline output has a non-intuitive type.

2024-10-22 13:59 UTC, chrisberkhout commented on packages/amazon_security_lake/data_stream/event/_dev/deploy/tf/env.yml
> +version: '2.3'
Okay. Optionally you could add a system test for the `event` DS with `assert.hit_count: 0`. That would make sure that the routing rules are correctly sending the events elsewhere.

2024-10-23 08:15 UTC, chrisberkhout commented
I forgot to mention, regarding `type: keyword` for arrays of strings...

Elasticsearch will always let you provide an array of values rather than a single value.

ECS can say that a field should be array rather than a single value ([example](https://github.com/elastic/ecs/blob/4fa0abdf5db87abc91791b9a0093b371cc696032/schemas/base.yml#L51-L52)) and `elastic-package` will enforce that ([doc](https://github.com/elastic/elastic-package/blob/9f7d00b6/docs/howto/update_major_package_spec.md#field--is-not-normalized-as-expected-expected-array-found-)), but Elasticsearch doesn't require anything different in field definitions.

That may gradually change in the future: [[Meta] Better handling of single-valued fields elasticsearch#80825](https://github.com/elastic/elasticsearch/issues/80825).

2024-10-23 10:31 UTC, ShourieG commented on packages/amazon_security_lake/data_stream/event/fields/actor-fields.yml
for base-fields being the way they are I think is a standard practice across all existing integrations, should we really deviate from that ?

2024-10-23 10:36 UTC, chrisberkhout commented on packages/amazon_security_lake/data_stream/event/fields/actor-fields.yml
I haven't seen anything documented about that, but yeah if you leave that out, then `base-fields.yml` and `fields.yml` are the two that differ, and all others are identical wherever they're used. That seems good. Also `base-fields.yml` isn't very long, so there's less value in extracting the duplication from it.

2024-10-23 12:12 UTC, ShourieG commented
@chrisberkhout, I've addressed all the PR suggestions except the system tests. Tests don't seem to be terminating with assert.hit_count: 0, so I've not updated that as of yet and I feel it would be better to do with the elastic package changes since we can have actual working system tests then.

2024-10-23 12:29 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17493)
* Commit: 69b2f19fc0dcd18d4291fa1e3e2affcea7beee3b

### History
* :green_heart: [Build #17391](https://buildkite.com/elastic/integrations/builds/17391) succeeded 06209ba02a64ae39f7c68be8d0cf63662b82c5ba
* :green_heart: [Build #15019](https://buildkite.com/elastic/integrations/builds/15019) succeeded 5794401cbdd19c06ab9771621fa2409875a0de1f
* :green_heart: [Build #14728](https://buildkite.com/elastic/integrations/builds/14728) succeeded 22614312f73ad61f91b3479d39ed9e8c4b6a51d1
* :broken_heart: [Build #14641](https://buildkite.com/elastic/integrations/builds/14641) failed 360c3d8ecc9fc17e8f0205aef174e060442389b7
* :broken_heart: [Build #14630](https://buildkite.com/elastic/integrations/builds/14630) failed dd90df2d7ab685aead26fb4e87985644d7422fa7
* :broken_heart: [Build #14525](https://buildkite.com/elastic/integrations/builds/14525) failed 19ffbf7897fde115f81388e653008bfa506cd737

cc @ShourieG

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17493","number":17493,"commit":"69b2f19fc0dcd18d4291fa1e3e2affcea7beee3b"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17391","number":17391,"commit":"06209ba02a64ae39f7c68be8d0cf63662b82c5ba"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15019","number":15019,"commit":"5794401cbdd19c06ab9771621fa2409875a0de1f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14728","number":14728,"commit":"22614312f73ad61f91b3479d39ed9e8c4b6a51d1"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14641","number":14641,"commit":"360c3d8ecc9fc17e8f0205aef174e060442389b7"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14630","number":14630,"commit":"dd90df2d7ab685aead26fb4e87985644d7422fa7"}],"number":17493}
buildkite-pr-comment-->

2024-10-23 13:53 UTC, chrisberkhout approved these changes
:ship:

2024-10-23 14:04 UTC, merged