fix Grok pattern Failure
elastic/integrations pull request #10412
Opened 2024-07-08 13:15 UTC by kush-elastic

- Enhancement

## Description
log_destination (string)
PostgreSQL supports several methods for logging server messages, including stderr, csvlog, jsonlog, and syslog. On Windows, eventlog is also supported. Set this parameter to a list of desired log destinations separated by commas. The default is to log to stderr only. This parameter can only be set in the postgresql.conf file or on the server command line.
cf.https://www.postgresql.org/docs/current/runtime-config-logging.html

raw message example :

```
[3192491]: [50743-1] db=,user=,app=,client= WARNING:  archiving write-ahead log file "00000001000018920000000D" failed too many times, will try again later
```

2024-07-08 13:33 UTC, elasticmachine commented
### :rocket: Benchmarks report


#### Package `postgresql` :&#43;1:(0) :green_heart:(0) :broken_heart:(1)
<details>
<summary>Expand to view</summary>

Data stream | Previous EPS | New EPS | Diff (%) | Result
----------- | ------------ | ------- | -------- | ------
`log` | 4255.32 | 3546.1 | -709.22 (-16.67%) | :broken_heart:
</details>


To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-07-08 13:34 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13372)
* Commit: 3193b5e0a2ae4c5424bb3eaddfb2d57e7faab156

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13372","number":13372,"commit":"3193b5e0a2ae4c5424bb3eaddfb2d57e7faab156"}],"number":13372}
buildkite-pr-comment-->

2024-07-11 06:12 UTC, harnish-elastic approved these changes
LGTM! 🚀

Please resolve merge conflicts!

2024-07-11 07:38 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13524)
* Commit: 358e1df4b35343330e8123817745336efa321c35

### Failed CI Steps
* [Check integrations postgresql](https://buildkite.com/elastic/integrations/builds/13524#0190a0b6-8f9e-49b6-93a6-b53f64ee68a8)

### History
* :green_heart: [Build #13372](https://buildkite.com/elastic/integrations/builds/13372) succeeded 3193b5e0a2ae4c5424bb3eaddfb2d57e7faab156

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13524","number":13524,"commit":"358e1df4b35343330e8123817745336efa321c35"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13372","number":13372,"commit":"3193b5e0a2ae4c5424bb3eaddfb2d57e7faab156"}],"number":13524}
buildkite-pr-comment-->

2024-07-24 09:58 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13918)
* Commit: b44a79e7eae03a3b296647c0ddbc127a77abb1ad

### Failed CI Steps
* [Check integrations postgresql](https://buildkite.com/elastic/integrations/builds/13918#0190e428-8b00-4ec9-8857-564006ae3515)

### History
* :broken_heart: [Build #13524](https://buildkite.com/elastic/integrations/builds/13524) failed 358e1df4b35343330e8123817745336efa321c35
* :green_heart: [Build #13372](https://buildkite.com/elastic/integrations/builds/13372) succeeded 3193b5e0a2ae4c5424bb3eaddfb2d57e7faab156

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13918","number":13918,"commit":"b44a79e7eae03a3b296647c0ddbc127a77abb1ad"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13524","number":13524,"commit":"358e1df4b35343330e8123817745336efa321c35"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13372","number":13372,"commit":"3193b5e0a2ae4c5424bb3eaddfb2d57e7faab156"}],"number":13918}
buildkite-pr-comment-->

2024-07-26 05:34 UTC, kush-elastic commented
/test

2024-07-26 05:49 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14035)
* Commit: 5c52cbd5ecd72df28f06e3a92d4807ee4d247e53

### Failed CI Steps
* [Check integrations postgresql](https://buildkite.com/elastic/integrations/builds/14035#0190ed8e-6fbc-45b8-b274-e3197471f99d)

### History
* :broken_heart: [Build #13918](https://buildkite.com/elastic/integrations/builds/13918) failed b44a79e7eae03a3b296647c0ddbc127a77abb1ad
* :broken_heart: [Build #13524](https://buildkite.com/elastic/integrations/builds/13524) failed 358e1df4b35343330e8123817745336efa321c35
* :green_heart: [Build #13372](https://buildkite.com/elastic/integrations/builds/13372) succeeded 3193b5e0a2ae4c5424bb3eaddfb2d57e7faab156

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14035","number":14035,"commit":"5c52cbd5ecd72df28f06e3a92d4807ee4d247e53"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13918","number":13918,"commit":"b44a79e7eae03a3b296647c0ddbc127a77abb1ad"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13524","number":13524,"commit":"358e1df4b35343330e8123817745336efa321c35"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13372","number":13372,"commit":"3193b5e0a2ae4c5424bb3eaddfb2d57e7faab156"}],"number":14035}
buildkite-pr-comment-->

2024-07-29 09:49 UTC, kush-elastic commented
/test

2024-07-29 09:58 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14092)
* Commit: 5c52cbd5ecd72df28f06e3a92d4807ee4d247e53

### Failed CI Steps
* [Check integrations postgresql](https://buildkite.com/elastic/integrations/builds/14092#0190fde9-a840-41b7-9f22-c656c37b1162)

### History
* :broken_heart: [Build #14035](https://buildkite.com/elastic/integrations/builds/14035) failed 5c52cbd5ecd72df28f06e3a92d4807ee4d247e53
* :broken_heart: [Build #13918](https://buildkite.com/elastic/integrations/builds/13918) failed b44a79e7eae03a3b296647c0ddbc127a77abb1ad
* :broken_heart: [Build #13524](https://buildkite.com/elastic/integrations/builds/13524) failed 358e1df4b35343330e8123817745336efa321c35
* :green_heart: [Build #13372](https://buildkite.com/elastic/integrations/builds/13372) succeeded 3193b5e0a2ae4c5424bb3eaddfb2d57e7faab156

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14092","number":14092,"commit":"5c52cbd5ecd72df28f06e3a92d4807ee4d247e53"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14035","number":14035,"commit":"5c52cbd5ecd72df28f06e3a92d4807ee4d247e53"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13918","number":13918,"commit":"b44a79e7eae03a3b296647c0ddbc127a77abb1ad"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13524","number":13524,"commit":"358e1df4b35343330e8123817745336efa321c35"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13372","number":13372,"commit":"3193b5e0a2ae4c5424bb3eaddfb2d57e7faab156"}],"number":14092}
buildkite-pr-comment-->

2024-07-29 10:04 UTC, shmsr commented on packages/postgresql/data_stream/log/elasticsearch/ingest_pipeline/pipeline-log.yml
> +      - '^(\[%{NUMBER:process.pid:long}(-%{BASE16FLOAT:postgresql.log.session_line_number:long})?\]:? ?)?(\[%{NUMBER:postgresql.log.session_line_number:long}(-%{BASE16FLOAT:postgresql.log.sequence_nu
Curios why we are not considering timestamp? Any idea? As simple as this: `^%{TIMESTAMP_ISO8601:timestamp} %{TZ:timezone}`

2024-08-08 08:38 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14463)
* Commit: 6fd765ee4d3cdf455d0351c5f3d41bafec443012

### Failed CI Steps
* [Check integrations postgresql](https://buildkite.com/elastic/integrations/builds/14463#0191311b-f404-4bad-97a4-cf62da09a8d0)

### History
* :broken_heart: [Build #14092](https://buildkite.com/elastic/integrations/builds/14092) failed 5c52cbd5ecd72df28f06e3a92d4807ee4d247e53
* :broken_heart: [Build #14035](https://buildkite.com/elastic/integrations/builds/14035) failed 5c52cbd5ecd72df28f06e3a92d4807ee4d247e53
* :broken_heart: [Build #13918](https://buildkite.com/elastic/integrations/builds/13918) failed b44a79e7eae03a3b296647c0ddbc127a77abb1ad
* :broken_heart: [Build #13524](https://buildkite.com/elastic/integrations/builds/13524) failed 358e1df4b35343330e8123817745336efa321c35
* :green_heart: [Build #13372](https://buildkite.com/elastic/integrations/builds/13372) succeeded 3193b5e0a2ae4c5424bb3eaddfb2d57e7faab156

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14463","number":14463,"commit":"6fd765ee4d3cdf455d0351c5f3d41bafec443012"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14092","number":14092,"commit":"5c52cbd5ecd72df28f06e3a92d4807ee4d247e53"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14035","number":14035,"commit":"5c52cbd5ecd72df28f06e3a92d4807ee4d247e53"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13918","number":13918,"commit":"b44a79e7eae03a3b296647c0ddbc127a77abb1ad"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13524","number":13524,"commit":"358e1df4b35343330e8123817745336efa321c35"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13372","number":13372,"commit":"3193b5e0a2ae4c5424bb3eaddfb2d57e7faab156"}],"number":14463}
buildkite-pr-comment-->

2024-08-08 09:30 UTC, kush-elastic commented on packages/postgresql/data_stream/log/elasticsearch/ingest_pipeline/pipeline-log.yml
> +      - '^(\[%{NUMBER:process.pid:long}(-%{BASE16FLOAT:postgresql.log.session_line_number:long})?\]:? ?)?(\[%{NUMBER:postgresql.log.session_line_number:long}(-%{BASE16FLOAT:postgresql.log.sequence_nu
It is already being extracted in default pipeline and then we are extracting more details from remaining raw message.

2024-08-22 10:16 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14892)
* Commit: 4e13804d2685a852a48bf16543ee483a824da13a

### History
* :broken_heart: [Build #14463](https://buildkite.com/elastic/integrations/builds/14463) failed 6fd765ee4d3cdf455d0351c5f3d41bafec443012
* :broken_heart: [Build #14092](https://buildkite.com/elastic/integrations/builds/14092) failed 5c52cbd5ecd72df28f06e3a92d4807ee4d247e53
* :broken_heart: [Build #14035](https://buildkite.com/elastic/integrations/builds/14035) failed 5c52cbd5ecd72df28f06e3a92d4807ee4d247e53
* :broken_heart: [Build #13918](https://buildkite.com/elastic/integrations/builds/13918) failed b44a79e7eae03a3b296647c0ddbc127a77abb1ad
* :broken_heart: [Build #13524](https://buildkite.com/elastic/integrations/builds/13524) failed 358e1df4b35343330e8123817745336efa321c35

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14892","number":14892,"commit":"4e13804d2685a852a48bf16543ee483a824da13a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14463","number":14463,"commit":"6fd765ee4d3cdf455d0351c5f3d41bafec443012"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14092","number":14092,"commit":"5c52cbd5ecd72df28f06e3a92d4807ee4d247e53"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14035","number":14035,"commit":"5c52cbd5ecd72df28f06e3a92d4807ee4d247e53"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13918","number":13918,"commit":"b44a79e7eae03a3b296647c0ddbc127a77abb1ad"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13524","number":13524,"commit":"358e1df4b35343330e8123817745336efa321c35"}],"number":14892}
buildkite-pr-comment-->

2024-08-28 11:56 UTC, Linu-Elias commented on packages/postgresql/data_stream/activity/manifest.yml
> +
I think a new line got added here which is not needed

2024-08-28 12:00 UTC, harnish-elastic commented on packages/postgresql/data_stream/activity/manifest.yml
> +
This is automatically formatted by `elastic-package check` command.

2024-09-03 05:55 UTC, shmsr commented
AFAIK, we do not pack support for custom log formats in our integration packages, right?

2024-09-03 05:58 UTC, shmsr requested changes

2024-09-03 05:58 UTC, shmsr commented on packages/postgresql/data_stream/statement/manifest.yml
> +        description: "Processors are used to reduce the number of fields in the exported event or to enhance the event with metadata. This executes in the agent before the events are shipped. See [Pr
```suggestion
        description: "Processors are used to reduce the number of fields in the exported event or to enhance the event with metadata. The agent executes this before the events are shipped. See [Processors](https://www.elastic.co/guide/en/fleet/current/elastic-agent-processor-configuration.html) for details.\n"
```

Not sure why did we add "\n" here? Any particular reason?

2024-09-03 05:58 UTC, shmsr commented on packages/postgresql/data_stream/log/fields/fields.yml
> +        Sequence number circumvents that last message was repeated N times.
```suggestion
        Sequence number circumvents that the last message was repeated N times.
```

2024-09-03 05:58 UTC, shmsr commented on packages/postgresql/data_stream/log/fields/fields.yml
> +  description: Identification code for this event.
```suggestion
  description: Identification code for the event.
```

2024-09-03 05:58 UTC, shmsr commented on packages/postgresql/data_stream/log/fields/fields.yml
> +  description: Event severity (e.g. info, error).
```suggestion
  description: Severity of the event (info, error, etc.).
```

2024-09-03 05:59 UTC, shmsr commented on packages/postgresql/changelog.yml
> +    - description: Fix log datastream grok pattern to support standard logs.
Along with standard, aren't you also handling the custom formats like the one mentioned in the SDH?

2024-09-03 06:42 UTC, harnish-elastic commented on packages/postgresql/changelog.yml
> +    - description: Fix log datastream grok pattern to support standard logs.
Yes we are!

2024-09-03 06:53 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15345)
* Commit: b8a6041be24449e0db4ca72aa2b4126598553fbc

### Failed CI Steps
* [Check integrations postgresql](https://buildkite.com/elastic/integrations/builds/15345#0191b6a3-7637-484a-8bd6-f3fce94f1a5c)

### History
* :green_heart: [Build #14892](https://buildkite.com/elastic/integrations/builds/14892) succeeded 4e13804d2685a852a48bf16543ee483a824da13a
* :broken_heart: [Build #14463](https://buildkite.com/elastic/integrations/builds/14463) failed 6fd765ee4d3cdf455d0351c5f3d41bafec443012
* :broken_heart: [Build #14092](https://buildkite.com/elastic/integrations/builds/14092) failed 5c52cbd5ecd72df28f06e3a92d4807ee4d247e53
* :broken_heart: [Build #14035](https://buildkite.com/elastic/integrations/builds/14035) failed 5c52cbd5ecd72df28f06e3a92d4807ee4d247e53
* :broken_heart: [Build #13918](https://buildkite.com/elastic/integrations/builds/13918) failed b44a79e7eae03a3b296647c0ddbc127a77abb1ad
* :broken_heart: [Build #13524](https://buildkite.com/elastic/integrations/builds/13524) failed 358e1df4b35343330e8123817745336efa321c35

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15345","number":15345,"commit":"b8a6041be24449e0db4ca72aa2b4126598553fbc"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14892","number":14892,"commit":"4e13804d2685a852a48bf16543ee483a824da13a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14463","number":14463,"commit":"6fd765ee4d3cdf455d0351c5f3d41bafec443012"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14092","number":14092,"commit":"5c52cbd5ecd72df28f06e3a92d4807ee4d247e53"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14035","number":14035,"commit":"5c52cbd5ecd72df28f06e3a92d4807ee4d247e53"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13918","number":13918,"commit":"b44a79e7eae03a3b296647c0ddbc127a77abb1ad"}],"number":15345}
buildkite-pr-comment-->

2024-09-03 06:56 UTC, harnish-elastic commented
> AFAIK, we do not pack support for custom log formats in our integration packages, right?

Yes, we are not. But there are 3 new fields that we have seen in the client logs appeared in the two different SDHs that seems crucial. Also we saw the new timezones which is not the default like UTC/IST. We have supported those new timezones (CEST, EST, +02:00 and +02). [Refer](https://github.com/elastic/integrations/pull/10412/files#diff-d03f092ede0c36066589266f0f3d3c5e0fb77557744acac7e17f582312edf7abR27-R72). Also you can refer the generated pipeline tests.

2024-09-03 07:59 UTC, shmsr commented
> > AFAIK, we do not pack support for custom log formats in our integration packages, right?
> 
> Yes, we are not. But there are 3 new fields that we have seen in the client logs appeared in the two different SDHs that seems crucial. Also we saw the new timezones which is not the default like UTC/IST. We have supported those new timezones (CEST, EST, +02:00 and +02). [Refer](https://github.com/elastic/integrations/pull/10412/files#diff-d03f092ede0c36066589266f0f3d3c5e0fb77557744acac7e17f582312edf7abR27-R72). The changes that we have made is not affecting our existing behavior. You can refer the generated pipeline tests.

For defaults, UTC is fine. But IST or any other shouldn't be considered a default. Also, if I see correctly there are more such time zones.

See how the "date" processor is considering the timezone: https://github.com/elastic/elasticsearch/blob/2871b94603655ff3b6120788728bfbf7c009d27f/modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/DateProcessor.java#L96

So, I was playing with the script and made some changes and noticed that some results in the pipeline tests are incorrect. I'll share the patch with you here, please confirm:

```diff
diff --git a/packages/postgresql/data_stream/log/elasticsearch/ingest_pipeline/default.yml b/packages/postgresql/data_stream/log/elasticsearch/ingest_pipeline/default.yml
index 523134dfe9..23447adaad 100644
--- a/packages/postgresql/data_stream/log/elasticsearch/ingest_pipeline/default.yml
+++ b/packages/postgresql/data_stream/log/elasticsearch/ingest_pipeline/default.yml
@@ -33,43 +33,53 @@ processors:
         UTC as before.
       if: ctx._temp_?.timestamp != null
       source: |-
-       String get_timezone(def ctx) { 
+        String get_timezone(def ctx) {
           if (ctx.event?.timezone != null) {
-          
-            // if timezone is in format of CEST,EST etc.
-            if (ctx.event.timezone.length() <= 4) {
-              // all time zone abbreviations need to be uppercase
-              return ctx.event.timezone.toUpperCase();
+            String tz = ctx.event.timezone.trim().toUpperCase();
+
+            // Handle abbreviations (e.g., CEST, EST)
+            if (tz.length() <= 4) {
+              return tz;
             }
 
-            // if timezone is in format of +00:00, -00:00, +00 & -00
-            if(ctx.event?.timezone.contains('+') || ctx.event?.timezone.contains('-')) {
-              // if timezone is in format of +00 or -00
-              if (ctx.event.timezone.length() == 3) {
-                return "UTC"+ctx.event.timezone+":00";
-              }
-              return "UTC"+ctx.event.timezone;
+            // Handle offset formats (+00:00, -00:00, +00, -00)
+            if (tz.startsWith('+') || tz.startsWith('-')) {
+              return tz.length() == 3 ? "UTC" + tz + ":00" : "UTC" + tz;
             }
-              
-            return ctx.event.timezone;
+
+            return tz;
           }
-                  
+
           ctx.event.timezone = 'UTC';
           return 'UTC';
         }
-        
+
         def event_timezone = get_timezone(ctx);
-        if (!(event_timezone.contains('+')) && !(event_timezone.contains('-')) && !(event_timezone.length() > 4)) {
-          // timezone abbreviation e.g. CEST need to be put inside the timestamp
-          SimpleDateFormat sdf = new SimpleDateFormat("z");
-          sdf.parse(event_timezone);
-          ctx._temp_.date_timezone = ZoneId.of(sdf.getTimeZone().getID(), ZoneId.SHORT_IDS).getId();
-          ctx?._temp_.timestamp = ctx?._temp_.timestamp + " " + event_timezone;
+        boolean isAbbreviation = !(event_timezone.contains('+') || event_timezone.contains('-') || event_timezone.length() > 4);
+
+        if (isAbbreviation) {
+          Map CUSTOM_ZONE_IDS = new HashMap(ZoneId.SHORT_IDS);
+          CUSTOM_ZONE_IDS.put("CEST", "Europe/Paris");
+          CUSTOM_ZONE_IDS.put("CET", "Europe/Paris");
+          CUSTOM_ZONE_IDS.put("BST", "Europe/London");
+          CUSTOM_ZONE_IDS.put("IST", "Asia/Kolkata");
+          CUSTOM_ZONE_IDS.put("EEST", "Europe/Athens");
+          CUSTOM_ZONE_IDS.put("EET", "Europe/Athens");
+          CUSTOM_ZONE_IDS.put("AEST", "Australia/Sydney");
+          CUSTOM_ZONE_IDS.put("AEDT", "Australia/Sydney");
+          CUSTOM_ZONE_IDS.put("ACST", "Australia/Adelaide");
+          CUSTOM_ZONE_IDS.put("ACDT", "Australia/Adelaide");
+          CUSTOM_ZONE_IDS.put("AWST", "Australia/Perth");
+
+          // Timezone abbreviation (e.g., CEST) needs to be put inside the timestamp
+          ZoneId zoneId = ZoneId.of(event_timezone, CUSTOM_ZONE_IDS);
+          ctx._temp_.date_timezone = zoneId.getId();
+          ctx?._temp_.timestamp += " " + event_timezone;
         } else {
-          // timezone is either abbreviation+-offset e.g. UTC+1 or long representation
-          // e.g. Europe/Athens needs to be put as a ZoneId and *not* inside the timestamp
+          // Timezone is either abbreviation+-offset (e.g., UTC+1) or long representation (e.g., Europe/Athens)
           ctx._temp_.date_timezone = event_timezone;
-        }  
+        }
+
   - pipeline:
       name: '{{ IngestPipeline "pipeline-log" }}'
       if: ctx.separator != ',' && ctx.separator != ':'
@@ -86,8 +96,8 @@ processors:
       formats:
       - yyyy-MM-dd HH:mm:ss.SSS zz
       - yyyy-MM-dd HH:mm:ss zz
-      - yyyy-MM-dd HH:mm:ss.SSS 
-      - yyyy-MM-dd HH:mm:ss 
+      - yyyy-MM-dd HH:mm:ss.SSS
+      - yyyy-MM-dd HH:mm:ss
       on_failure:
         - set:
             field: error.message
diff --git a/packages/postgresql/data_stream/log/elasticsearch/ingest_pipeline/pipeline-log.yml b/packages/postgresql/data_stream/log/elasticsearch/ingest_pipeline/pipeline-log.yml
index 7e697a59cc..51693ff1e3 100644
--- a/packages/postgresql/data_stream/log/elasticsearch/ingest_pipeline/pipeline-log.yml
+++ b/packages/postgresql/data_stream/log/elasticsearch/ingest_pipeline/pipeline-log.yml
@@ -16,11 +16,11 @@ processors:
   - kv:
       tag: kv_log_database_info
       field: _temp_.database_connection_str
-      target_field: _temp_.database_connection_obj 
+      target_field: _temp_.database_connection_obj
       field_split: ','
       value_split: '='
       ignore_missing: true
-      strip_brackets: true  
+      strip_brackets: true
       description: Splits PostgreSQL log info string into key-value pairs.
       ignore_failure: true
       on_failure:
@@ -32,16 +32,16 @@ processors:
   - rename:
       field: _temp_.database_connection_obj.app
       target_field: postgresql.log.application_name
-      ignore_missing: true          
+      ignore_missing: true
   - rename:
       field: _temp_.database_connection_obj.client
       target_field: postgresql.log.client_addr
-      ignore_missing: true          
+      ignore_missing: true
   - rename:
       field: _temp_.database_connection_obj.db
       target_field: postgresql.log.database
-      ignore_missing: true          
+      ignore_missing: true
   - rename:
       field: _temp_.database_connection_obj.user
       target_field: user.name
-      ignore_missing: true      
\ No newline at end of file
+      ignore_missing: true
\ No newline at end of file
```

This is a diff patch. You can directly apply this using git commands.


Example failures:

Search for `@timestamp": "2017-07-31T13:36:43.000-04:00` in `postgresql/log test-postgresql-9-6-new-timestamp.log`
 and if you notice the timezone is "EST" for which TZ offset is `-05:00` but in the timestamp it is `-04:00`.
 
 
 Also, had to introduce a custom map because https://docs.oracle.com/javase/8/docs/api/java/time/ZoneId.html#SHORT_IDS only supports a few; not all.

2024-09-03 12:33 UTC, harnish-elastic commented
@shmsr Thanks for the suggestion. Based on your provided [changes](https://github.com/elastic/integrations/pull/10412#issuecomment-2325847778) I have implemented the pipeline tests, here are the result of the current pipeline behavior vs suggested behavior and please observe the `@timestamp` field. Technically both are giving the same output and the pipeline test were correct in the current behavior. Let me do one round of live data collection of the suggested changes and will push it after that!

Current behaviour
```
{
    "@timestamp": "2017-07-31T13:36:43.557-04:00",
    "_temp_": {
        "date_timezone": "America/New_York",
        "timestamp": "2017-07-31 13:36:43.557 EST"
    }
}
```

Suggested behavior
```
{
    "@timestamp": "2017-07-31T12:36:43.557-05:00",
    "_temp_": {
        "date_timezone": "-05:00",
        "timestamp": "2017-07-31 13:36:43.557 EST"
    }
}
```

2024-09-03 13:22 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15370)
* Commit: fa9f1c36bb216b954b8260da1b7f15b17e211f1f

### History
* :broken_heart: [Build #15345](https://buildkite.com/elastic/integrations/builds/15345) failed b8a6041be24449e0db4ca72aa2b4126598553fbc
* :green_heart: [Build #14892](https://buildkite.com/elastic/integrations/builds/14892) succeeded 4e13804d2685a852a48bf16543ee483a824da13a
* :broken_heart: [Build #14463](https://buildkite.com/elastic/integrations/builds/14463) failed 6fd765ee4d3cdf455d0351c5f3d41bafec443012
* :broken_heart: [Build #14092](https://buildkite.com/elastic/integrations/builds/14092) failed 5c52cbd5ecd72df28f06e3a92d4807ee4d247e53
* :broken_heart: [Build #14035](https://buildkite.com/elastic/integrations/builds/14035) failed 5c52cbd5ecd72df28f06e3a92d4807ee4d247e53

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15370","number":15370,"commit":"fa9f1c36bb216b954b8260da1b7f15b17e211f1f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15345","number":15345,"commit":"b8a6041be24449e0db4ca72aa2b4126598553fbc"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14892","number":14892,"commit":"4e13804d2685a852a48bf16543ee483a824da13a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14463","number":14463,"commit":"6fd765ee4d3cdf455d0351c5f3d41bafec443012"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14092","number":14092,"commit":"5c52cbd5ecd72df28f06e3a92d4807ee4d247e53"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14035","number":14035,"commit":"5c52cbd5ecd72df28f06e3a92d4807ee4d247e53"}],"number":15370}
buildkite-pr-comment-->

2024-09-05 08:53 UTC, gpop63 commented on packages/postgresql/data_stream/log/elasticsearch/ingest_pipeline/pipeline-log.yml
> +      target_field: postgresql.log.client_addr
Could this be converted to `ip` type? Also would it make sense here to remove/cleanup `_temp_` after you have finished renaming these fields?

2024-09-10 06:41 UTC, harnish-elastic commented on packages/postgresql/data_stream/log/elasticsearch/ingest_pipeline/pipeline-log.yml
> +      target_field: postgresql.log.client_addr
> Could this be converted to ip type?

There are values like `local` for this field. Also there are IP values as well. I have updated the pipeline that can set IP values to related.ip field and the keyword values can be set to related.host field.

> Also would it make sense here to remove/cleanup _temp_ after you have finished renaming these fields?

Yes, after renaming the fields there are some fields still remaining that needed cleanup in `_temp_`. Hence removed `_temp_`.

2024-09-10 06:58 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15688)
* Commit: 7d2396ad05d2d9dfcf59eb3c76518aafa6fcf03c

### History
* :green_heart: [Build #15370](https://buildkite.com/elastic/integrations/builds/15370) succeeded fa9f1c36bb216b954b8260da1b7f15b17e211f1f
* :broken_heart: [Build #15345](https://buildkite.com/elastic/integrations/builds/15345) failed b8a6041be24449e0db4ca72aa2b4126598553fbc
* :green_heart: [Build #14892](https://buildkite.com/elastic/integrations/builds/14892) succeeded 4e13804d2685a852a48bf16543ee483a824da13a
* :broken_heart: [Build #14463](https://buildkite.com/elastic/integrations/builds/14463) failed 6fd765ee4d3cdf455d0351c5f3d41bafec443012
* :broken_heart: [Build #14092](https://buildkite.com/elastic/integrations/builds/14092) failed 5c52cbd5ecd72df28f06e3a92d4807ee4d247e53
* :broken_heart: [Build #14035](https://buildkite.com/elastic/integrations/builds/14035) failed 5c52cbd5ecd72df28f06e3a92d4807ee4d247e53

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15688","number":15688,"commit":"7d2396ad05d2d9dfcf59eb3c76518aafa6fcf03c"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15370","number":15370,"commit":"fa9f1c36bb216b954b8260da1b7f15b17e211f1f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15345","number":15345,"commit":"b8a6041be24449e0db4ca72aa2b4126598553fbc"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14892","number":14892,"commit":"4e13804d2685a852a48bf16543ee483a824da13a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14463","number":14463,"commit":"6fd765ee4d3cdf455d0351c5f3d41bafec443012"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14092","number":14092,"commit":"5c52cbd5ecd72df28f06e3a92d4807ee4d247e53"}],"number":15688}
buildkite-pr-comment-->

2024-09-16 06:49 UTC, harnish-elastic commented
> [#10412 (comment)](https://github.com/elastic/integrations/pull/10412#issuecomment-2326407434)
> 
> > here are the result of the current pipeline behavior vs suggested behavior and please observe the @timestamp field. Technically both are giving the same output and the pipeline test were correct in the current behavior.
> 
> Didn't understand this.
> 
> > Example failures:
> 
> > Search for @timestamp": "2017-07-31T13:36:43.000-04:00 in postgresql/log test-postgresql-9-6-new-timestamp.log
> > and if you notice the timezone is "EST" for which TZ offset is -05:00 but in the timestamp it is -04:00.
> 
> Did you check this ^^? Previously, EST's TZ offset was shown as -05:00 but if you search EST is actually -04:00

Yes @shmsr I have checked your previous comment and as shown in above [comment](https://github.com/elastic/integrations/pull/10412#issuecomment-2326407434), both timestamps are logically same if you notice the hour of that timestamp. In the -04:00 the hour was 13:36 and in the -05:00 the hour was 12:36. 

I have already made changes as per your suggestions which you can see in the updated PR.

2024-09-17 05:30 UTC, shmsr commented
> > [#10412 (comment)](https://github.com/elastic/integrations/pull/10412#issuecomment-2326407434)
> > > here are the result of the current pipeline behavior vs suggested behavior and please observe the @timestamp field. Technically both are giving the same output and the pipeline test were correct in the current behavior.
> > 
> > 
> > Didn't understand this.
> > > Example failures:
> > 
> > 
> > > Search for @timestamp": "2017-07-31T13:36:43.000-04:00 in postgresql/log test-postgresql-9-6-new-timestamp.log
> > > and if you notice the timezone is "EST" for which TZ offset is -05:00 but in the timestamp it is -04:00.
> > 
> > 
> > Did you check this ^^? Previously, EST's TZ offset was shown as -05:00 but if you search EST is actually -04:00
> 
> Yes @shmsr I have checked your previous comment and as shown in above [comment](https://github.com/elastic/integrations/pull/10412#issuecomment-2326407434), both timestamps are logically same if you notice the hour of that timestamp. In the -04:00 the hour was 13:36 and in the -05:00 the hour was 12:36.
> 
> I have already made changes as per your suggestions which you can see in the updated PR.

Change is good. But I am thinking of this: https://stackoverflow.com/a/68821105/5821408

For 3 letter timezones, it is tricky, that's why 4 letter timezones are there to clear it up. For example:

> For compatibility with JDK 1.1.x, some other three-letter time zone IDs (such as "PST", "CTT", "AST") are also supported. However, their use is deprecated because the same abbreviation is often used for multiple time zones (for example, "CST" could be U.S. "Central Standard Time" and "China Standard Time"), and the Java platform can then only recognize one of them.

Same for IST; it could be Indian Standard Time or maybe even Israel Standard Time. And depending on what we choose to map, we will get the offset accordingly.


Change looks good. I don't think we can do much here. In case, there's ever an SDH/ clarification required, we can point them to assumed defaults. Approving this PR.

2024-09-17 05:31 UTC, shmsr approved these changes

2024-09-18 05:58 UTC, merged

2024-12-04 11:46 UTC, shaunbugler commented
How does one go about adding to the list of CUSTOM_ZONE_IDS? Since this update we have been receiving:
 `Unknown time-zone ID: SAST`
the example postgresql.log.timestamp  is `2024-11-22 11:26:25.482 SAST`

If I update the `logs-postgresql.log-1.25.0` ingest pipeline and add:
`CUSTOM_ZONE_IDS.put(\"SAST\", \"Africa/Johannesburg\"); `
then my problems are solved, until the pipeline is updated, so is there a better way to handle this? Thanks!