[Azure OpenAI] Add PTU deployment metrics dashboard
elastic/integrations pull request #10452
Opened 2024-07-11 09:06 UTC by muthu-mps

- Enhancement

This PR creates new dashboard for the PTU deployment specific metrics. Here is the [issue](https://github.com/elastic/integrations/issues/10117) for more details on PTU metrics.

## Author's Checklist

- Install the integration and verify the dashboard for PTU metrics loads in Kibana.
- Verify the signals are being added to the dashboard.

## Related issues

- Closes #10117

## Screenshots
<img width="1727" alt="azure_open_ai_ptu_deployment" src="https://github.com/elastic/integrations/assets/101238137/1ca627a4-9041-4dc2-a3b8-2aa73ec94571">

2024-07-11 09:18 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13539)
* Commit: cdada337184322bf5338d8708e244f70970621e0

### Failed CI Steps
* [Check integrations azure_openai](https://buildkite.com/elastic/integrations/builds/13539#0190a10f-d842-45ab-80d7-8b06e7f94b76)

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13539","number":13539,"commit":"cdada337184322bf5338d8708e244f70970621e0"}],"number":13539}
buildkite-pr-comment-->

2024-07-11 09:32 UTC, harnish-elastic requested changes

2024-07-11 09:32 UTC, harnish-elastic commented on packages/azure_openai/img/azure_open_ai_ptu_deployment.png
Can we add dashboard level filter (data_stream.dataset: <value>)

2024-07-11 09:32 UTC, harnish-elastic commented on packages/azure_openai/img/azure_open_ai_ptu_deployment.png
Suggestions: 

Can we update the title from `Active tokens total over time` to `Total number of active tokens over time`? 

Also the represent of active token is with decimal? If the active tokens are integer, can we remove decimals from visualization?

2024-07-11 09:32 UTC, harnish-elastic commented on packages/azure_openai/img/azure_open_ai_ptu_deployment.png
For the `Time to first response` line chart, can we update the Y-axis text to `Response time`?

2024-07-11 09:32 UTC, harnish-elastic commented on packages/azure_openai/img/azure_open_ai_ptu_deployment.png
Since all 4 charts are respected to timestamp, Can we update the titles using suffix `over time`?

`Time to first response` -> `Initial response time over time` / `Initial response time`

`Provisioned utilization in percentage` -> `Provisioned utilization over time` (as user can see the y-axis shown as percentage, hence no need to mention percentage in title!)

`Token cache match rate` -> `Match rate of token cache over time`

2024-07-11 09:35 UTC, muthu-mps commented on packages/azure_openai/img/azure_open_ai_ptu_deployment.png
Those names are from the Azure OpenAI. I would like to keep it in the same way which would help users to match the metrics with service.

2024-07-11 09:39 UTC, muthu-mps commented on packages/azure_openai/img/azure_open_ai_ptu_deployment.png
Changing the name to `Active tokens over time`.

2024-07-11 09:40 UTC, muthu-mps commented on packages/azure_openai/img/azure_open_ai_ptu_deployment.png
> Since all 4 charts are respected to timestamp, Can we update the titles using suffix over time?

Yes.

2024-07-11 10:22 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-07-11 10:22 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13544)
* Commit: 6145797a1dcb0f5b56fbafb0b54fa5e24cf1a3dd

### History
* :broken_heart: [Build #13539](https://buildkite.com/elastic/integrations/builds/13539) failed cdada337184322bf5338d8708e244f70970621e0

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13544","number":13544,"commit":"6145797a1dcb0f5b56fbafb0b54fa5e24cf1a3dd"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13539","number":13539,"commit":"cdada337184322bf5338d8708e244f70970621e0"}],"number":13544}
buildkite-pr-comment-->

2024-07-12 05:31 UTC, harnish-elastic approved these changes
LGTM! 🚀

2024-07-12 07:38 UTC, shmsr commented
@muthu-mps Put it in a project.

2024-07-12 07:39 UTC, shmsr approved these changes

2024-07-12 07:42 UTC, merged

2024-07-12 08:01 UTC, elasticmachine commented
Package azure_openai - 1.1.2 containing this change is available at https://epr.elastic.co/search?package=azure_openai