Jamf pro integration
elastic/integrations pull request #10470
Opened 2024-07-12 08:27 UTC by wshaman

- Enhancement

## Proposed commit message

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## How to test this PR locally

## Related issues

- 

## Screenshots

2024-08-05 08:57 UTC, alexwizp commented
/ci

2024-08-06 16:57 UTC, alexwizp commented
/ci

2024-08-06 16:59 UTC, gpop63 commented
/test

2024-08-06 17:03 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14387)
* Commit: d8831e49266e31df7e239ddc0842ec339377d854

### Failed CI Steps
* [:white_check_mark: Check go sources](https://buildkite.com/elastic/integrations/builds/14387#019128a2-a999-4cc5-9d21-101efaa9d027)

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14387","number":14387,"commit":"d8831e49266e31df7e239ddc0842ec339377d854"}],"number":14387}
buildkite-pr-comment-->

2024-08-07 05:56 UTC, wshaman commented
/test

2024-08-07 06:17 UTC, alexwizp commented
/test

2024-08-07 06:21 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14398)
* Commit: 70c939c6847d130f9628857f68f3561ae5f4a683

### Failed CI Steps
* [:white_check_mark: Check go sources](https://buildkite.com/elastic/integrations/builds/14398#01912b7d-7d00-4c44-9425-fba28621e0e6)

### History
* :broken_heart: [Build #14387](https://buildkite.com/elastic/integrations/builds/14387) failed d8831e49266e31df7e239ddc0842ec339377d854

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14398","number":14398,"commit":"70c939c6847d130f9628857f68f3561ae5f4a683"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14387","number":14387,"commit":"d8831e49266e31df7e239ddc0842ec339377d854"}],"number":14398}
buildkite-pr-comment-->

2024-08-07 06:32 UTC, alexwizp commented
/test

2024-08-07 06:37 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14399)
* Commit: cd526b66b77a6173678602d7d0b1d98ada12556e

### Failed CI Steps
* [:white_check_mark: Check go sources](https://buildkite.com/elastic/integrations/builds/14399#01912b8a-a3b1-4ace-8d80-9e0565e54a86)

### History
* :broken_heart: [Build #14398](https://buildkite.com/elastic/integrations/builds/14398) failed 70c939c6847d130f9628857f68f3561ae5f4a683
* :broken_heart: [Build #14387](https://buildkite.com/elastic/integrations/builds/14387) failed d8831e49266e31df7e239ddc0842ec339377d854

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14399","number":14399,"commit":"cd526b66b77a6173678602d7d0b1d98ada12556e"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14398","number":14398,"commit":"70c939c6847d130f9628857f68f3561ae5f4a683"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14387","number":14387,"commit":"d8831e49266e31df7e239ddc0842ec339377d854"}],"number":14399}
buildkite-pr-comment-->

2024-08-07 06:47 UTC, alexwizp commented
/test

2024-08-07 06:51 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14400)
* Commit: d1159c73612fd07b1117f3d439703ef4c61f5548

### Failed CI Steps
* [:white_check_mark: Check go sources](https://buildkite.com/elastic/integrations/builds/14400#01912b98-7596-4ed8-9f78-2f2829747ca3)

### History
* :broken_heart: [Build #14399](https://buildkite.com/elastic/integrations/builds/14399) failed cd526b66b77a6173678602d7d0b1d98ada12556e
* :broken_heart: [Build #14398](https://buildkite.com/elastic/integrations/builds/14398) failed 70c939c6847d130f9628857f68f3561ae5f4a683
* :broken_heart: [Build #14387](https://buildkite.com/elastic/integrations/builds/14387) failed d8831e49266e31df7e239ddc0842ec339377d854

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14400","number":14400,"commit":"d1159c73612fd07b1117f3d439703ef4c61f5548"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14399","number":14399,"commit":"cd526b66b77a6173678602d7d0b1d98ada12556e"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14398","number":14398,"commit":"70c939c6847d130f9628857f68f3561ae5f4a683"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14387","number":14387,"commit":"d8831e49266e31df7e239ddc0842ec339377d854"}],"number":14400}
buildkite-pr-comment-->

2024-08-07 07:09 UTC, wshaman commented
/test

2024-08-07 07:10 UTC, alexwizp commented
/test

2024-08-07 07:24 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14401)
* Commit: d0770769e400350cf9ec3b6efeaa6fbf0076321b

### Failed CI Steps
* [Check integrations jamf_pro](https://buildkite.com/elastic/integrations/builds/14401#01912bb1-ad8c-40a3-8498-d7991085d990)

### History
* :broken_heart: [Build #14400](https://buildkite.com/elastic/integrations/builds/14400) failed d1159c73612fd07b1117f3d439703ef4c61f5548
* :broken_heart: [Build #14399](https://buildkite.com/elastic/integrations/builds/14399) failed cd526b66b77a6173678602d7d0b1d98ada12556e
* :broken_heart: [Build #14398](https://buildkite.com/elastic/integrations/builds/14398) failed 70c939c6847d130f9628857f68f3561ae5f4a683
* :broken_heart: [Build #14387](https://buildkite.com/elastic/integrations/builds/14387) failed d8831e49266e31df7e239ddc0842ec339377d854

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14401","number":14401,"commit":"d0770769e400350cf9ec3b6efeaa6fbf0076321b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14400","number":14400,"commit":"d1159c73612fd07b1117f3d439703ef4c61f5548"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14399","number":14399,"commit":"cd526b66b77a6173678602d7d0b1d98ada12556e"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14398","number":14398,"commit":"70c939c6847d130f9628857f68f3561ae5f4a683"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14387","number":14387,"commit":"d8831e49266e31df7e239ddc0842ec339377d854"}],"number":14401}
buildkite-pr-comment-->

2024-08-07 09:38 UTC, alexwizp commented
/test

2024-08-07 09:53 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-08-07 09:53 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14408)
* Commit: ec90d748cbbf643d1a0eab238ecf458d4e3f4032

### History
* :broken_heart: [Build #14401](https://buildkite.com/elastic/integrations/builds/14401) failed d0770769e400350cf9ec3b6efeaa6fbf0076321b
* :broken_heart: [Build #14400](https://buildkite.com/elastic/integrations/builds/14400) failed d1159c73612fd07b1117f3d439703ef4c61f5548
* :broken_heart: [Build #14399](https://buildkite.com/elastic/integrations/builds/14399) failed cd526b66b77a6173678602d7d0b1d98ada12556e
* :broken_heart: [Build #14398](https://buildkite.com/elastic/integrations/builds/14398) failed 70c939c6847d130f9628857f68f3561ae5f4a683
* :broken_heart: [Build #14387](https://buildkite.com/elastic/integrations/builds/14387) failed d8831e49266e31df7e239ddc0842ec339377d854

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14408","number":14408,"commit":"ec90d748cbbf643d1a0eab238ecf458d4e3f4032"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14401","number":14401,"commit":"d0770769e400350cf9ec3b6efeaa6fbf0076321b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14400","number":14400,"commit":"d1159c73612fd07b1117f3d439703ef4c61f5548"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14399","number":14399,"commit":"cd526b66b77a6173678602d7d0b1d98ada12556e"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14398","number":14398,"commit":"70c939c6847d130f9628857f68f3561ae5f4a683"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14387","number":14387,"commit":"d8831e49266e31df7e239ddc0842ec339377d854"}],"number":14408}
buildkite-pr-comment-->

2024-08-07 17:07 UTC, alexwizp commented
/test

2024-08-07 17:25 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14435)
* Commit: 0caae6934943c3f248043ed07b4d40005650faf8

### History
* :green_heart: [Build #14408](https://buildkite.com/elastic/integrations/builds/14408) succeeded ec90d748cbbf643d1a0eab238ecf458d4e3f4032
* :broken_heart: [Build #14401](https://buildkite.com/elastic/integrations/builds/14401) failed d0770769e400350cf9ec3b6efeaa6fbf0076321b
* :broken_heart: [Build #14400](https://buildkite.com/elastic/integrations/builds/14400) failed d1159c73612fd07b1117f3d439703ef4c61f5548
* :broken_heart: [Build #14399](https://buildkite.com/elastic/integrations/builds/14399) failed cd526b66b77a6173678602d7d0b1d98ada12556e
* :broken_heart: [Build #14398](https://buildkite.com/elastic/integrations/builds/14398) failed 70c939c6847d130f9628857f68f3561ae5f4a683
* :broken_heart: [Build #14387](https://buildkite.com/elastic/integrations/builds/14387) failed d8831e49266e31df7e239ddc0842ec339377d854

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14435","number":14435,"commit":"0caae6934943c3f248043ed07b4d40005650faf8"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14408","number":14408,"commit":"ec90d748cbbf643d1a0eab238ecf458d4e3f4032"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14401","number":14401,"commit":"d0770769e400350cf9ec3b6efeaa6fbf0076321b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14400","number":14400,"commit":"d1159c73612fd07b1117f3d439703ef4c61f5548"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14399","number":14399,"commit":"cd526b66b77a6173678602d7d0b1d98ada12556e"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14398","number":14398,"commit":"70c939c6847d130f9628857f68f3561ae5f4a683"}],"number":14435}
buildkite-pr-comment-->

2024-08-08 16:22 UTC, alexwizp commented
/test

2024-08-08 16:40 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14488)
* Commit: 2450e0a63f7a297437fe6d1ab3c3b0ea4b2935bf

### History
* :green_heart: [Build #14435](https://buildkite.com/elastic/integrations/builds/14435) succeeded 0caae6934943c3f248043ed07b4d40005650faf8
* :green_heart: [Build #14408](https://buildkite.com/elastic/integrations/builds/14408) succeeded ec90d748cbbf643d1a0eab238ecf458d4e3f4032
* :broken_heart: [Build #14401](https://buildkite.com/elastic/integrations/builds/14401) failed d0770769e400350cf9ec3b6efeaa6fbf0076321b
* :broken_heart: [Build #14400](https://buildkite.com/elastic/integrations/builds/14400) failed d1159c73612fd07b1117f3d439703ef4c61f5548
* :broken_heart: [Build #14399](https://buildkite.com/elastic/integrations/builds/14399) failed cd526b66b77a6173678602d7d0b1d98ada12556e
* :broken_heart: [Build #14398](https://buildkite.com/elastic/integrations/builds/14398) failed 70c939c6847d130f9628857f68f3561ae5f4a683

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14488","number":14488,"commit":"2450e0a63f7a297437fe6d1ab3c3b0ea4b2935bf"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14435","number":14435,"commit":"0caae6934943c3f248043ed07b4d40005650faf8"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14408","number":14408,"commit":"ec90d748cbbf643d1a0eab238ecf458d4e3f4032"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14401","number":14401,"commit":"d0770769e400350cf9ec3b6efeaa6fbf0076321b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14400","number":14400,"commit":"d1159c73612fd07b1117f3d439703ef4c61f5548"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14399","number":14399,"commit":"cd526b66b77a6173678602d7d0b1d98ada12556e"}],"number":14488}
buildkite-pr-comment-->

2024-08-09 14:26 UTC, alexwizp commented
/test

2024-08-09 14:45 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14519)
* Commit: 590209cfd756f1b228d480d40f876f5694136c24

### History
* :green_heart: [Build #14488](https://buildkite.com/elastic/integrations/builds/14488) succeeded 2450e0a63f7a297437fe6d1ab3c3b0ea4b2935bf
* :green_heart: [Build #14435](https://buildkite.com/elastic/integrations/builds/14435) succeeded 0caae6934943c3f248043ed07b4d40005650faf8
* :green_heart: [Build #14408](https://buildkite.com/elastic/integrations/builds/14408) succeeded ec90d748cbbf643d1a0eab238ecf458d4e3f4032
* :broken_heart: [Build #14401](https://buildkite.com/elastic/integrations/builds/14401) failed d0770769e400350cf9ec3b6efeaa6fbf0076321b
* :broken_heart: [Build #14400](https://buildkite.com/elastic/integrations/builds/14400) failed d1159c73612fd07b1117f3d439703ef4c61f5548
* :broken_heart: [Build #14399](https://buildkite.com/elastic/integrations/builds/14399) failed cd526b66b77a6173678602d7d0b1d98ada12556e

cc @wshaman

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14519","number":14519,"commit":"590209cfd756f1b228d480d40f876f5694136c24"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14488","number":14488,"commit":"2450e0a63f7a297437fe6d1ab3c3b0ea4b2935bf"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14435","number":14435,"commit":"0caae6934943c3f248043ed07b4d40005650faf8"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14408","number":14408,"commit":"ec90d748cbbf643d1a0eab238ecf458d4e3f4032"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14401","number":14401,"commit":"d0770769e400350cf9ec3b6efeaa6fbf0076321b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14400","number":14400,"commit":"d1159c73612fd07b1117f3d439703ef4c61f5548"}],"number":14519}
buildkite-pr-comment-->

2024-08-09 15:42 UTC, chrisberkhout requested changes
Looking good.

I feel like it's 80% there.

The main issues are the pagination logic and ECS mappings. The other points are tweaks.

2024-08-09 15:42 UTC, chrisberkhout commented on packages/jamf_pro/data_stream/inventory/agent/stream/cel.yml.hbs
> +      "page": [string(state.?cursor.?page.orValue(int(0)))]
**Important issue**

Currently the pagination logic will make requests with the default sort order, default to page 0 to begin, then increment the page number with each successive request. That incrementing page number will persist between restarts because it is passed forward in `state.cursor`. Currently it is never reset.
The `want_more` flag will indicate whether we want to get another page immediately. When it is set to false, the input will wait for `interval` time and then run again, but it will still have access to the `state.cursor` data from the previous request.

Usually we want to fetch all data once, then periodically poll for new or updated data.

A version of this is what is recommended by Jamf. Read the last paragraph of [this page](https://developer.jamf.com/developer-guide/docs/jamf-pro-api-scalability-best-practices#frequency-of-syncs), under "Frequency of Syncs".

Think about setting up pagination so it works like this:
- initial request with default values (sort order `general.reportDate:asc`, no filter)
- additional page request from initial pagination sequence
- new pagination sequence with `general.reportDate` filtered to >= max of last seen.
- same `general.reportDate` filter value reused for rest of pagination sequence

2024-08-09 15:42 UTC, chrisberkhout commented on packages/jamf_pro/data_stream/inventory/_dev/deploy/docker/files/config.yml
> +          {
when i ran `elastic-package format`, this fairly nicely formatted JSON turned into:

```yaml
    responses:
      - status_code: 200
        body: "{\n  \"totalCount\": 8,\n  \"results\": [\n...
```

I think that's because of the blank lines in the JSON. If you pretty print the JSON first (`jq .`), and put it here at the current level of indentation, the `elastic-package format` will leave it there in a readable form.

2024-08-09 15:42 UTC, chrisberkhout commented on packages/jamf_pro/data_stream/inventory/elasticsearch/ingest_pipeline/default.yml
> +    field: jamf_pro.inventory.error.message
Set this in `error.message` instead.

2024-08-09 15:42 UTC, chrisberkhout commented on packages/jamf_pro/data_stream/inventory/fields/fields-disk_encryption.yml
> +- name: jamf_pro
probably nice to not mix `-` and `_`. This could just be 
```
packages/jamf_pro/data_stream/inventory/fields/fields-disk-encryption.yml
```
(other files too)

2024-08-09 15:42 UTC, chrisberkhout commented on packages/jamf_pro/data_stream/inventory/sample_event.json
> +        }
these host fields are from the agent. Usually we don't want that. In `cel.yml.hbs`, this part should disable adding these fields:
```
{{#contains "forwarded" tags}}
publisher_pipeline.disable_host: true
{{/contains}}
```
The usual pattern is to add `forwarded` as a default tag in a manifest variable so that logic is activated. Or we could just hard-code it, because it doesn't make sense to add it for this type of integration. It's still good to set that `forwarded` tag.

2024-08-09 15:42 UTC, chrisberkhout commented on packages/jamf_pro/data_stream/inventory/sample_event.json
> +        }
The `forwarded` tag means that data is forwarded (by the agent) from another source (the API).

2024-08-09 15:42 UTC, chrisberkhout commented on packages/jamf_pro/data_stream/inventory/elasticsearch/ingest_pipeline/default.yml
> +    field: jamf_pro.inventory.error.message
And set `event.kind` to `pipeline_error`.

2024-08-09 15:42 UTC, chrisberkhout commented on packages/jamf_pro/data_stream/inventory/sample_event.json
> +    }
JAMF Pro fields should be copied to ECS fields wherever the values will make sense.

Go through the different sections of the [ECS Field Reference](https://www.elastic.co/guide/en/ecs/current/ecs-field-reference.html) to find relevant fields.

Some good ECS field mapping ideas are the:
- `related.*` fields
- maybe `user.*` fields
- `os.*` fields
- `device.*` fields


Would also be good to give the user the option (default off) to set `event.original` to the JSON string of the original event. Since you already have that data parsed, it would need to be re-serialized, probably in the CEL. The `ti_opencti` integration is one example of doing it in CEL, based of the setting of the policy option.

2024-08-09 15:42 UTC, chrisberkhout commented on packages/jamf_pro/docs/README.md
> +```json
The README should be in
```
packages/jamf_pro/_dev/build/docs/README.md
```
in order for `elastic-package build` to run some templating and generate
```
packages/jamf_pro/README.md
```
Doing it that way you can get the `sample_event.json` embedded automatically with
```
{{event "inventory"}}
```
and a table of field names and types with
```
{{fields "inventory"}}
```

2024-08-09 15:42 UTC, chrisberkhout commented on packages/jamf_pro/docs/README.md
> +Credentials generated during this process are required for the subsequent steps.
Would be good to say in this earlier section exactly which credentials are will be gathered, using the terminology form the Jamf documentation.

Also, list the required Jamf Pro API role privileges that should be set.

Don't worry about repeating information that is very clear in the linked documentation.

2024-08-09 15:42 UTC, chrisberkhout commented on packages/jamf_pro/docs/README.md
> +Credentials generated during this process are required for the subsequent steps.
Oh, I see these things are above in Requirements. In Requirements I would put just the "Jamf Pro Active License", then put the other credentials and permission details down here in the setup section.

2024-08-09 15:42 UTC, chrisberkhout commented on packages/jamf_pro/img/jamfpro_map.png
in the dashboard, according to our dashboard style guide, it's better to not have top-level filters, but instead to set filters on each panel/element in the dashboard.

2024-08-09 15:42 UTC, chrisberkhout commented on packages/jamf_pro/docs/README.md
> +```json
Commit both the source and the generated README files.

2024-08-09 15:45 UTC, chrisberkhout commented on packages/jamf_pro/data_stream/inventory/_dev/deploy/docker/files/config.yml
> +rules:
We usually put this system test mock stuff at the top level (`packages/jamf_pro/_dev/deploy/...`). I think the point is that one container can be used for system tests for multiple data streams. So it's probably good to do that, especially since we may add additional data streams at some point.

2024-08-09 15:46 UTC, chrisberkhout commented on packages/jamf_pro/manifest.yml
> +            required: true
Missing a `title` field.

2024-08-12 10:25 UTC, wshaman commented on packages/jamf_pro/docs/README.md
> +```json
Fixed here: https://github.com/elastic/integrations/commit/f14ac3cd76447c66b928f69b7b61d4332b3bade6

2024-08-12 10:27 UTC, wshaman commented on packages/jamf_pro/LICENSE.txt
> +Elastic License 2.0
Fixed here: https://github.com/elastic/integrations/commit/cf60f0ded1b988e1d469de87e2e0051e4a8614d7

2024-08-12 10:30 UTC, wshaman commented on packages/jamf_pro/changelog.yml
> +- version: "0.0.1"
Fixed here: https://github.com/elastic/integrations/commit/884638e7c49f106ad6a96f2a70b6409523b23794

2024-08-12 10:30 UTC, wshaman commented on packages/jamf_pro/changelog.yml
> +    - description: Initial Release of Jamf Pro Integration
Fixed here: https://github.com/elastic/integrations/commit/884638e7c49f106ad6a96f2a70b6409523b23794

2024-08-12 10:43 UTC, wshaman commented on packages/jamf_pro/data_stream/inventory/fields/base-fields.yml
> +  type: keyword
Fixed here: https://github.com/elastic/integrations/commit/6981d484e0ee63a0f4df302a60c3230e2c2ba307

2024-08-12 10:54 UTC, wshaman commented on packages/jamf_pro/data_stream/inventory/agent/stream/cel.yml.hbs
> +      "page": [string(state.?cursor.?page.orValue(int(0)))]
Yes, this conversion is required 
`ERROR: <input>:12:19: no such overload for format_url: type conversion error from Double to 'string'`
`.?` is required as `cursor` doesn't have `page`  at first iteration thus execution failing.

2024-08-12 10:55 UTC, wshaman commented on packages/jamf_pro/data_stream/inventory/agent/stream/cel.yml.hbs
> +          "cursor": {"page": int(state.?cursor.?page.orValue(int(0))) + 1},
It is required at first iteration.

2024-08-12 11:15 UTC, wshaman commented on packages/jamf_pro/data_stream/inventory/agent/stream/cel.yml.hbs
> +          "want_more": (int(state.?cursor.?page.orValue(int(0))) + 1) * int(state.page_size) < int(body.totalCount),
We have a field `"totalCount": X` which stands the same for each page we request. 
E.g. we have 167 resuls, totalCount:167, while body.results will be 100 on 1st page, 67 on 2nd.
There is an option to keep current length in cursor and use it to calculate total count 
smth like  `"cursor:" {"count" : state.?cursor.count+ body.results.len(), "page": state.cursor.page+1}` but in this case we are storing both `page` and `page * page_size`
Type conversions fixed here: https://github.com/elastic/integrations/commit/777a00d80ec6572237ff59bc641b489152c46f6b

2024-08-12 11:18 UTC, wshaman commented on packages/jamf_pro/data_stream/inventory/elasticsearch/ingest_pipeline/default.yml
> +    field: jamf_pro.inventory.error.message
Fixed here: https://github.com/elastic/integrations/commit/72e828ec783c06939a18ec88a6041a2da39e6a28

2024-08-12 11:39 UTC, wshaman commented on packages/jamf_pro/data_stream/inventory/sample_event.json
> +        }
Fixed here: https://github.com/elastic/integrations/commit/e5e613857c958c1e5bdc6c0fbca917709d17eb24

2024-08-12 14:51 UTC, alexwizp commented
/test

2024-08-12 15:08 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14583)
* Commit: e5e613857c958c1e5bdc6c0fbca917709d17eb24

### Failed CI Steps
* [Check integrations jamf_pro](https://buildkite.com/elastic/integrations/builds/14583#01914719-5322-4eac-982d-08343c8f37ae)

### History
* :green_heart: [Build #14519](https://buildkite.com/elastic/integrations/builds/14519) succeeded 590209cfd756f1b228d480d40f876f5694136c24
* :green_heart: [Build #14488](https://buildkite.com/elastic/integrations/builds/14488) succeeded 2450e0a63f7a297437fe6d1ab3c3b0ea4b2935bf
* :green_heart: [Build #14435](https://buildkite.com/elastic/integrations/builds/14435) succeeded 0caae6934943c3f248043ed07b4d40005650faf8
* :green_heart: [Build #14408](https://buildkite.com/elastic/integrations/builds/14408) succeeded ec90d748cbbf643d1a0eab238ecf458d4e3f4032
* :broken_heart: [Build #14401](https://buildkite.com/elastic/integrations/builds/14401) failed d0770769e400350cf9ec3b6efeaa6fbf0076321b
* :broken_heart: [Build #14400](https://buildkite.com/elastic/integrations/builds/14400) failed d1159c73612fd07b1117f3d439703ef4c61f5548

cc @wshaman

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14583","number":14583,"commit":"e5e613857c958c1e5bdc6c0fbca917709d17eb24"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14519","number":14519,"commit":"590209cfd756f1b228d480d40f876f5694136c24"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14488","number":14488,"commit":"2450e0a63f7a297437fe6d1ab3c3b0ea4b2935bf"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14435","number":14435,"commit":"0caae6934943c3f248043ed07b4d40005650faf8"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14408","number":14408,"commit":"ec90d748cbbf643d1a0eab238ecf458d4e3f4032"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14401","number":14401,"commit":"d0770769e400350cf9ec3b6efeaa6fbf0076321b"}],"number":14583}
buildkite-pr-comment-->

2024-08-12 15:28 UTC, alexwizp commented
/test

2024-08-12 15:41 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14587)
* Commit: eb3304360d96479449723e8f38c00879f66e9698

### Failed CI Steps
* [Check integrations jamf_pro](https://buildkite.com/elastic/integrations/builds/14587#01914739-14e3-436e-b7d4-abe5225129ee)

### History
* :broken_heart: [Build #14583](https://buildkite.com/elastic/integrations/builds/14583) failed e5e613857c958c1e5bdc6c0fbca917709d17eb24
* :green_heart: [Build #14519](https://buildkite.com/elastic/integrations/builds/14519) succeeded 590209cfd756f1b228d480d40f876f5694136c24
* :green_heart: [Build #14488](https://buildkite.com/elastic/integrations/builds/14488) succeeded 2450e0a63f7a297437fe6d1ab3c3b0ea4b2935bf
* :green_heart: [Build #14435](https://buildkite.com/elastic/integrations/builds/14435) succeeded 0caae6934943c3f248043ed07b4d40005650faf8
* :green_heart: [Build #14408](https://buildkite.com/elastic/integrations/builds/14408) succeeded ec90d748cbbf643d1a0eab238ecf458d4e3f4032

cc @wshaman

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14587","number":14587,"commit":"eb3304360d96479449723e8f38c00879f66e9698"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14583","number":14583,"commit":"e5e613857c958c1e5bdc6c0fbca917709d17eb24"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14519","number":14519,"commit":"590209cfd756f1b228d480d40f876f5694136c24"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14488","number":14488,"commit":"2450e0a63f7a297437fe6d1ab3c3b0ea4b2935bf"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14435","number":14435,"commit":"0caae6934943c3f248043ed07b4d40005650faf8"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14408","number":14408,"commit":"ec90d748cbbf643d1a0eab238ecf458d4e3f4032"}],"number":14587}
buildkite-pr-comment-->

2024-08-12 15:57 UTC, alexwizp commented
/test

2024-08-12 16:11 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14589)
* Commit: b3ba030903fc7006fd9724fc8f2f07f641a89816

### Failed CI Steps
* [Check integrations jamf_pro](https://buildkite.com/elastic/integrations/builds/14589#01914753-ca02-44bc-895e-eb24b688b81e)

### History
* :broken_heart: [Build #14587](https://buildkite.com/elastic/integrations/builds/14587) failed eb3304360d96479449723e8f38c00879f66e9698
* :broken_heart: [Build #14583](https://buildkite.com/elastic/integrations/builds/14583) failed e5e613857c958c1e5bdc6c0fbca917709d17eb24
* :green_heart: [Build #14519](https://buildkite.com/elastic/integrations/builds/14519) succeeded 590209cfd756f1b228d480d40f876f5694136c24
* :green_heart: [Build #14488](https://buildkite.com/elastic/integrations/builds/14488) succeeded 2450e0a63f7a297437fe6d1ab3c3b0ea4b2935bf
* :green_heart: [Build #14435](https://buildkite.com/elastic/integrations/builds/14435) succeeded 0caae6934943c3f248043ed07b4d40005650faf8

cc @wshaman

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14589","number":14589,"commit":"b3ba030903fc7006fd9724fc8f2f07f641a89816"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14587","number":14587,"commit":"eb3304360d96479449723e8f38c00879f66e9698"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14583","number":14583,"commit":"e5e613857c958c1e5bdc6c0fbca917709d17eb24"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14519","number":14519,"commit":"590209cfd756f1b228d480d40f876f5694136c24"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14488","number":14488,"commit":"2450e0a63f7a297437fe6d1ab3c3b0ea4b2935bf"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14435","number":14435,"commit":"0caae6934943c3f248043ed07b4d40005650faf8"}],"number":14589}
buildkite-pr-comment-->

2024-08-12 16:41 UTC, alexwizp commented
/test

2024-08-12 16:57 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14591)
* Commit: 11f2713b2fd5773a99f0a89f10415c8d8eb73a38

### History
* :broken_heart: [Build #14589](https://buildkite.com/elastic/integrations/builds/14589) failed b3ba030903fc7006fd9724fc8f2f07f641a89816
* :broken_heart: [Build #14587](https://buildkite.com/elastic/integrations/builds/14587) failed eb3304360d96479449723e8f38c00879f66e9698
* :broken_heart: [Build #14583](https://buildkite.com/elastic/integrations/builds/14583) failed e5e613857c958c1e5bdc6c0fbca917709d17eb24
* :green_heart: [Build #14519](https://buildkite.com/elastic/integrations/builds/14519) succeeded 590209cfd756f1b228d480d40f876f5694136c24
* :green_heart: [Build #14488](https://buildkite.com/elastic/integrations/builds/14488) succeeded 2450e0a63f7a297437fe6d1ab3c3b0ea4b2935bf

cc @wshaman

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14591","number":14591,"commit":"11f2713b2fd5773a99f0a89f10415c8d8eb73a38"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14589","number":14589,"commit":"b3ba030903fc7006fd9724fc8f2f07f641a89816"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14587","number":14587,"commit":"eb3304360d96479449723e8f38c00879f66e9698"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14583","number":14583,"commit":"e5e613857c958c1e5bdc6c0fbca917709d17eb24"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14519","number":14519,"commit":"590209cfd756f1b228d480d40f876f5694136c24"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14488","number":14488,"commit":"2450e0a63f7a297437fe6d1ab3c3b0ea4b2935bf"}],"number":14591}
buildkite-pr-comment-->

2024-08-12 17:36 UTC, alexwizp commented
/test

2024-08-12 17:52 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14595)
* Commit: bc019e53b0da461ee18bf14c0bcdce2e8be7428f

### History
* :green_heart: [Build #14591](https://buildkite.com/elastic/integrations/builds/14591) succeeded 11f2713b2fd5773a99f0a89f10415c8d8eb73a38
* :broken_heart: [Build #14589](https://buildkite.com/elastic/integrations/builds/14589) failed b3ba030903fc7006fd9724fc8f2f07f641a89816
* :broken_heart: [Build #14587](https://buildkite.com/elastic/integrations/builds/14587) failed eb3304360d96479449723e8f38c00879f66e9698
* :broken_heart: [Build #14583](https://buildkite.com/elastic/integrations/builds/14583) failed e5e613857c958c1e5bdc6c0fbca917709d17eb24
* :green_heart: [Build #14519](https://buildkite.com/elastic/integrations/builds/14519) succeeded 590209cfd756f1b228d480d40f876f5694136c24
* :green_heart: [Build #14488](https://buildkite.com/elastic/integrations/builds/14488) succeeded 2450e0a63f7a297437fe6d1ab3c3b0ea4b2935bf

cc @wshaman

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14595","number":14595,"commit":"bc019e53b0da461ee18bf14c0bcdce2e8be7428f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14591","number":14591,"commit":"11f2713b2fd5773a99f0a89f10415c8d8eb73a38"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14589","number":14589,"commit":"b3ba030903fc7006fd9724fc8f2f07f641a89816"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14587","number":14587,"commit":"eb3304360d96479449723e8f38c00879f66e9698"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14583","number":14583,"commit":"e5e613857c958c1e5bdc6c0fbca917709d17eb24"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14519","number":14519,"commit":"590209cfd756f1b228d480d40f876f5694136c24"}],"number":14595}
buildkite-pr-comment-->

2024-08-12 18:44 UTC, wshaman commented on packages/jamf_pro/data_stream/inventory/_dev/deploy/docker/files/config.yml
> +rules:
Fixed here: https://github.com/elastic/integrations/pull/10470/commits/ee6cb1b9a156e3cc1e17a86f49be917fff5fb51e

2024-08-12 18:44 UTC, wshaman commented on packages/jamf_pro/data_stream/inventory/fields/fields-disk_encryption.yml
> +- name: jamf_pro
Fixed here: https://github.com/elastic/integrations/pull/10470/commits/bc019e53b0da461ee18bf14c0bcdce2e8be7428f

2024-08-12 18:45 UTC, wshaman commented on packages/jamf_pro/data_stream/inventory/_dev/test/pipeline/test-inventory.json
> +{
Fixed here: https://github.com/elastic/integrations/pull/10470/commits/bc019e53b0da461ee18bf14c0bcdce2e8be7428f

2024-08-12 18:45 UTC, alexwizp commented
/test

2024-08-12 18:47 UTC, wshaman commented on packages/jamf_pro/data_stream/inventory/agent/stream/cel.yml.hbs
> +  {{#if enable_section_general }} "GENERAL", {{/if}}
Fixed here: https://github.com/elastic/integrations/pull/10470/commits/777a00d80ec6572237ff59bc641b489152c46f6b  https://github.com/elastic/integrations/pull/10470/commits/11f2713b2fd5773a99f0a89f10415c8d8eb73a38

2024-08-12 18:48 UTC, wshaman commented on packages/jamf_pro/data_stream/inventory/agent/stream/cel.yml.hbs
> +      "page": [string(state.?cursor.?page.orValue(int(0)))]
Reset cursor value: https://github.com/elastic/integrations/pull/10470/commits/961d77e6c9f162a2ae98d330164a1ac012cecb83

2024-08-12 18:49 UTC, wshaman commented on packages/jamf_pro/data_stream/inventory/_dev/deploy/docker/files/config.yml
> +          {
Fixed here: https://github.com/elastic/integrations/pull/10470/commits/bc019e53b0da461ee18bf14c0bcdce2e8be7428f

2024-08-12 18:52 UTC, wshaman commented on packages/jamf_pro/data_stream/inventory/_dev/deploy/docker/files/config.yml
> +rules:
Fixed here: https://github.com/elastic/integrations/commit/ee6cb1b9a156e3cc1e17a86f49be917fff5fb51e

2024-08-12 19:00 UTC, wshaman commented on packages/jamf_pro/docs/README.md
> +Credentials generated during this process are required for the subsequent steps.
Fixed here: https://github.com/elastic/integrations/commit/e296a88fbb92ffb61796ce05cf4db6f84907e225

2024-08-12 19:00 UTC, wshaman commented on packages/jamf_pro/manifest.yml
> +            required: true
Fixed here: https://github.com/elastic/integrations/commit/e296a88fbb92ffb61796ce05cf4db6f84907e225

2024-08-12 19:04 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14600)
* Commit: ee6cb1b9a156e3cc1e17a86f49be917fff5fb51e

### History
* :green_heart: [Build #14595](https://buildkite.com/elastic/integrations/builds/14595) succeeded bc019e53b0da461ee18bf14c0bcdce2e8be7428f
* :green_heart: [Build #14591](https://buildkite.com/elastic/integrations/builds/14591) succeeded 11f2713b2fd5773a99f0a89f10415c8d8eb73a38
* :broken_heart: [Build #14589](https://buildkite.com/elastic/integrations/builds/14589) failed b3ba030903fc7006fd9724fc8f2f07f641a89816
* :broken_heart: [Build #14587](https://buildkite.com/elastic/integrations/builds/14587) failed eb3304360d96479449723e8f38c00879f66e9698
* :broken_heart: [Build #14583](https://buildkite.com/elastic/integrations/builds/14583) failed e5e613857c958c1e5bdc6c0fbca917709d17eb24
* :green_heart: [Build #14519](https://buildkite.com/elastic/integrations/builds/14519) succeeded 590209cfd756f1b228d480d40f876f5694136c24

cc @wshaman

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14600","number":14600,"commit":"ee6cb1b9a156e3cc1e17a86f49be917fff5fb51e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14595","number":14595,"commit":"bc019e53b0da461ee18bf14c0bcdce2e8be7428f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14591","number":14591,"commit":"11f2713b2fd5773a99f0a89f10415c8d8eb73a38"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14589","number":14589,"commit":"b3ba030903fc7006fd9724fc8f2f07f641a89816"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14587","number":14587,"commit":"eb3304360d96479449723e8f38c00879f66e9698"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14583","number":14583,"commit":"e5e613857c958c1e5bdc6c0fbca917709d17eb24"}],"number":14600}
buildkite-pr-comment-->

2024-08-12 19:07 UTC, wshaman commented on packages/jamf_pro/img/jamfpro_map.png
Fixed here: https://github.com/elastic/integrations/pull/10470/commits/5c5a8424e6ee893b5ab2e4efc1a68614bd89c550

2024-08-13 07:01 UTC, alexwizp commented
/test

2024-08-13 07:17 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14620)
* Commit: 5c5a8424e6ee893b5ab2e4efc1a68614bd89c550

### History
* :green_heart: [Build #14600](https://buildkite.com/elastic/integrations/builds/14600) succeeded ee6cb1b9a156e3cc1e17a86f49be917fff5fb51e
* :green_heart: [Build #14595](https://buildkite.com/elastic/integrations/builds/14595) succeeded bc019e53b0da461ee18bf14c0bcdce2e8be7428f
* :green_heart: [Build #14591](https://buildkite.com/elastic/integrations/builds/14591) succeeded 11f2713b2fd5773a99f0a89f10415c8d8eb73a38
* :broken_heart: [Build #14589](https://buildkite.com/elastic/integrations/builds/14589) failed b3ba030903fc7006fd9724fc8f2f07f641a89816
* :broken_heart: [Build #14587](https://buildkite.com/elastic/integrations/builds/14587) failed eb3304360d96479449723e8f38c00879f66e9698
* :broken_heart: [Build #14583](https://buildkite.com/elastic/integrations/builds/14583) failed e5e613857c958c1e5bdc6c0fbca917709d17eb24

cc @wshaman

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14620","number":14620,"commit":"5c5a8424e6ee893b5ab2e4efc1a68614bd89c550"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14600","number":14600,"commit":"ee6cb1b9a156e3cc1e17a86f49be917fff5fb51e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14595","number":14595,"commit":"bc019e53b0da461ee18bf14c0bcdce2e8be7428f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14591","number":14591,"commit":"11f2713b2fd5773a99f0a89f10415c8d8eb73a38"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14589","number":14589,"commit":"b3ba030903fc7006fd9724fc8f2f07f641a89816"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14587","number":14587,"commit":"eb3304360d96479449723e8f38c00879f66e9698"}],"number":14620}
buildkite-pr-comment-->

2024-08-13 16:36 UTC, alexwizp commented
/test

2024-08-13 16:53 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14627)
* Commit: 9a5a9fc40e23979d451bf87b696193d07e6027dd

### History
* :green_heart: [Build #14620](https://buildkite.com/elastic/integrations/builds/14620) succeeded 5c5a8424e6ee893b5ab2e4efc1a68614bd89c550
* :green_heart: [Build #14600](https://buildkite.com/elastic/integrations/builds/14600) succeeded ee6cb1b9a156e3cc1e17a86f49be917fff5fb51e
* :green_heart: [Build #14595](https://buildkite.com/elastic/integrations/builds/14595) succeeded bc019e53b0da461ee18bf14c0bcdce2e8be7428f
* :green_heart: [Build #14591](https://buildkite.com/elastic/integrations/builds/14591) succeeded 11f2713b2fd5773a99f0a89f10415c8d8eb73a38
* :broken_heart: [Build #14589](https://buildkite.com/elastic/integrations/builds/14589) failed b3ba030903fc7006fd9724fc8f2f07f641a89816
* :broken_heart: [Build #14587](https://buildkite.com/elastic/integrations/builds/14587) failed eb3304360d96479449723e8f38c00879f66e9698

cc @wshaman

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14627","number":14627,"commit":"9a5a9fc40e23979d451bf87b696193d07e6027dd"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14620","number":14620,"commit":"5c5a8424e6ee893b5ab2e4efc1a68614bd89c550"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14600","number":14600,"commit":"ee6cb1b9a156e3cc1e17a86f49be917fff5fb51e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14595","number":14595,"commit":"bc019e53b0da461ee18bf14c0bcdce2e8be7428f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14591","number":14591,"commit":"11f2713b2fd5773a99f0a89f10415c8d8eb73a38"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14589","number":14589,"commit":"b3ba030903fc7006fd9724fc8f2f07f641a89816"}],"number":14627}
buildkite-pr-comment-->

2024-08-13 18:04 UTC, wshaman commented on packages/jamf_pro/data_stream/inventory/agent/stream/cel.yml.hbs
> +      "page": [string(state.?cursor.?page.orValue(int(0)))]
Fixed here: https://github.com/elastic/integrations/pull/10470/commits/d2d2a2858637307a3ab5387d3f528aead6ffa751

2024-08-14 07:17 UTC, alexwizp commented
/test

2024-08-14 07:27 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14643)
* Commit: f013a28ea82ed6ff6adbf08dc941bed6fa598b63

### Failed CI Steps
* [Check integrations jamf_pro](https://buildkite.com/elastic/integrations/builds/14643#01914fc4-b068-4e16-9626-3ec7df2b3f46)

### History
* :green_heart: [Build #14627](https://buildkite.com/elastic/integrations/builds/14627) succeeded 9a5a9fc40e23979d451bf87b696193d07e6027dd
* :green_heart: [Build #14620](https://buildkite.com/elastic/integrations/builds/14620) succeeded 5c5a8424e6ee893b5ab2e4efc1a68614bd89c550
* :green_heart: [Build #14600](https://buildkite.com/elastic/integrations/builds/14600) succeeded ee6cb1b9a156e3cc1e17a86f49be917fff5fb51e
* :green_heart: [Build #14595](https://buildkite.com/elastic/integrations/builds/14595) succeeded bc019e53b0da461ee18bf14c0bcdce2e8be7428f
* :green_heart: [Build #14591](https://buildkite.com/elastic/integrations/builds/14591) succeeded 11f2713b2fd5773a99f0a89f10415c8d8eb73a38
* :broken_heart: [Build #14589](https://buildkite.com/elastic/integrations/builds/14589) failed b3ba030903fc7006fd9724fc8f2f07f641a89816

cc @wshaman

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14643","number":14643,"commit":"f013a28ea82ed6ff6adbf08dc941bed6fa598b63"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14627","number":14627,"commit":"9a5a9fc40e23979d451bf87b696193d07e6027dd"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14620","number":14620,"commit":"5c5a8424e6ee893b5ab2e4efc1a68614bd89c550"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14600","number":14600,"commit":"ee6cb1b9a156e3cc1e17a86f49be917fff5fb51e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14595","number":14595,"commit":"bc019e53b0da461ee18bf14c0bcdce2e8be7428f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14591","number":14591,"commit":"11f2713b2fd5773a99f0a89f10415c8d8eb73a38"}],"number":14643}
buildkite-pr-comment-->

2024-08-14 10:10 UTC, wshaman commented on packages/jamf_pro/data_stream/inventory/agent/stream/cel.yml.hbs
> +      "page": [string(state.?cursor.?page.orValue(int(0)))]
Rework here: https://github.com/elastic/integrations/pull/10470/commits/66d406b88917c1c78f6ea44986570c247f5656a5

2024-08-14 10:10 UTC, wshaman commented on packages/jamf_pro/data_stream/inventory/_dev/deploy/docker/files/config.yml
> +    responses:
Fixed here: https://github.com/elastic/integrations/pull/10470/commits/66d406b88917c1c78f6ea44986570c247f5656a5

2024-08-14 10:10 UTC, alexwizp commented
/test

2024-08-14 10:20 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14651)
* Commit: 5d1de99735f1fe0d6f8fff3262eff5ada224d97b

### Failed CI Steps
* [Check integrations jamf_pro](https://buildkite.com/elastic/integrations/builds/14651#01915063-0f7f-4bc7-ba88-c445e103bcc3)

### History
* :broken_heart: [Build #14643](https://buildkite.com/elastic/integrations/builds/14643) failed f013a28ea82ed6ff6adbf08dc941bed6fa598b63
* :green_heart: [Build #14627](https://buildkite.com/elastic/integrations/builds/14627) succeeded 9a5a9fc40e23979d451bf87b696193d07e6027dd
* :green_heart: [Build #14620](https://buildkite.com/elastic/integrations/builds/14620) succeeded 5c5a8424e6ee893b5ab2e4efc1a68614bd89c550
* :green_heart: [Build #14600](https://buildkite.com/elastic/integrations/builds/14600) succeeded ee6cb1b9a156e3cc1e17a86f49be917fff5fb51e
* :green_heart: [Build #14595](https://buildkite.com/elastic/integrations/builds/14595) succeeded bc019e53b0da461ee18bf14c0bcdce2e8be7428f

cc @wshaman

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14651","number":14651,"commit":"5d1de99735f1fe0d6f8fff3262eff5ada224d97b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14643","number":14643,"commit":"f013a28ea82ed6ff6adbf08dc941bed6fa598b63"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14627","number":14627,"commit":"9a5a9fc40e23979d451bf87b696193d07e6027dd"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14620","number":14620,"commit":"5c5a8424e6ee893b5ab2e4efc1a68614bd89c550"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14600","number":14600,"commit":"ee6cb1b9a156e3cc1e17a86f49be917fff5fb51e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14595","number":14595,"commit":"bc019e53b0da461ee18bf14c0bcdce2e8be7428f"}],"number":14651}
buildkite-pr-comment-->

2024-08-14 10:54 UTC, wshaman commented on packages/jamf_pro/data_stream/inventory/sample_event.json
> +    }
Fixed here: https://github.com/elastic/integrations/pull/10470/commits/c87802e0ec7cd06853a27e752d97721ed997244b

2024-08-14 11:32 UTC, alexwizp commented
/test

2024-08-14 11:50 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14654)
* Commit: c87802e0ec7cd06853a27e752d97721ed997244b

### History
* :broken_heart: [Build #14651](https://buildkite.com/elastic/integrations/builds/14651) failed 5d1de99735f1fe0d6f8fff3262eff5ada224d97b
* :broken_heart: [Build #14643](https://buildkite.com/elastic/integrations/builds/14643) failed f013a28ea82ed6ff6adbf08dc941bed6fa598b63
* :green_heart: [Build #14627](https://buildkite.com/elastic/integrations/builds/14627) succeeded 9a5a9fc40e23979d451bf87b696193d07e6027dd
* :green_heart: [Build #14620](https://buildkite.com/elastic/integrations/builds/14620) succeeded 5c5a8424e6ee893b5ab2e4efc1a68614bd89c550
* :green_heart: [Build #14600](https://buildkite.com/elastic/integrations/builds/14600) succeeded ee6cb1b9a156e3cc1e17a86f49be917fff5fb51e

cc @wshaman

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14654","number":14654,"commit":"c87802e0ec7cd06853a27e752d97721ed997244b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14651","number":14651,"commit":"5d1de99735f1fe0d6f8fff3262eff5ada224d97b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14643","number":14643,"commit":"f013a28ea82ed6ff6adbf08dc941bed6fa598b63"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14627","number":14627,"commit":"9a5a9fc40e23979d451bf87b696193d07e6027dd"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14620","number":14620,"commit":"5c5a8424e6ee893b5ab2e4efc1a68614bd89c550"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14600","number":14600,"commit":"ee6cb1b9a156e3cc1e17a86f49be917fff5fb51e"}],"number":14654}
buildkite-pr-comment-->

2024-08-14 13:33 UTC, alexwizp commented
/test

2024-08-14 13:51 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14656)
* Commit: f6887de2d83ce3b03078ced8adbd7a429682c6d2

### History
* :green_heart: [Build #14654](https://buildkite.com/elastic/integrations/builds/14654) succeeded c87802e0ec7cd06853a27e752d97721ed997244b
* :broken_heart: [Build #14651](https://buildkite.com/elastic/integrations/builds/14651) failed 5d1de99735f1fe0d6f8fff3262eff5ada224d97b
* :broken_heart: [Build #14643](https://buildkite.com/elastic/integrations/builds/14643) failed f013a28ea82ed6ff6adbf08dc941bed6fa598b63
* :green_heart: [Build #14627](https://buildkite.com/elastic/integrations/builds/14627) succeeded 9a5a9fc40e23979d451bf87b696193d07e6027dd
* :green_heart: [Build #14620](https://buildkite.com/elastic/integrations/builds/14620) succeeded 5c5a8424e6ee893b5ab2e4efc1a68614bd89c550
* :green_heart: [Build #14600](https://buildkite.com/elastic/integrations/builds/14600) succeeded ee6cb1b9a156e3cc1e17a86f49be917fff5fb51e

cc @wshaman

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14656","number":14656,"commit":"f6887de2d83ce3b03078ced8adbd7a429682c6d2"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14654","number":14654,"commit":"c87802e0ec7cd06853a27e752d97721ed997244b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14651","number":14651,"commit":"5d1de99735f1fe0d6f8fff3262eff5ada224d97b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14643","number":14643,"commit":"f013a28ea82ed6ff6adbf08dc941bed6fa598b63"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14627","number":14627,"commit":"9a5a9fc40e23979d451bf87b696193d07e6027dd"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14620","number":14620,"commit":"5c5a8424e6ee893b5ab2e4efc1a68614bd89c550"}],"number":14656}
buildkite-pr-comment-->

2024-08-23 16:41 UTC, elasticmachine commented
Pinging @elastic/security-service-integrations (Team:Security-Service Integrations)

2024-08-23 17:40 UTC, chrisberkhout requested changes
Thanks for the excellent follow-up on the last review.

There are a few more small things.

Can probably merge early next week.

2024-08-23 17:40 UTC, chrisberkhout commented on packages/jamf_pro/data_stream/inventory/elasticsearch/ingest_pipeline/default.yml
> +    field: jamf_pro.inventory.error.message
I think the fix for this one got lost in the final version.

So bring that back.
Then, it would also be good to make the message a bit more comprehensive, like this:
```
          value: 'Processor {{{_ingest.on_failure_processor_type}}} with tag {{{_ingest.on_failure_processor_tag}}} in pipeline {{{_ingest.on_failure_pipeline}}} failed with message: {{{_ingest.on_failure_message}}}'
```
and then remove the on_failure handler above for additional-info-keys-to-snake-case, so it just falls through to here.

2024-08-23 17:40 UTC, chrisberkhout commented on packages/jamf_pro/data_stream/inventory/elasticsearch/ingest_pipeline/default.yml
> +    ignore_empty_value: true
These `related.*` fields should have array values. It's good to use the `append` processor to create the array if necessary and add a value to it.

2024-08-23 17:40 UTC, chrisberkhout commented on packages/jamf_pro/data_stream/inventory/sample_event.json
> +                "message": "cannot access method/field [mac_address] from a null def reference"
This file should be regenerated with
```
elastic-package test system --generate
```
After changing `jamf_pro.inventory.error.message` to `error.message`, etc.

The example shouldn't have errors in it, so that might require adjusting system test data or making the pipeline more resilient to missing values.

2024-08-23 17:40 UTC, chrisberkhout commented on packages/jamf_pro/data_stream/inventory/agent/stream/cel.yml.hbs
> +        optional.of(['general.reportDate>"'+state.cursor.last_report_date+'"'])
Neither option is perfect, but I think it's better to make this `>=` (and risk a loop if page_size results have the same report time to the millisecond), rather than `>` (and miss results if the report times aren't unique).

Sorry if i reversed myself on this.

2024-08-26 11:26 UTC, wshaman commented on packages/jamf_pro/data_stream/inventory/fields/base-fields.yml
> +  value: jamf_pro
Fixed here: https://github.com/elastic/integrations/pull/10470/commits/48c0fedfece35b97d8f13210e41ef1f21b4909b5

2024-08-26 11:39 UTC, wshaman commented on packages/jamf_pro/data_stream/inventory/elasticsearch/ingest_pipeline/default.yml
> +    field: jamf_pro.inventory.error.message
Fixed here: https://github.com/elastic/integrations/pull/10470/commits/cf085fee83e51cd9519ad6a21812741fa5fa5501

2024-08-26 11:39 UTC, wshaman commented on packages/jamf_pro/data_stream/inventory/sample_event.json
> +                "message": "cannot access method/field [mac_address] from a null def reference"
Fixed here: https://github.com/elastic/integrations/pull/10470/commits/cf085fee83e51cd9519ad6a21812741fa5fa5501

2024-08-26 11:47 UTC, wshaman commented on packages/jamf_pro/data_stream/inventory/elasticsearch/ingest_pipeline/default.yml
> +    ignore_empty_value: true
Fixed here: https://github.com/elastic/integrations/pull/10470/commits/db41cf7b5831ef806cf882ac2b74a069e3d3484a

2024-08-26 12:01 UTC, wshaman commented on packages/jamf_pro/data_stream/inventory/agent/stream/cel.yml.hbs
> +        optional.of(['general.reportDate>"'+state.cursor.last_report_date+'"'])
Fixed here: https://github.com/elastic/integrations/pull/10470/commits/5558eaedee9f6125814ab5620375ae89f8a4c46a

2024-08-26 12:16 UTC, alexwizp commented
/test

2024-08-26 12:31 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15031)
* Commit: 5558eaedee9f6125814ab5620375ae89f8a4c46a

### History
* :green_heart: [Build #14656](https://buildkite.com/elastic/integrations/builds/14656) succeeded f6887de2d83ce3b03078ced8adbd7a429682c6d2
* :green_heart: [Build #14654](https://buildkite.com/elastic/integrations/builds/14654) succeeded c87802e0ec7cd06853a27e752d97721ed997244b
* :broken_heart: [Build #14651](https://buildkite.com/elastic/integrations/builds/14651) failed 5d1de99735f1fe0d6f8fff3262eff5ada224d97b
* :broken_heart: [Build #14643](https://buildkite.com/elastic/integrations/builds/14643) failed f013a28ea82ed6ff6adbf08dc941bed6fa598b63
* :green_heart: [Build #14627](https://buildkite.com/elastic/integrations/builds/14627) succeeded 9a5a9fc40e23979d451bf87b696193d07e6027dd
* :green_heart: [Build #14620](https://buildkite.com/elastic/integrations/builds/14620) succeeded 5c5a8424e6ee893b5ab2e4efc1a68614bd89c550

cc @wshaman

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15031","number":15031,"commit":"5558eaedee9f6125814ab5620375ae89f8a4c46a"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14656","number":14656,"commit":"f6887de2d83ce3b03078ced8adbd7a429682c6d2"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14654","number":14654,"commit":"c87802e0ec7cd06853a27e752d97721ed997244b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14651","number":14651,"commit":"5d1de99735f1fe0d6f8fff3262eff5ada224d97b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14643","number":14643,"commit":"f013a28ea82ed6ff6adbf08dc941bed6fa598b63"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14627","number":14627,"commit":"9a5a9fc40e23979d451bf87b696193d07e6027dd"}],"number":15031}
buildkite-pr-comment-->

2024-09-02 08:31 UTC, alexwizp commented
/test

2024-09-02 08:45 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15288)
* Commit: 675799579ec3718c6e144e87e1f7badd43ac7901

### Failed CI Steps
* [Check integrations jamf_pro](https://buildkite.com/elastic/integrations/builds/15288#0191b1e1-e878-438b-a366-a9fbb3cc55ce)

### History
* :green_heart: [Build #15031](https://buildkite.com/elastic/integrations/builds/15031) succeeded 5558eaedee9f6125814ab5620375ae89f8a4c46a
* :green_heart: [Build #14656](https://buildkite.com/elastic/integrations/builds/14656) succeeded f6887de2d83ce3b03078ced8adbd7a429682c6d2
* :green_heart: [Build #14654](https://buildkite.com/elastic/integrations/builds/14654) succeeded c87802e0ec7cd06853a27e752d97721ed997244b
* :broken_heart: [Build #14651](https://buildkite.com/elastic/integrations/builds/14651) failed 5d1de99735f1fe0d6f8fff3262eff5ada224d97b
* :broken_heart: [Build #14643](https://buildkite.com/elastic/integrations/builds/14643) failed f013a28ea82ed6ff6adbf08dc941bed6fa598b63
* :green_heart: [Build #14627](https://buildkite.com/elastic/integrations/builds/14627) succeeded 9a5a9fc40e23979d451bf87b696193d07e6027dd

cc @wshaman

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15288","number":15288,"commit":"675799579ec3718c6e144e87e1f7badd43ac7901"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15031","number":15031,"commit":"5558eaedee9f6125814ab5620375ae89f8a4c46a"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14656","number":14656,"commit":"f6887de2d83ce3b03078ced8adbd7a429682c6d2"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14654","number":14654,"commit":"c87802e0ec7cd06853a27e752d97721ed997244b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14651","number":14651,"commit":"5d1de99735f1fe0d6f8fff3262eff5ada224d97b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14643","number":14643,"commit":"f013a28ea82ed6ff6adbf08dc941bed6fa598b63"}],"number":15288}
buildkite-pr-comment-->

2024-09-02 13:18 UTC, alexwizp commented
/test

2024-09-02 13:36 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15308)
* Commit: 3cbff3014cf1884f2323f76191dc49a537001bab

### History
* :broken_heart: [Build #15288](https://buildkite.com/elastic/integrations/builds/15288) failed 675799579ec3718c6e144e87e1f7badd43ac7901
* :green_heart: [Build #15031](https://buildkite.com/elastic/integrations/builds/15031) succeeded 5558eaedee9f6125814ab5620375ae89f8a4c46a
* :green_heart: [Build #14656](https://buildkite.com/elastic/integrations/builds/14656) succeeded f6887de2d83ce3b03078ced8adbd7a429682c6d2
* :green_heart: [Build #14654](https://buildkite.com/elastic/integrations/builds/14654) succeeded c87802e0ec7cd06853a27e752d97721ed997244b
* :broken_heart: [Build #14651](https://buildkite.com/elastic/integrations/builds/14651) failed 5d1de99735f1fe0d6f8fff3262eff5ada224d97b

cc @wshaman

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15308","number":15308,"commit":"3cbff3014cf1884f2323f76191dc49a537001bab"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15288","number":15288,"commit":"675799579ec3718c6e144e87e1f7badd43ac7901"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15031","number":15031,"commit":"5558eaedee9f6125814ab5620375ae89f8a4c46a"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14656","number":14656,"commit":"f6887de2d83ce3b03078ced8adbd7a429682c6d2"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14654","number":14654,"commit":"c87802e0ec7cd06853a27e752d97721ed997244b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14651","number":14651,"commit":"5d1de99735f1fe0d6f8fff3262eff5ada224d97b"}],"number":15308}
buildkite-pr-comment-->

2024-09-03 16:27 UTC, chrisberkhout requested changes

2024-09-03 16:27 UTC, chrisberkhout commented on packages/jamf_pro/_dev/build/docs/README.md
> +* _Webhook URL_ must be in form `https://your-kibana-name:9202/jamf-pro-events` Note note: `9202` is a port and `/jamf-pro-events` are default values and can be changed this connector's setup.
I think the `your-kibana-name` will actually be the Elastic Agent, which in production will usually be different from the Kibana host, so probably best to say `your-elastic-agent`.

2024-09-03 16:27 UTC, chrisberkhout commented on packages/jamf_pro/_dev/build/docs/README.md
> +#### Step 3: Create a Webhook in Jamf Pro:
Probably good to say something about SSL setup.
Does Jamf Pro force HTTPS rather than HTTP?
Can I use HTTPS with a self-signed certificate?

2024-09-03 16:27 UTC, chrisberkhout commented on packages/jamf_pro/manifest.yml
> +              key: "/etc/pki/client/cert.key"
A better example would show how certificates can be provided inline, like [this](https://github.com/elastic/integrations/blob/d4d67d2d2de5577c4339f420422f9ef1c6bb4008/packages/ping_one/manifest.yml#L40-L68).

2024-09-03 16:27 UTC, chrisberkhout commented on packages/jamf_pro/kibana/dashboard/jamf_pro-a6cf6d1d-b2a7-4a59-9fdf-51d1c7b1706e.json
> +        "title": "[Jamf Pro] Real time ",
It would be good to balance out the layout of this dashboard.

Rather than **Inventory** and **Real time** in the navigation, match the data set names.
Change Real time -> Events, and Events -> Overview in the navigation, and name the dashboard itself "[Jamf Pro] Events Overview". The other dashobards dashboard names can also be adjusted to differentiate them from the events data, e.g. "[Jamf Pro] Inventory Overview"

![image](https://github.com/user-attachments/assets/1446bd51-96ca-442c-a6ee-50ce8ab800b4)

2024-09-03 16:27 UTC, chrisberkhout commented on packages/jamf_pro/img/image.png
Can this be compressed a bit to have the same vertical size as the other dashboards?

If that's going to be too tight, it's okay that the overview is bigger, but extend the lower border of the navigation down to the lower border of the bottom panels.

2024-09-04 06:56 UTC, wshaman commented on packages/jamf_pro/data_stream/inventory/agent/stream/cel.yml.hbs
> +    - GROUP_MEMBERSHIP
Fixed here: https://github.com/elastic/integrations/pull/10470/commits/cee275710facae27df5fabd0d5047ae76203e1f1

2024-09-04 06:56 UTC, wshaman commented on packages/jamf_pro/data_stream/inventory/manifest.yml
> +        description: Period of fetching metrics, i.e. 1s/1m/1h.
Fixed here: https://github.com/elastic/integrations/pull/10470/commits/68271781e8431e152cec9e1c6f9c37062c01c467

2024-09-04 06:57 UTC, wshaman commented on packages/jamf_pro/data_stream/inventory/elasticsearch/ingest_pipeline/default.yml
> +
Fixed here: https://github.com/elastic/integrations/pull/10470/commits/fc1a0c2b036b95eccaee7ddac13a0abde60149de

2024-09-04 06:59 UTC, wshaman commented on packages/jamf_pro/data_stream/events/elasticsearch/ingest_pipeline/default.yml
> +    ignore_empty_value: true
This is about getting one value, based on response. Based on response structure these fields will be located in different objects.

2024-09-04 08:45 UTC, wshaman commented on packages/jamf_pro/manifest.yml
> +              key: "/etc/pki/client/cert.key"
Fixed here: https://github.com/elastic/integrations/pull/10470/commits/2c1ceea98484322bbf3c286008666c41e26d076a

2024-09-04 08:45 UTC, wshaman commented on packages/jamf_pro/_dev/build/docs/README.md
> +* _Webhook URL_ must be in form `https://your-kibana-name:9202/jamf-pro-events` Note note: `9202` is a port and `/jamf-pro-events` are default values and can be changed this connector's setup.
Fixed here: https://github.com/elastic/integrations/pull/10470/commits/2c1ceea98484322bbf3c286008666c41e26d076a

2024-09-04 08:46 UTC, wshaman commented on packages/jamf_pro/data_stream/inventory/_dev/test/system/test-inventory-config.yml
> +    period: 24h
Fixed here: https://github.com/elastic/integrations/pull/10470/commits/68271781e8431e152cec9e1c6f9c37062c01c467

2024-09-04 08:47 UTC, wshaman commented on packages/jamf_pro/data_stream/events/elasticsearch/ingest_pipeline/default.yml
> +    if: "ctx?.jamf_pro.events.event.ip_address != ''"
Fixed here: https://github.com/elastic/integrations/pull/10470/commits/91f51ca84eac35ca3870f2c202532763c83fc6ff

2024-09-04 08:47 UTC, wshaman commented on packages/jamf_pro/data_stream/events/elasticsearch/ingest_pipeline/default.yml
> +    ignore_failure: true
Fixed here: https://github.com/elastic/integrations/pull/10470/commits/91f51ca84eac35ca3870f2c202532763c83fc6ff

2024-09-04 08:48 UTC, wshaman commented on packages/jamf_pro/data_stream/events/elasticsearch/ingest_pipeline/default.yml
> +    ignore_failure: true
Fixed here: https://github.com/elastic/integrations/pull/10470/commits/91f51ca84eac35ca3870f2c202532763c83fc6ff

2024-09-04 08:48 UTC, wshaman commented on packages/jamf_pro/data_stream/events/elasticsearch/ingest_pipeline/default.yml
> +    if: ctx.message != null
Fixed here: https://github.com/elastic/integrations/pull/10470/commits/91f51ca84eac35ca3870f2c202532763c83fc6ff

2024-09-04 09:22 UTC, jamiehynds commented on packages/jamf_pro/_dev/build/docs/README.md
> +The connector provides integration with Jamf Pro, it is designed to enhance the management and security of Apple devices across an organization.
Can we make a slight adjustment here please:

Jamf Pro is a comprehensive management solution designed to help organizations deploy, configure, secure, and manage Apple devices. This integration enables organizations to seamlessly monitor and protect their Mac fleet through Elastic, providing a unified view of security events across all endpoints and facilitating a more effective response to threats. This integration encompasses both event and inventory data ingestion from Jamf Pro.

2024-09-04 09:23 UTC, jamiehynds commented on packages/jamf_pro/_dev/build/docs/README.md
> +* __events__ catches events, generated by [Jamf Pro Webhooks](https://developer.jamf.com/developer-guide/docs/webhooks) This datastream requires opening a port on kibana system
Is there a specific port or recommended port that we can add here. Change kibana system to Kibana instance.

2024-09-04 09:25 UTC, jamiehynds commented on packages/jamf_pro/_dev/build/docs/README.md
> +This connector utilizes Jamf Pro API, therefore active license is a requirement
Is there a specific license tier required from Jamf? If so, can we call it out here. e.g. Jamf Premium license or above is required.

2024-09-04 09:26 UTC, jamiehynds commented on packages/jamf_pro/data_stream/events/_dev/test/pipeline/test-computer-added.log-expected.json
> +                        "os_build": "string",
These os fields could be mapped to some ECS os.* fields.

2024-09-04 11:22 UTC, wshaman commented on packages/jamf_pro/data_stream/events/sample_event.json
> +    },
Fixed here: https://github.com/elastic/integrations/pull/10470/commits/3ef276f26a29b3b30689b4cfe5f2948afbf6fec6

2024-09-04 11:22 UTC, wshaman commented on packages/jamf_pro/data_stream/events/_dev/test/pipeline/test-smart-group-computer-membership-change.log
> +{"event":{"computer":true,"groupAddedDevices":[],"groupAddedDevicesIds":[],"groupRemovedDevices":[],"groupRemovedDevicesIds":[123],"jssid":123,"name":"acme-name","smartGroup":true},"webhook":{"eventT
Fixed here: https://github.com/elastic/integrations/pull/10470/commits/3ef276f26a29b3b30689b4cfe5f2948afbf6fec6

2024-09-04 12:56 UTC, wshaman commented on packages/jamf_pro/_dev/build/docs/README.md
> +This connector utilizes Jamf Pro API, therefore active license is a requirement
Addressed here: https://github.com/elastic/integrations/pull/10470/commits/6db500acec6954c1513935723d378b1b81176fe5

2024-09-05 07:10 UTC, wshaman commented on packages/jamf_pro/_dev/build/docs/README.md
> +* __events__ catches events, generated by [Jamf Pro Webhooks](https://developer.jamf.com/developer-guide/docs/webhooks) This datastream requires opening a port on kibana system
I think we can't recommend a specific port, later it is also mentioned as a point to be consulted with IT or Security department.

2024-09-05 07:12 UTC, wshaman commented on packages/jamf_pro/kibana/dashboard/jamf_pro-a6cf6d1d-b2a7-4a59-9fdf-51d1c7b1706e.json
> +        "title": "[Jamf Pro] Real time ",
As per conversation with @chrisberkhout  decided to keep as it is for now.

2024-09-05 07:12 UTC, wshaman commented on packages/jamf_pro/_dev/build/docs/README.md
> +* __events__ catches events, generated by [Jamf Pro Webhooks](https://developer.jamf.com/developer-guide/docs/webhooks) This datastream requires opening a port on kibana system
Addresses here https://github.com/elastic/integrations/pull/10470/commits/35b268b9f94410ba4c79bd105cd0127c9d0cf5f0

2024-09-05 07:12 UTC, wshaman commented on packages/jamf_pro/img/image.png
Fixed here https://github.com/elastic/integrations/pull/10470/commits/35b268b9f94410ba4c79bd105cd0127c9d0cf5f0

2024-09-05 07:13 UTC, wshaman commented on packages/jamf_pro/_dev/build/docs/README.md
> +#### Step 3: Create a Webhook in Jamf Pro:
Addressed here https://github.com/elastic/integrations/pull/10470/commits/35b268b9f94410ba4c79bd105cd0127c9d0cf5f0

2024-09-05 07:13 UTC, wshaman commented on packages/jamf_pro/_dev/build/docs/README.md
> +This connector utilizes Jamf Pro API, therefore active license is a requirement
Addressed here https://github.com/elastic/integrations/pull/10470/commits/35b268b9f94410ba4c79bd105cd0127c9d0cf5f0

2024-09-05 07:29 UTC, alexwizp commented
/test

2024-09-05 07:38 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15511)
* Commit: 35b268b9f94410ba4c79bd105cd0127c9d0cf5f0

### Failed CI Steps
* [Check integrations jamf_pro](https://buildkite.com/elastic/integrations/builds/15511#0191c11a-f7a9-4fef-985f-c30a5ec79803)

### History
* :green_heart: [Build #15308](https://buildkite.com/elastic/integrations/builds/15308) succeeded 3cbff3014cf1884f2323f76191dc49a537001bab
* :broken_heart: [Build #15288](https://buildkite.com/elastic/integrations/builds/15288) failed 675799579ec3718c6e144e87e1f7badd43ac7901
* :green_heart: [Build #15031](https://buildkite.com/elastic/integrations/builds/15031) succeeded 5558eaedee9f6125814ab5620375ae89f8a4c46a
* :green_heart: [Build #14656](https://buildkite.com/elastic/integrations/builds/14656) succeeded f6887de2d83ce3b03078ced8adbd7a429682c6d2
* :green_heart: [Build #14654](https://buildkite.com/elastic/integrations/builds/14654) succeeded c87802e0ec7cd06853a27e752d97721ed997244b
* :broken_heart: [Build #14651](https://buildkite.com/elastic/integrations/builds/14651) failed 5d1de99735f1fe0d6f8fff3262eff5ada224d97b

cc @wshaman

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15511","number":15511,"commit":"35b268b9f94410ba4c79bd105cd0127c9d0cf5f0"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15308","number":15308,"commit":"3cbff3014cf1884f2323f76191dc49a537001bab"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15288","number":15288,"commit":"675799579ec3718c6e144e87e1f7badd43ac7901"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15031","number":15031,"commit":"5558eaedee9f6125814ab5620375ae89f8a4c46a"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14656","number":14656,"commit":"f6887de2d83ce3b03078ced8adbd7a429682c6d2"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14654","number":14654,"commit":"c87802e0ec7cd06853a27e752d97721ed997244b"}],"number":15511}
buildkite-pr-comment-->

2024-09-05 11:08 UTC, wshaman commented on packages/jamf_pro/_dev/build/docs/README.md
> +#### Step 3: Create a Webhook in Jamf Pro:
Addressed here: https://github.com/elastic/integrations/pull/10470/commits/35b268b9f94410ba4c79bd105cd0127c9d0cf5f0

2024-09-05 11:08 UTC, wshaman commented on packages/jamf_pro/img/image.png
Fixed here: https://github.com/elastic/integrations/pull/10470/commits/35b268b9f94410ba4c79bd105cd0127c9d0cf5f0

2024-09-05 11:08 UTC, wshaman commented on packages/jamf_pro/_dev/build/docs/README.md
> +The connector provides integration with Jamf Pro, it is designed to enhance the management and security of Apple devices across an organization.
Addressed here :https://github.com/elastic/integrations/pull/10470/commits/35b268b9f94410ba4c79bd105cd0127c9d0cf5f0

2024-09-05 11:09 UTC, wshaman commented on packages/jamf_pro/data_stream/events/elasticsearch/ingest_pipeline/default.yml
> +    ignore_empty_value: true
Fixed here: https://github.com/elastic/integrations/pull/10470/commits/f8e10c2b21daa4ddb21a3561df90fa3a90ae1151

2024-09-05 11:10 UTC, wshaman commented on packages/jamf_pro/data_stream/events/elasticsearch/ingest_pipeline/default.yml
> +    if: ctx.message != null
Fixed here: https://github.com/elastic/integrations/pull/10470/commits/f8e10c2b21daa4ddb21a3561df90fa3a90ae1151

2024-09-05 11:46 UTC, alexwizp commented
/test

2024-09-05 11:56 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15527)
* Commit: f8e10c2b21daa4ddb21a3561df90fa3a90ae1151

### Failed CI Steps
* [Check integrations jamf_pro](https://buildkite.com/elastic/integrations/builds/15527#0191c206-55c0-45d4-be48-b7035f95382b)

### History
* :broken_heart: [Build #15511](https://buildkite.com/elastic/integrations/builds/15511) failed 35b268b9f94410ba4c79bd105cd0127c9d0cf5f0
* :green_heart: [Build #15308](https://buildkite.com/elastic/integrations/builds/15308) succeeded 3cbff3014cf1884f2323f76191dc49a537001bab
* :broken_heart: [Build #15288](https://buildkite.com/elastic/integrations/builds/15288) failed 675799579ec3718c6e144e87e1f7badd43ac7901
* :green_heart: [Build #15031](https://buildkite.com/elastic/integrations/builds/15031) succeeded 5558eaedee9f6125814ab5620375ae89f8a4c46a
* :green_heart: [Build #14656](https://buildkite.com/elastic/integrations/builds/14656) succeeded f6887de2d83ce3b03078ced8adbd7a429682c6d2

cc @wshaman

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15527","number":15527,"commit":"f8e10c2b21daa4ddb21a3561df90fa3a90ae1151"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15511","number":15511,"commit":"35b268b9f94410ba4c79bd105cd0127c9d0cf5f0"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15308","number":15308,"commit":"3cbff3014cf1884f2323f76191dc49a537001bab"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15288","number":15288,"commit":"675799579ec3718c6e144e87e1f7badd43ac7901"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15031","number":15031,"commit":"5558eaedee9f6125814ab5620375ae89f8a4c46a"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14656","number":14656,"commit":"f6887de2d83ce3b03078ced8adbd7a429682c6d2"}],"number":15527}
buildkite-pr-comment-->

2024-09-05 12:28 UTC, alexwizp commented
/test

2024-09-05 12:47 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15531)
* Commit: b96ae822fdcae3fdd11ad109b07542c3144e9c08

### History
* :broken_heart: [Build #15527](https://buildkite.com/elastic/integrations/builds/15527) failed f8e10c2b21daa4ddb21a3561df90fa3a90ae1151
* :broken_heart: [Build #15511](https://buildkite.com/elastic/integrations/builds/15511) failed 35b268b9f94410ba4c79bd105cd0127c9d0cf5f0
* :green_heart: [Build #15308](https://buildkite.com/elastic/integrations/builds/15308) succeeded 3cbff3014cf1884f2323f76191dc49a537001bab
* :broken_heart: [Build #15288](https://buildkite.com/elastic/integrations/builds/15288) failed 675799579ec3718c6e144e87e1f7badd43ac7901
* :green_heart: [Build #15031](https://buildkite.com/elastic/integrations/builds/15031) succeeded 5558eaedee9f6125814ab5620375ae89f8a4c46a

cc @wshaman

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15531","number":15531,"commit":"b96ae822fdcae3fdd11ad109b07542c3144e9c08"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15527","number":15527,"commit":"f8e10c2b21daa4ddb21a3561df90fa3a90ae1151"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15511","number":15511,"commit":"35b268b9f94410ba4c79bd105cd0127c9d0cf5f0"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15308","number":15308,"commit":"3cbff3014cf1884f2323f76191dc49a537001bab"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15288","number":15288,"commit":"675799579ec3718c6e144e87e1f7badd43ac7901"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15031","number":15031,"commit":"5558eaedee9f6125814ab5620375ae89f8a4c46a"}],"number":15531}
buildkite-pr-comment-->

2024-09-06 14:47 UTC, alexwizp commented
/test

2024-09-06 14:57 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15597)
* Commit: c76e570c1f25d2f370be607a168e8a175b8c8e1e

### Failed CI Steps
* [Check integrations jamf_pro](https://buildkite.com/elastic/integrations/builds/15597#0191c7d2-fcae-4c1b-a5c6-97a17d800cfa)

### History
* :green_heart: [Build #15531](https://buildkite.com/elastic/integrations/builds/15531) succeeded b96ae822fdcae3fdd11ad109b07542c3144e9c08
* :broken_heart: [Build #15527](https://buildkite.com/elastic/integrations/builds/15527) failed f8e10c2b21daa4ddb21a3561df90fa3a90ae1151
* :broken_heart: [Build #15511](https://buildkite.com/elastic/integrations/builds/15511) failed 35b268b9f94410ba4c79bd105cd0127c9d0cf5f0
* :green_heart: [Build #15308](https://buildkite.com/elastic/integrations/builds/15308) succeeded 3cbff3014cf1884f2323f76191dc49a537001bab
* :broken_heart: [Build #15288](https://buildkite.com/elastic/integrations/builds/15288) failed 675799579ec3718c6e144e87e1f7badd43ac7901
* :green_heart: [Build #15031](https://buildkite.com/elastic/integrations/builds/15031) succeeded 5558eaedee9f6125814ab5620375ae89f8a4c46a

cc @wshaman

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15597","number":15597,"commit":"c76e570c1f25d2f370be607a168e8a175b8c8e1e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15531","number":15531,"commit":"b96ae822fdcae3fdd11ad109b07542c3144e9c08"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15527","number":15527,"commit":"f8e10c2b21daa4ddb21a3561df90fa3a90ae1151"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15511","number":15511,"commit":"35b268b9f94410ba4c79bd105cd0127c9d0cf5f0"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15308","number":15308,"commit":"3cbff3014cf1884f2323f76191dc49a537001bab"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15288","number":15288,"commit":"675799579ec3718c6e144e87e1f7badd43ac7901"}],"number":15597}
buildkite-pr-comment-->

2024-09-06 16:08 UTC, alexwizp commented
/test

2024-09-06 16:19 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15602)
* Commit: 4738058ec3b4fbe47adbaf134188a19fa78f2543

### Failed CI Steps
* [Check integrations jamf_pro](https://buildkite.com/elastic/integrations/builds/15602#0191c81d-db66-46ef-be03-620c556974a6)

### History
* :broken_heart: [Build #15597](https://buildkite.com/elastic/integrations/builds/15597) failed c76e570c1f25d2f370be607a168e8a175b8c8e1e
* :green_heart: [Build #15531](https://buildkite.com/elastic/integrations/builds/15531) succeeded b96ae822fdcae3fdd11ad109b07542c3144e9c08
* :broken_heart: [Build #15527](https://buildkite.com/elastic/integrations/builds/15527) failed f8e10c2b21daa4ddb21a3561df90fa3a90ae1151
* :broken_heart: [Build #15511](https://buildkite.com/elastic/integrations/builds/15511) failed 35b268b9f94410ba4c79bd105cd0127c9d0cf5f0
* :green_heart: [Build #15308](https://buildkite.com/elastic/integrations/builds/15308) succeeded 3cbff3014cf1884f2323f76191dc49a537001bab

cc @wshaman

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15602","number":15602,"commit":"4738058ec3b4fbe47adbaf134188a19fa78f2543"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15597","number":15597,"commit":"c76e570c1f25d2f370be607a168e8a175b8c8e1e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15531","number":15531,"commit":"b96ae822fdcae3fdd11ad109b07542c3144e9c08"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15527","number":15527,"commit":"f8e10c2b21daa4ddb21a3561df90fa3a90ae1151"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15511","number":15511,"commit":"35b268b9f94410ba4c79bd105cd0127c9d0cf5f0"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15308","number":15308,"commit":"3cbff3014cf1884f2323f76191dc49a537001bab"}],"number":15602}
buildkite-pr-comment-->

2024-09-06 17:18 UTC, alexwizp commented
/test

2024-09-06 20:06 UTC, alexwizp commented
/test

2024-09-06 20:30 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15609)
* Commit: d8de06a3577882edba74dbbcc05f4cef37bf2787

### History
* :broken_heart: [Build #15604](https://buildkite.com/elastic/integrations/builds/15604) failed 4210ebcb14897178446177bdd8600e3ab379d038
* :broken_heart: [Build #15602](https://buildkite.com/elastic/integrations/builds/15602) failed 4738058ec3b4fbe47adbaf134188a19fa78f2543
* :broken_heart: [Build #15597](https://buildkite.com/elastic/integrations/builds/15597) failed c76e570c1f25d2f370be607a168e8a175b8c8e1e
* :green_heart: [Build #15531](https://buildkite.com/elastic/integrations/builds/15531) succeeded b96ae822fdcae3fdd11ad109b07542c3144e9c08
* :broken_heart: [Build #15527](https://buildkite.com/elastic/integrations/builds/15527) failed f8e10c2b21daa4ddb21a3561df90fa3a90ae1151

cc @wshaman

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15609","number":15609,"commit":"d8de06a3577882edba74dbbcc05f4cef37bf2787"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15604","number":15604,"commit":"4210ebcb14897178446177bdd8600e3ab379d038"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15602","number":15602,"commit":"4738058ec3b4fbe47adbaf134188a19fa78f2543"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15597","number":15597,"commit":"c76e570c1f25d2f370be607a168e8a175b8c8e1e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15531","number":15531,"commit":"b96ae822fdcae3fdd11ad109b07542c3144e9c08"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15527","number":15527,"commit":"f8e10c2b21daa4ddb21a3561df90fa3a90ae1151"}],"number":15609}
buildkite-pr-comment-->

2024-09-09 22:16 UTC, joedatlive commented
Thanks looks good to Entity Analytics from a Product perspective.  We are always trying to get data on privileged users, e.g. local admin/root privileges, but we (Jared and I) didn't see that available from JAMF...

2024-09-10 15:01 UTC, chrisberkhout commented
@joedatlive Good to know. The [Entity Analytics input](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-entity-analytics.html#provider-jamf) currently uses the [`/api/preview/computers`](https://developer.jamf.com/jamf-pro/reference/get_preview-computers) endpoint. This this package is using the [`/api/v1/computers-inventory`](https://developer.jamf.com/jamf-pro/reference/get_v1-computers-inventory) endpoint, so there is quite a bit more information available.

2024-09-10 15:02 UTC, chrisberkhout approved these changes
Looks great! Good responses to all the feedback from earlier reviews.

2024-09-10 15:08 UTC, merged