[HAProxy] updating haproxy ECS version and adding event.original options
elastic/integrations pull request #1048
Opened 2021-06-01 12:05 UTC by P1llus

## What does this PR do?

Updates package ECS version to 1.10.
Sync module changes to packages if any.
Adds Preserve Raw event functionality if not already exists.
Adds pipeline tests if missing.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] If I'm introducing a new feature, I have modified the Kibana version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^7.13.0`).

## Related issues

- Relates #994

2021-06-01 12:13 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1048/detail/PR-1048/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1048/detail/PR-1048/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1048/detail/PR-1048/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1048/detail/PR-1048/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_1048.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #1048 opened`



* Start Time: 2021-06-01T12:05:53.821+0000


* Duration: 8 min 54 sec


* Commit: cb7bfea0f18d821bde7041dbe649271da316db50




#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/PR-1048/buildTimeGraph/png)



</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->









### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1048/detail/PR-1048/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Check integration: haproxy`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-1048/runs/1/steps/394/log/?start=0">here</a></li>
<li>Description: <code>../../build/elastic-package check -v</code></l1>
</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-06-01T12:13:06.968Z] go: downloading github.com/Masterminds/semver/v3 v3.1.1
[2021-06-01T12:13:06.968Z] go: downloading github.com/peterbourgon/diskv v2.0.1+incompatible
[2021-06-01T12:13:06.968Z] go: downloading github.com/xanzy/ssh-agent v0.2.1
[2021-06-01T12:13:07.232Z] go: downloading github.com/modern-go/reflect2 v1.0.1
[2021-06-01T12:13:07.232Z] go: downloading github.com/asaskevich/govalidator v0.0.0-20200428143746-21a406dcc535
[2021-06-01T12:13:07.232Z] go: downloading github.com/go-logr/logr v0.2.0
[2021-06-01T12:13:07.232Z] go: downloading github.com/xeipuuv/gojsonschema v1.2.0
[2021-06-01T12:13:07.232Z] go: downloading k8s.io/kube-openapi v0.0.0-20201113171705-d219536bb9fd
[2021-06-01T12:13:07.232Z] go: downloading github.com/rakyll/statik v0.1.7
[2021-06-01T12:13:07.232Z] go: downloading gopkg.in/inf.v0 v0.9.1
[2021-06-01T12:13:07.232Z] go: downloading github.com/json-iterator/go v1.1.10
[2021-06-01T12:13:07.232Z] go: downloading golang.org/x/time v0.0.0-20200630173020-3af7569d3a1e
[2021-06-01T12:13:07.232Z] go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
[2021-06-01T12:13:07.232Z] go: downloading github.com/xeipuuv/gojsonreference v0.0.0-20180127040603-bd5ef7bd5415
[2021-06-01T12:13:07.232Z] go: downloading github.com/golang/protobuf v1.4.3
[2021-06-01T12:13:07.232Z] go: downloading github.com/google/btree v1.0.0
[2021-06-01T12:13:07.232Z] go: downloading k8s.io/utils v0.0.0-20201110183641-67b214c5f920
[2021-06-01T12:13:07.232Z] go: downloading github.com/xeipuuv/gojsonpointer v0.0.0-20190905194746-02993c407bfb
[2021-06-01T12:13:07.232Z] go: downloading github.com/go-openapi/spec v0.19.3
[2021-06-01T12:13:07.232Z] go: downloading github.com/google/go-cmp v0.5.2
[2021-06-01T12:13:07.232Z] go: downloading github.com/googleapis/gnostic v0.4.1
[2021-06-01T12:13:07.232Z] go: downloading k8s.io/apiextensions-apiserver v0.20.1
[2021-06-01T12:13:07.495Z] go: downloading github.com/hashicorp/golang-lru v0.5.1
[2021-06-01T12:13:07.495Z] go: downloading github.com/go-openapi/jsonreference v0.19.3
[2021-06-01T12:13:07.495Z] go: downloading github.com/PuerkitoBio/purell v1.1.1
[2021-06-01T12:13:07.495Z] go: downloading github.com/emicklei/go-restful v2.9.5+incompatible
[2021-06-01T12:13:07.495Z] go: downloading github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578
[2021-06-01T12:13:07.495Z] go: downloading google.golang.org/protobuf v1.25.0
[2021-06-01T12:13:07.495Z] go: downloading github.com/google/gofuzz v1.1.0
[2021-06-01T12:13:07.495Z] go: downloading github.com/go-openapi/jsonpointer v0.19.3
[2021-06-01T12:13:07.495Z] go: downloading github.com/davecgh/go-spew v1.1.1
[2021-06-01T12:13:07.495Z] go: downloading github.com/go-stack/stack v1.8.0
[2021-06-01T12:13:07.495Z] go: downloading github.com/liggitt/tabwriter v0.0.0-20181228230101-89fcab3d43de
[2021-06-01T12:13:07.495Z] go: downloading github.com/joeshaw/multierror v0.0.0-20140124173710-69b34d4ec901
[2021-06-01T12:13:07.495Z] go: downloading github.com/MakeNowJust/heredoc v0.0.0-20170808103936-bb23615498cd
[2021-06-01T12:13:07.495Z] go: downloading k8s.io/component-base v0.20.1
[2021-06-01T12:13:07.756Z] go: downloading github.com/go-openapi/swag v0.19.5
[2021-06-01T12:13:07.756Z] go: downloading github.com/mailru/easyjson v0.7.0
[2021-06-01T12:13:07.756Z] go: downloading github.com/PaesslerAG/jsonpath v0.1.1
[2021-06-01T12:13:07.756Z] go: downloading github.com/mitchellh/go-wordwrap v1.0.0
[2021-06-01T12:13:07.756Z] go: downloading github.com/moby/term v0.0.0-20200312100748-672ec06f55cd
[2021-06-01T12:13:07.756Z] go: downloading github.com/exponent-io/jsonpath v0.0.0-20151013193312-d6023ce2651d
[2021-06-01T12:13:07.756Z] go: downloading github.com/russross/blackfriday v1.5.2
[2021-06-01T12:13:07.756Z] go: downloading github.com/docker/spdystream v0.0.0-20160310174837-449fdfce4d96
[2021-06-01T12:13:07.756Z] go: downloading github.com/PaesslerAG/gval v1.0.0
[2021-06-01T12:13:40.026Z] Running in /var/lib/jenkins/workspace/est-manager_integrations_PR-1048/src/github.com/elastic/integrations/packages/haproxy
[2021-06-01T12:13:40.362Z] + ../../build/elastic-package check -v
[2021-06-01T12:13:40.362Z] elastic-package has been installed.
[2021-06-01T12:13:40.362Z] 2021/06/01 12:13:40 DEBUG Enable verbose logging
[2021-06-01T12:13:40.362Z] Format the package
[2021-06-01T12:13:40.362Z] Error: checking package failed: formatting the integration failed (path: /var/lib/jenkins/workspace/est-manager_integrations_PR-1048/src/github.com/elastic/integrations/packages/haproxy, failFast: true): walking through the integration files failed: formatting file failed (path: /var/lib/jenkins/workspace/est-manager_integrations_PR-1048/src/github.com/elastic/integrations/packages/haproxy/data_stream/log/_dev/test/pipeline/test-common-config.yml): file is not formatted (path: /var/lib/jenkins/workspace/est-manager_integrations_PR-1048/src/github.com/elastic/integrations/packages/haproxy/data_stream/log/_dev/test/pipeline/test-common-config.yml)
[2021-06-01T12:13:40.447Z] Running in /var/lib/jenkins/workspace/est-manager_integrations_PR-1048/src/github.com/elastic/integrations
[2021-06-01T12:13:40.489Z] Archiving artifacts
[2021-06-01T12:13:40.892Z] ‘build/test-results/*.xml’ doesn’t match anything: ‘build’ exists but not ‘build/test-results/*.xml’
[2021-06-01T12:13:40.892Z] No artifacts found that match the file pattern "build/test-results/*.xml". Configuration error?
[2021-06-01T12:13:40.914Z] Recording test results
[2021-06-01T12:13:41.261Z] None of the test reports contained any result
[2021-06-01T12:13:41.261Z] [Checks API] No suitable checks publisher found.
[2021-06-01T12:13:41.574Z] + build/elastic-packa [...]

2021-06-07 11:17 UTC, elasticmachine commented
Pinging @elastic/integrations (Team:Integrations)

2021-06-07 12:58 UTC, andrewkroh approved these changes

2021-06-07 12:58 UTC, andrewkroh commented on packages/haproxy/_dev/deploy/docker/docker-compose.yml
> +    image: akroh/stream:v0.0.1
Use `docker.elastic.co/observability/stream:v0.4.0`.

https://container-library.elastic.co/r/observability/stream:v0.4.0

2021-06-09 13:53 UTC, mtojek requested changes
CI raised an issue around Docker Compose version.

2021-06-16 11:30 UTC, mtojek approved these changes
Please merge it only if CI passes.

2021-06-16 11:45 UTC, merged