[MongoDB Atlas] Disk data stream
elastic/integrations pull request #10555
Opened 2024-07-23 07:14 UTC by niraj-elastic

- Enhancement

## What does this PR do?

- Added 1 data stream (Disk Metrics).
- Added data collection logic for the data streams.
- Added the ingest pipeline for the data streams.
- Mapped fields according to the ECS schema and added Fields metadata in the appropriate yaml files.
- Added dashboards and visualizations.
- Added system test cases for the data stream.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally

- Clone integrations repo.
- Install elastic-package locally.
- Start elastic stack using elastic-package.
- Move to integrations/packages/mongodb_atlas) directory.
- Run the following command to run tests. elastic-package test

## Screenshots
![mongodb_atlas-disk-dashboard](https://github.com/user-attachments/assets/c8f6a6e9-4760-451c-9704-32f6f607a1b7)

## Related issue
- [[MongoDB Atlas metrics] Disk Datastream](https://github.com/elastic/obs-infraobs-team/issues/1361)

2024-07-23 07:26 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13859)
* Commit: b8f0e40467c966df71f854a57996781a10350190

### Failed CI Steps
* [Check integrations mongodb_atlas](https://buildkite.com/elastic/integrations/builds/13859#0190de77-8763-411b-9709-81447e91a9e0)

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13859","number":13859,"commit":"b8f0e40467c966df71f854a57996781a10350190"}],"number":13859}
buildkite-pr-comment-->

2024-07-23 09:31 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-07-23 09:32 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13865)
* Commit: 8b5220fc082c7238e3482ebbba4aab4e0f96bfad

### History
* :broken_heart: [Build #13859](https://buildkite.com/elastic/integrations/builds/13859) failed b8f0e40467c966df71f854a57996781a10350190

cc @niraj-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13865","number":13865,"commit":"8b5220fc082c7238e3482ebbba4aab4e0f96bfad"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13859","number":13859,"commit":"b8f0e40467c966df71f854a57996781a10350190"}],"number":13865}
buildkite-pr-comment-->

2024-07-24 06:37 UTC, harnish-elastic approved these changes
LGTM 🚀

2024-07-24 06:37 UTC, harnish-elastic commented on packages/mongodb_atlas/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/1 #Fix ME
Please update the PR link

2024-07-24 07:52 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13905)
* Commit: 1bf47713e6c9e8418538356ba4033e385795c130

### History
* :green_heart: [Build #13865](https://buildkite.com/elastic/integrations/builds/13865) succeeded 8b5220fc082c7238e3482ebbba4aab4e0f96bfad
* :broken_heart: [Build #13859](https://buildkite.com/elastic/integrations/builds/13859) failed b8f0e40467c966df71f854a57996781a10350190

cc @niraj-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13905","number":13905,"commit":"1bf47713e6c9e8418538356ba4033e385795c130"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13865","number":13865,"commit":"8b5220fc082c7238e3482ebbba4aab4e0f96bfad"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13859","number":13859,"commit":"b8f0e40467c966df71f854a57996781a10350190"}],"number":13905}
buildkite-pr-comment-->

2024-07-24 22:59 UTC, efd6 reviewed
CEL program looks OK. Suggestions are for increased robustness.

2024-07-24 22:59 UTC, efd6 commented on packages/mongodb_atlas/data_stream/disk/agent/stream/input.yml.hbs
> +            state.with(request("GET", state.url + "/api/atlas/v2/groups/" + state.group_id + "/processes?pageNum=" + string(state.page_num) + "&itemsPerPage=100").with({
```suggestion
            state.with(request("GET", state.url.trim_right("/") + "/api/atlas/v2/groups/" + state.group_id + "/processes?pageNum=" + string(state.page_num) + "&itemsPerPage=100").with({
```

2024-07-24 22:59 UTC, efd6 commented on packages/mongodb_atlas/data_stream/disk/agent/stream/input.yml.hbs
> +                "host_list": body.results.map(e, state.url + "/api/atlas/v2/groups/" + state.group_id + "/processes/" + e.id + "/disks/"),
```suggestion
                "host_list": body.results.map(e, state.url.trim_right("/") + "/api/atlas/v2/groups/" + state.group_id + "/processes/" + e.id + "/disks/"),
```

2024-07-24 22:59 UTC, efd6 commented on packages/mongodb_atlas/data_stream/disk/agent/stream/input.yml.hbs
> +            }).do_request().as(resp,
```suggestion
            }).do_request().as(resp, resp.StatusCode == 200 ?
```
with this for the false branch
```
{
  "events": {
    "error": {
      "code": string(resp.StatusCode),
      "id": string(resp.Status),
      "message": "GET:" + (
        size(resp.Body) != 0 ?
          string(resp.Body)
        :
          string(resp.Status) + " (" + string(resp.StatusCode) + ")"
      ),
    },
  },
  "want_more": false,
}
```
Similar for the other requests.

2024-07-24 22:59 UTC, efd6 commented on packages/mongodb_atlas/data_stream/disk/elasticsearch/ingest_pipeline/default.yml
Add a processor to asses the error state from the CEL program. We use something like this
```
  - fail:
      if: ctx.error?.message != null && ctx.message == null && ctx.event?.original == null
      message: error message set and no data to process
```

2024-07-25 10:50 UTC, shmsr commented
Review:

1. Remove trailing spaces
2. Grouping of ops in the ingest pipeline
3. Improved description for the fields

```diff
diff --git a/packages/mongodb_atlas/data_stream/disk/agent/stream/input.yml.hbs b/packages/mongodb_atlas/data_stream/disk/agent/stream/input.yml.hbs
index be868f1b1..1a37b8579 100644
--- a/packages/mongodb_atlas/data_stream/disk/agent/stream/input.yml.hbs
+++ b/packages/mongodb_atlas/data_stream/disk/agent/stream/input.yml.hbs
@@ -41,12 +41,12 @@ program: |
         has(state.host_list) && size(state.host_list) > 0
           ?
             state
-          : 
+          :
             state.with(request("GET", state.url + "/api/atlas/v2/groups/" + state.group_id + "/processes?pageNum=" + string(state.page_num) + "&itemsPerPage=100").with({
               "Header": {
                 "Accept": ["application/vnd.atlas." + string(timestamp(now).getFullYear()) + "-01-01+json"]
               }
-            }).do_request().as(resp, 
+            }).do_request().as(resp,
               bytes(resp.Body).decode_json().as(body, {
                 "host_list": body.results.map(e, state.url + "/api/atlas/v2/groups/" + state.group_id + "/processes/" + e.id + "/disks/"),
                 "next": 0,
@@ -54,16 +54,16 @@ program: |
               })))
       ).as(state, state.next >= size(state.host_list) ? {} :
         (
-          has(state.disk_list) && size(state.disk_list) > 0 
+          has(state.disk_list) && size(state.disk_list) > 0
             ?
               state
-            : 
+            :
               state.with(request("GET", string(state.host_list[state.next] + "?pageNum=" + string(state.disk_page_num) + "&itemsPerPage=100" ))
               .with({
                 "Header": {
                   "Accept": ["application/vnd.atlas." + string(timestamp(now).getFullYear()) + "-01-01+json"]
                 }
-              }).do_request().as(resp, 
+              }).do_request().as(resp,
                 bytes(resp.Body).decode_json().as(body, {
                   "disk_list": body.results.map(e, e.partitionName),
                   "disk_next": 0,
diff --git a/packages/mongodb_atlas/data_stream/disk/elasticsearch/ingest_pipeline/default.yml b/packages/mongodb_atlas/data_stream/disk/elasticsearch/ingest_pipeline/default.yml
index b7c04ff46..b8e11c28b 100644
--- a/packages/mongodb_atlas/data_stream/disk/elasticsearch/ingest_pipeline/default.yml
+++ b/packages/mongodb_atlas/data_stream/disk/elasticsearch/ingest_pipeline/default.yml
@@ -20,6 +20,18 @@ processors:
       field: groupId
       target_field: group.id
       ignore_missing: true
+  - rename:
+      field: processId
+      target_field: mongodb_atlas.process_id
+      ignore_missing: true
+  - rename:
+      field: partitionName
+      target_field: mongodb_atlas.partition_name
+      ignore_missing: true
+  - rename:
+      field: hostId
+      target_field: mongodb_atlas.host_id
+      ignore_missing: true
   - rename:
       field: response.MAX_DISK_PARTITION_IOPS_READ
       target_field: mongodb_atlas.disk.read.iops.max.throughput
@@ -36,6 +48,22 @@ processors:
       field: response.DISK_PARTITION_LATENCY_READ
       target_field: mongodb_atlas.disk.read.latency.ms
       ignore_missing: true
+  - rename:
+      field: response.MAX_DISK_PARTITION_IOPS_WRITE
+      target_field: mongodb_atlas.disk.write.iops.max.throughput
+      ignore_missing: true
+  - rename:
+      field: response.DISK_PARTITION_IOPS_WRITE
+      target_field: mongodb_atlas.disk.write.iops.throughput
+      ignore_missing: true
+  - rename:
+      field: response.MAX_DISK_PARTITION_LATENCY_WRITE
+      target_field: mongodb_atlas.disk.write.latency.max.ms
+      ignore_missing: true
+  - rename:
+      field: response.DISK_PARTITION_LATENCY_WRITE
+      target_field: mongodb_atlas.disk.write.latency.ms
+      ignore_missing: true
   - rename:
       field: response.DISK_PARTITION_SPACE_FREE
       target_field: mongodb_atlas.disk.space.free.bytes
@@ -76,34 +104,6 @@ processors:
       field: response.DISK_PARTITION_IOPS_TOTAL
       target_field: mongodb_atlas.disk.total.iops.throughput
       ignore_missing: true
-  - rename:
-      field: response.MAX_DISK_PARTITION_IOPS_WRITE
-      target_field: mongodb_atlas.disk.write.iops.max.throughput
-      ignore_missing: true
-  - rename:
-      field: response.DISK_PARTITION_IOPS_WRITE
-      target_field: mongodb_atlas.disk.write.iops.throughput
-      ignore_missing: true
-  - rename:
-      field: response.MAX_DISK_PARTITION_LATENCY_WRITE
-      target_field: mongodb_atlas.disk.write.latency.max.ms
-      ignore_missing: true
-  - rename:
-      field: response.DISK_PARTITION_LATENCY_WRITE
-      target_field: mongodb_atlas.disk.write.latency.ms
-      ignore_missing: true
-  - rename:
-      field: processId
-      target_field: mongodb_atlas.process_id
-      ignore_missing: true
-  - rename:
-      field: partitionName
-      target_field: mongodb_atlas.partition_name
-      ignore_missing: true
-  - rename:
-      field: hostId
-      target_field: mongodb_atlas.host_id
-      ignore_missing: true
   - remove:
       field:
         - response
@@ -140,4 +140,3 @@ on_failure:
       field: event.kind
       value: pipeline_error
       allow_duplicates: false
-      
\ No newline at end of file
diff --git a/packages/mongodb_atlas/data_stream/disk/fields/fields.yml b/packages/mongodb_atlas/data_stream/disk/fields/fields.yml
index 1d86a9ef3..55ebc92a2 100644
--- a/packages/mongodb_atlas/data_stream/disk/fields/fields.yml
+++ b/packages/mongodb_atlas/data_stream/disk/fields/fields.yml
@@ -13,11 +13,11 @@
                 - name: max.throughput
                   type: double
                   metric_type: gauge
-                  description: Max throughput of I/O read operations for the disk partition used for MongoDB Atlas.
+                  description: Maximum throughput of I/O read operations for the disk partition used by MongoDB Atlas.
                 - name: throughput
                   type: double
                   metric_type: gauge
-                  description: Throughput of I/O read operations for the disk partition used for MongoDB Atlas.
+                  description: Current throughput of I/O read operations for the disk partition used by MongoDB Atlas.
             - name: latency
               type: group
               fields:
@@ -25,12 +25,12 @@
                   type: double
                   metric_type: gauge
                   unit: ms
-                  description: Max read latency of the disk partition that hosts MongoDB Atlas.
+                  description: Maximum read latency in milliseconds for the disk partition used by MongoDB Atlas.
                 - name: ms
                   type: double
                   metric_type: gauge
                   unit: ms
-                  description: Read latency of the disk partition that hosts MongoDB Atlas.
+                  description: Current read latency in milliseconds for the disk partition used by MongoDB Atlas.
         - name: space
           type: group
           fields:
@@ -41,7 +41,7 @@
                   type: double
                   metric_type: gauge
                   unit: byte
-                  description: Amount of disk space free in Bytes, on the disk partition used by MongoDB Atlas.
+                  description: Current amount of free disk space in bytes on the disk partition used by MongoDB Atlas.
                 - name: max
                   type: group
                   fields:
@@ -49,17 +49,17 @@
                       type: double
                       metric_type: gauge
                       unit: byte
-                      description: Max amount of disk space free in Bytes, on the disk partition used by MongoDB Atlas.
+                      description: Maximum amount of free disk space in bytes on the disk partition used by MongoDB Atlas.
                     - name: pct
                       type: doubl [...]

2024-07-25 10:57 UTC, shmsr requested changes

2024-07-25 10:57 UTC, shmsr commented on packages/mongodb_atlas/_dev/build/docs/README.md
> +- `disk`: This data stream collects metrics of disk or partition for all the hosts in the specified group. Metrics like measurements for the disk, such as I/O operations, read and write latency, and
```suggestion
- `disk`: This data stream collects disk or partition metrics for all the hosts in the specified group. Metrics like measurements for the disk, such as I/O operations, read and write latency, and space usage.
```

2024-07-25 10:57 UTC, shmsr commented on packages/mongodb_atlas/_dev/build/docs/README.md
> +This is the `disk` data stream. This data stream collects detailed view on disk usage and captures crucial information about I/O operations, read and write latency, and space utilization. To collect
```suggestion
This is the `disk` data stream. This data stream collects a detailed overview of disk usage and captures important data about I/O operations, read and write latency, and space utilization. To collect disk metrics, the API Key making the request must have the `Project Read Only` role.
```

2024-07-25 10:57 UTC, shmsr commented on packages/mongodb_atlas/changelog.yml
> +    - description: MongoDB Atlas integration package with "disk" data stream.
I didn't notice this changelog description until now. It's acceptable since it follows the same convention as the older changelog. However, this changelog could have been better, as the message is not clear.

2024-07-29 06:44 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14082)
* Commit: 62a44c85c1e20f96b9e7563e071d5196afb440b5

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/14082#0190fd3a-f97d-404f-b2d5-6afcf7e79c70)

### History
* :green_heart: [Build #13905](https://buildkite.com/elastic/integrations/builds/13905) succeeded 1bf47713e6c9e8418538356ba4033e385795c130
* :green_heart: [Build #13865](https://buildkite.com/elastic/integrations/builds/13865) succeeded 8b5220fc082c7238e3482ebbba4aab4e0f96bfad
* :broken_heart: [Build #13859](https://buildkite.com/elastic/integrations/builds/13859) failed b8f0e40467c966df71f854a57996781a10350190

cc @niraj-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14082","number":14082,"commit":"62a44c85c1e20f96b9e7563e071d5196afb440b5"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13905","number":13905,"commit":"1bf47713e6c9e8418538356ba4033e385795c130"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13865","number":13865,"commit":"8b5220fc082c7238e3482ebbba4aab4e0f96bfad"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13859","number":13859,"commit":"b8f0e40467c966df71f854a57996781a10350190"}],"number":14082}
buildkite-pr-comment-->

2024-07-29 07:14 UTC, niraj-elastic commented on packages/mongodb_atlas/data_stream/disk/agent/stream/input.yml.hbs
> +            }).do_request().as(resp,
I added this error handling, but even if we get unsuccessful result the program execution continues. so can we somehow terminate the execution after setting `want_more` to false ?

2024-10-15 12:18 UTC, niraj-elastic commented on packages/mongodb_atlas/changelog.yml
> +    - description: MongoDB Atlas integration package with "disk" data stream.
Agree, But for the sake of continuity, I am keeping it as it is for now.

2024-10-15 12:42 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17144)
* Commit: 1873ead3cb9cb5680330f6561c2bd5b122ca4af5

### History
* :green_heart: [Build #16757](https://buildkite.com/elastic/integrations/builds/16757) succeeded b32c558f03d52279ea34f93933ce6de12b357073
* :broken_heart: [Build #14082](https://buildkite.com/elastic/integrations/builds/14082) failed 62a44c85c1e20f96b9e7563e071d5196afb440b5
* :green_heart: [Build #13905](https://buildkite.com/elastic/integrations/builds/13905) succeeded 1bf47713e6c9e8418538356ba4033e385795c130
* :green_heart: [Build #13865](https://buildkite.com/elastic/integrations/builds/13865) succeeded 8b5220fc082c7238e3482ebbba4aab4e0f96bfad
* :broken_heart: [Build #13859](https://buildkite.com/elastic/integrations/builds/13859) failed b8f0e40467c966df71f854a57996781a10350190

cc @niraj-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17144","number":17144,"commit":"1873ead3cb9cb5680330f6561c2bd5b122ca4af5"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16757","number":16757,"commit":"b32c558f03d52279ea34f93933ce6de12b357073"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14082","number":14082,"commit":"62a44c85c1e20f96b9e7563e071d5196afb440b5"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13905","number":13905,"commit":"1bf47713e6c9e8418538356ba4033e385795c130"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13865","number":13865,"commit":"8b5220fc082c7238e3482ebbba4aab4e0f96bfad"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13859","number":13859,"commit":"b8f0e40467c966df71f854a57996781a10350190"}],"number":17144}
buildkite-pr-comment-->

2024-10-17 20:29 UTC, efd6 reviewed
CEL code LGTM (reviewed lightly). Could do with an indentation fix-up.

2024-10-28 06:40 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17603)
* Commit: 40127aaf5a9a5e66455f2f8a7dac8339577f281b

### History
* :green_heart: [Build #17144](https://buildkite.com/elastic/integrations/builds/17144) succeeded 1873ead3cb9cb5680330f6561c2bd5b122ca4af5
* :green_heart: [Build #16757](https://buildkite.com/elastic/integrations/builds/16757) succeeded b32c558f03d52279ea34f93933ce6de12b357073
* :broken_heart: [Build #14082](https://buildkite.com/elastic/integrations/builds/14082) failed 62a44c85c1e20f96b9e7563e071d5196afb440b5
* :green_heart: [Build #13905](https://buildkite.com/elastic/integrations/builds/13905) succeeded 1bf47713e6c9e8418538356ba4033e385795c130
* :green_heart: [Build #13865](https://buildkite.com/elastic/integrations/builds/13865) succeeded 8b5220fc082c7238e3482ebbba4aab4e0f96bfad
* :broken_heart: [Build #13859](https://buildkite.com/elastic/integrations/builds/13859) failed b8f0e40467c966df71f854a57996781a10350190

cc @niraj-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17603","number":17603,"commit":"40127aaf5a9a5e66455f2f8a7dac8339577f281b"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17144","number":17144,"commit":"1873ead3cb9cb5680330f6561c2bd5b122ca4af5"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16757","number":16757,"commit":"b32c558f03d52279ea34f93933ce6de12b357073"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14082","number":14082,"commit":"62a44c85c1e20f96b9e7563e071d5196afb440b5"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13905","number":13905,"commit":"1bf47713e6c9e8418538356ba4033e385795c130"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13865","number":13865,"commit":"8b5220fc082c7238e3482ebbba4aab4e0f96bfad"}],"number":17603}
buildkite-pr-comment-->

2024-10-29 09:05 UTC, shmsr approved these changes

2024-10-30 06:10 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17710)
* Commit: 0bfc164072c6fd4fe67561e137a9bf62940a17f3

### History
* :green_heart: [Build #17603](https://buildkite.com/elastic/integrations/builds/17603) succeeded 40127aaf5a9a5e66455f2f8a7dac8339577f281b
* :green_heart: [Build #17144](https://buildkite.com/elastic/integrations/builds/17144) succeeded 1873ead3cb9cb5680330f6561c2bd5b122ca4af5
* :green_heart: [Build #16757](https://buildkite.com/elastic/integrations/builds/16757) succeeded b32c558f03d52279ea34f93933ce6de12b357073
* :broken_heart: [Build #14082](https://buildkite.com/elastic/integrations/builds/14082) failed 62a44c85c1e20f96b9e7563e071d5196afb440b5
* :green_heart: [Build #13905](https://buildkite.com/elastic/integrations/builds/13905) succeeded 1bf47713e6c9e8418538356ba4033e385795c130
* :green_heart: [Build #13865](https://buildkite.com/elastic/integrations/builds/13865) succeeded 8b5220fc082c7238e3482ebbba4aab4e0f96bfad

cc @niraj-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17710","number":17710,"commit":"0bfc164072c6fd4fe67561e137a9bf62940a17f3"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17603","number":17603,"commit":"40127aaf5a9a5e66455f2f8a7dac8339577f281b"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17144","number":17144,"commit":"1873ead3cb9cb5680330f6561c2bd5b122ca4af5"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16757","number":16757,"commit":"b32c558f03d52279ea34f93933ce6de12b357073"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14082","number":14082,"commit":"62a44c85c1e20f96b9e7563e071d5196afb440b5"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13905","number":13905,"commit":"1bf47713e6c9e8418538356ba4033e385795c130"}],"number":17710}
buildkite-pr-comment-->

2024-10-30 06:15 UTC, merged