Feature/216 synthetics browser
elastic/integrations pull request #1064
Opened 2021-06-01 20:56 UTC by dominiqueclarke

Type of change
- Enhancement

## What does this PR do?
This PR adds the `browser`, `browser_screenshot`, and `browser_network` data streams to the synthetics package.

This PR is a draft state =.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect -metrics or logs- synthetics.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] If I'm introducing a new feature, I have modified the Kibana version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^7.13.0`).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2021-06-01 21:09 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1064/detail/PR-1064/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1064/detail/PR-1064/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1064/detail/PR-1064/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1064/detail/PR-1064/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_1064.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #1064 opened`



* Start Time: 2021-06-01T21:00:55.315+0000


* Duration: 8 min 56 sec


* Commit: 3c254ef60e29d51ae89ba00b7e88ab8c9e8b50d0




#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/PR-1064/buildTimeGraph/png)



</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->









### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1064/detail/PR-1064/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Check integration: synthetics`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-1064/runs/1/steps/394/log/?start=0">here</a></li>
<li>Description: <code>../../build/elastic-package check -v</code></l1>
</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-06-01T21:08:09.422Z] go: downloading gopkg.in/inf.v0 v0.9.1
[2021-06-01T21:08:09.688Z] go: downloading k8s.io/apiextensions-apiserver v0.20.1
[2021-06-01T21:08:09.953Z] go: downloading k8s.io/utils v0.0.0-20201110183641-67b214c5f920
[2021-06-01T21:08:09.953Z] go: downloading github.com/xanzy/ssh-agent v0.2.1
[2021-06-01T21:08:09.953Z] go: downloading sigs.k8s.io/kustomize v2.0.3+incompatible
[2021-06-01T21:08:09.953Z] go: downloading github.com/kevinburke/ssh_config v0.0.0-20190725054713-01f96b0aa0cd
[2021-06-01T21:08:09.953Z] go: downloading github.com/json-iterator/go v1.1.10
[2021-06-01T21:08:09.953Z] go: downloading github.com/davecgh/go-spew v1.1.1
[2021-06-01T21:08:10.218Z] go: downloading k8s.io/kubectl v0.20.1
[2021-06-01T21:08:10.218Z] go: downloading sigs.k8s.io/yaml v1.2.0
[2021-06-01T21:08:10.218Z] go: downloading github.com/go-git/gcfg v1.5.0
[2021-06-01T21:08:10.218Z] go: downloading github.com/modern-go/reflect2 v1.0.1
[2021-06-01T21:08:10.218Z] go: downloading github.com/liggitt/tabwriter v0.0.0-20181228230101-89fcab3d43de
[2021-06-01T21:08:10.218Z] go: downloading github.com/googleapis/gnostic v0.4.1
[2021-06-01T21:08:10.218Z] go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
[2021-06-01T21:08:10.218Z] go: downloading github.com/asaskevich/govalidator v0.0.0-20200428143746-21a406dcc535
[2021-06-01T21:08:10.218Z] go: downloading gopkg.in/warnings.v0 v0.1.2
[2021-06-01T21:08:10.218Z] go: downloading k8s.io/kube-openapi v0.0.0-20201113171705-d219536bb9fd
[2021-06-01T21:08:10.218Z] go: downloading github.com/evanphx/json-patch v4.9.0+incompatible
[2021-06-01T21:08:10.219Z] go: downloading github.com/go-stack/stack v1.8.0
[2021-06-01T21:08:10.219Z] go: downloading github.com/golang/protobuf v1.4.3
[2021-06-01T21:08:10.219Z] go: downloading google.golang.org/protobuf v1.25.0
[2021-06-01T21:08:10.219Z] go: downloading sigs.k8s.io/structured-merge-diff/v4 v4.0.2
[2021-06-01T21:08:10.219Z] go: downloading github.com/ghodss/yaml v1.0.0
[2021-06-01T21:08:10.219Z] go: downloading golang.org/x/time v0.0.0-20200630173020-3af7569d3a1e
[2021-06-01T21:08:10.484Z] go: downloading github.com/go-openapi/spec v0.19.3
[2021-06-01T21:08:10.484Z] go: downloading github.com/gregjones/httpcache v0.0.0-20180305231024-9cad4c3443a7
[2021-06-01T21:08:10.484Z] go: downloading github.com/emicklei/go-restful v2.9.5+incompatible
[2021-06-01T21:08:10.484Z] go: downloading github.com/go-openapi/jsonpointer v0.19.3
[2021-06-01T21:08:10.484Z] go: downloading github.com/go-openapi/jsonreference v0.19.3
[2021-06-01T21:08:10.484Z] go: downloading github.com/peterbourgon/diskv v2.0.1+incompatible
[2021-06-01T21:08:10.484Z] go: downloading github.com/hashicorp/golang-lru v0.5.1
[2021-06-01T21:08:10.484Z] go: downloading github.com/PuerkitoBio/purell v1.1.1
[2021-06-01T21:08:10.484Z] go: downloading github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578
[2021-06-01T21:08:10.484Z] go: downloading github.com/go-openapi/swag v0.19.5
[2021-06-01T21:08:10.484Z] go: downloading github.com/google/go-cmp v0.5.2
[2021-06-01T21:08:10.484Z] go: downloading github.com/mailru/easyjson v0.7.0
[2021-06-01T21:08:10.484Z] go: downloading github.com/google/btree v1.0.0
[2021-06-01T21:08:10.746Z] go: downloading github.com/exponent-io/jsonpath v0.0.0-20151013193312-d6023ce2651d
[2021-06-01T21:08:10.747Z] go: downloading k8s.io/component-base v0.20.1
[2021-06-01T21:08:10.747Z] go: downloading github.com/MakeNowJust/heredoc v0.0.0-20170808103936-bb23615498cd
[2021-06-01T21:08:10.747Z] go: downloading github.com/russross/blackfriday v1.5.2
[2021-06-01T21:08:10.747Z] go: downloading github.com/mitchellh/go-wordwrap v1.0.0
[2021-06-01T21:08:10.747Z] go: downloading github.com/moby/term v0.0.0-20200312100748-672ec06f55cd
[2021-06-01T21:08:10.747Z] go: downloading github.com/docker/spdystream v0.0.0-20160310174837-449fdfce4d96
[2021-06-01T21:08:43.023Z] Running in /var/lib/jenkins/workspace/est-manager_integrations_PR-1064/src/github.com/elastic/integrations/packages/synthetics
[2021-06-01T21:08:43.350Z] + ../../build/elastic-package check -v
[2021-06-01T21:08:43.350Z] elastic-package has been installed.
[2021-06-01T21:08:43.350Z] 2021/06/01 21:08:43 DEBUG Enable verbose logging
[2021-06-01T21:08:43.350Z] Format the package
[2021-06-01T21:08:43.350Z] Error: checking package failed: formatting the integration failed (path: /var/lib/jenkins/workspace/est-manager_integrations_PR-1064/src/github.com/elastic/integrations/packages/synthetics, failFast: true): walking through the integration files failed: formatting file failed (path: /var/lib/jenkins/workspace/est-manager_integrations_PR-1064/src/github.com/elastic/integrations/packages/synthetics/data_stream/browser/fields/synthetics.yml): file is not formatted (path: /var/lib/jenkins/workspace/est-manager_integrations_PR-1064/src/github.com/elastic/integrations/packages/synthetics/data_stream/browser/fields/synthetics.yml)
[2021-06-01T21:08:43.432Z] Running in /var/lib/jenkins/workspace/est-manager_integrations_PR-1064/src/github.com/elastic/integrations
[2021-06-01T21:08:43.476Z] Archiving artifacts
[2021-06-01T21:08:43.840Z] ‘build/test-results/*.xml’ doesn’t match anything: ‘build’ exists but not ‘build/test-results/*.xml’
[2021-06-01T21:08:43.840Z] No artifacts found that match the file pattern "build/test-results/*.xml". Configuration error?
[2021-06-01T21:08:43.863Z] Recording test results
[2021-06-01T21:08:44.195Z] None of the test reports contained any result
[2021-06-01T21:08:44.195Z] [Checks API] No suitable checks publisher found.
[2021-06-01T21:08:44.509Z] + build/elastic-package stack dump -v --output build/elastic-stack-dump/latest/syn [...]

2021-08-17 14:00 UTC, elasticmachine commented
Pinging @elastic/uptime (Team:Uptime)

2021-08-17 20:02 UTC, andrewvc requested changes

2021-08-17 20:02 UTC, andrewvc commented on packages/synthetics/data_stream/browser_screenshot/fields/base-fields.yml
> +- name: data_stream.dataset
Dataset would be hard coded to `constant_keyword` with a `value` of `browser_screenshot`

2021-08-17 20:02 UTC, andrewvc commented on packages/synthetics/data_stream/browser_screenshot/fields/tls.yml
> +- name: tls
We can nix this file for screenshots

2021-08-17 20:02 UTC, andrewvc commented on packages/synthetics/data_stream/browser_screenshot/fields/tcp.yml
> +- name: tcp
We can nix this file for screenshots

2021-08-17 20:02 UTC, andrewvc commented on packages/synthetics/data_stream/browser_screenshot/fields/resolve.yml
> +- name: resolve
We can nix this file for screenshots

2021-08-17 20:02 UTC, andrewvc commented on packages/synthetics/data_stream/browser_screenshot/fields/http.yml
> +- name: http
We can nix this file for screenshots

2021-08-17 20:48 UTC, dominiqueclarke commented on packages/synthetics/data_stream/browser/agent/stream/browser.yml.hbs
> +{{#if source.zip_url.username}}
This is a great idea. I love it. I think it'll provide a lot more flexibility to add new nested keys to the UI without having to do a corresponding change on the integrations package side.

However, the UI is not currently set up to support this. Each field receives a key corresponding to the correct parameter, resulting in the UI in a large object with with all the field names, using dot notation for the nested fields, and the field values. So we have an object that looks like
```
{
    'source.zip_url.username': 'username',
    'source.zip_url.password': 'password'
}
```
Fleet exposes an integration policy object that represents the policy values. It looks something like
```
{
    'source.zip_url.username': {
          value: '',
          type: 'text,
     },
    'source.zip_url.password': {
          value: '',
          type: 'text,
     }
}
```
We iterate over the first object's keys and assign values to the exposed fleet policy.
https://github.com/elastic/kibana/blob/master/x-pack/plugins/uptime/public/components/fleet_package/use_update_policy.ts#L62
Which ends up looking something like
```
dataStream.vars['source.zip_url.username'].value = ourConfig.source.zip_url.username;
```
So the UI doesn't currently support nested keys. It is a flattened object.

To do this properly, we should convert all of the fields in http, tcp, icmp, and browser to only expose their top level params and allow the UI to handle nested params.

We can then transform our flatted object into a nested object, and use those values to populate nested fields.

I don't think that'll make it in for 7.15, but sounds like it could be a useful refactor for 7.16. Thoughts?

2021-08-17 20:54 UTC, andrewvc commented on packages/synthetics/data_stream/browser/agent/stream/browser.yml.hbs
> +{{#if source.zip_url.username}}
That makes sense. Let's keep it the way it is now and reevaluate going forward

2021-08-23 13:21 UTC, dominiqueclarke commented on packages/synthetics/data_stream/browser/fields/base-fields.yml
> +- name: data_stream.dataset
As discussed, this type is also `constant_keyword` and the appropriate value has been added.

2021-08-23 13:50 UTC, andrewvc approved these changes
LGTM

2021-08-23 15:07 UTC, merged