[AWS] Update ECS version, add event.original options and preparing for package GA
elastic/integrations pull request #1070
Opened 2021-06-02 12:37 UTC by P1llus

## What does this PR do?

Updates package ECS version to 1.10.
Sync module changes to packages if any.
Adds Preserve Raw event functionality if not already exists.
Adds pipeline tests if missing.
Adds missing tags + moving tags to advanced settings.
Adds possibility to add custom processors.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] If I'm introducing a new feature, I have modified the Kibana version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^7.13.0`).

## Related issues

- Relates #994

2021-06-02 12:37 UTC, elasticmachine commented
Pinging @elastic/integrations (Team:Integrations)

2021-06-02 12:37 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2021-06-02 12:45 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1070/detail/PR-1070/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1070/detail/PR-1070/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1070/detail/PR-1070/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1070/detail/PR-1070/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_1070.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #1070 opened`



* Start Time: 2021-06-02T12:37:57.057+0000


* Duration: 7 min 21 sec


* Commit: 40053007b366de35a13261b12ee93c5f0da09043




#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/PR-1070/buildTimeGraph/png)



</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->









### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1070/detail/PR-1070/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Check integration: aws`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-1070/runs/1/steps/394/log/?start=0">here</a></li>
<li>Description: <code>../../build/elastic-package check -v</code></l1>
</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-06-02T12:44:38.092Z] go: downloading github.com/mattn/go-colorable v0.1.8
[2021-06-02T12:44:38.092Z] go: downloading k8s.io/kubectl v0.20.1
[2021-06-02T12:44:38.092Z] go: downloading k8s.io/klog/v2 v2.4.0
[2021-06-02T12:44:38.092Z] go: downloading github.com/peterbourgon/diskv v2.0.1+incompatible
[2021-06-02T12:44:38.092Z] go: downloading github.com/liggitt/tabwriter v0.0.0-20181228230101-89fcab3d43de
[2021-06-02T12:44:38.092Z] go: downloading github.com/go-stack/stack v1.8.0
[2021-06-02T12:44:38.092Z] go: downloading github.com/mattn/go-isatty v0.0.12
[2021-06-02T12:44:38.092Z] go: downloading gopkg.in/warnings.v0 v0.1.2
[2021-06-02T12:44:38.092Z] go: downloading golang.org/x/time v0.0.0-20200630173020-3af7569d3a1e
[2021-06-02T12:44:38.092Z] go: downloading github.com/magefile/mage v1.11.0
[2021-06-02T12:44:38.092Z] go: downloading github.com/davecgh/go-spew v1.1.1
[2021-06-02T12:44:38.092Z] go: downloading github.com/xeipuuv/gojsonreference v0.0.0-20180127040603-bd5ef7bd5415
[2021-06-02T12:44:38.092Z] go: downloading github.com/xeipuuv/gojsonpointer v0.0.0-20190905194746-02993c407bfb
[2021-06-02T12:44:38.092Z] go: downloading k8s.io/utils v0.0.0-20201110183641-67b214c5f920
[2021-06-02T12:44:38.092Z] go: downloading github.com/ghodss/yaml v1.0.0
[2021-06-02T12:44:38.353Z] go: downloading github.com/xanzy/ssh-agent v0.2.1
[2021-06-02T12:44:38.353Z] go: downloading gopkg.in/inf.v0 v0.9.1
[2021-06-02T12:44:38.353Z] go: downloading github.com/googleapis/gnostic v0.4.1
[2021-06-02T12:44:38.353Z] go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
[2021-06-02T12:44:38.612Z] go: downloading github.com/modern-go/reflect2 v1.0.1
[2021-06-02T12:44:38.612Z] go: downloading k8s.io/component-base v0.20.1
[2021-06-02T12:44:38.612Z] go: downloading github.com/hashicorp/golang-lru v0.5.1
[2021-06-02T12:44:38.612Z] go: downloading github.com/golang/protobuf v1.4.3
[2021-06-02T12:44:38.612Z] go: downloading github.com/exponent-io/jsonpath v0.0.0-20151013193312-d6023ce2651d
[2021-06-02T12:44:38.612Z] go: downloading github.com/kevinburke/ssh_config v0.0.0-20190725054713-01f96b0aa0cd
[2021-06-02T12:44:38.612Z] go: downloading github.com/go-openapi/spec v0.19.3
[2021-06-02T12:44:38.612Z] go: downloading github.com/go-logr/logr v0.2.0
[2021-06-02T12:44:38.612Z] go: downloading k8s.io/kube-openapi v0.0.0-20201113171705-d219536bb9fd
[2021-06-02T12:44:38.612Z] go: downloading github.com/fatih/color v1.10.0
[2021-06-02T12:44:38.612Z] go: downloading github.com/google/btree v1.0.0
[2021-06-02T12:44:38.612Z] go: downloading github.com/russross/blackfriday v1.5.2
[2021-06-02T12:44:38.612Z] go: downloading github.com/emirpasic/gods v1.12.0
[2021-06-02T12:44:38.612Z] go: downloading google.golang.org/protobuf v1.25.0
[2021-06-02T12:44:38.612Z] go: downloading github.com/moby/term v0.0.0-20200312100748-672ec06f55cd
[2021-06-02T12:44:38.612Z] go: downloading github.com/MakeNowJust/heredoc v0.0.0-20170808103936-bb23615498cd
[2021-06-02T12:44:38.612Z] go: downloading github.com/mitchellh/go-wordwrap v1.0.0
[2021-06-02T12:44:38.872Z] go: downloading github.com/go-openapi/jsonreference v0.19.3
[2021-06-02T12:44:38.872Z] go: downloading github.com/emicklei/go-restful v2.9.5+incompatible
[2021-06-02T12:44:38.872Z] go: downloading github.com/PuerkitoBio/purell v1.1.1
[2021-06-02T12:44:38.872Z] go: downloading github.com/google/go-cmp v0.5.2
[2021-06-02T12:44:38.872Z] go: downloading github.com/go-openapi/jsonpointer v0.19.3
[2021-06-02T12:44:38.872Z] go: downloading github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578
[2021-06-02T12:44:38.872Z] go: downloading github.com/go-openapi/swag v0.19.5
[2021-06-02T12:44:38.872Z] go: downloading github.com/docker/spdystream v0.0.0-20160310174837-449fdfce4d96
[2021-06-02T12:44:38.872Z] go: downloading github.com/mailru/easyjson v0.7.0
[2021-06-02T12:45:11.102Z] Running in /var/lib/jenkins/workspace/est-manager_integrations_PR-1070/src/github.com/elastic/integrations/packages/aws
[2021-06-02T12:45:11.417Z] + ../../build/elastic-package check -v
[2021-06-02T12:45:11.417Z] elastic-package has been installed.
[2021-06-02T12:45:11.417Z] 2021/06/02 12:45:11 DEBUG Enable verbose logging
[2021-06-02T12:45:11.417Z] Format the package
[2021-06-02T12:45:11.417Z] Error: checking package failed: formatting the integration failed (path: /var/lib/jenkins/workspace/est-manager_integrations_PR-1070/src/github.com/elastic/integrations/packages/aws, failFast: true): walking through the integration files failed: formatting file failed (path: /var/lib/jenkins/workspace/est-manager_integrations_PR-1070/src/github.com/elastic/integrations/packages/aws/data_stream/cloudtrail/fields/ecs.yml): file is not formatted (path: /var/lib/jenkins/workspace/est-manager_integrations_PR-1070/src/github.com/elastic/integrations/packages/aws/data_stream/cloudtrail/fields/ecs.yml)
[2021-06-02T12:45:11.484Z] Running in /var/lib/jenkins/workspace/est-manager_integrations_PR-1070/src/github.com/elastic/integrations
[2021-06-02T12:45:11.521Z] Archiving artifacts
[2021-06-02T12:45:11.828Z] ‘build/test-results/*.xml’ doesn’t match anything: ‘build’ exists but not ‘build/test-results/*.xml’
[2021-06-02T12:45:11.828Z] No artifacts found that match the file pattern "build/test-results/*.xml". Configuration error?
[2021-06-02T12:45:11.849Z] Recording test results
[2021-06-02T12:45:12.123Z] None of the test reports contained any result
[2021-06-02T12:45:12.124Z] [Checks API] No suitable checks publisher found.
[2021-06-02T12:45:12.445Z] + build/elastic-package stack dump -v --output build/elastic-stack-dump/latest/aws
[2021-06-02T12:45:12.445Z] 2021/06/02 12:45:12  WARN CommitHash is undefined, in  [...]

2021-06-02 14:45 UTC, kaiyan-sheng commented on packages/aws/data_stream/ec2_metrics/fields/fields.yml
> +    - name: cloudwatch
We might be missing this field in beats too... thanks for catching it!

2021-06-02 14:45 UTC, kaiyan-sheng approved these changes

2021-06-02 15:53 UTC, leehinman requested changes

2021-06-02 15:53 UTC, leehinman commented on packages/aws/data_stream/cloudtrail/elasticsearch/ingest_pipeline/default.yml
> +  - rename:
I might be wrong, but I don't think result.host or result.source make sense for CloudTrail.

2021-06-02 15:59 UTC, P1llus commented on packages/aws/data_stream/cloudtrail/elasticsearch/ingest_pipeline/default.yml
> +  - rename:
Are they not the ones mapped with splunk? That part is inside the splunk specific parsing, and should just be a conversion from the edge processor used for splunk?

2021-06-02 17:32 UTC, leehinman commented on packages/aws/data_stream/cloudtrail/elasticsearch/ingest_pipeline/default.yml
> +  - rename:
the original Splunk cloudtrail edge processing didn't copy `result.host` or `result.source` also they weren't included in the fingerprint.

pretty sure the data wasn't valuable.  `result.host` would be the Splunk machine that downloaded the data and `results.source` should be the S3 object which we already have.

2021-06-02 19:01 UTC, P1llus commented on packages/aws/data_stream/cloudtrail/elasticsearch/ingest_pipeline/default.yml
> +  - rename:
Ah I must have gotten it from another splunk source, sorry about that, will modify it tomorrow then :) Did you find anything else or was this the only part @leehinman ?

2021-06-03 13:28 UTC, leehinman commented on packages/aws/data_stream/cloudtrail/elasticsearch/ingest_pipeline/default.yml
> +  - rename:
everything else looked great

2021-06-04 09:38 UTC, marc-gr approved these changes

2021-06-04 10:02 UTC, merged