Citrix ADC Integration Grok Fix
elastic/integrations pull request #10778
Opened 2024-08-13 12:15 UTC by Linu-Elias

## Proposed commit message
SDH issue on Citrix-ADC logs not being ingested properly.
Fix -Modified the grok pattern by updating ` %{WORD: event.timezone} ` optional in native.yaml file.

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [X] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## How to test this PR locally

## Related issues

## Screenshots

2024-08-13 12:43 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-08-13 12:44 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14623)
* Commit: 79a95d8e3491d70adf460e8ed875052a2e3557dd

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14623","number":14623,"commit":"79a95d8e3491d70adf460e8ed875052a2e3557dd"}],"number":14623}
buildkite-pr-comment-->

2024-08-14 03:58 UTC, ishleenk17 commented on packages/citrix_adc/changelog.yml
> +    - description: Timezone field has been updated to optional in the native header Grok pattern.
```suggestion
    - description: Timezone field made optional for the citrix_adc log messages

```

2024-08-14 04:01 UTC, ishleenk17 commented
@Linu-Elias :  There are couple more ingest pipeline as well in citrix_adc other than native.yml
Do we need to take care of timezone there as well ?

Tagging @elastic/security-external-integrations for review as well since they implemented the log part of the Citrix ADC.

2024-08-14 06:01 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14639)
* Commit: 705b111c4c643aa718956c1b89672584ced69a87

### History
* :green_heart: [Build #14623](https://buildkite.com/elastic/integrations/builds/14623) succeeded 79a95d8e3491d70adf460e8ed875052a2e3557dd

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14639","number":14639,"commit":"705b111c4c643aa718956c1b89672584ced69a87"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14623","number":14623,"commit":"79a95d8e3491d70adf460e8ed875052a2e3557dd"}],"number":14639}
buildkite-pr-comment-->

2024-08-14 06:24 UTC, ShourieG approved these changes
LGTM

2024-08-14 06:32 UTC, ishleenk17 approved these changes
Looks good!

2024-08-14 07:56 UTC, efd6 requested changes

2024-08-14 07:56 UTC, efd6 commented on packages/citrix_adc/data_stream/log/_dev/test/pipeline/test-citrix-waf-native.log
> +<123> 10/08/2024:09:38:41  SYSLOGHOST 0-PPE-1 : default TCP CONN_TERMINATE 6715345 0 :  Source 127.1.2.1:80 - Destination 127.1.1.2:20714 - Start Time 10/08/2024:09:37:54  - End Time 10/08/2024:09:38
Should this have a terminal `\n` literal? That doesn't look right.

2024-08-14 11:32 UTC, Linu-Elias commented
> @Linu-Elias Please check if we need the change on other ingest pipelines, otherwise looks good

@ishleenk17 I don't think we need to change other ingest pipelines since they all are passing with this change.

2024-08-14 11:51 UTC, Linu-Elias commented on packages/citrix_adc/data_stream/log/_dev/test/pipeline/test-citrix-waf-native.log
> +<123> 10/08/2024:09:38:41  SYSLOGHOST 0-PPE-1 : default TCP CONN_TERMINATE 6715345 0 :  Source 127.1.2.1:80 - Destination 127.1.1.2:20714 - Start Time 10/08/2024:09:37:54  - End Time 10/08/2024:09:38
@efd6 This is in the format of the sample logs that the customer provided in the [SDH isuue](https://github.com/elastic/sdh-beats/issues/5014.)

2024-08-20 21:55 UTC, andrewkroh commented on packages/citrix_adc/data_stream/log/_dev/test/pipeline/test-citrix-waf-native.log
> +<123> 10/08/2024:09:38:41  SYSLOGHOST 0-PPE-1 : default TCP CONN_TERMINATE 6715345 0 :  Source 127.1.2.1:80 - Destination 127.1.1.2:20714 - Start Time 10/08/2024:09:37:54  - End Time 10/08/2024:09:38
There's a difference between this line and what are in the `event.original` samples from the user. The user's samples have an actual newline at the end of the `event.original` (encoded to "\n" in JSON). What's in in this `.log` file is a slash followed by an "n" to be literal. You can see that in the expected.json file where it contains `"Total_bytes_recv 1 \\n"` instead of `"Total_bytes_recv 1 \n"`.

To match a test case to the user's samples, I think you will need to use the a [.json test file](https://github.com/elastic/elastic-package/blob/main/docs/howto/pipeline_testing.md#input-events) instead of `.log` so that you can encode the newline into the `message`.

2024-08-21 06:31 UTC, Linu-Elias commented on packages/citrix_adc/data_stream/log/_dev/test/pipeline/test-citrix-waf-native.log
> +<123> 10/08/2024:09:38:41  SYSLOGHOST 0-PPE-1 : default TCP CONN_TERMINATE 6715345 0 :  Source 127.1.2.1:80 - Destination 127.1.1.2:20714 - Start Time 10/08/2024:09:37:54  - End Time 10/08/2024:09:38
@andrewkroh Thanks, I have now used a `.json` file intead of `.log`. In this context, the  `expected.json` file contains `"Total_bytes_recv 1 \n"` intead of `"Total_bytes_recv 1 \\n"`.

2024-08-21 06:53 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14818)
* Commit: e2ce0a229ffcd31949bdac98351d5b42aa906827

### History
* :green_heart: [Build #14639](https://buildkite.com/elastic/integrations/builds/14639) succeeded 705b111c4c643aa718956c1b89672584ced69a87
* :green_heart: [Build #14623](https://buildkite.com/elastic/integrations/builds/14623) succeeded 79a95d8e3491d70adf460e8ed875052a2e3557dd

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14818","number":14818,"commit":"e2ce0a229ffcd31949bdac98351d5b42aa906827"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14639","number":14639,"commit":"705b111c4c643aa718956c1b89672584ced69a87"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14623","number":14623,"commit":"79a95d8e3491d70adf460e8ed875052a2e3557dd"}],"number":14818}
buildkite-pr-comment-->

2024-08-21 10:37 UTC, andrewkroh approved these changes

2024-08-21 12:27 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14854)
* Commit: 07c4792b94bda99a2b2e3a8821a2d874c96aace0

### History
* :green_heart: [Build #14818](https://buildkite.com/elastic/integrations/builds/14818) succeeded e2ce0a229ffcd31949bdac98351d5b42aa906827
* :green_heart: [Build #14639](https://buildkite.com/elastic/integrations/builds/14639) succeeded 705b111c4c643aa718956c1b89672584ced69a87
* :green_heart: [Build #14623](https://buildkite.com/elastic/integrations/builds/14623) succeeded 79a95d8e3491d70adf460e8ed875052a2e3557dd

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14854","number":14854,"commit":"07c4792b94bda99a2b2e3a8821a2d874c96aace0"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14818","number":14818,"commit":"e2ce0a229ffcd31949bdac98351d5b42aa906827"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14639","number":14639,"commit":"705b111c4c643aa718956c1b89672584ced69a87"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14623","number":14623,"commit":"79a95d8e3491d70adf460e8ed875052a2e3557dd"}],"number":14854}
buildkite-pr-comment-->

2024-08-21 12:51 UTC, merged

2024-08-21 13:07 UTC, elasticmachine commented
Package citrix_adc - 1.7.1 containing this change is available at https://epr.elastic.co/search?package=citrix_adc