in progress
elastic/integrations pull request #10780
Opened 2024-08-13 14:19 UTC by gauravneelwarna

## Proposed commit message

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## How to test this PR locally

## Related issues

- 

## Screenshots

2024-09-20 16:28 UTC, chrisberkhout requested changes
A lot of great work in this. I'm impressed!

Hopefully a lot of the comments will be quick to address. Some will take a bit more time but then I think we'll be done or very close.

2024-09-20 16:28 UTC, chrisberkhout commented on packages/checkpoint_harmony_endpoint/data_stream/threatemulation/elasticsearch/ingest_pipeline/default.yml
> +      if: ctx.file?.name != null && ctx.json?.file_name != null
Why check `ctx.file?.name != null`?
That's the destination for the joined value. I think the current condition is never true.
Also, it is possible to have multiple values in any field, so I think you should not join these types of values (there are other cases too).
Probably the best way to hand this is to rename the array field to its destination, then in the end have a `script` processor that for a list of fields will turn an array with one value into a plain value.

2024-09-20 16:28 UTC, chrisberkhout commented on packages/checkpoint_harmony_endpoint/data_stream/threatemulation/elasticsearch/ingest_pipeline/default.yml
> +      if: ctx.file?.name == " "
set/append then remove can usually be set/append with an if condition. if conditions are in Painless, so you can do things like check an array length.

2024-09-20 16:28 UTC, chrisberkhout commented on packages/checkpoint_harmony_endpoint/data_stream/threatemulation/elasticsearch/ingest_pipeline/default.yml
> +      ignore_failure: true
I think most of the work in this range can be replaced by just a rename of `json` to `checkpoint_harmony_endpoint.threatemulation`.

2024-09-20 16:28 UTC, chrisberkhout commented on packages/checkpoint_harmony_endpoint/data_stream/threatemulation/elasticsearch/ingest_pipeline/default.yml
> +      ignore_failure: true
Avoid using `ignore_failure: true`. If there is no valid data we want it to fail. Most other failures can be avoided by setting `ignore_missing: true`, `ignore_empty_value: true` or an appropriate `if` condition.

2024-09-20 16:28 UTC, chrisberkhout commented on packages/checkpoint_harmony_endpoint/data_stream/threatemulation/elasticsearch/ingest_pipeline/default.yml
> +      value: checkpoint_harmony_endpoint
better to do at the top

2024-09-20 16:28 UTC, chrisberkhout commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/agent/stream/antibot.yml.hbs
> +{{/if}}
The `enable_request_tracer` variable needs to be defined. Do it in the top level `manifest.yml` and make it default to false and not be shown to the user by default (so it will appear under "Advanced options").

2024-09-20 16:28 UTC, chrisberkhout commented on packages/checkpoint_harmony_endpoint/kibana/dashboard/checkpoint_harmony_endpoint-21fdef7e-31b1-4eda-8842-3a100dc33851.json
What I see now is a good start:

![image](https://github.com/user-attachments/assets/9ea95e29-e5a7-4e22-9e1e-3fe802818334)

A few points:
- Don't include "Dashboard" in the name. A better name would be "Check Point Harmony Endpoint Overview" or just "Check Point Harmony Endpoint", since there's only one.
- I think the severity field, and others that might be shared across different data streams, should be raised up to the `checkpoint_harmony_endpoint` prefix, so all types can be filtered on that (for that bottom right panel).
- We prefer to set filters on each panel rather than having an overall filter at the top. Once it's set up it makes the user experience a bit more intuitive.

There are some more guidelines for dashboards. One document you may not have seen I will share on Slack.
The other, more generic one is [here](https://www.elastic.co/guide/en/integrations-developer/current/dashboard-guidelines.html).

2024-09-20 16:30 UTC, chrisberkhout commented
> ❌ Author of the following commits did not sign a [Contributor Agreement](https://www.elastic.co/contributor-agreement): [f943064](https://github.com/elastic/integrations/commit/f943064e707f16f4533be4f46742ac24c4b77431), [2081cfd](https://github.com/elastic/integrations/commit/2081cfd4ee577336c2f8e53932a05f683244835b), [c7d0b6a](https://github.com/elastic/integrations/commit/c7d0b6aa1eaf80c6e7cca3e304abe307980265fb), [1b1fddd](https://github.com/elastic/integrations/commit/1b1fdddc3eaf113c7b890d1a03c086f30cca8777), [85f04eb](https://github.com/elastic/integrations/commit/85f04ebc38e8b43f527600a500b9bc877590e256), [2740521](https://github.com/elastic/integrations/commit/2740521c417473786d9a142cb019345554bb2f8b), [346f9a0](https://github.com/elastic/integrations/commit/346f9a02ccabdc01c2c087267cfa7cec52620c64), [2ef5cea](https://github.com/elastic/integrations/commit/2ef5cea702fc5666f4548eaa13f425aa48551e93), [a84d705](https://github.com/elastic/integrations/commit/a84d705963febaa5ba8f37b5d53ff47010feb9ee), [de5f43a](https://github.com/elastic/integrations/commit/de5f43af9a5fd8625a6def275c5ccf264da26a6d), [b2565e3](https://github.com/elastic/integrations/commit/b2565e3873b2d5696b50e34422a02aed17049e4a), [b4c0ec1](https://github.com/elastic/integrations/commit/b4c0ec1fa8c14ae76e4846cfe835824d46b48069), [3db6cc6](https://github.com/elastic/integrations/commit/3db6cc697392590a653c2db895e9baebc4da7e58)
> 
> Please, read and sign the above mentioned agreement if you want to contribute to this project

Please do this we we're able to merge when ready.

2024-10-08 12:34 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/agent/stream/antibot.yml.hbs
> +  page_limit: {{page_limit}}
It is `page_limit` and we have used the same variable name in every file.

2024-10-08 12:38 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/agent/stream/antibot.yml.hbs
> +                "next_startTime": timestamp(timestamp(body.data.records[0].time) + duration("1s")).format(time_layout.RFC3339),
Yes, that's correct

2024-10-08 12:45 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/data_stream/threatextraction/agent/stream/threatextraction.yml.hbs
> +          "filter": "product:\"Threat Extraction\" AND NOT event_type:\"TEX Info Event\"",
The  `TEX Info Event` logs seems to be a system info/notification logs, 
`{"policy_date":"2024-09-06T10:21:38.0000000Z","severity":"Informational","time":"2024-09-09T12:46:36Z","id":"a4640108-91b1-0f19-66df-dc9a00000004","orig":"164.100.1.8","sequencenum":16777215,"client_name":"Check Point Endpoint Security Client","client_version":["88.50.0213"],"description":"Threat Emulation is enabled due to valid license. ","event_type":"TE Info Event","host_type":["Desktop"],"installed_products":"Full Disk Encryption; Media Encryption & Port Protection; Firewall; Compliance; Application Control; Anti-Malware; VPN; Anti-Bot; Forensics; Threat Emulation","os_name":["Microsoft Windows 10 Pro"],"os_version":["10.0-19045-SP0.0-SMP"],"policy_name":"Default Threat Extraction, Emulation and Anti-Exploit settings for the entire organization","policy_number":7,"product":"Threat Emulation","product_family":"Endpoint","reason":"Valid_TE_License","src":"10.35.38.102","src_machine_name":"DESKTOP-E2P4OL0","src_user_name":["admin"],"tenant_id":"3e15ed24-89ff-4986-a204-c425cee4ba48","user_sid":"S-1-5-21-3766288932-3295778425-2939962592-1001","domain":"SMC User","type":"Control"}`

If you want to include these events/logs as well, Please let us know. We'll update the filter for both `Threat Extraction` and `Threat Emualtion` data stream.

2024-10-10 09:40 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/data_stream/threatemulation/agent/stream/threatemulation.yml.hbs
> +          "filter": "product:\"Threat Emulation\" AND NOT event_type:\"TE Info Event\"",
The  `TEX Info Event` logs seems to be a system info/notification logs, 
```
{"policy_date":"2024-09-06T10:21:38.0000000Z","severity":"Informational","time":"2024-09-09T12:46:36Z","id":"a4640108-91b1-0f19-66df-dc9a00000004","orig":"164.100.1.8","sequencenum":16777215,"client_name":"Check Point Endpoint Security Client","client_version":["88.50.0213"],"description":"Threat Emulation is enabled due to valid license. ","event_type":"TE Info Event","host_type":["Desktop"],"installed_products":"Full Disk Encryption; Media Encryption & Port Protection; Firewall; Compliance; Application Control; Anti-Malware; VPN; Anti-Bot; Forensics; Threat Emulation","os_name":["Microsoft Windows 10 Pro"],"os_version":["10.0-19045-SP0.0-SMP"],"policy_name":"Default Threat Extraction, Emulation and Anti-Exploit settings for the entire organization","policy_number":7,"product":"Threat Emulation","product_family":"Endpoint","reason":"Valid_TE_License","src":"10.35.38.102","src_machine_name":"DESKTOP-E2P4OL0","src_user_name":["admin"],"tenant_id":"3e15ed24-89ff-4986-a204-c425cee4ba48","user_sid":"S-1-5-21-3766288932-3295778425-2939962592-1001","domain":"SMC User","type":"Control"}
``` 

If you want to include these events/logs as well, Please let us know. We'll update the filter for `Threat Emualtion` data stream.

2024-10-11 11:00 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/manifest.yml
> +    type: image/png
fixed

2024-10-11 11:00 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/changelog.yml
> +    - description: Initial draft of the package
fixed

2024-10-11 11:01 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/manifest.yml
> +version: 0.0.1
fixed

2024-10-11 11:01 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/manifest.yml
> +  type: elastic
fixed

2024-10-11 11:02 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/docs/README.md
> +Refer to Check Point's Infinity API Guide to create an API key: https://app.swaggerhub.com/apis-docs/Check-Point/infinity-events-api/1.0.0#/Authentication/getAuthToken
fixed

2024-10-11 11:02 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/docs/README.md
> +2. Interval: Interval at which the logs will be pulled.
fixed

2024-10-11 11:03 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/docs/README.md
> +
fixed

2024-10-11 11:04 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/docs/README.md
> +
fixed

2024-10-11 11:04 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/agent/stream/antibot.yml.hbs
fixed

2024-10-11 11:04 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/manifest.yml
> +          - forwarded
fixed

2024-10-11 11:04 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/LICENSE.txt
fixed

2024-10-11 11:04 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/manifest.yml
> +    version: "^8.12.2"
fixed

2024-10-11 11:05 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/_dev/build/build.yml
> +    import_mappings: true
fixed

2024-10-11 11:05 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/docs/README.md
> +# Check Point Harmony Endpoint
fixed

2024-10-11 11:05 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/_dev/deploy/docker/files/config.yml
> +          ],"recordsCount":1,"nextPageToken":"NULL"}}
fixed

2024-10-11 11:05 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/agent/stream/antibot.yml.hbs
fixed

2024-10-11 11:06 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/agent/stream/antibot.yml.hbs
fixed

2024-10-11 11:07 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/agent/stream/antibot.yml.hbs
> +    (!has(state.cursor) || (has(state.cursor) && has(state.cursor.auth_token) && state.cursor.auth_token == null))
fixed

2024-10-11 11:08 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/agent/stream/antibot.yml.hbs
> +            }
fixed

2024-10-11 11:08 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/agent/stream/antibot.yml.hbs
> +interval: {{interval}}
fixed

2024-10-11 11:08 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/agent/stream/antibot.yml.hbs
> +              body.data.state == "Done"
fixed

2024-10-11 11:14 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/data_stream/threatextraction/agent/stream/threatextraction.yml.hbs
> +          "filter": "product:\"Threat Extraction\" AND NOT event_type:\"TEX Info Event\"",
Added comment in Threat Emulation file https://github.com/elastic/integrations/pull/10780#discussion_r1795070019

2024-10-11 11:25 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/sample_event.json
> +        "type": [
fixed

2024-10-11 11:26 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/sample_event.json
> +}
fixed

2024-10-11 11:26 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/_dev/test/pipeline/test-antibot.log
> +{"confidence_level":"High","policy_date":"2024-09-03T10:46:14.0000000Z","severity":"High","time":"2024-09-06T08:32:28Z","id":"a4640108-91b1-0f19-66da-bf6400000001","orig":"164.100.1.8","sequencenum":
fixed

2024-10-11 11:26 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/data_stream/threatemulation/elasticsearch/ingest_pipeline/default.yml
> +      value: "{{ _ingest.on_failure_message }}"
fixed

2024-10-11 11:26 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/data_stream/threatemulation/elasticsearch/ingest_pipeline/default.yml
> +      ignore_failure: true
fixed

2024-10-11 11:27 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/data_stream/threatemulation/elasticsearch/ingest_pipeline/default.yml
> +  - append:
fixed

2024-10-11 11:28 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/data_stream/threatemulation/elasticsearch/ingest_pipeline/default.yml
> +      ignore_failure: true
fixed

2024-10-11 11:29 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/data_stream/threatemulation/elasticsearch/ingest_pipeline/default.yml
> +      value: checkpoint_harmony_endpoint
fixed

2024-10-11 11:34 UTC, gauravneelwarna commented on packages/checkpoint_harmony_endpoint/docs/README.md
> +7. **Zero-phishing:** Examines various website characteristics to ensure a site isn't impersonating another to maliciously collect personal information. It generates alerts for potential phishing sit
Yes, the summary is comprehensive and covers all the points we've identified about Harmony Endpoint so far.

We've achieved good coverage by creating as many events as possible through various activities on a managed Windows endpoint. While we may have missed some scenarios—such as ransomware-related events—due to the impossibility of safely triggering them, we can always add these in the future when we encounter real-world samples.

2024-10-11 11:41 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/10780 # FIXME Replace with the real PR link
fixed

2024-10-11 11:41 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/agent/stream/antibot.yml.hbs
> +{{/if}}
fixed

2024-10-11 11:41 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/manifest.yml
> +description: "Package to collect logs from Check Point Harmony Endpoint"
fixed

2024-10-11 11:41 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/manifest.yml
> +#        description: Collecting sample logs
fixed

2024-10-11 11:41 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/manifest.yml
> +            secret: true
fixed

2024-10-11 13:01 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/kibana/dashboard/checkpoint_harmony_endpoint-21fdef7e-31b1-4eda-8842-3a100dc33851.json
Regarding -->  filter for dashboards.

When we skip an overall filter at the top of dashboard.
it shows an error while exporting a dashboard `expected filter in dashboard: no filter found and at least one panel does not have a filter `

However, we have added a filter, i.e.,( `event.module:"checkpoint_harmony_endpoint"`) which would be evaluated as true for every log coming from Checkpoint Harmony Endpoint.

2024-10-14 04:35 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/data_stream/threatemulation/elasticsearch/ingest_pipeline/default.yml
> +      if: ctx.file?.name != null && ctx.json?.file_name != null
fixed

2024-10-14 04:35 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/data_stream/threatemulation/elasticsearch/ingest_pipeline/default.yml
> +      value: alert
fixed

2024-10-14 04:36 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/data_stream/threatemulation/elasticsearch/ingest_pipeline/default.yml
> +      if: ctx.file?.name == " "
fixed

2024-10-14 04:36 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/agent/stream/antibot.yml.hbs
> +{{/if}}
fixed

2024-10-15 12:34 UTC, chrisberkhout commented on packages/checkpoint_harmony_endpoint/img/sample-logo.svg
Still needs to be removed.

2024-10-15 12:35 UTC, chrisberkhout commented on packages/checkpoint_harmony_endpoint/img/sample-screenshot.png
Still needs to be removed. There are new screenshots but `manifest.yml` needs to be updated to refer to those and not `sample-screenshot.png`.

2024-10-15 12:40 UTC, chrisberkhout commented on packages/checkpoint_harmony_endpoint/docs/README.md
> +Refer to Check Point's Infinity API Guide to create an API key: https://app.swaggerhub.com/apis-docs/Check-Point/infinity-events-api/1.0.0#/Authentication/getAuthToken
Missing full stop at the end.

2024-10-15 12:43 UTC, chrisberkhout commented on packages/checkpoint_harmony_endpoint/docs/README.md
> +
The links aren't formatted in correct markdown:
```diff
-They are described in the ECS documentation.(https://www.elastic.co/guide/en/ecs/current/ecs-field-reference.html)
+They are described in the [ECS documentation](https://www.elastic.co/guide/en/ecs/current/ecs-field-reference.html).
```

2024-10-15 12:56 UTC, chrisberkhout commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/manifest.yml
> +          - forwarded
Thanks. I think I was mixing up `preserve_original_event` and `forwarded`. Also I learned that it's important to have the `forwarded` tag to avoid host fields. The details are complicated  (see https://github.com/elastic/beats/issues/41046 if interested), but setting `publisher_pipeline.disable_host: true` isn't enough.

To finish this, just do this change to each data stream manifest:

```diff
diff --git a/packages/checkpoint_harmony_endpoint/data_stream/antibot/manifest.yml b/packages/checkpoint_harmony_endpoint/data_stream/antibot/manifest.yml
index bc5c0b2a30..c200f7b543 100644
--- a/packages/checkpoint_harmony_endpoint/data_stream/antibot/manifest.yml
+++ b/packages/checkpoint_harmony_endpoint/data_stream/antibot/manifest.yml
@@ -13,7 +13,7 @@ streams:
         required: true
         show_user: false
         default:
-          - preserve_original_event
+          - forwarded
       - name: filter
         type: text
         title: Filter
```

2024-10-15 13:04 UTC, chrisberkhout commented on packages/checkpoint_harmony_endpoint/_dev/deploy/docker/files/config.yml
> +          ],"recordsCount":1,"nextPageToken":"NULL"}}
I see the wrapper is changed for the large responses.
Please also have one record per line, like this:

```diff
diff --git a/packages/checkpoint_harmony_endpoint/_dev/deploy/docker/files/config.yml b/packages/checkpoint_harmony_endpoint/_dev/deploy/docker/files/config.yml
index 4dc11dda86..17d5be4b1b 100644
--- a/packages/checkpoint_harmony_endpoint/_dev/deploy/docker/files/config.yml
+++ b/packages/checkpoint_harmony_endpoint/_dev/deploy/docker/files/config.yml
@@ -131,7 +131,9 @@ rules:
             "success": true,
             "data": {
               "records": [
-                {"confidence_level": "High", "policy_date": "2024-09-03T10:46:14.0000000Z", "severity": "High", "time": "2024-09-06T08:32:28Z", "id": "a4640108-91b1-0f19-66da-bf6400000001", "orig": "164.100.1.8", "sequencenum": 16777215, "action": "Detect", "product": "Anti-Bot", "domain": "SMC User", "product_family": "Endpoint", "type": "Log", "client_name": "Check Point Endpoint Security Client", "client_version": [ "88.50.0213" ], "description": "Detected dns query to malicious domain malware.wicar.org [Infecting Website.RS.TC.32eclVjT]. To exclude: On the Harmony Endpoint Management add an Anti-Bot exclusion of type Domain with value: \"malware.wicar.org\"", "event_type": "Anti Bot Event", "host_type": [ "Desktop" ], "installed_products": "Full Disk Encryption; Media Encryption & Port Protection; Firewall; Compliance; Application Control; Anti-Malware; VPN; Anti-Bot; Forensics; Threat Emulation", "os_name": [ "Microsoft Windows 10 Pro" ], "os_version": [ "10.0-19045-SP0.0-SMP" ], "policy_name": "Default Anti-Bot settings", "src": "10.35.38.102", "src_machine_name": "DESKTOP-E2P4OL0", "src_user_name": [ "admin" ], "tenant_id": "3e15ed24-89ff-4986-a204-c425cee4ba48", "user_sid": "S-1-5-21-3766288932-3295778425-2939962592-1001", "policy_number": 3, "protection_type": "URL Reputation", "file_md5": "7469cc568ad6821fd9d925542730a7d8", "file_name": [ "svchost.exe" ], "file_size": 47040, "file_type": "exe", "malware_action": [ "Access to site known to contain malware" ], "packet_capture_unique_id": "e71ae8af-f40e-49cb-9bef-1a91602f8faf", "protection_name": "Infecting Website.RS.TC.32eclVjT", "resource": [ "malware.wicar.org" ], "packet_capture": "Packet Capture", "advanced_info": "\"exclusions\":[{\"exclusion_engine_type\":\"Anti Bot exclusions\",\"exclusion_type\":\"Domain\",\"exclusion_value\":{\"default_value\":\"malware.wicar.org\",\"md5\":\"\",\"original_name\":\"\",\"signer\":\"\",\"process\":\"\",\"protection\":\"\",\"comment\":\"\"}}]", "dst": "0.0.0.0", "process_username": "NETWORK SERVICE", "proxy_src_ip": "0.0.0.0" }, { "confidence_level": "High", "policy_date": "2024-09-03T10:46:14.0000000Z", "severity": "High", "time": "2024-09-06T08:32:26Z", "id": "a4640108-91b1-0f19-66da-bf6400000000", "orig": "164.100.1.8", "sequencenum": 16777215, "action": "Detect", "product": "Anti-Bot", "domain": "SMC User", "product_family": "Endpoint", "type": "Log", "client_name": "Check Point Endpoint Security Client", "client_version": [ "88.50.0213" ], "description": "Detected dns query to malicious domain malware.wicar.org [Infecting Website.RS.TC.32eclVjT]. To exclude: On the Harmony Endpoint Management add an Anti-Bot exclusion of type Domain with value: \"malware.wicar.org\"", "event_type": "Anti Bot Event", "host_type": [ "Desktop" ], "installed_products": "Full Disk Encryption; Media Encryption & Port Protection; Firewall; Compliance; Application Control; Anti-Malware; VPN; Anti-Bot; Forensics; Threat Emulation", "os_name": [ "Microsoft Windows 10 Pro" ], "os_version": [ "10.0-19045-SP0.0-SMP" ], "policy_name": "Default Anti-Bot settings", "src": "10.35.38.102", "src_machine_name": "DESKTOP-E2P4OL0", "src_user_name": [ "admin" ], "tenant_id": "3e15ed24-89ff-4986-a204-c425cee4ba48", "user_sid": "S-1-5-21-3766288932-3295778425-2939962592-1001", "policy_number": 3, "protection_type": "URL Reputation", "file_md5": "bb7c48cddde076e7eb44022520f40f77", "file_name": [ "chrome.exe" ], "file_size": 2742376, "file_type": "exe", "malware_action": [ "Access to site known to contain malware" ], "packet_capture_unique_id": "087e116c-c098-44ba-95dd-064a90189b4a", "protection_name": "Infecting Website.RS.TC.32eclVjT", "resource": [ "malware.wicar.org" ], "packet_capture": "Packet Capture", "advanced_info": "\"exclusions\":[{\"exclusion_engine_type\":\"Anti Bot exclusions\",\"exclusion_type\":\"Domain\",\"exclusion_value\":{\"default_value\":\"malware.wicar.org\",\"md5\":\"\",\"original_name\":\"\",\"signer\":\"\",\"process\":\"\",\"protection\":\"\",\"comment\":\"\"}}]", "dst": "0.0.0.0", "process_username": "admin", "proxy_src_ip": "0.0.0.0" }, { "confidence_level": "Medium", "policy_date": "2024-08-29T13:12:51.0000000Z", "severity": "Critical", "time": "2024-09-02T08:53:44Z", "id": "a4640108-91b1-0f19-66d5-7d9d00000000", "orig": "164.100.1.8", "sequencenum": 16777215, "action": "Detect", "product": "Anti-Bot", "domain": "SMC User", "product_family": "Endpoint", "type": "Log", "client_name": "Check Point Endpoint Security Client", "client_version": [ "88.50.0213" ], "description": "Detected bot activity [Anti-Bot test.TC.e]. To exclude: On the Harmony Endpoint Management add an exclusion of type \"URL\" with value: \"http://www.threat-cloud.com/test/files/MediumConfidenceBot.html\"", "event_type": "Anti Bot Event", "host_type": [ "Desktop" ], "installed_products": "Full Disk Encryption; Media Encryption & Port Protection; Firewall; Compliance; Application Control; Anti-Malware; VPN; Anti-Bot; Forensics; Threat Emulation", "os_name": [ "Microsoft Windows 10 Pro" ], "os_version": [ "10.0-19045-SP0.0-SMP" ], "policy_name": "Default Anti-Bot settings", "src": "10.35.38.102", "src_machine_name": "DESKTOP-E2P4OL0", "src_user_name": [ "admin" ], "tenant_id": "3e15ed24-89ff-4986-a204-c425cee4ba48", "user_sid": "S-1-5-21-3766288932-3295778425-2939962592-1001", "policy_number": 2, "protection_type": "URL Reputation", "file_md5": "bd075be9d011daaa82c3f9ff2572076e", "file_name": [ "chrome.exe" ], "file_size": 2742376, "file_type": "exe", "malware_action": [ "Communication with C&C" ], "packet_capture_unique_id": "6c239c74-89a9-4797-ab6b-75a2b2a6afd7", "protection_name": "Anti-Bot test.TC.e", "resource": [ "www.threat-cloud.com" ], "packet_capture": "Packet Capture", "advanced_info": "\"exclusions\":[{\"exclusion_engine_type\":\"Anti Bot exclusions\",\"exclusion_type\":\"URL\",\"exclusion_value\":{\"default_value\":\"http://www.threat-cloud.com/test/files/MediumConfidenceBot.html\",\"md5\":\"\",\"original_name\":\"\",\"signer\":\"\",\"process\":\"\",\"protection\":\"\",\"comment\":\"\"}}]", "dst": "89.160.20.128", "process_username": "admin", "proxy_src_ip": "89.160.20.128", "dst_country": [ "UnitedStates" ]}
+                {"confidence_level": "High", "policy_date": "2024-09-03T10:46:14.0000000Z", "severity": "High", "time": "2024-09-06T08:32:28Z", "id": "a4640108-91b1-0f19-66da-bf6400000001", "orig": "164.100.1.8", "sequencenum": 16777215, "action": "Detect", "product": "Anti-Bot", "domain": "SMC User", "product_family": "Endpoint", "type": "Log", "client_name": "Check Point Endpoint Security Client", "client_version": [ "88.50.0213" ], "description": "Detected dns query to malicious domain malware.wicar.org [Infecting Website.RS.TC.32eclVjT]. To exclude: On the Harmony Endpoint Management add an Anti-Bot exclusion of type Domain with value: \"malware.wicar.org\"", "event_type": "Anti Bot Event", "host_type": [ "Desktop" ], "installed_products": "Full Disk Encryption; Media Encryption & Port Protection; Firewall; Compliance; Application Control; Anti-Malware; VPN; Anti-Bot; Forensics; Threat Emulation", "os_name": [ "Microsoft Windows 10 Pro" ], "os_version": [ "10.0-19045-SP0.0-SMP" ], "policy_name": "Default Anti-Bot settings", "src": "10.35.38.102", "src_machine_name": "DESKTOP-E2P4OL0", "src_user_name": [ "admin" ], "tenant_id": "3e15ed24-89ff-4986-a204-c425cee4ba48", "user_sid": "S-1-5-21-3766288932-32957784 [...]

2024-10-15 13:07 UTC, chrisberkhout commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/agent/stream/antibot.yml.hbs
Beautiful!

2024-10-15 13:40 UTC, chrisberkhout commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/agent/stream/antibot.yml.hbs
> +            }
I see it down in the 2nd half. It can also be done in lines [71-89](https://github.com/elastic/integrations/blob/0cd4bb1ba47500bfafa2e7206ad38d26d4aa0916/packages/checkpoint_harmony_endpoint/data_stream/antibot/agent/stream/cel.yml.hbs#L71-L89) and [92-115](https://github.com/elastic/integrations/blob/0cd4bb1ba47500bfafa2e7206ad38d26d4aa0916/packages/checkpoint_harmony_endpoint/data_stream/antibot/agent/stream/cel.yml.hbs#L92-L115).

2024-10-15 13:44 UTC, chrisberkhout commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/agent/stream/antibot.yml.hbs
> +interval: {{interval}}
These don't need to be wrapped in a condition and have an associated variable. They can just be hard-coded settings in the input config, like this (but for all data streams):

```diff
diff --git a/packages/checkpoint_harmony_endpoint/data_stream/antibot/agent/stream/cel.yml.hbs b/packages/checkpoint_harmony_endpoint/data_stream/antibot/agent/stream/cel.yml.hbs
index 7cca27649b..063f9a75dc 100644
--- a/packages/checkpoint_harmony_endpoint/data_stream/antibot/agent/stream/cel.yml.hbs
+++ b/packages/checkpoint_harmony_endpoint/data_stream/antibot/agent/stream/cel.yml.hbs
@@ -1,10 +1,6 @@
 config_version: 3
-{{#if resource_rate_limit_limit}}
 resource.rate_limit.limit: 0.2
-{{/if}}
-{{#if resource_rate_limit_burst}}
 resource.rate_limit.burst: 5
-{{/if}}
 {{#if enable_request_tracer}}
 resource.tracer.filename: "../../logs/cel/http-request-trace-*.ndjson"
 resource.tracer.maxbackups: 5
diff --git a/packages/checkpoint_harmony_endpoint/data_stream/antibot/manifest.yml b/packages/checkpoint_harmony_endpoint/data_stream/antibot/manifest.yml
index bc5c0b2a30..acadb782b6 100644
--- a/packages/checkpoint_harmony_endpoint/data_stream/antibot/manifest.yml
+++ b/packages/checkpoint_harmony_endpoint/data_stream/antibot/manifest.yml
@@ -27,20 +27,6 @@ streams:
         multi: false
         required: false
         show_user: false
-      - name: resource_rate_limit_limit
-        type: text
-        title: Resource Rate Limit
-        description: The value of the response that specifies the total limit.
-        show_user: false
-        multi: false
-        required: false
-      - name: resource_rate_limit_burst
-        type: text
-        title: Resource Rate Limit Burst
-        description: The maximum burst size. Burst is the maximum number of resource requests that can be made above the overall rate limit.
-        show_user: false
-        multi: false
-        required: false
       - name: preserve_original_event
         type: bool
         title: Preserve original event
```

2024-10-15 13:50 UTC, chrisberkhout commented on packages/checkpoint_harmony_endpoint/data_stream/threatemulation/agent/stream/threatemulation.yml.hbs
> +          "filter": "product:\"Threat Emulation\" AND NOT event_type:\"TE Info Event\"",
Thanks for the info. I see what you mean.

Please do add it as well though, by adjusting the filter and adding a pipeline test case for it.

2024-10-15 13:55 UTC, chrisberkhout commented on packages/checkpoint_harmony_endpoint/docs/README.md
> +7. **Zero-phishing:** Examines various website characteristics to ensure a site isn't impersonating another to maliciously collect personal information. It generates alerts for potential phishing sit
Thanks!

2024-10-15 14:00 UTC, chrisberkhout commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/sample_event.json
> +}
Thanks. I see this in the pipeline logic.

Please regenerate the `sample_events.json` files (`elastic-package test system -v --generate`) so that we see related fields there.

2024-10-15 14:25 UTC, chrisberkhout commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/elasticsearch/ingest_pipeline/default.yml
> +      field: ['checkpoint_harmony_endpoint.antibot.product_family', 'checkpoint_harmony_endpoint.antibot.file_name', 'checkpoint_harmony_endpoint.antibot.malware_action','checkpoint_harmony_endpoint.
In other pipelines too...

A list like this can be formatted more nicely in YAML:
```yaml
- remove:
    field:
      - checkpoint_harmony_endpoint.antibot.product_family
      - checkpoint_harmony_endpoint.antibot.file_name
      - checkpoint_harmony_endpoint.antibot.malware_action
      - checkpoint_harmony_endpoint.antibot.orig
      - checkpoint_harmony_endpoint.antibot.client_version
      - checkpoint_harmony_endpoint.antibot.os_version
      - checkpoint_harmony_endpoint.antibot.os_name
      - checkpoint_harmony_endpoint.antibot.time
      - checkpoint_harmony_endpoint.antibot.src
```

2024-10-15 14:25 UTC, chrisberkhout commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/agent/stream/antibot.yml.hbs
> +{{/if}}
Please add it once to the top-level _integration_ manifest, then it can be removed from each of the data stream manifests.

2024-10-15 15:02 UTC, chrisberkhout commented on packages/checkpoint_harmony_endpoint/kibana/dashboard/checkpoint_harmony_endpoint-21fdef7e-31b1-4eda-8842-3a100dc33851.json
Is this export error still an issue?

I see two dashboards there now and I was able to export both without seeing that error. I assume that "Check Point Harmony Endpoint Overview" will be kept and the older "Check Point Harmony Endpoint Dashboard" one will be removed. Is that right?

For "Check Point Harmony Endpoint Overview", I can see there is no global filter and there are filters are set on each panel, except for "Top entries by Destination Country". **A filter should be added there.**

(There's also no filter for "Table of Contents" markdown panel, but that's fine.)

The filter/query set in each panel is: `*.client.name:("Check Point Endpoint Security Client")`
**I think it would be better to use: `event.module: checkpoint_harmony_endpoint`**

It'll look like this in edit mode (note Filters vs Query):
![image](https://github.com/user-attachments/assets/ec7fdbc0-d795-4529-83fe-f2dbebab32ad)

When editing a panel's filters do it like this:
![Screenshot From 2024-10-15 16-58-10](https://github.com/user-attachments/assets/7aa1cd1f-f911-43f9-8358-247714173140)

2024-10-15 15:04 UTC, chrisberkhout commented
> > ❌ Author of the following commits did not sign a [Contributor Agreement](https://www.elastic.co/contributor-agreement): [f943064](https://github.com/elastic/integrations/commit/f943064e707f16f4533be4f46742ac24c4b77431), [2081cfd](https://github.com/elastic/integrations/commit/2081cfd4ee577336c2f8e53932a05f683244835b), [c7d0b6a](https://github.com/elastic/integrations/commit/c7d0b6aa1eaf80c6e7cca3e304abe307980265fb), [1b1fddd](https://github.com/elastic/integrations/commit/1b1fdddc3eaf113c7b890d1a03c086f30cca8777), [85f04eb](https://github.com/elastic/integrations/commit/85f04ebc38e8b43f527600a500b9bc877590e256), [2740521](https://github.com/elastic/integrations/commit/2740521c417473786d9a142cb019345554bb2f8b), [346f9a0](https://github.com/elastic/integrations/commit/346f9a02ccabdc01c2c087267cfa7cec52620c64), [2ef5cea](https://github.com/elastic/integrations/commit/2ef5cea702fc5666f4548eaa13f425aa48551e93), [a84d705](https://github.com/elastic/integrations/commit/a84d705963febaa5ba8f37b5d53ff47010feb9ee), [de5f43a](https://github.com/elastic/integrations/commit/de5f43af9a5fd8625a6def275c5ccf264da26a6d), [b2565e3](https://github.com/elastic/integrations/commit/b2565e3873b2d5696b50e34422a02aed17049e4a), [b4c0ec1](https://github.com/elastic/integrations/commit/b4c0ec1fa8c14ae76e4846cfe835824d46b48069), [3db6cc6](https://github.com/elastic/integrations/commit/3db6cc697392590a653c2db895e9baebc4da7e58)
> > Please, read and sign the above mentioned agreement if you want to contribute to this project
> 
> Please do this so we're able to merge when ready.

@aniket-phapale Please use the link in there to sign the CLA.

2024-10-15 15:04 UTC, elasticmachine commented
Pinging @elastic/security-service-integrations (Team:Security-Service Integrations)

2024-10-15 15:18 UTC, chrisberkhout commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/agent/stream/antibot.yml.hbs
> +          "want_more": true,
Thanks for the feedback. Looking at the related code in the CEL input I think this may not be the right approach after all. I will raise it with my teammates and let you know what we figure out. In the mean time it's okay to leave it as returning an empty list of events.

2024-10-15 15:25 UTC, chrisberkhout commented on packages/checkpoint_harmony_endpoint/kibana/dashboard/checkpoint_harmony_endpoint-21fdef7e-31b1-4eda-8842-3a100dc33851.json
Also, please name the dashboard:

```
[Logs Check Point Harmony Endpoint] Overview
```

2024-10-15 15:26 UTC, chrisberkhout requested changes
A good step forward!

Some existing points unresolved, a couple of small new ones.

2024-10-15 15:39 UTC, chrisberkhout commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/agent/stream/antibot.yml.hbs
> +          "want_more": true,
It turns out I misunderstood the approach. This is what we want to do:

Return this (note that it's an array now):
```
    "events": [{ "event": { "reason": "polling" }}]
```

Then in each ingest pipeline, after parsing the json, drop those events:
```diff
diff --git a/packages/checkpoint_harmony_endpoint/data_stream/antibot/elasticsearch/ingest_pipeline/default.yml b/packages/checkpoint_harmony_endpoint/data_stream/antibot/elasticsearch/ingest_pipeline/default.yml
index 595840220b..1e73520c07 100644
--- a/packages/checkpoint_harmony_endpoint/data_stream/antibot/elasticsearch/ingest_pipeline/default.yml
+++ b/packages/checkpoint_harmony_endpoint/data_stream/antibot/elasticsearch/ingest_pipeline/default.yml
@@ -34,6 +34,8 @@ processors:
   - json:
       field: event.original
       target_field: json
+  - drop:
+      if: ctx.json?.event?.reason == 'polling'
   - rename:
       field: json.id
       target_field: event.id
```

2024-10-16 06:06 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/kibana/dashboard/checkpoint_harmony_endpoint-21fdef7e-31b1-4eda-8842-3a100dc33851.json
fixed

2024-10-16 06:06 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/agent/stream/antibot.yml.hbs
> +{{/if}}
fixed

2024-10-16 06:06 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/agent/stream/antibot.yml.hbs
> +interval: {{interval}}
fixed

2024-10-16 06:07 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/docs/README.md
> +
fixed

2024-10-16 06:08 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/docs/README.md
> +Refer to Check Point's Infinity API Guide to create an API key: https://app.swaggerhub.com/apis-docs/Check-Point/infinity-events-api/1.0.0#/Authentication/getAuthToken
fixed

2024-10-16 06:08 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/manifest.yml
> +    type: image/png
fixed

2024-10-16 06:08 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/img/sample-screenshot.png
fixed

2024-10-16 06:08 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/img/sample-logo.svg
fixed

2024-10-16 08:28 UTC, gitanjali-panhale commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/manifest.yml
> +          - forwarded
fixed.

2024-10-16 08:29 UTC, gitanjali-panhale commented on packages/checkpoint_harmony_endpoint/_dev/deploy/docker/files/config.yml
> +          ],"recordsCount":1,"nextPageToken":"NULL"}}
fixed.

2024-10-16 08:30 UTC, gitanjali-panhale commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/elasticsearch/ingest_pipeline/default.yml
> +      field: ['checkpoint_harmony_endpoint.antibot.product_family', 'checkpoint_harmony_endpoint.antibot.file_name', 'checkpoint_harmony_endpoint.antibot.malware_action','checkpoint_harmony_endpoint.
fixed.

2024-10-16 12:37 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/agent/stream/antibot.yml.hbs
> +  page_limit: {{page_limit}}
fixed

2024-10-16 12:39 UTC, gitanjali-panhale commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/agent/stream/antibot.yml.hbs
Done!

2024-10-16 12:40 UTC, gitanjali-panhale commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/agent/stream/antibot.yml.hbs
> +            }
Done.

2024-10-16 12:40 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/data_stream/threatemulation/agent/stream/threatemulation.yml.hbs
> +          "filter": "product:\"Threat Emulation\" AND NOT event_type:\"TE Info Event\"",
fixed

2024-10-16 12:44 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/sample_event.json
> +}
fixed

2024-10-17 06:55 UTC, efd6 commented
@gauravneelwarna This PR cannot be reviewed until the CLA has been signed. From the list of commits shown by the CLA bot, there is a user called aniket-phapale. If this is you, please ensure that you have signed the CLA for that user as well. If it is not, please remove those commit from the change.

2024-10-17 07:17 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/agent/stream/antibot.yml.hbs
> +          "want_more": true,
@chrisberkhout 
We tried with the `[{ "event": { "reason": "polling" }}]` and got an error
```
Processor "json" with tag "" in pipeline "logs-checkpoint_harmony_endpoint.antibot-0.1.0" failed with message "field [original] not present as part of path [event.original]"
 ```
 After reviewing some docker logs we noticed that the events starts with `message` so updated the sample event as :
  `{ "message": { "reason": "polling" }}` and
```
  - drop:
      if: ctx.json?.message?.reason == 'polling'
```
 After adding above event and field mappings the logs were visible on UI but the terminal was failing with an error: 
 ```
DEBUG Error found in failure store: org.elasticsearch.index.mapper.DocumentParsingException: [1:564] failed to parse field [event.original] of type [keyword] in document with id 'gG04mZIBMZ1eIE_-p6ie'. Preview of field's value: '{reason=polling}'
```

Please look into this and suggest the next action.
Thanks.!

2024-10-17 07:28 UTC, chrisberkhout commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/agent/stream/antibot.yml.hbs
> +          "want_more": true,
Oh, that's right. The pipeline doesn't expect raw events, it expects:
```json
{ "message": "<JSON-encoded-event>" }
```
So the CEL can return it like this:
```
"events": [{ "message": { "event": { "reason": "polling" }}.encode_json() }]
```
And then in the pipeline it's still:
```yaml
  - drop:
      if: ctx.json?.event?.reason == 'polling'
```

2024-10-17 08:34 UTC, gauravneelwarna commented
> @gauravneelwarna This PR cannot be reviewed until the CLA has been signed. From the list of commits shown by the CLA bot, there is a user called aniket-phapale. If this is you, please ensure that you have signed the CLA for that user as well. If it is not, please remove those commit from the change.

@efd6 aniket-phapale and other 2 users signed CLA. Please confirm and let me know if you need copies of the individual agreements.

2024-10-17 08:54 UTC, gauravneelwarna commented
> @gauravneelwarna Did they sign via https://www.elastic.co/contributor-agreement?
> 
> We want to get this check to pass:
> 
> ![Screenshot From 2024-10-17 10-51-09](https://private-user-images.githubusercontent.com/124641/377389092-e41da08e-187d-41d9-a568-41a49483d3cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNTU1NDIsIm5iZiI6MTcyOTE1NTI0MiwicGF0aCI6Ii8xMjQ2NDEvMzc3Mzg5MDkyLWU0MWRhMDhlLTE4N2QtNDFkOS1hNTY4LTQxYTQ5NDgzZDNjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QwODU0MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MWQ1NjAzZGM1YzMwNDNlNDEyZGUyNTU0ZDFhNTExM2Y0NDkwOTZjMTJkYzdmNzY0NWMxYmFkYWZiMmI0MzA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.O7QQdYsA_SsE-B6OTaFiY77paOdMmz2CIfthAQvfiYQ)

yes

2024-10-17 08:57 UTC, chrisberkhout commented
/test

2024-10-17 09:00 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17283)
* Commit: 89eb0177b4a771bf93eb88ff1ce8bb1358a64c43

### Failed CI Steps
* [:white_check_mark: Check go sources](https://buildkite.com/elastic/integrations/builds/17283#019299b3-1749-4f06-9017-819686296d14)

cc @gauravneelwarna

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17283","number":17283,"commit":"89eb0177b4a771bf93eb88ff1ce8bb1358a64c43"}],"number":17283}
buildkite-pr-comment-->

2024-10-17 09:36 UTC, aniket-phapale commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/agent/stream/antibot.yml.hbs
> +          "want_more": true,
fixed

2024-10-17 10:35 UTC, gauravneelwarna commented
/test

2024-10-23 16:18 UTC, chrisberkhout commented on packages/checkpoint_harmony_endpoint/img/sample-logo.svg
No, it's still there.

2024-10-23 16:19 UTC, chrisberkhout commented on packages/checkpoint_harmony_endpoint/img/sample-logo.svg
It is removed from the manifest, but the file is still there in the `img/` directory.

2024-10-23 16:21 UTC, chrisberkhout commented on packages/checkpoint_harmony_endpoint/img/sample-screenshot.png
yes, this one has been removed.

2024-10-23 16:31 UTC, chrisberkhout commented on packages/checkpoint_harmony_endpoint/manifest.yml
> +    title: Sample logo
```suggestion
    title: Check Point logo
```

2024-10-23 16:31 UTC, chrisberkhout commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/manifest.yml
> +          - forwarded
The diff above suggested to remove `preserve_original_event` and add `forwarded`, but `preserve_original_event` is still there. Please remove that also.

2024-10-23 16:31 UTC, chrisberkhout commented on packages/checkpoint_harmony_endpoint/data_stream/antibot/agent/stream/antibot.yml.hbs
> +{{/if}}
The definition of `enable_request_tracer` in the top level manifest still needs to have a `default: false` setting added.

2024-10-23 17:12 UTC, chrisberkhout commented
/test

2024-10-23 17:58 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17509)
* Commit: c8efd047a3fff623b23d15fbd06b2b7352d9503f

### Failed CI Steps
* [Check integrations checkpoint_harmony_endpoint](https://buildkite.com/elastic/integrations/builds/17509#0192ba7c-564f-42e9-9cdb-d02cd9d4583d)

### History
* :broken_heart: [Build #17283](https://buildkite.com/elastic/integrations/builds/17283) failed 89eb0177b4a771bf93eb88ff1ce8bb1358a64c43

cc @gauravneelwarna

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17509","number":17509,"commit":"c8efd047a3fff623b23d15fbd06b2b7352d9503f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17283","number":17283,"commit":"89eb0177b4a771bf93eb88ff1ce8bb1358a64c43"}],"number":17509}
buildkite-pr-comment-->

2024-10-23 18:38 UTC, chrisberkhout commented on packages/checkpoint_harmony_endpoint/manifest.yml
> +    version: "^8.13.0"
The build is failing like this:
```
Error: can't install the package: could not zip-install package;
API status code = 422;
response body = {
  "statusCode": 422,
  "error": "Unprocessable Entity",
  "message": "Document \"checkpoint_harmony_endpoint-75b9a9f1-9671-4d51-a418-fed3fb5e274c\" belongs to a more recent version of Kibana [10.2.0] when the last known version is [8.9.0]."
}
```

because the dashboard was exported from a version of the Elastic stack that is later than the version set here  (`^8.13.0`). The easiest way to fix this is to raise this `conditions.kibana.version` setting to whatever version of the stack you are using for development.

2024-10-24 05:55 UTC, gitanjali-panhale commented on packages/checkpoint_harmony_endpoint/manifest.yml
> +    version: "^8.13.0"
Hi @chrisberkhout , We checked version from dev console and took that one i.e  "^8.15.1"
![image](https://github.com/user-attachments/assets/063d9873-393e-46a4-8d9a-587f18f85c40)
Please let us know is it correct or not.

2024-10-24 09:34 UTC, chrisberkhout commented on packages/checkpoint_harmony_endpoint/manifest.yml
> +    version: "^8.13.0"
Thanks. This is a correct version. 8.15.1 was released September 05, 2024.
I just checked version 8.14.0 and the dashboard imports correctly there too, so it would be good to set the `conditions.kibana.version` to `"^8.14.0"`, just so more users on slightly older versions can use it.

2024-10-25 07:32 UTC, chrisberkhout commented
/test

2024-10-25 07:41 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17565)
* Commit: f5ea746f998535dd9493fea2277b952929e7579b

### Failed CI Steps
* [Check integrations checkpoint_harmony_endpoint](https://buildkite.com/elastic/integrations/builds/17565#0192c29b-2a68-48c1-98c1-7dbd5bc721d5)

### History
* :broken_heart: [Build #17509](https://buildkite.com/elastic/integrations/builds/17509) failed c8efd047a3fff623b23d15fbd06b2b7352d9503f
* :broken_heart: [Build #17283](https://buildkite.com/elastic/integrations/builds/17283) failed 89eb0177b4a771bf93eb88ff1ce8bb1358a64c43

cc @gauravneelwarna

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17565","number":17565,"commit":"f5ea746f998535dd9493fea2277b952929e7579b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17509","number":17509,"commit":"c8efd047a3fff623b23d15fbd06b2b7352d9503f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17283","number":17283,"commit":"89eb0177b4a771bf93eb88ff1ce8bb1358a64c43"}],"number":17565}
buildkite-pr-comment-->

2024-10-25 08:39 UTC, chrisberkhout commented
/test

2024-10-25 09:05 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17568)
* Commit: 9c50ea541fb029bc854c847465e6b075a1bb254a

### History
* :broken_heart: [Build #17565](https://buildkite.com/elastic/integrations/builds/17565) failed f5ea746f998535dd9493fea2277b952929e7579b
* :broken_heart: [Build #17509](https://buildkite.com/elastic/integrations/builds/17509) failed c8efd047a3fff623b23d15fbd06b2b7352d9503f
* :broken_heart: [Build #17283](https://buildkite.com/elastic/integrations/builds/17283) failed 89eb0177b4a771bf93eb88ff1ce8bb1358a64c43

cc @gauravneelwarna

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17568","number":17568,"commit":"9c50ea541fb029bc854c847465e6b075a1bb254a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17565","number":17565,"commit":"f5ea746f998535dd9493fea2277b952929e7579b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17509","number":17509,"commit":"c8efd047a3fff623b23d15fbd06b2b7352d9503f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17283","number":17283,"commit":"89eb0177b4a771bf93eb88ff1ce8bb1358a64c43"}],"number":17568}
buildkite-pr-comment-->

2024-10-25 09:43 UTC, chrisberkhout approved these changes
All review points addressed. Thanks! It looks good.

2024-10-25 10:24 UTC, merged