Fix powershell error on events 40961 and 40962
elastic/integrations pull request #10792
Opened 2024-08-14 17:31 UTC by bjmcnic

## Proposed commit message

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## How to test this PR locally

## Related issues

- 

## Screenshots

2024-08-14 17:31 UTC, elasticmachine commented
Pinging @elastic/sec-windows-platform (Team:Security-Windows Platform)

2024-08-14 17:45 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14663)
* Commit: 6aac51ff5084f62e577153d059b9c12d42b284c8

### Failed CI Steps
* [Check integrations windows](https://buildkite.com/elastic/integrations/builds/14663#019151fa-1df9-4f6f-8925-b4968103c32c)

cc @bjmcnic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14663","number":14663,"commit":"6aac51ff5084f62e577153d059b9c12d42b284c8"}],"number":14663}
buildkite-pr-comment-->

2024-08-14 20:01 UTC, leehinman requested changes
missing changes to `manifest.yml` that match the change in `changelog.yml`

2024-08-14 20:01 UTC, leehinman commented on packages/windows/data_stream/powershell_operational/elasticsearch/ingest_pipeline/default.yml
> +      if: ctx?.winlog?.event_data != null
For sure we need to add this to:

forwarded/elasticsearch/ingest_pipeline/powershell_operational.yml

but it probably applies to:
- `powershell/elasticsearch/ingest_pipeline/default.yml`
- `sysmon_operational/elasticsearch/ingest_pipeline/default.yml`
- `forwarded/elasticsearch/ingest_pipeline/powershell.yml`
- `forwarded/elasticsearch/ingest_pipeline/sysmon_operational.yml`

Do you happen to have any sample events you could add to `powershell_operational/_dev/test/pipeline/test-events.json` ?  That way the tests will catch this if we break it in the future.

2024-09-09 13:28 UTC, jamiehynds commented
Hi @bjmcnic - a customer has been in touch looking for an update on this PR. Their main focus is 40961 and 40962 event support within the `powershell_operational` pipeline? Is it possible to prioritise that pipeline first, and handle the forwarded events (and other) pipelines separately?

2024-09-10 00:15 UTC, bjmcnic commented on packages/windows/data_stream/powershell_operational/elasticsearch/ingest_pipeline/default.yml
> +      if: ctx?.winlog?.event_data != null
@leehinman Thanks for the tips.  I was able to find sample events for `powershell_operational` and added them to tests.  I also made the analogous fix `powershell` and `sysmon_operational` as you'd suggested, but was unable to create real events that would trigger the issue for those.

2024-09-10 00:20 UTC, bjmcnic commented
@jamiehynds I added the tests for `powershell_operational` and the forwarded events for that.  I was unable to naturally generate erring events for `powershell` or `sysmon_operational`, but I put the fixes in anyway.  We'll see what reviewers think.

2024-09-10 00:40 UTC, elasticmachine commented
### :rocket: Benchmarks report


#### Package `windows` :&#43;1:(4) :green_heart:(2) :broken_heart:(3)
<details>
<summary>Expand to view</summary>

Data stream | Previous EPS | New EPS | Diff (%) | Result
----------- | ------------ | ------- | -------- | ------
`applocker_msi_and_script` | 9433.96 | 7462.69 | -1971.27 (-20.9%) | :broken_heart:
`applocker_packaged_app_deployment` | 14705.88 | 11904.76 | -2801.12 (-19.05%) | :broken_heart:
`powershell_operational` | 4347.83 | 2976.19 | -1371.64 (-31.55%) | :broken_heart:
</details>


To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-09-10 13:57 UTC, leehinman approved these changes
LGTM. Thanks for adding the test cases.

2024-09-12 08:14 UTC, marc-gr approved these changes

2024-09-12 12:59 UTC, merged

2024-09-12 13:16 UTC, elasticmachine commented
Package windows - 2.0.2 containing this change is available at https://epr.elastic.co/search?package=windows

2024-10-08 17:04 UTC, maggieghamry commented
Just as a head's up, it appears there may be a bug (confirmed in `2.1.0` but all Powershell event dashboards are now empty) after installation