WIP: Initial Release of Sysdig Secure Integration
elastic/integrations pull request #10841
Opened 2024-08-21 11:57 UTC by cole-labar

## What does this PR do?

This is an initial release of a new integration for [Sysdig Secure](https://docs.sysdig.com/en/docs/sysdig-secure/). It captures events that are created by Sysdig's Rules. It includes:

A data stream for events from Sysdig rules.
Ingest pipeline for events data stream
Mapped fields according to the ECS schema and added Fields metadata in the appropriate yml files
Dashboard and visualizations of events. (WIP)
Test for pipeline for event data stream.
System test cases for event data stream.
Documentation for users on how to configure Sysdig for this integration.

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## What's Ready to Review

- [X] Data Stream & Mappings
- [X] Ingest Pipelines
- [X] Pipeline Tests
- [ ] System (Integration) Tests
- [ ] Visualizations
- [ ] Documentation

## How to test this PR locally

WIP

## Related issues

- References [Sysdig Secure](https://github.com/elastic/integrations/issues/9564)

## Screenshots

WIP

2024-08-22 20:52 UTC, andrewkroh commented
/test

2024-08-22 21:09 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-08-22 21:10 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/14932)
* Commit: 92f801f6163338d2ec8758fa91bc30e6cf1aadd0

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14932","number":14932,"commit":"92f801f6163338d2ec8758fa91bc30e6cf1aadd0"}],"number":14932}
buildkite-pr-comment-->

2024-08-27 19:10 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15089)
* Commit: a8efbf5d56812b1392d8324321b90e88cea788ce

### History
* :green_heart: [Build #14932](https://buildkite.com/elastic/integrations/builds/14932) succeeded 92f801f6163338d2ec8758fa91bc30e6cf1aadd0

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15089","number":15089,"commit":"a8efbf5d56812b1392d8324321b90e88cea788ce"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14932","number":14932,"commit":"92f801f6163338d2ec8758fa91bc30e6cf1aadd0"}],"number":15089}
buildkite-pr-comment-->

2024-09-02 08:05 UTC, chemamartinez requested changes

2024-09-02 08:05 UTC, chemamartinez commented on packages/sysdig/data_stream/alerts/elasticsearch/ingest_pipeline/default.yml
> +- script:
Please review this script and the set of cloud fields in general, for some reason, cloud fields are not properly merged:
```
"cloud": {
    "account": {
        "id": "289645096542"
    },
    "availability_zone": "us-central1-c",
    "project": {
        "id": "289645096542",
        "name": "alliances-chronicle"
    },
    "provider": "gcp",
    "region": "us-central1"
},
"cloud.instance.id": "648229130641697246",
"cloud.instance.name": "gke-cluster-gcp-demo-san-default-pool-66250c41-vd1o",
"cloud.machine.type": "e2-standard-4",
```

2024-09-03 18:15 UTC, cole-labar commented on packages/sysdig/validation.yml
> +errors:
Done!

2024-09-03 18:16 UTC, cole-labar commented on packages/sysdig/kibana/dashboard/sysdig-1b3c9930-f0c2-46c8-9bce-47738b8bfa33.json
Updated! Controls have been added, Hide zero values has been disabled on the Alerts over Time, and Events have been renamed to Alerts to match the integrations focus

2024-09-03 18:16 UTC, cole-labar commented on packages/sysdig/_dev/build/docs/README.md
> +The Sysdig integration collects one type of data stream: logs.
Updated

2024-09-03 18:17 UTC, cole-labar commented on packages/sysdig/_dev/build/docs/README.md
> +```json
Updated

2024-09-03 18:17 UTC, cole-labar commented on packages/sysdig/changelog.yml
> +    - description: Initial draft of the Sysdig integration
Updated

2024-09-03 18:18 UTC, cole-labar commented on packages/sysdig/data_stream/alerts/manifest.yml
> +      - name: pipeline
Updated to remove this

2024-09-03 18:19 UTC, cole-labar commented on packages/sysdig/_dev/build/docs/README.md
> +**Logs** The Logs data stream collected by the Sysdig integration is comprised of Sysdig Alerts. See more details about Sysdig Alerts in [Sysdig's Alerts Documentation](https://docs.sysdig.com/en/doc
Updated!

2024-09-03 18:19 UTC, cole-labar commented on packages/sysdig/data_stream/alerts/manifest.yml
> +      - name: method
Removed!

2024-09-03 18:19 UTC, cole-labar commented on packages/sysdig/data_stream/alerts/agent/stream/http.yml.hbs
> +  - preserve_duplicate_custom_fields
Updated

2024-09-03 18:19 UTC, cole-labar commented on packages/sysdig/data_stream/alerts/agent/stream/http.yml.hbs
> +  - preserve_original_event
Updated

2024-09-03 18:20 UTC, cole-labar commented on packages/sysdig/data_stream/alerts/manifest.yml
> +          - forwarded
Done!

2024-09-03 18:20 UTC, cole-labar commented on packages/sysdig/data_stream/alerts/manifest.yml
> +      - name: data_stream.dataset
Updated

2024-09-03 18:22 UTC, cole-labar commented on packages/sysdig/data_stream/alerts/elasticsearch/ingest_pipeline/default.yml
> +- set:
Not 100% sure why they were split out, but I do agree that nesting them under an `event` field would be better. I'll take care of that.

2024-09-03 18:36 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15410)
* Commit: 03ab01186533ec04a4cc158aa97d4fd40c1b3c35

### History
* :green_heart: [Build #15089](https://buildkite.com/elastic/integrations/builds/15089) succeeded a8efbf5d56812b1392d8324321b90e88cea788ce
* :green_heart: [Build #14932](https://buildkite.com/elastic/integrations/builds/14932) succeeded 92f801f6163338d2ec8758fa91bc30e6cf1aadd0

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15410","number":15410,"commit":"03ab01186533ec04a4cc158aa97d4fd40c1b3c35"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15089","number":15089,"commit":"a8efbf5d56812b1392d8324321b90e88cea788ce"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14932","number":14932,"commit":"92f801f6163338d2ec8758fa91bc30e6cf1aadd0"}],"number":15410}
buildkite-pr-comment-->

2024-09-04 08:23 UTC, elasticmachine commented
Pinging @elastic/security-service-integrations (Team:Security-Service Integrations)

2024-09-04 13:55 UTC, cole-labar commented on packages/sysdig/data_stream/alerts/elasticsearch/ingest_pipeline/default.yml
> +- script:
Updated! These should be nesting appropriately now

2024-09-04 13:55 UTC, cole-labar commented on packages/sysdig/data_stream/alerts/elasticsearch/ingest_pipeline/default.yml
> +- set:
Updated

2024-09-04 14:13 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15462)
* Commit: 99cebae11acbea2d7b247b8c1e77d5d22722800f

### History
* :green_heart: [Build #15410](https://buildkite.com/elastic/integrations/builds/15410) succeeded 03ab01186533ec04a4cc158aa97d4fd40c1b3c35
* :green_heart: [Build #15089](https://buildkite.com/elastic/integrations/builds/15089) succeeded a8efbf5d56812b1392d8324321b90e88cea788ce
* :green_heart: [Build #14932](https://buildkite.com/elastic/integrations/builds/14932) succeeded 92f801f6163338d2ec8758fa91bc30e6cf1aadd0

cc @chemamartinez

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15462","number":15462,"commit":"99cebae11acbea2d7b247b8c1e77d5d22722800f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15410","number":15410,"commit":"03ab01186533ec04a4cc158aa97d4fd40c1b3c35"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15089","number":15089,"commit":"a8efbf5d56812b1392d8324321b90e88cea788ce"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14932","number":14932,"commit":"92f801f6163338d2ec8758fa91bc30e6cf1aadd0"}],"number":15462}
buildkite-pr-comment-->

2024-09-04 20:48 UTC, cole-labar commented on packages/sysdig/data_stream/alerts/manifest.yml
> +      - name: prefix
Alright, I think I've pulled out the non-essential ones and left the ones that are referenced in the documentation. The `.hbs` file has also been updated.

2024-09-04 21:05 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15482)
* Commit: 91f25427b03834e1e9d9b7328e053929cd7e9370

### History
* :green_heart: [Build #15462](https://buildkite.com/elastic/integrations/builds/15462) succeeded 99cebae11acbea2d7b247b8c1e77d5d22722800f
* :green_heart: [Build #15410](https://buildkite.com/elastic/integrations/builds/15410) succeeded 03ab01186533ec04a4cc158aa97d4fd40c1b3c35
* :green_heart: [Build #15089](https://buildkite.com/elastic/integrations/builds/15089) succeeded a8efbf5d56812b1392d8324321b90e88cea788ce
* :green_heart: [Build #14932](https://buildkite.com/elastic/integrations/builds/14932) succeeded 92f801f6163338d2ec8758fa91bc30e6cf1aadd0

cc @chemamartinez

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15482","number":15482,"commit":"91f25427b03834e1e9d9b7328e053929cd7e9370"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15462","number":15462,"commit":"99cebae11acbea2d7b247b8c1e77d5d22722800f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15410","number":15410,"commit":"03ab01186533ec04a4cc158aa97d4fd40c1b3c35"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15089","number":15089,"commit":"a8efbf5d56812b1392d8324321b90e88cea788ce"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14932","number":14932,"commit":"92f801f6163338d2ec8758fa91bc30e6cf1aadd0"}],"number":15482}
buildkite-pr-comment-->

2024-09-11 06:45 UTC, chemamartinez commented on packages/sysdig/data_stream/alerts/agent/stream/http.yml.hbs
> +  - preserve_duplicate_custom_fields
The option is still in the manifest. Please remove it from there as well.

2024-09-11 06:51 UTC, chemamartinez commented on packages/sysdig/data_stream/alerts/elasticsearch/ingest_pipeline/default.yml
> +- set:
`SysdigEvent` is still defined in fields.yml.

2024-09-11 07:16 UTC, chemamartinez commented on packages/sysdig/data_stream/alerts/fields/fields.yml
> +- name: host.name
From this one down they look like ECS fields, so they don't need to be defined here.

2024-09-11 07:16 UTC, chemamartinez commented on packages/sysdig/data_stream/alerts/_dev/test/system/test-default-config.yml
> +    dataset: 'sysdig.alerts'
`dataset` and `namespace` are no longer data stream options. You can remove them from here.

2024-09-11 07:16 UTC, chemamartinez commented on packages/sysdig/data_stream/alerts/elasticsearch/ingest_pipeline/default.yml
> +    if: ctx?.message != null
```suggestion
    if: ctx.message != null
```

`ctx` is assumed that always exist, so can you replace every `ctx?` by just `ctx`?

2024-09-11 07:16 UTC, chemamartinez commented on packages/sysdig/data_stream/alerts/elasticsearch/ingest_pipeline/default.yml
> +    if: ctx?.sysdig?.labels?.kubernetes?.cluster?.name != null || ctx?.sysdig?.labels?.kubernetes?.namespace?.name != null || ctx?.sysdig?.labels?.kubernetes?.pod?.name != null || ctx?.sysdig?.labels
Easier to read:
```suggestion
if: >-
  ctx?.sysdig?.labels?.kubernetes?.cluster?.name != null ||
  ctx?.sysdig?.labels?.kubernetes?.namespace?.name != null ||
  ctx?.sysdig?.labels?.kubernetes?.pod?.name != null ||
  ctx?.sysdig?.labels?.kubernetes?.workload?.type != null
```

2024-09-11 07:24 UTC, chemamartinez commented on packages/sysdig/data_stream/alerts/manifest.yml
> +      - name: prefix
I think the following options are still missing in the `http.yml.hbs` file but present in the manifest:
- url (needed)
- basic_auth
- username
- password
- hmac_header
- hmac_key
- hmac_prefix
- response_code
- response_body
- include_headers

I'd say most of them are not needed for our use case. The documentation is generic for the HTTP endpoint input, but we need to adjust to the Sysdig specifications when working with HTTP webhooks.

2024-09-11 13:30 UTC, cole-labar commented on packages/sysdig/data_stream/alerts/agent/stream/http.yml.hbs
> +  - preserve_duplicate_custom_fields
Removed

2024-09-11 13:30 UTC, cole-labar commented on packages/sysdig/data_stream/alerts/agent/stream/http.yml.hbs
> +  - preserve_original_event
Done!

2024-09-11 13:30 UTC, cole-labar commented on packages/sysdig/data_stream/alerts/elasticsearch/ingest_pipeline/default.yml
> +- set:
I pulled them out now

2024-09-11 13:30 UTC, cole-labar commented on packages/sysdig/data_stream/alerts/manifest.yml
> +          enabled: false
Done!

2024-09-11 13:31 UTC, cole-labar commented on packages/sysdig/data_stream/alerts/_dev/test/system/test-default-config.yml
> +    dataset: 'sysdig.alerts'
Updated

2024-09-11 13:31 UTC, cole-labar commented on packages/sysdig/data_stream/alerts/elasticsearch/ingest_pipeline/default.yml
> +    if: ctx?.message != null
Makes sense to me - updated

2024-09-11 13:31 UTC, cole-labar commented on packages/sysdig/data_stream/alerts/elasticsearch/ingest_pipeline/default.yml
> +    if: ctx?.sysdig?.labels?.kubernetes?.cluster?.name != null || ctx?.sysdig?.labels?.kubernetes?.namespace?.name != null || ctx?.sysdig?.labels?.kubernetes?.pod?.name != null || ctx?.sysdig?.labels
Thanks for this! Updated

2024-09-11 13:48 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15764)
* Commit: b2740c9d37d3517f8561cce5c8059ae2a52add49

### History
* :green_heart: [Build #15482](https://buildkite.com/elastic/integrations/builds/15482) succeeded 91f25427b03834e1e9d9b7328e053929cd7e9370
* :green_heart: [Build #15462](https://buildkite.com/elastic/integrations/builds/15462) succeeded 99cebae11acbea2d7b247b8c1e77d5d22722800f
* :green_heart: [Build #15410](https://buildkite.com/elastic/integrations/builds/15410) succeeded 03ab01186533ec04a4cc158aa97d4fd40c1b3c35
* :green_heart: [Build #15089](https://buildkite.com/elastic/integrations/builds/15089) succeeded a8efbf5d56812b1392d8324321b90e88cea788ce
* :green_heart: [Build #14932](https://buildkite.com/elastic/integrations/builds/14932) succeeded 92f801f6163338d2ec8758fa91bc30e6cf1aadd0

cc @chemamartinez

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15764","number":15764,"commit":"b2740c9d37d3517f8561cce5c8059ae2a52add49"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15482","number":15482,"commit":"91f25427b03834e1e9d9b7328e053929cd7e9370"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15462","number":15462,"commit":"99cebae11acbea2d7b247b8c1e77d5d22722800f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15410","number":15410,"commit":"03ab01186533ec04a4cc158aa97d4fd40c1b3c35"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15089","number":15089,"commit":"a8efbf5d56812b1392d8324321b90e88cea788ce"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/14932","number":14932,"commit":"92f801f6163338d2ec8758fa91bc30e6cf1aadd0"}],"number":15764}
buildkite-pr-comment-->

2024-09-11 20:02 UTC, cole-labar commented on packages/sysdig/data_stream/alerts/manifest.yml
> +      - name: prefix
This should now be updated to include only the relevant configs now

2024-09-12 09:10 UTC, chemamartinez commented on packages/sysdig/data_stream/alerts/manifest.yml
> +      - name: prefix
I still think following changes are needed for consistency:
**manifest.yml**
- Remove basic_auth
- Remove username
- Remove password
- Add secret header
- Add secret value

**http.yml.hbs**
- Add URL

2024-09-12 13:29 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15833)
* Commit: d0d1301df04addb98ce26028b92dac3577f03972

### Failed CI Steps
* [Check integrations sysdig](https://buildkite.com/elastic/integrations/builds/15833#0191e664-aa6a-474a-b5ca-22a67377107e)

### History
* :green_heart: [Build #15781](https://buildkite.com/elastic/integrations/builds/15781) succeeded e30cb53a9a383142bc973ad19970d04893043bb6
* :green_heart: [Build #15764](https://buildkite.com/elastic/integrations/builds/15764) succeeded b2740c9d37d3517f8561cce5c8059ae2a52add49
* :green_heart: [Build #15482](https://buildkite.com/elastic/integrations/builds/15482) succeeded 91f25427b03834e1e9d9b7328e053929cd7e9370
* :green_heart: [Build #15462](https://buildkite.com/elastic/integrations/builds/15462) succeeded 99cebae11acbea2d7b247b8c1e77d5d22722800f
* :green_heart: [Build #15410](https://buildkite.com/elastic/integrations/builds/15410) succeeded 03ab01186533ec04a4cc158aa97d4fd40c1b3c35
* :green_heart: [Build #15089](https://buildkite.com/elastic/integrations/builds/15089) succeeded a8efbf5d56812b1392d8324321b90e88cea788ce

cc @chemamartinez

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15833","number":15833,"commit":"d0d1301df04addb98ce26028b92dac3577f03972"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15781","number":15781,"commit":"e30cb53a9a383142bc973ad19970d04893043bb6"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15764","number":15764,"commit":"b2740c9d37d3517f8561cce5c8059ae2a52add49"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15482","number":15482,"commit":"91f25427b03834e1e9d9b7328e053929cd7e9370"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15462","number":15462,"commit":"99cebae11acbea2d7b247b8c1e77d5d22722800f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15410","number":15410,"commit":"03ab01186533ec04a4cc158aa97d4fd40c1b3c35"}],"number":15833}
buildkite-pr-comment-->

2024-09-12 13:48 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15835)
* Commit: 894efbebae2ff8574a90e4cb1c13063f8ecbf430

### History
* :broken_heart: [Build #15833](https://buildkite.com/elastic/integrations/builds/15833) failed d0d1301df04addb98ce26028b92dac3577f03972
* :green_heart: [Build #15781](https://buildkite.com/elastic/integrations/builds/15781) succeeded e30cb53a9a383142bc973ad19970d04893043bb6
* :green_heart: [Build #15764](https://buildkite.com/elastic/integrations/builds/15764) succeeded b2740c9d37d3517f8561cce5c8059ae2a52add49
* :green_heart: [Build #15482](https://buildkite.com/elastic/integrations/builds/15482) succeeded 91f25427b03834e1e9d9b7328e053929cd7e9370
* :green_heart: [Build #15462](https://buildkite.com/elastic/integrations/builds/15462) succeeded 99cebae11acbea2d7b247b8c1e77d5d22722800f
* :green_heart: [Build #15410](https://buildkite.com/elastic/integrations/builds/15410) succeeded 03ab01186533ec04a4cc158aa97d4fd40c1b3c35

cc @chemamartinez

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15835","number":15835,"commit":"894efbebae2ff8574a90e4cb1c13063f8ecbf430"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15833","number":15833,"commit":"d0d1301df04addb98ce26028b92dac3577f03972"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15781","number":15781,"commit":"e30cb53a9a383142bc973ad19970d04893043bb6"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15764","number":15764,"commit":"b2740c9d37d3517f8561cce5c8059ae2a52add49"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15482","number":15482,"commit":"91f25427b03834e1e9d9b7328e053929cd7e9370"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15462","number":15462,"commit":"99cebae11acbea2d7b247b8c1e77d5d22722800f"}],"number":15835}
buildkite-pr-comment-->

2024-09-13 15:08 UTC, chemamartinez reviewed
PR changes LGTM! Waiting for a manual test in a real scenario to approve it.

2024-09-17 14:03 UTC, cole-labar commented
> PR changes LGTM! Waiting for a manual test in a real scenario to approve it.

Integration was connected to a Sysdig event forwarder for "live environment" testing and data was successfully intercepted!

2024-09-17 14:28 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16015)
* Commit: 3715e3dc2cd8619231c83dc5a5da7d137b3a3c52

### History
* :green_heart: [Build #15835](https://buildkite.com/elastic/integrations/builds/15835) succeeded 894efbebae2ff8574a90e4cb1c13063f8ecbf430
* :broken_heart: [Build #15833](https://buildkite.com/elastic/integrations/builds/15833) failed d0d1301df04addb98ce26028b92dac3577f03972
* :green_heart: [Build #15781](https://buildkite.com/elastic/integrations/builds/15781) succeeded e30cb53a9a383142bc973ad19970d04893043bb6
* :green_heart: [Build #15764](https://buildkite.com/elastic/integrations/builds/15764) succeeded b2740c9d37d3517f8561cce5c8059ae2a52add49
* :green_heart: [Build #15482](https://buildkite.com/elastic/integrations/builds/15482) succeeded 91f25427b03834e1e9d9b7328e053929cd7e9370
* :green_heart: [Build #15462](https://buildkite.com/elastic/integrations/builds/15462) succeeded 99cebae11acbea2d7b247b8c1e77d5d22722800f

cc @chemamartinez

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16015","number":16015,"commit":"3715e3dc2cd8619231c83dc5a5da7d137b3a3c52"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15835","number":15835,"commit":"894efbebae2ff8574a90e4cb1c13063f8ecbf430"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15833","number":15833,"commit":"d0d1301df04addb98ce26028b92dac3577f03972"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15781","number":15781,"commit":"e30cb53a9a383142bc973ad19970d04893043bb6"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15764","number":15764,"commit":"b2740c9d37d3517f8561cce5c8059ae2a52add49"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15482","number":15482,"commit":"91f25427b03834e1e9d9b7328e053929cd7e9370"}],"number":16015}
buildkite-pr-comment-->

2024-09-17 14:55 UTC, chemamartinez approved these changes

2024-09-17 14:57 UTC, merged