zscaler_zia: Remove department field and add on_failure clauses in web
elastic/integrations pull request #10874
Opened 2024-08-26 05:01 UTC by kcreddy

## Proposed commit message
Remove department field and add on_failure clauses in web.

The `department` is already being ingested from `dept` field. Removing the 
`department` field in favour of `dept` due to noticed improper hex-encoding in 
fields prefixed with `e` [here](https://github.com/elastic/integrations/pull/10855#issue-2481310988). 
Also add `on_failure` clause on `urldecode` processors to continue execution 
when fields are derived from corresponding hex-encoded values.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## How to test this PR locally

## Related issues

- 

## Screenshots

2024-08-26 05:13 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15014)
* Commit: 59b861f17e7d0b14879077b6e975b72df5b88aad

### Failed CI Steps
* [Check integrations zscaler_zia](https://buildkite.com/elastic/integrations/builds/15014#01918d16-a3ec-464f-b1aa-7bc97cbb83f3)

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15014","number":15014,"commit":"59b861f17e7d0b14879077b6e975b72df5b88aad"}],"number":15014}
buildkite-pr-comment-->

2024-08-26 11:18 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15021)
* Commit: 390a85880dbe6691f440bdb30438fcd9f6d92ed4

### History
* :broken_heart: [Build #15014](https://buildkite.com/elastic/integrations/builds/15014) failed 59b861f17e7d0b14879077b6e975b72df5b88aad

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15021","number":15021,"commit":"390a85880dbe6691f440bdb30438fcd9f6d92ed4"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15014","number":15014,"commit":"59b861f17e7d0b14879077b6e975b72df5b88aad"}],"number":15021}
buildkite-pr-comment-->

2024-08-26 11:20 UTC, elasticmachine commented
Pinging @elastic/security-service-integrations (Team:Security-Service Integrations)

2024-08-26 14:42 UTC, chrisberkhout requested changes

2024-08-26 14:42 UTC, chrisberkhout commented on packages/zscaler_zia/_dev/build/docs/README.md
> +\{"version":"v8","sourcetype":"zscalernss-web","event":\{"time":"%s{time}","cloudname":"%s{cloudname}","host":"%s{ehost}","serverip":"%s{sip}","external_devid":"%s{external_devid}","devicemodel":"%s{
The start of the pattern now has the version number in it, so should keep that up to date too;
```
\{"version":"v8","sourcetype":"zscalernss-web","event":\{"time":"%s{time}",...
```

2024-08-26 14:42 UTC, chrisberkhout commented on packages/zscaler_zia/_dev/build/docs/README.md
> +\{"version":"v8","sourcetype":"zscalernss-web","event":\{"time":"%s{time}","cloudname":"%s{cloudname}","host":"%s{ehost}","serverip":"%s{sip}","external_devid":"%s{external_devid}","devicemodel":"%s{
In the tests too.

If we successfully keep it up to date, we'll be able to look at logs and see what version of the pattern is configured in Zscaler. There's no validation of use of it in pipeline, but maybe one day https://github.com/elastic/integrations/issues/10743

2024-08-26 14:42 UTC, chrisberkhout commented on packages/zscaler_zia/data_stream/web/elasticsearch/ingest_pipeline/default.yml
> +      on_failure:
Is there any reason to not let failures fall through to the global `on_failure` handler [down at the bottom](https://github.com/elastic/integrations/blob/32fc06feb0223689a23afa0ecf05deab329ccd68/packages/zscaler_zia/data_stream/web/elasticsearch/ingest_pipeline/default.yml#L1511-L1518)?

2024-08-27 03:49 UTC, kcreddy commented on packages/zscaler_zia/data_stream/web/elasticsearch/ingest_pipeline/default.yml
> +      on_failure:
It was because the execution stops here and rest of the pipeline wouldn't execute. This results in incorrect value for `@timestamp` and even missing several other ECS fields as reported by user. 
I don't think parsing some of these fields from their hex-encoded counterpart correctly is as important as missing rest of the pipeline.

2024-08-27 03:51 UTC, kcreddy commented on packages/zscaler_zia/_dev/build/docs/README.md
> +\{"version":"v8","sourcetype":"zscalernss-web","event":\{"time":"%s{time}","cloudname":"%s{cloudname}","host":"%s{ehost}","serverip":"%s{sip}","external_devid":"%s{external_devid}","devicemodel":"%s{
Thank you, I think I missed checking on this `version` update in your last PR. I update the version to `v9` from `v8` in above suggestion and in test events.

2024-08-27 04:31 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-08-27 04:32 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15053)
* Commit: 4f7ff43fbd247d6969ba399b8fc90f6066e18050

### History
* :green_heart: [Build #15021](https://buildkite.com/elastic/integrations/builds/15021) succeeded 390a85880dbe6691f440bdb30438fcd9f6d92ed4
* :broken_heart: [Build #15014](https://buildkite.com/elastic/integrations/builds/15014) failed 59b861f17e7d0b14879077b6e975b72df5b88aad

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15053","number":15053,"commit":"4f7ff43fbd247d6969ba399b8fc90f6066e18050"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15021","number":15021,"commit":"390a85880dbe6691f440bdb30438fcd9f6d92ed4"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15014","number":15014,"commit":"59b861f17e7d0b14879077b6e975b72df5b88aad"}],"number":15053}
buildkite-pr-comment-->

2024-08-27 08:19 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15057)
* Commit: 2b88d6127533e44b08c718d34611841362e3f341

### History
* :green_heart: [Build #15053](https://buildkite.com/elastic/integrations/builds/15053) succeeded 4f7ff43fbd247d6969ba399b8fc90f6066e18050
* :green_heart: [Build #15021](https://buildkite.com/elastic/integrations/builds/15021) succeeded 390a85880dbe6691f440bdb30438fcd9f6d92ed4
* :broken_heart: [Build #15014](https://buildkite.com/elastic/integrations/builds/15014) failed 59b861f17e7d0b14879077b6e975b72df5b88aad

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15057","number":15057,"commit":"2b88d6127533e44b08c718d34611841362e3f341"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15053","number":15053,"commit":"4f7ff43fbd247d6969ba399b8fc90f6066e18050"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15021","number":15021,"commit":"390a85880dbe6691f440bdb30438fcd9f6d92ed4"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15014","number":15014,"commit":"59b861f17e7d0b14879077b6e975b72df5b88aad"}],"number":15057}
buildkite-pr-comment-->

2024-08-27 10:47 UTC, chrisberkhout commented on packages/zscaler_zia/data_stream/web/elasticsearch/ingest_pipeline/default.yml
> +      on_failure:
Oh, right! Yes, makes sense.

2024-08-27 11:45 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15068)
* Commit: 03073b296822039dcf0d458976efb74857aa7008

### History
* :green_heart: [Build #15057](https://buildkite.com/elastic/integrations/builds/15057) succeeded 2b88d6127533e44b08c718d34611841362e3f341
* :green_heart: [Build #15053](https://buildkite.com/elastic/integrations/builds/15053) succeeded 4f7ff43fbd247d6969ba399b8fc90f6066e18050
* :green_heart: [Build #15021](https://buildkite.com/elastic/integrations/builds/15021) succeeded 390a85880dbe6691f440bdb30438fcd9f6d92ed4
* :broken_heart: [Build #15014](https://buildkite.com/elastic/integrations/builds/15014) failed 59b861f17e7d0b14879077b6e975b72df5b88aad

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15068","number":15068,"commit":"03073b296822039dcf0d458976efb74857aa7008"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15057","number":15057,"commit":"2b88d6127533e44b08c718d34611841362e3f341"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15053","number":15053,"commit":"4f7ff43fbd247d6969ba399b8fc90f6066e18050"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15021","number":15021,"commit":"390a85880dbe6691f440bdb30438fcd9f6d92ed4"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15014","number":15014,"commit":"59b861f17e7d0b14879077b6e975b72df5b88aad"}],"number":15068}
buildkite-pr-comment-->

2024-08-27 14:58 UTC, chrisberkhout approved these changes

2024-08-28 03:02 UTC, merged

2024-08-28 03:17 UTC, elasticmachine commented
Package zscaler_zia - 3.2.3 containing this change is available at https://epr.elastic.co/search?package=zscaler_zia