Add Latest Transform - Wiz Vulnerabilities
elastic/integrations pull request #10895
Opened 2024-08-27 12:20 UTC by CohenIdo

solves:
- https://github.com/elastic/security-team/issues/9829

## Summary
* Create latest transform for the Wiz vulnerabilities.

2024-08-27 12:48 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15075)
* Commit: b152e20683203220e53e969cf91a81ef572b8de5

### Failed CI Steps
* [Check integrations wiz](https://buildkite.com/elastic/integrations/builds/15075#019193d8-593a-4aa9-bcdd-ea31e4085aec)

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15075","number":15075,"commit":"b152e20683203220e53e969cf91a81ef572b8de5"}],"number":15075}
buildkite-pr-comment-->

2024-08-28 10:16 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15114)
* Commit: 9cca8088afad179c492f83d237293d765fcdfcb8

### Failed CI Steps
* [Check integrations wiz](https://buildkite.com/elastic/integrations/builds/15114#01919878-ed73-4742-8229-551b20127701)

### History
* :broken_heart: [Build #15075](https://buildkite.com/elastic/integrations/builds/15075) failed b152e20683203220e53e969cf91a81ef572b8de5

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15114","number":15114,"commit":"9cca8088afad179c492f83d237293d765fcdfcb8"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15075","number":15075,"commit":"b152e20683203220e53e969cf91a81ef572b8de5"}],"number":15114}
buildkite-pr-comment-->

2024-08-28 12:11 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15123)
* Commit: c09d118a2cad3ac30e328178e9febc218d03ae59

### Failed CI Steps
* [Check integrations wiz](https://buildkite.com/elastic/integrations/builds/15123#019198dc-d666-4df8-b72b-422171882a99)

### History
* :broken_heart: [Build #15114](https://buildkite.com/elastic/integrations/builds/15114) failed 9cca8088afad179c492f83d237293d765fcdfcb8
* :broken_heart: [Build #15075](https://buildkite.com/elastic/integrations/builds/15075) failed b152e20683203220e53e969cf91a81ef572b8de5

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15123","number":15123,"commit":"c09d118a2cad3ac30e328178e9febc218d03ae59"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15114","number":15114,"commit":"9cca8088afad179c492f83d237293d765fcdfcb8"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15075","number":15075,"commit":"b152e20683203220e53e969cf91a81ef572b8de5"}],"number":15123}
buildkite-pr-comment-->

2024-08-28 13:03 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15124)
* Commit: 263dfcc5ce647919164d35c6706e7e05afe7ef58

### Failed CI Steps
* [Check integrations wiz](https://buildkite.com/elastic/integrations/builds/15124#0191990d-85f6-450b-95e5-c1054b412cdc)

### History
* :broken_heart: [Build #15123](https://buildkite.com/elastic/integrations/builds/15123) failed c09d118a2cad3ac30e328178e9febc218d03ae59
* :broken_heart: [Build #15114](https://buildkite.com/elastic/integrations/builds/15114) failed 9cca8088afad179c492f83d237293d765fcdfcb8
* :broken_heart: [Build #15075](https://buildkite.com/elastic/integrations/builds/15075) failed b152e20683203220e53e969cf91a81ef572b8de5

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15124","number":15124,"commit":"263dfcc5ce647919164d35c6706e7e05afe7ef58"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15123","number":15123,"commit":"c09d118a2cad3ac30e328178e9febc218d03ae59"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15114","number":15114,"commit":"9cca8088afad179c492f83d237293d765fcdfcb8"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15075","number":15075,"commit":"b152e20683203220e53e969cf91a81ef572b8de5"}],"number":15124}
buildkite-pr-comment-->

2024-08-28 15:19 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15139)
* Commit: 307c49a78d05837c591bba975edd0de0699c39c5

### Failed CI Steps
* [Check integrations wiz](https://buildkite.com/elastic/integrations/builds/15139#0191998d-a3ec-48ce-9200-ce510bc4c10e)

### History
* :broken_heart: [Build #15124](https://buildkite.com/elastic/integrations/builds/15124) failed 263dfcc5ce647919164d35c6706e7e05afe7ef58
* :broken_heart: [Build #15123](https://buildkite.com/elastic/integrations/builds/15123) failed c09d118a2cad3ac30e328178e9febc218d03ae59
* :broken_heart: [Build #15114](https://buildkite.com/elastic/integrations/builds/15114) failed 9cca8088afad179c492f83d237293d765fcdfcb8
* :broken_heart: [Build #15075](https://buildkite.com/elastic/integrations/builds/15075) failed b152e20683203220e53e969cf91a81ef572b8de5

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15139","number":15139,"commit":"307c49a78d05837c591bba975edd0de0699c39c5"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15124","number":15124,"commit":"263dfcc5ce647919164d35c6706e7e05afe7ef58"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15123","number":15123,"commit":"c09d118a2cad3ac30e328178e9febc218d03ae59"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15114","number":15114,"commit":"9cca8088afad179c492f83d237293d765fcdfcb8"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15075","number":15075,"commit":"b152e20683203220e53e969cf91a81ef572b8de5"}],"number":15139}
buildkite-pr-comment-->

2024-08-28 20:36 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15149)
* Commit: 0d554193cbd7937ba602386b52625fcccc5fe51b

### Failed CI Steps
* [Check integrations wiz](https://buildkite.com/elastic/integrations/builds/15149#01919aab-ff80-4038-ab68-59dc5fd5a400)

### History
* :broken_heart: [Build #15139](https://buildkite.com/elastic/integrations/builds/15139) failed 307c49a78d05837c591bba975edd0de0699c39c5
* :broken_heart: [Build #15124](https://buildkite.com/elastic/integrations/builds/15124) failed 263dfcc5ce647919164d35c6706e7e05afe7ef58
* :broken_heart: [Build #15123](https://buildkite.com/elastic/integrations/builds/15123) failed c09d118a2cad3ac30e328178e9febc218d03ae59
* :broken_heart: [Build #15114](https://buildkite.com/elastic/integrations/builds/15114) failed 9cca8088afad179c492f83d237293d765fcdfcb8
* :broken_heart: [Build #15075](https://buildkite.com/elastic/integrations/builds/15075) failed b152e20683203220e53e969cf91a81ef572b8de5

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15149","number":15149,"commit":"0d554193cbd7937ba602386b52625fcccc5fe51b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15139","number":15139,"commit":"307c49a78d05837c591bba975edd0de0699c39c5"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15124","number":15124,"commit":"263dfcc5ce647919164d35c6706e7e05afe7ef58"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15123","number":15123,"commit":"c09d118a2cad3ac30e328178e9febc218d03ae59"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15114","number":15114,"commit":"9cca8088afad179c492f83d237293d765fcdfcb8"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15075","number":15075,"commit":"b152e20683203220e53e969cf91a81ef572b8de5"}],"number":15149}
buildkite-pr-comment-->

2024-08-28 21:15 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15150)
* Commit: a8c8decf8779669fef20801a028f52566e9d8221

### Failed CI Steps
* [Check integrations wiz](https://buildkite.com/elastic/integrations/builds/15150#01919ad3-2bfe-4181-a954-a3ab8eca17e3)

### History
* :broken_heart: [Build #15149](https://buildkite.com/elastic/integrations/builds/15149) failed 0d554193cbd7937ba602386b52625fcccc5fe51b
* :broken_heart: [Build #15139](https://buildkite.com/elastic/integrations/builds/15139) failed 307c49a78d05837c591bba975edd0de0699c39c5
* :broken_heart: [Build #15124](https://buildkite.com/elastic/integrations/builds/15124) failed 263dfcc5ce647919164d35c6706e7e05afe7ef58
* :broken_heart: [Build #15123](https://buildkite.com/elastic/integrations/builds/15123) failed c09d118a2cad3ac30e328178e9febc218d03ae59
* :broken_heart: [Build #15114](https://buildkite.com/elastic/integrations/builds/15114) failed 9cca8088afad179c492f83d237293d765fcdfcb8

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15150","number":15150,"commit":"a8c8decf8779669fef20801a028f52566e9d8221"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15149","number":15149,"commit":"0d554193cbd7937ba602386b52625fcccc5fe51b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15139","number":15139,"commit":"307c49a78d05837c591bba975edd0de0699c39c5"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15124","number":15124,"commit":"263dfcc5ce647919164d35c6706e7e05afe7ef58"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15123","number":15123,"commit":"c09d118a2cad3ac30e328178e9febc218d03ae59"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15114","number":15114,"commit":"9cca8088afad179c492f83d237293d765fcdfcb8"}],"number":15150}
buildkite-pr-comment-->

2024-08-29 11:10 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15178)
* Commit: 3c0e0b9751233edba2baffe166c69e857dfd7466

### Failed CI Steps
* [Check integrations wiz](https://buildkite.com/elastic/integrations/builds/15178#01919dcc-a7d3-4e90-89b1-e497eb1342e6)

### History
* :broken_heart: [Build #15150](https://buildkite.com/elastic/integrations/builds/15150) failed a8c8decf8779669fef20801a028f52566e9d8221
* :broken_heart: [Build #15149](https://buildkite.com/elastic/integrations/builds/15149) failed 0d554193cbd7937ba602386b52625fcccc5fe51b
* :broken_heart: [Build #15139](https://buildkite.com/elastic/integrations/builds/15139) failed 307c49a78d05837c591bba975edd0de0699c39c5
* :broken_heart: [Build #15124](https://buildkite.com/elastic/integrations/builds/15124) failed 263dfcc5ce647919164d35c6706e7e05afe7ef58
* :broken_heart: [Build #15123](https://buildkite.com/elastic/integrations/builds/15123) failed c09d118a2cad3ac30e328178e9febc218d03ae59

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15178","number":15178,"commit":"3c0e0b9751233edba2baffe166c69e857dfd7466"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15150","number":15150,"commit":"a8c8decf8779669fef20801a028f52566e9d8221"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15149","number":15149,"commit":"0d554193cbd7937ba602386b52625fcccc5fe51b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15139","number":15139,"commit":"307c49a78d05837c591bba975edd0de0699c39c5"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15124","number":15124,"commit":"263dfcc5ce647919164d35c6706e7e05afe7ef58"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15123","number":15123,"commit":"c09d118a2cad3ac30e328178e9febc218d03ae59"}],"number":15178}
buildkite-pr-comment-->

2024-08-29 11:27 UTC, kcreddy commented
@CohenIdo, the CI is failing with error: 
```
error running package asset tests: could not complete test run: can't install the package: there was an apply error: installation failed: can't install the package: could not zip-install package; API status code = 500; response body = {"statusCode":500,"error":"Internal Server Error","message":"security_exception\n\tRoot causes:\n\t\tsecurity_exception: action [indices:admin/delete] is unauthorized for service account [elastic/kibana] on indices [security_solution-wiz.vulnerability_latest-v1], this action is granted by the index privileges [delete_index,manage,all]"}
```
If you added the necessary permissions into Elasticsearch, which will be merged into `8.15.3` version, then the `manifest.yml` should be updated with, so that CI runs on the version you added permissions:
```
conditions:
  kibana:
    version: "^8.15.3"
```

2024-08-30 13:41 UTC, maxcold commented on packages/wiz/elasticsearch/transform/latest_cdr_vulnerabilities/transform.yml
> +source:
on our native integration, we also have `settings: {unattended: true}`. I think we also need it here, wdyt?

2024-08-30 13:42 UTC, maxcold commented on packages/wiz/elasticsearch/transform/latest_cdr_vulnerabilities/transform.yml
> +    field: event.ingested
in native we have `delay: 60s`. The default I think is different. I don't know the history behind `60s` but should we also add it for this transform?

2024-08-30 13:43 UTC, maxcold commented on packages/wiz/elasticsearch/transform/latest_cdr_vulnerabilities/transform.yml
> +_meta:
some meta is missing
```
package: {
      name: 'wiz',
    },
    managed_by: 'cloud_security_posture',
```

2024-09-02 08:14 UTC, CohenIdo commented on packages/wiz/elasticsearch/transform/latest_cdr_vulnerabilities/transform.yml
> +source:
Good catch.

2024-09-02 08:38 UTC, CohenIdo commented on packages/wiz/elasticsearch/transform/latest_cdr_vulnerabilities/transform.yml
> +  managed: true
The `meta` object is added automatically: 


```json
{
  "id": "logs-wiz.latest_cdr_vulnerabilities-default-0.1.0",
  "authorization": {
    "roles": [
      "kibana_system"
    ]
  },
  "version": "10.0.0",
  "create_time": 1725266123777,
  "source": {
    "index": [
      "logs-wiz.vulnerability-*"
    ],
    "query": {
      "match_all": {}
    }
  },
  "dest": {
    "index": "security_solution-wiz.vulnerability_latest-v1",
    "aliases": [
      {
        "alias": "security_solution-wiz.vulnerability_latest",
        "move_on_creation": true
      }
    ]
  },
  "frequency": "5m",
  "sync": {
    "time": {
      "field": "event.ingested",
      "delay": "60s"
    }
  },
  "latest": {
    "unique_key": [
      "vulnerability.id",
      "resource.id",
      "vulnerability.package.name",
      "vulnerability.package.version",
      "data_stream.namespace"
    ],
    "sort": "@timestamp"
  },
  "description": "Latest Cloud Vulnerabilities Findings from Wiz",
  "settings": {
    "unattended": true
  },
  "_meta": {
    "managed": true,
    "fleet_transform_version": "0.1.0",
    "managed_by": "fleet",
    "package": {
      "name": "wiz"
    },
    "installed_by": "elastic",
    "run_as_kibana_system": true
  },
  "retention_policy": {
    "time": {
      "field": "@timestamp",
      "max_age": "3d"
    }
  }
}
```

2024-09-02 11:41 UTC, CohenIdo commented on packages/wiz/elasticsearch/transform/latest_cdr_vulnerabilities/transform.yml
> +    field: event.ingested
The [default](https://www.elastic.co/guide/en/elasticsearch/reference/current/put-transform.html) is `60s`

2024-09-02 11:43 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15304)
* Commit: f3ef6f8beb9b941fac7790bedd50598e24ed03b1

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/15304#0191b28b-5839-4716-947c-b1691df94567)

### History
* :broken_heart: [Build #15178](https://buildkite.com/elastic/integrations/builds/15178) failed 3c0e0b9751233edba2baffe166c69e857dfd7466
* :broken_heart: [Build #15150](https://buildkite.com/elastic/integrations/builds/15150) failed a8c8decf8779669fef20801a028f52566e9d8221
* :broken_heart: [Build #15149](https://buildkite.com/elastic/integrations/builds/15149) failed 0d554193cbd7937ba602386b52625fcccc5fe51b
* :broken_heart: [Build #15139](https://buildkite.com/elastic/integrations/builds/15139) failed 307c49a78d05837c591bba975edd0de0699c39c5
* :broken_heart: [Build #15124](https://buildkite.com/elastic/integrations/builds/15124) failed 263dfcc5ce647919164d35c6706e7e05afe7ef58

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15304","number":15304,"commit":"f3ef6f8beb9b941fac7790bedd50598e24ed03b1"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15178","number":15178,"commit":"3c0e0b9751233edba2baffe166c69e857dfd7466"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15150","number":15150,"commit":"a8c8decf8779669fef20801a028f52566e9d8221"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15149","number":15149,"commit":"0d554193cbd7937ba602386b52625fcccc5fe51b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15139","number":15139,"commit":"307c49a78d05837c591bba975edd0de0699c39c5"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15124","number":15124,"commit":"263dfcc5ce647919164d35c6706e7e05afe7ef58"}],"number":15304}
buildkite-pr-comment-->

2024-09-02 13:14 UTC, maxcold requested changes
the required version seem to be incorrect and we also must not merge until this change in ES https://github.com/elastic/elasticsearch/pull/11219 is merged and made it to Serverless production. Otherwise the integration will be available in serverless, but transform would fail

2024-09-02 13:14 UTC, maxcold commented on packages/wiz/manifest.yml
> +    version: '^8.15.2'
Why it's 8.15.2 and not 8.16.0? If I understand correctly we are adding kibana_system privileges required for transform to work to 8.16.0

2024-09-02 14:47 UTC, maxcold approved these changes

2024-09-02 14:52 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15313)
* Commit: 4dc1d3b99010095eae83139ccbd04d5fad82fa5a

### Failed CI Steps
* [Check integrations wiz](https://buildkite.com/elastic/integrations/builds/15313#0191b331-0f22-4ece-ab12-009832d8ec53)

### History
* :broken_heart: [Build #15306](https://buildkite.com/elastic/integrations/builds/15306) failed e7662ee95c819b300bb6bf97f0edc5a27685a5f9
* :broken_heart: [Build #15304](https://buildkite.com/elastic/integrations/builds/15304) failed f3ef6f8beb9b941fac7790bedd50598e24ed03b1
* :broken_heart: [Build #15178](https://buildkite.com/elastic/integrations/builds/15178) failed 3c0e0b9751233edba2baffe166c69e857dfd7466
* :broken_heart: [Build #15150](https://buildkite.com/elastic/integrations/builds/15150) failed a8c8decf8779669fef20801a028f52566e9d8221
* :broken_heart: [Build #15149](https://buildkite.com/elastic/integrations/builds/15149) failed 0d554193cbd7937ba602386b52625fcccc5fe51b

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15313","number":15313,"commit":"4dc1d3b99010095eae83139ccbd04d5fad82fa5a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15306","number":15306,"commit":"e7662ee95c819b300bb6bf97f0edc5a27685a5f9"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15304","number":15304,"commit":"f3ef6f8beb9b941fac7790bedd50598e24ed03b1"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15178","number":15178,"commit":"3c0e0b9751233edba2baffe166c69e857dfd7466"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15150","number":15150,"commit":"a8c8decf8779669fef20801a028f52566e9d8221"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15149","number":15149,"commit":"0d554193cbd7937ba602386b52625fcccc5fe51b"}],"number":15313}
buildkite-pr-comment-->

2024-09-03 10:03 UTC, maxcold commented on packages/wiz/manifest.yml
> +version: '1.8.0'
As discussed with @CohenIdo we might want to make this change under `preview` version first as the UX is not yet ready, plus as the change is quite big and requires more e2e testing

2024-09-03 13:45 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15376)
* Commit: 2828c7076de7fdda8dfed323691b0b29a302b52d

### Failed CI Steps
* [Check integrations wiz](https://buildkite.com/elastic/integrations/builds/15376#0191b819-bc9b-4ea7-9feb-22eb965294ae)

### History
* :broken_heart: [Build #15313](https://buildkite.com/elastic/integrations/builds/15313) failed 4dc1d3b99010095eae83139ccbd04d5fad82fa5a
* :broken_heart: [Build #15306](https://buildkite.com/elastic/integrations/builds/15306) failed e7662ee95c819b300bb6bf97f0edc5a27685a5f9
* :broken_heart: [Build #15304](https://buildkite.com/elastic/integrations/builds/15304) failed f3ef6f8beb9b941fac7790bedd50598e24ed03b1
* :broken_heart: [Build #15178](https://buildkite.com/elastic/integrations/builds/15178) failed 3c0e0b9751233edba2baffe166c69e857dfd7466
* :broken_heart: [Build #15150](https://buildkite.com/elastic/integrations/builds/15150) failed a8c8decf8779669fef20801a028f52566e9d8221

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15376","number":15376,"commit":"2828c7076de7fdda8dfed323691b0b29a302b52d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15313","number":15313,"commit":"4dc1d3b99010095eae83139ccbd04d5fad82fa5a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15306","number":15306,"commit":"e7662ee95c819b300bb6bf97f0edc5a27685a5f9"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15304","number":15304,"commit":"f3ef6f8beb9b941fac7790bedd50598e24ed03b1"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15178","number":15178,"commit":"3c0e0b9751233edba2baffe166c69e857dfd7466"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15150","number":15150,"commit":"a8c8decf8779669fef20801a028f52566e9d8221"}],"number":15376}
buildkite-pr-comment-->

2024-09-03 17:33 UTC, kfirpeled commented on packages/wiz/manifest.yml
> +version: '1.8.0'
lets put this on preview guys
I don't think we should release this change without a full QA cycle
wdyt?

2024-09-04 07:37 UTC, CohenIdo commented on packages/wiz/manifest.yml
> +version: '1.8.0'
@kfirpeled yes, me and @maxcold were agreed on that and put it on today sync agenda sync to get the team approval. So it seems we all agree. will do

2024-09-04 07:56 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15435)
* Commit: 28d6aae0f447e38eef864e3fb2189bd30ec5509d

### Failed CI Steps
* [Check integrations mysql](https://buildkite.com/elastic/integrations/builds/15435#0191bbfe-9ee2-4f19-b36b-bb939d8d8976)

### History
* :broken_heart: [Build #15376](https://buildkite.com/elastic/integrations/builds/15376) failed 2828c7076de7fdda8dfed323691b0b29a302b52d
* :broken_heart: [Build #15313](https://buildkite.com/elastic/integrations/builds/15313) failed 4dc1d3b99010095eae83139ccbd04d5fad82fa5a
* :broken_heart: [Build #15306](https://buildkite.com/elastic/integrations/builds/15306) failed e7662ee95c819b300bb6bf97f0edc5a27685a5f9
* :broken_heart: [Build #15304](https://buildkite.com/elastic/integrations/builds/15304) failed f3ef6f8beb9b941fac7790bedd50598e24ed03b1
* :broken_heart: [Build #15178](https://buildkite.com/elastic/integrations/builds/15178) failed 3c0e0b9751233edba2baffe166c69e857dfd7466

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15435","number":15435,"commit":"28d6aae0f447e38eef864e3fb2189bd30ec5509d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15376","number":15376,"commit":"2828c7076de7fdda8dfed323691b0b29a302b52d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15313","number":15313,"commit":"4dc1d3b99010095eae83139ccbd04d5fad82fa5a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15306","number":15306,"commit":"e7662ee95c819b300bb6bf97f0edc5a27685a5f9"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15304","number":15304,"commit":"f3ef6f8beb9b941fac7790bedd50598e24ed03b1"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15178","number":15178,"commit":"3c0e0b9751233edba2baffe166c69e857dfd7466"}],"number":15435}
buildkite-pr-comment-->

2024-09-04 09:17 UTC, elasticmachine commented
### :rocket: Benchmarks report












































































































































































































































































































































































































































































To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-09-05 09:49 UTC, maxcold commented on packages/wiz/manifest.yml
> +    subscription: 'basic'
seems like some formatting mishap, double quotes should be fine in the manifest, correct?

2024-09-05 10:14 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15518)
* Commit: 49acef63be72d1684b3405803cc9c51b53dd1d7d

### History
* :broken_heart: [Build #15435](https://buildkite.com/elastic/integrations/builds/15435) failed 28d6aae0f447e38eef864e3fb2189bd30ec5509d
* :broken_heart: [Build #15376](https://buildkite.com/elastic/integrations/builds/15376) failed 2828c7076de7fdda8dfed323691b0b29a302b52d
* :broken_heart: [Build #15313](https://buildkite.com/elastic/integrations/builds/15313) failed 4dc1d3b99010095eae83139ccbd04d5fad82fa5a
* :broken_heart: [Build #15306](https://buildkite.com/elastic/integrations/builds/15306) failed e7662ee95c819b300bb6bf97f0edc5a27685a5f9
* :broken_heart: [Build #15304](https://buildkite.com/elastic/integrations/builds/15304) failed f3ef6f8beb9b941fac7790bedd50598e24ed03b1

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15518","number":15518,"commit":"49acef63be72d1684b3405803cc9c51b53dd1d7d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15435","number":15435,"commit":"28d6aae0f447e38eef864e3fb2189bd30ec5509d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15376","number":15376,"commit":"2828c7076de7fdda8dfed323691b0b29a302b52d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15313","number":15313,"commit":"4dc1d3b99010095eae83139ccbd04d5fad82fa5a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15306","number":15306,"commit":"e7662ee95c819b300bb6bf97f0edc5a27685a5f9"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15304","number":15304,"commit":"f3ef6f8beb9b941fac7790bedd50598e24ed03b1"}],"number":15518}
buildkite-pr-comment-->

2024-09-06 00:14 UTC, efd6 commented on packages/wiz/changelog.yml
> +- version: "1.8.0-preview01"
Why is this not just a release?

2024-09-06 00:14 UTC, efd6 commented on packages/wiz/elasticsearch/transform/latest_cdr_vulnerabilities/fields/fields.yml
> +  external: ecs
Do these need to be added?

2024-09-06 00:14 UTC, efd6 commented on packages/wiz/manifest.yml
> +    version: "^8.16.0"
If this is the requirement, this should probably be a draft PR until we get there. If we merge this now, all the subsequent changes will either require 8.16 or have to have back-ports.

2024-09-06 16:02 UTC, maxcold commented on packages/wiz/changelog.yml
> +- version: "1.8.0-preview01"
as the change introduces the transform we want to test the approach extensively before opening it up for users. There are also some UX adjustments we might need to do based on the real data coming from Wiz. Making the integration a preview first, will allow the team better DX for testing the features. This approach works well for us in the cloud_security_posture integration

2024-09-08 06:25 UTC, CohenIdo commented on packages/wiz/elasticsearch/transform/latest_cdr_vulnerabilities/fields/fields.yml
> +  external: ecs
Yes, the transform destination index is not predefined in Elasticsearch (unlike the `logs-*` and `metrics-*` indices), so the ECS fields are not inherited automatically and must be explicitly defined.

2024-09-08 06:43 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15619)
* Commit: 9f77a15915e20a6db8f4ba20042d414d5b912e2b

### History
* :green_heart: [Build #15518](https://buildkite.com/elastic/integrations/builds/15518) succeeded 49acef63be72d1684b3405803cc9c51b53dd1d7d
* :broken_heart: [Build #15435](https://buildkite.com/elastic/integrations/builds/15435) failed 28d6aae0f447e38eef864e3fb2189bd30ec5509d
* :broken_heart: [Build #15376](https://buildkite.com/elastic/integrations/builds/15376) failed 2828c7076de7fdda8dfed323691b0b29a302b52d
* :broken_heart: [Build #15313](https://buildkite.com/elastic/integrations/builds/15313) failed 4dc1d3b99010095eae83139ccbd04d5fad82fa5a
* :broken_heart: [Build #15306](https://buildkite.com/elastic/integrations/builds/15306) failed e7662ee95c819b300bb6bf97f0edc5a27685a5f9
* :broken_heart: [Build #15304](https://buildkite.com/elastic/integrations/builds/15304) failed f3ef6f8beb9b941fac7790bedd50598e24ed03b1

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15619","number":15619,"commit":"9f77a15915e20a6db8f4ba20042d414d5b912e2b"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15518","number":15518,"commit":"49acef63be72d1684b3405803cc9c51b53dd1d7d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15435","number":15435,"commit":"28d6aae0f447e38eef864e3fb2189bd30ec5509d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15376","number":15376,"commit":"2828c7076de7fdda8dfed323691b0b29a302b52d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15313","number":15313,"commit":"4dc1d3b99010095eae83139ccbd04d5fad82fa5a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15306","number":15306,"commit":"e7662ee95c819b300bb6bf97f0edc5a27685a5f9"}],"number":15619}
buildkite-pr-comment-->

2024-09-08 21:00 UTC, efd6 commented on packages/wiz/manifest.yml
> +    version: "^8.16.0"
> Are there changes planned for Wiz integration where backporting a concern?

It's difficult to predict bugs.

2024-09-09 07:26 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15637)
* Commit: 4c3f8f9afdba923df23054a02a521739895b0ceb

### History
* :green_heart: [Build #15619](https://buildkite.com/elastic/integrations/builds/15619) succeeded 9f77a15915e20a6db8f4ba20042d414d5b912e2b
* :green_heart: [Build #15518](https://buildkite.com/elastic/integrations/builds/15518) succeeded 49acef63be72d1684b3405803cc9c51b53dd1d7d
* :broken_heart: [Build #15435](https://buildkite.com/elastic/integrations/builds/15435) failed 28d6aae0f447e38eef864e3fb2189bd30ec5509d
* :broken_heart: [Build #15376](https://buildkite.com/elastic/integrations/builds/15376) failed 2828c7076de7fdda8dfed323691b0b29a302b52d
* :broken_heart: [Build #15313](https://buildkite.com/elastic/integrations/builds/15313) failed 4dc1d3b99010095eae83139ccbd04d5fad82fa5a
* :broken_heart: [Build #15306](https://buildkite.com/elastic/integrations/builds/15306) failed e7662ee95c819b300bb6bf97f0edc5a27685a5f9

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15637","number":15637,"commit":"4c3f8f9afdba923df23054a02a521739895b0ceb"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15619","number":15619,"commit":"9f77a15915e20a6db8f4ba20042d414d5b912e2b"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15518","number":15518,"commit":"49acef63be72d1684b3405803cc9c51b53dd1d7d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15435","number":15435,"commit":"28d6aae0f447e38eef864e3fb2189bd30ec5509d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15376","number":15376,"commit":"2828c7076de7fdda8dfed323691b0b29a302b52d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15313","number":15313,"commit":"4dc1d3b99010095eae83139ccbd04d5fad82fa5a"}],"number":15637}
buildkite-pr-comment-->

2024-09-09 08:26 UTC, CohenIdo commented on packages/wiz/changelog.yml
> +- version: "1.8.0-preview01"
Just to make it clearer, any bug fix can be merged under `1.7.x` and any changes that are for 8.16 will be under `1.8.0-preview0x`

2024-09-09 08:47 UTC, kcreddy commented on packages/wiz/changelog.yml
> +- version: "1.8.0-preview01"
If bugfixes were continued to be merged under `1.7.x`, I think the users will not be seeing them because the `mainfest`'s `kibana.version` has moved to `8.16.0`. The users need to be >= package's `kibana.version` to get the fixes/upgrades.

2024-09-09 09:38 UTC, maxcold commented on packages/wiz/manifest.yml
> +    version: "^8.16.0"
I think unexpected bug fixes can be backported to 1.7, I assume the backporting flow exists for this reason. The bumping kibana stack version while using preview versions works quite well for `cloud_security_posture`, more so with the introduction of serverless. Any concern with this approach for Wiz except the potential backports?

2024-09-09 10:19 UTC, efd6 requested changes
Hold purely to avoid a merge before the version issue is discussed within the team.

2024-09-10 07:36 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15691)
* Commit: 4a7732a03508dbbe04a8da259067588d2dabddd1

### History
* :green_heart: [Build #15637](https://buildkite.com/elastic/integrations/builds/15637) succeeded 4c3f8f9afdba923df23054a02a521739895b0ceb
* :green_heart: [Build #15619](https://buildkite.com/elastic/integrations/builds/15619) succeeded 9f77a15915e20a6db8f4ba20042d414d5b912e2b
* :green_heart: [Build #15518](https://buildkite.com/elastic/integrations/builds/15518) succeeded 49acef63be72d1684b3405803cc9c51b53dd1d7d
* :broken_heart: [Build #15435](https://buildkite.com/elastic/integrations/builds/15435) failed 28d6aae0f447e38eef864e3fb2189bd30ec5509d
* :broken_heart: [Build #15376](https://buildkite.com/elastic/integrations/builds/15376) failed 2828c7076de7fdda8dfed323691b0b29a302b52d
* :broken_heart: [Build #15313](https://buildkite.com/elastic/integrations/builds/15313) failed 4dc1d3b99010095eae83139ccbd04d5fad82fa5a

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15691","number":15691,"commit":"4a7732a03508dbbe04a8da259067588d2dabddd1"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15637","number":15637,"commit":"4c3f8f9afdba923df23054a02a521739895b0ceb"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15619","number":15619,"commit":"9f77a15915e20a6db8f4ba20042d414d5b912e2b"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15518","number":15518,"commit":"49acef63be72d1684b3405803cc9c51b53dd1d7d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15435","number":15435,"commit":"28d6aae0f447e38eef864e3fb2189bd30ec5509d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15376","number":15376,"commit":"2828c7076de7fdda8dfed323691b0b29a302b52d"}],"number":15691}
buildkite-pr-comment-->

2024-09-10 09:03 UTC, CohenIdo commented
> Hold purely to avoid a merge before the version issue is discussed within the team.

There is a simple way to backport for the pervious stack version.
Adding @maxcold's investigations findings:
_"all the docs I could find is this issue https://github.com/elastic/package-spec/issues/225 (linked in the package-spec) To my understanding, our use of the pre-release version is totally valid. I also don't see a problem with backport flow after I did backport for csp integration. It involves a bit more work (create backport branch via CI and remember to update the changelog in main manually) but I don't see it as a big blocker"_

2024-09-10 22:18 UTC, efd6 commented on packages/wiz/manifest.yml
> +    version: "^8.16.0"
Can you explain what the feature is present in 8.16 that is not present in 8.13? If there is none, what is the reason for wanting to bump this?

2024-09-11 09:14 UTC, maxcold commented on packages/wiz/manifest.yml
> +    version: "^8.16.0"
thanks @kcreddy , that's correct. Plus we release UX features that would leverage the latest transform results, without them having transform would be just a waste of resources. and yes, won't event work properly due to missing privileges

2024-09-11 11:46 UTC, andrewkroh commented on packages/wiz/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/10936
Links to wrong PR.

```suggestion
      link: https://github.com/elastic/integrations/pull/10895
```

2024-09-11 13:11 UTC, andrewkroh commented on packages/wiz/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/10936
Also the link for version 1.8.0 should point to #10997.

2024-09-11 18:45 UTC, CohenIdo commented on packages/wiz/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/10936
Thanks.

2024-09-11 19:14 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15789)
* Commit: b75bcfd40c8afacdf985adf7d9eef7538e6ce75a

### History
* :green_heart: [Build #15691](https://buildkite.com/elastic/integrations/builds/15691) succeeded 4a7732a03508dbbe04a8da259067588d2dabddd1
* :green_heart: [Build #15637](https://buildkite.com/elastic/integrations/builds/15637) succeeded 4c3f8f9afdba923df23054a02a521739895b0ceb
* :green_heart: [Build #15619](https://buildkite.com/elastic/integrations/builds/15619) succeeded 9f77a15915e20a6db8f4ba20042d414d5b912e2b
* :green_heart: [Build #15518](https://buildkite.com/elastic/integrations/builds/15518) succeeded 49acef63be72d1684b3405803cc9c51b53dd1d7d
* :broken_heart: [Build #15435](https://buildkite.com/elastic/integrations/builds/15435) failed 28d6aae0f447e38eef864e3fb2189bd30ec5509d
* :broken_heart: [Build #15376](https://buildkite.com/elastic/integrations/builds/15376) failed 2828c7076de7fdda8dfed323691b0b29a302b52d

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15789","number":15789,"commit":"b75bcfd40c8afacdf985adf7d9eef7538e6ce75a"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15691","number":15691,"commit":"4a7732a03508dbbe04a8da259067588d2dabddd1"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15637","number":15637,"commit":"4c3f8f9afdba923df23054a02a521739895b0ceb"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15619","number":15619,"commit":"9f77a15915e20a6db8f4ba20042d414d5b912e2b"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15518","number":15518,"commit":"49acef63be72d1684b3405803cc9c51b53dd1d7d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15435","number":15435,"commit":"28d6aae0f447e38eef864e3fb2189bd30ec5509d"}],"number":15789}
buildkite-pr-comment-->

2024-09-11 23:02 UTC, efd6 commented on packages/wiz/manifest.yml
> +    version: "^8.16.0"
I'm going to remove my block, but despite the documented backport release workflow, in practice, making this change will in all likelihood result in reduction in fixes being released for pre-8.16-dependent versions of the package. This is just an observation on normal dev responses to additional friction from this kind of thing.

2024-09-12 07:18 UTC, kcreddy approved these changes
LGTM

2024-09-12 07:20 UTC, merged

2024-09-12 07:34 UTC, elasticmachine commented
Package wiz - 1.9.0-preview01 containing this change is available at https://epr.elastic.co/search?package=wiz