[vSphere][host] Add support for new metrics in Host datastream
elastic/integrations pull request #10894
Opened 2024-08-27 10:52 UTC by kush-elastic

## Description
Here are the following metrics to be added for the host data stream in the vSphere Integration. Here we added a new performance API to get more detailed information from the vSphere.

Metrics Type | Metrics | API | Field Mappings
-- | -- | -- | --
Host Disk Performance |   |   |  
  | disk.deviceLatency.average        (ms) | Performance | disk.devicelatency.average.ms
  | disk.maxTotalLatency.latest        (ms) | Performance | disk.latency.total.ms
  | disk.usage.average (KBps) | Performance | disk.total.bytes
  | disk.read.average  (KBps) | Performance | disk.read.bytes
  | disk.write.average  (KBps) | Performance | disk.write.bytes
  | disk.capacity.usage.average (KB) | Performance | disk.capacity.usage.bytes
  |   |   |  
Host uptime/status |   |   |  
  | host.Summary.OverallStatus | Summary | status
  | host.Summary.QuickStats.Uptime | Summary | uptime
  | host.Datastore | Extra | datastore.names
  |   |   | datastore.count
  | host.Vm | Extra | vm.names
  |   |   | vm.count
  |   |   |  
Host Network Stats | host.Netowork | Extra | network.names
  |   |   | network.count
  | net.transmitted.average (KBps) | Performance | network.bandwidth.transmitted.bytes
  | net.received.average (KBps) | Performance | network.bandwidth.received.bytes
  | net.usage.average (KBps) | Performance | network.bandwidth.total.bytes
  | net.packetsTx.summation (num) | Performance | network.packets.transmitted.count
  | net.packetsRx.summation (num) | Performance | network.packets.received.count
  | net.errorsRx.summation (num) | Performance | network.packets.errors.received.count
  | net.errorsTx.summation (num) | Performance | network.packets.errors.transmitted.count
  |   |   | network.packets.errors.total.count
  | net.multicastTx.summation (num) | Performance | network.packets.multicast.transmitted.count
  | net.multicastRx.summation (num) | Performance | network.packets.multicast.received.count
  |   |   | network.packets.multicast.total.count
  | net.droppedTx.summation (num) | Performance | network.packets.dropped.transmitted.count
  | net.droppedRx.summation (num) | Performance | network.packets.dropped.received.count
  |   |   | network.packets.dropped.total.count

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Closes https://github.com/elastic/obs-integration-team/issues/28

2024-08-27 10:56 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15066)
* Commit: 7cd38f8dcfcc9c0d396aa151a79a46efe81bd158

### Failed CI Steps
* [:white_check_mark: Check go sources](https://buildkite.com/elastic/integrations/builds/15066#01919378-8a25-487f-ba9d-0c4e121d136d)

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15066","number":15066,"commit":"7cd38f8dcfcc9c0d396aa151a79a46efe81bd158"}],"number":15066}
buildkite-pr-comment-->

2024-08-29 06:55 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15170)
* Commit: 5ed5f2f7be925ebc058e7f74816aed94a5231f1d

### Failed CI Steps
* [Check integrations vsphere](https://buildkite.com/elastic/integrations/builds/15170#01919ce4-f9a3-4787-abfe-74bc98a25d85)

### History
* :broken_heart: [Build #15066](https://buildkite.com/elastic/integrations/builds/15066) failed 7cd38f8dcfcc9c0d396aa151a79a46efe81bd158

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15170","number":15170,"commit":"5ed5f2f7be925ebc058e7f74816aed94a5231f1d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15066","number":15066,"commit":"7cd38f8dcfcc9c0d396aa151a79a46efe81bd158"}],"number":15170}
buildkite-pr-comment-->

2024-08-29 07:23 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15171)
* Commit: f17173f4d8215c8aed8a38a82c8cedc769826556

### Failed CI Steps
* [Check integrations vsphere](https://buildkite.com/elastic/integrations/builds/15171#01919cf8-3f02-43ae-b6af-cdcbc838aa11)

### History
* :broken_heart: [Build #15170](https://buildkite.com/elastic/integrations/builds/15170) failed 5ed5f2f7be925ebc058e7f74816aed94a5231f1d
* :broken_heart: [Build #15066](https://buildkite.com/elastic/integrations/builds/15066) failed 7cd38f8dcfcc9c0d396aa151a79a46efe81bd158

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15171","number":15171,"commit":"f17173f4d8215c8aed8a38a82c8cedc769826556"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15170","number":15170,"commit":"5ed5f2f7be925ebc058e7f74816aed94a5231f1d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15066","number":15066,"commit":"7cd38f8dcfcc9c0d396aa151a79a46efe81bd158"}],"number":15171}
buildkite-pr-comment-->

2024-08-30 06:42 UTC, ishleenk17 commented on packages/vsphere/data_stream/host/fields/agent.yml
> +    - name: architecture
We need not have these fields. These are part of ecs@mapping template.

2024-09-11 05:43 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15737)
* Commit: a886dc2368baaa6ae8a364545f77e2eaedb461c2

### Failed CI Steps
* [Check integrations vsphere](https://buildkite.com/elastic/integrations/builds/15737#0191df97-7328-4a3f-a484-8433632cd65d)

### History
* :broken_heart: [Build #15171](https://buildkite.com/elastic/integrations/builds/15171) failed f17173f4d8215c8aed8a38a82c8cedc769826556
* :broken_heart: [Build #15170](https://buildkite.com/elastic/integrations/builds/15170) failed 5ed5f2f7be925ebc058e7f74816aed94a5231f1d
* :broken_heart: [Build #15066](https://buildkite.com/elastic/integrations/builds/15066) failed 7cd38f8dcfcc9c0d396aa151a79a46efe81bd158

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15737","number":15737,"commit":"a886dc2368baaa6ae8a364545f77e2eaedb461c2"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15171","number":15171,"commit":"f17173f4d8215c8aed8a38a82c8cedc769826556"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15170","number":15170,"commit":"5ed5f2f7be925ebc058e7f74816aed94a5231f1d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15066","number":15066,"commit":"7cd38f8dcfcc9c0d396aa151a79a46efe81bd158"}],"number":15737}
buildkite-pr-comment-->

2024-09-11 09:49 UTC, lucian-ioan commented on packages/vsphere/data_stream/datastore/manifest.yml
>    index_mode: "time_series"
Please provide a screenshot with results from [TSDB-migration-test-kit](https://github.com/elastic/TSDB-migration-test-kit) with the new field changes.

2024-09-17 06:40 UTC, ishleenk17 commented on packages/vsphere/_dev/build/docs/README.md
> +- The vSphere performance API allows for collecting host and datastore metrics at various intervals, including real-time (every 20 seconds), 5-minutes, and longer durations. To get accurate results,
Let's ensure we have this usage of period exactly as mentioned in the beats module.

2024-09-17 06:40 UTC, ishleenk17 commented on packages/vsphere/_dev/build/docs/README.md
>  The integration uses the [Govmomi](https://github.com/vmware/govmomi) library to collect metrics and logs from any Vmware SDK URL (ESXi/VCenter). This library is built for and tested against ESXi and
Update this as per the compatibility mentioned in beats.
Also, we need not mention about the library as its tested on actual system now.

2024-09-17 06:40 UTC, ishleenk17 commented on packages/vsphere/_dev/build/docs/README.md
> +- To access the metrics, provide the URL <https://host:port(8989)/sdk> in the "Add Integration" page of the vSphere package.
We can skip mention of 8989 port here ?
Might create confusion.

2024-09-17 06:40 UTC, ishleenk17 commented on packages/vsphere/_dev/build/docs/README.md
> +Note: vSphere Integration currently supports network names of VMs connected only to vSS (vSphere Standard Switch) and not vDS (vSphere Distributed Switches).
We do support the Distributed Virtual Port Group (DVPG) now. 
Can we see if vDS will also be handled under this ?
Then we should remove this fromdocumentation

2024-09-17 06:40 UTC, ishleenk17 commented on packages/vsphere/data_stream/host/fields/fields.yml
> +      description: Number of datastores on the host.
The descriptions are different from the fields for host metricset in beats. 
Lets maintain the definitions across beats and integrations.

2024-09-17 06:40 UTC, ishleenk17 commented on packages/vsphere/data_stream/host/fields/fields.yml
>        type: keyword
cpu.used.pcyt field in not present in beats. Are we calculating it specifically for integration ?

2024-09-17 06:40 UTC, ishleenk17 commented on packages/vsphere/data_stream/host/fields/fields.yml
> +      description: Number of virtual machines on the host.
Lets add triggerd_alarms.* mapping here

2024-09-17 06:40 UTC, ishleenk17 commented on packages/vsphere/data_stream/host/manifest.yml
> +        description: The vSphere performance API allows for collecting host and datastore metrics at various intervals, including real-time (every 20 seconds), 5-minutes, and longer durations. Due to
Should be at par with beats description

2024-09-17 12:39 UTC, kush-elastic commented on packages/vsphere/data_stream/host/fields/fields.yml
>        type: keyword
Yes

2024-09-17 12:40 UTC, kush-elastic commented on packages/vsphere/data_stream/host/fields/fields.yml
> +      description: Number of virtual machines on the host.
Added

2024-09-17 13:04 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16003)
* Commit: 12a3667b5a7495267eb4bda08a222aae4ed294df

### History
* :broken_heart: [Build #15737](https://buildkite.com/elastic/integrations/builds/15737) failed a886dc2368baaa6ae8a364545f77e2eaedb461c2
* :broken_heart: [Build #15171](https://buildkite.com/elastic/integrations/builds/15171) failed f17173f4d8215c8aed8a38a82c8cedc769826556
* :broken_heart: [Build #15170](https://buildkite.com/elastic/integrations/builds/15170) failed 5ed5f2f7be925ebc058e7f74816aed94a5231f1d
* :broken_heart: [Build #15066](https://buildkite.com/elastic/integrations/builds/15066) failed 7cd38f8dcfcc9c0d396aa151a79a46efe81bd158

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16003","number":16003,"commit":"12a3667b5a7495267eb4bda08a222aae4ed294df"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15737","number":15737,"commit":"a886dc2368baaa6ae8a364545f77e2eaedb461c2"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15171","number":15171,"commit":"f17173f4d8215c8aed8a38a82c8cedc769826556"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15170","number":15170,"commit":"5ed5f2f7be925ebc058e7f74816aed94a5231f1d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15066","number":15066,"commit":"7cd38f8dcfcc9c0d396aa151a79a46efe81bd158"}],"number":16003}
buildkite-pr-comment-->

2024-09-18 05:25 UTC, ishleenk17 commented on packages/vsphere/data_stream/host/fields/agent.yml
> -      example: "18D109"
Please add dimension fields from datastore datastream

2024-09-18 05:32 UTC, ishleenk17 commented on packages/vsphere/data_stream/host/fields/fields.yml
> +        List of all the triggered alarms.
Are we defining this differently here and in beats and why so ?

2024-09-18 05:32 UTC, ishleenk17 commented on packages/vsphere/data_stream/host/fields/fields.yml
> +    - name: disk.devicelatency.average.ms
Unit if the ".ms" fields ?

2024-09-18 06:02 UTC, kush-elastic commented on packages/vsphere/data_stream/datastore/manifest.yml
>    index_mode: "time_series"
```
Values being used:
        elasticsearch_host = https://localhost:9200
        elasticsearch_ca_path = /root/.elastic-package/profiles/default/certs/elasticsearch/ca-cert.pem
        elasticsearch_user = elastic
        elasticsearch_pwd = changeme
        data_stream = metrics-vsphere.host-default
        docs_index = First index of the data stream
        settings_mappings_index = Last index of the data stream
        max_docs = All documents
        get_overlapping_files = True
        directory_overlapping_files = overwritten-docs-metrics-vsphere.host-default
        display_docs = 10
        copy_docs_per_dimension = 2

You're testing with version 8.16.0-SNAPSHOT.

Testing data stream metrics-vsphere.host-default.
Index being used for the documents is .ds-metrics-vsphere.host-default-2024.09.17-000001.
Index being used for the settings and mappings is .ds-metrics-vsphere.host-default-2024.09.17-000002.

The time series fields for the TSDB index are: 
        - dimension (10 fields):
                - agent.id
                - cloud.account.id
                - cloud.availability_zone
                - cloud.instance.id
                - cloud.provider
                - cloud.region
                - container.id
                - host.name
                - service.address
                - vsphere.host.name
        - counter (1 fields):
                - vsphere.host.cpu.total.mhz
        - gauge (30 fields):
                - vsphere.host.cpu.free.mhz
                - vsphere.host.cpu.used.mhz
                - vsphere.host.cpu.used.pct
                - vsphere.host.datastore.count
                - vsphere.host.disk.capacity.usage.bytes
                - vsphere.host.disk.devicelatency.average.ms
                - vsphere.host.disk.latency.total.ms
                - vsphere.host.disk.read.bytes
                - vsphere.host.disk.total.bytes
                - vsphere.host.disk.write.bytes
                - vsphere.host.memory.free.bytes
                - vsphere.host.memory.total.bytes
                - vsphere.host.memory.used.bytes
                - vsphere.host.memory.used.pct
                - vsphere.host.network.bandwidth.received.bytes
                - vsphere.host.network.bandwidth.total.bytes
                - vsphere.host.network.bandwidth.transmitted.bytes
                - vsphere.host.network.count
                - vsphere.host.network.packets.dropped.received.count
                - vsphere.host.network.packets.dropped.total.count
                - vsphere.host.network.packets.dropped.transmitted.count
                - vsphere.host.network.packets.errors.received.count
                - vsphere.host.network.packets.errors.total.count
                - vsphere.host.network.packets.errors.transmitted.count
                - vsphere.host.network.packets.multicast.received.count
                - vsphere.host.network.packets.multicast.total.count
                - vsphere.host.network.packets.multicast.transmitted.count
                - vsphere.host.network.packets.received.count
                - vsphere.host.network.packets.transmitted.count
                - vsphere.host.vm.count
        - routing_path (10 fields):
                - agent.id
                - cloud.account.id
                - cloud.availability_zone
                - cloud.instance.id
                - cloud.provider
                - cloud.region
                - container.id
                - host.name
                - service.address
                - vsphere.host.name

Index tsdb-index-enabled successfully created.

Copying documents from .ds-metrics-vsphere.host-default-2024.09.17-000001 to tsdb-index-enabled...
All 23 documents taken from index .ds-metrics-vsphere.host-default-2024.09.17-000001 were successfully placed to index tsdb-index-enabled.
```

2024-09-18 06:06 UTC, ishleenk17 commented on packages/vsphere/data_stream/host/fields/agent.yml
> -      example: "18D109"
Oh, I think the ones that are dimension are already added here. 
My bad.
@kush-elastic Please cross check once.

2024-09-18 11:53 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16057)
* Commit: 65777b31c2211109338eba12d6ee97a48e60345c

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/16057#019204f9-991b-406f-8149-d3f1838c87ab)

### History
* :green_heart: [Build #16003](https://buildkite.com/elastic/integrations/builds/16003) succeeded 12a3667b5a7495267eb4bda08a222aae4ed294df
* :broken_heart: [Build #15737](https://buildkite.com/elastic/integrations/builds/15737) failed a886dc2368baaa6ae8a364545f77e2eaedb461c2
* :broken_heart: [Build #15171](https://buildkite.com/elastic/integrations/builds/15171) failed f17173f4d8215c8aed8a38a82c8cedc769826556
* :broken_heart: [Build #15170](https://buildkite.com/elastic/integrations/builds/15170) failed 5ed5f2f7be925ebc058e7f74816aed94a5231f1d
* :broken_heart: [Build #15066](https://buildkite.com/elastic/integrations/builds/15066) failed 7cd38f8dcfcc9c0d396aa151a79a46efe81bd158

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16057","number":16057,"commit":"65777b31c2211109338eba12d6ee97a48e60345c"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16003","number":16003,"commit":"12a3667b5a7495267eb4bda08a222aae4ed294df"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15737","number":15737,"commit":"a886dc2368baaa6ae8a364545f77e2eaedb461c2"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15171","number":15171,"commit":"f17173f4d8215c8aed8a38a82c8cedc769826556"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15170","number":15170,"commit":"5ed5f2f7be925ebc058e7f74816aed94a5231f1d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15066","number":15066,"commit":"7cd38f8dcfcc9c0d396aa151a79a46efe81bd158"}],"number":16057}
buildkite-pr-comment-->

2024-09-18 12:19 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16062)
* Commit: 3040ee671629d044b16cf84a880fa0ab9be3ada5

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/16062#01920511-0b85-4077-846f-aacdd98cdb00)

### History
* :broken_heart: [Build #16057](https://buildkite.com/elastic/integrations/builds/16057) failed 65777b31c2211109338eba12d6ee97a48e60345c
* :green_heart: [Build #16003](https://buildkite.com/elastic/integrations/builds/16003) succeeded 12a3667b5a7495267eb4bda08a222aae4ed294df
* :broken_heart: [Build #15737](https://buildkite.com/elastic/integrations/builds/15737) failed a886dc2368baaa6ae8a364545f77e2eaedb461c2
* :broken_heart: [Build #15171](https://buildkite.com/elastic/integrations/builds/15171) failed f17173f4d8215c8aed8a38a82c8cedc769826556
* :broken_heart: [Build #15170](https://buildkite.com/elastic/integrations/builds/15170) failed 5ed5f2f7be925ebc058e7f74816aed94a5231f1d
* :broken_heart: [Build #15066](https://buildkite.com/elastic/integrations/builds/15066) failed 7cd38f8dcfcc9c0d396aa151a79a46efe81bd158

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16062","number":16062,"commit":"3040ee671629d044b16cf84a880fa0ab9be3ada5"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16057","number":16057,"commit":"65777b31c2211109338eba12d6ee97a48e60345c"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16003","number":16003,"commit":"12a3667b5a7495267eb4bda08a222aae4ed294df"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15737","number":15737,"commit":"a886dc2368baaa6ae8a364545f77e2eaedb461c2"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15171","number":15171,"commit":"f17173f4d8215c8aed8a38a82c8cedc769826556"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15170","number":15170,"commit":"5ed5f2f7be925ebc058e7f74816aed94a5231f1d"}],"number":16062}
buildkite-pr-comment-->

2024-09-18 12:23 UTC, kush-elastic commented on packages/vsphere/data_stream/host/fields/fields.yml
> +        List of all the triggered alarms.
if we use type as object every fields under it would need to be same type, i will need to try and fix this once i am able to test `triggered_alarms` changes.

```
file "/integrations/build/packages/vsphere-1.13.0.zip/data_stream/host/fields/fields.yml" is invalid: field 0.fields.35.type: 0.fields.35.type must be one of the following: "group", "nested"
```

2024-09-18 12:23 UTC, kush-elastic commented on packages/vsphere/data_stream/host/fields/fields.yml
> +    - name: disk.devicelatency.average.ms
added units.

2024-09-19 06:02 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16109)
* Commit: b6e4b13f6a689c66d02563e3391e3a97954e298a

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/16109#019208de-d73a-4028-b434-9e4d55c9776c)

### History
* :broken_heart: [Build #16062](https://buildkite.com/elastic/integrations/builds/16062) failed 3040ee671629d044b16cf84a880fa0ab9be3ada5
* :broken_heart: [Build #16057](https://buildkite.com/elastic/integrations/builds/16057) failed 65777b31c2211109338eba12d6ee97a48e60345c
* :green_heart: [Build #16003](https://buildkite.com/elastic/integrations/builds/16003) succeeded 12a3667b5a7495267eb4bda08a222aae4ed294df
* :broken_heart: [Build #15737](https://buildkite.com/elastic/integrations/builds/15737) failed a886dc2368baaa6ae8a364545f77e2eaedb461c2
* :broken_heart: [Build #15171](https://buildkite.com/elastic/integrations/builds/15171) failed f17173f4d8215c8aed8a38a82c8cedc769826556
* :broken_heart: [Build #15170](https://buildkite.com/elastic/integrations/builds/15170) failed 5ed5f2f7be925ebc058e7f74816aed94a5231f1d

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16109","number":16109,"commit":"b6e4b13f6a689c66d02563e3391e3a97954e298a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16062","number":16062,"commit":"3040ee671629d044b16cf84a880fa0ab9be3ada5"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16057","number":16057,"commit":"65777b31c2211109338eba12d6ee97a48e60345c"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16003","number":16003,"commit":"12a3667b5a7495267eb4bda08a222aae4ed294df"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15737","number":15737,"commit":"a886dc2368baaa6ae8a364545f77e2eaedb461c2"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15171","number":15171,"commit":"f17173f4d8215c8aed8a38a82c8cedc769826556"}],"number":16109}
buildkite-pr-comment-->

2024-09-19 06:12 UTC, kush-elastic commented on packages/vsphere/data_stream/host/fields/fields.yml
> +      description: Number of datastores on the host.
This is kept from how it is in Beats itself.

2024-09-19 06:28 UTC, ishleenk17 commented on packages/vsphere/data_stream/host/elasticsearch/ingest_pipeline/default.yml
> +  - rename:
Is this required? Now we have the latest changes with correct triggered_alarm ?

2024-09-19 06:29 UTC, ishleenk17 commented on packages/vsphere/data_stream/datastore/manifest.yml
>    index_mode: "time_series"
@agithomas : Is this testing sufficient to confirm that TSDB is working fone on the datastreams ?

2024-09-19 06:30 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16112)
* Commit: 956eeb4069f0f86913ee5e0c12d1d19a1c7020b3

### Failed CI Steps
* [Check integrations vsphere](https://buildkite.com/elastic/integrations/builds/16112#019208ec-8d81-4d45-aa37-57da9c38940d)

### History
* :broken_heart: [Build #16109](https://buildkite.com/elastic/integrations/builds/16109) failed b6e4b13f6a689c66d02563e3391e3a97954e298a
* :broken_heart: [Build #16062](https://buildkite.com/elastic/integrations/builds/16062) failed 3040ee671629d044b16cf84a880fa0ab9be3ada5
* :broken_heart: [Build #16057](https://buildkite.com/elastic/integrations/builds/16057) failed 65777b31c2211109338eba12d6ee97a48e60345c
* :green_heart: [Build #16003](https://buildkite.com/elastic/integrations/builds/16003) succeeded 12a3667b5a7495267eb4bda08a222aae4ed294df
* :broken_heart: [Build #15737](https://buildkite.com/elastic/integrations/builds/15737) failed a886dc2368baaa6ae8a364545f77e2eaedb461c2
* :broken_heart: [Build #15171](https://buildkite.com/elastic/integrations/builds/15171) failed f17173f4d8215c8aed8a38a82c8cedc769826556

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16112","number":16112,"commit":"956eeb4069f0f86913ee5e0c12d1d19a1c7020b3"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16109","number":16109,"commit":"b6e4b13f6a689c66d02563e3391e3a97954e298a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16062","number":16062,"commit":"3040ee671629d044b16cf84a880fa0ab9be3ada5"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16057","number":16057,"commit":"65777b31c2211109338eba12d6ee97a48e60345c"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16003","number":16003,"commit":"12a3667b5a7495267eb4bda08a222aae4ed294df"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15737","number":15737,"commit":"a886dc2368baaa6ae8a364545f77e2eaedb461c2"}],"number":16112}
buildkite-pr-comment-->

2024-09-19 06:52 UTC, kush-elastic commented
/test

2024-09-19 06:53 UTC, kush-elastic commented on packages/vsphere/data_stream/host/elasticsearch/ingest_pipeline/default.yml
> +  - rename:
Changes are still in snapshot.
it will not break as we have null check.

2024-09-19 06:57 UTC, ishleenk17 commented on packages/vsphere/data_stream/host/fields/fields.yml
> +        List of all the triggered alarms.
Is this mapping sorted now ?

2024-09-19 07:11 UTC, ishleenk17 commented on packages/vsphere/data_stream/host/elasticsearch/ingest_pipeline/default.yml
> +  - rename:
As discussed lets remove this change

2024-09-19 07:12 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16113)
* Commit: 956eeb4069f0f86913ee5e0c12d1d19a1c7020b3

### Failed CI Steps
* [Check integrations vsphere](https://buildkite.com/elastic/integrations/builds/16113#01920911-5c22-4828-b6c3-e6169cf618ab)

### History
* :broken_heart: [Build #16112](https://buildkite.com/elastic/integrations/builds/16112) failed 956eeb4069f0f86913ee5e0c12d1d19a1c7020b3
* :broken_heart: [Build #16109](https://buildkite.com/elastic/integrations/builds/16109) failed b6e4b13f6a689c66d02563e3391e3a97954e298a
* :broken_heart: [Build #16062](https://buildkite.com/elastic/integrations/builds/16062) failed 3040ee671629d044b16cf84a880fa0ab9be3ada5
* :broken_heart: [Build #16057](https://buildkite.com/elastic/integrations/builds/16057) failed 65777b31c2211109338eba12d6ee97a48e60345c
* :green_heart: [Build #16003](https://buildkite.com/elastic/integrations/builds/16003) succeeded 12a3667b5a7495267eb4bda08a222aae4ed294df

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16113","number":16113,"commit":"956eeb4069f0f86913ee5e0c12d1d19a1c7020b3"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16112","number":16112,"commit":"956eeb4069f0f86913ee5e0c12d1d19a1c7020b3"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16109","number":16109,"commit":"b6e4b13f6a689c66d02563e3391e3a97954e298a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16062","number":16062,"commit":"3040ee671629d044b16cf84a880fa0ab9be3ada5"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16057","number":16057,"commit":"65777b31c2211109338eba12d6ee97a48e60345c"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16003","number":16003,"commit":"12a3667b5a7495267eb4bda08a222aae4ed294df"}],"number":16113}
buildkite-pr-comment-->

2024-09-19 07:47 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16116)
* Commit: 710bc9c3753f01b0ac2472ec117d92d1816fd34f

### History
* :broken_heart: [Build #16113](https://buildkite.com/elastic/integrations/builds/16113) failed 956eeb4069f0f86913ee5e0c12d1d19a1c7020b3
* :broken_heart: [Build #16112](https://buildkite.com/elastic/integrations/builds/16112) failed 956eeb4069f0f86913ee5e0c12d1d19a1c7020b3
* :broken_heart: [Build #16109](https://buildkite.com/elastic/integrations/builds/16109) failed b6e4b13f6a689c66d02563e3391e3a97954e298a
* :broken_heart: [Build #16062](https://buildkite.com/elastic/integrations/builds/16062) failed 3040ee671629d044b16cf84a880fa0ab9be3ada5
* :broken_heart: [Build #16057](https://buildkite.com/elastic/integrations/builds/16057) failed 65777b31c2211109338eba12d6ee97a48e60345c

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16116","number":16116,"commit":"710bc9c3753f01b0ac2472ec117d92d1816fd34f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16113","number":16113,"commit":"956eeb4069f0f86913ee5e0c12d1d19a1c7020b3"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16112","number":16112,"commit":"956eeb4069f0f86913ee5e0c12d1d19a1c7020b3"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16109","number":16109,"commit":"b6e4b13f6a689c66d02563e3391e3a97954e298a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16062","number":16062,"commit":"3040ee671629d044b16cf84a880fa0ab9be3ada5"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16057","number":16057,"commit":"65777b31c2211109338eba12d6ee97a48e60345c"}],"number":16116}
buildkite-pr-comment-->

2024-09-19 08:13 UTC, kush-elastic commented on packages/vsphere/data_stream/host/fields/fields.yml
> +        List of all the triggered alarms.
Working on it.

2024-09-19 08:43 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16123)
* Commit: b6f9c2e252ffbaca0b2173ff7d02d7d054981ee5

### History
* :green_heart: [Build #16116](https://buildkite.com/elastic/integrations/builds/16116) succeeded 710bc9c3753f01b0ac2472ec117d92d1816fd34f
* :broken_heart: [Build #16113](https://buildkite.com/elastic/integrations/builds/16113) failed 956eeb4069f0f86913ee5e0c12d1d19a1c7020b3
* :broken_heart: [Build #16112](https://buildkite.com/elastic/integrations/builds/16112) failed 956eeb4069f0f86913ee5e0c12d1d19a1c7020b3
* :broken_heart: [Build #16109](https://buildkite.com/elastic/integrations/builds/16109) failed b6e4b13f6a689c66d02563e3391e3a97954e298a
* :broken_heart: [Build #16062](https://buildkite.com/elastic/integrations/builds/16062) failed 3040ee671629d044b16cf84a880fa0ab9be3ada5
* :broken_heart: [Build #16057](https://buildkite.com/elastic/integrations/builds/16057) failed 65777b31c2211109338eba12d6ee97a48e60345c

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16123","number":16123,"commit":"b6f9c2e252ffbaca0b2173ff7d02d7d054981ee5"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16116","number":16116,"commit":"710bc9c3753f01b0ac2472ec117d92d1816fd34f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16113","number":16113,"commit":"956eeb4069f0f86913ee5e0c12d1d19a1c7020b3"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16112","number":16112,"commit":"956eeb4069f0f86913ee5e0c12d1d19a1c7020b3"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16109","number":16109,"commit":"b6e4b13f6a689c66d02563e3391e3a97954e298a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16062","number":16062,"commit":"3040ee671629d044b16cf84a880fa0ab9be3ada5"}],"number":16123}
buildkite-pr-comment-->

2024-09-19 08:50 UTC, harnish-elastic approved these changes

2024-09-19 09:25 UTC, ishleenk17 commented on packages/vsphere/data_stream/datastore/manifest.yml
>    index_mode: "time_series"
@kush-elastic If this is the testing TSDB tokllkit siggests and this is what we have been following, I am good with it

2024-09-19 09:49 UTC, ishleenk17 commented on packages/vsphere/data_stream/virtualmachine/fields/fields.yml
> +    - name: triggerd_alarms.*
I am ok with it as we have to do this for CI to pass.
@lucian-ioan : Please keep this in mind as you will have to take care of these fields in datastore and Virtualmachine PR.

2024-09-19 09:49 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16129)
* Commit: 31ba5eac333f46e10da31bd201889774e7f57b4b

### History
* :green_heart: [Build #16123](https://buildkite.com/elastic/integrations/builds/16123) succeeded b6f9c2e252ffbaca0b2173ff7d02d7d054981ee5
* :green_heart: [Build #16116](https://buildkite.com/elastic/integrations/builds/16116) succeeded 710bc9c3753f01b0ac2472ec117d92d1816fd34f
* :broken_heart: [Build #16113](https://buildkite.com/elastic/integrations/builds/16113) failed 956eeb4069f0f86913ee5e0c12d1d19a1c7020b3
* :broken_heart: [Build #16112](https://buildkite.com/elastic/integrations/builds/16112) failed 956eeb4069f0f86913ee5e0c12d1d19a1c7020b3
* :broken_heart: [Build #16109](https://buildkite.com/elastic/integrations/builds/16109) failed b6e4b13f6a689c66d02563e3391e3a97954e298a
* :broken_heart: [Build #16062](https://buildkite.com/elastic/integrations/builds/16062) failed 3040ee671629d044b16cf84a880fa0ab9be3ada5

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16129","number":16129,"commit":"31ba5eac333f46e10da31bd201889774e7f57b4b"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16123","number":16123,"commit":"b6f9c2e252ffbaca0b2173ff7d02d7d054981ee5"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16116","number":16116,"commit":"710bc9c3753f01b0ac2472ec117d92d1816fd34f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16113","number":16113,"commit":"956eeb4069f0f86913ee5e0c12d1d19a1c7020b3"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16112","number":16112,"commit":"956eeb4069f0f86913ee5e0c12d1d19a1c7020b3"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16109","number":16109,"commit":"b6e4b13f6a689c66d02563e3391e3a97954e298a"}],"number":16129}
buildkite-pr-comment-->

2024-09-19 09:50 UTC, niraj-elastic requested changes

2024-09-19 09:50 UTC, niraj-elastic commented on packages/vsphere/data_stream/datastore/fields/fields.yml
> +      type: object
lets change this to group, other than that everything looks good.

2024-09-19 09:51 UTC, ishleenk17 commented on packages/vsphere/data_stream/datastore/fields/fields.yml
> +      type: object
As Kush [mentioned](https://github.com/elastic/integrations/pull/10894#discussion_r1766491448) this will be taken care in the datastore PR. We had to add these in Host PR to let the CI pass.

2024-09-19 10:13 UTC, niraj-elastic commented on packages/vsphere/data_stream/datastore/fields/fields.yml
> +      type: object
As discussed we can complete this in next PR's.

2024-09-19 10:14 UTC, niraj-elastic approved these changes
LGTM

2024-09-19 10:14 UTC, ishleenk17 approved these changes
All good, once the CI passes!

2024-09-19 10:28 UTC, lucian-ioan approved these changes
LGTM.

2024-09-19 10:31 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16130)
* Commit: 11ee48f4b15bee91a959081cb3cc5701328a5a8d

### History
* :green_heart: [Build #16129](https://buildkite.com/elastic/integrations/builds/16129) succeeded 31ba5eac333f46e10da31bd201889774e7f57b4b
* :green_heart: [Build #16123](https://buildkite.com/elastic/integrations/builds/16123) succeeded b6f9c2e252ffbaca0b2173ff7d02d7d054981ee5
* :green_heart: [Build #16116](https://buildkite.com/elastic/integrations/builds/16116) succeeded 710bc9c3753f01b0ac2472ec117d92d1816fd34f
* :broken_heart: [Build #16113](https://buildkite.com/elastic/integrations/builds/16113) failed 956eeb4069f0f86913ee5e0c12d1d19a1c7020b3
* :broken_heart: [Build #16112](https://buildkite.com/elastic/integrations/builds/16112) failed 956eeb4069f0f86913ee5e0c12d1d19a1c7020b3
* :broken_heart: [Build #16109](https://buildkite.com/elastic/integrations/builds/16109) failed b6e4b13f6a689c66d02563e3391e3a97954e298a

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16130","number":16130,"commit":"11ee48f4b15bee91a959081cb3cc5701328a5a8d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16129","number":16129,"commit":"31ba5eac333f46e10da31bd201889774e7f57b4b"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16123","number":16123,"commit":"b6f9c2e252ffbaca0b2173ff7d02d7d054981ee5"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16116","number":16116,"commit":"710bc9c3753f01b0ac2472ec117d92d1816fd34f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16113","number":16113,"commit":"956eeb4069f0f86913ee5e0c12d1d19a1c7020b3"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16112","number":16112,"commit":"956eeb4069f0f86913ee5e0c12d1d19a1c7020b3"}],"number":16130}
buildkite-pr-comment-->

2024-09-19 10:37 UTC, merged

2024-09-19 11:16 UTC, niraj-elastic reviewed
LGTM