[Fortinet] updating fortinet ecs version and adding event.original options
elastic/integrations pull request #1092
Opened 2021-06-07 10:32 UTC by P1llus

## What does this PR do?

Updates package ECS version to 1.10.
Sync module changes to packages if any.
Adds Preserve Raw event functionality if not already exists.
Adds pipeline tests if missing.
Adds missing tags + moving tags to advanced settings.
Adds possibility to add custom processors.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] If I'm introducing a new feature, I have modified the Kibana version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^7.13.0`).

## Related issues

- Relates #994

2021-06-07 10:32 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2021-06-07 10:57 UTC, elasticmachine commented
## :broken_heart: Tests Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1092/detail/PR-1092/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1092/detail/PR-1092/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1092/detail/PR-1092/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1092/detail/PR-1092/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_1092.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #1092 opened`



* Start Time: 2021-06-07T10:32:36.920+0000


* Duration: 25 min 45 sec


* Commit: 8a55458276caf6971f22c267bfd73696adcfd42c



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 3  |
| Passed       | 9  |
| Skipped      | 0 |
| Total        | 12   |


#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/PR-1092/buildTimeGraph/png)


![Image of Tests](https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/PR-1092/1/testReport/history/countGraph/png?start=0&amp;end=25)


</p>
</details>

<!-- TEST RESULTS IF ANY-->

  ### Test errors [![3](https://img.shields.io/badge/3%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1092/detail/PR-1092/1//tests)
<details><summary>Expand to view the tests failures</summary><p>
    
    
##### `system test: tcp – fortinet.fortimanager`


<ul>
<li>no error details</li>
<details><summary>Expand to view the stacktrace</summary><p>

```
 one or more errors found in documents stored in logs-fortinet.fortimanager-ep data stream: [0] field "url.extension" is undefined
[1] field "url.fragment" is undefined
[2] field "url.scheme" is undefined 
 ```
</p></details>
</ul>
    
##### `system test: udp – fortinet.fortimanager`


<ul>
<li>no error details</li>
<details><summary>Expand to view the stacktrace</summary><p>

```
 one or more errors found in documents stored in logs-fortinet.fortimanager-ep data stream: [0] field "url.extension" is undefined
[1] field "url.fragment" is undefined
[2] field "url.scheme" is undefined 
 ```
</p></details>
</ul>
    
##### `system test: logfile – fortinet.fortimanager`


<ul>
<li>no error details</li>
<details><summary>Expand to view the stacktrace</summary><p>

```
 one or more errors found in documents stored in logs-fortinet.fortimanager-ep data stream: [0] field "url.extension" is undefined
[1] field "url.fragment" is undefined
[2] field "url.scheme" is undefined 
 ```
</p></details>
</ul>
    
</p></details>


<!-- STEPS ERRORS IF ANY -->









### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1092/detail/PR-1092/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Test integration: fortinet`
<ul>
<li>Took 15 min 2 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-1092/runs/1/steps/421/log/?start=0">here</a></li>
<li>Description: <code>                                eval "$(../../build/elastic-package stack shellinit)"                                ../../build/elastic-package test -v --report-format xUnit --report-output file                                </code></l1>
</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-06-07T10:55:54.078Z] 2021/06/07 10:55:53 DEBUG Policy revision assigned to the agent (ID: 6b9b0b59-0b84-4f3d-a236-f39e41f7a499)...
[2021-06-07T10:55:54.078Z] 2021/06/07 10:55:53 DEBUG checking for expected data in data stream...
[2021-06-07T10:55:54.078Z] 2021/06/07 10:55:53 DEBUG found 0 hits in logs-fortinet.fortimanager-ep data stream
[2021-06-07T10:55:55.064Z] 2021/06/07 10:55:54 DEBUG found 0 hits in logs-fortinet.fortimanager-ep data stream
[2021-06-07T10:55:56.050Z] 2021/06/07 10:55:55 DEBUG found 0 hits in logs-fortinet.fortimanager-ep data stream
[2021-06-07T10:55:56.998Z] 2021/06/07 10:55:56 DEBUG found 100 hits in logs-fortinet.fortimanager-ep data stream
[2021-06-07T10:56:53.291Z] 2021/06/07 10:56:47 DEBUG reassigning original policy back to agent...
[2021-06-07T10:56:53.291Z] 2021/06/07 10:56:47 DEBUG PUT http://127.0.0.1:5601/api/fleet/agents/6b9b0b59-0b84-4f3d-a236-f39e41f7a499/reassign
[2021-06-07T10:56:53.291Z] 2021/06/07 10:56:48 DEBUG GET http://127.0.0.1:5601/api/fleet/agents/6b9b0b59-0b84-4f3d-a236-f39e41f7a499
[2021-06-07T10:56:53.291Z] 2021/06/07 10:56:48 DEBUG Wait until the policy (ID: ec4d4090-c77c-11eb-80a3-b704ad7abce5, revision: 1) is assigned to the agent (ID: 6b9b0b59-0b84-4f3d-a236-f39e41f7a499)...
[2021-06-07T10:56:53.291Z] 2021/06/07 10:56:50 DEBUG GET http://127.0.0.1:5601/api/fleet/agents/6b9b0b59-0b84-4f3d-a236-f39e41f7a499
[2021-06-07T10:56:53.292Z] 2021/06/07 10:56:50 DEBUG Wait until the policy (ID: ec4d4090-c77c-11eb-80a3-b704ad7abce5, revision: 1) is assigned to the agent (ID: 6b9b0b59-0b84-4f3d-a236-f39e41f7a499)...
[2021-06-07T10:56:53.292Z] 2021/06/07 10:56:52 DEBUG GET http://127.0.0.1:5601/api/fleet/agents/6b9b0b59-0b84-4f3d-a236-f39e41f7a499
[2021-06-07T10:56:53.292Z] 2021/06/07 10:56:52 DEBUG Wait until the policy (ID: ec4d4090-c77c-11eb-80a3-b704ad7abce5, revision: 1) is assigned to the agent (ID: 6b9b0b59-0b84-4f3d-a236-f39e41f7a499)...
[2021-06-07T10:56:54.673Z] 2021/06/07 10:56:54 DEBUG GET http://127.0.0.1:5601/api/fleet/agents/6b9b0b59-0b84-4f3d-a236-f39e41f7a499
[2021-06-07T10:56:54.933Z] 2021/06/07 10:56:54 DEBUG Policy revision assigned to the agent (ID: 6b9b0b59-0b84-4f3d-a236-f39e41f7a499)...
[2021-06-07T10:56:54.933Z] 2021/06/07 10:56:54 DEBUG deleting test policy...
[2021-06-07T10:56:54.933Z] 2021/06/07 10:56:54 DEBUG POST http://127.0.0.1:5601/api/fleet/agent_policies/delete
[2021-06-07T10:56:56.313Z] 2021/06/07 10:56:56 DEBUG tearing down service...
[2021-06-07T10:56:56.313Z] 2021/06/07 10:56:56 DEBUG tearing down service using docker compose runner
[2021-06-07T10:56:56.313Z] 2021/06/07 10:56:56 DEBUG running command: /usr/local/bin/docker-compose -f /var/lib/jenkins/workspace/est-manager_integrations_PR-1092/src/github.com/elastic/integrations/packages/fortinet/_dev/deploy/docker/docker-compose.yml -p elastic-package-service down
[2021-06-07T10:56:56.882Z] Stopping elastic-package-service_fortinet-clientendpoint-udp_1 ... 
[2021-06-07T10:56:56.882Z] Stopping elastic-package-service_fortinet-fortimail-tcp_1      ... 
[2021-06-07T10:56:56.882Z] Stopping elastic-package-service_fortinet-fortimanager-udp_1   ... 
[2021-06-07T10:56:56.882Z] Stopping elastic-package-service_fortinet-fortimanager-tcp_1   ... 
[2021-06-07T10:56:56.882Z] Stopping elastic-package-service_fortinet-firewall-udp_1       ... 
[2021-06-07T10:56:56.882Z] Stopping elastic-package-service_fortinet-firewall-tcp_1       ... 
[2021-06-07T10:56:56.882Z] Stopping elastic-package-service_fortinet-clientendpoint-tcp_1 ... 
[2021-06-07T10:56:56.882Z] Stopping elastic-package-service_fortinet-fortimail-udp_1      ... 
[2021-06-07T10:56:58.792Z] 
Stopping elastic-package-service_fortinet-clientendpoint-udp_1  [...]

2021-06-14 15:04 UTC, leehinman requested changes

2021-06-14 15:04 UTC, leehinman commented on packages/fortinet/data_stream/firewall/agent/stream/log.yml.hbs
> +{{/if}}
Do we need all these if statements?  I think we can always have `processors:` object, even if the list is empty.

2021-06-14 15:06 UTC, P1llus commented on packages/fortinet/data_stream/firewall/agent/stream/log.yml.hbs
> +{{/if}}
Unfortunately leaving it empty breaks system tests, I think @marc-gr can confirm this as well

2021-06-14 15:30 UTC, leehinman commented on packages/fortinet/data_stream/firewall/agent/stream/log.yml.hbs
> +{{/if}}
bummer, never mind then.

2021-06-14 15:30 UTC, leehinman approved these changes

2021-06-14 15:32 UTC, merged