Issue 10875
elastic/integrations pull request #10939
Opened 2024-08-29 18:58 UTC by agithomas

## Proposed commit message

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## How to test this PR locally

## Related issues

- 

## Screenshots

2024-08-29 19:16 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15208)
* Commit: 1cc9839f8ead59126e2f99461580abe920ca0f43

### Failed CI Steps
* [Check integrations aws_bedrock](https://buildkite.com/elastic/integrations/builds/15208#01919f85-debf-4756-9ff0-f8dc6764d697)

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15208","number":15208,"commit":"1cc9839f8ead59126e2f99461580abe920ca0f43"}],"number":15208}
buildkite-pr-comment-->

2024-08-29 19:43 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15209)
* Commit: e15fafc1b595c23fdacdd84c4b89c9739b5dfcf8

### Failed CI Steps
* [Check integrations aws_bedrock](https://buildkite.com/elastic/integrations/builds/15209#01919f9d-c4b1-4520-b8ba-bf591aadb15a)

### History
* :broken_heart: [Build #15208](https://buildkite.com/elastic/integrations/builds/15208) failed 1cc9839f8ead59126e2f99461580abe920ca0f43

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15209","number":15209,"commit":"e15fafc1b595c23fdacdd84c4b89c9739b5dfcf8"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15208","number":15208,"commit":"1cc9839f8ead59126e2f99461580abe920ca0f43"}],"number":15209}
buildkite-pr-comment-->

2024-08-30 04:56 UTC, agithomas commented
/test

2024-08-30 05:22 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15223)
* Commit: 0545ddb23aa067db3e20014cd5df0ecee1b7e92b

### Failed CI Steps
* [Check integrations aws_bedrock](https://buildkite.com/elastic/integrations/builds/15223#0191a1af-e0d8-40a8-b26f-aea715dc87be)

### History
* :broken_heart: [Build #15209](https://buildkite.com/elastic/integrations/builds/15209) failed e15fafc1b595c23fdacdd84c4b89c9739b5dfcf8
* :broken_heart: [Build #15208](https://buildkite.com/elastic/integrations/builds/15208) failed 1cc9839f8ead59126e2f99461580abe920ca0f43

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15223","number":15223,"commit":"0545ddb23aa067db3e20014cd5df0ecee1b7e92b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15209","number":15209,"commit":"e15fafc1b595c23fdacdd84c4b89c9739b5dfcf8"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15208","number":15208,"commit":"1cc9839f8ead59126e2f99461580abe920ca0f43"}],"number":15223}
buildkite-pr-comment-->

2024-08-30 06:40 UTC, agithomas commented
/test

2024-08-30 06:56 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15225)
* Commit: 0545ddb23aa067db3e20014cd5df0ecee1b7e92b

### Failed CI Steps
* [Check integrations aws_bedrock](https://buildkite.com/elastic/integrations/builds/15225#0191a207-ceb3-47af-8967-401c82aa29da)

### History
* :broken_heart: [Build #15223](https://buildkite.com/elastic/integrations/builds/15223) failed 0545ddb23aa067db3e20014cd5df0ecee1b7e92b
* :broken_heart: [Build #15209](https://buildkite.com/elastic/integrations/builds/15209) failed e15fafc1b595c23fdacdd84c4b89c9739b5dfcf8
* :broken_heart: [Build #15208](https://buildkite.com/elastic/integrations/builds/15208) failed 1cc9839f8ead59126e2f99461580abe920ca0f43

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15225","number":15225,"commit":"0545ddb23aa067db3e20014cd5df0ecee1b7e92b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15223","number":15223,"commit":"0545ddb23aa067db3e20014cd5df0ecee1b7e92b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15209","number":15209,"commit":"e15fafc1b595c23fdacdd84c4b89c9739b5dfcf8"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15208","number":15208,"commit":"1cc9839f8ead59126e2f99461580abe920ca0f43"}],"number":15225}
buildkite-pr-comment-->

2024-08-30 09:45 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-08-30 09:45 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15231)
* Commit: 49aa4a3eb18a15627c6f2ed23426312cfe33be3d

### History
* :broken_heart: [Build #15225](https://buildkite.com/elastic/integrations/builds/15225) failed 0545ddb23aa067db3e20014cd5df0ecee1b7e92b
* :broken_heart: [Build #15223](https://buildkite.com/elastic/integrations/builds/15223) failed 0545ddb23aa067db3e20014cd5df0ecee1b7e92b
* :broken_heart: [Build #15209](https://buildkite.com/elastic/integrations/builds/15209) failed e15fafc1b595c23fdacdd84c4b89c9739b5dfcf8
* :broken_heart: [Build #15208](https://buildkite.com/elastic/integrations/builds/15208) failed 1cc9839f8ead59126e2f99461580abe920ca0f43

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15231","number":15231,"commit":"49aa4a3eb18a15627c6f2ed23426312cfe33be3d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15225","number":15225,"commit":"0545ddb23aa067db3e20014cd5df0ecee1b7e92b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15223","number":15223,"commit":"0545ddb23aa067db3e20014cd5df0ecee1b7e92b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15209","number":15209,"commit":"e15fafc1b595c23fdacdd84c4b89c9739b5dfcf8"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15208","number":15208,"commit":"1cc9839f8ead59126e2f99461580abe920ca0f43"}],"number":15231}
buildkite-pr-comment-->

2024-08-30 11:27 UTC, muthu-mps commented
The logs dashboard uses the `gen_ai.*` fields for prompt text and token_usage and for the response completion text the `aws.bedrock.invocation.*` field is used. Is it possible to ingest the response text in the gen_ai.* field?

2024-08-30 11:38 UTC, agithomas commented
> The logs dashboard uses the `gen_ai.*` fields for prompt text and token_usage and for the response completion text the `aws.bedrock.invocation.*` field is used. Is it possible to ingest the response text in the gen_ai.* field?

After referring to this [comment](https://github.com/elastic/integrations/pull/9667#pullrequestreview-2037126807), field names beginning with `gen_ai` are proposed OTEL fields. 

Since I could not find an equivalent name in the proposed list, i kep the field name prefix as `aws_bedrock.invocation.output` instead of `gen_ai.`

```

2024-08-30 12:43 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15246)
* Commit: 87708bef1a2c49f2f8a3e011c76024013decced3

### History
* :green_heart: [Build #15231](https://buildkite.com/elastic/integrations/builds/15231) succeeded 49aa4a3eb18a15627c6f2ed23426312cfe33be3d
* :broken_heart: [Build #15225](https://buildkite.com/elastic/integrations/builds/15225) failed 0545ddb23aa067db3e20014cd5df0ecee1b7e92b
* :broken_heart: [Build #15223](https://buildkite.com/elastic/integrations/builds/15223) failed 0545ddb23aa067db3e20014cd5df0ecee1b7e92b
* :broken_heart: [Build #15209](https://buildkite.com/elastic/integrations/builds/15209) failed e15fafc1b595c23fdacdd84c4b89c9739b5dfcf8
* :broken_heart: [Build #15208](https://buildkite.com/elastic/integrations/builds/15208) failed 1cc9839f8ead59126e2f99461580abe920ca0f43

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15246","number":15246,"commit":"87708bef1a2c49f2f8a3e011c76024013decced3"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15231","number":15231,"commit":"49aa4a3eb18a15627c6f2ed23426312cfe33be3d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15225","number":15225,"commit":"0545ddb23aa067db3e20014cd5df0ecee1b7e92b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15223","number":15223,"commit":"0545ddb23aa067db3e20014cd5df0ecee1b7e92b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15209","number":15209,"commit":"e15fafc1b595c23fdacdd84c4b89c9739b5dfcf8"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15208","number":15208,"commit":"1cc9839f8ead59126e2f99461580abe920ca0f43"}],"number":15246}
buildkite-pr-comment-->

2024-08-30 13:23 UTC, andrewkroh commented on packages/aws_bedrock/changelog.yml
> +    - description: Add new field having LLM text model response. Add visualization for LLM prompt and response.
I suggest mentioning the name of the new field so users know.

```suggestion
    - description: Add new field `aws_bedrock.invocation.output.completion_text` having LLM text model response. Add visualization for LLM prompt and response.
```

2024-09-02 05:40 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15285)
* Commit: 0c44b606cf4ddb053a45d94d7595aa467648bed4

### History
* :green_heart: [Build #15246](https://buildkite.com/elastic/integrations/builds/15246) succeeded 87708bef1a2c49f2f8a3e011c76024013decced3
* :green_heart: [Build #15231](https://buildkite.com/elastic/integrations/builds/15231) succeeded 49aa4a3eb18a15627c6f2ed23426312cfe33be3d
* :broken_heart: [Build #15225](https://buildkite.com/elastic/integrations/builds/15225) failed 0545ddb23aa067db3e20014cd5df0ecee1b7e92b
* :broken_heart: [Build #15223](https://buildkite.com/elastic/integrations/builds/15223) failed 0545ddb23aa067db3e20014cd5df0ecee1b7e92b
* :broken_heart: [Build #15209](https://buildkite.com/elastic/integrations/builds/15209) failed e15fafc1b595c23fdacdd84c4b89c9739b5dfcf8
* :broken_heart: [Build #15208](https://buildkite.com/elastic/integrations/builds/15208) failed 1cc9839f8ead59126e2f99461580abe920ca0f43

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15285","number":15285,"commit":"0c44b606cf4ddb053a45d94d7595aa467648bed4"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15246","number":15246,"commit":"87708bef1a2c49f2f8a3e011c76024013decced3"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15231","number":15231,"commit":"49aa4a3eb18a15627c6f2ed23426312cfe33be3d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15225","number":15225,"commit":"0545ddb23aa067db3e20014cd5df0ecee1b7e92b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15223","number":15223,"commit":"0545ddb23aa067db3e20014cd5df0ecee1b7e92b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15209","number":15209,"commit":"e15fafc1b595c23fdacdd84c4b89c9739b5dfcf8"}],"number":15285}
buildkite-pr-comment-->

2024-09-02 05:51 UTC, muthu-mps commented on packages/aws_bedrock/data_stream/invocation/elasticsearch/ingest_pipeline/default.yml
> +            completionText.setLength(32766);
- We try to trim the characters above `32766`. Is there any difference in using the `ignore_above` value set in the fields.yml?
- I am not sure how we define value for `ignore_above` as we would also get non-ascii characters in the response.

2024-09-02 06:02 UTC, muthu-mps commented on packages/aws_bedrock/data_stream/invocation/elasticsearch/ingest_pipeline/default.yml
> +            completionText.setLength(32766);
`ignore_above` skips the field itself when exceeding the limit. By this way we can have the trimmed version of the response.

2024-09-02 06:12 UTC, efd6 commented on packages/aws_bedrock/data_stream/invocation/elasticsearch/ingest_pipeline/default.yml
> +                if (block instanceof Map) {
I'd like it if this were inverted and we `continue`d in the case that the condition fires. This reduces the indent level. Similarly in the major else block below.

2024-09-02 06:22 UTC, muthu-mps commented on packages/aws_bedrock/kibana/search/aws_bedrock-a8901990-aaf9-469e-aec7-5e6c93d820dc.json
> +    "typeMigrationVersion": "10.2.0"
The "typeMigrationVersion": "8.9.0" in the dashboard file and it is `10.2.0` is search. I hope this doesn't break things with minimum supported version.

2024-09-02 06:36 UTC, harnish-elastic commented on packages/aws_bedrock/img/aws_bedrock_chat_image.png
Added image is not containing Dataset filter. Can we update the screenshot?

2024-09-02 07:50 UTC, agithomas commented on packages/aws_bedrock/kibana/search/aws_bedrock-a8901990-aaf9-469e-aec7-5e6c93d820dc.json
> +    "typeMigrationVersion": "10.2.0"
The dashboard is exported with `8.13.4` version.

2024-09-02 07:51 UTC, agithomas commented on packages/aws_bedrock/kibana/search/aws_bedrock-a8901990-aaf9-469e-aec7-5e6c93d820dc.json
> +    "typeMigrationVersion": "10.2.0"
No issues was observed during installing the package on 8.13.4 stack

2024-09-02 08:58 UTC, agithomas commented on packages/aws_bedrock/img/aws_bedrock_chat_image.png
Updated the screenshot.

2024-09-02 09:01 UTC, agithomas commented on packages/aws_bedrock/data_stream/invocation/elasticsearch/ingest_pipeline/default.yml
> +                if (block instanceof Map) {
Thanks. I have made the change. Not sure, if i understood incorrectly,  in the else clause, as there is no iteration, `continue` cannot be used. 

Please correct me, if i misunderstood.

2024-09-02 09:17 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15292)
* Commit: 89c27f2a7d9176aad98b5b3ad44e9c8572046fe5

### History
* :green_heart: [Build #15285](https://buildkite.com/elastic/integrations/builds/15285) succeeded 0c44b606cf4ddb053a45d94d7595aa467648bed4
* :green_heart: [Build #15246](https://buildkite.com/elastic/integrations/builds/15246) succeeded 87708bef1a2c49f2f8a3e011c76024013decced3
* :green_heart: [Build #15231](https://buildkite.com/elastic/integrations/builds/15231) succeeded 49aa4a3eb18a15627c6f2ed23426312cfe33be3d
* :broken_heart: [Build #15225](https://buildkite.com/elastic/integrations/builds/15225) failed 0545ddb23aa067db3e20014cd5df0ecee1b7e92b
* :broken_heart: [Build #15223](https://buildkite.com/elastic/integrations/builds/15223) failed 0545ddb23aa067db3e20014cd5df0ecee1b7e92b
* :broken_heart: [Build #15209](https://buildkite.com/elastic/integrations/builds/15209) failed e15fafc1b595c23fdacdd84c4b89c9739b5dfcf8

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15292","number":15292,"commit":"89c27f2a7d9176aad98b5b3ad44e9c8572046fe5"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15285","number":15285,"commit":"0c44b606cf4ddb053a45d94d7595aa467648bed4"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15246","number":15246,"commit":"87708bef1a2c49f2f8a3e011c76024013decced3"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15231","number":15231,"commit":"49aa4a3eb18a15627c6f2ed23426312cfe33be3d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15225","number":15225,"commit":"0545ddb23aa067db3e20014cd5df0ecee1b7e92b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15223","number":15223,"commit":"0545ddb23aa067db3e20014cd5df0ecee1b7e92b"}],"number":15292}
buildkite-pr-comment-->

2024-09-02 17:14 UTC, harnish-elastic requested changes

2024-09-02 17:14 UTC, harnish-elastic commented on packages/aws_bedrock/kibana/search/aws_bedrock-a8901990-aaf9-469e-aec7-5e6c93d820dc.json
AWS Bedrock is using kibana `8.13.0` version as well format version is `3.0.2`, so you can unlink saved search from library and export it (make sure to delete this file). Can you do that here?

2024-09-02 17:14 UTC, harnish-elastic commented on packages/aws_bedrock/kibana/search/aws_bedrock-102e7881-0c3f-4996-91e6-453f682df2f2.json
Same here, we can remove/delete this file after exporting.

2024-09-02 17:14 UTC, harnish-elastic commented on packages/aws_bedrock/data_stream/invocation/_dev/test/pipeline/test-aws-bedrock.log-expected.json
Strange: Without doing a log addition/updation in the `test-aws-bedrock.log` file pipeline tests generated?

2024-09-02 22:14 UTC, efd6 commented on packages/aws_bedrock/data_stream/invocation/elasticsearch/ingest_pipeline/default.yml
> +                if (block instanceof Map) {
Sorry, you are correct.

2024-09-03 03:21 UTC, agithomas commented on packages/aws_bedrock/data_stream/invocation/_dev/test/pipeline/test-aws-bedrock.log-expected.json
Please refer here.

https://github.com/elastic/integrations/tree/main/packages/aws_bedrock/data_stream/invocation/_dev/test/pipeline

2024-09-03 04:24 UTC, agithomas commented on packages/aws_bedrock/kibana/search/aws_bedrock-a8901990-aaf9-469e-aec7-5e6c93d820dc.json
Resolved

2024-09-03 04:24 UTC, agithomas commented on packages/aws_bedrock/kibana/search/aws_bedrock-102e7881-0c3f-4996-91e6-453f682df2f2.json
Resolved

2024-09-03 04:42 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15341)
* Commit: e69d22e78d14c62fe7b9110b461f2f0b9a1634bf

### History
* :green_heart: [Build #15292](https://buildkite.com/elastic/integrations/builds/15292) succeeded 89c27f2a7d9176aad98b5b3ad44e9c8572046fe5
* :green_heart: [Build #15285](https://buildkite.com/elastic/integrations/builds/15285) succeeded 0c44b606cf4ddb053a45d94d7595aa467648bed4
* :green_heart: [Build #15246](https://buildkite.com/elastic/integrations/builds/15246) succeeded 87708bef1a2c49f2f8a3e011c76024013decced3
* :green_heart: [Build #15231](https://buildkite.com/elastic/integrations/builds/15231) succeeded 49aa4a3eb18a15627c6f2ed23426312cfe33be3d
* :broken_heart: [Build #15225](https://buildkite.com/elastic/integrations/builds/15225) failed 0545ddb23aa067db3e20014cd5df0ecee1b7e92b
* :broken_heart: [Build #15223](https://buildkite.com/elastic/integrations/builds/15223) failed 0545ddb23aa067db3e20014cd5df0ecee1b7e92b

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15341","number":15341,"commit":"e69d22e78d14c62fe7b9110b461f2f0b9a1634bf"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15292","number":15292,"commit":"89c27f2a7d9176aad98b5b3ad44e9c8572046fe5"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15285","number":15285,"commit":"0c44b606cf4ddb053a45d94d7595aa467648bed4"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15246","number":15246,"commit":"87708bef1a2c49f2f8a3e011c76024013decced3"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15231","number":15231,"commit":"49aa4a3eb18a15627c6f2ed23426312cfe33be3d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15225","number":15225,"commit":"0545ddb23aa067db3e20014cd5df0ecee1b7e92b"}],"number":15341}
buildkite-pr-comment-->

2024-09-03 05:36 UTC, harnish-elastic approved these changes

2024-09-03 05:38 UTC, muthu-mps approved these changes
LGTM!

2024-09-04 05:33 UTC, efd6 commented on packages/aws_bedrock/data_stream/invocation/elasticsearch/ingest_pipeline/default.yml
> +      source: |
The script can be simplified considerably

```diff
diff --git a/packages/aws_bedrock/data_stream/invocation/elasticsearch/ingest_pipeline/default.yml b/packages/aws_bedrock/data_stream/invocation/elasticsearch/ingest_pipeline/default.yml
index b650cda473..3d89c4e6b8 100644
--- a/packages/aws_bedrock/data_stream/invocation/elasticsearch/ingest_pipeline/default.yml
+++ b/packages/aws_bedrock/data_stream/invocation/elasticsearch/ingest_pipeline/default.yml
@@ -457,41 +457,31 @@ processors:
                 if (block.containsKey('delta') && block.delta instanceof Map && block.delta.containsKey('text')) {
                   // Titan model response
                   completionText.append(block.delta.text);
-                } else if (block.containsKey('outputs') && block.outputs instanceof List) {
+                } else if (block.outputs instanceof List) {
                   // Mistral model response
                   for (def cont : block.outputs) {
-                    if (cont instanceof Map && cont.containsKey('text')) {
+                    if (cont.text instanceof String) {
                         completionText.append(cont.text);
                     }
                   }
-                } else if (block.containsKey('generation')) {
+                } else if (block.generation != null) {
                   // Llama3 model response
                   completionText.append(block.generation);
-                } else if (block.containsKey('outputText')) {
-                    // Titan Text G1 - Express response
-                    completionText.append(block.outputText);
+                } else if (block.outputText != null) {
+                  // Titan Text G1 - Express response
+                  completionText.append(block.outputText);
                 }
               }
-            }else if (ctx.aws_bedrock.invocation.output.output_body_json instanceof Map) {
+            } else if (ctx.aws_bedrock.invocation.output.output_body_json instanceof Map) {
               def block = ctx.aws_bedrock.invocation.output.output_body_json;
-              if (block instanceof Map) {
-                Map blockMap = (Map) block;
-                if (blockMap.containsKey('output') && blockMap.output instanceof Map) {
-                  Map outputMap = (Map) blockMap.output;
-                  if (outputMap.containsKey('message') && outputMap.message instanceof Map) {
-                    Map messageMap = (Map) outputMap.message;
-                    if (messageMap.containsKey('content') && messageMap.content instanceof List) {
-                      List contentList = (List) messageMap.content;
-                      for (def cont : contentList) {
-                        if (cont.containsKey('text')) {
-                          completionText.append(cont.text);
-                        }
-                      }
-                    }
+              if (block.output?.message?.content instanceof List) {
+                for (def cont : block.output.message.content) {
+                  if (cont.containsKey('text')) {
+                    completionText.append(cont.text);
                   }
                 }
               }
-            }else if (ctx.aws_bedrock.invocation.output.output_body_json instanceof String){
+            } else if (ctx.aws_bedrock.invocation.output.output_body_json instanceof String){
               completionText.append(ctx.aws_bedrock.invocation.output.output_body_json)
             }
           }
```
Are these reasonable changes IYO?

2024-09-04 05:36 UTC, efd6 approved these changes
Approving with or without change in previous comment.

2024-09-04 06:07 UTC, merged

2024-09-04 06:09 UTC, agithomas commented on packages/aws_bedrock/data_stream/invocation/elasticsearch/ingest_pipeline/default.yml
> +      source: |
We had discussed  and agreed that it is safer to keep the structure in the PR is safe as the shape of the output document is not consistent across various LLM text models.

2024-09-04 06:21 UTC, elasticmachine commented
Package aws_bedrock - 0.6.0 containing this change is available at https://epr.elastic.co/search?package=aws_bedrock