[vSphere][virtualmachine] Add support for additional metrics
elastic/integrations pull request #10942
Opened 2024-08-30 08:04 UTC by lucian-ioan

## Proposed commit message
Following beats code changes in https://github.com/elastic/beats/pull/40485, the following metrics need integration update:

Metrics | API | Field Mappings
-- | -- | --
VirtualMachine.Summary.QuickStats.UptimeSeconds | Summary | virtualmachine.uptime
VirtualMachine.Summary.OverallStatus | Summary | virtualmachine.status
VirtualMachine.Summary.Datastore| Summary | virtualmachine.datastore.names

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## How to test this PR locally

## Related issues

- Closes https://github.com/elastic/obs-integration-team/issues/35

## Screenshots

2024-08-30 08:26 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-08-30 08:26 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15227)
* Commit: 8e782c61e30a14f0cfbef998e2ea8bf63cd95c96

cc @lucian-ioan

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15227","number":15227,"commit":"8e782c61e30a14f0cfbef998e2ea8bf63cd95c96"}],"number":15227}
buildkite-pr-comment-->

2024-08-30 10:08 UTC, lalit-satapathy commented on packages/vsphere/data_stream/virtualmachine/fields/fields.yml
> -      metric_type: gauge
Any reason to remove these metric_types?

2024-09-02 07:08 UTC, ishleenk17 commented on packages/vsphere/data_stream/virtualmachine/fields/fields.yml
> -      dimension: true
@lucian-ioan : I suppose you are using the fields.yml directly from the beats code. 
That would not be correct as we don't consider tsdb there. 
Also, for any new fields please keep TSDB into consideration.

2024-09-02 07:08 UTC, ishleenk17 commented on packages/vsphere/data_stream/virtualmachine/sample_event.json
>          "virtualmachine": {
Are these events autogenerated by system tests ?
Looks like these are being used from beats code ?

2024-09-02 09:35 UTC, lucian-ioan commented on packages/vsphere/data_stream/virtualmachine/fields/fields.yml
> -      metric_type: gauge
No, reverting, tested first with beats code directly.

2024-09-02 09:45 UTC, lucian-ioan commented on packages/vsphere/data_stream/virtualmachine/sample_event.json
>          "virtualmachine": {
Tested with beats code, regenerated it now.

2024-09-02 10:14 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15295)
* Commit: 953b653d499bdf78cd1eb65550c6eb94a3620180

### History
* :green_heart: [Build #15227](https://buildkite.com/elastic/integrations/builds/15227) succeeded 8e782c61e30a14f0cfbef998e2ea8bf63cd95c96

cc @lucian-ioan

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15295","number":15295,"commit":"953b653d499bdf78cd1eb65550c6eb94a3620180"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15227","number":15227,"commit":"8e782c61e30a14f0cfbef998e2ea8bf63cd95c96"}],"number":15295}
buildkite-pr-comment-->

2024-09-18 08:56 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16042)
* Commit: 56c61bdc47f8d31364686bbad6b89370605e234c

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/16042#01920457-f725-4d1f-b094-39acaa200f40)

### History
* :broken_heart: [Build #16040](https://buildkite.com/elastic/integrations/builds/16040) failed e1af4afc6e3c6f72744adbbbbec6cf369cee49bd
* :green_heart: [Build #15295](https://buildkite.com/elastic/integrations/builds/15295) succeeded 953b653d499bdf78cd1eb65550c6eb94a3620180
* :green_heart: [Build #15227](https://buildkite.com/elastic/integrations/builds/15227) succeeded 8e782c61e30a14f0cfbef998e2ea8bf63cd95c96

cc @lucian-ioan

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16042","number":16042,"commit":"56c61bdc47f8d31364686bbad6b89370605e234c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16040","number":16040,"commit":"e1af4afc6e3c6f72744adbbbbec6cf369cee49bd"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15295","number":15295,"commit":"953b653d499bdf78cd1eb65550c6eb94a3620180"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15227","number":15227,"commit":"8e782c61e30a14f0cfbef998e2ea8bf63cd95c96"}],"number":16042}
buildkite-pr-comment-->

2024-09-18 08:59 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16044)
* Commit: 28978e01cb2e7e5a56a535631c9722664fae6c34

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/16044#01920459-f687-4d2a-bd20-3d66184612bd)

### History
* :broken_heart: [Build #16042](https://buildkite.com/elastic/integrations/builds/16042) failed 56c61bdc47f8d31364686bbad6b89370605e234c
* :broken_heart: [Build #16040](https://buildkite.com/elastic/integrations/builds/16040) failed e1af4afc6e3c6f72744adbbbbec6cf369cee49bd
* :green_heart: [Build #15295](https://buildkite.com/elastic/integrations/builds/15295) succeeded 953b653d499bdf78cd1eb65550c6eb94a3620180
* :green_heart: [Build #15227](https://buildkite.com/elastic/integrations/builds/15227) succeeded 8e782c61e30a14f0cfbef998e2ea8bf63cd95c96

cc @lucian-ioan

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16044","number":16044,"commit":"28978e01cb2e7e5a56a535631c9722664fae6c34"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16042","number":16042,"commit":"56c61bdc47f8d31364686bbad6b89370605e234c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16040","number":16040,"commit":"e1af4afc6e3c6f72744adbbbbec6cf369cee49bd"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15295","number":15295,"commit":"953b653d499bdf78cd1eb65550c6eb94a3620180"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15227","number":15227,"commit":"8e782c61e30a14f0cfbef998e2ea8bf63cd95c96"}],"number":16044}
buildkite-pr-comment-->

2024-09-18 09:06 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16045)
* Commit: 6c72eb4ea29727e44cbedcf5c5b3b75603f493df

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/16045#01920461-14a3-4621-9a9e-c41f33e934c9)

### History
* :broken_heart: [Build #16044](https://buildkite.com/elastic/integrations/builds/16044) failed 28978e01cb2e7e5a56a535631c9722664fae6c34
* :broken_heart: [Build #16042](https://buildkite.com/elastic/integrations/builds/16042) failed 56c61bdc47f8d31364686bbad6b89370605e234c
* :broken_heart: [Build #16040](https://buildkite.com/elastic/integrations/builds/16040) failed e1af4afc6e3c6f72744adbbbbec6cf369cee49bd
* :green_heart: [Build #15295](https://buildkite.com/elastic/integrations/builds/15295) succeeded 953b653d499bdf78cd1eb65550c6eb94a3620180
* :green_heart: [Build #15227](https://buildkite.com/elastic/integrations/builds/15227) succeeded 8e782c61e30a14f0cfbef998e2ea8bf63cd95c96

cc @lucian-ioan

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16045","number":16045,"commit":"6c72eb4ea29727e44cbedcf5c5b3b75603f493df"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16044","number":16044,"commit":"28978e01cb2e7e5a56a535631c9722664fae6c34"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16042","number":16042,"commit":"56c61bdc47f8d31364686bbad6b89370605e234c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16040","number":16040,"commit":"e1af4afc6e3c6f72744adbbbbec6cf369cee49bd"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15295","number":15295,"commit":"953b653d499bdf78cd1eb65550c6eb94a3620180"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15227","number":15227,"commit":"8e782c61e30a14f0cfbef998e2ea8bf63cd95c96"}],"number":16045}
buildkite-pr-comment-->

2024-09-18 09:18 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16047)
* Commit: 9d3b1a0b895c77951da7d322975b2639545b612b

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/16047#0192046c-0abd-4b78-ada2-40089b0e096c)

### History
* :broken_heart: [Build #16045](https://buildkite.com/elastic/integrations/builds/16045) failed 6c72eb4ea29727e44cbedcf5c5b3b75603f493df
* :broken_heart: [Build #16044](https://buildkite.com/elastic/integrations/builds/16044) failed 28978e01cb2e7e5a56a535631c9722664fae6c34
* :broken_heart: [Build #16042](https://buildkite.com/elastic/integrations/builds/16042) failed 56c61bdc47f8d31364686bbad6b89370605e234c
* :broken_heart: [Build #16040](https://buildkite.com/elastic/integrations/builds/16040) failed e1af4afc6e3c6f72744adbbbbec6cf369cee49bd
* :green_heart: [Build #15295](https://buildkite.com/elastic/integrations/builds/15295) succeeded 953b653d499bdf78cd1eb65550c6eb94a3620180
* :green_heart: [Build #15227](https://buildkite.com/elastic/integrations/builds/15227) succeeded 8e782c61e30a14f0cfbef998e2ea8bf63cd95c96

cc @lucian-ioan

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16047","number":16047,"commit":"9d3b1a0b895c77951da7d322975b2639545b612b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16045","number":16045,"commit":"6c72eb4ea29727e44cbedcf5c5b3b75603f493df"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16044","number":16044,"commit":"28978e01cb2e7e5a56a535631c9722664fae6c34"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16042","number":16042,"commit":"56c61bdc47f8d31364686bbad6b89370605e234c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16040","number":16040,"commit":"e1af4afc6e3c6f72744adbbbbec6cf369cee49bd"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15295","number":15295,"commit":"953b653d499bdf78cd1eb65550c6eb94a3620180"}],"number":16047}
buildkite-pr-comment-->

2024-09-18 09:43 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16051)
* Commit: a782210629125d5def10c6e3fab0880b8d2eef49

### Failed CI Steps
* [Check integrations vsphere](https://buildkite.com/elastic/integrations/builds/16051#0192047c-6c1b-4fa8-b370-e50922a1dd7f)

### History
* :broken_heart: [Build #16047](https://buildkite.com/elastic/integrations/builds/16047) failed 9d3b1a0b895c77951da7d322975b2639545b612b
* :broken_heart: [Build #16045](https://buildkite.com/elastic/integrations/builds/16045) failed 6c72eb4ea29727e44cbedcf5c5b3b75603f493df
* :broken_heart: [Build #16044](https://buildkite.com/elastic/integrations/builds/16044) failed 28978e01cb2e7e5a56a535631c9722664fae6c34
* :broken_heart: [Build #16042](https://buildkite.com/elastic/integrations/builds/16042) failed 56c61bdc47f8d31364686bbad6b89370605e234c
* :broken_heart: [Build #16040](https://buildkite.com/elastic/integrations/builds/16040) failed e1af4afc6e3c6f72744adbbbbec6cf369cee49bd
* :green_heart: [Build #15295](https://buildkite.com/elastic/integrations/builds/15295) succeeded 953b653d499bdf78cd1eb65550c6eb94a3620180

cc @lucian-ioan

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16051","number":16051,"commit":"a782210629125d5def10c6e3fab0880b8d2eef49"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16047","number":16047,"commit":"9d3b1a0b895c77951da7d322975b2639545b612b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16045","number":16045,"commit":"6c72eb4ea29727e44cbedcf5c5b3b75603f493df"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16044","number":16044,"commit":"28978e01cb2e7e5a56a535631c9722664fae6c34"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16042","number":16042,"commit":"56c61bdc47f8d31364686bbad6b89370605e234c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16040","number":16040,"commit":"e1af4afc6e3c6f72744adbbbbec6cf369cee49bd"}],"number":16051}
buildkite-pr-comment-->

2024-09-18 10:12 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16053)
* Commit: 8e01de87d1323d6d0d3d9c9e46fd8ef90b5cbace

### Failed CI Steps
* [Check integrations vsphere](https://buildkite.com/elastic/integrations/builds/16053#0192049a-8f6e-43e6-9869-1ff633cecb92)

### History
* :broken_heart: [Build #16051](https://buildkite.com/elastic/integrations/builds/16051) failed a782210629125d5def10c6e3fab0880b8d2eef49
* :broken_heart: [Build #16047](https://buildkite.com/elastic/integrations/builds/16047) failed 9d3b1a0b895c77951da7d322975b2639545b612b
* :broken_heart: [Build #16045](https://buildkite.com/elastic/integrations/builds/16045) failed 6c72eb4ea29727e44cbedcf5c5b3b75603f493df
* :broken_heart: [Build #16044](https://buildkite.com/elastic/integrations/builds/16044) failed 28978e01cb2e7e5a56a535631c9722664fae6c34
* :broken_heart: [Build #16042](https://buildkite.com/elastic/integrations/builds/16042) failed 56c61bdc47f8d31364686bbad6b89370605e234c

cc @lucian-ioan

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16053","number":16053,"commit":"8e01de87d1323d6d0d3d9c9e46fd8ef90b5cbace"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16051","number":16051,"commit":"a782210629125d5def10c6e3fab0880b8d2eef49"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16047","number":16047,"commit":"9d3b1a0b895c77951da7d322975b2639545b612b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16045","number":16045,"commit":"6c72eb4ea29727e44cbedcf5c5b3b75603f493df"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16044","number":16044,"commit":"28978e01cb2e7e5a56a535631c9722664fae6c34"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16042","number":16042,"commit":"56c61bdc47f8d31364686bbad6b89370605e234c"}],"number":16053}
buildkite-pr-comment-->

2024-09-18 10:29 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16054)
* Commit: d6b991649480442c419680aa2edfa9283502a703

### Failed CI Steps
* [Check integrations vsphere](https://buildkite.com/elastic/integrations/builds/16054#019204a5-d25b-46b7-b49a-8551e6cb5180)

### History
* :broken_heart: [Build #16053](https://buildkite.com/elastic/integrations/builds/16053) failed 8e01de87d1323d6d0d3d9c9e46fd8ef90b5cbace
* :broken_heart: [Build #16051](https://buildkite.com/elastic/integrations/builds/16051) failed a782210629125d5def10c6e3fab0880b8d2eef49
* :broken_heart: [Build #16047](https://buildkite.com/elastic/integrations/builds/16047) failed 9d3b1a0b895c77951da7d322975b2639545b612b
* :broken_heart: [Build #16045](https://buildkite.com/elastic/integrations/builds/16045) failed 6c72eb4ea29727e44cbedcf5c5b3b75603f493df
* :broken_heart: [Build #16044](https://buildkite.com/elastic/integrations/builds/16044) failed 28978e01cb2e7e5a56a535631c9722664fae6c34
* :broken_heart: [Build #16042](https://buildkite.com/elastic/integrations/builds/16042) failed 56c61bdc47f8d31364686bbad6b89370605e234c

cc @lucian-ioan

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16054","number":16054,"commit":"d6b991649480442c419680aa2edfa9283502a703"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16053","number":16053,"commit":"8e01de87d1323d6d0d3d9c9e46fd8ef90b5cbace"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16051","number":16051,"commit":"a782210629125d5def10c6e3fab0880b8d2eef49"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16047","number":16047,"commit":"9d3b1a0b895c77951da7d322975b2639545b612b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16045","number":16045,"commit":"6c72eb4ea29727e44cbedcf5c5b3b75603f493df"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16044","number":16044,"commit":"28978e01cb2e7e5a56a535631c9722664fae6c34"}],"number":16054}
buildkite-pr-comment-->

2024-09-18 10:58 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16055)
* Commit: eca68137bcb2c62e83884db8287f2e567754c484

### History
* :broken_heart: [Build #16054](https://buildkite.com/elastic/integrations/builds/16054) failed d6b991649480442c419680aa2edfa9283502a703
* :broken_heart: [Build #16053](https://buildkite.com/elastic/integrations/builds/16053) failed 8e01de87d1323d6d0d3d9c9e46fd8ef90b5cbace
* :broken_heart: [Build #16051](https://buildkite.com/elastic/integrations/builds/16051) failed a782210629125d5def10c6e3fab0880b8d2eef49
* :broken_heart: [Build #16047](https://buildkite.com/elastic/integrations/builds/16047) failed 9d3b1a0b895c77951da7d322975b2639545b612b
* :broken_heart: [Build #16045](https://buildkite.com/elastic/integrations/builds/16045) failed 6c72eb4ea29727e44cbedcf5c5b3b75603f493df

cc @lucian-ioan

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16055","number":16055,"commit":"eca68137bcb2c62e83884db8287f2e567754c484"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16054","number":16054,"commit":"d6b991649480442c419680aa2edfa9283502a703"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16053","number":16053,"commit":"8e01de87d1323d6d0d3d9c9e46fd8ef90b5cbace"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16051","number":16051,"commit":"a782210629125d5def10c6e3fab0880b8d2eef49"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16047","number":16047,"commit":"9d3b1a0b895c77951da7d322975b2639545b612b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16045","number":16045,"commit":"6c72eb4ea29727e44cbedcf5c5b3b75603f493df"}],"number":16055}
buildkite-pr-comment-->

2024-09-19 06:18 UTC, ishleenk17 commented on packages/vsphere/changelog.yml
> +- version: "1.14.0-next"
Lets update this to latest 1.15.0-next

2024-09-19 06:18 UTC, ishleenk17 commented on packages/vsphere/data_stream/virtualmachine/fields/fields.yml
> +    - name: triggerd_alarms.*
This needs to incorporate the latest change of this name change yesterday.
`"triggered_alamrs"`

2024-09-19 06:18 UTC, ishleenk17 commented on packages/vsphere/data_stream/virtualmachine/manifest.yml
> +        description: The vSphere performance API allows for collecting host and datastore metrics at various intervals, including real-time (every 20 seconds), 5 minutes, or longer durations. Properl
Change the description as discussed yesterday

2024-09-19 12:32 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16168)
* Commit: 649c864e261087d24c8728e6573c024a785c2e0d

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/16168#01920a44-58b1-417f-a2dd-eb8900260f28)

### History
* :green_heart: [Build #16055](https://buildkite.com/elastic/integrations/builds/16055) succeeded eca68137bcb2c62e83884db8287f2e567754c484
* :broken_heart: [Build #16054](https://buildkite.com/elastic/integrations/builds/16054) failed d6b991649480442c419680aa2edfa9283502a703
* :broken_heart: [Build #16053](https://buildkite.com/elastic/integrations/builds/16053) failed 8e01de87d1323d6d0d3d9c9e46fd8ef90b5cbace
* :broken_heart: [Build #16051](https://buildkite.com/elastic/integrations/builds/16051) failed a782210629125d5def10c6e3fab0880b8d2eef49
* :broken_heart: [Build #16047](https://buildkite.com/elastic/integrations/builds/16047) failed 9d3b1a0b895c77951da7d322975b2639545b612b
* :broken_heart: [Build #16045](https://buildkite.com/elastic/integrations/builds/16045) failed 6c72eb4ea29727e44cbedcf5c5b3b75603f493df

cc @lucian-ioan

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16168","number":16168,"commit":"649c864e261087d24c8728e6573c024a785c2e0d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16055","number":16055,"commit":"eca68137bcb2c62e83884db8287f2e567754c484"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16054","number":16054,"commit":"d6b991649480442c419680aa2edfa9283502a703"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16053","number":16053,"commit":"8e01de87d1323d6d0d3d9c9e46fd8ef90b5cbace"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16051","number":16051,"commit":"a782210629125d5def10c6e3fab0880b8d2eef49"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16047","number":16047,"commit":"9d3b1a0b895c77951da7d322975b2639545b612b"}],"number":16168}
buildkite-pr-comment-->

2024-09-19 12:34 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16169)
* Commit: d2f467ef1155294524fb40eaa92ffe4e4ba355f0

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/16169#01920a46-0c43-423c-bcaa-71acc0b7e714)

### History
* :broken_heart: [Build #16168](https://buildkite.com/elastic/integrations/builds/16168) failed 649c864e261087d24c8728e6573c024a785c2e0d
* :green_heart: [Build #16055](https://buildkite.com/elastic/integrations/builds/16055) succeeded eca68137bcb2c62e83884db8287f2e567754c484
* :broken_heart: [Build #16054](https://buildkite.com/elastic/integrations/builds/16054) failed d6b991649480442c419680aa2edfa9283502a703
* :broken_heart: [Build #16053](https://buildkite.com/elastic/integrations/builds/16053) failed 8e01de87d1323d6d0d3d9c9e46fd8ef90b5cbace
* :broken_heart: [Build #16051](https://buildkite.com/elastic/integrations/builds/16051) failed a782210629125d5def10c6e3fab0880b8d2eef49
* :broken_heart: [Build #16047](https://buildkite.com/elastic/integrations/builds/16047) failed 9d3b1a0b895c77951da7d322975b2639545b612b

cc @lucian-ioan

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16169","number":16169,"commit":"d2f467ef1155294524fb40eaa92ffe4e4ba355f0"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16168","number":16168,"commit":"649c864e261087d24c8728e6573c024a785c2e0d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16055","number":16055,"commit":"eca68137bcb2c62e83884db8287f2e567754c484"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16054","number":16054,"commit":"d6b991649480442c419680aa2edfa9283502a703"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16053","number":16053,"commit":"8e01de87d1323d6d0d3d9c9e46fd8ef90b5cbace"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16051","number":16051,"commit":"a782210629125d5def10c6e3fab0880b8d2eef49"}],"number":16169}
buildkite-pr-comment-->

2024-09-19 12:38 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16170)
* Commit: 6b27dc4397602b24633e5406c302636f121058c0

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/16170#01920a48-e443-45e1-9502-a6cf76d39c99)

### History
* :broken_heart: [Build #16169](https://buildkite.com/elastic/integrations/builds/16169) failed d2f467ef1155294524fb40eaa92ffe4e4ba355f0
* :broken_heart: [Build #16168](https://buildkite.com/elastic/integrations/builds/16168) failed 649c864e261087d24c8728e6573c024a785c2e0d
* :green_heart: [Build #16055](https://buildkite.com/elastic/integrations/builds/16055) succeeded eca68137bcb2c62e83884db8287f2e567754c484
* :broken_heart: [Build #16054](https://buildkite.com/elastic/integrations/builds/16054) failed d6b991649480442c419680aa2edfa9283502a703
* :broken_heart: [Build #16053](https://buildkite.com/elastic/integrations/builds/16053) failed 8e01de87d1323d6d0d3d9c9e46fd8ef90b5cbace
* :broken_heart: [Build #16051](https://buildkite.com/elastic/integrations/builds/16051) failed a782210629125d5def10c6e3fab0880b8d2eef49

cc @lucian-ioan

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16170","number":16170,"commit":"6b27dc4397602b24633e5406c302636f121058c0"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16169","number":16169,"commit":"d2f467ef1155294524fb40eaa92ffe4e4ba355f0"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16168","number":16168,"commit":"649c864e261087d24c8728e6573c024a785c2e0d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16055","number":16055,"commit":"eca68137bcb2c62e83884db8287f2e567754c484"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16054","number":16054,"commit":"d6b991649480442c419680aa2edfa9283502a703"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16053","number":16053,"commit":"8e01de87d1323d6d0d3d9c9e46fd8ef90b5cbace"}],"number":16170}
buildkite-pr-comment-->

2024-09-19 12:44 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16172)
* Commit: f546aa80f7d4e0204685915138cba6856e08b7bd

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/16172#01920a4e-983d-4428-8fbf-e9bab8794beb)

### History
* :broken_heart: [Build #16170](https://buildkite.com/elastic/integrations/builds/16170) failed 6b27dc4397602b24633e5406c302636f121058c0
* :broken_heart: [Build #16169](https://buildkite.com/elastic/integrations/builds/16169) failed d2f467ef1155294524fb40eaa92ffe4e4ba355f0
* :broken_heart: [Build #16168](https://buildkite.com/elastic/integrations/builds/16168) failed 649c864e261087d24c8728e6573c024a785c2e0d
* :green_heart: [Build #16055](https://buildkite.com/elastic/integrations/builds/16055) succeeded eca68137bcb2c62e83884db8287f2e567754c484
* :broken_heart: [Build #16054](https://buildkite.com/elastic/integrations/builds/16054) failed d6b991649480442c419680aa2edfa9283502a703
* :broken_heart: [Build #16053](https://buildkite.com/elastic/integrations/builds/16053) failed 8e01de87d1323d6d0d3d9c9e46fd8ef90b5cbace

cc @lucian-ioan

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16172","number":16172,"commit":"f546aa80f7d4e0204685915138cba6856e08b7bd"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16170","number":16170,"commit":"6b27dc4397602b24633e5406c302636f121058c0"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16169","number":16169,"commit":"d2f467ef1155294524fb40eaa92ffe4e4ba355f0"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16168","number":16168,"commit":"649c864e261087d24c8728e6573c024a785c2e0d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16055","number":16055,"commit":"eca68137bcb2c62e83884db8287f2e567754c484"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16054","number":16054,"commit":"d6b991649480442c419680aa2edfa9283502a703"}],"number":16172}
buildkite-pr-comment-->

2024-09-19 12:55 UTC, niraj-elastic commented
@lucian-ioan Please add tags in hbs file.

2024-09-19 13:23 UTC, niraj-elastic requested changes

2024-09-19 13:23 UTC, niraj-elastic commented on packages/vsphere/data_stream/virtualmachine/_dev/test/pipeline/test-virtualmachine.json-expected.json
> +                    "172.18.0.4",
Are this real IP's ? please change this if it belongs to any known VM.

2024-09-19 13:26 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16177)
* Commit: 4aa0c34a6756d40fabbcaece92887dee641f3787

### History
* :broken_heart: [Build #16172](https://buildkite.com/elastic/integrations/builds/16172) failed f546aa80f7d4e0204685915138cba6856e08b7bd
* :broken_heart: [Build #16170](https://buildkite.com/elastic/integrations/builds/16170) failed 6b27dc4397602b24633e5406c302636f121058c0
* :broken_heart: [Build #16169](https://buildkite.com/elastic/integrations/builds/16169) failed d2f467ef1155294524fb40eaa92ffe4e4ba355f0
* :broken_heart: [Build #16168](https://buildkite.com/elastic/integrations/builds/16168) failed 649c864e261087d24c8728e6573c024a785c2e0d
* :green_heart: [Build #16055](https://buildkite.com/elastic/integrations/builds/16055) succeeded eca68137bcb2c62e83884db8287f2e567754c484
* :broken_heart: [Build #16054](https://buildkite.com/elastic/integrations/builds/16054) failed d6b991649480442c419680aa2edfa9283502a703

cc @lucian-ioan

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16177","number":16177,"commit":"4aa0c34a6756d40fabbcaece92887dee641f3787"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16172","number":16172,"commit":"f546aa80f7d4e0204685915138cba6856e08b7bd"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16170","number":16170,"commit":"6b27dc4397602b24633e5406c302636f121058c0"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16169","number":16169,"commit":"d2f467ef1155294524fb40eaa92ffe4e4ba355f0"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16168","number":16168,"commit":"649c864e261087d24c8728e6573c024a785c2e0d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16055","number":16055,"commit":"eca68137bcb2c62e83884db8287f2e567754c484"}],"number":16177}
buildkite-pr-comment-->

2024-09-19 14:09 UTC, ishleenk17 commented
Update description of commit PR with the snapshot fields as well

2024-09-20 05:13 UTC, lucian-ioan commented on packages/vsphere/data_stream/virtualmachine/_dev/test/pipeline/test-virtualmachine.json-expected.json
> +                    "172.18.0.4",
Shouldn't be relevant anymore but I went ahead and modified all ips/domains.

2024-09-20 05:14 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16212)
* Commit: ba0636d1995bb3b441307eaff57da341f296b85c

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/16212#01920dd9-6cbe-41f3-b9ac-f039946d00ff)

### History
* :green_heart: [Build #16177](https://buildkite.com/elastic/integrations/builds/16177) succeeded 4aa0c34a6756d40fabbcaece92887dee641f3787
* :broken_heart: [Build #16172](https://buildkite.com/elastic/integrations/builds/16172) failed f546aa80f7d4e0204685915138cba6856e08b7bd
* :broken_heart: [Build #16170](https://buildkite.com/elastic/integrations/builds/16170) failed 6b27dc4397602b24633e5406c302636f121058c0
* :broken_heart: [Build #16169](https://buildkite.com/elastic/integrations/builds/16169) failed d2f467ef1155294524fb40eaa92ffe4e4ba355f0
* :broken_heart: [Build #16168](https://buildkite.com/elastic/integrations/builds/16168) failed 649c864e261087d24c8728e6573c024a785c2e0d
* :green_heart: [Build #16055](https://buildkite.com/elastic/integrations/builds/16055) succeeded eca68137bcb2c62e83884db8287f2e567754c484

cc @lucian-ioan

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"running","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16212","number":16212,"commit":"ba0636d1995bb3b441307eaff57da341f296b85c"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16177","number":16177,"commit":"4aa0c34a6756d40fabbcaece92887dee641f3787"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16172","number":16172,"commit":"f546aa80f7d4e0204685915138cba6856e08b7bd"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16170","number":16170,"commit":"6b27dc4397602b24633e5406c302636f121058c0"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16169","number":16169,"commit":"d2f467ef1155294524fb40eaa92ffe4e4ba355f0"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16168","number":16168,"commit":"649c864e261087d24c8728e6573c024a785c2e0d"}],"number":16212}
buildkite-pr-comment-->

2024-09-20 05:24 UTC, ishleenk17 approved these changes
Looks good!
Let the CI pass

2024-09-20 05:39 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16213)
* Commit: a0094540492f9b44b93885389b2452c803ef3511

### History
* :broken_heart: [Build #16212](https://buildkite.com/elastic/integrations/builds/16212) failed ba0636d1995bb3b441307eaff57da341f296b85c
* :green_heart: [Build #16177](https://buildkite.com/elastic/integrations/builds/16177) succeeded 4aa0c34a6756d40fabbcaece92887dee641f3787
* :broken_heart: [Build #16172](https://buildkite.com/elastic/integrations/builds/16172) failed f546aa80f7d4e0204685915138cba6856e08b7bd
* :broken_heart: [Build #16170](https://buildkite.com/elastic/integrations/builds/16170) failed 6b27dc4397602b24633e5406c302636f121058c0
* :broken_heart: [Build #16169](https://buildkite.com/elastic/integrations/builds/16169) failed d2f467ef1155294524fb40eaa92ffe4e4ba355f0
* :broken_heart: [Build #16168](https://buildkite.com/elastic/integrations/builds/16168) failed 649c864e261087d24c8728e6573c024a785c2e0d

cc @lucian-ioan

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16213","number":16213,"commit":"a0094540492f9b44b93885389b2452c803ef3511"},{"buildStatus":{"state":"running","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16212","number":16212,"commit":"ba0636d1995bb3b441307eaff57da341f296b85c"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16177","number":16177,"commit":"4aa0c34a6756d40fabbcaece92887dee641f3787"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16172","number":16172,"commit":"f546aa80f7d4e0204685915138cba6856e08b7bd"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16170","number":16170,"commit":"6b27dc4397602b24633e5406c302636f121058c0"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16169","number":16169,"commit":"d2f467ef1155294524fb40eaa92ffe4e4ba355f0"}],"number":16213}
buildkite-pr-comment-->

2024-09-20 06:00 UTC, merged