[vSphere] Add new cluster datatastream
elastic/integrations pull request #10949
Opened 2024-08-30 16:04 UTC by niraj-elastic

- Enhancement

## What does this PR do?

- Added 1 data stream (Cluster Metrics).
- Added data collection metrics for the data streams.
- Added the ingest pipeline for the data streams.
- Mapped fields according to the ECS schema and added Fields metadata in the appropriate yaml files.
- Added dashboards and visualizations.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.

## How to test this PR locally

- Clone integrations repo.
- Install elastic-package locally.
- Start elastic stack using elastic-package.
- Move to integrations/packages/vsphere) directory.
- Run the following command to run tests. elastic-package test

2024-08-30 16:36 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-08-30 16:37 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15265)
* Commit: 89a2b424120fb87f795a20b77d58ad6b1c3627e3

cc @niraj-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15265","number":15265,"commit":"89a2b424120fb87f795a20b77d58ad6b1c3627e3"}],"number":15265}
buildkite-pr-comment-->

2024-09-11 09:53 UTC, lucian-ioan commented on packages/vsphere/manifest.yml
> +version: "1.14.0"
Change version "1.14.0-next" as per this https://github.com/elastic/obs-integration-team/issues/22.

2024-09-11 09:54 UTC, lucian-ioan commented on packages/vsphere/data_stream/cluster/manifest.yml
> +  index_mode: "time_series"
Please provide a screenshot with results from [TSDB-migration-test-kit](https://github.com/elastic/TSDB-migration-test-kit) before enabling TSDB (after adding metric_type to the fields).

2024-09-11 09:54 UTC, lucian-ioan commented on packages/vsphere/data_stream/cluster/fields/fields.yml
> +            List of all the Network names associated with the cluster.
Add metric_type to all these fields.

2024-09-11 09:55 UTC, lucian-ioan commented on packages/vsphere/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/10949
Change version "1.14.0-next" as per this https://github.com/elastic/obs-integration-team/issues/22.

2024-09-17 13:36 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16011)
* Commit: 0544e1fda72ae0283390f0a0f06d4fdfd38bb0bd

### Failed CI Steps
* [Check integrations vsphere](https://buildkite.com/elastic/integrations/builds/16011#01920019-35fe-45c0-a29a-f9280c04f55b)

### History
* :green_heart: [Build #15265](https://buildkite.com/elastic/integrations/builds/15265) succeeded 89a2b424120fb87f795a20b77d58ad6b1c3627e3

cc @niraj-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16011","number":16011,"commit":"0544e1fda72ae0283390f0a0f06d4fdfd38bb0bd"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15265","number":15265,"commit":"89a2b424120fb87f795a20b77d58ad6b1c3627e3"}],"number":16011}
buildkite-pr-comment-->

2024-09-18 05:40 UTC, ishleenk17 commented on packages/vsphere/data_stream/cluster/manifest.yml
> +        description: The vSphere performance API allows for collecting host and datastore metrics at various intervals, including real-time (every 20 seconds), 5-minutes, and longer durations. Due to
Since this is relevant only to host and datastore, do you think we should describe it here as well ?

2024-09-18 05:40 UTC, ishleenk17 commented on packages/vsphere/manifest.yml
>              description: vSphere account password (not root VMAMI account)
Kibana version change to 8.15.2

2024-09-19 07:23 UTC, ishleenk17 commented on packages/vsphere/data_stream/cluster/manifest.yml
> +        description: The vSphere performance API allows for collecting host and datastore metrics at various intervals, including real-time (every 20 seconds), 5-minutes, and longer durations. Due to
As discussed yesterday, lets keep the description generic here

2024-09-19 07:38 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16117)
* Commit: 7d0f731f5e8fdaaedd747c7cc0814b8116d47e05

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/16117#01920937-287d-4f81-be91-645e3ab05c6a)

### History
* :broken_heart: [Build #16011](https://buildkite.com/elastic/integrations/builds/16011) failed 0544e1fda72ae0283390f0a0f06d4fdfd38bb0bd
* :green_heart: [Build #15265](https://buildkite.com/elastic/integrations/builds/15265) succeeded 89a2b424120fb87f795a20b77d58ad6b1c3627e3

cc @niraj-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16117","number":16117,"commit":"7d0f731f5e8fdaaedd747c7cc0814b8116d47e05"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16011","number":16011,"commit":"0544e1fda72ae0283390f0a0f06d4fdfd38bb0bd"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15265","number":15265,"commit":"89a2b424120fb87f795a20b77d58ad6b1c3627e3"}],"number":16117}
buildkite-pr-comment-->

2024-09-19 08:33 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16120)
* Commit: 1a880f8301943a5bfd4f23d3aff9025b50538683

### Failed CI Steps
* [Check integrations vsphere](https://buildkite.com/elastic/integrations/builds/16120#0192095a-4aff-447a-b53e-7e357f82978b)

### History
* :broken_heart: [Build #16117](https://buildkite.com/elastic/integrations/builds/16117) failed 7d0f731f5e8fdaaedd747c7cc0814b8116d47e05
* :broken_heart: [Build #16011](https://buildkite.com/elastic/integrations/builds/16011) failed 0544e1fda72ae0283390f0a0f06d4fdfd38bb0bd
* :green_heart: [Build #15265](https://buildkite.com/elastic/integrations/builds/15265) succeeded 89a2b424120fb87f795a20b77d58ad6b1c3627e3

cc @niraj-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16120","number":16120,"commit":"1a880f8301943a5bfd4f23d3aff9025b50538683"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16117","number":16117,"commit":"7d0f731f5e8fdaaedd747c7cc0814b8116d47e05"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16011","number":16011,"commit":"0544e1fda72ae0283390f0a0f06d4fdfd38bb0bd"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15265","number":15265,"commit":"89a2b424120fb87f795a20b77d58ad6b1c3627e3"}],"number":16120}
buildkite-pr-comment-->

2024-09-19 09:20 UTC, niraj-elastic commented on packages/vsphere/data_stream/cluster/manifest.yml
> +  index_mode: "time_series"
updated the description.

2024-09-19 10:01 UTC, kush-elastic commented on packages/vsphere/changelog.yml
> +    - description: vSphere integration package with "cluster" data stream.
```suggestion
    - description: Add new cluster data-stream.
```

2024-09-19 10:02 UTC, kush-elastic commented on packages/vsphere/data_stream/cluster/_dev/test/pipeline/test-common-config.yml
I don't think we need this file.

2024-09-19 10:05 UTC, kush-elastic requested changes
Added few comments

2024-09-19 11:41 UTC, ishleenk17 commented on packages/vsphere/_dev/build/docs/README.md
> +### Cluster Metrics
Add mention of Cluster to the Datastream section also.

2024-09-19 12:19 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16162)
* Commit: bd92b70e3ade79750a8f3b9d58f7984aad1a59de

### History
* :broken_heart: [Build #16120](https://buildkite.com/elastic/integrations/builds/16120) failed 1a880f8301943a5bfd4f23d3aff9025b50538683
* :broken_heart: [Build #16117](https://buildkite.com/elastic/integrations/builds/16117) failed 7d0f731f5e8fdaaedd747c7cc0814b8116d47e05
* :broken_heart: [Build #16011](https://buildkite.com/elastic/integrations/builds/16011) failed 0544e1fda72ae0283390f0a0f06d4fdfd38bb0bd
* :green_heart: [Build #15265](https://buildkite.com/elastic/integrations/builds/15265) succeeded 89a2b424120fb87f795a20b77d58ad6b1c3627e3

cc @niraj-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16162","number":16162,"commit":"bd92b70e3ade79750a8f3b9d58f7984aad1a59de"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16120","number":16120,"commit":"1a880f8301943a5bfd4f23d3aff9025b50538683"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16117","number":16117,"commit":"7d0f731f5e8fdaaedd747c7cc0814b8116d47e05"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16011","number":16011,"commit":"0544e1fda72ae0283390f0a0f06d4fdfd38bb0bd"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15265","number":15265,"commit":"89a2b424120fb87f795a20b77d58ad6b1c3627e3"}],"number":16162}
buildkite-pr-comment-->

2024-09-19 12:22 UTC, lucian-ioan approved these changes

2024-09-19 12:25 UTC, ishleenk17 approved these changes
Looks good!

2024-09-19 12:26 UTC, kush-elastic approved these changes
LGTM!

2024-09-19 12:27 UTC, merged