[vSphere][network] Create network datastream
elastic/integrations pull request #10993
Opened 2024-09-03 20:08 UTC by lucian-ioan

## Proposed commit message

Following beats code changes in https://github.com/elastic/beats/pull/40559, the following metrics are added to the network datastream:

Metrics Type | Metrics | API | Field Mappings
-- | -- | -- | --
Network/DistributedVirtualPort | Network.OverallStatus | Summary | status
  | Network.Summary.Accessible | Summary | accessible
  | Network.ConfigStatus | Summary | config.status
  | Network.type | Summary | type
  | Network.Vm | ExtraApi | vm.names
  |   | ExtraApi | vm.count
  | Network.Host | ExtraApi | host.names
  |   | ExtraApi | host.count

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## How to test this PR locally

## Related issues

-  Closes https://github.com/elastic/obs-integration-team/issues/40

## Screenshots

2024-09-03 20:41 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15415)
* Commit: 4a84d4b086fbfed0864f8a3fc9a9a58b86748953

### Failed CI Steps
* [Check integrations vsphere](https://buildkite.com/elastic/integrations/builds/15415#0191b985-22ea-445f-9be0-088dcdfb0e0b)

cc @lucian-ioan

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15415","number":15415,"commit":"4a84d4b086fbfed0864f8a3fc9a9a58b86748953"}],"number":15415}
buildkite-pr-comment-->

2024-09-06 10:43 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15572)
* Commit: 4e5d27ad8dc7274f63f0a54c8f3853100953041b

### Failed CI Steps
* [Check integrations vsphere](https://buildkite.com/elastic/integrations/builds/15572#0191c6d6-46fe-4eea-921c-b350281c0980)

### History
* :broken_heart: [Build #15415](https://buildkite.com/elastic/integrations/builds/15415) failed 4a84d4b086fbfed0864f8a3fc9a9a58b86748953

cc @lucian-ioan

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15572","number":15572,"commit":"4e5d27ad8dc7274f63f0a54c8f3853100953041b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15415","number":15415,"commit":"4a84d4b086fbfed0864f8a3fc9a9a58b86748953"}],"number":15572}
buildkite-pr-comment-->

2024-09-11 10:51 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15751)
* Commit: c424ec3bcb7bcb25c26861210a926322dd46a58d

### Failed CI Steps
* [Check integrations vsphere](https://buildkite.com/elastic/integrations/builds/15751#0191e09a-e8de-4f57-9f3a-44a2ca715ec0)

### History
* :broken_heart: [Build #15572](https://buildkite.com/elastic/integrations/builds/15572) failed 4e5d27ad8dc7274f63f0a54c8f3853100953041b
* :broken_heart: [Build #15415](https://buildkite.com/elastic/integrations/builds/15415) failed 4a84d4b086fbfed0864f8a3fc9a9a58b86748953

cc @lucian-ioan

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15751","number":15751,"commit":"c424ec3bcb7bcb25c26861210a926322dd46a58d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15572","number":15572,"commit":"4e5d27ad8dc7274f63f0a54c8f3853100953041b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15415","number":15415,"commit":"4a84d4b086fbfed0864f8a3fc9a9a58b86748953"}],"number":15751}
buildkite-pr-comment-->

2024-09-19 07:38 UTC, ishleenk17 commented
1. README is missing. 
2. update kibana version
3. Perios has not been taken care in this

2024-09-19 07:38 UTC, ishleenk17 commented on packages/vsphere/changelog.yml
> +- version: "1.14.0-next"
change version to 1.15.0-next

2024-09-19 07:38 UTC, ishleenk17 commented on packages/vsphere/data_stream/network/fields/fields.yml
> +            Number of virtual machines connected to this network.
Missing the latest fields

2024-09-21 07:02 UTC, niraj-elastic requested changes

2024-09-21 07:02 UTC, niraj-elastic commented on packages/vsphere/data_stream/network/manifest.yml
> +    description: vSphere network metrics
please add `period` here, along with other configuration parameters.

2024-09-21 07:02 UTC, niraj-elastic commented on packages/vsphere/data_stream/network/agent/stream/stream.yml.hbs
> +insecure: {{insecure}}
please add `tags` and `processors`.

2024-09-22 20:52 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16269)
* Commit: ef389adeb20caaf96e31fe4ec68fb5d4feadc124

### History
* :broken_heart: [Build #15751](https://buildkite.com/elastic/integrations/builds/15751) failed c424ec3bcb7bcb25c26861210a926322dd46a58d
* :broken_heart: [Build #15572](https://buildkite.com/elastic/integrations/builds/15572) failed 4e5d27ad8dc7274f63f0a54c8f3853100953041b
* :broken_heart: [Build #15415](https://buildkite.com/elastic/integrations/builds/15415) failed 4a84d4b086fbfed0864f8a3fc9a9a58b86748953

cc @lucian-ioan

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16269","number":16269,"commit":"ef389adeb20caaf96e31fe4ec68fb5d4feadc124"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15751","number":15751,"commit":"c424ec3bcb7bcb25c26861210a926322dd46a58d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15572","number":15572,"commit":"4e5d27ad8dc7274f63f0a54c8f3853100953041b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15415","number":15415,"commit":"4a84d4b086fbfed0864f8a3fc9a9a58b86748953"}],"number":16269}
buildkite-pr-comment-->

2024-09-22 21:23 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16272)
* Commit: ffbe17382a0580537fe81a9ca6f9effdd7205c38

### Failed CI Steps
* [Check integrations vsphere](https://buildkite.com/elastic/integrations/builds/16272#01921b96-98f2-431c-a085-fdca82deafc3)

### History
* :green_heart: [Build #16269](https://buildkite.com/elastic/integrations/builds/16269) succeeded ef389adeb20caaf96e31fe4ec68fb5d4feadc124
* :broken_heart: [Build #15751](https://buildkite.com/elastic/integrations/builds/15751) failed c424ec3bcb7bcb25c26861210a926322dd46a58d
* :broken_heart: [Build #15572](https://buildkite.com/elastic/integrations/builds/15572) failed 4e5d27ad8dc7274f63f0a54c8f3853100953041b
* :broken_heart: [Build #15415](https://buildkite.com/elastic/integrations/builds/15415) failed 4a84d4b086fbfed0864f8a3fc9a9a58b86748953

cc @lucian-ioan

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16272","number":16272,"commit":"ffbe17382a0580537fe81a9ca6f9effdd7205c38"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16269","number":16269,"commit":"ef389adeb20caaf96e31fe4ec68fb5d4feadc124"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15751","number":15751,"commit":"c424ec3bcb7bcb25c26861210a926322dd46a58d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15572","number":15572,"commit":"4e5d27ad8dc7274f63f0a54c8f3853100953041b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15415","number":15415,"commit":"4a84d4b086fbfed0864f8a3fc9a9a58b86748953"}],"number":16272}
buildkite-pr-comment-->

2024-09-22 21:58 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16273)
* Commit: 655cf0dfc313a4d8a419356134413a07092db4f8

### History
* :broken_heart: [Build #16272](https://buildkite.com/elastic/integrations/builds/16272) failed ffbe17382a0580537fe81a9ca6f9effdd7205c38
* :green_heart: [Build #16269](https://buildkite.com/elastic/integrations/builds/16269) succeeded ef389adeb20caaf96e31fe4ec68fb5d4feadc124
* :broken_heart: [Build #15751](https://buildkite.com/elastic/integrations/builds/15751) failed c424ec3bcb7bcb25c26861210a926322dd46a58d
* :broken_heart: [Build #15572](https://buildkite.com/elastic/integrations/builds/15572) failed 4e5d27ad8dc7274f63f0a54c8f3853100953041b
* :broken_heart: [Build #15415](https://buildkite.com/elastic/integrations/builds/15415) failed 4a84d4b086fbfed0864f8a3fc9a9a58b86748953

cc @lucian-ioan

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16273","number":16273,"commit":"655cf0dfc313a4d8a419356134413a07092db4f8"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16272","number":16272,"commit":"ffbe17382a0580537fe81a9ca6f9effdd7205c38"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16269","number":16269,"commit":"ef389adeb20caaf96e31fe4ec68fb5d4feadc124"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15751","number":15751,"commit":"c424ec3bcb7bcb25c26861210a926322dd46a58d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15572","number":15572,"commit":"4e5d27ad8dc7274f63f0a54c8f3853100953041b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15415","number":15415,"commit":"4a84d4b086fbfed0864f8a3fc9a9a58b86748953"}],"number":16273}
buildkite-pr-comment-->

2024-09-23 04:49 UTC, ishleenk17 commented on packages/vsphere/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/11205
Incorrect PR number

2024-09-23 04:49 UTC, ishleenk17 commented on packages/vsphere/data_stream/network/fields/agent.yml
> +    - name: os.build
These are ecs fields w/o dimensions. Not required here.

2024-09-23 04:49 UTC, ishleenk17 commented
@lucian-ioan : Pls share details of TSDB testing

2024-09-23 05:29 UTC, kush-elastic commented on packages/vsphere/changelog.yml
>  - version: "1.15.0-next"
```suggestion
- version: "1.15.0"
```
As this PR is the last one we need to remove `next` tag and update version in manifest to `1.15.0`.

2024-09-23 05:29 UTC, kush-elastic commented on packages/vsphere/data_stream/network/_dev/test/pipeline/test-network.json
> +
```suggestion
```

Empty Line

2024-09-23 05:36 UTC, lucian-ioan commented on packages/vsphere/changelog.yml
>  - version: "1.15.0-next"
I guess so, should we do it with this PR @ishleenk17?

2024-09-23 05:38 UTC, kush-elastic commented on packages/vsphere/data_stream/network/sample_event.json
> +        "period": 20000
This formatting seems wrong, can you check once?
```suggestion
    },
    "metricset": {
      "name": "network",
      "period": 20000
```

2024-09-23 05:40 UTC, kush-elastic requested changes
Added few comments

2024-09-23 05:47 UTC, niraj-elastic requested changes

2024-09-23 05:47 UTC, niraj-elastic commented on packages/vsphere/data_stream/network/fields/fields.yml
> +            Names of the virtual machines connected to this network.
```suggestion
            List of all the virtual machines connected to this network.
```

minor nit. Please do it for other similar fields as well.

2024-09-23 05:52 UTC, lucian-ioan commented on packages/vsphere/data_stream/network/sample_event.json
> +        "period": 20000
Should work fine but re-formatted it just in case.

2024-09-23 05:57 UTC, kush-elastic approved these changes
LGTM!

2024-09-23 06:06 UTC, niraj-elastic requested changes

2024-09-23 06:06 UTC, niraj-elastic commented on packages/vsphere/docs/README.md
> +
```suggestion
```

2024-09-23 06:09 UTC, lucian-ioan commented on packages/vsphere/docs/README.md
> +
I don't think this is necessary, it's the default format for all datastreams in docs.

2024-09-23 06:23 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16284)
* Commit: ed60052c63685a69594852684d5ee530cc743872

### History
* :green_heart: [Build #16273](https://buildkite.com/elastic/integrations/builds/16273) succeeded 655cf0dfc313a4d8a419356134413a07092db4f8
* :broken_heart: [Build #16272](https://buildkite.com/elastic/integrations/builds/16272) failed ffbe17382a0580537fe81a9ca6f9effdd7205c38
* :green_heart: [Build #16269](https://buildkite.com/elastic/integrations/builds/16269) succeeded ef389adeb20caaf96e31fe4ec68fb5d4feadc124
* :broken_heart: [Build #15751](https://buildkite.com/elastic/integrations/builds/15751) failed c424ec3bcb7bcb25c26861210a926322dd46a58d
* :broken_heart: [Build #15572](https://buildkite.com/elastic/integrations/builds/15572) failed 4e5d27ad8dc7274f63f0a54c8f3853100953041b
* :broken_heart: [Build #15415](https://buildkite.com/elastic/integrations/builds/15415) failed 4a84d4b086fbfed0864f8a3fc9a9a58b86748953

cc @lucian-ioan

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16284","number":16284,"commit":"ed60052c63685a69594852684d5ee530cc743872"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16273","number":16273,"commit":"655cf0dfc313a4d8a419356134413a07092db4f8"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16272","number":16272,"commit":"ffbe17382a0580537fe81a9ca6f9effdd7205c38"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16269","number":16269,"commit":"ef389adeb20caaf96e31fe4ec68fb5d4feadc124"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15751","number":15751,"commit":"c424ec3bcb7bcb25c26861210a926322dd46a58d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15572","number":15572,"commit":"4e5d27ad8dc7274f63f0a54c8f3853100953041b"}],"number":16284}
buildkite-pr-comment-->

2024-09-23 06:35 UTC, niraj-elastic approved these changes

2024-09-23 06:38 UTC, niraj-elastic commented
LGTM

2024-09-23 07:31 UTC, ishleenk17 commented on packages/vsphere/changelog.yml
>  - version: "1.15.0-next"
Lets keep the next label as of now.
We will raise a PR when we are ready to release it.

2024-09-23 08:23 UTC, ishleenk17 approved these changes

2024-09-23 08:26 UTC, merged