[vSphere][datastorecluster] Add new Datastream Datastore Cluster
elastic/integrations pull request #11089
Opened 2024-09-11 05:45 UTC by kush-elastic

## Description
Here are the following metrics to be added as part of new datastream datastore cluster in the vSphere Integration.

Metrics Type | Metrics | API | Field Mappings
-- | -- | -- | --
Datastore cluster capacity | StoragePod.Summary.Capacity | Summary | capacity.bytes
  | StoragePod.Summary.FreeSpace | Summary | free_space.bytes
  Datastore cluster | childEntity(type= datastore) | Extra API | datastore.names
  | childEntity(type= datastore) | Extra API | datastore.count

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Closes https://github.com/elastic/obs-integration-team/issues/45

2024-09-11 06:08 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-09-11 06:08 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15738)
* Commit: 45f3247e8481a9b4bb210b2e5329ad9de1d53e04

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15738","number":15738,"commit":"45f3247e8481a9b4bb210b2e5329ad9de1d53e04"}],"number":15738}
buildkite-pr-comment-->

2024-09-11 09:51 UTC, lucian-ioan commented on packages/vsphere/data_stream/datastorecluster/fields/fields.yml
> +            Number of datastores in the Datastore Cluster.
Add metric_type to all these fields.

2024-09-11 09:51 UTC, lucian-ioan commented on packages/vsphere/data_stream/datastorecluster/manifest.yml
> +  index_mode: "time_series"
Please provide a screenshot with results from [TSDB-migration-test-kit](https://github.com/elastic/TSDB-migration-test-kit) before enabling TSDB (after adding metric_type to the fields).

2024-09-11 09:53 UTC, lucian-ioan requested changes
Add a changelog entry with version "1.14.0-next" as per this [issue](https://github.com/elastic/obs-integration-team/issues/22).

2024-09-18 09:14 UTC, niraj-elastic requested changes

2024-09-18 09:14 UTC, niraj-elastic commented on packages/vsphere/data_stream/datastorecluster/fields/fields.yml
Lets add triggered alarms as well.

2024-09-18 09:14 UTC, niraj-elastic commented on packages/vsphere/data_stream/datastorecluster/fields/agent.yml
> +    - name: containerized
I think ecs@mapping could take care of this fields, if these fields are included in ecs and are not dimension than we dont need to mention these.

2024-09-19 10:45 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16144)
* Commit: f237db86b38a127f54e3dbb4d4bc2d743edd6db2

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/16144#019209e2-2d64-4cdf-a84e-1580145a482e)

### History
* :green_heart: [Build #15738](https://buildkite.com/elastic/integrations/builds/15738) succeeded 45f3247e8481a9b4bb210b2e5329ad9de1d53e04

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16144","number":16144,"commit":"f237db86b38a127f54e3dbb4d4bc2d743edd6db2"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15738","number":15738,"commit":"45f3247e8481a9b4bb210b2e5329ad9de1d53e04"}],"number":16144}
buildkite-pr-comment-->

2024-09-19 11:01 UTC, ishleenk17 commented on packages/vsphere/_dev/build/docs/README.md
> +### Datastore Cluster
We should also add this to the datastreams section.

2024-09-19 11:01 UTC, ishleenk17 commented on packages/vsphere/_dev/build/docs/README.md
> +## Logs
Why is this being added in this ? I thought we already had this section

2024-09-19 11:39 UTC, kush-elastic commented on packages/vsphere/data_stream/datastorecluster/fields/fields.yml
> +            Number of datastores in the Datastore Cluster.
Updated

2024-09-19 11:42 UTC, kush-elastic commented on packages/vsphere/data_stream/datastorecluster/fields/fields.yml
Added

2024-09-19 11:42 UTC, kush-elastic commented on packages/vsphere/data_stream/datastorecluster/fields/agent.yml
> +    - name: containerized
removed unnecessary

2024-09-19 11:43 UTC, kush-elastic commented on packages/vsphere/_dev/build/docs/README.md
> +### Datastore Cluster
Right

2024-09-19 12:11 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16158)
* Commit: 6283078a0c31a97383eb1c8d9c5d13c680a1a21c

### Failed CI Steps
* [Check integrations vsphere](https://buildkite.com/elastic/integrations/builds/16158#01920a18-9e9e-48b6-ae42-2d8881bd5336)

### History
* :broken_heart: [Build #16144](https://buildkite.com/elastic/integrations/builds/16144) failed f237db86b38a127f54e3dbb4d4bc2d743edd6db2
* :green_heart: [Build #15738](https://buildkite.com/elastic/integrations/builds/15738) succeeded 45f3247e8481a9b4bb210b2e5329ad9de1d53e04

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16158","number":16158,"commit":"6283078a0c31a97383eb1c8d9c5d13c680a1a21c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16144","number":16144,"commit":"f237db86b38a127f54e3dbb4d4bc2d743edd6db2"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15738","number":15738,"commit":"45f3247e8481a9b4bb210b2e5329ad9de1d53e04"}],"number":16158}
buildkite-pr-comment-->

2024-09-19 12:50 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16175)
* Commit: 502aea3f158d86aa0a874423aab2a146705b1e4b

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/16175#01920a53-b923-439b-bc00-ce0f82add4c5)

### History
* :broken_heart: [Build #16158](https://buildkite.com/elastic/integrations/builds/16158) failed 6283078a0c31a97383eb1c8d9c5d13c680a1a21c
* :broken_heart: [Build #16144](https://buildkite.com/elastic/integrations/builds/16144) failed f237db86b38a127f54e3dbb4d4bc2d743edd6db2
* :green_heart: [Build #15738](https://buildkite.com/elastic/integrations/builds/15738) succeeded 45f3247e8481a9b4bb210b2e5329ad9de1d53e04

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16175","number":16175,"commit":"502aea3f158d86aa0a874423aab2a146705b1e4b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16158","number":16158,"commit":"6283078a0c31a97383eb1c8d9c5d13c680a1a21c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16144","number":16144,"commit":"f237db86b38a127f54e3dbb4d4bc2d743edd6db2"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15738","number":15738,"commit":"45f3247e8481a9b4bb210b2e5329ad9de1d53e04"}],"number":16175}
buildkite-pr-comment-->

2024-09-19 13:23 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16176)
* Commit: 3c533040ad4adcccb3c40d0badb2993d815fffae

### Failed CI Steps
* [Check integrations vsphere](https://buildkite.com/elastic/integrations/builds/16176#01920a5b-f58d-43f7-8457-08ff311304ad)

### History
* :broken_heart: [Build #16175](https://buildkite.com/elastic/integrations/builds/16175) failed 502aea3f158d86aa0a874423aab2a146705b1e4b
* :broken_heart: [Build #16158](https://buildkite.com/elastic/integrations/builds/16158) failed 6283078a0c31a97383eb1c8d9c5d13c680a1a21c
* :broken_heart: [Build #16144](https://buildkite.com/elastic/integrations/builds/16144) failed f237db86b38a127f54e3dbb4d4bc2d743edd6db2
* :green_heart: [Build #15738](https://buildkite.com/elastic/integrations/builds/15738) succeeded 45f3247e8481a9b4bb210b2e5329ad9de1d53e04

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16176","number":16176,"commit":"3c533040ad4adcccb3c40d0badb2993d815fffae"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16175","number":16175,"commit":"502aea3f158d86aa0a874423aab2a146705b1e4b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16158","number":16158,"commit":"6283078a0c31a97383eb1c8d9c5d13c680a1a21c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16144","number":16144,"commit":"f237db86b38a127f54e3dbb4d4bc2d743edd6db2"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15738","number":15738,"commit":"45f3247e8481a9b4bb210b2e5329ad9de1d53e04"}],"number":16176}
buildkite-pr-comment-->

2024-09-19 13:53 UTC, ishleenk17 commented on packages/vsphere/_dev/build/docs/README.md
> +>>>>>>> bde6b5118be928daf948a9cdfa1eadb0a857a852
Left out from a merge ?

2024-09-19 13:53 UTC, ishleenk17 commented on packages/vsphere/_dev/deploy/docker/Dockerfile
> +CMD vcsim -pod 1 -l :8989
Why the change here ?

2024-09-19 13:53 UTC, ishleenk17 commented on packages/vsphere/data_stream/datastorecluster/manifest.yml
> +        description: The period for fetching metrics. Supported units for this parameter are s (seconds), h (hours) and m (minutes).
Description differes from other datastreams.

2024-09-19 13:53 UTC, niraj-elastic requested changes

2024-09-19 13:53 UTC, niraj-elastic commented on packages/vsphere/_dev/build/docs/README.md
> +<<<<<<< HEAD
please fix this.

2024-09-19 17:00 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16195)
* Commit: 09ed4884857d03fc0b376f19b6f3dee40c8a0cd5

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/16195#01920b39-bf5e-4824-925a-3a015176e59a)

### History
* :broken_heart: [Build #16176](https://buildkite.com/elastic/integrations/builds/16176) failed 3c533040ad4adcccb3c40d0badb2993d815fffae
* :broken_heart: [Build #16175](https://buildkite.com/elastic/integrations/builds/16175) failed 502aea3f158d86aa0a874423aab2a146705b1e4b
* :broken_heart: [Build #16158](https://buildkite.com/elastic/integrations/builds/16158) failed 6283078a0c31a97383eb1c8d9c5d13c680a1a21c
* :broken_heart: [Build #16144](https://buildkite.com/elastic/integrations/builds/16144) failed f237db86b38a127f54e3dbb4d4bc2d743edd6db2
* :green_heart: [Build #15738](https://buildkite.com/elastic/integrations/builds/15738) succeeded 45f3247e8481a9b4bb210b2e5329ad9de1d53e04

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16195","number":16195,"commit":"09ed4884857d03fc0b376f19b6f3dee40c8a0cd5"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16176","number":16176,"commit":"3c533040ad4adcccb3c40d0badb2993d815fffae"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16175","number":16175,"commit":"502aea3f158d86aa0a874423aab2a146705b1e4b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16158","number":16158,"commit":"6283078a0c31a97383eb1c8d9c5d13c680a1a21c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16144","number":16144,"commit":"f237db86b38a127f54e3dbb4d4bc2d743edd6db2"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15738","number":15738,"commit":"45f3247e8481a9b4bb210b2e5329ad9de1d53e04"}],"number":16195}
buildkite-pr-comment-->

2024-09-19 17:03 UTC, kush-elastic commented on packages/vsphere/_dev/build/docs/README.md
> +>>>>>>> bde6b5118be928daf948a9cdfa1eadb0a857a852
Fixed.

2024-09-19 17:04 UTC, kush-elastic commented on packages/vsphere/_dev/deploy/docker/Dockerfile
> +CMD vcsim -pod 1 -l :8989
vcsim's default instance does not have any StoragePod.

2024-09-19 17:04 UTC, kush-elastic commented on packages/vsphere/_dev/build/docs/README.md
> +<<<<<<< HEAD
Fixed.

2024-09-19 17:17 UTC, willemdh commented
Is there support for Vsphere 8?

2024-09-19 17:38 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16196)
* Commit: daf72a461313bb3e3e10b225b2f3ba029c92e74d

### Failed CI Steps
* [Check integrations vsphere](https://buildkite.com/elastic/integrations/builds/16196#01920b43-3bb4-48d6-b29a-d782a84174ec)

### History
* :broken_heart: [Build #16195](https://buildkite.com/elastic/integrations/builds/16195) failed 09ed4884857d03fc0b376f19b6f3dee40c8a0cd5
* :broken_heart: [Build #16176](https://buildkite.com/elastic/integrations/builds/16176) failed 3c533040ad4adcccb3c40d0badb2993d815fffae
* :broken_heart: [Build #16175](https://buildkite.com/elastic/integrations/builds/16175) failed 502aea3f158d86aa0a874423aab2a146705b1e4b
* :broken_heart: [Build #16158](https://buildkite.com/elastic/integrations/builds/16158) failed 6283078a0c31a97383eb1c8d9c5d13c680a1a21c
* :broken_heart: [Build #16144](https://buildkite.com/elastic/integrations/builds/16144) failed f237db86b38a127f54e3dbb4d4bc2d743edd6db2
* :green_heart: [Build #15738](https://buildkite.com/elastic/integrations/builds/15738) succeeded 45f3247e8481a9b4bb210b2e5329ad9de1d53e04

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16196","number":16196,"commit":"daf72a461313bb3e3e10b225b2f3ba029c92e74d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16195","number":16195,"commit":"09ed4884857d03fc0b376f19b6f3dee40c8a0cd5"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16176","number":16176,"commit":"3c533040ad4adcccb3c40d0badb2993d815fffae"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16175","number":16175,"commit":"502aea3f158d86aa0a874423aab2a146705b1e4b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16158","number":16158,"commit":"6283078a0c31a97383eb1c8d9c5d13c680a1a21c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16144","number":16144,"commit":"f237db86b38a127f54e3dbb4d4bc2d743edd6db2"}],"number":16196}
buildkite-pr-comment-->

2024-09-21 13:40 UTC, kush-elastic commented on packages/vsphere/data_stream/datastorecluster/manifest.yml
> +        description: The period for fetching metrics. Supported units for this parameter are s (seconds), h (hours) and m (minutes).
fixed

2024-09-22 05:36 UTC, kush-elastic commented
> Is there support for Vsphere 8?

We have tested current integration with version 7.0.3, i cannot say confidently but it might just work fine with 8.0.0 as well.

2024-09-22 06:00 UTC, kush-elastic commented on packages/vsphere/data_stream/datastorecluster/manifest.yml
> +  index_mode: "time_series"
```
Values being used:
        elasticsearch_host = https://localhost:9200
        elasticsearch_ca_path = /root/.elastic-package/profiles/default/certs/elasticsearch/ca-cert.pem
        elasticsearch_user = elastic
        elasticsearch_pwd = changeme
        data_stream = metrics-vsphere.datastorecluster-default
        docs_index = First index of the data stream
        settings_mappings_index = Last index of the data stream
        max_docs = All documents
        get_overlapping_files = True
        directory_overlapping_files = overwritten-docs-metrics-vsphere.datastorecluster-default
        display_docs = 10
        copy_docs_per_dimension = 2

You're testing with version 8.15.2-SNAPSHOT.

Testing data stream metrics-vsphere.datastorecluster-default.
Index being used for the documents is .ds-metrics-vsphere.datastorecluster-default-2024.09.22-000001.
Index being used for the settings and mappings is .ds-metrics-vsphere.datastorecluster-default-2024.09.22-000001.

The time series fields for the TSDB index are: 
        - dimension (10 fields):
                - agent.id
                - cloud.account.id
                - cloud.availability_zone
                - cloud.instance.id
                - cloud.provider
                - cloud.region
                - container.id
                - host.name
                - service.address
                - vsphere.datastorecluster.name
        - gauge (3 fields):
                - vsphere.datastorecluster.capacity.bytes
                - vsphere.datastorecluster.datastore.count
                - vsphere.datastorecluster.free_space.bytes
        - routing_path (10 fields):
                - agent.id
                - cloud.account.id
                - cloud.availability_zone
                - cloud.instance.id
                - cloud.provider
                - cloud.region
                - container.id
                - host.name
                - service.address
                - vsphere.datastorecluster.name

Index tsdb-index-enabled successfully created.

Copying documents from .ds-metrics-vsphere.datastorecluster-default-2024.09.22-000001 to tsdb-index-enabled...
All 6 documents taken from index .ds-metrics-vsphere.datastorecluster-default-2024.09.22-000001 were successfully placed to index tsdb-index-enabled.
```

2024-09-22 06:06 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16258)
* Commit: 68bc8445878dc5ecbd690a1edcbf05c25befd727

### History
* :broken_heart: [Build #16253](https://buildkite.com/elastic/integrations/builds/16253) failed 20c51ac809f2e89b87e4c1c3fd4a2a270b127007
* :broken_heart: [Build #16196](https://buildkite.com/elastic/integrations/builds/16196) failed daf72a461313bb3e3e10b225b2f3ba029c92e74d
* :broken_heart: [Build #16195](https://buildkite.com/elastic/integrations/builds/16195) failed 09ed4884857d03fc0b376f19b6f3dee40c8a0cd5
* :broken_heart: [Build #16176](https://buildkite.com/elastic/integrations/builds/16176) failed 3c533040ad4adcccb3c40d0badb2993d815fffae
* :broken_heart: [Build #16175](https://buildkite.com/elastic/integrations/builds/16175) failed 502aea3f158d86aa0a874423aab2a146705b1e4b

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16258","number":16258,"commit":"68bc8445878dc5ecbd690a1edcbf05c25befd727"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16253","number":16253,"commit":"20c51ac809f2e89b87e4c1c3fd4a2a270b127007"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16196","number":16196,"commit":"daf72a461313bb3e3e10b225b2f3ba029c92e74d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16195","number":16195,"commit":"09ed4884857d03fc0b376f19b6f3dee40c8a0cd5"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16176","number":16176,"commit":"3c533040ad4adcccb3c40d0badb2993d815fffae"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16175","number":16175,"commit":"502aea3f158d86aa0a874423aab2a146705b1e4b"}],"number":16258}
buildkite-pr-comment-->

2024-09-22 08:22 UTC, niraj-elastic approved these changes
LGTM

2024-09-22 09:40 UTC, lucian-ioan approved these changes
LGTM

2024-09-22 10:03 UTC, ishleenk17 commented on packages/vsphere/_dev/deploy/docker/docker-compose.yml
> -    image: docker.elastic.co/integrations-ci/beats-vsphere:${VSPHERE_GOLANG_VERSION:-1.17}-1
IS this image not used ?

2024-09-22 10:03 UTC, ishleenk17 commented on packages/vsphere/data_stream/datastorecluster/fields/agent.yml
> +    - name: os.build
Are os.build and os.codename ecs fields ?

2024-09-22 10:03 UTC, ishleenk17 commented on packages/vsphere/data_stream/datastorecluster/manifest.yml
> +        description: Processors are used to reduce the number of fields in the exported event or to enhance the event with metadata. This executes in the agent before the logs are parsed. See [Proces
Link to the Fleet Processors pls

2024-09-22 10:05 UTC, kush-elastic commented on packages/vsphere/_dev/deploy/docker/docker-compose.yml
> -    image: docker.elastic.co/integrations-ci/beats-vsphere:${VSPHERE_GOLANG_VERSION:-1.17}-1
it was using image by default. if we want to use dockerfile we need to remove it.

2024-09-22 10:07 UTC, kush-elastic commented on packages/vsphere/data_stream/datastorecluster/fields/agent.yml
> +    - name: os.build
i think so, this i followed from datastore datastream, i think @lucian-ioan might be able to explain this.

2024-09-22 10:07 UTC, kush-elastic commented on packages/vsphere/data_stream/datastorecluster/manifest.yml
> +        description: Processors are used to reduce the number of fields in the exported event or to enhance the event with metadata. This executes in the agent before the logs are parsed. See [Proces
sure

2024-09-22 10:20 UTC, kush-elastic commented on packages/vsphere/data_stream/datastorecluster/manifest.yml
> +        description: Processors are used to reduce the number of fields in the exported event or to enhance the event with metadata. This executes in the agent before the logs are parsed. See [Proces
Fixed

2024-09-22 10:43 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16259)
* Commit: 2d702eb7f0743e06181399cdcc07b57212989d2f

### History
* :green_heart: [Build #16258](https://buildkite.com/elastic/integrations/builds/16258) succeeded 68bc8445878dc5ecbd690a1edcbf05c25befd727
* :broken_heart: [Build #16253](https://buildkite.com/elastic/integrations/builds/16253) failed 20c51ac809f2e89b87e4c1c3fd4a2a270b127007
* :broken_heart: [Build #16196](https://buildkite.com/elastic/integrations/builds/16196) failed daf72a461313bb3e3e10b225b2f3ba029c92e74d
* :broken_heart: [Build #16195](https://buildkite.com/elastic/integrations/builds/16195) failed 09ed4884857d03fc0b376f19b6f3dee40c8a0cd5
* :broken_heart: [Build #16176](https://buildkite.com/elastic/integrations/builds/16176) failed 3c533040ad4adcccb3c40d0badb2993d815fffae
* :broken_heart: [Build #16175](https://buildkite.com/elastic/integrations/builds/16175) failed 502aea3f158d86aa0a874423aab2a146705b1e4b

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16259","number":16259,"commit":"2d702eb7f0743e06181399cdcc07b57212989d2f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16258","number":16258,"commit":"68bc8445878dc5ecbd690a1edcbf05c25befd727"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16253","number":16253,"commit":"20c51ac809f2e89b87e4c1c3fd4a2a270b127007"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16196","number":16196,"commit":"daf72a461313bb3e3e10b225b2f3ba029c92e74d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16195","number":16195,"commit":"09ed4884857d03fc0b376f19b6f3dee40c8a0cd5"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16176","number":16176,"commit":"3c533040ad4adcccb3c40d0badb2993d815fffae"}],"number":16259}
buildkite-pr-comment-->

2024-09-22 11:47 UTC, ishleenk17 commented on packages/vsphere/data_stream/datastorecluster/fields/agent.yml
> +    - name: os.build
If its ecs and not dimension field, we should remove it.

2024-09-22 11:51 UTC, ishleenk17 approved these changes
Approving, please address 1 pending comment.

2024-09-22 12:10 UTC, kush-elastic commented on packages/vsphere/data_stream/datastorecluster/fields/agent.yml
> +    - name: os.build
Removed

2024-09-22 12:33 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16260)
* Commit: 2151e370d4fd2c3d3f1c074fc5c07a9a10a27ec1

### History
* :green_heart: [Build #16259](https://buildkite.com/elastic/integrations/builds/16259) succeeded 2d702eb7f0743e06181399cdcc07b57212989d2f
* :green_heart: [Build #16258](https://buildkite.com/elastic/integrations/builds/16258) succeeded 68bc8445878dc5ecbd690a1edcbf05c25befd727
* :broken_heart: [Build #16253](https://buildkite.com/elastic/integrations/builds/16253) failed 20c51ac809f2e89b87e4c1c3fd4a2a270b127007
* :broken_heart: [Build #16196](https://buildkite.com/elastic/integrations/builds/16196) failed daf72a461313bb3e3e10b225b2f3ba029c92e74d
* :broken_heart: [Build #16195](https://buildkite.com/elastic/integrations/builds/16195) failed 09ed4884857d03fc0b376f19b6f3dee40c8a0cd5
* :broken_heart: [Build #16176](https://buildkite.com/elastic/integrations/builds/16176) failed 3c533040ad4adcccb3c40d0badb2993d815fffae

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16260","number":16260,"commit":"2151e370d4fd2c3d3f1c074fc5c07a9a10a27ec1"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16259","number":16259,"commit":"2d702eb7f0743e06181399cdcc07b57212989d2f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16258","number":16258,"commit":"68bc8445878dc5ecbd690a1edcbf05c25befd727"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16253","number":16253,"commit":"20c51ac809f2e89b87e4c1c3fd4a2a270b127007"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16196","number":16196,"commit":"daf72a461313bb3e3e10b225b2f3ba029c92e74d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16195","number":16195,"commit":"09ed4884857d03fc0b376f19b6f3dee40c8a0cd5"}],"number":16260}
buildkite-pr-comment-->

2024-09-22 12:44 UTC, merged