[okta] Enable Agentless deployment
elastic/integrations pull request #11116
Opened 2024-09-12 14:22 UTC by aleksmaus

This is a draft PR for testing purposes as requested by collaborating team.

## Proposed commit message

[okta] Enable Agentless deployment

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

2024-09-12 14:56 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-09-12 15:59 UTC, elasticmachine commented
Pinging @elastic/security-service-integrations (Team:Security-Service Integrations)

2024-09-12 16:24 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15842)
* Commit: 3687e0820c58b455f8924b7f408e297f6b2a8107

### History
* :green_heart: [Build #15839](https://buildkite.com/elastic/integrations/builds/15839) succeeded e793c28310cab1520c68559510ac3a4a989e519d

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15842","number":15842,"commit":"3687e0820c58b455f8924b7f408e297f6b2a8107"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15839","number":15839,"commit":"e793c28310cab1520c68559510ac3a4a989e519d"}],"number":15842}
buildkite-pr-comment-->

2024-09-13 01:29 UTC, andrewkroh requested changes
Until we get the agentless cursor state persistence solved we need to hold on merging this. We do have some integrations like `ti_abusech` that do not depend on persistence so if we needed to push out an agentless-enabled package for validation purposes that would be a safer choice.

2024-09-13 12:44 UTC, aleksmaus commented
> Until we get the agentless cursor state persistence solved we need to hold on merging this. We do have some integrations like `ti_abusech` that do not depend on persistence so if we needed to push out an agentless-enabled package for validation purposes that would be a safer choice.

It's going to be a problem in general for the agent as well, because the agent has a state, identity, logs etc, that could be lost, causing the creation and enrollment of the new agents and loosing the state of data collection for any beat that collects logs.

2024-09-18 13:52 UTC, aleksmaus commented
> > It's going to be a problem in general for the agent as well, because the agent has a state, identity, logs etc, that could be lost, causing the creation and enrollment of the new agents and loosing the state of data collection for any beat that collects logs.
> 
> @aleksmaus can you elaborate? Why do you think that will be a problem?

In the fairly stable cluster where the pod is not relocated between the nodes often or maybe never. The state loss would not happen often while utilizing the ```emptyDir``` (non-memory backed) as a storage, but there are cases where it might happen including the reasons our of our control (k8s provider operations).

Let me turn my previous statement into questions. Maybe it's not a problem and is already addressed in some way that I don't know about. 

Regarding the Agent data itself, lets say the Agent data is lost. What happens next?
I assume the new agent would be enrolled, creating the new agent document with new identity (agent id).

1. What happens to the old agent document? What is the user experience?
2. What happens to the agent specific settings (logging level, containment? maybe something else per agent)?
3. Are there any pending actions tied to the previous agent id that the newly created agent could miss?
4. What happens with the data history collected in the stack which is tied to the specific agent id, like alerts, diagnostics, data collected, logs? Is the agent id reassigned/reused somehow?
5. Is this acceptable to potentially lose some of the logs that didn't make to Elasticsearch from the previous instance of the agent?
6. And from the point of view of any "data shipper"/beat/collector, as we already discussed before losing the persistent state/cursor/queue would lead to the duplicate data or data loss. Is this acceptable?

Am I missing anything? It's totally possible that there is something is already being done about these that I'm just not aware of at the moment.
Let me know if this is already being addressed either with the implementation or the documentation of the expectations.

2024-11-05 16:10 UTC, aleksmaus commented
Resolved conflicts, since this PR been stale for awhile

2024-11-05 16:21 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17937)
* Commit: 166d5068e5212401f3c5cc7206246f7474561068

### Failed CI Steps
* [Check integrations okta](https://buildkite.com/elastic/integrations/builds/17937#0192fd1d-8fe0-4918-b90a-1042c1b57c91)

### History
* :green_heart: [Build #15842](https://buildkite.com/elastic/integrations/builds/15842) succeeded 3687e0820c58b455f8924b7f408e297f6b2a8107
* :green_heart: [Build #15839](https://buildkite.com/elastic/integrations/builds/15839) succeeded e793c28310cab1520c68559510ac3a4a989e519d

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17937","number":17937,"commit":"166d5068e5212401f3c5cc7206246f7474561068"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15842","number":15842,"commit":"3687e0820c58b455f8924b7f408e297f6b2a8107"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15839","number":15839,"commit":"e793c28310cab1520c68559510ac3a4a989e519d"}],"number":17937}
buildkite-pr-comment-->

2024-12-13 16:01 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/19483)
* Commit: 2cb28f340986e345dbce1e534d8bf267e1f5457a

### History
* :green_heart: [Build #18275](https://buildkite.com/elastic/integrations/builds/18275) succeeded c8b4fac9483442551206964251b4a284b46acbc9
* :broken_heart: [Build #17937](https://buildkite.com/elastic/integrations/builds/17937) failed 166d5068e5212401f3c5cc7206246f7474561068
* :green_heart: [Build #15842](https://buildkite.com/elastic/integrations/builds/15842) succeeded 3687e0820c58b455f8924b7f408e297f6b2a8107
* :green_heart: [Build #15839](https://buildkite.com/elastic/integrations/builds/15839) succeeded e793c28310cab1520c68559510ac3a4a989e519d

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19483","number":19483,"commit":"2cb28f340986e345dbce1e534d8bf267e1f5457a"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18275","number":18275,"commit":"c8b4fac9483442551206964251b4a284b46acbc9"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17937","number":17937,"commit":"166d5068e5212401f3c5cc7206246f7474561068"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15842","number":15842,"commit":"3687e0820c58b455f8924b7f408e297f6b2a8107"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15839","number":15839,"commit":"e793c28310cab1520c68559510ac3a4a989e519d"}],"number":19483}
buildkite-pr-comment-->

2025-01-16 11:14 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20499)
* Commit: 62de72e870fadad2085ba6314d012efe42313eaf

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/20499#01946ed1-9da9-40a8-917b-3895adeb38fd)

### History
* :green_heart: [Build #19483](https://buildkite.com/elastic/integrations/builds/19483) succeeded 2cb28f340986e345dbce1e534d8bf267e1f5457a
* :green_heart: [Build #18275](https://buildkite.com/elastic/integrations/builds/18275) succeeded c8b4fac9483442551206964251b4a284b46acbc9
* :broken_heart: [Build #17937](https://buildkite.com/elastic/integrations/builds/17937) failed 166d5068e5212401f3c5cc7206246f7474561068
* :green_heart: [Build #15842](https://buildkite.com/elastic/integrations/builds/15842) succeeded 3687e0820c58b455f8924b7f408e297f6b2a8107
* :green_heart: [Build #15839](https://buildkite.com/elastic/integrations/builds/15839) succeeded e793c28310cab1520c68559510ac3a4a989e519d

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20499","number":20499,"commit":"62de72e870fadad2085ba6314d012efe42313eaf"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19483","number":19483,"commit":"2cb28f340986e345dbce1e534d8bf267e1f5457a"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18275","number":18275,"commit":"c8b4fac9483442551206964251b4a284b46acbc9"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17937","number":17937,"commit":"166d5068e5212401f3c5cc7206246f7474561068"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15842","number":15842,"commit":"3687e0820c58b455f8924b7f408e297f6b2a8107"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15839","number":15839,"commit":"e793c28310cab1520c68559510ac3a4a989e519d"}],"number":20499}
buildkite-pr-comment-->

2025-01-16 11:35 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20500)
* Commit: 0b5482fbf23c072c0163e991844e4701714d26bc

### History
* :broken_heart: [Build #20499](https://buildkite.com/elastic/integrations/builds/20499) failed 62de72e870fadad2085ba6314d012efe42313eaf
* :green_heart: [Build #19483](https://buildkite.com/elastic/integrations/builds/19483) succeeded 2cb28f340986e345dbce1e534d8bf267e1f5457a
* :green_heart: [Build #18275](https://buildkite.com/elastic/integrations/builds/18275) succeeded c8b4fac9483442551206964251b4a284b46acbc9
* :broken_heart: [Build #17937](https://buildkite.com/elastic/integrations/builds/17937) failed 166d5068e5212401f3c5cc7206246f7474561068
* :green_heart: [Build #15842](https://buildkite.com/elastic/integrations/builds/15842) succeeded 3687e0820c58b455f8924b7f408e297f6b2a8107
* :green_heart: [Build #15839](https://buildkite.com/elastic/integrations/builds/15839) succeeded e793c28310cab1520c68559510ac3a4a989e519d

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20500","number":20500,"commit":"0b5482fbf23c072c0163e991844e4701714d26bc"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20499","number":20499,"commit":"62de72e870fadad2085ba6314d012efe42313eaf"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19483","number":19483,"commit":"2cb28f340986e345dbce1e534d8bf267e1f5457a"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18275","number":18275,"commit":"c8b4fac9483442551206964251b4a284b46acbc9"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17937","number":17937,"commit":"166d5068e5212401f3c5cc7206246f7474561068"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15842","number":15842,"commit":"3687e0820c58b455f8924b7f408e297f6b2a8107"}],"number":20500}
buildkite-pr-comment-->

2025-02-05 03:27 UTC, closed without merging