carbon_black_cloud: nsure alert search range is a valid temporal ordeing
elastic/integrations pull request #11149
Opened 2024-09-17 00:02 UTC by efd6

## Proposed commit message

See title.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## How to test this PR locally

## Related issues

- 

## Screenshots

2024-09-17 00:38 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/15970)
* Commit: 336e08fe3ac833d22a8d2cf24b9d56cc38e2c364

cc @efd6

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15970","number":15970,"commit":"336e08fe3ac833d22a8d2cf24b9d56cc38e2c364"}],"number":15970}
buildkite-pr-comment-->

2024-09-17 00:44 UTC, elasticmachine commented
Pinging @elastic/security-service-integrations (Team:Security-Service Integrations)

2024-09-17 06:53 UTC, chrisberkhout requested changes

2024-09-17 06:53 UTC, chrisberkhout commented on packages/carbon_black_cloud/data_stream/alert_v7/agent/stream/cel.yml.hbs
> +  				"time_range": (now - duration("15m")).as(delayed, {
This logic looks good.

As mentioned elsewhere, I think we can reduce the 15m to 60s, remove the [note](https://github.com/elastic/integrations/blob/2e72e8524728daca2d47c814d8042031b8f5804f/packages/carbon_black_cloud/_dev/build/docs/README.md?plain=1#L81-L83) in the README and link to the [documentation](https://developer.carbonblack.com/reference/carbon-black-cloud/guides/alert-bulk-export/) here.

2024-09-17 07:43 UTC, efd6 commented on packages/carbon_black_cloud/data_stream/alert_v7/agent/stream/cel.yml.hbs
> +  				"time_range": (now - duration("15m")).as(delayed, {
Do you think it's worth making this configurable?

2024-09-17 21:04 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16019)
* Commit: 37e5c7dc7bbec502a43a96733bdccedddbdce4d0

### History
* :green_heart: [Build #15970](https://buildkite.com/elastic/integrations/builds/15970) succeeded 336e08fe3ac833d22a8d2cf24b9d56cc38e2c364

cc @efd6

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16019","number":16019,"commit":"37e5c7dc7bbec502a43a96733bdccedddbdce4d0"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/15970","number":15970,"commit":"336e08fe3ac833d22a8d2cf24b9d56cc38e2c364"}],"number":16019}
buildkite-pr-comment-->

2024-09-18 08:38 UTC, chrisberkhout commented on packages/carbon_black_cloud/data_stream/alert_v7/agent/stream/cel.yml.hbs
> +  				"time_range": (now - duration("15m")).as(delayed, {
No, I don't think so.

I think it's probably just a matter of a timestamp being assigned a value in application code and then written after a variable delay, or being assigned in a database with multiple write nodes and then replicated with variable delay. So they're out of order by roughly the duration of a request. There could be other systems with longer delays, but if they say 60 seconds it's probably 1ms - 15s that we're really worried about.

2024-09-19 16:34 UTC, chrisberkhout approved these changes

2024-09-19 21:18 UTC, merged

2024-09-23 14:35 UTC, jamiehynds commented
@efd6 there's a custom on our Discuss forums still reporting an issue with Carbon Black after updating to the latest integration. https://discuss.elastic.co/t/carbon-black-cloud-cel-alert-v7-400-bad-request/366464/3