aws.securityhub_findings: Improve support for CDR
elastic/integrations pull request #11158
Opened 2024-09-17 13:01 UTC by kcreddy

## Proposed commit message

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## How to test this PR locally

## Related issues

- 

## Screenshots

2024-09-17 14:37 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16013)
* Commit: 364c668f4e1320fc65ce9e1b02c8d1df96c60049

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16013","number":16013,"commit":"364c668f4e1320fc65ce9e1b02c8d1df96c60049"}],"number":16013}
buildkite-pr-comment-->

2024-09-20 12:43 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16222)
* Commit: 866e8c9d5e387c90f9919a40728c01a8beb551cf

### History
* :green_heart: [Build #16013](https://buildkite.com/elastic/integrations/builds/16013) succeeded 364c668f4e1320fc65ce9e1b02c8d1df96c60049

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16222","number":16222,"commit":"866e8c9d5e387c90f9919a40728c01a8beb551cf"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16013","number":16013,"commit":"364c668f4e1320fc65ce9e1b02c8d1df96c60049"}],"number":16222}
buildkite-pr-comment-->

2024-09-23 08:00 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16287)
* Commit: a73b971c97461539863fe2ad584e23b03ae01b57

### History
* :green_heart: [Build #16222](https://buildkite.com/elastic/integrations/builds/16222) succeeded 866e8c9d5e387c90f9919a40728c01a8beb551cf
* :green_heart: [Build #16013](https://buildkite.com/elastic/integrations/builds/16013) succeeded 364c668f4e1320fc65ce9e1b02c8d1df96c60049

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16287","number":16287,"commit":"a73b971c97461539863fe2ad584e23b03ae01b57"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16222","number":16222,"commit":"866e8c9d5e387c90f9919a40728c01a8beb551cf"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16013","number":16013,"commit":"364c668f4e1320fc65ce9e1b02c8d1df96c60049"}],"number":16287}
buildkite-pr-comment-->

2024-09-23 12:24 UTC, elasticmachine commented
Pinging @elastic/security-service-integrations (Team:Security-Service Integrations)

2024-09-23 12:41 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16294)
* Commit: 549ea69b8044f6ac7e45c12583596381402a68eb

### Failed CI Steps
* [Check integrations aws](https://buildkite.com/elastic/integrations/builds/16294#01921edb-a0c8-4a02-a00e-b566f1ab5752)

### History
* :green_heart: [Build #16287](https://buildkite.com/elastic/integrations/builds/16287) succeeded a73b971c97461539863fe2ad584e23b03ae01b57
* :green_heart: [Build #16222](https://buildkite.com/elastic/integrations/builds/16222) succeeded 866e8c9d5e387c90f9919a40728c01a8beb551cf
* :green_heart: [Build #16013](https://buildkite.com/elastic/integrations/builds/16013) succeeded 364c668f4e1320fc65ce9e1b02c8d1df96c60049

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16294","number":16294,"commit":"549ea69b8044f6ac7e45c12583596381402a68eb"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16287","number":16287,"commit":"a73b971c97461539863fe2ad584e23b03ae01b57"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16222","number":16222,"commit":"866e8c9d5e387c90f9919a40728c01a8beb551cf"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16013","number":16013,"commit":"364c668f4e1320fc65ce9e1b02c8d1df96c60049"}],"number":16294}
buildkite-pr-comment-->

2024-09-23 19:09 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16315)
* Commit: 09a3e99c71743f4fa6538d23a93c80c70538446c

### History
* :broken_heart: [Build #16294](https://buildkite.com/elastic/integrations/builds/16294) failed 549ea69b8044f6ac7e45c12583596381402a68eb
* :green_heart: [Build #16287](https://buildkite.com/elastic/integrations/builds/16287) succeeded a73b971c97461539863fe2ad584e23b03ae01b57
* :green_heart: [Build #16222](https://buildkite.com/elastic/integrations/builds/16222) succeeded 866e8c9d5e387c90f9919a40728c01a8beb551cf
* :green_heart: [Build #16013](https://buildkite.com/elastic/integrations/builds/16013) succeeded 364c668f4e1320fc65ce9e1b02c8d1df96c60049

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16315","number":16315,"commit":"09a3e99c71743f4fa6538d23a93c80c70538446c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16294","number":16294,"commit":"549ea69b8044f6ac7e45c12583596381402a68eb"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16287","number":16287,"commit":"a73b971c97461539863fe2ad584e23b03ae01b57"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16222","number":16222,"commit":"866e8c9d5e387c90f9919a40728c01a8beb551cf"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16013","number":16013,"commit":"364c668f4e1320fc65ce9e1b02c8d1df96c60049"}],"number":16315}
buildkite-pr-comment-->

2024-09-24 04:43 UTC, efd6 reviewed
The issue refers to a document upload, but I cannot find it. So I cannot see whether this follows what has been designed. Is there a reason this is not a public document in the issue?

2024-09-24 04:43 UTC, efd6 commented on packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
> +      if: ctx.json?.UpdatedAt != null && ctx.json?.UpdatedAt != ''
```suggestion
      if: ctx.json?.UpdatedAt != null && ctx.json.UpdatedAt != ''
```

2024-09-24 04:43 UTC, efd6 commented on packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
> +      if: ctx.json?.ProcessedAt != null && ctx.json?.ProcessedAt != ''
```suggestion
      if: ctx.json?.ProcessedAt != null && ctx.json.ProcessedAt != ''
```

2024-09-24 04:43 UTC, efd6 commented on packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
> +      value: '{{{aws.securityhub_findings.remediation.recommendation.text}}} \n {{{aws.securityhub_findings.remediation.recommendation.url}}}'
Is this `\n` intentional? It won't be expanded since we are in single quotes.

2024-09-24 04:43 UTC, efd6 commented on packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
> +        // This extraction logic is only for single resource case. Multiple resources are extracted inside script - script_extract_fields_from_multiple_resources.
Why is this differentiated?

2024-09-24 09:52 UTC, kcreddy commented on packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
> +      value: '{{{aws.securityhub_findings.remediation.recommendation.text}}} \n {{{aws.securityhub_findings.remediation.recommendation.url}}}'
Thanks for pointing this out. I've modified it in [f898ffc](https://github.com/elastic/integrations/pull/11158/commits/f898ffcedd1ecbc6c5675e4c34b69626195ef767) to make it similar to Wiz. 

https://github.com/elastic/integrations/blob/4c3838725b4174509eb91f5dc067a32290f8ef76/packages/wiz/data_stream/cloud_configuration_finding/_dev/test/pipeline/test-cloud-configuration-finding.log-expected.json#L45

The field is a markdown and should be expanded. Example:
<img width="868" alt="Screenshot 2024-09-24 at 3 20 59 PM" src="https://github.com/user-attachments/assets/c6567054-2bb8-4d39-8363-f4a9b0bfc7bd">

2024-09-24 09:54 UTC, kcreddy commented on packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
> +      value: '{{{aws.securityhub_findings.remediation.recommendation.text}}} \n {{{aws.securityhub_findings.remediation.recommendation.url}}}'
@maxcold, does this make sense to use `\r\n` as delimiter to append `remediation.text` and `remediation.url` to derive the field `rule.remediation`? The outcome is similar to Wiz.

2024-09-24 09:58 UTC, kcreddy commented on packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
> +        // This extraction logic is only for single resource case. Multiple resources are extracted inside script - script_extract_fields_from_multiple_resources.
I've added comment to the issue now: https://github.com/elastic/integrations/issues/11040#issuecomment-2370820278 which links it to the suggestion on why this was opted.

2024-09-24 09:59 UTC, kcreddy commented on packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
> +        // This extraction logic is only for single resource case. Multiple resources are extracted inside script - script_extract_fields_from_multiple_resources.
I've also added comments to the beginning of script on why this separation was made.

2024-09-24 11:16 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16348)
* Commit: f898ffcedd1ecbc6c5675e4c34b69626195ef767

### History
* :green_heart: [Build #16315](https://buildkite.com/elastic/integrations/builds/16315) succeeded 09a3e99c71743f4fa6538d23a93c80c70538446c
* :broken_heart: [Build #16294](https://buildkite.com/elastic/integrations/builds/16294) failed 549ea69b8044f6ac7e45c12583596381402a68eb
* :green_heart: [Build #16287](https://buildkite.com/elastic/integrations/builds/16287) succeeded a73b971c97461539863fe2ad584e23b03ae01b57
* :green_heart: [Build #16222](https://buildkite.com/elastic/integrations/builds/16222) succeeded 866e8c9d5e387c90f9919a40728c01a8beb551cf
* :green_heart: [Build #16013](https://buildkite.com/elastic/integrations/builds/16013) succeeded 364c668f4e1320fc65ce9e1b02c8d1df96c60049

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16348","number":16348,"commit":"f898ffcedd1ecbc6c5675e4c34b69626195ef767"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16315","number":16315,"commit":"09a3e99c71743f4fa6538d23a93c80c70538446c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16294","number":16294,"commit":"549ea69b8044f6ac7e45c12583596381402a68eb"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16287","number":16287,"commit":"a73b971c97461539863fe2ad584e23b03ae01b57"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16222","number":16222,"commit":"866e8c9d5e387c90f9919a40728c01a8beb551cf"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16013","number":16013,"commit":"364c668f4e1320fc65ce9e1b02c8d1df96c60049"}],"number":16348}
buildkite-pr-comment-->

2024-09-25 02:39 UTC, efd6 reviewed
I'm not completely comfortable approving this based on a set of linked proposals that don't have a conclusion (there are items that appear to be still under discussion) and are spread across those documents. IMO a summary acceptance document should be prepared and made public so that users can see what the intended behaviour is, and so that reviewers and maintainers can have truth to base future work on.

2024-09-25 02:39 UTC, efd6 commented on packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
> +      value: "{{{aws.securityhub_findings.remediation.recommendation.text}}} \r\n {{{aws.securityhub_findings.remediation.recommendation.url}}}"
```suggestion
      value: "{{{aws.securityhub_findings.remediation.recommendation.text}}}\r\n{{{aws.securityhub_findings.remediation.recommendation.url}}}"
```
Otherwise there is a trailing space on the first line and a leading space on the second.

2024-09-25 02:39 UTC, efd6 commented on packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
> +      copy_from : aws.securityhub_findings.updated_at
```suggestion
      copy_from: aws.securityhub_findings.updated_at
```

2024-09-25 02:39 UTC, efd6 commented on packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
> +            res_name = tokenList[tokenList.length - 1];
Is there is no `/`, !bang. Is there guaranteed to be one?

2024-09-25 02:39 UTC, efd6 commented on packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
> +          }
Conditionally execute all of this if `res.Details != null` and `s/res\.Details\?/res.Details/g`.

2024-09-25 02:39 UTC, efd6 commented on packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
> +          // Extract ECS user field
Block conditional on `res.Details != null`.

2024-09-25 03:07 UTC, efd6 commented on packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
> +      value: state
Can this be made a constant keyword?

2024-09-25 03:07 UTC, efd6 commented on packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
> +      tag: set_cloud_provider
Constant keywords?

2024-09-25 13:58 UTC, CohenIdo commented
It seems that some fields (`host.name`, `rule.author`) that were mapped [here](https://docs.google.com/spreadsheets/d/11jXBnH0JFrscPiiH4ZA3lHLjAn0x_XB-ly9yCuzniQU/edit?gid=0#gid=0) are missing.

2024-09-25 13:59 UTC, CohenIdo requested changes
It seems that some fields (`host.name`, `rule.author`) that were mapped [here](https://docs.google.com/spreadsheets/d/11jXBnH0JFrscPiiH4ZA3lHLjAn0x_XB-ly9yCuzniQU/edit?gid=0#gid=0) are missing.

2024-09-25 14:16 UTC, andrewkroh commented
> IMO a summary acceptance document should be prepared and made public so that users can see what the intended behaviour is, and so that reviewers and maintainers can have truth to base future work on.

++

Logistically, I think a markdown doc in https://github.com/elastic/integrations/tree/main/docs would be ideal for integration developers. It's public, version controlled, and close to the integrations that will implement its guidance.

2024-09-25 17:20 UTC, kcreddy commented on packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
> +      value: state
Do you know if this would cause a conflict between existing `keyword` and `constant_keyword`? I can also test this.
In general, since the `constant_keyword` contains same value for all documents inside an index, what if there was a bug in this value and it has to be changed? Would an integration upgrade automatically rollover the datastream-backed index, so that new index will be populated with updated value?

2024-09-25 17:21 UTC, kcreddy commented on packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
> +      tag: set_cloud_provider
Waiting for clarity on https://github.com/elastic/integrations/pull/11158#discussion_r1775652768 to apply the `constant_keyword` or not.

2024-09-25 17:39 UTC, kcreddy commented on packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
> +          // Extract ECS user field
updated with block conditional.

2024-09-25 17:39 UTC, kcreddy commented on packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
> +          }
updated with block conditional.

2024-09-25 17:40 UTC, kcreddy commented on packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
> +      value: "{{{aws.securityhub_findings.remediation.recommendation.text}}} \r\n {{{aws.securityhub_findings.remediation.recommendation.url}}}"
updated as suggested.

2024-09-25 17:40 UTC, kcreddy commented on packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
> +      copy_from : aws.securityhub_findings.updated_at
updated as suggested

2024-09-25 17:49 UTC, kcreddy commented on packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
> +            res_name = tokenList[tokenList.length - 1];
As per https://docs.aws.amazon.com/IAM/latest/UserGuide/reference-arns.html, it is possible that `/` is not necessary. Also, for S3 object, taking the last `/` would only provide incomplete object prefix.
Hence, I updated to split on `:` and take the last `:`. This would mean previous `i-0e2ede89308a594d7` would now be `instance/i-0e2ede89308a594d7`, i.e., an additional `<resource-type>/` will be added as prefix. Is this tradeoff okay?
Note that this case of splitting by `/` or `:` will only happen if the `.Name` is not present in `Details`.

2024-09-25 18:32 UTC, kcreddy commented
> It seems that some fields (host.name, rule.author) that were mapped [here](https://docs.google.com/spreadsheets/d/11jXBnH0JFrscPiiH4ZA3lHLjAn0x_XB-ly9yCuzniQU/edit?gid=0#gid=0) are missing.
@CohenIdo, The `host.name` was missed. I noticed that `host.name` is infact missing for resources of type `AwsEc2Instance`, but it is present for `AwsEcsContainer`. I added accordingly. 
Also, `host.ip` was missed for `AwsEc2Instance` which is also added.
Commit [0897d24](https://github.com/elastic/integrations/pull/11158/commits/0897d247be25de2bfc6d53e41b62802cedbbdfb4) has both changes.

As per clarification from @maxcold, I skipped `rule.author`

2024-09-25 20:07 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16427)
* Commit: 0897d247be25de2bfc6d53e41b62802cedbbdfb4

### History
* :green_heart: [Build #16348](https://buildkite.com/elastic/integrations/builds/16348) succeeded f898ffcedd1ecbc6c5675e4c34b69626195ef767
* :green_heart: [Build #16315](https://buildkite.com/elastic/integrations/builds/16315) succeeded 09a3e99c71743f4fa6538d23a93c80c70538446c
* :broken_heart: [Build #16294](https://buildkite.com/elastic/integrations/builds/16294) failed 549ea69b8044f6ac7e45c12583596381402a68eb
* :green_heart: [Build #16287](https://buildkite.com/elastic/integrations/builds/16287) succeeded a73b971c97461539863fe2ad584e23b03ae01b57
* :green_heart: [Build #16222](https://buildkite.com/elastic/integrations/builds/16222) succeeded 866e8c9d5e387c90f9919a40728c01a8beb551cf
* :green_heart: [Build #16013](https://buildkite.com/elastic/integrations/builds/16013) succeeded 364c668f4e1320fc65ce9e1b02c8d1df96c60049

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16427","number":16427,"commit":"0897d247be25de2bfc6d53e41b62802cedbbdfb4"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16348","number":16348,"commit":"f898ffcedd1ecbc6c5675e4c34b69626195ef767"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16315","number":16315,"commit":"09a3e99c71743f4fa6538d23a93c80c70538446c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16294","number":16294,"commit":"549ea69b8044f6ac7e45c12583596381402a68eb"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16287","number":16287,"commit":"a73b971c97461539863fe2ad584e23b03ae01b57"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16222","number":16222,"commit":"866e8c9d5e387c90f9919a40728c01a8beb551cf"}],"number":16427}
buildkite-pr-comment-->

2024-09-25 23:04 UTC, efd6 commented on packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
> +          if (res.Details != null) {
```suggestion

          // Extract ECS orchestrator field
```
?

2024-09-25 23:04 UTC, efd6 commented on packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
> +          if (res.Details != null) {
```suggestion

          // Extract ECS orchestrator field
```
?

2024-09-25 23:30 UTC, andrewkroh commented on packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
> +      value: state
> Do you know if this would cause a conflict between existing keyword and constant_keyword? I can also test this.

These data types are in the same keyword family so there should not be any issue.

> In general, since the constant_keyword contains same value for all documents inside an index, what if there was a bug in this value and it has to be changed?

The index must be rolled over if you want to change a constant_keyword value. Fleet _should_ handle this automatically, but I would test this scenario because we have seen bugs recently in optimizations made to limit rollovers to cases where they are necessary.

2024-09-26 09:21 UTC, kcreddy commented
> > IMO a summary acceptance document should be prepared and made public so that users can see what the intended behaviour is, and so that reviewers and maintainers can have truth to base future work on.
> 
> ++
> 
> Logistically, I think a markdown doc in https://github.com/elastic/integrations/tree/main/docs would be ideal for integration developers. It's public, version controlled, and close to the integrations that will implement its guidance.

Regards to https://github.com/elastic/integrations/pull/11158#pullrequestreview-2326828544: 

@maxcold / @CohenIdo, could you make the guide `Adapting data stream to Cloud Security in Kibana` publicly available in https://github.com/elastic/integrations/tree/main/docs?

2024-09-26 09:37 UTC, kcreddy commented on packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
> +      tag: set_cloud_provider
Updated to `constant_keyword` in [69603d5](https://github.com/elastic/integrations/pull/11158/commits/69603d51729dfee260d67da680b1c02ff33ac626)

2024-09-26 09:37 UTC, kcreddy commented on packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
> +      value: state
I tested the rollover and it is working as expected.
Updated to `constant_keyword` in [69603d5](https://github.com/elastic/integrations/pull/11158/commits/69603d51729dfee260d67da680b1c02ff33ac626)

2024-09-26 09:52 UTC, kcreddy commented on packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
> +          if (res.Details != null) {
Done in [a806320](https://github.com/elastic/integrations/pull/11158/commits/a80632023edc9676c45c31f9dc3670bf1ffce6e2)

2024-09-26 09:52 UTC, kcreddy commented on packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
> +          if (res.Details != null) {
Done in [a806320](https://github.com/elastic/integrations/pull/11158/commits/a80632023edc9676c45c31f9dc3670bf1ffce6e2)

2024-09-26 11:46 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16473)
* Commit: a80632023edc9676c45c31f9dc3670bf1ffce6e2

### History
* :green_heart: [Build #16427](https://buildkite.com/elastic/integrations/builds/16427) succeeded 0897d247be25de2bfc6d53e41b62802cedbbdfb4
* :green_heart: [Build #16348](https://buildkite.com/elastic/integrations/builds/16348) succeeded f898ffcedd1ecbc6c5675e4c34b69626195ef767
* :green_heart: [Build #16315](https://buildkite.com/elastic/integrations/builds/16315) succeeded 09a3e99c71743f4fa6538d23a93c80c70538446c
* :broken_heart: [Build #16294](https://buildkite.com/elastic/integrations/builds/16294) failed 549ea69b8044f6ac7e45c12583596381402a68eb
* :green_heart: [Build #16287](https://buildkite.com/elastic/integrations/builds/16287) succeeded a73b971c97461539863fe2ad584e23b03ae01b57
* :green_heart: [Build #16222](https://buildkite.com/elastic/integrations/builds/16222) succeeded 866e8c9d5e387c90f9919a40728c01a8beb551cf

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16473","number":16473,"commit":"a80632023edc9676c45c31f9dc3670bf1ffce6e2"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16427","number":16427,"commit":"0897d247be25de2bfc6d53e41b62802cedbbdfb4"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16348","number":16348,"commit":"f898ffcedd1ecbc6c5675e4c34b69626195ef767"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16315","number":16315,"commit":"09a3e99c71743f4fa6538d23a93c80c70538446c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16294","number":16294,"commit":"549ea69b8044f6ac7e45c12583596381402a68eb"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16287","number":16287,"commit":"a73b971c97461539863fe2ad584e23b03ae01b57"}],"number":16473}
buildkite-pr-comment-->

2024-09-30 07:59 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16581)
* Commit: a914bcf7603e1664bcdfae86721f9336fc1ba535

### History
* :green_heart: [Build #16473](https://buildkite.com/elastic/integrations/builds/16473) succeeded a80632023edc9676c45c31f9dc3670bf1ffce6e2
* :green_heart: [Build #16427](https://buildkite.com/elastic/integrations/builds/16427) succeeded 0897d247be25de2bfc6d53e41b62802cedbbdfb4
* :green_heart: [Build #16348](https://buildkite.com/elastic/integrations/builds/16348) succeeded f898ffcedd1ecbc6c5675e4c34b69626195ef767
* :green_heart: [Build #16315](https://buildkite.com/elastic/integrations/builds/16315) succeeded 09a3e99c71743f4fa6538d23a93c80c70538446c
* :broken_heart: [Build #16294](https://buildkite.com/elastic/integrations/builds/16294) failed 549ea69b8044f6ac7e45c12583596381402a68eb
* :green_heart: [Build #16287](https://buildkite.com/elastic/integrations/builds/16287) succeeded a73b971c97461539863fe2ad584e23b03ae01b57

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16581","number":16581,"commit":"a914bcf7603e1664bcdfae86721f9336fc1ba535"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16473","number":16473,"commit":"a80632023edc9676c45c31f9dc3670bf1ffce6e2"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16427","number":16427,"commit":"0897d247be25de2bfc6d53e41b62802cedbbdfb4"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16348","number":16348,"commit":"f898ffcedd1ecbc6c5675e4c34b69626195ef767"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16315","number":16315,"commit":"09a3e99c71743f4fa6538d23a93c80c70538446c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16294","number":16294,"commit":"549ea69b8044f6ac7e45c12583596381402a68eb"}],"number":16581}
buildkite-pr-comment-->

2024-10-02 12:29 UTC, maxcold commented on packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
> +      value: '{{{aws.securityhub_findings.remediation.recommendation.text}}} \n {{{aws.securityhub_findings.remediation.recommendation.url}}}'
I think it makes sense

2024-10-02 14:35 UTC, maxcold commented on packages/aws/data_stream/securityhub_findings/fields/result.yml
> +    - name: evidence
as far as I can see aws security hub doesn't provide evidence, at least I don't see it in the ingest pipeline, so let's not map it. This structure matches Wiz but native for example doesn't map `result.evidence` at all as cloudbeat provides arbitrary object as evidence

2024-10-02 14:37 UTC, maxcold commented on packages/aws/data_stream/securityhub_findings/fields/resource.yml
> +    - name: sub_type
we don't provide `sub_type` atm, should we avoid mapping it just yet?

2024-10-02 14:41 UTC, maxcold commented on packages/aws/data_stream/securityhub_findings/fields/rule.yml
> +    - name: uuid
I see that we are not providing `uuid` in the ingest pipeline, remind me what is the outcome regarding this field? If we decide not to provide it for now, it probably makes sense to remove it from the mapping as well

2024-10-02 14:53 UTC, maxcold requested changes
I think we need to double check the version, probably should be a preview version. Also some questions regarding the mappings

2024-10-02 14:53 UTC, maxcold commented on packages/aws/manifest.yml
> -version: 2.25.0-preview01
I think having 2.25.0-preview01 while 2.25.0 has been already released was a typo in the https://github.com/elastic/integrations/pull/11115/files#diff-0051942df0fb72638a0d9837c6151eff8475149d600860c5972cd41d96ca68e3R2 , I guess it should have been `2.26.0-preivew01` as it introduces the kibana version change to `version: "^8.16.0"` 
Should we now go with `2.26.0-preview01` ?

2024-10-02 14:57 UTC, maxcold commented
@kcreddy thanks for highlighting the question about the guide. Let me bring up back with the team. In short I have two concerns:
- the guide is still in progress in some parts
- it focuses on a specific Kibana features support, which feels a bit weird to be a part of general integration dev documentation.
I wonder if we should decouple this PR from making the guide public.

2024-10-02 15:53 UTC, kcreddy commented on packages/aws/data_stream/securityhub_findings/fields/rule.yml
> +    - name: uuid
Yes, the suggestion was to use `rule.id` instead of `rule.uuid` for the transform and ignore this for now.

2024-10-02 16:04 UTC, kcreddy commented on packages/aws/manifest.yml
> -version: 2.25.0-preview01
I was following the Wiz changes which used non-preview versions for mapping related changes: https://github.com/elastic/integrations/pull/10892 and https://github.com/elastic/integrations/pull/10790. 
Later, the transform was added as preview versions. Do you think preview versions makes more sense because of untested mappings?

> Should we now go with 2.26.0-preview01 ?

Considering that its a typo, if we go with preview versions, shouldn't we go with `2.26.0-preview02` or `2.27.0-preview01` because the previous one should've been `2.26.0-preview01`?

2024-10-02 16:06 UTC, kcreddy commented on packages/aws/data_stream/securityhub_findings/fields/rule.yml
> +    - name: uuid
Removed `rule.uuid`

2024-10-02 16:07 UTC, kcreddy commented on packages/aws/data_stream/securityhub_findings/fields/resource.yml
> +    - name: sub_type
Removed `sub_type`

2024-10-02 16:07 UTC, kcreddy commented on packages/aws/data_stream/securityhub_findings/fields/result.yml
> +    - name: evidence
Removed `result.evidence` from mapping.

2024-10-02 16:18 UTC, kcreddy commented
> @kcreddy thanks for highlighting the question about the guide. Let me bring up back with the team. In short I have two concerns:
> 
> * the guide is still in progress in some parts
> * it focuses on a specific Kibana features support, which feels a bit weird to be a part of general integration dev documentation.
>   I wonder if we should decouple this PR from making the guide public.

Hey @efd6 / @andrewkroh, 

Based on above concerns from @maxcold, would it be okay to decouple this public guide from AWS SecurityHub integration updates and move towards merging this PR? 
Wiz and AWS SecurityHub should help clear some open questions regarding CSPM workflow after which the guide can be made public. Then the guide can be used as source of truth for subsequent integration reviews.

2024-10-02 16:51 UTC, maxcold commented on packages/aws/manifest.yml
> -version: 2.25.0-preview01
I'm not sure how best to resolve this version confusion :) maybe releasing first `2.26.0-preview01` separately with the same changelog as `2.25.0-preview01` and then using `2.26.0-preview02` here would do to keep the versioning consistent? 

as for non-preview version, I guess this is exactly the concern regarding versioning with previews the team had - now as main has kibana dependency 8.16.0 which is not released, we are bound to preview versions. Or we need to backport to 2.25.x but it can only be patch version, which doesn't make sense from the amount of changes perspective. I guess we need to keep with preview until 8.16.0 is released

2024-10-02 17:54 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16714)
* Commit: 6d9d901022a6f17a1388aa9180a1b022856abdee

### History
* :green_heart: [Build #16581](https://buildkite.com/elastic/integrations/builds/16581) succeeded a914bcf7603e1664bcdfae86721f9336fc1ba535
* :green_heart: [Build #16473](https://buildkite.com/elastic/integrations/builds/16473) succeeded a80632023edc9676c45c31f9dc3670bf1ffce6e2
* :green_heart: [Build #16427](https://buildkite.com/elastic/integrations/builds/16427) succeeded 0897d247be25de2bfc6d53e41b62802cedbbdfb4
* :green_heart: [Build #16348](https://buildkite.com/elastic/integrations/builds/16348) succeeded f898ffcedd1ecbc6c5675e4c34b69626195ef767
* :green_heart: [Build #16315](https://buildkite.com/elastic/integrations/builds/16315) succeeded 09a3e99c71743f4fa6538d23a93c80c70538446c
* :broken_heart: [Build #16294](https://buildkite.com/elastic/integrations/builds/16294) failed 549ea69b8044f6ac7e45c12583596381402a68eb

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16714","number":16714,"commit":"6d9d901022a6f17a1388aa9180a1b022856abdee"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16581","number":16581,"commit":"a914bcf7603e1664bcdfae86721f9336fc1ba535"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16473","number":16473,"commit":"a80632023edc9676c45c31f9dc3670bf1ffce6e2"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16427","number":16427,"commit":"0897d247be25de2bfc6d53e41b62802cedbbdfb4"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16348","number":16348,"commit":"f898ffcedd1ecbc6c5675e4c34b69626195ef767"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16315","number":16315,"commit":"09a3e99c71743f4fa6538d23a93c80c70538446c"}],"number":16714}
buildkite-pr-comment-->

2024-10-02 20:40 UTC, efd6 commented on packages/aws/manifest.yml
> -version: 2.25.0-preview01
For fear of sounding like a broken record, including preview releases in the main branch causes problems. I think that these should be released as versioned preview branches. This does not resolve our current issue, but if it had happened would have prevented them.

2024-10-02 20:42 UTC, efd6 commented
@kcreddy If this becomes a subset of the changes here that are explained by a finalised public document, that would be fine with me.

2024-10-07 07:11 UTC, kcreddy commented
@maxcold, as per our latest discussion, I added the transform in the latest commit: [603643a](https://github.com/elastic/integrations/pull/11158/commits/603643ac69933209c8f8bd6ef9833f74de6fcc9d). I installed package and tested transform on `8.16.0-SNAPSHOT` cluster using this guide: https://www.elastic.co/guide/en/integrations-developer/current/elastic-package.html#_customization.

2024-10-07 08:46 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16841)
* Commit: 603643ac69933209c8f8bd6ef9833f74de6fcc9d

### History
* :green_heart: [Build #16714](https://buildkite.com/elastic/integrations/builds/16714) succeeded 6d9d901022a6f17a1388aa9180a1b022856abdee
* :green_heart: [Build #16581](https://buildkite.com/elastic/integrations/builds/16581) succeeded a914bcf7603e1664bcdfae86721f9336fc1ba535
* :green_heart: [Build #16473](https://buildkite.com/elastic/integrations/builds/16473) succeeded a80632023edc9676c45c31f9dc3670bf1ffce6e2
* :green_heart: [Build #16427](https://buildkite.com/elastic/integrations/builds/16427) succeeded 0897d247be25de2bfc6d53e41b62802cedbbdfb4
* :green_heart: [Build #16348](https://buildkite.com/elastic/integrations/builds/16348) succeeded f898ffcedd1ecbc6c5675e4c34b69626195ef767
* :green_heart: [Build #16315](https://buildkite.com/elastic/integrations/builds/16315) succeeded 09a3e99c71743f4fa6538d23a93c80c70538446c

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16841","number":16841,"commit":"603643ac69933209c8f8bd6ef9833f74de6fcc9d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16714","number":16714,"commit":"6d9d901022a6f17a1388aa9180a1b022856abdee"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16581","number":16581,"commit":"a914bcf7603e1664bcdfae86721f9336fc1ba535"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16473","number":16473,"commit":"a80632023edc9676c45c31f9dc3670bf1ffce6e2"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16427","number":16427,"commit":"0897d247be25de2bfc6d53e41b62802cedbbdfb4"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16348","number":16348,"commit":"f898ffcedd1ecbc6c5675e4c34b69626195ef767"}],"number":16841}
buildkite-pr-comment-->

2024-10-07 21:47 UTC, maxcold commented on packages/aws/manifest.yml
> -version: 2.25.0-preview01
@romulets fyi as it concerns the change you made in the scope of cloud assets work

2024-10-07 21:50 UTC, maxcold commented on packages/aws/manifest.yml
> -version: 2.25.0-preview01
@efd6 can you provide more details on `I think that these should be released as versioned preview branches.` ? Do you mean a long living branch with the changes, from which we build integration manually and install programmatically on testing envs? or do you mean some other process?

2024-10-07 21:55 UTC, maxcold commented
@kcreddy thanks for incorporating the transforms into the PR. To clarify the current status - before merging this PR we want to try to overcome the issue of incremental APIs not providing full posture on the Kibana side. The idea is that we want to remove the retention period from our queries and increase the retention period on transforms for Wiz and AWS Security Hub to a large number (say 90 days) to give users an option by specifying a large enough initial interval to get a more complete posture view. This means that we want to ask to keep this PR open until we get an outcome of our investigation on Kibana side. Hope this makes sense

2024-10-07 22:20 UTC, efd6 commented on packages/aws/manifest.yml
> -version: 2.25.0-preview01
> Do you mean a long living branch with the changes, from which we build integration manually and install programmatically on testing envs?

Yes, this is what I mean. I am in a situation in #11112 where making a change that should be easy is significantly harder because of one of these preview changes.

2024-10-11 07:38 UTC, mbondyra approved these changes

2024-10-11 11:50 UTC, maxcold commented on packages/aws/elasticsearch/transform/latest_cdr_misconfigurations/transform.yml
> +    max_age: 26h
@kcreddy for 8.16 we decided to go with increased retention_policy to solve the issue of incremental data. Can you set this to `90d` ? It will align with the retention period on Kibana

2024-10-11 12:09 UTC, kcreddy commented on packages/aws/elasticsearch/transform/latest_cdr_misconfigurations/transform.yml
> +    max_age: 26h
Updated transform retention to `90d` in [be802d8](https://github.com/elastic/integrations/pull/11158/commits/be802d8816d00a136ee597c63371b0b05ef17fc9)

2024-10-11 12:11 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17063)
* Commit: be802d8816d00a136ee597c63371b0b05ef17fc9

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/17063#01927b7b-e283-48de-b9fb-c330a51b23b0)

### History
* :green_heart: [Build #16841](https://buildkite.com/elastic/integrations/builds/16841) succeeded 603643ac69933209c8f8bd6ef9833f74de6fcc9d
* :green_heart: [Build #16714](https://buildkite.com/elastic/integrations/builds/16714) succeeded 6d9d901022a6f17a1388aa9180a1b022856abdee
* :green_heart: [Build #16581](https://buildkite.com/elastic/integrations/builds/16581) succeeded a914bcf7603e1664bcdfae86721f9336fc1ba535
* :green_heart: [Build #16473](https://buildkite.com/elastic/integrations/builds/16473) succeeded a80632023edc9676c45c31f9dc3670bf1ffce6e2
* :green_heart: [Build #16427](https://buildkite.com/elastic/integrations/builds/16427) succeeded 0897d247be25de2bfc6d53e41b62802cedbbdfb4
* :green_heart: [Build #16348](https://buildkite.com/elastic/integrations/builds/16348) succeeded f898ffcedd1ecbc6c5675e4c34b69626195ef767

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17063","number":17063,"commit":"be802d8816d00a136ee597c63371b0b05ef17fc9"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16841","number":16841,"commit":"603643ac69933209c8f8bd6ef9833f74de6fcc9d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16714","number":16714,"commit":"6d9d901022a6f17a1388aa9180a1b022856abdee"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16581","number":16581,"commit":"a914bcf7603e1664bcdfae86721f9336fc1ba535"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16473","number":16473,"commit":"a80632023edc9676c45c31f9dc3670bf1ffce6e2"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16427","number":16427,"commit":"0897d247be25de2bfc6d53e41b62802cedbbdfb4"}],"number":17063}
buildkite-pr-comment-->

2024-10-11 12:45 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17064)
* Commit: 6b31c8a24c2b5333f057dd44ebf7501e4d93a7ef

### Failed CI Steps
* [Check integrations aws](https://buildkite.com/elastic/integrations/builds/17064#01927b91-7c3b-49dc-b367-8ec71c2607c0)

### History
* :broken_heart: [Build #17063](https://buildkite.com/elastic/integrations/builds/17063) failed be802d8816d00a136ee597c63371b0b05ef17fc9
* :green_heart: [Build #16841](https://buildkite.com/elastic/integrations/builds/16841) succeeded 603643ac69933209c8f8bd6ef9833f74de6fcc9d
* :green_heart: [Build #16714](https://buildkite.com/elastic/integrations/builds/16714) succeeded 6d9d901022a6f17a1388aa9180a1b022856abdee
* :green_heart: [Build #16581](https://buildkite.com/elastic/integrations/builds/16581) succeeded a914bcf7603e1664bcdfae86721f9336fc1ba535
* :green_heart: [Build #16473](https://buildkite.com/elastic/integrations/builds/16473) succeeded a80632023edc9676c45c31f9dc3670bf1ffce6e2
* :green_heart: [Build #16427](https://buildkite.com/elastic/integrations/builds/16427) succeeded 0897d247be25de2bfc6d53e41b62802cedbbdfb4

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17064","number":17064,"commit":"6b31c8a24c2b5333f057dd44ebf7501e4d93a7ef"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17063","number":17063,"commit":"be802d8816d00a136ee597c63371b0b05ef17fc9"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16841","number":16841,"commit":"603643ac69933209c8f8bd6ef9833f74de6fcc9d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16714","number":16714,"commit":"6d9d901022a6f17a1388aa9180a1b022856abdee"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16581","number":16581,"commit":"a914bcf7603e1664bcdfae86721f9336fc1ba535"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16473","number":16473,"commit":"a80632023edc9676c45c31f9dc3670bf1ffce6e2"}],"number":17064}
buildkite-pr-comment-->

2024-10-11 13:16 UTC, kcreddy commented
/test

2024-10-11 13:38 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17066)
* Commit: 6b31c8a24c2b5333f057dd44ebf7501e4d93a7ef

### Failed CI Steps
* [Check integrations aws](https://buildkite.com/elastic/integrations/builds/17066#01927bbe-17e3-4ab6-93a1-6e851773029f)

### History
* :broken_heart: [Build #17064](https://buildkite.com/elastic/integrations/builds/17064) failed 6b31c8a24c2b5333f057dd44ebf7501e4d93a7ef
* :broken_heart: [Build #17063](https://buildkite.com/elastic/integrations/builds/17063) failed be802d8816d00a136ee597c63371b0b05ef17fc9
* :green_heart: [Build #16841](https://buildkite.com/elastic/integrations/builds/16841) succeeded 603643ac69933209c8f8bd6ef9833f74de6fcc9d
* :green_heart: [Build #16714](https://buildkite.com/elastic/integrations/builds/16714) succeeded 6d9d901022a6f17a1388aa9180a1b022856abdee
* :green_heart: [Build #16581](https://buildkite.com/elastic/integrations/builds/16581) succeeded a914bcf7603e1664bcdfae86721f9336fc1ba535

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17066","number":17066,"commit":"6b31c8a24c2b5333f057dd44ebf7501e4d93a7ef"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17064","number":17064,"commit":"6b31c8a24c2b5333f057dd44ebf7501e4d93a7ef"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17063","number":17063,"commit":"be802d8816d00a136ee597c63371b0b05ef17fc9"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16841","number":16841,"commit":"603643ac69933209c8f8bd6ef9833f74de6fcc9d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16714","number":16714,"commit":"6d9d901022a6f17a1388aa9180a1b022856abdee"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16581","number":16581,"commit":"a914bcf7603e1664bcdfae86721f9336fc1ba535"}],"number":17066}
buildkite-pr-comment-->

2024-10-11 20:14 UTC, maxcold approved these changes
A couple of more comments to fix and good to go. Thanks for the patience!

2024-10-11 20:14 UTC, maxcold commented on packages/aws/elasticsearch/transform/latest_cdr_misconfigurations/fields/rule.yml
> +    - name: description
`description`, `remediation` and `reference` can be changed to `keyword`

2024-10-11 20:14 UTC, maxcold commented on packages/aws/elasticsearch/transform/latest_cdr_misconfigurations/fields/rule.yml
> +    - name: description
Initially I mapped them incorrectly in the guide, I updated the guide as well

2024-10-11 20:14 UTC, maxcold commented on packages/aws/elasticsearch/transform/latest_cdr_misconfigurations/fields/rule.yml
> +    - name: references
`references` is non-ecs field, we decided to get rid of it before 8.16 https://github.com/elastic/kibana/pull/195932/files , let's remove it from the mapping and from the ingest pipeline, to avoid depricating it later

2024-10-15 05:03 UTC, kcreddy commented on packages/aws/elasticsearch/transform/latest_cdr_misconfigurations/fields/rule.yml
> +    - name: references
Got it. Please also update the guide on this.

2024-10-15 05:04 UTC, kcreddy commented on packages/aws/elasticsearch/transform/latest_cdr_misconfigurations/fields/rule.yml
> +    - name: description
Updated in  [6ae7527](https://github.com/elastic/integrations/pull/11158/commits/6ae75270fcf916ed94372d847bc6fc7cc42857e1)

2024-10-15 05:11 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17126)
* Commit: 6ae75270fcf916ed94372d847bc6fc7cc42857e1

### Failed CI Steps
* [Check integrations aws](https://buildkite.com/elastic/integrations/builds/17126#01928e92-61c6-4dcc-a288-b384abbf4c83)

### History
* :broken_heart: [Build #17066](https://buildkite.com/elastic/integrations/builds/17066) failed 6b31c8a24c2b5333f057dd44ebf7501e4d93a7ef
* :broken_heart: [Build #17064](https://buildkite.com/elastic/integrations/builds/17064) failed 6b31c8a24c2b5333f057dd44ebf7501e4d93a7ef
* :broken_heart: [Build #17063](https://buildkite.com/elastic/integrations/builds/17063) failed be802d8816d00a136ee597c63371b0b05ef17fc9
* :green_heart: [Build #16841](https://buildkite.com/elastic/integrations/builds/16841) succeeded 603643ac69933209c8f8bd6ef9833f74de6fcc9d
* :green_heart: [Build #16714](https://buildkite.com/elastic/integrations/builds/16714) succeeded 6d9d901022a6f17a1388aa9180a1b022856abdee

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17126","number":17126,"commit":"6ae75270fcf916ed94372d847bc6fc7cc42857e1"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17066","number":17066,"commit":"6b31c8a24c2b5333f057dd44ebf7501e4d93a7ef"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17064","number":17064,"commit":"6b31c8a24c2b5333f057dd44ebf7501e4d93a7ef"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17063","number":17063,"commit":"be802d8816d00a136ee597c63371b0b05ef17fc9"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16841","number":16841,"commit":"603643ac69933209c8f8bd6ef9833f74de6fcc9d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16714","number":16714,"commit":"6d9d901022a6f17a1388aa9180a1b022856abdee"}],"number":17126}
buildkite-pr-comment-->

2024-10-15 05:46 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17127)
* Commit: 63fdd870ee049819f3785678258e85e719fee3a6

### Failed CI Steps
* [Check integrations aws](https://buildkite.com/elastic/integrations/builds/17127#01928ead-f924-407d-b755-cd6701eea684)

### History
* :broken_heart: [Build #17126](https://buildkite.com/elastic/integrations/builds/17126) failed 6ae75270fcf916ed94372d847bc6fc7cc42857e1
* :broken_heart: [Build #17066](https://buildkite.com/elastic/integrations/builds/17066) failed 6b31c8a24c2b5333f057dd44ebf7501e4d93a7ef
* :broken_heart: [Build #17064](https://buildkite.com/elastic/integrations/builds/17064) failed 6b31c8a24c2b5333f057dd44ebf7501e4d93a7ef
* :broken_heart: [Build #17063](https://buildkite.com/elastic/integrations/builds/17063) failed be802d8816d00a136ee597c63371b0b05ef17fc9
* :green_heart: [Build #16841](https://buildkite.com/elastic/integrations/builds/16841) succeeded 603643ac69933209c8f8bd6ef9833f74de6fcc9d

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17127","number":17127,"commit":"63fdd870ee049819f3785678258e85e719fee3a6"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17126","number":17126,"commit":"6ae75270fcf916ed94372d847bc6fc7cc42857e1"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17066","number":17066,"commit":"6b31c8a24c2b5333f057dd44ebf7501e4d93a7ef"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17064","number":17064,"commit":"6b31c8a24c2b5333f057dd44ebf7501e4d93a7ef"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17063","number":17063,"commit":"be802d8816d00a136ee597c63371b0b05ef17fc9"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16841","number":16841,"commit":"603643ac69933209c8f8bd6ef9833f74de6fcc9d"}],"number":17127}
buildkite-pr-comment-->

2024-10-15 07:27 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17128)
* Commit: b26ac6b58a548d3ca2c51251a3246917237e593b

### History
* :broken_heart: [Build #17127](https://buildkite.com/elastic/integrations/builds/17127) failed 63fdd870ee049819f3785678258e85e719fee3a6
* :broken_heart: [Build #17126](https://buildkite.com/elastic/integrations/builds/17126) failed 6ae75270fcf916ed94372d847bc6fc7cc42857e1
* :broken_heart: [Build #17066](https://buildkite.com/elastic/integrations/builds/17066) failed 6b31c8a24c2b5333f057dd44ebf7501e4d93a7ef
* :broken_heart: [Build #17064](https://buildkite.com/elastic/integrations/builds/17064) failed 6b31c8a24c2b5333f057dd44ebf7501e4d93a7ef
* :broken_heart: [Build #17063](https://buildkite.com/elastic/integrations/builds/17063) failed be802d8816d00a136ee597c63371b0b05ef17fc9

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17128","number":17128,"commit":"b26ac6b58a548d3ca2c51251a3246917237e593b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17127","number":17127,"commit":"63fdd870ee049819f3785678258e85e719fee3a6"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17126","number":17126,"commit":"6ae75270fcf916ed94372d847bc6fc7cc42857e1"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17066","number":17066,"commit":"6b31c8a24c2b5333f057dd44ebf7501e4d93a7ef"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17064","number":17064,"commit":"6b31c8a24c2b5333f057dd44ebf7501e4d93a7ef"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17063","number":17063,"commit":"be802d8816d00a136ee597c63371b0b05ef17fc9"}],"number":17128}
buildkite-pr-comment-->

2024-10-15 09:01 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17134)
* Commit: 1d92a8f381f66e096b18956c0f4759618215bbd0

### History
* :green_heart: [Build #17128](https://buildkite.com/elastic/integrations/builds/17128) succeeded b26ac6b58a548d3ca2c51251a3246917237e593b
* :broken_heart: [Build #17127](https://buildkite.com/elastic/integrations/builds/17127) failed 63fdd870ee049819f3785678258e85e719fee3a6
* :broken_heart: [Build #17126](https://buildkite.com/elastic/integrations/builds/17126) failed 6ae75270fcf916ed94372d847bc6fc7cc42857e1
* :broken_heart: [Build #17066](https://buildkite.com/elastic/integrations/builds/17066) failed 6b31c8a24c2b5333f057dd44ebf7501e4d93a7ef
* :broken_heart: [Build #17064](https://buildkite.com/elastic/integrations/builds/17064) failed 6b31c8a24c2b5333f057dd44ebf7501e4d93a7ef
* :broken_heart: [Build #17063](https://buildkite.com/elastic/integrations/builds/17063) failed be802d8816d00a136ee597c63371b0b05ef17fc9

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17134","number":17134,"commit":"1d92a8f381f66e096b18956c0f4759618215bbd0"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17128","number":17128,"commit":"b26ac6b58a548d3ca2c51251a3246917237e593b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17127","number":17127,"commit":"63fdd870ee049819f3785678258e85e719fee3a6"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17126","number":17126,"commit":"6ae75270fcf916ed94372d847bc6fc7cc42857e1"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17066","number":17066,"commit":"6b31c8a24c2b5333f057dd44ebf7501e4d93a7ef"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17064","number":17064,"commit":"6b31c8a24c2b5333f057dd44ebf7501e4d93a7ef"}],"number":17134}
buildkite-pr-comment-->

2024-10-28 19:23 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17658)
* Commit: 0dfc25d90caf9d3c16926705378c609e4acb9d35

### History
* :green_heart: [Build #17134](https://buildkite.com/elastic/integrations/builds/17134) succeeded 1d92a8f381f66e096b18956c0f4759618215bbd0
* :green_heart: [Build #17128](https://buildkite.com/elastic/integrations/builds/17128) succeeded b26ac6b58a548d3ca2c51251a3246917237e593b
* :broken_heart: [Build #17127](https://buildkite.com/elastic/integrations/builds/17127) failed 63fdd870ee049819f3785678258e85e719fee3a6
* :broken_heart: [Build #17126](https://buildkite.com/elastic/integrations/builds/17126) failed 6ae75270fcf916ed94372d847bc6fc7cc42857e1
* :broken_heart: [Build #17066](https://buildkite.com/elastic/integrations/builds/17066) failed 6b31c8a24c2b5333f057dd44ebf7501e4d93a7ef
* :broken_heart: [Build #17064](https://buildkite.com/elastic/integrations/builds/17064) failed 6b31c8a24c2b5333f057dd44ebf7501e4d93a7ef

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17658","number":17658,"commit":"0dfc25d90caf9d3c16926705378c609e4acb9d35"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17134","number":17134,"commit":"1d92a8f381f66e096b18956c0f4759618215bbd0"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17128","number":17128,"commit":"b26ac6b58a548d3ca2c51251a3246917237e593b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17127","number":17127,"commit":"63fdd870ee049819f3785678258e85e719fee3a6"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17126","number":17126,"commit":"6ae75270fcf916ed94372d847bc6fc7cc42857e1"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17066","number":17066,"commit":"6b31c8a24c2b5333f057dd44ebf7501e4d93a7ef"}],"number":17658}
buildkite-pr-comment-->

2024-10-28 21:40 UTC, andrewkroh commented on packages/aws/kibana/dashboard/aws-c9f103d0-5f63-11ed-bd69-473ce047ef30.json
> +                "title": "Events with Failure Findings [Logs AWS] (copy)",
Why is this labeled as a "(copy)"?

2024-10-28 21:40 UTC, andrewkroh commented on packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
> +      tag: set_cloud_provider
The three fields being converted to `constant_keyword` would all benefit from removal from `_source`.

I recommend setting the static values in the `ecs.yml` file where they fields are declared instead of the ingest pipeline, and then exchange the three `set` processors with a single `remove` processor that has a `description` field explaining that the fields are defined as constant_keyword and we are removing the fields from _source to gain storage efficiency.

2024-10-28 21:42 UTC, andrewkroh commented
Also, please update the commit message (in the PR description) to specify why the minimum kibana version was changed.

2024-10-29 06:01 UTC, kcreddy commented on packages/aws/kibana/dashboard/aws-c9f103d0-5f63-11ed-bd69-473ce047ef30.json
> +                "title": "Events with Failure Findings [Logs AWS] (copy)",
Removed `(copy)` from title. Perhaps added when visualisation was cloned to create a new one.

2024-10-29 06:02 UTC, kcreddy commented
@andrewkroh the comments are addressed in [0e44091](https://github.com/elastic/integrations/pull/11158/commits/0e4409161a73e99763b266042288416edace0599) and PR commit message is also updated.

2024-10-29 06:12 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17673)
* Commit: 0e4409161a73e99763b266042288416edace0599

### Failed CI Steps
* [Check integrations aws](https://buildkite.com/elastic/integrations/builds/17673#0192d6de-2490-4b28-91d5-1057285f5ee8)

### History
* :green_heart: [Build #17658](https://buildkite.com/elastic/integrations/builds/17658) succeeded 0dfc25d90caf9d3c16926705378c609e4acb9d35
* :green_heart: [Build #17134](https://buildkite.com/elastic/integrations/builds/17134) succeeded 1d92a8f381f66e096b18956c0f4759618215bbd0
* :green_heart: [Build #17128](https://buildkite.com/elastic/integrations/builds/17128) succeeded b26ac6b58a548d3ca2c51251a3246917237e593b
* :broken_heart: [Build #17127](https://buildkite.com/elastic/integrations/builds/17127) failed 63fdd870ee049819f3785678258e85e719fee3a6
* :broken_heart: [Build #17126](https://buildkite.com/elastic/integrations/builds/17126) failed 6ae75270fcf916ed94372d847bc6fc7cc42857e1
* :broken_heart: [Build #17066](https://buildkite.com/elastic/integrations/builds/17066) failed 6b31c8a24c2b5333f057dd44ebf7501e4d93a7ef

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17673","number":17673,"commit":"0e4409161a73e99763b266042288416edace0599"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17658","number":17658,"commit":"0dfc25d90caf9d3c16926705378c609e4acb9d35"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17134","number":17134,"commit":"1d92a8f381f66e096b18956c0f4759618215bbd0"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17128","number":17128,"commit":"b26ac6b58a548d3ca2c51251a3246917237e593b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17127","number":17127,"commit":"63fdd870ee049819f3785678258e85e719fee3a6"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17126","number":17126,"commit":"6ae75270fcf916ed94372d847bc6fc7cc42857e1"}],"number":17673}
buildkite-pr-comment-->

2024-10-30 01:30 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17700)
* Commit: d861580c3e04a68028aaba83476fa5ebadbd4062

### Failed CI Steps
* [Check integrations aws](https://buildkite.com/elastic/integrations/builds/17700#0192db07-dfe9-4356-8070-b1bfeb47c1be)

### History
* :broken_heart: [Build #17673](https://buildkite.com/elastic/integrations/builds/17673) failed 0e4409161a73e99763b266042288416edace0599
* :green_heart: [Build #17658](https://buildkite.com/elastic/integrations/builds/17658) succeeded 0dfc25d90caf9d3c16926705378c609e4acb9d35
* :green_heart: [Build #17134](https://buildkite.com/elastic/integrations/builds/17134) succeeded 1d92a8f381f66e096b18956c0f4759618215bbd0
* :green_heart: [Build #17128](https://buildkite.com/elastic/integrations/builds/17128) succeeded b26ac6b58a548d3ca2c51251a3246917237e593b
* :broken_heart: [Build #17127](https://buildkite.com/elastic/integrations/builds/17127) failed 63fdd870ee049819f3785678258e85e719fee3a6

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17700","number":17700,"commit":"d861580c3e04a68028aaba83476fa5ebadbd4062"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17673","number":17673,"commit":"0e4409161a73e99763b266042288416edace0599"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17658","number":17658,"commit":"0dfc25d90caf9d3c16926705378c609e4acb9d35"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17134","number":17134,"commit":"1d92a8f381f66e096b18956c0f4759618215bbd0"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17128","number":17128,"commit":"b26ac6b58a548d3ca2c51251a3246917237e593b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17127","number":17127,"commit":"63fdd870ee049819f3785678258e85e719fee3a6"}],"number":17700}
buildkite-pr-comment-->

2024-10-30 05:05 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17708)
* Commit: a0a7e23ccd71eae359f04875a95c133a3882c175

### History
* :broken_heart: [Build #17700](https://buildkite.com/elastic/integrations/builds/17700) failed d861580c3e04a68028aaba83476fa5ebadbd4062
* :broken_heart: [Build #17673](https://buildkite.com/elastic/integrations/builds/17673) failed 0e4409161a73e99763b266042288416edace0599
* :green_heart: [Build #17658](https://buildkite.com/elastic/integrations/builds/17658) succeeded 0dfc25d90caf9d3c16926705378c609e4acb9d35
* :green_heart: [Build #17134](https://buildkite.com/elastic/integrations/builds/17134) succeeded 1d92a8f381f66e096b18956c0f4759618215bbd0
* :green_heart: [Build #17128](https://buildkite.com/elastic/integrations/builds/17128) succeeded b26ac6b58a548d3ca2c51251a3246917237e593b

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17708","number":17708,"commit":"a0a7e23ccd71eae359f04875a95c133a3882c175"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17700","number":17700,"commit":"d861580c3e04a68028aaba83476fa5ebadbd4062"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17673","number":17673,"commit":"0e4409161a73e99763b266042288416edace0599"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17658","number":17658,"commit":"0dfc25d90caf9d3c16926705378c609e4acb9d35"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17134","number":17134,"commit":"1d92a8f381f66e096b18956c0f4759618215bbd0"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17128","number":17128,"commit":"b26ac6b58a548d3ca2c51251a3246917237e593b"}],"number":17708}
buildkite-pr-comment-->

2024-10-30 11:19 UTC, CohenIdo approved these changes

2024-10-30 12:50 UTC, andrewkroh approved these changes
I left a few more minor comments.

2024-10-30 12:50 UTC, andrewkroh commented on packages/aws/changelog.yml
> +    - description: Improve support for CDR in securityhub_findings data stream.
What is CDR? 😉 I recommend expanding the acronym to aid those less familiar with the terminology (`s/CDR/Cloud Detection and Response (CDR) workflows/`).

2024-10-30 12:50 UTC, andrewkroh commented on packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
> +      ignore_empty_value: true
With a static `value` (not a template) this option is unnecessary so I recommend to remove it (appears multiple times).

2024-10-30 12:50 UTC, andrewkroh commented on packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
> +            value: '{{{_ingest.on_failure_message}}}'
This error would benefit from more contextual information. As is, it might be hard to diagnose where it came from. I recommend adding a `tag` to the date processor, and using the same error value template as is added on L739.

2024-10-30 12:50 UTC, andrewkroh commented on packages/aws/elasticsearch/transform/latest_cdr_misconfigurations/fields/ecs.yml
> +- name: vulnerability.id
Duplicate definition. See L160.

2024-10-30 12:50 UTC, andrewkroh commented on packages/aws/elasticsearch/transform/latest_cdr_misconfigurations/fields/base-fields.yml
> +  value: aws.securityhub_findings
Duplicate definition. See ecs.yml#L44.

2024-10-30 13:30 UTC, kcreddy commented on packages/aws/elasticsearch/transform/latest_cdr_misconfigurations/fields/base-fields.yml
> +  value: aws.securityhub_findings
Removed duplicate from `ecs.yml` in [1080998](https://github.com/elastic/integrations/pull/11158/commits/10809981f74088910c11176a405febb94b40cccc).

2024-10-30 13:31 UTC, kcreddy commented on packages/aws/elasticsearch/transform/latest_cdr_misconfigurations/fields/ecs.yml
> +- name: vulnerability.id
Removed duplicate in [1080998](https://github.com/elastic/integrations/pull/11158/commits/10809981f74088910c11176a405febb94b40cccc).

2024-10-30 13:31 UTC, kcreddy commented on packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
> +            value: '{{{_ingest.on_failure_message}}}'
Added tag and updated error.message as suggested.

2024-10-30 13:59 UTC, andrewkroh commented on packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
> +      ignore_empty_value: true
I'm speaking about the `ignore_empty_value: true`. This option is unnecessary for non-template values. It leads to additional unnecessary `instanceof` checks in the processor code. Those would be short-circuited if `ignore_empty_value` were omitted.

2024-10-30 15:05 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17728)
* Commit: 10809981f74088910c11176a405febb94b40cccc

### History
* :green_heart: [Build #17708](https://buildkite.com/elastic/integrations/builds/17708) succeeded a0a7e23ccd71eae359f04875a95c133a3882c175
* :broken_heart: [Build #17700](https://buildkite.com/elastic/integrations/builds/17700) failed d861580c3e04a68028aaba83476fa5ebadbd4062
* :broken_heart: [Build #17673](https://buildkite.com/elastic/integrations/builds/17673) failed 0e4409161a73e99763b266042288416edace0599
* :green_heart: [Build #17658](https://buildkite.com/elastic/integrations/builds/17658) succeeded 0dfc25d90caf9d3c16926705378c609e4acb9d35
* :green_heart: [Build #17134](https://buildkite.com/elastic/integrations/builds/17134) succeeded 1d92a8f381f66e096b18956c0f4759618215bbd0
* :green_heart: [Build #17128](https://buildkite.com/elastic/integrations/builds/17128) succeeded b26ac6b58a548d3ca2c51251a3246917237e593b

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17728","number":17728,"commit":"10809981f74088910c11176a405febb94b40cccc"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17708","number":17708,"commit":"a0a7e23ccd71eae359f04875a95c133a3882c175"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17700","number":17700,"commit":"d861580c3e04a68028aaba83476fa5ebadbd4062"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17673","number":17673,"commit":"0e4409161a73e99763b266042288416edace0599"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17658","number":17658,"commit":"0dfc25d90caf9d3c16926705378c609e4acb9d35"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17134","number":17134,"commit":"1d92a8f381f66e096b18956c0f4759618215bbd0"}],"number":17728}
buildkite-pr-comment-->

2024-10-30 15:06 UTC, shmsr approved these changes
Based on other approvals, approving as a CODEOWNER from @elastic/obs-infraobs-integrations

2024-10-30 15:39 UTC, kcreddy commented on packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
> +      ignore_empty_value: true
Thanks for the clarification. Updated in [aafe9a9](https://github.com/elastic/integrations/pull/11158/commits/aafe9a93a42bcbde45a7c1c5b278e1fe45b98a1c)

2024-10-30 16:25 UTC, zmoog approved these changes

2024-10-30 17:11 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17732)
* Commit: aafe9a93a42bcbde45a7c1c5b278e1fe45b98a1c

### History
* :green_heart: [Build #17728](https://buildkite.com/elastic/integrations/builds/17728) succeeded 10809981f74088910c11176a405febb94b40cccc
* :green_heart: [Build #17708](https://buildkite.com/elastic/integrations/builds/17708) succeeded a0a7e23ccd71eae359f04875a95c133a3882c175
* :broken_heart: [Build #17700](https://buildkite.com/elastic/integrations/builds/17700) failed d861580c3e04a68028aaba83476fa5ebadbd4062
* :broken_heart: [Build #17673](https://buildkite.com/elastic/integrations/builds/17673) failed 0e4409161a73e99763b266042288416edace0599
* :green_heart: [Build #17658](https://buildkite.com/elastic/integrations/builds/17658) succeeded 0dfc25d90caf9d3c16926705378c609e4acb9d35
* :green_heart: [Build #17134](https://buildkite.com/elastic/integrations/builds/17134) succeeded 1d92a8f381f66e096b18956c0f4759618215bbd0

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17732","number":17732,"commit":"aafe9a93a42bcbde45a7c1c5b278e1fe45b98a1c"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17728","number":17728,"commit":"10809981f74088910c11176a405febb94b40cccc"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17708","number":17708,"commit":"a0a7e23ccd71eae359f04875a95c133a3882c175"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17700","number":17700,"commit":"d861580c3e04a68028aaba83476fa5ebadbd4062"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17673","number":17673,"commit":"0e4409161a73e99763b266042288416edace0599"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17658","number":17658,"commit":"0dfc25d90caf9d3c16926705378c609e4acb9d35"}],"number":17732}
buildkite-pr-comment-->

2024-10-30 17:17 UTC, andrewkroh commented on packages/aws/data_stream/securityhub_findings/elasticsearch/ingest_pipeline/default.yml
> +      ignore_empty_value: true
There are several occurrences of this beyond what was addressed in aafe9a9.

2024-10-30 17:32 UTC, merged