all: fix sample_event.json final newlines
elastic/integrations pull request #11174
Opened 2024-09-18 12:15 UTC by efd6

## Proposed commit message

```
This ensures that all sample_event.json files have no final new line,
and that the resulting generated README.md pre-blocks that show the
sample event do not include a final redundant blank line.

[git-generate]
parallel "perl -p -i -e 'chomp if eof'" {} ::: $(rg -l -U -g 'sample_event.json' '^}\n')
for d in $(git diff --name-only|cut -f1,2 -d/|sort|uniq); do (cd $d; elastic-package build); done
```

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## How to test this PR locally

## Related issues

- For elastic/elastic-package#2087

## Screenshots

2024-09-18 14:03 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16061)
* Commit: 6ec29cbde51e3091ec8a2b8313a37ac67f1f921b

cc @efd6

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16061","number":16061,"commit":"6ec29cbde51e3091ec8a2b8313a37ac67f1f921b"}],"number":16061}
buildkite-pr-comment-->

2024-09-18 21:02 UTC, elasticmachine commented
Pinging @elastic/elastic-agent-data-plane (Team:Elastic-Agent-Data-Plane)

2024-09-18 21:02 UTC, elasticmachine commented
Pinging @elastic/security-service-integrations (Team:Security-Service Integrations)

2024-09-18 21:02 UTC, elasticmachine commented
Pinging @elastic/sec-deployment-and-devices (Team:Security-Deployment and Devices)

2024-09-18 21:02 UTC, elasticmachine commented
Pinging @elastic/sec-linux-platform (Team:Security-Linux Platform)

2024-09-18 21:02 UTC, elasticmachine commented
Pinging @elastic/sec-windows-platform (Team:Security-Windows Platform)

2024-09-18 22:58 UTC, mjwolf approved these changes

2024-09-19 04:23 UTC, shmsr approved these changes

2024-09-19 08:57 UTC, zmoog approved these changes

2024-09-19 09:06 UTC, andrewkroh approved these changes

2024-09-19 12:59 UTC, mauri870 approved these changes

2024-09-19 14:23 UTC, jsoriano requested changes
Let's wait for a decision in https://github.com/elastic/elastic-package/pull/2087 before applying this change.

2024-09-19 21:18 UTC, efd6 commented
@jsoriano This is fixing an issue independent of that change.

2024-09-23 08:56 UTC, tetianakravchenko approved these changes

2024-09-23 10:40 UTC, nfritts approved these changes

2024-09-23 12:35 UTC, consulthys approved these changes
Approving for the Stack Monitoring team.
There's only a single change located in the `kibana` integration (`status` metric set)

2024-09-23 12:59 UTC, taylor-swanson approved these changes

2024-09-23 20:40 UTC, merged