Added deployment_mode and properties
elastic/integrations pull request #11203
Opened 2024-09-20 18:17 UTC by seanrathier

## Proposed commit message

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## How to test this PR locally

## Related issues

- 

## Screenshots

2024-09-20 18:27 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16246)
* Commit: 18678bd478ada16db93c9ae7f446073a5359c40f

### Failed CI Steps
* [Check integrations elastic_connectors](https://buildkite.com/elastic/integrations/builds/16246#019210ab-d08a-4443-8055-3dbe04abbc65)

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16246","number":16246,"commit":"18678bd478ada16db93c9ae7f446073a5359c40f"}],"number":16246}
buildkite-pr-comment-->

2024-09-23 14:53 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16304)
* Commit: af1b249e95fcbb5a51ae28610a1873d1f1f07cdb

### Failed CI Steps
* [Check integrations elastic_connectors](https://buildkite.com/elastic/integrations/builds/16304#01921f5b-5dbf-4fd7-9312-498fa16c4dea)

### History
* :broken_heart: [Build #16246](https://buildkite.com/elastic/integrations/builds/16246) failed 18678bd478ada16db93c9ae7f446073a5359c40f

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16304","number":16304,"commit":"af1b249e95fcbb5a51ae28610a1873d1f1f07cdb"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16246","number":16246,"commit":"18678bd478ada16db93c9ae7f446073a5359c40f"}],"number":16304}
buildkite-pr-comment-->

2024-10-10 21:25 UTC, seanrathier commented
When version 3.2.3 gets released next week, the CI should pass, and we should be able to merge.

2024-10-11 13:46 UTC, maxcold commented on packages/cloud_security_posture/changelog.yml
> +   - description: Added deployment_mode agentless to the policy template
nit: passing the review I once got from integrations team "add instead of added"

2024-10-11 13:46 UTC, maxcold commented on packages/cloud_security_posture/changelog.yml
>  - version: "1.11.0-preview08"
I think we need to bump the preview number here to `1.11.0-preview09`. The `1.11.0-preview08` has already been built and released

2024-10-11 13:46 UTC, maxcold commented on packages/elastic_connectors/changelog.yml
>  - version: 0.0.1
here I guess we also need to bump the version

2024-10-11 20:20 UTC, seanstory commented on packages/elastic_connectors/manifest.yml
> +        team: ingestion-team
Nit: https://github.com/orgs/elastic/teams/search-extract-and-transform is the better team for us (assuming you're using github teams). `ingestion-team` is an older group that's a little wider than we'd prefer to use.

2024-10-11 20:24 UTC, seanrathier commented on packages/cloud_security_posture/changelog.yml
>  - version: "1.11.0-preview08"
We need to be "1.11.0-preview11",  thanks for pointing this out.

2024-10-11 21:15 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17075)
* Commit: b2c4bc80191bf4417008d39dea33b781d7f54283

### Failed CI Steps
* [Check integrations elastic_connectors](https://buildkite.com/elastic/integrations/builds/17075#01927d6b-1bc1-41b3-8224-39ae88e6438e)

### History
* :broken_heart: [Build #16304](https://buildkite.com/elastic/integrations/builds/16304) failed af1b249e95fcbb5a51ae28610a1873d1f1f07cdb
* :broken_heart: [Build #16246](https://buildkite.com/elastic/integrations/builds/16246) failed 18678bd478ada16db93c9ae7f446073a5359c40f

cc @seanrathier

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17075","number":17075,"commit":"b2c4bc80191bf4417008d39dea33b781d7f54283"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16304","number":16304,"commit":"af1b249e95fcbb5a51ae28610a1873d1f1f07cdb"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16246","number":16246,"commit":"18678bd478ada16db93c9ae7f446073a5359c40f"}],"number":17075}
buildkite-pr-comment-->

2024-10-14 08:10 UTC, maxcold commented on packages/cloud_security_posture/changelog.yml
> +   - description: Added deployment_mode agentless to the policy template
remove this changelog entry as you added it to a new version

2024-10-14 08:10 UTC, maxcold commented on packages/elastic_connectors/changelog.yml
> +    - description: Added owner information when deployment_mode has agentless enabled
here as well

2024-10-14 08:14 UTC, maxcold requested changes
@seanrathier seems like some old code hasn't been removed, pls check

2024-10-14 08:14 UTC, maxcold commented on packages/elastic_connectors/manifest.yml
> +        team: ingestion-team
if I understood the review comment correctly the ask was to change `ingestion-team` to `search-extract-and-transform` but now we have both for some reason

2024-10-14 16:14 UTC, maxcold approved these changes

2024-10-14 16:23 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17110)
* Commit: 6b479934e74382dd408c3cefac86c639ed531ccf

### Failed CI Steps
* [Check integrations elastic_connectors](https://buildkite.com/elastic/integrations/builds/17110#01928bd2-ed41-497b-9e0c-232d7f6e0b4d)

### History
* :broken_heart: [Build #17075](https://buildkite.com/elastic/integrations/builds/17075) failed b2c4bc80191bf4417008d39dea33b781d7f54283
* :broken_heart: [Build #16304](https://buildkite.com/elastic/integrations/builds/16304) failed af1b249e95fcbb5a51ae28610a1873d1f1f07cdb
* :broken_heart: [Build #16246](https://buildkite.com/elastic/integrations/builds/16246) failed 18678bd478ada16db93c9ae7f446073a5359c40f

cc @seanrathier

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17110","number":17110,"commit":"6b479934e74382dd408c3cefac86c639ed531ccf"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17075","number":17075,"commit":"b2c4bc80191bf4417008d39dea33b781d7f54283"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16304","number":16304,"commit":"af1b249e95fcbb5a51ae28610a1873d1f1f07cdb"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16246","number":16246,"commit":"18678bd478ada16db93c9ae7f446073a5359c40f"}],"number":17110}
buildkite-pr-comment-->

2024-10-14 16:28 UTC, jsoriano commented
This change is co-dependant of https://github.com/elastic/integrations/pull/11400, we will merge both changes together in the other PR. Thanks!

2024-10-15 07:48 UTC, DianaJourdan approved these changes

2024-10-15 08:02 UTC, mrodm commented
@seanrathier @maxcold https://github.com/elastic/integrations/pull/11400 has already been merged. I think this PR can be closed.

2024-10-15 08:19 UTC, closed without merging