Add in technique.name field to the transform. Remove milliseconds from TQL query.
elastic/integrations pull request #11217
Opened 2024-09-23 18:32 UTC by GShepherdTC

- Bug
- Enhancement

## Proposed commit message

Add in technique.name field to the transform that came from a customer request. 
Remove milliseconds from TQL query as current code drops the last 0 in the milliseconds which causes as issue. 

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] Confirm new field is consistent across files 

## How to test this PR locally

Test by running against TC with correct data including technique tag on an indicator. Confirm in ES that technique name is included. And then confirm in the ES request logs that milliseconds are not included in API request. 

## Related issues

- 

## Screenshots

-

2024-09-23 18:58 UTC, elasticmachine commented
Pinging @elastic/security-service-integrations (Team:Security-Service Integrations)

2024-09-24 04:18 UTC, efd6 commented on packages/ti_threatconnect/changelog.yml
> +- version: "1.2.3"
```suggestion
- version: "1.3.0"
```
(enhancements bump minor)

2024-09-24 04:18 UTC, efd6 commented on packages/ti_threatconnect/manifest.yml
> +version: "1.2.3"
```suggestion
version: "1.3.0"
```

2024-09-24 04:18 UTC, efd6 commented on packages/ti_threatconnect/data_stream/indicator/elasticsearch/ingest_pipeline/default.yml
> +      source: >-
```suggestion
      source: |-
```

2024-09-24 04:18 UTC, efd6 commented on packages/ti_threatconnect/data_stream/indicator/agent/stream/cel.yml.hbs
> +          state.?cursor.last_timestamp.orValue(string((now - duration(state.initial_interval)).format(time_layout.DateTime)))
```suggestion
          state.?cursor.last_timestamp.orValue(string((now - duration(state.initial_interval)).format(time_layout.RFC3339)))
```
`time_layout.DateTime` is not the same as the DateTime that ThreatConnect use, theirs is [RFC3339 (they say ISO8601, but the example they show is in the intersection)](https://docs.threatconnect.com/en/latest/tcex/module_utils.html#date-to-datetime), `time_layout.DateTime` looks like "2006-01-02 15:04:05".

2024-09-24 04:18 UTC, efd6 commented on packages/ti_threatconnect/data_stream/indicator/agent/stream/cel.yml.hbs
> +# milliseconds and if it ended in 0, that 0 would be dropped and TC TQL then would error on the timestamp.
```suggestion
```
Their documentation is enough.

2024-09-24 05:45 UTC, kcreddy commented on packages/ti_threatconnect/data_stream/indicator/elasticsearch/ingest_pipeline/default.yml
> +            t_names.add(obj.get('name'));
Is it possible that only `techniqueId` exists but `name` doesn't? 
Have you come across such scenario in the data?

2024-09-24 05:45 UTC, kcreddy commented on packages/ti_threatconnect/data_stream/indicator/elasticsearch/ingest_pipeline/default.yml
> +  # Some tags are Attack Patterns, map technique name to ES field if technique ID exists
```suggestion
  # Some tags are Attack Patterns, map technique name to ECS field if technique ID exists
```

2024-09-24 05:45 UTC, kcreddy commented on packages/ti_threatconnect/data_stream/indicator/elasticsearch/ingest_pipeline/default.yml
> +# Some tags are Attack Patterns, map technique id to ES field
```suggestion
# Some tags are Attack Patterns, map technique id to ECS field
```

2024-09-24 05:45 UTC, kcreddy commented
/test

2024-09-24 05:55 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16335)
* Commit: 0af9db3fbed279a8d7d50ba23c7ccbbf9db5ca03

### Failed CI Steps
* [Check integrations ti_threatconnect](https://buildkite.com/elastic/integrations/builds/16335#01922294-c004-4cdc-a679-80dc7d373ff9)

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16335","number":16335,"commit":"0af9db3fbed279a8d7d50ba23c7ccbbf9db5ca03"}],"number":16335}
buildkite-pr-comment-->

2024-09-24 13:06 UTC, GShepherdTC commented on packages/ti_threatconnect/data_stream/indicator/agent/stream/cel.yml.hbs
> +          state.?cursor.last_timestamp.orValue(string((now - duration(state.initial_interval)).format(time_layout.DateTime)))
We want to stay with .DateTime as the format as it provides the exact format you posted in your comment. RFC3339 can include milliseconds which we don't want.

2024-09-24 13:10 UTC, GShepherdTC commented on packages/ti_threatconnect/data_stream/indicator/elasticsearch/ingest_pipeline/default.yml
> +      source: >-
Will include this change. Can you point me to painless docs that talk about the different between > and | in this context?  Or explain the reason for the change?  I just copied from an example.

2024-09-24 13:11 UTC, GShepherdTC commented on packages/ti_threatconnect/data_stream/indicator/elasticsearch/ingest_pipeline/default.yml
> +            t_names.add(obj.get('name'));
No. Our system requires a name if the tag type is an 'attack' tag which means it has a technique ID.

2024-09-24 19:13 UTC, kcreddy approved these changes

2024-09-24 20:45 UTC, efd6 commented on packages/ti_threatconnect/data_stream/indicator/agent/stream/cel.yml.hbs
> +          state.?cursor.last_timestamp.orValue(string((now - duration(state.initial_interval)).format(time_layout.DateTime)))
> RFC3339 can include milliseconds which we don't want.

This is not true. [`time_layout.RFC3339`](https://pkg.go.dev/github.com/elastic/mito/lib#hdr-Global_Variables-Time) is based on [`time.RFC3339`](https://pkg.go.dev/time#pkg-constants) which formats the time without sub-second resolution. If we were using `time_layout.RFC3339Nano` then it would be true, but that is not what is being suggested.

`time_layout.DateTime` is not ISO 8601 and does not include time zone information.

2024-09-24 20:46 UTC, efd6 commented on packages/ti_threatconnect/data_stream/indicator/elasticsearch/ingest_pipeline/default.yml
> +      source: >-
These are YAML syntax. The `>` mark indicates flowed text while the `|` mark indicates retention of new lines. This is described in the string literals section of the YAML spec.

2024-09-24 20:47 UTC, efd6 requested changes
Blocking until time rendering issue is resolved.

2024-09-24 20:51 UTC, efd6 commented on packages/ti_threatconnect/changelog.yml
> +- version: "1.2.3"
This has not been done.

2024-09-25 15:01 UTC, GShepherdTC commented on packages/ti_threatconnect/data_stream/indicator/agent/stream/cel.yml.hbs
> +          state.?cursor.last_timestamp.orValue(string((now - duration(state.initial_interval)).format(time_layout.DateTime)))
I just looked at the base spec for that RFC and say millis were possible.  Thanks for the detail on the 2 different formats.  Will accept this change.

2024-09-25 15:02 UTC, GShepherdTC reviewed
Accepting suggested changes.

2024-09-26 04:12 UTC, andrewkroh commented
/test

2024-09-26 04:31 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16450)
* Commit: 66c025a658509e4e70b56edfcef3c2adb93d44f7

### History
* :broken_heart: [Build #16335](https://buildkite.com/elastic/integrations/builds/16335) failed 0af9db3fbed279a8d7d50ba23c7ccbbf9db5ca03

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16450","number":16450,"commit":"66c025a658509e4e70b56edfcef3c2adb93d44f7"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16335","number":16335,"commit":"0af9db3fbed279a8d7d50ba23c7ccbbf9db5ca03"}],"number":16450}
buildkite-pr-comment-->

2024-09-27 13:20 UTC, GShepherdTC commented on packages/ti_threatconnect/data_stream/indicator/agent/stream/cel.yml.hbs
> +# milliseconds and if it ended in 0, that 0 would be dropped and TC TQL then would error on the timestamp.
Thanks. Its still a correct comment. The old/default format caused issues with our API since it would drop the last numeric if it was a 0.  The new format that you suggested, works just fine.

2024-09-30 00:07 UTC, efd6 commented
/test

2024-09-30 00:24 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16568)
* Commit: 089983e1630311ebb2105a65d9927c93366c260e

### History
* :green_heart: [Build #16450](https://buildkite.com/elastic/integrations/builds/16450) succeeded 66c025a658509e4e70b56edfcef3c2adb93d44f7
* :broken_heart: [Build #16335](https://buildkite.com/elastic/integrations/builds/16335) failed 0af9db3fbed279a8d7d50ba23c7ccbbf9db5ca03

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16568","number":16568,"commit":"089983e1630311ebb2105a65d9927c93366c260e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16450","number":16450,"commit":"66c025a658509e4e70b56edfcef3c2adb93d44f7"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16335","number":16335,"commit":"0af9db3fbed279a8d7d50ba23c7ccbbf9db5ca03"}],"number":16568}
buildkite-pr-comment-->

2024-09-30 00:44 UTC, efd6 commented on packages/ti_threatconnect/data_stream/indicator/agent/stream/cel.yml.hbs
> +          state.?cursor.last_timestamp.orValue(string((now - duration(state.initial_interval)).format(time_layout.RFC3339)))
```suggestion
          state.?cursor.last_timestamp.orValue((now - duration(state.initial_interval)).format(time_layout.RFC3339))
```
`.format()` returns a string, so the type conversion is not necessary. I'll deal with this.

2024-09-30 00:46 UTC, efd6 commented
/test

2024-09-30 01:02 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16569)
* Commit: 0e3500167a01a46ec1cd5a09c9385a04773e0a21

### History
* :green_heart: [Build #16568](https://buildkite.com/elastic/integrations/builds/16568) succeeded 089983e1630311ebb2105a65d9927c93366c260e
* :green_heart: [Build #16450](https://buildkite.com/elastic/integrations/builds/16450) succeeded 66c025a658509e4e70b56edfcef3c2adb93d44f7
* :broken_heart: [Build #16335](https://buildkite.com/elastic/integrations/builds/16335) failed 0af9db3fbed279a8d7d50ba23c7ccbbf9db5ca03

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16569","number":16569,"commit":"0e3500167a01a46ec1cd5a09c9385a04773e0a21"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16568","number":16568,"commit":"089983e1630311ebb2105a65d9927c93366c260e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16450","number":16450,"commit":"66c025a658509e4e70b56edfcef3c2adb93d44f7"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16335","number":16335,"commit":"0af9db3fbed279a8d7d50ba23c7ccbbf9db5ca03"}],"number":16569}
buildkite-pr-comment-->

2024-09-30 01:27 UTC, merged