[vSphere] Update README and fix Resourcepool datastream TSDB
elastic/integrations pull request #11242
Opened 2024-09-25 11:22 UTC by kush-elastic

- Enhancement

## Description

- Fix TSDB issue in resource pool datastream
- Update README

2024-09-25 12:03 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16408)
* Commit: 71d3d4a1726210c18fa1b54500d5bbadd8b4daa2

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16408","number":16408,"commit":"71d3d4a1726210c18fa1b54500d5bbadd8b4daa2"}],"number":16408}
buildkite-pr-comment-->

2024-09-26 05:40 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16455)
* Commit: 2a8987f4012f8c262cf46837a1b77499c29c4d52

### History
* :green_heart: [Build #16408](https://buildkite.com/elastic/integrations/builds/16408) succeeded 71d3d4a1726210c18fa1b54500d5bbadd8b4daa2

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16455","number":16455,"commit":"2a8987f4012f8c262cf46837a1b77499c29c4d52"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16408","number":16408,"commit":"71d3d4a1726210c18fa1b54500d5bbadd8b4daa2"}],"number":16455}
buildkite-pr-comment-->

2024-09-26 07:05 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16457)
* Commit: ff4bd77422f8121b29958975322bec2edbf7f3f1

### Failed CI Steps
* [Check integrations vsphere](https://buildkite.com/elastic/integrations/builds/16457#01922d1e-3173-4f1d-89e5-c7e016e7631c)

### History
* :green_heart: [Build #16455](https://buildkite.com/elastic/integrations/builds/16455) succeeded 2a8987f4012f8c262cf46837a1b77499c29c4d52
* :green_heart: [Build #16408](https://buildkite.com/elastic/integrations/builds/16408) succeeded 71d3d4a1726210c18fa1b54500d5bbadd8b4daa2

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16457","number":16457,"commit":"ff4bd77422f8121b29958975322bec2edbf7f3f1"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16455","number":16455,"commit":"2a8987f4012f8c262cf46837a1b77499c29c4d52"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16408","number":16408,"commit":"71d3d4a1726210c18fa1b54500d5bbadd8b4daa2"}],"number":16457}
buildkite-pr-comment-->

2024-09-26 08:56 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16460)
* Commit: cc74b407e29959dce0a26cbde22e24cc11775714

### History
* :broken_heart: [Build #16457](https://buildkite.com/elastic/integrations/builds/16457) failed ff4bd77422f8121b29958975322bec2edbf7f3f1
* :green_heart: [Build #16455](https://buildkite.com/elastic/integrations/builds/16455) succeeded 2a8987f4012f8c262cf46837a1b77499c29c4d52
* :green_heart: [Build #16408](https://buildkite.com/elastic/integrations/builds/16408) succeeded 71d3d4a1726210c18fa1b54500d5bbadd8b4daa2

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16460","number":16460,"commit":"cc74b407e29959dce0a26cbde22e24cc11775714"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16457","number":16457,"commit":"ff4bd77422f8121b29958975322bec2edbf7f3f1"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16455","number":16455,"commit":"2a8987f4012f8c262cf46837a1b77499c29c4d52"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16408","number":16408,"commit":"71d3d4a1726210c18fa1b54500d5bbadd8b4daa2"}],"number":16460}
buildkite-pr-comment-->

2024-09-26 09:02 UTC, niraj-elastic requested changes

2024-09-26 09:37 UTC, kush-elastic commented on packages/vsphere/data_stream/resourcepool/fields/fields.yml
> +        Unique ID of the resourcepool.
using ecs field `event.id`.

2024-09-26 09:41 UTC, niraj-elastic approved these changes
LGTM

2024-09-26 09:55 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16467)
* Commit: 0e94e444b2390f2644273405dbb879fd3faaffaf

### History
* :green_heart: [Build #16460](https://buildkite.com/elastic/integrations/builds/16460) succeeded cc74b407e29959dce0a26cbde22e24cc11775714
* :broken_heart: [Build #16457](https://buildkite.com/elastic/integrations/builds/16457) failed ff4bd77422f8121b29958975322bec2edbf7f3f1
* :green_heart: [Build #16455](https://buildkite.com/elastic/integrations/builds/16455) succeeded 2a8987f4012f8c262cf46837a1b77499c29c4d52
* :green_heart: [Build #16408](https://buildkite.com/elastic/integrations/builds/16408) succeeded 71d3d4a1726210c18fa1b54500d5bbadd8b4daa2

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16467","number":16467,"commit":"0e94e444b2390f2644273405dbb879fd3faaffaf"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16460","number":16460,"commit":"cc74b407e29959dce0a26cbde22e24cc11775714"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16457","number":16457,"commit":"ff4bd77422f8121b29958975322bec2edbf7f3f1"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16455","number":16455,"commit":"2a8987f4012f8c262cf46837a1b77499c29c4d52"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16408","number":16408,"commit":"71d3d4a1726210c18fa1b54500d5bbadd8b4daa2"}],"number":16467}
buildkite-pr-comment-->

2024-09-26 10:01 UTC, ishleenk17 commented on packages/vsphere/data_stream/resourcepool/elasticsearch/ingest_pipeline/default.yml
> +    target_field: event.id
Let's not use the target field as an ecs field. Please use a different name here.
What if this field is already being populated. We are overwriting it. Please use a different field here.

2024-09-26 10:23 UTC, kush-elastic commented on packages/vsphere/_dev/build/docs/README.md
> +If you encounter any issues during the setup or usage of the VMware vSphere integration, particularly with regards to Data Collection Intervals, with agent error messages such as **`Failed to query p
Yes, its not working

2024-09-26 10:24 UTC, kush-elastic commented on packages/vsphere/data_stream/resourcepool/elasticsearch/ingest_pipeline/default.yml
> +    target_field: event.id
I checked, its not getting populated.

2024-09-26 10:26 UTC, ishleenk17 commented on packages/vsphere/data_stream/resourcepool/elasticsearch/ingest_pipeline/default.yml
> +    target_field: event.id
But, I would like to avoid any such future occurrence. There can be a scenario where it is used along with Logstasgh and it can populate this value.
So, if we are not gaining anything with using event.id, I would like to refrain from using this here

2024-09-26 10:44 UTC, kush-elastic commented on packages/vsphere/data_stream/resourcepool/elasticsearch/ingest_pipeline/default.yml
> +    target_field: event.id
Introducing our own field here might confuse user for understanding its usability.

2024-09-26 10:58 UTC, ishleenk17 commented on packages/vsphere/data_stream/resourcepool/elasticsearch/ingest_pipeline/default.yml
> +    target_field: event.id
vsphere.resourcepool.fingerprint/vsphere.resourcepool_fingerprint. We can have this name.
This way of naming has been followed across other integrations as well. Eg: [here](https://github.com/elastic/integrations/blob/396cf21a79ad4764507ed0fcc87362e05cce2aa9/packages/prometheus/data_stream/collector/elasticsearch/ingest_pipeline/default.yml#L6)

2024-09-26 11:30 UTC, kush-elastic commented on packages/vsphere/data_stream/resourcepool/elasticsearch/ingest_pipeline/default.yml
> +    target_field: event.id
going with `vsphere.resourcepool.fingerprint`

2024-09-26 11:42 UTC, ishleenk17 approved these changes
Looks good!

2024-09-26 11:42 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16482)
* Commit: 0f5c797f3f6f462de444ad15e2311f3ab8033cd3

### Failed CI Steps
* [Check integrations vsphere](https://buildkite.com/elastic/integrations/builds/16482#01922e1c-1e67-41dd-a378-be665d6d94fb)

### History
* :green_heart: [Build #16467](https://buildkite.com/elastic/integrations/builds/16467) succeeded 0e94e444b2390f2644273405dbb879fd3faaffaf
* :green_heart: [Build #16460](https://buildkite.com/elastic/integrations/builds/16460) succeeded cc74b407e29959dce0a26cbde22e24cc11775714
* :broken_heart: [Build #16457](https://buildkite.com/elastic/integrations/builds/16457) failed ff4bd77422f8121b29958975322bec2edbf7f3f1
* :green_heart: [Build #16455](https://buildkite.com/elastic/integrations/builds/16455) succeeded 2a8987f4012f8c262cf46837a1b77499c29c4d52
* :green_heart: [Build #16408](https://buildkite.com/elastic/integrations/builds/16408) succeeded 71d3d4a1726210c18fa1b54500d5bbadd8b4daa2

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16482","number":16482,"commit":"0f5c797f3f6f462de444ad15e2311f3ab8033cd3"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16467","number":16467,"commit":"0e94e444b2390f2644273405dbb879fd3faaffaf"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16460","number":16460,"commit":"cc74b407e29959dce0a26cbde22e24cc11775714"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16457","number":16457,"commit":"ff4bd77422f8121b29958975322bec2edbf7f3f1"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16455","number":16455,"commit":"2a8987f4012f8c262cf46837a1b77499c29c4d52"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16408","number":16408,"commit":"71d3d4a1726210c18fa1b54500d5bbadd8b4daa2"}],"number":16482}
buildkite-pr-comment-->

2024-09-26 11:46 UTC, ishleenk17 commented
/test

2024-09-26 12:30 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16486)
* Commit: 084007525e7a9f1d3f1c5f1d631224b96c969a00

### History
* :broken_heart: [Build #16482](https://buildkite.com/elastic/integrations/builds/16482) failed 0f5c797f3f6f462de444ad15e2311f3ab8033cd3
* :green_heart: [Build #16467](https://buildkite.com/elastic/integrations/builds/16467) succeeded 0e94e444b2390f2644273405dbb879fd3faaffaf
* :green_heart: [Build #16460](https://buildkite.com/elastic/integrations/builds/16460) succeeded cc74b407e29959dce0a26cbde22e24cc11775714
* :broken_heart: [Build #16457](https://buildkite.com/elastic/integrations/builds/16457) failed ff4bd77422f8121b29958975322bec2edbf7f3f1
* :green_heart: [Build #16455](https://buildkite.com/elastic/integrations/builds/16455) succeeded 2a8987f4012f8c262cf46837a1b77499c29c4d52

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16486","number":16486,"commit":"084007525e7a9f1d3f1c5f1d631224b96c969a00"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16482","number":16482,"commit":"0f5c797f3f6f462de444ad15e2311f3ab8033cd3"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16467","number":16467,"commit":"0e94e444b2390f2644273405dbb879fd3faaffaf"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16460","number":16460,"commit":"cc74b407e29959dce0a26cbde22e24cc11775714"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16457","number":16457,"commit":"ff4bd77422f8121b29958975322bec2edbf7f3f1"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16455","number":16455,"commit":"2a8987f4012f8c262cf46837a1b77499c29c4d52"}],"number":16486}
buildkite-pr-comment-->

2024-09-26 12:40 UTC, merged