Frontdoor integration types fix
elastic/integrations pull request #11272
Opened 2024-09-28 08:16 UTC by eyescreamxd

This PR fix wrong types for the following fields:
Access:
- azure.frontdoor.access.time_to_first_byte
-  azure.frontdoor.access.time_taken
-  azure.frontdoor.access.time
WAF:
- azure.frontdoor.waf.time

Reason: wrong types blocks usage of numeric function to build visualizations e.g. percentile

## Proposed commit message

## Checklist

- [ x ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ x ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ x ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## How to test this PR locally

## Related issues

- 

## Screenshots

2024-09-28 10:31 UTC, elasticmachine commented
Pinging @elastic/security-service-integrations (Team:Security-Service Integrations)

2024-09-28 20:44 UTC, eyescreamxd commented
I've signed CLA right after PR creation. I guess it take some time, right?

2024-09-29 23:25 UTC, efd6 commented
/test

2024-09-29 23:37 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16567)
* Commit: cc8d9858231b4b4be742874824b9606cb0df2e36

### Failed CI Steps
* [Check integrations azure_frontdoor](https://buildkite.com/elastic/integrations/builds/16567#0192401e-ba96-4819-9309-bf823cb6182c)

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16567","number":16567,"commit":"cc8d9858231b4b4be742874824b9606cb0df2e36"}],"number":16567}
buildkite-pr-comment-->

2024-09-29 23:59 UTC, efd6 requested changes
Please update the changelog and manifest files for the package. You will also need to rerun the package and system tests.

You will also need to ensure that the types of the values in the documents are correctly converted e.g. in the access data stream
```diff
diff --git a/packages/azure_frontdoor/data_stream/access/elasticsearch/ingest_pipeline/default.yml b/packages/azure_frontdoor/data_stream/access/elasticsearch/ingest_pipeline/default.yml
index 9d07a6ddaa..a1bce5f25c 100644
--- a/packages/azure_frontdoor/data_stream/access/elasticsearch/ingest_pipeline/default.yml
+++ b/packages/azure_frontdoor/data_stream/access/elasticsearch/ingest_pipeline/default.yml
@@ -76,9 +76,18 @@ processors:
       field: azure.frontdoor.access.properties.httpMethod
       target_field: http.request.method
       ignore_missing: true
-  - rename:
+  - convert:
       field: azure.frontdoor.access.properties.timeToFirstByte
       target_field: azure.frontdoor.access.time_to_first_byte
+      type: double
+      tag: convert_properties_time_to_first_byte
+      ignore_missing: true
+      on_failure:
+        - append:
+            field: error.message
+            value: 'Processor {{{_ingest.on_failure_processor_type}}} with tag {{{_ingest.on_failure_processor_tag}}} in pipeline {{{_ingest.on_failure_pipeline}}} failed with message: {{{_ingest.on_failure_message}}}'
+  - remove:
+      field: azure.frontdoor.access.properties.timeToFirstByte
       ignore_missing: true
   - rename:
       field: azure.frontdoor.access.properties.pop
@@ -88,9 +97,18 @@ processors:
       field: azure.frontdoor.access.properties.responseBytes
       target_field: http.response.bytes
       ignore_missing: true
-  - rename:
+  - convert:
       field: azure.frontdoor.access.properties.timeTaken
       target_field: azure.frontdoor.access.time_taken
+      type: double
+      tag: convert_properties_time_taken
+      ignore_missing: true
+      on_failure:
+        - append:
+            field: error.message
+            value: 'Processor {{{_ingest.on_failure_processor_type}}} with tag {{{_ingest.on_failure_processor_tag}}} in pipeline {{{_ingest.on_failure_pipeline}}} failed with message: {{{_ingest.on_failure_message}}}'
+  - remove:
+      field: azure.frontdoor.access.properties.timeTaken
       ignore_missing: true
   - rename:
       field: azure.frontdoor.access.properties.routingRuleName
```
Note that strictly this is a breaking change since documents will need to be reindexed.

2024-09-29 23:59 UTC, efd6 commented on packages/azure_frontdoor/docs/README.md
> +| azure.frontdoor.waf.time | The date and time when the AFD edge delivered requested contents to client (in UTC). | date |
This never ends up in the document since it's removed [here](https://github.com/elastic/integrations/blob/75c9958902095f05862426ca7f31770d7a32ff5c/packages/azure_frontdoor/data_stream/waf/elasticsearch/ingest_pipeline/default.yml#L237-L242). Maybe just remove the field definition?

2024-09-30 06:36 UTC, eyescreamxd commented on packages/azure_frontdoor/docs/README.md
> +| azure.frontdoor.waf.time | The date and time when the AFD edge delivered requested contents to client (in UTC). | date |
I agree. I removed those definitons from README and fields

2024-09-30 06:36 UTC, eyescreamxd commented
Tested locally. Changelog and manifest files updated

2024-09-30 06:48 UTC, efd6 commented
/test

2024-09-30 06:56 UTC, efd6 commented on packages/azure_frontdoor/changelog.yml
> +      type: breaking-change
If we are saying this is a breaking change, this would be 2.0.0.

2024-09-30 07:00 UTC, eyescreamxd commented on packages/azure_frontdoor/changelog.yml
> +      type: breaking-change
Changed to 2.0.0

2024-09-30 21:54 UTC, efd6 commented
/test

2024-09-30 22:07 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16623)
* Commit: f05c64dedfd680d2f763a65944ee2956b0e3debd

### Failed CI Steps
* [Check integrations azure_frontdoor](https://buildkite.com/elastic/integrations/builds/16623#019244f2-0bf3-4ddc-9900-ce585b6e21dd)

### History
* :broken_heart: [Build #16583](https://buildkite.com/elastic/integrations/builds/16583) failed fbd1aaf3e66ac0680dfcca636136d85dfdc0e009
* :broken_heart: [Build #16567](https://buildkite.com/elastic/integrations/builds/16567) failed cc8d9858231b4b4be742874824b9606cb0df2e36

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16623","number":16623,"commit":"f05c64dedfd680d2f763a65944ee2956b0e3debd"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16583","number":16583,"commit":"fbd1aaf3e66ac0680dfcca636136d85dfdc0e009"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16567","number":16567,"commit":"cc8d9858231b4b4be742874824b9606cb0df2e36"}],"number":16623}
buildkite-pr-comment-->

2024-10-01 01:54 UTC, efd6 commented
/test

2024-10-01 02:08 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16635)
* Commit: c756c345512ab944a099987e0331ab24b7e4aa69

### Failed CI Steps
* [Check integrations azure_frontdoor](https://buildkite.com/elastic/integrations/builds/16635#019245ce-846b-4102-a741-f968c364a6e3)

### History
* :broken_heart: [Build #16623](https://buildkite.com/elastic/integrations/builds/16623) failed f05c64dedfd680d2f763a65944ee2956b0e3debd
* :broken_heart: [Build #16583](https://buildkite.com/elastic/integrations/builds/16583) failed fbd1aaf3e66ac0680dfcca636136d85dfdc0e009
* :broken_heart: [Build #16567](https://buildkite.com/elastic/integrations/builds/16567) failed cc8d9858231b4b4be742874824b9606cb0df2e36

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16635","number":16635,"commit":"c756c345512ab944a099987e0331ab24b7e4aa69"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16623","number":16623,"commit":"f05c64dedfd680d2f763a65944ee2956b0e3debd"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16583","number":16583,"commit":"fbd1aaf3e66ac0680dfcca636136d85dfdc0e009"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16567","number":16567,"commit":"cc8d9858231b4b4be742874824b9606cb0df2e36"}],"number":16635}
buildkite-pr-comment-->

2024-10-01 02:38 UTC, efd6 commented
/test

2024-10-01 02:53 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16636)
* Commit: d9787a521333d2feea8c2a7d41e0f2dfcf5ef300

### History
* :broken_heart: [Build #16635](https://buildkite.com/elastic/integrations/builds/16635) failed c756c345512ab944a099987e0331ab24b7e4aa69
* :broken_heart: [Build #16623](https://buildkite.com/elastic/integrations/builds/16623) failed f05c64dedfd680d2f763a65944ee2956b0e3debd
* :broken_heart: [Build #16583](https://buildkite.com/elastic/integrations/builds/16583) failed fbd1aaf3e66ac0680dfcca636136d85dfdc0e009
* :broken_heart: [Build #16567](https://buildkite.com/elastic/integrations/builds/16567) failed cc8d9858231b4b4be742874824b9606cb0df2e36

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16636","number":16636,"commit":"d9787a521333d2feea8c2a7d41e0f2dfcf5ef300"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16635","number":16635,"commit":"c756c345512ab944a099987e0331ab24b7e4aa69"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16623","number":16623,"commit":"f05c64dedfd680d2f763a65944ee2956b0e3debd"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16583","number":16583,"commit":"fbd1aaf3e66ac0680dfcca636136d85dfdc0e009"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16567","number":16567,"commit":"cc8d9858231b4b4be742874824b9606cb0df2e36"}],"number":16636}
buildkite-pr-comment-->

2024-10-01 03:01 UTC, merged