[CISCO ASA]: Events with Cod 7250** could have destination.address insteat of destination.ip
elastic/integrations pull request #11292
Opened 2024-10-01 13:06 UTC by xtruthx

closes #11290

## Proposed commit message

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## How to test this PR locally

## Related issues
Closes #11290 

## Screenshots

2024-10-02 13:02 UTC, andrewkroh commented on packages/cisco_asa/changelog.yml
> +    - description: "Introduce destination address to 725001,725002,725007 and 725016"
```suggestion
    - description: Introduce destination.address to message ID 725001, 725002, 725007, and 725016.
```

2024-10-02 13:02 UTC, andrewkroh commented on packages/cisco_asa/changelog.yml
> +- version: "2.37.1"
Under https://semver.org/ this version should be 2.38.0.

2024-10-02 13:02 UTC, andrewkroh commented on packages/cisco_asa/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/10897
```suggestion
      link: https://github.com/elastic/integrations/pull/11292
```

2024-10-02 14:36 UTC, xtruthx commented on packages/cisco_asa/changelog.yml
> +    - description: "Introduce destination address to 725001,725002,725007 and 725016"
done

2024-10-02 14:37 UTC, andrewkroh commented on packages/cisco_asa/manifest.yml
> +version: "2.38.0
```suggestion
version: "2.38.0"
```

2024-10-02 14:37 UTC, xtruthx commented on packages/cisco_asa/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/10897
i forgot do adapt the pr number. done

2024-10-02 14:37 UTC, xtruthx commented on packages/cisco_asa/changelog.yml
> +- version: "2.37.1"
done

2024-10-02 14:41 UTC, xtruthx commented on packages/cisco_asa/manifest.yml
> +version: "2.38.0
thx

2024-10-02 14:42 UTC, nicholasberlin approved these changes

2024-10-02 15:08 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16711)
* Commit: 76549d69499d3c4f23f990ee944899315f21c899

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16711","number":16711,"commit":"76549d69499d3c4f23f990ee944899315f21c899"}],"number":16711}
buildkite-pr-comment-->

2024-10-02 15:10 UTC, xtruthx commented
/test benchmark fullreport

2024-10-07 13:53 UTC, taylor-swanson reviewed
Could you add pipeline test cases to show the new patterns work?

The [test-asa.log](https://github.com/elastic/integrations/blob/main/packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-asa.log) file should be fine.

As a note, `destination.address` can hold either an IP or hostname. `destination.domain` is a better fit for a hostname-only value.

https://www.elastic.co/guide/en/ecs/current/ecs-destination.html

As the note mentions for `destination.address`, the value should duplicated to either `destination.ip` or `destination.domain` depending on what type it is. That would be a more complicated change and we'd also have to consider interactions with other message IDs, so I wouldn't worry about it for this change.

2024-10-07 19:26 UTC, xtruthx commented
you're right. destination.domain is correct, I made a mistake. I would say simply checking whether IP or domain via the GROK pattern should be enough. Or not?

I will add the tests with changes.

2024-10-08 14:45 UTC, taylor-swanson commented
> I would say simply checking whether IP or domain via the GROK pattern should be enough. Or not?

I think both approaches have merit.

If we rely on GROK, then we just copy the values to `destination.address`. The end result is the same, we just work backwards compared to extracting to `destination.address` first, then rely on a convert processor to detect if it's an IP or not. The downside with GROK is that it won't be immediately obvious if parsing fails due to a bad ip/hostname value. I don't have strong enough opinions either way to say which way to go. I'm fine with keeping the GROK as is for now.

2024-10-09 13:07 UTC, taylor-swanson requested changes
On closer inspection of the pipeline, there are a couple of groks towards the end that handle extracting the `*.address` values to either ip or domain. So for this changes, let's revert back to the old patterns, but change where they extract to to the `*.address` fields.

When updating the expected test files, existing tests should only show the addition of the `*.address` fields, they should still extract to the `*.ip` fields.

2024-10-09 13:07 UTC, taylor-swanson commented on packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
> +        - '^Starting SSL handshake with %{NOTSPACE:_temp_.cisco.peer_type} %{DATA:_temp_.cisco.source_interface}:%{NOTSPACE:source.ip}/%{NOTSPACE:source.port} to (?:%{IP:destination.ip}|%{HOSTNAME:de
```suggestion
        - '^Starting SSL handshake with %{NOTSPACE:_temp_.cisco.peer_type} %{DATA:_temp_.cisco.source_interface}:%{NOTSPACE:source.address}/%{NOTSPACE:source.port} to %{NOTSPACE:destination.address}/%{NOTSPACE:destination.port} for %{NOTSPACE:_temp_.cisco.tls_version} session'
```

2024-10-09 13:07 UTC, taylor-swanson commented on packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
>          - '^Starting SSL handshake with %{NOTSPACE:_temp_.cisco.peer_type} %{DATA:_temp_.cisco.source_interface}:%{NOTSPACE:source.ip}/%{NOTSPACE:source.port} for %{NOTSPACE:_temp_.cisco.tls_version}
```suggestion
        - '^Starting SSL handshake with %{NOTSPACE:_temp_.cisco.peer_type} %{DATA:_temp_.cisco.source_interface}:%{NOTSPACE:source.address}/%{NOTSPACE:source.port} for %{NOTSPACE:_temp_.cisco.tls_version} session'
```

2024-10-09 13:07 UTC, taylor-swanson commented on packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
> +        - '^Device completed SSL handshake with %{NOTSPACE:_temp_.cisco.peer_type} %{DATA:_temp_.cisco.source_interface}:%{NOTSPACE:source.ip}/%{NOTSPACE:source.port} to (?:%{IP:destination.ip}|%{HOS
```suggestion
        - '^Device completed SSL handshake with %{NOTSPACE:_temp_.cisco.peer_type} %{DATA:_temp_.cisco.source_interface}:%{NOTSPACE:source.address}/%{NOTSPACE:source.port} to %{NOTSPACE:destination.address}/%{NOTSPACE:destination.port} for %{NOTSPACE:_temp_.cisco.tls_version}'
```

2024-10-09 13:07 UTC, taylor-swanson commented on packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
> +        - '^SSL session with %{NOTSPACE:_temp_.cisco.peer_type} %{DATA:_temp_.cisco.source_interface}:%{NOTSPACE:source.ip}/%{NOTSPACE:source.port} to (?:%{IP:destination.ip}|%{HOSTNAME:destination.a
```suggestion
        - '^SSL session with %{NOTSPACE:_temp_.cisco.peer_type} %{DATA:_temp_.cisco.source_interface}:%{NOTSPACE:source.address}/%{NOTSPACE:source.port} to %{NOTSPACE:destination.address}/%{NOTSPACE:destination.port} terminated'
```

2024-10-09 13:07 UTC, taylor-swanson commented on packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
> +        - '^Device selects trust-point %{DATA:_temp_.cisco.trustpoint} for %{NOTSPACE:_temp_.cisco.peer_type} %{DATA:_temp_.cisco.source_interface}:%{NOTSPACE:source.ip}/%{NOTSPACE:source.port} to (?
```suggestion
        - '^Device selects trust-point %{DATA:_temp_.cisco.trustpoint} for %{NOTSPACE:_temp_.cisco.peer_type} %{DATA:_temp_.cisco.source_interface}:%{NOTSPACE:source.address}/%{NOTSPACE:source.port} to %{NOTSPACE:destination.address}/%{NOTSPACE:destination.port}$'
```

2024-10-09 15:31 UTC, xtruthx commented
Ok, I haven't seen them. Then of course it makes more sense to fill *.address and then let the GROK processors decide. 

For the processors, however, I would not want to set the pattern for *.domain to GREEDYDATA but rather to HOSTNAME.
I would also prefer to use HOSTNAME

2024-10-09 15:45 UTC, xtruthx commented
but I can't find an event in the tests that contains a domain?

2024-10-09 17:38 UTC, taylor-swanson commented
/test

2024-10-09 17:50 UTC, taylor-swanson commented
> For the processors, however, I would not want to set the pattern for *.domain to GREEDYDATA but rather to HOSTNAME. I would also prefer to use HOSTNAME

No disagreement there. I think the intent was for it to set *.ip if it's an IP, otherwise everything else goes to *.domain. That code has been there for over 3 years now and we haven't received any complaints on it yet as far as I know. 🤷

I triggered CI to run, but it will fail due to the expected files not being updated.

Could you run the following and commit the changes?

```
elastic-package test pipeline -g
```

This will update the pipeline test expected files so they will pass.

2024-10-09 17:52 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16975)
* Commit: 88952231d59be6181c4614b62ed6eee412b57b65

### Failed CI Steps
* [Check integrations cisco_asa](https://buildkite.com/elastic/integrations/builds/16975#01927260-df7c-416f-9385-f5f093b9062b)

### History
* :green_heart: [Build #16711](https://buildkite.com/elastic/integrations/builds/16711) succeeded 76549d69499d3c4f23f990ee944899315f21c899

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16975","number":16975,"commit":"88952231d59be6181c4614b62ed6eee412b57b65"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16711","number":16711,"commit":"76549d69499d3c4f23f990ee944899315f21c899"}],"number":16975}
buildkite-pr-comment-->

2024-10-09 18:39 UTC, xtruthx commented
> No disagreement there. I think the intent was for it to set *.ip if it's an IP, otherwise everything else goes to *.domain. That code has been there for over 3 years now and we haven't received any complaints on it yet as far as I know.

I will do that.


It was not meant as a complaint but as an improvement. Wildcard patterns are more expensive than precise patterns

2024-10-09 18:59 UTC, xtruthx commented
```
xtruthx   cisco-asa  …  integrations-fork  packages  cisco_asa  elastic-package test pipeline -g
Run pipeline tests for the package
--- Test results for package: cisco_asa - START ---
╭───────────┬─────────────┬───────────┬─────────────────────────────────────────────────────────┬────────┬──────────────╮
│ PACKAGE   │ DATA STREAM │ TEST TYPE │ TEST NAME                                               │ RESULT │ TIME ELAPSED │
├───────────┼─────────────┼───────────┼─────────────────────────────────────────────────────────┼────────┼──────────────┤
│ cisco_asa │ log         │ pipeline  │ (ingest pipeline warnings test-additional-messages.log) │ PASS   │ 134.795116ms │
│ cisco_asa │ log         │ pipeline  │ (ingest pipeline warnings test-anyconnect-messages.log) │ PASS   │ 144.740119ms │
│ cisco_asa │ log         │ pipeline  │ (ingest pipeline warnings test-asa-fix.log)             │ PASS   │ 137.902587ms │
│ cisco_asa │ log         │ pipeline  │ (ingest pipeline warnings test-asa-missing-groups.log)  │ PASS   │ 136.258244ms │
│ cisco_asa │ log         │ pipeline  │ (ingest pipeline warnings test-asa.log)                 │ PASS   │ 138.979295ms │
│ cisco_asa │ log         │ pipeline  │ (ingest pipeline warnings test-dap-records.log)         │ PASS   │ 136.255288ms │
│ cisco_asa │ log         │ pipeline  │ (ingest pipeline warnings test-filtered.log)            │ PASS   │   136.2838ms │
│ cisco_asa │ log         │ pipeline  │ (ingest pipeline warnings test-hostnames.log)           │ PASS   │ 136.799084ms │
│ cisco_asa │ log         │ pipeline  │ (ingest pipeline warnings test-non-canonical.log)       │ PASS   │ 130.839458ms │
│ cisco_asa │ log         │ pipeline  │ (ingest pipeline warnings test-not-ip.log)              │ PASS   │ 152.314736ms │
│ cisco_asa │ log         │ pipeline  │ (ingest pipeline warnings test-sample.log)              │ PASS   │ 168.144326ms │
│ cisco_asa │ log         │ pipeline  │ (ingest pipeline warnings test-sgt-tag-name.log)        │ PASS   │ 143.442329ms │
│ cisco_asa │ log         │ pipeline  │ (ingest pipeline warnings test-sip.log)                 │ PASS   │    150.306ms │
│ cisco_asa │ log         │ pipeline  │ test-additional-messages.log                            │ PASS   │  729.07818ms │
│ cisco_asa │ log         │ pipeline  │ test-anyconnect-messages.log                            │ PASS   │ 144.167914ms │
│ cisco_asa │ log         │ pipeline  │ test-asa-fix.log                                        │ PASS   │ 164.375689ms │
│ cisco_asa │ log         │ pipeline  │ test-asa-missing-groups.log                             │ PASS   │ 147.380757ms │
│ cisco_asa │ log         │ pipeline  │ test-asa.log                                            │ PASS   │ 1.247635801s │
│ cisco_asa │ log         │ pipeline  │ test-dap-records.log                                    │ PASS   │  89.198875ms │
│ cisco_asa │ log         │ pipeline  │ test-filtered.log                                       │ PASS   │  92.931751ms │
│ cisco_asa │ log         │ pipeline  │ test-hostnames.log                                      │ PASS   │  98.451796ms │
│ cisco_asa │ log         │ pipeline  │ test-non-canonical.log                                  │ PASS   │ 175.226643ms │
│ cisco_asa │ log         │ pipeline  │ test-not-ip.log                                         │ PASS   │ 106.357273ms │
│ cisco_asa │ log         │ pipeline  │ test-sample.log                                         │ PASS   │ 542.359218ms │
│ cisco_asa │ log         │ pipeline  │ test-sgt-tag-name.log                                   │ PASS   │  236.40216ms │
│ cisco_asa │ log         │ pipeline  │ test-sip.log                                            │ PASS   │ 113.469469ms │
╰───────────┴─────────────┴───────────┴─────────────────────────────────────────────────────────┴────────┴──────────────╯
--- Test results for package: cisco_asa - END   ---
Done
```

2024-10-09 19:07 UTC, taylor-swanson commented
/test

2024-10-09 19:08 UTC, taylor-swanson approved these changes
LGTM!

2024-10-09 19:33 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/16976)
* Commit: 87b270b45ce6ed91cf8df830f9cfac915c821bfb

### History
* :broken_heart: [Build #16975](https://buildkite.com/elastic/integrations/builds/16975) failed 88952231d59be6181c4614b62ed6eee412b57b65
* :green_heart: [Build #16711](https://buildkite.com/elastic/integrations/builds/16711) succeeded 76549d69499d3c4f23f990ee944899315f21c899

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16976","number":16976,"commit":"87b270b45ce6ed91cf8df830f9cfac915c821bfb"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16975","number":16975,"commit":"88952231d59be6181c4614b62ed6eee412b57b65"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/16711","number":16711,"commit":"76549d69499d3c4f23f990ee944899315f21c899"}],"number":16976}
buildkite-pr-comment-->

2024-10-09 19:34 UTC, merged