[Cisco Duo] New data stream for Activity logs
elastic/integrations pull request #11394
Opened 2024-10-10 18:04 UTC by chemamartinez

## Proposed commit message

Added new data stream `activity` to collect [Activity logs](https://duo.com/docs/adminapi#activity) from Cisco Duo.

The CEL program follows the API specifications set at:
  - [Authentication](https://duo.com/docs/adminapi#authentication)
  - [Response format](https://duo.com/docs/adminapi#response-format)
  - [Parameters and pagination](https://duo.com/docs/adminapi#activity)

It also adds a feature request for the `auth` data stream, including geo enrichment for the IP into the `access_device` field.

*Note: this PR has been built on top of https://github.com/elastic/integrations/pull/11327 so it includes its changes while it is in review. To avoid reviewing the content of the first PR, see the commits list where they can be easily identified.*

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).
- [x] I have verified that any added dashboard complies with Kibana's [Dashboard good practices](https://docs.elastic.dev/ux-guidelines/data-viz/dashboard-good-practices) 

## How to test this PR locally

Added pipeline and system tests for the new data stream:
```
Run asset tests for the package
--- Test results for package: cisco_duo - START ---
╭───────────┬────────────────────┬───────────┬────────────────────────────────────────────────────────────────────┬────────┬──────────────╮
│ PACKAGE   │ DATA STREAM        │ TEST TYPE │ TEST NAME                                                          │ RESULT │ TIME ELAPSED │
├───────────┼────────────────────┼───────────┼────────────────────────────────────────────────────────────────────┼────────┼──────────────┤
│ cisco_duo │                    │ asset     │ dashboard cisco_duo-0607d4a3-5322-41c1-b8fa-f0d29bcc2757 is loaded │ PASS   │      1.584µs │
│ cisco_duo │                    │ asset     │ dashboard cisco_duo-118061c3-3130-4c71-8899-157bab1ad447 is loaded │ PASS   │        292ns │
│ cisco_duo │                    │ asset     │ dashboard cisco_duo-5a0b80af-49ad-42ee-89b7-c89faa927826 is loaded │ PASS   │        416ns │
│ cisco_duo │                    │ asset     │ dashboard cisco_duo-7a135061-78a3-45d9-951b-4b9b665fa729 is loaded │ PASS   │        208ns │
│ cisco_duo │                    │ asset     │ dashboard cisco_duo-b386f94c-0856-4508-ba08-a525a2f3b70f is loaded │ PASS   │        417ns │
│ cisco_duo │                    │ asset     │ dashboard cisco_duo-c3336a66-68ff-4bcd-95ff-fb388793f721 is loaded │ PASS   │        375ns │
│ cisco_duo │                    │ asset     │ dashboard cisco_duo-e91470e5-2ded-4ff1-8bb5-24e06b949c1d is loaded │ PASS   │        250ns │
│ cisco_duo │                    │ asset     │ map cisco_duo-158c0e80-148c-11ec-9386-31989719f9db is loaded       │ PASS   │        250ns │
│ cisco_duo │                    │ asset     │ search cisco_duo-64869c89-8c44-4644-a84a-9815c0fddba0 is loaded    │ PASS   │        375ns │
│ cisco_duo │ activity           │ asset     │ index_template logs-cisco_duo.activity is loaded                   │ PASS   │        250ns │
│ cisco_duo │ activity           │ asset     │ ingest_pipeline logs-cisco_duo.activity-2.2.0 is loaded            │ PASS   │        292ns │
│ cisco_duo │ admin              │ asset     │ index_template logs-cisco_duo.admin is loaded                      │ PASS   │        166ns │
│ cisco_duo │ admin              │ asset     │ ingest_pipeline logs-cisco_duo.admin-2.2.0 is loaded               │ PASS   │        292ns │
│ cisco_duo │ auth               │ asset     │ index_template logs-cisco_duo.auth is loaded                       │ PASS   │        334ns │
│ cisco_duo │ auth               │ asset     │ ingest_pipeline logs-cisco_duo.auth-2.2.0 is loaded                │ PASS   │        125ns │
│ cisco_duo │ offline_enrollment │ asset     │ index_template logs-cisco_duo.offline_enrollment is loaded         │ PASS   │        209ns │
│ cisco_duo │ offline_enrollment │ asset     │ ingest_pipeline logs-cisco_duo.offline_enrollment-2.2.0 is loaded  │ PASS   │        125ns │
│ cisco_duo │ summary            │ asset     │ index_template logs-cisco_duo.summary is loaded                    │ PASS   │        208ns │
│ cisco_duo │ summary            │ asset     │ ingest_pipeline logs-cisco_duo.summary-2.2.0 is loaded             │ PASS   │        125ns │
│ cisco_duo │ telephony          │ asset     │ index_template logs-cisco_duo.telephony is loaded                  │ PASS   │        209ns │
│ cisco_duo │ telephony          │ asset     │ ingest_pipeline logs-cisco_duo.telephony-2.2.0 is loaded           │ PASS   │        125ns │
│ cisco_duo │ telephony_v2       │ asset     │ index_template logs-cisco_duo.telephony_v2 is loaded               │ PASS   │        375ns │
│ cisco_duo │ telephony_v2       │ asset     │ ingest_pipeline logs-cisco_duo.telephony_v2-2.2.0 is loaded        │ PASS   │        166ns │
│ cisco_duo │ trust_monitor      │ asset     │ index_template logs-cisco_duo.trust_monitor is loaded              │ PASS   │        375ns │
│ cisco_duo │ trust_monitor      │ asset     │ ingest_pipeline logs-cisco_duo.trust_monitor-2.2.0 is loaded       │ PASS   │        125ns │
╰───────────┴────────────────────┴───────────┴────────────────────────────────────────────────────────────────────┴────────┴──────────────╯
--- Test results for package: cisco_duo - END   ---
Done
Run pipeline tests for the package
--- Test results for package: cisco_duo - START ---
╭───────────┬────────────────────┬───────────┬────────────────────────────────────────────────────────┬────────┬──────────────╮
│ PACKAGE   │ DATA STREAM        │ TEST TYPE │ TEST NAME                                              │ RESULT │ TIME ELAPSED │
├───────────┼────────────────────┼───────────┼────────────────────────────────────────────────────────┼────────┼──────────────┤
│ cisco_duo │ activity           │ pipeline  │ (ingest pipeline warnings test-activity.log)           │ PASS   │ 196.669625ms │
│ cisco_duo │ activity           │ pipeline  │ test-activity.log                                      │ PASS   │ 134.559833ms │
│ cisco_duo │ admin              │ pipeline  │ (ingest pipeline warnings test-admin.log)              │ PASS   │ 206.523291ms │
│ cisco_duo │ admin              │ pipeline  │ (ingest pipeline warnings test-empty.log)              │ PASS   │ 202.109375ms │
│ cisco_duo │ admin              │ pipeline  │ test-admin.log                                         │ PASS   │    151.045ms │
│ cisco_duo │ admin              │ pipeline  │ test-empty.log                                         │ PASS   │  40.457458ms │
│ cisco_duo │ auth               │ pipeline  │ (ingest pipeline warnings test-auth.log)               │ PASS   │ 218.412834ms │
│ cisco_duo │ auth               │ pipeline  │ (ingest pipeline warnings test-empty.log)              │ PASS   │   194.9385ms │
│ cisco_duo │ auth               │ pipeline  │ test-auth.log                                          │ PASS   │ 345.084917ms │
│ cisco_duo │ auth               │ pipeline  │ test-empty.log                                         │ PASS   │   40.33725ms │
│ cisco_duo │ offline_enrollment │ pipeline  │ (ingest pipeline warnings test-empty.log)              │ PASS   │  198.41075ms │
│ cisco_duo │ offline_enrollment │ pipeline  │ (ingest pipeline warnings test-offline-enrollment.log) │ PASS   │   200.7585ms │
│ cisco_duo │ offline_enrollment │ pipeline  │ test-empty.log                                         │ PASS   │  37.008042ms │
│ cisco_duo │ offline_enrollment │ pipeline  │ test-offline- [...]

2024-10-10 18:05 UTC, elasticmachine commented
Pinging @elastic/security-service-integrations (Team:Security-Service Integrations)

2024-10-10 18:33 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17032)
* Commit: f49238eff315e6a4733025df73fa43d711df185d

cc @chemamartinez

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17032","number":17032,"commit":"f49238eff315e6a4733025df73fa43d711df185d"}],"number":17032}
buildkite-pr-comment-->

2024-10-10 21:24 UTC, efd6 commented on packages/cisco_duo/data_stream/activity/_dev/test/system/test-default-config.yml
> +  hit_count: 1
Can we make the test go through at least one round of pagination?

2024-10-10 21:24 UTC, efd6 commented on packages/cisco_duo/data_stream/activity/agent/stream/cel.yml.hbs
> +                    "date": now.format(time_layout.RFC1123Z),
This is already defined as `state.date` from the preamble.

2024-10-10 21:24 UTC, efd6 commented on packages/cisco_duo/data_stream/activity/agent/stream/cel.yml.hbs
> +                    "next_url": (has(body.?response.?metadata.next_offset) && body.response.metadata.next_offset != null) ?
```suggestion
                    "next_url": (body.?response.?metadata.next_offset.orValue(null) != null) ?
```

2024-10-10 21:24 UTC, efd6 commented on packages/cisco_duo/data_stream/activity/agent/stream/cel.yml.hbs
> +                        ?"last_published": (has(body.?response.?metadata.next_offset) && body.response.metadata.next_offset != null) ?
```suggestion
                        ?"last_published": (body.?response.?metadata.next_offset.orValue(null) != null) ?
```

2024-10-10 21:24 UTC, efd6 commented on packages/cisco_duo/data_stream/activity/elasticsearch/ingest_pipeline/default.yml
> +      if: ctx.json?.ts == null
Same [comment](https://github.com/elastic/integrations/pull/11327#discussion_r1796087970) as for trust monitor.

2024-10-10 21:24 UTC, efd6 commented on packages/cisco_duo/data_stream/activity/elasticsearch/ingest_pipeline/default.yml
> +  ## Custom fields
tags

2024-10-10 21:24 UTC, efd6 commented on packages/cisco_duo/data_stream/activity/elasticsearch/ingest_pipeline/default.yml
> +      if: ctx.cisco_duo?.activity?.outcome != null && ctx.cisco_duo.activity.outcome == 'SUCCESS'
```suggestion
      if: ctx.cisco_duo?.activity?.outcome == 'SUCCESS'
```

2024-10-10 21:24 UTC, efd6 commented on packages/cisco_duo/data_stream/activity/elasticsearch/ingest_pipeline/default.yml
> +      if: ctx.cisco_duo?.activity?.outcome != null && ctx.cisco_duo.activity.outcome == 'FAILURE'
```suggestion
      if: ctx.cisco_duo?.activity?.outcome == 'FAILURE'
```

2024-10-10 21:24 UTC, efd6 commented on packages/cisco_duo/data_stream/activity/elasticsearch/ingest_pipeline/default.yml
> +      if: ctx.cisco_duo?.activity?.actor?.type != null && ctx.cisco_duo.activity.actor.type == 'user'
```suggestion
      if: ctx.cisco_duo?.activity?.actor?.type == 'user'
```

2024-10-15 17:05 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17165)
* Commit: 3ee5a428bd2476907666713f7c6b49495d46a7eb

### History
* :green_heart: [Build #17032](https://buildkite.com/elastic/integrations/builds/17032) succeeded f49238eff315e6a4733025df73fa43d711df185d

cc @chemamartinez

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17165","number":17165,"commit":"3ee5a428bd2476907666713f7c6b49495d46a7eb"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17032","number":17032,"commit":"f49238eff315e6a4733025df73fa43d711df185d"}],"number":17165}
buildkite-pr-comment-->

2024-10-15 21:04 UTC, efd6 approved these changes
Though note the concern about the string(list) conversion.

2024-10-15 22:11 UTC, efd6 requested changes
Something about real-world Cisco Duo documents is causing breakage with this code (as it exists in auth). So blocking.

2024-10-17 08:17 UTC, chemamartinez commented on packages/cisco_duo/data_stream/trust_monitor/agent/stream/cel.yml.hbs
> +                                            ": " + string(body.message_detail)
Resolving this comment as it was caused by `next_offset` and is already solved https://github.com/elastic/integrations/pull/11422

2024-10-17 08:39 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17280)
* Commit: 18213e82f45fb7a5f2232a14bda0cb92e5bb3110

### History
* :green_heart: [Build #17165](https://buildkite.com/elastic/integrations/builds/17165) succeeded 3ee5a428bd2476907666713f7c6b49495d46a7eb
* :green_heart: [Build #17032](https://buildkite.com/elastic/integrations/builds/17032) succeeded f49238eff315e6a4733025df73fa43d711df185d

cc @chemamartinez

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17280","number":17280,"commit":"18213e82f45fb7a5f2232a14bda0cb92e5bb3110"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17165","number":17165,"commit":"3ee5a428bd2476907666713f7c6b49495d46a7eb"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17032","number":17032,"commit":"f49238eff315e6a4733025df73fa43d711df185d"}],"number":17280}
buildkite-pr-comment-->

2024-10-18 14:59 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17351)
* Commit: 2f89700c8e7412f726a1d868e280e92c3ec31a61

### History
* :green_heart: [Build #17280](https://buildkite.com/elastic/integrations/builds/17280) succeeded 18213e82f45fb7a5f2232a14bda0cb92e5bb3110
* :green_heart: [Build #17165](https://buildkite.com/elastic/integrations/builds/17165) succeeded 3ee5a428bd2476907666713f7c6b49495d46a7eb
* :green_heart: [Build #17032](https://buildkite.com/elastic/integrations/builds/17032) succeeded f49238eff315e6a4733025df73fa43d711df185d

cc @chemamartinez

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17351","number":17351,"commit":"2f89700c8e7412f726a1d868e280e92c3ec31a61"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17280","number":17280,"commit":"18213e82f45fb7a5f2232a14bda0cb92e5bb3110"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17165","number":17165,"commit":"3ee5a428bd2476907666713f7c6b49495d46a7eb"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17032","number":17032,"commit":"f49238eff315e6a4733025df73fa43d711df185d"}],"number":17351}
buildkite-pr-comment-->

2024-10-20 20:33 UTC, efd6 approved these changes
LGTM after nit addressed.

2024-10-20 20:33 UTC, efd6 commented on packages/cisco_duo/data_stream/activity/agent/stream/cel.yml.hbs
> +                                        optional.none(),
Same comment here as [this](https://github.com/elastic/integrations/pull/11327#discussion_r1807937159).

2024-10-21 08:52 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17395)
* Commit: b496f0f65a7ed7a2a6e65d2790cd27ac5c344ca1

### History
* :green_heart: [Build #17351](https://buildkite.com/elastic/integrations/builds/17351) succeeded 2f89700c8e7412f726a1d868e280e92c3ec31a61
* :green_heart: [Build #17280](https://buildkite.com/elastic/integrations/builds/17280) succeeded 18213e82f45fb7a5f2232a14bda0cb92e5bb3110
* :green_heart: [Build #17165](https://buildkite.com/elastic/integrations/builds/17165) succeeded 3ee5a428bd2476907666713f7c6b49495d46a7eb
* :green_heart: [Build #17032](https://buildkite.com/elastic/integrations/builds/17032) succeeded f49238eff315e6a4733025df73fa43d711df185d

cc @chemamartinez

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17395","number":17395,"commit":"b496f0f65a7ed7a2a6e65d2790cd27ac5c344ca1"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17351","number":17351,"commit":"2f89700c8e7412f726a1d868e280e92c3ec31a61"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17280","number":17280,"commit":"18213e82f45fb7a5f2232a14bda0cb92e5bb3110"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17165","number":17165,"commit":"3ee5a428bd2476907666713f7c6b49495d46a7eb"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17032","number":17032,"commit":"f49238eff315e6a4733025df73fa43d711df185d"}],"number":17395}
buildkite-pr-comment-->

2024-10-21 10:32 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17399)
* Commit: ab1fb89c764ac670bc5325d90bf04d2f81f9bb27

### History
* :green_heart: [Build #17395](https://buildkite.com/elastic/integrations/builds/17395) succeeded b496f0f65a7ed7a2a6e65d2790cd27ac5c344ca1
* :green_heart: [Build #17351](https://buildkite.com/elastic/integrations/builds/17351) succeeded 2f89700c8e7412f726a1d868e280e92c3ec31a61
* :green_heart: [Build #17280](https://buildkite.com/elastic/integrations/builds/17280) succeeded 18213e82f45fb7a5f2232a14bda0cb92e5bb3110
* :green_heart: [Build #17165](https://buildkite.com/elastic/integrations/builds/17165) succeeded 3ee5a428bd2476907666713f7c6b49495d46a7eb
* :green_heart: [Build #17032](https://buildkite.com/elastic/integrations/builds/17032) succeeded f49238eff315e6a4733025df73fa43d711df185d

cc @chemamartinez

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17399","number":17399,"commit":"ab1fb89c764ac670bc5325d90bf04d2f81f9bb27"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17395","number":17395,"commit":"b496f0f65a7ed7a2a6e65d2790cd27ac5c344ca1"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17351","number":17351,"commit":"2f89700c8e7412f726a1d868e280e92c3ec31a61"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17280","number":17280,"commit":"18213e82f45fb7a5f2232a14bda0cb92e5bb3110"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17165","number":17165,"commit":"3ee5a428bd2476907666713f7c6b49495d46a7eb"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17032","number":17032,"commit":"f49238eff315e6a4733025df73fa43d711df185d"}],"number":17399}
buildkite-pr-comment-->

2024-10-21 10:45 UTC, merged