[Cloud Security] release Wiz version 2.0.0
elastic/integrations pull request #11414
Opened 2024-10-15 11:40 UTC by maxcold

## Proposed commit message

Changes: 
- removing `rule.references` non-ecs as this field is not required anymore by Kibana https://github.com/elastic/security-team/issues/10793 . The field `rule.reference` should be used instead
- mappings for rule.* fields which were `text` changed to `keyword` to match ecs
- `resource.id` is provided from `id` when `provider_id` is missing on Wiz
- `external: esc` is added for ECS fields
- add `cloud.account.name` mapping to vulnerability cdr transform destination

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).
- [x] I have verified that any added dashboard complies with Kibana's [Dashboard good practices](https://docs.elastic.dev/ux-guidelines/data-viz/dashboard-good-practices) 

## Author's Checklist

- [ ] 

## How to test this PR locally

## Related issues

- relates to https://github.com/elastic/security-team/issues/10794
- fixes https://github.com/elastic/security-team/issues/10595
- fixes https://github.com/elastic/security-team/issues/10811
- fixes  https://github.com/elastic/security-team/issues/10819
- fixes https://github.com/elastic/security-team/issues/10875

## Screenshots

2024-10-15 11:54 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17142)
* Commit: 03a32bd3d87cf2d6cab0858942e5dacd1a560b84

### Failed CI Steps
* [Check integrations wiz](https://buildkite.com/elastic/integrations/builds/17142#01928fff-e89c-427f-a92b-83aa22fb4b3d)

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17142","number":17142,"commit":"03a32bd3d87cf2d6cab0858942e5dacd1a560b84"}],"number":17142}
buildkite-pr-comment-->

2024-10-15 12:26 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17143)
* Commit: 6dde700d5372b438d22ff0dc810146881311f4ad

### History
* :broken_heart: [Build #17142](https://buildkite.com/elastic/integrations/builds/17142) failed 03a32bd3d87cf2d6cab0858942e5dacd1a560b84

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17143","number":17143,"commit":"6dde700d5372b438d22ff0dc810146881311f4ad"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17142","number":17142,"commit":"03a32bd3d87cf2d6cab0858942e5dacd1a560b84"}],"number":17143}
buildkite-pr-comment-->

2024-10-15 12:49 UTC, elasticmachine commented
Pinging @elastic/security-service-integrations (Team:Security-Service Integrations)

2024-10-16 08:25 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17214)
* Commit: 5ca6264cb5a40d105a6cbbc50244408ad9f9ba22

### History
* :green_heart: [Build #17143](https://buildkite.com/elastic/integrations/builds/17143) succeeded 6dde700d5372b438d22ff0dc810146881311f4ad
* :broken_heart: [Build #17142](https://buildkite.com/elastic/integrations/builds/17142) failed 03a32bd3d87cf2d6cab0858942e5dacd1a560b84

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17214","number":17214,"commit":"5ca6264cb5a40d105a6cbbc50244408ad9f9ba22"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17143","number":17143,"commit":"6dde700d5372b438d22ff0dc810146881311f4ad"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17142","number":17142,"commit":"03a32bd3d87cf2d6cab0858942e5dacd1a560b84"}],"number":17214}
buildkite-pr-comment-->

2024-10-16 16:02 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17232)
* Commit: 4d557e660da7712d12329c8037d48bf04996a814

### History
* :green_heart: [Build #17214](https://buildkite.com/elastic/integrations/builds/17214) succeeded 5ca6264cb5a40d105a6cbbc50244408ad9f9ba22
* :green_heart: [Build #17143](https://buildkite.com/elastic/integrations/builds/17143) succeeded 6dde700d5372b438d22ff0dc810146881311f4ad
* :broken_heart: [Build #17142](https://buildkite.com/elastic/integrations/builds/17142) failed 03a32bd3d87cf2d6cab0858942e5dacd1a560b84

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17232","number":17232,"commit":"4d557e660da7712d12329c8037d48bf04996a814"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17214","number":17214,"commit":"5ca6264cb5a40d105a6cbbc50244408ad9f9ba22"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17143","number":17143,"commit":"6dde700d5372b438d22ff0dc810146881311f4ad"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17142","number":17142,"commit":"03a32bd3d87cf2d6cab0858942e5dacd1a560b84"}],"number":17232}
buildkite-pr-comment-->

2024-10-16 19:16 UTC, andrewkroh commented on packages/wiz/changelog.yml
> +      type: enhancement
> and adjust rule.* mappings.

When I read this I'm wonder what adjustments were made.

I also think the changelog should tell user how to deal with the breaking change if they were using the removed field.

```suggestion
    - description: Remove rule.references field and its mapping. Please use the ECS rule.reference field instead.
      type: breaking-change
```

2024-10-16 19:18 UTC, andrewkroh commented on packages/wiz/data_stream/cloud_configuration_finding/fields/rule.yml
>        type: text
The `rule` fields are part of ECS. Anywhere we have an ECS field we should depend on the ECS definition through the use of `external: ecs` to ensure that we always have consistent mappings. This ensures that there are never data type conflicts between data streams for ECS fields.

This is what it would look like to use `external: ecs` for the ECS fields in wiz -- https://github.com/elastic/integrations/commit/d3d335c73bd32df269c71719a2f77bce03a57281.

However, after doing that clean-up it becomes easier to spot other problems.

1) There are two problematic field definitions that are conflicting with ECS.

    ```
    packages/wiz/data_stream/cloud_configuration_finding/fields/rule.yml:10:7 rule.description field declared as type text conflicts with the ECS data type keyword (conflict)
    packages/wiz/data_stream/cloud_configuration_finding/fields/rule.yml:14:7 rule.reference field declared as type text conflicts with the ECS data type keyword (conflict)
    ```

2) rule.remediation has multiple data types (keyword, text)

    ```
    packages/wiz/elasticsearch/transform/latest_cdr_misconfigurations/fields/rule.yml:12:7 keyword (conflict)
    packages/wiz/data_stream/cloud_configuration_finding/fields/rule.yml:12:7 text (conflict)
    ```

3) duplicate definitions of the same field in a data stream

    ```
    packages/wiz/elasticsearch/transform/latest_cdr_misconfigurations/fields/ecs.yml:1:3 event.created is declared 2 times (duplicate)
      packages/wiz/elasticsearch/transform/latest_cdr_misconfigurations/fields/ecs.yml:19:3 additional definition (duplicate)
    packages/wiz/elasticsearch/transform/latest_cdr_vulnerabilities/fields/fields.yml:5:3 package.name is declared 2 times (duplicate)
      packages/wiz/elasticsearch/transform/latest_cdr_vulnerabilities/fields/fields.yml:23:3 additional definition (duplicate)
    ```

2024-10-17 07:45 UTC, maxcold commented on packages/wiz/changelog.yml
> +      type: enhancement
thanks, makes sense!

2024-10-17 08:00 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17276)
* Commit: 82f883459dbde13be79dbafd2bd7349a0cb391f7

### History
* :green_heart: [Build #17232](https://buildkite.com/elastic/integrations/builds/17232) succeeded 4d557e660da7712d12329c8037d48bf04996a814
* :green_heart: [Build #17214](https://buildkite.com/elastic/integrations/builds/17214) succeeded 5ca6264cb5a40d105a6cbbc50244408ad9f9ba22
* :green_heart: [Build #17143](https://buildkite.com/elastic/integrations/builds/17143) succeeded 6dde700d5372b438d22ff0dc810146881311f4ad
* :broken_heart: [Build #17142](https://buildkite.com/elastic/integrations/builds/17142) failed 03a32bd3d87cf2d6cab0858942e5dacd1a560b84

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17276","number":17276,"commit":"82f883459dbde13be79dbafd2bd7349a0cb391f7"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17232","number":17232,"commit":"4d557e660da7712d12329c8037d48bf04996a814"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17214","number":17214,"commit":"5ca6264cb5a40d105a6cbbc50244408ad9f9ba22"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17143","number":17143,"commit":"6dde700d5372b438d22ff0dc810146881311f4ad"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17142","number":17142,"commit":"03a32bd3d87cf2d6cab0858942e5dacd1a560b84"}],"number":17276}
buildkite-pr-comment-->

2024-10-17 08:12 UTC, maxcold commented on packages/wiz/data_stream/cloud_configuration_finding/fields/rule.yml
>        type: text
@andrewkroh thanks for the detailed feedback! I updated the mapping according to your suggestion. A couple of questions:
1. how do I check for conflicts with ECS? neither `lint` nor `check` produce the same output as you have in your comment
2. I changed `rule.description` and `rule.reference` to `ecs` and that means the mapping changed from `text` to `keyword` which is a breaking change as far as I understand. What should be the guidance for users in the changelog in that case?

2024-10-17 08:29 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17277)
* Commit: c5599fa32a332ddf7c8f17294b5f8712de0c46a4

### History
* :green_heart: [Build #17276](https://buildkite.com/elastic/integrations/builds/17276) succeeded 82f883459dbde13be79dbafd2bd7349a0cb391f7
* :green_heart: [Build #17232](https://buildkite.com/elastic/integrations/builds/17232) succeeded 4d557e660da7712d12329c8037d48bf04996a814
* :green_heart: [Build #17214](https://buildkite.com/elastic/integrations/builds/17214) succeeded 5ca6264cb5a40d105a6cbbc50244408ad9f9ba22
* :green_heart: [Build #17143](https://buildkite.com/elastic/integrations/builds/17143) succeeded 6dde700d5372b438d22ff0dc810146881311f4ad
* :broken_heart: [Build #17142](https://buildkite.com/elastic/integrations/builds/17142) failed 03a32bd3d87cf2d6cab0858942e5dacd1a560b84

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17277","number":17277,"commit":"c5599fa32a332ddf7c8f17294b5f8712de0c46a4"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17276","number":17276,"commit":"82f883459dbde13be79dbafd2bd7349a0cb391f7"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17232","number":17232,"commit":"4d557e660da7712d12329c8037d48bf04996a814"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17214","number":17214,"commit":"5ca6264cb5a40d105a6cbbc50244408ad9f9ba22"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17143","number":17143,"commit":"6dde700d5372b438d22ff0dc810146881311f4ad"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17142","number":17142,"commit":"03a32bd3d87cf2d6cab0858942e5dacd1a560b84"}],"number":17277}
buildkite-pr-comment-->

2024-10-17 16:52 UTC, andrewkroh commented on packages/wiz/data_stream/cloud_configuration_finding/fields/rule.yml
>        type: text
> how do I check for conflicts with ECS? 

I don't know that elastic-package has this capability yet. I have an unofficial [means](https://github.com/andrewkroh/fydler) that I occasionally use to audit the mappings.

> I changed rule.description and rule.reference to ecs and that means the mapping changed from text to keyword which is a breaking change as far as I understand. What should be the guidance for users in the changelog in that case?

It's hard to prescribe one solution because it depends on how the data is being used and what problem they encounter (types of queries or aggregations they are performing). One solution for conflicts mentioned in this [blog post](https://www.elastic.co/blog/troubleshooting-guide-common-issues-kibana-discover-load) is to apply a runtime field to the old index to make the field a keyword.

2024-10-17 17:00 UTC, andrewkroh commented on packages/wiz/data_stream/cloud_configuration_finding/fields/base-fields.yml
>    description: Event dataset.
This can use `external: ecs` too. Leave the `value` and `type` which will override the ECS `keyword` which is completely fine because constant_keyword and keyword are the same field type family.

2024-10-18 15:04 UTC, maxcold commented on packages/wiz/data_stream/cloud_configuration_finding/fields/base-fields.yml
>    description: Event dataset.
I'm assuming the same works for `data_stream.namespace` when we want to redefine it as `keyword` for the transform destination index, correct?

2024-10-18 15:38 UTC, andrewkroh commented on packages/wiz/data_stream/cloud_configuration_finding/fields/base-fields.yml
>    description: Event dataset.
Correct.

2024-10-18 15:40 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17354)
* Commit: 25632c2a1771af07b92ce21f2fc3cef5c5736684

### History
* :green_heart: [Build #17277](https://buildkite.com/elastic/integrations/builds/17277) succeeded c5599fa32a332ddf7c8f17294b5f8712de0c46a4
* :green_heart: [Build #17276](https://buildkite.com/elastic/integrations/builds/17276) succeeded 82f883459dbde13be79dbafd2bd7349a0cb391f7
* :green_heart: [Build #17232](https://buildkite.com/elastic/integrations/builds/17232) succeeded 4d557e660da7712d12329c8037d48bf04996a814
* :green_heart: [Build #17214](https://buildkite.com/elastic/integrations/builds/17214) succeeded 5ca6264cb5a40d105a6cbbc50244408ad9f9ba22
* :green_heart: [Build #17143](https://buildkite.com/elastic/integrations/builds/17143) succeeded 6dde700d5372b438d22ff0dc810146881311f4ad
* :broken_heart: [Build #17142](https://buildkite.com/elastic/integrations/builds/17142) failed 03a32bd3d87cf2d6cab0858942e5dacd1a560b84

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17354","number":17354,"commit":"25632c2a1771af07b92ce21f2fc3cef5c5736684"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17277","number":17277,"commit":"c5599fa32a332ddf7c8f17294b5f8712de0c46a4"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17276","number":17276,"commit":"82f883459dbde13be79dbafd2bd7349a0cb391f7"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17232","number":17232,"commit":"4d557e660da7712d12329c8037d48bf04996a814"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17214","number":17214,"commit":"5ca6264cb5a40d105a6cbbc50244408ad9f9ba22"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17143","number":17143,"commit":"6dde700d5372b438d22ff0dc810146881311f4ad"}],"number":17354}
buildkite-pr-comment-->

2024-10-21 14:00 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17412)
* Commit: 9f8506d87465e4db6051a2d075ab2c9dd1710932

### History
* :green_heart: [Build #17354](https://buildkite.com/elastic/integrations/builds/17354) succeeded 25632c2a1771af07b92ce21f2fc3cef5c5736684
* :green_heart: [Build #17277](https://buildkite.com/elastic/integrations/builds/17277) succeeded c5599fa32a332ddf7c8f17294b5f8712de0c46a4
* :green_heart: [Build #17276](https://buildkite.com/elastic/integrations/builds/17276) succeeded 82f883459dbde13be79dbafd2bd7349a0cb391f7
* :green_heart: [Build #17232](https://buildkite.com/elastic/integrations/builds/17232) succeeded 4d557e660da7712d12329c8037d48bf04996a814
* :green_heart: [Build #17214](https://buildkite.com/elastic/integrations/builds/17214) succeeded 5ca6264cb5a40d105a6cbbc50244408ad9f9ba22
* :green_heart: [Build #17143](https://buildkite.com/elastic/integrations/builds/17143) succeeded 6dde700d5372b438d22ff0dc810146881311f4ad

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17412","number":17412,"commit":"9f8506d87465e4db6051a2d075ab2c9dd1710932"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17354","number":17354,"commit":"25632c2a1771af07b92ce21f2fc3cef5c5736684"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17277","number":17277,"commit":"c5599fa32a332ddf7c8f17294b5f8712de0c46a4"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17276","number":17276,"commit":"82f883459dbde13be79dbafd2bd7349a0cb391f7"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17232","number":17232,"commit":"4d557e660da7712d12329c8037d48bf04996a814"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17214","number":17214,"commit":"5ca6264cb5a40d105a6cbbc50244408ad9f9ba22"}],"number":17412}
buildkite-pr-comment-->

2024-10-23 09:24 UTC, kcreddy commented on packages/wiz/changelog.yml
> +    - description: Add cloud.account.name mapping to latest_cdr_vulnerabilities transform destination,
```suggestion
    - description: Add cloud.account.name mapping to latest_cdr_vulnerabilities transform destination.
```

2024-10-23 09:25 UTC, kcreddy commented on packages/wiz/data_stream/cloud_configuration_finding/fields/rule.yml
>        type: text
Since we are adhering to ECS, should we even define the rule fields that are of `external: ecs`? The `ecs@mappings` component template should take care of them for the datastream.

2024-10-23 09:35 UTC, kcreddy reviewed
Change `external: esc` to `external: ecs` in PR commit message.

2024-10-23 09:35 UTC, kcreddy commented on packages/wiz/data_stream/cloud_configuration_finding/fields/rule.yml
> +      external: ecs
Added comment: https://github.com/elastic/integrations/pull/11414#discussion_r1812325626 to clarify if this is even required.

2024-10-23 11:11 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17492)
* Commit: a2cbc199c77e370ecd57639ddc28089742db86e9

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/17492#0192b911-c508-4b7b-a02f-bbf4a4dcdd26)

### History
* :green_heart: [Build #17412](https://buildkite.com/elastic/integrations/builds/17412) succeeded 9f8506d87465e4db6051a2d075ab2c9dd1710932
* :green_heart: [Build #17354](https://buildkite.com/elastic/integrations/builds/17354) succeeded 25632c2a1771af07b92ce21f2fc3cef5c5736684
* :green_heart: [Build #17277](https://buildkite.com/elastic/integrations/builds/17277) succeeded c5599fa32a332ddf7c8f17294b5f8712de0c46a4
* :green_heart: [Build #17276](https://buildkite.com/elastic/integrations/builds/17276) succeeded 82f883459dbde13be79dbafd2bd7349a0cb391f7
* :green_heart: [Build #17232](https://buildkite.com/elastic/integrations/builds/17232) succeeded 4d557e660da7712d12329c8037d48bf04996a814
* :green_heart: [Build #17214](https://buildkite.com/elastic/integrations/builds/17214) succeeded 5ca6264cb5a40d105a6cbbc50244408ad9f9ba22

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17492","number":17492,"commit":"a2cbc199c77e370ecd57639ddc28089742db86e9"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17412","number":17412,"commit":"9f8506d87465e4db6051a2d075ab2c9dd1710932"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17354","number":17354,"commit":"25632c2a1771af07b92ce21f2fc3cef5c5736684"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17277","number":17277,"commit":"c5599fa32a332ddf7c8f17294b5f8712de0c46a4"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17276","number":17276,"commit":"82f883459dbde13be79dbafd2bd7349a0cb391f7"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17232","number":17232,"commit":"4d557e660da7712d12329c8037d48bf04996a814"}],"number":17492}
buildkite-pr-comment-->

2024-10-23 11:19 UTC, maxcold commented on packages/wiz/data_stream/cloud_configuration_finding/fields/rule.yml
>        type: text
@kcreddy @andrewkroh Looking at the value of the `ecs@mappings` in my stack I don't see it as a replacement of `external: ecs` . Actually, I would like to understand the use of `ecs@mappings` better, as in our team we understood that it is a replacement of manual mapping, but then not everything that is available in ECS also mapped in this component template. Eg. there are no mappings for the `rule.*` fields, except the ones falling into broader mappings such as `*.name` 
```
{
  "dynamic_templates": [
    {
      "ecs_timestamp": {
        "mapping": {
          "ignore_malformed": false,
          "type": "date"
        },
        "match": "@timestamp"
      }
    },
    {
      "ecs_message_match_only_text": {
        "path_match": [
          "message",
          "*.message"
        ],
        "mapping": {
          "type": "match_only_text"
        },
        "unmatch_mapping_type": "object"
      }
    },
    {
      "ecs_non_indexed_keyword": {
        "path_match": [
          "*event.original"
        ],
        "mapping": {
          "index": false,
          "type": "keyword",
          "doc_values": false
        }
      }
    },
    {
      "ecs_non_indexed_long": {
        "path_match": [
          "*.x509.public_key_exponent"
        ],
        "mapping": {
          "index": false,
          "type": "long",
          "doc_values": false
        }
      }
    },
    {
      "ecs_ip": {
        "path_match": [
          "ip",
          "*.ip",
          "*_ip"
        ],
        "mapping": {
          "type": "ip"
        },
        "match_mapping_type": "string"
      }
    },
    {
      "ecs_wildcard": {
        "path_match": [
          "*.io.text",
          "*.message_id",
          "*registry.data.strings",
          "*url.path"
        ],
        "mapping": {
          "type": "wildcard"
        },
        "unmatch_mapping_type": "object"
      }
    },
    {
      "ecs_path_match_wildcard_and_match_only_text": {
        "path_match": [
          "*.body.content",
          "*url.full",
          "*url.original"
        ],
        "mapping": {
          "fields": {
            "text": {
              "type": "match_only_text"
            }
          },
          "type": "wildcard"
        },
        "unmatch_mapping_type": "object"
      }
    },
    {
      "ecs_match_wildcard_and_match_only_text": {
        "mapping": {
          "fields": {
            "text": {
              "type": "match_only_text"
            }
          },
          "type": "wildcard"
        },
        "unmatch_mapping_type": "object",
        "match": [
          "*command_line",
          "*stack_trace"
        ]
      }
    },
    {
      "ecs_path_match_keyword_and_match_only_text": {
        "path_match": [
          "*.title",
          "*.executable",
          "*.name",
          "*.working_directory",
          "*.full_name",
          "*file.path",
          "*file.target_path",
          "*os.full",
          "*email.subject",
          "*vulnerability.description",
          "*user_agent.original"
        ],
        "mapping": {
          "fields": {
            "text": {
              "type": "match_only_text"
            }
          },
          "type": "keyword"
        },
        "unmatch_mapping_type": "object"
      }
    },
    {
      "ecs_date": {
        "path_match": [
          "*.timestamp",
          "*_timestamp",
          "*.not_after",
          "*.not_before",
          "*.accessed",
          "created",
          "*.created",
          "*.installed",
          "*.creation_date",
          "*.ctime",
          "*.mtime",
          "ingested",
          "*.ingested",
          "*.start",
          "*.end",
          "*.indicator.first_seen",
          "*.indicator.last_seen",
          "*.indicator.modified_at",
          "*threat.enrichments.matched.occurred"
        ],
        "mapping": {
          "type": "date"
        },
        "unmatch_mapping_type": "object"
      }
    },
    {
      "ecs_path_match_float": {
        "path_match": [
          "*.score.*",
          "*_score*"
        ],
        "mapping": {
          "type": "float"
        },
        "path_unmatch": "*.version",
        "unmatch_mapping_type": "object"
      }
    },
    {
      "ecs_usage_double_scaled_float": {
        "path_match": "*.usage",
        "mapping": {
          "scaling_factor": 1000,
          "type": "scaled_float"
        },
        "match_mapping_type": [
          "double",
          "long",
          "string"
        ]
      }
    },
    {
      "ecs_geo_point": {
        "path_match": [
          "*.geo.location"
        ],
        "mapping": {
          "type": "geo_point"
        }
      }
    },
    {
      "ecs_flattened": {
        "path_match": [
          "*structured_data",
          "*exports",
          "*imports"
        ],
        "mapping": {
          "type": "flattened"
        },
        "match_mapping_type": "object"
      }
    },
    {
      "all_strings_to_keywords": {
        "mapping": {
          "ignore_above": 1024,
          "type": "keyword"
        },
        "match_mapping_type": "string"
      }
    }
  ]
}
```

2024-10-23 11:33 UTC, maxcold commented on packages/wiz/data_stream/cloud_configuration_finding/fields/rule.yml
> +      external: ecs
I have some concerns about it, answered in the linked comment

2024-10-23 12:19 UTC, kcreddy commented on packages/wiz/data_stream/cloud_configuration_finding/fields/rule.yml
>        type: text
AFAIU the idea of `ecs@mappings` component template is to have a generic set of dynamic templates that works across all ECS entities, instead of defining mappings for specific entities like `rule.*`, `vulnerability.*` etc. 

In our case, following are `rule.*` fields that are defined as `external: ecs` and the corresponding dynamic template inside [`ecs@mappings`](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/core/template-resources/src/main/resources/ecs%40mappings.json) that is handling it:
| Field in `rule.yml`   |      Handled by dynamic template     |
|----------|:-------------:|
| rule.uuid |  `all_strings_to_keywords` |
| rule.id |    `all_strings_to_keywords`   |
| rule.name |    `ecs_path_match_keyword_and_match_only_text`   |
| rule.description |    `all_strings_to_keywords`   |
| rule.reference |    `all_strings_to_keywords`   |

Comparing the above dynamic mappings with [ECS rule fields](https://www.elastic.co/guide/en/ecs/current/ecs-rule.html), it matches correctly. 

`rule.remediation` is anyway manually defined as it is not in ECS.

2024-10-23 13:05 UTC, kcreddy commented
@maxcold, should this PR also contain a documentation update suggesting users to update `Initial Interval` according to their needs, like we discussed? or is it going to be part of Cloud Security documentation and we just link it here?

2024-10-23 13:48 UTC, maxcold commented on packages/wiz/data_stream/cloud_configuration_finding/fields/rule.yml
>        type: text
@kcreddy now I see how `keyword` mapping is being solved in the template, thanks. Then yes, I agree, it makes sense to remove these explicit ecs mappings

2024-10-23 13:53 UTC, maxcold commented on packages/wiz/data_stream/cloud_configuration_finding/fields/rule.yml
> +      external: ecs
updated

2024-10-23 13:54 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17497)
* Commit: 16239674f3adb987f82e3041acb23f35cb676d4d

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/17497#0192b9a7-45f5-4fed-a06c-ea3d4e3a33dc)

### History
* :broken_heart: [Build #17492](https://buildkite.com/elastic/integrations/builds/17492) failed a2cbc199c77e370ecd57639ddc28089742db86e9
* :green_heart: [Build #17412](https://buildkite.com/elastic/integrations/builds/17412) succeeded 9f8506d87465e4db6051a2d075ab2c9dd1710932
* :green_heart: [Build #17354](https://buildkite.com/elastic/integrations/builds/17354) succeeded 25632c2a1771af07b92ce21f2fc3cef5c5736684
* :green_heart: [Build #17277](https://buildkite.com/elastic/integrations/builds/17277) succeeded c5599fa32a332ddf7c8f17294b5f8712de0c46a4
* :green_heart: [Build #17276](https://buildkite.com/elastic/integrations/builds/17276) succeeded 82f883459dbde13be79dbafd2bd7349a0cb391f7
* :green_heart: [Build #17232](https://buildkite.com/elastic/integrations/builds/17232) succeeded 4d557e660da7712d12329c8037d48bf04996a814

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17497","number":17497,"commit":"16239674f3adb987f82e3041acb23f35cb676d4d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17492","number":17492,"commit":"a2cbc199c77e370ecd57639ddc28089742db86e9"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17412","number":17412,"commit":"9f8506d87465e4db6051a2d075ab2c9dd1710932"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17354","number":17354,"commit":"25632c2a1771af07b92ce21f2fc3cef5c5736684"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17277","number":17277,"commit":"c5599fa32a332ddf7c8f17294b5f8712de0c46a4"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17276","number":17276,"commit":"82f883459dbde13be79dbafd2bd7349a0cb391f7"}],"number":17497}
buildkite-pr-comment-->

2024-10-23 14:06 UTC, maxcold commented
@kcreddy regarding the docs, the work on them is in progress, when product with docs team come up with a final version we can incorporate these changes in our PRs

2024-10-23 14:39 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17499)
* Commit: 1184a6b751d2d1ccaf4687fb1a451315391c605d

### History
* :broken_heart: [Build #17497](https://buildkite.com/elastic/integrations/builds/17497) failed 16239674f3adb987f82e3041acb23f35cb676d4d
* :broken_heart: [Build #17492](https://buildkite.com/elastic/integrations/builds/17492) failed a2cbc199c77e370ecd57639ddc28089742db86e9
* :green_heart: [Build #17412](https://buildkite.com/elastic/integrations/builds/17412) succeeded 9f8506d87465e4db6051a2d075ab2c9dd1710932
* :green_heart: [Build #17354](https://buildkite.com/elastic/integrations/builds/17354) succeeded 25632c2a1771af07b92ce21f2fc3cef5c5736684
* :green_heart: [Build #17277](https://buildkite.com/elastic/integrations/builds/17277) succeeded c5599fa32a332ddf7c8f17294b5f8712de0c46a4
* :green_heart: [Build #17276](https://buildkite.com/elastic/integrations/builds/17276) succeeded 82f883459dbde13be79dbafd2bd7349a0cb391f7

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17499","number":17499,"commit":"1184a6b751d2d1ccaf4687fb1a451315391c605d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17497","number":17497,"commit":"16239674f3adb987f82e3041acb23f35cb676d4d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17492","number":17492,"commit":"a2cbc199c77e370ecd57639ddc28089742db86e9"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17412","number":17412,"commit":"9f8506d87465e4db6051a2d075ab2c9dd1710932"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17354","number":17354,"commit":"25632c2a1771af07b92ce21f2fc3cef5c5736684"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17277","number":17277,"commit":"c5599fa32a332ddf7c8f17294b5f8712de0c46a4"}],"number":17499}
buildkite-pr-comment-->

2024-10-23 21:04 UTC, efd6 requested changes

2024-10-23 21:04 UTC, efd6 commented on packages/wiz/changelog.yml
> +- version: "2.0.0"
I don't think this is the correct way to do this; the versions that have been released should continue to exist.

Also, what is it that makes this a 2.0.0? What is breaking here?

2024-10-24 05:58 UTC, kcreddy approved these changes
LGTM for my comments. 
Please merge after Dan's comments are addressed regarding version.

2024-10-24 11:50 UTC, maxcold commented on packages/wiz/changelog.yml
> +- version: "2.0.0"
what would be the correct way to do that? From a user's point of view if they never enabled "show beta integrations", they would upgrade from 1.8.1 (latest released non-preview version) to 2.0.0 and would get all the changes from `1.9.0-preview*` with the change, and as a user I would expect to see this as a part of 2.0.0 changelog

> Also, what is it that makes this a 2.0.0? What is breaking here?

this is reflected in the changelog
```
    - description: Rely on external ecs for ESC fields. rule.reference, rule.descipriton and rule.remediation changed from text to keyword.
      type: breaking-change
      link: https://github.com/elastic/integrations/pull/11414
    - description: Remove rule.references field and its mapping. Please use the ECS rule.reference field instead.
      type: breaking-change
      link: https://github.com/elastic/integrations/pull/11414
```

2024-10-24 20:09 UTC, efd6 commented on packages/wiz/changelog.yml
> +- version: "2.0.0"
The change here inserts a bunch of breaking changes before a bugfix that had already been released as a 1.9.0 preview. If correct chronological order had been used and they were added as a 1.9.0, the full set of 1.9.0 changes would not have been breaking; there would have been a single new version entry looking like this:
```
- version: "1.9.0"
  changes:
    - description: Add cloud.account.name mapping to latest_cdr_vulnerabilities transform destination.
      type: bugfix
      link: https://github.com/elastic/integrations/pull/<SOMEOTHERPRNUMBER>
    - description: Default to resource id when provider_id is missing for resource.id field in cloud_configuration_finding data stream.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/<SOMEOTHERPRNUMBER>
    - description: Add cloud.account.name mapping to latest_cdr_vulnerabilities transform destination.
      type: enhancement
      link: https://github.com/elastic/integrations/pull/11414
```
(leaving all the other already published versions in tact)

then you could have added this breaking enhancement:
```
- version: "2.0.0"
  changes:
    - description: Rely on external ecs for ESC fields. rule.reference, rule.descipriton and rule.remediation changed from text to keyword.
      type: breaking-change
      link: https://github.com/elastic/integrations/pull/11414
    - description: Remove rule.references field and its mapping. Please use the ECS rule.reference field instead.
      type: breaking-change
      link: https://github.com/elastic/integrations/pull/11414
```
This is not an academic issue; there is a bugfix that is being hidden here from people who may not want to upgrade across a break, and also blocks them from getting non-breaking enhancements. Admittedly, there is a fix in 1.8.something hidden in a backport branch, so the bugfix is less of a concern, but the non-breaking enhancements are still an issue.

2024-10-25 07:57 UTC, maxcold commented on packages/wiz/changelog.yml
> +- version: "2.0.0"
The problem is that 1.9.0-preview1 and 1.9.0-preview3 introduce the latest transforms, which we plan to release as part of the CDR initiative. These changes require the 8.16.x version of the stack; that's why we were asked to hold them in an open PR until closer to the 8.16 release date, as the flow with preview is not advised to be used. So, I can't release 1.9.0 just yet. Additionally, there are problems that we found while testing the CDR approach, together with the product folks, which require breaking changes before we can release transforms. That's why I'm skipping the 1.9.0 release and moving to 2.0.0, as all the changes there are bundled under CDR. We don't want users to be able to install the version with the transforms before the breaking changes are made. I can move the breaking change entries to the top of the changelog if you think that this would help.

2024-10-27 20:13 UTC, efd6 commented on packages/wiz/changelog.yml
> +- version: "2.0.0"
This is deeply dissatisfying. I have removed my block.

2024-10-28 09:31 UTC, CohenIdo commented on packages/wiz/data_stream/vulnerability/fields/base-fields.yml
>    type: constant_keyword
Shouldn’t we remove type: constant_keyword? 
The type is inherited from ecs.

2024-10-28 10:15 UTC, CohenIdo requested changes
There are several fields configured as ecs that also have a specified type. Is there a reason for this configuration?

2024-10-28 10:27 UTC, maxcold commented on packages/wiz/data_stream/issue/fields/base-fields.yml
>    type: constant_keyword
the type in ECS is `keyword` but we set the value `wiz`, that's why we change the type to the one which is better for performance as per recommendation from Service Integration team

2024-10-28 10:27 UTC, maxcold commented on packages/wiz/data_stream/issue/fields/base-fields.yml
>    type: constant_keyword
the type in ECS is `keyword` but we set the value `wiz.issue`, that's why we change the type to the one which is better for performance as per recommendation from Service Integration team

2024-10-28 10:27 UTC, maxcold commented on packages/wiz/data_stream/vulnerability/fields/base-fields.yml
>    type: constant_keyword
the type in ECS is keyword but we set the value wiz, that's why we change the type to the one which is better for performance as per recommendation from Service Integration team

2024-10-28 10:32 UTC, CohenIdo approved these changes

2024-10-28 11:18 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17620)
* Commit: 15734c8f7ea98d463e0dd9c67ea4ce691e5615c4

### Failed CI Steps
* [Check integrations wiz](https://buildkite.com/elastic/integrations/builds/17620#0192d2d4-a9d6-420c-bfd8-9defae0a5c56)

### History
* :green_heart: [Build #17499](https://buildkite.com/elastic/integrations/builds/17499) succeeded 1184a6b751d2d1ccaf4687fb1a451315391c605d
* :broken_heart: [Build #17497](https://buildkite.com/elastic/integrations/builds/17497) failed 16239674f3adb987f82e3041acb23f35cb676d4d
* :broken_heart: [Build #17492](https://buildkite.com/elastic/integrations/builds/17492) failed a2cbc199c77e370ecd57639ddc28089742db86e9
* :green_heart: [Build #17412](https://buildkite.com/elastic/integrations/builds/17412) succeeded 9f8506d87465e4db6051a2d075ab2c9dd1710932
* :green_heart: [Build #17354](https://buildkite.com/elastic/integrations/builds/17354) succeeded 25632c2a1771af07b92ce21f2fc3cef5c5736684
* :green_heart: [Build #17277](https://buildkite.com/elastic/integrations/builds/17277) succeeded c5599fa32a332ddf7c8f17294b5f8712de0c46a4

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17620","number":17620,"commit":"15734c8f7ea98d463e0dd9c67ea4ce691e5615c4"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17499","number":17499,"commit":"1184a6b751d2d1ccaf4687fb1a451315391c605d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17497","number":17497,"commit":"16239674f3adb987f82e3041acb23f35cb676d4d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17492","number":17492,"commit":"a2cbc199c77e370ecd57639ddc28089742db86e9"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17412","number":17412,"commit":"9f8506d87465e4db6051a2d075ab2c9dd1710932"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17354","number":17354,"commit":"25632c2a1771af07b92ce21f2fc3cef5c5736684"}],"number":17620}
buildkite-pr-comment-->

2024-10-29 09:17 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17675)
* Commit: 93271dff8e6b2f0ab77b34d6c919981851bc63c6

### History
* :green_heart: [Build #17638](https://buildkite.com/elastic/integrations/builds/17638) succeeded e7616b0dd2ae583d7574ab46b2c49a91b41fcfeb
* :broken_heart: [Build #17620](https://buildkite.com/elastic/integrations/builds/17620) failed 15734c8f7ea98d463e0dd9c67ea4ce691e5615c4
* :green_heart: [Build #17499](https://buildkite.com/elastic/integrations/builds/17499) succeeded 1184a6b751d2d1ccaf4687fb1a451315391c605d
* :broken_heart: [Build #17497](https://buildkite.com/elastic/integrations/builds/17497) failed 16239674f3adb987f82e3041acb23f35cb676d4d
* :broken_heart: [Build #17492](https://buildkite.com/elastic/integrations/builds/17492) failed a2cbc199c77e370ecd57639ddc28089742db86e9
* :green_heart: [Build #17412](https://buildkite.com/elastic/integrations/builds/17412) succeeded 9f8506d87465e4db6051a2d075ab2c9dd1710932

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17675","number":17675,"commit":"93271dff8e6b2f0ab77b34d6c919981851bc63c6"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17638","number":17638,"commit":"e7616b0dd2ae583d7574ab46b2c49a91b41fcfeb"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17620","number":17620,"commit":"15734c8f7ea98d463e0dd9c67ea4ce691e5615c4"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17499","number":17499,"commit":"1184a6b751d2d1ccaf4687fb1a451315391c605d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17497","number":17497,"commit":"16239674f3adb987f82e3041acb23f35cb676d4d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17492","number":17492,"commit":"a2cbc199c77e370ecd57639ddc28089742db86e9"}],"number":17675}
buildkite-pr-comment-->

2024-10-29 10:38 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17681)
* Commit: 3f11a0f18dfaa9aaa06876cb9a521bb720750c72

### History
* :green_heart: [Build #17675](https://buildkite.com/elastic/integrations/builds/17675) succeeded 93271dff8e6b2f0ab77b34d6c919981851bc63c6
* :green_heart: [Build #17638](https://buildkite.com/elastic/integrations/builds/17638) succeeded e7616b0dd2ae583d7574ab46b2c49a91b41fcfeb
* :broken_heart: [Build #17620](https://buildkite.com/elastic/integrations/builds/17620) failed 15734c8f7ea98d463e0dd9c67ea4ce691e5615c4
* :green_heart: [Build #17499](https://buildkite.com/elastic/integrations/builds/17499) succeeded 1184a6b751d2d1ccaf4687fb1a451315391c605d
* :broken_heart: [Build #17497](https://buildkite.com/elastic/integrations/builds/17497) failed 16239674f3adb987f82e3041acb23f35cb676d4d
* :broken_heart: [Build #17492](https://buildkite.com/elastic/integrations/builds/17492) failed a2cbc199c77e370ecd57639ddc28089742db86e9

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17681","number":17681,"commit":"3f11a0f18dfaa9aaa06876cb9a521bb720750c72"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17675","number":17675,"commit":"93271dff8e6b2f0ab77b34d6c919981851bc63c6"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17638","number":17638,"commit":"e7616b0dd2ae583d7574ab46b2c49a91b41fcfeb"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17620","number":17620,"commit":"15734c8f7ea98d463e0dd9c67ea4ce691e5615c4"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17499","number":17499,"commit":"1184a6b751d2d1ccaf4687fb1a451315391c605d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17497","number":17497,"commit":"16239674f3adb987f82e3041acb23f35cb676d4d"}],"number":17681}
buildkite-pr-comment-->

2024-10-30 10:08 UTC, merged