cisco_duo.trust_monitor: Fix 400 and 401 errors in Trust Monitor
elastic/integrations pull request #11621
Opened 2024-11-03 18:23 UTC by kcreddy

## Proposed commit message

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).
- [ ] I have verified that any added dashboard complies with Kibana's [Dashboard good practices](https://docs.elastic.dev/ux-guidelines/data-viz/dashboard-good-practices) 

## Author's Checklist

- [ ] 

## How to test this PR locally

## Related issues

- 

## Screenshots

2024-11-03 18:45 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17835)
* Commit: ef23a21776ec387d06267fce7ab56fff2bac4301

### Failed CI Steps
* [Check integrations cisco_duo](https://buildkite.com/elastic/integrations/builds/17835#0192f348-7bbb-4b93-8f25-6d6ba9852a3f)

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17835","number":17835,"commit":"ef23a21776ec387d06267fce7ab56fff2bac4301"}],"number":17835}
buildkite-pr-comment-->

2024-11-04 08:46 UTC, kcreddy commented on packages/cisco_duo/data_stream/trust_monitor/agent/stream/cel.yml.hbs
> +                                        !has(dyn(state).?cursor.last_published) ?
`dyn` added in few places to avoid error: `type 'string' does not support field selection`

2024-11-05 11:28 UTC, kcreddy commented on packages/cisco_duo/data_stream/trust_monitor/agent/stream/cel.yml.hbs
> +                 "limit": [string(dyn(state).limit)],
`dyn(state)` added here to avoid error: `no such overload string(double)`

2024-11-05 11:54 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17914)
* Commit: 25817536a612e9e60c222139a62d5e380740d2d6

### History
* :broken_heart: [Build #17835](https://buildkite.com/elastic/integrations/builds/17835) failed ef23a21776ec387d06267fce7ab56fff2bac4301

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17914","number":17914,"commit":"25817536a612e9e60c222139a62d5e380740d2d6"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17835","number":17835,"commit":"ef23a21776ec387d06267fce7ab56fff2bac4301"}],"number":17914}
buildkite-pr-comment-->

2024-11-06 13:32 UTC, kcreddy commented
Addressed comments: https://github.com/elastic/integrations/pull/11640#discussion_r1830739341 and https://github.com/elastic/integrations/pull/11640#discussion_r1830743284 and also @chemamartinez's suggestion on using `now()` vs `now` in `date` calculation. 

The change is in commit [edcac5a](https://github.com/elastic/integrations/pull/11621/commits/edcac5aa8461a94a1349be7e44f9cbb133db6572)

2024-11-06 13:57 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17970)
* Commit: edcac5aa8461a94a1349be7e44f9cbb133db6572

### History
* :green_heart: [Build #17914](https://buildkite.com/elastic/integrations/builds/17914) succeeded 25817536a612e9e60c222139a62d5e380740d2d6
* :broken_heart: [Build #17835](https://buildkite.com/elastic/integrations/builds/17835) failed ef23a21776ec387d06267fce7ab56fff2bac4301

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17970","number":17970,"commit":"edcac5aa8461a94a1349be7e44f9cbb133db6572"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17914","number":17914,"commit":"25817536a612e9e60c222139a62d5e380740d2d6"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17835","number":17835,"commit":"ef23a21776ec387d06267fce7ab56fff2bac4301"}],"number":17970}
buildkite-pr-comment-->

2024-11-06 14:12 UTC, kcreddy commented on packages/cisco_duo/data_stream/trust_monitor/agent/stream/cel.yml.hbs
> +                mx < oneeigthydays ? (state.want_more ? string(state.maxtime) : string(mx * 1000)) : string(oneeigthydays * 1000)
This is not formatted due to following error (if formatted):

`failed to check program: failed compilation: ERROR: <input>:-1:0: error recovery token lookahead limit exceeded: 256\nERROR: <input>:13:33: Syntax error: mismatched input '?' expecting ':'\n |                 state.want_more ? \n | ................................^\nERROR: <input>:17:13: Syntax error: mismatched input ':' expecting ')'\n |             : \n | ............^\nERROR: <input>:18:44: Syntax error: mismatched input ')' expecting {'}', ','}\n |                 string(oneeigthydays * 1000)\n | ...........................................^\nERROR: <input>:20:5: Syntax error: mismatched input ')' expecting <EOF>\n |     )\n | ....^ accessing config`

2024-11-06 14:13 UTC, kcreddy commented on packages/cisco_duo/data_stream/trust_monitor/agent/stream/cel.yml.hbs
> +                mx < oneeigthydays ? (state.want_more ? string(state.maxtime) : string(mx * 1000)) : string(oneeigthydays * 1000)
This is not formatted because of following error (if formatted):

`failed to check program: failed compilation: ERROR: <input>:-1:0: error recovery token lookahead limit exceeded: 256\nERROR: <input>:13:33: Syntax error: mismatched input '?' expecting ':'\n |                 state.want_more ? \n | ................................^\nERROR: <input>:17:13: Syntax error: mismatched input ':' expecting ')'\n |             : \n | ............^\nERROR: <input>:18:44: Syntax error: mismatched input ')' expecting {'}', ','}\n |                 string(oneeigthydays * 1000)\n | ...........................................^\nERROR: <input>:20:5: Syntax error: mismatched input ')' expecting <EOF>\n |     )\n | ....^ accessing config`

2024-11-06 14:28 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/17971)
* Commit: 1a39f3e2c4cfa12ec177556582af494e0b50b4bc

### History
* :green_heart: [Build #17970](https://buildkite.com/elastic/integrations/builds/17970) succeeded edcac5aa8461a94a1349be7e44f9cbb133db6572
* :green_heart: [Build #17914](https://buildkite.com/elastic/integrations/builds/17914) succeeded 25817536a612e9e60c222139a62d5e380740d2d6
* :broken_heart: [Build #17835](https://buildkite.com/elastic/integrations/builds/17835) failed ef23a21776ec387d06267fce7ab56fff2bac4301

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17971","number":17971,"commit":"1a39f3e2c4cfa12ec177556582af494e0b50b4bc"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17970","number":17970,"commit":"edcac5aa8461a94a1349be7e44f9cbb133db6572"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17914","number":17914,"commit":"25817536a612e9e60c222139a62d5e380740d2d6"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17835","number":17835,"commit":"ef23a21776ec387d06267fce7ab56fff2bac4301"}],"number":17971}
buildkite-pr-comment-->

2024-11-06 14:46 UTC, chemamartinez approved these changes

2024-11-07 09:45 UTC, chrisberkhout requested changes

2024-11-07 09:45 UTC, chrisberkhout commented on packages/cisco_duo/data_stream/trust_monitor/agent/stream/cel.yml.hbs
> +                "mintime": string(state.?cursor.last_published.orValue(int(now - duration(state.initial_interval)) * 1000)),
```suggestion
                "mintime": string(int(state.?cursor.last_published.orValue(int(now - duration(state.initial_interval)) * 1000))),
```

I think this outer `int` is needed for the case that `state.cursor.last_published` is used.

Large int values will be formatted in floating point notation if not explicitly cast to int. It doesn't just happen with JSON input data, it happens with int values passed forward in state.

For example:
```
mito -max_executions 3 -data <(echo '{"t": 1746522206000}') <(echo '{
  "t": state.t,
  "int_t": int(state.t),
  "str_t": string(state.t),
  "str_int_t": string(int(state.t)),
  "want_more": true,
}')
```
```
{
	"int_t": 1746522206000,
	"str_int_t": "1746522206000",
	"str_t": "1.746522206e+12",
	"t": 1746522206000,
	"want_more": true
}
{
	"int_t": 1746522206000,
	"str_int_t": "1746522206000",
	"str_t": "1.746522206e+12",
	"t": 1746522206000,
	"want_more": true
}
{
	"int_t": 1746522206000,
	"str_int_t": "1746522206000",
	"str_t": "1.746522206e+12",
	"t": 1746522206000,
	"want_more": true
}
```

2024-11-07 09:45 UTC, chrisberkhout commented on packages/cisco_duo/data_stream/trust_monitor/agent/stream/cel.yml.hbs
> +                mx < oneeigthydays ? (state.want_more ? string(state.maxtime) : string(mx * 1000)) : string(oneeigthydays * 1000)
```suggestion
        "maxtime": [int(timestamp(int(state.mintime)/1000) + duration("4320h")), int(now - duration("2m"))].min()
```

Easier to read:
Go 180 days forward, or up to 2 mins ago, whichever is less.

2024-11-07 09:57 UTC, chrisberkhout commented on packages/cisco_duo/data_stream/trust_monitor/agent/stream/cel.yml.hbs
> +                    optional.none(),
```suggestion
                 ?"offset": state.?next_offset.optMap(v, [string(v)]),
```

2024-11-07 11:35 UTC, kcreddy commented on packages/cisco_duo/data_stream/trust_monitor/agent/stream/cel.yml.hbs
> +                mx < oneeigthydays ? (state.want_more ? string(state.maxtime) : string(mx * 1000)) : string(oneeigthydays * 1000)
But this doesn't check the `state.want_more ?` case which is required to pass same `maxtime` to the pagination requests and not re-calculated one.

2024-11-07 11:36 UTC, kcreddy commented on packages/cisco_duo/data_stream/trust_monitor/agent/stream/cel.yml.hbs
> +                "mintime": string(state.?cursor.last_published.orValue(int(now - duration(state.initial_interval)) * 1000)),
This is nice. I had same errors, didn't know where `double` was coming from. Guess I could remove one of the `dyn(`

2024-11-07 11:42 UTC, kcreddy commented on packages/cisco_duo/data_stream/trust_monitor/agent/stream/cel.yml.hbs
> +                "mintime": string(state.?cursor.last_published.orValue(int(now - duration(state.initial_interval)) * 1000)),
Guess not, removing that `dyn` still leads to same error `no such overload string(double)`. So retained the `dyn`.

Updated as per suggestion in [9122974](https://github.com/elastic/integrations/pull/11621/commits/912297463ec88b9f1b1f22bbf47561b62f8ed539)

2024-11-07 11:43 UTC, kcreddy commented on packages/cisco_duo/data_stream/trust_monitor/agent/stream/cel.yml.hbs
> +                    optional.none(),
Updated as suggested.

2024-11-07 12:02 UTC, chrisberkhout commented on packages/cisco_duo/data_stream/trust_monitor/agent/stream/cel.yml.hbs
> +                mx < oneeigthydays ? (state.want_more ? string(state.maxtime) : string(mx * 1000)) : string(oneeigthydays * 1000)
Sorry, I missed that.

In the original, if `state.want_more == true` it will not reuse the existing `state.maxtime` if a newly calculated value crosses the current time.

I updated the suggestion to check `state.want_more` and only calculate a new value if it's an initial page.

Is that correct?

Feel free to take whatever parts help.

2024-11-07 12:09 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/18011)
* Commit: 912297463ec88b9f1b1f22bbf47561b62f8ed539

### History
* :green_heart: [Build #17971](https://buildkite.com/elastic/integrations/builds/17971) succeeded 1a39f3e2c4cfa12ec177556582af494e0b50b4bc
* :green_heart: [Build #17970](https://buildkite.com/elastic/integrations/builds/17970) succeeded edcac5aa8461a94a1349be7e44f9cbb133db6572
* :green_heart: [Build #17914](https://buildkite.com/elastic/integrations/builds/17914) succeeded 25817536a612e9e60c222139a62d5e380740d2d6
* :broken_heart: [Build #17835](https://buildkite.com/elastic/integrations/builds/17835) failed ef23a21776ec387d06267fce7ab56fff2bac4301

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18011","number":18011,"commit":"912297463ec88b9f1b1f22bbf47561b62f8ed539"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17971","number":17971,"commit":"1a39f3e2c4cfa12ec177556582af494e0b50b4bc"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17970","number":17970,"commit":"edcac5aa8461a94a1349be7e44f9cbb133db6572"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17914","number":17914,"commit":"25817536a612e9e60c222139a62d5e380740d2d6"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17835","number":17835,"commit":"ef23a21776ec387d06267fce7ab56fff2bac4301"}],"number":18011}
buildkite-pr-comment-->

2024-11-07 12:59 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/18014)
* Commit: 0a796ab4d6f26d5682e5c8a26163dc2154dce7a9

### History
* :green_heart: [Build #18011](https://buildkite.com/elastic/integrations/builds/18011) succeeded 912297463ec88b9f1b1f22bbf47561b62f8ed539
* :green_heart: [Build #17971](https://buildkite.com/elastic/integrations/builds/17971) succeeded 1a39f3e2c4cfa12ec177556582af494e0b50b4bc
* :green_heart: [Build #17970](https://buildkite.com/elastic/integrations/builds/17970) succeeded edcac5aa8461a94a1349be7e44f9cbb133db6572
* :green_heart: [Build #17914](https://buildkite.com/elastic/integrations/builds/17914) succeeded 25817536a612e9e60c222139a62d5e380740d2d6
* :broken_heart: [Build #17835](https://buildkite.com/elastic/integrations/builds/17835) failed ef23a21776ec387d06267fce7ab56fff2bac4301

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18014","number":18014,"commit":"0a796ab4d6f26d5682e5c8a26163dc2154dce7a9"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18011","number":18011,"commit":"912297463ec88b9f1b1f22bbf47561b62f8ed539"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17971","number":17971,"commit":"1a39f3e2c4cfa12ec177556582af494e0b50b4bc"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17970","number":17970,"commit":"edcac5aa8461a94a1349be7e44f9cbb133db6572"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17914","number":17914,"commit":"25817536a612e9e60c222139a62d5e380740d2d6"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/17835","number":17835,"commit":"ef23a21776ec387d06267fce7ab56fff2bac4301"}],"number":18014}
buildkite-pr-comment-->

2024-11-07 17:23 UTC, chrisberkhout approved these changes
In this PR, since there was some refactoring with indentation changes, it would have been helpful to separate changes in that category from the functional changes, just to be able to check things in smaller diffs.

Looks like good and correct changes. :+1:

2024-11-08 04:32 UTC, merged