CSPM: add cloud connectors support
elastic/integrations pull request #11663
Opened 2024-11-07 14:54 UTC by moukoublen

## Proposed commit message

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).
- [ ] I have verified that any added dashboard complies with Kibana's [Dashboard good practices](https://docs.elastic.dev/ux-guidelines/data-viz/dashboard-good-practices) 

## Author's Checklist

- [ ] 

## How to test this PR locally

## Related issues

- 

## Screenshots

2024-11-07 15:11 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/18024)
* Commit: 68981ecd3d215174caf182c083d18990b62528a7

cc @moukoublen

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18024","number":18024,"commit":"68981ecd3d215174caf182c083d18990b62528a7"}],"number":18024}
buildkite-pr-comment-->

2024-11-08 10:09 UTC, maxcold commented on packages/cloud_security_posture/changelog.yml
> +- version: "1.11.0-preview14"
do we want this change in 8.16 ? as we didn't test 8.16 with this change, maybe it would be safer to have in in 1.12.x?

2024-11-08 10:12 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/18055)
* Commit: ba48abd8738f6100f9d5219f12117ff717c0deb9

### History
* :green_heart: [Build #18024](https://buildkite.com/elastic/integrations/builds/18024) succeeded 68981ecd3d215174caf182c083d18990b62528a7

cc @moukoublen

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18055","number":18055,"commit":"ba48abd8738f6100f9d5219f12117ff717c0deb9"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18024","number":18024,"commit":"68981ecd3d215174caf182c083d18990b62528a7"}],"number":18055}
buildkite-pr-comment-->

2024-11-08 10:21 UTC, moukoublen commented on packages/cloud_security_posture/changelog.yml
> +- version: "1.11.0-preview14"
You are right; I forgot we still need to bump to 8.17. 
This means I should merge after we bump the stable `1.11.0` to create the `1.12.0-preview1.` (otherwise, it would be a bit more complicated to produce the stable `1.11.0` release with a backport branch).

2024-11-11 14:38 UTC, Omolola-Akinleye commented on packages/cloud_security_posture/data_stream/findings/agent/stream/aws.yml.hbs
> +      supports_cloud_connectors: {{supports_cloud_connectors}}
@moukoublen I thought  we're going to add the `support_cloud_connectors`  config in `agentPolicy.agent_features` . Why do we need the `supports_cloud_connectors` field here?  Will cloudbeat use this field `support_cloud_connectors`?

2024-11-11 14:38 UTC, Omolola-Akinleye commented on packages/cloud_security_posture/manifest.yml
> +            # PROJECT_ID project id for serverless / deployment id for ess
PROJECT_ID refers to Serverless Projects this maybe be confusing toinclude the deployment id. Perhaps another slightly more generic name `ELASTIC_SERVICE_ID`?

2024-11-13 11:53 UTC, moukoublen commented on packages/cloud_security_posture/data_stream/findings/agent/stream/aws.yml.hbs
> +      supports_cloud_connectors: {{supports_cloud_connectors}}
@Omolola-Akinleye yes we need it in both places currently. This flag will be used on the cloudbeat (or beat in general) side to perform double role chaining towards the remote role. 

So we need to be able to indicate that this double chaining needs to happen.

2024-11-13 11:54 UTC, moukoublen commented on packages/cloud_security_posture/manifest.yml
> +            # PROJECT_ID project id for serverless / deployment id for ess
Sure I will update accordingly.

2024-11-13 12:19 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/18274)
* Commit: 52dc54afa792252b9546e180db950fa174e657c5

### History
* :green_heart: [Build #18055](https://buildkite.com/elastic/integrations/builds/18055) succeeded ba48abd8738f6100f9d5219f12117ff717c0deb9
* :green_heart: [Build #18024](https://buildkite.com/elastic/integrations/builds/18024) succeeded 68981ecd3d215174caf182c083d18990b62528a7

cc @moukoublen

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18274","number":18274,"commit":"52dc54afa792252b9546e180db950fa174e657c5"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18055","number":18055,"commit":"ba48abd8738f6100f9d5219f12117ff717c0deb9"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18024","number":18024,"commit":"68981ecd3d215174caf182c083d18990b62528a7"}],"number":18274}
buildkite-pr-comment-->

2024-11-13 18:34 UTC, Omolola-Akinleye approved these changes

2024-11-13 21:46 UTC, Omolola-Akinleye commented on packages/cloud_security_posture/data_stream/findings/manifest.yml
> +      - name: supports_cloud_connectors
should we prefix `aws.support_cloud_connectors` here?

2024-11-14 11:21 UTC, moukoublen commented on packages/cloud_security_posture/data_stream/findings/manifest.yml
> +      - name: supports_cloud_connectors
Thats a good question, I am not entirely sure. I thought that since, hierarchy wise, we are under the  `input: cloudbeat/cis_aws` object that its not really needed. But I will try to find out why do we have the `aws.` prefix on the `aws.credentials.type` and in `aws.account_type`.

2024-11-18 12:35 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/18398)
* Commit: 1479acdc7472d02401d66b99b6def281d3099848

### History
* :green_heart: [Build #18274](https://buildkite.com/elastic/integrations/builds/18274) succeeded 52dc54afa792252b9546e180db950fa174e657c5
* :green_heart: [Build #18055](https://buildkite.com/elastic/integrations/builds/18055) succeeded ba48abd8738f6100f9d5219f12117ff717c0deb9
* :green_heart: [Build #18024](https://buildkite.com/elastic/integrations/builds/18024) succeeded 68981ecd3d215174caf182c083d18990b62528a7

cc @moukoublen

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18398","number":18398,"commit":"1479acdc7472d02401d66b99b6def281d3099848"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18274","number":18274,"commit":"52dc54afa792252b9546e180db950fa174e657c5"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18055","number":18055,"commit":"ba48abd8738f6100f9d5219f12117ff717c0deb9"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18024","number":18024,"commit":"68981ecd3d215174caf182c083d18990b62528a7"}],"number":18398}
buildkite-pr-comment-->

2024-11-18 13:49 UTC, orestisfl requested changes

2024-11-18 14:50 UTC, moukoublen commented on packages/cloud_security_posture/data_stream/findings/manifest.yml
> +      - name: supports_cloud_connectors
Thanks @kubasobon! I added `aws.` prefix in `supports_cloud_connectors` as well.

2024-11-18 14:56 UTC, orestisfl approved these changes

2024-11-18 15:08 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/18403)
* Commit: 8b10322a90bfa52207bffb8493b9c0839432d019

### History
* :green_heart: [Build #18398](https://buildkite.com/elastic/integrations/builds/18398) succeeded 1479acdc7472d02401d66b99b6def281d3099848
* :green_heart: [Build #18274](https://buildkite.com/elastic/integrations/builds/18274) succeeded 52dc54afa792252b9546e180db950fa174e657c5
* :green_heart: [Build #18055](https://buildkite.com/elastic/integrations/builds/18055) succeeded ba48abd8738f6100f9d5219f12117ff717c0deb9
* :green_heart: [Build #18024](https://buildkite.com/elastic/integrations/builds/18024) succeeded 68981ecd3d215174caf182c083d18990b62528a7

cc @moukoublen

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18403","number":18403,"commit":"8b10322a90bfa52207bffb8493b9c0839432d019"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18398","number":18398,"commit":"1479acdc7472d02401d66b99b6def281d3099848"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18274","number":18274,"commit":"52dc54afa792252b9546e180db950fa174e657c5"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18055","number":18055,"commit":"ba48abd8738f6100f9d5219f12117ff717c0deb9"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18024","number":18024,"commit":"68981ecd3d215174caf182c083d18990b62528a7"}],"number":18403}
buildkite-pr-comment-->

2024-11-18 15:29 UTC, kubasobon approved these changes
Thanks for adding the prefixes

2024-11-18 15:45 UTC, merged