[fortinet_fortigate] add hostname parsing for syslog
elastic/integrations pull request #11678
Opened 2024-11-08 18:57 UTC by Nacon96

## Proposed commit message

The current parser is not processing the hostname field of syslog messages, so in some cases, the `observer.name` field remains empty.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).
- [ ] I have verified that any added dashboard complies with Kibana's [Dashboard good practices](https://docs.elastic.dev/ux-guidelines/data-viz/dashboard-good-practices)

2024-11-08 19:02 UTC, elasticmachine commented
Pinging @elastic/sec-deployment-and-devices (Team:Security-Deployment and Devices)

2024-11-11 18:08 UTC, taylor-swanson reviewed
Some minor changes, but otherwise seems good to me.

The top-level manifest version needs to be updated as well:

`manifest.yml`:

```diff
- version: "1.26.0"
+ version: "1.27.0"
```

2024-11-11 18:08 UTC, taylor-swanson commented on packages/fortinet_fortigate/data_stream/log/elasticsearch/ingest_pipeline/default.yml
> +        - "^(?:%{SYSLOG5424PRI}%{NONNEGINT:syslog5424_ver} )+(?:%{TIMESTAMP_ISO8601:syslog5424_ts}|-) +(?:%{HOSTNAME:syslog5424_host}|-) +(-|%{SYSLOG5424PRINTASCII:syslog5424_app}) +(-|%{SYSLOG5424PR
Since we only use `syslog5424_host` and `syslog5424_msg`, we don't need to set the other fields.

```suggestion
        - "^(?:%{SYSLOG5424PRI}%{NONNEGINT} )+(?:%{TIMESTAMP_ISO8601}|-) +(?:%{HOSTNAME:syslog5424_host}|-) +(-|%{SYSLOG5424PRINTASCII}) +(-|%{SYSLOG5424PRINTASCII}) +(-|%{SYSLOG5424PRINTASCII}) +(-|%{SYSLOG5424PRINTASCII}) +(?:%{GREEDYDATA:syslog5424_msg}|-|)"
```

2024-11-11 18:08 UTC, taylor-swanson commented on packages/fortinet_fortigate/changelog.yml
> +- version: "1.26.1"
Since a new field is being added, let's make this a minor change.

```suggestion
- version: "1.27.0"
```

2024-11-11 18:08 UTC, taylor-swanson commented on packages/fortinet_fortigate/data_stream/log/elasticsearch/ingest_pipeline/default.yml
> +        - syslog5424_ver
```suggestion
        - syslog5424_host
        - syslog5424_msg
```

2024-11-11 18:08 UTC, taylor-swanson commented on packages/fortinet_fortigate/data_stream/log/elasticsearch/ingest_pipeline/default.yml
> +        - syslog5424_msg
```suggestion
```

2024-11-11 22:45 UTC, Nacon96 reviewed
i see the changes adequate, thanks.

2024-11-12 14:28 UTC, taylor-swanson requested changes
In case I wasn't clear, the changes I requested are ones I'm requiring.

- For how we use [semver](https://semver.org/), any additional fields added require at least a `minor` change to versioning. Patch versions are reserved for bugfixes/enhancements that don't alter the structure of documents, among other things.
- We don't need to set fields from a grok only to not use them and only remove them later. This just adds unnecessary actions to the pipeline.

2024-11-12 17:06 UTC, taylor-swanson reviewed
Updated changes LGTM, we just need to bump the version in the manifest.

`packages/fortinet_fortigate/manifest.yml`

```diff
- version: "1.26.0"
+ version: "1.27.0"
```

2024-11-18 17:56 UTC, taylor-swanson commented
/test

2024-11-18 18:08 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/18414)
* Commit: 47d8c9c60f2e446be2ecfa4b5756f2c141b363f0

### Failed CI Steps
* [Check integrations fortinet_fortigate](https://buildkite.com/elastic/integrations/builds/18414#01934071-ac97-4c51-a3c9-13fa26f71255)

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18414","number":18414,"commit":"47d8c9c60f2e446be2ecfa4b5756f2c141b363f0"}],"number":18414}
buildkite-pr-comment-->

2024-12-06 19:04 UTC, andrewkroh commented
> we just need to bump the version in the manifest.

I pushed this change. And aligned the changelog to use `enhancement`. PTAL

2024-12-06 19:46 UTC, taylor-swanson commented
/test

2024-12-06 19:47 UTC, taylor-swanson approved these changes

2024-12-06 20:08 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/19163)
* Commit: 768d2e34241454b566cc4d40967bd7cc28898dad

### History
* :broken_heart: [Build #18414](https://buildkite.com/elastic/integrations/builds/18414) failed 47d8c9c60f2e446be2ecfa4b5756f2c141b363f0

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19163","number":19163,"commit":"768d2e34241454b566cc4d40967bd7cc28898dad"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18414","number":18414,"commit":"47d8c9c60f2e446be2ecfa4b5756f2c141b363f0"}],"number":19163}
buildkite-pr-comment-->

2024-12-06 21:17 UTC, merged