Add mailbox_quota_staus and outlook_app_usage datastreams.
elastic/integrations pull request #11687
Opened 2024-11-11 09:28 UTC by ritalwar

- Enhancement

## Proposed commit message

Add mailbox_quota_staus and outlook_app_usage datastreams.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).
- [ ] I have verified that any added dashboard complies with Kibana's [Dashboard good practices](https://docs.elastic.dev/ux-guidelines/data-viz/dashboard-good-practices) 

## How to test this PR locally

## Related issues

- Relates https://github.com/elastic/obs-integration-team/issues/76

## Screenshots

<img width="1063" alt="image" src="https://github.com/user-attachments/assets/dcc62435-2223-49b9-9262-9d107fb24368">

2024-12-02 05:59 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/18944)
* Commit: d598fdcecad1dfa9560ae2ef3da5d7a5e18b5bcb

### Failed CI Steps
* [:white_check_mark: Check go sources](https://buildkite.com/elastic/integrations/builds/18944#019385f1-8fc0-46de-b16c-830ace9b60e0)

### History
* :broken_heart: [Build #18119](https://buildkite.com/elastic/integrations/builds/18119) failed 0242bb6e5319816296af46598c27157a27a9776c

cc @ritalwar

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18944","number":18944,"commit":"d598fdcecad1dfa9560ae2ef3da5d7a5e18b5bcb"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18119","number":18119,"commit":"0242bb6e5319816296af46598c27157a27a9776c"}],"number":18944}
buildkite-pr-comment-->

2024-12-02 06:03 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/18945)
* Commit: dcbf6d03130bb140f9235ddfcab9a11a53533a68

### Failed CI Steps
* [:white_check_mark: Check go sources](https://buildkite.com/elastic/integrations/builds/18945#019385f4-e554-4b20-a3cc-d5e1228a9a33)

### History
* :broken_heart: [Build #18944](https://buildkite.com/elastic/integrations/builds/18944) failed d598fdcecad1dfa9560ae2ef3da5d7a5e18b5bcb
* :broken_heart: [Build #18119](https://buildkite.com/elastic/integrations/builds/18119) failed 0242bb6e5319816296af46598c27157a27a9776c

cc @ritalwar

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18945","number":18945,"commit":"dcbf6d03130bb140f9235ddfcab9a11a53533a68"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18944","number":18944,"commit":"d598fdcecad1dfa9560ae2ef3da5d7a5e18b5bcb"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18119","number":18119,"commit":"0242bb6e5319816296af46598c27157a27a9776c"}],"number":18945}
buildkite-pr-comment-->

2024-12-02 06:19 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/18946)
* Commit: 0cb9e1381e451e9be432743dfba37b7e21b1b860

### Failed CI Steps
* [:white_check_mark: Check go sources](https://buildkite.com/elastic/integrations/builds/18946#01938604-2d7d-460c-a46c-3d8410d4ed78)

### History
* :broken_heart: [Build #18945](https://buildkite.com/elastic/integrations/builds/18945) failed dcbf6d03130bb140f9235ddfcab9a11a53533a68
* :broken_heart: [Build #18944](https://buildkite.com/elastic/integrations/builds/18944) failed d598fdcecad1dfa9560ae2ef3da5d7a5e18b5bcb
* :broken_heart: [Build #18119](https://buildkite.com/elastic/integrations/builds/18119) failed 0242bb6e5319816296af46598c27157a27a9776c

cc @ritalwar

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18946","number":18946,"commit":"0cb9e1381e451e9be432743dfba37b7e21b1b860"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18945","number":18945,"commit":"dcbf6d03130bb140f9235ddfcab9a11a53533a68"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18944","number":18944,"commit":"d598fdcecad1dfa9560ae2ef3da5d7a5e18b5bcb"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18119","number":18119,"commit":"0242bb6e5319816296af46598c27157a27a9776c"}],"number":18946}
buildkite-pr-comment-->

2024-12-02 07:12 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/18949)
* Commit: 2081c3d13c28f14e0540f78485639b08eed01136

### Failed CI Steps
* [Check integrations o365_metrics](https://buildkite.com/elastic/integrations/builds/18949#0193862f-635b-4eed-8dc7-82eca9da0808)

### History
* :broken_heart: [Build #18946](https://buildkite.com/elastic/integrations/builds/18946) failed 0cb9e1381e451e9be432743dfba37b7e21b1b860
* :broken_heart: [Build #18945](https://buildkite.com/elastic/integrations/builds/18945) failed dcbf6d03130bb140f9235ddfcab9a11a53533a68
* :broken_heart: [Build #18944](https://buildkite.com/elastic/integrations/builds/18944) failed d598fdcecad1dfa9560ae2ef3da5d7a5e18b5bcb
* :broken_heart: [Build #18119](https://buildkite.com/elastic/integrations/builds/18119) failed 0242bb6e5319816296af46598c27157a27a9776c

cc @ritalwar

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18949","number":18949,"commit":"2081c3d13c28f14e0540f78485639b08eed01136"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18946","number":18946,"commit":"0cb9e1381e451e9be432743dfba37b7e21b1b860"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18945","number":18945,"commit":"dcbf6d03130bb140f9235ddfcab9a11a53533a68"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18944","number":18944,"commit":"d598fdcecad1dfa9560ae2ef3da5d7a5e18b5bcb"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18119","number":18119,"commit":"0242bb6e5319816296af46598c27157a27a9776c"}],"number":18949}
buildkite-pr-comment-->

2024-12-17 03:46 UTC, ishleenk17 commented
Is this still a valid PR ?

2024-12-17 08:17 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/19593)
* Commit: 6245fbd2e4f2de63685902b5dd5c19a16903380c

### Failed CI Steps
* [Check integrations o365_metrics](https://buildkite.com/elastic/integrations/builds/19593#0193d3ad-7eca-4c6c-ab4f-3965354d4d79)

### History
* :broken_heart: [Build #18949](https://buildkite.com/elastic/integrations/builds/18949) failed 2081c3d13c28f14e0540f78485639b08eed01136
* :broken_heart: [Build #18946](https://buildkite.com/elastic/integrations/builds/18946) failed 0cb9e1381e451e9be432743dfba37b7e21b1b860
* :broken_heart: [Build #18945](https://buildkite.com/elastic/integrations/builds/18945) failed dcbf6d03130bb140f9235ddfcab9a11a53533a68
* :broken_heart: [Build #18944](https://buildkite.com/elastic/integrations/builds/18944) failed d598fdcecad1dfa9560ae2ef3da5d7a5e18b5bcb
* :broken_heart: [Build #18119](https://buildkite.com/elastic/integrations/builds/18119) failed 0242bb6e5319816296af46598c27157a27a9776c

cc @ritalwar

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19593","number":19593,"commit":"6245fbd2e4f2de63685902b5dd5c19a16903380c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18949","number":18949,"commit":"2081c3d13c28f14e0540f78485639b08eed01136"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18946","number":18946,"commit":"0cb9e1381e451e9be432743dfba37b7e21b1b860"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18945","number":18945,"commit":"dcbf6d03130bb140f9235ddfcab9a11a53533a68"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18944","number":18944,"commit":"d598fdcecad1dfa9560ae2ef3da5d7a5e18b5bcb"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18119","number":18119,"commit":"0242bb6e5319816296af46598c27157a27a9776c"}],"number":19593}
buildkite-pr-comment-->

2024-12-19 07:07 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/19696)
* Commit: 4a19251a83ea0ca78a2659c78d51d2442c9d3ebf

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/19696#0193ddbd-6bc8-4b7f-8f40-a8727c2e8554)

### History
* :broken_heart: [Build #19593](https://buildkite.com/elastic/integrations/builds/19593) failed 6245fbd2e4f2de63685902b5dd5c19a16903380c
* :broken_heart: [Build #18949](https://buildkite.com/elastic/integrations/builds/18949) failed 2081c3d13c28f14e0540f78485639b08eed01136
* :broken_heart: [Build #18946](https://buildkite.com/elastic/integrations/builds/18946) failed 0cb9e1381e451e9be432743dfba37b7e21b1b860
* :broken_heart: [Build #18945](https://buildkite.com/elastic/integrations/builds/18945) failed dcbf6d03130bb140f9235ddfcab9a11a53533a68
* :broken_heart: [Build #18944](https://buildkite.com/elastic/integrations/builds/18944) failed d598fdcecad1dfa9560ae2ef3da5d7a5e18b5bcb

cc @ritalwar

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19696","number":19696,"commit":"4a19251a83ea0ca78a2659c78d51d2442c9d3ebf"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19593","number":19593,"commit":"6245fbd2e4f2de63685902b5dd5c19a16903380c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18949","number":18949,"commit":"2081c3d13c28f14e0540f78485639b08eed01136"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18946","number":18946,"commit":"0cb9e1381e451e9be432743dfba37b7e21b1b860"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18945","number":18945,"commit":"dcbf6d03130bb140f9235ddfcab9a11a53533a68"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18944","number":18944,"commit":"d598fdcecad1dfa9560ae2ef3da5d7a5e18b5bcb"}],"number":19696}
buildkite-pr-comment-->

2024-12-19 08:58 UTC, ritalwar commented on packages/o365_metrics/data_stream/mailboxquotastatus/fields/agent.yml
> +  footnote: 'Examples: If Metricbeat is running on an EC2 host and fetches data from its host, the cloud info contains the data about this machine. If Metricbeat runs on a remote machine outside the
I couldn’t find these fields in the [list](https://github.com/elastic/ecs/blob/8.16/generated/csv/fields.csv). Should I check elsewhere to confirm?

2024-12-19 09:16 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/19701)
* Commit: 103abd65b3ccc7d584b4a623f52707bacaf3e242

### History
* :broken_heart: [Build #19696](https://buildkite.com/elastic/integrations/builds/19696) failed 4a19251a83ea0ca78a2659c78d51d2442c9d3ebf
* :broken_heart: [Build #19593](https://buildkite.com/elastic/integrations/builds/19593) failed 6245fbd2e4f2de63685902b5dd5c19a16903380c
* :broken_heart: [Build #18949](https://buildkite.com/elastic/integrations/builds/18949) failed 2081c3d13c28f14e0540f78485639b08eed01136
* :broken_heart: [Build #18946](https://buildkite.com/elastic/integrations/builds/18946) failed 0cb9e1381e451e9be432743dfba37b7e21b1b860
* :broken_heart: [Build #18945](https://buildkite.com/elastic/integrations/builds/18945) failed dcbf6d03130bb140f9235ddfcab9a11a53533a68
* :broken_heart: [Build #18944](https://buildkite.com/elastic/integrations/builds/18944) failed d598fdcecad1dfa9560ae2ef3da5d7a5e18b5bcb

cc @ritalwar

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19701","number":19701,"commit":"103abd65b3ccc7d584b4a623f52707bacaf3e242"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19696","number":19696,"commit":"4a19251a83ea0ca78a2659c78d51d2442c9d3ebf"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19593","number":19593,"commit":"6245fbd2e4f2de63685902b5dd5c19a16903380c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18949","number":18949,"commit":"2081c3d13c28f14e0540f78485639b08eed01136"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18946","number":18946,"commit":"0cb9e1381e451e9be432743dfba37b7e21b1b860"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18945","number":18945,"commit":"dcbf6d03130bb140f9235ddfcab9a11a53533a68"}],"number":19701}
buildkite-pr-comment-->

2024-12-19 09:30 UTC, lucian-ioan commented on packages/o365_metrics/_dev/build/docs/README.md
> +### OutlookActivity
I wonder if those should be written with spaces eg. Outlook Activity. WDYT?

2024-12-19 09:33 UTC, lucian-ioan commented on packages/o365_metrics/data_stream/mailbox_usage/agent/stream/cel.yml.hbs
> +resource.url: https://graph.microsoft.com/v1.0/reports/getMailboxUsageQuotaStatusMailboxCounts(period='D7')
Is there a way to get rid of this since we are using it hardcoded in CEL code?

2024-12-19 09:35 UTC, lucian-ioan commented on packages/o365_metrics/data_stream/outlook_app_usage/_dev/test/pipeline/test-metrics.json
> +  "events": [
Add some values to the test event, even if they are not from the env.

2024-12-19 09:37 UTC, lucian-ioan requested changes
Testing it. Few nits for now.

2024-12-19 10:11 UTC, ritalwar commented on packages/o365_metrics/data_stream/mailbox_usage/agent/stream/cel.yml.hbs
> +resource.url: https://graph.microsoft.com/v1.0/reports/getMailboxUsageQuotaStatusMailboxCounts(period='D7')
Missed it, will update.

2024-12-19 10:36 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/19706)
* Commit: 0d97b5328a897b6d3f98789cbdf4c6ca431256bf

### History
* :green_heart: [Build #19701](https://buildkite.com/elastic/integrations/builds/19701) succeeded 103abd65b3ccc7d584b4a623f52707bacaf3e242
* :broken_heart: [Build #19696](https://buildkite.com/elastic/integrations/builds/19696) failed 4a19251a83ea0ca78a2659c78d51d2442c9d3ebf
* :broken_heart: [Build #19593](https://buildkite.com/elastic/integrations/builds/19593) failed 6245fbd2e4f2de63685902b5dd5c19a16903380c
* :broken_heart: [Build #18949](https://buildkite.com/elastic/integrations/builds/18949) failed 2081c3d13c28f14e0540f78485639b08eed01136
* :broken_heart: [Build #18946](https://buildkite.com/elastic/integrations/builds/18946) failed 0cb9e1381e451e9be432743dfba37b7e21b1b860
* :broken_heart: [Build #18945](https://buildkite.com/elastic/integrations/builds/18945) failed dcbf6d03130bb140f9235ddfcab9a11a53533a68

cc @ritalwar

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19706","number":19706,"commit":"0d97b5328a897b6d3f98789cbdf4c6ca431256bf"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19701","number":19701,"commit":"103abd65b3ccc7d584b4a623f52707bacaf3e242"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19696","number":19696,"commit":"4a19251a83ea0ca78a2659c78d51d2442c9d3ebf"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19593","number":19593,"commit":"6245fbd2e4f2de63685902b5dd5c19a16903380c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18949","number":18949,"commit":"2081c3d13c28f14e0540f78485639b08eed01136"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18946","number":18946,"commit":"0cb9e1381e451e9be432743dfba37b7e21b1b860"}],"number":19706}
buildkite-pr-comment-->

2024-12-24 03:57 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/19793)
* Commit: 70642b0a8732fa8ef7da0ad1a09197da50f7141f

### History
* :green_heart: [Build #19706](https://buildkite.com/elastic/integrations/builds/19706) succeeded 0d97b5328a897b6d3f98789cbdf4c6ca431256bf
* :green_heart: [Build #19701](https://buildkite.com/elastic/integrations/builds/19701) succeeded 103abd65b3ccc7d584b4a623f52707bacaf3e242
* :broken_heart: [Build #19696](https://buildkite.com/elastic/integrations/builds/19696) failed 4a19251a83ea0ca78a2659c78d51d2442c9d3ebf
* :broken_heart: [Build #19593](https://buildkite.com/elastic/integrations/builds/19593) failed 6245fbd2e4f2de63685902b5dd5c19a16903380c
* :broken_heart: [Build #18949](https://buildkite.com/elastic/integrations/builds/18949) failed 2081c3d13c28f14e0540f78485639b08eed01136
* :broken_heart: [Build #18946](https://buildkite.com/elastic/integrations/builds/18946) failed 0cb9e1381e451e9be432743dfba37b7e21b1b860

cc @ritalwar

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19793","number":19793,"commit":"70642b0a8732fa8ef7da0ad1a09197da50f7141f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19706","number":19706,"commit":"0d97b5328a897b6d3f98789cbdf4c6ca431256bf"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19701","number":19701,"commit":"103abd65b3ccc7d584b4a623f52707bacaf3e242"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19696","number":19696,"commit":"4a19251a83ea0ca78a2659c78d51d2442c9d3ebf"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19593","number":19593,"commit":"6245fbd2e4f2de63685902b5dd5c19a16903380c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18949","number":18949,"commit":"2081c3d13c28f14e0540f78485639b08eed01136"}],"number":19793}
buildkite-pr-comment-->

2024-12-24 05:20 UTC, lucian-ioan approved these changes
LGTM

2024-12-24 06:21 UTC, agithomas commented on packages/o365_metrics/data_stream/mailbox_usage/_dev/test/pipeline/test-mailbox-usage-detail.json-expected.json
> +                                "prohibit_send/receive_quota": {
Please try to rename this field `prohibit_send/receive_quota` by removing the `/` character

2024-12-24 06:23 UTC, agithomas commented on packages/o365_metrics/data_stream/mailbox_usage/fields/fields.yml
> +        - name: period
When i look at the sample, it is not clear what `7` represents. So, adding the unit of period in the description will be good. 

```
                                "report": {
                                    "period": "7",
                                    "refresh_date": "2024-12-15"
                                },

```

2024-12-24 06:24 UTC, agithomas commented on packages/o365_metrics/_dev/build/docs/README.md
This section is blank. It will be good to add the version that this integration is tested with. If this is not relevant, kindly remove this section.

2024-12-24 06:26 UTC, agithomas commented on packages/o365_metrics/data_stream/outlook_app_usage/elasticsearch/ingest_pipeline/default.yml
> +
Good to remove this empty line.

2024-12-24 06:28 UTC, agithomas commented on packages/o365_metrics/data_stream/outlook_app_usage/elasticsearch/ingest_pipeline/default.yml
> +on_failure:
Suggestion
```
on_failure:
  - set:
      field: error.message
      value: >-
        Processor '{{{ _ingest.on_failure_processor_type }}}'
        {{{#_ingest.on_failure_processor_tag}}}with tag '{{{ _ingest.on_failure_processor_tag }}}'
        {{{/_ingest.on_failure_processor_tag}}}failed with message '{{{ _ingest.on_failure_message }}}'
```

2024-12-24 06:40 UTC, agithomas commented on packages/o365_metrics/data_stream/outlook_app_usage/elasticsearch/ingest_pipeline/default.yml
> +      ignore_missing: true
Something like below, to avoid a situation we have to keep track of date (2007, 2010, 2013, 2016 etc)


```
- script:
    lang: painless
    source: >
      for (String field : ctx.keySet()) {
        if (field.startsWith('o365.metrics.outlook.app.usage.outlook_') && !field.endsWith('.count')) {
          String targetField = field + '.count';
          ctx[targetField] = ctx.remove(field);
        }
      }

```

2024-12-24 07:22 UTC, ishleenk17 commented
@ritalwar  Are we not looking at the TSDB aspect for these datastreams yet ?

2024-12-24 09:58 UTC, ritalwar commented on packages/o365_metrics/data_stream/outlook_app_usage/elasticsearch/ingest_pipeline/default.yml
> +      ignore_missing: true
I’d like to keep it simple and handle it field by field as needed since this is the API response, and I want to avoid breaking anything if it changes in the future.  

That said, I tried a similar approach in the script, but the behavior was unexpected. Instead of treating the `count` value as a unit, it appended it to the key name. For example, instead of showing:  

```json
"outlook_2007": {
  "count": "5"
}
```

It displayed:  

```json
"outlook_2007.count": 5
```

2024-12-24 09:58 UTC, ritalwar commented on packages/o365_metrics/_dev/build/docs/README.md
> +
Updated!

2024-12-24 09:59 UTC, ritalwar commented on packages/o365_metrics/data_stream/mailbox_usage/manifest.yml
> +        description: How often the API is polled, supports seconds, minutes and hours.
Updated!

2024-12-24 10:00 UTC, ritalwar commented on packages/o365_metrics/data_stream/mailbox_usage/manifest.yml
> +          Specifies the length of time over which the report is aggregated. The supported values for {period} are: D7, D30, D90, and D180.
No! I’ve  also updated the description to prevent any confusion for others.

2024-12-24 10:01 UTC, ritalwar commented on packages/o365_metrics/data_stream/mailbox_usage/manifest.yml
> +        required: true
Copied from another package, but yes, even though we provide a default value, we can make it optional since it’s not being used as a mandatory field.

2024-12-24 10:01 UTC, ritalwar commented on packages/o365_metrics/data_stream/mailbox_usage/elasticsearch/ingest_pipeline/default.yml
> +      field: o365.metrics.mailbox.usage.detail.report_period
No, the response of this API does not return report_date.

2024-12-24 10:05 UTC, ritalwar commented on packages/o365_metrics/docs/README.md
> +| o365.metrics.outlook.activity.report_date | The specific date for which the report data applies. | date |
> Or maybe previosuly we have used report_date for outlook activity and now it is report.date for these datastreams.

Right, Updated to be consistent

2024-12-24 10:06 UTC, ritalwar commented on packages/o365_metrics/data_stream/outlook_app_usage/agent/stream/cel.yml.hbs
> +{{#if resource_retry_wait_min}}
I noticed that these are not currently being used in our script, so I’ve removed them now . I’ll add them back in the future if needed.

2024-12-24 10:08 UTC, ritalwar commented
> 1. Are we not looking at the TSDB aspect for these datastreams yet?
> 2. Also, in general metric_type is missing for the metrics.
We will manage TSDB-related activities separately, including the addition of `metric_type`.

2024-12-24 10:10 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/19806)
* Commit: fa5e1d724ccae1f3e01f8098048ff8555890dfc1

### Failed CI Steps
* [Check integrations o365_metrics](https://buildkite.com/elastic/integrations/builds/19806#0193f819-fa10-4026-bc58-17320cd1e78f)

### History
* :green_heart: [Build #19793](https://buildkite.com/elastic/integrations/builds/19793) succeeded 70642b0a8732fa8ef7da0ad1a09197da50f7141f
* :green_heart: [Build #19706](https://buildkite.com/elastic/integrations/builds/19706) succeeded 0d97b5328a897b6d3f98789cbdf4c6ca431256bf
* :green_heart: [Build #19701](https://buildkite.com/elastic/integrations/builds/19701) succeeded 103abd65b3ccc7d584b4a623f52707bacaf3e242
* :broken_heart: [Build #19696](https://buildkite.com/elastic/integrations/builds/19696) failed 4a19251a83ea0ca78a2659c78d51d2442c9d3ebf
* :broken_heart: [Build #19593](https://buildkite.com/elastic/integrations/builds/19593) failed 6245fbd2e4f2de63685902b5dd5c19a16903380c
* :broken_heart: [Build #18949](https://buildkite.com/elastic/integrations/builds/18949) failed 2081c3d13c28f14e0540f78485639b08eed01136

cc @ritalwar

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19806","number":19806,"commit":"fa5e1d724ccae1f3e01f8098048ff8555890dfc1"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19793","number":19793,"commit":"70642b0a8732fa8ef7da0ad1a09197da50f7141f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19706","number":19706,"commit":"0d97b5328a897b6d3f98789cbdf4c6ca431256bf"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19701","number":19701,"commit":"103abd65b3ccc7d584b4a623f52707bacaf3e242"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19696","number":19696,"commit":"4a19251a83ea0ca78a2659c78d51d2442c9d3ebf"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19593","number":19593,"commit":"6245fbd2e4f2de63685902b5dd5c19a16903380c"}],"number":19806}
buildkite-pr-comment-->

2024-12-24 10:47 UTC, agithomas approved these changes
LGTM!

2024-12-24 14:00 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/19816)
* Commit: b48bf239cb503ef1505b5e860c2b553d4a07f05b

### Failed CI Steps
* [Check integrations o365_metrics](https://buildkite.com/elastic/integrations/builds/19816#0193f8f0-9532-4d46-aec6-6c00d50053dd)

### History
* :broken_heart: [Build #19806](https://buildkite.com/elastic/integrations/builds/19806) failed fa5e1d724ccae1f3e01f8098048ff8555890dfc1
* :green_heart: [Build #19793](https://buildkite.com/elastic/integrations/builds/19793) succeeded 70642b0a8732fa8ef7da0ad1a09197da50f7141f
* :green_heart: [Build #19706](https://buildkite.com/elastic/integrations/builds/19706) succeeded 0d97b5328a897b6d3f98789cbdf4c6ca431256bf
* :green_heart: [Build #19701](https://buildkite.com/elastic/integrations/builds/19701) succeeded 103abd65b3ccc7d584b4a623f52707bacaf3e242
* :broken_heart: [Build #19696](https://buildkite.com/elastic/integrations/builds/19696) failed 4a19251a83ea0ca78a2659c78d51d2442c9d3ebf

cc @ritalwar

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19816","number":19816,"commit":"b48bf239cb503ef1505b5e860c2b553d4a07f05b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19806","number":19806,"commit":"fa5e1d724ccae1f3e01f8098048ff8555890dfc1"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19793","number":19793,"commit":"70642b0a8732fa8ef7da0ad1a09197da50f7141f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19706","number":19706,"commit":"0d97b5328a897b6d3f98789cbdf4c6ca431256bf"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19701","number":19701,"commit":"103abd65b3ccc7d584b4a623f52707bacaf3e242"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19696","number":19696,"commit":"4a19251a83ea0ca78a2659c78d51d2442c9d3ebf"}],"number":19816}
buildkite-pr-comment-->

2024-12-24 16:03 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/19820)
* Commit: 5ab945fee9892c146682071094d4f33491a542ae

### History
* :broken_heart: [Build #19816](https://buildkite.com/elastic/integrations/builds/19816) failed b48bf239cb503ef1505b5e860c2b553d4a07f05b
* :broken_heart: [Build #19806](https://buildkite.com/elastic/integrations/builds/19806) failed fa5e1d724ccae1f3e01f8098048ff8555890dfc1
* :green_heart: [Build #19793](https://buildkite.com/elastic/integrations/builds/19793) succeeded 70642b0a8732fa8ef7da0ad1a09197da50f7141f
* :green_heart: [Build #19706](https://buildkite.com/elastic/integrations/builds/19706) succeeded 0d97b5328a897b6d3f98789cbdf4c6ca431256bf
* :green_heart: [Build #19701](https://buildkite.com/elastic/integrations/builds/19701) succeeded 103abd65b3ccc7d584b4a623f52707bacaf3e242

cc @ritalwar

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19820","number":19820,"commit":"5ab945fee9892c146682071094d4f33491a542ae"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19816","number":19816,"commit":"b48bf239cb503ef1505b5e860c2b553d4a07f05b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19806","number":19806,"commit":"fa5e1d724ccae1f3e01f8098048ff8555890dfc1"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19793","number":19793,"commit":"70642b0a8732fa8ef7da0ad1a09197da50f7141f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19706","number":19706,"commit":"0d97b5328a897b6d3f98789cbdf4c6ca431256bf"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19701","number":19701,"commit":"103abd65b3ccc7d584b4a623f52707bacaf3e242"}],"number":19820}
buildkite-pr-comment-->

2024-12-26 04:08 UTC, merged