Intial release of BeyondTrust Password Safe
elastic/integrations pull request #11710
Opened 2024-11-12 13:29 UTC by HeroicHorizon

## Proposed commit message

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).
- [ ] I have verified that any added dashboard complies with Kibana's [Dashboard good practices](https://docs.elastic.dev/ux-guidelines/data-viz/dashboard-good-practices) 

## Author's Checklist

- [ ] 

## How to test this PR locally

## Related issues

- 

## Screenshots

2024-12-03 19:29 UTC, andrewkroh commented on packages/cybereason/data_stream/poll_malop/agent/stream/cel.yml.hbs
> +{{/if}}
Please undo the changes to the `cybereason` files.

2024-12-09 11:45 UTC, alexwizp commented
/test

2024-12-09 11:49 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/19217)
* Commit: 00d6bfa42ac080835af0abca2c2b6f867b12c73d

### Failed CI Steps
* [:white_check_mark: Check go sources](https://buildkite.com/elastic/integrations/builds/19217#0193ab3e-0de3-4621-90bc-9fe73d6a4eee)

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19217","number":19217,"commit":"00d6bfa42ac080835af0abca2c2b6f867b12c73d"}],"number":19217}
buildkite-pr-comment-->

2024-12-16 12:13 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/useraudit/agent/stream/cel.yml.hbs
> +  			"startdate": [string(state.?cursor.startdate.orValue((now - duration(string(int(int(state.initial_interval)) / 24) + "h")).format(time_layout.RFC3339)))],
initialization of startdate should be done earlier and the value should be given a name. that's because later if we are going to get another page, we need to use the same start date. Maybe do something like:

```
{
  "limit": [...]
  "startdate": [...]
}.as(params,
  	request(
  		"GET",
  		state.url + "/UserAudits?" + params.format_query()
  	)...
)
```
then later it will be available as `params.startdate[0]`

2024-12-16 12:13 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/useraudit/agent/stream/cel.yml.hbs
> +  									"startdate": wantMore ? state.?cursor.startdate.orValue("") : state.?cursor.tempStartDate.orValue(""),
this isn't getting the right startdate. can be fixed with the start date initialization change described above.

2024-12-16 12:14 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/useraudit/agent/stream/cel.yml.hbs
> +  			"startdate": [string(state.?cursor.startdate.orValue((now - duration(string(int(int(state.initial_interval)) / 24) + "h")).format(time_layout.RFC3339)))],
at least one of these conversions is redundant `int(int(state.initial_interval))`

2024-12-16 12:15 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/useraudit/agent/stream/cel.yml.hbs
> +  					string(wantMore ? body.Data[size(body.Data) - 1].CreateDate : "").as(enddate,
if it's a new value, give it a new name: `newEnddate`

2024-12-16 12:16 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/managedaccount/elasticsearch/ingest_pipeline/default.yml
> +      if: ctx.beyondinsight_password_safe.managedaccount?.code == '401'
move this one to the start

2024-12-16 12:16 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/managedaccount/elasticsearch/ingest_pipeline/default.yml
> +      if: ctx.beyondinsight_password_safe.managedaccount?.code == '401'
Also, update the naming as described elsewhere.

2024-12-16 12:19 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/managedaccount/elasticsearch/ingest_pipeline/default.yml
> +      ignore_failure: false
don't ignore failures unless there is a specific reason to expect it to fail.

2024-12-16 12:20 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/managedaccount/elasticsearch/ingest_pipeline/default.yml
> +      formats: ["yyyy-MM-dd'T'HH:mm:ss.SS", "ISO8601"]
use the yaml array style:
```yaml
formats:
  - yyyy-MM-dd'T'HH:mm:ss.SS
  - ISO8601
```

2024-12-16 12:21 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/managedaccount/elasticsearch/ingest_pipeline/default.yml
> +      target_field: "beyondinsight_password_safe.managedaccount.last_change_date"
No need for quotes around these strings.

2024-12-16 12:24 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/managedaccount/elasticsearch/ingest_pipeline/default.yml
> +        }
this shouldn't be needed if they are indexed as keywords, and the right test configuration is set.
example: https://github.com/elastic/integrations/blob/22c30d9f3a9d42495fc78086dbb250e1f363ee8a/packages/tanium/data_stream/threat_response/_dev/test/pipeline/test-common-config.yml#L5-L12

2024-12-16 12:24 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/managedaccount/elasticsearch/ingest_pipeline/default.yml
> +        }
also, when converting to string, it's probably better to use the `convert` processor. Painless isn't necessary here.

2024-12-17 08:26 UTC, HeroicHorizon commented on packages/beyondinsight_password_safe/data_stream/managedaccount/_dev/test/pipeline/test-managedaccount.json
> +                "NextChangeDate": "2024-12-12T00:00:00.0",
his the format of real data from the live system and we have converted to 2024-12-10T08:57:45.900Z format.

2024-12-17 13:56 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/_dev/build/docs/README.md
> +### BeyondInsight integration
Correct the header level

2024-12-17 13:57 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/_dev/build/docs/README.md
> +### Configure API registration ###
Leave off the trailing ` ###`

2024-12-17 13:58 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/_dev/build/docs/README.md
> +Here is an example useraudit document:
This line is redundant, since similar text in provided by `{{event "useraudit"}}`

2024-12-17 14:05 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/_dev/build/docs/README.md
> +{{fields "asset"}}
I see this section's placeholders get replaced with a sample event and field data in the generated README, but the `asset` data stream isn't checked in yet. That will be needed to re-generated the README via `elastic-package`. Also, the current sample event JSON has inconsistent indentation. Perhaps the corresponding `sample_event.json` file needs to be regenerated or at least reformatted.

2024-12-18 10:39 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/useraudit/agent/stream/cel.yml.hbs
> +  			"startdate": [string(state.?cursor.startdate.orValue((now - duration(string(int(int(state.initial_interval)) / 24) + "h")).format(time_layout.RFC3339)))],
extended example...
```
  (
  	(!has(state.cursor) || has(state.cursor) && has(state.cursor.auth_cookie) && state.?cursor.auth_cookie.orValue(null) == null) ?
  		// Authenticating using API to retrieve auth Cookie
  		request("POST", state.url + "/Auth/SignAppin").with(
  			{
  				"Header": {
  					"Authorization": [
  						"PS-Auth key=" + state.apikeytoken + ";runas=" + state.username + ";pwd=[" + state.password + "];",
  					],
  					"Content-Type": ["application/json"],
  				},
  			}
  		).do_request().as(resp,
  			resp.Header["Set-Cookie"].filter(e, e.contains("ASP.NET_SessionId")).as(auth_cookie,
  				auth_cookie[0]
  			)
  		)
  	:
  		state.cursor.auth_cookie
  ).as(auth_cookie,
    {
      "limit": [string(state.limit)],
      "startdate": [string(state.?cursor.startdate.orValue((now - duration(string(int(int(state.initial_interval)) / 24) + "h")).format(time_layout.RFC3339)))],
      "enddate": [string(state.?cursor.enddate.orValue(""))],
    }.as(params,
      request(
        "GET",
        state.url + "/UserAudits?" + params.format_query()
      ).with(
        {
          "Header": {
            "Content-Type": ["application/json"],
            "Cookie": [auth_cookie],
          },
        }
      ).do_request().as(resp,
        (resp.StatusCode == 401) ?
          state.with(
            {
              "events": {"message": {"reason": "User not authenticated", "code": string(resp.StatusCode)}.encode_json()},
              "want_more": true,
              "cursor": {
                "auth_cookie": null,
                "enddate": state.?cursor.enddate.orValue(""),
                "startdate": state.?cursor.startdate.orValue(""),
                "tempStartDate": state.?cursor.tempStartDate.orValue(""),
              },
            }
          )
        :
          bytes(resp.Body).decode_json().as(body,
            bool(size(body.Data) > 0 && state.?cursor.enddate.orValue("") != body.?Data[size(body.Data) - 1].CreateDate.orValue("")).as(wantMore,
              string(wantMore ? body.Data[size(body.Data) - 1].CreateDate : "").as(enddate,
                state.with(
                  {
                    "events": body.Data.map(e,
                      {
                        "message": e,
                        ?"event.original": state.?preserve_original_event.orValue(false) ? optional.of(e.encode_json()) : optional.none(),
                      }
                    ),
                    "want_more": wantMore,
                    "cursor": {
                      "auth_cookie": auth_cookie,
                      "enddate": enddate,
                      "startdate": wantMore ? params.startdate[0] : state.?cursor.tempStartDate.orValue(""),
                      "tempStartDate": (enddate == "") ? string(body.Data[0].CreateDate) : state.?cursor.tempStartDate.orValue(""),
                    },
                  }
                )
              )
            )
          )
      )
    )
  )
```

2025-01-09 19:21 UTC, alexwizp commented
/test

2025-01-09 19:26 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20254)
* Commit: 237de151d17f8970ec349ce20f6e2765bddb19e2

### Failed CI Steps
* [:white_check_mark: Check go sources](https://buildkite.com/elastic/integrations/builds/20254#01944c85-3206-4b7b-9de6-538d7a978b1d)

### History
* :broken_heart: [Build #19217](https://buildkite.com/elastic/integrations/builds/19217) failed 00d6bfa42ac080835af0abca2c2b6f867b12c73d

cc @chrisberkhout

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"running","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20254","number":20254,"commit":"237de151d17f8970ec349ce20f6e2765bddb19e2"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19217","number":19217,"commit":"00d6bfa42ac080835af0abca2c2b6f867b12c73d"}],"number":20254}
buildkite-pr-comment-->

2025-01-09 19:30 UTC, alexwizp commented on packages/beyondinsight_password_safe/_dev/build/docs/README.md
> +### BeyondInsight integration
- [ ] Not fixed

2025-01-09 19:30 UTC, alexwizp commented on packages/beyondinsight_password_safe/_dev/build/docs/README.md
> +### Configure API registration ###
- [ ] Not fixed

2025-01-09 19:32 UTC, alexwizp commented on packages/beyondinsight_password_safe/changelog.yml
> +# newer versions go on top
- [ ] Please remove extra comment

2025-01-09 19:41 UTC, alexwizp commented on packages/beyondinsight_password_safe/data_stream/asset/agent/stream/cel.yml.hbs
> +  									"message": "Workgroups fetched successfully",
- [ ]  we don't need to push into elastic extra messages.

2025-01-09 19:42 UTC, alexwizp commented on packages/beyondinsight_password_safe/data_stream/asset/agent/stream/cel.yml.hbs
> +  								"auth_cookie": auth_cookie,
- [ ] let's set to null auth_cookie. That case this block will also handle auth error

2025-01-09 19:44 UTC, alexwizp commented on packages/beyondinsight_password_safe/data_stream/useraudit/manifest.yml
> +    title: "Collect BeyondInsight User Audit Events"
- [] extra ", please check all similar places

2025-01-09 19:46 UTC, alexwizp commented on packages/beyondinsight_password_safe/data_stream/useraudit/manifest.yml
> +title: "BeyondInsight User Audit Events"
- [] Please compare title with other ones. It looks different. Please think about splitting product name from data stream name.

2025-01-09 19:50 UTC, alexwizp commented on packages/beyondinsight_password_safe/manifest.yml
> +            title: URL of BeyondInsight Events API Server
- [ ] - please fix all titles and descriptions within that file and other ones. We need to be more consistent in naming, use a single style, notation across all files.

2025-01-09 19:53 UTC, alexwizp commented
- [ ] Error: there is no owner for "packages/beyondinsight_password_safe" in ".github/CODEOWNERS"

2025-01-09 20:03 UTC, alexwizp commented on packages/beyondinsight_password_safe/data_stream/asset/agent/stream/cel.yml.hbs
> +  		// Fetching all workgroups because no assets are left to fetch
- [ ] this comment confuse.

2025-01-09 20:13 UTC, alexwizp requested changes
Needs cleanup

2025-01-09 20:24 UTC, alexwizp commented on packages/beyondinsight_password_safe/data_stream/asset/agent/stream/cel.yml.hbs
> +  									"want_more": int(size(r.rest_workgroups)) > 0,
- [ ] just interesting. size.fn should already return numeric value, do we need to cast into int after that?

2025-01-09 20:32 UTC, alexwizp commented on packages/beyondinsight_password_safe/_dev/deploy/docker/files/config.yml
> +rules:
- [ ] I see pagination not implemente and comment "why" not added. If  mocking a separate responses not possible like e.g. `side_effect = ['a response', 'b response', 'c response']` comment about that should be added.

2025-01-10 07:59 UTC, HeroicHorizon commented
/test

2025-01-10 08:57 UTC, HeroicHorizon commented
/test

2025-01-10 09:52 UTC, chrisberkhout commented
/test

2025-01-10 09:55 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20275)
* Commit: 966a6f8af0a72181f5705f52c72ebf1e35cdea8c

### Failed CI Steps
* [:white_check_mark: Check go sources](https://buildkite.com/elastic/integrations/builds/20275#01944fa2-1f7e-495c-8278-25ebbc7e58b2)

### History
* :broken_heart: [Build #20254](https://buildkite.com/elastic/integrations/builds/20254) failed 237de151d17f8970ec349ce20f6e2765bddb19e2
* :broken_heart: [Build #19217](https://buildkite.com/elastic/integrations/builds/19217) failed 00d6bfa42ac080835af0abca2c2b6f867b12c73d

cc @chrisberkhout

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20275","number":20275,"commit":"966a6f8af0a72181f5705f52c72ebf1e35cdea8c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20254","number":20254,"commit":"237de151d17f8970ec349ce20f6e2765bddb19e2"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19217","number":19217,"commit":"00d6bfa42ac080835af0abca2c2b6f867b12c73d"}],"number":20275}
buildkite-pr-comment-->

2025-01-13 09:30 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20332)
* Commit: 7bdaaa5647c86c74950dd1d79cfb5db406977c14

### Failed CI Steps
* [Check integrations beyondinsight_password_safe](https://buildkite.com/elastic/integrations/builds/20332#01945efb-9b28-4281-8b12-712d13cb4d11)

### History
* :broken_heart: [Build #20275](https://buildkite.com/elastic/integrations/builds/20275) failed 966a6f8af0a72181f5705f52c72ebf1e35cdea8c
* :broken_heart: [Build #20254](https://buildkite.com/elastic/integrations/builds/20254) failed 237de151d17f8970ec349ce20f6e2765bddb19e2
* :broken_heart: [Build #19217](https://buildkite.com/elastic/integrations/builds/19217) failed 00d6bfa42ac080835af0abca2c2b6f867b12c73d

cc @chrisberkhout

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20332","number":20332,"commit":"7bdaaa5647c86c74950dd1d79cfb5db406977c14"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20275","number":20275,"commit":"966a6f8af0a72181f5705f52c72ebf1e35cdea8c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20254","number":20254,"commit":"237de151d17f8970ec349ce20f6e2765bddb19e2"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19217","number":19217,"commit":"00d6bfa42ac080835af0abca2c2b6f867b12c73d"}],"number":20332}
buildkite-pr-comment-->

2025-01-13 09:43 UTC, alexwizp commented
/test

2025-01-13 09:43 UTC, HeroicHorizon commented
/test

2025-01-13 11:00 UTC, HeroicHorizon commented
/test

2025-01-13 11:08 UTC, alexwizp commented
/test

2025-01-13 11:30 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20350)
* Commit: 6325be19d27330335ca07fe95564608e8fc57c05

### History
* :broken_heart: [Build #20334](https://buildkite.com/elastic/integrations/builds/20334) failed 6fc535c0533075e5888d0a4e4ecd613278597c87
* :broken_heart: [Build #20332](https://buildkite.com/elastic/integrations/builds/20332) failed 7bdaaa5647c86c74950dd1d79cfb5db406977c14
* :broken_heart: [Build #20275](https://buildkite.com/elastic/integrations/builds/20275) failed 966a6f8af0a72181f5705f52c72ebf1e35cdea8c
* :broken_heart: [Build #20254](https://buildkite.com/elastic/integrations/builds/20254) failed 237de151d17f8970ec349ce20f6e2765bddb19e2
* :broken_heart: [Build #19217](https://buildkite.com/elastic/integrations/builds/19217) failed 00d6bfa42ac080835af0abca2c2b6f867b12c73d

cc @chrisberkhout

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20350","number":20350,"commit":"6325be19d27330335ca07fe95564608e8fc57c05"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20334","number":20334,"commit":"6fc535c0533075e5888d0a4e4ecd613278597c87"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20332","number":20332,"commit":"7bdaaa5647c86c74950dd1d79cfb5db406977c14"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20275","number":20275,"commit":"966a6f8af0a72181f5705f52c72ebf1e35cdea8c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20254","number":20254,"commit":"237de151d17f8970ec349ce20f6e2765bddb19e2"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19217","number":19217,"commit":"00d6bfa42ac080835af0abca2c2b6f867b12c73d"}],"number":20350}
buildkite-pr-comment-->

2025-01-15 14:08 UTC, alexwizp commented
/test

2025-01-15 14:09 UTC, alexwizp commented
/test

2025-01-15 14:29 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20440)
* Commit: 71b201b56d5c64116e3672e0d21e24d7a7acb65b

### History
* :green_heart: [Build #20350](https://buildkite.com/elastic/integrations/builds/20350) succeeded 6325be19d27330335ca07fe95564608e8fc57c05
* :broken_heart: [Build #20334](https://buildkite.com/elastic/integrations/builds/20334) failed 6fc535c0533075e5888d0a4e4ecd613278597c87
* :broken_heart: [Build #20332](https://buildkite.com/elastic/integrations/builds/20332) failed 7bdaaa5647c86c74950dd1d79cfb5db406977c14
* :broken_heart: [Build #20275](https://buildkite.com/elastic/integrations/builds/20275) failed 966a6f8af0a72181f5705f52c72ebf1e35cdea8c
* :broken_heart: [Build #20254](https://buildkite.com/elastic/integrations/builds/20254) failed 237de151d17f8970ec349ce20f6e2765bddb19e2
* :broken_heart: [Build #19217](https://buildkite.com/elastic/integrations/builds/19217) failed 00d6bfa42ac080835af0abca2c2b6f867b12c73d

cc @chrisberkhout

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20440","number":20440,"commit":"71b201b56d5c64116e3672e0d21e24d7a7acb65b"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20350","number":20350,"commit":"6325be19d27330335ca07fe95564608e8fc57c05"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20334","number":20334,"commit":"6fc535c0533075e5888d0a4e4ecd613278597c87"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20332","number":20332,"commit":"7bdaaa5647c86c74950dd1d79cfb5db406977c14"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20275","number":20275,"commit":"966a6f8af0a72181f5705f52c72ebf1e35cdea8c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20254","number":20254,"commit":"237de151d17f8970ec349ce20f6e2765bddb19e2"}],"number":20440}
buildkite-pr-comment-->

2025-01-16 17:54 UTC, chrisberkhout reviewed
I'm not finished reviewing. I just submitting now so the first few comments go through.
I will continue tomorrow.

2025-01-16 17:54 UTC, chrisberkhout commented on .github/CODEOWNERS
> +/packages/beyondinsight_password_safe @elastic/security-service-integrations
Most of this file is in alphabetical order.

- [ ] Please insert this entry near the top in alphabetical order, and ensure it's a 1-line change.

2025-01-16 17:54 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/_dev/deploy/docker/files/config.yml
> +rules:
Not done yet.

2025-01-16 17:54 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/kibana/tag/beyondinsight_password_safe-16cfa47f-7c6f-456d-8525-11ce35775cb8.json
> +{
It's possible to include various Kibana assets in integrations, but usually we avoid adding tags and index patterns / data views.

- [ ] Remove this file.

2025-01-16 17:54 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/manifest.yml
> +  - custom
- [ ] remove `custom`, add `security`

2025-01-16 17:54 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/session/agent/stream/cel.yml.hbs
> +  		state.cursor.auth_cookie
```suggestion
  	(state.?cursor.auth_cooke.orValue(
  		// Authenticating using API to retrieve auth Cookie
  		request("POST", state.url.trim_suffix("/") + "/Auth/SignAppin").with(
  			{
  				"Header": {
  					"Authorization": [
  						"PS-Auth key=" + state.apikeytoken + ";runas=" + state.username + ";pwd=[" + state.password + "];",
  					],
  					"Content-Type": ["application/json"],
  				},
  			}
  		).do_request().as(resp,
  			resp.Header["Set-Cookie"].filter(e, e.contains("ASP.NET_SessionId")).as(auth_cookie,
  				auth_cookie[0]
  			)
  		)
    )
```
- [ ] Get the value in `orValue`.

2025-01-16 17:54 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/managedaccount/agent/stream/cel.yml.hbs
> +resource.ssl.verification_mode: "certificate"
What about the `verification_mode`?
https://www.elastic.co/guide/en/beats/filebeat/current/configuration-ssl.html#client-verification-mode

2025-01-17 10:57 UTC, alexwizp commented
/test

2025-01-17 11:18 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20611)
* Commit: b855f29e1a5176ab7b8fe39b46ae4ec642f65a36

### History
* :green_heart: [Build #20440](https://buildkite.com/elastic/integrations/builds/20440) succeeded 71b201b56d5c64116e3672e0d21e24d7a7acb65b
* :green_heart: [Build #20350](https://buildkite.com/elastic/integrations/builds/20350) succeeded 6325be19d27330335ca07fe95564608e8fc57c05
* :broken_heart: [Build #20334](https://buildkite.com/elastic/integrations/builds/20334) failed 6fc535c0533075e5888d0a4e4ecd613278597c87
* :broken_heart: [Build #20332](https://buildkite.com/elastic/integrations/builds/20332) failed 7bdaaa5647c86c74950dd1d79cfb5db406977c14
* :broken_heart: [Build #20275](https://buildkite.com/elastic/integrations/builds/20275) failed 966a6f8af0a72181f5705f52c72ebf1e35cdea8c
* :broken_heart: [Build #20254](https://buildkite.com/elastic/integrations/builds/20254) failed 237de151d17f8970ec349ce20f6e2765bddb19e2

cc @chrisberkhout

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20611","number":20611,"commit":"b855f29e1a5176ab7b8fe39b46ae4ec642f65a36"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20440","number":20440,"commit":"71b201b56d5c64116e3672e0d21e24d7a7acb65b"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20350","number":20350,"commit":"6325be19d27330335ca07fe95564608e8fc57c05"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20334","number":20334,"commit":"6fc535c0533075e5888d0a4e4ecd613278597c87"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20332","number":20332,"commit":"7bdaaa5647c86c74950dd1d79cfb5db406977c14"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20275","number":20275,"commit":"966a6f8af0a72181f5705f52c72ebf1e35cdea8c"}],"number":20611}
buildkite-pr-comment-->

2025-01-17 17:43 UTC, chrisberkhout requested changes
Here's some more feedback.
I will continue reviewing on Monday.

2025-01-17 17:43 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/useraudit/elasticsearch/ingest_pipeline/default.yml
> +     formats: ["ISO8601"]
You can give an ISO-formatted timestamp to Elasticsearch for a field of `date` type. The create date is already in ISO 8601 format, so you can just copy the value.
```suggestion
  - set:
     field: "@timestamp"
     copy_from: beyondinsight_password_safe.useraudit.create_date
     ignore_empty_value: true
```

2025-01-17 17:43 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/useraudit/elasticsearch/ingest_pipeline/default.yml
> +      target_field: beyondinsight_password_safe.useraudit.ipaddress
```suggestion
```

By default, convert will update the field in-place. `target_field` is optional.

2025-01-17 17:43 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/useraudit/elasticsearch/ingest_pipeline/default.yml
> +
Before the conversion, can you please strip the leading zeros from the ip address.
BeyondTrust returns values like `077.191.192.032`, but I think we should index such a value as `77.191.192.32`. It's automatic for `ip`-typed fields, but for `keyword` fields like `related.hosts`, we need to adjust the string ourselves.

I suggest using the gsub processor and a regular expression, e.g. `\b0+`.

2025-01-17 17:43 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/_dev/build/docs/README.md
> +**pwd**: The RunAs user password surrounded by square brackets `(optional; required only if the User Password is required on the application API registration).`
This should be rewritten from the user perspective. The user doesn't need to know about headers, endpoints or other request details, they need to know about credentials and what things are called in the BeyondInsight UI.

It looks like the URL has changed. This is the correct one (there are identical pages for cloud and on-prem, so we can just use the first one:
https://docs.beyondtrust.com/bips/docs/configure-api

The user should be able to read that page of documentation, and the notes we provide in the README, and quickly set up API credentials.

We should say that we use API key, a username and (if enabled) the user password. We don't use oAuth.

That documentation I linked to doesn't mention it, but I think even for the API key method, it's necessary to associate the user whose username we'll use with the API registration, so we should explain that.

2025-01-17 17:43 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/_dev/build/docs/README.md
> +API registrations allow you to integrate part of the BeyondInsight and Password Safe functionality into your applications, which allows you to expand your application's overall functionality and prov
This explains the BeyondInsight product, not the configuration of the integration.

We need to tell them something like:

> To configure the BeyondInsight and Password Safe integration, a BeyondInsight administrator needs to create an API registration and provide an API key, a username and (depending on configuration) the user's password. In order to create the registration, the administrator may need to know the IP address of the Elastic Agent that will run the integration.

2025-01-21 10:20 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/useraudit/agent/stream/cel.yml.hbs
> +  					"PS-Auth key=" + state.apikey + ";runas=" + state.username + ((state.password != "") ? (";pwd=[" + state.password + "];") : ""),
```suggestion
  					"PS-Auth key=" + state.apikey + ";runas=" + state.username + ((state.?password.orValue("") != "") ? (";pwd=[" + state.password + "];") : ""),
```

I'm not sure if `state.password` will be an empty string or a `null` if that option is not yet. The suggested change handles the null as well.

The other CEL files need this optional pwd change as well.

2025-01-21 10:20 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/session/agent/stream/cel.yml.hbs
> +  		state.cursor.auth_cookie
This one is done everywhere. Thanks.

2025-01-21 10:51 UTC, alexwizp commented
/done

2025-01-21 11:02 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/asset/_dev/test/system/test-default-config.yml
> +  apikeytoken: abcd1234byiapitoken
system tests are failing because `apikeytoken` needs to be renamed to `apikey` in test config as well.

2025-01-21 11:02 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/kibana/tag/beyondinsight_password_safe-16cfa47f-7c6f-456d-8525-11ce35775cb8.json
> +{
Done

2025-01-21 11:11 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/managedaccount/agent/stream/cel.yml.hbs
> +program: |-
System tests are failing for a different reason at the moment.

I'm resolving this one in favor of the other comment about system tests covering pagination logic.

2025-01-21 11:11 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/managedaccount/agent/stream/cel.yml.hbs
> +  	).with(
Interval description is updated.

Interval default setting unchanged, but I'll resolve this one in favor of another comment about that.

2025-01-21 11:15 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/managedsystem/agent/stream/cel.yml.hbs
> +  						"want_more": (state.?cursor.offset.orValue(0) != body.TotalCount) ? true : false,
First suggestion applied.

2025-01-21 11:25 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/_dev/build/docs/README.md
> +### BeyondInsight integration
Now fixed.

2025-01-21 11:25 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/_dev/build/docs/README.md
> +### Configure API registration ###
Now fixed

2025-01-21 11:27 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/changelog.yml
> +# newer versions go on top
Okay to leave this one in the future. It's in most integrations.

2025-01-21 11:30 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/asset/agent/stream/cel.yml.hbs
> +  									"want_more": int(size(r.rest_workgroups)) > 0,
redundant cast now removed.

2025-01-21 11:35 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/manifest.yml
> +            description: This is the API key token you have created on BeyondInsight Password Safe.
Still requires updates to the system test config, but I made another comment about that.

2025-01-21 11:40 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/useraudit/elasticsearch/ingest_pipeline/default.yml
> +
I suggested `drop` by mistake. Thank you for using the `remove` processor!

2025-01-21 12:06 UTC, alexwizp commented
/test

2025-01-21 12:28 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20706)
* Commit: a74463778291b9fe4561b48ea04619fde359bf5c

### History
* :green_heart: [Build #20611](https://buildkite.com/elastic/integrations/builds/20611) succeeded b855f29e1a5176ab7b8fe39b46ae4ec642f65a36
* :green_heart: [Build #20440](https://buildkite.com/elastic/integrations/builds/20440) succeeded 71b201b56d5c64116e3672e0d21e24d7a7acb65b
* :green_heart: [Build #20350](https://buildkite.com/elastic/integrations/builds/20350) succeeded 6325be19d27330335ca07fe95564608e8fc57c05
* :broken_heart: [Build #20334](https://buildkite.com/elastic/integrations/builds/20334) failed 6fc535c0533075e5888d0a4e4ecd613278597c87
* :broken_heart: [Build #20332](https://buildkite.com/elastic/integrations/builds/20332) failed 7bdaaa5647c86c74950dd1d79cfb5db406977c14
* :broken_heart: [Build #20275](https://buildkite.com/elastic/integrations/builds/20275) failed 966a6f8af0a72181f5705f52c72ebf1e35cdea8c

cc @chrisberkhout

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20706","number":20706,"commit":"a74463778291b9fe4561b48ea04619fde359bf5c"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20611","number":20611,"commit":"b855f29e1a5176ab7b8fe39b46ae4ec642f65a36"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20440","number":20440,"commit":"71b201b56d5c64116e3672e0d21e24d7a7acb65b"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20350","number":20350,"commit":"6325be19d27330335ca07fe95564608e8fc57c05"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20334","number":20334,"commit":"6fc535c0533075e5888d0a4e4ecd613278597c87"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20332","number":20332,"commit":"7bdaaa5647c86c74950dd1d79cfb5db406977c14"}],"number":20706}
buildkite-pr-comment-->

2025-01-21 18:26 UTC, chrisberkhout requested changes
These review comments cover the CEL programs.

2025-01-21 18:26 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/useraudit/agent/stream/cel.yml.hbs
> +  					bool(size(body.Data) > 0 && state.?cursor.enddate.orValue(params.enddate[0]) != body.?Data[size(body.Data) - 1].CreateDate.orValue("")).as(wantMore,
* You shouldn't need to wrap this in `bool()` if it's already a boolean value.
* Use the name we gave to the end date param rather than checking the cursor again.
* The `size(body.Data) > 0` condition being true means we don't need the conditional in `body.?Data...`. You can assume an audit entry will have a `CreateDate`.

```suggestion
  					(size(body.Data) > 0 && params.enddate[0] != body.Data[size(body.Data) - 1].CreateDate).as(wantMore,
```

2025-01-21 18:26 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/useraudit/agent/stream/cel.yml.hbs
> +  										"startdate": wantMore ? state.?cursor.startdate.orValue(params.startdate[0]) : state.?cursor.tempStartDate.orValue(""),
Again, use the named value rather than cursor and logic.
```suggestion
  										"startdate": wantMore ? params.startdate[0] : state.?cursor.tempStartDate.orValue(""),
```

2025-01-21 18:26 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/useraudit/agent/stream/cel.yml.hbs
> +  										"tempStartDate": (newEnddate == "") ? string(body.Data[0].CreateDate) : state.?cursor.tempStartDate.orValue(""),
`tempStartDate` should have a better name. Maybe `nextStartDate`?

I checked that this works for the first sequence of pages (by running against the test account and checking the request trace logs).

The logic for finishing one pagination sequence and starting a new one looks either correct or close to correct, but I'm not really sure. I'd like to check it when there's a system test that covers that case.

A special case is what happens when there are no results.

2025-01-21 18:29 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/asset/elasticsearch/ingest_pipeline/default.yml
> +         ctx.beyondinsight_password_safe.asset.ipaddress = ip;
This works but I think the `gsub` method used elsewhere is simpler and may also work for ipv6.

2025-01-21 18:38 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/asset/elasticsearch/ingest_pipeline/default.yml
> +        - beyondinsight_password_safe.asset.AssetID
Please add `LastUpdateDate`, so we get new documents indexed whenever there are updates to an asset.

2025-01-21 18:40 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/managedsystem/elasticsearch/ingest_pipeline/default.yml
> +      target_field: "_id"
Here as well, i think we need to fingerprint all fields to index updates. You can say `beyondinsight_password_safe.managedsystem` and it will cover everything inside that.

2025-01-21 18:43 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/session/elasticsearch/ingest_pipeline/default.yml
> +        - beyondinsight_password_safe.session.SessionID
```suggestion
        - beyondinsight_password_safe.session
```

To index changes when they happen.

2025-01-21 18:43 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/useraudit/elasticsearch/ingest_pipeline/default.yml
> +        - beyondinsight_password_safe.useraudit.AuditID
```suggestion
        - beyondinsight_password_safe.useraudit
```

2025-01-21 18:47 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/managedsystem/elasticsearch/ingest_pipeline/default.yml
> +         ctx.beyondinsight_password_safe.managedsystem.ipaddress = ip;
Again, the `gsub` approach is probably better.

2025-01-21 18:54 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/session/elasticsearch/ingest_pipeline/default.yml
> +        }
This type of script can be rewritten as:

```
  - script:
      description: Convert status to their text meaning using params
      lang: painless
      params:
        descriptions:
          0: "not_started"
          1: "in_progress"
          2: "completed"
          5: "locked"
          7: "terminated"
          8: "logged_off"
          9: "disconnected"
      if: ctx.beyondinsight_password_safe?.session?.status != null
      source: |
        ctx.beyondinsight_password_safe.session.status = params.descriptions.getOrDefault(
          ctx.beyondinsight_password_safe.session.status,
          "unknown"
        );
```

Also the ones below.

2025-01-21 18:55 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/session/elasticsearch/ingest_pipeline/default.yml
> +        }
Shouldn't be necessary if the fields are of type `keyword` and the `numeric_keyword_fields` configuration is used for the tests (see existing examples).

2025-01-21 20:05 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20753)
* Commit: ca5f3a583d3c3159400e611850035b0aeb33bf3f

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/20753#01948a77-4d18-4772-8fd8-7ad0a2a49328)

### History
* :green_heart: [Build #20706](https://buildkite.com/elastic/integrations/builds/20706) succeeded a74463778291b9fe4561b48ea04619fde359bf5c
* :green_heart: [Build #20611](https://buildkite.com/elastic/integrations/builds/20611) succeeded b855f29e1a5176ab7b8fe39b46ae4ec642f65a36
* :green_heart: [Build #20440](https://buildkite.com/elastic/integrations/builds/20440) succeeded 71b201b56d5c64116e3672e0d21e24d7a7acb65b
* :green_heart: [Build #20350](https://buildkite.com/elastic/integrations/builds/20350) succeeded 6325be19d27330335ca07fe95564608e8fc57c05
* :broken_heart: [Build #20334](https://buildkite.com/elastic/integrations/builds/20334) failed 6fc535c0533075e5888d0a4e4ecd613278597c87
* :broken_heart: [Build #20332](https://buildkite.com/elastic/integrations/builds/20332) failed 7bdaaa5647c86c74950dd1d79cfb5db406977c14

cc @chrisberkhout

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20753","number":20753,"commit":"ca5f3a583d3c3159400e611850035b0aeb33bf3f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20706","number":20706,"commit":"a74463778291b9fe4561b48ea04619fde359bf5c"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20611","number":20611,"commit":"b855f29e1a5176ab7b8fe39b46ae4ec642f65a36"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20440","number":20440,"commit":"71b201b56d5c64116e3672e0d21e24d7a7acb65b"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20350","number":20350,"commit":"6325be19d27330335ca07fe95564608e8fc57c05"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20334","number":20334,"commit":"6fc535c0533075e5888d0a4e4ecd613278597c87"}],"number":20753}
buildkite-pr-comment-->

2025-01-21 20:19 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20754)
* Commit: 83f607364cda2821d28528ed19aaae5f471cfe93

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/20754#01948a83-e657-4195-be7d-7311849ec602)

### History
* :broken_heart: [Build #20753](https://buildkite.com/elastic/integrations/builds/20753) failed ca5f3a583d3c3159400e611850035b0aeb33bf3f
* :green_heart: [Build #20706](https://buildkite.com/elastic/integrations/builds/20706) succeeded a74463778291b9fe4561b48ea04619fde359bf5c
* :green_heart: [Build #20611](https://buildkite.com/elastic/integrations/builds/20611) succeeded b855f29e1a5176ab7b8fe39b46ae4ec642f65a36
* :green_heart: [Build #20440](https://buildkite.com/elastic/integrations/builds/20440) succeeded 71b201b56d5c64116e3672e0d21e24d7a7acb65b
* :green_heart: [Build #20350](https://buildkite.com/elastic/integrations/builds/20350) succeeded 6325be19d27330335ca07fe95564608e8fc57c05
* :broken_heart: [Build #20334](https://buildkite.com/elastic/integrations/builds/20334) failed 6fc535c0533075e5888d0a4e4ecd613278597c87

cc @chrisberkhout

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20754","number":20754,"commit":"83f607364cda2821d28528ed19aaae5f471cfe93"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20753","number":20753,"commit":"ca5f3a583d3c3159400e611850035b0aeb33bf3f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20706","number":20706,"commit":"a74463778291b9fe4561b48ea04619fde359bf5c"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20611","number":20611,"commit":"b855f29e1a5176ab7b8fe39b46ae4ec642f65a36"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20440","number":20440,"commit":"71b201b56d5c64116e3672e0d21e24d7a7acb65b"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20350","number":20350,"commit":"6325be19d27330335ca07fe95564608e8fc57c05"}],"number":20754}
buildkite-pr-comment-->

2025-01-21 20:21 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20755)
* Commit: 17cb367ff9a28389bbe7a72a0caae0f609ca389a

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/20755#01948a85-f378-4c00-ad71-b8396c6b5139)

### History
* :broken_heart: [Build #20754](https://buildkite.com/elastic/integrations/builds/20754) failed 83f607364cda2821d28528ed19aaae5f471cfe93
* :broken_heart: [Build #20753](https://buildkite.com/elastic/integrations/builds/20753) failed ca5f3a583d3c3159400e611850035b0aeb33bf3f
* :green_heart: [Build #20706](https://buildkite.com/elastic/integrations/builds/20706) succeeded a74463778291b9fe4561b48ea04619fde359bf5c
* :green_heart: [Build #20611](https://buildkite.com/elastic/integrations/builds/20611) succeeded b855f29e1a5176ab7b8fe39b46ae4ec642f65a36
* :green_heart: [Build #20440](https://buildkite.com/elastic/integrations/builds/20440) succeeded 71b201b56d5c64116e3672e0d21e24d7a7acb65b
* :green_heart: [Build #20350](https://buildkite.com/elastic/integrations/builds/20350) succeeded 6325be19d27330335ca07fe95564608e8fc57c05

cc @chrisberkhout

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20755","number":20755,"commit":"17cb367ff9a28389bbe7a72a0caae0f609ca389a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20754","number":20754,"commit":"83f607364cda2821d28528ed19aaae5f471cfe93"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20753","number":20753,"commit":"ca5f3a583d3c3159400e611850035b0aeb33bf3f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20706","number":20706,"commit":"a74463778291b9fe4561b48ea04619fde359bf5c"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20611","number":20611,"commit":"b855f29e1a5176ab7b8fe39b46ae4ec642f65a36"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20440","number":20440,"commit":"71b201b56d5c64116e3672e0d21e24d7a7acb65b"}],"number":20755}
buildkite-pr-comment-->

2025-01-21 20:58 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20756)
* Commit: 654aadb607230833efdb2934dfc210d0cf7d8a98

### Failed CI Steps
* [Check integrations beyondinsight_password_safe](https://buildkite.com/elastic/integrations/builds/20756#01948aa0-d2ec-439a-9525-c454e5989be9)

### History
* :broken_heart: [Build #20755](https://buildkite.com/elastic/integrations/builds/20755) failed 17cb367ff9a28389bbe7a72a0caae0f609ca389a
* :broken_heart: [Build #20754](https://buildkite.com/elastic/integrations/builds/20754) failed 83f607364cda2821d28528ed19aaae5f471cfe93
* :broken_heart: [Build #20753](https://buildkite.com/elastic/integrations/builds/20753) failed ca5f3a583d3c3159400e611850035b0aeb33bf3f
* :green_heart: [Build #20706](https://buildkite.com/elastic/integrations/builds/20706) succeeded a74463778291b9fe4561b48ea04619fde359bf5c
* :green_heart: [Build #20611](https://buildkite.com/elastic/integrations/builds/20611) succeeded b855f29e1a5176ab7b8fe39b46ae4ec642f65a36
* :green_heart: [Build #20440](https://buildkite.com/elastic/integrations/builds/20440) succeeded 71b201b56d5c64116e3672e0d21e24d7a7acb65b

cc @chrisberkhout

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20756","number":20756,"commit":"654aadb607230833efdb2934dfc210d0cf7d8a98"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20755","number":20755,"commit":"17cb367ff9a28389bbe7a72a0caae0f609ca389a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20754","number":20754,"commit":"83f607364cda2821d28528ed19aaae5f471cfe93"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20753","number":20753,"commit":"ca5f3a583d3c3159400e611850035b0aeb33bf3f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20706","number":20706,"commit":"a74463778291b9fe4561b48ea04619fde359bf5c"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20611","number":20611,"commit":"b855f29e1a5176ab7b8fe39b46ae4ec642f65a36"}],"number":20756}
buildkite-pr-comment-->

2025-01-22 07:44 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20772)
* Commit: 8c948dda2175787fad35ce6653ddf79beeabc1f6

### Failed CI Steps
* [Check integrations beyondinsight_password_safe](https://buildkite.com/elastic/integrations/builds/20772#01948cf0-7b9f-4a45-a126-74acb6890809)

### History
* :broken_heart: [Build #20756](https://buildkite.com/elastic/integrations/builds/20756) failed 654aadb607230833efdb2934dfc210d0cf7d8a98
* :broken_heart: [Build #20755](https://buildkite.com/elastic/integrations/builds/20755) failed 17cb367ff9a28389bbe7a72a0caae0f609ca389a
* :broken_heart: [Build #20754](https://buildkite.com/elastic/integrations/builds/20754) failed 83f607364cda2821d28528ed19aaae5f471cfe93
* :broken_heart: [Build #20753](https://buildkite.com/elastic/integrations/builds/20753) failed ca5f3a583d3c3159400e611850035b0aeb33bf3f
* :green_heart: [Build #20706](https://buildkite.com/elastic/integrations/builds/20706) succeeded a74463778291b9fe4561b48ea04619fde359bf5c

cc @chrisberkhout

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20772","number":20772,"commit":"8c948dda2175787fad35ce6653ddf79beeabc1f6"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20756","number":20756,"commit":"654aadb607230833efdb2934dfc210d0cf7d8a98"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20755","number":20755,"commit":"17cb367ff9a28389bbe7a72a0caae0f609ca389a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20754","number":20754,"commit":"83f607364cda2821d28528ed19aaae5f471cfe93"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20753","number":20753,"commit":"ca5f3a583d3c3159400e611850035b0aeb33bf3f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20706","number":20706,"commit":"a74463778291b9fe4561b48ea04619fde359bf5c"}],"number":20772}
buildkite-pr-comment-->

2025-01-22 08:41 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20775)
* Commit: 02fddb6ef17174ec788e779f1832a597290226ac

### History
* :broken_heart: [Build #20772](https://buildkite.com/elastic/integrations/builds/20772) failed 8c948dda2175787fad35ce6653ddf79beeabc1f6
* :broken_heart: [Build #20756](https://buildkite.com/elastic/integrations/builds/20756) failed 654aadb607230833efdb2934dfc210d0cf7d8a98
* :broken_heart: [Build #20755](https://buildkite.com/elastic/integrations/builds/20755) failed 17cb367ff9a28389bbe7a72a0caae0f609ca389a
* :broken_heart: [Build #20754](https://buildkite.com/elastic/integrations/builds/20754) failed 83f607364cda2821d28528ed19aaae5f471cfe93
* :broken_heart: [Build #20753](https://buildkite.com/elastic/integrations/builds/20753) failed ca5f3a583d3c3159400e611850035b0aeb33bf3f

cc @chrisberkhout

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20775","number":20775,"commit":"02fddb6ef17174ec788e779f1832a597290226ac"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20772","number":20772,"commit":"8c948dda2175787fad35ce6653ddf79beeabc1f6"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20756","number":20756,"commit":"654aadb607230833efdb2934dfc210d0cf7d8a98"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20755","number":20755,"commit":"17cb367ff9a28389bbe7a72a0caae0f609ca389a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20754","number":20754,"commit":"83f607364cda2821d28528ed19aaae5f471cfe93"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20753","number":20753,"commit":"ca5f3a583d3c3159400e611850035b0aeb33bf3f"}],"number":20775}
buildkite-pr-comment-->

2025-01-22 09:06 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/asset/elasticsearch/ingest_pipeline/default.yml
> +      allow_duplicates: false
Run `geoip` on `host.ip` after setting `host.ip`.

(the other data streams don't have this problem)

2025-01-22 10:10 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20782)
* Commit: 1b2e461b189b274659625690d6ad76f9168b4b2f

### History
* :green_heart: [Build #20777](https://buildkite.com/elastic/integrations/builds/20777) succeeded f6ec1da9d4774b8dc09b61a90523cb19b9fbf0f0
* :green_heart: [Build #20775](https://buildkite.com/elastic/integrations/builds/20775) succeeded 02fddb6ef17174ec788e779f1832a597290226ac
* :broken_heart: [Build #20772](https://buildkite.com/elastic/integrations/builds/20772) failed 8c948dda2175787fad35ce6653ddf79beeabc1f6
* :broken_heart: [Build #20756](https://buildkite.com/elastic/integrations/builds/20756) failed 654aadb607230833efdb2934dfc210d0cf7d8a98
* :broken_heart: [Build #20755](https://buildkite.com/elastic/integrations/builds/20755) failed 17cb367ff9a28389bbe7a72a0caae0f609ca389a
* :broken_heart: [Build #20754](https://buildkite.com/elastic/integrations/builds/20754) failed 83f607364cda2821d28528ed19aaae5f471cfe93

cc @chrisberkhout

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20782","number":20782,"commit":"1b2e461b189b274659625690d6ad76f9168b4b2f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20777","number":20777,"commit":"f6ec1da9d4774b8dc09b61a90523cb19b9fbf0f0"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20775","number":20775,"commit":"02fddb6ef17174ec788e779f1832a597290226ac"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20772","number":20772,"commit":"8c948dda2175787fad35ce6653ddf79beeabc1f6"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20756","number":20756,"commit":"654aadb607230833efdb2934dfc210d0cf7d8a98"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20755","number":20755,"commit":"17cb367ff9a28389bbe7a72a0caae0f609ca389a"}],"number":20782}
buildkite-pr-comment-->

2025-01-22 11:01 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20785)
* Commit: 137f5b50926e83b026d6ec33714a5f2c11f02ede

### History
* :green_heart: [Build #20782](https://buildkite.com/elastic/integrations/builds/20782) succeeded 1b2e461b189b274659625690d6ad76f9168b4b2f
* :green_heart: [Build #20777](https://buildkite.com/elastic/integrations/builds/20777) succeeded f6ec1da9d4774b8dc09b61a90523cb19b9fbf0f0
* :green_heart: [Build #20775](https://buildkite.com/elastic/integrations/builds/20775) succeeded 02fddb6ef17174ec788e779f1832a597290226ac
* :broken_heart: [Build #20772](https://buildkite.com/elastic/integrations/builds/20772) failed 8c948dda2175787fad35ce6653ddf79beeabc1f6
* :broken_heart: [Build #20756](https://buildkite.com/elastic/integrations/builds/20756) failed 654aadb607230833efdb2934dfc210d0cf7d8a98
* :broken_heart: [Build #20755](https://buildkite.com/elastic/integrations/builds/20755) failed 17cb367ff9a28389bbe7a72a0caae0f609ca389a

cc @chrisberkhout

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20785","number":20785,"commit":"137f5b50926e83b026d6ec33714a5f2c11f02ede"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20782","number":20782,"commit":"1b2e461b189b274659625690d6ad76f9168b4b2f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20777","number":20777,"commit":"f6ec1da9d4774b8dc09b61a90523cb19b9fbf0f0"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20775","number":20775,"commit":"02fddb6ef17174ec788e779f1832a597290226ac"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20772","number":20772,"commit":"8c948dda2175787fad35ce6653ddf79beeabc1f6"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20756","number":20756,"commit":"654aadb607230833efdb2934dfc210d0cf7d8a98"}],"number":20785}
buildkite-pr-comment-->

2025-01-22 11:16 UTC, ravikumar5555 commented on packages/beyondinsight_password_safe/data_stream/session/elasticsearch/ingest_pipeline/default.yml
> +        }
if i try params key as numeric value then i was getting some error
so I have used convert processor to convert numeric to int and then used "0" insetad of 0

2025-01-22 11:32 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20792)
* Commit: 016298ea7848ba80a42aaf7d16cfb4216ed64e59

### Failed CI Steps
* [Check integrations beyondinsight_password_safe](https://buildkite.com/elastic/integrations/builds/20792#01948dc0-cb3b-4593-9881-843c8d673814)

### History
* :green_heart: [Build #20785](https://buildkite.com/elastic/integrations/builds/20785) succeeded 137f5b50926e83b026d6ec33714a5f2c11f02ede
* :green_heart: [Build #20782](https://buildkite.com/elastic/integrations/builds/20782) succeeded 1b2e461b189b274659625690d6ad76f9168b4b2f
* :green_heart: [Build #20777](https://buildkite.com/elastic/integrations/builds/20777) succeeded f6ec1da9d4774b8dc09b61a90523cb19b9fbf0f0
* :green_heart: [Build #20775](https://buildkite.com/elastic/integrations/builds/20775) succeeded 02fddb6ef17174ec788e779f1832a597290226ac
* :broken_heart: [Build #20772](https://buildkite.com/elastic/integrations/builds/20772) failed 8c948dda2175787fad35ce6653ddf79beeabc1f6
* :broken_heart: [Build #20756](https://buildkite.com/elastic/integrations/builds/20756) failed 654aadb607230833efdb2934dfc210d0cf7d8a98

cc @chrisberkhout

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20792","number":20792,"commit":"016298ea7848ba80a42aaf7d16cfb4216ed64e59"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20785","number":20785,"commit":"137f5b50926e83b026d6ec33714a5f2c11f02ede"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20782","number":20782,"commit":"1b2e461b189b274659625690d6ad76f9168b4b2f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20777","number":20777,"commit":"f6ec1da9d4774b8dc09b61a90523cb19b9fbf0f0"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20775","number":20775,"commit":"02fddb6ef17174ec788e779f1832a597290226ac"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20772","number":20772,"commit":"8c948dda2175787fad35ce6653ddf79beeabc1f6"}],"number":20792}
buildkite-pr-comment-->

2025-01-22 11:50 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20796)
* Commit: 1398e05d0136e3dd81e9d5806456e3fd03918435

### Failed CI Steps
* [Check integrations beyondinsight_password_safe](https://buildkite.com/elastic/integrations/builds/20796#01948dd1-c8fc-41a6-8ac4-737f9ae1e763)

### History
* :broken_heart: [Build #20792](https://buildkite.com/elastic/integrations/builds/20792) failed 016298ea7848ba80a42aaf7d16cfb4216ed64e59
* :green_heart: [Build #20785](https://buildkite.com/elastic/integrations/builds/20785) succeeded 137f5b50926e83b026d6ec33714a5f2c11f02ede
* :green_heart: [Build #20782](https://buildkite.com/elastic/integrations/builds/20782) succeeded 1b2e461b189b274659625690d6ad76f9168b4b2f
* :green_heart: [Build #20777](https://buildkite.com/elastic/integrations/builds/20777) succeeded f6ec1da9d4774b8dc09b61a90523cb19b9fbf0f0
* :green_heart: [Build #20775](https://buildkite.com/elastic/integrations/builds/20775) succeeded 02fddb6ef17174ec788e779f1832a597290226ac
* :broken_heart: [Build #20772](https://buildkite.com/elastic/integrations/builds/20772) failed 8c948dda2175787fad35ce6653ddf79beeabc1f6

cc @chrisberkhout

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20796","number":20796,"commit":"1398e05d0136e3dd81e9d5806456e3fd03918435"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20792","number":20792,"commit":"016298ea7848ba80a42aaf7d16cfb4216ed64e59"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20785","number":20785,"commit":"137f5b50926e83b026d6ec33714a5f2c11f02ede"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20782","number":20782,"commit":"1b2e461b189b274659625690d6ad76f9168b4b2f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20777","number":20777,"commit":"f6ec1da9d4774b8dc09b61a90523cb19b9fbf0f0"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20775","number":20775,"commit":"02fddb6ef17174ec788e779f1832a597290226ac"}],"number":20796}
buildkite-pr-comment-->

2025-01-22 12:58 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20801)
* Commit: 307af44eb598d6cf43c1f97608541d06e26ec90a

### Failed CI Steps
* [Check integrations beyondinsight_password_safe](https://buildkite.com/elastic/integrations/builds/20801#01948e13-2343-4c4b-9a6e-91a26fd20b80)

### History
* :broken_heart: [Build #20796](https://buildkite.com/elastic/integrations/builds/20796) failed 1398e05d0136e3dd81e9d5806456e3fd03918435
* :broken_heart: [Build #20792](https://buildkite.com/elastic/integrations/builds/20792) failed 016298ea7848ba80a42aaf7d16cfb4216ed64e59
* :green_heart: [Build #20785](https://buildkite.com/elastic/integrations/builds/20785) succeeded 137f5b50926e83b026d6ec33714a5f2c11f02ede
* :green_heart: [Build #20782](https://buildkite.com/elastic/integrations/builds/20782) succeeded 1b2e461b189b274659625690d6ad76f9168b4b2f
* :green_heart: [Build #20777](https://buildkite.com/elastic/integrations/builds/20777) succeeded f6ec1da9d4774b8dc09b61a90523cb19b9fbf0f0

cc @chrisberkhout

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20801","number":20801,"commit":"307af44eb598d6cf43c1f97608541d06e26ec90a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20796","number":20796,"commit":"1398e05d0136e3dd81e9d5806456e3fd03918435"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20792","number":20792,"commit":"016298ea7848ba80a42aaf7d16cfb4216ed64e59"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20785","number":20785,"commit":"137f5b50926e83b026d6ec33714a5f2c11f02ede"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20782","number":20782,"commit":"1b2e461b189b274659625690d6ad76f9168b4b2f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20777","number":20777,"commit":"f6ec1da9d4774b8dc09b61a90523cb19b9fbf0f0"}],"number":20801}
buildkite-pr-comment-->

2025-01-22 16:25 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20809)
* Commit: 4de97f036365c256f0e29da55bde6c894cf01a94

### History
* :broken_heart: [Build #20801](https://buildkite.com/elastic/integrations/builds/20801) failed 307af44eb598d6cf43c1f97608541d06e26ec90a
* :broken_heart: [Build #20796](https://buildkite.com/elastic/integrations/builds/20796) failed 1398e05d0136e3dd81e9d5806456e3fd03918435
* :broken_heart: [Build #20792](https://buildkite.com/elastic/integrations/builds/20792) failed 016298ea7848ba80a42aaf7d16cfb4216ed64e59
* :green_heart: [Build #20785](https://buildkite.com/elastic/integrations/builds/20785) succeeded 137f5b50926e83b026d6ec33714a5f2c11f02ede
* :green_heart: [Build #20782](https://buildkite.com/elastic/integrations/builds/20782) succeeded 1b2e461b189b274659625690d6ad76f9168b4b2f

cc @chrisberkhout

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20809","number":20809,"commit":"4de97f036365c256f0e29da55bde6c894cf01a94"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20801","number":20801,"commit":"307af44eb598d6cf43c1f97608541d06e26ec90a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20796","number":20796,"commit":"1398e05d0136e3dd81e9d5806456e3fd03918435"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20792","number":20792,"commit":"016298ea7848ba80a42aaf7d16cfb4216ed64e59"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20785","number":20785,"commit":"137f5b50926e83b026d6ec33714a5f2c11f02ede"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20782","number":20782,"commit":"1b2e461b189b274659625690d6ad76f9168b4b2f"}],"number":20809}
buildkite-pr-comment-->

2025-01-22 18:06 UTC, chrisberkhout requested changes
Dashboard review:

Later when dashboards are finalized, the dashboard screenshots included in the package should be updated. The more interesting the data looks, the better.

Overview:
![dashboard - overview - with notes](https://github.com/user-attachments/assets/6524be66-82a1-4447-b082-4d6f4afbf5bb)

Session and assets:
![dashboard - sessions and assets - with notes](https://github.com/user-attachments/assets/c1afac75-962d-4890-a306-e1b873ece3d7)

2025-01-22 18:08 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/session/elasticsearch/ingest_pipeline/default.yml
> +
Please populate the `related.*` fields where possible (already done for other data streams).

2025-01-23 10:06 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20842)
* Commit: 0b41ad94eef12589de5b38470e3e47b3c9e7952c

### History
* :green_heart: [Build #20809](https://buildkite.com/elastic/integrations/builds/20809) succeeded 4de97f036365c256f0e29da55bde6c894cf01a94
* :broken_heart: [Build #20801](https://buildkite.com/elastic/integrations/builds/20801) failed 307af44eb598d6cf43c1f97608541d06e26ec90a
* :broken_heart: [Build #20796](https://buildkite.com/elastic/integrations/builds/20796) failed 1398e05d0136e3dd81e9d5806456e3fd03918435
* :broken_heart: [Build #20792](https://buildkite.com/elastic/integrations/builds/20792) failed 016298ea7848ba80a42aaf7d16cfb4216ed64e59
* :green_heart: [Build #20785](https://buildkite.com/elastic/integrations/builds/20785) succeeded 137f5b50926e83b026d6ec33714a5f2c11f02ede
* :green_heart: [Build #20782](https://buildkite.com/elastic/integrations/builds/20782) succeeded 1b2e461b189b274659625690d6ad76f9168b4b2f

cc @chrisberkhout

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20842","number":20842,"commit":"0b41ad94eef12589de5b38470e3e47b3c9e7952c"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20809","number":20809,"commit":"4de97f036365c256f0e29da55bde6c894cf01a94"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20801","number":20801,"commit":"307af44eb598d6cf43c1f97608541d06e26ec90a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20796","number":20796,"commit":"1398e05d0136e3dd81e9d5806456e3fd03918435"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20792","number":20792,"commit":"016298ea7848ba80a42aaf7d16cfb4216ed64e59"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20785","number":20785,"commit":"137f5b50926e83b026d6ec33714a5f2c11f02ede"}],"number":20842}
buildkite-pr-comment-->

2025-01-23 13:54 UTC, alexwizp commented
/test

2025-01-23 21:14 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20879)
* Commit: d3c4fe0230db747cb592702fa0b58e660c857c32

### Failed CI Steps
* [Check integrations beyondinsight_password_safe](https://buildkite.com/elastic/integrations/builds/20879#019494fc-bddd-4b61-ac0c-003045fe4060)

### History
* :green_heart: [Build #20855](https://buildkite.com/elastic/integrations/builds/20855) succeeded a5d8651094167f783ee8260689b08fd0e78054ce
* :green_heart: [Build #20842](https://buildkite.com/elastic/integrations/builds/20842) succeeded 0b41ad94eef12589de5b38470e3e47b3c9e7952c
* :green_heart: [Build #20809](https://buildkite.com/elastic/integrations/builds/20809) succeeded 4de97f036365c256f0e29da55bde6c894cf01a94
* :broken_heart: [Build #20801](https://buildkite.com/elastic/integrations/builds/20801) failed 307af44eb598d6cf43c1f97608541d06e26ec90a
* :broken_heart: [Build #20796](https://buildkite.com/elastic/integrations/builds/20796) failed 1398e05d0136e3dd81e9d5806456e3fd03918435
* :broken_heart: [Build #20792](https://buildkite.com/elastic/integrations/builds/20792) failed 016298ea7848ba80a42aaf7d16cfb4216ed64e59

cc @chrisberkhout

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20879","number":20879,"commit":"d3c4fe0230db747cb592702fa0b58e660c857c32"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20855","number":20855,"commit":"a5d8651094167f783ee8260689b08fd0e78054ce"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20842","number":20842,"commit":"0b41ad94eef12589de5b38470e3e47b3c9e7952c"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20809","number":20809,"commit":"4de97f036365c256f0e29da55bde6c894cf01a94"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20801","number":20801,"commit":"307af44eb598d6cf43c1f97608541d06e26ec90a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20796","number":20796,"commit":"1398e05d0136e3dd81e9d5806456e3fd03918435"}],"number":20879}
buildkite-pr-comment-->

2025-01-23 21:43 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20882)
* Commit: 9b04bf82ed7f27c7a830dae5fd8afe670897004b

### History
* :broken_heart: [Build #20879](https://buildkite.com/elastic/integrations/builds/20879) failed d3c4fe0230db747cb592702fa0b58e660c857c32
* :green_heart: [Build #20855](https://buildkite.com/elastic/integrations/builds/20855) succeeded a5d8651094167f783ee8260689b08fd0e78054ce
* :green_heart: [Build #20842](https://buildkite.com/elastic/integrations/builds/20842) succeeded 0b41ad94eef12589de5b38470e3e47b3c9e7952c
* :green_heart: [Build #20809](https://buildkite.com/elastic/integrations/builds/20809) succeeded 4de97f036365c256f0e29da55bde6c894cf01a94
* :broken_heart: [Build #20801](https://buildkite.com/elastic/integrations/builds/20801) failed 307af44eb598d6cf43c1f97608541d06e26ec90a

cc @chrisberkhout

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20882","number":20882,"commit":"9b04bf82ed7f27c7a830dae5fd8afe670897004b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20879","number":20879,"commit":"d3c4fe0230db747cb592702fa0b58e660c857c32"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20855","number":20855,"commit":"a5d8651094167f783ee8260689b08fd0e78054ce"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20842","number":20842,"commit":"0b41ad94eef12589de5b38470e3e47b3c9e7952c"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20809","number":20809,"commit":"4de97f036365c256f0e29da55bde6c894cf01a94"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20801","number":20801,"commit":"307af44eb598d6cf43c1f97608541d06e26ec90a"}],"number":20882}
buildkite-pr-comment-->

2025-01-24 11:19 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20907)
* Commit: 8b46e6643e59f5411e93ea3cb7610a23b0b68067

### History
* :green_heart: [Build #20882](https://buildkite.com/elastic/integrations/builds/20882) succeeded 9b04bf82ed7f27c7a830dae5fd8afe670897004b
* :broken_heart: [Build #20879](https://buildkite.com/elastic/integrations/builds/20879) failed d3c4fe0230db747cb592702fa0b58e660c857c32
* :green_heart: [Build #20855](https://buildkite.com/elastic/integrations/builds/20855) succeeded a5d8651094167f783ee8260689b08fd0e78054ce
* :green_heart: [Build #20842](https://buildkite.com/elastic/integrations/builds/20842) succeeded 0b41ad94eef12589de5b38470e3e47b3c9e7952c
* :green_heart: [Build #20809](https://buildkite.com/elastic/integrations/builds/20809) succeeded 4de97f036365c256f0e29da55bde6c894cf01a94
* :broken_heart: [Build #20801](https://buildkite.com/elastic/integrations/builds/20801) failed 307af44eb598d6cf43c1f97608541d06e26ec90a

cc @chrisberkhout

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20907","number":20907,"commit":"8b46e6643e59f5411e93ea3cb7610a23b0b68067"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20882","number":20882,"commit":"9b04bf82ed7f27c7a830dae5fd8afe670897004b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20879","number":20879,"commit":"d3c4fe0230db747cb592702fa0b58e660c857c32"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20855","number":20855,"commit":"a5d8651094167f783ee8260689b08fd0e78054ce"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20842","number":20842,"commit":"0b41ad94eef12589de5b38470e3e47b3c9e7952c"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20809","number":20809,"commit":"4de97f036365c256f0e29da55bde6c894cf01a94"}],"number":20907}
buildkite-pr-comment-->

2025-01-24 12:40 UTC, HeroicHorizon commented on packages/beyondinsight_password_safe/data_stream/session/elasticsearch/ingest_pipeline/default.yml
> +
I have verified the design document, data streams have mapping ECS fields.  I have added for network.protocol one.  Many ECS fields for other data stream, but session its only one field as of now.

2025-01-24 13:03 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20913)
* Commit: b21a561c321b748c2a7256558fe179bf028f3a1e

### History
* :green_heart: [Build #20907](https://buildkite.com/elastic/integrations/builds/20907) succeeded 8b46e6643e59f5411e93ea3cb7610a23b0b68067
* :green_heart: [Build #20882](https://buildkite.com/elastic/integrations/builds/20882) succeeded 9b04bf82ed7f27c7a830dae5fd8afe670897004b
* :broken_heart: [Build #20879](https://buildkite.com/elastic/integrations/builds/20879) failed d3c4fe0230db747cb592702fa0b58e660c857c32
* :green_heart: [Build #20855](https://buildkite.com/elastic/integrations/builds/20855) succeeded a5d8651094167f783ee8260689b08fd0e78054ce
* :green_heart: [Build #20842](https://buildkite.com/elastic/integrations/builds/20842) succeeded 0b41ad94eef12589de5b38470e3e47b3c9e7952c
* :green_heart: [Build #20809](https://buildkite.com/elastic/integrations/builds/20809) succeeded 4de97f036365c256f0e29da55bde6c894cf01a94

cc @chrisberkhout

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20913","number":20913,"commit":"b21a561c321b748c2a7256558fe179bf028f3a1e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20907","number":20907,"commit":"8b46e6643e59f5411e93ea3cb7610a23b0b68067"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20882","number":20882,"commit":"9b04bf82ed7f27c7a830dae5fd8afe670897004b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20879","number":20879,"commit":"d3c4fe0230db747cb592702fa0b58e660c857c32"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20855","number":20855,"commit":"a5d8651094167f783ee8260689b08fd0e78054ce"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20842","number":20842,"commit":"0b41ad94eef12589de5b38470e3e47b3c9e7952c"}],"number":20913}
buildkite-pr-comment-->

2025-01-24 14:00 UTC, alexwizp commented
/test

2025-01-24 14:25 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20916)
* Commit: b21a561c321b748c2a7256558fe179bf028f3a1e

### History
* :green_heart: [Build #20913](https://buildkite.com/elastic/integrations/builds/20913) succeeded b21a561c321b748c2a7256558fe179bf028f3a1e
* :green_heart: [Build #20907](https://buildkite.com/elastic/integrations/builds/20907) succeeded 8b46e6643e59f5411e93ea3cb7610a23b0b68067
* :green_heart: [Build #20882](https://buildkite.com/elastic/integrations/builds/20882) succeeded 9b04bf82ed7f27c7a830dae5fd8afe670897004b
* :broken_heart: [Build #20879](https://buildkite.com/elastic/integrations/builds/20879) failed d3c4fe0230db747cb592702fa0b58e660c857c32
* :green_heart: [Build #20855](https://buildkite.com/elastic/integrations/builds/20855) succeeded a5d8651094167f783ee8260689b08fd0e78054ce
* :green_heart: [Build #20842](https://buildkite.com/elastic/integrations/builds/20842) succeeded 0b41ad94eef12589de5b38470e3e47b3c9e7952c

cc @chrisberkhout

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20916","number":20916,"commit":"b21a561c321b748c2a7256558fe179bf028f3a1e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20913","number":20913,"commit":"b21a561c321b748c2a7256558fe179bf028f3a1e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20907","number":20907,"commit":"8b46e6643e59f5411e93ea3cb7610a23b0b68067"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20882","number":20882,"commit":"9b04bf82ed7f27c7a830dae5fd8afe670897004b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20879","number":20879,"commit":"d3c4fe0230db747cb592702fa0b58e660c857c32"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20855","number":20855,"commit":"a5d8651094167f783ee8260689b08fd0e78054ce"}],"number":20916}
buildkite-pr-comment-->

2025-01-27 03:33 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/useraudit/agent/stream/cel.yml.hbs
> +program: |-
There is a bug in here.

I ran it against the test account, only for user audit, with:
- request tracing on
- `limit: 100`
- `initial_interval: 300h`
- `interval: 1m`

What I observe in the request tracing logs is this:
- the first request has a good `startdate`, no `enddate` (ok). the response has a page of the most recent data.
- the 2nd request keeps the same `startdate` (good) and `enddate` is set to stop at earliest result seen so far (good)
- later pages continue to go back towards the start date (good)
- after a non-full page is received, it stops and waits interval (good)
- after the interval, the first request of the new sequence has empty `startdate` and `enddate` (bad), and then it pages backwards with no `startdate`, so it refetches all data, and goes back through the whole history, beyond the configured `initial_interval`

Here's some excerpts from log, showing the last two requests and responses from the first sequence and the first two from the next sequence:

```
{"@timestamp":"2025-01-27T02:59:32.835Z","url.query":"enddate=2025-01-15T14%3A58%3A26.37Z&limit=100&startdate=2025-01-14+14%3A55%3A16"}
{"@timestamp":"2025-01-27T02:59:34.439Z","http.response.body.content":"{\"TotalCount\":123,\"Data\":[{\"AuditID\":36172,\"ActionType\":\"Login\",..."}

{"@timestamp":"2025-01-27T02:59:34.446Z","url.query":"enddate=2025-01-15T14%3A00%3A32.357Z&limit=100&startdate=2025-01-14+14%3A55%3A16"}
{"@timestamp":"2025-01-27T02:59:35.692Z","http.response.body.content":"{\"TotalCount\":24,\"Data\":[{\"AuditID\":36073,\"ActionType\":\"Login\",..."}

{"@timestamp":"2025-01-27T03:00:35.697Z","url.query":"enddate=&limit=100&startdate="}
{"@timestamp":"2025-01-27T03:00:37.213Z","http.response.body.content":"{\"TotalCount\":53882,\"Data\":[{\"AuditID\":53882,\"ActionType\":\"Login\",..."}

{"@timestamp":"2025-01-27T03:00:37.220Z","url.query":"enddate=2025-01-22T18%3A03%3A26.793Z&limit=100&startdate="}
{"@timestamp":"2025-01-27T03:00:38.747Z","http.response.body.content":"{\"TotalCount\":53783,\"Data\":[{\"AuditID\":53783,\"ActionType\":\"Login\",..."}
```

2025-01-27 04:15 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/_dev/deploy/docker/files/config.yml
> +rules:
The tests have been extended to cover several pages, which is good.

There is still a bug in the `useraudit` data stream's pagination logic, as described elsewhere.

It would be good for the test to cover the currently buggy case: starting a 2nd pagination sequence.

2025-01-27 04:20 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/_dev/build/docs/README.md
> +**pwd**: The RunAs user password surrounded by square brackets `(optional; required only if the User Password is required on the application API registration).`
The content of this section has been rewritten and is now from the user's perspective, except for one line that I will separately suggest removing.

2025-01-27 05:58 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/asset/agent/stream/cel.yml.hbs
> +  						)
Nice

2025-01-27 06:09 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/useraudit/agent/stream/cel.yml.hbs
> +  					bool(size(body.Data) > 0 && state.?cursor.enddate.orValue(params.enddate[0]) != body.?Data[size(body.Data) - 1].CreateDate.orValue("")).as(wantMore,
These issues are resolved. The current logic is probably involved in the bug described in detail elsewhere.

2025-01-27 06:11 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/useraudit/agent/stream/cel.yml.hbs
> +  										"tempStartDate": (newEnddate == "") ? string(body.Data[0].CreateDate) : state.?cursor.tempStartDate.orValue(""),
The variable naming is improved.

There is a problem with the logic of starting a new pagination sequence but that is described in more detail elsewhere.

2025-01-27 06:16 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/asset/elasticsearch/ingest_pipeline/default.yml
> +        - beyondinsight_password_safe.asset.AssetID
It looks like `AssetID` was replaced with `LastUpdateDate`, but they should both be included.

```yaml
  - fingerprint:
      fields:
        - beyondinsight_password_safe.asset.AssetID
        - beyondinsight_password_safe.asset.LastUpdateDate
      target_field: "_id"
```

2025-01-27 06:45 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/asset/elasticsearch/ingest_pipeline/default.yml
> +
```suggestion
```

Just remove this, because `geoip` is run correctly later in the pipeline.

2025-01-27 06:45 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/asset/elasticsearch/ingest_pipeline/default.yml
> +      allow_duplicates: false
I think a version of this issue is still there. The issue is that the `geoip` processor is run on `host.ip` before `host.ip` is set.

Later in the pipeline it's done in the right order. The earlier `geoip` processor can be removed. I will resolve this one and will make that suggestion separately.

2025-01-27 06:56 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/session/elasticsearch/ingest_pipeline/default.yml
> +
In particular, I was thinking about `related.user` for the `UserID` value.

2025-01-27 07:26 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20963)
* Commit: 7e1f7f7405e4eae9ed60ff7db21f1f9c816b208e

### History
* :green_heart: [Build #20916](https://buildkite.com/elastic/integrations/builds/20916) succeeded b21a561c321b748c2a7256558fe179bf028f3a1e
* :green_heart: [Build #20913](https://buildkite.com/elastic/integrations/builds/20913) succeeded b21a561c321b748c2a7256558fe179bf028f3a1e
* :green_heart: [Build #20907](https://buildkite.com/elastic/integrations/builds/20907) succeeded 8b46e6643e59f5411e93ea3cb7610a23b0b68067
* :green_heart: [Build #20882](https://buildkite.com/elastic/integrations/builds/20882) succeeded 9b04bf82ed7f27c7a830dae5fd8afe670897004b
* :broken_heart: [Build #20879](https://buildkite.com/elastic/integrations/builds/20879) failed d3c4fe0230db747cb592702fa0b58e660c857c32
* :green_heart: [Build #20855](https://buildkite.com/elastic/integrations/builds/20855) succeeded a5d8651094167f783ee8260689b08fd0e78054ce

cc @chrisberkhout

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20963","number":20963,"commit":"7e1f7f7405e4eae9ed60ff7db21f1f9c816b208e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20916","number":20916,"commit":"b21a561c321b748c2a7256558fe179bf028f3a1e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20913","number":20913,"commit":"b21a561c321b748c2a7256558fe179bf028f3a1e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20907","number":20907,"commit":"8b46e6643e59f5411e93ea3cb7610a23b0b68067"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20882","number":20882,"commit":"9b04bf82ed7f27c7a830dae5fd8afe670897004b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20879","number":20879,"commit":"d3c4fe0230db747cb592702fa0b58e660c857c32"}],"number":20963}
buildkite-pr-comment-->

2025-01-27 07:59 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/session/manifest.yml
> +        default: "60s"
```suggestion
        default: 5m
```
Please make this the default.

2025-01-27 08:55 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20970)
* Commit: 7e1f7f7405e4eae9ed60ff7db21f1f9c816b208e

### History
* :green_heart: [Build #20963](https://buildkite.com/elastic/integrations/builds/20963) succeeded 7e1f7f7405e4eae9ed60ff7db21f1f9c816b208e
* :green_heart: [Build #20916](https://buildkite.com/elastic/integrations/builds/20916) succeeded b21a561c321b748c2a7256558fe179bf028f3a1e
* :green_heart: [Build #20913](https://buildkite.com/elastic/integrations/builds/20913) succeeded b21a561c321b748c2a7256558fe179bf028f3a1e
* :green_heart: [Build #20907](https://buildkite.com/elastic/integrations/builds/20907) succeeded 8b46e6643e59f5411e93ea3cb7610a23b0b68067
* :green_heart: [Build #20882](https://buildkite.com/elastic/integrations/builds/20882) succeeded 9b04bf82ed7f27c7a830dae5fd8afe670897004b
* :broken_heart: [Build #20879](https://buildkite.com/elastic/integrations/builds/20879) failed d3c4fe0230db747cb592702fa0b58e660c857c32

cc @chrisberkhout

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20970","number":20970,"commit":"7e1f7f7405e4eae9ed60ff7db21f1f9c816b208e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20963","number":20963,"commit":"7e1f7f7405e4eae9ed60ff7db21f1f9c816b208e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20916","number":20916,"commit":"b21a561c321b748c2a7256558fe179bf028f3a1e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20913","number":20913,"commit":"b21a561c321b748c2a7256558fe179bf028f3a1e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20907","number":20907,"commit":"8b46e6643e59f5411e93ea3cb7610a23b0b68067"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20882","number":20882,"commit":"9b04bf82ed7f27c7a830dae5fd8afe670897004b"}],"number":20970}
buildkite-pr-comment-->

2025-01-27 10:00 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20974)
* Commit: 85925889d96b02e3f45bfbfc6bf3024ce4f64526

### History
* :green_heart: [Build #20970](https://buildkite.com/elastic/integrations/builds/20970) succeeded 7e1f7f7405e4eae9ed60ff7db21f1f9c816b208e
* :green_heart: [Build #20963](https://buildkite.com/elastic/integrations/builds/20963) succeeded 7e1f7f7405e4eae9ed60ff7db21f1f9c816b208e
* :green_heart: [Build #20916](https://buildkite.com/elastic/integrations/builds/20916) succeeded b21a561c321b748c2a7256558fe179bf028f3a1e
* :green_heart: [Build #20913](https://buildkite.com/elastic/integrations/builds/20913) succeeded b21a561c321b748c2a7256558fe179bf028f3a1e
* :green_heart: [Build #20907](https://buildkite.com/elastic/integrations/builds/20907) succeeded 8b46e6643e59f5411e93ea3cb7610a23b0b68067
* :green_heart: [Build #20882](https://buildkite.com/elastic/integrations/builds/20882) succeeded 9b04bf82ed7f27c7a830dae5fd8afe670897004b

cc @chrisberkhout

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20974","number":20974,"commit":"85925889d96b02e3f45bfbfc6bf3024ce4f64526"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20970","number":20970,"commit":"7e1f7f7405e4eae9ed60ff7db21f1f9c816b208e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20963","number":20963,"commit":"7e1f7f7405e4eae9ed60ff7db21f1f9c816b208e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20916","number":20916,"commit":"b21a561c321b748c2a7256558fe179bf028f3a1e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20913","number":20913,"commit":"b21a561c321b748c2a7256558fe179bf028f3a1e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20907","number":20907,"commit":"8b46e6643e59f5411e93ea3cb7610a23b0b68067"}],"number":20974}
buildkite-pr-comment-->

2025-01-27 14:36 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20990)
* Commit: 61a77ebb8613f549da3a14951e52f04622419223

### History
* :green_heart: [Build #20974](https://buildkite.com/elastic/integrations/builds/20974) succeeded 85925889d96b02e3f45bfbfc6bf3024ce4f64526
* :green_heart: [Build #20970](https://buildkite.com/elastic/integrations/builds/20970) succeeded 7e1f7f7405e4eae9ed60ff7db21f1f9c816b208e
* :green_heart: [Build #20963](https://buildkite.com/elastic/integrations/builds/20963) succeeded 7e1f7f7405e4eae9ed60ff7db21f1f9c816b208e
* :green_heart: [Build #20916](https://buildkite.com/elastic/integrations/builds/20916) succeeded b21a561c321b748c2a7256558fe179bf028f3a1e
* :green_heart: [Build #20913](https://buildkite.com/elastic/integrations/builds/20913) succeeded b21a561c321b748c2a7256558fe179bf028f3a1e
* :green_heart: [Build #20907](https://buildkite.com/elastic/integrations/builds/20907) succeeded 8b46e6643e59f5411e93ea3cb7610a23b0b68067

cc @chrisberkhout

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20990","number":20990,"commit":"61a77ebb8613f549da3a14951e52f04622419223"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20974","number":20974,"commit":"85925889d96b02e3f45bfbfc6bf3024ce4f64526"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20970","number":20970,"commit":"7e1f7f7405e4eae9ed60ff7db21f1f9c816b208e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20963","number":20963,"commit":"7e1f7f7405e4eae9ed60ff7db21f1f9c816b208e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20916","number":20916,"commit":"b21a561c321b748c2a7256558fe179bf028f3a1e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20913","number":20913,"commit":"b21a561c321b748c2a7256558fe179bf028f3a1e"}],"number":20990}
buildkite-pr-comment-->

2025-01-27 17:46 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/21003)
* Commit: 26277dbdab25ea4c16031639afed39dd73958d70

### History
* :green_heart: [Build #20990](https://buildkite.com/elastic/integrations/builds/20990) succeeded 61a77ebb8613f549da3a14951e52f04622419223
* :green_heart: [Build #20974](https://buildkite.com/elastic/integrations/builds/20974) succeeded 85925889d96b02e3f45bfbfc6bf3024ce4f64526
* :green_heart: [Build #20970](https://buildkite.com/elastic/integrations/builds/20970) succeeded 7e1f7f7405e4eae9ed60ff7db21f1f9c816b208e
* :green_heart: [Build #20963](https://buildkite.com/elastic/integrations/builds/20963) succeeded 7e1f7f7405e4eae9ed60ff7db21f1f9c816b208e
* :green_heart: [Build #20916](https://buildkite.com/elastic/integrations/builds/20916) succeeded b21a561c321b748c2a7256558fe179bf028f3a1e
* :green_heart: [Build #20913](https://buildkite.com/elastic/integrations/builds/20913) succeeded b21a561c321b748c2a7256558fe179bf028f3a1e

cc @chrisberkhout

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/21003","number":21003,"commit":"26277dbdab25ea4c16031639afed39dd73958d70"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20990","number":20990,"commit":"61a77ebb8613f549da3a14951e52f04622419223"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20974","number":20974,"commit":"85925889d96b02e3f45bfbfc6bf3024ce4f64526"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20970","number":20970,"commit":"7e1f7f7405e4eae9ed60ff7db21f1f9c816b208e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20963","number":20963,"commit":"7e1f7f7405e4eae9ed60ff7db21f1f9c816b208e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20916","number":20916,"commit":"b21a561c321b748c2a7256558fe179bf028f3a1e"}],"number":21003}
buildkite-pr-comment-->

2025-01-29 07:11 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/21167)
* Commit: 5f95849be33165ea1e8b04bb36b4fa893b46f71d

### History
* :green_heart: [Build #21003](https://buildkite.com/elastic/integrations/builds/21003) succeeded 26277dbdab25ea4c16031639afed39dd73958d70
* :green_heart: [Build #20990](https://buildkite.com/elastic/integrations/builds/20990) succeeded 61a77ebb8613f549da3a14951e52f04622419223
* :green_heart: [Build #20974](https://buildkite.com/elastic/integrations/builds/20974) succeeded 85925889d96b02e3f45bfbfc6bf3024ce4f64526
* :green_heart: [Build #20970](https://buildkite.com/elastic/integrations/builds/20970) succeeded 7e1f7f7405e4eae9ed60ff7db21f1f9c816b208e
* :green_heart: [Build #20963](https://buildkite.com/elastic/integrations/builds/20963) succeeded 7e1f7f7405e4eae9ed60ff7db21f1f9c816b208e
* :green_heart: [Build #20916](https://buildkite.com/elastic/integrations/builds/20916) succeeded b21a561c321b748c2a7256558fe179bf028f3a1e

cc @chrisberkhout

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/21167","number":21167,"commit":"5f95849be33165ea1e8b04bb36b4fa893b46f71d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/21003","number":21003,"commit":"26277dbdab25ea4c16031639afed39dd73958d70"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20990","number":20990,"commit":"61a77ebb8613f549da3a14951e52f04622419223"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20974","number":20974,"commit":"85925889d96b02e3f45bfbfc6bf3024ce4f64526"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20970","number":20970,"commit":"7e1f7f7405e4eae9ed60ff7db21f1f9c816b208e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20963","number":20963,"commit":"7e1f7f7405e4eae9ed60ff7db21f1f9c816b208e"}],"number":21167}
buildkite-pr-comment-->

2025-01-29 08:29 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/21171)
* Commit: 78a4520becc02626965136727210e5915886bb9d

### History
* :green_heart: [Build #21167](https://buildkite.com/elastic/integrations/builds/21167) succeeded 5f95849be33165ea1e8b04bb36b4fa893b46f71d
* :green_heart: [Build #21003](https://buildkite.com/elastic/integrations/builds/21003) succeeded 26277dbdab25ea4c16031639afed39dd73958d70
* :green_heart: [Build #20990](https://buildkite.com/elastic/integrations/builds/20990) succeeded 61a77ebb8613f549da3a14951e52f04622419223
* :green_heart: [Build #20974](https://buildkite.com/elastic/integrations/builds/20974) succeeded 85925889d96b02e3f45bfbfc6bf3024ce4f64526
* :green_heart: [Build #20970](https://buildkite.com/elastic/integrations/builds/20970) succeeded 7e1f7f7405e4eae9ed60ff7db21f1f9c816b208e
* :green_heart: [Build #20963](https://buildkite.com/elastic/integrations/builds/20963) succeeded 7e1f7f7405e4eae9ed60ff7db21f1f9c816b208e

cc @chrisberkhout

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/21171","number":21171,"commit":"78a4520becc02626965136727210e5915886bb9d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/21167","number":21167,"commit":"5f95849be33165ea1e8b04bb36b4fa893b46f71d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/21003","number":21003,"commit":"26277dbdab25ea4c16031639afed39dd73958d70"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20990","number":20990,"commit":"61a77ebb8613f549da3a14951e52f04622419223"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20974","number":20974,"commit":"85925889d96b02e3f45bfbfc6bf3024ce4f64526"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20970","number":20970,"commit":"7e1f7f7405e4eae9ed60ff7db21f1f9c816b208e"}],"number":21171}
buildkite-pr-comment-->

2025-01-29 12:51 UTC, alexwizp approved these changes

2025-01-29 13:08 UTC, ravikumar5555 approved these changes

2025-01-30 00:04 UTC, chrisberkhout requested changes

2025-01-30 00:07 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/data_stream/useraudit/agent/stream/cel.yml.hbs
> +program: |-
Manual testing shows it now starts a 2nd pagination sequence correctly.

2025-01-30 00:10 UTC, chrisberkhout commented on packages/beyondinsight_password_safe/_dev/deploy/docker/files/config.yml
> +rules:
The system test doesn't cover the 2nd pagination sequence, but the bug there is fixed.

2025-01-30 06:32 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/21262)
* Commit: aebf65d779a9bc1de2703c4679224cd20236532f

### History
* :green_heart: [Build #21171](https://buildkite.com/elastic/integrations/builds/21171) succeeded 78a4520becc02626965136727210e5915886bb9d
* :green_heart: [Build #21167](https://buildkite.com/elastic/integrations/builds/21167) succeeded 5f95849be33165ea1e8b04bb36b4fa893b46f71d
* :green_heart: [Build #21003](https://buildkite.com/elastic/integrations/builds/21003) succeeded 26277dbdab25ea4c16031639afed39dd73958d70
* :green_heart: [Build #20990](https://buildkite.com/elastic/integrations/builds/20990) succeeded 61a77ebb8613f549da3a14951e52f04622419223
* :green_heart: [Build #20974](https://buildkite.com/elastic/integrations/builds/20974) succeeded 85925889d96b02e3f45bfbfc6bf3024ce4f64526
* :green_heart: [Build #20970](https://buildkite.com/elastic/integrations/builds/20970) succeeded 7e1f7f7405e4eae9ed60ff7db21f1f9c816b208e

cc @chrisberkhout

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/21262","number":21262,"commit":"aebf65d779a9bc1de2703c4679224cd20236532f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/21171","number":21171,"commit":"78a4520becc02626965136727210e5915886bb9d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/21167","number":21167,"commit":"5f95849be33165ea1e8b04bb36b4fa893b46f71d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/21003","number":21003,"commit":"26277dbdab25ea4c16031639afed39dd73958d70"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20990","number":20990,"commit":"61a77ebb8613f549da3a14951e52f04622419223"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20974","number":20974,"commit":"85925889d96b02e3f45bfbfc6bf3024ce4f64526"}],"number":21262}
buildkite-pr-comment-->

2025-01-30 06:59 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/21264)
* Commit: 9889e650f5f41e00609bc09a75fac51353235224

### Failed CI Steps
* [Check integrations beyondinsight_password_safe](https://buildkite.com/elastic/integrations/builds/21264#0194b5f6-68c6-4fa3-b0a9-8f4c346ac6f2)

### History
* :green_heart: [Build #21262](https://buildkite.com/elastic/integrations/builds/21262) succeeded aebf65d779a9bc1de2703c4679224cd20236532f
* :green_heart: [Build #21171](https://buildkite.com/elastic/integrations/builds/21171) succeeded 78a4520becc02626965136727210e5915886bb9d
* :green_heart: [Build #21167](https://buildkite.com/elastic/integrations/builds/21167) succeeded 5f95849be33165ea1e8b04bb36b4fa893b46f71d
* :green_heart: [Build #21003](https://buildkite.com/elastic/integrations/builds/21003) succeeded 26277dbdab25ea4c16031639afed39dd73958d70
* :green_heart: [Build #20990](https://buildkite.com/elastic/integrations/builds/20990) succeeded 61a77ebb8613f549da3a14951e52f04622419223
* :green_heart: [Build #20974](https://buildkite.com/elastic/integrations/builds/20974) succeeded 85925889d96b02e3f45bfbfc6bf3024ce4f64526

cc @chrisberkhout

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/21264","number":21264,"commit":"9889e650f5f41e00609bc09a75fac51353235224"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/21262","number":21262,"commit":"aebf65d779a9bc1de2703c4679224cd20236532f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/21171","number":21171,"commit":"78a4520becc02626965136727210e5915886bb9d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/21167","number":21167,"commit":"5f95849be33165ea1e8b04bb36b4fa893b46f71d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/21003","number":21003,"commit":"26277dbdab25ea4c16031639afed39dd73958d70"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20990","number":20990,"commit":"61a77ebb8613f549da3a14951e52f04622419223"}],"number":21264}
buildkite-pr-comment-->

2025-01-30 07:42 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/21266)
* Commit: 8f161174b35c7368742cd85a5fa2c6832970f723

### History
* :broken_heart: [Build #21264](https://buildkite.com/elastic/integrations/builds/21264) failed 9889e650f5f41e00609bc09a75fac51353235224
* :green_heart: [Build #21262](https://buildkite.com/elastic/integrations/builds/21262) succeeded aebf65d779a9bc1de2703c4679224cd20236532f
* :green_heart: [Build #21171](https://buildkite.com/elastic/integrations/builds/21171) succeeded 78a4520becc02626965136727210e5915886bb9d
* :green_heart: [Build #21167](https://buildkite.com/elastic/integrations/builds/21167) succeeded 5f95849be33165ea1e8b04bb36b4fa893b46f71d
* :green_heart: [Build #21003](https://buildkite.com/elastic/integrations/builds/21003) succeeded 26277dbdab25ea4c16031639afed39dd73958d70

cc @chrisberkhout

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/21266","number":21266,"commit":"8f161174b35c7368742cd85a5fa2c6832970f723"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/21264","number":21264,"commit":"9889e650f5f41e00609bc09a75fac51353235224"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/21262","number":21262,"commit":"aebf65d779a9bc1de2703c4679224cd20236532f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/21171","number":21171,"commit":"78a4520becc02626965136727210e5915886bb9d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/21167","number":21167,"commit":"5f95849be33165ea1e8b04bb36b4fa893b46f71d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/21003","number":21003,"commit":"26277dbdab25ea4c16031639afed39dd73958d70"}],"number":21266}
buildkite-pr-comment-->

2025-01-30 09:35 UTC, chrisberkhout approved these changes
Thanks!

2025-01-30 09:39 UTC, merged