[Draft] Add Integration for Missile Map
elastic/integrations pull request #11758
Opened 2024-11-18 07:36 UTC by navnit-crest

## Proposed commit message
Create a new integration package, missile_map, and add the Missile Map dashboard.

The Missile Map dashboard includes a custom map visualization that uses the Elastic Map Service to add a base map. For the marks (path, text, arc, etc.) and animations, it uses the [Vega](https://vega.github.io/vega/) visualization framework within Kibana.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's changelog.yml file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally

1. Clone integrations repo.
2. Install elastic package locally.
3. Start elastic stack using elastic-package.
4. Move to integrations/packages/missile_map directory.
5. Run the following command to run tests. 
> elastic-package test

```
--- Test results for package: missile_map - START ---
╭─────────────┬─────────────┬───────────┬──────────────────────────────────────────────────────────────────────┬────────┬──────────────╮
│ PACKAGE     │ DATA STREAM │ TEST TYPE │ TEST NAME                                                            │ RESULT │ TIME ELAPSED │
├─────────────┼─────────────┼───────────┼──────────────────────────────────────────────────────────────────────┼────────┼──────────────┤
│ missile_map │             │ asset     │ dashboard missile_map-7b9c1c24-64b0-4e75-b321-dce264eb0776 is loaded │ PASS   │      1.595µs │
╰─────────────┴─────────────┴───────────┴──────────────────────────────────────────────────────────────────────┴────────┴──────────────╯
--- Test results for package: missile_map - END   ---
Done
```
## Screenshots
![missile-map](https://github.com/user-attachments/assets/7364b129-eb59-4a76-bc29-ec895de7f437)

2024-11-25 08:55 UTC, kcreddy commented
/test

2024-11-25 08:59 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/18654)
* Commit: 614347912e8eb7a604cd208548b52a3d50da4c6a

### Failed CI Steps
* [:white_check_mark: Check go sources](https://buildkite.com/elastic/integrations/builds/18654#01936289-61fb-4470-851b-5b018b33da3b)

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18654","number":18654,"commit":"614347912e8eb7a604cd208548b52a3d50da4c6a"}],"number":18654}
buildkite-pr-comment-->

2024-11-25 09:24 UTC, kcreddy commented on packages/missile_map/docs/README.md
> +### 1. Duplicate the Entire Dashboard
```suggestion
### 1. Duplicate the Dashboard
```

2024-11-25 09:24 UTC, kcreddy commented on packages/missile_map/docs/README.md
> +To use the Missile Map visualization, ensure the following:
```suggestion
To use the Missile Map dashboard, ensure the following:
```

2024-11-25 09:31 UTC, kcreddy commented on packages/missile_map/manifest.yml
> +  github: elastic/integrations
```suggestion
  github: elastic/security-service-integrations
```

2024-11-25 12:19 UTC, navnit-crest commented on packages/missile_map/manifest.yml
> +    version: "^8.10.0"
We chose `^8.10.0` to support a wider range of versions that align with the requirements. However, we can update it to `8.13.0` if that is preferred.

2024-11-25 12:24 UTC, kcreddy commented on packages/missile_map/manifest.yml
> +    version: "^8.10.0"
@jamiehynds , could you confirm if we can change the minimum kibana version to `8.14.0`, as it is used by most new integrations we are building?

2024-11-25 12:38 UTC, jamiehynds commented on packages/missile_map/manifest.yml
> +    version: "^8.10.0"
@kcreddy the customer behind this request is on `8.15.0` so no issues with setting the minimum to `8.14.0`

2024-11-25 12:40 UTC, kcreddy commented on packages/missile_map/manifest.yml
> +    version: "^8.10.0"
@navnit-crest , can you change this to `^8.14.0` and also build it on `8.14.0` elastic-package stack version.

Also, export dashboard once again on this version: `elastic-package export dashboards`

2024-11-25 15:53 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/18670)
* Commit: ccbd7cfd81797c0e3b320b45d31f956488bc2cc1

### History
* :broken_heart: [Build #18654](https://buildkite.com/elastic/integrations/builds/18654) failed 614347912e8eb7a604cd208548b52a3d50da4c6a

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18670","number":18670,"commit":"ccbd7cfd81797c0e3b320b45d31f956488bc2cc1"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18654","number":18654,"commit":"614347912e8eb7a604cd208548b52a3d50da4c6a"}],"number":18670}
buildkite-pr-comment-->

2024-11-25 15:54 UTC, kcreddy requested changes

2024-11-25 15:54 UTC, kcreddy commented on packages/missile_map/manifest.yml
> +description: "This integration ships a missile map, a custom visualization to analyze network traffic data."
Package name and description requires a change. Holding off merge until then.

2024-11-28 05:53 UTC, kcreddy commented
/test

2024-11-28 06:04 UTC, kcreddy reviewed
Please update PR's `Proposed commit message` section with updated package name.

2024-11-28 06:04 UTC, kcreddy commented on packages/threat_map/docs/README.md
This `README.md` should be under `_dev/build/docs/README.md`. [Example](https://github.com/elastic/integrations/blob/main/packages/abnormal_security/_dev/build/docs/README.md) 

When you run `build`, the `docs/README.md` is auto-generated.
Reference:
https://github.com/elastic/elastic-package/blob/main/docs/howto/add_package_readme.md

2024-11-28 06:09 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/18829)
* Commit: 0863359949f59903ac47b485a50cd0bb512ffae2

### History
* :green_heart: [Build #18670](https://buildkite.com/elastic/integrations/builds/18670) succeeded ccbd7cfd81797c0e3b320b45d31f956488bc2cc1
* :broken_heart: [Build #18654](https://buildkite.com/elastic/integrations/builds/18654) failed 614347912e8eb7a604cd208548b52a3d50da4c6a

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18829","number":18829,"commit":"0863359949f59903ac47b485a50cd0bb512ffae2"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18670","number":18670,"commit":"ccbd7cfd81797c0e3b320b45d31f956488bc2cc1"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18654","number":18654,"commit":"614347912e8eb7a604cd208548b52a3d50da4c6a"}],"number":18829}
buildkite-pr-comment-->

2024-11-28 07:20 UTC, kcreddy commented
/test

2024-11-28 07:36 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/18833)
* Commit: 55a554ba058d15f9ae2bf3433ce59c1f410e92d6

### History
* :green_heart: [Build #18829](https://buildkite.com/elastic/integrations/builds/18829) succeeded 0863359949f59903ac47b485a50cd0bb512ffae2
* :green_heart: [Build #18670](https://buildkite.com/elastic/integrations/builds/18670) succeeded ccbd7cfd81797c0e3b320b45d31f956488bc2cc1
* :broken_heart: [Build #18654](https://buildkite.com/elastic/integrations/builds/18654) failed 614347912e8eb7a604cd208548b52a3d50da4c6a

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18833","number":18833,"commit":"55a554ba058d15f9ae2bf3433ce59c1f410e92d6"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18829","number":18829,"commit":"0863359949f59903ac47b485a50cd0bb512ffae2"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18670","number":18670,"commit":"ccbd7cfd81797c0e3b320b45d31f956488bc2cc1"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18654","number":18654,"commit":"614347912e8eb7a604cd208548b52a3d50da4c6a"}],"number":18833}
buildkite-pr-comment-->

2024-11-28 07:38 UTC, merged