Removed technical preview language
elastic/integrations pull request #11761
Opened 2024-11-18 17:10 UTC by flexitrev

Documentation

## Proposed commit message
Updated documentation to remove technical preview label on Agent based monitoring

-->

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).
- [X] I have verified that any added dashboard complies with Kibana's [Dashboard good practices](https://docs.elastic.dev/ux-guidelines/data-viz/dashboard-good-practices) 

## Author's Checklist

## How to test this PR locally

## Related issues

## Screenshots

2024-11-18 17:14 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/18409)
* Commit: 24386654acbebaa338e0b1030128ceda787c9c55

### Failed CI Steps
* [:white_check_mark: Check go sources](https://buildkite.com/elastic/integrations/builds/18409#01934042-482f-4218-b01f-1084cf6ae7cf)

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18409","number":18409,"commit":"24386654acbebaa338e0b1030128ceda787c9c55"}],"number":18409}
buildkite-pr-comment-->

2024-11-18 17:17 UTC, consulthys reviewed
Just a few typos to fix

2024-11-18 17:17 UTC, consulthys commented on packages/logstash/docs/README.md
> +Metrics colleciton is not compatible with the Stack Monitoring UI inside Kibana, only only type of Metrics collection should be selected with this integration.
Typo: `colleciton` => `collection`
Typo: `only only`

2024-11-18 17:17 UTC, consulthys commented on packages/logstash/docs/README.md
> +By utilizing Elastic Agent we are able to query additional monitoring APIs and provide addtional dashboards, which include provide the best view into your Logstash deployment and pipeline execution.
"include" or "provide"?

2024-11-18 17:19 UTC, flexitrev commented on packages/logstash/docs/README.md
> +Metrics colleciton is not compatible with the Stack Monitoring UI inside Kibana, only only type of Metrics collection should be selected with this integration.
thanks, fixed!

2024-11-19 06:58 UTC, consulthys commented on packages/logstash/docs/README.md
> +By utilizing Elastic Agent we are able to query additional monitoring APIs and provide addtional dashboards, which provide the best view into your Logstash deployment and pipeline execution.
Sorry I missed this other typo: `addtional` => `additional`

2024-11-19 16:57 UTC, flexitrev commented on packages/logstash/docs/README.md
> +By utilizing Elastic Agent we are able to query additional monitoring APIs and provide addtional dashboards, which provide the best view into your Logstash deployment and pipeline execution.
fixed, thank you

2024-11-19 16:59 UTC, consulthys approved these changes
LGT Stack Monitoring

2024-11-19 17:02 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/18459)
* Commit: bc169a49c96e3dd23fc7632b78e89ae45a61b655

### Failed CI Steps
* [:white_check_mark: Check go sources](https://buildkite.com/elastic/integrations/builds/18459#0193455d-159b-4b1a-87e8-0eba222fce13)

### History
* :broken_heart: [Build #18412](https://buildkite.com/elastic/integrations/builds/18412) failed 1b2b0ef2fede234b59cc922dc13e146119f80912
* :broken_heart: [Build #18409](https://buildkite.com/elastic/integrations/builds/18409) failed 24386654acbebaa338e0b1030128ceda787c9c55

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18459","number":18459,"commit":"bc169a49c96e3dd23fc7632b78e89ae45a61b655"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18412","number":18412,"commit":"1b2b0ef2fede234b59cc922dc13e146119f80912"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18409","number":18409,"commit":"24386654acbebaa338e0b1030128ceda787c9c55"}],"number":18459}
buildkite-pr-comment-->

2024-12-18 17:56 UTC, robbavey requested changes
Some comments on consistency and wording

2024-12-18 17:56 UTC, robbavey commented on packages/logstash/docs/README.md
> +Metrics collection is not compatible with the Stack Monitoring UI inside Kibana, only a single type of Metrics collection should be selected with this integration.
I think this might be confusing - it's `Metrics (Elastic Agent)` that is not compatible with the Stack Monitoring UI, rather than `Metrics collection` as a whole.

Plus there is `Metrics collection` and `Metric collection` in this section - we should probably choose one, and be consistent with it.

2024-12-18 17:56 UTC, robbavey commented on packages/logstash/manifest.yml
> +        description: "Collect node metrics and stats from Logstash instances to power the Stack Monitoring application in Kibana.\n Disable if using Agent Based Monitoring."
```suggestion
        description: "Collect node metrics and stats from Logstash instances to power the Stack Monitoring application in Kibana.\n Disable if using Elastic Agent Based Monitoring."
```
Maybe use `Elastic Agent` here to be consistent with the `Metrics (Elastic Agent)` text from earlier?

2024-12-18 18:16 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/19676)
* Commit: 2a30858e5f396bf1cbbd3fa7a75dbb9ff3446f4b

### Failed CI Steps
* [:white_check_mark: Check go sources](https://buildkite.com/elastic/integrations/builds/19676#0193daf9-6532-44f6-bb2c-b32fc48e280d)

### History
* :broken_heart: [Build #18459](https://buildkite.com/elastic/integrations/builds/18459) failed bc169a49c96e3dd23fc7632b78e89ae45a61b655
* :broken_heart: [Build #18412](https://buildkite.com/elastic/integrations/builds/18412) failed 1b2b0ef2fede234b59cc922dc13e146119f80912
* :broken_heart: [Build #18409](https://buildkite.com/elastic/integrations/builds/18409) failed 24386654acbebaa338e0b1030128ceda787c9c55

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19676","number":19676,"commit":"2a30858e5f396bf1cbbd3fa7a75dbb9ff3446f4b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18459","number":18459,"commit":"bc169a49c96e3dd23fc7632b78e89ae45a61b655"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18412","number":18412,"commit":"1b2b0ef2fede234b59cc922dc13e146119f80912"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18409","number":18409,"commit":"24386654acbebaa338e0b1030128ceda787c9c55"}],"number":19676}
buildkite-pr-comment-->

2024-12-18 18:20 UTC, robbavey approved these changes
LGTM

2024-12-18 18:35 UTC, flexitrev commented
@consulthys any tips on getting ci to work?

2025-01-17 20:10 UTC, flexitrev commented
Refreshing to get away from stale label

2025-01-17 22:10 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20651)
* Commit: f6f76eba4c26e5affc05cbcce245dfd47510e261

### Failed CI Steps
* [:white_check_mark: Check go sources](https://buildkite.com/elastic/integrations/builds/20651#0194764e-a89b-4f37-af66-3e8d0f262d42)

### History
* :broken_heart: [Build #19676](https://buildkite.com/elastic/integrations/builds/19676) failed 2a30858e5f396bf1cbbd3fa7a75dbb9ff3446f4b
* :broken_heart: [Build #18459](https://buildkite.com/elastic/integrations/builds/18459) failed bc169a49c96e3dd23fc7632b78e89ae45a61b655
* :broken_heart: [Build #18412](https://buildkite.com/elastic/integrations/builds/18412) failed 1b2b0ef2fede234b59cc922dc13e146119f80912
* :broken_heart: [Build #18409](https://buildkite.com/elastic/integrations/builds/18409) failed 24386654acbebaa338e0b1030128ceda787c9c55

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20651","number":20651,"commit":"f6f76eba4c26e5affc05cbcce245dfd47510e261"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19676","number":19676,"commit":"2a30858e5f396bf1cbbd3fa7a75dbb9ff3446f4b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18459","number":18459,"commit":"bc169a49c96e3dd23fc7632b78e89ae45a61b655"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18412","number":18412,"commit":"1b2b0ef2fede234b59cc922dc13e146119f80912"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18409","number":18409,"commit":"24386654acbebaa338e0b1030128ceda787c9c55"}],"number":20651}
buildkite-pr-comment-->

2025-01-17 22:23 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20653)
* Commit: 432d9ce48207dba524bf3747fca50114859b4f45

### Failed CI Steps
* [Check integrations logstash](https://buildkite.com/elastic/integrations/builds/20653#01947658-901a-49d0-910c-1154b6ec9116)

### History
* :broken_heart: [Build #20651](https://buildkite.com/elastic/integrations/builds/20651) failed f6f76eba4c26e5affc05cbcce245dfd47510e261
* :broken_heart: [Build #19676](https://buildkite.com/elastic/integrations/builds/19676) failed 2a30858e5f396bf1cbbd3fa7a75dbb9ff3446f4b
* :broken_heart: [Build #18459](https://buildkite.com/elastic/integrations/builds/18459) failed bc169a49c96e3dd23fc7632b78e89ae45a61b655
* :broken_heart: [Build #18412](https://buildkite.com/elastic/integrations/builds/18412) failed 1b2b0ef2fede234b59cc922dc13e146119f80912
* :broken_heart: [Build #18409](https://buildkite.com/elastic/integrations/builds/18409) failed 24386654acbebaa338e0b1030128ceda787c9c55

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20653","number":20653,"commit":"432d9ce48207dba524bf3747fca50114859b4f45"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20651","number":20651,"commit":"f6f76eba4c26e5affc05cbcce245dfd47510e261"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19676","number":19676,"commit":"2a30858e5f396bf1cbbd3fa7a75dbb9ff3446f4b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18459","number":18459,"commit":"bc169a49c96e3dd23fc7632b78e89ae45a61b655"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18412","number":18412,"commit":"1b2b0ef2fede234b59cc922dc13e146119f80912"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18409","number":18409,"commit":"24386654acbebaa338e0b1030128ceda787c9c55"}],"number":20653}
buildkite-pr-comment-->

2025-01-17 23:31 UTC, robbavey commented
The build is failing because your [template](https://github.com/elastic/integrations/pull/11761/files#diff-15cf2158138ada733b1898b06facac3aaaf85da6bc2659dcd006fed031bf2365) README file has different content than the [generated](https://github.com/elastic/integrations/pull/11761/files#diff-f1d5ac2e7f7d2130ba341b9d27ec983ae1d7f5e5b35b543eca84786c70ddff91) content - try running `elastic-package build`  locally, and reup the generated content

2025-01-21 21:47 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20759)
* Commit: 5adcb243b35735abdd55744ab5274695405de26f

### History
* :broken_heart: [Build #20653](https://buildkite.com/elastic/integrations/builds/20653) failed 432d9ce48207dba524bf3747fca50114859b4f45
* :broken_heart: [Build #20651](https://buildkite.com/elastic/integrations/builds/20651) failed f6f76eba4c26e5affc05cbcce245dfd47510e261
* :broken_heart: [Build #19676](https://buildkite.com/elastic/integrations/builds/19676) failed 2a30858e5f396bf1cbbd3fa7a75dbb9ff3446f4b
* :broken_heart: [Build #18459](https://buildkite.com/elastic/integrations/builds/18459) failed bc169a49c96e3dd23fc7632b78e89ae45a61b655
* :broken_heart: [Build #18412](https://buildkite.com/elastic/integrations/builds/18412) failed 1b2b0ef2fede234b59cc922dc13e146119f80912

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20759","number":20759,"commit":"5adcb243b35735abdd55744ab5274695405de26f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20653","number":20653,"commit":"432d9ce48207dba524bf3747fca50114859b4f45"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20651","number":20651,"commit":"f6f76eba4c26e5affc05cbcce245dfd47510e261"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19676","number":19676,"commit":"2a30858e5f396bf1cbbd3fa7a75dbb9ff3446f4b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18459","number":18459,"commit":"bc169a49c96e3dd23fc7632b78e89ae45a61b655"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18412","number":18412,"commit":"1b2b0ef2fede234b59cc922dc13e146119f80912"}],"number":20759}
buildkite-pr-comment-->

2025-01-22 15:33 UTC, robbavey commented on packages/logstash/_dev/build/docs/README.md
> +An example event for `node_stats` looks as following:
The dev version of `readme.md` should have the macro for event objects such as `node_stats` to be expanded automatically

2025-01-22 20:38 UTC, merged

2025-01-22 21:02 UTC, robbavey commented
@flexitrev We will need a follow up PR here, to fix [this](https://github.com/elastic/integrations/pull/11761#discussion_r1925530998) issue - the README.md file in `_dev/build/docs'  should not contain the raw events, but should use the macros/variables instead - eg https://github.com/elastic/integrations/blob/main/packages/elasticsearch/_dev/build/docs/README.md

2025-01-24 17:45 UTC, flexitrev commented
https://github.com/elastic/integrations/pull/12461 follow up to fix README