Add network trafic package
elastic/integrations pull request #1176
Opened 2021-06-22 15:41 UTC by andrewstucki

## What does this PR do?

This is a generic network traffic package that is a replacement for Packetbeat. It contains data streams and configuration for the following protocols:

- amqp
- cassandra
- dhcpv4
- dns
- flow (not a protocol, just flow tracking stats)
- http
- icmp
- memcached
- mongodb
- mysql
- nfs
- pgsql
- redis
- sip
- thrift
- tls

I still need to add test fixtures for it. As it uses the `contains` handlebars helper I extended in Kibana to support strings and conditional blocks, it requires Kibana 7.14.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] If I'm introducing a new feature, I have modified the Kibana version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^7.13.0`).

## How to test this PR locally

Wait until the newest nightly 7.14 snapshot comes out. Boot the stack with it and you should be able to verify this as any oter package.

## Screenshots

<img width="945" alt="Screen Shot 2021-06-22 at 11 24 33 AM" src="https://user-images.githubusercontent.com/3577250/122955724-590f0b00-d34e-11eb-8c14-65600ee1bf34.png">

2021-06-22 15:41 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2021-06-22 15:54 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1176/detail/PR-1176/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1176/detail/PR-1176/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1176/detail/PR-1176/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1176/detail/PR-1176/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_1176.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #1176 opened`



* Start Time: 2021-06-22T15:41:20.313+0000


* Duration: 13 min 4 sec


* Commit: fe07878b6a6e65f074dc21f442d51d780ac15405



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 16  |
| Skipped      | 0 |
| Total        | 16   |


#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/PR-1176/buildTimeGraph/png)


![Image of Tests](https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/PR-1176/1/testReport/history/countGraph/png?start=0&amp;end=25)


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2021-06-29 19:20 UTC, andrewkroh approved these changes
LGTM. This is a good start. I know there are more configuration options that we will want to expose in the future like `include_raw_certificates` for TLS, etc.

2021-06-29 19:20 UTC, andrewkroh commented on packages/network_traffic/data_stream/amqp/manifest.yml
> +        # currently the Kibana UI doesn't support multi inputs
Is there an issue for this that you can link to in the comment. Then it will be clear when we can start allowing numeric mutli-inputs.

2021-06-29 19:21 UTC, andrewstucki commented on packages/network_traffic/data_stream/amqp/manifest.yml
> +        # currently the Kibana UI doesn't support multi inputs
I'll create one and link it

2021-06-29 20:30 UTC, leehinman requested changes
Looks good.

Do you think there is value in adding `Tags` as a variable?

2021-06-29 20:30 UTC, leehinman commented on packages/network_traffic/manifest.yml
> +            show_user: false
might be good to add a `description` that says what happens if you don't specify the interface (any interface or no interface?)  Do we want to expose that you could give a filename here for pcap files?

2021-06-29 20:32 UTC, leehinman approved these changes

2021-06-29 20:37 UTC, andrewstucki commented on packages/network_traffic/manifest.yml
> +            show_user: false
> might be good to add a description that says what happens if you don't specify the interface (any interface or no interface?)

I'll try and come up with something for the description, felt the need to, but wasn't sure what to put since it's not super simple -- it actually follows the logic of Packetbeat's default template which is:
- Mac OS X: `en0`
- Linux: `any`
- Windows: whatever the first interface is 😅 

> Do we want to expose that you could give a filename here for pcap files?

I think I'd probably want to avoid adding that, mainly because I don't see a good use-case for 99.99% of users to add a pcap file as the thing to read from.

2021-07-12 16:07 UTC, andrewstucki commented
I'm going to go ahead and just merge this so it doesn't sit out any longer, will add the descriptions and comments to an issue link in a follow-up PR. Still have additional dashboards to add and potentially some installation lifecycle management stuff to work out before this goes primetime anyway.

2021-07-12 16:07 UTC, merged

2023-08-21 10:51 UTC, elasticmachine commented
Package cloud_security_posture - 1.5.0 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture