[O11y][MySQL] Update README to clarify the supported setup information for replica_status data stream
elastic/integrations pull request #11861
Opened 2024-11-25 10:15 UTC by harnish-elastic

- Enhancement

## Proposed commit message

- Update README to clarify the supported setup information for replica_status data stream

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).
- [x] I have verified that any added dashboard complies with Kibana's [Dashboard good practices](https://docs.elastic.dev/ux-guidelines/data-viz/dashboard-good-practices) 

## Related issues

- Closes #11826

2024-11-25 10:50 UTC, shmsr requested changes

2024-11-25 10:50 UTC, shmsr commented on packages/mysql/_dev/build/docs/README.md
> +- `replica_status` data stream is currently supporting master-slave or master-replica replication configurations as specified in the [MySQL Replication Configuration](https://dev.mysql.com/doc/refman
```suggestion
- The `replica_status` data stream supports master-slave or master-replica replication configurations as specified in the [MySQL Replication Configuration](https://dev.mysql.com/doc/refman/8.4/en/replication-configuration.html) documentation.
```

2024-11-25 10:50 UTC, shmsr commented on packages/mysql/docs/README.md
> +- `replica_status` data stream is currently supporting master-slave or master-replica replication configurations as specified in the [MySQL Replication Configuration](https://dev.mysql.com/doc/refman
```suggestion
- The `replica_status` data stream supports master-slave or master-replica replication configurations as specified in the [MySQL Replication Configuration](https://dev.mysql.com/doc/refman/8.4/en/replication-configuration.html) documentation.
```

2024-11-25 10:50 UTC, shmsr commented on packages/mysql/changelog.yml
> +    - description: Update README to clarify the setup information for replica_status data stream.
```suggestion
    - description: Update README to clarify the setup information for `replica_status` data stream.
```

2024-11-25 10:55 UTC, shmsr approved these changes

2024-11-25 10:58 UTC, shmsr commented
Oh wait. You have referenced MySQL 8.4 docs. But if you see the supported versions:

> |replica_status|`5.7`,`8.0.22`|`10.4`,`10.5.1`|`5.7`,`8.0.22`|

Max supported is 8.0.22 in our package. Can you quickly if nothing changed much between 8.0.x and 8.4.x

2024-11-25 11:28 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/18660)
* Commit: 780cdf3c49ca450c15d9af3a436f20ba729c92b3

### History
* :green_heart: [Build #18657](https://buildkite.com/elastic/integrations/builds/18657) succeeded 015bfd43b5c3a0510f40689d5edbe9f28b3d2cc6

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18660","number":18660,"commit":"780cdf3c49ca450c15d9af3a436f20ba729c92b3"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18657","number":18657,"commit":"015bfd43b5c3a0510f40689d5edbe9f28b3d2cc6"}],"number":18660}
buildkite-pr-comment-->

2024-11-26 05:52 UTC, harnish-elastic commented
> Oh wait. You have referenced MySQL 8.4 docs. But if you see the supported versions:
> 
> > |replica_status|`5.7`,`8.0.22`|`10.4`,`10.5.1`|`5.7`,`8.0.22`|
> 
> Max supported is 8.0.22 in our package. Can you quickly check if nothing changed much between 8.0.x and 8.4.x?

@shmsr Checked, no major updates between 8.0.x and 8.4.x, thanks!

2024-11-27 05:46 UTC, merged