aws_bedrock: retain contextualGroundingPolicy check details
elastic/integrations pull request #11890
Opened 2024-11-27 08:22 UTC by efd6

## Proposed commit message

See title.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).
- [ ] I have verified that any added dashboard complies with Kibana's [Dashboard good practices](https://docs.elastic.dev/ux-guidelines/data-viz/dashboard-good-practices) 

## Author's Checklist

- [ ] 

## How to test this PR locally

## Related issues

- Closes #11809

## Screenshots

2024-11-27 08:43 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/18755)
* Commit: be801ece6d962ed832afe3264a95f4713cbc912c

cc @efd6

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18755","number":18755,"commit":"be801ece6d962ed832afe3264a95f4713cbc912c"}],"number":18755}
buildkite-pr-comment-->

2024-11-27 08:55 UTC, elasticmachine commented
Pinging @elastic/security-service-integrations (Team:Security-Service Integrations)

2024-11-27 11:27 UTC, shashank-elastic approved these changes
Filed mapping correction looks good

2024-11-27 14:24 UTC, chrisberkhout commented
It looks like we should be looking at `body.trace.guardrail.outputAssessments` in general, since we are looking at `body.amazon_bedrock_trace.guardrail.outputs`. I probably should have done that in my last change, which started looking at outputs.

If that's added, then the other change is to expand which details objects get added to `gen_ai.policy.match_detail`.

What do you think about this version? The test output is slightly different.
```diff
--- a/packages/aws_bedrock/data_stream/invocation/elasticsearch/ingest_pipeline/default.yml
+++ b/packages/aws_bedrock/data_stream/invocation/elasticsearch/ingest_pipeline/default.yml
@@ -170,6 +170,7 @@ processors:
         "topicPolicy": "topic_policy"
         "customWords": "custom_words"
         "sensitiveInformationPolicy": "sensitive_information_policy"
+        "contextualGroundingPolicy": "contextual_grounding_policy"
         "invocationMetrics": "invocation_metrics"
         "guardrailCoverage": "guardrail_coverage"
         "textCharacters": "text_characters"
@@ -356,6 +357,7 @@ processors:
           )
           .flatMap(body -> [
             [body.trace?.guardrail?.inputAssessment],
+            body.trace?.guardrail?.outputAssessments,
             [body.amazon_bedrock_trace?.guardrail?.input],
             body.amazon_bedrock_trace?.guardrail?.outputs
           ].stream())
@@ -404,7 +406,7 @@ processors:
           .collect(Collectors.toList());
 
         ctx.gen_ai.policy.match_detail = nameAndDetailsOfPolicies.stream()
-          .filter(policy -> policy.details.match != null)
+          .filter(policy -> policy.details.match != null || policy.name == 'contextual_grounding_policy')
           .map(policy -> policy.details)
           .distinct()  // no sort because HashMap isn't Comparable
           .collect(Collectors.toList());
```

2024-11-27 14:27 UTC, chrisberkhout reviewed
It looks like we should be looking at `body.trace.guardrail.outputAssessments` in general, since we are looking at `body.amazon_bedrock_trace.guardrail.outputs`. I probably should have done that in my last change, which started looking at outputs.

If that's added, then the other change is to expand which details objects get added to `gen_ai.policy.match_detail`.

What do you think about this version? The test output is slightly different.
```diff
--- a/packages/aws_bedrock/data_stream/invocation/elasticsearch/ingest_pipeline/default.yml
+++ b/packages/aws_bedrock/data_stream/invocation/elasticsearch/ingest_pipeline/default.yml
@@ -170,6 +170,7 @@ processors:
         "topicPolicy": "topic_policy"
         "customWords": "custom_words"
         "sensitiveInformationPolicy": "sensitive_information_policy"
+        "contextualGroundingPolicy": "contextual_grounding_policy"
         "invocationMetrics": "invocation_metrics"
         "guardrailCoverage": "guardrail_coverage"
         "textCharacters": "text_characters"
@@ -356,6 +357,7 @@ processors:
           )
           .flatMap(body -> [
             [body.trace?.guardrail?.inputAssessment],
+            body.trace?.guardrail?.outputAssessments,
             [body.amazon_bedrock_trace?.guardrail?.input],
             body.amazon_bedrock_trace?.guardrail?.outputs
           ].stream())
@@ -404,7 +406,7 @@ processors:
           .collect(Collectors.toList());
 
         ctx.gen_ai.policy.match_detail = nameAndDetailsOfPolicies.stream()
-          .filter(policy -> policy.details.match != null)
+          .filter(policy -> policy.details.match != null || policy.name == 'contextual_grounding_policy')
           .map(policy -> policy.details)
           .distinct()  // no sort because HashMap isn't Comparable
           .collect(Collectors.toList());
```

2024-11-27 21:35 UTC, efd6 commented
Yeah, I think that's good. The changes that I see in the test expectation actually fix concerns that I had with the current behaviour, so that is nice. Will wait for @shashank-elastic's input though.

2024-11-27 21:56 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/18811)
* Commit: 687d504f666b086695ea82273f4c12baea22db59

### History
* :green_heart: [Build #18755](https://buildkite.com/elastic/integrations/builds/18755) succeeded be801ece6d962ed832afe3264a95f4713cbc912c

cc @efd6

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18811","number":18811,"commit":"687d504f666b086695ea82273f4c12baea22db59"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18755","number":18755,"commit":"be801ece6d962ed832afe3264a95f4713cbc912c"}],"number":18811}
buildkite-pr-comment-->

2024-11-28 09:09 UTC, chrisberkhout requested changes

2024-11-28 09:09 UTC, chrisberkhout commented on packages/aws_bedrock/data_stream/invocation/elasticsearch/ingest_pipeline/default.yml
> +        .collect(Collectors.toList());
My diff was on `main` version of this file, so this part would just be:

```suggestion
        ctx.gen_ai.policy.match_detail = nameAndDetailsOfPolicies.stream()
          .filter(policy -> policy.details.match != null || policy.name == 'contextual_grounding_policy')
          .map(policy -> policy.details)
          .distinct()  // no sort because HashMap isn't Comparable
          .collect(Collectors.toList());
```

Currently the 2nd part of the concat generates nothing because it uses the camel case name `contextualGroundingPolicy`.

2024-11-28 10:15 UTC, efd6 commented on packages/aws_bedrock/data_stream/invocation/elasticsearch/ingest_pipeline/default.yml
> +        .collect(Collectors.toList());
Thanks for clarifying, I missed that. Much nicer.

2024-11-28 10:31 UTC, chrisberkhout approved these changes

2024-11-28 10:40 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/18838)
* Commit: 188311dbd563de93940cbfb88e69e3478a5c6134

### History
* :green_heart: [Build #18811](https://buildkite.com/elastic/integrations/builds/18811) succeeded 687d504f666b086695ea82273f4c12baea22db59
* :green_heart: [Build #18755](https://buildkite.com/elastic/integrations/builds/18755) succeeded be801ece6d962ed832afe3264a95f4713cbc912c

cc @efd6

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18838","number":18838,"commit":"188311dbd563de93940cbfb88e69e3478a5c6134"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18811","number":18811,"commit":"687d504f666b086695ea82273f4c12baea22db59"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/18755","number":18755,"commit":"be801ece6d962ed832afe3264a95f4713cbc912c"}],"number":18838}
buildkite-pr-comment-->

2024-11-28 10:41 UTC, merged