Add ELB Connection logs dashboard
elastic/integrations pull request #12030
Opened 2024-12-09 11:03 UTC by agithomas

- Enhancement

## Proposed commit message

AWS ELB dataset supports connection logs of the Application load balancers. Create a dashboard for visualising key metrics and information of connection logs

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).
- [ ] I have verified that any added dashboard complies with Kibana's [Dashboard good practices](https://docs.elastic.dev/ux-guidelines/data-viz/dashboard-good-practices) 

## Author's Checklist

- [x] Testing of the dashboard with version 8.16.0 and 8.16.1
- [x] Testing of the dashboard content with data from pipeline tests as well as from real ALB data. 

## How to test this PR locally

- elastic-package build
- elastic-package stack up -v -d --services package-registry
- Perform package upgrade

## Related issues

- Relates https://github.com/elastic/integrations/issues/11770

## Screenshots

<img width="2560" alt="Screenshot 2024-12-05 at 10 43 19 AM" src="https://github.com/user-attachments/assets/ec9288af-e3f8-4828-b168-a5e5fc7cbe34">

------

<img width="2553" alt="aws-load-balancer-overview" src="https://github.com/user-attachments/assets/ec0a0699-a33f-4035-8b1c-2ed682dbbc06">

2024-12-10 07:12 UTC, harnish-elastic commented on packages/aws/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/1
```suggestion
      link: https://github.com/elastic/integrations/pull/12030
```

2024-12-10 07:16 UTC, harnish-elastic commented on packages/aws/img/filebeat-aws-alb-connection-overview.png
Can we show `failed` connection request status as red color in `Connection Request Status` chart?

2024-12-10 07:17 UTC, agithomas commented on packages/aws/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/1
Addressed. Thanks

2024-12-10 07:25 UTC, harnish-elastic commented on packages/aws/img/filebeat-aws-alb-connection-overview.png
Minor suggestion:

Can we update the title from `Certificate Expired and Expiring in 30 days` to `Certificate Expired or Expiring in 30 days`?

2024-12-10 07:26 UTC, harnish-elastic requested changes
Minor nits given!

2024-12-10 08:50 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/19268)
* Commit: 3ab2f41739eacf6a99d5fca79e12c1ad06bc23d6

### History
* :green_heart: [Build #19214](https://buildkite.com/elastic/integrations/builds/19214) succeeded 7e35dd145267e13d6313a9ad668f5b36718a2cd6

cc @agithomas

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19268","number":19268,"commit":"3ab2f41739eacf6a99d5fca79e12c1ad06bc23d6"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19214","number":19214,"commit":"7e35dd145267e13d6313a9ad668f5b36718a2cd6"}],"number":19268}
buildkite-pr-comment-->

2024-12-10 11:46 UTC, agithomas commented on packages/aws/img/filebeat-aws-alb-connection-overview.png
Updated as suggested.

2024-12-10 11:46 UTC, agithomas commented on packages/aws/img/filebeat-aws-alb-connection-overview.png
Updated as suggested.

2024-12-10 13:01 UTC, harnish-elastic approved these changes

2024-12-10 13:21 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/19280)
* Commit: fcb24bfb67582ef80c33c3439c47d6cf4156b87b

### History
* :green_heart: [Build #19268](https://buildkite.com/elastic/integrations/builds/19268) succeeded 3ab2f41739eacf6a99d5fca79e12c1ad06bc23d6
* :green_heart: [Build #19214](https://buildkite.com/elastic/integrations/builds/19214) succeeded 7e35dd145267e13d6313a9ad668f5b36718a2cd6

cc @agithomas

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19280","number":19280,"commit":"fcb24bfb67582ef80c33c3439c47d6cf4156b87b"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19268","number":19268,"commit":"3ab2f41739eacf6a99d5fca79e12c1ad06bc23d6"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19214","number":19214,"commit":"7e35dd145267e13d6313a9ad668f5b36718a2cd6"}],"number":19280}
buildkite-pr-comment-->

2024-12-11 04:53 UTC, muthu-mps commented
@agithomas - Why the latency is shown in metric chart? Is it possible to visualise the latency in line chart?

2024-12-11 07:25 UTC, agithomas commented
> @agithomas - Why the latency is shown in metric chart? Is it possible to visualise the latency in line chart?

Updated as suggested.

2024-12-11 07:38 UTC, muthu-mps approved these changes
LGTM!

2024-12-11 09:05 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/19342)
* Commit: e07cbf5c50c31fffdb4a2b785d70c48c0bf8c46c

### History
* :green_heart: [Build #19280](https://buildkite.com/elastic/integrations/builds/19280) succeeded fcb24bfb67582ef80c33c3439c47d6cf4156b87b
* :green_heart: [Build #19268](https://buildkite.com/elastic/integrations/builds/19268) succeeded 3ab2f41739eacf6a99d5fca79e12c1ad06bc23d6
* :green_heart: [Build #19214](https://buildkite.com/elastic/integrations/builds/19214) succeeded 7e35dd145267e13d6313a9ad668f5b36718a2cd6

cc @agithomas

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19342","number":19342,"commit":"e07cbf5c50c31fffdb4a2b785d70c48c0bf8c46c"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19280","number":19280,"commit":"fcb24bfb67582ef80c33c3439c47d6cf4156b87b"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19268","number":19268,"commit":"3ab2f41739eacf6a99d5fca79e12c1ad06bc23d6"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19214","number":19214,"commit":"7e35dd145267e13d6313a9ad668f5b36718a2cd6"}],"number":19342}
buildkite-pr-comment-->

2024-12-11 09:13 UTC, merged