ssi_all: do not remove event.original in main ingest pipeline
elastic/integrations pull request #12076
Opened 2024-12-11 23:24 UTC by efd6

## Proposed commit message

See title.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).
- [ ] I have verified that any added dashboard complies with Kibana's [Dashboard good practices](https://docs.elastic.dev/ux-guidelines/data-viz/dashboard-good-practices) 

## Author's Checklist

- [ ] 

## How to test this PR locally

## Related issues

- For #12046

## Screenshots

2024-12-11 23:45 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/19381)
* Commit: cbd28ebcd805f0d3546ae6863a2498f8f82b48dd

### Failed CI Steps
* [Check integrations okta](https://buildkite.com/elastic/integrations/builds/19381#0193b818-6af3-4ba2-b55c-d94424e1bf1f)

cc @efd6

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19381","number":19381,"commit":"cbd28ebcd805f0d3546ae6863a2498f8f82b48dd"}],"number":19381}
buildkite-pr-comment-->

2024-12-11 23:57 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/19382)
* Commit: c890e5eab1c0634ec8ad40bca25e7b98b0f45e40

### Failed CI Steps
* [Check integrations okta](https://buildkite.com/elastic/integrations/builds/19382#0193b823-38a2-4b17-b8a2-7f241595f1d5)

### History
* :broken_heart: [Build #19381](https://buildkite.com/elastic/integrations/builds/19381) failed cbd28ebcd805f0d3546ae6863a2498f8f82b48dd

cc @efd6

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19382","number":19382,"commit":"c890e5eab1c0634ec8ad40bca25e7b98b0f45e40"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19381","number":19381,"commit":"cbd28ebcd805f0d3546ae6863a2498f8f82b48dd"}],"number":19382}
buildkite-pr-comment-->

2024-12-12 00:38 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/19383)
* Commit: 0a51a0e3875fcf038db51e776319e6e73bf2744d

### Failed CI Steps
* [Check integrations okta](https://buildkite.com/elastic/integrations/builds/19383#0193b848-e59e-4a4d-a5b3-0d0ab38d5840)

### History
* :broken_heart: [Build #19382](https://buildkite.com/elastic/integrations/builds/19382) failed c890e5eab1c0634ec8ad40bca25e7b98b0f45e40
* :broken_heart: [Build #19381](https://buildkite.com/elastic/integrations/builds/19381) failed cbd28ebcd805f0d3546ae6863a2498f8f82b48dd

cc @efd6

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19383","number":19383,"commit":"0a51a0e3875fcf038db51e776319e6e73bf2744d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19382","number":19382,"commit":"c890e5eab1c0634ec8ad40bca25e7b98b0f45e40"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19381","number":19381,"commit":"cbd28ebcd805f0d3546ae6863a2498f8f82b48dd"}],"number":19383}
buildkite-pr-comment-->

2024-12-12 01:19 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/19384)
* Commit: 66186a21b998e161794c6864622d9d5f7062cc8c

### Failed CI Steps
* [Check integrations okta](https://buildkite.com/elastic/integrations/builds/19384#0193b86a-eecf-4cb6-be6b-63db926638b5)

### History
* :broken_heart: [Build #19383](https://buildkite.com/elastic/integrations/builds/19383) failed 0a51a0e3875fcf038db51e776319e6e73bf2744d
* :broken_heart: [Build #19382](https://buildkite.com/elastic/integrations/builds/19382) failed c890e5eab1c0634ec8ad40bca25e7b98b0f45e40
* :broken_heart: [Build #19381](https://buildkite.com/elastic/integrations/builds/19381) failed cbd28ebcd805f0d3546ae6863a2498f8f82b48dd

cc @efd6

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19384","number":19384,"commit":"66186a21b998e161794c6864622d9d5f7062cc8c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19383","number":19383,"commit":"0a51a0e3875fcf038db51e776319e6e73bf2744d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19382","number":19382,"commit":"c890e5eab1c0634ec8ad40bca25e7b98b0f45e40"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19381","number":19381,"commit":"cbd28ebcd805f0d3546ae6863a2498f8f82b48dd"}],"number":19384}
buildkite-pr-comment-->

2024-12-12 03:07 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/19389)
* Commit: e40fac2bacf9ec749ad5f76f5c75242cf661f90b

### History
* :broken_heart: [Build #19384](https://buildkite.com/elastic/integrations/builds/19384) failed 66186a21b998e161794c6864622d9d5f7062cc8c
* :broken_heart: [Build #19383](https://buildkite.com/elastic/integrations/builds/19383) failed 0a51a0e3875fcf038db51e776319e6e73bf2744d
* :broken_heart: [Build #19382](https://buildkite.com/elastic/integrations/builds/19382) failed c890e5eab1c0634ec8ad40bca25e7b98b0f45e40
* :broken_heart: [Build #19381](https://buildkite.com/elastic/integrations/builds/19381) failed cbd28ebcd805f0d3546ae6863a2498f8f82b48dd

cc @efd6

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19389","number":19389,"commit":"e40fac2bacf9ec749ad5f76f5c75242cf661f90b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19384","number":19384,"commit":"66186a21b998e161794c6864622d9d5f7062cc8c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19383","number":19383,"commit":"0a51a0e3875fcf038db51e776319e6e73bf2744d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19382","number":19382,"commit":"c890e5eab1c0634ec8ad40bca25e7b98b0f45e40"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19381","number":19381,"commit":"cbd28ebcd805f0d3546ae6863a2498f8f82b48dd"}],"number":19389}
buildkite-pr-comment-->

2024-12-12 03:14 UTC, elasticmachine commented
Pinging @elastic/security-service-integrations (Team:Security-Service Integrations)

2024-12-12 15:58 UTC, chrisberkhout requested changes
These changes look good.

Why was `okta` (owned by SSI) backed out?

Looking for `preserve_original_event` in SSI integrations I found...

Some were missed: `gcp` (because co-owned?) and `google_workspace` (owned by SSI).

Other relevant changes would be to remove the conditions in these:
- https://github.com/elastic/integrations/blob/e40fac2bacf9ec749ad5f76f5c75242cf661f90b/packages/falco/data_stream/alerts/elasticsearch/ingest_pipeline/default.yml#L7-L11
- https://github.com/elastic/integrations/blob/e40fac2bacf9ec749ad5f76f5c75242cf661f90b/packages/qualys_vmdr/data_stream/knowledge_base/elasticsearch/ingest_pipeline/default.yml#L772-L777
- https://github.com/elastic/integrations/blob/e40fac2bacf9ec749ad5f76f5c75242cf661f90b/packages/qualys_vmdr/data_stream/asset_host_detection/elasticsearch/ingest_pipeline/default.yml#L1388-L1393

Also, off-topic, but the condition is wrong here:
- https://github.com/elastic/integrations/blob/e40fac2bacf9ec749ad5f76f5c75242cf661f90b/packages/mimecast/data_stream/audit_events/elasticsearch/ingest_pipeline/default.yml#L347-L351

2024-12-12 20:04 UTC, efd6 commented on packages/forgerock/data_stream/am_access/_dev/test/pipeline/test-am-access.log-expected.json
> +                "original": "{\"payload\":{\"_id\":\"45463f84-ff1b-499f-aa84-8d4bd93150de-256203\",\"client\":{\"ip\":\"1.128.0.0\"},\"component\":\"OAuth\",\"eventName\":\"AM-ACCESS-ATTEMPT\",\"http
Yes, this is expected.

2024-12-12 20:04 UTC, efd6 commented
On deletion of the remove processor, elastic-package complains that the following remove processor requires an `if` attribute. This is incorrect, so I have omitted that change until the issue there is resolved.

google_workspace is omitted due to unrelated build failures.

2024-12-12 20:20 UTC, efd6 commented
For the mimecast issue noted in the PR comment. I don't know exactly what is going on there. I suspect that this is actually intended to be a remove of the `event.original` field, not the `source.ip` field given its location and the `source.ip` is never set.

I'll deal with that in a separate PR.

2024-12-12 20:31 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/19425)
* Commit: fd429653658d78316888ea18a69c3dc96635ddc9

### Failed CI Steps
* [Check integrations falco](https://buildkite.com/elastic/integrations/builds/19425#0193bc89-ad94-4ba9-ab9c-344c99247e6c)

### History
* :green_heart: [Build #19389](https://buildkite.com/elastic/integrations/builds/19389) succeeded e40fac2bacf9ec749ad5f76f5c75242cf661f90b
* :broken_heart: [Build #19384](https://buildkite.com/elastic/integrations/builds/19384) failed 66186a21b998e161794c6864622d9d5f7062cc8c
* :broken_heart: [Build #19383](https://buildkite.com/elastic/integrations/builds/19383) failed 0a51a0e3875fcf038db51e776319e6e73bf2744d
* :broken_heart: [Build #19382](https://buildkite.com/elastic/integrations/builds/19382) failed c890e5eab1c0634ec8ad40bca25e7b98b0f45e40
* :broken_heart: [Build #19381](https://buildkite.com/elastic/integrations/builds/19381) failed cbd28ebcd805f0d3546ae6863a2498f8f82b48dd

cc @efd6

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19425","number":19425,"commit":"fd429653658d78316888ea18a69c3dc96635ddc9"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19389","number":19389,"commit":"e40fac2bacf9ec749ad5f76f5c75242cf661f90b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19384","number":19384,"commit":"66186a21b998e161794c6864622d9d5f7062cc8c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19383","number":19383,"commit":"0a51a0e3875fcf038db51e776319e6e73bf2744d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19382","number":19382,"commit":"c890e5eab1c0634ec8ad40bca25e7b98b0f45e40"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19381","number":19381,"commit":"cbd28ebcd805f0d3546ae6863a2498f8f82b48dd"}],"number":19425}
buildkite-pr-comment-->

2024-12-12 21:11 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/19428)
* Commit: b643b908fe97606f5a731efafcd04f5824cea4f6

### History
* :broken_heart: [Build #19425](https://buildkite.com/elastic/integrations/builds/19425) failed fd429653658d78316888ea18a69c3dc96635ddc9
* :green_heart: [Build #19389](https://buildkite.com/elastic/integrations/builds/19389) succeeded e40fac2bacf9ec749ad5f76f5c75242cf661f90b
* :broken_heart: [Build #19384](https://buildkite.com/elastic/integrations/builds/19384) failed 66186a21b998e161794c6864622d9d5f7062cc8c
* :broken_heart: [Build #19383](https://buildkite.com/elastic/integrations/builds/19383) failed 0a51a0e3875fcf038db51e776319e6e73bf2744d
* :broken_heart: [Build #19382](https://buildkite.com/elastic/integrations/builds/19382) failed c890e5eab1c0634ec8ad40bca25e7b98b0f45e40
* :broken_heart: [Build #19381](https://buildkite.com/elastic/integrations/builds/19381) failed cbd28ebcd805f0d3546ae6863a2498f8f82b48dd

cc @efd6

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19428","number":19428,"commit":"b643b908fe97606f5a731efafcd04f5824cea4f6"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19425","number":19425,"commit":"fd429653658d78316888ea18a69c3dc96635ddc9"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19389","number":19389,"commit":"e40fac2bacf9ec749ad5f76f5c75242cf661f90b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19384","number":19384,"commit":"66186a21b998e161794c6864622d9d5f7062cc8c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19383","number":19383,"commit":"0a51a0e3875fcf038db51e776319e6e73bf2744d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19382","number":19382,"commit":"c890e5eab1c0634ec8ad40bca25e7b98b0f45e40"}],"number":19428}
buildkite-pr-comment-->

2024-12-13 04:47 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/19446)
* Commit: fc0d982b918f74e6a9abfb868f72b4b67e6cdbdb

### History
* :green_heart: [Build #19428](https://buildkite.com/elastic/integrations/builds/19428) succeeded b643b908fe97606f5a731efafcd04f5824cea4f6
* :broken_heart: [Build #19425](https://buildkite.com/elastic/integrations/builds/19425) failed fd429653658d78316888ea18a69c3dc96635ddc9
* :green_heart: [Build #19389](https://buildkite.com/elastic/integrations/builds/19389) succeeded e40fac2bacf9ec749ad5f76f5c75242cf661f90b
* :broken_heart: [Build #19384](https://buildkite.com/elastic/integrations/builds/19384) failed 66186a21b998e161794c6864622d9d5f7062cc8c
* :broken_heart: [Build #19383](https://buildkite.com/elastic/integrations/builds/19383) failed 0a51a0e3875fcf038db51e776319e6e73bf2744d
* :broken_heart: [Build #19382](https://buildkite.com/elastic/integrations/builds/19382) failed c890e5eab1c0634ec8ad40bca25e7b98b0f45e40

cc @efd6

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19446","number":19446,"commit":"fc0d982b918f74e6a9abfb868f72b4b67e6cdbdb"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19428","number":19428,"commit":"b643b908fe97606f5a731efafcd04f5824cea4f6"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19425","number":19425,"commit":"fd429653658d78316888ea18a69c3dc96635ddc9"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19389","number":19389,"commit":"e40fac2bacf9ec749ad5f76f5c75242cf661f90b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19384","number":19384,"commit":"66186a21b998e161794c6864622d9d5f7062cc8c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19383","number":19383,"commit":"0a51a0e3875fcf038db51e776319e6e73bf2744d"}],"number":19446}
buildkite-pr-comment-->

2024-12-13 08:39 UTC, chrisberkhout approved these changes

2024-12-13 08:52 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/19461)
* Commit: b3e8baec37c3bdd9d96cbb42ad9a08a285dd7f88

### History
* :green_heart: [Build #19446](https://buildkite.com/elastic/integrations/builds/19446) succeeded fc0d982b918f74e6a9abfb868f72b4b67e6cdbdb
* :green_heart: [Build #19428](https://buildkite.com/elastic/integrations/builds/19428) succeeded b643b908fe97606f5a731efafcd04f5824cea4f6
* :broken_heart: [Build #19425](https://buildkite.com/elastic/integrations/builds/19425) failed fd429653658d78316888ea18a69c3dc96635ddc9
* :green_heart: [Build #19389](https://buildkite.com/elastic/integrations/builds/19389) succeeded e40fac2bacf9ec749ad5f76f5c75242cf661f90b
* :broken_heart: [Build #19384](https://buildkite.com/elastic/integrations/builds/19384) failed 66186a21b998e161794c6864622d9d5f7062cc8c
* :broken_heart: [Build #19383](https://buildkite.com/elastic/integrations/builds/19383) failed 0a51a0e3875fcf038db51e776319e6e73bf2744d

cc @efd6

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19461","number":19461,"commit":"b3e8baec37c3bdd9d96cbb42ad9a08a285dd7f88"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19446","number":19446,"commit":"fc0d982b918f74e6a9abfb868f72b4b67e6cdbdb"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19428","number":19428,"commit":"b643b908fe97606f5a731efafcd04f5824cea4f6"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19425","number":19425,"commit":"fd429653658d78316888ea18a69c3dc96635ddc9"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19389","number":19389,"commit":"e40fac2bacf9ec749ad5f76f5c75242cf661f90b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19384","number":19384,"commit":"66186a21b998e161794c6864622d9d5f7062cc8c"}],"number":19461}
buildkite-pr-comment-->

2024-12-13 09:07 UTC, merged