ti_custom: Improve pagination options for TAXII servers
elastic/integrations pull request #12084
Opened 2024-12-12 19:02 UTC by chemamartinez

## Proposed commit message

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).
- [ ] I have verified that any added dashboard complies with Kibana's [Dashboard good practices](https://docs.elastic.dev/ux-guidelines/data-viz/dashboard-good-practices)

2024-12-12 19:07 UTC, elasticmachine commented
Pinging @elastic/security-service-integrations (Team:Security-Service Integrations)

2024-12-12 19:24 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/19423)
* Commit: d2c27c9854035d6cf31ee7d1a9d65aec1bdb9e6a

cc @chemamartinez

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19423","number":19423,"commit":"d2c27c9854035d6cf31ee7d1a9d65aec1bdb9e6a"}],"number":19423}
buildkite-pr-comment-->

2024-12-13 15:14 UTC, chrisberkhout requested changes
The change is good.

You can use `optMap`, etc. to handle optional values in a more streamlined way.

I think that's better at least for the simpler examples. Maybe not worth it for the more complicated one.

2024-12-13 15:14 UTC, chrisberkhout commented on packages/ti_custom/data_stream/indicator/agent/stream/cel.yml.hbs
> +                                optional.none(),
```suggestion
                        ?"added_after": state.?cursor.last_timestamp.optMap(ts,
                            [ts]
                        ).or(
                            state.?initial_interval.optMap(i, [(now() - duration(i)).format(time_layout.RFC3339)])
                        ),

```
Using the the optional types more here works, but is less helpful than the other cases.

Alternative formatting:
```suggestion
                        ?"added_after": state.?cursor.last_timestamp.optMap(ts, [ts]).or(
                            state.?initial_interval.optMap(i, [(now() - duration(i)).format(time_layout.RFC3339)])
                        ),

```

2024-12-17 11:20 UTC, chrisberkhout requested changes
one thing left in by mistake

2024-12-17 11:20 UTC, chrisberkhout commented on packages/ti_custom/data_stream/indicator/agent/stream/cel.yml.hbs
> +                                optional.none(),
For `added_after`, if you want to keep the `optMap` version then delete the original version.

2024-12-17 11:34 UTC, chemamartinez commented on packages/ti_custom/data_stream/indicator/agent/stream/cel.yml.hbs
> +                                optional.none(),
Yeah... left by mistake. Thank you for noticing it!

2024-12-17 11:44 UTC, chrisberkhout approved these changes

2024-12-17 12:09 UTC, merged

2025-01-30 15:11 UTC, AkodoGarou commented
Good Morning.

I found your integration, and it fits perfect into our TI feed for hashes with another server we have. But I'm running into an issue, where I'm getting a CEL error:

 failed eval: ERROR: <input>:32:22: no such key: objects
   |     ).do_request().as(resp, (resp.StatusCode == 200 || resp.StatusCode == 206) ?
   | .....................^,
  Processor "conditional" with tag "" in pipeline "logs-ti_custom.indicator-0.6.0" failed with message "Error during CEL program evaluation"

Is this where I need to set my CEL url location? And would that be changing the code that was commented out in the "The CEL program to be run for each polling." in settings? Any help would be appreciated.

2025-01-30 20:29 UTC, efd6 commented
@AkodoGarou From the error you have posted, you are likely using the built-in CEL program. What is happening is that the document being returned by the API endpoint does not contain a field "objects", which the program expects (you can see that [here](https://github.com/elastic/integrations/blob/661a312c6be43b2d0fe81789c42b7cda0ac0b117/packages/ti_custom/data_stream/indicator/agent/stream/cel.yml.hbs#L98)).

There is not enough information in your post to figure out what is going wrong for you, but this really should be a question in community slack or at https://discuss.elastic.co/. If you believe that it is a bug, please file an issue here.