Fix Asciidoc broken links (post migration)
elastic/integrations pull request #12145
Opened 2024-12-18 06:59 UTC by alaudazzi

This PR updates the following links to their final destination to prevent the AsciiDoc link checker from failing.

Change:

- [ ] Before: https://www.elastic.co/guide/en/observability/current/ingest-splunk.html
- [ ] After: https://www.elastic.co/guide/en/observability/current/splunk-get-started.html

Change:

- [ ] Before: https://www.elastic.co/guide/en/welcome-to-elastic/current/getting-started-observability.html
- [ ] After: https://www.elastic.co/guide/en/starting-with-the-elasticsearch-platform-and-its-solutions/current/getting-started-observability.html

2024-12-18 06:59 UTC, elasticmachine commented
Pinging @elastic/elastic-agent-data-plane (Team:Elastic-Agent-Data-Plane)

2024-12-18 06:59 UTC, elasticmachine commented
Pinging @elastic/sec-linux-platform (Team:Security-Linux Platform)

2024-12-18 06:59 UTC, elasticmachine commented
Pinging @elastic/security-service-integrations (Team:Security-Service Integrations)

2024-12-18 06:59 UTC, elasticmachine commented
Pinging @elastic/sec-windows-platform (Team:Security-Windows Platform)

2024-12-18 07:09 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/19641)
* Commit: e84a4d6415a6da3d50033dbb0752ba479873d7f0

### Failed CI Steps
* [Check integrations azure_metrics](https://buildkite.com/elastic/integrations/builds/19641#0193d895-059c-4fc9-828b-d5102ced9635)

cc @alaudazzi

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19641","number":19641,"commit":"e84a4d6415a6da3d50033dbb0752ba479873d7f0"}],"number":19641}
buildkite-pr-comment-->

2024-12-18 12:34 UTC, jsoriano commented on packages/activemq/_dev/build/docs/README.md
> +For step-by-step instructions on how to set up an integration, see the [Getting Started](https://www.elastic.co/guide/en/starting-with-the-elasticsearch-platform-and-its-solutions/current/getting-sta
@alaudazzi do you need these packages to be released with this change? If that's the case you will also need to add a changelog entry. You can do that by running the following command on each package directory:
```
elastic-package changelog add --description "Update links to getting started docs" --next patch --link https://github.com/elastic/integrations/issues/12145 --type enhancement
```

2024-12-18 16:14 UTC, chrisberkhout approved these changes
Looks good with the changelog/manifest updates as described by @jsoriano

2024-12-18 20:17 UTC, mjwolf commented
You'll need to run `elastic-package build` in each of the integration package directories that are failing in CI, to regenerate the readme, and fix the test failures like this one (from the logs of the failing test jobs):

```
README.md is outdated. Rebuild the package with 'elastic-package build'

want | 0s
  | got | 0s
  | @@ -205,3 +205,3 @@
  | For step-by-step instructions on how to set up an integration, see the
  | -[Getting started](https://www.elastic.co/guide/en/welcome-to-elastic/current/getting-started-observability.html) guide.
  | +[Getting started](https://www.elastic.co/guide/en/starting-with-the-elasticsearch-platform-and-its-solutions/current/getting-started-observability.html) guide.
 
```

2025-01-07 13:54 UTC, alaudazzi commented on packages/activemq/_dev/build/docs/README.md
> +For step-by-step instructions on how to set up an integration, see the [Getting Started](https://www.elastic.co/guide/en/starting-with-the-elasticsearch-platform-and-its-solutions/current/getting-sta
I'm on it

2025-01-07 15:29 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20094)
* Commit: 99d312245da31daab8552c23d5b47ca11199d935

### Failed CI Steps
* [Check integrations pps](https://buildkite.com/elastic/integrations/builds/20094#0194415b-18e1-4943-afd6-7890b2076226)

### History
* :broken_heart: [Build #19641](https://buildkite.com/elastic/integrations/builds/19641) failed e84a4d6415a6da3d50033dbb0752ba479873d7f0

cc @alaudazzi

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20094","number":20094,"commit":"99d312245da31daab8552c23d5b47ca11199d935"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19641","number":19641,"commit":"e84a4d6415a6da3d50033dbb0752ba479873d7f0"}],"number":20094}
buildkite-pr-comment-->

2025-01-08 08:52 UTC, zmoog approved these changes

2025-01-08 11:52 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20168)
* Commit: ea3ef38fb6cef540bbe648ac60ae6eadffcf43d4

### Failed CI Steps
* [Check integrations watchguard_firebox](https://buildkite.com/elastic/integrations/builds/20168#019445b9-9a8d-4fe7-9909-b85bec62ea29)

### History
* :broken_heart: [Build #20094](https://buildkite.com/elastic/integrations/builds/20094) failed 99d312245da31daab8552c23d5b47ca11199d935
* :broken_heart: [Build #19641](https://buildkite.com/elastic/integrations/builds/19641) failed e84a4d6415a6da3d50033dbb0752ba479873d7f0

cc @alaudazzi

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20168","number":20168,"commit":"ea3ef38fb6cef540bbe648ac60ae6eadffcf43d4"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20094","number":20094,"commit":"99d312245da31daab8552c23d5b47ca11199d935"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19641","number":19641,"commit":"e84a4d6415a6da3d50033dbb0752ba479873d7f0"}],"number":20168}
buildkite-pr-comment-->

2025-01-08 16:02 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20186)
* Commit: 8fae6c58882dc12c6da7f9b1c770a15916970ed0

### Failed CI Steps
* [Check integrations cisco_ise](https://buildkite.com/elastic/integrations/builds/20186#019446a2-5c6d-4deb-968a-07e9eedc6253)

### History
* :broken_heart: [Build #20168](https://buildkite.com/elastic/integrations/builds/20168) failed ea3ef38fb6cef540bbe648ac60ae6eadffcf43d4
* :broken_heart: [Build #20094](https://buildkite.com/elastic/integrations/builds/20094) failed 99d312245da31daab8552c23d5b47ca11199d935
* :broken_heart: [Build #19641](https://buildkite.com/elastic/integrations/builds/19641) failed e84a4d6415a6da3d50033dbb0752ba479873d7f0

cc @alaudazzi

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20186","number":20186,"commit":"8fae6c58882dc12c6da7f9b1c770a15916970ed0"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20168","number":20168,"commit":"ea3ef38fb6cef540bbe648ac60ae6eadffcf43d4"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20094","number":20094,"commit":"99d312245da31daab8552c23d5b47ca11199d935"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19641","number":19641,"commit":"e84a4d6415a6da3d50033dbb0752ba479873d7f0"}],"number":20186}
buildkite-pr-comment-->

2025-01-08 16:06 UTC, nfritts approved these changes

2025-01-08 18:03 UTC, jsoriano commented
/test

2025-01-09 04:54 UTC, shmsr approved these changes

2025-01-09 09:29 UTC, jrmolin requested changes
it's a really small mistake, but since it affects so many integrations, please fix it.

otherwise, looks fine.

2025-01-09 09:29 UTC, jrmolin commented on packages/activemq/changelog.yml
> +      link: https://github.com/elastic/integrations/issues/12145
this should be a link to this PR, which is `https://github.com/elastic/integrations/pull/12145` (notice the `pull` instead of `issues`)

2025-01-09 09:29 UTC, jrmolin commented on packages/activemq/changelog.yml
> +      link: https://github.com/elastic/integrations/issues/12145
hrm, well, that url auto-redirects to this PR, so I guess it's fine. I don't see that issue listed anywhere, though, so it's a bit confusing to me. Could you still change it, please?

2025-01-09 09:29 UTC, jrmolin commented on packages/activemq/changelog.yml
> +      link: https://github.com/elastic/integrations/issues/12145
This same incorrect URI shows up in every `changelog.yml` in this PR

2025-01-09 10:17 UTC, jsoriano commented on packages/activemq/changelog.yml
> +      link: https://github.com/elastic/integrations/issues/12145
Oops, sorry, my mistake, fixed in https://github.com/elastic/integrations/pull/12145

2025-01-09 10:41 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20215)
* Commit: 8b75e134ec1ea0d0b7fa4e6074530aa1bb5c3f06

### Failed CI Steps
* [Check integrations mysql](https://buildkite.com/elastic/integrations/builds/20215#01944a95-71cb-496a-809f-6b9a9691ddd0)

### History
* :broken_heart: [Build #20186](https://buildkite.com/elastic/integrations/builds/20186) failed 8fae6c58882dc12c6da7f9b1c770a15916970ed0
* :broken_heart: [Build #20168](https://buildkite.com/elastic/integrations/builds/20168) failed ea3ef38fb6cef540bbe648ac60ae6eadffcf43d4
* :broken_heart: [Build #20094](https://buildkite.com/elastic/integrations/builds/20094) failed 99d312245da31daab8552c23d5b47ca11199d935
* :broken_heart: [Build #19641](https://buildkite.com/elastic/integrations/builds/19641) failed e84a4d6415a6da3d50033dbb0752ba479873d7f0

cc @alaudazzi

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20215","number":20215,"commit":"8b75e134ec1ea0d0b7fa4e6074530aa1bb5c3f06"},{"buildStatus":{"state":"failed","success":false,"hasRetries":true,"hasNonPreemptionRetries":true},"url":"https://buildkite.com/elastic/integrations/builds/20186","number":20186,"commit":"8fae6c58882dc12c6da7f9b1c770a15916970ed0"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20168","number":20168,"commit":"ea3ef38fb6cef540bbe648ac60ae6eadffcf43d4"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20094","number":20094,"commit":"99d312245da31daab8552c23d5b47ca11199d935"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19641","number":19641,"commit":"e84a4d6415a6da3d50033dbb0752ba479873d7f0"}],"number":20215}
buildkite-pr-comment-->

2025-01-09 13:18 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20228)
* Commit: 8b75e134ec1ea0d0b7fa4e6074530aa1bb5c3f06

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/20228#01944b35-d68f-4651-b61d-a08ec63e9e52)

### History
* :broken_heart: [Build #20215](https://buildkite.com/elastic/integrations/builds/20215) failed 8b75e134ec1ea0d0b7fa4e6074530aa1bb5c3f06
* :broken_heart: [Build #20186](https://buildkite.com/elastic/integrations/builds/20186) failed 8fae6c58882dc12c6da7f9b1c770a15916970ed0
* :broken_heart: [Build #20168](https://buildkite.com/elastic/integrations/builds/20168) failed ea3ef38fb6cef540bbe648ac60ae6eadffcf43d4
* :broken_heart: [Build #20094](https://buildkite.com/elastic/integrations/builds/20094) failed 99d312245da31daab8552c23d5b47ca11199d935
* :broken_heart: [Build #19641](https://buildkite.com/elastic/integrations/builds/19641) failed e84a4d6415a6da3d50033dbb0752ba479873d7f0

cc @alaudazzi

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20228","number":20228,"commit":"8b75e134ec1ea0d0b7fa4e6074530aa1bb5c3f06"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20215","number":20215,"commit":"8b75e134ec1ea0d0b7fa4e6074530aa1bb5c3f06"},{"buildStatus":{"state":"failed","success":false,"hasRetries":true,"hasNonPreemptionRetries":true},"url":"https://buildkite.com/elastic/integrations/builds/20186","number":20186,"commit":"8fae6c58882dc12c6da7f9b1c770a15916970ed0"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20168","number":20168,"commit":"ea3ef38fb6cef540bbe648ac60ae6eadffcf43d4"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20094","number":20094,"commit":"99d312245da31daab8552c23d5b47ca11199d935"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19641","number":19641,"commit":"e84a4d6415a6da3d50033dbb0752ba479873d7f0"}],"number":20228}
buildkite-pr-comment-->

2025-01-09 14:17 UTC, chrisberkhout commented on packages/activemq/changelog.yml
> +      link: https://github.com/elastic/integrations/issues/12145
looks good now. resolving this one.

2025-01-09 14:20 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20233)
* Commit: a796d9e9ead1735637ee29a1ac970c0de731003f

### Failed CI Steps
* [Check integrations windows](https://buildkite.com/elastic/integrations/builds/20233#01944b6b-0658-4981-95b8-7704e96c2597)

### History
* :broken_heart: [Build #20228](https://buildkite.com/elastic/integrations/builds/20228) failed 8b75e134ec1ea0d0b7fa4e6074530aa1bb5c3f06
* :broken_heart: [Build #20215](https://buildkite.com/elastic/integrations/builds/20215) failed 8b75e134ec1ea0d0b7fa4e6074530aa1bb5c3f06
* :broken_heart: [Build #20186](https://buildkite.com/elastic/integrations/builds/20186) failed 8fae6c58882dc12c6da7f9b1c770a15916970ed0
* :broken_heart: [Build #20168](https://buildkite.com/elastic/integrations/builds/20168) failed ea3ef38fb6cef540bbe648ac60ae6eadffcf43d4
* :broken_heart: [Build #20094](https://buildkite.com/elastic/integrations/builds/20094) failed 99d312245da31daab8552c23d5b47ca11199d935
* :broken_heart: [Build #19641](https://buildkite.com/elastic/integrations/builds/19641) failed e84a4d6415a6da3d50033dbb0752ba479873d7f0

cc @alaudazzi

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20233","number":20233,"commit":"a796d9e9ead1735637ee29a1ac970c0de731003f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20228","number":20228,"commit":"8b75e134ec1ea0d0b7fa4e6074530aa1bb5c3f06"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20215","number":20215,"commit":"8b75e134ec1ea0d0b7fa4e6074530aa1bb5c3f06"},{"buildStatus":{"state":"failed","success":false,"hasRetries":true,"hasNonPreemptionRetries":true},"url":"https://buildkite.com/elastic/integrations/builds/20186","number":20186,"commit":"8fae6c58882dc12c6da7f9b1c770a15916970ed0"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20168","number":20168,"commit":"ea3ef38fb6cef540bbe648ac60ae6eadffcf43d4"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20094","number":20094,"commit":"99d312245da31daab8552c23d5b47ca11199d935"}],"number":20233}
buildkite-pr-comment-->

2025-01-09 14:35 UTC, jrmolin approved these changes
i looked at all of them, and they look good to me. thanks!

2025-01-09 14:39 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20234)
* Commit: 6124811447d85d83ebb6faf4c8d482fb8c09c74e

### Failed CI Steps
* [Check integrations windows](https://buildkite.com/elastic/integrations/builds/20234#01944b7c-4f2c-44e2-be55-2f5d73381acd)

### History
* :broken_heart: [Build #20233](https://buildkite.com/elastic/integrations/builds/20233) failed a796d9e9ead1735637ee29a1ac970c0de731003f
* :broken_heart: [Build #20228](https://buildkite.com/elastic/integrations/builds/20228) failed 8b75e134ec1ea0d0b7fa4e6074530aa1bb5c3f06
* :broken_heart: [Build #20215](https://buildkite.com/elastic/integrations/builds/20215) failed 8b75e134ec1ea0d0b7fa4e6074530aa1bb5c3f06
* :broken_heart: [Build #20186](https://buildkite.com/elastic/integrations/builds/20186) failed 8fae6c58882dc12c6da7f9b1c770a15916970ed0
* :broken_heart: [Build #20168](https://buildkite.com/elastic/integrations/builds/20168) failed ea3ef38fb6cef540bbe648ac60ae6eadffcf43d4

cc @alaudazzi

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20234","number":20234,"commit":"6124811447d85d83ebb6faf4c8d482fb8c09c74e"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20233","number":20233,"commit":"a796d9e9ead1735637ee29a1ac970c0de731003f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20228","number":20228,"commit":"8b75e134ec1ea0d0b7fa4e6074530aa1bb5c3f06"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20215","number":20215,"commit":"8b75e134ec1ea0d0b7fa4e6074530aa1bb5c3f06"},{"buildStatus":{"state":"failed","success":false,"hasRetries":true,"hasNonPreemptionRetries":true},"url":"https://buildkite.com/elastic/integrations/builds/20186","number":20186,"commit":"8fae6c58882dc12c6da7f9b1c770a15916970ed0"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20168","number":20168,"commit":"ea3ef38fb6cef540bbe648ac60ae6eadffcf43d4"}],"number":20234}
buildkite-pr-comment-->

2025-01-09 16:47 UTC, shmsr commented
/test

2025-01-09 16:59 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20244)
* Commit: 6124811447d85d83ebb6faf4c8d482fb8c09c74e

### Failed CI Steps
* [Check integrations ibmmq](https://buildkite.com/elastic/integrations/builds/20244#01944bfc-02c2-472a-873f-d9f153436bd7)

### History
* :broken_heart: [Build #20234](https://buildkite.com/elastic/integrations/builds/20234) failed 6124811447d85d83ebb6faf4c8d482fb8c09c74e
* :broken_heart: [Build #20233](https://buildkite.com/elastic/integrations/builds/20233) failed a796d9e9ead1735637ee29a1ac970c0de731003f
* :broken_heart: [Build #20228](https://buildkite.com/elastic/integrations/builds/20228) failed 8b75e134ec1ea0d0b7fa4e6074530aa1bb5c3f06
* :broken_heart: [Build #20215](https://buildkite.com/elastic/integrations/builds/20215) failed 8b75e134ec1ea0d0b7fa4e6074530aa1bb5c3f06
* :broken_heart: [Build #20186](https://buildkite.com/elastic/integrations/builds/20186) failed 8fae6c58882dc12c6da7f9b1c770a15916970ed0

cc @alaudazzi

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20244","number":20244,"commit":"6124811447d85d83ebb6faf4c8d482fb8c09c74e"},{"buildStatus":{"state":"failed","success":false,"hasRetries":true,"hasNonPreemptionRetries":true},"url":"https://buildkite.com/elastic/integrations/builds/20234","number":20234,"commit":"6124811447d85d83ebb6faf4c8d482fb8c09c74e"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20233","number":20233,"commit":"a796d9e9ead1735637ee29a1ac970c0de731003f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20228","number":20228,"commit":"8b75e134ec1ea0d0b7fa4e6074530aa1bb5c3f06"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20215","number":20215,"commit":"8b75e134ec1ea0d0b7fa4e6074530aa1bb5c3f06"},{"buildStatus":{"state":"failed","success":false,"hasRetries":true,"hasNonPreemptionRetries":true},"url":"https://buildkite.com/elastic/integrations/builds/20186","number":20186,"commit":"8fae6c58882dc12c6da7f9b1c770a15916970ed0"}],"number":20244}
buildkite-pr-comment-->

2025-01-09 17:19 UTC, shmsr commented
/test

2025-01-09 17:29 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20246)
* Commit: 6124811447d85d83ebb6faf4c8d482fb8c09c74e

### Failed CI Steps
* [Check integrations windows](https://buildkite.com/elastic/integrations/builds/20246#01944c18-270e-46d4-8250-fa00f8daeb6b)

### History
* :broken_heart: [Build #20244](https://buildkite.com/elastic/integrations/builds/20244) failed 6124811447d85d83ebb6faf4c8d482fb8c09c74e
* :broken_heart: [Build #20234](https://buildkite.com/elastic/integrations/builds/20234) failed 6124811447d85d83ebb6faf4c8d482fb8c09c74e
* :broken_heart: [Build #20233](https://buildkite.com/elastic/integrations/builds/20233) failed a796d9e9ead1735637ee29a1ac970c0de731003f
* :broken_heart: [Build #20228](https://buildkite.com/elastic/integrations/builds/20228) failed 8b75e134ec1ea0d0b7fa4e6074530aa1bb5c3f06
* :broken_heart: [Build #20215](https://buildkite.com/elastic/integrations/builds/20215) failed 8b75e134ec1ea0d0b7fa4e6074530aa1bb5c3f06

cc @alaudazzi

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20246","number":20246,"commit":"6124811447d85d83ebb6faf4c8d482fb8c09c74e"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20244","number":20244,"commit":"6124811447d85d83ebb6faf4c8d482fb8c09c74e"},{"buildStatus":{"state":"failed","success":false,"hasRetries":true,"hasNonPreemptionRetries":true},"url":"https://buildkite.com/elastic/integrations/builds/20234","number":20234,"commit":"6124811447d85d83ebb6faf4c8d482fb8c09c74e"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20233","number":20233,"commit":"a796d9e9ead1735637ee29a1ac970c0de731003f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20228","number":20228,"commit":"8b75e134ec1ea0d0b7fa4e6074530aa1bb5c3f06"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20215","number":20215,"commit":"8b75e134ec1ea0d0b7fa4e6074530aa1bb5c3f06"}],"number":20246}
buildkite-pr-comment-->

2025-01-09 18:03 UTC, shmsr commented
/test

2025-01-09 18:14 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20247)
* Commit: 6124811447d85d83ebb6faf4c8d482fb8c09c74e

### Failed CI Steps
* [Check integrations windows](https://buildkite.com/elastic/integrations/builds/20247#01944c40-bf9e-47dd-b263-d66c247d9a24)

### History
* :broken_heart: [Build #20246](https://buildkite.com/elastic/integrations/builds/20246) failed 6124811447d85d83ebb6faf4c8d482fb8c09c74e
* :broken_heart: [Build #20244](https://buildkite.com/elastic/integrations/builds/20244) failed 6124811447d85d83ebb6faf4c8d482fb8c09c74e
* :broken_heart: [Build #20234](https://buildkite.com/elastic/integrations/builds/20234) failed 6124811447d85d83ebb6faf4c8d482fb8c09c74e
* :broken_heart: [Build #20233](https://buildkite.com/elastic/integrations/builds/20233) failed a796d9e9ead1735637ee29a1ac970c0de731003f
* :broken_heart: [Build #20228](https://buildkite.com/elastic/integrations/builds/20228) failed 8b75e134ec1ea0d0b7fa4e6074530aa1bb5c3f06

cc @alaudazzi

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20247","number":20247,"commit":"6124811447d85d83ebb6faf4c8d482fb8c09c74e"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20246","number":20246,"commit":"6124811447d85d83ebb6faf4c8d482fb8c09c74e"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20244","number":20244,"commit":"6124811447d85d83ebb6faf4c8d482fb8c09c74e"},{"buildStatus":{"state":"failed","success":false,"hasRetries":true,"hasNonPreemptionRetries":true},"url":"https://buildkite.com/elastic/integrations/builds/20234","number":20234,"commit":"6124811447d85d83ebb6faf4c8d482fb8c09c74e"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20233","number":20233,"commit":"a796d9e9ead1735637ee29a1ac970c0de731003f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20228","number":20228,"commit":"8b75e134ec1ea0d0b7fa4e6074530aa1bb5c3f06"}],"number":20247}
buildkite-pr-comment-->

2025-01-09 18:56 UTC, shmsr commented
/test

2025-01-09 19:07 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20250)
* Commit: 6124811447d85d83ebb6faf4c8d482fb8c09c74e

### Failed CI Steps
* [Check integrations windows](https://buildkite.com/elastic/integrations/builds/20250#01944c71-4921-412d-870d-a1562e9c6a4d)

### History
* :broken_heart: [Build #20247](https://buildkite.com/elastic/integrations/builds/20247) failed 6124811447d85d83ebb6faf4c8d482fb8c09c74e
* :broken_heart: [Build #20246](https://buildkite.com/elastic/integrations/builds/20246) failed 6124811447d85d83ebb6faf4c8d482fb8c09c74e
* :broken_heart: [Build #20244](https://buildkite.com/elastic/integrations/builds/20244) failed 6124811447d85d83ebb6faf4c8d482fb8c09c74e
* :broken_heart: [Build #20234](https://buildkite.com/elastic/integrations/builds/20234) failed 6124811447d85d83ebb6faf4c8d482fb8c09c74e
* :broken_heart: [Build #20233](https://buildkite.com/elastic/integrations/builds/20233) failed a796d9e9ead1735637ee29a1ac970c0de731003f

cc @alaudazzi

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20250","number":20250,"commit":"6124811447d85d83ebb6faf4c8d482fb8c09c74e"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20247","number":20247,"commit":"6124811447d85d83ebb6faf4c8d482fb8c09c74e"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20246","number":20246,"commit":"6124811447d85d83ebb6faf4c8d482fb8c09c74e"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20244","number":20244,"commit":"6124811447d85d83ebb6faf4c8d482fb8c09c74e"},{"buildStatus":{"state":"failed","success":false,"hasRetries":true,"hasNonPreemptionRetries":true},"url":"https://buildkite.com/elastic/integrations/builds/20234","number":20234,"commit":"6124811447d85d83ebb6faf4c8d482fb8c09c74e"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20233","number":20233,"commit":"a796d9e9ead1735637ee29a1ac970c0de731003f"}],"number":20250}
buildkite-pr-comment-->

2025-01-09 19:36 UTC, shmsr commented
/test

2025-01-09 19:47 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20255)
* Commit: 6124811447d85d83ebb6faf4c8d482fb8c09c74e

### Failed CI Steps
* [Check integrations windows](https://buildkite.com/elastic/integrations/builds/20255#01944c95-fb4c-4e5d-a44f-ead51f932136)

### History
* :broken_heart: [Build #20250](https://buildkite.com/elastic/integrations/builds/20250) failed 6124811447d85d83ebb6faf4c8d482fb8c09c74e
* :broken_heart: [Build #20247](https://buildkite.com/elastic/integrations/builds/20247) failed 6124811447d85d83ebb6faf4c8d482fb8c09c74e
* :broken_heart: [Build #20246](https://buildkite.com/elastic/integrations/builds/20246) failed 6124811447d85d83ebb6faf4c8d482fb8c09c74e
* :broken_heart: [Build #20244](https://buildkite.com/elastic/integrations/builds/20244) failed 6124811447d85d83ebb6faf4c8d482fb8c09c74e
* :broken_heart: [Build #20234](https://buildkite.com/elastic/integrations/builds/20234) failed 6124811447d85d83ebb6faf4c8d482fb8c09c74e

cc @alaudazzi

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20255","number":20255,"commit":"6124811447d85d83ebb6faf4c8d482fb8c09c74e"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20250","number":20250,"commit":"6124811447d85d83ebb6faf4c8d482fb8c09c74e"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20247","number":20247,"commit":"6124811447d85d83ebb6faf4c8d482fb8c09c74e"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20246","number":20246,"commit":"6124811447d85d83ebb6faf4c8d482fb8c09c74e"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20244","number":20244,"commit":"6124811447d85d83ebb6faf4c8d482fb8c09c74e"},{"buildStatus":{"state":"failed","success":false,"hasRetries":true,"hasNonPreemptionRetries":true},"url":"https://buildkite.com/elastic/integrations/builds/20234","number":20234,"commit":"6124811447d85d83ebb6faf4c8d482fb8c09c74e"}],"number":20255}
buildkite-pr-comment-->

2025-01-10 09:48 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/20271)
* Commit: 4db8d68df383c4fdc94e8fbaf9e4e7d4f5272cad

### History
* :broken_heart: [Build #20255](https://buildkite.com/elastic/integrations/builds/20255) failed 6124811447d85d83ebb6faf4c8d482fb8c09c74e
* :broken_heart: [Build #20250](https://buildkite.com/elastic/integrations/builds/20250) failed 6124811447d85d83ebb6faf4c8d482fb8c09c74e
* :broken_heart: [Build #20247](https://buildkite.com/elastic/integrations/builds/20247) failed 6124811447d85d83ebb6faf4c8d482fb8c09c74e
* :broken_heart: [Build #20246](https://buildkite.com/elastic/integrations/builds/20246) failed 6124811447d85d83ebb6faf4c8d482fb8c09c74e
* :broken_heart: [Build #20244](https://buildkite.com/elastic/integrations/builds/20244) failed 6124811447d85d83ebb6faf4c8d482fb8c09c74e

cc @alaudazzi

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20271","number":20271,"commit":"4db8d68df383c4fdc94e8fbaf9e4e7d4f5272cad"},{"buildStatus":{"state":"failed","success":false,"hasRetries":true,"hasNonPreemptionRetries":true},"url":"https://buildkite.com/elastic/integrations/builds/20255","number":20255,"commit":"6124811447d85d83ebb6faf4c8d482fb8c09c74e"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20250","number":20250,"commit":"6124811447d85d83ebb6faf4c8d482fb8c09c74e"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20247","number":20247,"commit":"6124811447d85d83ebb6faf4c8d482fb8c09c74e"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20246","number":20246,"commit":"6124811447d85d83ebb6faf4c8d482fb8c09c74e"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/20244","number":20244,"commit":"6124811447d85d83ebb6faf4c8d482fb8c09c74e"}],"number":20271}
buildkite-pr-comment-->

2025-01-10 10:33 UTC, merged