entityanalytics_okta: Add `event.original` field when `preserve_original_event` tag is set.
elastic/integrations pull request #12206
Opened 2024-12-27 18:17 UTC by kcreddy

## Proposed commit message
Okta Entity Analytics doesn't capture full event inside raw `message` field. Add a painless script to capture the original event into `event.original`.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).
- [ ] I have verified that any added dashboard complies with Kibana's [Dashboard good practices](https://docs.elastic.dev/ux-guidelines/data-viz/dashboard-good-practices) 

## How to test this PR locally

Running Pipeline tests should pass successfully.
Run -> `cd packages/entityanalytics_okta && elastic-package stack down && elastic-package build && elastic-package stack up --version=8.13.0 -d -v && eval "$(elastic-package stack shellinit)" && elastic-package test pipeline --generate -v`
Returns -> 
```
--- Test results for package: entityanalytics_okta - START ---
╭──────────────────────┬─────────────┬───────────┬───────────────────────────────────────────┬────────┬──────────────╮
│ PACKAGE              │ DATA STREAM │ TEST TYPE │ TEST NAME                                 │ RESULT │ TIME ELAPSED │
├──────────────────────┼─────────────┼───────────┼───────────────────────────────────────────┼────────┼──────────────┤
│ entityanalytics_okta │ user        │ pipeline  │ (ingest pipeline warnings test-user.json) │ PASS   │ 321.542792ms │
│ entityanalytics_okta │ user        │ pipeline  │ test-user.json                            │ PASS   │  51.258333ms │
╰──────────────────────┴─────────────┴───────────┴───────────────────────────────────────────┴────────┴──────────────╯
--- Test results for package: entityanalytics_okta - END   ---
Done
```

2024-12-27 18:18 UTC, elasticmachine commented
Pinging @elastic/security-service-integrations (Team:Security-Service Integrations)

2024-12-27 18:35 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/19887)
* Commit: ea0d9a68c535c1dffc1ddec1ae832d97d26a7db6

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19887","number":19887,"commit":"ea0d9a68c535c1dffc1ddec1ae832d97d26a7db6"}],"number":19887}
buildkite-pr-comment-->

2024-12-30 10:52 UTC, chrisberkhout requested changes

2024-12-30 10:52 UTC, chrisberkhout commented on packages/entityanalytics_okta/data_stream/user/elasticsearch/ingest_pipeline/default.yml
> +        orig.entrySet().removeIf(entry -> ['_index', '_id'].contains(entry.getKey()));
After `def org = ctx;`, `org` has the same reference as `ctx`, so `_index` and `_id` get removed from `ctx` as well.

Pipeline tests won't accept data with `_id` or `_index` (the simulate API rejects it), if you run this logic by modifying the system test as follows, it will show index/publishing failures.

```diff
diff --git a/packages/entityanalytics_okta/data_stream/user/_dev/test/system/test-default-config.yml b/packages/entityanalytics_okta/data_stream/user/_dev/test/system/test-default-config.yml
index 8db4e54f64..0ec78b6d3c 100644
--- a/packages/entityanalytics_okta/data_stream/user/_dev/test/system/test-default-config.yml
+++ b/packages/entityanalytics_okta/data_stream/user/_dev/test/system/test-default-config.yml
@@ -5,6 +5,7 @@ data_stream:
     okta_domain: trial-xxxxxxx-admin.okta.com
     okta_token: xxxx
     preserve_duplicate_custom_fields: true
+    preserve_original_event: true
     enable_request_tracer: true
     ssl: |
       certificate_authorities:
@@ -42,3 +43,5 @@ data_stream:
           JE3WRcwNIONSRY/9seTyK6y9ed61m40Bx92kO2H0Ld+vKkYnFWAoZNYEM0WZ0zWz
           9EkWoxHOkvz1Pnp41Llpc7OPdbOQrx4=
           -----END CERTIFICATE-----
+assert:
+  hit_count: 4
```

2024-12-31 12:15 UTC, kcreddy commented on packages/entityanalytics_okta/data_stream/user/elasticsearch/ingest_pipeline/default.yml
> +        orig.entrySet().removeIf(entry -> ['_index', '_id'].contains(entry.getKey()));
Maybe I was on a different stack version earlier. When I ran on `8.15` (kibana.version), I got them successful locally without having to delete `_id` and `_index`.

2024-12-31 12:31 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/19936)
* Commit: 35697b87e5fc72b875b3b185f23499f31b6f11f9

### History
* :green_heart: [Build #19887](https://buildkite.com/elastic/integrations/builds/19887) succeeded ea0d9a68c535c1dffc1ddec1ae832d97d26a7db6

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19936","number":19936,"commit":"35697b87e5fc72b875b3b185f23499f31b6f11f9"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19887","number":19887,"commit":"ea0d9a68c535c1dffc1ddec1ae832d97d26a7db6"}],"number":19936}
buildkite-pr-comment-->

2025-01-02 08:06 UTC, chrisberkhout approved these changes
Good, with a new `assert.hit_count` change.

2025-01-02 08:06 UTC, chrisberkhout commented on packages/entityanalytics_okta/data_stream/user/elasticsearch/ingest_pipeline/default.yml
> +        def stringified_orig = Json.dump(orig);
```suggestion
        def stringified_orig = Json.dump(ctx);
```
`orig` refers to the same object, so we might as well use it directly.

2025-01-02 09:06 UTC, kcreddy commented on packages/entityanalytics_okta/data_stream/user/_dev/test/system/test-default-config.yml
> +  hit_count: 3 # 1 start marker + 1 user + 1 end marker
Got it, thanks for this analysis. I didn't run many test runs, and I was going off by system tests' mock records. 

I wonder if we shouldn't allow `incremental update` to start until 1 full sync is finished.

2025-01-02 09:29 UTC, chrisberkhout commented on packages/entityanalytics_okta/data_stream/user/_dev/test/system/test-default-config.yml
> +  hit_count: 3 # 1 start marker + 1 user + 1 end marker
Yeah, probably.

At the moment when it starts up it sets the next times based on what's in the store. If it's a fresh start it will end up with both due and then choose randomly, but if its resuming it will continue on the previous schedule.

So the change might be: if times from the store aren't in the future, set do the full sync now and the incremental after its interval.

2025-01-02 09:33 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/19953)
* Commit: d7a24b8dc3aef3c1a1b974719b8df7f265dcf920

### History
* :green_heart: [Build #19936](https://buildkite.com/elastic/integrations/builds/19936) succeeded 35697b87e5fc72b875b3b185f23499f31b6f11f9
* :green_heart: [Build #19887](https://buildkite.com/elastic/integrations/builds/19887) succeeded ea0d9a68c535c1dffc1ddec1ae832d97d26a7db6

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19953","number":19953,"commit":"d7a24b8dc3aef3c1a1b974719b8df7f265dcf920"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19936","number":19936,"commit":"35697b87e5fc72b875b3b185f23499f31b6f11f9"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/19887","number":19887,"commit":"ea0d9a68c535c1dffc1ddec1ae832d97d26a7db6"}],"number":19953}
buildkite-pr-comment-->

2025-01-02 09:34 UTC, merged