[crowdstrike] Set event.module and event.dataset
elastic/integrations pull request #1258
Opened 2021-06-30 09:36 UTC by marc-gr

## What does this PR do?

Sets event.module and event.dataset

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] If I'm introducing a new feature, I have modified the Kibana version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^7.13.0`).

2021-06-30 09:40 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1258/detail/PR-1258/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1258/detail/PR-1258/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1258/detail/PR-1258/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1258/detail/PR-1258/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://null_1258.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #1258 opened`



* Start Time: 2021-06-30T09:36:16.344+0000


* Duration: 4 min 45 sec


* Commit: 8d252461782325c9c00497c9d9992ebc63e53608




#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/PR-1258/buildTimeGraph/png)



</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->









### Steps errors [![3](https://img.shields.io/badge/3%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1258/detail/PR-1258/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Check out from version control`
<ul>
<li>Took 0 min 10 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-1258/runs/1/steps/11/log/?start=0">here</a></li>
<li>Description: <code>[2021-06-30T09:38:44.055Z] The recommended git tool is: git
[2021-06-30T09:38:45.960Z] using creden</code></l1>
</ul>
  
  
  
  
##### `Check out from version control`
<ul>
<li>Took 0 min 8 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-1258/runs/1/steps/15/log/?start=0">here</a></li>
<li>Description: <code>[2021-06-30T09:39:14.101Z] The recommended git tool is: git
[2021-06-30T09:39:14.112Z] using creden</code></l1>
</ul>
  
  
  
  
##### `Check out from version control`
<ul>
<li>Took 0 min 8 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-1258/runs/1/steps/19/log/?start=0">here</a></li>
<li>Description: <code>[2021-06-30T09:39:52.046Z] The recommended git tool is: git
[2021-06-30T09:39:52.056Z] using creden</code></l1>
</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-06-30T09:39:14.164Z]  > git --version # 'git version 2.25.1'
[2021-06-30T09:39:14.165Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-06-30T09:39:14.168Z]  > git fetch --no-tags --force --progress -- git@github.com:elastic/integrations.git +refs/heads/*:refs/remotes/origin/* # timeout=15
[2021-06-30T09:39:21.319Z] Cleaning workspace
[2021-06-30T09:39:21.331Z] Using shallow fetch with depth 4
[2021-06-30T09:39:21.331Z] Pruning obsolete local branches
[2021-06-30T09:39:21.923Z] Merging remotes/origin/master commit 25a1844e8999e4bb911295a1ab775c136b83da08 into PR head commit 8d252461782325c9c00497c9d9992ebc63e53608
[2021-06-30T09:39:21.973Z] ERROR: Execution failed
[2021-06-30T09:39:21.973Z] hudson.plugins.git.GitException: Command "git checkout -f 8d252461782325c9c00497c9d9992ebc63e53608" returned status code 128:
[2021-06-30T09:39:21.973Z] stdout: 
[2021-06-30T09:39:21.973Z] stderr: fatal: reference is not a tree: 8d252461782325c9c00497c9d9992ebc63e53608
[2021-06-30T09:39:21.973Z] 
[2021-06-30T09:39:21.973Z] 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2661)
[2021-06-30T09:39:21.973Z] 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$1100(CliGitAPIImpl.java:86)
[2021-06-30T09:39:21.973Z] 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2979)
[2021-06-30T09:39:21.973Z] Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from beats-ci-immutable-ubuntu-2004-1625045842714793194.c.elastic-ci-prod.internal/10.224.1.55:52228
[2021-06-30T09:39:21.973Z] 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
[2021-06-30T09:39:21.973Z] 		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
[2021-06-30T09:39:21.973Z] 		at hudson.remoting.Channel.call(Channel.java:1001)
[2021-06-30T09:39:21.973Z] 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:145)
[2021-06-30T09:39:21.973Z] 		at sun.reflect.GeneratedMethodAccessor914.invoke(Unknown Source)
[2021-06-30T09:39:21.973Z] 		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-06-30T09:39:21.973Z] 		at java.lang.reflect.Method.invoke(Method.java:498)
[2021-06-30T09:39:21.973Z] 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:131)
[2021-06-30T09:39:21.973Z] 		at com.sun.proxy.$Proxy140.execute(Unknown Source)
[2021-06-30T09:39:21.973Z] 		at jenkins.plugins.git.MergeWithGitSCMExtension.checkout(MergeWithGitSCMExtension.java:145)
[2021-06-30T09:39:21.973Z] 		at jenkins.plugins.git.MergeWithGitSCMExtension.decorateRevisionToBuild(MergeWithGitSCMExtension.java:111)
[2021-06-30T09:39:21.973Z] 		at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:1163)
[2021-06-30T09:39:21.973Z] 		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1302)
[2021-06-30T09:39:21.973Z] 		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:125)
[2021-06-30T09:39:21.973Z] 		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:93)
[2021-06-30T09:39:21.973Z] 		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:80)
[2021-06-30T09:39:21.973Z] 		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
[2021-06-30T09:39:21.973Z] 		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2021-06-30T09:39:21.973Z] 		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2021-06-30T09:39:21.973Z] 		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2021-06-30T09:39:21.973Z] 		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2021-06-30T09:39:21.973Z] Caused: hudson.plugins.git.GitException: Could not checkout 8d252461782325c9c00497c9d9992ebc63e53608
[2021-06-30T09:39:21.973Z] 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:3003)
[2021-06-30T09:39:21.973Z] 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:160)
[2021-06-30T09:39:21.973Z] 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:153)
[2021-06-30T09:39:21.973Z] 	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
[2021-06-30T09:39:21.973Z] 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
[2021-06-30T09:39:21.973Z] 	at hudson.remoting.Request$2.run(Request.java:376)
[2021-06-30T09:39:21.973Z] 	at hudson.remoting.InterceptingExecutorService.lambda [...]

2021-06-30 15:19 UTC, andrewkroh requested changes

2021-06-30 15:19 UTC, andrewkroh commented on packages/crowdstrike/data_stream/falcon/fields/base-fields.yml
> +  description: Event dataset
Missing `value`.

2021-07-01 08:56 UTC, P1llus approved these changes

2021-07-01 09:10 UTC, merged