Update package descriptions
elastic/integrations pull request #1364
Opened 2021-07-28 18:25 UTC by bmorelli25

2021-07-28 18:59 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1364/detail/PR-1364/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1364/detail/PR-1364/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1364/detail/PR-1364/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1364/detail/PR-1364/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_1364.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2021-07-28T18:26:40.878Z&rangeTo=2021-07-28T18:46:40.878Z&transactionName=Ingest-manager/integrations/PR-{number}&transactionType=unknown&latencyAggregationType=avg&traceId=f6fde665bccaf89eae5fe5f08f5b9469&transactionId=e3dd8a9f44663260)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2021-07-28T18:36:40.878+0000


* Duration: 23 min 57 sec


* Commit: a5e8dd252750dcfb3e1f55a65e184c41fd0f643a



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 623  |
| Skipped      | 0 |
| Total        | 623   |


#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/PR-1364/buildTimeGraph/png)


![Image of Tests](https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/PR-1364/1/testReport/history/countGraph/png?start=0&amp;end=25)


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2021-07-28 19:12 UTC, andrewkroh commented on packages/cef/manifest.yml
> +description: This integration collects logs from common event format (CEF) instances
CEF isn't a product that you would run an "instance" of. It's a log format like JSON. So perhaps there is a better phrasing of this description.

2021-07-28 19:14 UTC, bmorelli25 commented on packages/cef/manifest.yml
> +description: This integration collects logs from common event format (CEF) instances
Thanks, Andrew! I pulled "CEF instance" from L17 of the manifest file. Should I update that line as well to remove it? https://github.com/elastic/integrations/pull/1364/files#diff-966e13402568cef1412dea521600e7fb5172601510e51030c0bbb41d55351e43L17

2021-07-28 19:15 UTC, bmorelli25 commented on packages/cef/manifest.yml
> +description: This integration collects logs from common event format (CEF) instances
Not sure if that link will work. Here's a better one: https://github.com/elastic/integrations/blob/a5e8dd252750dcfb3e1f55a65e184c41fd0f643a/packages/cef/manifest.yml#L17

2021-07-28 21:06 UTC, goodroot commented on packages/auditd/manifest.yml
> +description: This Elastic integration collects and parses logs from the Audit daemon (`auditd`)
We will not be able to interpolate the backticks into code snippets.

Suggestion is to remove. 
```suggestion
description: This Elastic integration collects and parses logs from the Audit daemon (auditd)
```

2021-07-28 21:06 UTC, goodroot commented on packages/log/manifest.yml
>  description: >
This "works", but the > is removed when it's parsed.

2021-07-28 21:06 UTC, goodroot commented on packages/system/manifest.yml
> +description: This Elastic integration collects logs and metrics of your Systems
This blew my mind. Maybe elaborate a bit on systems?

2021-07-28 21:14 UTC, bmorelli25 commented on packages/system/manifest.yml
> +description: This Elastic integration collects logs and metrics of your Systems
LOL. Deal.

2021-07-28 21:15 UTC, bmorelli25 commented on packages/auditd/manifest.yml
> +description: This Elastic integration collects and parses logs from the Audit daemon (`auditd`)
Perfect. I was wondering about that.

2021-07-28 21:16 UTC, bmorelli25 commented on packages/log/manifest.yml
>  description: >
👍 Should be OK then. I'm not sure why some descriptions use this format -- so I chose not to mess with it.

2021-07-28 22:42 UTC, mtojek requested changes
In general we use `elastic-package format` to format sources of integrations.

2021-07-28 22:42 UTC, mtojek commented on packages/apache/manifest.yml
> +description: This Elastic integration collects logs and metrics from Apache servers
Integrations (or packages in general) are idempotent, which mean that you have bump up the version (I suggest semver's "minor") and add an entry to the changelog file.

Unfortunately you have to do this for every integration.

2021-07-28 22:42 UTC, mtojek commented on packages/elastic_agent/manifest.yml
> -type: integration
Please revert this line (`type: integration`). You may notice that CI complained about it.

2021-07-28 22:44 UTC, bmorelli25 commented on packages/elastic_agent/manifest.yml
> -type: integration
Oops! Good catch. This was an accident.

2021-07-28 22:46 UTC, bmorelli25 commented on packages/apache/manifest.yml
> +description: This Elastic integration collects logs and metrics from Apache servers
😬 OH

2021-07-28 22:46 UTC, bmorelli25 commented on packages/apache/manifest.yml
> +description: This Elastic integration collects logs and metrics from Apache servers
😄 Thanks, will get started

2021-07-28 23:20 UTC, bmorelli25 commented on packages/apache/manifest.yml
> +description: This Elastic integration collects logs and metrics from Apache servers
Not as bad as I thought it would be. Updated!

2021-07-29 08:35 UTC, mtojek requested changes
@bmorelli25 

We have requirement that CI must report green state to get the PR merged. In this case is red which means there is something wrong with this PR. There are problems with elastic_agent (missing manifest entry) and okta (missing manifest entry).

2021-07-29 14:28 UTC, bmorelli25 commented on packages/elastic_agent/changelog.yml
> +- version: "0.1.7"
```suggestion
- version: "0.1.0"
```

2021-07-29 14:29 UTC, bmorelli25 commented on packages/okta/manifest.yml
> +format_version: 1.1.0
```suggestion
format_version: 1.0.0
```

2021-07-29 14:29 UTC, bmorelli25 commented on packages/okta/manifest.yml
>  version: 1.0.1
```suggestion
version: 1.1.0
```

2021-07-29 14:30 UTC, bmorelli25 commented
> There are problems with elastic_agent (missing manifest entry) and okta (missing manifest entry).

Thanks! I _think_ everything should pass this time 🤞

2021-07-29 15:42 UTC, bmorelli25 commented
Noooooo. Green, but a change was merged to the system integration. I'll fix the conflicts and let the tests run again.

2021-07-29 15:46 UTC, mtojek approved these changes
Remember to bump up package versions accordingly in case of conflicts.

LGTM, feel free to merge this PR if CI is happy.

2021-07-29 15:47 UTC, bmorelli25 commented
> Remember to bump up package versions accordingly in case of conflicts.

Yup. The merged update in this case happened to be a patch, so my minor update was still the latest -- just needed to merge in the new CL entry.

> LGTM, feel free to merge this PR if CI is happy.

Thanks! I'll be clicking the button the second it's green :)

2021-07-29 17:52 UTC, bmorelli25 commented
Test just timed out. Restarting.

2021-07-29 19:04 UTC, merged