Add Cluster filter on Kubernetes Overview dashboard
elastic/integrations pull request #1413
Opened 2021-07-30 15:07 UTC by akshay-saraswat

## What does this PR do?
Added a Cluster name selector on the [Metrics Kubernetes] Overview dashboard. This selector will be used as a filter for the dashboard. Also, added a blurb for this selector on the Kubernetes package guide to explain how this selector works and where it sources the data from.

## Why is it important?
We have added a new Cluster name field in the Kubernetes package. This field will not be useful unless users could discover it in some form
in UI.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have added an entry to my package's `changelog.yml` file.

<img width="2560" alt="Screen Shot 2021-07-30 at 9 49 11 AM" src="https://user-images.githubusercontent.com/14043218/127673209-e40ee351-8e0d-4b6e-b698-145eada25dbd.png">

2021-07-30 15:07 UTC, elasticmachine commented
Pinging @elastic/integrations (Team:Integrations)

2021-07-30 15:10 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1413/detail/PR-1413/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1413/detail/PR-1413/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1413/detail/PR-1413/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1413/detail/PR-1413/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://null_1413.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2021-07-30T14:57:57.066Z&rangeTo=2021-07-30T15:17:57.066Z&transactionName=Ingest-manager/integrations/PR-{number}&transactionType=unknown&latencyAggregationType=avg&traceId=d9ff1d9c661d177bbcd3820f0ed421e7&transactionId=1b0b45ae45a73102)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2021-07-30T15:07:57.066+0000


* Duration: 3 min 33 sec


* Commit: 26586446ea65b1e45f5c4a306731f5cc2d4c0a10




#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/PR-1413/buildTimeGraph/png)



</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->









### Steps errors [![3](https://img.shields.io/badge/3%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1413/detail/PR-1413/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Check out from version control`
<ul>
<li>Took 0 min 10 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-1413/runs/1/steps/11/log/?start=0">here</a></li>
<li>Description: <code>[2021-07-30T15:09:13.787Z] The recommended git tool is: git
[2021-07-30T15:09:15.827Z] using creden</code></l1>
</ul>
  
  
  
  
##### `Check out from version control`
<ul>
<li>Took 0 min 8 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-1413/runs/1/steps/15/log/?start=0">here</a></li>
<li>Description: <code>[2021-07-30T15:09:43.809Z] The recommended git tool is: git
[2021-07-30T15:09:43.820Z] using creden</code></l1>
</ul>
  
  
  
  
##### `Check out from version control`
<ul>
<li>Took 0 min 8 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-1413/runs/1/steps/19/log/?start=0">here</a></li>
<li>Description: <code>[2021-07-30T15:10:21.478Z] The recommended git tool is: git
[2021-07-30T15:10:21.490Z] using creden</code></l1>
</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-07-30T15:09:51.407Z] 	at hudson.remoting.Request$2.run(Request.java:376)
[2021-07-30T15:09:51.407Z] 	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
[2021-07-30T15:09:51.407Z] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2021-07-30T15:09:51.407Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2021-07-30T15:09:51.407Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2021-07-30T15:09:51.407Z] 	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:122)
[2021-07-30T15:09:51.407Z] 	at java.lang.Thread.run(Thread.java:748)
[2021-07-30T15:09:51.407Z] Retrying
[2021-07-30T15:09:51.446Z] Sleeping for 30 sec
[2021-07-30T15:09:50.759Z]  > git config remote.origin.url git@github.com:elastic/integrations.git # timeout=10
[2021-07-30T15:09:50.763Z]  > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
[2021-07-30T15:09:50.771Z]  > git config remote.origin.url git@github.com:elastic/integrations.git # timeout=10
[2021-07-30T15:09:50.779Z]  > git rev-parse --verify HEAD # timeout=10
[2021-07-30T15:09:50.783Z] No valid HEAD. Skipping the resetting
[2021-07-30T15:09:50.783Z]  > git clean -fdx # timeout=10
[2021-07-30T15:09:50.795Z] Fetching upstream changes from git@github.com:elastic/integrations.git
[2021-07-30T15:09:50.795Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-07-30T15:09:50.799Z]  > git fetch --no-tags --force --progress --prune -- git@github.com:elastic/integrations.git +refs/pull/1413/head:refs/remotes/origin/PR-1413 +refs/heads/master:refs/remotes/origin/master # timeout=15
[2021-07-30T15:09:51.369Z]  > git config core.sparsecheckout # timeout=10
[2021-07-30T15:09:51.373Z]  > git checkout -f 26586446ea65b1e45f5c4a306731f5cc2d4c0a10 # timeout=15
[2021-07-30T15:10:21.478Z] The recommended git tool is: git
[2021-07-30T15:10:21.490Z] using credential f6c7695a-671e-4f4f-a331-acdce44ff9ba
[2021-07-30T15:10:21.496Z] Wiping out workspace first.
[2021-07-30T15:10:21.525Z] Cloning the remote Git repository
[2021-07-30T15:10:21.525Z] Using shallow clone with depth 4
[2021-07-30T15:10:21.525Z] Avoid fetching tags
[2021-07-30T15:10:21.532Z] Cloning repository git@github.com:elastic/integrations.git
[2021-07-30T15:10:21.533Z]  > git init /var/lib/jenkins/workspace/est-manager_integrations_PR-1413 # timeout=10
[2021-07-30T15:10:21.540Z] Fetching upstream changes from git@github.com:elastic/integrations.git
[2021-07-30T15:10:21.540Z]  > git --version # timeout=10
[2021-07-30T15:10:21.543Z]  > git --version # 'git version 2.25.1'
[2021-07-30T15:10:21.544Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-07-30T15:10:21.548Z]  > git fetch --no-tags --force --progress -- git@github.com:elastic/integrations.git +refs/heads/*:refs/remotes/origin/* # timeout=15
[2021-07-30T15:10:28.534Z] Cleaning workspace
[2021-07-30T15:10:28.548Z] Using shallow fetch with depth 4
[2021-07-30T15:10:28.548Z] Pruning obsolete local branches
[2021-07-30T15:10:29.148Z] Merging remotes/origin/master commit 9b379b1e1e5e789298b6c7f24af3cdcb4d857801 into PR head commit 26586446ea65b1e45f5c4a306731f5cc2d4c0a10
[2021-07-30T15:10:29.356Z] Error when executing always post condition:
[2021-07-30T15:10:29.357Z] groovy.lang.MissingPropertyException: No such property: BASE_DIR for class: groovy.lang.Binding
[2021-07-30T15:10:29.357Z] 	at groovy.lang.Binding.getVariable(Binding.java:63)
[2021-07-30T15:10:29.357Z] 	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:271)
[2021-07-30T15:10:29.357Z] 	at org.kohsuke.groovy.sandbox.impl.Checker$7.call(Checker.java:353)
[2021-07-30T15:10:29.357Z] 	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:357)
[2021-07-30T15:10:29.357Z] 	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:333)
[2021-07-30T15:10:29.357Z] 	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.getProperty(SandboxInvoker.java:29)
[2021-07-30T15:10:29.357Z] 	at com.cloudbees.groovy.cps.impl.PropertyAccessBlock.rawGet(PropertyAccessBlock.java:20)
[2021-07-30T15:10:29.357Z] 	at WorkflowScript.publishCoverageReports(WorkflowScript:277)
[2021-07-30T15:10:29.357Z] 	at ___cps.transform___(Native Method)
[2021-07-30T15:10:29.357Z] 	at com.cloudbees.groovy.cps.impl.PropertyishBl [...]

2021-08-02 07:10 UTC, MichaelKatsoulis commented on packages/kubernetes/docs/README.md
> +If you are using HA for those components, be aware that when gathering data from all instances the dashboard will usually show and average of the metrics. For those scenarios filtering by hosts or se
```suggestion
If you are using HA for those components, be aware that when gathering data from all instances the dashboard will usually show the average of the metrics. For those scenarios filtering by hosts or service address is possible.
```

2021-08-02 07:18 UTC, ChrsMark requested changes
Thanks for submitting this. I left some comments. Also I think that we miss the updated screenshot for the docs.

2021-08-02 07:18 UTC, ChrsMark commented on packages/kubernetes/changelog.yml
> +- version: "0.11.1"
Better rebase on top of https://github.com/elastic/integrations/pull/1407 after it is merged.

2021-08-02 07:18 UTC, ChrsMark commented on packages/kubernetes/docs/events.md
> +| kubernetes.annotations.\* | Kubernetes annotations map | object |  |
Are these backslashes intentional?

2021-08-02 07:18 UTC, ChrsMark commented on packages/kubernetes/kibana/visualization/kubernetes-16fa4470-2bfd-11e7-859b-f78b612cde28.json
> -                    "query": "data_stream.dataset: kubernetes.pod"
Any reason for removing these? These are supposed to make the loading of the dashboard faster.

2021-08-02 07:22 UTC, MichaelKatsoulis commented
@akshay-saraswat  thanks for this. I think you should run `elastic-package format` to format the new dashboard. Also you need to update the version in the `manifest.yml`

2021-08-02 13:43 UTC, akshay-saraswat commented on packages/kubernetes/docs/events.md
> +| kubernetes.annotations.\* | Kubernetes annotations map | object |  |
These changes were generated by the `elastic-package build`. Don't know why these are required.

2021-08-02 13:44 UTC, akshay-saraswat commented on packages/kubernetes/kibana/visualization/kubernetes-16fa4470-2bfd-11e7-859b-f78b612cde28.json
> -                    "query": "data_stream.dataset: kubernetes.pod"
Same as above. This change was generated by the `elastic-package build`.

2021-08-02 14:32 UTC, akshay-saraswat commented on packages/kubernetes/changelog.yml
> +- version: "0.11.1"
Will do it. Thnaks!

2021-08-02 14:38 UTC, ChrsMark commented on packages/kubernetes/docs/events.md
> +| kubernetes.annotations.\* | Kubernetes annotations map | object |  |
@mtojek do you know if this is normal?

2021-08-02 14:54 UTC, akshay-saraswat commented on packages/kubernetes/docs/events.md
> +| kubernetes.annotations.\* | Kubernetes annotations map | object |  |
I ran `elastic-package build` after `elastic-package format` and don't see this change introduced anymore.

2021-08-02 14:56 UTC, akshay-saraswat commented on packages/kubernetes/kibana/visualization/kubernetes-16fa4470-2bfd-11e7-859b-f78b612cde28.json
> -                    "query": "data_stream.dataset: kubernetes.pod"
I'll manually revert this change in all the visualizations.

2021-08-02 15:24 UTC, mtojek commented on packages/kubernetes/docs/events.md
> +| kubernetes.annotations.\* | Kubernetes annotations map | object |  |
Yes, this escaping is needed to properly visualize them in READMEs (potential conflict with *italics* ).

2021-08-02 16:43 UTC, akshay-saraswat commented on packages/kubernetes/docs/README.md
> +If you are using HA for those components, be aware that when gathering data from all instances the dashboard will usually show and average of the metrics. For those scenarios filtering by hosts or se
Fixed. Thanks!

2021-08-02 16:46 UTC, akshay-saraswat commented
> @akshay-saraswat thanks for this. I think you should run `elastic-package format` to format the new dashboard. Also you need to update the version in the `manifest.yml`

2021-08-02 16:49 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1413/detail/PR-1413/3//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1413/detail/PR-1413/3//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1413/detail/PR-1413/3//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1413/detail/PR-1413/3//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_1413.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2021-08-02T16:32:50.856Z&rangeTo=2021-08-02T16:52:50.856Z&transactionName=Ingest-manager/integrations/PR-{number}&transactionType=unknown&latencyAggregationType=avg&traceId=325826d80a3f58c20f968d798ee961f8&transactionId=bf59fb91c322ac48)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2021-08-02T16:42:50.856+0000


* Duration: 6 min 6 sec


* Commit: d72385cab47aaef41127cd027a6c6ff97f033776




#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/PR-1413/buildTimeGraph/png)



</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->









### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1413/detail/PR-1413/3//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Check integration: kubernetes`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-1413/runs/3/steps/402/log/?start=0">here</a></li>
<li>Description: <code>../../build/elastic-package check -v</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-1413/runs/3/steps/434/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-08-02T16:48:02.093Z] go: downloading k8s.io/kube-openapi v0.0.0-20210305001622-591a79e4bda7
[2021-08-02T16:48:02.093Z] go: downloading github.com/davecgh/go-spew v1.1.1
[2021-08-02T16:48:02.353Z] go: downloading golang.org/x/time v0.0.0-20210220033141-f8bda1e9f3ba
[2021-08-02T16:48:02.354Z] go: downloading github.com/google/btree v1.0.0
[2021-08-02T16:48:02.354Z] go: downloading gopkg.in/inf.v0 v0.9.1
[2021-08-02T16:48:02.354Z] go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
[2021-08-02T16:48:02.354Z] go: downloading google.golang.org/protobuf v1.26.0
[2021-08-02T16:48:02.354Z] go: downloading github.com/go-stack/stack v1.8.0
[2021-08-02T16:48:02.614Z] go: downloading github.com/hashicorp/golang-lru v0.5.1
[2021-08-02T16:48:02.614Z] go: downloading github.com/google/shlex v0.0.0-20191202100458-e7afc7fbc510
[2021-08-02T16:48:02.614Z] go: downloading github.com/go-openapi/spec v0.19.5
[2021-08-02T16:48:02.614Z] go: downloading github.com/monochromegane/go-gitignore v0.0.0-20200626010858-205db1a8cc00
[2021-08-02T16:48:02.614Z] go: downloading github.com/stretchr/testify v1.7.0
[2021-08-02T16:48:02.614Z] go: downloading github.com/xlab/treeprint v0.0.0-20181112141820-a009c3971eca
[2021-08-02T16:48:02.614Z] go: downloading github.com/go-errors/errors v1.0.1
[2021-08-02T16:48:02.614Z] go: downloading go.starlark.net v0.0.0-20200306205701-8dd3e2ee1dd5
[2021-08-02T16:48:02.614Z] go: downloading github.com/pmezard/go-difflib v1.0.0
[2021-08-02T16:48:02.614Z] go: downloading k8s.io/component-base v0.21.0
[2021-08-02T16:48:02.614Z] go: downloading github.com/exponent-io/jsonpath v0.0.0-20151013193312-d6023ce2651d
[2021-08-02T16:48:02.614Z] go: downloading github.com/MakeNowJust/heredoc v0.0.0-20170808103936-bb23615498cd
[2021-08-02T16:48:02.614Z] go: downloading github.com/russross/blackfriday v1.5.2
[2021-08-02T16:48:02.614Z] go: downloading github.com/mitchellh/go-wordwrap v1.0.0
[2021-08-02T16:48:02.614Z] go: downloading github.com/moby/term v0.0.0-20201216013528-df9cb8a40635
[2021-08-02T16:48:02.614Z] go: downloading github.com/moby/spdystream v0.2.0
[2021-08-02T16:48:02.614Z] go: downloading github.com/go-openapi/jsonreference v0.19.3
[2021-08-02T16:48:02.614Z] go: downloading github.com/go-openapi/jsonpointer v0.19.3
[2021-08-02T16:48:02.614Z] go: downloading github.com/go-openapi/swag v0.19.5
[2021-08-02T16:48:02.614Z] go: downloading github.com/PuerkitoBio/purell v1.1.1
[2021-08-02T16:48:02.614Z] go: downloading github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578
[2021-08-02T16:48:02.614Z] go: downloading github.com/mailru/easyjson v0.7.0
[2021-08-02T16:48:49.408Z] Running in /var/lib/jenkins/workspace/est-manager_integrations_PR-1413/src/github.com/elastic/integrations/packages/kubernetes
[2021-08-02T16:48:49.702Z] + ../../build/elastic-package check -v
[2021-08-02T16:48:49.702Z] elastic-package has been installed.
[2021-08-02T16:48:49.702Z] 2021/08/02 16:48:49 DEBUG Enable verbose logging
[2021-08-02T16:48:49.702Z] 2021/08/02 16:48:49 DEBUG Distribution built without a version tag, can't determine release chronology. Please consider using official releases at https://github.com/elastic/elastic-package/releases
[2021-08-02T16:48:49.702Z] Format the package
[2021-08-02T16:48:49.703Z] Error: checking package failed: formatting the integration failed (path: /var/lib/jenkins/workspace/est-manager_integrations_PR-1413/src/github.com/elastic/integrations/packages/kubernetes, failFast: true): walking through the integration files failed: formatting file failed (path: /var/lib/jenkins/workspace/est-manager_integrations_PR-1413/src/github.com/elastic/integrations/packages/kubernetes/kibana/visualization/kubernetes-022a54c0-2bf5-11e7-859b-f78b612cde28.json): file is not formatted (path: /var/lib/jenkins/workspace/est-manager_integrations_PR-1413/src/github.com/elastic/integrations/packages/kubernetes/kibana/visualization/kubernetes-022a54c0-2bf5-11e7-859b-f78b612cde28.json)
[2021-08-02T16:48:49.730Z] Running in /var/lib/jenkins/workspace/est-manager_integrations_PR-1413/src/github.com/elastic/integrations
[2021-08-02T16:48:49.746Z] Archiving artifacts
[2021-08-02T16:48:50.093Z] ‘build/test-results/*.xml’ doesn’t match anything: ‘build’ exists but not ‘build/test-results/*.xml’
[2021-08-02T16:48:50.093Z] No artifacts found that match the file pattern "build/test-results/*.xml". Configuration error?
[2021-08-02T16:48:50.104Z] Recording test results
[2021-08-02T16:48:50.300Z] None of the test reports contained any result
[2021-08-02T16:48:50.300Z] [Checks API] No suitable checks publisher found.
[2021-08-02T16:48:50.612Z] + build/elastic-package stack dump -v --output build/elastic-stack-dump/latest/kubernetes
[2021-08-02T16:48:50.612Z] 2021/08/02 16:48:50  WARN CommitHash is undefined, in both /var/lib/jenkins/workspace/est-manager_integrations_PR-1413/.elastic-package/version and the compiled binary, config may be out of date.
[2021-08-02T16:48:50.612Z] 2021/08/02 16:48:50 DEBUG Enable verbose logging
[2021-08-02T16:48:50.612Z] 2021/08/ [...]

2021-08-02 16:49 UTC, akshay-saraswat commented
Ran following commands in package/kubernetes
1. `elastic-package export dashboard -v`
2. `elastic-package format`
3. `elastic-package build`

Added a screenshot too to the updated commit.

2021-08-03 08:29 UTC, ChrsMark reviewed
Only one addition is needed, but overall it looks good to me.

2021-08-03 08:29 UTC, ChrsMark commented on packages/kubernetes/changelog.yml
> +- version: "0.12.1"
It will an update in the `manifest.yml` (https://github.com/elastic/integrations/blob/master/packages/kubernetes/manifest.yml#L4).

2021-08-03 13:00 UTC, akshay-saraswat commented on packages/kubernetes/changelog.yml
> +- version: "0.12.1"
Sorry about that. Forgot to amend the commit. Updating manifest.yml now.

2021-08-03 13:38 UTC, ChrsMark commented
Tests seem to fail to due to format failures: https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/PR-1413/5/pipeline

2021-08-03 14:45 UTC, akshay-saraswat commented
> Tests seem to fail to due to format failures: https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/PR-1413/5/pipeline

- Moved README changes from docs to _dev/build/docs.
- Ran elastic-package format
- Ran elastic-package lint
- Ran elastic-package build

2021-08-03 15:31 UTC, ChrsMark commented
@mtojek tests seems to fail in CI while locally `ep check` does not complain. I wonder what can be wrong here, I restarted the  the CI job several times but still 🤔 . Any ideas?

2021-08-04 10:56 UTC, ChrsMark approved these changes

2021-08-04 10:56 UTC, merged