Add datastream to collect pod logs in kubernetes integration
elastic/integrations pull request #1523
Opened 2021-08-12 10:49 UTC by MichaelKatsoulis

## What does this PR do?

This PR adds a new data stream in kubernetes integration to collect pods logs.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] If I'm introducing a new feature, I have modified the Kibana version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^7.13.0`).

## How to test this PR locally

Adding Kubernetes integration to a policy or just `kube-pod-logs` integration automatically
starts collecting pods logs. 

## Related issues

- Closes #1457

## Screenshots
![integrations-view](https://user-images.githubusercontent.com/26270880/130587621-9190149e-de8b-4232-a917-58743d6d1bae.png)
![container-logs-integration](https://user-images.githubusercontent.com/26270880/130587641-143d969c-3b86-4309-9e19-5161ce31922f.png)
![configure-integration](https://user-images.githubusercontent.com/26270880/130587649-54e8a6fa-0316-4ad4-a270-bd5d507b3d8e.png)

<img width="1769" alt="nginx-logs" src="https://user-images.githubusercontent.com/26270880/129184647-f391fe4f-f9c4-4297-9ce6-6e6a38cc5c61.png">

2021-08-12 11:20 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1523/detail/PR-1523/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1523/detail/PR-1523/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1523/detail/PR-1523/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1523/detail/PR-1523/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_1523.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2021-08-12T10:40:03.974Z&rangeTo=2021-08-12T11:00:03.974Z&transactionName=Ingest-manager/integrations/PR-{number}&transactionType=unknown&latencyAggregationType=avg&traceId=7d7dbf6bad890fbba7c4b3e8ba4539b2&transactionId=113810833c24d1a6)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2021-08-12T10:50:03.974+0000


* Duration: 30 min 54 sec


* Commit: d3cf43c2dd2dde27ed453aae45b0f246da87e5f8



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 113  |
| Skipped      | 0 |
| Total        | 113   |


#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/PR-1523/buildTimeGraph/png)


![Image of Tests](https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/PR-1523/1/testReport/history/countGraph/png?start=0&amp;end=25)


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2021-08-23 08:44 UTC, ChrsMark reviewed
Overall looks good to me and it should be a fair equivalent to https://github.com/elastic/beats/blob/3e2dcbea48e7a008ad981a69b0ad8d274e71350a/deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml#L216-L230. 

My only concern is about naming: Is `kube-pod-logs` ok or it should by just `pod-logs` (or even `container-logs`)? I'm afraid that by `kube-pod-logs` one could thing that we refer to logs from pods of the control plane like `controller` etc. Product team @mukeshelastic @akshay-saraswat  can provide some guidance here?

2021-08-23 14:57 UTC, mukeshelastic commented
I recommend container-logs because that is literally what we have.. Let's drop kube from the name because what @ChrsMark mentioned as potential confusion between control plane logs.

2021-08-24 08:53 UTC, elasticmachine commented
Pinging @elastic/integrations (Team:Integrations)

2021-08-24 08:54 UTC, MichaelKatsoulis commented
@ChrsMark , @mukeshelastic I changed the name to container-logs. It is ready for review now!

2021-08-24 09:42 UTC, ChrsMark requested changes

2021-08-24 09:42 UTC, ChrsMark commented on packages/kubernetes/_dev/build/docs/README.md
> +#### kube-pod-logs
this seems out dated

2021-08-24 09:42 UTC, ChrsMark commented on packages/kubernetes/docs/README.md
> +#### kube-pod-logs
this seems out dated too

2021-08-24 11:26 UTC, ChrsMark approved these changes
:+1:

2021-08-24 14:38 UTC, merged