New package for Carbon Black EDR logs
elastic/integrations pull request #1527
Opened 2021-08-14 15:48 UTC by adriansr

## What does this PR do?
Adds a new package for VMware Carbon Black EDR logs ingested via CB Event Forwarder.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] If I'm introducing a new feature, I have modified the Kibana version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^7.13.0`).

## Screenshots

TODO

2021-08-14 15:51 UTC, adriansr commented on packages/carbonback_edr/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/NNN
Update this

2021-08-14 15:52 UTC, adriansr commented on packages/carbonback_edr/manifest.yml
> +#icons:
Find an usable icon or remove this

2021-08-14 16:08 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1527/detail/PR-1527/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1527/detail/PR-1527/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1527/detail/PR-1527/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1527/detail/PR-1527/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_1527.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2021-08-14T15:38:27.546Z&rangeTo=2021-08-14T15:58:27.546Z&transactionName=Ingest-manager/integrations/PR-{number}&transactionType=unknown&latencyAggregationType=avg&traceId=45302c0b81a97de89fe0688afa9af08f&transactionId=7a4ac45cde2a6156)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2021-08-14T15:48:27.546+0000


* Duration: 20 min 18 sec


* Commit: b22fe8581db50374db646cd418a7a4b9f3e524d2



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 8  |
| Skipped      | 0 |
| Total        | 8   |


#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/PR-1527/buildTimeGraph/png)


![Image of Tests](https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/PR-1527/1/testReport/history/countGraph/png?start=0&amp;end=25)


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2021-08-16 09:18 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2021-08-17 14:03 UTC, leehinman requested changes
looks great.  2 minor things ecs.version bump and related.hash.  one optional.

2021-08-17 17:39 UTC, adriansr commented on packages/carbonback_edr/_dev/build/build.yml
> +    reference: git@1.10
Done

2021-08-17 17:39 UTC, adriansr commented on packages/carbonback_edr/data_stream/log/_dev/test/pipeline/test-events.json-expected.json
> +                    "sha256": "BCA92084BAC4A371631307A8015E0AB5F221CD0593D6D589007F2AF689B0C6FA",
Done

2021-08-17 17:39 UTC, adriansr commented on packages/carbonback_edr/data_stream/log/_dev/test/pipeline/test-events.json-expected.json
> +                    "md5": "B1EADD12A85FD321B05819041C27CC7B",
Done

2021-08-17 17:39 UTC, adriansr commented on packages/carbonback_edr/data_stream/log/manifest.yml
> +      - name: tags
I didn't know this was possible. Done

2021-08-17 18:03 UTC, adriansr commented on packages/carbonback_edr/data_stream/log/manifest.yml
> +      - name: tags
Turns out I can't get it to work. If I move those vars to the data_stream's top level either on the main manifest or the data_stream's manifest, there's no error but they don't show up in the UI. Do you have a working example?

2021-08-17 19:19 UTC, leehinman commented on packages/carbonback_edr/data_stream/log/manifest.yml
> +      - name: tags
For history I was thinking of what we did for zeek, but that is one variable for multiple data streams.  Looks like we don't have a way to do one variable for multiple inputs.

2021-08-17 19:19 UTC, leehinman approved these changes
LGTM

2021-08-17 21:01 UTC, merged

2022-03-29 05:11 UTC, CyberTaoFlow commented
no support for carbon black cloud events