ActiveMQ_package(#606)
elastic/integrations pull request #1550
Opened 2021-08-23 11:35 UTC by kush-crest

## What does this PR do?

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] If I'm introducing a new feature, I have modified the Kibana version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^7.13.0`).

## Author's Checklist

- [x] Each data streams should contains system tests.
- [x] Each data streams should contains sample_event.json.
- [x] Each data streams should successfully pass all tests.

## How to test this PR locally

- Clone integrations repo.
- Install elastic-package locally.
- Start elastic stack using elastic-package.
- Move to integrations/packages/activemq directory.
- Run following command to run system tests. elastic-package test system -v

## Related issues

- Relates #606

2021-08-23 11:39 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1550/detail/PR-1550/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1550/detail/PR-1550/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1550/detail/PR-1550/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1550/detail/PR-1550/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2021-08-23T11:25:56.803Z&rangeTo=2021-08-23T11:45:56.803Z&transactionName=Ingest-manager/integrations/PR-{number}&transactionType=unknown&latencyAggregationType=avg&traceId=0742e400c13844fbf375d7622386bddb&transactionId=73ce8f69ff48b481)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats



* Reason: `The PR is not allowed to run in the CI yet`


* Start Time: 2021-08-23T11:35:56.803+0000


* Duration: 3 min 7 sec


* Commit: 7851ca60b4c69e7d0912da0f572b773fb6065282




#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/PR-1550/buildTimeGraph/png)



</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->









### Steps errors [![3](https://img.shields.io/badge/3%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1550/detail/PR-1550/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Load a resource file from a shared library`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-1550/runs/1/steps/80/log/?start=0">here</a></li>
<li>Description: <code>approval-list/elastic/integrations.yml</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-1550/runs/1/steps/106/log/?start=0">here</a></li>

</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-1550/runs/1/steps/83/log/?start=0">here</a></li>
<li>Description: <code>githubPrCheckApproved: The PR is not allowed to run in the CI yet. (Only users with write permissions can do so.)</code></l1>
</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-08-23T11:38:25.479Z]  > git remote # timeout=10
[2021-08-23T11:38:25.484Z]  > git config --get remote.origin.url # timeout=10
[2021-08-23T11:38:25.488Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-08-23T11:38:25.491Z]  > git merge cbd829c069650918bb69f74663748bf7c118b2f7 # timeout=10
[2021-08-23T11:38:25.502Z]  > git rev-parse HEAD^{commit} # timeout=10
[2021-08-23T11:38:25.511Z]  > git config core.sparsecheckout # timeout=10
[2021-08-23T11:38:25.514Z]  > git checkout -f 7851ca60b4c69e7d0912da0f572b773fb6065282 # timeout=15
[2021-08-23T11:38:30.911Z] Commit message: "ActiveMQ_package(#606)"
[2021-08-23T11:38:30.912Z] First time build. Skipping changelog.
[2021-08-23T11:38:30.912Z] Cleaning workspace
[2021-08-23T11:38:31.079Z]  > git --version # timeout=10
[2021-08-23T11:38:31.083Z]  > git --version # 'git version 2.25.1'
[2021-08-23T11:38:31.086Z] fatal: bad object d11dc1f0af4927b4f3a9d92a4bff0584b7734b6b
[2021-08-23T11:38:30.914Z]  > git rev-parse --verify HEAD # timeout=10
[2021-08-23T11:38:30.918Z] Resetting working tree
[2021-08-23T11:38:30.918Z]  > git reset --hard # timeout=10
[2021-08-23T11:38:30.959Z]  > git clean -fdx # timeout=10
[2021-08-23T11:38:31.724Z] Timeout set to expire in 2 hr 0 min
[2021-08-23T11:38:31.752Z] The timestamps step is unnecessary when timestamps are enabled for all Pipeline builds.
[2021-08-23T11:38:32.562Z] [INFO] 'shallow' is forced to be disabled when running on PullRequests
[2021-08-23T11:38:32.586Z] Running in /var/lib/jenkins/workspace/est-manager_integrations_PR-1550/src/github.com/elastic/integrations
[2021-08-23T11:38:32.629Z] [INFO] gitCheckout: Checkout SCM PR-1550 with default customisation from the Item.
[2021-08-23T11:38:32.665Z] [INFO] Override default checkout
[2021-08-23T11:38:32.733Z] Sleeping for 10 sec
[2021-08-23T11:38:42.766Z] The recommended git tool is: git
[2021-08-23T11:38:42.866Z] using credential f6c7695a-671e-4f4f-a331-acdce44ff9ba
[2021-08-23T11:38:42.872Z] Wiping out workspace first.
[2021-08-23T11:38:42.885Z] Cloning the remote Git repository
[2021-08-23T11:38:42.885Z] Using shallow clone with depth 4
[2021-08-23T11:38:42.885Z] Avoid fetching tags
[2021-08-23T11:38:42.946Z] Cloning repository git@github.com:elastic/integrations.git
[2021-08-23T11:38:43.023Z]  > git init /var/lib/jenkins/workspace/est-manager_integrations_PR-1550/src/github.com/elastic/integrations # timeout=10
[2021-08-23T11:38:43.032Z] Fetching upstream changes from git@github.com:elastic/integrations.git
[2021-08-23T11:38:43.032Z]  > git --version # timeout=10
[2021-08-23T11:38:43.037Z]  > git --version # 'git version 2.25.1'
[2021-08-23T11:38:43.038Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-08-23T11:38:43.044Z]  > git fetch --no-tags --force --progress -- git@github.com:elastic/integrations.git +refs/heads/*:refs/remotes/origin/* # timeout=15
[2021-08-23T11:38:47.404Z] Cleaning workspace
[2021-08-23T11:38:47.419Z] Using shallow fetch with depth 4
[2021-08-23T11:38:47.419Z] Pruning obsolete local branches
[2021-08-23T11:38:48.029Z] Merging remotes/origin/master commit cbd829c069650918bb69f74663748bf7c118b2f7 into PR head commit 7851ca60b4c69e7d0912da0f572b773fb6065282
[2021-08-23T11:38:47.387Z]  > git config remote.origin.url git@github.com:elastic/integrations.git # timeout=10
[2021-08-23T11:38:47.390Z]  > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
[2021-08-23T11:38:47.398Z]  > git config remote.origin.url git@github.com:elastic/integrations.git # timeout=10
[2021-08-23T11:38:47.407Z]  > git rev-parse --verify HEAD # timeout=10
[2021-08-23T11:38:47.410Z] No valid HEAD. Skipping the resetting
[2021-08-23T11:38:47.410Z]  > git clean -fdx # timeout=10
[2021-08-23T11:38:47.422Z] Fetching upstream changes from git@github.com:elastic/integrations.git
[2021-08-23T11:38:47.423Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-08-23T11:38:47.426Z]  > git fetch --no-tags --force --progress --prune -- git@github.com:elastic/integrations.git +refs/pull/1550/head:refs/remotes/origin/PR-1550 +refs/heads/master:refs/remotes/origin/master # timeout=15
[2021-08-23T11:38:48.032Z]  > git config core.sparsecheckout # timeout=10
[2021-08-23T11:38:48.035Z]  > git checkout -f 7851ca60b4c69e7d0912da0f572b773fb6065282 # timeout=15
[2021-08-23T11:38:49.090Z] Merge succeeded, producing 7851ca60b4c69e7d0912da0f572b773fb6065282
[2021-08-23T11:38:49.091Z] Checking out Revision 7851ca60b4c69e7d0912da0f572b773fb6065282 (PR-1550)
[2021-08-23T11:38:49.165Z] Commit message: "ActiveMQ_package(#606)"
[2021-08-23T11:38:49.165Z]  [...]

2021-08-23 12:23 UTC, jsoriano commented
/test

2021-08-24 09:47 UTC, jsoriano commented
/test

2021-08-24 10:35 UTC, jsoriano requested changes

2021-08-24 10:35 UTC, jsoriano commented on packages/activemq/data_stream/broker/fields/ecs.yml
> +      example: elasticsearch
Please use `external` notation for ECS fields as done here for example: https://github.com/elastic/integrations/blob/227e245005f08881ffcb9535b393e08aa363c2e0/packages/apache/data_stream/access/fields/ecs.yml
This way you don't need to copy all the descriptions and so on.

2021-08-24 10:35 UTC, jsoriano commented on packages/activemq/data_stream/queue/fields/fields.yml
> +  release: ga
```suggestion
  release: beta
```

2021-08-24 10:35 UTC, jsoriano commented on packages/activemq/data_stream/queue/manifest.yml
> +release: experimental
```suggestion
release: beta
```

2021-08-24 10:35 UTC, jsoriano commented on packages/activemq/data_stream/topic/fields/fields.yml
> +  release: ga
```suggestion
  release: beta
```

2021-08-24 10:35 UTC, jsoriano commented on packages/activemq/data_stream/topic/manifest.yml
> +release: experimental
```suggestion
release: beta
```

2021-08-24 10:35 UTC, jsoriano commented on packages/activemq/data_stream/audit/manifest.yml
> +release: experimental
```suggestion
release: beta
```

2021-08-24 10:35 UTC, jsoriano commented on packages/activemq/data_stream/broker/fields/fields.yml
> +  release: ga
Let's start with beta.
```suggestion
  release: beta
```

2021-08-24 10:35 UTC, jsoriano commented on packages/activemq/data_stream/broker/manifest.yml
> +release: experimental
Experimental should be used only for features that we don't plan to give any kind of support in the long term in their current form.
```suggestion
release: beta
```

2021-08-24 10:35 UTC, jsoriano commented on packages/activemq/data_stream/log/manifest.yml
> +release: experimental
```suggestion
release: beta
```

2021-08-24 10:35 UTC, jsoriano commented on packages/activemq/data_stream/log/fields/ecs.yml
> +  description: Log flags
```suggestion
- name: log.flags
  external: ecs
```

2021-08-24 10:35 UTC, jsoriano commented on packages/activemq/data_stream/queue/fields/ecs.yml
> +      example: elasticsearch
Use `external` for ECS fields.

2021-08-24 10:35 UTC, jsoriano commented on packages/activemq/data_stream/topic/fields/ecs.yml
> +      example: elasticsearch
Use `external`.

2021-08-24 10:35 UTC, jsoriano commented on packages/activemq/manifest.yml
> +  kibana.version: ^7.9.0
We may want to use `7.14.1` or `7.15.0` here.

2021-08-25 05:16 UTC, kush-crest commented on packages/activemq/manifest.yml
> +  kibana.version: ^7.9.0
packages/activemq/manifest.yml
```version: 0.0.1
release: experimental
description: ActiveMQ Integration
```

Do i need to change release: experimental to release: beta here too?

2021-08-25 07:15 UTC, kush-crest commented on packages/activemq/_dev/deploy/docker/Dockerfile
> +ENV ACTIVEMQ_VERSION=5.15.9
Done

2021-08-25 07:15 UTC, kush-crest commented on packages/activemq/data_stream/audit/agent/stream/log.yml.hbs
> +        ecs.version: 1.10.0
Done

2021-08-25 07:15 UTC, kush-crest commented on packages/activemq/data_stream/broker/fields/ecs.yml
> +      example: elasticsearch
Done

2021-08-25 07:15 UTC, kush-crest commented on packages/activemq/data_stream/queue/fields/fields.yml
> +  release: ga
Done

2021-08-25 07:16 UTC, kush-crest commented on packages/activemq/data_stream/queue/manifest.yml
> +release: experimental
Done

2021-08-25 07:16 UTC, kush-crest commented on packages/activemq/data_stream/topic/fields/fields.yml
> +  release: ga
Done

2021-08-25 07:16 UTC, kush-crest commented on packages/activemq/data_stream/topic/manifest.yml
> +release: experimental
Done

2021-08-25 07:16 UTC, kush-crest commented on packages/activemq/data_stream/audit/manifest.yml
> +release: experimental
Done

2021-08-25 07:16 UTC, kush-crest commented on packages/activemq/data_stream/broker/fields/fields.yml
> +  release: ga
Done

2021-08-25 07:16 UTC, kush-crest commented on packages/activemq/data_stream/broker/manifest.yml
> +release: experimental
Done

2021-08-25 07:16 UTC, kush-crest commented on packages/activemq/data_stream/log/manifest.yml
> +release: experimental
Done

2021-08-25 07:17 UTC, kush-crest commented on packages/activemq/data_stream/log/fields/ecs.yml
> +  description: Log flags
Done

2021-08-25 07:17 UTC, kush-crest commented on packages/activemq/data_stream/queue/fields/ecs.yml
> +      example: elasticsearch
Done

2021-08-25 07:17 UTC, kush-crest commented on packages/activemq/data_stream/topic/fields/ecs.yml
> +      example: elasticsearch
Done

2021-08-25 07:17 UTC, kush-crest commented on packages/activemq/manifest.yml
> +  kibana.version: ^7.9.0
Done

2021-08-30 15:03 UTC, jsoriano commented
/test

2021-08-30 15:28 UTC, merged