[vSphere] Add vSphere package
elastic/integrations pull request #1579
Opened 2021-09-06 15:07 UTC by legoguy1000

## What does this PR do?

Adds initial vSphere package (copied from Metricbeat module).  Added syslog input for vCenter logs.

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [X] I have added an entry to my package's `changelog.yml` file.
- [X] If I'm introducing a new feature, I have modified the Kibana version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^7.13.0`).

## Author's Checklist

- [ ]

## How to test this PR locally
```
cd integrations/packages/pfsense
elastic-package check && elastic-package stack down && elastic-package build && elastic-package stack up -d -v && eval "$(elastic-package stack shellinit)" && elastic-package test  -v
```

## Related issues

<!-- Recommended
Link related issues below. Insert the issue link or reference after the word "Closes" if merging this should automatically close it.

- Closes #642 

## Screenshots
Dashboards copied from Metricbeat module
![metricbeat_vsphere_vm_dashboard](https://user-images.githubusercontent.com/13125104/132236728-05db99eb-7c72-473f-a70f-4f834efe72a2.png)
![metricbeat_vsphere_dashboard](https://user-images.githubusercontent.com/13125104/132236731-d53d02bd-0d32-450c-8754-f8193f667366.png)

2021-09-06 15:11 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1579/detail/PR-1579/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1579/detail/PR-1579/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1579/detail/PR-1579/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1579/detail/PR-1579/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2021-09-06T14:58:07.978Z&rangeTo=2021-09-06T15:18:07.978Z&transactionName=Ingest-manager/integrations/PR-{number}&transactionType=unknown&latencyAggregationType=avg&traceId=27ee9e8197e8f9825ad8738bc3872627&transactionId=62df667f4b385907)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats



* Reason: `The PR is not allowed to run in the CI yet`


* Start Time: 2021-09-06T15:08:07.978+0000


* Duration: 3 min 59 sec


* Commit: 9d1985149c3be8c11d901118a9edd7f59905eda0




#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/PR-1579/buildTimeGraph/png)



</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->









### Steps errors [![3](https://img.shields.io/badge/3%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1579/detail/PR-1579/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Load a resource file from a shared library`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-1579/runs/1/steps/80/log/?start=0">here</a></li>
<li>Description: <code>approval-list/elastic/integrations.yml</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-1579/runs/1/steps/106/log/?start=0">here</a></li>

</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-1579/runs/1/steps/83/log/?start=0">here</a></li>
<li>Description: <code>githubPrCheckApproved: The PR is not allowed to run in the CI yet. (Only users with write permissions can do so.)</code></l1>
</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-09-06T15:10:26.811Z]  > git remote # timeout=10
[2021-09-06T15:10:26.816Z]  > git config --get remote.origin.url # timeout=10
[2021-09-06T15:10:26.820Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-09-06T15:10:26.823Z]  > git merge 1d28bf2548255597697c53ea3c095d8679da5856 # timeout=10
[2021-09-06T15:10:26.834Z]  > git rev-parse HEAD^{commit} # timeout=10
[2021-09-06T15:10:26.844Z]  > git config core.sparsecheckout # timeout=10
[2021-09-06T15:10:26.848Z]  > git checkout -f 9d1985149c3be8c11d901118a9edd7f59905eda0 # timeout=15
[2021-09-06T15:10:32.727Z] Commit message: "#642: Add vSphere package"
[2021-09-06T15:10:32.727Z] First time build. Skipping changelog.
[2021-09-06T15:10:32.727Z] Cleaning workspace
[2021-09-06T15:10:32.907Z]  > git --version # timeout=10
[2021-09-06T15:10:32.910Z]  > git --version # 'git version 2.25.1'
[2021-09-06T15:10:32.914Z] fatal: bad object c5f57d47a0629cbee35e4f521afa55cd7028e994
[2021-09-06T15:10:32.730Z]  > git rev-parse --verify HEAD # timeout=10
[2021-09-06T15:10:32.733Z] Resetting working tree
[2021-09-06T15:10:32.733Z]  > git reset --hard # timeout=10
[2021-09-06T15:10:32.781Z]  > git clean -fdx # timeout=10
[2021-09-06T15:10:33.801Z] Timeout set to expire in 2 hr 0 min
[2021-09-06T15:10:33.830Z] The timestamps step is unnecessary when timestamps are enabled for all Pipeline builds.
[2021-09-06T15:10:34.539Z] [INFO] 'shallow' is forced to be disabled when running on PullRequests
[2021-09-06T15:10:34.563Z] Running in /var/lib/jenkins/workspace/est-manager_integrations_PR-1579/src/github.com/elastic/integrations
[2021-09-06T15:10:34.609Z] [INFO] gitCheckout: Checkout SCM PR-1579 with default customisation from the Item.
[2021-09-06T15:10:34.649Z] [INFO] Override default checkout
[2021-09-06T15:10:34.737Z] Sleeping for 10 sec
[2021-09-06T15:10:44.769Z] The recommended git tool is: git
[2021-09-06T15:10:44.870Z] using credential f6c7695a-671e-4f4f-a331-acdce44ff9ba
[2021-09-06T15:10:44.876Z] Wiping out workspace first.
[2021-09-06T15:10:44.887Z] Cloning the remote Git repository
[2021-09-06T15:10:44.887Z] Using shallow clone with depth 4
[2021-09-06T15:10:44.887Z] Avoid fetching tags
[2021-09-06T15:10:44.949Z] Cloning repository git@github.com:elastic/integrations.git
[2021-09-06T15:10:45.026Z]  > git init /var/lib/jenkins/workspace/est-manager_integrations_PR-1579/src/github.com/elastic/integrations # timeout=10
[2021-09-06T15:10:45.031Z] Fetching upstream changes from git@github.com:elastic/integrations.git
[2021-09-06T15:10:45.032Z]  > git --version # timeout=10
[2021-09-06T15:10:45.037Z]  > git --version # 'git version 2.25.1'
[2021-09-06T15:10:45.037Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-09-06T15:10:45.042Z]  > git fetch --no-tags --force --progress -- git@github.com:elastic/integrations.git +refs/heads/*:refs/remotes/origin/* # timeout=15
[2021-09-06T15:10:49.709Z] Cleaning workspace
[2021-09-06T15:10:49.725Z] Using shallow fetch with depth 4
[2021-09-06T15:10:49.725Z] Pruning obsolete local branches
[2021-09-06T15:10:49.692Z]  > git config remote.origin.url git@github.com:elastic/integrations.git # timeout=10
[2021-09-06T15:10:49.695Z]  > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
[2021-09-06T15:10:49.704Z]  > git config remote.origin.url git@github.com:elastic/integrations.git # timeout=10
[2021-09-06T15:10:49.711Z]  > git rev-parse --verify HEAD # timeout=10
[2021-09-06T15:10:49.716Z] No valid HEAD. Skipping the resetting
[2021-09-06T15:10:49.716Z]  > git clean -fdx # timeout=10
[2021-09-06T15:10:49.728Z] Fetching upstream changes from git@github.com:elastic/integrations.git
[2021-09-06T15:10:49.728Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-09-06T15:10:49.732Z]  > git fetch --no-tags --force --progress --prune -- git@github.com:elastic/integrations.git +refs/pull/1579/head:refs/remotes/origin/PR-1579 +refs/heads/master:refs/remotes/origin/master # timeout=15
[2021-09-06T15:10:50.359Z] Merging remotes/origin/master commit 1d28bf2548255597697c53ea3c095d8679da5856 into PR head commit 9d1985149c3be8c11d901118a9edd7f59905eda0
[2021-09-06T15:10:51.412Z] Merge succeeded, producing 9d1985149c3be8c11d901118a9edd7f59905eda0
[2021-09-06T15:10:51.413Z] Checking out Revision 9d1985149c3be8c11d901118a9edd7f59905eda0 (PR-1579)
[2021-09-06T15:10:50.362Z]  > git config core.sparsecheckout # timeout=10
[2021-09-06T15:10:50.365Z]  > git checkout -f 9d1985149c3be8c11d901118a9edd7f59905eda0 # timeout=15
[2021-09-06T15:10:51.385Z]  > git remote # timeout=10
[2021-09-06T15:10:51.389Z]  > git con [...]

2021-09-08 08:39 UTC, elasticmachine commented
Pinging @elastic/integrations (Team:Integrations)

2021-09-13 10:49 UTC, legoguy1000 commented on packages/vsphere/_dev/build/build.yml
> +    reference: git@1.11
Need to update to 1.12

2021-09-13 10:49 UTC, legoguy1000 commented on packages/vsphere/data_stream/log/elasticsearch/ingest_pipeline/default.yml
> +      value: '1.11.0'
Need to update to 1.12

2021-09-14 08:07 UTC, jsoriano requested changes
Thanks for working on the migration of this integration!

2021-09-14 08:07 UTC, jsoriano commented on packages/vsphere/data_stream/virtualmachine/fields/ecs.yml
> +  type: text
Use `external`.

2021-09-14 08:07 UTC, jsoriano commented on packages/vsphere/manifest.yml
> +release: experimental
```suggestion
release: beta
```

2021-09-14 08:08 UTC, jsoriano commented
/test

2021-09-14 11:10 UTC, legoguy1000 commented
@jsoriano Updates made

2021-09-14 11:42 UTC, jsoriano approved these changes
Great, thanks!

2021-09-14 11:42 UTC, jsoriano commented
/test

2021-09-14 14:30 UTC, jsoriano commented
@legoguy1000 there seems to be some formatting issues, can you take a look?

2021-09-14 14:37 UTC, legoguy1000 commented
> @legoguy1000 there seems to be some formatting issues, can you take a look?

Done.  The formatting will be the death of me

2021-09-15 09:37 UTC, jsoriano approved these changes

2021-09-15 09:37 UTC, merged

2021-12-09 16:00 UTC, jsoriano commented
> do you know if this package is stuck in staging? Don't see it listed in our integration docs or within the Kibana integrations page (7.16).

Yes, I think this package has been never promoted to production. Pinging @elastic/integrations to see if this can be promoted.

2021-12-09 16:30 UTC, kaiyan-sheng commented
I haven't tested this integration yet but seems like @marc-gr already made a bug fix on it. Marc, do you think this package is ready to be promoted? Also just a thought, maybe the owner should be the security-external-integrations team for now? 😄