Make Apache integration GA
elastic/integrations pull request #1607
Opened 2021-09-09 08:24 UTC by sayden

## What does this PR do?

Release Apache integration as GA

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] If I'm introducing a new feature, I have modified the Kibana version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^7.13.0`).

2021-09-09 08:24 UTC, elasticmachine commented
Pinging @elastic/integrations (Team:Integrations)

2021-09-09 08:28 UTC, jsoriano commented on packages/apache/manifest.yml
> +release: ga
I think this should be updated in the data stream manifests too.

2021-09-09 08:28 UTC, mtojek approved these changes

2021-09-09 08:28 UTC, mtojek commented on packages/apache/manifest.yml
>    kibana.version: "^7.14.0"
nit: is it bound with a particular Kibana release or not?

2021-09-09 08:34 UTC, mtojek commented on packages/apache/manifest.yml
> +release: ga
FTR "GA" for data streams means removing the "release" property at all (according to spec).

2021-09-09 08:39 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1607/detail/PR-1607/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1607/detail/PR-1607/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1607/detail/PR-1607/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1607/detail/PR-1607/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_1607.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2021-09-09T08:14:43.894Z&rangeTo=2021-09-09T08:34:43.894Z&transactionName=Ingest-manager/integrations/PR-{number}&transactionType=unknown&latencyAggregationType=avg&traceId=cbf714d65038b0bc04b8e243ff20321a&transactionId=538adf0dc65c0691)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2021-09-09T08:24:43.894+0000


* Duration: 15 min 57 sec


* Commit: ff5748f53d12c48c3a0ae420e7f1d46285858406



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 43  |
| Skipped      | 0 |
| Total        | 43   |


#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/PR-1607/buildTimeGraph/png)


![Image of Tests](https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/PR-1607/1/testReport/history/countGraph/png?start=0&amp;end=25)


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2021-09-09 10:14 UTC, sayden commented on packages/apache/manifest.yml
>    kibana.version: "^7.14.0"
It shouldn't. Why the version should be different if everything is the same? Maybe I'm missing something :thinking:

2021-09-10 07:39 UTC, mtojek requested changes
There are some unadressed comments.

2021-09-10 07:45 UTC, mtojek commented on packages/apache/manifest.yml
>    kibana.version: "^7.14.0"
We had an offline chat with Jaime, I agree we can take the risk here and leave the constraint as is (please ignore this comment).

2021-09-10 11:14 UTC, mtojek commented
@sayden Please take a look at the CI report. If the package is "GA", you don't need the property "release".

2021-09-10 12:23 UTC, mtojek approved these changes

2021-09-13 12:43 UTC, sayden commented
Ok so I removed the `release` property from data_streams :)

2021-09-13 12:43 UTC, merged