Add cassandra package and log data-stream
elastic/integrations pull request #1745
Opened 2021-09-21 10:33 UTC by kush-elastic

## What does this PR do?

- This PR is draft PR for suggestions and reviewing cassandra integration for log data-stream.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] If I'm introducing a new feature, I have modified the Kibana version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^7.13.0`).

## How to test this PR locally

- Clone integrations repo.
- Install elastic-package locally.
- Start elastic stack using elastic-package.
- Move to integrations/packages/cassandra directory.
- Run following command to run tests. elastic-package test -v

## Related issues

- Relates #381 

## Screenshots
![image](https://user-images.githubusercontent.com/89848966/134155883-f8a6abde-c2ac-4785-9200-0de1d0332a97.png)

2021-09-21 10:36 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1745/detail/PR-1745/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1745/detail/PR-1745/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1745/detail/PR-1745/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1745/detail/PR-1745/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2021-09-21T10:23:39.948Z&rangeTo=2021-09-21T10:43:39.948Z&transactionName=Ingest-manager/integrations/PR-{number}&transactionType=unknown&latencyAggregationType=avg&traceId=0303097fe36adb82d3c870b39e9ac017&transactionId=b0ba8111193028b6)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats



* Reason: `The PR is not allowed to run in the CI yet`


* Start Time: 2021-09-21T10:33:39.948+0000


* Duration: 3 min 48 sec


* Commit: a7daa35f6016a1a847a39fd683322d1627635bbe




#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/PR-1745/buildTimeGraph/png)



</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->









### Steps errors [![3](https://img.shields.io/badge/3%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-1745/detail/PR-1745/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Load a resource file from a shared library`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-1745/runs/1/steps/80/log/?start=0">here</a></li>
<li>Description: <code>approval-list/elastic/integrations.yml</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-1745/runs/1/steps/106/log/?start=0">here</a></li>

</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-1745/runs/1/steps/83/log/?start=0">here</a></li>
<li>Description: <code>githubPrCheckApproved: The PR is not allowed to run in the CI yet. (Only users with write permissions can do so.)</code></l1>
</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-09-21T10:35:44.655Z] Checking out Revision 9fc902f2ee90a610330f1c635f6a37713db48418 (PR-1745)
[2021-09-21T10:35:44.649Z]  > git rev-parse HEAD^{commit} # timeout=10
[2021-09-21T10:35:44.658Z]  > git config core.sparsecheckout # timeout=10
[2021-09-21T10:35:44.662Z]  > git checkout -f 9fc902f2ee90a610330f1c635f6a37713db48418 # timeout=15
[2021-09-21T10:35:49.523Z] Commit message: "Merge commit 'bd7a0d8e053b1a51a1338cdc8c6e3d3d8658d744' into HEAD"
[2021-09-21T10:35:49.524Z] First time build. Skipping changelog.
[2021-09-21T10:35:49.524Z] Cleaning workspace
[2021-09-21T10:35:49.721Z]  > git --version # timeout=10
[2021-09-21T10:35:49.724Z]  > git --version # 'git version 2.25.1'
[2021-09-21T10:35:49.727Z] fatal: bad object 1c8ed22ab8cf441e7c1995377954b93c51bd4997
[2021-09-21T10:35:49.526Z]  > git rev-parse --verify HEAD # timeout=10
[2021-09-21T10:35:49.530Z] Resetting working tree
[2021-09-21T10:35:49.530Z]  > git reset --hard # timeout=10
[2021-09-21T10:35:49.580Z]  > git clean -fdx # timeout=10
[2021-09-21T10:35:50.589Z] Timeout set to expire in 2 hr 0 min
[2021-09-21T10:35:50.642Z] The timestamps step is unnecessary when timestamps are enabled for all Pipeline builds.
[2021-09-21T10:35:51.645Z] [INFO] 'shallow' is forced to be disabled when running on PullRequests
[2021-09-21T10:35:51.688Z] Running in /var/lib/jenkins/workspace/est-manager_integrations_PR-1745/src/github.com/elastic/integrations
[2021-09-21T10:35:51.772Z] [INFO] gitCheckout: Checkout SCM PR-1745 with default customisation from the Item.
[2021-09-21T10:35:51.828Z] [INFO] Override default checkout
[2021-09-21T10:35:51.983Z] Sleeping for 10 sec
[2021-09-21T10:36:02.037Z] The recommended git tool is: git
[2021-09-21T10:36:02.146Z] using credential f6c7695a-671e-4f4f-a331-acdce44ff9ba
[2021-09-21T10:36:02.155Z] Wiping out workspace first.
[2021-09-21T10:36:02.166Z] Cloning the remote Git repository
[2021-09-21T10:36:02.166Z] Using shallow clone with depth 4
[2021-09-21T10:36:02.166Z] Avoid fetching tags
[2021-09-21T10:36:02.229Z] Cloning repository git@github.com:elastic/integrations.git
[2021-09-21T10:36:02.347Z]  > git init /var/lib/jenkins/workspace/est-manager_integrations_PR-1745/src/github.com/elastic/integrations # timeout=10
[2021-09-21T10:36:02.353Z] Fetching upstream changes from git@github.com:elastic/integrations.git
[2021-09-21T10:36:02.353Z]  > git --version # timeout=10
[2021-09-21T10:36:02.357Z]  > git --version # 'git version 2.25.1'
[2021-09-21T10:36:02.357Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-09-21T10:36:02.362Z]  > git fetch --no-tags --force --progress -- git@github.com:elastic/integrations.git +refs/heads/*:refs/remotes/origin/* # timeout=15
[2021-09-21T10:36:08.396Z]  > git config remote.origin.url git@github.com:elastic/integrations.git # timeout=10
[2021-09-21T10:36:08.400Z]  > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
[2021-09-21T10:36:09.622Z] Cleaning workspace
[2021-09-21T10:36:09.637Z] Using shallow fetch with depth 4
[2021-09-21T10:36:09.637Z] Pruning obsolete local branches
[2021-09-21T10:36:09.616Z]  > git config remote.origin.url git@github.com:elastic/integrations.git # timeout=10
[2021-09-21T10:36:09.625Z]  > git rev-parse --verify HEAD # timeout=10
[2021-09-21T10:36:09.628Z] No valid HEAD. Skipping the resetting
[2021-09-21T10:36:09.628Z]  > git clean -fdx # timeout=10
[2021-09-21T10:36:09.640Z] Fetching upstream changes from git@github.com:elastic/integrations.git
[2021-09-21T10:36:09.640Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-09-21T10:36:09.644Z]  > git fetch --no-tags --force --progress --prune -- git@github.com:elastic/integrations.git +refs/pull/1745/head:refs/remotes/origin/PR-1745 +refs/heads/master:refs/remotes/origin/master # timeout=15
[2021-09-21T10:36:10.318Z] Merging remotes/origin/master commit bd7a0d8e053b1a51a1338cdc8c6e3d3d8658d744 into PR head commit a7daa35f6016a1a847a39fd683322d1627635bbe
[2021-09-21T10:36:10.321Z]  > git config core.sparsecheckout # timeout=10
[2021-09-21T10:36:10.324Z]  > git checkout -f a7daa35f6016a1a847a39fd683322d1627635bbe # timeout=15
[2021-09-21T10:36:11.423Z]  > git remote # timeout=10
[2021-09-21T10:36:11.426Z]  > git config --get remote.origin.url # timeout=10
[2021-09-21T10:36:11.429Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-09-21T10:36:11.433Z]  > git merge bd7a0d8e053b1a51a1338cdc8c6e3d3d8658d744 # timeout=10
[2021-09-21T10:36:12.262Z] Merge succeeded, producing 1ca5958907f7a8fbc02d27dd369d3067a1e992d1
[2021-09-21T10:36:12.263Z] Checking out Revision 1ca5958907f [...]

2021-09-22 07:36 UTC, mtojek commented
/test

2021-09-22 08:10 UTC, mtojek requested changes
First round of reviews, left few comments on the design.

2021-09-22 08:10 UTC, mtojek commented on packages/cassandra/_dev/deploy/docker/Dockerfile
> +FROM adoptopenjdk:8-jre-hotspot-focal
What was the reason that you decided to write the Dockerfile on your own instead of using official images: https://hub.docker.com/_/cassandra ? 

I think we should go that way and in the worst case extend the base image.

2021-09-22 08:10 UTC, mtojek commented on packages/cassandra/_dev/build/build.yml
> +    reference: git@1.11
Please check if 1.12 isn't ready.

2021-09-22 08:10 UTC, mtojek commented on packages/cassandra/data_stream/metrics/sample_event.json
> +                "mbean": "org.apache.cassandra.metrics:type=ClientRequest,scope=*,name=*",
We don't expose mbean fields at all.

2021-09-22 08:10 UTC, mtojek commented on packages/cassandra/data_stream/metrics/sample_event.json
> +                    "75thPercentile": 30130.992000000002,
If we need to do metrics math like percentiles, average, mid, we're using Kibana for this, so all these percentile metrics can be removed.

2021-09-22 08:10 UTC, mtojek commented on packages/cassandra/data_stream/metrics/sample_event.json
> +                "LiveSSTableCount": 11,
naming convention for all metrics:

live_ss_table_count (snake case)__

2021-09-22 08:10 UTC, mtojek commented on packages/cassandra/data_stream/metrics/agent/stream/stream.yml.hbs
> +  - mbean: 'org.apache.cassandra.metrics:name=PendingTasks,path=request,scope=CounterMutationStage,type=ThreadPools'
Is there an option to collect all metrics for `path=*`, but the path is treated/stored as any other document property? This way you can filter docs with Kibana (`PATH=request and FOO=BAR`).

2021-09-30 05:52 UTC, kush-elastic commented on packages/cassandra/data_stream/log/_dev/test/system/test-logfile-config.yml
> +service: cassandra-logfile
Changed 
only one service will be used which is cassandra.

2021-09-30 05:52 UTC, kush-elastic commented on packages/cassandra/_dev/deploy/docker/Dockerfile
> +FROM adoptopenjdk:8-jre-hotspot-focal
Changed
used cassandra official image.

2021-09-30 05:54 UTC, kush-elastic commented on packages/cassandra/_dev/build/build.yml
> +    reference: git@1.11
Changed
now ecs version is 1.12.0

2021-09-30 05:55 UTC, kush-elastic commented on packages/cassandra/data_stream/metrics/sample_event.json
> +                "mbean": "org.apache.cassandra.metrics:type=ClientRequest,scope=*,name=*",
Updated
removed mbean fields

2021-09-30 05:55 UTC, kush-elastic commented on packages/cassandra/data_stream/metrics/sample_event.json
> +                    "75thPercentile": 30130.992000000002,
Updated
removed Percentile fields

2021-09-30 05:56 UTC, kush-elastic commented on packages/cassandra/data_stream/metrics/sample_event.json
> +                "LiveSSTableCount": 11,
Updated
changed naming convention to snake case

2021-09-30 06:00 UTC, kush-elastic commented on packages/cassandra/data_stream/metrics/agent/stream/stream.yml.hbs
> +  - mbean: 'org.apache.cassandra.metrics:name=PendingTasks,path=request,scope=CounterMutationStage,type=ThreadPools'
Updated
There were actually only two paths and for following metrics from threadpool we will only used path for request only so no need to set as `path=*`

`org.apache.cassandra.metrics:name=(ActiveTasks:PendingTasks),path=request,scope=CounterMutationStage,type=ThreadPools
org.apache.cassandra.metrics:name=(ActiveTasks:PendingTasks),path=request,scope=MutationStage,type=ThreadPools
org.apache.cassandra.metrics:name=(ActiveTasks:PendingTasks),path=request,scope=ReadRepairStage,type=ThreadPools
org.apache.cassandra.metrics:name=(ActiveTasks:PendingTasks),path=request,scope=ReadStage,type=ThreadPools
org.apache.cassandra.metrics:name=(ActiveTasks:PendingTasks),path=request,scope=RequestResponseStage,type=ThreadPools`

2021-09-30 07:07 UTC, mtojek commented on packages/cassandra/_dev/deploy/docker/Dockerfile
> +COPY docker-entrypoint-initdb.d /docker-entrypoint-initdb.d
nit: maybe add a comment why do we need a custom docker entrypoint

2021-09-30 07:07 UTC, mtojek commented on packages/cassandra/_dev/deploy/variants.yml
> +  v3.11.11:
Did you try with older versions to?

2021-09-30 07:07 UTC, mtojek commented on packages/cassandra/manifest.yml
> +            default: ffa
nit: is it the default Cassandra user/password: ffa/ffa? If it isn't, can we change it to something "really" default?

2021-09-30 07:07 UTC, mtojek commented on packages/cassandra/manifest.yml
> +        vars:
I think you can hide (`show_user: false`) few of these variables: path, username, password.

2021-09-30 07:07 UTC, mtojek commented
/test

2021-10-04 13:26 UTC, mtojek commented
/test

2021-10-05 11:54 UTC, mtojek commented
/test

2021-10-05 12:24 UTC, kush-elastic commented on packages/cassandra/_dev/deploy/variants.yml
> +  v3.11.11:
i have tested integration with:
2.2
3.0
3.11
4.0

2021-10-05 12:25 UTC, kush-elastic commented on packages/cassandra/manifest.yml
> +            default: ffa
Updated:
admin/admin

2021-10-05 12:25 UTC, kush-elastic commented on packages/cassandra/manifest.yml
> +        vars:
updated
for path, username, password

2021-10-05 12:31 UTC, mtojek commented
/test

2021-10-05 13:42 UTC, mtojek approved these changes
I don't see anything blocking here. You're good to go! Well done.

BTW I left a comment about service variants, but it isn't blocking. You can do this later on while maintaining the integration.

2021-10-05 13:42 UTC, mtojek commented on packages/cassandra/_dev/deploy/docker/docker-compose.yml
> +    image: cassandra:3.11.11
Hmmmm... you have service variants, but 3.11.11 here. Is there an option to test with other versions?

2021-10-05 13:42 UTC, mtojek commented on packages/cassandra/_dev/deploy/variants.yml
> +  v3.11.11:
Sure, but could you define it here to see if the integration works?

It can be done once this PR is merged (non-blocking).

2021-10-06 21:14 UTC, merged