[GCP] Add GCP Metrics Data streams
elastic/integrations pull request #2066
Opened 2021-10-29 17:56 UTC by legoguy1000

## What does this PR do?

Migrates GCP Metricsets to GCP package

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] If I'm introducing a new feature, I have modified the Kibana version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^7.13.0`).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

- Closes #490

## Screenshots

2021-11-03 10:43 UTC, endorama requested changes

2021-11-03 10:45 UTC, endorama commented
/test

2021-11-03 12:03 UTC, legoguy1000 commented on packages/gcp/_dev/build/docs/logs.md
> +The Google Cloud Project Logs integration collects and parses Google Cloud audit, VPC flow,
Ya, I meant Platform.

2021-11-03 12:49 UTC, legoguy1000 commented on packages/gcp/manifest.yml
> +        #     description: "GCP Alternative host"
@endorama When I uncomment this and lines 101-124 and then try to configure the integration I get the below error.  Any ideas? I can move the alternative host setting to each data stream but I think it makes sense to keep it at this level.
![image](https://user-images.githubusercontent.com/13125104/140062716-b81d5fa7-c4dc-4cd5-b753-013ea148b612.png)

2021-11-03 14:22 UTC, endorama commented on packages/gcp/manifest.yml
> +        #     description: "GCP Alternative host"
I think this is a known missing feature, [Fleet does not support input level variables](https://github.com/elastic/kibana/issues/112272). Is this the case?

2021-11-03 14:47 UTC, legoguy1000 commented on packages/gcp/manifest.yml
> +        #     description: "GCP Alternative host"
I mean that lines up but if you look at the current version of the GCP package, it currently has input level variables, https://github.com/elastic/integrations/blob/master/packages/gcp/manifest.yml#L33.  I haven't actually brought up a stack with the current version of the package to see if it also errors out.

2021-11-08 16:53 UTC, endorama commented on packages/gcp/manifest.yml
> +        #     description: "GCP Alternative host"
You can have 1 input with input level packages, but multiple inputs are not supported. So the solution is to move variables to the package level instead.

2021-11-08 17:03 UTC, endorama commented
Hello @legoguy1000, I spent some time on this PR but the changes is very big and is difficult to review. Moreover I would like to add tests alongside all these changes, but this proves difficult.

As I really value this contribution and I would like to move it forward, here is my proposal: I created a new branch called [`gcp-metrics`](https://github.com/elastic/integrations/tree/gcp-metrics). May you to split this PR into multiple ones (one for each datastream/metricset) and target `gcp-metrics` as base branch?
Doing that would allow better review and being able to merge and add tests in smaller batches, which in the end will speed up inclusion.

What do you think? From your side the only additional effort would be to split this PR, as then I would be able add the missing pieces as needed.

Thank you!

2021-11-08 18:21 UTC, legoguy1000 commented on packages/gcp/manifest.yml
> +        #     description: "GCP Alternative host"
ok, i figured it was something like that.

2021-11-08 18:44 UTC, closed without merging

2021-11-08 18:55 UTC, legoguy1000 commented
Do you want me to make each log/metricset its own policy template so they can show up individually like AWS or like I had it and just group Logs and Metrics?

2021-11-15 15:56 UTC, endorama commented
@legoguy1000 As in the AWS integration I expect each data stream will require it's own policy, but I'll check internally. In any case as we are targetting a dedicated branch I can help performing these changes after merge :)