microsoft: changes for unified integration UI
elastic/integrations pull request #2099
Opened 2021-11-02 09:53 UTC by endorama

## What does this PR do?

Align package title and description for improved Unified Integration UI display.

## Checklist

- [ ] ~~I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.~~
- [ ] ~~I have verified that all data streams collect metrics or logs.~~
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] ~~If I'm introducing a new feature, I have modified the Kibana version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^7.13.0`).~~

## Author's Checklist

- [ ] promote package to staging
- [ ] promote package to production

## How to test this PR locally

## Related issues

- Part of https://github.com/elastic/integrations/issues/1901

## Screenshots

2021-11-02 09:53 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2021-11-02 10:59 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2099/detail/PR-2099/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2099/detail/PR-2099/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2099/detail/PR-2099/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2099/detail/PR-2099/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_2099.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2021-11-02T09:43:34.840Z&rangeTo=2021-11-02T10:03:34.840Z&transactionName=Ingest-manager/integrations/PR-{number}&transactionType=unknown&latencyAggregationType=avg&traceId=f909e1aae4798115fcfa03607ef9e01b&transactionId=2caa6bec9669a60b)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2021-11-02T09:53:34.840+0000


* Duration: 66 min 36 sec


* Commit: 0ea4afe595d59d47767f68a80a7b0586b23e0ef7



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 220  |
| Skipped      | 0 |
| Total        | 220   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












## :robot: GitHub comments

To re-run your PR in the CI, just comment with:


- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2021-11-05 12:43 UTC, andrewkroh requested changes
We should not change this. This package is deprecated and I'd like to keep that information in the description until there is a better way of expressing that info in the package metadata. The message is based on feedback in https://github.com/elastic/integrations/issues/1900#issuecomment-945972295.

2021-11-08 05:55 UTC, akshay-saraswat commented
> We should not change this. This package is deprecated and I'd like to keep that information in the description until there is a better way of expressing that info in the package metadata. The message is based on feedback in [#1900 (comment)](https://github.com/elastic/integrations/issues/1900#issuecomment-945972295).

@endorama let's leave it as it is because it has been deprecated.

2021-11-08 13:10 UTC, endorama commented
Closing as per discussion.

2021-11-08 13:10 UTC, closed without merging