Adds ML supervised model Problem child package
elastic/integrations pull request #2115
Opened 2021-11-03 00:03 UTC by alvarezmelissa87

## What does this PR do?

Adds the ML supervised model package for Problem child model.

Package includes:
- pipelines
- ml_module
- ml_model

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] If I'm introducing a new feature, I have modified the Kibana version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^7.13.0`).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2021-11-03 00:13 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2115/detail/PR-2115/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2115/detail/PR-2115/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2115/detail/PR-2115/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2115/detail/PR-2115/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_2115.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2021-11-02T23:53:43.255Z&rangeTo=2021-11-03T00:13:43.255Z&transactionName=Ingest-manager/integrations/PR-{number}&transactionType=unknown&latencyAggregationType=avg&traceId=0c1cc1f84bd9d7d8a05a4c2922bba715&transactionId=331c3a499ece1be3)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2021-11-03T00:03:43.255+0000


* Duration: 9 min 4 sec


* Commit: 9bd74bc3a907566da1533ac56844135e8df2fc97




</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->











### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2115/detail/PR-2115/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Check integration: ml_problem_child`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-2115/runs/1/steps/521/log/?start=0">here</a></li>
<li>Description: <code>../../build/elastic-package check -v</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-2115/runs/1/steps/557/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>


## :robot: GitHub comments

To re-run your PR in the CI, just comment with:


- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2021-12-17 15:57 UTC, peteharverson commented
Is it possible to set a description field for the model, so that something like `The Problem child model is used to detect living off the land (LOtl) activity.` appears in the models list:

![image](https://user-images.githubusercontent.com/7405507/146572167-5c2e290d-c738-4b80-81a7-975113957fbd.png)

2021-12-17 16:24 UTC, peteharverson commented on packages/ml_problem_child/kibana/ml_module/problem-child-ml.json
> +        "title": "Problem child anomaly detection",
I don't think we need `anomaly detection` in here - can just be `Problem child`.

2021-12-17 16:24 UTC, peteharverson commented on packages/ml_problem_child/kibana/ml_module/problem-child-ml.json
> +        "description": "Identify malicious processes.",
I'd suggest adding `detect potential living off the land activity` in here, something like this:

![image](https://user-images.githubusercontent.com/7405507/146575512-2b7b9c99-61da-484d-83fe-051ead08e81b.png)

2021-12-17 16:24 UTC, peteharverson commented on packages/ml_problem_child/kibana/ml_module/problem-child-ml.json
> +            "description": "A machine learning job to detect potential living off the land activity. Looks for a process that has been classified as malicious on a host that does not commonly manifes
I don't think we need `A machine learning job to detect potential living off the land activity.` at the start of all these descriptions. `A machine learning job` can definitely be removed, and probably the whole of the first sentence is unnecessary.

2021-12-17 16:36 UTC, peteharverson commented on packages/ml_problem_child/kibana/ml_module/problem-child-ml.json
> +          "indices": [
The indices should not be hardcoded in the datafeed configs, or else it won't use the data view selected by the user in the ML job wizard. It should just be

```
  "indices": [
     "INDEX_PATTERN_NAME"
   ],
```

2021-12-17 17:03 UTC, peteharverson commented on packages/ml_problem_child/kibana/ml_module/problem-child-ml.json
> +          "config": {
We probably want to add a `groups` property in here to make it easier to identify / search for these jobs in the UI - would need to find out what groups we should be adding for these jobs. `security`, `process` `problemchild` ?

![image](https://user-images.githubusercontent.com/7405507/146580711-75f733e9-af64-4f82-a5a1-196ab0dbe3d8.png)

2021-12-20 21:37 UTC, alvarezmelissa87 commented on packages/ml_problem_child/kibana/ml_module/problem-child-ml.json
> +        "title": "Problem child anomaly detection",
Updated in 020da604273535260ba2dc54088c1bc9d63ad80f

2021-12-20 21:37 UTC, alvarezmelissa87 commented on packages/ml_problem_child/kibana/ml_module/problem-child-ml.json
> +        "description": "Identify malicious processes.",
Updated in 020da604273535260ba2dc54088c1bc9d63ad80f

2021-12-20 21:38 UTC, alvarezmelissa87 commented on packages/ml_problem_child/kibana/ml_module/problem-child-ml.json
> +            "description": "A machine learning job to detect potential living off the land activity. Looks for a process that has been classified as malicious on a host that does not commonly manifes
Updated in 020da604273535260ba2dc54088c1bc9d63ad80f

2021-12-20 21:38 UTC, alvarezmelissa87 commented on packages/ml_problem_child/kibana/ml_module/problem-child-ml.json
> +          "indices": [
Updated in 020da604273535260ba2dc54088c1bc9d63ad80f

2022-01-31 10:55 UTC, peteharverson commented on packages/ml_problem_child/changelog.yml
> +    - description: Initial draft of the package
I think the word `draft` can be lost here - other packages I've looked at go with something like `Initial release`

2022-01-31 10:55 UTC, peteharverson commented on packages/ml_problem_child/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/0 # FIXME Replace with the real PR link
You can put in the actual PR number now - `2115`

2022-01-31 11:50 UTC, peteharverson commented on packages/ml_problem_child/kibana/ml_module/problem-child-ml.json
> +        "type": "ML model",
The `type` field in the module is generally used to describe the type of data the jobs run against. So maybe something like `Process data`  would be a better description here? Or even `Problem child`? Note this field isn't currently used in the UI - it just acts as an extra label in the module definition.

2022-01-31 11:50 UTC, peteharverson commented on packages/ml_problem_child/kibana/ml_module/problem-child-ml.json
> +                    "description": "Looks for a process that has been classified as malicious on a host that does not commonly manifest malicious process activity. This is an experimental job and is
Just want to confirm that we should be describing these jobs as experimental.

2022-01-31 11:50 UTC, peteharverson commented on packages/ml_problem_child/kibana/ml_module/problem-child-ml.json
> +                    }
We should add `created_by` fields for all these jobs
```
  "custom_settings": {
    "created_by": "ml-module-problem-child"
  }
```

2022-01-31 11:50 UTC, peteharverson commented on packages/ml_problem_child/kibana/ml_module/problem-child-ml.json
> +                                "detector_description": "high sum by host",
Is there a reason why the two detectors in this job have been given the same description? Could it be given a more human readable description, such as `high number of malicious processes by host`?

2022-01-31 11:50 UTC, peteharverson commented on packages/ml_problem_child/kibana/ml_module/problem-child-ml.json
> +                                "detector_description": "high sum by host",
As above, could the description here be edited to indicate the field it is running on `blocklist_label`? I don't have enough context on what information is held in `blocklist_label` to advise here.

2022-01-31 11:50 UTC, peteharverson commented on packages/ml_problem_child/kibana/ml_module/problem-child-ml.json
> +                                "detector_description": "high sum by host",
Could we include the field name in the description of this detector - what is it a high sum of?

2022-01-31 11:50 UTC, peteharverson commented on packages/ml_problem_child/kibana/ml_module/problem-child-ml.json
> +                                "detector_description": "high sum by user",
Could we include the field name in the description of this detector - what is it a high sum of?

2022-01-31 11:50 UTC, peteharverson commented on packages/ml_problem_child/kibana/ml_module/problem-child-ml.json
> +                                "detector_description": "high sum by parent process",
Could we include the field name in the description of this detector - what is it a high sum of?

2022-01-31 11:50 UTC, peteharverson commented on packages/ml_problem_child/kibana/ml_module/problem-child-ml.json
> +                                "detector_description": "high sum by host",
Could we include the field name in the description of this detector - what is it a high sum of?

2022-01-31 11:59 UTC, peteharverson commented on packages/ml_problem_child/manifest.yml
> +description: "The Problem Child model is used to detect LOtL activity."
This package is more than just a 'model'. How about `The Problem Child framework is used to detect living of the land (LOtL) activity.`

2022-01-31 12:17 UTC, peteharverson commented on packages/ml_problem_child/manifest.yml
> +name: ml_problem_child
I'm not sure we need `ml` in the name, title and even the folder name (`ml_problem_child`) of the package, as the emphasis should be on the use case 'problem child'.

2022-01-31 21:15 UTC, ajosh0504 reviewed
Thanks for getting this done! Super excited to see these models in packages. Just one question. So once a user installs a package, what's the process for them to update/change artifacts produced by the package?

2022-01-31 21:15 UTC, ajosh0504 commented on packages/ml_problem_child/kibana/ml_module/problem-child-ml.json
> +                                "detector_description": "high sum by host",
I second this.

2022-01-31 21:15 UTC, ajosh0504 commented on packages/ml_problem_child/kibana/ml_module/problem-child-ml.json
> +                                "detector_description": "high sum by host",
@peteharverson So the way we classify processes as malicious is using either a supervised model or a blocklist for things the model may have missed. I think adding this in the description will introduce complexity.

2022-01-31 21:15 UTC, ajosh0504 commented on packages/ml_problem_child/kibana/ml_module/problem-child-ml.json
> +                                "detector_description": "high sum by user",
As above, I think introducing field names in the descriptions might introduce complexity, since users may not know what the fields exactly mean.

2022-01-31 21:28 UTC, ajosh0504 commented
As with the DGA model, should the model file name here be something more understandable? It's currently `problemchild_20210526_1.0.json`. This will also need to be changed in the inference pipeline.

2022-01-31 23:09 UTC, dishadasgupta commented on packages/ml_problem_child/changelog.yml
> +    - description: Initial draft of the package
Agreed, I think draft implies this isn't ready for users to use

2022-01-31 23:11 UTC, dishadasgupta commented on packages/ml_problem_child/elasticsearch/ingest_pipeline/ml_problem_child_ingest_pipeline.yml
> +description: "A pipeline of pipelines for ProblemChild detection"
Is there a way to make this description a bit clearer? I feel like "pipeline of pipelines" at first read could be a bit confusing

2022-01-31 23:13 UTC, dishadasgupta commented on packages/ml_problem_child/kibana/ml_module/problem-child-ml.json
> +                                "detector_description": "high sum by user",
I agree with Apoorva, field names aren't always the most user-centric and don't add that much value (imo) for the complexity they could add

2022-01-31 23:19 UTC, dishadasgupta commented on packages/ml_problem_child/docs/README.md
> +To download the assets, click **Settings** > **Install ML Problem child assets**.
I'm assuming this is within a cluster? Could we get an example of what that is supposed to look like? Are there any steps needed before this? i.e. ProblemChild requires Platinum level capabilities, is that denoted anywhere (unless I missed it)? Maybe even a quick note in the README would be helpful

2022-02-01 17:16 UTC, peteharverson commented on packages/ml_problem_child/kibana/ml_module/problem-child-ml.json
> +                                "detector_description": "high sum by host",
OK. Thanks for explanation @ajosh0504

2022-02-01 18:00 UTC, peteharverson commented on packages/ml_problem_child/kibana/ml_module/problem-child-ml.json
> +                    "description": "Looks for a process that has been classified as malicious on a host that does not commonly manifest malicious process activity. This is an experimental job and is
Confirmed that yes, we should mark these jobs as experimental for now. The package too has the experimental tag on it.

2022-02-01 23:17 UTC, alvarezmelissa87 commented on packages/ml_problem_child/docs/README.md
> +To download the assets, click **Settings** > **Install ML Problem child assets**.
The package manifest file has the license type that is required - that is enforced in Fleet. We could add a note in the README as well 👍

2022-02-02 00:11 UTC, alvarezmelissa87 commented on packages/ml_problem_child/changelog.yml
> +    - description: Initial draft of the package
Updated in 7d33b9d65996d461f7d20ece7d0f96a636698584

2022-02-02 00:11 UTC, alvarezmelissa87 commented on packages/ml_problem_child/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/0 # FIXME Replace with the real PR link
Updated in 7d33b9d65996d461f7d20ece7d0f96a636698584

2022-02-02 00:12 UTC, alvarezmelissa87 commented on packages/ml_problem_child/kibana/ml_module/problem-child-ml.json
> +        "type": "ML model",
Updated in 7d33b9d65996d461f7d20ece7d0f96a636698584

2022-02-02 00:12 UTC, alvarezmelissa87 commented on packages/ml_problem_child/kibana/ml_module/problem-child-ml.json
> +                    }
Added in 7d33b9d65996d461f7d20ece7d0f96a636698584

2022-02-02 00:12 UTC, alvarezmelissa87 commented on packages/ml_problem_child/kibana/ml_module/problem-child-ml.json
> +                                "detector_description": "high sum by host",
Updated in 7d33b9d65996d461f7d20ece7d0f96a636698584

2022-02-02 00:12 UTC, alvarezmelissa87 commented on packages/ml_problem_child/manifest.yml
> +description: "The Problem Child model is used to detect LOtL activity."
Updated in 7d33b9d65996d461f7d20ece7d0f96a636698584

2022-02-02 00:12 UTC, alvarezmelissa87 commented on packages/ml_problem_child/manifest.yml
> +name: ml_problem_child
Updated in 7d33b9d65996d461f7d20ece7d0f96a636698584

2022-02-02 00:13 UTC, alvarezmelissa87 commented on packages/ml_problem_child/docs/README.md
> +# ML Problem Child
Updated to use `ProblemChild` everywhere in 7d33b9d65996d461f7d20ece7d0f96a636698584

2022-02-02 00:13 UTC, alvarezmelissa87 commented on packages/ml_problem_child/docs/README.md
> +The Problem child model package contains the [Problem child model and associated assets](https://www.elastic.co/blog/problemchild-generate-alerts-to-detect-living-off-the-land-attacks), which are use
Updated in 7d33b9d65996d461f7d20ece7d0f96a636698584

2022-02-02 15:29 UTC, alvarezmelissa87 commented
cc @lcawl for package/model description text in the readme and such.

2022-02-02 22:33 UTC, brokensound77 reviewed
So cool to see this finally going into the product (after being in an experimental state for so long). I left a few suggestions.

@spong FYSA, if I am not mistaken, this and #2352 and the first integrations outside of the prebuilt rules to add rules destined for the detection engine. Not sure if there were any assumptions or considerations to be made.

2022-02-02 22:33 UTC, brokensound77 commented on packages/problem_child/kibana/security_rule/34184d4e-ef61-477b-8d76-5c93448c29bf.json
> +        "description": "A supervised machine learning model (ProblemChild) or its blocklist has identified\na suspicious Windows process event to be malicious activity.\n",
is the line break in the middle intentional?

2022-02-02 22:33 UTC, brokensound77 commented on packages/problem_child/kibana/security_rule/34184d4e-ef61-477b-8d76-5c93448c29bf.json
> +        "description": "A supervised machine learning model (ProblemChild) or its blocklist has identified\na suspicious Windows process event to be malicious activity.\n",
Shouldn't need a trailing one either

2022-02-02 22:33 UTC, brokensound77 commented on packages/problem_child/kibana/security_rule/9a2e372a-cbeb-4ad6-a288-017ef086324c.json
> +        "query": "(problemchild.prediction:1 and problemchild.prediction_probability \u003e 0.98) or blocklist_label:1",
was the `\u003e` a unicode conversion error?

2022-02-02 22:37 UTC, brokensound77 commented on packages/problem_child/docs/README.md
> +
is it worth elaborating on this to explain the relationship between the model, jobs, and rules. I believe the job and rules will be installed but in a disabled state. Also if the rule is enabled before the job, it will throw an error. 

The schema for rules accepts defining `enabled = true`, though I am not totally sure on the ml jobs

2022-02-03 17:52 UTC, alvarezmelissa87 commented on packages/problem_child/kibana/security_rule/34184d4e-ef61-477b-8d76-5c93448c29bf.json
> +        "description": "A supervised machine learning model (ProblemChild) or its blocklist has identified\na suspicious Windows process event to be malicious activity.\n",
These lines breaks were part of the release and haven't been changed. I'd need confirmation that it's okay to remove them.

2022-02-03 17:52 UTC, alvarezmelissa87 commented on packages/problem_child/kibana/security_rule/9a2e372a-cbeb-4ad6-a288-017ef086324c.json
> +        "query": "(problemchild.prediction:1 and problemchild.prediction_probability \u003e 0.98) or blocklist_label:1",
Yep - fixed! thanks!

2022-02-03 23:23 UTC, alvarezmelissa87 commented on packages/problem_child/manifest.yml
> +title: "ML ProblemChild"
Removed in 7d0d4520824c3e32aa600a4ecfa43d919e2217c2

2022-02-04 16:20 UTC, peteharverson commented on packages/ml_problem_child/elasticsearch/ingest_pipeline/ml_problem_child_ingest_pipeline.yml
> +description: "A pipeline of pipelines for ProblemChild detection"
How about just `Pipelines for ProblemChild detection`? Is this label actually shown anywhere in the UI?

2022-02-04 16:52 UTC, peteharverson approved these changes
Latest changes LGTM

2022-02-07 22:41 UTC, alvarezmelissa87 commented on packages/problem_child/docs/README.md
> +
How about adding something to the `Configuration` section of the readme - after the `to download the assets` bit 
Something like `Ingest data with the installed ingest pipeline to enrich your indices with inference data and run the provided anomaly detection jobs.` 
cc @peteharverson

2022-02-07 22:48 UTC, alvarezmelissa87 commented
This has been updated with all suggestions and is ready for another look when you get a chance 🙏 
cc @dishadasgupta, @ajosh0504, @brokensound77

2022-02-07 23:09 UTC, lcawl commented on packages/problem_child/docs/README.md
> +
The goal is to ultimately have a page in the docs that walks through the installation and use of this integration's assets, but since that's not available to link to yet, I agree with your suggestion for a couple of lines in the Configuration section of the readme as a stop-gap.

2022-02-09 23:18 UTC, alvarezmelissa87 commented on packages/problem_child/docs/README.md
> +
Added in 11eb4a152ddadf13c75d6e469e97f01d6db9dd06
cc @lcawl, @peteharverson

2022-02-09 23:27 UTC, spong commented on packages/problem_child/kibana/security_rule/34184d4e-ef61-477b-8d76-5c93448c29bf.json
> +        "description": "A supervised machine learning model (ProblemChild) or its blocklist has identified\na suspicious Windows process event to be malicious activity.\n",
FWIW there doesn't appear to be any issue with rendering (these newlines are ignored):

<p align="center">
  <img width="500" src="https://user-images.githubusercontent.com/2946766/153307527-04f086c7-2b80-4ffc-9a39-6a457d027e0e.png" />
</p>

2022-02-09 23:32 UTC, spong commented on packages/problem_child/kibana/security_rule/34184d4e-ef61-477b-8d76-5c93448c29bf.json
> +        "version": 2
Since these are brand new rules is there a reason its initial version is `2`? Is there any versioning handled elsewhere by chance (perhaps auto-generated like they do in the `detection-rules` repo)?

2022-02-10 16:33 UTC, alvarezmelissa87 commented on packages/problem_child/kibana/security_rule/34184d4e-ef61-477b-8d76-5c93448c29bf.json
> +        "version": 2
cc @Winterflower, @dishadasgupta Not sure who I'd need to check with for the answer to this

2022-02-11 22:50 UTC, brokensound77 commented on packages/problem_child/kibana/security_rule/34184d4e-ef61-477b-8d76-5c93448c29bf.json
> +        "version": 2
My guess is that they were versioned based on their existence in pre-releases within the detection-rules repo (which was considered experimental and not fully supported). Best course of action would probably be to regenerate a new random UUID for `rule_id` and then reset to version 1

2022-02-11 22:52 UTC, spong commented on packages/problem_child/kibana/security_rule/34184d4e-ef61-477b-8d76-5c93448c29bf.json
> +        "version": 2
Not a big deal either way, these rules can ship with their initial version as `2` and it's no issue. There aren't many guidelines around versioning other than it must be incremented (if there's a previous version) for the update logic to catch it.

2022-02-15 22:52 UTC, grabowskit commented
Could we change the title of the card be "Living off the Land Attack Detection" or if there are character limits "LotL Attack Detection"?  Then include in the card description... "The ProblemChild package is used to detect Living off the Land attacks. Platinum license required" (having LotL spelled out in the description).  Also, let me know if we run into a character limit. I would like to keep ProblemChild in the card description because the ML model is called ProblemChild and the inference pipeline has ProblemChild description in it.

This would also require a change to the title after clicking on the card, but the Overview description looks like it won't need any other changes.

cc: @hmnichols

2022-02-17 00:54 UTC, alvarezmelissa87 commented
> Could we change the title of the card be "Living off the Land Attack Detection" or if there are character limits "LotL Attack Detection"? Then include in the card description... "The ProblemChild package is used to detect Living off the Land attacks. Platinum license required" (having LotL spelled out in the description). Also, let me know if we run into a character limit. I would like to keep ProblemChild in the card description because the ML model is called ProblemChild and the inference pipeline has ProblemChild description in it.
> 
> This would also require a change to the title after clicking on the card, but the Overview description looks like it won't need any other changes.
> 
> cc: @hmnichols

Updated the title card and the overview f05aa70beca85fb47b1a90c245097e288175ed18
Also updated the screenshots in the description

2022-02-17 22:56 UTC, lcawl approved these changes
One suggestion, otherwise text LGTM

2022-03-02 20:41 UTC, ajosh0504 approved these changes
LGTM if all the outstanding feedback has been resolved. 👍

2022-03-02 20:44 UTC, bfilar approved these changes
LGTM -- If anyone needs help with documentation please feel free to reach out to me.

2022-03-02 20:49 UTC, dishadasgupta commented on packages/problem_child/_dev/build/docs/README.md
> +# ProblemChild Detection Model
IMO, I think it'd be best to leave it as ProblemChild Detection Model for consistency for the user since it's being referenced as ProblemChild + the README goes on to describe the purpose

2022-03-02 20:50 UTC, dishadasgupta approved these changes
LGTM once all outstanding comments are handled + checks pass. Likewise, I am around for any help with docs

2022-03-02 21:35 UTC, lcawl commented on packages/problem_child/_dev/build/docs/README.md
> +# ProblemChild Detection Model
Won't that cause confusion? The title in the UI will not match the title in the docs (https://docs.elastic.co/en/integrations)

2022-03-02 21:47 UTC, dishadasgupta commented on packages/problem_child/_dev/build/docs/README.md
> +# ProblemChild Detection Model
@lcawl This link doesn't point to anything specific regarding ProblemChild that I can see, what will it be listed as in the UI? If it's not ProblemChild, perhaps that should change, since we've been calling it ProblemChild everywhere. Let me know if I'm misunderstanding something, thanks

2022-03-02 21:52 UTC, lcawl commented on packages/problem_child/_dev/build/docs/README.md
> +# ProblemChild Detection Model
Right, that documentation can only be created after this integration is pushed to the package repository and it's generated from whatever we put in the readme here. IMO the readme title should therefore match the integration's UI title.

2022-03-04 00:41 UTC, lcawl commented on packages/problem_child/manifest.yml
> +  - custom
While testing just now I sought this package in the "security" category of integrations and didn't think to look in the "custom" category. If this is just a newbie mistake, feel free to ignore.

2022-03-04 11:59 UTC, peteharverson commented on packages/problem_child/manifest.yml
> +  - custom
I think we should make this `[custom, security]`. Or even just switch it to `security`?

2022-03-07 15:32 UTC, mtojek requested changes
Could you please update this PR with the latest main branch and add an appropriate entry to the CODEOWNERS file?

2022-03-15 05:33 UTC, alvarezmelissa87 commented on packages/problem_child/manifest.yml
> +  - custom
Updated in c3692a17d515ebdd31e95e03652f735d04db5748

2022-03-15 05:33 UTC, alvarezmelissa87 commented on packages/problem_child/_dev/build/docs/README.md
> +# ProblemChild Detection Model
Updated this to `LotL Attack Detection` in c3692a17d515ebdd31e95e03652f735d04db5748

2022-03-15 05:35 UTC, alvarezmelissa87 commented on packages/problem_child/docs/README.md
> +
@lcawl, @peteharverson, @Winterflower 
The latest screenshots and README file have been updated with more detailed instructions on how to use the package - as discussed - in c3692a17d515ebdd31e95e03652f735d04db5748
Would appreciate confirmation that it's what we want when you get a chance! 🙏

2022-03-15 05:36 UTC, alvarezmelissa87 commented on packages/problem_child/kibana/security_rule/9a2e372a-cbeb-4ad6-a288-017ef086324c.json
> +        "query": "(problemchild.prediction:1 and problemchild.prediction_probability \u003e 0.98) or blocklist_label:1",
Thanks for catching this - this should now be a `>` instead of the encoded version 👍 Fixed in c3692a17d515ebdd31e95e03652f735d04db5748

2022-03-16 00:52 UTC, lcawl commented on packages/problem_child/_dev/build/docs/README.md
> +Follow these instructions to ingest data with the ingest pipeline and enrich your indices with inference data. Then use these detection rules and anomaly detection jobs to detect LotL attacks. For mo
I think this space causes a problematic link:
```suggestion
Follow these instructions to ingest data with the ingest pipeline and enrich your indices with inference data. Then use these detection rules and anomaly detection jobs to detect LotL attacks. For more detailed information refer to the [ProblemChild blog](https://www.elastic.co/blog/problemchild-generate-alerts-to-detect-living-off-the-land-attacks)
```

2022-03-16 00:53 UTC, lcawl commented on packages/problem_child/_dev/build/docs/README.md
> +This pipeline is designed to work with [Winglogbeat data] (https://www.elastic.co/downloads/beats/winlogbeat).
Ditto re unnecessary space:
```suggestion
This pipeline is designed to work with [Winglogbeat data](https://www.elastic.co/downloads/beats/winlogbeat).
```

2022-03-16 00:56 UTC, lcawl commented on packages/problem_child/_dev/build/docs/README.md
> +In Machine Learning > Anomaly Detection, when you create a job, you should see an option to `Use preconfigured jobs` with a card for LotL Attacks. Select that option. Once you select the card you wil
Minor edits:
```suggestion
In **Machine Learning > Anomaly Detection**, when you create a job, you should see an option to `Use preconfigured jobs` with a card for LotL Attacks. When you select the card, you will see several pre-configured anomaly detection jobs that you can enable depending on what makes the most sense for your environment. Note these jobs are only useful for indices that have been enriched by the ingest pipeline.
```

2022-03-16 00:56 UTC, lcawl commented on packages/problem_child/_dev/build/docs/README.md
> +### (Optional) Enable Security Rules
```suggestion
### (Optional) Enable security rules
```

2022-03-16 00:58 UTC, lcawl commented on packages/problem_child/_dev/build/docs/README.md
> +In order to maximize the benefit of the LotL Detection framework, you might consider activating detection rules that are triggered when certain conditions for the supervised model or anomaly detectio
Ditto re unnecessary space and there's also a missing bracket:
```suggestion
In order to maximize the benefit of the LotL Detection framework, you might consider activating detection rules that are triggered when certain conditions for the supervised model or anomaly detection jobs are satisfied. See the [documentation](https://www.elastic.co/guide/en/security/current/detection-engine-overview.html) for more information on importing and enabling the rules.
```

2022-03-17 19:30 UTC, alvarezmelissa87 commented
This has been updated with the license/subscription language, the CODEOWNERS file has been updated, and the NOTICE.txt has been added. This is ready for a final look when you get a chance. cc @amandarichey, @mtojek, @spong

2022-03-18 04:07 UTC, spong approved these changes
LGTM from the Security Solution side. Thank you for all your efforts here and helping me get my test environment up and running @alvarezmelissa87! And congrats on the milestone here with the first ML integration! 🎉 🥳 🙌  

Only thing to note from the Security side is now that we have multiple integrations that are shipping assets of `"type": "security-rule"`, there could be the possibility of accidentally shipping rules that don't have a unique `rule_id` across all the other packages. This would manifest as an issue on the application side as the Security Solution app will only allow you to install rules with unique `rule_id`'s. I tested this locally by running this PR w/ package-registry and modifying one of the `rule_id`'s to be the same as one of the Detection Rule Integrations', and while both the integration asset SO's will be installed without issue, once you're in the Security UI it'll only install one of them (with no error or anything that there's a dupe, which is on our end, but is technically unsupported).

So that said, I think we need test case within the `integrations` repo here that checks any added assets of `"type": "security-rule"` and ensure's that there are no duplicates across all the other integrations. I'm not too familiar with integrations dev to know if this is possible, but would love to hear your thoughts if there may be another way of accomplishing this check. Since the rule asset `rule_id's` added in this PR are unique there's no need to hold up this PR, so we could just write an issue and handle this later (something my team @elastic/security-detections-response-rules can probably help with).

2022-03-18 08:28 UTC, mtojek requested changes
I've added the `elastic/ml-ui` team "write" permissions to this repository.

2022-03-18 08:28 UTC, mtojek commented on packages/problem_child/manifest.yml
> +  github: elastic/integrations
Please change it to `elastic/ml-ui` as in the CODEOWNERS file.

2022-03-18 08:28 UTC, mtojek commented on .github/CODEOWNERS
> +/packages/problem_child @elastic/ml-ui
Please merge the latest main branch so that the CODEOWNERS file is fixed.

2022-03-18 09:38 UTC, jsoriano commented
> I think we need test case within the `integrations` repo here that checks any added assets of `"type": "security-rule"` and ensure's that there are no duplicates across all the other integrations. I'm not too familiar with integrations dev to know if this is possible, but would love to hear your thoughts if there may be another way of accomplishing this check.

Take into account that not all packages are hosted in the `integrations` repo, there are packages whose source is in other repositories, and this is something we want to support. So we cannot trust only on checks on this repository.

There are other cases of assets that must have unique ids. For example for dashboards it is required that they are prefixed with the name of the package. Would this be an option here?

Other option could be that fleet guarantees that ids are unique on install time, I remember discussing this option for some asset in the past but I am not sure if this was implemented for some asset. The problem with this approach is that it can complicate maintaining references to these assets.

2022-03-18 15:53 UTC, alvarezmelissa87 commented on packages/problem_child/manifest.yml
> +  github: elastic/integrations
Updated in f89096226aa2afbf8622cd7480b5712cd7cea54e

2022-03-18 17:44 UTC, alvarezmelissa87 commented on packages/problem_child/kibana/security_rule/9a2e372a-cbeb-4ad6-a288-017ef086324c.json
> +        "query": "(problemchild.prediction:1 and problemchild.prediction_probability \u003e 0.98) or blocklist_label:1",
@spong - looks like running the `elastic-package format` command is what's causing the change from `>` to the encoded version. Is this expected?
cc @mtojek

2022-03-18 18:50 UTC, brokensound77 commented on packages/problem_child/kibana/security_rule/9a2e372a-cbeb-4ad6-a288-017ef086324c.json
> +        "query": "(problemchild.prediction:1 and problemchild.prediction_probability \u003e 0.98) or blocklist_label:1",
Oh wow, looks like you are right https://github.com/elastic/integrations/blob/1d18f55bd4e33f6d4b2c93bd2ad45e82bb1d4fd0/packages/security_detection_engine/kibana/security_rule/a9b05c3b-b304-4bf9-970d-acdfaef2944c.json#L16

I guess it is ok to leave it converted then 🤷

2022-03-20 21:44 UTC, spong commented
> Take into account that not all packages are hosted in the integrations repo, there are packages whose source is in other repositories, and this is something we want to support. So we cannot trust only on checks on this repository.

Thank you for clarifying @jsoriano! I wasn't aware, but kinda figured this might be the case (or at least that there'd be some support for arbitrary integrations hosted elsewhere).

> There are other cases of assets that must have unique ids. For example for dashboards it is required that they are prefixed with the name of the package. Would this be an option here?

Potentially, this `rule_id` essentially behaves as an external static id so that as these assets traverse different systems or continue to be reinstantiated we can still maintain a way of identifying them, so tagging them with their source integration shouldn't be disruptive here. That said we do have to take into consideration that we're already shipping `security-rule` assets in the `detection rules` integration, and those also separately ship pre-bundled with Kibana as well -- so would need to coordinate changes there too.

> Other option could be that fleet guarantees that ids are unique on install time, I remember discussing this option in the past but I am not sure if this was implemented for some asset. The problem with this approach is that it can complicate maintaining references to these assets.

I don't think this would be an option since as mentioned above we'll want this ID to remain static between installs/import/export/etc.

Let me discus the first option with our team and see if that'll work, or if folks have any other ideas here. Thanks again for the details here! 🙂

2022-03-21 08:41 UTC, mtojek commented on packages/problem_child/kibana/security_rule/9a2e372a-cbeb-4ad6-a288-017ef086324c.json
> +        "query": "(problemchild.prediction:1 and problemchild.prediction_probability \u003e 0.98) or blocklist_label:1",
What we can see in the CI output is:

```
[2022-03-18T15:59:14.998Z] Error: checking package failed: formatting the integration failed (path: /var/lib/jenkins/workspace/est-manager_integrations_PR-2115/src/github.com/elastic/integrations/packages/problem_child, failFast: true): walking through the integration files failed: formatting file failed (path: /var/lib/jenkins/workspace/est-manager_integrations_PR-2115/src/github.com/elastic/integrations/packages/problem_child/kibana/security_rule/9a2e372a-cbeb-4ad6-a288-017ef086324c.json): file is not formatted (path: /var/lib/jenkins/workspace/est-manager_integrations_PR-2115/src/github.com/elastic/integrations/packages/problem_child/kibana/security_rule/9a2e372a-cbeb-4ad6-a288-017ef086324c.json)
```

so it confirms that you have to post the formatted code. Sometimes the formatted code might be harder to read, but we don't have a choice here if we want to depend on standard JSON libraries. Please run `elastic-package format` and post the formatted content.

2022-03-21 08:45 UTC, mtojek commented on packages/problem_child/kibana/security_rule/9a2e372a-cbeb-4ad6-a288-017ef086324c.json
> +        "query": "(problemchild.prediction:1 and problemchild.prediction_probability \u003e 0.98) or blocklist_label:1",
> cc @mtojek - also - running elastic-package check locally is failing with a reference to the ml_model file name - though the update was made to package-spec to match that file name pattern and I've tested with the package-spec validator test so curious if this could be something going on locally? Might need to chat with you quickly on that one.

It depends on which elastic-package [release](https://github.com/elastic/elastic-package/releases) you have locally and which one is in the `go.mod` in the Integrations.

BTW we're struggling a bit with updating the dependency - [here](https://github.com/elastic/integrations/pull/2845).

2022-03-21 15:23 UTC, spong commented
@jsoriano @alvarezmelissa87 

I discussed with the team this morning and the recommended output was to create a discussion issue with all our options and how it affects the UX and then discuss with Product this Thursday and let them decide -- so I'll be creating that issue later today and will share here in case there's any additional input.

I don't want to block this PR on these changes, but if they decide to prefix the rule_id's with the package name we'll have to ensure that these ID's are updated before this package is published. In talking with @alvarezmelissa87 I think we're fine to merge this when ready, but if we can wait till we hear back from Product on Thursday before publishing that would be great. 👍

2022-03-22 22:18 UTC, mtojek commented on packages/problemchild/kibana/ml_module/problemchild-ml.json
> +    "id": "problem_child",
@alvarezmelissa87 What about this "id"? CI mentioned that field.

2022-03-24 15:18 UTC, alvarezmelissa87 commented on packages/problemchild/kibana/ml_module/problemchild-ml.json
> +    "id": "problem_child",
Ah, thank you! I thought I changed it - updating 👍

2022-03-24 16:12 UTC, alvarezmelissa87 commented on packages/problemchild/kibana/ml_module/problemchild-ml.json
> +    "id": "problem_child",
Ah, thanks - missed this the first time! Updated in 38fd11b82218701d16107b60c6e418b8f7c9ff2f

2022-03-24 22:54 UTC, spong commented
Just commenting to update that we've come to consensus on how we'll handle the aforementioned issue around `rule_id` uniqueness between packages, and that there is no reason to hold up the merging or publishing of this package from the Security Solution side. Please see this comment https://github.com/elastic/kibana/issues/128202#issuecomment-1078457192 for all the details, and thank you all for all your input here! 🙂

2022-03-28 14:39 UTC, mtojek approved these changes

2022-03-29 00:28 UTC, merged