Osquery_manager: Update to GA. Reduce the number of explicitly mapped text/keyword osquery fields.
elastic/integrations pull request #2123
Opened 2021-11-03 20:32 UTC by aleksmaus

## What does this PR do?

* Update manifest release tag from beta to ga
* Add host_users, host_groups, host_processes tables columns into package readme
* Remove previously explicitly mapped text/keywords fields. This relies on the dynamic keyword[1024] mapping
```
      "dynamic_templates": [
        {
          "strings_as_keyword": {
            "match_mapping_type": "string",
            "mapping": {
              "ignore_above": 1024,
              "type": "keyword"
            }
          }
        }
      ]
```
and helps to:
** Reduce the size of the mapping
** Eliminate the kibana warning 
```
kibana         | [2021-11-03T19:02:37.819+00:00][WARN ][plugins.fleet] large amount of default fields detected for index template logs-osquery_manager.result in package osquery_manager, applying the first 1024 fields
```

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] If I'm introducing a new feature, I have modified the Kibana version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^7.13.0`).

## Screenshots
<img width="544" alt="Screen Shot 2021-11-03 at 4 19 21 PM" src="https://user-images.githubusercontent.com/872351/140188110-43507162-513f-407a-b010-cd9753efdf25.png">

2021-11-03 20:37 UTC, melissaburpo approved these changes
looks good!

2021-11-03 20:45 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2123/detail/PR-2123/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2123/detail/PR-2123/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2123/detail/PR-2123/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2123/detail/PR-2123/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_2123.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2021-11-03T20:22:50.393Z&rangeTo=2021-11-03T20:42:50.393Z&transactionName=Ingest-manager/integrations/PR-{number}&transactionType=unknown&latencyAggregationType=avg&traceId=abcb11cc45ee2a709a530da34bddc5e0&transactionId=eef74f6febcc79ee)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2021-11-03T20:32:50.393+0000


* Duration: 13 min 53 sec


* Commit: bcf86162229cef5069d325e42ba4d7a2f7704e95



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 1  |
| Skipped      | 0 |
| Total        | 1   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












## :robot: GitHub comments

To re-run your PR in the CI, just comment with:


- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2021-11-04 20:15 UTC, james-elastic requested changes

2021-11-04 20:15 UTC, james-elastic commented on packages/osquery_manager/manifest.yml
> +release: ga
🥇

2021-11-04 20:15 UTC, james-elastic approved these changes

2021-11-04 20:48 UTC, aleksmaus commented
After conversation with @patrykkopycinski added more mappings for ECS long, boolean, float fields
<img width="499" alt="Screen Shot 2021-11-04 at 4 40 58 PM" src="https://user-images.githubusercontent.com/872351/140417547-b77abcbe-c1f2-48e9-b8c9-5d8aa5868a24.png">

2021-11-05 00:24 UTC, merged