Mimecast_Elastic integration
elastic/integrations pull request #2157
Opened 2021-11-15 08:21 UTC by djordje-adzemovic-devtech

## What does this PR do?

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] If I'm introducing a new feature, I have modified the Kibana version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^7.13.0`).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2021-11-15 08:25 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2157/detail/PR-2157/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2157/detail/PR-2157/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2157/detail/PR-2157/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2157/detail/PR-2157/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2021-11-15T08:12:00.508Z&rangeTo=2021-11-15T08:32:00.508Z&transactionName=Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=unknown&latencyAggregationType=avg&traceId=202aa149767448ad7332b6832b26d6e0&transactionId=3ae787032372378b)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats



* Reason: `The PR is not allowed to run in the CI yet`


* Start Time: 2021-11-15T08:22:00.508+0000


* Duration: 3 min 14 sec


* Commit: bdb535c27268d469ff283806e2c7e20fc3b8ae52




</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->











### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2157/detail/PR-2157/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-2157/runs/1/steps/109/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>


## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2021-11-15 09:55 UTC, djordje-adzemovic-devtech commented
/test

2021-11-15 10:12 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2021-11-15 10:13 UTC, marc-gr commented
/test

2021-11-15 10:35 UTC, marc-gr requested changes
Left some comments. In addition could be interesting to add some system tests (you can take a look at the tests in the google_workspace integration for reference), this way we can ensure the httpjson config is set as expected on top of validating the pipelines.

2021-11-15 10:35 UTC, marc-gr commented on packages/mimecast/data_stream/audit_events/elasticsearch/ingest_pipeline/default.yml
> +#   - join:
I think this comment slipped in.

2021-11-15 10:35 UTC, marc-gr commented on packages/mimecast/data_stream/audit_events/elasticsearch/ingest_pipeline/default.yml
> +        - mimecast.eventTime
not sure if this is the case here, but if you are listing all remaining fields in `mimecast.*` you could shorten this by doing 

```
field:
  - mimecast
```

2021-11-15 10:35 UTC, marc-gr commented on packages/mimecast/docs/README.md
> +This is a new integration created using the [elastic-package](https://github.com/elastic/elastic-package) tool.
Would be nice to add some information about the integration in the readme, anything relevant to its setup, prerequisites, ... along with the list of fields and a sample event. You can take a look at the README template found in `_dev/build/docs/README.md` and use the one in some other packages as a guide.

2021-11-15 10:35 UTC, marc-gr commented on packages/mimecast/data_stream/ttp_ap_logs/_dev/test/pipeline/test-ttp-ap-logs.log-expected.json
> +                    "hash": "2fb26be55ac710e4d9f80677ba24ae212dbb36bd934a0569fe521839e9f5d16e",
Hashes, user info, ips, etc.. would be nice if you could add a processor to copy them into the `related.*` fields, it is very useful for cross referencing and making searches easier. https://www.elastic.co/guide/en/ecs/current/ecs-related.html

2021-11-15 10:35 UTC, marc-gr commented on packages/mimecast/data_stream/ttp_ap_logs/_dev/test/pipeline/test-ttp-ap-logs.log-expected.json
> +                "action": "user release, none",
I am not 100% sure spaces and commas are desired in the `event.action` field, maybe processing it a bit to clean it up would be nice

2021-11-18 22:08 UTC, ebeahan commented
@djordje-adzemovic-devtech the Mimecast integration is looking awesome!

@jamiehynds had mentioned you've adopted some fields proposed over in the ECS [email RFC](https://github.com/elastic/ecs/pull/1593).

Not sure if it impacts any work here, but I wanted to call out that I've changed the proposed mappings a bit based on feedback from several users. A summary of the changes is covered in https://github.com/elastic/ecs/pull/1593#issuecomment-973307098

2021-11-19 13:11 UTC, djordje-adzemovic-devtech commented
Thank you @ebeahan ! Should not be such a big deal, and will be implemented.

2021-11-22 14:27 UTC, djordje-adzemovic-devtech commented on packages/mimecast/data_stream/audit_events/elasticsearch/ingest_pipeline/default.yml
> +        - mimecast.eventTime
There is a few fields they are under mimecast.* and needs to be there, so I cannot delete all in mimecast.*

2021-11-23 09:26 UTC, marc-gr commented
/test

2021-11-23 14:56 UTC, marc-gr commented
/test

2021-11-24 08:28 UTC, marc-gr commented
/test

2021-11-24 08:49 UTC, marc-gr commented
/test

2021-11-24 08:53 UTC, marc-gr commented
/test

2021-11-24 15:22 UTC, marc-gr commented
/test

2021-11-24 15:29 UTC, marc-gr commented
/test

2021-11-24 16:23 UTC, marc-gr commented
/test

2021-11-25 09:19 UTC, marc-gr commented
/test

2021-11-25 09:50 UTC, marc-gr commented
Great work! Could you add a screenshot of the dashboards and the setup page? Would help a lot :)

2021-11-25 10:17 UTC, marc-gr requested changes
Some small changes aside from the screenshots and I think it should be good to go

2021-11-25 10:17 UTC, marc-gr commented on packages/mimecast/data_stream/audit_events/elasticsearch/ingest_pipeline/default.yml
> +      if: 'ctx?.mimecast?.date != null && ctx?.mimecast?.time != null'
```suggestion
  - join: 
      field: event.created
      separator: " "
      if: 'ctx?.mimecast?.date != null && ctx?.mimecast?.time != null'
```

2021-11-25 10:20 UTC, marc-gr commented on packages/mimecast/data_stream/siem_logs/elasticsearch/ingest_pipeline/default.yml
> +      target_field: cloud.account.id
This field might be populated in some cases, would be necessary to re-map to a custom field to avoid issues (it is failing right now in CI, for example `one or more errors found in documents stored in logs-mimecast.siem_logs-ep data stream: [0] found error.message in event: field [cloud.account.id] already exists`

2021-11-25 11:41 UTC, djordje-adzemovic-devtech commented
Here are dashboards:
![Screenshot_4](https://user-images.githubusercontent.com/73986407/143435185-374885f9-af72-4487-9cea-24b0a431d86e.png)
![Screenshot_5](https://user-images.githubusercontent.com/73986407/143435189-4f9923f9-9476-4a2b-8f9a-06e932926dc1.png)
![Screenshot_6](https://user-images.githubusercontent.com/73986407/143435191-e74a119b-154b-4088-8410-9c0ca7c69fe3.png)
![Screenshot_7](https://user-images.githubusercontent.com/73986407/143435192-ed3f18a4-d5bf-4f5d-b661-e35ff82333d8.png)
![Screenshot_8](https://user-images.githubusercontent.com/73986407/143435196-3755238b-8a16-4ddc-828b-a0671c6beb96.png)
![Screenshot_9](https://user-images.githubusercontent.com/73986407/143435198-bb241cec-6fc0-4b6c-9487-c4fe071748e8.png)
![Screenshot_10](https://user-images.githubusercontent.com/73986407/143435201-03ed87a1-2b7c-443b-92c2-033e76beac9f.png)
![Screenshot_11](https://user-images.githubusercontent.com/73986407/143435202-ece14d40-35e0-4505-9d3a-98e9b1a2dc1b.png)
![Screenshot_12](https://user-images.githubusercontent.com/73986407/143435203-8d8a6ac5-9412-44ac-b864-8d6631ae413d.png)
![Screenshot_13](https://user-images.githubusercontent.com/73986407/143435207-35638a7c-17f6-41ef-9e75-ea1ca9a5ea6d.png)
![Screenshot_14](https://user-images.githubusercontent.com/73986407/143435208-00d53580-435d-4a23-be34-32ad78c2d19c.png)
![Screenshot_15](https://user-images.githubusercontent.com/73986407/143435211-1a013c94-6e41-4210-92b5-a20b31bc36a8.png)
![Screenshot_16](https://user-images.githubusercontent.com/73986407/143435215-87784405-6167-46c6-83d1-848293071ff3.png)
![Screenshot_17](https://user-images.githubusercontent.com/73986407/143435218-38563942-8f48-4e7b-bcb1-eafd0d56f179.png)
![Screenshot_18](https://user-images.githubusercontent.com/73986407/143435219-c7f1afb0-bdaf-4c2f-8e5d-376485d7bd6a.png)
![Screenshot_19](https://user-images.githubusercontent.com/73986407/143435221-712470df-229a-44a9-910c-6b84665f95e0.png)
![Screenshot_20](https://user-images.githubusercontent.com/73986407/143435223-bc3999aa-6caa-477d-8b85-ec442eb45731.png)
![Screenshot_21](https://user-images.githubusercontent.com/73986407/143435224-bd2268c2-4544-4a25-a520-688128991b03.png)
![Screenshot_22](https://user-images.githubusercontent.com/73986407/143435228-a50bb89e-f0ba-4852-9433-7696feaa6444.png)
![Screenshot_23](https://user-images.githubusercontent.com/73986407/143435230-9995c8a0-0e25-4555-b099-2333d627928d.png)
![Screenshot_24](https://user-images.githubusercontent.com/73986407/143435232-2673a789-56b6-4d83-9a3b-6ac9d13a4552.png)
![Screenshot_25](https://user-images.githubusercontent.com/73986407/143435237-5155196a-1f03-419a-8ce8-cefcb9e54c58.png)
![Screenshot_26](https://user-images.githubusercontent.com/73986407/143435240-8626eff2-4acc-4a50-86cf-e236129e2d7c.png)
![Screenshot_27](https://user-images.githubusercontent.com/73986407/143435242-49fb59e7-09a7-4896-aaf4-a171123bbc5d.png)
![Screenshot_28](https://user-images.githubusercontent.com/73986407/143435243-7b2b0c41-b38f-4619-8d58-4af90ec6ed1c.png)
![Screenshot_29](https://user-images.githubusercontent.com/73986407/143435245-4d5c6dca-244c-466f-b73f-0ba9281e4073.png)
![Screenshot_30](https://user-images.githubusercontent.com/73986407/143435248-608d40c9-74fb-4d60-a8b0-329273669164.png)
![Screenshot_31](https://user-images.githubusercontent.com/73986407/143435250-69830446-9f90-4cf9-9d46-718a4e6f14fe.png)
![Screenshot_32](https://user-images.githubusercontent.com/73986407/143435252-acf20a64-dd1b-4a0c-b4aa-0321f0634dbc.png)
![Screenshot_3](https://user-images.githubusercontent.com/73986407/143435326-1c2c2a31-b040-4c54-987f-19ca498c8b61.png)

2021-11-25 12:10 UTC, djordje-adzemovic-devtech commented
Setup page screenshots:
![Screenshot_1](https://user-images.githubusercontent.com/73986407/143439429-5d3d1d90-a2ef-4b4f-a0de-6581e8ba2048.png)
![Screenshot_2](https://user-images.githubusercontent.com/73986407/143439435-e2bc6810-0b80-4920-8108-9a97b01af2d7.png)
![Screenshot_3](https://user-images.githubusercontent.com/73986407/143439437-98bb82ba-ed6b-41bf-b724-dec164e6a294.png)
![Screenshot_4](https://user-images.githubusercontent.com/73986407/143439440-0d32a647-b41d-422b-9c93-53c64ad36e6e.png)
![Screenshot_5](https://user-images.githubusercontent.com/73986407/143439441-f24407c8-a366-4ff3-bf0b-e56432076be4.png)
![Screenshot_6](https://user-images.githubusercontent.com/73986407/143439444-4af0beaa-1c90-4ca7-a847-649238ea7de1.png)
![Screenshot_7](https://user-images.githubusercontent.com/73986407/143439445-47e9af4d-6144-4f03-b9f5-cbd00ec628a3.png)
![Screenshot_8](https://user-images.githubusercontent.com/73986407/143439448-b12a2f3a-fd68-4950-882f-2ef7b9abf794.png)
![Screenshot_34](https://user-images.githubusercontent.com/73986407/143439450-85966130-5281-454b-9a50-49a63f302d81.png)

2021-11-26 10:26 UTC, marc-gr commented
/test

2021-11-26 10:27 UTC, marc-gr commented
/test

2021-11-26 11:11 UTC, marc-gr commented
/test

2021-11-26 11:38 UTC, marc-gr approved these changes

2021-11-26 11:38 UTC, merged