[Sophos] Update Sophos pipelines for new fields
elastic/integrations pull request #2163
Opened 2021-11-16 04:14 UTC by legoguy1000

## What does this PR do?

Updates Sophos pipelines to support new fields.

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [X] I have added an entry to my package's `changelog.yml` file.
- [X] If I'm introducing a new feature, I have modified the Kibana version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^7.13.0`).

## Author's Checklist

- [ ]

## How to test this PR locally
```
cd integrations/packages/sophos
elastic-package build && elastic-package stack down && elastic-package stack up --version 7.16.0-SNAPSHOT -d -v && eval "$(elastic-package stack shellinit)" && elastic-package test -v
```

## Related issues

- Closes #2158 

## Screenshots

2021-11-16 04:17 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2163/detail/PR-2163/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2163/detail/PR-2163/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2163/detail/PR-2163/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2163/detail/PR-2163/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://null_2163.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2021-11-16T04:04:18.519Z&rangeTo=2021-11-16T04:24:18.519Z&transactionName=Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=unknown&latencyAggregationType=avg&traceId=12c0a1c565893b2df14ab190d29e96da&transactionId=228b7aeb80e5d92b)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2021-11-16T04:14:18.519+0000


* Duration: 3 min 36 sec


* Commit: b5aa4a8da61bf7cb523aaf6ec045b300b205e0c3




</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->











### Steps errors [![3](https://img.shields.io/badge/3%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2163/detail/PR-2163/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Check out from version control`
<ul>
<li>Took 0 min 14 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-2163/runs/1/steps/11/log/?start=0">here</a></li>
<li>Description: <code>[2021-11-16T04:15:38.393Z] The recommended git tool is: git
[2021-11-16T04:15:45.610Z] using creden</code></l1>
</ul>
  
  
  
  
##### `Check out from version control`
<ul>
<li>Took 0 min 6 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-2163/runs/1/steps/15/log/?start=0">here</a></li>
<li>Description: <code>[2021-11-16T04:16:12.167Z] The recommended git tool is: git
[2021-11-16T04:16:12.179Z] using creden</code></l1>
</ul>
  
  
  
  
##### `Check out from version control`
<ul>
<li>Took 0 min 6 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-2163/runs/1/steps/19/log/?start=0">here</a></li>
<li>Description: <code>[2021-11-16T04:16:47.849Z] The recommended git tool is: git
[2021-11-16T04:16:47.861Z] using creden</code></l1>
</ul>
  
  </p>
  </details>


## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2021-11-17 17:53 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2021-11-17 17:53 UTC, P1llus commented
/test

2021-11-22 20:42 UTC, leehinman requested changes

2021-11-22 20:42 UTC, leehinman commented on packages/sophos/data_stream/xg/elasticsearch/ingest_pipeline/default.yml
> -    field: sophos.xg.srczonetype
so this switches from `srczonetype` to `srczone` for the mapping to `observer.ingress.zone`.  I'm wondering if that will cause problems for users that already expect this to be what was in `srczonetype`.  What do you think about adding a custom field for `srczone` so that both are captured?  It looks like some older logs only had `srczonetype`.

This would apply to dstzone and all of Sophos spellings of zones too :-)

2021-11-23 00:00 UTC, legoguy1000 commented on packages/sophos/data_stream/xg/elasticsearch/ingest_pipeline/default.yml
> -    field: sophos.xg.srczonetype
So if the older logs only had the `zonetype` i guess that makes sense.  All the sample logs I saw seemed to have both and they were always the same.  I can just change it back, no worries.

2021-11-29 00:55 UTC, legoguy1000 commented on packages/sophos/data_stream/xg/elasticsearch/ingest_pipeline/default.yml
> -    field: sophos.xg.srczonetype
looking at the docs https://docs.sophos.com/nsg/sophos-firewall/17.5/Help/en-us/webhelp/onlinehelp/nsg/sfos/concepts/LogFields.html, I think the srczone would technically be the correct field to use for the `observer.ingress.zone` as its the actual name not the "type". I'll leave it to you on if we should change it or not.

<html>
<body>
<!--StartFragment-->

src_zone | String | Name of source zone
-- | -- | --
src_zone_type | String | Type of source zone

<!--EndFragment-->
</body>
</html>

2022-03-29 14:43 UTC, jamiehynds commented
Hey @legoguy1000 - can you advise on the current state of this PR? Do you need anything from us to move towards merging?

2022-03-29 14:50 UTC, legoguy1000 commented
> Hey @legoguy1000 - can you advise on the current state of this PR? Do you need anything from us to move towards merging?

I think the big thing was the question/conversation above regarding a couple of fields.

2022-03-29 15:08 UTC, legoguy1000 commented
Also i know this was also brought up in the Beats repo so we can also wait for that to be updated and then just copy the changes?? the parallel effort was also wonky as wanted to keep the changes consistent.

2022-03-29 15:11 UTC, andrewkroh commented
I was just commenting about have parallel changes in https://github.com/elastic/beats/issues/29002#issuecomment-1081993289.

2022-03-29 15:19 UTC, legoguy1000 commented
Ok, I will rebase and get this updated.

2022-03-31 13:33 UTC, legoguy1000 commented on packages/sophos/data_stream/xg/elasticsearch/ingest_pipeline/default.yml
> -    field: sophos.xg.srczonetype
@andrewkroh @leehinman Thoughts on this??

2022-04-06 18:29 UTC, andrewkroh commented
/test

2022-04-12 17:39 UTC, andrewkroh commented on packages/sophos/data_stream/xg/elasticsearch/ingest_pipeline/default.yml
> +    - sophos.xg.srczonetype
It looks like src_zone_type and dst_zone_type are not incorporated into the event anywhere. Should that field now be kept (and normalized to snake case) to avoid losing that data?

2022-04-12 17:40 UTC, andrewkroh commented on packages/sophos/data_stream/xg/elasticsearch/ingest_pipeline/default.yml
> -    field: sophos.xg.srczonetype
It seems like using src_zone / dst_zone aligns best with ECS.

2022-04-13 00:15 UTC, legoguy1000 commented on packages/sophos/data_stream/xg/elasticsearch/ingest_pipeline/default.yml
> +    - sophos.xg.srczonetype
I can do that

2022-04-13 00:31 UTC, legoguy1000 commented
@andrewkroh pushed changes

2022-04-13 03:01 UTC, andrewkroh commented
/test

2022-04-18 19:13 UTC, andrewkroh approved these changes

2022-04-18 19:13 UTC, andrewkroh commented on packages/sophos/data_stream/xg/elasticsearch/ingest_pipeline/firewall.yml
>  - set:
Instead of copying each of `destination.*` fields into `server.*`, I think it would be simpler to copy the whole `destination` object as `server` (like a `set: {copy_from: destination, field: server, ...}`. The same for `source` and `client`. WDYT?

2022-04-18 19:52 UTC, legoguy1000 commented on packages/sophos/data_stream/xg/elasticsearch/ingest_pipeline/firewall.yml
>  - set:
completely agree

2022-04-18 20:01 UTC, legoguy1000 commented on packages/sophos/data_stream/xg/elasticsearch/ingest_pipeline/firewall.yml
>  - set:
Other question I would ask is do we even need the client/server fields? If we're arbitrarily copying them from source/dest, does it really help?

2022-04-18 20:07 UTC, andrewkroh commented on packages/sophos/data_stream/xg/elasticsearch/ingest_pipeline/firewall.yml
>  - set:
I would say no for new work. I haven't found client/server useful when you have source/destination. Assuming this was already setting client/server I wouldn't want to revert that (it would be a breaking change).

2022-04-18 20:09 UTC, legoguy1000 commented on packages/sophos/data_stream/xg/elasticsearch/ingest_pipeline/firewall.yml
>  - set:
rog, i'll update accordingly to replace all the individual field copying between source/client and dest/server with the parent field copies and call it a day

2022-04-18 20:12 UTC, andrewkroh commented on packages/sophos/data_stream/xg/elasticsearch/ingest_pipeline/firewall.yml
>  - set:
I'll merge this as is since it looks good, and then if there's some cleanup you want to do that can be separate.

2022-04-18 20:15 UTC, andrewkroh commented
/test

2022-04-18 20:30 UTC, legoguy1000 commented
some weird glitch with the pipeline.  I tried to rebuild README and there are no changes so idk.

2022-04-18 22:17 UTC, andrewkroh commented
> some weird glitch with the pipeline. I tried to rebuild README and there are no changes so idk.

You might have an old version of elastic-package. Try running `go install github.com/elastic/elastic-package` from the main branch of `elastic/integrations` to install the version specified in the go.mod file.

2022-04-18 22:36 UTC, merged