[GCP] Add GCP Compute Metricset
elastic/integrations pull request #2301
Opened 2021-12-02 04:20 UTC by legoguy1000

## What does this PR do?

Adds GCP Compute Metricset

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [X] If I'm introducing a new feature, I have modified the Kibana version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^7.13.0`).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2021-12-02 04:24 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2301/detail/PR-2301/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2301/detail/PR-2301/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2301/detail/PR-2301/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2301/detail/PR-2301/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2021-12-02T04:10:46.364Z&rangeTo=2021-12-02T04:30:46.364Z&transactionName=Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=unknown&latencyAggregationType=avg&traceId=ad5facfb9bab4f29bb731cb98b29e0c3&transactionId=7cf45ac643982e38)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats



* Reason: `The PR is not allowed to run in the CI yet`


* Start Time: 2021-12-02T04:20:46.364+0000


* Duration: 4 min 0 sec


* Commit: 44378a0eac4b7da2e7dec21403a56b6eec1950e7




</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->











### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2301/detail/PR-2301/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-2301/runs/1/steps/109/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>


## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2021-12-02 04:29 UTC, legoguy1000 commented
@endorama next one ready for your review

2021-12-13 18:38 UTC, legoguy1000 commented
@endorama Any thoughts on this one?

2021-12-14 19:04 UTC, elasticmachine commented
Pinging @elastic/integrations (Team:Integrations)

2021-12-14 19:11 UTC, kaiyan-sheng approved these changes
Looks good to me! Waiting for @endorama 's review 🙂

2021-12-14 19:11 UTC, kaiyan-sheng commented
/test

2021-12-20 16:14 UTC, endorama requested changes

2021-12-20 16:14 UTC, endorama commented on packages/gcp/data_stream/compute/agent/stream/stream.yml.hbs
> +credentials_file: {{credentials_file}}
```suggestion
credentials_file_path: {{credentials_file}}
```

[While testing](https://github.com/elastic/integrations/pull/2312/commits/cb31f893b8da21af526fd0c14ad9624ed60aec18) the `billing` package I discovered the key should be `credentials_file_path`.

2021-12-20 16:14 UTC, endorama commented on packages/gcp/data_stream/compute/fields/agent.yml
> +  footnote: 'Examples: If Metricbeat is running on an EC2 host and fetches data from its host, the cloud info contains the data about this machine. If Metricbeat runs on a remote machine outside the
```suggestion
  footnote: 'Examples: If Metricbeat is running on an GCP Compute VM and fetches data from its host, the cloud info contains the data about this machine. If Metricbeat runs on a remote machine outside the cloud and fetches data from a service running in the cloud, the field contains cloud data from the machine the service is running on.'
```

2021-12-20 16:14 UTC, endorama commented on packages/gcp/docs/compute.md
> +| gcp.compute.instance.disk.read_bytes_count.value | Count of bytes read from disk | long |
I just noticed that most of these fields are different from the values in gcp metricset. For example: https://github.com/elastic/beats/blob/e6e65aa92fe355c95789691ebf5a3bcecaf5b4ea/x-pack/metricbeat/module/gcp/compute/_meta/fields.yml#L21

I'm wondering if this is ok or beats and integrations are expected to have the same fields (I would expect the latter). Pinging @mtojek here.

@legoguy1000 which version of beats you started this migration from? It seems has old fields values.

2021-12-20 16:19 UTC, endorama commented
Sorry for the delay, I've been stuck adding tests to the `billing` data stream. I did a first round of review and noticed something strange with field names.

2021-12-20 16:20 UTC, legoguy1000 commented on packages/gcp/docs/compute.md
> +| gcp.compute.instance.disk.read_bytes_count.value | Count of bytes read from disk | long |
Its totally possible I copied the fields from an old branch. I'll go to master and pull the latest.

2021-12-20 17:09 UTC, legoguy1000 commented
@endorama updates pushed

2021-12-20 17:14 UTC, endorama commented
@legoguy1000 May you please check dashboards too? It seems those still contains old values.

2021-12-24 11:56 UTC, endorama reviewed
Thank you for the updates! I see tests are still failing, but wasn't able to pin point the exact issue.

2021-12-24 11:57 UTC, endorama commented
rerunning tests in case has been a transactional issue.

/test

2021-12-24 15:06 UTC, legoguy1000 commented
@endorama It looks to be a mismatch between the sample _event.json and the defined fields for the compute dataset.  The sample events from Metricbeat, https://github.com/elastic/beats/tree/master/x-pack/metricbeat/module/gcp/compute/_meta, were not updated for the new field names and as such don't match the fields.yml.  Do you happen to have updated sample events that could be used?

2021-12-27 17:06 UTC, endorama commented
@legoguy1000 I'm working on updating the sample data, thanks for the hint

2021-12-28 14:37 UTC, endorama commented
I've been able to update the sample data and working on a PR in beats to update them.

2021-12-28 15:02 UTC, legoguy1000 commented
> I've been able to update the sample data and working on a PR in beats to update them.

Cool, feel free to push that update to this branch or send it to me and I'll update it.

2021-12-29 17:43 UTC, endorama commented
@legoguy1000 I started working on updating the sample events in beats in the linked PR, but is taking longer than expected. In any case I've been able to update the `compute` metricset sample events, so you may take those to update this PR, and I expect that to work. Meanwhile I'll work on updating the beats side too.

2021-12-29 22:25 UTC, legoguy1000 commented
@endorama looks like it worked.

2021-12-31 16:11 UTC, endorama commented
Thank you! I'm merging this as is good to go, I'll open a separate PR with testing for this data stream.

@legoguy1000 next week I'll be off, so feel free to open the next PR but I won't be able to look at it before the 10th of January. Thank you for the contribution and happy new year!

2021-12-31 16:11 UTC, merged