[atlassian_jira] Upgrade ECS to 8.0.0
elastic/integrations pull request #2379
Opened 2021-12-24 01:02 UTC by r00tu53r

Automated PR.

Upgrades ECS to 8.0.0.

2021-12-24 01:04 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2021-12-24 01:18 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2379/detail/PR-2379/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2379/detail/PR-2379/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2379/detail/PR-2379/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2379/detail/PR-2379/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_2379.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2021-12-24T00:52:50.892Z&rangeTo=2021-12-24T01:12:50.892Z&transactionName=Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=unknown&latencyAggregationType=avg&traceId=0e2c72f16dc8dd2597630b3cf1bd1cee&transactionId=f9d8c8c022a65ee0)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2021-12-24T01:02:50.892+0000


* Duration: 16 min 52 sec


* Commit: 7d4419bd561d94229a1faa53fe75867cd95f7efc



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 7  |
| Skipped      | 0 |
| Total        | 7   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-01-13 22:11 UTC, efd6 requested changes

2022-01-13 22:11 UTC, efd6 commented on packages/atlassian_jira/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/
```suggestion
      link: https://github.com/elastic/integrations/pull/2379
```

2022-01-25 05:04 UTC, efd6 approved these changes

2022-01-25 11:05 UTC, P1llus approved these changes
LGTM, but the output of the test samples is a bit different? I guess another sample was used to generate it?

2022-01-25 12:01 UTC, merged