[auditd] Upgrade ECS to 8.0.0
elastic/integrations pull request #2380
Opened 2021-12-24 01:33 UTC by r00tu53r

Automated PR.

Upgrades ECS to 8.0.0.

2021-12-24 01:34 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2021-12-24 01:47 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2380/detail/PR-2380/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2380/detail/PR-2380/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2380/detail/PR-2380/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2380/detail/PR-2380/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_2380.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2021-12-24T01:23:38.149Z&rangeTo=2021-12-24T01:43:38.149Z&transactionName=Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=unknown&latencyAggregationType=avg&traceId=a7e9ed29220b038df66fdbe6ce65a116&transactionId=7dc8319affa5a51f)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2021-12-24T01:33:38.149+0000


* Duration: 14 min 6 sec


* Commit: f70fb051f8d0c9f55e078c25b4adb9b62d7a5dcc



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 13  |
| Skipped      | 0 |
| Total        | 13   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2021-12-24 07:43 UTC, adriansr requested changes

2021-12-24 07:43 UTC, adriansr commented on packages/auditd/manifest.yml
> +  kibana.version: ^7.16.0 || ^8.0.0
I understand we shouldn't increment the minimum version unless we introduce a feature that requires a higher version

2022-01-13 22:18 UTC, efd6 approved these changes

2022-01-13 22:18 UTC, efd6 commented on packages/auditd/changelog.yml
> +- version: "2.0.0"
Just confirming that this is bumped to 2 because of ppid -> parent.pid change.

2022-01-25 04:39 UTC, r00tu53r commented on packages/auditd/changelog.yml
> +- version: "2.0.0"
Yes that's right as it results in a breaking change.

2022-01-25 11:05 UTC, P1llus approved these changes

2022-01-25 12:50 UTC, adriansr approved these changes

2022-01-27 22:46 UTC, andrewkroh commented on packages/auditd/changelog.yml
> +      type: enhancement
It's also a "breaking change". Perhaps there should be a secondary change listed with the same PR link that describes that `process.ppid` was replaced with `process.parent.pid`.

2022-02-02 04:54 UTC, merged