[bluecoat] Upgrade ECS to 8.0.0
elastic/integrations pull request #2382
Opened 2021-12-24 08:57 UTC by r00tu53r

Automated PR.

Upgrades ECS to 8.0.0.

2021-12-24 08:58 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2021-12-24 09:14 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2382/detail/PR-2382/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2382/detail/PR-2382/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2382/detail/PR-2382/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2382/detail/PR-2382/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_2382.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2021-12-24T08:48:08.184Z&rangeTo=2021-12-24T09:08:08.184Z&transactionName=Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=unknown&latencyAggregationType=avg&traceId=2ade0d8ec50d02cf34b865e5f21d7b93&transactionId=cea3b56b39fec55e)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2021-12-24T08:58:08.184+0000


* Duration: 17 min 35 sec


* Commit: df130ed645bba3b2ad744ab07756161a6a4ea8ee



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 7  |
| Skipped      | 0 |
| Total        | 7   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2021-12-24 09:59 UTC, adriansr requested changes

2021-12-24 09:59 UTC, adriansr commented on packages/bluecoat/changelog.yml
> +- version: "1.0.0"
versions >= 1.0.0 should be reserved for when the package is released as _GA._ Currently it's still _experimental._

2021-12-24 09:59 UTC, adriansr commented on packages/bluecoat/manifest.yml
> +  kibana.version: "^7.16.0 || ^8.0.0"
Same as with other packages. Do we really need to do this?

2022-01-13 22:28 UTC, efd6 commented on packages/bluecoat/data_stream/director/fields/ecs.yml
> +  name: process.parent.pid
Breaking change?

2022-01-13 22:28 UTC, efd6 commented on packages/bluecoat/manifest.yml
> +version: 0.6.2
0.7.0?

2022-01-25 07:15 UTC, r00tu53r commented on packages/bluecoat/manifest.yml
> +version: 0.6.2
fixed. Thanks!!

2022-01-25 07:15 UTC, r00tu53r commented on packages/bluecoat/data_stream/director/fields/ecs.yml
> +  name: process.parent.pid
That's right!

2022-01-25 11:29 UTC, marc-gr approved these changes

2022-01-26 10:25 UTC, adriansr commented
Replaced with #2576

2022-01-26 10:25 UTC, closed without merging