[cyberarkpas] Upgrade ECS to 8.0.0
elastic/integrations pull request #2400
Opened 2021-12-30 06:23 UTC by r00tu53r

Automated PR.

Upgrades ECS to 8.0.0.

2021-12-30 06:33 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2400/detail/PR-2400/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2400/detail/PR-2400/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2400/detail/PR-2400/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2400/detail/PR-2400/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_2400.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2021-12-30T06:13:52.335Z&rangeTo=2021-12-30T06:33:52.335Z&transactionName=Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=unknown&latencyAggregationType=avg&traceId=4715b978b1e7640bfa27c2139b6b7821&transactionId=f319c0ade764e689)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2021-12-30T06:23:52.335+0000


* Duration: 10 min 43 sec


* Commit: 23c2cb0b3f6c1b20a6f1094520ec0bfca63691c6




</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->











### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2400/detail/PR-2400/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Check integration: cyberarkpas`
<ul>
<li>Took 0 min 1 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-2400/runs/1/steps/702/log/?start=0">here</a></li>
<li>Description: <code>../../build/elastic-package check -v</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-2400/runs/1/steps/738/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>


## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2021-12-31 00:53 UTC, r00tu53r commented
/test

2022-01-14 02:12 UTC, efd6 requested changes

2022-01-14 02:12 UTC, efd6 commented on packages/cyberarkpas/data_stream/audit/sample_event.json
> +        "version": "1.12.0"
8.0.0

2022-01-14 02:12 UTC, efd6 commented on packages/fireeye/data_stream/nx/sample_event.json
>          "version": "1.12.0"
8.0.0

2022-02-03 12:54 UTC, r00tu53r commented on packages/cyberarkpas/data_stream/audit/sample_event.json
> +        "version": "1.12.0"
Fixed.

2022-02-03 12:58 UTC, r00tu53r commented on packages/fireeye/data_stream/nx/sample_event.json
>          "version": "1.12.0"
Due to merge issue it was in fireeye. Its been resolved.

2022-02-03 13:25 UTC, marc-gr approved these changes

2022-02-04 01:55 UTC, efd6 approved these changes

2022-02-04 01:56 UTC, merged