Add zeek package
elastic/integrations pull request #245
Opened 2020-08-12 22:20 UTC by leehinman

## What does this PR do?

Add package for the filebeat Zeek module.  Includes capture_loss,
connection, dce_rpc, dhcp, dnp3, dns, dpd, files, ftp, http, intel
irc, kerberos, modbus, mysql, notice, ntlm, ocsp, pe, radius, rdp
rfb, sip, smb_cmd, smb_files, smb_mapping, smtp, snmp, socks
ssh, ssl, stats, syslog, traceroute, tunnel, weird, x509

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md#tips-for-building-integrations) and this pull request is aligned with them.
- [x] I have verified that all datasets collect metrics or logs.

## Related issues

- Closes #225

## Screenshots
![image](https://user-images.githubusercontent.com/57081003/90073873-a434a800-dcbf-11ea-893f-212c622171df.png)
![image](https://user-images.githubusercontent.com/57081003/90073919-bf071c80-dcbf-11ea-85a4-54c7a471da5f.png)
![image](https://user-images.githubusercontent.com/57081003/90073980-d80fcd80-dcbf-11ea-811c-ac13427c9c44.png)
![image](https://user-images.githubusercontent.com/57081003/90074004-e8c04380-dcbf-11ea-8735-6e28336c8f7b.png)
![image](https://user-images.githubusercontent.com/57081003/90074055-01c8f480-dcc0-11ea-8645-d406efec69bb.png)

2020-08-12 22:20 UTC, elasticmachine commented
Pinging @elastic/integrations (Team:Integrations)

2020-08-12 22:20 UTC, elasticmachine commented
Pinging @elastic/siem (Team:SIEM)

2020-08-12 22:24 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fintegrations%2FPR-245/detail/PR-245/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fintegrations%2FPR-245/detail/PR-245/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fintegrations%2FPR-245/detail/PR-245/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fintegrations%2FPR-245/detail/PR-245/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_245.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats

* Build Cause: `[Pull request #245 opened]`

* Start Time: 2020-08-12T22:20:59.399+0000

* Duration: 4 min 48 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY-->





<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2020-08-13 23:41 UTC, andrewstucki commented
I'll go through this... slowly... reviews will be in chunks

2020-09-14 19:26 UTC, andrewkroh commented on packages/zeek/kibana/visualization/1df7ea80-370d-11e9-aa6d-ff445a78330c.json
> +                    "query": ""
Should these visualizations have a query to only select Zeek data? If so we can take advantage of the constant_keyword data_stream fields for this.

2020-09-14 19:26 UTC, andrewkroh commented on packages/zeek/dataset/dhcp/manifest.yml
> +  - name: community_id
This might be a lot of work, but I'd like to have this config option removed from everywhere. The processor should always be included. I can't think of any reason to make it configurable.

2020-09-17 12:01 UTC, andrewkroh approved these changes
LGTM 🎉

2020-09-17 12:14 UTC, mtojek requested changes
Unfortunately CI reported issues for this PR: https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fintegrations/detail/PR-245/13/pipeline

2020-09-17 14:30 UTC, leehinman commented
> Unfortunately CI reported issues for this PR: https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fintegrations/detail/PR-245/13/pipeline
> 
> EDIT:
> 
> After a short investigation with @ycombinator , it looks that we have a requirement for dataset names to be at least 3 characters: https://github.com/elastic/package-spec/blob/master/versions/1/dataset/spec.yml#L6 . I'm wondering whether it's a good requirement to prevent a non-descriptive, mysterious names like in this case "pe".
> 
> It's not a big deal to change it, but maybe it's better to keep it. WDYT @ruflin @ycombinator ?

Just a bit of context.  The datasets are named after the ~40 log files that zeek produces.  And in this case the log file is called `pe.log` (abbreviation for Portable Executable).  

It might be a little weird for all the others to be direct mappings (mysql.log -> mysql) but this one to be pe.log -> portable_executable.  I'd vote for an exception in this case, most of the time a 2 letter name would be mysterious but in this context making it not like all the others could be more mysterious.  Luckily this is the only 2 letter log name for zeek. https://docs.zeek.org/en/current/script-reference/log-files.html

2020-09-17 14:39 UTC, ycombinator commented
I'm in favor of keeping it as `pe` (which would mean relaxing [the constraint in the spec](https://github.com/elastic/package-spec/blob/master/versions/1/dataset/spec.yml#L6)). `pe` makes sense in the context of this integration so I would expect it would make sense to developers of this integration as well.

However, if we decide to change it to be more descriptive, then I'd suggest doing that consistently for other datasets of this integration as well, e.g. `dnp3`, `dpd`, `ocsp`, `rfb`. But then you'd again run into an issue of subjectivity: who decides whether an abbreviation need to expanded to be more descriptive vs. leaving it as-is?

So I think the rule-of-thumb should be that we use dataset names that makes sense in the context of an integration.

2020-09-18 06:48 UTC, mtojek commented
Ok, I'm going to open PR against package-spec to adjust the schema.

2020-09-18 07:08 UTC, ruflin commented
I'm good with changing the constraint. Keep in mind that in most cases this also effects the index name. For short vs long: We probably should have a recommendation but in the end, it is up to the person writing the package to make the call.

2020-09-18 08:41 UTC, mtojek commented
@leehinman I updated the dependency on package-spec on master branch. Please rebase this PR against master and `mage clean && mage check`.

2020-09-18 18:29 UTC, leehinman commented
> @leehinman I updated the dependency on package-spec on master branch. Please rebase this PR against master and `mage clean && mage check`.

Done.  Thanks for all the help.

2020-09-18 19:12 UTC, mtojek approved these changes

2020-09-18 20:06 UTC, merged