Azure
elastic/integrations pull request #2497
Opened 2022-01-11 07:29 UTC by emnp

## What does this PR do?
A new package to collect logs from azure frondoor.
Two data-streams;
- AFD access log
- AFD waf log

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally
```
# cd integrations/packages/azure_frontdoor
# elastic-package build
# elastic-package stack up -d -v
# eval "$(elastic-package stack shellinit)"
# elastic-package test  -v
```

## Screenshots
![azure-frontdoor-overview](https://user-images.githubusercontent.com/29004087/148899335-0d8508d7-5417-4305-bb84-dfdd9db9a280.png)

2022-01-11 07:33 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2497/detail/PR-2497/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2497/detail/PR-2497/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2497/detail/PR-2497/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2497/detail/PR-2497/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-01-11T07:19:51.398Z&rangeTo=2022-01-11T07:39:51.398Z&transactionName=Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=unknown&latencyAggregationType=avg&traceId=a548cc98ecec8d0a741a3f142b8f2a2a&transactionId=aa0cb77805b5d729)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats



* Reason: `The PR is not allowed to run in the CI yet`


* Start Time: 2022-01-11T07:29:51.398+0000


* Duration: 4 min 42 sec


* Commit: cab955b51d0b7e5453d8b4e4c6bd6e5ea4389b2c




</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->











### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2497/detail/PR-2497/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-2497/runs/1/steps/109/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>


## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-09-28 07:47 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2022-09-28 07:48 UTC, P1llus commented
Hello @emnp 

Sorry for the delayed response on this! Are you still open to finalize the package together with me as a review?

2022-11-28 04:05 UTC, emnp commented
Hi @P1llus, sorry for the delay. Can I continue to work on this PR?

2022-11-28 06:08 UTC, P1llus commented
Absolutely @emnp . I will try to merge your other PR soon as well, sorry for the delay!

2022-11-28 10:40 UTC, emnp commented
> Absolutely @emnp . I will try to merge your other PR soon as well, sorry for the delay!

Hi @P1llus, I just updated the stuff like the readme file as per documentation guidelines, kibana version up to 8 in manifest.yml and change IPs in the test log to allowed IPs. Please take a look.

2022-11-29 08:59 UTC, P1llus commented
/test

2022-11-30 05:32 UTC, ShourieG commented on packages/azure_frontdoor/data_stream/access/elasticsearch/ingest_pipeline/default.yml
> +#      field: event.original
Please remove commented configs.

2022-11-30 05:43 UTC, ShourieG commented
/test

2022-11-30 06:07 UTC, ShourieG commented on packages/azure_frontdoor/data_stream/access/agent/stream/azure-eventhub.yml.hbs
> +{{#each tags as |tag i|}}
```suggestion
{{#each tags as |tag|}}
```

2022-11-30 06:08 UTC, ShourieG commented on packages/azure_frontdoor/data_stream/access/elasticsearch/ingest_pipeline/default.yml
> +#      patterns:
please remove commented code

2022-11-30 06:09 UTC, ShourieG commented on packages/azure_frontdoor/data_stream/waf/elasticsearch/ingest_pipeline/default.yml
> +#      patterns:
please remove commented code

2022-11-30 06:17 UTC, ShourieG commented on packages/azure_frontdoor/data_stream/waf/agent/stream/azure-eventhub.yml.hbs
> +{{#each tags as |tag i|}}
```suggestion
{{#each tags as |tag|}}
```

2022-11-30 06:17 UTC, ShourieG commented on packages/azure_frontdoor/data_stream/access/agent/stream/stream.yml.hbs
> +{{#each paths as |path i|}}
```suggestion
{{#each paths as |path|}}
```

2022-11-30 06:18 UTC, ShourieG commented on packages/azure_frontdoor/data_stream/waf/agent/stream/stream.yml.hbs
> +{{#each paths as |path i|}}
```suggestion
{{#each paths as |path|}}
```

2022-12-01 09:16 UTC, P1llus commented
/test

2022-12-01 11:13 UTC, kcreddy commented
@emnp Can you add an entry to `.github/CODEOWNERS` for this package? CI is failing because of this error.

2022-12-01 13:16 UTC, ShourieG commented on packages/azure_frontdoor/data_stream/access/elasticsearch/ingest_pipeline/default.yml
> +      ignore_failure: true
```suggestion
```

2022-12-01 13:25 UTC, ShourieG commented on packages/azure_frontdoor/data_stream/waf/elasticsearch/ingest_pipeline/default.yml
> +      ignore_failure: true
```suggestion
```

2022-12-01 13:35 UTC, ShourieG commented on packages/azure_frontdoor/data_stream/waf/elasticsearch/ingest_pipeline/default.yml
> +      value: "{{_ingest.timestamp}}"
```suggestion
```

We add this by default now, so it's not required to be defined explicitly

2022-12-01 13:35 UTC, ShourieG commented on packages/azure_frontdoor/data_stream/waf/elasticsearch/ingest_pipeline/default.yml
> +      value: "1.12.0"
```suggestion
      value: "8.5.0"
```

2022-12-01 13:38 UTC, ShourieG commented on packages/azure_frontdoor/_dev/build/build.yml
> +    reference: git@1.12
```suggestion
    reference: git@v8.5.0
```
Needs to be 8.5 and above, you can use  8.5.1  also but it requires to be changed throughout accordingly.

2022-12-01 13:39 UTC, ShourieG commented on packages/azure_frontdoor/changelog.yml
> +- version: "0.0.1"
```suggestion
- version: "0.1.0"
```
Since system tests are added, this can be considered a beta of sorts and hence the version bump.

2022-12-01 13:49 UTC, ShourieG commented on packages/azure_frontdoor/data_stream/access/_dev/test/pipeline/test-fdaccess.log-expected.json
> +                    "operation_name": "Microsoft.Network/FrontDoor/AccessLog/Write",
**"operation_name"** seems like an action is taking place, this can be made more verbose by treating it so. Example we can add it as part of the event object `"event": {
                "action": "Microsoft.Network/FrontDoor/AccessLog/Write"
            }`

2022-12-01 13:51 UTC, ShourieG commented on packages/azure_frontdoor/data_stream/access/_dev/test/pipeline/test-fdaccess.log-expected.json
> +                "version": "1.12.0"
```suggestion
                "version": "8.5.0"
```
The "*-expected.json" files need to be all updated with the correct ecs version

2022-12-01 13:53 UTC, ShourieG commented on packages/azure_frontdoor/data_stream/access/_dev/test/pipeline/test-fdaccess.log-expected.json
> +                "ingested": "2022-11-30T08:39:10.169846321Z"
```suggestion
                "ingested": "2022-11-30T08:39:10.169846321Z",
                "category": "some_category",
                "type": "some_type"
```
If you can, please add a **type** & **category** attribute to the event object, since this are standard fields for our integrations.

2022-12-01 14:06 UTC, ShourieG commented on packages/azure_frontdoor/data_stream/access/_dev/test/pipeline/test-fdaccess.log-expected.json
> +                "version": "1.12.0"
```suggestion
                "version": "8.5.0"
```

2022-12-01 14:08 UTC, ShourieG commented on packages/azure_frontdoor/data_stream/waf/_dev/test/system/test-default-config.yml
> +service: fdwaf-log-logfile
Is this only used for log file test ? If so we can remove it

2022-12-01 14:08 UTC, ShourieG commented on packages/azure_frontdoor/data_stream/access/_dev/test/system/test-default-config.yml
> +service: fdaccess-log-logfile
Is this only used for log file test ? If so we can remove it.

2022-12-01 14:09 UTC, ShourieG commented on packages/azure_frontdoor/data_stream/waf/_dev/test/pipeline/test-fdwaf.log-expected.json
> +        null
is it null because you are testing the drop processor ?

2022-12-01 14:11 UTC, ShourieG commented on packages/azure_frontdoor/data_stream/waf/agent/stream/stream.yml.hbs
> +paths:
is this being used for only testing log files ?

2022-12-07 04:05 UTC, emnp commented on packages/azure_frontdoor/_dev/build/build.yml
> +    reference: git@1.12
Hello @ShourieG , I got an error with 8.5 so I used 8.4 instead of that. Is this okay?

2022-12-07 04:08 UTC, emnp commented on packages/azure_frontdoor/data_stream/access/_dev/test/pipeline/test-fdaccess.log-expected.json
> +                "preserve_original_event"
Could you please check for me? I'm not getting the tags that I want to set.

2022-12-07 04:09 UTC, emnp commented on packages/azure_frontdoor/data_stream/access/_dev/test/system/test-default-config.yml
> +service: fdaccess-log-logfile
I will remove it later.

2022-12-07 04:11 UTC, emnp commented on packages/azure_frontdoor/data_stream/waf/_dev/test/pipeline/test-fdwaf.log-expected.json
> +        null
Yes. Sometimes logs can include that kind of format. So for now I removed the invalid JSON log from the test log.

2022-12-08 04:57 UTC, ShourieG commented on packages/azure_frontdoor/data_stream/access/_dev/test/system/test-default-config.yml
> +service: fdaccess-log-logfile
ok

2022-12-08 05:36 UTC, ShourieG commented on packages/azure_frontdoor/_dev/build/build.yml
> +    reference: git@1.12
what exact errors are you facing ?

2022-12-08 06:17 UTC, emnp commented on packages/azure_frontdoor/_dev/build/build.yml
> +    reference: git@1.12
With 8.5, I got this.
```
Error: updating files failed: updating readme file README.md failed: rendering Readme failed: executing template failed: template: README.md:21:2: executing "README.md" at <fields "deep_security">: error calling fields: can't create fields validator instance (path: /mnt/c/k/current/trendmicro/integrations/packages/trendmicro/data_stream/deep_security): can't create field dependency manager: can't build fields schema: can't load fields: unmarshalling field body failed: yaml: unmarshal errors:Error: updating files failed: updating readme file README.md failed: rendering Readme failed: executing template failed: template: README.md:21:2: executing "README.md" at <fields "deep_security">: error calling fields: can't create fields validator instance (path: /mnt/c/k/current/trendmicro/integrations/packages/trendmicro/data_stream/deep_security): can't create field dependency manager: can't build fields schema: can't load fields: unmarshalling field body failed: yaml: unmarshal errors:
```

2022-12-27 08:03 UTC, kcreddy commented on packages/azure_frontdoor/data_stream/access/_dev/test/pipeline/test-fdaccess.log-expected.json
> +                "preserve_original_event"
The expected file corresponds to pipeline tests. In that case, the tags need to be defined here: https://github.com/emnp/integrations/blob/azure/packages/azure_frontdoor/data_stream/access/_dev/test/pipeline/test-common-config.yml

2022-12-27 08:44 UTC, kcreddy requested changes
Add an entry into `.github/CODEOWNERS`

2022-12-27 08:44 UTC, kcreddy commented on packages/azure_frontdoor/kibana/dashboard/azure_frontdoor-d05e0860-6ea7-11ec-bf35-712f9048d91f.json
> +            "type": "lens"
As a best practice, we are moving dashboards using `by-reference` into `by-value`. Could you instead use `by-value` visualisations here if those lens visuals are not going to be used independently? 
You could refer here:
https://www.elastic.co/blog/new-in-kibana-how-we-made-it-easier-manage-visualizations-and-build-dashboards

2022-12-27 08:44 UTC, kcreddy commented on packages/azure_frontdoor/data_stream/access/elasticsearch/ingest_pipeline/default.yml
> +      if: 'ctx?.event.original.contains(''"records"'')'
```suggestion
      if: 'ctx.event?.original?.contains(''"records"'')'
```
Since `ctx` is never null

2022-12-27 08:44 UTC, kcreddy commented on packages/azure_frontdoor/data_stream/access/elasticsearch/ingest_pipeline/default.yml
> +      pattern: "%{tls.version_protocol} %{tls.version}"
Could you add `ignore_missing` here in case the field is null?

2022-12-27 08:44 UTC, kcreddy commented on packages/azure_frontdoor/data_stream/access/elasticsearch/ingest_pipeline/default.yml
> +        - event.original
Could you add `ignore_missing` here in case the field(s) is null?

2022-12-27 08:44 UTC, kcreddy commented on packages/azure_frontdoor/data_stream/access/elasticsearch/ingest_pipeline/default.yml
> +      if: 'ctx?.event.original.contains(''"records"'')'
```suggestion
      if: 'ctx.event?.original?.contains(''"records"'')'
```
Since `ctx` is never null

2022-12-27 08:44 UTC, kcreddy commented on packages/azure_frontdoor/data_stream/access/elasticsearch/ingest_pipeline/default.yml
> +      if: 'ctx?.event.original.contains(''"records"'')'
Can you add a pipeline test to verify this?

2022-12-27 08:44 UTC, kcreddy commented on packages/azure_frontdoor/data_stream/access/manifest.yml
> +  - input: logfile
Please use the [new filestream input](https://www.elastic.co/guide/en/beats/filebeat/master/filebeat-input-filestream.html) instead. Config is very similar to `log` input.

You will need to change in 2 places. 
Refer:
https://github.com/elastic/integrations/blob/bbf0e61385e2567d0b00ee257fa3b023ae2bc4b5/packages/hid_bravura_monitor/manifest.yml#L46
https://github.com/elastic/integrations/blob/bbf0e61385e2567d0b00ee257fa3b023ae2bc4b5/packages/hid_bravura_monitor/data_stream/log/manifest.yml#L4

2022-12-27 08:44 UTC, kcreddy commented on packages/azure_frontdoor/data_stream/waf/elasticsearch/ingest_pipeline/default.yml
> +      if: 'ctx?.event.original.contains(''"records"'')'
Look at similar comment on `access` data_stream.

2022-12-27 08:44 UTC, kcreddy commented on packages/azure_frontdoor/data_stream/waf/elasticsearch/ingest_pipeline/default.yml
> +        - event.original
needs `ignore_missing`

2022-12-27 08:44 UTC, kcreddy commented on packages/azure_frontdoor/data_stream/waf/manifest.yml
> +  - input: logfile
Needs to be converted to `filestream` input. Look at comment on `access` data_stream.

2022-12-27 08:44 UTC, kcreddy commented on packages/azure_frontdoor/manifest.yml
> +release: experimental
Please mark it as `beta`.

2023-02-02 06:57 UTC, P1llus commented
@kcreddy i think it might be good if we apply the last commits to this PR, would that be okay?

2023-02-02 10:14 UTC, kcreddy commented on packages/azure_frontdoor/manifest.yml
> +release: experimental
marked as beta

2023-02-02 10:18 UTC, kcreddy commented
/test

2023-02-02 10:20 UTC, kcreddy commented on packages/azure_frontdoor/data_stream/waf/manifest.yml
> +  - input: logfile
changed to `filestream`

2023-02-02 10:20 UTC, kcreddy commented on packages/azure_frontdoor/data_stream/waf/elasticsearch/ingest_pipeline/default.yml
> +        - event.original
added `ignore_missing`

2023-02-02 10:20 UTC, kcreddy commented on packages/azure_frontdoor/data_stream/waf/elasticsearch/ingest_pipeline/default.yml
> +      if: 'ctx?.event.original.contains(''"records"'')'
changed it to `if: 'ctx.event?.original != null && ctx.event.original.contains(''"records"'')'`

2023-02-02 10:21 UTC, kcreddy commented on packages/azure_frontdoor/data_stream/access/manifest.yml
> +  - input: logfile
updated to `filestream`

2023-02-02 10:21 UTC, kcreddy commented on packages/azure_frontdoor/data_stream/access/elasticsearch/ingest_pipeline/default.yml
> +      if: 'ctx?.event.original.contains(''"records"'')'
updated to `if: 'ctx.event?.original != null && ctx.event.original.contains(''"records"'')'`

2023-02-02 10:21 UTC, kcreddy commented on packages/azure_frontdoor/data_stream/access/elasticsearch/ingest_pipeline/default.yml
> +      if: 'ctx?.event.original.contains(''"records"'')'
added pipeline test

2023-02-02 10:21 UTC, kcreddy commented on packages/azure_frontdoor/data_stream/access/elasticsearch/ingest_pipeline/default.yml
> +      pattern: "%{tls.version_protocol} %{tls.version}"
added ignore_missing

2023-02-02 10:22 UTC, kcreddy commented on packages/azure_frontdoor/data_stream/access/elasticsearch/ingest_pipeline/default.yml
> +      if: 'ctx?.event.original.contains(''"records"'')'
updated to `if: 'ctx.event?.original != null && ctx.event.original.contains(''"records"'')'`

2023-02-02 10:22 UTC, kcreddy commented on packages/azure_frontdoor/kibana/dashboard/azure_frontdoor-d05e0860-6ea7-11ec-bf35-712f9048d91f.json
> +            "type": "lens"
changed dashboard to by-value

2023-02-02 10:23 UTC, kcreddy reviewed
LGTM

2023-02-02 10:25 UTC, kcreddy approved these changes
Changes made based on the review suggestions. Once @P1llus gives thumbsup, can be merged

2023-02-02 10:32 UTC, kcreddy commented
/test

2023-02-02 10:53 UTC, kcreddy commented
/test

2023-02-02 11:09 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`2/2`) | :green_heart: 
Files | 100.0% (`2/2`) | :green_heart: 
Classes | 100.0% (`2/2`) | :green_heart: 
Methods | 100.0% (`24/24`) | :green_heart: 3.846
Lines | 100.0% (`288/288`) | :green_heart: 
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-02-02 11:57 UTC, kcreddy commented
/test

2023-02-02 12:00 UTC, P1llus approved these changes
LGTM from what I can see

2023-02-03 07:43 UTC, P1llus commented
@emnp we have added the last changes needed before a merge, just wanted to check in with you that this is okay?

Sorry for the unusual long waiting time here!

2023-02-09 10:59 UTC, merged

2023-02-09 11:19 UTC, elasticmachine commented
Package azure_frontdoor - 0.0.1 containing this change is available at https://epr.elastic.co/search?package=azure_frontdoor