updated max connections to max agent
elastic/integrations pull request #2531
Opened 2022-01-14 03:40 UTC by lykkin

## What does this PR do?

Converts the max connections to a max agents field. This change is related to https://github.com/elastic/fleet-server/pull/1014.

Technically a breaking change, since this removes a field that may be used by users. 

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally

Host the package registry, enroll and run an agent, set a value in the Max agents field and observe the config come down as such:

```
...
    inputs:
    - data_stream:
        namespace: default
      id: default-fleet-server-agent-policy
      meta:
        package:
          name: fleet_server
          version: 2.0.0
      name: fleet_server-1
      revision: 3
      server:
        host: 0.0.0.0
        limits.max_agents: 100
        port: 8220
      type: fleet-server
      use_output: default

...
```

## Related issues

Closes https://github.com/elastic/fleet-server/issues/571

2022-01-14 03:50 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2531/detail/PR-2531/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2531/detail/PR-2531/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2531/detail/PR-2531/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2531/detail/PR-2531/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_2531.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-01-14T03:30:43.085Z&rangeTo=2022-01-14T03:50:43.085Z&transactionName=Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=unknown&latencyAggregationType=avg&traceId=33720a1225e48f2929d6140f4317a3f9&transactionId=7668f569a583ad72)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-01-14T03:40:43.085+0000


* Duration: 10 min 53 sec


* Commit: 497e96b5ba95ad7e912d849a826338cf1782d374




</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->











### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2531/detail/PR-2531/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Check integration: fleet_server`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-2531/runs/1/steps/706/log/?start=0">here</a></li>
<li>Description: <code>../../build/elastic-package check -v</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-2531/runs/1/steps/742/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>


## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-01-14 10:24 UTC, ruflin requested changes
I would like to better understand what is the migration path for our users here? What if users have set the setting in a previous version and upgrade? Do we need to adjust the compatibility of this package to a more recent version of Kibana?

So far we tried to stay away from breaking changes in packages and especially for a package like fleet_server that every Elastic Agent users use, we should not introduce any change that will break users just upgrading.

Lets figure out the migration story. If there is already a plan, can you link it here to read up?

2022-01-19 18:55 UTC, ph requested changes
See issue with goroutine.

2022-01-25 16:30 UTC, lykkin commented
@ruflin @nimarezainia i started [a migration doc](https://docs.google.com/document/d/1oeCvQ-QXUU1d7KQeyXPTR_kex8zmDtR3viUwBqwDyRU/edit) where we can start talking about how to handle the update.

2022-02-22 09:24 UTC, jlind23 commented
@lykkin any update there?

2022-03-22 08:06 UTC, jlind23 commented
@lykkin is it ready to be reviewed again?

2022-03-28 07:25 UTC, ruflin reviewed
What is the migration story we landed on? Lets add the details to this Pull Request so everyone is aware and the PR can be reviewed with this migration story in mind.

2022-03-28 07:25 UTC, ruflin commented on packages/fleet_server/manifest.yml
> +  kibana.version: "^7.16.0 || ^8.1.0"
It seems odd that someone can install a package in 7.16, but then when going to 8.0 it is not compatible anymore and only compatible in 8.1?

2022-03-28 14:08 UTC, lykkin commented on packages/fleet_server/manifest.yml
> +  kibana.version: "^7.16.0 || ^8.1.0"
good catch, this was left over from when we were going to land UI changes alongside this.

2022-03-28 14:10 UTC, lykkin commented
> migration story we landed on? Lets add the details to this Pull Request so everyone is aware and the PR can be reviewed with this migration story in mind.

we are going to update the UI to have the new field and handle reconciliation of the values on the fleet server side. there will be some UI changes to make it easier to work with in a later release.

2022-03-29 07:45 UTC, ruflin commented
> Technically a breaking change, since this removes a field that may be used by users.
Nit: Can you cleanup the PR description. I assume this is not true anymore?

In this PR the required Kibana version is not changed. But https://github.com/elastic/fleet-server/pull/1014 is not merged yet and very unlikely backported to 7.x. What happens if this is used with an 8.0 or 7.last fleet-server version that does not support this config yet. There is also the scenario, that Kibana is actually on a more recent version but fleet-server is not upgraded yet.

2022-03-29 15:41 UTC, lykkin commented
> > Technically a breaking change, since this removes a field that may be used by users.
> > Nit: Can you cleanup the PR description. I assume this is not true anymore?
> 
> In this PR the required Kibana version is not changed. But [elastic/fleet-server#1014](https://github.com/elastic/fleet-server/pull/1014) is not merged yet and very unlikely backported to 7.x. What happens if this is used with an 8.0 or 7.last fleet-server version that does not support this config yet. There is also the scenario, that Kibana is actually on a more recent version but fleet-server is not upgraded yet.

In those cases the field will be ignored by fleet-server, however there will be no feedback to the user that this will be an issue.

Is there a way to add a condition for this case? If not, do we report library version to ES?

I'm not entirely sure what the best way forward here is. @ruflin @ph, thoughts?

2022-03-29 17:47 UTC, ph commented
I've given some thoughts on this, I do not consider this a breaking change because of the following:

- We are actually giving them a better experience at the cost of removing an option.
- We aren't crashing hard on the use.

Now concerning the behavior of the Fleet Server, we should make sure we log that you are using a deprecated field.

@ruflin Concerning the case of running an 8.0 Kibana and a 7.last Fleet-Server, I am not sure this really applies. Because 8.0 needs to support 7. last. I am not sure that 8.2 is a hard requirement to support 7.last and we do suggest upgrading and have the stack aligned.

2022-03-29 17:48 UTC, ph approved these changes

2022-03-29 17:51 UTC, lykkin commented
We are actually giving them a better experience at the cost of removing an option.

Currently we aren't removing a field, just deprecating it. We will be handling the reconciliation of the values when they hit fleet-server. This _should_ avoid a breaking change, as it won't change behavior until they update their configs to use the new value.

2022-03-30 14:14 UTC, ruflin commented
Lets assume we have a user that uses fleet-server 8.0 and Kibana 8.3. That user will put in a config option assuming it works. But in reality, nothing happens. Maybe we can solve this by just adding a note in the description of the config option?

2022-03-30 14:57 UTC, lykkin commented
> Lets assume we have a user that uses fleet-server 8.0 and Kibana 8.3. That user will put in a config option assuming it works. But in reality, nothing happens. Maybe we can solve this by just adding a note in the description of the config option?

 I think this is a decent compromise. Ideally, I think we would want something programmatic that would gate fields based on installed library versions, but I think that would be a future feature.

2022-03-30 20:05 UTC, lykkin commented on packages/fleet_server/manifest.yml
> +              Requires fleet-server v8.2 and higher.
I'll update this to be 8.3 if we decide to punt due to feature freeze

2022-05-04 07:07 UTC, jlind23 commented
@ruflin can we get your eyes on this as you are the last step before being able to merge.

2022-05-05 07:36 UTC, ruflin approved these changes
LGTM. I assume this was tested with 8.3 but also 8.0 / 7.17 version of fleet-server. In theory it should work, but lets make sure we do not break any old deployments when this package is upgraded.

2022-05-18 09:08 UTC, jlind23 commented
@ph can you merge it please?

2022-05-18 16:39 UTC, merged