add ssl.certificate_authorities configuration
elastic/integrations pull request #2613
Opened 2022-01-28 10:57 UTC by tetianakravchenko

Signed-off-by: Tetiana Kravchenko <tetiana.kravchenko@elastic.co>

## What does this PR do?

To support Openshift k8s package is missing some configuration settings - for more details - https://github.com/elastic/observability-docs/pull/1498/files and https://github.com/elastic/beats/pull/30054/files

for `kubernetes.state_*`:
no way to set:
```
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  ssl.certificate_authorities:
    - /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
```

to all datastreams that connnect to `https://${env.NODE_NAME}:10250` (like `kubernetes.container`) no way to set:
```
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  ssl.certificate_authorities:
    - /path/to/ca-bundle.crt
```

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally

## Related issues

- Relates https://github.com/elastic/integrations/issues/2065

## Screenshots

For `kubernetes.state_*` resources:
<img width="726" alt="Screenshot 2022-01-28 at 11 42 43" src="https://user-images.githubusercontent.com/28299531/151534143-c6ee61d6-dc2e-4d9f-b2ac-b2c2f6786d9e.png">

for kubernetes.

2022-01-28 11:03 UTC, tetianakravchenko commented on packages/kubernetes/data_stream/state_container/manifest.yml
> +        show_user: false
I did not set here a default value, though it is mostly standard - `/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt` for `kubernetes.state_` datasets just to avoid getting `ssl.certificate_authorities` setting in final config, is there any better way to handle it?

2022-01-28 11:08 UTC, ChrsMark commented on packages/kubernetes/data_stream/state_container/manifest.yml
> +        show_user: false
I think leaving it blank is just fine since you have the `ifs` in the handlebars file (`stream.yml.hbs `).

2022-01-28 11:10 UTC, ChrsMark requested changes
Nice @tetianakravchenko ! Could you maybe move `node` and `namespace` settings under advanced settings too? This would make the basic setting panel more compact.

2022-01-28 11:32 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2613/detail/PR-2613/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2613/detail/PR-2613/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2613/detail/PR-2613/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2613/detail/PR-2613/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_2613.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-01-28T10:47:58.964Z&rangeTo=2022-01-28T11:07:58.964Z&transactionName=Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=c1513312938fc7c5b9ab5a79d06b6204&transactionId=29d166985b227bb0)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats



* Reason: `null`


* Start Time: 2022-01-28T10:57:58.964+0000


* Duration: 35 min 31 sec


* Commit: 9dc565ed16cbd4621e1f5bffd58ebef551f052fb



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 116  |
| Skipped      | 0 |
| Total        | 116   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-01-28 12:09 UTC, MichaelKatsoulis commented on packages/kubernetes/data_stream/state_container/manifest.yml
> +        show_user: false
+1

2022-01-28 13:23 UTC, tetianakravchenko commented
@ChrsMark done https://github.com/elastic/integrations/pull/2613/commits/f5bb0085e861d1b7739b131a824ddfb0938a4838, also updated the screenshot in description

2022-01-31 08:09 UTC, MichaelKatsoulis approved these changes

2022-02-02 11:24 UTC, ChrsMark commented
Thank you @tetianakravchenko ! It looks good now but there are some conflicts to be resolved.

2022-02-02 11:40 UTC, ChrsMark approved these changes

2022-02-02 15:36 UTC, merged