Add gcp.dns integration
elastic/integrations pull request #2624
Opened 2022-02-01 08:03 UTC by LiamSennitt

## What does this PR do?

Add gcp.dns integration

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2022-02-01 08:11 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2624/detail/PR-2624/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2624/detail/PR-2624/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2624/detail/PR-2624/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2624/detail/PR-2624/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-02-01T07:53:40.305Z&rangeTo=2022-02-01T08:13:40.305Z&transactionName=Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=edf4f7be07a0dec81ccf4bd48b125eaa&transactionId=3dee70afb982a496)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats



* Reason: `The PR is not allowed to run in the CI yet`


* Start Time: 2022-02-01T08:03:40.305+0000


* Duration: 7 min 17 sec


* Commit: b6cdbc2104b65bcc644fdddaff4c9aa08c0a88e2




</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->











### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2624/detail/PR-2624/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-2624/runs/1/steps/109/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>


## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-02-01 19:05 UTC, andrewkroh commented
/test

2022-02-01 19:05 UTC, elasticmachine commented
Pinging @elastic/integrations (Team:Integrations)

2022-02-01 19:14 UTC, andrewkroh requested changes

2022-02-01 19:14 UTC, andrewkroh commented on packages/gcp/data_stream/dns/elasticsearch/ingest_pipeline/default.yml
> +  - set:
This can be removed. There is a final_pipeline that adds this field to all events.

2022-02-01 19:14 UTC, andrewkroh commented on packages/gcp/data_stream/dns/_dev/test/pipeline/test-common-config.yml
> +  event.ingested: ".*"
This can be removed after event.ingested is removed from your pipeline.

2022-02-01 19:14 UTC, andrewkroh commented on packages/gcp/data_stream/dns/elasticsearch/ingest_pipeline/default.yml
> +      ignore_missing: true
`ignore_missing` becomes redundant when used with `ignore_failure`.

2022-02-01 19:14 UTC, andrewkroh commented on packages/gcp/data_stream/dns/elasticsearch/ingest_pipeline/default.yml
> +      value: "{{gcp.dns.destination_ip}}"
I prefer using `set: {copy_from: gcp.dns.destination_i, field: destination.address, ignore_failure: true}` rather because it avoid needing to evaluate a template.

2022-02-01 19:14 UTC, andrewkroh commented on packages/gcp/data_stream/dns/elasticsearch/ingest_pipeline/default.yml
> +  - set:
Use a `convert: {type: ip}` processor to ensure the value is a valid IP address. This prevents an index-time error if the data is bad.

2022-02-01 19:14 UTC, andrewkroh commented on packages/gcp/data_stream/dns/elasticsearch/ingest_pipeline/default.yml
> +      lang: javascript
A [gsub](https://www.elastic.co/guide/en/elasticsearch/reference/current/gsub-processor.html) processor can be used.

2022-02-01 19:14 UTC, andrewkroh commented on packages/gcp/data_stream/dns/elasticsearch/ingest_pipeline/default.yml
> +      value: "{{gcp.dns.query_type}}"
Use `set` with `copy_from`.

2022-02-01 19:14 UTC, andrewkroh commented on packages/gcp/data_stream/dns/elasticsearch/ingest_pipeline/default.yml
> +      lang: painless
Please add a descriptive `tag` and a `description` to script processors.

2022-02-02 08:32 UTC, LiamSennitt commented on packages/gcp/data_stream/dns/elasticsearch/ingest_pipeline/default.yml
> +  - set:
I'll update, by the way this was taken from the gcp audit [ingest_pipeline/default.yml](https://github.com/elastic/integrations/blob/main/packages/gcp/data_stream/audit/elasticsearch/ingest_pipeline/default.yml#L5-L7)

2022-02-02 18:16 UTC, andrewkroh commented
/test

2022-02-02 23:37 UTC, andrewkroh commented
/test

2022-02-03 15:12 UTC, andrewkroh commented
> [2022-02-02T23:59:55.323Z] Error: error running package asset tests: could not complete test run: can't install the package: can't install the package: could not install package; API status code = 500; response body = {"statusCode":500,"error":"Internal Server Error","message":"exception: [exception] Reason: java.lang.IllegalArgumentException: script_lang not supported [javascript]"}

That script will need ported over to Painless.

2022-02-03 17:01 UTC, andrewkroh commented
/test

2022-02-03 17:50 UTC, andrewkroh commented
CI errors:

```
one or more errors found in document: [0] field "dns.response_code" is undefined
[1] field "dns.answers" is undefined
[2] field "dns.question.type" is undefined
[3] field "dns.question.name" is undefined
[4] field "dns.resolved_ip" is undefined
[5] parsing field value failed: field "event.dataset"'s value "gcp.dns" does not match the declared constant_keyword value "gcp.audit"
[6] field "network.transport" is undefined
[7] field "service.type" is undefined
[8] field "fileset.name" is undefined
[9] field "source.address" is undefined
```

2022-02-03 18:26 UTC, andrewkroh commented
/test

2022-02-03 18:46 UTC, LiamSennitt commented
Sorry @andrewkroh, forgot to re-run `elastic-package format`.

2022-02-03 20:30 UTC, andrewkroh commented
/test

2022-02-04 21:31 UTC, andrewkroh commented
/test

2022-02-07 14:49 UTC, LiamSennitt commented
@andrewkroh are you able to re-run the tests?

2022-02-07 14:54 UTC, andrewkroh commented
/test

2022-02-07 17:38 UTC, LiamSennitt commented
@andrewkroh with the CI error, should I be updating [elastic-package/blob/main/internal/fields/_static/allowed_geo_ips.txt](https://github.com/elastic/elastic-package/blob/main/internal/fields/_static/allowed_geo_ips.txt) or changing my tests to only include those IP's?

2022-02-07 17:53 UTC, andrewkroh commented
You should change your test data to use those IPs or private IPs.

2022-02-07 19:59 UTC, andrewkroh commented
/test

2022-02-07 22:18 UTC, andrewkroh commented
/test

2022-02-08 07:53 UTC, LiamSennitt commented
@andrewkroh this should all be good now, thank you for being patient 😄

2022-02-08 15:18 UTC, andrewkroh commented
/test

2022-02-08 15:52 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2022-02-09 07:09 UTC, efd6 approved these changes

2022-02-11 22:26 UTC, merged