Add use cases for parsing audit events logs and update sample events …
elastic/integrations pull request #2690
Opened 2022-02-14 10:29 UTC by djordje-adzemovic-devtech

…and docs

## What does this PR do?

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2022-02-14 10:36 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2690/detail/PR-2690/2//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2690/detail/PR-2690/2//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2690/detail/PR-2690/2//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2690/detail/PR-2690/2//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-02-14T10:21:08.452Z&rangeTo=2022-02-14T10:41:08.452Z&transactionName=Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=391f87516960b9e0c607d024d69ed639&transactionId=ddf6e8f91d18de31)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-02-14T10:31:08.452+0000


* Duration: 5 min 50 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->











### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2690/detail/PR-2690/2//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-2690/runs/2/steps/109/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>


## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-02-14 11:01 UTC, marc-gr requested changes
Nice additions! Just as a note aside of the comments, I think the changes done in README.md need to be done instead to the `_dev/build/...` README file.

2022-02-14 11:01 UTC, marc-gr commented on packages/mimecast/docs/README.md
> +#### Log Types
If you prefer to separate the explanations from the samples, would be nice to add a link on each log explanation to its sample.

2022-02-14 12:18 UTC, djordje-adzemovic-devtech commented on packages/mimecast/data_stream/audit_events/elasticsearch/ingest_pipeline/default.yml
> +      if: 'ctx?.event?.action=="logon-authentication-failed" && (ctx?.mimecast?.email?.metadata != "")'
Yes, it is on purpose, although I am not sure if it necessary, I add it just in case. Because we have multiple eventInfo format for logon-authentication-failed, I just want to be sure that only in case if metadata exists this dissect is executed. For now, it works as expected if I remove it, so I will remove it.

2022-02-14 12:20 UTC, djordje-adzemovic-devtech commented on packages/mimecast/docs/README.md
> +Full guide how to configure, deploy and use this integration find [here]()
I do not have this link, this will be removed. Good spot.

2022-02-14 14:32 UTC, marc-gr commented on packages/mimecast/data_stream/audit_events/elasticsearch/ingest_pipeline/default.yml
> +  - dissect:
Do you think using the KV processor could help here? https://www.elastic.co/guide/en/elasticsearch/reference/7.16/kv-processor.html. You can split by `", "` instead of `,` and use `:` as the kv separator.

2022-02-17 14:35 UTC, djordje-adzemovic-devtech commented on packages/mimecast/data_stream/audit_events/_dev/test/pipeline/test-audit-events.log-expected.json
> +                "eventInfo": "Failed authentication for johndoe@example.com \u003cJohn Doe\u003e, Date: 2022-01-11, Time: 21:48:01 GMT, IP: 67.43.156.15, Application: POP-POP2, Method: Cloud, Reason:
mimecast.application_method is on the list to be removed at he end of the the pipeline. Idk if it is useful information or not, I can potentially remove from the list of properties to be deleted and update expected jsons.

2022-02-22 09:52 UTC, marc-gr commented on packages/mimecast/data_stream/audit_events/elasticsearch/ingest_pipeline/default.yml
> +      pattern: "%{mimecast.info}, %{mimecast.rest_of_event_info}"
```suggestion
      pattern: "%{mimecast.info}, %{mimecast.rest_of_event_info}"
      if: 'ctx.mimecast?.info == null'
```

Without this condition this dissect will get executed for every event, so we either add it or if this works, we could remove all the previous, more specific dissect processors.

2022-02-22 09:52 UTC, marc-gr commented on packages/mimecast/data_stream/audit_events/elasticsearch/ingest_pipeline/default.yml
> +      pattern: "%{mimecast.info}, %{mimecast.type}, %{mimecast.rest_of_event_info}"
Just a question: could this `mimecast.type` be set as the `event.type`?

2022-02-22 09:52 UTC, marc-gr commented on packages/mimecast/data_stream/audit_events/elasticsearch/ingest_pipeline/default.yml
> +      if: 'ctx?.event?.action == "threat-intel-feed-download" || ctx?.event?.action == "existing-archive-task-changed" || ctx?.event?.action == "case-action" || ctx?.event?.action == "user-logged-on"
Do we need this conditions? I feel like just having the kv processor should work, since it seems if `mimecast.rest_of_event_info` is missing it will just be a no op, and I can't think of a situation were we have it and do not want to parse it.
```suggestion
```

2022-02-22 09:52 UTC, marc-gr commented on packages/mimecast/data_stream/audit_events/_dev/test/pipeline/test-audit-events.log-expected.json
> +                "eventInfo": "Intermediate authentication for johndoe@example.com \u003cJohn Doe\u003e, Date: 2021-10-11, Time: 18:17:26 BST, IP: 67.43.156.15, Application: Administration Console, Me
```suggestion
                "eventInfo": "Intermediate authentication for johndoe@example.com \u003cJohn Doe\u003e, Date: 2021-10-11, Time: 18:17:26 BST, IP: 67.43.156.15, Application: Administration Console, Method: Office 365, 2FA: TOTP",
```

Could we also keep the 2FA field? Just adding the mapping and not discarding it in the pipeline.

2022-02-22 10:48 UTC, djordje-adzemovic-devtech commented on packages/mimecast/data_stream/audit_events/elasticsearch/ingest_pipeline/default.yml
> +      pattern: "%{mimecast.info}, %{mimecast.type}, %{mimecast.rest_of_event_info}"
From documentation about ECS field reference:

Important: The field value must be one of the following:

access, admin, allowed, change, connection, creation, deletion, denied, end, error, group, indicator, info, installation, protocol, start, user

mimecast.type is not any of this values, I will not change anything here. Besides that, mimecast.type is remove at he end of the pipeline.

2022-02-22 10:56 UTC, djordje-adzemovic-devtech commented on packages/mimecast/data_stream/audit_events/elasticsearch/ingest_pipeline/default.yml
> +      pattern: "%{mimecast.info}, %{mimecast.rest_of_event_info}"
condition added

2022-02-22 10:56 UTC, djordje-adzemovic-devtech commented on packages/mimecast/data_stream/audit_events/elasticsearch/ingest_pipeline/default.yml
> +      if: 'ctx?.event?.action == "threat-intel-feed-download" || ctx?.event?.action == "existing-archive-task-changed" || ctx?.event?.action == "case-action" || ctx?.event?.action == "user-logged-on"
you are right. if condition removed.

2022-02-22 10:58 UTC, djordje-adzemovic-devtech commented on packages/mimecast/data_stream/audit_events/_dev/test/pipeline/test-audit-events.log-expected.json
> +                "eventInfo": "Intermediate authentication for johndoe@example.com \u003cJohn Doe\u003e, Date: 2021-10-11, Time: 18:17:26 BST, IP: 67.43.156.15, Application: Administration Console, Me
Yes, changes implemented. 2FA will remain in json as  a new property.

2022-02-22 13:14 UTC, marc-gr commented on packages/mimecast/data_stream/audit_events/elasticsearch/ingest_pipeline/default.yml
> +#      if: 'ctx?.event?.action == "threat-intel-feed-download" || ctx?.event?.action == "existing-archive-task-changed" || ctx?.event?.action == "case-action" || ctx?.event?.action == "user-logged-on
```suggestion
```

2022-02-22 14:51 UTC, marc-gr commented
/test

2022-02-22 15:01 UTC, andrewkroh commented
I'm not sure if you want to do this here, but the the ECS version used in the package should be changed from 1.12.0 to 8.0.0.

It's in the ingest pipeline and this [file](https://github.com/elastic/integrations/blob/ff0c953dff32eed0067e53f4723390203994e1f4/packages/mimecast/_dev/build/build.yml#L3).

2022-02-22 15:02 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2022-02-22 15:09 UTC, andrewkroh commented on packages/mimecast/_dev/build/build.yml
> +    reference: git@8.0.0
Please point this at the `8.0` branch. https://github.com/elastic/ecs/tree/8.0

Then in the ingest pipelines (e.g. https://github.com/elastic/integrations/blob/ff0c953dff32eed0067e53f4723390203994e1f4/packages/mimecast/data_stream/audit_events/elasticsearch/ingest_pipeline/default.yml#L7) find and replace the 1.12.0 to 8.0.0. After making this change you should re-run the `elastic-package test pipeline -g` to update any generated files.

2022-02-22 15:47 UTC, marc-gr commented
/test

2022-02-22 15:55 UTC, marc-gr approved these changes

2022-02-23 08:27 UTC, marc-gr commented
/test

2022-02-23 08:58 UTC, marc-gr approved these changes

2022-02-23 09:16 UTC, marc-gr commented
/test

2022-02-23 09:17 UTC, P1llus approved these changes
LGTM. I only reviewed the generation of the Readme + the 8.0 ecs changes and generation of test data.

2022-02-23 09:59 UTC, merged