[GCP] Add firestore data_stream
elastic/integrations pull request #2704
Opened 2022-02-16 11:19 UTC by gpop63

## What does this PR do?

Adds firestore datastream.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2022-02-16 11:36 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2704/detail/PR-2704/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2704/detail/PR-2704/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2704/detail/PR-2704/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2704/detail/PR-2704/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_2704.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-02-16T11:10:03.086Z&rangeTo=2022-02-16T11:30:03.086Z&transactionName=Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=4bcf1e839aef4d9a2c919dc55494dde4&transactionId=16e5d26333ab738b)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-02-16T11:20:03.086+0000


* Duration: 16 min 21 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->











### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2704/detail/PR-2704/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Check integration: gcp`
<ul>
<li>Took 0 min 1 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-2704/runs/1/steps/718/log/?start=0">here</a></li>
<li>Description: <code>../../build/elastic-package check -v</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-2704/runs/1/steps/754/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>


## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-03-17 10:38 UTC, endorama requested changes
Please ensure `elastic-package check` does not error. I added some minor changes but overall looks good to me and we can merge this as soon as CI is green

2022-03-17 10:38 UTC, endorama commented on packages/gcp/data_stream/firestore/manifest.yml
> +        default: 10s
Instead of fixing the period in the test case, let's change the default here, as `10s` is wrong and triggers an error in metricbeat.

```suggestion
        default: 60s
```

2022-03-17 10:38 UTC, endorama commented on packages/gcp/data_stream/firestore/_dev/deploy/tf/main.tf
> +  collection  = var.collection_name
```suggestion
  collection  = "${var.collection_name}-${var.TEST_RUN_ID}"
```

2022-03-17 10:38 UTC, endorama commented on packages/gcp/data_stream/firestore/_dev/deploy/tf/main.tf
> +  default = "elastic-obs-integrations-dev"
```suggestion
```

2022-03-17 10:38 UTC, endorama commented on packages/gcp/data_stream/firestore/_dev/deploy/tf/main.tf
> +  default = "elastic-collection1"
```suggestion
  default = "integration-test-collection"
```

2022-03-17 10:38 UTC, endorama commented on packages/gcp/data_stream/firestore/_dev/test/system/test-default-config.yml
> +  period: 60s
```suggestion
```

See comment in `packages/gcp/data_stream/firestore/manifest.yml`

2022-03-18 08:34 UTC, mtojek reviewed
If you need any help from me, let me know, but please resolve first all conflicts :)

2022-03-22 08:33 UTC, endorama commented on packages/gcp/data_stream/firestore/_dev/deploy/tf/main.tf
> +variable "project_id" {
This has been changed and should be:
```suggestion
variable "gcp_project_id" {
```

2022-03-22 08:33 UTC, endorama commented on packages/gcp/data_stream/firestore/_dev/deploy/tf/main.tf
> +  project = var.project_id
Follows https://github.com/elastic/integrations/pull/2704/files#r831894335

```suggestion
  project = var.gcp_project_id
```

2022-03-22 08:34 UTC, endorama commented on packages/gcp/data_stream/firestore/_dev/deploy/tf/main.tf
> +  project     = var.project_id
This line can be omitted, using the globally define project in the `provider` resource

```suggestion
```

2022-03-22 09:31 UTC, endorama commented on packages/gcp/data_stream/firestore/_dev/deploy/tf/main.tf
> +variable "project_id" {
I noticed this change was not included in https://github.com/elastic/integrations/pull/2704/commits/081c2ce70dfd0a67e2e8eeb79c3dfe3dc8eab89e, is that done on purpose?

2022-03-22 09:32 UTC, endorama commented on packages/gcp/data_stream/firestore/_dev/deploy/tf/main.tf
> +  project     = var.project_id
fixed in https://github.com/elastic/integrations/pull/2704/commits/081c2ce70dfd0a67e2e8eeb79c3dfe3dc8eab89e

2022-03-23 15:06 UTC, gpop63 commented
/test

2022-03-23 15:57 UTC, gpop63 commented
/test

2022-03-30 14:28 UTC, merged