Add new fields to sonicwall pipeline
elastic/integrations pull request #2729
Opened 2022-02-22 18:37 UTC by jhaugh0

## What does this PR do?

Adds new fields to be parsed from sonicwall logs
## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally
Example logs to test against:

`10.0.0.1  id=firewall sn=123456789 time="2022-02-22 18:24:30 UTC" fw=10.0.0.2 pri=6 c=262144 gcat=6 m=98 msg="Connection Opened" src=10.0.0.3:52379:X0 natSrc=10.0.0.2:48245 dst=8.8.8.8:443:X1 natDst=8.8.8.8:443 usr="Unknown (SSO failed)" proto=tcp/https sent=52 app=49177 appName='General HTTPS' n=123456789 fw_action="NA" dpi=0`

`10.0.0.1  id=firewall sn=123456789 time="2022-02-22 18:29:37 UTC" fw=10.0.0.2 pri=6 c=1024 gcat=2 m=97 msg="Web site hit" srcMac=12:34:56:78:90:ab src=10.0.0.3:64828:X0 srcZone=Trusted natSrc=10.0.0.2:47621 dstMac=ab:09:87:65:43:21 dst=8.8.8.8:443:X1 dstZone=Untrusted natDst=8.8.8.8:443 usr="Unknown (SSO failed)" proto=tcp/https sent=3523 rcvd=14226 app=7927 dstname=chat-pa.clients6.google.com arg=/ code=29 Category="Search Engines and Portals" note="Policy: cfsZonePolicy0, Info: 6148 " n=123456789 fw_action="NA" dpi=1`

`10.0.0.1  id=firewall sn=2CB8ED17E180 time="2022-02-22 18:34:21 UTC" fw=10.0.0.2 pri=6 c=1024 gcat=2 m=97 msg="Web site hit" srcMac=12:34:56:78:90:ab src=10.0.0.3:49217:X0 srcZone=Trusted natSrc=10.0.0.2:53466 dstMac=ab:09:87:65:43:21 dst=8.8.8.8:443:X1 dstZone=Untrusted natDst=8.8.8.8:443 usr="Unknown (SSO failed)" proto=tcp/https sent=2079 rcvd=6642 app=7927 dstname=seg.ad.gt arg=/ code=15 Category="Business and Economy" note="Policy: cfsZonePolicy0, Info: 6148 " n=123456789 fw_action="NA" dpi=1`

## Related issues

-

## Screenshots

2022-02-22 18:42 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2729/detail/PR-2729/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2729/detail/PR-2729/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2729/detail/PR-2729/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2729/detail/PR-2729/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-02-22T18:27:23.757Z&rangeTo=2022-02-22T18:47:23.757Z&transactionName=Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=70dbb060b80c6e70b5b939adf3a557e6&transactionId=72fd8a0ecee6af46)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-02-22T18:37:23.757+0000


* Duration: 5 min 3 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2729/detail/PR-2729/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-2729/runs/1/steps/109/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-02-24 00:58 UTC, andrewkroh commented
/test

2022-02-24 01:02 UTC, andrewkroh commented
The test cases should be added in https://github.com/elastic/integrations/tree/main/packages/sonicwall/data_stream/firewall/_dev/test/pipeline. See https://github.com/elastic/elastic-package/blob/main/docs/howto/pipeline_testing.md for info on how to update the "expected" files.

2022-02-24 18:28 UTC, jhaugh0 commented
> The test cases should be added in https://github.com/elastic/integrations/tree/main/packages/sonicwall/data_stream/firewall/_dev/test/pipeline. See https://github.com/elastic/elastic-package/blob/main/docs/howto/pipeline_testing.md for info on how to update the "expected" files.

This is updated now

2022-02-24 19:42 UTC, andrewkroh commented
/test

2022-02-24 20:11 UTC, andrewkroh requested changes

2022-02-24 20:11 UTC, andrewkroh commented on packages/sonicwall/data_stream/firewall/_dev/test/pipeline/test-general.log-expected.json
> +        },
These 3 sample logs should go into a file like:

```
diff --git a/packages/sonicwall/data_stream/firewall/_dev/test/pipeline/test-issue2729.log b/packages/sonicwall/data_stream/firewall/_dev/test/pipeline/test-issue2729.log
new file mode 100644
index 000000000..0a2758170
--- /dev/null
+++ b/packages/sonicwall/data_stream/firewall/_dev/test/pipeline/test-issue2729.log
@@ -0,0 +1,3 @@
+10.0.0.1 id=firewall sn=123456789 time="2022-02-22 18:24:30 UTC" fw=10.0.0.2 pri=6 c=262144 gcat=6 m=98 msg="Connection Opened" src=10.0.0.3:52379:X0 natSrc=10.0.0.2:48245 dst=8.8.8.8:443:X1 natDst=8.8.8.8:443 usr="Unknown (SSO failed)" proto=tcp/https sent=52 app=49177 appName='General HTTPS' n=123456789 fw_action="NA" dpi=0
+10.0.0.1 id=firewall sn=123456789 time="2022-02-22 18:29:37 UTC" fw=10.0.0.2 pri=6 c=1024 gcat=2 m=97 msg="Web site hit" srcMac=12:34:56:78:90:ab src=10.0.0.3:64828:X0 srcZone=Trusted natSrc=10.0.0.2:47621 dstMac=ab:09:87:65:43:21 dst=8.8.8.8:443:X1 dstZone=Untrusted natDst=8.8.8.8:443 usr="Unknown (SSO failed)" proto=tcp/https sent=3523 rcvd=14226 app=7927 dstname=chat-pa.clients6.google.com arg=/ code=29 Category="Search Engines and Portals" note="Policy: cfsZonePolicy0, Info: 6148 " n=123456789 fw_action="NA" dpi=1
+10.0.0.1 id=firewall sn=2CB8ED17E180 time="2022-02-22 18:34:21 UTC" fw=10.0.0.2 pri=6 c=1024 gcat=2 m=97 msg="Web site hit" srcMac=12:34:56:78:90:ab src=10.0.0.3:49217:X0 srcZone=Trusted natSrc=10.0.0.2:53466 dstMac=ab:09:87:65:43:21 dst=8.8.8.8:443:X1 dstZone=Untrusted natDst=8.8.8.8:443 usr="Unknown (SSO failed)" proto=tcp/https sent=2079 rcvd=6642 app=7927 dstname=seg.ad.gt arg=/ code=15 Category="Business and Economy" note="Policy: cfsZonePolicy0, Info: 6148 " n=123456789 fw_action="NA" dpi=1
```

then you would use the tooling (`elastic-package test pipeline -g`) to generate the "-expected.json" file.

2022-02-24 20:11 UTC, andrewkroh commented on packages/sonicwall/data_stream/firewall/fields/fields.yml
> +      - name: pipeline
This file is malformed. Looks like indentation around this location. Please use [`elastic-package check`](https://github.com/elastic/elastic-package/#elastic-package-check) to check for problems.

2022-02-24 20:11 UTC, andrewkroh commented on packages/sonicwall/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
> +        "SONICWALL_TIME" : "%{SONICWALL_TIME_WITH_TIMEZONE}?%{SONICWALL_TIME_NO_TIMEZONE}?"
Remove the spaces between the key and the colon.

2022-02-24 20:11 UTC, andrewkroh commented on packages/sonicwall/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
> +   - grok:
Indentation is off. Please test the pipeline with [`elastic-package test pipeline`](https://github.com/elastic/elastic-package/#elastic-package-test). The test will fail if the pipeline is invalid.

2022-02-24 20:11 UTC, andrewkroh commented on packages/sonicwall/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
> +      value: "{{_ingest_timestamp}}
Missing a closing quote.

2022-02-28 21:12 UTC, jhaugh0 commented on packages/sonicwall/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
> +      value: "{{_ingest_timestamp}}
fixed

2022-02-28 21:13 UTC, jhaugh0 commented on packages/sonicwall/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
> +   - grok:
fixed

I'm having it fail on test-generated.log, but after a look through those logs I do not believe they are properly formatted logs from a sonicwall. Not sure if too much identifying information was removed, or just improperly removed/replaced

2022-02-28 21:14 UTC, jhaugh0 commented on packages/sonicwall/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
> +        "SONICWALL_TIME" : "%{SONICWALL_TIME_WITH_TIMEZONE}?%{SONICWALL_TIME_NO_TIMEZONE}?"
fixed

2022-02-28 21:14 UTC, jhaugh0 commented on packages/sonicwall/data_stream/firewall/fields/fields.yml
> +      - name: pipeline
fixed. Indented too far

2022-03-04 01:14 UTC, efd6 commented
/test

2022-03-09 03:19 UTC, efd6 commented on packages/sonicwall/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
> +        ]
I'd suggest that you simplify this so that you just collect the timestamp and leading IP address with grok and leave the rest of the line to be processed later by grabbing it as greedy data.

```
---
description: Pipeline for Sonicwall-FW

processors:
  - set:
      field: event.module
      value: "sonicwall"
  - set:
      field: ecs.version
      value: '8.0.0'

  - rename:
      field: message
      target_field: event.original
      ignore_missing: true
  - grok:
      description: "Pull header information"
      field: event.original
      patterns:
        - "^%{DATA}%{TIMESTAMP:event.created} %{IP:observer.ip:ip} %{GREEDYDATA:message}$"
        - "^%{DATA}%{IP:observer.ip:ip} %{GREEDYDATA:message}$"
      pattern_definitions:
        TIMESTAMP: "%{MONTH} +%{MONTHDAY} %{TIME}"

# split Sonicwall fields
  - kv:
      field: message
      field_split: " (?=[a-zA-Z0-9_]+=)"
      value_split: "="
      prefix: "sonicwall."
      ignore_missing: true
      ignore_failure: false
      trim_value: "\""
```

This will give you the observer IP and the creation time if it exists, and it will then leave you with the remainder of the line to parse.

From looking at the log lines, these are all key-value pairs with field separated by space and key/val separated by `=`, so the kv processor will happily consume those (with a little help since some of the values have spaces; the `field_split` regex handles that). With that all of the grok processors below can go away.

This will leave you finally with event that look like this
```
        {
            "ecs": {
                "version": "8.0.0"
            },
            "event": {
                "created": "Jan  3 13:45:50",
                "module": "sonicwall",
                "original": "Jan  3 13:45:50 192.168.5.1 id=firewall sn=000SERIAL time=\"2007-01-03 14:48:21\" fw=1.128.3.4 pri=6 c=262144 m=98 msg=\"Connection Opened\" n=23427 src=192.168.6.10:28503:WAN dst=192.168.5.10:53:LAN proto=tcp/dns"
            },
            "message": "id=firewall sn=000SERIAL time=\"2007-01-03 14:48:21\" fw=1.128.3.4 pri=6 c=262144 m=98 msg=\"Connection Opened\" n=23427 src=192.168.6.10:28503:WAN dst=192.168.5.10:53:LAN proto=tcp/dns",
            "observer": {
                "ip": "192.168.5.1"
            },
            "sonicwall": {
                "c": "262144",
                "dst": "192.168.5.10:53:LAN",
                "fw": "1.128.3.4",
                "id": "firewall",
                "m": "98",
                "msg": "Connection Opened",
                "n": "23427",
                "pri": "6",
                "proto": "tcp/dns",
                "sn": "000SERIAL",
                "src": "192.168.6.10:28503:WAN",
                "time": "2007-01-03 14:48:21"
            },
            "tags": [
                "preserve_original_event"
            ]
        },
        {
            "ecs": {
                "version": "8.0.0"
            },
            "event": {
                "module": "sonicwall",
                "original": "10.0.0.1 id=firewall sn=123456789 time=\"2022-02-22 18:24:30 UTC\" fw=10.0.0.2 pri=6 c=262144 gcat=6 m=98 msg=\"Connection Opened\" src=10.0.0.3:52379:X0 natSrc=10.0.0.2:48245 dst=216.160.83.61:443:X1 natDst=216.160.83.61:443 usr=\"Unknown (SSO failed)\" proto=tcp/https sent=52 app=49177 appName='General HTTPS' n=123456789 fw_action=\"NA\" dpi=0"
            },
            "message": "id=firewall sn=123456789 time=\"2022-02-22 18:24:30 UTC\" fw=10.0.0.2 pri=6 c=262144 gcat=6 m=98 msg=\"Connection Opened\" src=10.0.0.3:52379:X0 natSrc=10.0.0.2:48245 dst=216.160.83.61:443:X1 natDst=216.160.83.61:443 usr=\"Unknown (SSO failed)\" proto=tcp/https sent=52 app=49177 appName='General HTTPS' n=123456789 fw_action=\"NA\" dpi=0",
            "observer": {
                "ip": "10.0.0.1"
            },
            "sonicwall": {
                "app": "49177",
                "appName": "'General HTTPS'",
                "c": "262144",
                "dpi": "0",
                "dst": "216.160.83.61:443:X1",
                "fw": "10.0.0.2",
                "fw_action": "NA",
                "gcat": "6",
                "id": "firewall",
                "m": "98",
                "msg": "Connection Opened",
                "n": "123456789",
                "natDst": "216.160.83.61:443",
                "natSrc": "10.0.0.2:48245",
                "pri": "6",
                "proto": "tcp/https",
                "sent": "52",
                "sn": "123456789",
                "src": "10.0.0.3:52379:X0",
                "time": "2022-02-22 18:24:30 UTC",
                "usr": "Unknown (SSO failed)"
            },
            "tags": [
                "preserve_original_event"
            ]
        },
```
So all that is now needed is to appropriately [`rename`](https://www.elastic.co/guide/en/elasticsearch/reference/master/rename-processor.html) the fields mapping them to the right place in the ECS and giving them the right types with [`convert`](https://www.elastic.co/guide/en/elasticsearch/reference/master/convert-processor.html) processors, and some cases [`dissect`](https://www.elastic.co/guide/en/elasticsearch/reference/master/dissect-processor.html) (for IPs, which can be enriched through [`geoip`](https://www.elastic.co/guide/en/elasticsearch/reference/master/geoip-processor.html) and [`community_id`](https://www.elastic.co/guide/en/elasticsearch/reference/master/community-id-processor.html)) and [`date`](https://www.elastic.co/guide/en/elasticsearch/reference/master/date-processor.html).

There is a caveat to this, this does not work with the generated log. I suspect that some of the lines there are not valid, so in the first instance delete that file so at least you can have something that works. If there are valid lines in that sample set, they can be added back later, adjusting the processors as needed.

Also, you can delete the script processors in data_stream/firewall/agent/stream/stream.yml.hbs, data_stream/firewall/agent/stream/tcp.yml.hbs and data_stream/firewall/agent/stream/udp.yml.hbs since we are now doing the work here.

2022-03-09 03:26 UTC, efd6 commented on packages/sonicwall/data_stream/firewall/fields/fields.yml
> +  type: date
Sorry, forgot to mention. This needs to have its final newline added in. Running `elastic-package format` will do this for you.

2022-03-09 15:36 UTC, jhaugh0 commented on packages/sonicwall/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
> +        ]
Just extracting the time/IP first is a good idea, less to break on. It needs to be reworked a bit from what you posted though as it seems like different firmware versions have different header formats. Also using rsyslog to write logs to disk first, which I do, by default adds the prepends the sender IP address, which could be different from the IP in the log if they're on different subnets. For example:
`10.0.0.1 id=firewall sn=123456789 time="2022-02-22 18:29:37 UTC" fw=10.0.0.2`
Where 10.0.0.1 is the IP on the subnet as the rsyslog host, and 10.0.02 is the DMZ IP of the sonicwall. I recognize I might be a bit more of a rare case for that use though. What are your thoughts on that? 

It's been a bit since I initially wrote up this version, but I think I initially tried using KV and found some logs that broke it. I'm going to dig in some more and see if I can pull those up, or maybe it was nothing.

2022-03-15 00:54 UTC, efd6 reviewed
It would be helpful for future maintenance if logically related sections were split from each other with vertical whitespace and with comment annotation, but this is looking good.

2022-03-15 00:54 UTC, efd6 commented on packages/sonicwall/changelog.yml
> +- version: "1.0"
```suggestion
- version: "0.8.0"
```

2022-03-15 00:54 UTC, efd6 commented on packages/sonicwall/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
> -
Please revert this deletion.

2022-03-15 00:54 UTC, efd6 commented on packages/sonicwall/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
> +          %{GREEDYDATA:message}$
I don't think the multi-line string improves clarity here and is arguably more fragile to un-noticed damage in the future.

```suggestion
      patterns:
        - "^%{DATA}%{TIMESTAMP:event.created} %{IP:observer.ip:ip} %{GREEDYDATA:message}$"
        - "^%{DATA}%{IP:observer.ip:ip} %{GREEDYDATA:message}$"
```

2022-03-15 13:49 UTC, jhaugh0 commented on packages/sonicwall/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
> +          %{GREEDYDATA:message}$
Missed that, I just used a json > yaml converter from doing testing in kibana. Looks like that added that.

Just had to add an extra '+' to keep the message field from starting with a whitespace and breaking the kv proccessor

2022-05-17 11:33 UTC, adriansr commented
Hi @jhaugh0 

Thanks for your contribution.

After discussing this we've decided it's better to create a brand new integration and deprecate the existing one. I've created a new integration for SonicWall (#3365). Uses some of your ideas and logs, will give you proper credit.

2022-05-19 10:47 UTC, jamiehynds commented
Closing as per @adriansr comment above. Thanks again @jhaugh0!

2022-05-19 10:47 UTC, closed without merging