OSQuery POC package ported from package-storage
elastic/integrations pull request #273
Opened 2020-09-17 14:40 UTC by aleksmaus

## What does this PR do?

OSQuery package ported from POC PR https://github.com/elastic/package-storage/pull/98

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md#tips-for-building-integrations) and this pull request is aligned with them.
- [x] I have verified that all datasets collect metrics or logs.

The later requires osquerybeat that is currently not a part of the agent distribution by default.

## Screenshots
<img width="1310" alt="Screen Shot 2020-09-17 at 10 30 46 AM" src="https://user-images.githubusercontent.com/872351/93486304-0a6da580-f8d2-11ea-8c9a-523a98ca1228.png">

This doesn't need to be merged right away, the development is still pending on product input and the shape of the package is expected to change.

2020-09-17 14:43 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fintegrations%2FPR-273/detail/PR-273/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fintegrations%2FPR-273/detail/PR-273/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fintegrations%2FPR-273/detail/PR-273/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fintegrations%2FPR-273/detail/PR-273/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_273.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats

* Build Cause: `[Pull request #273 opened]`

* Start Time: 2020-09-17T14:40:15.286+0000

* Duration: 4 min 36 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY-->


### Steps errors

  <details><summary>Expand to view the steps failures</summary>
  <p>
  
  * **Name**: `Checks and builds integration sources`
    * Description: mage -debug check
    
    * Duration: 0 min 21 sec
    
    * Start Time: 2020-09-17T14:43:29.162+0000
    
    * [log](https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/integrations/pipelines/PR-273/runs/1/steps/114/log)
    
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2020-09-17T14:43:31.645Z] go: downloading github.com/imdario/mergo v0.3.9
[2020-09-17T14:43:31.645Z] go: downloading golang.org/x/sys v0.0.0-20200817155316-9781c653f443
[2020-09-17T14:43:31.645Z] go: downloading golang.org/x/net v0.0.0-20200822124328-c89045814202
[2020-09-17T14:43:31.645Z] go: downloading github.com/emirpasic/gods v1.12.0
[2020-09-17T14:43:31.645Z] go: downloading github.com/rakyll/statik v0.1.7
[2020-09-17T14:43:31.645Z] go: downloading github.com/mitchellh/go-homedir v1.1.0
[2020-09-17T14:43:31.906Z] go: downloading github.com/xeipuuv/gojsonpointer v0.0.0-20180127040702-4e3ac2762d5f
[2020-09-17T14:43:31.906Z] go: downloading github.com/jbenet/go-context v0.0.0-20150711004518-d14ea06fba99
[2020-09-17T14:43:31.906Z] go: downloading github.com/mattn/go-isatty v0.0.8
[2020-09-17T14:43:31.906Z] go: downloading github.com/go-git/gcfg v1.5.0
[2020-09-17T14:43:31.906Z] go: downloading github.com/sergi/go-diff v1.1.0
[2020-09-17T14:43:31.906Z] go: downloading github.com/kevinburke/ssh_config v0.0.0-20190725054713-01f96b0aa0cd
[2020-09-17T14:43:31.906Z] go: downloading github.com/xanzy/ssh-agent v0.2.1
[2020-09-17T14:43:31.906Z] go: downloading gopkg.in/warnings.v0 v0.1.2
[2020-09-17T14:43:50.056Z] elastic-package format
[2020-09-17T14:43:50.056Z] elastic-package has been installed.
[2020-09-17T14:43:50.056Z] Format the package
[2020-09-17T14:43:50.056Z] Done
[2020-09-17T14:43:50.056Z] packages/aws:
[2020-09-17T14:43:50.056Z] elastic-package format
[2020-09-17T14:43:50.056Z] Format the package
[2020-09-17T14:43:50.056Z] Done
[2020-09-17T14:43:50.056Z] packages/checkpoint:
[2020-09-17T14:43:50.056Z] elastic-package format
[2020-09-17T14:43:50.056Z] Format the package
[2020-09-17T14:43:50.056Z] Done
[2020-09-17T14:43:50.056Z] packages/cisco:
[2020-09-17T14:43:50.056Z] elastic-package format
[2020-09-17T14:43:50.056Z] Format the package
[2020-09-17T14:43:50.056Z] Done
[2020-09-17T14:43:50.056Z] packages/crowdstrike:
[2020-09-17T14:43:50.056Z] elastic-package format
[2020-09-17T14:43:50.056Z] Format the package
[2020-09-17T14:43:50.056Z] Done
[2020-09-17T14:43:50.056Z] packages/fortinet:
[2020-09-17T14:43:50.056Z] elastic-package format
[2020-09-17T14:43:50.056Z] Format the package
[2020-09-17T14:43:50.056Z] Done
[2020-09-17T14:43:50.056Z] packages/haproxy:
[2020-09-17T14:43:50.056Z] elastic-package format
[2020-09-17T14:43:50.056Z] Format the package
[2020-09-17T14:43:50.056Z] Done
[2020-09-17T14:43:50.056Z] packages/iis:
[2020-09-17T14:43:50.056Z] elastic-package format
[2020-09-17T14:43:50.056Z] Format the package
[2020-09-17T14:43:50.056Z] Done
[2020-09-17T14:43:50.056Z] packages/kafka:
[2020-09-17T14:43:50.056Z] elastic-package format
[2020-09-17T14:43:50.056Z] Format the package
[2020-09-17T14:43:50.056Z] Done
[2020-09-17T14:43:50.056Z] packages/kubernetes:
[2020-09-17T14:43:50.056Z] elastic-package format
[2020-09-17T14:43:50.056Z] Format the package
[2020-09-17T14:43:50.056Z] Done
[2020-09-17T14:43:50.056Z] packages/log:
[2020-09-17T14:43:50.056Z] elastic-package format
[2020-09-17T14:43:50.056Z] Format the package
[2020-09-17T14:43:50.056Z] Done
[2020-09-17T14:43:50.056Z] packages/microsoft:
[2020-09-17T14:43:50.056Z] elastic-package format
[2020-09-17T14:43:50.056Z] Format the package
[2020-09-17T14:43:50.056Z] Done
[2020-09-17T14:43:50.056Z] packages/mongodb:
[2020-09-17T14:43:50.056Z] elastic-package format
[2020-09-17T14:43:50.056Z] Format the package
[2020-09-17T14:43:50.056Z] Done
[2020-09-17T14:43:50.056Z] packages/mysql:
[2020-09-17T14:43:50.056Z] elastic-package format
[2020-09-17T14:43:50.056Z] Format the package
[2020-09-17T14:43:50.056Z] Done
[2020-09-17T14:43:50.056Z] packages/netflow:
[2020-09-17T14:43:50.056Z] elastic-package format
[2020-09-17T14:43:50.056Z] Format the package
[2020-09-17T14:43:50.056Z] Done
[2020-09-17T14:43:50.056Z] packages/nginx:
[2020-09-17T14:43:50.056Z] elastic-package format
[2020-09-17T14:43:50.056Z] Format the package
[2020-09-17T14:43:50.056Z] Done
[2020-09-17T14:43:50.056Z] packages/o365:
[2020-09-17T14:43:50.056Z] elastic-package format
[2020-09-17T14:43:50.056Z] Format the package
[2020-09-17T14:43:50.056Z] Done
[2020-09-17T14:43:50.056Z] packages/okta:
[2020-09-17T14:43:50.056Z] elastic-package format
[2020-09-17T14:43:50.056Z] Format the package
[2020-09-17T14:43:50.056Z] Done
[2020-09-17T14:43:50.056Z] packages/osquery:
[2020-09-17T14:43:50.056Z] elastic-package format
[2020-09-17T14:43:50.056Z] Format the package
[2020-09-17T14:43:50.056Z] Error: formatting the integration failed (path: /var/lib/jenkins/workspace/Beats_integrations_PR-273/src/github.com/elastic/integrations/packages/osquery, failFast: false): walking through the integration files failed: formatting file failed (path: /var/lib/jenkins/workspace/Beats_integrations_PR-273/src/github.com/elastic/integrations/packages/osquery/dataset/osquery/fields/fields.yml): formatting file content failed: marshalling YAML node failed: yaml: expected SCALAR, SEQUENCE-START, MAPPING-START, or ALIAS, but got document end
[2020-09-17T14:43:50.056Z] Error: running elastic-package failed: running "/var/lib/jenkins/workspace/Beats_integrations_PR-273/src/github.com/elastic/integrations/build/elastic-package format" failed with exit code 1
[2020-09-17T14:43:50.216Z] Stage "Update Package Storage" skipped due to earlier failure(s)
[2020-09-17T14:43:50.721Z] Running on Jenkins in /var/lib/jenkins/workspace/Beats_integrations_PR-273
[2020-09-17T14:43:50.970Z] [INFO] getVaultSecret: Getting secrets
[2020-09-17T14:43:51.057Z] Masking supported pattern matches of $VAULT_ADDR or $VAULT_ROLE_ID or $VAULT_SECRET_ID
[2020-09-17T14:43:51.875Z] + chmod 755 generate-build-data.sh
[2020-09-17T14:43:51.875Z] + ./generate-build-data.sh https://beats-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/Beats/integrations/PR-273/ https://beats-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/Beats/integrations/PR-273/runs/1 FAILURE 216315
[2020-09-17T14:43:51.875Z] INFO: curl https://beats-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/Beats/integrations/PR-273/runs/1/steps/?limit=10000 -o steps-info.json
[2020-09-17T14:43:52.126Z] INFO: curl https://beats-ci.elastic.co/blue/rest/organizations/jenkins/pipel [...]

2020-09-17 19:39 UTC, elasticmachine commented
Pinging @elastic/integrations (Team:Integrations)

2020-09-17 19:39 UTC, elasticmachine commented
Pinging @elastic/siem (Team:SIEM)

2020-09-18 16:21 UTC, james-elastic approved these changes

2020-09-21 09:59 UTC, mtojek commented
The CI is unhappy at the moment. Please run `mage check` locally and commit modified files. Most likely it's about formatting.

2020-09-21 09:59 UTC, mtojek requested changes
CI notified about issues.

2020-09-21 18:24 UTC, aleksmaus commented
@mtojek `mage check` ran cleanly before as still finishes cleanly on the same branch locally, just checked

2020-09-21 18:37 UTC, mtojek commented
Hm.. it's weird. Could you please push-force changes to restart CI job?

2020-09-21 20:32 UTC, jonathan-buttner commented on packages/osquery/kibana/dashboard/2c5565b0-bd32-11ea-9023-9f2ec2bc3202.json
> +        "panelsJSON": "[{\"version\":\"8.0.0-SNAPSHOT\",\"gridData\":{\"x\":0,\"y\":0,\"w\":11,\"h\":11,\"i\":\"187b6ce3-13d7-4cfe-be4b-9e568a90ad64\"},\"panelIndex\":\"187b6ce3-13d7-4cfe-be4b-9e568a
I think these json blobs might need to be decoded 🤔 . I think the scripts in this repo handle encoding them before they are copied to the `package-storage` repo.

Example: https://github.com/elastic/package-storage/blob/production/packages/aws/0.2.4/kibana/dashboard/aws-0eb5a6a0-694f-11ea-b0ac-95d4ecb1fecd.json#L9

2020-09-28 18:06 UTC, aleksmaus commented on packages/osquery/kibana/dashboard/2c5565b0-bd32-11ea-9023-9f2ec2bc3202.json
> +        "panelsJSON": "[{\"version\":\"8.0.0-SNAPSHOT\",\"gridData\":{\"x\":0,\"y\":0,\"w\":11,\"h\":11,\"i\":\"187b6ce3-13d7-4cfe-be4b-9e568a90ad64\"},\"panelIndex\":\"187b6ce3-13d7-4cfe-be4b-9e568a
These are from POC and sure will change as well. Will update to have it decoded.

2020-09-28 18:40 UTC, aleksmaus commented
Rebased, so had to force push.

2020-10-02 06:30 UTC, mtojek commented
Please adjust the PR accordingly to changes introduced in https://github.com/elastic/integrations/pull/280 .

Main changes:
0. Rebase against master.
1. Rename "dataset" folder to "data_stream".
2. Rename "config_templates" to "policy_templates" in package manifest file.

2020-11-23 08:16 UTC, mtojek commented
@aleksmaus I'm afraid this PR is not compliant with latest changes in the Integrations. Would you like to re-adjust it or prefer to close it?

2020-11-23 13:15 UTC, aleksmaus commented
will check what's up and update as needed.

2020-11-30 13:50 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > Either there was a build timeout or someone aborted the build.'}
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-273/detail/PR-273/9//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-273/detail/PR-273/9//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-273/detail/PR-273/9//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-273/detail/PR-273/9//artifacts) 

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats

* Build Cause: `Started by user Marcin Tojek`

* Start Time: 2020-11-30T13:49:30.954+0000

* Duration: 0 min 9 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY-->




<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2020-11-30T13:49:30.955Z] Started by user Marcin Tojek
[2020-11-30T13:49:31.068Z] Connecting to https://api.github.com using elasticmachine/****** (GitHub user @elasticmachine User + Personal Access Token)
[2020-11-30T13:49:32.031Z] Connecting to https://api.github.com to check permissions of obtain list of aleksmaus for elastic/integrations
[2020-11-30T13:49:32.570Z] Obtained .ci/Jenkinsfile from 56c762ac63a48617bf6cab3c90624d749d926862+ee6031d50123ab4550a223df2aea41f2d90e136c (e5d3ee29993a93c2d70942b82b3ff4123231fa8b)
[2020-11-30T13:49:32.570Z] Resume disabled by user, switching to high-performance, low-durability mode.
[2020-11-30T13:49:32.586Z] Loading library apm@current
[2020-11-30T13:49:32.587Z] Attempting to resolve current from remote references...
[2020-11-30T13:49:32.587Z]  > git --version # timeout=10
[2020-11-30T13:49:32.619Z]  > git --version # 'git version 2.7.4'
[2020-11-30T13:49:32.619Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2020-11-30T13:49:32.629Z]  > git ls-remote -h git@github.com:elastic/apm-pipeline-library.git # timeout=10
[2020-11-30T13:49:33.169Z] Could not find current in remote references. Pulling heads to local for deep search...
[2020-11-30T13:49:33.170Z]  > git rev-parse --is-inside-work-tree # timeout=10
[2020-11-30T13:49:33.180Z] Setting origin to git@github.com:elastic/apm-pipeline-library.git
[2020-11-30T13:49:33.180Z]  > git config remote.origin.url git@github.com:elastic/apm-pipeline-library.git # timeout=10
[2020-11-30T13:49:33.187Z] Fetching origin...
[2020-11-30T13:49:33.187Z] Fetching upstream changes from origin
[2020-11-30T13:49:33.187Z]  > git --version # timeout=10
[2020-11-30T13:49:33.193Z]  > git --version # 'git version 2.7.4'
[2020-11-30T13:49:33.193Z]  > git config --get remote.origin.url # timeout=10
[2020-11-30T13:49:33.200Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2020-11-30T13:49:33.209Z]  > git fetch --tags --progress origin +refs/heads/*:refs/remotes/origin/* # timeout=10
[2020-11-30T13:49:33.801Z]  > git rev-parse current^{commit} # timeout=10
[2020-11-30T13:49:33.809Z]  > git branch -a -v --no-abbrev --contains 1f8b3659465d49fec019a8b0c9a96d2b7af4c8ab # timeout=10
[2020-11-30T13:49:33.856Z] Selected match: master revision 1f8b3659465d49fec019a8b0c9a96d2b7af4c8ab
[2020-11-30T13:49:33.858Z] using credential f6c7695a-671e-4f4f-a331-acdce44ff9ba
[2020-11-30T13:49:33.902Z] Cloning the remote Git repository
[2020-11-30T13:49:33.902Z] Cloning with configured refspecs honoured and without tags
[2020-11-30T13:49:33.902Z] Cloning repository git@github.com:elastic/apm-pipeline-library.git
[2020-11-30T13:49:33.902Z]  > git init /var/lib/jenkins/workspace/gest-manager_integrations_PR-273@libs/apm # timeout=10
[2020-11-30T13:49:33.912Z] Fetching upstream changes from git@github.com:elastic/apm-pipeline-library.git
[2020-11-30T13:49:33.912Z]  > git --version # timeout=10
[2020-11-30T13:49:33.919Z]  > git --version # 'git version 2.7.4'
[2020-11-30T13:49:33.919Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2020-11-30T13:49:33.932Z]  > git fetch --no-tags --progress git@github.com:elastic/apm-pipeline-library.git +refs/heads/*:refs/remotes/origin/* # timeout=10
[2020-11-30T13:49:34.897Z]  > git config remote.origin.url git@github.com:elastic/apm-pipeline-library.git # timeout=10
[2020-11-30T13:49:34.904Z]  > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
[2020-11-30T13:49:34.912Z]  > git config remote.origin.url git@github.com:elastic/apm-pipeline-library.git # timeout=10
[2020-11-30T13:49:34.920Z] Fetching without tags
[2020-11-30T13:49:34.920Z] Fetching upstream changes from git@github.com:elastic/apm-pipeline-library.git
[2020-11-30T13:49:34.920Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2020-11-30T13:49:34.928Z]  > git fetch --no-tags --progress git@github.com:elastic/apm-pipeline-library.git +refs/heads/*:refs/remotes/origin/* # timeout=10
[2020-11-30T13:49:35.524Z] Checking out Revision 1f8b3659465d49fec019a8b0c9a96d2b7af4c8ab (master)
[2020-11-30T13:49:35.524Z]  > git config core.sparsecheckout # timeout=10
[2020-11-30T13:49:35.531Z]  > git checkout -f 1f8b3659465d49fec019a8b0c9a96d2b7af4c8ab # timeout=10
[2020-11-30T13:49:35.606Z] Commit message: "docs: update CHANGELOG.md"
[2020-11-30T13:49:36.115Z] Excluding src/test/ from checkout of git git@github.com:elastic/apm-pipeline-library.git so that shared library test code cannot be accessed by Pipelines.
[2020-11-30T13:49:36.115Z] To remove this log message, move the test code outside of src/. To restore the previous behavior that allowed access to files in src/test/, pass -Dorg.jenkinsci.plugins.workflow.libs.SCMSourceRetriever.INCLUDE_SRC_TEST_IN_LIBRARIES=true to the java command used to start Jenkins.
[2020-11-30T13:49:38.794Z] Aborted by Marcin Tojek
[2020-11-30T13:49:39.007Z] Running on worker-1244230 in /var/lib/jenkins/workspace/gest-manager_integrations_PR-273
[2020-11-30T13:49:39.125Z] [39;49m[INFO] getVaultSecret: Getting secrets[0m
[2020-11-30T13:49:39.180Z] Masking supported pattern matches of $VAULT_ADDR or $VAULT_ROLE_ID or $VAULT_SECRET_ID
[2020-11-30T13:49:41.196Z] + chmod 755 generate-build-data.sh
[2020-11-30T13:49:41.196Z] + ./generate-build-data.sh https://beats-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/Ingest-manager/integrations/PR-273/ https://beats-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/Ingest-manager/integrations/PR-273/runs/9 ABORTED 8867
[2020-11-30T13:49:41.196Z] INFO: curl https://beats-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/Ingest-manager/integrations/PR-273/runs/9/steps/?limit=10000 -o steps-info.json
[2020-11-30T13:49:41.892Z] INFO: curl https://beats-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/Ingest-manager/integrations/PR-273/runs/9/tests/?status=FAILED -o tests-errors.json
[2020-11-30T13:49:42.588Z] Retry 1/3 exited 22, retrying in 1 seconds...
[2020-11-30T13:49:44.031Z] Retry 2/3 exited 22, retrying in 2 seconds...
[2020-11-30T13:49:46.275Z] Retry 3/3 exited 22, no more retries left.
[2020-11-30T13:49:46.275Z] INFO: curl https://beats-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/Ingest-manager/integrations/PR-273/runs/9/log/ -o pipeline-log.txt

```

</p>
</details>



<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2021-01-26 21:22 UTC, aleksmaus commented
Updated the package naming in order to resolve the conflict with existing osquery filebeat package

<img width="1095" alt="Screen Shot 2021-01-26 at 4 00 05 PM" src="https://user-images.githubusercontent.com/872351/105907039-7be10180-5ff2-11eb-97e1-36fbd795ae57.png">
<img width="1127" alt="Screen Shot 2021-01-26 at 4 00 20 PM" src="https://user-images.githubusercontent.com/872351/105907071-87342d00-5ff2-11eb-8d15-451561fa7b64.png">
<img width="727" alt="Screen Shot 2021-01-26 at 4 19 05 PM" src="https://user-images.githubusercontent.com/872351/105907123-96b37600-5ff2-11eb-87f2-c29191e8d1d9.png">

2021-01-26 21:24 UTC, aleksmaus commented
Removed all the kibana files for now, these were for POC.
@mtojek

2021-01-27 09:57 UTC, mtojek approved these changes

2021-01-27 16:30 UTC, james-elastic approved these changes

2021-01-27 19:37 UTC, aleksmaus commented
<img width="600" alt="Screen Shot 2021-01-27 at 2 34 48 PM" src="https://user-images.githubusercontent.com/872351/106043846-f4a49400-60ac-11eb-8735-621e8393bd8d.png">
This makes the input_type more cleaner and concise for the actions that will target osquery.

2021-01-27 21:07 UTC, merged