[auditd_manager] New auditd manager package
elastic/integrations pull request #2763
Opened 2022-03-03 11:43 UTC by marc-gr

## What does this PR do?

Adds a new auditd_manager integration

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

2022-03-03 12:07 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2763/detail/PR-2763/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2763/detail/PR-2763/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2763/detail/PR-2763/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2763/detail/PR-2763/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_2763.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-03-03T11:33:54.816Z&rangeTo=2022-03-03T11:53:54.816Z&transactionName=Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=fe6ae110b5ba2277bc5815583d29600a&transactionId=cc48f940b7cc74e9)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-03-03T11:43:54.816+0000


* Duration: 24 min 37 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 14  |
| Skipped      | 0 |
| Total        | 14   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2763/detail/PR-2763/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Check integration: auditd_manager`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-2763/runs/1/steps/786/log/?start=0">here</a></li>
<li>Description: <code>../../build/elastic-package check -v</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-03-24 13:13 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2022-03-29 15:38 UTC, adriansr requested changes
Had a quick look.

Needs manual update of .git/CODEOWNERS

2022-03-29 15:38 UTC, adriansr commented on packages/auditd/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/
```suggestion
      link: https://github.com/elastic/integrations/pull/2763
```

2022-03-29 15:53 UTC, adriansr commented on packages/auditd_manager/manifest.yml
> +license: basic
```suggestion
license: basic
release: beta
```

2022-04-26 11:08 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`1/1`) | :green_heart: 
Files | 100.0% (`1/1`) | :green_heart: 2.941
Classes | 100.0% (`1/1`) | :green_heart: 2.941
Methods | 100.0% (`15/15`) | :green_heart: 12.218
Lines | 97.985% (`2140/2184`) | :+1: 9.407
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-05-19 14:50 UTC, adriansr requested changes

2022-05-19 14:50 UTC, adriansr commented on packages/auditd_manager/data_stream/auditd/elasticsearch/ingest_pipeline/default.yml
> +        handleMap(ctx);
is this necessary to apply this for all fields in ctx, instead of a subset like ctx.auditd ?

2022-05-19 14:50 UTC, adriansr commented on packages/auditd_manager/data_stream/auditd/manifest.yml
> +        description: "This setting controls if the socket type used to receive events is multicast.\nThis setting should be disabled when `elastic-agent` is the primary userspace\ndaemon for receivin
This description would be more readable as a yaml multiline block, and it has a weird \\n\" at the end.

2022-05-19 14:50 UTC, adriansr commented on packages/auditd_manager/data_stream/auditd/manifest.yml
> +          limit of `5000``. Users should test their setup and adjust the `Rate limit`
There's an extra ` here that's causing formmating issues.

2022-05-20 01:46 UTC, efd6 reviewed
Nice!

2022-05-20 01:46 UTC, efd6 commented on packages/auditd_manager/kibana/dashboard/auditd_manager-7de391b0-c1ca-11e7-8995-936807a28b16.json
> +                "title": "[Auditd Manager] Exe Name Tag Cloud",
s/Exe/Executable/?

2022-05-20 01:46 UTC, efd6 commented on packages/auditd_manager/data_stream/auditd/manifest.yml
> +        description: "This setting controls if the socket type used to receive events is multicast.\nThis setting should be disabled when `elastic-agent` is the primary userspace\ndaemon for receivin
Also below for the long lines.

2022-05-20 08:26 UTC, marc-gr commented on packages/auditd_manager/data_stream/auditd/manifest.yml
> +        description: "This setting controls if the socket type used to receive events is multicast.\nThis setting should be disabled when `elastic-agent` is the primary userspace\ndaemon for receivin
elastic-package format command converts multiline strings to single line ones, I will fix the ending weird `\n` though

2022-05-20 08:51 UTC, efd6 approved these changes
LGTM after query about the painless is satisfied.

(and audit_manager is rebuilt)

2022-05-20 09:03 UTC, marc-gr commented on packages/auditd_manager/data_stream/auditd/elasticsearch/ingest_pipeline/default.yml
> +        handleMap(ctx);
the events come with also custom fields under user.* and file.*, since I was not able to generate many different samples, I am not 100% sure these are the only ones, so I tried to err on the more consistent way of dealing with them. If you prefer I can change it to operate on auditd, user, and file and we can deal with any other case found if any.

2022-05-20 09:08 UTC, adriansr commented on packages/auditd_manager/data_stream/auditd/elasticsearch/ingest_pipeline/default.yml
> +        handleMap(ctx);
It's ok then, let's keep it as is now.

2022-05-20 09:09 UTC, adriansr approved these changes

2022-05-20 09:19 UTC, merged