[apache_spark] Add Apache Spark package
elastic/integrations pull request #2811
Opened 2022-03-10 06:39 UTC by yug-elastic

## What does this PR do?

- Generated the skeleton of Apache Spark integration package.
- Added 1 data streams ( Metrics )
- Added data collection logic for the data stream.
- Added the ingest pipeline for the data stream.
- Mapped fields according to the ECS schema and added Fields metadata in the appropriate yml files.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] If I'm introducing a new feature, I have modified the Kibana version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^7.13.0`).

## How to test this PR locally

- Clone integrations repo.
- Install elastic-package locally.
- Start elastic stack using elastic-package.
- Move to integrations/packages/apache_spark directory.
- Run the following command to run tests. 
> elastic-package test 

## Screenshots

2022-03-10 06:51 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2811/detail/PR-2811/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2811/detail/PR-2811/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2811/detail/PR-2811/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2811/detail/PR-2811/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_2811.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-03-10T06:30:09.234Z&rangeTo=2022-03-10T06:50:09.234Z&transactionName=BUILD Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=36abdb8d7e8abe6b3d5d87c427949046&transactionId=3de2d5ad566be111)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-03-10T06:40:09.234+0000


* Duration: 11 min 49 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 1  |
| Skipped      | 0 |
| Total        | 1   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-03-10 11:54 UTC, mtojek reviewed
Did you take a look at the Spark project [documentation](https://spark.apache.org/docs/latest/monitoring.html#metrics)? Metrics are grouped based on instances, there isn't one big bucket for all metrics.

2022-03-10 11:54 UTC, mtojek commented on packages/apache_spark/manifest.yml
> +    description: Collect Apache Spark metrics
Same problem as with Spring Boot, you need to divide metrics into logical groups.

2022-03-10 11:54 UTC, mtojek commented on packages/apache_spark/manifest.yml
> +  - src: /img/apache_spark-logo.svg
I guess you can use the right logo?

2022-03-10 11:54 UTC, mtojek commented on packages/apache_spark/manifest.yml
> +  kibana.version: ^7.16.2 || ^8.0.0
Hm... I think you can go with ^8.0.0 only. We don't need to publish this package for old releases.

2022-03-10 11:54 UTC, mtojek commented on packages/apache_spark/changelog.yml
> +    - description: Initial draft of the package
If you plan to merge this package with only this PR, it won't be a draft anymore :)

2022-03-10 11:54 UTC, mtojek commented on packages/apache_spark/docs/README.md
> +Consider using the README template file `_dev/build/docs/README.md`to generate a list of exported fields or include a sample event.
What is required from the end-user to make it integrated? What kind of changes should be introduced to Spark?

2022-03-10 13:59 UTC, yug-elastic commented
> Could you populate "README.md" with all details needed? It does not have any details of the integration currently.

@lalit-satapathy , yes that's something we are still working on. This PR is still in progress, so expect system tests, dashboards, and README in the later commits

2022-03-11 11:39 UTC, yug-elastic commented
> Did you take a look at the Spark project [documentation](https://spark.apache.org/docs/latest/monitoring.html#metrics)? Metrics are grouped based on instances, there isn't one big bucket for all metrics.

@mtojek Yes, we did check out the documentation. However, we referred to the Hadoop integration where we have clubbed multiple metrics in a single data stream keeping in mind the future extensibility and thought of using the same approach here for Apache Spark.

2022-03-11 11:40 UTC, yug-elastic commented on packages/apache_spark/manifest.yml
> +    description: Collect Apache Spark metrics
I hope we have addressed this in our [previous comment](https://github.com/elastic/integrations/pull/2811#issuecomment-1065034805)

2022-03-11 11:40 UTC, yug-elastic commented on packages/apache_spark/manifest.yml
> +  - src: /img/apache_spark-logo.svg
What do you think about using this one?
[https://upload.wikimedia.org/wikipedia/commons/f/f3/Apache_Spark_logo.svg](https://commons.wikimedia.org/wiki/File:Apache_Spark_logo.svg)

2022-03-11 11:40 UTC, yug-elastic commented on packages/apache_spark/manifest.yml
> +  kibana.version: ^7.16.2 || ^8.0.0
The execution/sprint plan that we sent out mentioned ^7.16.0 and hence we kept this. But if you believe we should just keep ^8.0.0, we will update it.
CC: @akshay-saraswat

2022-03-11 11:41 UTC, yug-elastic commented on packages/apache_spark/changelog.yml
> +    - description: Initial draft of the package
Yes, that's in the plan for future commits.
Does this look good?
Apache Spark integration package with Driver, Executor, Master, Worker and ApplicationSource metrics

2022-03-11 11:42 UTC, yug-elastic commented on packages/apache_spark/docs/README.md
> +Consider using the README template file `_dev/build/docs/README.md`to generate a list of exported fields or include a sample event.
Yes, that's something we are still working on. We'll update the README with detailed steps of the changes required.

2022-03-12 08:23 UTC, elasticmachine commented
Pinging @elastic/integrations (Team:Integrations)

2022-03-13 06:23 UTC, yug-elastic commented
/test

2022-03-14 08:23 UTC, mtojek requested changes
> @mtojek Yes, we did check out the documentation. However, we referred to the Hadoop integration where we have clubbed multiple metrics in a single data stream keeping in mind the future extensibility and thought of using the same approach here for Apache Spark.

I'm afraid that it isn't the way we'd like to follow. We'd rather see metrics split into multiple areas and add a new area if needed. We have to iterate on this. I will check the Hadoop integration and if it applies also there, I guess we have to refactor that one as well.

2022-03-15 09:00 UTC, yug-elastic commented
/test

2022-03-15 10:55 UTC, yug-elastic commented
> I'm afraid that it isn't the way we'd like to follow. We'd rather see metrics split into multiple areas and add a new area if needed. We have to iterate on this. I will check the Hadoop integration and if it applies also there, I guess we have to refactor that one as well.

Okay, we'll need to iterate on this then. As of now, we have the following 5 types of metrics:
Master, Worker, ApplicationSource, Driver, Executor
Let me know what you think of these groups:
[Master, Worker], [ApplicationSource], [Driver, Executor]

Just double-checking, splitting metrics into multiple areas means creating number of data streams equal to the number of areas. Is our understanding correct?

2022-03-15 13:10 UTC, yug-elastic commented
Thanks for the organization, @mtojek! I'll make the changes accordingly.

> I'm missing here the part _Cluster Manager_ part, is it possible to cover it too?

Cluster Manager was not a part of the [PRD](https://github.com/elastic/integrations/issues/493) and V1, so we didn't cover it considering our standard connector size.
CC: @akshay-saraswat

2022-03-16 18:46 UTC, akshay-saraswat commented
> Cluster Manager was not a part of the https://github.com/elastic/integrations/issues/493 and V1, so we didn't cover it considering our standard connector size.

Which provider or logs are you planning to use for the Cluster Manager metrics?

2022-03-22 06:00 UTC, yug-elastic commented
> Which provider or logs are you planning to use for the Cluster Manager metrics?

We haven't actually analyzed the `Cluster Manager` as of now. Also, it wasn't a part of the [documentation](https://spark.apache.org/docs/latest/monitoring.html) which was mentioned in the PRD.

2022-03-22 06:19 UTC, yug-elastic commented
We are facing an issue with the system tests for the ApplicationSource, Driver and Executor as we need to keep an application running in the container to collect the metrics. We are actively working on the same, and we'll update the PR as soon as it's done. Meanwhile, please feel free to add reviews to the other changes that are completed.

2022-03-23 05:26 UTC, yug-elastic commented
Issue with system tests:
The system tests for the `nodes` data stream are working fine. However, in case of `driver` and `executors` data streams, the metrics would be fetched when any application is running.

If we run a sample application (for example, WordCount) as a part of the Dockerfile, it would be considered as a step and would complete when the application is ran completely, and hence the metrics are not found during the system tests. We also tried running the application in background (once and in an infinite loop) using entrypoint script, but were unsuccessful and were not able to hit Jolokia even after that.

Please let us know if you have any ideas on the same. We can push the code over the PR for you to take a look if you think that's a good idea.

2022-03-23 10:27 UTC, mtojek reviewed
Yug, I did partially the review as some comments apply to many places. Please revisit the entire PR based on those.

2022-03-23 10:27 UTC, mtojek commented on packages/apache_spark/data_stream/applications/fields/fields.yml
> +    - name: application_source
This should be called `applications` as the data stream.

2022-03-23 10:27 UTC, mtojek commented on packages/apache_spark/data_stream/applications/sample_event.json
> +        "dataset": "apache_spark.metrics",
Please regenerate this sample event.

2022-03-23 10:27 UTC, mtojek commented on packages/apache_spark/data_stream/driver/fields/fields.yml
> +        - name: application.name
Did you mean `application_name`?

2022-03-23 10:27 UTC, mtojek commented on packages/apache_spark/data_stream/driver/fields/fields.yml
> +        - name: live_listener_bus
Do we need these metrics? Isn't it too detailed?

2022-03-23 10:27 UTC, mtojek commented on packages/apache_spark/data_stream/driver/fields/fields.yml
> +        - name: dag_schedular
Schedular or scheduler?

2022-03-23 10:27 UTC, mtojek commented on packages/apache_spark/data_stream/executors/fields/fields.yml
> +    - name: executor
Same, data stream name is inconsistent with this field

2022-03-23 13:49 UTC, yug-elastic commented on packages/apache_spark/data_stream/executors/fields/fields.yml
> +        - name: deserialize
I agree, but we followed the [PRD](https://github.com/elastic/integrations/issues/493) where it has been mentioned to collect gauge and counter metrics.

> Spark provides the following types of metrics - Gauge, Counter, Histogram, Meter, Timer. The most common types of metrics used in Spark instrumentation are gauges and counters. Hence, we will support only Gauge and Counter metrics from the following providers 

How should we take it forward?
CC: @akshay-saraswat

2022-03-28 08:34 UTC, yug-elastic commented on packages/apache_spark/data_stream/applications/sample_event.json
> +        "dataset": "apache_spark.metrics",
Yes, this sample event is old because the system tests are only completed for the `nodes` data stream as of now. The sample event would be updated along with the same.

2022-03-28 08:38 UTC, yug-elastic commented on packages/apache_spark/data_stream/driver/sample_event.json
> +        "metrics": {
Yes, this sample event is old because the system tests are only completed for the `nodes` data stream as of now. The sample event would be updated along with the same.

2022-03-28 08:40 UTC, yug-elastic commented on packages/apache_spark/data_stream/driver/fields/fields.yml
> +        - name: live_listener_bus
Same answer as [this comment](https://github.com/elastic/integrations/pull/2811#discussion_r833290354).

2022-03-28 08:40 UTC, yug-elastic commented on packages/apache_spark/data_stream/driver/fields/fields.yml
> +        - name: hive_external_catalog
Same answer as [this comment](https://github.com/elastic/integrations/pull/2811#discussion_r833290354).

2022-03-28 08:59 UTC, yug-elastic commented on packages/apache_spark/data_stream/executors/fields/fields.yml
> +        - name: hive_client_calls
Same answer as [this comment](https://github.com/elastic/integrations/pull/2811#discussion_r833290354).

2022-03-28 08:59 UTC, yug-elastic commented on packages/apache_spark/data_stream/executors/sample_event.json
> +        "metrics": {
Yes, this sample event is old because the system tests are only completed for the `nodes` data stream as of now. The sample event would be updated along with the same.

2022-03-28 11:59 UTC, yug-elastic commented on packages/apache_spark/_dev/build/docs/README.md
> +Now, create `/usr/local/spark/conf/jolokia-master.properties` file with following content:
Are you suggesting to use `main`/`worker` everywhere in the README or everywhere else (like the field names)?

2022-03-28 12:03 UTC, mtojek commented on packages/apache_spark/_dev/build/docs/README.md
> +Now, create `/usr/local/spark/conf/jolokia-master.properties` file with following content:
Everywhere where it can be applied.

2022-03-28 12:04 UTC, mtojek commented on packages/apache_spark/_dev/build/docs/README.md
> +Now, create `/usr/local/spark/conf/jolokia-master.properties` file with following content:
See: https://issues.apache.org/jira/browse/SPARK-32004 and https://issues.apache.org/jira/browse/SPARK-32333

2022-03-28 12:32 UTC, yug-elastic commented on packages/apache_spark/_dev/deploy/docker/Dockerfiles/Dockerfile-master
> +  wget
Good idea, thank you!

2022-03-28 12:39 UTC, yug-elastic commented on packages/apache_spark/_dev/build/docs/README.md
> +Now, create `/usr/local/spark/conf/jolokia-master.properties` file with following content:
Got it. Thanks for passing links, I'll make the changes.

2022-03-29 05:27 UTC, yug-elastic commented on packages/apache_spark/data_stream/driver/fields/fields.yml
> +          fields:
Sure, what are your thoughts on the following groups?
**memory**
direct_pool_memory
jvm.heap_memory
jvm.off_heap_memory
mappped_pool_memory

**gc**
major_gc.count
major_gc.time
minor_gc.count
minor_gc.time

**heap_memory**
off_heap.execution_memory
off_heap.storage_memory
off_heap.unified_memory
on_heap.execution_memory
on_heap.storage_memory
on_heap.unified_memory

**process_tree**
process_tree.jvm.rss_memory
process_tree.jvm.v_memory
process_tree.other.rss_memory
process_tree.other.v_memory
process_tree.python.rss_memory
process_tree.python.v_memory

2022-03-29 08:17 UTC, mtojek commented on packages/apache_spark/data_stream/driver/fields/fields.yml
> +          fields:
Yup, it looks much better with this split. "Memory" is still redundant for many of these metrics, so maybe just strip it?

`direct_pool_memory` -> `direct_pool`
`jvm.heap_memory` -> `jvm.heap`
etc.

`off_heap.unified_memory` -> `off.unified` (so we have `heap_memory.off`, not `heap_memory.off_heap.unified_memory`)

same with `process tree`

 Few questions though to better understand these metrics, could you please explain what these are representing:
* direct_pool_memory vs mappped_pool_memory
* on_heap.execution_memory vs on_heap.storage_memory vs on_heap.unified_memory

2022-03-29 08:28 UTC, mtojek commented on packages/apache_spark/data_stream/executors/fields/fields.yml
> +        - name: deserialize
Ok, I will pass the final decision to @akshay-saraswat.

2022-03-30 00:49 UTC, akshay-saraswat commented
> > Which provider or logs are you planning to use for the Cluster Manager metrics?
> 
> We haven't actually analyzed the `Cluster Manager` as of now. Also, it wasn't a part of the [documentation](https://spark.apache.org/docs/latest/monitoring.html) which was mentioned in the PRD.

I think Cluster Manager is just a component in the architecture and you get the metrics associated via Master or ApplicationMaster if I am not mistaken. Feel free to correct my understanding if you find anything different.

2022-03-30 01:08 UTC, akshay-saraswat commented on packages/apache_spark/data_stream/executors/fields/fields.yml
> +        - name: hive_client_calls
These are Gauge and Count metrics respectively, I believe. Let's keep them.

2022-03-30 01:36 UTC, akshay-saraswat commented on packages/apache_spark/data_stream/driver/fields/fields.yml
> +        - name: hive_external_catalog
Yes, our competitors collect these which validates the need. We should collect them in my opinion.

2022-03-30 01:41 UTC, akshay-saraswat commented on packages/apache_spark/manifest.yml
> +  kibana.version: ^7.16.2 || ^8.0.0
8.0 sounds fine to me too. Let's reduce the supported versions and hence the need for backward compatibility as much as we can. :)

2022-03-30 05:04 UTC, yug-elastic commented on packages/apache_spark/manifest.yml
> +  kibana.version: ^7.16.2 || ^8.0.0
Understood, thank you for the clarification. We will go with 8.0.

2022-03-30 06:04 UTC, akshay-saraswat commented on packages/apache_spark/manifest.yml
> +  kibana.version: ^7.16.2 || ^8.0.0
Made a similar comment on Nagios integration just now. Let's make it 8.2.0 instead. 8.0 is already released and we will not be able to publish this integration before 8.2.0 I am guessing.

2022-03-30 06:57 UTC, ruflin commented on packages/apache_spark/manifest.yml
> +  kibana.version: ^7.16.2 || ^8.0.0
++ on releasing new integrations only for the most recent version. I assume we don't test all the previous releases.

2022-03-30 07:01 UTC, ruflin commented
This PR would strongly benefit from splitting it up into multiple PRs. One for the foundation of spark + 1 data stream and then have an additional PR for each data stream. As the comments in this PR are important and should not be lost, I recommend to switch this PR to draft, open a fresh new PR and copy over the parts needed for the first foundation PR and reference this PR there. Then go on an copy over each data stream directory to a PR per data stream as soon as the first PR is merged. This should make it possible to move forward much more quickly and more focused.

2022-03-30 14:39 UTC, yug-elastic commented on packages/apache_spark/manifest.yml
> +  kibana.version: ^7.16.2 || ^8.0.0
Sure, we'll update it once it has been verified and tested on our end. We'll follow the same for the future integrations as well.

2022-03-30 19:16 UTC, yug-elastic commented
> This PR would strongly benefit from splitting it up into multiple PRs. One for the foundation of spark + 1 data stream and then have an additional PR for each data stream. As the comments in this PR are important and should not be lost, I recommend to switch this PR to draft, open a fresh new PR and copy over the parts needed for the first foundation PR and reference this PR there. Then go on an copy over each data stream directory to a PR per data stream as soon as the first PR is merged. This should make it possible to move forward much more quickly and more focused.

Thanks @ruflin, it's a good idea. Here are the links for the PRs that this PR is split into:
https://github.com/elastic/integrations/pull/2939/
https://github.com/elastic/integrations/pull/2941/
https://github.com/elastic/integrations/pull/2945/
https://github.com/elastic/integrations/pull/2943/

2022-03-31 06:41 UTC, yug-elastic commented on packages/apache_spark/data_stream/driver/fields/fields.yml
> +        - name: live_listener_bus
Thanks for the clarification, Akshay!

2022-03-31 06:41 UTC, yug-elastic commented on packages/apache_spark/data_stream/driver/fields/fields.yml
> +        - name: hive_external_catalog
Thanks for the clarification, Akshay!

2022-03-31 07:35 UTC, ruflin commented
Thanks for the split up @yug-elastic . Which of the PRs we should have a detailed look first? We need one PR to get merged first and then follow up with the other 3, this ensures we don't review some of the content twice.

2022-03-31 08:59 UTC, yug-elastic commented
> Update: Looks like #2939 is the one?

Yes, #2939 it the one. Thanks for the review, @ruflin! We'll address the review comments soon.

2022-03-31 09:39 UTC, yug-elastic commented on packages/apache_spark/data_stream/driver/fields/fields.yml
> +          fields:
Thanks for the detailed grouping, @mtojek! Makes sense.
[direct_pool_memory](https://spark.apache.org/docs/latest/monitoring.html#:~:text=%C2%A0%C2%A0%C2%A0%C2%A0.-,DirectPoolMemory,-Peak%20memory%20that) vs [mapped_pool_memory](https://spark.apache.org/docs/latest/monitoring.html#:~:text=%C2%A0%C2%A0%C2%A0%C2%A0.-,MappedPoolMemory,-Peak%20memory%20that): I also found [this](https://stackoverflow.com/questions/15657837/what-is-mapped-buffer-pool-direct-buffer-pool-and-how-to-increase-their-size#:~:text=A%20direct%20buffer%20is%20a,which%20Java%20can%20read%20directly.) answer explaining it on StackOverflow.

[on_heap.execution_memory](https://spark.apache.org/docs/latest/monitoring.html#:~:text=%C2%A0%C2%A0%C2%A0%C2%A0.-,OnHeapExecutionMemory,-Peak%20on%20heap) vs [on_heap.storage_memory](https://spark.apache.org/docs/latest/monitoring.html#:~:text=%C2%A0%C2%A0%C2%A0%C2%A0.-,OnHeapStorageMemory,-Peak%20on%20heap) vs [on_heap.unified_memory](https://spark.apache.org/docs/latest/monitoring.html#:~:text=%C2%A0%C2%A0%C2%A0%C2%A0.-,OnHeapUnifiedMemory,-Peak%20on%20heap): As far as my understanding goes, `Unified = Execution + Storage`

2022-03-31 10:10 UTC, yug-elastic commented on packages/apache_spark/data_stream/executors/fields/fields.yml
> +        - name: deserialize
Right, thanks for the clarification!

2022-04-27 19:07 UTC, akshay-saraswat commented on packages/apache_spark/_dev/build/docs/README.md
> +The Apache Spark integration collects and parses data using the Jolokia Metricbeat Module.
nit: Would stating 'metricbeat module' confuse users into thinking that a separate metricbeat module is required for this integration. Should we instead say "Jolokia Input"? Although it's implicit from the requirements that the metricbeat module is not required. But it would be nice to make it explicit if you receive more comments to address and update this PR. Don't update just for this nitpick.

2022-04-28 06:29 UTC, yug-elastic commented on packages/apache_spark/_dev/build/docs/README.md
> +The Apache Spark integration collects and parses data using the Jolokia Metricbeat Module.
Thanks for the approval, @akshay-saraswat! This PR is the old PR which was split into data stream specific PRs as discussed. The other PRs have been approved and some of them are already merged. We do have one open PR (https://github.com/elastic/integrations/pull/3070/) which is approved by Jaime Soriano Pastor and waiting for the approval from CODEOWNERS. If "Jolokia Input" sounds more intuitive to you, we'll update that PR with the same change, it's not a problem.

2022-04-28 06:32 UTC, yug-elastic commented on packages/apache_spark/_dev/build/docs/README.md
> +The Apache Spark integration collects and parses data using the Jolokia Metricbeat Module.
Updated the same.
Quick Reference: https://github.com/elastic/integrations/pull/3070/files#diff-05a30b6a3e489638b54c77068eb780e019e4dcf90827f391e5693aa96aefb4f2R3

2022-05-09 08:21 UTC, yug-elastic commented
Closing this PR as it was split up into multiple PRs as discussed in the comment https://github.com/elastic/integrations/pull/2811#issuecomment-1082701692. All the parts are now merged and the linked issue (https://github.com/elastic/integrations/issues/493) has been closed.

Thanks a lot @mtojek, @ruflin, @jsoriano, @akshay-saraswat and @lalit-satapathy for taking out time to review the PRs and providing valuable feedback!

2022-05-09 08:21 UTC, closed without merging