Import zoom module from Filebeat
elastic/integrations pull request #284
Opened 2020-10-01 16:42 UTC by adriansr

## What does this PR do?

This imports the `zoom` module (`webhook` dataset) from Filebeat.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md#tips-for-building-integrations) and this pull request is aligned with them.
- [x] I have verified that all datasets collect metrics or logs.

## Author's Checklist

- [ ] Categories are correct (main `manifest.yml`), currently _security_ and _productivity._

## How to test this PR locally

You can send to it events from `<beats>/x-pack/filebeat/module/zoom/webhook/test/*.log` using an HTTP POST with `Content-Type: application/json`. 

## Screenshots

<img width="294" alt="Screen Shot 2020-10-01 at 18 32 50" src="https://user-images.githubusercontent.com/15056957/94838435-de940900-0415-11eb-9f07-1717fa66e984.png">

![Screenshot_2020-10-01 Zoom - Integrations - Fleet - Elastic](https://user-images.githubusercontent.com/15056957/94838358-c0c6a400-0415-11eb-8157-871bfe250fc9.png)

![Screenshot_2020-10-01 Add integration - Zoom - Integrations - Fleet - Elastic](https://user-images.githubusercontent.com/15056957/94838417-d5a33780-0415-11eb-82cf-7ffd657daa7e.png)

2020-10-01 16:46 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fintegrations%2FPR-284/detail/PR-284/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fintegrations%2FPR-284/detail/PR-284/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fintegrations%2FPR-284/detail/PR-284/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fintegrations%2FPR-284/detail/PR-284/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_284.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats

* Build Cause: `[Pull request #284 opened]`

* Start Time: 2020-10-01T16:42:54.083+0000

* Duration: 4 min 52 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY-->


### Steps errors

  <details><summary>Expand to view the steps failures</summary>
  <p>
  
  * **Name**: `Checks and builds integration sources`
    * Description: mage -debug check
    
    * Duration: 1 min 28 sec
    
    * Start Time: 2020-10-01T16:45:16.480+0000
    
    * [log](https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/integrations/pipelines/PR-284/runs/1/steps/114/log)
    
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2020-10-01T16:46:44.720Z] Done
[2020-10-01T16:46:44.720Z] packages/panw:
[2020-10-01T16:46:44.720Z] elastic-package test
[2020-10-01T16:46:44.720Z] Run test suite for the package
[2020-10-01T16:46:44.720Z] Run pipeline tests for the package
[2020-10-01T16:46:44.720Z] Done
[2020-10-01T16:46:44.720Z] Run system tests for the package
[2020-10-01T16:46:44.720Z] Done
[2020-10-01T16:46:44.720Z] packages/postgresql:
[2020-10-01T16:46:44.720Z] elastic-package test
[2020-10-01T16:46:44.720Z] Run test suite for the package
[2020-10-01T16:46:44.720Z] Run pipeline tests for the package
[2020-10-01T16:46:44.720Z] Done
[2020-10-01T16:46:44.720Z] Run system tests for the package
[2020-10-01T16:46:44.720Z] Done
[2020-10-01T16:46:44.720Z] packages/prometheus:
[2020-10-01T16:46:44.720Z] elastic-package test
[2020-10-01T16:46:44.720Z] Run test suite for the package
[2020-10-01T16:46:44.720Z] Run system tests for the package
[2020-10-01T16:46:44.720Z] Done
[2020-10-01T16:46:44.720Z] Run pipeline tests for the package
[2020-10-01T16:46:44.720Z] Done
[2020-10-01T16:46:44.720Z] packages/rabbitmq:
[2020-10-01T16:46:44.720Z] elastic-package test
[2020-10-01T16:46:44.720Z] Run test suite for the package
[2020-10-01T16:46:44.720Z] Run pipeline tests for the package
[2020-10-01T16:46:44.720Z] Done
[2020-10-01T16:46:44.720Z] Run system tests for the package
[2020-10-01T16:46:44.720Z] Done
[2020-10-01T16:46:44.720Z] packages/redis:
[2020-10-01T16:46:44.720Z] elastic-package test
[2020-10-01T16:46:44.720Z] Run test suite for the package
[2020-10-01T16:46:44.720Z] Run system tests for the package
[2020-10-01T16:46:44.720Z] Done
[2020-10-01T16:46:44.720Z] Run pipeline tests for the package
[2020-10-01T16:46:44.720Z] Done
[2020-10-01T16:46:44.720Z] packages/suricata:
[2020-10-01T16:46:44.720Z] elastic-package test
[2020-10-01T16:46:44.720Z] Run test suite for the package
[2020-10-01T16:46:44.720Z] Run system tests for the package
[2020-10-01T16:46:44.720Z] Done
[2020-10-01T16:46:44.720Z] Run pipeline tests for the package
[2020-10-01T16:46:44.720Z] Done
[2020-10-01T16:46:44.720Z] packages/synthetics:
[2020-10-01T16:46:44.720Z] elastic-package test
[2020-10-01T16:46:44.720Z] Run test suite for the package
[2020-10-01T16:46:44.720Z] Run pipeline tests for the package
[2020-10-01T16:46:44.720Z] Done
[2020-10-01T16:46:44.720Z] Run system tests for the package
[2020-10-01T16:46:44.720Z] Done
[2020-10-01T16:46:44.720Z] packages/system:
[2020-10-01T16:46:44.720Z] elastic-package test
[2020-10-01T16:46:44.720Z] Run test suite for the package
[2020-10-01T16:46:44.720Z] Run pipeline tests for the package
[2020-10-01T16:46:44.720Z] Done
[2020-10-01T16:46:44.720Z] Run system tests for the package
[2020-10-01T16:46:44.720Z] Done
[2020-10-01T16:46:44.720Z] packages/windows:
[2020-10-01T16:46:44.720Z] elastic-package test
[2020-10-01T16:46:44.720Z] Run test suite for the package
[2020-10-01T16:46:44.720Z] Run pipeline tests for the package
[2020-10-01T16:46:44.720Z] Done
[2020-10-01T16:46:44.720Z] Run system tests for the package
[2020-10-01T16:46:44.720Z] Done
[2020-10-01T16:46:44.720Z] packages/zeek:
[2020-10-01T16:46:44.720Z] elastic-package test
[2020-10-01T16:46:44.720Z] Run test suite for the package
[2020-10-01T16:46:44.720Z] Run pipeline tests for the package
[2020-10-01T16:46:44.720Z] Done
[2020-10-01T16:46:44.720Z] Run system tests for the package
[2020-10-01T16:46:44.720Z] Done
[2020-10-01T16:46:44.720Z] packages/zookeeper:
[2020-10-01T16:46:44.720Z] elastic-package test
[2020-10-01T16:46:44.720Z] Run test suite for the package
[2020-10-01T16:46:44.720Z] Run pipeline tests for the package
[2020-10-01T16:46:44.720Z] Done
[2020-10-01T16:46:44.720Z] Run system tests for the package
[2020-10-01T16:46:44.720Z] Done
[2020-10-01T16:46:44.720Z] packages/zoom:
[2020-10-01T16:46:44.720Z] elastic-package test
[2020-10-01T16:46:44.720Z] Run test suite for the package
[2020-10-01T16:46:44.720Z] Run pipeline tests for the package
[2020-10-01T16:46:44.720Z] Done
[2020-10-01T16:46:44.720Z] Run system tests for the package
[2020-10-01T16:46:44.720Z] Done
[2020-10-01T16:46:44.720Z] elastic-package stack down
[2020-10-01T16:46:44.720Z] Take down the Elastic stack
[2020-10-01T16:46:44.720Z] Done
[2020-10-01T16:46:44.720Z] packages/zoom/dataset/webhook/fields/fields.yml: needs update
[2020-10-01T16:46:44.720Z] packages/zoom/dataset/webhook/manifest.yml: needs update
[2020-10-01T16:46:44.720Z] packages/zoom/manifest.yml: needs update
[2020-10-01T16:46:44.720Z] Error: running "git update-index --refresh" failed with exit code 1
[2020-10-01T16:46:44.865Z] Stage "Update Package Storage" skipped due to earlier failure(s)
[2020-10-01T16:46:45.073Z] Running on Jenkins in /var/lib/jenkins/workspace/Beats_integrations_PR-284
[2020-10-01T16:46:45.187Z] [INFO] getVaultSecret: Getting secrets
[2020-10-01T16:46:45.267Z] Masking supported pattern matches of $VAULT_ADDR or $VAULT_ROLE_ID or $VAULT_SECRET_ID
[2020-10-01T16:46:46.049Z] + chmod 755 generate-build-data.sh
[2020-10-01T16:46:46.049Z] + ./generate-build-data.sh https://beats-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/Beats/integrations/PR-284/ https://beats-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/Beats/integrations/PR-284/runs/1 FAILURE 231696
[2020-10-01T16:46:46.049Z] INFO: curl https://beats-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/Beats/integrations/PR-284/runs/1/steps/?limit=10000 -o steps-info.json
[2020-10-01T16:46:46.300Z] INFO: curl https://beats-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/Beats/integrations/PR-284/runs/1/tests/?status=FAILED -o tests-errors.json

```

</p>
</details>



<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2020-10-01 18:32 UTC, andrewkroh approved these changes
LGTM

2020-10-02 06:29 UTC, mtojek requested changes
Please adjust the PR accordingly to changes introduced in https://github.com/elastic/integrations/pull/280 .

Main changes:

0. Rebase against master.
1. Rename "dataset" folder to "data_stream".
2. Rename "config_templates" to "policy_templates" in package manifest file.

2020-10-02 07:10 UTC, elasticmachine commented
Pinging @elastic/siem (Team:SIEM)

2020-10-02 09:33 UTC, merged