Update ecs verion to 8.2 and implementing best practice for ingesting…
elastic/integrations pull request #2841
Opened 2022-03-17 13:42 UTC by djordje-adzemovic-devtech

… email fields in pipelines

## What does this PR do?

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2022-03-17 13:45 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2841/detail/PR-2841/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2841/detail/PR-2841/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2841/detail/PR-2841/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2841/detail/PR-2841/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-03-17T13:33:11.912Z&rangeTo=2022-03-17T13:53:11.912Z&transactionName=BUILD+Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=d806c81c04808e1ff96993d1a6a2092d&transactionId=ca2d11f45a5863b2)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-03-17T13:43:11.912+0000


* Duration: 3 min 30 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2841/detail/PR-2841/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-2841/runs/1/steps/107/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-03-17 21:44 UTC, efd6 requested changes

2022-03-17 21:44 UTC, efd6 commented on packages/mimecast/data_stream/dlp_logs/elasticsearch/ingest_pipeline/default.yml
> +#       if: 'ctx?.mimecast?.recipientAddress !=null'
Please clean up these commented out blocks.

2022-03-17 21:44 UTC, efd6 commented on packages/mimecast/data_stream/siem_logs/elasticsearch/ingest_pipeline/default.yml
> +#       if: 'ctx?.mimecast?.Sender !=null'
Please clean this up and below.

2022-03-17 21:44 UTC, efd6 commented on packages/mimecast/data_stream/ttp_ap_logs/elasticsearch/ingest_pipeline/default.yml
> +#       if: 'ctx?.mimecast?.recipientAddress !=null'
Please clean up these commented blocks.

2022-03-17 21:44 UTC, efd6 commented on packages/mimecast/data_stream/ttp_ip_logs/elasticsearch/ingest_pipeline/default.yml
> +#       ignore_missing: true
Commented block here and below.

2022-03-17 21:44 UTC, efd6 commented on packages/mimecast/data_stream/ttp_url_logs/elasticsearch/ingest_pipeline/default.yml
> +#       ignore_missing: true
Commented block.

2022-03-17 21:44 UTC, efd6 commented
/test

2022-03-18 09:09 UTC, efd6 commented
/test

2022-03-18 14:21 UTC, taylor-swanson commented on packages/mimecast/data_stream/audit_events/elasticsearch/ingest_pipeline/default.yml
> +      ignore_failure: true
As mentioned above, these can be replaced by a `set` processor instead of `rename`/`append`:

```yaml
- set:
    field: email.from.address
    value: ["{{{email.from.address}}}"]
    if: "ctx?.email?.from?.address != null"
```

2022-03-18 14:21 UTC, taylor-swanson commented on packages/mimecast/data_stream/audit_events/elasticsearch/ingest_pipeline/default.yml
> +        - email.from.addr
No longer necessary if implementing steps above.

2022-03-20 23:29 UTC, efd6 commented
Please run `elastic-package build` to bring the README.md up-to-date.

2022-03-21 14:18 UTC, taylor-swanson approved these changes
LGTM

2022-03-21 23:58 UTC, efd6 commented on packages/mimecast/data_stream/audit_events/elasticsearch/ingest_pipeline/default.yml
> -        - mimecast.rest_of_event_info
Please add this line back in.

2022-03-28 02:10 UTC, efd6 commented
/test

2022-03-28 02:36 UTC, efd6 commented
@djordje-adzemovic-devtech You will need to update the generated docs: `README.md is outdated. Rebuild the package with 'elastic-package build'` from the CI.

2022-03-30 09:18 UTC, djordje-adzemovic-devtech commented
Is this ok to be merged? @efd6 @taylor-swanson

2022-03-30 21:11 UTC, andrewkroh commented on packages/mimecast/docs/README.md
> +                "\u003c\u003e"
Maybe the pipeline should drop these `<>`. I assume that's an empty address and omitting the field would carry the same meaning.

2022-03-30 21:13 UTC, andrewkroh commented
/test

2022-03-30 21:37 UTC, efd6 commented on packages/mimecast/docs/README.md
> +                "\u003c\u003e"
I was thinking similarly.

2022-03-31 07:46 UTC, djordje-adzemovic-devtech commented on packages/mimecast/docs/README.md
> +                "\u003c\u003e"
I will do this here.

2022-03-31 22:06 UTC, efd6 commented on packages/mimecast/docs/README.md
> +                "\u003c\u003e"
@djordje-adzemovic-devtech If the address ends up being `""` it should probably be dropped from the array and if the array ends up being empty as a result it should be dropped from the object.

2022-04-01 12:18 UTC, djordje-adzemovic-devtech commented on packages/mimecast/docs/README.md
> +                "\u003c\u003e"
@efd6 In general, I agree. But in this case, possibly if I left "" as address it has some meaning for person analyzing the logs. Mimecast does not complain about <> neither.
I can implement that, but then I would like to change sample event with some log that has value, because this is docs file and I would like to present as much properties as possible.

2022-04-03 22:54 UTC, efd6 commented on packages/mimecast/data_stream/dlp_logs/_dev/test/pipeline/test-dlp-logs.log-expected.json
>                  },
Drop these in the case that they are an empty `<>`? (for other data streams as well).

2022-04-03 22:54 UTC, efd6 commented
/test

2022-04-05 12:02 UTC, djordje-adzemovic-devtech commented on packages/mimecast/data_stream/dlp_logs/_dev/test/pipeline/test-dlp-logs.log-expected.json
>                  },
@efd6 This makes sense in general, but in context of Mimecast integration does not, because if it is present and it is empty it still says something the one who uses this integration (if address is empty that means that it is postmaster email address - there are solid amount of ;ogs with this case). I check with Mimecast and they are rather to keep it even if it is empty. Can we proceed with review and not to touch this?

2022-04-05 23:37 UTC, andrewkroh approved these changes

2022-04-05 23:38 UTC, andrewkroh approved these changes
LGTM. Will wait for an approval from @efd6 then it can be merged.

2022-04-06 01:17 UTC, efd6 approved these changes
Thanks

2022-04-06 01:23 UTC, merged