[m365_defender] New Package
elastic/integrations pull request #2854
Opened 2022-03-21 12:23 UTC by P1llus

## What does this PR do?

This copies over the m365_defender filebeat fileset over to its own package, with some smaller modifications.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

2022-03-21 12:23 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2022-03-21 12:28 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2854/detail/PR-2854/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2854/detail/PR-2854/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2854/detail/PR-2854/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2854/detail/PR-2854/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_2854.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-03-21T12:14:08.084Z&rangeTo=2022-03-21T12:34:08.084Z&transactionName=BUILD+Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=db8a37c9ecb104a13c95b4c62afda402&transactionId=00df241452b0529e)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-03-21T12:24:08.084+0000


* Duration: 4 min 41 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2854/detail/PR-2854/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Checks and builds Go sources`
<ul>
<li>Took 0 min 17 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-2854/runs/1/steps/140/log/?start=0">here</a></li>
<li>Description: <code>mage -debug check</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-2854/runs/1/steps/157/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-03-21 12:38 UTC, marc-gr commented on packages/m365_defender/data_stream/log/_dev/test/pipeline/test-m365-defender-empty-ndjson.log-expected.json
> +                "comments": [],
nit: We could remove this as part of the cleanup processor in the pipeline

2022-03-21 16:46 UTC, adriansr requested changes
A few questions and small things.

2022-03-21 16:46 UTC, adriansr commented on packages/m365_defender/data_stream/log/elasticsearch/ingest_pipeline/default.yml
> +      if: ctx.json?.severity == 'Unspecified'
In the test logs and the documentation this seems to be "UnSpecified", with a capital S.

Also, I'm wondering, if an unspecified severity should be mapped at all, or it's better to leave the field unset.

2022-03-21 16:46 UTC, adriansr commented on packages/m365_defender/data_stream/log/elasticsearch/ingest_pipeline/default.yml
> +      if: ctx.json?.alerts != null && ctx.json?.alerts?.description != null && ctx.json?.alerts?.description.length() < 1020
Some checks are redundant.
```suggestion
      if: ctx.json?.alerts?.description != null && ctx.json.alerts.description.length() < 1020
```

I wonder why rename only when the length doesn't exceed 1020 chars? Maybe we want to truncate instead.

2022-03-21 16:46 UTC, adriansr commented on packages/m365_defender/data_stream/log/fields/fields.yml
> +    Module for ingesting Microsoft Defender ATP.
Description needs an update

2022-03-22 08:15 UTC, P1llus commented on packages/m365_defender/data_stream/log/agent/stream/httpjson.yml.hbs
> +  - "https://api.security.microsoft.com/.default"
In general this should never change, the option for request/login_url was mostly added in to support system tests, But I wouldn't mind adding it in just in case.

2022-03-22 08:17 UTC, P1llus commented on packages/m365_defender/data_stream/log/elasticsearch/ingest_pipeline/default.yml
> +      lang: painless
I added a description and also moved it further down the pipeline, as it was not catching all cases.

2022-03-23 11:12 UTC, adriansr approved these changes
LGTM

2022-03-23 11:14 UTC, merged