initial commit for adding Microsoft Threat Protection package
elastic/integrations pull request #286
Opened 2020-10-02 12:57 UTC by P1llus

## What does this PR do?

This PR adds a package for a new module related to Microsoft Threat Protection that can be followed here: https://github.com/elastic/beats/pull/21446

## Related issues

<!-- Recommended
Link related issues below. Insert the issue link or reference after the word "Closes" if merging this should automatically close it.

- Related #elastic/beats#21446

2020-10-02 13:00 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fintegrations%2FPR-286/detail/PR-286/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fintegrations%2FPR-286/detail/PR-286/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fintegrations%2FPR-286/detail/PR-286/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fintegrations%2FPR-286/detail/PR-286/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_286.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats

* Build Cause: `[Pull request #286 opened]`

* Start Time: 2020-10-02T12:58:01.803+0000

* Duration: 3 min 38 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY-->


### Steps errors

  <details><summary>Expand to view the steps failures</summary>
  <p>
  
  * **Name**: `Checks and builds integration sources`
    * Description: mage -debug check
    
    * Duration: 0 min 24 sec
    
    * Start Time: 2020-10-02T13:00:14.337+0000
    
    * [log](https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/integrations/pipelines/PR-286/runs/1/steps/114/log)
    
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2020-10-02T13:00:37.156Z] Done
[2020-10-02T13:00:37.156Z] packages/redis:
[2020-10-02T13:00:37.156Z] elastic-package format
[2020-10-02T13:00:37.156Z] Format the package
[2020-10-02T13:00:37.156Z] Done
[2020-10-02T13:00:37.156Z] packages/suricata:
[2020-10-02T13:00:37.156Z] elastic-package format
[2020-10-02T13:00:37.156Z] Format the package
[2020-10-02T13:00:37.156Z] Done
[2020-10-02T13:00:37.156Z] packages/synthetics:
[2020-10-02T13:00:37.156Z] elastic-package format
[2020-10-02T13:00:37.156Z] Format the package
[2020-10-02T13:00:37.156Z] Done
[2020-10-02T13:00:37.156Z] packages/system:
[2020-10-02T13:00:37.156Z] elastic-package format
[2020-10-02T13:00:37.156Z] Format the package
[2020-10-02T13:00:37.156Z] Done
[2020-10-02T13:00:37.156Z] packages/windows:
[2020-10-02T13:00:37.156Z] elastic-package format
[2020-10-02T13:00:37.156Z] Format the package
[2020-10-02T13:00:37.156Z] Done
[2020-10-02T13:00:37.156Z] packages/zeek:
[2020-10-02T13:00:37.156Z] elastic-package format
[2020-10-02T13:00:37.156Z] Format the package
[2020-10-02T13:00:37.416Z] Done
[2020-10-02T13:00:37.416Z] packages/zookeeper:
[2020-10-02T13:00:37.416Z] elastic-package format
[2020-10-02T13:00:37.416Z] Format the package
[2020-10-02T13:00:37.416Z] Done
[2020-10-02T13:00:37.416Z] packages/zoom:
[2020-10-02T13:00:37.416Z] elastic-package format
[2020-10-02T13:00:37.416Z] Format the package
[2020-10-02T13:00:37.416Z] Done
[2020-10-02T13:00:37.416Z] packages/apache:
[2020-10-02T13:00:37.416Z] elastic-package lint
[2020-10-02T13:00:37.416Z] Lint the package
[2020-10-02T13:00:37.416Z] Done
[2020-10-02T13:00:37.416Z] packages/aws:
[2020-10-02T13:00:37.416Z] elastic-package lint
[2020-10-02T13:00:37.416Z] Lint the package
[2020-10-02T13:00:37.416Z] Done
[2020-10-02T13:00:37.416Z] packages/checkpoint:
[2020-10-02T13:00:37.416Z] elastic-package lint
[2020-10-02T13:00:37.416Z] Lint the package
[2020-10-02T13:00:37.677Z] Done
[2020-10-02T13:00:37.677Z] packages/cisco:
[2020-10-02T13:00:37.677Z] elastic-package lint
[2020-10-02T13:00:37.677Z] Lint the package
[2020-10-02T13:00:37.677Z] Done
[2020-10-02T13:00:37.677Z] packages/crowdstrike:
[2020-10-02T13:00:37.677Z] elastic-package lint
[2020-10-02T13:00:37.677Z] Lint the package
[2020-10-02T13:00:37.677Z] Done
[2020-10-02T13:00:37.677Z] packages/fortinet:
[2020-10-02T13:00:37.677Z] elastic-package lint
[2020-10-02T13:00:37.677Z] Lint the package
[2020-10-02T13:00:37.677Z] Done
[2020-10-02T13:00:37.677Z] packages/haproxy:
[2020-10-02T13:00:37.677Z] elastic-package lint
[2020-10-02T13:00:37.677Z] Lint the package
[2020-10-02T13:00:37.677Z] Done
[2020-10-02T13:00:37.677Z] packages/iis:
[2020-10-02T13:00:37.677Z] elastic-package lint
[2020-10-02T13:00:37.677Z] Lint the package
[2020-10-02T13:00:37.677Z] Done
[2020-10-02T13:00:37.677Z] packages/kafka:
[2020-10-02T13:00:37.677Z] elastic-package lint
[2020-10-02T13:00:37.677Z] Lint the package
[2020-10-02T13:00:37.938Z] Done
[2020-10-02T13:00:37.938Z] packages/kubernetes:
[2020-10-02T13:00:37.938Z] elastic-package lint
[2020-10-02T13:00:37.938Z] Lint the package
[2020-10-02T13:00:37.938Z] Done
[2020-10-02T13:00:37.938Z] packages/linux:
[2020-10-02T13:00:37.938Z] elastic-package lint
[2020-10-02T13:00:37.938Z] Lint the package
[2020-10-02T13:00:37.938Z] Done
[2020-10-02T13:00:37.938Z] packages/log:
[2020-10-02T13:00:37.938Z] elastic-package lint
[2020-10-02T13:00:37.938Z] Lint the package
[2020-10-02T13:00:37.938Z] Done
[2020-10-02T13:00:37.938Z] packages/microsoft:
[2020-10-02T13:00:37.938Z] elastic-package lint
[2020-10-02T13:00:37.938Z] Lint the package
[2020-10-02T13:00:37.938Z] Error: linting package failed: found 3 validation errors:
[2020-10-02T13:00:37.938Z]    1. file "/var/lib/jenkins/workspace/Beats_integrations_PR-286/src/github.com/elastic/integrations/packages/microsoft/manifest.yml" is invalid: field screenshots.0: Additional property path is not allowed
[2020-10-02T13:00:37.938Z]    2. file "/var/lib/jenkins/workspace/Beats_integrations_PR-286/src/github.com/elastic/integrations/packages/microsoft/manifest.yml" is invalid: field screenshots.1: Additional property path is not allowed
[2020-10-02T13:00:37.938Z]    3. file "/var/lib/jenkins/workspace/Beats_integrations_PR-286/src/github.com/elastic/integrations/packages/microsoft/manifest.yml" is invalid: field screenshots.2: Additional property path is not allowed
[2020-10-02T13:00:37.938Z] 
[2020-10-02T13:00:37.938Z] Error: running elastic-package failed: running "/var/lib/jenkins/workspace/Beats_integrations_PR-286/src/github.com/elastic/integrations/build/elastic-package lint" failed with exit code 1
[2020-10-02T13:00:38.096Z] Stage "Update Package Storage" skipped due to earlier failure(s)
[2020-10-02T13:00:38.573Z] Running on Jenkins in /var/lib/jenkins/workspace/Beats_integrations_PR-286
[2020-10-02T13:00:38.822Z] [INFO] getVaultSecret: Getting secrets
[2020-10-02T13:00:38.906Z] Masking supported pattern matches of $VAULT_ADDR or $VAULT_ROLE_ID or $VAULT_SECRET_ID
[2020-10-02T13:00:39.682Z] + chmod 755 generate-build-data.sh
[2020-10-02T13:00:39.682Z] + ./generate-build-data.sh https://beats-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/Beats/integrations/PR-286/ https://beats-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/Beats/integrations/PR-286/runs/1 FAILURE 157605
[2020-10-02T13:00:39.682Z] INFO: curl https://beats-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/Beats/integrations/PR-286/runs/1/steps/?limit=10000 -o steps-info.json
[2020-10-02T13:00:39.932Z] INFO: curl https://beats-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/Beats/integrations/PR-286/runs/1/tests/?status=FAILED -o tests-errors.json
[2020-10-02T13:00:39.932Z] Retry 1/3 exited 22, retrying in 1 seconds...
[2020-10-02T13:00:41.276Z] Retry 2/3 exited 22, retrying in 2 seconds...

```

</p>
</details>



<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2020-10-02 13:03 UTC, elasticmachine commented
Pinging @elastic/siem (Team:SIEM)

2020-10-02 13:08 UTC, mtojek commented
Let's convert it to draft to prevent from accidental merge.

2020-10-02 13:16 UTC, mtojek commented
I checked out your PR and found out some issue.  I fixed them with the `mage check` command (https://github.com/mtojek/integrations/commit/b7d58f0d649f76398cc8707bbfe5536d2a43b9f5).

Regarding docs, please use the template file: https://github.com/elastic/integrations/blob/master/dev/import-beats-resources/microsoft/docs/README.md . This file is a template for the package's README.

You can either use the `testing/environment` stack or try the relatively fresh tool to work with integrations: https://github.com/elastic/elastic-package . Once you install it according to the README instruction, simply navigate to the `packages/microsoft` and run:

```
elastic-package build
elastic-package stack up -d
```

^ this command will bring up the Elastic stack with modified Microsoft package and spawn the Elastic Agent (all as docker images).

Please be aware that we need to wait for the new Kibana snapshot image, which will support data stream and policy templates (last renaming operation). I hope it's a matter day as snapshots are built on daily basis.

To update stack images you can use:

```
elastic-package stack update -v
```

If you have any questions about integrations and elastic-package tool, feel free to mention @ycombinator or me.

2020-10-02 13:18 UTC, P1llus commented
Thanks for your comments @mtojek !

For the documentation, the Microsoft Package already existed, but the module had some new datasets added to it, so when using ImportBeats it overrides certain parts of the documentation, however I restored the format of the documentation back to its original form, so it's a bit weird that the documentation which was already in master was wrong.

No worries though, learning experience for me! Will go through your steps and documentation later today to apply the fixes :+1:

2020-10-02 13:21 UTC, mtojek commented
> so when using ImportBeats it overrides certain parts of the documentation

Yes, ideally the ImportBeats target should be used only once to import all the stuff you need. Otherwise there is a risk to override/lose your changes.

Please be aware that the elastic-package (used internally via mage) is still experimental, so it may not be perfect. We appreciate any feedback on this one.

2020-10-19 08:38 UTC, mtojek commented on packages/microsoft/manifest.yml
>    github: elastic/security-external-integrations
You have two same Github keys defined.

2020-10-19 08:40 UTC, P1llus commented on packages/microsoft/manifest.yml
>    github: elastic/security-external-integrations
Yeah just fixing it up, but docker builds are not coming up which im trying to fix first. With both elastic-package and the "old" way.

mage check:
```
2020/10/19 10:33:48 Notice: the template file "dev/import-beats-resources/log/docs/README.md" does not exist. The README.md file will not be rendered.
>> mod - updating vendor directory
elastic-package stack up -d
Boot up the Elastic stack
Custom build packages directory found: /home/marius/go/src/github.com/elastic/integrations/build/integrations
Error: booting up the stack failed: running docker-compose failed: running command failed: running Docker Compose up command failed: exit status 1
Error: running elastic-package failed: running "/home/marius/go/src/github.com/elastic/integrations/build/elastic-package stack up -d" failed with exit code 
```

2020-10-19 08:43 UTC, mtojek commented on packages/microsoft/manifest.yml
>    github: elastic/security-external-integrations
Try to run:

```bash
rm -rf ~/.elastic-package/
elastic-package stack update -v
```

It's always good to verify it with the CI, which should always use latest Docker images.

2020-10-19 08:47 UTC, P1llus commented on packages/microsoft/manifest.yml
>    github: elastic/security-external-integrations
By the way, if a mage check fails on docker, it will not kill the running containers, so you will end up with something like this:

```
docker ps
CONTAINER ID        IMAGE                                                           COMMAND                  CREATED             STATUS                    PORTS                                NAMES
5c7617fb2eed        elastic-package-stack_package-registry                          "./package-registry …"   13 minutes ago      Up 12 minutes (healthy)   127.0.0.1:8080->8080/tcp             elastic-package-stack_package-registry_1
954a961924da        docker.elastic.co/elasticsearch/elasticsearch:7.10.0-SNAPSHOT   "/tini -- /usr/local…"   13 minutes ago      Up 12 minutes (healthy)   127.0.0.1:9200->9200/tcp, 9300/tcp   elastic-package-stack_elasticsearch_1
```

2020-10-19 08:51 UTC, P1llus commented on packages/microsoft/manifest.yml
>    github: elastic/security-external-integrations
> Try to run:
> 
> ```shell
> rm -rf ~/.elastic-package/
> elastic-package stack update -v
> ```
> 
> It's always good to verify it with the CI, which should always use latest Docker images.

This resolved my docker issues, will try to push a new complete commit soon once tested.

2020-10-19 10:32 UTC, mtojek commented
@P1llus let us know when the PR is ready for review (currentyl it's marked as draft).

2020-10-19 11:05 UTC, P1llus commented
@mtojek will let you know! Need to go through it with someone from the security ingest team later today first, too many small things to currently cover on comments and I want to ensure it follows the same convention we use for our other security packages.
That way I can apply that to all the packages I have in the pipeline :)

2020-11-23 08:25 UTC, mtojek requested changes
As there were incompatible changes pushed to the master branch (PR: https://github.com/elastic/integrations/pull/410), please rebase this PR against the master branch.

Long story short: `dev/import-beats-resources/microsoft/docs/README.md` is `packages/microsoft/_dev/build/docs/README.md` now.

2020-12-07 12:06 UTC, closed without merging