Fix propagation of information from host.name
elastic/integrations pull request #2915
Opened 2022-03-30 07:55 UTC by LaZyDK

## What does this PR do?
Propagating information from the host.name field. 
Also taking into account that `Install Started` events use the `cisco.secure_endpoint.hostname` field.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

2022-03-30 07:58 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2915/detail/PR-2915/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2915/detail/PR-2915/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2915/detail/PR-2915/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2915/detail/PR-2915/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-03-30T07:45:36.273Z&rangeTo=2022-03-30T08:05:36.273Z&transactionName=BUILD+Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=07e92862beb0cf96e0570bfc19bab141&transactionId=37df02cf8cc2c711)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-03-30T07:55:36.273+0000


* Duration: 2 min 23 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2915/detail/PR-2915/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-2915/runs/1/steps/107/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-03-30 09:50 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2022-03-30 21:01 UTC, andrewkroh commented
/test

2022-03-30 21:01 UTC, andrewkroh commented on packages/cisco_secure_endpoint/changelog.yml
> +- version: "2.1.1"
To follow semantic versioning, a `type: enhancement` would usually mean version 2.2.0.

```suggestion
- version: "2.2.0"
```

2022-04-04 14:16 UTC, P1llus commented
/test

2022-04-06 00:07 UTC, andrewkroh requested changes
We need some test data to validate the new command_line parsing script processors. 

I pushed some updates to make the pipeline valid, added descriptions, added two missing event.* fields, and generated the pipeline test data.

2022-04-06 00:07 UTC, andrewkroh commented on packages/cisco_secure_endpoint/data_stream/event/elasticsearch/ingest_pipeline/default.yml
> +      def commandLine = ctx?.cisco?.secure_endpoint?.command_line?.arguments;
It looks like we don't have any sample events that contain this field so this is untested. Do you have a sample that you can contribute to the tests in `packages/cisco_secure_endpoint/data_stream/event/_dev/test/pipeline`?

2022-04-06 00:26 UTC, andrewkroh commented
/test

2022-04-06 16:08 UTC, andrewkroh commented on packages/cisco_secure_endpoint/data_stream/event/elasticsearch/ingest_pipeline/default.yml
> +      def commandLine = ctx?.cisco?.secure_endpoint?.command_line?.arguments;
Thanks the tests surfaced a bug with the `removeIf` not working because the Arrays.asList returns a collection that does not support `remove()`. I modified the code, but preserved the same behavior.

2022-04-06 16:09 UTC, andrewkroh approved these changes

2022-04-06 16:39 UTC, andrewkroh commented on packages/cisco_secure_endpoint/data_stream/event/_dev/test/pipeline/test-cisco-amp1.log-expected.json
> -                "hostname": "Demo_Qakbot_1",
I think this was unintentional? It seems like in the case where the host name is not qualified with a domain that the events lose their `host.hostname`.

2022-04-06 16:48 UTC, LaZyDK commented on packages/cisco_secure_endpoint/data_stream/event/_dev/test/pipeline/test-cisco-amp1.log-expected.json
> -                "hostname": "Demo_Qakbot_1",
Yes. In that case we need to copy the host.name to host.hostname.

2022-04-06 17:48 UTC, LaZyDK commented
/test

2022-04-06 18:01 UTC, andrewkroh approved these changes

2022-04-06 18:56 UTC, merged