Update readme.md
elastic/integrations pull request #2918
Opened 2022-03-30 09:29 UTC by cherryleaf

Markdown tidy up

Type of change
- Enhancement

## What does this PR do?

Tidy up of the markdown in the readme file. 

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2022-03-30 09:32 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2918/detail/PR-2918/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2918/detail/PR-2918/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2918/detail/PR-2918/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2918/detail/PR-2918/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-03-30T09:20:02.865Z&rangeTo=2022-03-30T09:40:02.865Z&transactionName=BUILD+Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=2234651e3c3e04a18405ce64b39e251f&transactionId=513ab46f21592d9b)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-03-30T09:30:02.865+0000


* Duration: 2 min 23 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2918/detail/PR-2918/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-2918/runs/1/steps/107/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-03-30 09:49 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2022-03-31 00:11 UTC, efd6 commented on packages/zscaler_zpa/docs/README.md
> +>  Note: Please make sure to use the given response formats.
```suggestion
Note: Please make sure to use the provided response formats.
```

2022-04-08 10:12 UTC, GinnyGalicia commented on packages/zscaler_zpa/docs/README.md
> +>  Note: Please make sure to use the given response formats.
If the > is used, it should generate a Markdown admonition note box.

2022-04-14 09:06 UTC, cherryleaf commented on packages/zscaler_zpa/docs/README.md
> +>  Note: Please make sure to use the given response formats.
I've changed this to Elastic's `<DocCallOut title="Note">` tag

2022-04-27 21:30 UTC, bmorelli25 requested changes
The manifest version needs to be updated to `0.2.1`

2022-04-27 21:31 UTC, bmorelli25 commented on packages/zscaler_zpa/docs/README.md
> +>  Note: Please make sure to use the given response formats.
Unfortunately the `<DocCallOut title="Note">` don't work in `.md` files and are specifically for our `.mdx` files. Can you change this back please?

2022-04-28 14:34 UTC, closed without merging

2022-04-28 14:34 UTC, cherryleaf commented
Cannot resolve