[IBM WebSphere Application Server] Add WebSphere Application Server Integration Package
elastic/integrations pull request #2922
Opened 2022-03-30 12:04 UTC by kush-elastic

- Enhancement

## What does this PR do?

- Skeleton of IBM WebSphere Application Server Integration with JDBC data-stream.
- Added official Docker image of [IBM WebSphere Application Server](https://hub.docker.com/r/ibmcom/websphere-traditional/) for system testing
- Docker takes 8 to 15 min to startup with `healthy` status as elastic-package's minimum timeout for docker container is 10 minutes, therefore sometimes system tests can't go further (with throwing timeout error). is there any way to use custom timeout in elastic-package?

- We are thinking of following data-streams as Part of V1 Scope:
1. JDBC
2. Servelet
3. ThreadPool
4. Session Manager

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's changelog.yml file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally

- Clone integrations repo.
- Install elastic-package locally.
- Start elastic stack using elastic-package.
- Move to integrations/packages/nagios directory.
- Run the following command to run tests.
- elastic-package test

## Related issues

- Relates #2847

2022-03-30 12:08 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2922/detail/PR-2922/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2922/detail/PR-2922/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2922/detail/PR-2922/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2922/detail/PR-2922/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_2922.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-03-30T11:55:02.278Z&rangeTo=2022-03-30T12:15:02.278Z&transactionName=BUILD+Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=7135b6c127b6bf4a57cc8fcdcdaad216&transactionId=7e070d2380f373bc)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-03-30T12:05:02.278+0000


* Duration: 4 min 41 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2922/detail/PR-2922/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Checks and builds Go sources`
<ul>
<li>Took 0 min 14 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-2922/runs/1/steps/140/log/?start=0">here</a></li>
<li>Description: <code>mage -debug check</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-2922/runs/1/steps/157/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-04-25 06:38 UTC, kush-elastic commented
/test

2022-05-11 07:12 UTC, yug-elastic requested changes
Requested some changes

2022-05-11 07:12 UTC, yug-elastic commented on packages/websphere_application_server/docs/README.md
> +This Elastic integration is used to collect [IBM WebSphere Application Server](https://www.ibm.com/cloud/websphere-application-server) metrics as follows:
nit: 
```
This Elastic integration is used to collect the following metrics from [IBM WebSphere Application Server](https://www.ibm.com/cloud/websphere-application-server):
```

2022-05-11 07:12 UTC, yug-elastic commented on packages/websphere_application_server/manifest.yml
> +description: This Elastic integration collects metrics from WebSphere Application Server.
Please adjust the description as per https://github.com/elastic/integrations/pull/2614#discussion_r860162158

2022-05-11 07:12 UTC, yug-elastic commented on packages/websphere_application_server/manifest.yml
> +            description: WebSphere Application Server Host. (http://localhost:9080 or localhost:9080).
nit: `WebSphere Application Server Host (http://localhost:9080 or localhost:9080).`

2022-05-11 07:59 UTC, kush-elastic commented on packages/websphere_application_server/data_stream/jdbc/_dev/test/pipeline/test-jdbc-metrics.json-expected.json
> +                "prometheus"
We're giving user input [tags](https://github.com/kush-elastic/integrations/blob/package_websphere_application_server_jdbc/packages/websphere_application_server/data_stream/jdbc/manifest.yml#L14) where default value contains this tag if user want to keep it.

2022-05-11 08:16 UTC, yug-elastic commented on packages/websphere_application_server/data_stream/jdbc/_dev/test/pipeline/test-jdbc-metrics.json-expected.json
> +                "prometheus"
Got it, thanks for clarifying!

2022-05-11 08:57 UTC, yug-elastic approved these changes
Thanks for making the adjustments, @kush-elastic. LGTM!
Please make the changes suggested in this PR (if applicable) to the other IBM WAS PRs as well.

2022-05-11 10:51 UTC, kush-elastic commented
/test

2022-05-18 12:21 UTC, kush-elastic commented on packages/websphere_application_server/data_stream/jdbc/elasticsearch/ingest_pipeline/default.yml
> +      ignore_missing: true
Elastic has a standard field naming convention: https://www.elastic.co/guide/en/beats/devguide/current/event-conventions.html and we've been following the same standards throughout all the integration. All the fields that we are extracting in this integration also follows the same naming standards. Please refer to the shared doc and let me know if you still think we should change it.
CC: @akshay-saraswat

2022-05-18 12:21 UTC, kush-elastic commented on packages/websphere_application_server/data_stream/jdbc/elasticsearch/ingest_pipeline/default.yml
> +      ignore_missing: true
Please refer to the reply: https://github.com/elastic/integrations/pull/2922#discussion_r875824695

2022-05-18 18:30 UTC, kush-elastic commented on packages/websphere_application_server/data_stream/jdbc/elasticsearch/ingest_pipeline/default.yml
> +      lang: painless
I guess you should [refer this](https://github.com/elastic/integrations/pull/3066#discussion_r866704272) for drop processor discussion.

2022-05-19 04:27 UTC, kush-elastic commented on packages/websphere_application_server/_dev/deploy/docker/docker-compose.yml
> +    image: ibmcom/websphere-traditional:9.0.5.10
Sure, I have update new image. Please check it out.

2022-05-19 05:31 UTC, ishleenk17 commented on packages/websphere_application_server/data_stream/jdbc/elasticsearch/ingest_pipeline/default.yml
> +      ignore_missing: true
Thanks for the clarification.

2022-05-19 10:25 UTC, ishleenk17 commented on packages/websphere_application_server/data_stream/jdbc/fields/base-fields.yml
> +  description: Event timestamp.
It is always a good practice to have the event.* fields have their values populated in base-fields.yml.
Please refer to this as example:
https://github.com/elastic/integrations/blob/main/packages/prometheus/data_stream/collector/fields/base-fields.yml

2022-05-19 10:50 UTC, kush-elastic commented on packages/websphere_application_server/data_stream/jdbc/fields/base-fields.yml
> +  description: Event timestamp.
We have followed [this](https://www.elastic.co/guide/en/integrations-developer/current/add-a-mapping.html#:~:text=base%2Dfields.yml%20never%20changes%20and%20is%20required%20for%20all%20integrations) from integration developer guide.
if you still think we should change this please let us know.

2022-05-19 12:32 UTC, ishleenk17 commented on packages/websphere_application_server/data_stream/jdbc/fields/base-fields.yml
> +  description: Event timestamp.
This would mean that the existing fields in it will never change.
But the newer fields can be added. That's what is followed through all the integrations in Elastic.

2022-05-19 12:48 UTC, kush-elastic commented on packages/websphere_application_server/data_stream/jdbc/fields/base-fields.yml
> +  description: Event timestamp.
Okay, Thanks. will update it soon.

2022-05-20 05:42 UTC, kush-elastic commented
Hey @ishleenk17, thanks for the review! We have addressed all the review comments and made the required changes and re-requested review. Could you please take a look at the PR again and let us know if you think we should change anything else before we can have an approval from you over the PR?

2022-05-20 07:20 UTC, ishleenk17 commented
Looks good. Approved!

2022-05-20 07:21 UTC, ishleenk17 approved these changes

2022-05-20 07:45 UTC, merged