update cisco_umbrella readme
elastic/integrations pull request #2936
Opened 2022-03-30 14:15 UTC by cherryleaf

Added link to Cisco's documentation

Type of change

- Enhancement

## What does this PR do?

Added link to Cisco's documentation

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2022-03-30 23:55 UTC, efd6 commented
/test

2022-03-31 01:47 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2022-04-07 18:42 UTC, bmorelli25 requested changes
@cherryleaf, there are new changes to this integration. Please merge with main and update the changelog and manifest accordingly.

2022-04-08 08:27 UTC, cherryleaf commented on packages/cisco_umbrella/changelog.yml
> +    - description: Update to readmen file
Done

2022-04-08 08:27 UTC, cherryleaf commented
I think I've made the changes

2022-04-28 15:04 UTC, cherryleaf commented
Cannot resolve

2022-04-28 15:04 UTC, closed without merging