Update cockroachdb readme
elastic/integrations pull request #2938
Opened 2022-03-30 15:14 UTC by cherryleaf

Added link to cockroach's documentation

Type of change

- Enhancement

## What does this PR do?

Added link to cockroach's documentation

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2022-03-30 15:17 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2938/detail/PR-2938/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2938/detail/PR-2938/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2938/detail/PR-2938/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2938/detail/PR-2938/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-03-30T15:04:34.856Z&rangeTo=2022-03-30T15:24:34.856Z&transactionName=BUILD+Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=84d4854d62625f71491745df20faa02e&transactionId=9b715c066ab96612)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-03-30T15:14:34.856+0000


* Duration: 2 min 29 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2938/detail/PR-2938/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-2938/runs/1/steps/107/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-04-07 18:41 UTC, bmorelli25 requested changes

2022-04-07 18:41 UTC, bmorelli25 commented on packages/cockroachdb/_dev/build/docs/README.md
> +This integration collects metrics from [https://www.cockroachlabs.com/docs/stable/developer-guide-overview.html](https://www.cockroachlabs.com/docs/stable/developer-guide-overview.html). It includes
This link needs to be fixed

```suggestion
This integration collects metrics from [CockroachDB](https://www.cockroachlabs.com/docs/stable/developer-guide-overview.html). It includes the
```

2022-04-08 08:16 UTC, cherryleaf commented on packages/cockroachdb/_dev/build/docs/README.md
> +This integration collects metrics from [https://www.cockroachlabs.com/docs/stable/developer-guide-overview.html](https://www.cockroachlabs.com/docs/stable/developer-guide-overview.html). It includes
change made

2022-04-28 15:46 UTC, cherryleaf commented
I will raise a new PR

2022-04-28 15:46 UTC, closed without merging