[hadoop][cluster_metrics] Add cluster_metrics data stream for hadoop
elastic/integrations pull request #2953
Opened 2022-03-31 06:33 UTC by yug-elastic

## What does this PR do?

- Generated the skeleton of Hadoop integration package.
- Added 1 data stream ( Cluster Metrics )
- Added data collection logic.
- Added the ingest pipelines.
- Mapped fields according to the ECS schema and added Fields metadata in the appropriate yml files.
- Added system test cases.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] If I'm introducing a new feature, I have modified the Kibana version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^8.0.0`).

## How to test this PR locally

- Clone integrations repo.
- Install elastic-package locally.
- Start elastic stack using elastic-package.
- Move to integrations/packages/hadoop directory.
- Run the following command to run tests. 
> elastic-package test

2022-03-31 06:33 UTC, elasticmachine commented
Pinging @elastic/integrations (Team:Integrations)

2022-03-31 06:34 UTC, yug-elastic commented on packages/hadoop/manifest.yml
> +  kibana.version: "^8.0.0"
This will be updated with 8.2.0 after testing this integration on 8.2.0.

2022-03-31 06:34 UTC, yug-elastic commented
This PR is a split of https://github.com/elastic/integrations/pull/2614 as discussed over the comment https://github.com/elastic/integrations/pull/2614#issuecomment-1082704609

2022-03-31 06:47 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2953/detail/PR-2953/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2953/detail/PR-2953/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2953/detail/PR-2953/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2953/detail/PR-2953/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_2953.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-03-31T06:23:17.393Z&rangeTo=2022-03-31T06:43:17.393Z&transactionName=BUILD+Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=c130477307b9a532db61ba343b70f4e2&transactionId=6617ebd18684102a)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-03-31T06:33:17.393+0000


* Duration: 15 min 35 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 9  |
| Skipped      | 0 |
| Total        | 9   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-03-31 11:34 UTC, mtojek commented on packages/hadoop/data_stream/cluster_metrics/fields/fields.yml
> +    - name: apps
nit: applications

2022-03-31 11:34 UTC, mtojek commented on packages/hadoop/data_stream/cluster_metrics/fields/fields.yml
> +- name: hadoop.cluster_metrics
I suggest to strip the `metrics` suffix and just go with `cluster`.

2022-03-31 11:34 UTC, mtojek commented on packages/hadoop/data_stream/cluster_metrics/fields/fields.yml
> +  release: beta
`Release tag` is [deprecated now](https://github.com/elastic/package-spec/blob/main/versions/1/manifest.spec.yml#L148). You can drop it from here and from manifests. We will depend on semver prerelease.

2022-04-01 06:34 UTC, yug-elastic commented on packages/hadoop/data_stream/cluster_metrics/fields/fields.yml
> +- name: hadoop.cluster_metrics
Okay, we will change that.

2022-04-01 06:35 UTC, yug-elastic commented on packages/hadoop/data_stream/cluster_metrics/fields/fields.yml
> +  release: beta
Okay, thanks for passing links.

2022-04-05 09:28 UTC, mtojek commented on packages/hadoop/manifest.yml
> +          - name: proxy_url
Can we remove the `proxy_url` or will it be removed in other PR?

2022-04-05 09:28 UTC, mtojek commented on packages/hadoop/data_stream/cluster/fields/fields.yml
>      - name: application_master
Didn't we agree on replacing all "master" references with "main"?

2022-04-05 09:28 UTC, mtojek commented on packages/hadoop/data_stream/cluster/fields/fields.yml
>            description: Application Master Register Delay Operations (Operations)
nit: Operations (Operations), a repetition :)

Is the bracket information required or does it add more context?

2022-04-06 05:15 UTC, yug-elastic commented on packages/hadoop/data_stream/cluster/fields/fields.yml
>            description: Application Master Register Delay Operations (Operations)
It adds the context of unit i.e. number of Operations. Should we discard it?

2022-04-06 09:35 UTC, mtojek commented on packages/hadoop/data_stream/cluster/fields/fields.yml
>            description: Application Master Register Delay Operations (Operations)
Then I guess you should rephrase it to be more meaningful, as for a person looking at it for the first time it's a mix of words (application, master, delay, operations) without any sense.

2022-04-14 09:19 UTC, masci commented on packages/hadoop/manifest.yml
> +          - name: proxy_url
@yug-elastic can you follow up here?

2022-04-14 09:21 UTC, masci commented on packages/hadoop/data_stream/cluster/fields/fields.yml
>            description: Application Master Register Delay Operations (Operations)
@yug-elastic you can say `Register Delay Operations (measured in number of Operations)

2022-04-14 09:50 UTC, yug-elastic commented on packages/hadoop/data_stream/cluster/fields/fields.yml
>            description: Application Master Register Delay Operations (Operations)
We have updated it to "... Delay Operations (Number of Operations)". I hope that makes sense.

2022-04-14 09:51 UTC, yug-elastic commented on packages/hadoop/manifest.yml
> +          - name: proxy_url
The proxy_url has been removed as per the discussion over https://github.com/elastic/integrations/pull/2955#discussion_r839538174.

2022-04-15 09:47 UTC, mtojek requested changes
@yug-elastic Could you please rebase this PR?

2022-04-19 09:03 UTC, mtojek approved these changes

2022-04-20 06:50 UTC, yug-elastic commented on packages/hadoop/manifest.yml
> +  kibana.version: "^8.0.0"
Kibana version has been updated to 8.1.0 as discussed over weekly sync for all the integrations.

2022-04-27 08:30 UTC, lalit-satapathy commented on packages/hadoop/data_stream/cluster/manifest.yml
> +      - name: ssl
Is the ssl configuration placeholder now or working/used currently?

2022-04-27 09:22 UTC, yug-elastic commented on packages/hadoop/data_stream/cluster/manifest.yml
> +      - name: ssl
It's not a placeholder and is being used currently.

2022-04-28 07:03 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`2/2`) | :green_heart: 
Files | 100.0% (`4/4`) | :green_heart: 
Classes | 100.0% (`4/4`) | :green_heart: 
Methods | 100.0% (`22/22`) | :green_heart: 
Lines | 98.328% (`294/299`) | :grey_exclamation: 
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-05-03 09:38 UTC, lalit-satapathy approved these changes

2022-05-03 09:45 UTC, merged