Spring boot package [Audit events - data stream]
elastic/integrations pull request #2977
Opened 2022-04-03 07:43 UTC by sunny-elastic

## What does this PR do?

- Generated the skeleton of Spring Boot integration package.
- Added **Audit events** data stream
- Added data collection logic.
- Added the ingest pipelines.
- Mapped fields according to the ECS schema and added Fields metadata in the appropriate yml files.
- Added system test cases.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that Audit events data stream collect logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] If I'm introducing a new feature, I have modified the Kibana version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^7.13.0`).

## How to test this PR locally

- Clone integrations repo.
- Install elastic-package locally.
- Start elastic stack using elastic-package.
- Move to integrations/packages/spring_boot directory.
- Run the following command to run tests. 
> elastic-package test 

Note: We have covered dashboards and the visualisations for all data streams of spring boot into separate PR

2022-04-03 07:57 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2977/detail/PR-2977/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2977/detail/PR-2977/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2977/detail/PR-2977/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2977/detail/PR-2977/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_2977.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-04-03T07:33:59.238Z&rangeTo=2022-04-03T07:53:59.238Z&transactionName=BUILD+Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=6380619f9dde708571a394b1fb1c5b0c&transactionId=a3a0dbc72ee17774)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-04-03T07:43:59.238+0000


* Duration: 13 min 7 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 5  |
| Skipped      | 0 |
| Total        | 5   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-04-03 12:41 UTC, elasticmachine commented
Pinging @elastic/integrations (Team:Integrations)

2022-04-04 09:36 UTC, mtojek commented on .github/CODEOWNERS
> +/packages/zscaler_zpa @elastic/security-external-integrations
Please rebase the PR.

2022-04-04 09:36 UTC, mtojek commented on packages/spring_boot/data_stream/audit_events/fields/fields.yml
> +    - name: auditevents
This is inconsistent with the `data_stream` name.

2022-04-04 09:36 UTC, mtojek commented on packages/spring_boot/data_stream/audit_events/fields/fields.yml
> +          type: keyword
What are these fields about? Please add descriptions.

2022-04-04 09:36 UTC, mtojek commented on packages/spring_boot/data_stream/audit_events/_dev/test/pipeline/test-auditevent-metrics.log-expected.json
> +            "spring_boot": {
Looking at the `event.original`, is it possible to extract also data? Otherwise, this data stream doesn't make too much sense for me. It's just "actuator" and "AUTHENTICATION_SUCCESS". No source IP, no session details, service name, anything.

2022-04-07 12:10 UTC, sunny-elastic commented on .github/CODEOWNERS
> +/packages/zscaler_zpa @elastic/security-external-integrations
Yeah done

2022-04-07 12:10 UTC, sunny-elastic commented on packages/spring_boot/data_stream/audit_events/fields/fields.yml
> +          type: keyword
Done

2022-04-07 12:11 UTC, sunny-elastic commented on packages/spring_boot/data_stream/audit_events/_dev/test/pipeline/test-auditevent-metrics.log-expected.json
> +            "spring_boot": {
ok extracted remote address and session id from event.original

2022-04-14 09:56 UTC, masci commented on packages/spring_boot/data_stream/audit_events/fields/fields.yml
> +    - name: auditevents
@sunny-elastic can you use the data stream name here?

2022-04-14 11:25 UTC, mtojek requested changes

2022-04-14 11:25 UTC, mtojek commented on packages/spring_boot/data_stream/audit_events/fields/fields.yml
> +              description: Remote Address of the Spring Boot application
Remote address of the application or user?

2022-04-14 11:25 UTC, mtojek commented on packages/spring_boot/data_stream/audit_events/fields/fields.yml
> +              description: Session ID of the Spring Boot application
Session ID of user or application?

2022-04-14 11:25 UTC, mtojek commented on packages/spring_boot/data_stream/audit_events/fields/fields.yml
> +          description: Restricts the events to those with the given principal
Could you please rephrase it? I'm not sure that I understand what is this field about.

2022-04-14 12:35 UTC, sunny-elastic commented on packages/spring_boot/data_stream/audit_events/fields/fields.yml
> +    - name: auditevents
Its fixed

2022-04-14 12:46 UTC, sunny-elastic commented on packages/spring_boot/data_stream/audit_events/fields/fields.yml
> +              description: Remote Address of the Spring Boot application
As this field got extracted from event.original as we addressed in previous comment. And this looks remote address of spring boot application.

2022-04-14 12:50 UTC, sunny-elastic commented on packages/spring_boot/data_stream/audit_events/fields/fields.yml
> +              description: Session ID of the Spring Boot application
As this field got extracted from event.original as we addressed in previous comment. And this looks session id of spring boot application.

2022-04-14 12:51 UTC, mtojek requested changes

2022-04-14 12:51 UTC, mtojek commented on packages/spring_boot/data_stream/audit_events/_dev/test/pipeline/test-auditevent-metrics.log-expected.json
> +                        "session_id": "192.168.32.6"
Why session ID is IP address? Did you dump this event or prepared manually?

2022-04-14 12:51 UTC, mtojek commented on packages/spring_boot/data_stream/audit_events/fields/fields.yml
> +              description: Remote Address of the Spring Boot application
Just to be sure, could you please double-check it with Spring docs or source code? Usually, you don't collect server IP address, but user IP, hence I'm confused.

2022-04-14 12:57 UTC, mtojek commented on packages/spring_boot/data_stream/audit_events/fields/fields.yml
> +              description: Session ID of the Spring Boot application
If this field concerns the user, let's rephrase the description accordingly.

2022-04-14 13:06 UTC, sunny-elastic commented on packages/spring_boot/data_stream/audit_events/fields/fields.yml
> +          description: Restricts the events to those with the given principal
So here this principal is basically referring to the user. and those remote address and session id fields for that specific principal that is user.

2022-04-14 13:11 UTC, sunny-elastic commented
@mtojek yes remote_address refer to the user ip address and not the server ip address.

2022-04-14 13:18 UTC, mtojek commented
Thanks for checking this. Could you please post a link to the documentation or Spring Boot source, in case somebody in the future will have similar concerns?

2022-04-14 13:36 UTC, sunny-elastic commented on packages/spring_boot/data_stream/audit_events/fields/fields.yml
> +              description: Remote Address of the Spring Boot application
yes its user ip address and not the server ip address.

2022-04-14 13:57 UTC, mtojek requested changes

2022-04-14 13:57 UTC, mtojek commented on packages/spring_boot/_dev/build/build.yml
> +    reference: git@8.0
I think you can update it to 8.1, as you're setting the `ecs.version` in the pipeline to 8.1.0.

2022-04-14 14:03 UTC, sunny-elastic commented on packages/spring_boot/_dev/build/build.yml
> +    reference: git@8.0
Done. fixed. Thanks!

2022-04-14 15:32 UTC, merged