Spring boot package [Httptrace - data stream]
elastic/integrations pull request #2978
Opened 2022-04-03 07:49 UTC by sunny-elastic

## What does this PR do?

- Generated the skeleton of Spring Boot integration package.
- Added **Httptrace** data stream
- Added data collection logic.
- Added the ingest pipelines.
- Mapped fields according to the ECS schema and added Fields metadata in the appropriate yml files.
- Added system test cases.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that Httptrace data stream collect logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] If I'm introducing a new feature, I have modified the Kibana version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^7.13.0`).

## How to test this PR locally

- Clone integrations repo.
- Install elastic-package locally.
- Start elastic stack using elastic-package.
- Move to integrations/packages/spring_boot directory.
- Run the following command to run tests. 
> elastic-package test 

Note: We have covered dashboards and the visualisations for all data streams of spring boot into separate PR

2022-04-03 08:02 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2978/detail/PR-2978/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2978/detail/PR-2978/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2978/detail/PR-2978/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2978/detail/PR-2978/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_2978.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-04-03T07:39:19.263Z&rangeTo=2022-04-03T07:59:19.263Z&transactionName=BUILD+Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=e0b4ded2fc7184f1d760570f722a5dae&transactionId=26a5c756b7c19c83)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-04-03T07:49:19.263+0000


* Duration: 13 min 6 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 5  |
| Skipped      | 0 |
| Total        | 5   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-04-03 12:44 UTC, elasticmachine commented
Pinging @elastic/integrations (Team:Integrations)

2022-04-04 09:44 UTC, mtojek commented on packages/spring_boot/data_stream/http_trace/sample_event.json
> +                "uri": "http://springboot:8090/actuator/info"
Did you check that there isn't any field for URI in the [ECS repository](https://github.com/elastic/ecs)?

2022-04-04 09:44 UTC, mtojek commented on packages/spring_boot/data_stream/http_trace/fields/fields.yml
> +        - name: time_taken
What does it mean? Is it `event.duration`?

2022-04-04 09:44 UTC, mtojek commented on packages/spring_boot/data_stream/http_trace/fields/fields.yml
> +            - name: remote_address
Did you check it with the ECS repository?

2022-04-04 09:44 UTC, mtojek commented on packages/spring_boot/data_stream/http_trace/fields/fields.yml
> +    - name: http_trace
Maybe include also the content type and request size/response size?

2022-04-07 12:14 UTC, sunny-elastic commented on packages/spring_boot/data_stream/http_trace/sample_event.json
> +                "uri": "http://springboot:8090/actuator/info"
updated with http.request.referrer

2022-04-07 12:16 UTC, sunny-elastic commented on packages/spring_boot/data_stream/http_trace/fields/fields.yml
> +            - name: remote_address
updated host.ip

2022-04-07 12:17 UTC, sunny-elastic commented on packages/spring_boot/data_stream/http_trace/fields/fields.yml
> +    - name: http_trace
No. not getting that information for content type and request size

2022-04-14 11:30 UTC, mtojek requested changes

2022-04-14 11:30 UTC, mtojek commented on packages/spring_boot/data_stream/http_trace/_dev/test/pipeline/test-httptrace-metrics.log
> +{"timestamp":"2022-03-04T16:05:16.022Z","principal":null,"session":null,"request":{"method":"GET","uri":"http://10.0.14.124:8090/actuator/jolokia/read/java.lang:name=PS%20Old%20Gen,type=MemoryPool/Us
Could you please use a test where fields are not null values? We will be sure that we process values correctly.

2022-04-14 18:09 UTC, sunny-elastic commented on packages/spring_boot/data_stream/http_trace/_dev/test/pipeline/test-httptrace-metrics.log
> +{"timestamp":"2022-03-04T16:05:16.022Z","principal":null,"session":null,"request":{"method":"GET","uri":"http://10.0.14.124:8090/actuator/jolokia/read/java.lang:name=PS%20Old%20Gen,type=MemoryPool/Us
Yeah its updated.

2022-04-15 08:12 UTC, mtojek requested changes
Just a formal thing.

2022-04-15 08:12 UTC, mtojek commented on packages/spring_boot/changelog.yml
>      - description: Initial draft of the package
Since you've already merged the skeleton, it would be good to add a separate entry to the changelog for this data stream. Please also bump up the version in manifest.

2022-04-15 17:54 UTC, sunny-elastic commented on packages/spring_boot/changelog.yml
>      - description: Initial draft of the package
Yeah its done

2022-04-19 07:51 UTC, mtojek approved these changes

2022-04-19 12:26 UTC, merged