Spring boot package [Memory - data stream]
elastic/integrations pull request #2979
Opened 2022-04-03 07:53 UTC by sunny-elastic

## What does this PR do?

- Generated the skeleton of Spring Boot integration package.
- Added **Memory** data stream
- Added data collection logic.
- Added the ingest pipelines.
- Mapped fields according to the ECS schema and added Fields metadata in the appropriate yml files.
- Added system test cases.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that Memory data stream collect metrics.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] If I'm introducing a new feature, I have modified the Kibana version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^7.13.0`).

## How to test this PR locally

- Clone integrations repo.
- Install elastic-package locally.
- Start elastic stack using elastic-package.
- Move to integrations/packages/spring_boot directory.
- Run the following command to run tests. 
> elastic-package test 

Note: We have covered dashboards and the visualisations for all data streams of spring boot into separate PR

2022-04-03 08:06 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2979/detail/PR-2979/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2979/detail/PR-2979/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2979/detail/PR-2979/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2979/detail/PR-2979/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_2979.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-04-03T07:43:29.290Z&rangeTo=2022-04-03T08:03:29.290Z&transactionName=BUILD+Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=176f5a22d9948f101ee1b04825ef3b99&transactionId=337bfa5a9b6de551)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-04-03T07:53:29.290+0000


* Duration: 13 min 4 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 3  |
| Skipped      | 0 |
| Total        | 3   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-04-03 12:45 UTC, elasticmachine commented
Pinging @elastic/integrations (Team:Integrations)

2022-04-04 10:09 UTC, mtojek commented on packages/spring_boot/data_stream/memory/sample_event.json
> +                    "total_capacity": 81920
Used and total are the same? Does it mean that you have 100% consumed the memory?

2022-04-04 10:09 UTC, mtojek commented on packages/spring_boot/data_stream/memory/sample_event.json
> +    "jolokia": {},
I guess that you can strip empty Jolokia groups?

2022-04-04 10:09 UTC, mtojek commented on packages/spring_boot/data_stream/memory/sample_event.json
> +{
Could you dump an event that collects most of defined metrics?

2022-04-04 10:09 UTC, mtojek commented on packages/spring_boot/data_stream/memory/fields/fields.yml
> +            - name: verbose
What does the verbose mean here?

2022-04-07 12:18 UTC, sunny-elastic commented on packages/spring_boot/data_stream/memory/sample_event.json
> +    "jolokia": {},
yes removed that

2022-04-14 11:34 UTC, mtojek requested changes

2022-04-14 11:34 UTC, mtojek commented on packages/spring_boot/data_stream/memory/fields/fields.yml
> +                  description: Returns count of direct buffer pool memory
Could you please make all descriptions consistent? Why is there everywhere a verb "Returns"? Let's make it consistent with other data streams.

2022-04-14 11:34 UTC, mtojek commented on packages/spring_boot/data_stream/memory/fields/fields.yml
> +                  description: Returns count of mapped buffer pool memory
What is this metric about?

2022-04-14 11:34 UTC, mtojek commented on packages/spring_boot/docs/README.md
> +| spring_boot.memory.memory_manager.metaspace_manager.valid | Return the validation | boolean |
Please work together with @yug-elastic to refactor those metrics. `memory` is repeated a few times per metric.

2022-04-14 11:57 UTC, yug-elastic commented on packages/spring_boot/docs/README.md
> +| spring_boot.memory.memory_manager.metaspace_manager.valid | Return the validation | boolean |
Sure, putting the link to the similar discussion for Apache Spark here for ready reference
https://github.com/elastic/integrations/pull/2811#discussion_r837187132

2022-04-19 13:08 UTC, sunny-elastic commented on packages/spring_boot/data_stream/memory/sample_event.json
> +                    "total_capacity": 81920
Yes.

2022-04-19 13:17 UTC, sunny-elastic commented on packages/spring_boot/data_stream/memory/fields/fields.yml
> +            - name: verbose
Verbose: Tests if verbose output for the memory system is enabled. But I think its a boolean value and does not make any sense to collect that so we removed it.

2022-04-19 13:29 UTC, sunny-elastic commented on packages/spring_boot/data_stream/memory/fields/fields.yml
> +                  description: Returns count of mapped buffer pool memory
Count of buffer pool memory

2022-04-19 13:29 UTC, sunny-elastic commented on packages/spring_boot/docs/README.md
> +| spring_boot.memory.memory_manager.metaspace_manager.valid | Return the validation | boolean |
Its updated

2022-04-19 13:45 UTC, sunny-elastic commented on packages/spring_boot/data_stream/memory/sample_event.json
> +{
updated.

2022-04-19 13:50 UTC, mtojek commented on packages/spring_boot/data_stream/memory/fields/fields.yml
> +                  description: Returns count of mapped buffer pool memory
Still, what does it mean :) Is it the number of buffer pools, number of memory units, etc.?

2022-04-19 13:53 UTC, mtojek requested changes

2022-04-19 13:53 UTC, mtojek commented on packages/spring_boot/_dev/build/docs/README.md
> +- This data stream gives Memory information.
nit: memory

2022-04-19 13:53 UTC, mtojek commented on packages/spring_boot/data_stream/memory/fields/ecs.yml
> +- external: ecs
This data stream is about memory, so why do we need all these field definitions? Process, source, tls, HTTP. Did you add them on purpose?

2022-04-19 14:36 UTC, sunny-elastic commented on packages/spring_boot/data_stream/memory/fields/fields.yml
> +                  description: Returns count of mapped buffer pool memory
yes it is number of buffer pools

2022-04-19 14:36 UTC, sunny-elastic commented on packages/spring_boot/data_stream/memory/fields/ecs.yml
> +- external: ecs
yeah removed those extra ecs fields

2022-04-20 08:37 UTC, mtojek requested changes

2022-04-20 08:37 UTC, mtojek commented on packages/spring_boot/_dev/build/docs/README.md
> +- This data stream gives memory information.
I don't think that this description explains what kind of data the data stream is handling. Please rephrase it to something meaningful (what kind of metrics, from where).

2022-04-20 08:37 UTC, mtojek commented on packages/spring_boot/docs/README.md
> +| os.version | Operating system version as a raw string. | keyword |
Sample event doesn't contain metrics for these entries. Does the integration collect these values?

2022-04-20 08:37 UTC, mtojek commented on packages/spring_boot/docs/README.md
> +| event.outcome | This is one of four ECS Categorization Fields, and indicates the lowest level in the ECS category hierarchy. `event.outcome` simply denotes whether the event represents a success or
Same

2022-04-20 08:37 UTC, mtojek commented on packages/spring_boot/docs/README.md
> +| message | For log events the message field contains the log message, optimized for viewing in a log viewer. For structured logs without an original message field, other fields can be concatenated t
Same question. It's a metric based data stream. Why is there a message?

2022-04-20 11:51 UTC, sunny-elastic commented on packages/spring_boot/_dev/build/docs/README.md
> +- This data stream gives memory information.
Ok updated

2022-04-20 11:51 UTC, sunny-elastic commented on packages/spring_boot/docs/README.md
> +| os.version | Operating system version as a raw string. | keyword |
missed it from Readme, but its updated now

2022-04-20 11:52 UTC, sunny-elastic commented on packages/spring_boot/docs/README.md
> +| event.outcome | This is one of four ECS Categorization Fields, and indicates the lowest level in the ECS category hierarchy. `event.outcome` simply denotes whether the event represents a success or
yes updated

2022-04-20 11:52 UTC, sunny-elastic commented on packages/spring_boot/docs/README.md
> +| message | For log events the message field contains the log message, optimized for viewing in a log viewer. For structured logs without an original message field, other fields can be concatenated t
yeah its cleared

2022-04-20 12:26 UTC, mtojek commented on packages/spring_boot/docs/README.md
> +| event.outcome | This is one of four ECS Categorization Fields, and indicates the lowest level in the ECS category hierarchy. `event.outcome` simply denotes whether the event represents a success or
What did you update here? I can still see `event.outcome` and I can't see in the sample event. Could you please explain why is this field here?

2022-04-21 12:45 UTC, kush-elastic requested changes

2022-04-21 12:45 UTC, kush-elastic commented on packages/spring_boot/docs/README.md
> +| spring_boot.memory.manager.metaspace.valid | Returns the validation | boolean |
can we rephrase this to something like
```suggestion
| spring_boot.memory.manager.code_cache.valid | Validation of code cache | boolean |
| spring_boot.memory.manager.metaspace.name | Name of the Metaspace Manager to qualify the cache | keyword |
| spring_boot.memory.manager.metaspace.valid | Validation of metaspace manager | boolean |
```

2022-04-21 12:45 UTC, kush-elastic commented on packages/spring_boot/manifest.yml
> +                #certificate_authorities:
I think there's a mistake here, maybe remove this default here:
```suggestion
            default: |-
              #certificate_authorities:
```

2022-04-21 17:32 UTC, sunny-elastic commented on packages/spring_boot/docs/README.md
> +| spring_boot.memory.manager.metaspace.valid | Returns the validation | boolean |
Yes sure. It updated

2022-04-21 17:32 UTC, sunny-elastic commented on packages/spring_boot/manifest.yml
> +                #certificate_authorities:
fixed

2022-04-22 04:01 UTC, kush-elastic approved these changes
LGTM!

2022-04-25 07:25 UTC, mtojek approved these changes
Just a formality on my side. Thanks, @kush-elastic, for reviewing.

2022-04-25 09:30 UTC, merged