Spring boot package [Threads - data stream]
elastic/integrations pull request #2981
Opened 2022-04-03 07:59 UTC by sunny-elastic

## What does this PR do?

- Generated the skeleton of Spring Boot integration package.
- Added **Threads** data stream
- Added data collection logic.
- Added the ingest pipelines.
- Mapped fields according to the ECS schema and added Fields metadata in the appropriate yml files.
- Added system test cases.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that Threads data stream collect metrics.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] If I'm introducing a new feature, I have modified the Kibana version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^7.13.0`).

## How to test this PR locally

- Clone integrations repo.
- Install elastic-package locally.
- Start elastic stack using elastic-package.
- Move to integrations/packages/spring_boot directory.
- Run the following command to run tests. 
> elastic-package test 

Note: We have covered dashboards and the visualisations for all data streams of spring boot into separate PR

2022-04-03 08:12 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2981/detail/PR-2981/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2981/detail/PR-2981/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2981/detail/PR-2981/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2981/detail/PR-2981/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_2981.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-04-03T07:49:54.335Z&rangeTo=2022-04-03T08:09:54.335Z&transactionName=BUILD+Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=c2b2ff95a70f8666c397a4bc6f632e24&transactionId=968d07ab7f1bb999)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-04-03T07:59:54.335+0000


* Duration: 13 min 0 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 3  |
| Skipped      | 0 |
| Total        | 3   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-04-03 12:46 UTC, elasticmachine commented
Pinging @elastic/integrations (Team:Integrations)

2022-04-04 10:48 UTC, mtojek commented on packages/spring_boot/data_stream/threads/fields/fields.yml
> +            - name: thread
With this fields organization, we will end up with `spring_boot.threads.threading.thread.*`, which is wrong. Could you please refine this structure one more time?

I recommend sticking to the simplest, so `spring_boot.threading.*`. Then, rename also the data stream to threading.

2022-04-04 10:48 UTC, mtojek commented on packages/spring_boot/data_stream/threads/fields/fields.yml
> +              fields:
Please group the children: memory, contention, cpu.

2022-04-04 10:48 UTC, mtojek commented on packages/spring_boot/data_stream/threads/fields/fields.yml
> +            - name: current_thread
What does the `current_thread` mean in terms of Jolokia request? Which one is the current thread? Should we skip it?

2022-04-07 12:23 UTC, sunny-elastic commented on packages/spring_boot/data_stream/threads/fields/fields.yml
> +            - name: thread
its updated

2022-04-07 12:23 UTC, sunny-elastic commented on packages/spring_boot/data_stream/threads/fields/fields.yml
> +              fields:
done

2022-04-07 12:25 UTC, sunny-elastic commented on packages/spring_boot/data_stream/threads/fields/fields.yml
> +            - name: current_thread
so this current_thread should be current running thread , it has different values than threads. I think we should keep this.

2022-04-26 06:05 UTC, kush-elastic requested changes
@sunny-elastic that's all from my end, left some comments. 
@mtojek, please take a look and feel free to drop in suggestions/questions.

2022-04-26 07:06 UTC, kush-elastic approved these changes
LGTM! Let's wait for other's review.

2022-04-26 07:58 UTC, mtojek reviewed
Few comments on my side.

1. I'm not sure why do we need to collect these booleans.
2. I think we need another level `spring_boot.threading.threads.*` for metrics like `current` and `started` (instead of daemon and total_started).

2022-04-26 07:58 UTC, mtojek commented on packages/spring_boot/data_stream/threading/sample_event.json
> +            },
What do these metrics mean? They seem to me more like a configuration.

2022-04-26 07:58 UTC, mtojek commented on packages/spring_boot/data_stream/threading/sample_event.json
> +            },
Same story here. As a user, I expected `cpu_time` but got some booleans.

2022-04-26 07:58 UTC, mtojek commented on packages/spring_boot/data_stream/threading/sample_event.json
> +            "daemon": 16,
What does this metric mean?

2022-04-26 07:58 UTC, mtojek commented on packages/spring_boot/data_stream/threading/sample_event.json
> +            "object_monitor_usage_supported": true,
Boolean?

2022-04-26 07:58 UTC, mtojek commented on packages/spring_boot/data_stream/threading/sample_event.json
> +            "synchronizer_usage_supported": true,
Boolean?

2022-04-26 07:58 UTC, mtojek commented on packages/spring_boot/data_stream/threading/sample_event.json
> +            "total_started": 23
total_started what?

2022-04-26 07:58 UTC, mtojek requested changes
requested changes

2022-04-26 09:21 UTC, sunny-elastic commented on packages/spring_boot/manifest.yml
> +        description: Collecting metrics from Spring Boot of Memory and Threading.
yes done

2022-04-26 09:21 UTC, sunny-elastic commented on packages/spring_boot/data_stream/threading/fields/fields.yml
> +          description: Total number of threads created and also started since the Java virtual machine started
yeah make sense, its updated

2022-04-26 13:29 UTC, sunny-elastic commented
> Few comments on my side.
> 
> 1. I'm not sure why do we need to collect these booleans.
> 2. I think we need another level `spring_boot.threading.threads.*` for metrics like `current` and `started` (instead of daemon and total_started).

@mtojek is this following structure looks good to you, since only kept relevant fields which has meaningful values to collect 
```
"spring_boot"{
    "threading"{
        "threads"{
            "current"{
                "allocated_bytes",
                "time"{
                    "cpu",
                    "user"
                },
            },
            "count",
            "daemon",
            "total_started"
        }
    }
}
```

2022-04-26 13:38 UTC, mtojek commented
Yes, it's a better fit. I'm wondering if we improve it more by applying this [guidance](https://www.elastic.co/guide/en/beats/devguide/current/event-conventions.html). 

Then:
* `count` will be `value`
* `total_started` will be `started`

2022-04-26 13:50 UTC, sunny-elastic commented
> 

yeah but `count` has a specific meaning here as count of live threads _(Current number of live threads including both daemon and non-daemon threads.)_ 
and `total_started` is Total number of threads created and also started since the Java virtual machine started, we can keep this as `started`. let me know what you think

2022-04-27 06:46 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`2/2`) | :green_heart: 
Files | 100.0% (`2/2`) | :green_heart: 2.918
Classes | 100.0% (`2/2`) | :green_heart: 2.918
Methods | 100.0% (`24/24`) | :green_heart: 11.29
Lines | 93.289% (`139/149`) | :+1: 3.348
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-04-27 06:59 UTC, sunny-elastic commented on packages/spring_boot/data_stream/threading/sample_event.json
> +            },
its updated now and removed the unwanted ones

2022-04-27 06:59 UTC, sunny-elastic commented on packages/spring_boot/data_stream/threading/sample_event.json
> +            },
we updated the structure and kept only relevant fields

2022-04-27 07:01 UTC, sunny-elastic commented on packages/spring_boot/data_stream/threading/sample_event.json
> +            "daemon": 16,
for daemon ? its number of live daemon threads.

2022-04-27 07:02 UTC, sunny-elastic commented on packages/spring_boot/data_stream/threading/sample_event.json
> +            "object_monitor_usage_supported": true,
its updated

2022-04-27 07:02 UTC, sunny-elastic commented on packages/spring_boot/data_stream/threading/sample_event.json
> +            "synchronizer_usage_supported": true,
its updated

2022-04-27 07:03 UTC, sunny-elastic commented on packages/spring_boot/data_stream/threading/sample_event.json
> +            "total_started": 23
Total number of threads created and also started since the Java virtual machine started. Updated this hierarchy in structure

2022-04-27 07:03 UTC, sunny-elastic commented
> Ok, let's just change the `total_started` -> `started`. Otherwise, it LGTM.

Yeah its updated. Thanks!

2022-04-27 07:11 UTC, mtojek approved these changes

2022-04-27 07:30 UTC, merged