Update README.md
elastic/integrations pull request #2990
Opened 2022-04-04 15:06 UTC by cherryleaf

markdown syntax tidy up

Type of change

- Enhancement

markdown syntax tidy up

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2022-04-04 15:09 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2990/detail/PR-2990/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2990/detail/PR-2990/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2990/detail/PR-2990/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2990/detail/PR-2990/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-04-04T14:56:58.069Z&rangeTo=2022-04-04T15:16:58.069Z&transactionName=BUILD+Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=d6b7609c627e2a8ee922a7ac523247fc&transactionId=c044c3ba75435732)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-04-04T15:06:58.069+0000


* Duration: 3 min 33 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2990/detail/PR-2990/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-2990/runs/1/steps/107/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-04-06 18:07 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2022-04-07 18:31 UTC, bmorelli25 commented on packages/mimecast/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/2990
I don't think you have the most up to date version of these files locally. This PR needs to be merged with main and updated to version 0.0.10.

2022-04-08 09:17 UTC, GinnyGalicia commented on packages/mimecast/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/2990
changelog updated

2022-04-12 12:41 UTC, andrewkroh commented
/test

2022-04-12 12:43 UTC, andrewkroh requested changes

2022-04-12 12:43 UTC, andrewkroh commented on packages/1password/_dev/build/docs/README.md
> +{{event "item_usages"}}
This should be reverted given this is a mimecast PR.

2022-04-12 12:43 UTC, andrewkroh commented on packages/mimecast/changelog.yml
> +    - description: markdown syntax tidy up in readme
These are rendered in our docs so I think it would be best to use a complete sentence.

2022-04-13 09:17 UTC, ellis-elastic commented on packages/1password/_dev/build/docs/README.md
> +{{event "item_usages"}}
Done

2022-04-13 13:13 UTC, GinnyGalicia commented on packages/mimecast/changelog.yml
> +    - description: markdown syntax tidy up in readme
I've edited the description

2022-04-14 01:39 UTC, efd6 commented
/test

2022-04-17 23:22 UTC, JezelMishap approved these changes

2022-07-19 22:49 UTC, andrewkroh approved these changes

2022-07-20 00:46 UTC, andrewkroh commented
It looks like @cherryleaf has not given permissions to allow pushing updates to this PR. I'll open a new PR with the same content + a merge.

2022-07-20 01:15 UTC, closed without merging