update Microsoft defender endpoint readme
elastic/integrations pull request #2999
Opened 2022-04-05 13:15 UTC by cherryleaf

Type of change

- Enhancement

## What does this PR do?

Tidy up of Markdown in Readme.md, including adding link to developer's documentation, if missing 

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2022-04-05 13:18 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2999/detail/PR-2999/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2999/detail/PR-2999/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2999/detail/PR-2999/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2999/detail/PR-2999/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-04-05T13:05:59.786Z&rangeTo=2022-04-05T13:25:59.786Z&transactionName=BUILD+Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=7d53d4bf3c13162d910774f5ad838a4f&transactionId=f4f055ac8d2a369c)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-04-05T13:15:59.786+0000


* Duration: 2 min 28 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-2999/detail/PR-2999/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-2999/runs/1/steps/107/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-04-06 18:07 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2022-04-07 18:25 UTC, bmorelli25 commented on packages/microsoft_defender_endpoint/_dev/build/docs/README.md
> +> Note: When giving the application the API permissions described in the documentation (`Windows Defender ATP Alert.Read.All`), it will only grant access to read alerts from ATP and nothing else in t
Is the `>` intentional here?

2022-04-08 09:31 UTC, GinnyGalicia commented on packages/microsoft_defender_endpoint/_dev/build/docs/README.md
> +> Note: When giving the application the API permissions described in the documentation (`Windows Defender ATP Alert.Read.All`), it will only grant access to read alerts from ATP and nothing else in t
Yes, it generates a Markdown admonition note box

2022-04-14 08:54 UTC, GinnyGalicia commented on packages/microsoft_defender_endpoint/_dev/build/docs/README.md
> +> Note: When giving the application the API permissions described in the documentation (`Windows Defender ATP Alert.Read.All`), it will only grant access to read alerts from ATP and nothing else in t
I've changed this to Elastic's DocCallOut tag

2022-04-21 21:16 UTC, andrewkroh commented
/test

2022-04-28 19:41 UTC, andrewkroh commented
/test

2022-04-28 19:42 UTC, andrewkroh approved these changes

2022-05-02 22:21 UTC, bmorelli25 requested changes

2022-05-02 22:21 UTC, bmorelli25 commented on packages/microsoft_defender_endpoint/_dev/build/docs/README.md
> +When giving the application the API permissions described in the documentation (`Windows Defender ATP Alert.Read.All`), it will only grant access to read alerts from ATP and nothing else in the Azure
This needs to be reverted as it won't render in markdown.

2022-05-04 09:30 UTC, ellis-elastic commented on packages/microsoft_defender_endpoint/_dev/build/docs/README.md
> +When giving the application the API permissions described in the documentation (`Windows Defender ATP Alert.Read.All`), it will only grant access to read alerts from ATP and nothing else in the Azure
I'm going to have to raise a new PR, as I cant' seem to edit this.

2022-05-04 09:32 UTC, ellis-elastic commented
I'm going to have to raise a new PR, as I cant' seem to edit this.

2022-05-04 09:32 UTC, closed without merging