Update Netflow readme
elastic/integrations pull request #3002
Opened 2022-04-05 14:34 UTC by cherryleaf

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2022-04-06 18:07 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2022-04-07 18:20 UTC, bmorelli25 commented
/test

2022-04-07 18:23 UTC, bmorelli25 commented on packages/netflow/changelog.yml
> +    - description: Tidy up of Markdown in Readme.md, including adding link to developer's documentation, if missing
```suggestion
    - description: Added link to Netflow documentation
```

2022-04-12 01:50 UTC, efd6 requested changes

2022-04-12 01:50 UTC, efd6 commented on packages/1password/_dev/build/docs/README.md
> +{{event "item_usages"}}
Please revert this removal of a trailing newline.

2022-04-12 01:50 UTC, efd6 commented on packages/netflow/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/3002
This should be a new section, not an overwrite of the existing last entry.

2022-04-12 13:13 UTC, GinnyGalicia commented on packages/1password/_dev/build/docs/README.md
> +{{event "item_usages"}}
Done

2022-04-12 13:18 UTC, GinnyGalicia commented on packages/netflow/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/3002
Oops. Fixed

2022-04-13 01:11 UTC, efd6 commented on packages/1password/_dev/build/docs/README.md
> +{{event "item_usages"}}
Thank you.

2022-04-13 01:11 UTC, efd6 commented
/test

2022-07-20 01:00 UTC, andrewkroh requested changes

2022-07-20 01:00 UTC, andrewkroh commented on packages/netflow/_dev/build/docs/README.md
> +This integration is for receiving [NetFlow](https://docs.netflowlogic.com/) and IPFIX flow records over UDP. It
This is not the related link. Netflow and IPFIX are standards.

- https://www.ietf.org/rfc/rfc3954.txt

- https://www.ietf.org/rfc/rfc7011.txt

2022-08-09 15:33 UTC, GinnyGalicia commented on packages/netflow/_dev/build/docs/README.md
> +This integration is for receiving [NetFlow](https://docs.netflowlogic.com/) and IPFIX flow records over UDP. It
I've updated the links

2022-08-10 03:52 UTC, efd6 commented
/test

2022-08-14 19:35 UTC, andrewkroh commented
> README.md is outdated. Rebuild the package with 'elastic-package build'
> [2022-08-10T04:03:55.675Z] Error: checking package failed: checking readme files are up-to-date failed: checking readme files are up-to-date failed

@GinnyGalicia can you please regenerate the README file with `elastic-package build`.

2022-08-15 10:07 UTC, GinnyGalicia commented
Ran build again

2022-08-15 14:52 UTC, andrewkroh commented
/test

2022-08-15 15:12 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`1/1`) | :green_heart: 
Files | 100.0% (`1/1`) | :green_heart: 2.941
Classes | 100.0% (`1/1`) | :green_heart: 2.941
Methods | 100.0% (`7/7`) | :green_heart: 10.5
Lines | 100.0% (`56/56`) | :green_heart: 8.472
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-08-15 15:25 UTC, andrewkroh approved these changes

2022-08-15 15:26 UTC, merged