Update Netscout readme
elastic/integrations pull request #3004
Opened 2022-04-05 15:51 UTC by cherryleaf

Type of change

- Enhancement

## What does this PR do

Tidy up of Markdown in Readme.md, including adding link to developer's documentation, if missing 

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2022-04-05 15:55 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3004/detail/PR-3004/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3004/detail/PR-3004/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3004/detail/PR-3004/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3004/detail/PR-3004/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-04-05T15:42:02.702Z&rangeTo=2022-04-05T16:02:02.702Z&transactionName=BUILD+Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=27acea4763d12f69a07ae77543c52166&transactionId=9558d10931e34612)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-04-05T15:52:02.702+0000


* Duration: 3 min 43 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3004/detail/PR-3004/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3004/runs/1/steps/107/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-04-06 18:07 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2022-04-07 18:20 UTC, bmorelli25 commented
/test

2022-04-07 18:23 UTC, bmorelli25 commented on packages/netscout/changelog.yml
> +    - description: Tidy up of Markdown in Readme.md, including adding link to developer's documentation, if missing
```suggestion
    - description: Tidy up of Markdown in Readme.md, including adding link to developer's documentation
```

2022-04-12 01:45 UTC, efd6 commented on packages/1password/_dev/build/docs/README.md
> +{{event "item_usages"}}
Please revert this removal of a trailing newline.

2022-04-12 13:21 UTC, GinnyGalicia commented on packages/1password/_dev/build/docs/README.md
> +{{event "item_usages"}}
Done

2022-04-13 01:12 UTC, efd6 commented
/test

2022-07-20 01:02 UTC, andrewkroh requested changes

2022-07-20 01:02 UTC, andrewkroh commented on packages/netscout/docs/README.md
> +This integration is for [Netscout](https://my.netscout.com/pages/overview.aspx?&ReturnUrl=%2fmcp%2fAddlDocs%2fDocumentation%2f_layouts%2f15%2fAuthenticate.aspx%3fSource%3d%252Fmcp%252FAddlDocs%252FDo
This is a link to authenticate. How about using https://www.netscout.com/product/arbor-sightline

2022-08-09 15:24 UTC, GinnyGalicia commented on packages/netscout/docs/README.md
> +This integration is for [Netscout](https://my.netscout.com/pages/overview.aspx?&ReturnUrl=%2fmcp%2fAddlDocs%2fDocumentation%2f_layouts%2f15%2fAuthenticate.aspx%3fSource%3d%252Fmcp%252FAddlDocs%252FDo
I've changed it

2022-08-10 03:52 UTC, efd6 commented
/test

2022-08-10 04:11 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`1/1`) | :green_heart: 
Files | 100.0% (`1/1`) | :green_heart: 2.473
Classes | 100.0% (`1/1`) | :green_heart: 2.473
Methods | 77.778% (`7/9`) | :-1: -12.448
Lines | 82.143% (`46/56`) | :-1: -7.641
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-08-14 19:36 UTC, andrewkroh approved these changes

2022-08-14 19:38 UTC, merged