Update Netskope readme file
elastic/integrations pull request #3012
Opened 2022-04-06 10:21 UTC by cherryleaf

Type of change

- Enhancement

## What does this PR do?

Tidy up of Markdown in Readme.md, including adding link to developer's documentation, if missing

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2022-04-06 10:25 UTC, mtojek requested changes
Could you please revert changes in the `go.mod`? It shouldn't be part of this PR.

2022-04-06 18:06 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2022-04-07 11:17 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3012/detail/PR-3012/5//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3012/detail/PR-3012/5//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3012/detail/PR-3012/5//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3012/detail/PR-3012/5//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-04-07T11:04:58.834Z&rangeTo=2022-04-07T11:24:58.834Z&transactionName=BUILD+Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=5be918349198d4afd38945d46a26e7ab&transactionId=e34dac0d3e581070)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-04-07T11:14:58.834+0000


* Duration: 2 min 14 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3012/detail/PR-3012/5//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3012/runs/5/steps/106/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-04-07 18:19 UTC, bmorelli25 commented
/test

2022-04-07 18:20 UTC, bmorelli25 commented on packages/netskope/_dev/build/docs/README.md
> +        For detailed steps refer to[Configure Log Shipper SIEM Mappings](https://docs.netskope.com/en/configure-log-shipper-siem-mappings.html).
Missing a space

```suggestion
        For detailed steps refer to [Configure Log Shipper SIEM Mappings](https://docs.netskope.com/en/configure-log-shipper-siem-mappings.html).

```

2022-04-12 01:39 UTC, efd6 commented on packages/netskope/docs/README.md
> +        For detailed steps refer to[Configure Log Shipper SIEM Mappings](https://docs.netskope.com/en/configure-log-shipper-siem-mappings.html).
I'm not sure the indentation should be changed here. Also, `s/to[Configure/to [Configure/`.

2022-04-12 01:46 UTC, efd6 commented on packages/1password/_dev/build/docs/README.md
> +{{event "item_usages"}}
Please revert this removal of a trailing newline.

2022-04-12 13:28 UTC, GinnyGalicia commented on packages/1password/_dev/build/docs/README.md
> +{{event "item_usages"}}
Done

2022-04-12 13:31 UTC, GinnyGalicia commented on packages/netskope/docs/README.md
> +        For detailed steps refer to[Configure Log Shipper SIEM Mappings](https://docs.netskope.com/en/configure-log-shipper-siem-mappings.html).
I've moved this to a note

2022-04-12 13:33 UTC, GinnyGalicia commented on packages/netskope/_dev/build/docs/README.md
> +        For detailed steps refer to[Configure Log Shipper SIEM Mappings](https://docs.netskope.com/en/configure-log-shipper-siem-mappings.html).
Resolved. I've moved this to a note

2022-04-13 01:18 UTC, efd6 commented
/test

2022-04-13 03:38 UTC, efd6 commented
This needs `elastic-package build`.

2022-04-27 21:12 UTC, bmorelli25 requested changes

2022-04-27 21:12 UTC, bmorelli25 commented on packages/netskope/_dev/build/docs/README.md
> +Please make sure to use the given response formats. </DocCallOut>
These docCallOuts need to be removed as they're specific to our documentation build.

2022-04-28 15:17 UTC, cherryleaf commented
Cannot resolve

2022-04-28 15:17 UTC, closed without merging