[apache spark] Add visualizations and dashboard
elastic/integrations pull request #3020
Opened 2022-04-06 20:39 UTC by yug-elastic

- Enhancement

## What does this PR do?
This PR adds dashboard for apache-spark integration package.

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally

- Clone integrations repo.
- Install elastic-package locally.
- Start elastic stack using elastic-package.
- Move to integrations/packages/apache_spark directory.
- Run the following command to run tests.
`elastic-package test`

## Related issues

- Relates #493
- Relates #2811 
- Relates #2939
- Relates #2941
- Relates #2945 
- Relates #2943

## Screenshots
![apache-spark-overview-dashboard-screenshot](https://user-images.githubusercontent.com/96041884/162065334-76bd0c0b-37b2-416a-a886-1719d6b81c41.png)

2022-04-19 10:10 UTC, mtojek requested changes
I can share the high-level feedback.

* There are too many counters compared to standard graphs. You don't need to put every metrics on a dashboard
* I suggest showing:
  * counters: executors, jobs, stages, workers
  * graphs: stages, tasks, memory usage, read write bytes
  * gauges: cores
* Please simulate some tough Spark processing, so dashboards don't contain only zeros and flat lines.

2022-04-22 12:44 UTC, elasticmachine commented
Pinging @elastic/integrations (Team:Integrations)

2022-04-22 12:46 UTC, yug-elastic commented
Thanks for the feedback, @mtojek! 
We have incorporated the changes. Please take a look at your convenience.

2022-05-03 09:34 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 3.275
Classes | 100.0% (`0/0`) | :green_heart: 3.275
Methods | 75.0% (`12/16`) | :-1: -14.113
Lines | 100.0% (`0/0`) | :green_heart: 10.01
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-05-04 08:38 UTC, mtojek approved these changes

2022-05-09 08:10 UTC, mtojek approved these changes

2022-05-09 08:10 UTC, merged