Update Microsoft SQL Server readme
elastic/integrations pull request #3058
Opened 2022-04-11 14:26 UTC by ellis-elastic

Added links to Microsoft documentation

Type of change

- Enhancement

## What does this PR do?

Added links to Microsoft documentation

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2022-04-12 02:15 UTC, efd6 commented
/test

2022-04-12 03:29 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2022-04-12 03:34 UTC, r00tu53r requested changes

2022-04-12 03:34 UTC, r00tu53r commented on packages/microsoft_sqlserver/_dev/build/docs/README.md
>  The Microsoft SQL Server integration package allows you to search, observe and visualize the SQL Server audit events through Elasticsearch.
This line can be removed as it has been moved up.

2022-04-12 03:34 UTC, r00tu53r commented on packages/microsoft_sqlserver/docs/README.md
> -| destination.user.name.text | Multi-field of `destination.user.name`. | match_only_text |
Not sure why the field docs are changing. Please do a clean rebuild. The only files that must change are `_dev/build/docs/README.md, docs/README.md, changelog.yml, manifest.yml`.

2022-04-12 09:55 UTC, ellis-elastic commented on packages/microsoft_sqlserver/docs/README.md
> -| destination.user.name.text | Multi-field of `destination.user.name`. | match_only_text |
re ran build

2022-04-12 09:55 UTC, ellis-elastic commented on packages/microsoft_sqlserver/_dev/build/docs/README.md
>  The Microsoft SQL Server integration package allows you to search, observe and visualize the SQL Server audit events through Elasticsearch.
Updated file to remove the lines

2022-04-13 01:24 UTC, r00tu53r approved these changes
LGTM. @ellis-elastic thank you for the contribution. 

I noticed the CI was failing as the generated README.md (the one under `docs/README.md`) was not committed/pushed. So I pushed that.

2022-04-13 14:40 UTC, merged