Change naming convention of node datastream
elastic/integrations pull request #3070
Opened 2022-04-12 05:06 UTC by yug-elastic

## What does this PR do?

- Refactor the nodes data stream to adjust its name as per the discussion [here](https://github.com/elastic/integrations/pull/2941#discussion_r846707836)

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] If I'm introducing a new feature, I have modified the Kibana version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^7.13.0`).

## How to test this PR locally

- Clone integrations repo.
- Install elastic-package locally.
- Start elastic stack using elastic-package.
- Move to integrations/packages/apache_spark directory.
- Run the following command to run tests. 
> elastic-package test

2022-04-12 05:11 UTC, elasticmachine commented
Pinging @elastic/integrations (Team:Integrations)

2022-04-12 07:42 UTC, mtojek requested changes
requested changes

2022-04-12 09:30 UTC, ruflin approved these changes

2022-04-12 09:30 UTC, ruflin commented on packages/apache_spark/data_stream/node/elasticsearch/ingest_pipeline/default.yml
> +      field: jolokia
How is this change related? A bug found?

2022-04-12 09:52 UTC, yug-elastic commented on packages/apache_spark/data_stream/node/elasticsearch/ingest_pipeline/default.yml
> +      field: jolokia
Right, this change is unrelated. There was an empty field being generated in the sample event. We have made the same change in the other data streams as well and hence thought of shipping it here.

2022-04-12 10:01 UTC, mtojek commented on packages/apache_spark/changelog.yml
> +    - description: Refactor the nodes data stream to adjust its name to singular(node)
nit-pick: singular`<space>`(node)

2022-04-12 10:38 UTC, yug-elastic commented on packages/apache_spark/changelog.yml
> +    - description: Refactor the nodes data stream to adjust its name to singular(node)
Done

2022-04-27 10:51 UTC, jsoriano approved these changes
LGTM

2022-04-28 06:48 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 
Classes | 100.0% (`0/0`) | :green_heart: 
Methods | 75.0% (`12/16`) | :grey_exclamation: 
Lines | 100.0% (`0/0`) | :green_heart: 
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-05-09 06:55 UTC, merged