Update Azure_logs readme
elastic/integrations pull request #3072
Opened 2022-04-12 09:13 UTC by ellis-elastic

Added links to Microsoft's documentation and tidied up the markdown

Type of change

- Enhancement

## What does this PR do?

Added links to Microsoft's documentation and tidied up the markdown

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2022-04-12 09:16 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3072/detail/PR-3072/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3072/detail/PR-3072/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3072/detail/PR-3072/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3072/detail/PR-3072/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-04-12T09:03:49.317Z&rangeTo=2022-04-12T09:23:49.317Z&transactionName=BUILD+Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=79f717ecd53c4c3d059e5dcc15a10aee&transactionId=88d64478befead8d)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-04-12T09:13:49.317+0000


* Duration: 2 min 23 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3072/detail/PR-3072/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3072/runs/1/steps/107/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-04-27 20:40 UTC, bmorelli25 requested changes

2022-04-27 20:40 UTC, bmorelli25 commented on packages/azure/_dev/build/docs/README.md
> +   * To export audit and sign-in logs to event hubs, users can follow the steps in Microsoft's [Stream Azure Active Directory logs to an Azure event hub tutorial]( https://docs.microsoft.com/en-us/az
The extra spaces before https need to be fixed in both of these URLs

2022-04-27 20:40 UTC, bmorelli25 commented on packages/azure/_dev/build/docs/README.md
> +The connection string required to communicate with Event Hubs. See the steps described in: [Get an Event Hubs connection string](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-get-conne
The period in this URL needs to be moved outside of the parenthesis.

2022-06-09 13:51 UTC, ellis-elastic commented on packages/azure/_dev/build/docs/README.md
> +The connection string required to communicate with Event Hubs. See the steps described in: [Get an Event Hubs connection string](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-get-conne
Fixed

2022-06-09 13:51 UTC, ellis-elastic commented on packages/azure/_dev/build/docs/README.md
> +   * To export audit and sign-in logs to event hubs, users can follow the steps in Microsoft's [Stream Azure Active Directory logs to an Azure event hub tutorial]( https://docs.microsoft.com/en-us/az
fixed

2022-06-13 08:42 UTC, tommyers-elastic submitted a review, later dismissed
changes look good! - can we get this rebased and merged?

2022-06-20 19:02 UTC, bmorelli25 commented
Looks like this needs to be built again:

> [2022-06-20T08:29:02.031Z] README.md is outdated. Rebuild the package with 'elastic-package build'

2022-06-21 20:18 UTC, bmorelli25 commented
Updated to match the new documentation guidelines for integrations. See [`01e16a1`](https://github.com/elastic/integrations/pull/3072/commits/01e16a1111fd3daab9057f71249c4260d0868509) for the changes. Also changed from a minor bump to a bug patch.

2022-06-21 20:26 UTC, bmorelli25 commented on packages/azure/_dev/build/docs/README.md
Reviewers: I'd love to add an example here. Can you help?

To assist, here's what we have for the system integration:

> For example, if you wanted to be notified when less than 10% of the disk space is still available, you
could install the System integration to send file system metrics to Elastic.
Then, you could view real-time updates to disk space used on your system in Kibana's _[Metrics System] Overview_ dashboard.
You could also set up a new rule in the Elastic Observability Metrics app to alert you when the percent free is
less than 10% of the total disk space.

2022-06-22 06:51 UTC, ellis-elastic commented on packages/azure/_dev/build/docs/README.md
I don't know if there is an Elastic style rule on this, but IMHO "you must" would be better than "you have to".
 You could even use the [RFC 2119](http://microformats.org/wiki/rfc-2119#:~:text=RFC%202119%20gives%20the%20following,absolute%20prohibition%20of%20the%20specification) rules.

2022-06-22 08:04 UTC, zmoog commented on packages/azure/_dev/build/docs/README.md
@bmorelli25, for the example, I have a couple of ideas we can work on:

* Azure sign-in logs are often used in security scenarios, like tracking the number of failed sign-in attempts and detecting possible brute force attacks.
* Azure activity logs deliver information like a VM failed to start because we exceeded a quota limit. We want to keep track of these events to better plan our capacity and negotiations with Azure representatives.

2022-06-22 22:24 UTC, colleenmcginnis reviewed
I left a few comments about consistency!

2022-06-22 22:24 UTC, colleenmcginnis commented on packages/azure/_dev/build/docs/README.md
> +Then visualize that data in Kibana, create alerts to notify you if something goes wrong,
We should probably pick one: "Azure Logs Integration", "azure logs integration", or "Azure logs integration".

2022-06-22 22:24 UTC, colleenmcginnis commented on packages/azure/_dev/build/docs/README.md
> +Log data streams collected by the Azure logs integration include activity, platform, sign-in, audit, and spring cloud logs.
I think Spring Cloud is the name of a product.

```suggestion
Log data streams collected by the Azure logs integration include activity, platform, sign-in, audit, and Spring Cloud logs.
```

2022-06-22 22:24 UTC, colleenmcginnis commented on packages/azure/_dev/build/docs/README.md
> +The azure logs integration retrieves activity, platform, sign-in, audit, and spring cloud data from [Azure](https://docs.microsoft.com/en-us/azure/?product=popular).
```suggestion
The azure logs integration retrieves activity, platform, sign-in, audit, and Spring Cloud data from [Azure](https://docs.microsoft.com/en-us/azure/?product=popular).
```

2022-06-22 22:24 UTC, colleenmcginnis commented on packages/azure/_dev/build/docs/README.md
> +Retrieves Azure activity logs. Control-plane events on Azure Resource Manager resources. Activity logs provide insight into the operations that were performed on resources in your subscription.
While not the most important thing, a quick spot check of other integrations suggests that we usually use a more generic term for the title of the section like:

```suggestion
### Activity logs
Retrieves Azure `activitylogs`. Control-plane events on Azure Resource Manager resources. Activity logs provide insight into the operations that were performed on resources in your subscription.
```

2022-06-22 22:52 UTC, bmorelli25 commented on packages/azure/_dev/build/docs/README.md
> +Then visualize that data in Kibana, create alerts to notify you if something goes wrong,
Good point. The integration name is "Azure Logs" and we lowercase integration, so I'll update to "Azure Logs integration."

2022-06-22 22:52 UTC, bmorelli25 commented on packages/azure/_dev/build/docs/README.md
>  ## Settings
Ok sure sure sure.

2022-06-22 23:00 UTC, bmorelli25 commented on packages/azure/_dev/build/docs/README.md
> +Log data streams collected by the Azure logs integration include activity, platform, sign-in, audit, and spring cloud logs.
Couldn't commit this one after updating the capitalization of Logs, so I snuck the fix into 65aef9e.

2022-06-23 08:02 UTC, ellis-elastic commented on packages/azure/_dev/build/docs/README.md
Fine with me

2022-06-23 08:22 UTC, zmoog commented on packages/azure/_dev/build/docs/README.md
@bmorelli25 examples LGTM!

2022-06-23 08:23 UTC, zmoog approved these changes

2022-06-23 13:27 UTC, merged