Add Integration package WebSphere Application Server with Servlet dat…
elastic/integrations pull request #3085
Opened 2022-04-13 11:57 UTC by kush-elastic

- Enhancement

## What does this PR do?

- Generated the skeleton of WebSphere Application Server integration package.
- Added 1 data stream (Servlet).
- Added data collection logic for the data streams.
- Added the ingest pipeline for the data streams.
- Mapped fields according to the ECS schema and added Fields metadata in the appropriate yaml files.
- Added dashboards and visualizations.
- Added pipeline test cases for the data stream.
- Added system test cases for the data stream.

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [X] I have added an entry to my package's changelog.yml file.
- [X] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally

- Clone integrations repo.
- Install elastic-package locally.
- Start elastic stack using elastic-package.
- Move to integrations/packages/websphere_application_server directory.
- Run the following command to run tests.
`elastic-package test`

## Related issues

- Relates #2847
- Relates #2922

## Screenshots

![websphere_application_server-servlet-dashboard-screenshot](https://user-images.githubusercontent.com/89848966/163174977-dcd7ae86-1a16-484f-a61d-cb44fc9f4eca.png)

2022-04-13 12:02 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3085/detail/PR-3085/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3085/detail/PR-3085/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3085/detail/PR-3085/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3085/detail/PR-3085/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_3085.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-04-13T11:48:03.349Z&rangeTo=2022-04-13T12:08:03.349Z&transactionName=BUILD+Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=ce59378b79b405425eb1193659518208&transactionId=a844a02f0cebad33)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-04-13T11:58:03.349+0000


* Duration: 4 min 45 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3085/detail/PR-3085/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Checks and builds Go sources`
<ul>
<li>Took 0 min 14 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3085/runs/1/steps/140/log/?start=0">here</a></li>
<li>Description: <code>mage -debug check</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3085/runs/1/steps/157/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-04-26 14:08 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`1/1`) | :green_heart: 
Files | 100.0% (`1/1`) | :green_heart: 2.941
Classes | 100.0% (`1/1`) | :green_heart: 2.941
Methods | 100.0% (`7/7`) | :green_heart: 12.218
Lines | 100.0% (`127/127`) | :green_heart: 11.422
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-05-04 08:04 UTC, kush-elastic commented
/test

2022-05-04 08:24 UTC, kush-elastic commented
/test

2022-05-20 10:26 UTC, yug-elastic requested changes
Requested some changes.

2022-05-20 10:26 UTC, yug-elastic commented on packages/websphere_application_server/data_stream/servlet/_dev/test/pipeline/test-servlet-metrics.json-expected.json
> +                    "concurrent_requests": 0,
How about grouping `concurrent_requests` and `requests_processed` to `requests.concurrent` and `requests.processed`?

2022-05-20 10:26 UTC, yug-elastic commented on packages/websphere_application_server/data_stream/servlet/_dev/test/pipeline/test-servlet-metrics.json-expected.json
> +                    "responses_processed": 0
If we change `requests_processed` to `requests.processed`, I think we should also nest this like `responses.processed`.

2022-05-20 10:26 UTC, yug-elastic commented on packages/websphere_application_server/data_stream/servlet/fields/fields.yml
> +            total number of requests that a servlet processed for the specified URL.
nit:
```suggestion
            Total number of requests that a servlet processed for the specified URL.
```

2022-05-20 10:26 UTC, yug-elastic commented on packages/websphere_application_server/data_stream/servlet/fields/fields.yml
> +                The total time spent(in seconds) per URL for the AsyncContext response to complete.
nit:
```suggestion
                The total time spent (in seconds) per URL for the AsyncContext response to complete.
```

2022-05-20 10:26 UTC, yug-elastic commented on packages/websphere_application_server/data_stream/servlet/fields/fields.yml
> +            The total time spent(in seconds) per servlet for the AsyncContext response to complete.
nit:
```suggestion
            The total time spent (in seconds) per servlet for the AsyncContext response to complete.
```

2022-05-20 10:39 UTC, kush-elastic commented on packages/websphere_application_server/data_stream/servlet/_dev/test/pipeline/test-servlet-metrics.json-expected.json
> +                    "concurrent_requests": 0,
Makes sense, thanks!

2022-05-20 12:07 UTC, yug-elastic approved these changes
LGTM!

2022-05-24 07:22 UTC, ishleenk17 reviewed
How about the docker compose file in this data stream ?

2022-05-25 04:41 UTC, ishleenk17 approved these changes

2022-05-25 04:56 UTC, merged