[oracle_weblogic] Add Integration Package with Deployed Application Data Stream
elastic/integrations pull request #3121
Opened 2022-04-19 13:14 UTC by kush-elastic

- Enhancement

## What does this PR do?

- Generated the skeleton of Oracle WebLogic integration package.
- Added 1 data stream (Deployed Application).
- Added data collection logic for the data streams.
- Added the ingest pipeline for the data streams.
- Mapped fields according to the ECS schema and added Fields metadata in the appropriate yaml files.
- Added dashboards and visualizations.
- Added system test cases for the data stream.

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally

- Clone integrations repo.
- Install elastic-package locally.
- Start elastic stack using elastic-package.
- Move to integrations/packages/oracle_weblogic directory.
- Run the following command to run tests.
`elastic-package test`

## Related issues

- Relates #2823
- Relates #2910
- Relates #3066
- Relates #3067
- Relates #3068
- Relates #3069

## Screenshots

![image](https://user-images.githubusercontent.com/89848966/164011730-7a129897-8f59-45d6-b4c7-810d9b034250.png)

2022-04-19 13:18 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3121/detail/PR-3121/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3121/detail/PR-3121/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3121/detail/PR-3121/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3121/detail/PR-3121/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_3121.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-04-19T13:04:39.143Z&rangeTo=2022-04-19T13:24:39.143Z&transactionName=BUILD+Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=512d319a8607ab3bc9f10ed3b86f78a7&transactionId=ed21c11b5e22afc1)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-04-19T13:14:39.143+0000


* Duration: 4 min 50 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3121/detail/PR-3121/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Checks and builds Go sources`
<ul>
<li>Took 0 min 26 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3121/runs/1/steps/140/log/?start=0">here</a></li>
<li>Description: <code>mage -debug check</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3121/runs/1/steps/157/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-05-02 16:48 UTC, kush-elastic commented
/test

2022-05-02 17:03 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 3.21
Classes | 100.0% (`0/0`) | :green_heart: 3.21
Methods | 75.0% (`3/4`) | :-1: -13.28
Lines | 100.0% (`0/0`) | :green_heart: 11.1
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-05-11 16:14 UTC, kush-elastic commented
/test

2022-05-12 08:15 UTC, kush-elastic commented
/test

2022-05-16 04:55 UTC, kush-elastic commented
/test

2022-05-28 07:31 UTC, kush-elastic commented
/test

2022-05-30 16:50 UTC, kush-elastic commented
/test

2022-05-31 13:32 UTC, yug-elastic requested changes
Requested some changes

2022-05-31 13:32 UTC, yug-elastic commented on packages/oracle_weblogic/data_stream/deployed_application/elasticsearch/ingest_pipeline/default.yml
> +      if: ctx.oracle_weblogic.deployed_application.deployment.state_value == 0
Using a painless script with a `HashMap` seems to be a better option here.

2022-05-31 13:32 UTC, yug-elastic commented on packages/oracle_weblogic/data_stream/deployed_application/elasticsearch/ingest_pipeline/default.yml
> +  - remove:
Please move `remove` to the end

2022-06-06 05:17 UTC, yug-elastic approved these changes
LGTM!

2022-06-07 10:36 UTC, agithomas approved these changes
Looks good to me

2022-06-07 10:45 UTC, merged