[ci][terraform][aws] tags with metadata
elastic/integrations pull request #3126
Opened 2022-04-19 17:12 UTC by v1v

## What does this PR do?

Create the below tags in the terraform resources for AWS:
- `Environment` = "CI"
- `Owner`           = "Beats"
- `Branch`          => dynamic value
- `Build`             => dynamic value 
- `CreatedDate` => dynamic value

## Why is it important?

Help with tearing down any of the ephemeral resources which were not successfully removed as part of the system tests.

## Further details

> BUILD_ID
The current build ID, identical to BUILD_NUMBER for builds created in 1.597+, but a YYYY-MM-DD_hh-mm-ss timestamp for older builds.

> BRANCH_NAME
For a multibranch project, this will be set to the name of the branch being built, for example in case you wish to deploy to production from master but not from feature branches; if corresponding to some kind of change request, the name is generally arbitrary (refer to CHANGE_ID and CHANGE_TARGET).

Timestamp collected from https://javadoc.jenkins-ci.org/hudson/model/Run.html#getTimestampString2--

2022-04-19 17:59 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3126/detail/PR-3126/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3126/detail/PR-3126/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3126/detail/PR-3126/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3126/detail/PR-3126/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_3126.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-04-19T17:02:44.992Z&rangeTo=2022-04-19T17:22:44.992Z&transactionName=BUILD+Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=92c5a866ab272353ba76acb569ebc92e&transactionId=a8f72634de442747)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-04-19T17:12:44.992+0000


* Duration: 47 min 31 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3126/detail/PR-3126/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Boot up the Elastic stack`
<ul>
<li>Took 2 min 53 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3126/runs/1/steps/7814/log/?start=0">here</a></li>
<li>Description: <code>../../build/elastic-package stack up -d -v --version 7.16.0</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3126/runs/1/steps/18631/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-04-20 08:12 UTC, v1v commented on .ci/Jenkinsfile
> +             "TF_VAR_CREATED_DATE=${current.getRawBuild().getTimestampString2()}"]) {
```suggestion
             "TF_VAR_CREATED_DATE=${currentBuild.getRawBuild().getTimestampString2()}"]) {
```

2022-04-20 10:47 UTC, mtojek requested changes
I'm setting a blocker on this to merge the https://github.com/elastic/elastic-package/pull/792 first, then iterate on this one.

2022-04-21 13:42 UTC, mtojek reviewed
As the [PR](https://github.com/elastic/elastic-package/pull/792) changed the implementation of elastic-package, let's first [release a new version](https://github.com/elastic/elastic-package#release-process). It's just about Git tagging the latest commit in the main branch.

2022-04-21 18:08 UTC, kuisathaverat approved these changes

2022-04-25 08:53 UTC, v1v commented
I just merged the PR for the `elastic-package` and created the tag https://github.com/elastic/elastic-package/releases/tag/v0.47.0

2022-04-25 09:31 UTC, mtojek commented
Version bump PR here: https://github.com/elastic/integrations/pull/3182

2022-04-25 10:25 UTC, v1v commented
/test

2022-04-25 11:43 UTC, v1v commented on .ci/Jenkinsfile
> +    withEnv(["TF_VAR_BRANCH=${env.BRANCH_NAME.toLowerCase()}",
For some reason these changes are not consumed:

```
terraform_1  |       + tags                                 = {
terraform_1  |           + "Name" = "elastic-package-test-33598"
terraform_1  |         }
terraform_1  |       + tags_all                             = {
terraform_1  |           + "Name"         = "elastic-package-test-33598"
terraform_1  |           + "branch"       = "unknown-branch"
terraform_1  |           + "build"        = "unknown-build"
terraform_1  |           + "created_date" = "unknown-date"
terraform_1  |           + "environment"  = "unknown-environment"
terraform_1  |           + "repo"         = "unknown-repo-name"
terraform_1  |         }
```

2022-04-25 11:43 UTC, mtojek commented
@v1v Please merge the main branch, so that this PR will pick the last bumped version.

2022-04-25 11:45 UTC, v1v commented
@mergifyio rebase

2022-04-25 12:35 UTC, v1v commented on .ci/Jenkinsfile
> +    withEnv(["TF_VAR_BRANCH=${env.BRANCH_NAME.toLowerCase()}",
Somehow some env variables are not populated from the CI:

```
terraform_1  |       + tags                                 = {
terraform_1  |           + "Name" = "elastic-package-test-17719"
terraform_1  |         }
terraform_1  |       + tags_all                             = {
terraform_1  |           + "Name"         = "elastic-package-test-17719"
terraform_1  |           + "branch"       = "unknown"
terraform_1  |           + "build"        = "6"
terraform_1  |           + "created_date" = "unknown"
terraform_1  |           + "environment"  = "unknown"
terraform_1  |           + "repo"         = "integrations"
```

I guess, the elastic-packages has a higher precendence:
- https://github.com/elastic/elastic-package/pull/792/files#diff-1d4bd2c1ad56472b4dc4c97566e6ce9dc00bda82eb59cf14d1ab8d5c930a1fe0R9-R14

2022-04-25 12:44 UTC, mtojek commented on .ci/Jenkinsfile
> +    withEnv(["TF_VAR_BRANCH=${env.BRANCH_NAME.toLowerCase()}",
I would start with investigating why the releasing job for v0.47.0 failed: https://beats-ci.elastic.co/job/Ingest-manager/job/elastic-package/job/v0.47.0/

2022-04-25 12:46 UTC, mtojek commented on .ci/Jenkinsfile
> +    withEnv(["TF_VAR_BRANCH=${env.BRANCH_NAME.toLowerCase()}",
@v1v It looks like we need a fix:

```
terraform_1  | Plan: 1 to add, 0 to change, 0 to destroy.
terraform_1  | google_compute_instance.default: Creating...
terraform_1  |
terraform_1  | Error: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.labels': ''. Label value 'v0.47.0' violates format constraints. The value can only contain lowercase letters, numeric characters, underscores and dashes. The value can be at most 63 characters long. International characters are allowed., invalid
terraform_1  |
terraform_1  |   with google_compute_instance.default,
terraform_1  |   on compute.tf line 7, in resource "google_compute_instance" "default":
terraform_1  |    7: resource "google_compute_instance" "default" {
terraform_1  |
terraform_1  | + echo 'Terraform definitions applied.'
terraform_1  | Terraform definitions applied.
terraform_1  | + set +x
```

2022-04-25 14:14 UTC, v1v commented on .ci/Jenkinsfile
> +    withEnv(["TF_VAR_BRANCH=${env.BRANCH_NAME.toLowerCase()}",
Fixed already added to the elastic-package and also here, so the new metadata is populated now

```
terraform_1  |       + tags                                 = {
terraform_1  |           + "Name" = "elastic-package-test-73355"
terraform_1  |         }
terraform_1  |       + tags_all                             = {
terraform_1  |           + "Name"         = "elastic-package-test-73355"
terraform_1  |           + "branch"       = "pr-3126"
terraform_1  |           + "build"        = "8"
terraform_1  |           + "created_date" = "1650891241341"
terraform_1  |           + "environment"  = "ci"
terraform_1  |           + "repo"         = "integrations"
terraform_1  |         }
```

2022-04-25 14:56 UTC, mtojek commented on .ci/Jenkinsfile
> +    BRANCH_NAME_LOWER_CASE = "${env.BRANCH_NAME.toLowerCase().replaceAll('\\.', '_')}"
I guess that we have to apply a consistent fix as we agree on https://github.com/elastic/elastic-package/pull/799

2022-04-25 15:18 UTC, v1v commented on .ci/Jenkinsfile
> +    BRANCH_NAME_LOWER_CASE = "${env.BRANCH_NAME.toLowerCase().replaceAll('\\.', '_')}"
```suggestion
    BRANCH_NAME_LOWER_CASE = "${env.BRANCH_NAME.toLowerCase().replaceAll('[^a-z0-9-]', '-')}"
```

2022-04-25 16:36 UTC, v1v commented
> Just double-checking, system tests for GCP are not there yet, right?

I could not find any other references to terraform but only in the `aws` package

2022-04-26 07:50 UTC, mtojek commented
I checked these errors and they're unrelated. I guess that you can merge this PR.

2022-04-26 08:17 UTC, merged