update Kubernetes readme
elastic/integrations pull request #3139
Opened 2022-04-20 12:47 UTC by ellis-elastic

improved the wording of the link to Kubernetes documentation

Type of change

- Enhancement

## What does this PR do?

improved the wording of the link to Kubernetes documentation

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2022-04-20 12:57 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3139/detail/PR-3139/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3139/detail/PR-3139/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3139/detail/PR-3139/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3139/detail/PR-3139/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_3139.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-04-20T12:38:03.239Z&rangeTo=2022-04-20T12:58:03.239Z&transactionName=BUILD+Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=96ab5be0d5a9d5efda8e774714821fb4&transactionId=d705b8ec0dada77e)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-04-20T12:48:03.239+0000


* Duration: 9 min 7 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3139/detail/PR-3139/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Check integration: kubernetes`
<ul>
<li>Took 0 min 2 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3139/runs/1/steps/792/log/?start=0">here</a></li>
<li>Description: <code>../../build/elastic-package check -v</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3139/runs/1/steps/828/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-04-21 11:41 UTC, ChrsMark approved these changes

2022-04-27 20:26 UTC, bmorelli25 requested changes

2022-04-27 20:26 UTC, bmorelli25 commented on packages/kubernetes/_dev/build/docs/README.md
> +</DocCallOut>
This doc callout is specific to our new documentation build. It won't work in raw markdown. Can you remove this please?

2022-05-10 16:11 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 3.589
Classes | 100.0% (`0/0`) | :green_heart: 3.589
Methods | 94.872% (`74/78`) | :+1: 6.588
Lines | 100.0% (`0/0`) | :green_heart: 10.972
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-06-09 08:47 UTC, ellis-elastic commented on packages/kubernetes/_dev/build/docs/README.md
> +</DocCallOut>
Hi. I've done that, and pushed it up.

2022-06-15 08:41 UTC, ellis-elastic commented on packages/kubernetes/docs/README.md
> +</DocCallOut>
my mistake. I've rerun build

2022-06-15 14:37 UTC, bmorelli25 commented on packages/kubernetes/docs/README.md
> +</DocCallOut>
Thanks!

2022-06-16 21:16 UTC, merged