Update tenable.sc readme
elastic/integrations pull request #3165
Opened 2022-04-21 14:21 UTC by ellis-elastic

added links to tenable documentation and made the English clearer.

Type of change

- Enhancement

## What does this PR do?

added links to tenable documentation and made the English clearer. 

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2022-04-21 14:30 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3165/detail/PR-3165/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3165/detail/PR-3165/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3165/detail/PR-3165/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3165/detail/PR-3165/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_3165.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-04-21T14:11:57.352Z&rangeTo=2022-04-21T14:31:57.352Z&transactionName=BUILD+Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=a0f2b4dba455b26e62a4e3bec9556c5b&transactionId=7bf39af313c9b8b8)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-04-21T14:21:57.352+0000


* Duration: 8 min 9 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3165/detail/PR-3165/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Check integration: tenable_sc`
<ul>
<li>Took 0 min 1 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3165/runs/1/steps/796/log/?start=0">here</a></li>
<li>Description: <code>../../build/elastic-package check -v</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3165/runs/1/steps/832/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-04-27 19:56 UTC, bmorelli25 requested changes

2022-04-27 19:56 UTC, bmorelli25 commented on packages/tenable_sc/_dev/build/docs/README.md
> +Enable API keys to allow users to perform API key authentication. See: [Enable API Key Authentication]() in Tenable's documentation for more information.
It looks like the link destination was missed here

2022-04-27 19:56 UTC, bmorelli25 commented on packages/tenable_sc/_dev/build/docs/README.md
> +</DocCallOut>
Unfortunately these `<DocCallOut title="Note">` only work in our documentation system. These won't work in raw markdown. This will need to be changed back into a generic "note" that works in markdown.

2022-04-27 20:08 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`3/3`) | :green_heart: 
Files | 100.0% (`3/3`) | :green_heart: 2.857
Classes | 100.0% (`3/3`) | :green_heart: 2.857
Methods | 100.0% (`41/41`) | :green_heart: 11.905
Lines | 96.852% (`923/953`) | :+1: 8.014
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-06-07 19:36 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2022-06-09 13:19 UTC, ellis-elastic commented on packages/tenable_sc/_dev/build/docs/README.md
> +Enable API keys to allow users to perform API key authentication. See: [Enable API Key Authentication]() in Tenable's documentation for more information.
oops. Fixed

2022-06-10 09:29 UTC, ellis-elastic commented on packages/tenable_sc/_dev/build/docs/README.md
> +6. The "Your API Key" window appears, displaying the access key and secret key for the user.
I've reworded it so that it links to Tenable's documentation

2022-06-10 10:18 UTC, r00tu53r approved these changes
Thank you! LGTM

2022-06-24 20:00 UTC, bmorelli25 approved these changes

2022-06-24 20:01 UTC, merged