Add Integration Package with ThreadPool Data stream
elastic/integrations pull request #3189
Opened 2022-04-25 16:16 UTC by kush-elastic

- Enhancement

## What does this PR do?

- Generated the skeleton of Oracle WebLogic integration package.
- Added 1 data stream (ThreadPool).
- Added data collection logic for the data streams.
- Added the ingest pipeline for the data streams.
- Mapped fields according to the ECS schema and added Fields metadata in the appropriate yaml files.
- Added dashboards and visualizations.
- Added system test cases for the data stream.

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally

- Clone integrations repo.
- Install elastic-package locally.
- Start elastic stack using elastic-package.
- Move to integrations/packages/oracle_weblogic directory.
- Run the following command to run tests.
`elastic-package test`

## Related issues

- Relates #2823
- Relates #2910
- Relates #3066
- Relates #3067
- Relates #3068
- Relates #3069
- Relates #3121

## Screenshots

![Threadpool](https://user-images.githubusercontent.com/89848966/165130340-25e18552-7b38-43f6-b324-da2d4ff520e4.png)

2022-04-25 16:29 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3189/detail/PR-3189/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3189/detail/PR-3189/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3189/detail/PR-3189/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3189/detail/PR-3189/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_3189.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-04-25T16:06:29.346Z&rangeTo=2022-04-25T16:26:29.346Z&transactionName=BUILD+Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=274d6a434464c92acaea993503867808&transactionId=49a8a31f1c8c6ef8)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-04-25T16:16:29.346+0000


* Duration: 12 min 30 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 13  |
| Skipped      | 0 |
| Total        | 13   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-04-29 16:34 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 2.799
Classes | 100.0% (`0/0`) | :green_heart: 2.799
Methods | 75.0% (`3/4`) | :-1: -13.231
Lines | 100.0% (`0/0`) | :green_heart: 11.068
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-05-30 07:45 UTC, yug-elastic requested changes
Requested some changes

2022-05-30 07:45 UTC, yug-elastic commented on packages/oracle_weblogic/_dev/build/docs/README.md
> +- Add default path for jolokia.
nit: `Jolokia`

2022-05-30 07:45 UTC, yug-elastic commented on packages/oracle_weblogic/_dev/build/docs/README.md
> +- Configuring Jolokia for Weblogic
nit: `WebLogic`

2022-05-30 07:45 UTC, yug-elastic commented on packages/oracle_weblogic/data_stream/threadpool/elasticsearch/ingest_pipeline/default.yml
> +  - remove:
Please put this `remove` processor at the end

2022-05-30 09:38 UTC, yug-elastic approved these changes
LGTM!

2022-06-02 09:26 UTC, agithomas commented on packages/oracle_weblogic/kibana/lens/oracle_weblogic-c31dabf0-c132-11ec-aaae-35e5cf8554e6.json
> +        "title": "Live Daemon and Non-Daemon Threads [Metrics Oracle WebLogic]",
Please refer to the previous comment

2022-06-06 04:37 UTC, agithomas commented on packages/oracle_weblogic/data_stream/threadpool/fields/fields.yml
> +              description: Current number of live daemon and non-daemon threads.
You may need to update  below files

 the 
```
packages/oracle_weblogic/img/oracle_weblogic-threadpool.png
packages/oracle_weblogic/kibana/lens/oracle_weblogic-c31dabf0-c132-11ec-aaae-35e5cf8554e6.json
```

2022-06-06 07:05 UTC, agithomas approved these changes
Looks good to me

2022-06-06 07:08 UTC, merged