Add Integration package WebSphere Application Server with Session Man…
elastic/integrations pull request #3199
Opened 2022-04-26 13:50 UTC by kush-elastic

- Enhancement

## What does this PR do?

- Generated the skeleton of WebSphere Application Server integration package.
- Added 1 data stream (session_manager).
- Added data collection logic for the data streams.
- Added the ingest pipeline for the data streams.
- Mapped fields according to the ECS schema and added Fields metadata in the appropriate yaml files.
- Added dashboards and visualizations.
- Added pipeline test cases for the data stream.
- Added system test cases for the data stream.

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [X] I have added an entry to my package's changelog.yml file.
- [X] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally

- Clone integrations repo.
- Install elastic-package locally.
- Start elastic stack using elastic-package.
- Move to integrations/packages/websphere_application_server directory.
- Run the following command to run tests.
`elastic-package test`

## Related issues

- Relates #2847
- Relates #2922
- Relates #3138 
- Relates #3085

## Screenshots

![websphere_application_server-session_manager-dashboard-screenshot](https://user-images.githubusercontent.com/89848966/165314984-941af8b0-0f11-4656-a5e5-79845cd447e7.png)

2022-04-26 14:05 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3199/detail/PR-3199/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3199/detail/PR-3199/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3199/detail/PR-3199/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3199/detail/PR-3199/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_3199.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-04-26T13:40:19.650Z&rangeTo=2022-04-26T14:00:19.650Z&transactionName=BUILD+Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=f3763c35815cb724db1058344b6f00e5&transactionId=cc3a576dd04e411f)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-04-26T13:50:19.650+0000


* Duration: 15 min 17 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 10  |
| Skipped      | 0 |
| Total        | 10   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-04-26 14:05 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`1/1`) | :green_heart: 
Files | 100.0% (`1/1`) | :green_heart: 2.941
Classes | 100.0% (`1/1`) | :green_heart: 2.941
Methods | 100.0% (`7/7`) | :green_heart: 12.218
Lines | 100.0% (`132/132`) | :green_heart: 11.422
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-05-25 07:08 UTC, yug-elastic requested changes
Requested some changes

2022-05-25 07:31 UTC, kush-elastic commented on packages/websphere_application_server/data_stream/session_manager/_dev/test/pipeline/test-session-manager-metrics.json-expected.json
> +                        "create": 0,
I guess `session.created` would be better. Thanks!

2022-05-25 12:43 UTC, yug-elastic approved these changes
LGTM!

2022-05-31 11:14 UTC, ishleenk17 commented on packages/websphere_application_server/data_stream/session_manager/fields/fields.yml
> +          description: The number of session objects that were created by the server.
Can we have sessions here instead of session objects ?
To keep the description consistent across sessions group ?

2022-05-31 11:16 UTC, ishleenk17 requested changes

2022-05-31 11:16 UTC, ishleenk17 commented on packages/websphere_application_server/data_stream/session_manager/fields/fields.yml
> +      description: The number of times that the cache was discarded.
nit: The number of times the cache was discarded

2022-05-31 12:15 UTC, ishleenk17 approved these changes

2022-05-31 12:16 UTC, merged