[santa] update ingest pipeline to match new log format
elastic/integrations pull request #3347
Opened 2022-05-12 11:59 UTC by DamiaPoquet

## What does this PR do?

The log output for Santa changed on versions [0.9.19](https://github.com/google/santa/releases/tag/0.9.19), [v0.9.20](https://github.com/google/santa/releases/tag/0.9.20), and [0.9.21](https://github.com/google/santa/releases/tag/0.9.21), making this integration fundamentally broken since then. This PR addresses the new log format parsing.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] Check log parsing
- [ ] ECS 8.2 doesn't contains a field for process `pidversion`

## How to test this PR locally

## Related issues

I didn't find any related issue, although it seems to be broken since 2017.

2022-05-12 12:02 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3347/detail/PR-3347/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3347/detail/PR-3347/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3347/detail/PR-3347/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3347/detail/PR-3347/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-05-12T11:49:26.505Z&rangeTo=2022-05-12T12:09:26.505Z&transactionName=Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=89a7bfd8c73730189927972ec4ecc068&transactionId=2a93a4a1cf7aee1c)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-05-12T11:59:26.505+0000


* Duration: 3 min 53 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3347/detail/PR-3347/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3347/runs/1/steps/117/log/?start=0">here</a></li>

</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3347/runs/1/steps/88/log/?start=0">here</a></li>
<li>Description: <code>githubApiCall: The REST API call https://api.github.com/orgs/elastic/members/DamiaPoquet return the message : java.lang.Exception: httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/DamiaPoquet : httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/DamiaPoquet : Code: 404Error: {"message":"User does not exist or is not a member of the organization","documentation_url":"https://docs.github.com/rest/reference/orgs#check-organization-membership-for-a-user"}</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-05-16 00:24 UTC, efd6 requested changes
Can we leave the original tests in place while adding the new ones.

2022-05-16 00:24 UTC, efd6 commented
/test

2022-05-16 10:20 UTC, efd6 commented
Do we know that these are no users still on the old version? If we are going to drop support for the older log format then this should really be a breaking change and marked as such.

2022-05-16 14:01 UTC, DamiaPoquet commented
In my opinion, it doesn't make sense to support a pre-release output format for Santa. All the GA versions are outputting logs in the new format.

I'll mark this release as a breaking change.

2022-05-16 15:47 UTC, andrewkroh commented
/test

2022-05-16 15:56 UTC, andrewkroh requested changes
Thanks for the fix!

2022-05-16 15:56 UTC, andrewkroh commented on packages/santa/changelog.yml
> +    - description: Update log format
How about something like this to give a bit more detail...

```suggestion
    - description: Update log format to support the GA releases of Santa. The pre-GA Santa log format (circa 2017) is no longer accepted.
```

2022-05-16 15:56 UTC, andrewkroh commented on packages/santa/changelog.yml
> +- version: "2.2.0"
Given it's a breaking change, let's roll this over to 3.0.0.

2022-05-16 22:25 UTC, efd6 commented on packages/santa/data_stream/log/_dev/test/pipeline/test-santa-raw.log-expected.json
> +                "pidversion": 1097765,
`process.pidversion` is not an allowed ECS field, so it should be placed in `santa`, but we could construct a `process.entity_id` with it and `process.pid`, something like "{{{process.pid}}}-{{[process.pidversion}}}". @andrewkroh WDYT? We don't have any examples of it being used anywhere else AFAICS.

2022-05-16 22:55 UTC, andrewkroh commented on packages/santa/data_stream/log/_dev/test/pipeline/test-santa-raw.log-expected.json
> +                "pidversion": 1097765,
That sounds like a good idea. I am looking for some documentation on what `pidversion` in the Santa logs means just to confirm that it makes sense to use it as part of `process.entity_id`.

2022-05-16 23:23 UTC, efd6 commented on packages/santa/data_stream/log/_dev/test/pipeline/test-santa-raw.log-expected.json
> +                "pidversion": 1097765,
From what I could find it's just another pid, but from the kernel to prevent pid collision on pid rollover, e.g. https://www.exploit-db.com/exploits/46648

2022-05-17 07:39 UTC, DamiaPoquet commented on packages/santa/data_stream/log/_dev/test/pipeline/test-santa-raw.log-expected.json
> +                "pidversion": 1097765,
I have changed the field name to `santa.pidversion` while the ECS is not ready yet to support it.

2022-05-17 08:32 UTC, efd6 commented
/test

2022-05-17 19:34 UTC, andrewkroh approved these changes
LGTM. We could add a `process.entity_id` independently.

I was curious how Elastic Endpoint generates its `process.entity_id` to see if we could replicate that here. The code is

```
    (void)StringLib::FormatDuplicate(str, "%s-%llu-%llu.%llu", Cache::GetEndpointID().c_str(),
        (unsigned long long)pid, (unsigned long long)ts.tv_sec, (unsigned long long)ts.tv_nsec);
    (void)Titan_Encoding_toBase64(str.c_str(), str.size(), (void **)&(pBase64), &(base64Size));
```

But given that the start time we have is coming from the logger timestamp and lacks nanosecond precision, I don't think we can. So the only thing I would say is that if we do add an entity_id we should consider incorporating the agent ID.

2022-05-17 22:45 UTC, efd6 approved these changes

2022-05-17 22:46 UTC, efd6 commented
> But given that the start time we have is coming from the logger timestamp and lacks nanosecond precision, I don't think we can. So the only thing I would say is that if we do add an entity_id we should consider incorporating the agent ID.

SGTM

2022-05-18 02:27 UTC, merged