[Modsec] Fix date format & Json issues
elastic/integrations pull request #3363
Opened 2022-05-17 07:49 UTC by emnp

## What does this PR do?

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally
```
# cd integrations/packages/modsecurity
# elastic-package build
# elastic-package stack up -d -v
# eval "$(elastic-package stack shellinit)"
# elastic-package test  -v
```

## Related issues

-

## Screenshots

2022-05-17 07:53 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3363/detail/PR-3363/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3363/detail/PR-3363/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3363/detail/PR-3363/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3363/detail/PR-3363/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-05-17T07:40:03.864Z&rangeTo=2022-05-17T08:00:03.864Z&transactionName=Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=e0213e503740b1af78156e11952c4f18&transactionId=3a1f71c153657791)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-05-17T07:50:03.864+0000


* Duration: 3 min 36 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3363/detail/PR-3363/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3363/runs/1/steps/117/log/?start=0">here</a></li>

</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3363/runs/1/steps/88/log/?start=0">here</a></li>
<li>Description: <code>githubApiCall: The REST API call https://api.github.com/orgs/elastic/members/emnp return the message : java.lang.Exception: httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/emnp : httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/emnp : Code: 404Error: {"message":"User does not exist or is not a member of the organization","documentation_url":"https://docs.github.com/rest/reference/orgs#check-organization-membership-for-a-user"}</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-05-23 18:35 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2022-05-24 15:06 UTC, r00tu53r reviewed
Thank you for your contribution. I have a few comments around the date format. Also, can you please add a change log entry to `packages/modsecurity/changelog.yml` and update the version in `packages/modsecurity/manifest.yml`too.

2022-05-24 15:06 UTC, r00tu53r commented on packages/modsecurity/data_stream/auditlog/elasticsearch/ingest_pipeline/default.yml
> +        - E MMM  d HH:mm:ss yyyyXXX
Is this justification required ? 

I see modsecurity sets the `time_stamp`  [here](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/transaction.cc#L1688).  It calls `ctime` via `ascTime` [here](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/transaction.cc#L1669) which only prints to this format [here](https://en.cppreference.com/w/cpp/chrono/c/ctime).

2022-06-01 11:06 UTC, emnp commented
Hi @r00tu53r, this issue https://github.com/elastic/integrations/issues/2859 is fixed in this version too.

2022-06-06 04:27 UTC, r00tu53r commented
/test

2022-06-06 05:01 UTC, efd6 requested changes
It's unclear from the PR description what this is fixing (there is no issue and no comment on what the change is intended to address).

Can you explain why the old test inputs are being completely replaced? Were they wrong in some way? If so, please explain this in the PR. If they are not explicitly incorrect, please leave them and append new cases where needed.

A number of files have had there modes changed to include the execute bit set for all users. Please make sure that regular files are ugo-x unless the need to be otherwise.

2022-06-06 06:18 UTC, emnp commented
Hi @efd6, I edited the pr description. Please kindly check.

I used new test inputs with multiple date formats to check all the date formats were working well and also added new test inputs for the ModSecurity with apache.

2022-06-06 06:49 UTC, efd6 commented
Many of the files still show an addition of the x flags on their modes and there are still significant non-append changes to inputs. Please revert the deletions in test cases or explain why they need to be deleted.

2022-06-24 03:32 UTC, efd6 commented
Thank you, it is looking good now. Please resolve the conflict.

2022-06-24 03:59 UTC, emnp commented
Hello @efd6 , the conflicts are resolved.

2022-06-24 06:18 UTC, efd6 commented
/test

2022-06-24 06:42 UTC, efd6 requested changes

2022-06-24 06:42 UTC, efd6 commented on packages/modsecurity/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/1603
```suggestion
      link: https://github.com/elastic/integrations/pull/1603
```

2022-06-24 06:42 UTC, efd6 commented on packages/modsecurity/data_stream/auditlog/fields/fields.yml
> +          description: Details message of the audit event.
```suggestion
          description: Details message of the audit event.
```

2022-06-24 06:42 UTC, efd6 commented on packages/modsecurity/data_stream/auditlog/fields/fields.yml
> +          description: Details message of the audit event.
```suggestion
          description: Details message of the audit event.
```

2022-06-24 07:13 UTC, efd6 commented
/test

2022-06-24 07:32 UTC, efd6 requested changes
You will need to run `elastic-package build` after making changes.

The pipeline yaml files appear to have been indented extra, can you de-indent them. It looks like the processors are an extra 4 spaces to the right.

2022-06-24 07:32 UTC, efd6 commented on packages/modsecurity/_dev/build/docs/README.md
> +The logs were tested with Modsecurity v3 with nginx connector and Modsecurity v3 with apachae connector.Change the default modsecurity logging format to json as per configuration
```suggestion
The logs were tested with ModSecurity v3 with nginx connector and ModSecurity v3 with Apache Connector. Change the default ModSecurity logging format to json as per configuration
```

2022-06-24 07:32 UTC, efd6 commented on packages/modsecurity/_dev/build/docs/README.md
> +> Be cautious to drop **the list of all rules that matched for the transaction (K)** in SecAuditLogParts. That part can make raw logs too long to parse.
```suggestion
> Be careful to drop **the list of all rules that matched for the transaction (K)** in SecAuditLogParts. That part can make raw logs too long to parse.
```

2022-06-24 07:32 UTC, efd6 commented on packages/modsecurity/data_stream/auditlog/elasticsearch/ingest_pipeline/apache-modsec.yml
> +                ctx._temps.result = ctx.json.audit_data.messages[0]
```suggestion
      - script:
          lang: painless
          source: >-
                ctx._temps.result = ctx.json.audit_data.messages[0]
          ignore_failure: true
```

2022-06-24 07:32 UTC, efd6 commented on packages/modsecurity/data_stream/auditlog/elasticsearch/ingest_pipeline/apache-modsec.yml
> +          if: "ctx?.tags == null || !(ctx.tags.contains('preserve_original_event'))"
```suggestion
          if: "ctx.tags == null || !(ctx.tags.contains('preserve_original_event'))"
```

2022-06-24 07:32 UTC, efd6 commented on packages/modsecurity/data_stream/auditlog/elasticsearch/ingest_pipeline/apache-modsec.yml
> +          ignore_missing: true
```suggestion
          ignore_missing: true
```
Please ensure there is a final new line.

2022-06-24 07:32 UTC, efd6 commented on packages/modsecurity/data_stream/auditlog/elasticsearch/ingest_pipeline/nginx-modsec.yml
> +          ignore_missing: true
```suggestion
          ignore_missing: true
```

Please ensure there is a final new line.

2022-06-24 07:32 UTC, efd6 commented on packages/modsecurity/data_stream/auditlog/_dev/test/pipeline/test-apache-audit.log
> +{"transaction":{"time":"25/Mar/2022:11:15:35 +0100","transaction_id":"Yj2WRzj5DcQDZ5V47KL4JQAAAAE","remote_address":"89.160.20.112","remote_port":47461,"local_address":"172.21.50.216","local_port":44
Add a newline; this event is not being processed by the tests.

2022-06-24 22:03 UTC, efd6 commented
/test

2022-06-24 22:18 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 3.456
Classes | 100.0% (`0/0`) | :green_heart: 3.456
Methods | 100.0% (`3/3`) | :green_heart: 11.172
Lines | 100.0% (`0/0`) | :green_heart: 10.052
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-06-25 00:48 UTC, efd6 commented
Almost there. Please fix the indentation in the pipelines and then run `elastic-package test pipeline -g`.

2022-06-27 04:55 UTC, emnp commented
Hi @efd6, need to run `elastic-package build` again?

2022-06-27 05:26 UTC, efd6 commented
/test

2022-06-27 07:17 UTC, efd6 commented on packages/modsecurity/data_stream/auditlog/elasticsearch/ingest_pipeline/apache-modsec.yml
> +        - '%{GREEDYDATA} \[file "%{GREEDYDATA:modsec.audit.details.file}"\] \[line "%{GREEDYDATA:_temps.line_number}"\] \[id "%{GREEDYDATA:modsec.audit.details.rule_id}"\] \[msg "%{GREEDYDATA:modsec.
This is only getting us the first element of the messages array. I don't think that is right; the first test case for example has three messages. I'm not sure that we are winning by doing this rather that just 
```
  - rename:
      field: json.audit_data.messages
      target_field: modsec.audit.messages
      ignore_missing: true
```
We could do what you are doing for for the first message, but for each, but this would need to be flattened, so we lose searchability again and are back approximately where we started.

An alternative would be to migrate from loginput to httpjson since it can split these into separate documents. That is a bigger change.

2022-06-27 11:01 UTC, efd6 commented
Please run `elastic-package build`.

2022-06-27 11:09 UTC, emnp commented
Already run `elastic-package build` before pushing.

2022-06-27 11:11 UTC, efd6 commented
When I run it I get this
```diff
diff --git a/packages/modsecurity/docs/README.md b/packages/modsecurity/docs/README.md
index a76c4ec07..3bb671561 100644
--- a/packages/modsecurity/docs/README.md
+++ b/packages/modsecurity/docs/README.md
@@ -59,6 +59,7 @@ The `Audit Log` dataset collects Modsecurity Audit logs.
 | host.os.family | OS family (such as redhat, debian, freebsd, windows). | keyword |
 | host.os.kernel | Operating system kernel version as a raw string. | keyword |
 | host.os.name | Operating system name, without the version. | keyword |
+| host.os.name.text | Multi-field of `host.os.name`. | text |
 | host.os.platform | Operating system platform (such centos, ubuntu, windows). | keyword |
 | host.os.version | Operating system version as a raw string. | keyword |
 | host.type | Type of host. For Cloud providers this can be the machine type like `t2.medium`. If vm, this could be the container, for example, or other information meaningful in your environment. | keyword |
@@ -85,6 +86,7 @@ The `Audit Log` dataset collects Modsecurity Audit logs.
 | source.address | Some event source addresses are defined ambiguously. The event will sometimes list an IP, a domain or a unix socket.  You should always store the raw address in the `.address` field. Then it should be duplicated to `.ip` or `.domain`, depending on which one it is. | keyword |
 | source.as.number | Unique number allocated to the autonomous system. The autonomous system number (ASN) uniquely identifies each network on the Internet. | long |
 | source.as.organization.name | Organization name. | keyword |
+| source.as.organization.name.text | Multi-field of `source.as.organization.name`. | match_only_text |
 | source.geo.city_name | City name. | keyword |
 | source.geo.continent_name | Name of the continent. | keyword |
 | source.geo.country_iso_code | Country ISO code. | keyword |
@@ -99,16 +101,21 @@ The `Audit Log` dataset collects Modsecurity Audit logs.
 | url.extension | The field contains the file extension from the original request url, excluding the leading dot. The file extension is only set if it exists, as not every url has a file extension. The leading period must not be included. For example, the value must be "png", not ".png". Note that when the file name has multiple extensions (example.tar.gz), only the last one should be captured ("gz", not "tar.gz"). | keyword |
 | url.fragment | Portion of the url after the `#`, such as "top". The `#` is not part of the fragment. | keyword |
 | url.original | Unmodified original url as seen in the event source. Note that in network monitoring, the observed URL may be a full URL, whereas in access logs, the URL is often just represented as a path. This field is meant to represent the URL as it was observed, complete or not. | wildcard |
+| url.original.text | Multi-field of `url.original`. | match_only_text |
 | url.path | Path of the request, such as "/search". | wildcard |
 | url.port | Port of the request, such as 443. | long |
 | url.query | The query field describes the query string of the request, such as "q=elasticsearch". The `?` is excluded from the query string. If a URL contains no `?`, there is no query field. If there is a `?` but no query, the query field exists with an empty string. The `exists` query can be used to differentiate between the two cases. | keyword |
 | url.scheme | Scheme of the request, such as "https". Note: The `:` is not part of the scheme. | keyword |
 | user.name | Short name or login of the user. | keyword |
+| user.name.text | Multi-field of `user.name`. | match_only_text |
 | user_agent.device.name | Name of the device. | keyword |
 | user_agent.name | Name of the user agent. | keyword |
 | user_agent.original | Unparsed user_agent string. | keyword |
+| user_agent.original.text | Multi-field of `user_agent.original`. | match_only_text |
 | user_agent.os.full | Operating system name, including the version or code name. | keyword |
+| user_agent.os.full.text | Multi-field of `user_agent.os.full`. | match_only_text |
 | user_agent.os.name | Operating system name, without the version. | keyword |
+| user_agent.os.name.text | Multi-field of `user_agent.os.name`. | match_only_text |
 | user_agent.os.version | Operating system version as a raw string. | keyword |
 | user_agent.version | Version of the user agent. | keyword |
 
```

2022-06-27 11:12 UTC, efd6 commented on packages/modsecurity/data_stream/auditlog/elasticsearch/ingest_pipeline/apache-modsec.yml
> +             - '%{GREEDYDATA} \[file "%{GREEDYDATA:modsec.audit.details.file}"\] \[line "%{GREEDYDATA:_temps.line_number}"\] \[id "%{GREEDYDATA:modsec.audit.details.rule_id}"\] \[msg "%{GREEDYDATA:mo
This isn't going to do what we want. I would like to think about this some more.

2022-06-28 06:09 UTC, efd6 commented on packages/modsecurity/data_stream/auditlog/elasticsearch/ingest_pipeline/apache-modsec.yml
> +             - '%{GREEDYDATA} \[file "%{GREEDYDATA:modsec.audit.details.file}"\] \[line "%{GREEDYDATA:_temps.line_number}"\] \[id "%{GREEDYDATA:modsec.audit.details.rule_id}"\] \[msg "%{GREEDYDATA:mo
I don't think this is currently feasible.

2022-06-28 07:11 UTC, efd6 reviewed
I think that we should defer some of the changes here until they are more able to be handled. The changes that I'm suggesting don't lock us into anything in the future and retain the data in a reasonably searchable format.

2022-06-28 07:11 UTC, efd6 commented on packages/modsecurity/data_stream/auditlog/elasticsearch/ingest_pipeline/apache-modsec.yml
> +      ignore_missing: true
This would be nice to have, but the options available to make this work and to have it provide a benefit are not here. So I think that for this change it should be deleted with a view to revisiting it in the future.

```suggestion
  - rename:
      field: json.audit_data.messages
      target_field: modsec.audit.details
      ignore_missing: true
  - script:
      lang: painless
      ignore_failure: true
      source: |
        if (ctx.modsec?.audit?.details == null || ctx.modsec.audit.details.length == 0) {
          return;
        }
        def details = ctx.modsec.audit.details;
        def messages = new ArrayList();
        for (def i = 0; i < details.length; i++) {
          def idx = details[i].indexOf(' ['); // Find first key value mark.
          if (idx < 0) {
            idx = details[i].length;
          }
          messages.add(details[i].substring(0, idx));
        }
        ctx.modsec.audit.messages = messages

```

2022-06-28 07:11 UTC, efd6 commented on packages/modsecurity/data_stream/auditlog/fields/fields.yml
> +          description: Details message of the audit event.
```suggestion
    - name: details
      type: flattened
      description: Modsecurity audit details.
```

2022-06-28 11:51 UTC, emnp commented
> 

 Thanks for your suggestion <3. I have updated it. Please take a look.

2022-06-28 22:02 UTC, efd6 commented
/test

2022-06-29 01:10 UTC, efd6 commented
Sorry there was a version bump. Can you resolve the conflicts? Looks good to me though after that.

2022-06-29 07:42 UTC, efd6 commented
Yes, if you resolve the conflicts using the current tip, you will have `ecs.version` set to 8.3.0. This is [here](https://github.com/elastic/integrations/blob/12529d0925596bcbebfd566523234fe597589c0b/packages/modsecurity/data_stream/auditlog/elasticsearch/ingest_pipeline/default.yml#L8-L10).

2022-06-29 10:14 UTC, efd6 commented
/test

2022-06-29 10:26 UTC, efd6 commented
This needs to have `elastic-package build` run.

2022-06-30 02:41 UTC, emnp commented
I already run that command before pushing. What can be the problem?

2022-06-30 03:55 UTC, efd6 commented
When I run that locally, I get this diff
```diff
diff --git a/packages/modsecurity/docs/README.md b/packages/modsecurity/docs/README.md
index 77024f1bb..38af18462 100644
--- a/packages/modsecurity/docs/README.md
+++ b/packages/modsecurity/docs/README.md
@@ -59,6 +59,7 @@ The `Audit Log` dataset collects Modsecurity Audit logs.
 | host.os.family | OS family (such as redhat, debian, freebsd, windows). | keyword |
 | host.os.kernel | Operating system kernel version as a raw string. | keyword |
 | host.os.name | Operating system name, without the version. | keyword |
+| host.os.name.text | Multi-field of `host.os.name`. | text |
 | host.os.platform | Operating system platform (such centos, ubuntu, windows). | keyword |
 | host.os.version | Operating system version as a raw string. | keyword |
 | host.type | Type of host. For Cloud providers this can be the machine type like `t2.medium`. If vm, this could be the container, for example, or other information meaningful in your environment. | keyword |
@@ -80,6 +81,7 @@ The `Audit Log` dataset collects Modsecurity Audit logs.
 | source.address | Some event source addresses are defined ambiguously. The event will sometimes list an IP, a domain or a unix socket.  You should always store the raw address in the `.address` field. Then it should be duplicated to `.ip` or `.domain`, depending on which one it is. | keyword |
 | source.as.number | Unique number allocated to the autonomous system. The autonomous system number (ASN) uniquely identifies each network on the Internet. | long |
 | source.as.organization.name | Organization name. | keyword |
+| source.as.organization.name.text | Multi-field of `source.as.organization.name`. | match_only_text |
 | source.geo.city_name | City name. | keyword |
 | source.geo.continent_name | Name of the continent. | keyword |
 | source.geo.country_iso_code | Country ISO code. | keyword |
@@ -94,16 +96,21 @@ The `Audit Log` dataset collects Modsecurity Audit logs.
 | url.extension | The field contains the file extension from the original request url, excluding the leading dot. The file extension is only set if it exists, as not every url has a file extension. The leading period must not be included. For example, the value must be "png", not ".png". Note that when the file name has multiple extensions (example.tar.gz), only the last one should be captured ("gz", not "tar.gz"). | keyword |
 | url.fragment | Portion of the url after the `#`, such as "top". The `#` is not part of the fragment. | keyword |
 | url.original | Unmodified original url as seen in the event source. Note that in network monitoring, the observed URL may be a full URL, whereas in access logs, the URL is often just represented as a path. This field is meant to represent the URL as it was observed, complete or not. | wildcard |
+| url.original.text | Multi-field of `url.original`. | match_only_text |
 | url.path | Path of the request, such as "/search". | wildcard |
 | url.port | Port of the request, such as 443. | long |
 | url.query | The query field describes the query string of the request, such as "q=elasticsearch". The `?` is excluded from the query string. If a URL contains no `?`, there is no query field. If there is a `?` but no query, the query field exists with an empty string. The `exists` query can be used to differentiate between the two cases. | keyword |
 | url.scheme | Scheme of the request, such as "https". Note: The `:` is not part of the scheme. | keyword |
 | user.name | Short name or login of the user. | keyword |
+| user.name.text | Multi-field of `user.name`. | match_only_text |
 | user_agent.device.name | Name of the device. | keyword |
 | user_agent.name | Name of the user agent. | keyword |
 | user_agent.original | Unparsed user_agent string. | keyword |
+| user_agent.original.text | Multi-field of `user_agent.original`. | match_only_text |
 | user_agent.os.full | Operating system name, including the version or code name. | keyword |
+| user_agent.os.full.text | Multi-field of `user_agent.os.full`. | match_only_text |
 | user_agent.os.name | Operating system name, without the version. | keyword |
+| user_agent.os.name.text | Multi-field of `user_agent.os.name`. | match_only_text |
 | user_agent.os.version | Operating system version as a raw string. | keyword |
 | user_agent.version | Version of the user agent. | keyword |
 
```

2022-07-01 11:34 UTC, efd6 commented
/test

2022-07-03 23:16 UTC, efd6 commented
@emnp Thank you for your patience.

@r00tu53r Would you please take a look since some of the changes are mine.

2022-07-03 23:18 UTC, efd6 approved these changes

2022-07-20 08:00 UTC, efd6 commented
@emnp Would you please fix the conflicts and update the manifest version.

2022-07-20 21:58 UTC, merged