[microsoft_sqlserver] Add transaction log DataStream
elastic/integrations pull request #3395
Opened 2022-05-20 05:49 UTC by muthu-mps

## What does this PR do?
Collects the transaction log metrics for Microsoft Sql server. Added support to collect metrics from Named Instance.

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

MSSQL server integration using generic sql, as per the [design doc](https://docs.google.com/document/d/1xxiO5Lv8hV1-zoNoW153dn5CyNky6ZIxqhkogV7smFA)

## How to test this PR locally
   Install the MSSQL 
- Go to Integration UI in Kibana
- Add the Microsoft SQL Server Integration
- Enroll the new elastic-agent
- Test named Instance by providing the named instance port in the Microsoft Sqlserver integration config.
- In the asset -> Transaction Log dashboard you should be able to see the default visualisation.

## Pending Tasks
- Update the document to add the new metrics information.
- System test to be added.

## Screenshots

2022-05-20 06:03 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3395/detail/PR-3395/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3395/detail/PR-3395/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3395/detail/PR-3395/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3395/detail/PR-3395/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_3395.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-05-20T05:39:30.151Z&rangeTo=2022-05-20T05:59:30.151Z&transactionName=Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=1feb36a745d82024728076aacb9fbe83&transactionId=67835b400e6918c0)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-05-20T05:49:30.151+0000


* Duration: 13 min 24 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3395/detail/PR-3395/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Test integration: microsoft_sqlserver`
<ul>
<li>Took 0 min 14 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3395/runs/1/steps/850/log/?start=0">here</a></li>
<li>Description: <code>                                eval "$(../../build/elastic-package stack shellinit)"                                ../../build/elastic-package test -v --report-format xUnit --report-output file --test-coverage                                </code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-05-20 06:03 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 3.731
Classes | 100.0% (`0/0`) | :green_heart: 3.731
Methods | 0.0% (`0/2`) | :-1: -88.029
Lines | 100.0% (`0/0`) | :green_heart: 10.515
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-05-20 09:16 UTC, elasticmachine commented
Pinging @elastic/integrations (Team:Integrations)

2022-05-23 05:27 UTC, ishleenk17 commented on packages/microsoft_sqlserver/data_stream/transaction_log/fields/fields.yml
> +    - name: metrics.database_name
database_name and database_id seem to have no relevance for the metrics. This should not be a metric.* field. 
Either we can have a package.yml like in performance data stream or if we want to keep them in fields.yml, we should remove it from metrics. group

2022-05-23 05:33 UTC, ishleenk17 commented on packages/microsoft_sqlserver/data_stream/transaction_log/fields/fields.yml
> +      type: date
All the metrics.* fields can be grouped together as 

 name: metrics
      type: group
      fields:
        - name: log_since_last_checkpoint_mb
          description: Log size in bytes since last checkpoint log sequence number (LSN).
          type: long
          .......................

2022-05-23 07:42 UTC, ishleenk17 reviewed
Add ecs.yml file

2022-05-24 04:39 UTC, muthu-mps commented on packages/microsoft_sqlserver/data_stream/transaction_log/fields/fields.yml
> +    - name: metrics.database_name
In transaction_log we are grouping the data based on database name. database_name and database_id would come under metrics group

2022-05-24 04:39 UTC, muthu-mps commented on packages/microsoft_sqlserver/data_stream/transaction_log/fields/fields.yml
> +      type: date
done

2022-05-30 09:57 UTC, lalit-satapathy commented on packages/microsoft_sqlserver/manifest.yml
> -  kibana.version: "^7.16.0 || ^8.0.0"
Need to find a way to update kibana.version to work for ^7.16.0 to have backward compatibility?

2022-05-30 10:01 UTC, lalit-satapathy commented
Making the PR "open" for wider reviews, with still 2 pending WIP.

2022-05-31 11:51 UTC, ruflin commented on packages/microsoft_sqlserver/manifest.yml
> -  kibana.version: "^7.16.0 || ^8.0.0"
I would skip for now, see other comment.

2022-05-31 11:57 UTC, ruflin commented on packages/microsoft_sqlserver/_dev/build/docs/README.md
> +The package collects `performance`, `transaction_log` metrics and `audit` events from the event log. Other log sources such as file are not supported.
Does this PR conflict with the other PR around performance? It seems bot have docs in for each ohter?

2022-05-31 11:57 UTC, ruflin commented on packages/microsoft_sqlserver/data_stream/transaction_log/agent/stream/stream.yml.hbs
> +    - query: "SELECT name As 'database_name', database_id FROM sys.databases WHERE database_id=1;"
Do we need all the separate queries or could we reduce it by getting all data by default and then filter it out? Not sure in this scenario as there seems to be some magic related to the table modeling but worth asking.

2022-05-31 11:57 UTC, ruflin commented on packages/microsoft_sqlserver/data_stream/transaction_log/fields/fields.yml
> +        - name: log_recovery_size_mb
@lalit-satapathy We need to decide if we match the MB naming conventions or not: https://www.elastic.co/guide/en/beats/devguide/current/event-conventions.html

2022-05-31 11:57 UTC, ruflin commented on packages/microsoft_sqlserver/data_stream/transaction_log/fields/fields.yml
> +          description: Log size in bytes since log recovery log sequence number (LSN).
Above is `mb` and here it states `bytes`? Same for many other fields. Where is it mb, where bytes etc?

2022-05-31 11:57 UTC, ruflin commented on packages/microsoft_sqlserver/data_stream/transaction_log/fields/fields.yml
> +    - name: query
Do we need to index the query? Should we set it to `index: false`?

2022-05-31 11:57 UTC, ruflin commented on packages/microsoft_sqlserver/data_stream/transaction_log/fields/fields.yml
> +- name: sql
What is the reason we have `sql` here instead of `mssql`?

2022-05-31 11:57 UTC, ruflin commented on packages/microsoft_sqlserver/data_stream/transaction_log/sample_event.json
> +        "query": "SELECT *, 'msdb' As 'database_name' FROM sys.dm_db_log_space_usage model",
Do we have 1 event per query?

I remember we had a discussion around it. I think it is fine to get started with it but ideally it is not the end result and we improve the input to support merging query data or similar.

2022-06-01 10:25 UTC, lalit-satapathy commented on packages/microsoft_sqlserver/manifest.yml
> -  kibana.version: "^7.16.0 || ^8.0.0"
ok, will stick with 8.3.0

2022-06-02 06:44 UTC, lalit-satapathy commented on packages/microsoft_sqlserver/data_stream/transaction_log/agent/stream/stream.yml.hbs
> +    - query: "SELECT name As 'database_name', database_id FROM sys.databases WHERE database_id=1;"
Currently for simplicity and easy-ness of naming, we have all separate queries.

2022-06-02 09:57 UTC, muthu-mps commented on packages/microsoft_sqlserver/data_stream/transaction_log/fields/fields.yml
> +        - name: log_recovery_size_mb
@ruflin Can we stick to  **_mb** for the field names which we get as a response from the query ?

2022-06-02 12:14 UTC, muthu-mps commented on packages/microsoft_sqlserver/data_stream/transaction_log/fields/fields.yml
> +          description: Log size in bytes since log recovery log sequence number (LSN).
done

2022-06-02 12:14 UTC, muthu-mps commented on packages/microsoft_sqlserver/data_stream/transaction_log/fields/fields.yml
> +    - name: query
done

2022-06-02 12:14 UTC, muthu-mps commented on packages/microsoft_sqlserver/data_stream/transaction_log/fields/fields.yml
> +- name: sql
done

2022-06-03 05:44 UTC, muthu-mps commented
/test

2022-06-03 08:52 UTC, muthu-mps commented on packages/microsoft_sqlserver/data_stream/transaction_log/fields/fields.yml
> +        - name: log_recovery_size_mb
done

2022-06-03 08:52 UTC, muthu-mps commented on packages/microsoft_sqlserver/manifest.yml
> -  kibana.version: "^7.16.0 || ^8.0.0"
done

2022-06-03 14:30 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2022-06-06 11:48 UTC, r00tu53r commented on packages/microsoft_sqlserver/manifest.yml
> -  kibana.version: "^7.16.0 || ^8.0.0"
With this change will the users who have been using this on 7.x lose the ability to receive fixes after this update ?

2022-06-06 13:19 UTC, muthu-mps commented on packages/microsoft_sqlserver/manifest.yml
> -  kibana.version: "^7.16.0 || ^8.0.0"
Maybe in the future if you want to release a fix for 7.x you can create a patch version branched from the last supported version of the integration?

2022-06-06 14:31 UTC, r00tu53r commented on packages/microsoft_sqlserver/manifest.yml
> -  kibana.version: "^7.16.0 || ^8.0.0"
There are no release branches available for integrations. The availability of features to users are governed by `kibana.version`. I am unable to find the conversation that discusses why the version was updated.

2022-06-07 05:35 UTC, lalit-satapathy commented on packages/microsoft_sqlserver/manifest.yml
> -  kibana.version: "^7.16.0 || ^8.0.0"
Hi @r00tu53r,

Thanks for your feedback. Also refer another PR same discussion: https://github.com/elastic/integrations/pull/3391#discussion_r884650481 

The new features we are releasing in the new metrics data_streams are only available on elastic-stack 8.3 onwards, so these can not run on older versions.

As I understand, the earlier developed audit data_stream dashboards  is supported on 7.x. The new metric data_streams added now are supported on 8,3 onwards. So, we need to find a way to resolve it.

As I dive into this further, its also not clear to me why the manifest kibana version is package specific, it appears to me that kibana version should be data stream specific, so that a specific data streams can be tied to a specific version.

@ruflin, Please suggest what are our options to take this forward.

2022-06-07 05:55 UTC, r00tu53r commented on packages/microsoft_sqlserver/manifest.yml
> -  kibana.version: "^7.16.0 || ^8.0.0"
From what I understand this PR uses the generic SQL input `sql/metrics` which is not available in 7.x and hence the change to `kibana.version`. 

@jamiehynds please note - Microsoft SQL Server package's `kibana.version` will be set to `8.3` after this change. Existing users using it for Audit on 7.x will not be able to receive updates/fixes on 7.x unless they upgrade.

2022-06-07 08:11 UTC, ruflin commented on packages/microsoft_sqlserver/manifest.yml
> -  kibana.version: "^7.16.0 || ^8.0.0"
@lalit-satapathy Your point around data stream specific version is interesting. So far we stayed away from this issue as we haven't faced this problem yet. Happy to discuss further if we need it.

The part that is not clear to me is that you mentioned the earlier developed audit data stream dashboards? Are these already released? If not or not as GA, I would just make it all 8.3 for now and then follow up with wider compatibility.

2022-06-07 09:40 UTC, lalit-satapathy commented on packages/microsoft_sqlserver/manifest.yml
> -  kibana.version: "^7.16.0 || ^8.0.0"
@ruflin, Yes we can take the data-steam specific versioning discussion offline and file an issue if needed.

The security integrations were made GA [recently](https://github.com/elastic/integrations/pull/3428).

@r00tu53r , hoping we can migrate to 8.3 for this one.

2022-06-08 08:35 UTC, lalit-satapathy commented
@ManojS-shetty @muthu-mps,
Do we have any changes pending or all the feedbacks are resolved now? 

@ruflin @jsoriano @r00tu53r, tar-getting the merge of this PR, need your approval for the same.

2022-06-08 08:40 UTC, muthu-mps commented
> @ManojS-shetty @muthu-mps, Do we have any changes pending or all the feedbacks are resolved now?
> 
> @ruflin @jsoriano @r00tu53r, tar-getting the merge of this PR, need your approval for the same.



> @ManojS-shetty @muthu-mps, Do we have any changes pending or all the feedbacks are resolved now?
> 
> @ruflin @jsoriano @r00tu53r, tar-getting the merge of this PR, need your approval for the same.

All the feedbacks are resolved.

2022-06-08 08:43 UTC, muthu-mps commented
The changes are done!

2022-06-08 10:18 UTC, jsoriano requested changes
It looks good in general, but I am concerned about some changes in versions.

2022-06-08 10:18 UTC, jsoriano commented on packages/microsoft_sqlserver/data_stream/transaction_log/fields/fields.yml
> +        - name: database_id
This field looks like a dimension :slightly_smiling_face:

2022-06-08 10:18 UTC, jsoriano commented on packages/microsoft_sqlserver/data_stream/transaction_log/fields/fields.yml
> +    - name: driver
This field is useful when using the `sql` module/input, but it is redundant here. I think this field could be removed in the pipeline.

2022-06-08 10:18 UTC, jsoriano commented on packages/microsoft_sqlserver/data_stream/transaction_log/fields/fields.yml
> +    - name: query
Actually, do we need the query at all in the final document? This is an implementation detail of the integration, I think that it could be removed.

But, if we are storing metrics coming from different queries in different documents we may need some dimension to distinguish between queries. So we may need to index the query to use it as dimension, or find some other field that could cover this.

We can also wait to have some way to join events (https://github.com/elastic/beats/issues/31806#issuecomment-1148252201), then `database_id` will be probably enough as dimension.

2022-06-08 10:18 UTC, jsoriano commented on packages/microsoft_sqlserver/data_stream/transaction_log/fields/fields.yml
> +          description: Total transaction log size in bytes.
Thanks for adding the metrics type and units to all fields :+1:

2022-06-08 10:18 UTC, jsoriano commented on packages/microsoft_sqlserver/manifest.yml
> +version: 1.0.1
As you are changing the kibana version constraint, please increase the version of the package to `1.1.0`, so fixes can be still be made for older versions as 1.0.X.
```suggestion
version: 1.1.0
```

2022-06-08 10:18 UTC, jsoriano commented on packages/microsoft_sqlserver/manifest.yml
> +  - name: microsoft_sqlserver
Changes in policy template names can be breaking changes, see https://github.com/elastic/integrations/pull/3391#discussion_r889003040.

Can this change be avoided?

2022-06-08 10:26 UTC, lalit-satapathy commented on packages/microsoft_sqlserver/manifest.yml
> +  - name: microsoft_sqlserver
It was earlier audit_logs only and now have both metrics and logs.  Otherwise will have a meaning which is misleading to the users.

2022-06-08 10:27 UTC, lalit-satapathy commented on packages/microsoft_sqlserver/data_stream/transaction_log/fields/fields.yml
> +    - name: driver
Please drop this field.

2022-06-08 10:34 UTC, lalit-satapathy commented on packages/microsoft_sqlserver/manifest.yml
> +version: 1.0.1
sounds good.

2022-06-08 11:22 UTC, jsoriano commented on packages/microsoft_sqlserver/manifest.yml
> +  - name: microsoft_sqlserver
I think I would prefer keeping the legacy name than producing breaking changes. I think this name is internal and not displayed to users, so it could be fine. We could add a comment here mentioning the reason.

If you keep the new name, could you please test if upgrading from current version to this new one?

2022-06-08 11:36 UTC, muthu-mps commented on packages/microsoft_sqlserver/manifest.yml
> +  - name: microsoft_sqlserver
When we update to the newer version. This is the update we are getting in policy template for audit log.
```
    name: microsoft_sqlserver-1
    revision: 1
    type: winlog
```
and for Metrics

```
    name: microsoft_sqlserver-1
    revision: 1
    type: sql/metrics
```

2022-06-08 11:40 UTC, epixa commented on .github/CODEOWNERS
> +/packages/microsoft_sqlserver @elastic/obs-service-integrations
I'm not sure if this was made in error, but I don't think we should be switching over the entire package ownership. We could add `obs-service-integrations` as an additional owner to the whole package, or we could break down the data_streams and dashboards in terms of ownership, which is more complicated to maintain but would be a bit more accurate.

The audit log data_stream is pretty important for the security case, which is why this package was created initially.

2022-06-08 11:54 UTC, r00tu53r commented on packages/microsoft_sqlserver/manifest.yml
> -  kibana.version: "^7.16.0 || ^8.0.0"
Thanks @lalit-satapathy. I've pinged Jamie above for his comments/thoughts.

2022-06-08 12:15 UTC, ishleenk17 commented on packages/microsoft_sqlserver/data_stream/transaction_log/fields/base-fields.yml
> +  description: Event timestamp.
@jsoriano  If this has to be done, shouldn't these be moved to ecs.yml ?
Anything that we gain by keeping them under base-fields.yml ?

2022-06-08 13:41 UTC, muthu-mps commented on packages/microsoft_sqlserver/data_stream/transaction_log/fields/fields.yml
> +    - name: query
done.

2022-06-08 13:41 UTC, muthu-mps commented on packages/microsoft_sqlserver/_dev/build/build.yml
> +    reference: git@8.2
done.

2022-06-08 13:42 UTC, muthu-mps commented on packages/microsoft_sqlserver/data_stream/transaction_log/fields/fields.yml
> +    - name: driver
done.

2022-06-08 14:01 UTC, muthu-mps commented on .github/CODEOWNERS
> +/packages/microsoft_sqlserver @elastic/obs-service-integrations
Added `obs-service-integrations` as additional owner for whole package.

2022-06-08 14:59 UTC, muthu-mps commented on packages/microsoft_sqlserver/manifest.yml
> +  - name: microsoft_sqlserver
done. Updated the name to audit_logs

2022-06-08 15:53 UTC, jsoriano reviewed
Looks good, thanks for addressing all comments.

The main concern I would have now is about `mssql.query`. It is not clear to me if we are keeping it at the end or not.

Also I think that this data stream would benefit of https://github.com/elastic/beats/issues/31806, to store all the metrics in the same document. And if we end up storing the results of the queries in the same document, what would we store in `mssql.query`? Would we remove it? This would be a breaking change.

The more I think about storing the query, the more I think that we shouldn't store it. And it is easier in any case to add it later if I am wrong, than to remove it if needed later.

2022-06-08 15:53 UTC, jsoriano commented on packages/microsoft_sqlserver/data_stream/transaction_log/elasticsearch/ingest_pipeline/default.yml
> +      ignore_missing: true
Nit. There is one more indentation level here than in other processors.

2022-06-08 15:53 UTC, jsoriano commented on packages/microsoft_sqlserver/data_stream/transaction_log/elasticsearch/ingest_pipeline/default.yml
> +    value: "{{ _ingest.on_failure_message }}"
It would be good to add pipeline tests, but I am ok with adding them in a follow up.

2022-06-08 15:53 UTC, jsoriano commented on packages/microsoft_sqlserver/data_stream/transaction_log/sample_event.json
> +        }
Umm, are we keeping `mssql.query` field at the end? I don't see we are removing it in the pipeline, but it is not here :thinking:

2022-06-09 06:19 UTC, muthu-mps commented on packages/microsoft_sqlserver/data_stream/transaction_log/sample_event.json
> +        }
Removed the query field.

2022-06-09 06:19 UTC, muthu-mps commented on packages/microsoft_sqlserver/data_stream/transaction_log/elasticsearch/ingest_pipeline/default.yml
> +      ignore_missing: true
done

2022-06-09 09:13 UTC, jsoriano approved these changes
LGTM, please remember to add pipeline tests at some moment

2022-06-14 06:13 UTC, efd6 commented on packages/microsoft_sqlserver/_dev/build/docs/README.md
> +The package collects `performance`, `transaction_log` metrics and `audit` events from the event log. Other log sources such as file are not supported.
```suggestion
The package collects `performance` and `transaction_log` metrics, and `audit` events from the event log. Other log sources such as file are not supported.
```

2022-06-14 06:13 UTC, efd6 commented on packages/microsoft_sqlserver/_dev/build/docs/README.md
> +The `performance` metrics gathers the list of performance objects available on that server. Each server will have a different list of performance objects depending on the installed software.
```suggestion
`performance` metrics gathers the list of performance objects available on that server. Each server will have a different list of performance objects depending on the installed software.
```

2022-06-14 06:13 UTC, efd6 commented on packages/microsoft_sqlserver/_dev/build/docs/README.md
> +The Microsoft SQL Server has a feature that allows to run multiple databases on the same host (or Clustered hosts) with separate settings. Edit the instance port and provide the named instance port t
```suggestion
Microsoft SQL Server has a feature that allows running multiple databases on the same host (or clustered hosts) with separate settings. Edit the instance port and provide the named instance port to connect to the named instance and collect metrics.
```

2022-06-14 06:13 UTC, efd6 commented on packages/microsoft_sqlserver/_dev/build/docs/README.md
> +The Microsoft SQL Server `performance` dataset provides events from the performance counter table. All `performance` metrics will be available in `sqlserver.metrics` field group.
s/events/metrics/?

2022-06-14 06:13 UTC, efd6 commented on packages/microsoft_sqlserver/_dev/build/docs/README.md
> +The Microsoft SQL Server `transaction_log` dataset provides events from the log space usage and log stats tables of the system databases. All `transaction_log` metrics will be available in `sqlserver
s/events/metrics/?

2022-06-14 06:47 UTC, muthu-mps commented on packages/microsoft_sqlserver/_dev/build/docs/README.md
> +The Microsoft SQL Server `performance` dataset provides events from the performance counter table. All `performance` metrics will be available in `sqlserver.metrics` field group.
Thanks for the update! It is metrics

2022-06-14 06:48 UTC, muthu-mps commented on packages/microsoft_sqlserver/_dev/build/docs/README.md
> +The Microsoft SQL Server `transaction_log` dataset provides events from the log space usage and log stats tables of the system databases. All `transaction_log` metrics will be available in `sqlserver
done.

2022-06-14 06:51 UTC, muthu-mps commented on packages/microsoft_sqlserver/_dev/build/docs/README.md
> +The package collects `performance`, `transaction_log` metrics and `audit` events from the event log. Other log sources such as file are not supported.
done.

2022-06-14 06:51 UTC, muthu-mps commented on packages/microsoft_sqlserver/_dev/build/docs/README.md
> +The `performance` metrics gathers the list of performance objects available on that server. Each server will have a different list of performance objects depending on the installed software.
done.

2022-06-14 06:51 UTC, muthu-mps commented on packages/microsoft_sqlserver/_dev/build/docs/README.md
> +The Microsoft SQL Server has a feature that allows to run multiple databases on the same host (or Clustered hosts) with separate settings. Edit the instance port and provide the named instance port t
done.

2022-06-14 07:11 UTC, efd6 approved these changes

2022-06-14 12:09 UTC, merged