Remove invalid ips used in tests
elastic/integrations pull request #3410
Opened 2022-05-23 11:57 UTC by jsoriano

## What does this PR do?

elastic-package only allows the use of IPs that have geoip data in the included geoip database (see https://github.com/elastic/elastic-package/pull/605).

Fields validation is only done with the first element when the field contains an array. In https://github.com/elastic/elastic-package/pull/771 we are introducing the check for all elements in the array.

There are IPs in arrays that are not allowed by this check. Replace them.

## Related issues

- Related to https://github.com/elastic/elastic-package/pull/605
- Required by https://github.com/elastic/elastic-package/pull/771
- Fixes https://github.com/elastic/integrations/issues/3408

2022-05-23 12:55 UTC, jsoriano commented
Will wait for https://github.com/elastic/elastic-package/pull/826, to have more available ipv6 addresses, and to solve issues with addresses with leading zeroes.

2022-05-23 14:11 UTC, elasticmachine commented
## :broken_heart: Tests Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3410/detail/PR-3410/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3410/detail/PR-3410/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3410/detail/PR-3410/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3410/detail/PR-3410/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_3410.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-05-23T11:47:23.178Z&rangeTo=2022-05-23T12:07:23.178Z&transactionName=Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=1289a6e8fc3f1ec543ac13c81d05d555&transactionId=2b28308c158d49ce)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-05-23T11:57:23.178+0000


* Duration: 134 min 51 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 9  |
| Passed       | 4387  |
| Skipped      | 7 |
| Total        | 4403   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->

  ### Test errors [![9](https://img.shields.io/badge/9%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3410/detail/PR-3410/1//tests)
<details><summary>Expand to view the tests failures</summary><p>
    
    
##### `Check integrations / nagios_xi / nagios_xi: check / system test: default – nagios_xi.service`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 null 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 one or more errors found in documents stored in logs-nagios_xi.service-ep data stream: [0] parsing field value failed: field "event.kind"'s value "metrics" is not one of the allowed values (alert, enrichment, event, metric, state, pipeline_error, signal) 
 ```
</p></details>
</ul>
    
##### `Check integrations / microsoft_dhcp / microsoft_dhcp: check / pipeline test: test-logv6.log – microsoft_dhcp.log`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 null 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 test case failed: one or more problems with fields found in documents: [0] parsing field value failed: field "event.type"'s value "stop" is not one of the allowed values (access, admin, allowed, change, connection, creation, deletion, denied, end, error, group, indicator, info, installation, protocol, start, user) 
 ```
</p></details>
</ul>
    
##### `Check integrations / carbon_black_cloud / carbon_black_cloud: check / pipeline test: test-audit.log – carbon_black_cloud.audit`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 null 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 test case failed: one or more problems with fields found in documents: [0] parsing field value failed: field "event.outcome"'s value "failed" is not one of the allowed values (failure, success, unknown) 
 ```
</p></details>
</ul>
    
##### `Check integrations / windows / windows: check / pipeline test: test-sysmon-operational-events.json – windows.forwarded`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 null 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 test case failed: one or more problems with fields found in documents: [0] parsing field value failed: the IP "2a02:cf40:0add:4002:91f2:a9b2:e09a:6fc6" is not one of the allowed test IPs (see: https://github.com/elastic/elastic-package/blob/main/internal/fields/_static/allowed_geo_ips.txt) 
 ```
</p></details>
</ul>
    
##### `Check integrations / windows / windows: check / pipeline test: test-events.json – windows.sysmon_operational`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 null 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 test case failed: one or more problems with fields found in documents: [0] parsing field value failed: the IP "2a02:cf40:0add:4002:91f2:a9b2:e09a:6fc6" is not one of the allowed test IPs (see: https://github.com/elastic/elastic-package/blob/main/internal/fields/_static/allowed_geo_ips.txt) 
 ```
</p></details>
</ul>
    
##### `Check integrations / system / system: check / pipeline test: test-auth-ubuntu1204.log – system.auth`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 null 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 test case failed: one or more problems with fields found in documents: [0] parsing field value failed: field "event.outcome"'s value "authentication success" is not one of the allowed values (failure, success, unknown)
[1] parsing field value failed: field "event.type"'s value "success" is not one of the allowed values (access, admin, allowed, change, connection, creation, deletion, denied, end, error, group, indicator, info, installation, protocol, start, user) 
 ```
</p></details>
</ul>
    
##### `Check integrations / system / system: check / pipeline test: test-auth.log – system.auth`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 null 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 test case failed: one or more problems with fields found in documents: [0] parsing field value failed: field "event.outcome"'s value "authentication failure" is not one of the allowed values (failure, success, unknown)
[1] parsing field value failed: field "event.outcome"'s value "authentication success" is not one of the allowed values (failure, success, unknown)
[2] parsing field value failed: field "event.type"'s value "success" is not one of the allowed values (access, admin, allowed, change, connection, creation, deletion, denied, end, error, group, indicator, info, installation, protocol, start, user) 
 ```
</p></details>
</ul>
    
##### `Check integrations / system / system: check / pipeline test: test-secure-rhel7.log – system.auth`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 null 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 test case failed: one or more problems with fields found in documents: [0] parsing field value failed: field "event.outcome"'s value "authentication failure" is not one of the allowed values (failure, success, unknown) 
 ```
</p></details>
</ul>
    
##### `Check integrations / aws / aws: check / pipeline test: test-route53.log – aws.route53_resolver_logs`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 null 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 test case failed: one or more problems with fields found in documents: [0] parsing field value failed: the IP "154.21.22.15" is not one of the allowed test IPs (see: https://github.com/elastic/elastic-package/blob/main/internal/fields/_static/allowed_geo_ips.txt)
[1] parsing field value failed: the IP "162.159.200.1" is not one of the allowed test IPs (see: https://github.com/elastic/elastic-package/blob/ [...]

2022-05-23 14:11 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`207/207`) | :green_heart: 
Files | 95.918% (`329/343`) | :-1: -0.186
Classes | 95.918% (`329/343`) | :-1: -0.186
Methods | 89.236% (`3374/3781`) | :+1: 1.399
Lines | 88.471% (`59747/67533`) | :-1: -0.688
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-05-23 16:56 UTC, jsoriano commented
Pending validation of IPv6 address will be fixed by https://github.com/elastic/elastic-package/pull/826, opening this for review.

2022-05-23 23:16 UTC, efd6 reviewed
Where there are a number of IPv6 addresses in IP arrays and they are distinct and not in the first position (so not tagged as not-allowed under the current testing) I'd suggest to keep the distinctness so that they can be used to test fixes for `allow_duplicates: false`. This can be done with no loss of information by using RFC 4193 private IPs for those replacements.

2022-05-23 23:16 UTC, efd6 commented on packages/aws/data_stream/route53_resolver_logs/_dev/test/pipeline/test-route53.log-expected.json
> +                    "2a02:cf40:add:4002:91f2:a9b2:e09a:6fc6",
We should have more than one IPv6 so that this kind of thing doesn't happen. Really the processor should probably append `allow_duplicates: false`.

2022-05-23 23:16 UTC, efd6 commented on packages/aws/data_stream/route53_resolver_logs/_dev/test/pipeline/test-route53.log-expected.json
> +                    "67.43.156.12",
Make the second one distinct?

2022-05-23 23:16 UTC, efd6 commented on packages/zeek/data_stream/dns/_dev/test/pipeline/test-dns.log
> +{"ts":1617105592.9742,"uid":"CG1jsmeHcBCGnWXmk","id.orig_h":"10.156.0.2","id.orig_p":44310,"id.resp_h":"169.254.169.254","id.resp_p":53,"proto":"udp","trans_id":58458,"query":"login.microsoftonline.c
"1.128.3.435" is not a valid IP.

2022-05-24 07:03 UTC, jsoriano commented
@efd6 thanks for the review! I will wait then for https://github.com/elastic/elastic-package/pull/826 so we can have different ipv6 addresses, and address your comments.

2022-05-30 11:27 UTC, jsoriano commented
Open for review. @efd6 it'd be great if you could give it another look. Thanks!

2022-05-30 23:30 UTC, efd6 requested changes

2022-05-30 23:30 UTC, efd6 commented on packages/zeek/data_stream/dns/_dev/test/pipeline/test-dns.log
> +{"ts":1617105592.9742,"uid":"CG1jsmeHcBCGnWXmk","id.orig_h":"10.156.0.2","id.orig_p":44310,"id.resp_h":"169.254.169.254","id.resp_p":53,"proto":"udp","trans_id":58458,"query":"login.microsoftonline.c
This is not correct yet.

2022-05-30 23:31 UTC, efd6 approved these changes

2022-05-31 07:15 UTC, merged