system_2617_dashboard: tile_map to map
elastic/integrations pull request #3461
Opened 2022-06-02 10:06 UTC by ishleenk17

- Enhancement

## What does this PR do?

This PR replaces the tile_map object with map in system's SSH Log dashboard

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally

Load the newly created dashboard and we should see map as the object 

- Closes https://github.com/elastic/integrations/issues/2617

## Screenshots
Below screenshot shows map object updated in System SSH Log Dashboard

<img width="1283" alt="Screenshot 2022-06-02 at 3 12 03 PM" src="https://user-images.githubusercontent.com/102962586/171605845-2135ee11-8937-486d-b97d-5ac4a7a8fc4f.png">

2022-06-02 10:22 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3461/detail/PR-3461/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3461/detail/PR-3461/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3461/detail/PR-3461/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3461/detail/PR-3461/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_3461.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-06-02T09:57:11.816Z&rangeTo=2022-06-02T10:17:11.816Z&transactionName=Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=652b5debe6e031d33ea913d5ce15ba54&transactionId=77f2b7b0315afee5)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-06-02T10:07:11.816+0000


* Duration: 15 min 42 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 272  |
| Skipped      | 0 |
| Total        | 272   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-06-02 10:22 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`3/3`) | :green_heart: 
Files | 100.0% (`4/4`) | :green_heart: 
Classes | 100.0% (`4/4`) | :green_heart: 
Methods | 59.74% (`46/77`) | :grey_exclamation: 
Lines | 98.782% (`2676/2709`) | :grey_exclamation: 
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-06-03 05:19 UTC, muthu-mps approved these changes
LGTM!

2022-06-03 10:25 UTC, flash1293 requested changes

2022-06-03 10:25 UTC, flash1293 commented on packages/system/kibana/dashboard/system-5517a150-f9ce-11e6-8115-a7c18106d86a.json
> -            "id": "system-3cec3eb0-f9d3-11e6-8a3e-2b904044ea1d",
The old `system-3cec3eb0-f9d3-11e6-8a3e-2b904044ea1d` visualization is not part of the dashboard anymore, but it's not deleted:
<img width="787" alt="Screenshot 2022-06-03 at 12 24 20" src="https://user-images.githubusercontent.com/1508364/171836714-fed84c59-f2fc-4a83-aa08-b9140141bf66.png">

2022-06-03 10:25 UTC, flash1293 commented on packages/system/kibana/map/system-4217db10-e230-11ec-baf0-970634a1784d.json
> +{
The map is saved as a separate visualization in the library. As it's not used on another dashboard it makes sense to remove it from the library and make it part of the dashboard itself - see "Do not use “library visualizations”" in the best practices document: https://docs.google.com/document/d/1uyyFGx6xA5Kvl8c-ZdvXdvBGrHTylxU9F69TGqfzdmw/edit#

2022-06-13 12:08 UTC, ishleenk17 commented on packages/system/kibana/map/system-4217db10-e230-11ec-baf0-970634a1784d.json
> +{
> The map is saved as a separate visualization in the library. As it's not used on another dashboard it makes sense to remove it from the library and make it part of the dashboard itself - see "Do not use “library visualizations”" in the best practices document: https://docs.google.com/document/d/1uyyFGx6xA5Kvl8c-ZdvXdvBGrHTylxU9F69TGqfzdmw/edit#

Both the changes have been taken care of. Please re-review   the changes @flash1293

2022-06-13 12:57 UTC, ishleenk17 commented
/test

2022-06-14 13:23 UTC, closed without merging