Standardised names for security integrations
elastic/integrations pull request #3478
Opened 2022-06-07 14:31 UTC by kcreddy

## What does this PR do?
Updates the package names with standard wording

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues
- Closes #3400

2022-06-07 15:09 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`3/3`) | :green_heart: 
Files | 100.0% (`10/10`) | :green_heart: 3.432
Classes | 100.0% (`10/10`) | :green_heart: 3.432
Methods | 100.0% (`76/76`) | :green_heart: 11.111
Lines | 99.442% (`2138/2150`) | :+1: 9.684
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-06-08 06:14 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2022-06-08 07:20 UTC, marc-gr reviewed
Would be nice to also take a look at the descriptions and adapt their wording in the same way.

2022-06-08 07:20 UTC, marc-gr commented on packages/azure/manifest.yml
>  title: Azure Logs
I think we also need to change the integration title here.

2022-06-08 07:54 UTC, zmoog commented on packages/azure/manifest.yml
>  title: Azure Logs
Azure has multiple integrations:

- application insights
- billing
- logs (*)
- metrics

This one you commented on (*) focuses on collecting logs, so probably it's not a bad name to position it in the current Azure offering.

WDYT @ravikesarwani?

2022-06-13 16:43 UTC, adriansr requested changes

2022-06-13 16:43 UTC, adriansr commented on packages/auth0/manifest.yml
> +version: 1.1.0
I think it makes more sense to increase the patch level for small changes that don't introduce new features to the package.

There's no clear direction from the semver spec about whether to mark this kind of changes (docs, copy, etc.) as minor or patch (see https://github.com/semver/semver/pull/588), but the overall sentiment in the discussions I've read is to just increase the patch version.

2022-06-14 06:08 UTC, adriansr commented
/test

2022-06-14 06:33 UTC, kcreddy commented on packages/auth0/manifest.yml
> +version: 1.1.0
That makes sense @adriansr. I modified the version flag to reflect as patch

2022-06-21 13:05 UTC, serenachou commented on packages/httpjson/manifest.yml
> +title: Custom REST API Input
We removed our Custom API tile in 8.3 because we are deprecating our custom source api for Workplace Search in favor of a new architecture for custom development. You can use Custom API, but make sure it's clearly associated with Security use cases @jamiehynds

2022-07-05 19:48 UTC, serenachou commented on packages/httpjson/manifest.yml
> +title: Custom REST API Input
It's already removed@ we will be reintroducing a new one for the new custom option in 8.4, working on the naming of that right now. @jamiehynds

2022-07-11 10:38 UTC, kcreddy commented on packages/azure/manifest.yml
>  title: Azure Logs
Updated descriptions of the packages as well

2022-07-11 11:01 UTC, ishleenk17 approved these changes

2022-07-11 22:30 UTC, zmoog approved these changes
The Azure logs part LGTM

2022-07-12 19:04 UTC, adriansr approved these changes

2022-07-19 08:03 UTC, merged