mapping for rule id
elastic/integrations pull request #3503
Opened 2022-06-13 16:23 UTC by CohenIdo

2022-06-13 16:39 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3503/detail/PR-3503/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3503/detail/PR-3503/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3503/detail/PR-3503/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3503/detail/PR-3503/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_3503.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-06-13T16:14:02.043Z&rangeTo=2022-06-13T16:34:02.043Z&transactionName=Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=64cf10051c216d232538dc2af45c5a52&transactionId=54c87fa00b9c40d3)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-06-13T16:24:02.043+0000


* Duration: 15 min 0 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 1  |
| Skipped      | 0 |
| Total        | 1   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-06-13 16:39 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 3.432
Classes | 100.0% (`0/0`) | :green_heart: 3.432
Methods | 33.333% (`1/3`) | :-1: -55.556
Lines | 100.0% (`0/0`) | :green_heart: 10.108
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-06-14 09:43 UTC, eyalkraft commented
reverting the constraint as well?

2022-06-14 09:49 UTC, CohenIdo commented
> reverting the constraint as well?

I did the revert in different PR:
- https://github.com/elastic/integrations/pull/3506

2022-06-14 12:25 UTC, kfirpeled approved these changes

2022-06-14 12:29 UTC, kfirpeled requested changes
checked it up with @eyalkraft and we should create a new version, unlike what I've asked you to do - to edit the current one.
so please create version 0.0.14 and lower the condition for kibana to 8.3

2022-06-14 13:14 UTC, kfirpeled approved these changes

2022-06-14 13:19 UTC, merged