update readme for Akamai
elastic/integrations pull request #3532
Opened 2022-06-20 09:15 UTC by ellis-elastic

improved the clarity of the English

- Enhancement

## What does this PR do?

improved the clarity of the English

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2022-06-20 09:15 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2022-06-20 09:34 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`1/1`) | :green_heart: 
Files | 100.0% (`1/1`) | :green_heart: 3.497
Classes | 100.0% (`1/1`) | :green_heart: 3.497
Methods | 100.0% (`19/19`) | :green_heart: 10.527
Lines | 92.778% (`334/360`) | :+1: 1.807
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-06-20 09:48 UTC, r00tu53r approved these changes

2022-06-20 18:10 UTC, bmorelli25 requested changes

2022-06-20 18:10 UTC, bmorelli25 commented on packages/akamai/_dev/build/docs/README.md
> +See [Akamai API get started](https://techdocs.akamai.com/siem-integration/reference/api-get-started) to setup your Akamai account and get  your credentials.
```suggestion
See [Akamai API get started](https://techdocs.akamai.com/siem-integration/reference/api-get-started) to set up your Akamai account and get your credentials.
```

2022-06-21 19:18 UTC, bmorelli25 approved these changes

2022-06-21 19:56 UTC, merged