Add foundation, errorlog data stream, visualizations
elastic/integrations pull request #3590
Opened 2022-06-27 14:11 UTC by harnish-crest

- Enhancement

## What does this PR do?

- Generated the skeleton of IBM MQ integration package.
- Added 1 data stream (Queue Manager Error Logs).
- Added data collection logic for the data streams.
- Added the ingest pipeline for the data streams.
- Mapped fields according to the ECS schema and added Fields metadata in the appropriate yaml files.
- Added dashboards and visualizations.
- Added system test cases for the data stream.

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's changelog.yml file.
- [X] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally

- Clone integrations repo.
- Install elastic-package locally.
- Start elastic stack using elastic-package.
- Move to integrations/packages/ibmmq directory.
- Run the following command to run tests.
elastic-package test

## Related issues

- Relates #620

## Screenshots

2022-06-27 14:15 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3590/detail/PR-3590/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3590/detail/PR-3590/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3590/detail/PR-3590/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3590/detail/PR-3590/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-06-27T14:02:13.354Z&rangeTo=2022-06-27T14:22:13.354Z&transactionName=Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=b6d59ff3f78401b646d828c0077a5bfe&transactionId=44f192d1e45c249f)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-06-27T14:12:13.354+0000


* Duration: 3 min 57 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![3](https://img.shields.io/badge/3%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3590/detail/PR-3590/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Load a resource file from a shared library`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3590/runs/1/steps/91/log/?start=0">here</a></li>
<li>Description: <code>approval-list/elastic/integrations.yml</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3590/runs/1/steps/117/log/?start=0">here</a></li>

</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3590/runs/1/steps/88/log/?start=0">here</a></li>
<li>Description: <code>githubApiCall: The REST API call https://api.github.com/orgs/elastic/members/harnish-crest return the message : java.lang.Exception: httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/harnish-crest : httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/harnish-crest : Code: 404Error: {"message":"User does not exist or is not a member of the organization","documentation_url":"https://docs.github.com/rest/reference/orgs#check-organization-membership-for-a-user"}</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-06-28 12:37 UTC, yug-elastic commented
/test

2022-06-29 06:08 UTC, kush-elastic requested changes
Please change docker image tag from `latest` to specific version and lets use `variants.yml` for multiple version test.

2022-06-29 08:40 UTC, yug-elastic commented
/test

2022-06-29 08:58 UTC, harnish-crest commented on packages/ibmmq/_dev/deploy/docker/docker-compose.yml
> +    image: ibmcom/mq:latest
Added vriants.yml with latest version 9.2.4.0

2022-06-29 09:22 UTC, kush-elastic approved these changes
Added a comment.
else LGTM!

2022-06-29 09:22 UTC, kush-elastic commented on packages/ibmmq/_dev/deploy/variants.yml
> +default: 9.2.4.0-r1-amd64
nit: default will contain variants key name, which is in your case is `v9.2.4.0-r1-amd64`.
```suggestion
  v9.2.4.0-r1-amd64:
    SERVICE_VERSION: 9.2.4.0-r1-amd64
default: v9.2.4.0-r1-amd64
```

2022-07-04 07:42 UTC, kush-elastic approved these changes
LGTM!

2022-07-07 12:55 UTC, harnish-crest commented on packages/ibmmq/manifest.yml
> +  - web
Makes sense, thanks!

2022-07-07 13:15 UTC, harnish-crest commented on packages/ibmmq/_dev/build/docs/README.md
> +
Not quite sure what you are trying to refer to here. Could you please elaborate? This is the standard format of README that most of the integrations follow.

2022-07-08 05:18 UTC, harnish-crest commented on packages/ibmmq/_dev/build/docs/README.md
> +The `errorlog` data stream collects Error logs of Queue Manager which include the description, action, explanation and code of the error.
Not quite sure what you are trying to refer to here. Could you please elaborate? This is the standard format of README that most of the integrations follow.

2022-07-08 05:36 UTC, harnish-crest commented on packages/ibmmq/_dev/build/docs/README.md
> +The `errorlog` data stream collects Error logs of Queue Manager which include the description, action, explanation and code of the error.
I have referred to this link. Let me know does this link look good to you?

[https://www.site24x7.com/help/log-management/ibm-mq-error-logs.html](https://www.site24x7.com/help/log-management/ibm-mq-error-logs.html)

2022-07-08 05:40 UTC, ritalwar commented on packages/ibmmq/_dev/build/docs/README.md
> +The `errorlog` data stream collects Error logs of Queue Manager which include the description, action, explanation and code of the error.
Looks good! Please add it in the docs as well.

2022-07-08 05:49 UTC, harnish-crest commented on packages/ibmmq/_dev/build/docs/README.md
> +The `errorlog` data stream collects Error logs of Queue Manager which include the description, action, explanation and code of the error.
Added it, thanks.

2022-07-08 10:14 UTC, ritalwar commented on packages/ibmmq/_dev/build/docs/README.md
> +- User must know the path of IBM MQ Queue Manager Error logs. (default paths: `/var/mqm/errors/*.LOG` and `/var/mqm/qmgrs/*/errors/*.LOG`)
'user must know the path'. This line can be modified and it should be kind of 'user should specify the path'.

2022-07-08 10:22 UTC, ritalwar commented on packages/ibmmq/data_stream/errorlog/manifest.yml
> +        description: >
can we omit > and give description directly, like in other fields to maintain consistent format?

2022-07-08 10:23 UTC, harnish-crest commented on packages/ibmmq/_dev/build/docs/README.md
> +- User must know the path of IBM MQ Queue Manager Error logs. (default paths: `/var/mqm/errors/*.LOG` and `/var/mqm/qmgrs/*/errors/*.LOG`)
Makes sense, Thanks.

2022-07-08 10:35 UTC, harnish-crest commented on packages/ibmmq/data_stream/errorlog/manifest.yml
> +        description: >
Updated, thanks

2022-07-14 05:09 UTC, ritalwar commented on packages/ibmmq/_dev/build/docs/README.md
> +- User should specify the path IBM MQ Queue Manager Error logs. (default paths: `/var/mqm/errors/*.LOG` and `/var/mqm/qmgrs/*/errors/*.LOG`)
nit: path of IBM MQ.
Please check the docs and descriptions again and correct them.

2022-07-18 06:44 UTC, ritalwar approved these changes
LGTM!

2022-07-18 09:02 UTC, merged