[Platform Observability] Create initial PO package for ingesting kibana ECS formatted logs
elastic/integrations pull request #3622
Opened 2022-06-29 12:46 UTC by crespocarlos

## What does this PR do?

This PR is the initial work for creating the new Platform Observability package. We will start with ingesting Kibana logs but its capabilities will be extended over time. This package is heavily based on the solution provided here https://github.com/elastic/integrations/pull/2972

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [x] Define the package name 
- [x] Align current Kibana package ingest pipelines with this one  (This is a duplication of the existing Kibana package)
- [x] Decide whether we will go with Filebeat processors to parse the json object or not

## How to test this PR locally
In  order to tests this we first need to edit the configuration used by `elastic-packages`

* Enable kibana logging, by adding the configuration below to ` ~/.elastic-package/profiles/default/stack/kibana.config.8x.yml`
```
xpack.security.audit.enabled: true
xpack.security.audit.appender:
  type: rolling-file
  fileName: ./.kbn-logs/audit.log
  policy:
    type: time-interval
    interval: 24h
  strategy:
    type: numeric
    max: 10
  layout:
    type: json

logging:
  appenders:
    file:
      type: file
      fileName: ./.kbn-logs/kibana.log
      layout:
        type: json
  root:
    appenders: [default, file]
    level: all

  loggers:
    - name: server
      level: fatal
    - name: telemetry
      appenders: [file]
      level: all
    - name: metrics.ops
      appenders: [file]
      level: debug
```
* Edit ` ~/.elastic-package/profiles/default/stack/snapshot.yml`, adding `"../../../tmp/service_logs:/usr/share/kibana/.kbn-logs"` to the list of volumes for `kibana` container, to enable the agent to see the logs
* From the repo root folder go to `packages/platform_observability` folder and run `elastic-package build`
* Run `elastic-package stack up -v -d`
* On Kibana, go to `Integrations` 
* Install `Platform Observability` with default configuration, adding it to `Elastic-Agent` host

## Related issues

- Closes [#2226](https://github.com/elastic/observability-dev/issues/2226)

## Screenshots
**Integration page**
<img width="1287" alt="image" src="https://user-images.githubusercontent.com/2767137/179688807-5acc94b1-26e7-405a-8139-5b3f89e24a2b.png">

**Kibana logs**
<img width="1443" alt="image" src="https://user-images.githubusercontent.com/2767137/176436589-43a042d2-77e4-499d-b6ad-caa73db7afa0.png">

**Kibana audit logs**
<img width="1475" alt="image" src="https://user-images.githubusercontent.com/2767137/176436440-562a4bac-b529-4472-8ce1-d915d3161242.png">

2022-06-29 12:49 UTC, crespocarlos commented on packages/platform-observability/data_stream/audit/elasticsearch/ingest_pipeline/kibana-audit-logs-ecs.yml
> +---
duplicate from `data_steam/log`. could this be centralized?

2022-06-29 12:51 UTC, crespocarlos commented on packages/platform-observability/data_stream/log/fields/ecs.yml
> +- name: client.ip
based on the tests that I've run, if the fields on the logs are not present here, the ingestion will fail. Luckily the tests make it easier to identify what's missing

2022-06-30 03:29 UTC, matschaffer commented
The first time I made the changes I hit this which reverted them:

```
❯ elastic-package version
2022/06/30 12:26:04  WARN Default profile has been changed by user or updated by elastic-package. The current profile will be moved.
elastic-package has been installed.
elastic-package version-hash 3144604 (build time: 2022-06-30T12:23:43+09:00)
```

Maybe due to me having run elastic-package on an older version. Thought I'd mention it incase other testers bumped into the same thing.

2022-06-30 05:16 UTC, matschaffer commented
heh, so far my attempts at starting the stack are failing. Will have to dig:

```
Creating elastic-package-stack_kibana_1                    ... done

ERROR: for fleet-server  Container "a6027ac4a639" is unhealthy.

ERROR: for kibana_is_ready  Container "a6027ac4a639" is unhealthy.
ERROR: Encountered errors while bringing up the project.
Error: booting up the stack failed: running docker-compose failed: running command failed: running Docker Compose up command failed: exit status 1
```

2022-06-30 05:36 UTC, matschaffer commented
Interestingly enough, the kibana healthcheck checks for the ES security index. which is red. Go figure 😆 

https://github.com/elastic/elastic-package/blob/3b2d1e91503707f6be7685c9478a2107bd2a2ed7/internal/install/_static/kibana_healthcheck.sh#L6

2022-06-30 05:57 UTC, matschaffer commented
ah!
```
❯ docker logs elastic-package-stack_elasticsearch_1 -n 1
{"@timestamp":"2022-06-30T05:55:51.586Z", "log.level": "WARN", "message":"high disk watermark [90%] exceeded on [Vo4wyn23ReWufzMT2R9n3g][5b4a83809124][/usr/share/elasticsearch/data] free: 5.6gb[9.6%], shards will be relocated away from this node; currently relocating away shards totalling [0] bytes; the node is expected to continue to exceed the high disk watermark when these relocations are complete", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[5b4a83809124][masterService#updateTask][T#1]","log.logger":"org.elasticsearch.cluster.routing.allocation.DiskThresholdMonitor","elasticsearch.cluster.uuid":"wzlK4-GBTymeP6n_Izf6ZA","elasticsearch.node.id":"Vo4wyn23ReWufzMT2R9n3g","elasticsearch.node.name":"5b4a83809124","elasticsearch.cluster.name":"elasticsearch"}
```

2022-06-30 06:44 UTC, matschaffer reviewed
Success! I also had to do this stuff to get your package to show up https://github.com/elastic/integrations/blob/main/docs/developer_workflow_design_build_test_integration.md#build

<img width="1644" alt="Screen Shot 2022-06-30 at 15 29 17" src="https://user-images.githubusercontent.com/690/176607983-66ab073a-6b54-4f8e-a86a-0dfb16c7739e.png">

The elastic-package stack was surprisingly hard to setup. A full docker disk failed in a way that looked like kibana was wrong, I had to import & trust the self-signed SSL cert. Either I'm holding it wrong or we have some work to do there. :)

Oh, and not sure where the kibana logo SVG is from. It's a little different than https://brand.elastic.co/302f66895/p/41ff52-solution-logos/b/14d954/i/11013297 - maybe good to re-import?

2022-06-30 06:44 UTC, matschaffer commented on packages/platform-observability/data_stream/audit/fields/ecs.yml
> +- name: user.roles
If we add fields to the kibana log I wonder if they also need to be added here?

2022-06-30 06:44 UTC, matschaffer commented on packages/platform-observability/data_stream/log/manifest.yml
> +          - /tmp/service_logs/kibana.log
I see a `/usr/share/kibana/logs` in the container. Wondering if we should default to that path and update the elastic-package stack bindmounts to go there.

2022-06-30 06:44 UTC, matschaffer commented on packages/platform-observability/data_stream/audit/agent/stream/log.yml.hbs
> +{{processors}}
I'm guessing we can add "filebeat" processors (like https://www.elastic.co/guide/en/beats/filebeat/current/decode-json-fields.html) to the manifest and have them show up here. Or maybe just put them in this file directly.

Not sure what's in-fashion for packages today regarding reader-vs-ES side processing but personally I like to push as simple transformation as I can to the collection point. Maybe @mtojek can advise.

2022-06-30 07:42 UTC, crespocarlos commented on packages/platform-observability/data_stream/audit/fields/ecs.yml
> +- name: user.roles
I think so. On the logs UI I saw some errors because I didn't have the `http.request.headers` fields mapped out here. 

If you remove one of those fileds and run `elastic-packages test pipeline` within the `platform-observability`, the tests will fail

2022-06-30 07:47 UTC, crespocarlos commented on packages/platform-observability/data_stream/audit/fields/ecs.yml
> +- name: user.roles
oh! and yes. I forgot to mention this
>  I also had to do this stuff to get your package to show up https://github.com/elastic/integrations/blob/main/docs/developer_workflow_design_build_test_integration.md#build

2022-06-30 07:54 UTC, crespocarlos commented on packages/platform-observability/data_stream/log/manifest.yml
> +          - /tmp/service_logs/kibana.log
Yeah. Should we also enable Kibana logging by default?

2022-06-30 11:55 UTC, matschaffer commented on packages/platform-observability/data_stream/log/manifest.yml
> +          - /tmp/service_logs/kibana.log
Definitely :)

2022-07-04 02:56 UTC, matschaffer commented on packages/platform-observability/data_stream/audit/fields/ecs.yml
> +- name: user.roles
It seems unfortunate that adding an ECS-defined field to a service would require package changes.

@andresrc @ruflin can you confirm if this is expected?

I would have hoped as long as we stick to ECS logs can get imported even if they contain additional also-ECS fields.

2022-07-04 08:11 UTC, crespocarlos commented on packages/platform-observability/data_stream/audit/agent/stream/log.yml.hbs
> +{{processors}}
I did a quick test and it seems to work. I'll explore it a bit more. It would simplify the pipeline config

2022-07-04 08:12 UTC, crespocarlos commented on packages/platform-observability/data_stream/audit/fields/ecs.yml
> +- name: user.roles
I think what I said is not entirely true. Let me run a few more tests to confirm.

2022-07-04 09:17 UTC, matschaffer commented on packages/platform-observability/data_stream/audit/fields/ecs.yml
> +- name: user.roles
Thanks @crespocarlos - I'm hoping there's a way we can avoid re-documenting ECS fields in the package as well.

2022-07-04 09:24 UTC, crespocarlos commented on packages/platform-observability/data_stream/audit/agent/stream/log.yml.hbs
> +{{processors}}
It works.
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/2767137/177124976-e555512f-d2a0-4bc8-946e-ad3fe441a4d5.png">

<img width="884" alt="image" src="https://user-images.githubusercontent.com/2767137/177125033-ad0aa37d-7285-40df-8810-14c4cfeaf4b8.png">

this is all I have for the pipeline:
```
[
  {
    "remove": {
      "field": "data_stream.dataset",
      "ignore_missing": true
    }
  },
  {
    "remove": {
      "field": "event.dataset",
      "ignore_missing": true
    }
  },
  {
    "set": {
      "description": "Uses event.dataset as a default for data_stream.dataset if the latter is not set.",
      "field": "data_stream.dataset",
      "copy_from": "event.dataset",
      "if": "ctx.event?.dataset instanceof String && ctx.event.dataset.length() > 1",
      "override": false
    }
  },
  {
    "script": {
      "source": "ctx.data_stream.dataset = /[\\/*?\"<>|, #:-]/.matcher(ctx.data_stream.dataset).replaceAll('_')\n",
      "if": "ctx.data_stream?.dataset != null"
    }
  },
  {
    "script": {
      "source": "ctx.data_stream.namespace = /[\\/*?\"<>|, #:]/.matcher(ctx.data_stream.namespace).replaceAll('_')\n",
      "if": "ctx.data_stream?.namespace != null"
    }
  },
  {
    "set": {
      "field": "data_stream.type",
      "value": "logs"
    }
  },
  {
    "set": {
      "field": "data_stream.dataset",
      "value": "kibana-logs",
      "override": false
    }
  },
  {
    "set": {
      "field": "data_stream.namespace",
      "value": "platform-observability",
      "override": false
    }
  },
  {
    "set": {
      "field": "event.dataset",
      "copy_from": "data_stream.dataset"
    }
  },
  {
    "rename": {
      "field": "message",
      "target_field": "event.original",
      "ignore_missing": true
    }
  }
]
```

2022-07-04 09:50 UTC, crespocarlos commented on packages/platform-observability/data_stream/audit/agent/stream/log.yml.hbs
> +{{processors}}
A downside of this approach is that the tests are not able to use filebeat processor to parse the logs

2022-07-04 10:54 UTC, crespocarlos commented on packages/platform-observability/data_stream/audit/fields/ecs.yml
> +- name: user.roles
Yeah, we don't necessarily need to document them in order for the pipeline to work. It would be nice to understand what role these field files play in the integration packages. 

The only place where it had any impact was on the tests - when I didn't use the filebeat `decode_json_fields` processor

2022-07-04 12:34 UTC, matschaffer commented on packages/platform-observability/data_stream/audit/agent/stream/log.yml.hbs
> +{{processors}}
Another surprise here :) Hoping we can have some integration experts weigh-in. Are we maybe not supposed to use processors anymore?

2022-07-04 13:17 UTC, crespocarlos commented
I have changed and polished the PoC as I started to understand a bit better how to better configure packages.

### Solutions
For **kibana/audit** logs, the pipeline is configured to parse the json message using filebeat processors. With this approach, I noticed that the tests are not able to properly parse the json using the filebeat processor, but kibana is.

For **kibana/logs**, I kept the configuration from the previous iteration, using a similar approach as here https://github.com/elastic/integrations/pull/2972

### Field files
Field files can impact in some ways. Mostly, if we follow the approach for `kibana/logs` all fields present in the test log files must be documented in order for the tests to pass. New fields produced by the integration must be documented. 

During my tests, I noticed that ECS fields parsed from a json object don't necessarily need to be documented in the package and only what's documented in `base-fields.yml` must be present at all times in order for the pipeline to work

2022-07-06 08:34 UTC, crespocarlos commented on packages/platform-observability/data_stream/audit/_dev/test/pipeline/test-kibana-audit-logs.log-expected.json
> +            "message": "{\"event\":{\"action\":\"http_request\",\"category\":[\"web\"],\"outcome\":\"unknown\"},\"http\":{\"request\":{\"method\":\"post\"}},\"url\":{\"domain\":\"localhost\",\"path\"
Filebeat processors are not executed, that's why it looks like this

2022-07-06 15:55 UTC, klacabane commented
Is this implementation a drop-in replacement for the one we have in the [filebeat module](https://github.com/elastic/beats/tree/main/filebeat/module/kibana) ? If we go the single-package route for SM and PO integration, it'll be interesting to align both implementations. Also for a single-package we'll have to carry over all the ingest pipelines for the legacy pipelines as well, unless we decide to only support starting from v8

2022-07-07 08:18 UTC, crespocarlos commented
Good point @klacabane. I focused more on ingesting the ECS log as-is, but there are fields in the existing Kibana packaged that haven't been ported to this new package and fields from Kibana logs that I didn't remove in the new pipeline. So I'll probably have to align at least the missing fields and/or make sure the new pipeline generates the same expected output.

Since Kibana generates ECS formatted logs starting from V8 (correct me if I'm wrong) I think we'll probably support this new PO package starting from V8

@matschaffer, what's your opinion here?

2022-07-08 11:57 UTC, mtojek commented on .github/CODEOWNERS
> +/packages/platform-observability @elastic/obs-service-integrations @elastic/infra-monitoring-ui
Let's not introduce share ownership rules if it isn't necessary. Please leave just `elastic/infra-monitoring-ui` as it's in the manifest file.

2022-07-11 14:12 UTC, mtojek commented on packages/platform-observability/data_stream/audit/agent/stream/log.yml.hbs
> +{{processors}}
I used to follow the rule of thumb. Are you collecting large observability data and is the network loaded? If so, limit those with processors.

2022-07-11 15:23 UTC, mtojek commented on packages/platform-observability/data_stream/audit/agent/stream/log.yml.hbs
> +{{processors}}
We had a slack chat with @crespocarlos, and decided to go with the ingest pipeline due to code simplicity and convenient use of pipeline tests.

2022-07-18 08:19 UTC, mtojek requested changes

2022-07-18 08:19 UTC, mtojek commented on packages/platform_observability/manifest.yml
> +release: experimental
Release property is deprecated: https://github.com/elastic/package-spec/blob/main/versions/1/integration/manifest.spec.yml#L208

2022-07-18 08:19 UTC, mtojek commented on packages/platform_observability/manifest.yml
> +license: basic
License should be deprecated now too: https://github.com/elastic/package-spec/blob/main/versions/1/integration/manifest.spec.yml#L192

not sure what's the status of this initiative, so pinging @jsoriano.

2022-07-18 08:19 UTC, mtojek commented on packages/platform_observability/manifest.yml
> +  kibana.version: "^8.0.0"
Please set the compatibility against the last released Kibana version, unless it's crucial to support Kibana starting with version 8.0.0. It's easier to maintain to pair it with current releases :)

2022-07-18 08:19 UTC, mtojek commented on packages/platform_observability/_dev/build/build.yml
> +    reference: git@1.12
You should use the correct ECS reference. If you want to support Kibanas starting with 8.0.0, then it's `git@v8.0.0`, but if it's about 8.3.0, then `reference: git@v8.3.0`.

2022-07-18 08:19 UTC, mtojek commented on packages/platform_observability/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/1
Please fix the PR number

2022-07-18 08:19 UTC, mtojek commented on packages/platform_observability/data_stream/kibana_log/manifest.yml
> +release: experimental
You should drop the release property from this manifest.

2022-07-18 08:19 UTC, mtojek commented on packages/platform_observability/data_stream/kibana_audit/manifest.yml
> +release: experimental
You should drop the release property from this manifest.

2022-07-18 09:56 UTC, jsoriano commented on packages/platform_observability/manifest.yml
> +license: basic
Changes are in progress, let's continue using the deprecated fields by now.

2022-07-18 14:02 UTC, jsoriano commented on packages/platform_observability/manifest.yml
> +license: basic
The future way to define the current "license" will be with a condition:
```
conditions:
  elastic.subscription: 'basic'
```

If you want to support current and old model you can probably add it already here.

2022-07-18 14:03 UTC, jsoriano commented on packages/platform_observability/manifest.yml
> +license: basic
Oh, regarding `release` yes, you can remove it and rely on semantic versioning.

2022-07-18 14:48 UTC, crespocarlos commented on packages/platform_observability/manifest.yml
> +  kibana.version: "^8.0.0"
The version will probably not even be 8.4.0, because more work on this will be required in the future. But I'll at least for now change it to ^8.3.0

2022-07-18 14:58 UTC, crespocarlos commented on packages/platform_observability/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/1
done

2022-07-18 14:59 UTC, crespocarlos commented on packages/platform_observability/_dev/build/build.yml
> +    reference: git@1.12
done

2022-07-18 15:18 UTC, crespocarlos commented on packages/platform_observability/manifest.yml
> +license: basic
Keeping both old and current modes for license. thanks!

2022-07-19 06:50 UTC, mtojek approved these changes
👍 

I didn't review data stream ingestion as I don't have domain-specific knowledge. I will leave it for your team

2022-07-19 07:20 UTC, crespocarlos commented on packages/platform-observability/data_stream/audit/fields/ecs.yml
> +- name: user.roles
Getting back to this because I re-documented some fields. They are not only used in tests but also to document what the package outputs. Kibana audit logs for example, ingests `kibana.*` fields as-is, that's why I created [this file](https://github.com/elastic/integrations/pull/3622/files#diff-5c7aecc326a5c2da971275079304035cc45a66419ef15adfa21d84a7807f8e3a). The advantage of having ECS fields is that the package build is able to get the description dynamically from ECS repo, for the other types we have to describe them

2022-07-20 06:09 UTC, matschaffer reviewed
I had a couple of final-polish questions. But overall this is looking pretty good.

I guess once we add ES we'll need to rethink the package logo (maybe just use the elastic "cluster" logo), but at least it's an up-to-date kibana logo for now. Thanks for that :)

2022-07-20 06:09 UTC, matschaffer commented on packages/platform_observability/data_stream/kibana_audit/elasticsearch/ingest_pipeline/default.yml
> +      description: Uses event.dataset as a default for data_stream.dataset if the latter is not set.
I'd like to get some more background about why we have to manipulate event/data_stream this much. Is there something we should look at changing in the kibana logs?

2022-07-20 06:09 UTC, matschaffer commented on packages/platform_observability/data_stream/kibana_log/elasticsearch/ingest_pipeline/default.yml
> +  ## some scenarios as update_aliases_succeeded type of operation, these 2 fields are present on the logs
Should we open up a kibana issue to find out why these fields are getting added? Also if non-ECS fields do "leak" into the stream, do we just store them as-is in ES (hoping yes)?

2022-07-20 06:09 UTC, matschaffer commented on packages/platform_observability/data_stream/kibana_log/fields/ecs.yml
> +# only used for tests
Seems like this gets used to create the field lists in the readme as well right? If so we might want to mention on the readme that there could be additional fields in the final documents or something?

2022-07-20 07:40 UTC, crespocarlos commented on packages/platform_observability/data_stream/kibana_log/elasticsearch/ingest_pipeline/default.yml
> +  ## some scenarios as update_aliases_succeeded type of operation, these 2 fields are present on the logs
Make sense! I will open a ticket for them

2022-07-20 07:42 UTC, crespocarlos commented on packages/platform_observability/data_stream/kibana_audit/_dev/test/pipeline/test-common-config.yml
> +  event.ingested: ".*"
This makes the tests ignore any value stored in `event.ingested`. Because it will always have the current timestamp at the time of execution, so it would always fail to compare the expected with current results

2022-07-20 07:57 UTC, crespocarlos commented on packages/platform_observability/data_stream/kibana_log/fields/ecs.yml
> +# only used for tests
I will actually remove this comment altogether. What is documented here (inside `fields` folder) will not only end up in the README, but I just discovered that it will also appear in the Component Templates

2022-07-20 08:03 UTC, crespocarlos commented on packages/platform_observability/data_stream/kibana_audit/elasticsearch/ingest_pipeline/default.yml
> +      description: Uses event.dataset as a default for data_stream.dataset if the latter is not set.
Your question made me wonder whether we need to do all this processing on event/data_stream. In the end we pretty much set their values manually (even though with `override: false`). But all the tests I've run, both `data_stream.dataset` and `data_stream.namespace` had the values we set manually. I'll simplify this by removing these manipulations

2022-07-21 05:37 UTC, matschaffer commented on packages/platform-observability/data_stream/audit/agent/stream/log.yml.hbs
> +{{processors}}
> Are you collecting large observability data and is the network loaded?

Interesting. Does the end user get to set processors? I'd expect network load to be a factor of deployment size.

2022-07-21 05:38 UTC, matschaffer commented on packages/platform_observability/data_stream/kibana_audit/_dev/test/pipeline/test-common-config.yml
> +  event.ingested: ".*"
Ahhh, interesting. So it's a way to have the tests ignore the presence of fields then. Neat, thanks!

2022-07-21 05:42 UTC, matschaffer commented on packages/platform_observability/data_stream/kibana_log/fields/ecs.yml
> +# only used for tests
Thanks! I'm again wondering what happens when services decide to add new logging statements with fields we haven't covered here.

Seems like we might need some mechanism to periodically pull log samples and re-generate this yaml or something. 
Would be great if we could somehow the schema between both the package and kibana itself kind of like what is outlined in https://research.facebook.com/publications/positional-paper-schema-first-application-telemetry/ - but that's for another PR I'm sure :)

2022-07-21 06:16 UTC, matschaffer commented on packages/platform_observability/data_stream/kibana_audit/_dev/test/pipeline/test-kibana-audit-logs.log-expected.json
> +                "session_id": "ccZ0sbxrmmJwo+/y2Mn1tmGIrKOuZYaF8voUh0SkA/k=",
@jkakavas this feels like it could be risky to log (from a audit kibana log sample). Do you know if we should chase it down, or with whom? Or maybe if you know it's safe already?

2022-07-21 06:19 UTC, matschaffer commented on packages/platform_observability/data_stream/kibana_log/elasticsearch/ingest_pipeline/ecs-logs-pipeline.yml
> +  - remove:
Wondering why we set `data_stream` in the audit pipeline but not here. And if that means we're trusting the settings from the log file?

I think if we do that we could end up dropping a log that sets it incorrectly right? Maybe that's a good thing, or maybe it could end up biting us later.

2022-07-21 07:39 UTC, crespocarlos commented on packages/platform_observability/data_stream/kibana_log/elasticsearch/ingest_pipeline/ecs-logs-pipeline.yml
> +  - remove:
We set it, but in the `default.yml` https://github.com/elastic/integrations/pull/3622/files#diff-3f17369084f4b69202a8265f7e529dcfb59d17fb99541af210f273ca765430b0 - if this is what you meant. The `ecs-logs-pipeline.yml` only parses the json

2022-07-21 07:41 UTC, crespocarlos commented on packages/platform_observability/data_stream/kibana_audit/_dev/test/pipeline/test-kibana-audit-logs.log-expected.json
> +                "session_id": "ccZ0sbxrmmJwo+/y2Mn1tmGIrKOuZYaF8voUh0SkA/k=",
why would it be risky in your opinion? By looking at the [docs](https://www.elastic.co/guide/en/beats/filebeat/current/exported-fields-kibana.html), it seems that it's an id associated with the current loging.

2022-07-21 07:51 UTC, crespocarlos commented on packages/platform_observability/data_stream/kibana_log/fields/ecs.yml
> +# only used for tests
> Seems like we might need some mechanism to periodically pull log samples and re-generate this yaml or something. 

This would be great. At least for ECS fields, that's seems possible

2022-07-21 07:53 UTC, matschaffer commented on packages/platform_observability/data_stream/kibana_log/elasticsearch/ingest_pipeline/ecs-logs-pipeline.yml
> +  - remove:
https://github.com/elastic/integrations/pull/3622/files#diff-6df4f8149885dc1f42b4005405e0bec66343de9d81e1f17255545193f465ec22R16-R17 is the set I was referring to. Sorry for not including a link earlier.

2022-07-21 08:14 UTC, crespocarlos commented on packages/platform_observability/data_stream/kibana_log/elasticsearch/ingest_pipeline/ecs-logs-pipeline.yml
> +  - remove:
> I think if we do that we could end up dropping a log that sets it incorrectly right? Maybe that's a good thing, or maybe it could end up biting us later.

This is valid point. We could add an `override: false` there to make sure it doesn't drop anything incorrectly. wdyt?

2022-07-21 08:20 UTC, crespocarlos commented on packages/platform_observability/data_stream/kibana_log/elasticsearch/ingest_pipeline/ecs-logs-pipeline.yml
> +  - remove:
hmm. I'm still not sure if I understand your concern here. I guess you're assuming that `ecs-logs-pipeline.yml` will override the `data_stream` info we set in `default.yml`. I'll check if that would happen

2022-07-21 08:36 UTC, crespocarlos commented on packages/platform_observability/data_stream/kibana_log/elasticsearch/ingest_pipeline/ecs-logs-pipeline.yml
> +  - remove:
What is set in `default` pipeline is what will end up in the logs. If overriding what is being ingested could be problem, we could set `override` to `false`. This way, what's in the actual log file will be left untouched. I don't actually know whether overriding it could represent a problem
```
- set:
      field: data_stream.dataset
      value: kibana-audit-log
      override: false
```

2022-07-22 02:26 UTC, matschaffer commented on packages/platform_observability/data_stream/kibana_audit/_dev/test/pipeline/test-kibana-audit-logs.log-expected.json
> +                "session_id": "ccZ0sbxrmmJwo+/y2Mn1tmGIrKOuZYaF8voUh0SkA/k=",
ah, thanks that helps.

At least this is nothing new so if it's an issue we don't have to fix it in this PR.

I just get a little nervous whenever I see a base64 string in a log stream. Too many occasions when they turned out to be access-providing tokens (like JWT). Hopefully this is just an encoded UUID.  😅

2022-07-22 02:27 UTC, matschaffer commented on packages/platform_observability/data_stream/kibana_log/elasticsearch/ingest_pipeline/ecs-logs-pipeline.yml
> +  - remove:
Ah! Sorry I was getting my files mixed up. I see we set the constant_keyword fields in both pipelines. I was comparing this (logs/ecs pipeline) to the the audit/default pipeline.

In-browser review fail on my part. Much clearer when looking in the IDE.

2022-07-22 02:51 UTC, matschaffer approved these changes
I think this is probably good to merge, especially since it's 0.0.1 so shouldn't end up in a released UI (I think).

This is the deepest I've gone into integrations/packages so could be good to have @klacabane or @neptunian give a look too. Either in this PR or the next one.

2022-07-22 05:17 UTC, matschaffer commented on packages/platform_observability/data_stream/kibana_log/manifest.yml
> +          - /var/log/kibana/kibana.stdout
Oh, sorry about the late feedback, but it took an hour for the stack to start today. Seems like this should be kibana.log no? That's what appears in https://www.elastic.co/guide/en/kibana/master/logging-configuration.html anyway

2022-07-22 07:06 UTC, crespocarlos commented on packages/platform_observability/data_stream/kibana_log/manifest.yml
> +          - /var/log/kibana/kibana.stdout
good catch, I've also aligned the audit log file name with what's in Kibana docs

2022-07-25 12:24 UTC, klacabane approved these changes

2022-07-26 14:31 UTC, merged