[IBM MQ] Add 'qmgr' Data Stream to IBM MQ package
elastic/integrations pull request #3637
Opened 2022-07-01 13:35 UTC by harnish-crest

- Enhancement

## What does this PR do?

- Added 1 data stream (Queue Manager performance metrics).
- Added data collection logic for the data streams.
- Added the ingest pipeline for the data streams.
- Mapped fields according to the ECS schema and added Fields metadata in the appropriate yaml files.
- Added dashboards and visualizations.
- Added system test cases for the data stream.

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's changelog.yml file.
- [X] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally

- Clone integrations repo.
- Install elastic-package locally.
- Start elastic stack using elastic-package.
- Move to integrations/packages/ibmmq directory.
- Run the following command to run tests.
elastic-package test

## Related issues

- Relates #620
- Relates #3590 

## Screenshots
![ibmmq-calls](https://user-images.githubusercontent.com/102945525/176904957-fef30a85-4f70-4613-8eb1-d651593fd9b2.png)
![ibmmq-messages](https://user-images.githubusercontent.com/102945525/176904997-9ea3b8d4-dd03-420a-b1f0-0f80413f605f.png)
![ibmmq-subscriptions](https://user-images.githubusercontent.com/102945525/176905010-29be4077-63ac-4e7c-bb75-1693b5ab73d8.png)

2022-07-01 13:38 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3637/detail/PR-3637/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3637/detail/PR-3637/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3637/detail/PR-3637/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3637/detail/PR-3637/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-07-01T13:25:37.414Z&rangeTo=2022-07-01T13:45:37.414Z&transactionName=Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=a8ad558e7fdce80d0bb6dcf3f3733621&transactionId=abf1cfacaf5215ab)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-07-01T13:35:37.414+0000


* Duration: 2 min 30 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![3](https://img.shields.io/badge/3%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3637/detail/PR-3637/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Load a resource file from a shared library`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3637/runs/1/steps/91/log/?start=0">here</a></li>
<li>Description: <code>approval-list/elastic/integrations.yml</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3637/runs/1/steps/117/log/?start=0">here</a></li>

</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3637/runs/1/steps/88/log/?start=0">here</a></li>
<li>Description: <code>githubApiCall: The REST API call https://api.github.com/orgs/elastic/members/harnish-crest return the message : java.lang.Exception: httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/harnish-crest : httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/harnish-crest : Code: 404Error: {"message":"User does not exist or is not a member of the organization","documentation_url":"https://docs.github.com/rest/reference/orgs#check-organization-membership-for-a-user"}</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-07-01 13:39 UTC, yug-elastic commented
/test

2022-07-01 13:55 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`1/1`) | :green_heart: 
Files | 100.0% (`1/1`) | :green_heart: 3.472
Classes | 100.0% (`1/1`) | :green_heart: 3.472
Methods | 100.0% (`7/7`) | :green_heart: 10.635
Lines | 100.0% (`350/350`) | :green_heart: 9.056
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-07-04 06:21 UTC, yug-elastic commented on packages/ibmmq/data_stream/qmgr/sample_event.json
> +        "module": "prometheus",
I think `event.module` should be set to the package name as per the doc.
https://www.elastic.co/guide/en/ecs/current/ecs-event.html#field-event-module

2022-07-04 06:23 UTC, yug-elastic requested changes
Requested some changes

2022-07-04 07:40 UTC, yug-elastic commented
/test

2022-07-04 07:41 UTC, yug-elastic approved these changes
LGTM

2022-07-28 17:17 UTC, ritalwar requested changes
Please remove the group fields which contain only single field and use them directly wherever possible and also specify unit for the fields if applicable.

2022-07-28 17:30 UTC, harnish-crest commented on packages/ibmmq/data_stream/qmgr/fields/fields.yml
> +                - name: callback
Here, we have two callback count, one is failed and one is succeeded. So, we have done field mapping in such a manner that we have failed callback counts and succeeded callback counts.

2022-08-01 08:59 UTC, ritalwar approved these changes
LGTM

2022-08-02 05:41 UTC, harnish-crest commented on packages/ibmmq/data_stream/errorlog/fields/fields.yml
> -        - name: log_timestamp
@ritalwar : FYI, we initially set the `log_timestamp` value into `@timestamp` field and removed the `log_timestamp` field in the pipeline. So, defining the same is unecessary. Hence, removing it from fields.yml. The change is a part of the errorlog data stream, but we are shipping it here as the PR for it has been merged and this was caught at a later stage.

2022-08-02 11:57 UTC, ritalwar requested changes

2022-08-02 11:57 UTC, ritalwar commented on packages/ibmmq/data_stream/qmgr/fields/fields.yml
> +                  description: Interval total destructive get byte count.
Description is little unclear, Please refer https://www.ibm.com/docs/en/ibm-mq/9.0?topic=console-monitoring-system-resource-usage, if this could help.

2022-08-02 11:57 UTC, ritalwar commented on packages/ibmmq/data_stream/qmgr/fields/fields.yml
> +                  description: Interval total destructive get count.
Description is little unclear, Please refer https://www.ibm.com/docs/en/ibm-mq/9.0?topic=console-monitoring-system-resource-usage, if this could help.

2022-08-02 11:57 UTC, ritalwar commented on packages/ibmmq/data_stream/qmgr/fields/fields.yml
> +                      description: Non-persistent message destructive get count.
destructive get count or browse?

2022-08-02 11:57 UTC, ritalwar commented on packages/ibmmq/data_stream/qmgr/fields/fields.yml
> +                      description: Published to subscribers byte count.
byte count or count ?

2022-08-02 11:57 UTC, ritalwar commented on packages/ibmmq/data_stream/qmgr/fields/fields.yml
> +                  description: Alter durable subscription count.
Alter or Resume?

2022-08-02 12:16 UTC, harnish-crest commented on packages/ibmmq/data_stream/qmgr/fields/fields.yml
> +                  description: Interval total destructive get byte count.
We have referred this official [doc](https://www.ibm.com/docs/en/ibm-mq/9.2?topic=operator-metrics-published-when-using-mq#:~:text=Interval%20total%20destructive%20get%20%2D%20byte%20count) descriptions. Please have a look.

2022-08-02 12:18 UTC, harnish-crest commented on packages/ibmmq/data_stream/qmgr/fields/fields.yml
> +                  description: Interval total destructive get count.
We have referred this official [doc](https://www.ibm.com/docs/en/ibm-mq/9.2?topic=operator-metrics-published-when-using-mq#:~:text=Interval%20total%20destructive%20get%2D%20count) descriptions. Please have a look.

2022-08-03 12:52 UTC, ritalwar approved these changes

2022-08-03 12:54 UTC, merged