[Cloud Posture] add benchmark id to rule template
elastic/integrations pull request #3654
Opened 2022-07-05 13:37 UTC by orouz

## What does this PR do?

this PR uses the newly introduced `benchmark.id` property and assigns every existing rule templates to use `cis_k8s` as its benchmark id. 
when EKS rule templates are introduced, they should be added with their benchmark id property set to `cis_eks`

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] ~~I have verified that all data streams collect metrics or logs.~~
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] ~~I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).~~

## How to test this PR locally

1. use local package registry
   - setup `xpack.fleet.registryUrl: 'http://localhost:8080'` in `kibana.dev.yml` 
   - pull this PR [integrations PR](https://github.com/elastic/integrations/pull/3654) 
   - add an `eks`  rule
      - copy-paste a `cis_k8s` rule
      - change its `id` so it's unique (replace a single char)
      - change the `benchmark.id` to `cis_eks` 
   - run `elastic-package build && elastic-package stack up -v -s package-registry`  
2. add a CIS integration per benchmark and verify the number of rules is `92` for `cis_k8s` and `1` for `cis_eks` 
  
 example:
![Screen Shot 2022-07-11 at 16 06 55](https://user-images.githubusercontent.com/20814186/178271181-e0acfd22-7c73-4765-aff1-0a8b671f1caf.png)

2022-07-05 13:48 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3654/detail/PR-3654/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3654/detail/PR-3654/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3654/detail/PR-3654/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3654/detail/PR-3654/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_3654.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-07-05T13:28:05.059Z&rangeTo=2022-07-05T13:48:05.059Z&transactionName=Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=60887823cb239e560a994ce7fc237064&transactionId=424613440d49e8dd)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-07-05T13:38:05.059+0000


* Duration: 9 min 29 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3654/detail/PR-3654/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Check integration: cloud_security_posture`
<ul>
<li>Took 0 min 1 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3654/runs/1/steps/840/log/?start=0">here</a></li>
<li>Description: <code>../../build/elastic-package check -v</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3654/runs/1/steps/876/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-07-11 13:26 UTC, orouz commented on packages/cloud_security_posture/data_stream/findings/manifest.yml
> +      ###### only a single benchmark can be enabled. default is K8s CIS.
this was added to somewhat mitigate the confusion users may have when they install an integration with both or no benchmark types enabled and then learn we used the default type - `cis_k8s` 

the addition itself includes a text that's conviently rendered by a markdown formatter so it ends up looking like this: 
![Screen Shot 2022-07-11 at 15 21 33](https://user-images.githubusercontent.com/20814186/178273192-e129e65c-9194-4ed8-8c59-5cff69d73899.png)

note this should be temporary

2022-07-12 09:58 UTC, kfirpeled requested changes

2022-07-12 09:58 UTC, kfirpeled commented on packages/cloud_security_posture/changelog.yml
> +    - description: update rule benchmark field to include an id
Missing a capital letter at the beginning of a line

```diff
-    - description: update rule benchmark field to include an id
+    - description: Update rule benchmark field to include an id
```

2022-07-12 16:22 UTC, kfirpeled commented on packages/cloud_security_posture/data_stream/findings/manifest.yml
> +      ###### only a single benchmark can be enabled. default is K8s CIS.
same

2022-07-12 16:25 UTC, kfirpeled commented on packages/cloud_security_posture/data_stream/findings/manifest.yml
> +      ###### only a single benchmark can be enabled. default is K8s CIS.
```suggestion
      ###### Only a single benchmark can be enabled. Default is K8s CIS.
```

2022-07-12 16:25 UTC, kfirpeled commented on packages/cloud_security_posture/data_stream/findings/manifest.yml
> +      ###### only a single benchmark can be enabled. default is K8s CIS.
```suggestion
      ###### Only a single benchmark can be enabled. Default is K8s CIS.
```

2022-07-13 07:17 UTC, orouz commented
/test

2022-07-14 07:40 UTC, orouz commented
/test

2022-07-14 10:30 UTC, merged