[Osquery] OSQuery DFIR Saved Queries
elastic/integrations pull request #3659
Opened 2022-07-06 12:45 UTC by w0rk3r

## What does this PR do?

Adds DFIR-related saved queries to the OSQuery manager integration

2022-07-21 11:56 UTC, tomsonpl commented on packages/osquery_manager/kibana/osquery_saved_query/osquery_manager-157d5550-fd27-11ec-8645-83a23bc513b5.json
> +        "query": "select name, regex_match(r.key, '[^\\\\]\\w+$', 0) as ExclusionType, key, datetime(mtime, 'unixepoch', 'UTC') as ModificationTimeUTC from registry r where\nr.key == 'HKEY_LOCAL_MACH
I tested the query and it gets installed with integration  :) 👍  I would just suggest to put SELECT , FROM and OR in CAPITAL case.

2022-07-21 11:56 UTC, tomsonpl requested changes
Left one comments, besides LGTM from Asset management :)

2022-07-25 17:24 UTC, melissaburpo reviewed
I just had one small suggested change to update the `id`. 

Also, a question: should we add ECS mappings for any fields returned in the results? I tried testing the query to see what the results look like, but I wasn't able to run it successfully - I suspect that's because in its current form the query has some extra formatting for the json version of the saved object.

2022-07-25 17:35 UTC, w0rk3r commented
@melissaburpo did it returned any error? Because it will return null if no exceptions exist

2022-07-25 17:42 UTC, melissaburpo commented
The issue was that I tried to copy/paste the query directly from the PR to try running it, so it had some syntax issues (like the `\nr` characters). 

Thanks for sharing the screenshot though, that helps! Looking at the results, I don't think there are any ECS mappings needed for the `defender_exclusions` query, so that helps to answer that question. Appreciate it!

2022-08-10 00:49 UTC, w0rk3r commented
Here are a few screenshots on the queries returning the desired results:

<details>
<summary>defender_exclusions_windows_elastic</summary>

![image](https://user-images.githubusercontent.com/26856693/183784819-9ac7c827-d571-4472-bde6-f39909d72ef1.png)

</details>

<details>
<summary>posh_logging_windows_elastic</summary>

![image](https://user-images.githubusercontent.com/26856693/183785399-e6a89b8f-29cf-4091-afd9-2c7fd9823586.png)

</details>

<details>
<summary>unsigned_services_vt_windows_elastic</summary>

![image](https://user-images.githubusercontent.com/26856693/183785458-cbe45b73-e7fd-4bc9-a995-2aa12e3d30b5.png)

</details>

<details>
<summary>unsigned_processes_vt_windows_elastic</summary>

![image](https://user-images.githubusercontent.com/26856693/183785563-70d50a74-23fb-45b7-a14f-73935a5dd90a.png)

</details>

<details>
<summary>unsigned_startup_items_vt_windows_elastic</summary>

![image](https://user-images.githubusercontent.com/26856693/183785665-dc308745-91c7-486e-a8ba-e43a2dfaa797.png)

</details>

<details>
<summary>unsigned_dlls_on_system_folders_vt_windows_elastic</summary>

![image](https://user-images.githubusercontent.com/26856693/183785886-24a0fe9f-d21a-4f90-abf9-027d55d432aa.png)

</details>

<details>
<summary>winbaseobj_mutex_search_windows_elastic</summary>

![image](https://user-images.githubusercontent.com/26856693/183786032-541c4162-56f4-4b81-919a-87a590f7e121.png)

</details>

<details>
<summary>executables_or_drivers_in_temp_folder_vt_windows_elastic</summary>

![image](https://user-images.githubusercontent.com/26856693/183786118-281e0f76-7546-436d-b1d9-eabe154a01b3.png)

</details>

<details>
<summary>wdigest_uselogoncredential_windows_elastic</summary>

![image](https://user-images.githubusercontent.com/26856693/183786210-b57a631e-077e-4dd1-ac3c-f96ed1e14b46.png)

</details>

Let me know if I can help with anything around these ;)

2022-08-12 13:02 UTC, w0rk3r commented on packages/osquery_manager/kibana/osquery_saved_query/osquery_manager-0f61edf0-17e1-11ed-89c6-331eb0db6d01.json
> +        "https://www.sans.org/blog/looking-at-mutex-objects-for-malware-discovery-indicators-of-compromise/"
Not obligatory, just saw it available and thought the use could benefit of some additional context. I can remove them

2022-08-12 14:10 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 2.857
Classes | 100.0% (`0/0`) | :green_heart: 2.857
Methods | 33.333% (`1/3`) | :-1: -55.881
Lines | 100.0% (`0/0`) | :green_heart: 9.347
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-08-15 19:18 UTC, tomsonpl approved these changes
LGTM

2022-08-16 06:37 UTC, tomsonpl commented
@w0rk3r I think you can merge it. Let's then test the integration on staging before going on production :)

2022-08-16 08:54 UTC, merged

2022-08-16 09:43 UTC, tomsonpl commented
https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/main/1201/pipeline/ this is a job triggered from this PR. Let's see what happens next 🤞