[oracle_weblogic] Add Integration Package with Bucket Data Stream
elastic/integrations pull request #3666
Opened 2022-07-08 07:47 UTC by bhagyaraj-crest

- Enhancement

## What does this PR do?

- Generated the skeleton of Couchbase integration package.
- Added 1 data stream ( bucket )
- Added data collection logic.
- Added the ingest pipelines.
- Mapped fields according to the ECS schema and added Fields metadata in the appropriate yml files.
- Added system test cases.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's changelog.yml file.
- [x] If I'm introducing a new feature, I have modified the Kibana version constraint in my package's manifest.yml file to point to the latest Elastic stack release (e.g. ^7.13.0).

## How to test this PR locally

- Clone integrations repo.
- Install elastic-package locally.
- Start elastic stack using elastic-package.
- Move to integrations/packages/couchbase directory.
- Run the following command to run tests. 
> elastic-package test

2022-07-08 07:49 UTC, yug-elastic commented
/test

2022-07-08 07:50 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3666/detail/PR-3666/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3666/detail/PR-3666/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3666/detail/PR-3666/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3666/detail/PR-3666/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-07-08T07:37:32.872Z&rangeTo=2022-07-08T07:57:32.872Z&transactionName=Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=4cd34576934ef391964d5ef2e71d5ad5&transactionId=69a7e3e295d44bbf)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-07-08T07:47:32.872+0000


* Duration: 2 min 24 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![3](https://img.shields.io/badge/3%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3666/detail/PR-3666/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Load a resource file from a shared library`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3666/runs/1/steps/81/log/?start=0">here</a></li>
<li>Description: <code>approval-list/elastic/integrations.yml</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3666/runs/1/steps/117/log/?start=0">here</a></li>

</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3666/runs/1/steps/89/log/?start=0">here</a></li>
<li>Description: <code>githubApiCall: The REST API call https://api.github.com/orgs/elastic/members/bhagyaraj-crest return the message : java.lang.Exception: httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/bhagyaraj-crest : httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/bhagyaraj-crest : Code: 404Error: {"message":"User does not exist or is not a member of the organization","documentation_url":"https://docs.github.com/rest/reference/orgs#check-organization-membership-for-a-user"}</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-07-08 09:02 UTC, yug-elastic commented
/test

2022-07-08 09:26 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`1/1`) | :green_heart: 
Files | 100.0% (`1/1`) | :green_heart: 3.171
Classes | 100.0% (`1/1`) | :green_heart: 3.171
Methods | 100.0% (`7/7`) | :green_heart: 10.463
Lines | 100.0% (`89/89`) | :green_heart: 8.916
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-07-11 06:26 UTC, yug-elastic approved these changes
LGTM!

2022-07-18 09:17 UTC, yug-elastic commented
/test

2022-07-21 12:42 UTC, ritalwar requested changes
Please re-check and confirm the couchbase logo that is being used. 
Also, I don't see any dashboards for this integration.

2022-07-21 12:42 UTC, ritalwar commented on packages/couchbase/data_stream/bucket/fields/fields.yml
> +              type: group
Do we really need to make it group field? as it only contain one field, can we rather use used.bytes directly?

2022-07-21 12:42 UTC, ritalwar commented on packages/couchbase/data_stream/bucket/fields/fields.yml
> +        - name: item
Do we really need to make it group field? as it only contain one field, can we rather use item.count directly?

2022-07-21 12:42 UTC, ritalwar commented on packages/couchbase/data_stream/bucket/fields/fields.yml
> +        - name: memory
Do we really need to make it group field? as it only contain one field, can we rather use memory.used.bytes directly?

2022-07-21 12:42 UTC, ritalwar commented on packages/couchbase/data_stream/bucket/fields/fields.yml
> +                - name: used
Do we really need to make it group field? as it only contain one field, can we rather use used.pct directly?

2022-07-21 12:42 UTC, ritalwar commented on packages/couchbase/data_stream/bucket/fields/fields.yml
> +                      type: float
shouldn't this be scaled_float?

2022-07-21 12:42 UTC, ritalwar commented on packages/couchbase/data_stream/bucket/fields/fields.yml
> +          type: long
Please specify unit for long/float data types.

2022-07-21 12:42 UTC, ritalwar commented on packages/couchbase/data_stream/bucket/sample_event.json
> +        "version": "8.2.0"
The build ecs version is 8.3.0 and the sample event ecs version is 8.2.0.

2022-07-21 12:42 UTC, ritalwar commented on packages/couchbase/data_stream/bucket/elasticsearch/ingest_pipeline/default.yml
> +      value: [info]
nit: brackets not needed.

2022-07-21 12:42 UTC, ritalwar commented on packages/couchbase/data_stream/bucket/elasticsearch/ingest_pipeline/default.yml
> +      value: [database]
nit: brackets not needed.

2022-07-22 05:38 UTC, bhagyaraj-crest commented on packages/couchbase/manifest.yml
> +title: Couchbase
I believe most of the other integrations here are following the convention of mentioning the product name in the `title`. I just picked up a few common ones randomly.
References:
- https://github.com/elastic/integrations/blob/main/packages/1password/manifest.yml#L3
- https://github.com/elastic/integrations/blob/main/packages/apache/manifest.yml#L3
- https://github.com/elastic/integrations/blob/main/packages/google_workspace/manifest.yml#L2

Please let me know if you still think updating it `Couchbase Metrics` sounds more intuitive to you.

2022-07-22 06:01 UTC, bhagyaraj-crest commented on packages/couchbase/manifest.yml
> +        description: Collect Couchbase metrics using http module.
Agreed. However, the reason for keeping it generic is keeping in mind it's future extensibility of the data streams.
One more thing to add here, we already have the data stream specific title nested inside as the toggle button for more details. Hence, mentioning the details in the main title would make it redundant in my opinion. Please refer the screenshot.
![image](https://user-images.githubusercontent.com/108920532/180373422-e8355927-a7ac-463e-a68c-4bf48837c0dd.png)
These were just my two cents. Do you think we should still update the `title` as well as `description` to: `Collect bucket/cluster metrics from Couchbase instances`?

2022-07-22 06:08 UTC, bhagyaraj-crest commented on packages/couchbase/data_stream/bucket/manifest.yml
> +        description: i.e. certificate_authorities, supported_protocols, verification_mode etc.
We had a similar discussion over other GitHub PR with @muthu-mps and we agreed upon keeping it consistent with the other integrations.
Please refer: https://github.com/elastic/integrations/pull/3591#discussion_r916613240

2022-07-22 06:37 UTC, bhagyaraj-crest commented on packages/couchbase/data_stream/bucket/elasticsearch/ingest_pipeline/default.yml
> +      value: [database]
Please refer to the note mentioned in the ECS field reference for the field.
https://www.elastic.co/guide/en/ecs/current/ecs-event.html#field-event-category

> Note: this field should contain an array of values.

2022-07-22 06:39 UTC, bhagyaraj-crest commented on packages/couchbase/data_stream/bucket/elasticsearch/ingest_pipeline/default.yml
> +      value: [info]
Please refer to the note mentioned in the ECS field reference for the field.
https://www.elastic.co/guide/en/ecs/current/ecs-event.html#field-event-type

> Note: this field should contain an array of values.

2022-07-22 08:16 UTC, bhagyaraj-crest commented
> Please re-check and confirm the couchbase logo that is being used. 

Other option is to use the following logo:
https://worldvectorlogo.com/logo/couchbase
If you have any other link to a logo, kindly share and we can update it.


> Also, I don't see any dashboards for this integration.

Kindly refer the discussion here: https://github.com/elastic/integrations/pull/3706#issuecomment-1188991096

2022-07-26 05:37 UTC, ritalwar commented on packages/couchbase/data_stream/bucket/fields/fields.yml
> +          type: long
No, let's not.

2022-07-26 05:38 UTC, ritalwar commented
> https://worldvectorlogo.com/logo/couchbase

Yes, let's go with this one.

2022-07-26 19:17 UTC, bhagyaraj-crest commented
> > https://worldvectorlogo.com/logo/couchbase
> 
> Yes, let's go with this one.

Sure, thanks for the confirmation. Updated the PR with the changes. Kindly perform a final round of review and let us know if you have any further concerns.

2022-07-27 09:36 UTC, merged