Change event.kind and adjusting some relevant alert fields
elastic/integrations pull request #3669
Opened 2022-07-08 09:40 UTC by ChriZzn

## What does this PR do?

Added relevant fields for Alerts and changed the event.kind field to "alert", this is useful to show the Threats from Sentinel One in Kibana under "External Alerts"

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2022-07-08 09:43 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3669/detail/PR-3669/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3669/detail/PR-3669/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3669/detail/PR-3669/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3669/detail/PR-3669/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-07-08T09:30:52.568Z&rangeTo=2022-07-08T09:50:52.568Z&transactionName=Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=4c70725d0b0491ead3394bf0e9ebf7c3&transactionId=7841859f6cd12bcf)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-07-08T09:40:52.568+0000


* Duration: 3 min 44 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![3](https://img.shields.io/badge/3%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3669/detail/PR-3669/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Load a resource file from a shared library`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3669/runs/1/steps/81/log/?start=0">here</a></li>
<li>Description: <code>approval-list/elastic/integrations.yml</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3669/runs/1/steps/117/log/?start=0">here</a></li>

</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3669/runs/1/steps/89/log/?start=0">here</a></li>
<li>Description: <code>githubApiCall: The REST API call https://api.github.com/orgs/elastic/members/ChriZzn return the message : java.lang.Exception: httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/ChriZzn : httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/ChriZzn : Code: 404Error: {"message":"User does not exist or is not a member of the organization","documentation_url":"https://docs.github.com/rest/reference/orgs#check-organization-membership-for-a-user"}</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-07-08 12:51 UTC, andrewkroh commented
Hi @ChriZzn, could you please sign the CLA https://www.elastic.co/contributor-agreement? Thanks.

2022-07-08 12:52 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2022-07-20 23:52 UTC, andrewkroh requested changes

2022-07-20 23:52 UTC, andrewkroh commented on packages/sentinel_one/data_stream/threat/elasticsearch/ingest_pipeline/default.yml
> +      copy_from: json.threatInfo.engines
This field appears to be an array and `event.action` should be a string. https://www.elastic.co/guide/en/ecs/current/ecs-event.html#field-event-action

2022-07-20 23:52 UTC, andrewkroh commented on packages/sentinel_one/data_stream/threat/elasticsearch/ingest_pipeline/default.yml
> +      field: user.name
`user.name` is set later on in the pipeline. In order to preserve the existing behavior I recommend to move this after the existing processor that sets it and add a conditional.

```
  - set:
      if: ctx.user?.name == null
      field: user.name
      copy_from: json.threatInfo.processUser
      ignore_empty_value: true
```

2022-07-20 23:52 UTC, andrewkroh commented on packages/sentinel_one/data_stream/threat/elasticsearch/ingest_pipeline/default.yml
> +      if: ctx.json.threatInfo.originatorProcess != null
Instead of the `if` you can use `ignore_empty_value: true`.

2022-07-21 07:09 UTC, ChriZzn reviewed
Hi Andrew, 
thanks for the input, i have adjusted all problems/recommendations, should suit so far.

Regards Christoph

2022-08-16 19:04 UTC, andrewkroh commented
/test

2022-08-16 19:06 UTC, andrewkroh approved these changes

2022-08-16 19:23 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`5/5`) | :green_heart: 
Files | 100.0% (`5/5`) | :green_heart: 2.825
Classes | 100.0% (`5/5`) | :green_heart: 2.825
Methods | 100.0% (`71/71`) | :green_heart: 10.666
Lines | 97.976% (`2565/2618`) | :+1: 7.058
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-08-16 19:33 UTC, merged