[GCP] Add GCP Load Balancer Metricset
elastic/integrations pull request #3713
Opened 2022-07-14 11:41 UTC by legoguy1000

## What does this PR do?

Add GCP Load Balancer Metricset

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2022-07-14 11:41 UTC, legoguy1000 commented
@endorama I recreated the PR based on main now that you've merged the `gcp-metrics` branch

2022-07-14 11:44 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3713/detail/PR-3713/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3713/detail/PR-3713/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3713/detail/PR-3713/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3713/detail/PR-3713/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-07-14T11:31:19.860Z&rangeTo=2022-07-14T11:51:19.860Z&transactionName=Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=bcfeb309f6cef75bb982adf374eb32d2&transactionId=175e21ab5fb1dd99)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-07-14T11:41:19.860+0000


* Duration: 3 min 47 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![3](https://img.shields.io/badge/3%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3713/detail/PR-3713/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Load a resource file from a shared library`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3713/runs/1/steps/81/log/?start=0">here</a></li>
<li>Description: <code>approval-list/elastic/integrations.yml</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3713/runs/1/steps/117/log/?start=0">here</a></li>

</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3713/runs/1/steps/89/log/?start=0">here</a></li>
<li>Description: <code>githubApiCall: The REST API call https://api.github.com/orgs/elastic/members/legoguy1000 return the message : java.lang.Exception: httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/legoguy1000 : httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/legoguy1000 : Code: 404Error: {"message":"User does not exist or is not a member of the organization","documentation_url":"https://docs.github.com/rest/reference/orgs#check-organization-membership-for-a-user"}</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-07-17 22:29 UTC, efd6 commented
/test

2022-07-17 22:50 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`4/4`) | :green_heart: 
Files | 100.0% (`4/4`) | :green_heart: 3.145
Classes | 100.0% (`4/4`) | :green_heart: 3.145
Methods | 92.754% (`64/69`) | :+1: 3.337
Lines | 95.969% (`1119/1166`) | :+1: 4.938
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-07-18 00:22 UTC, efd6 reviewed
Are you able to add screenshots of the new dashboards?

2022-07-18 00:22 UTC, efd6 commented on packages/gcp/_dev/build/docs/loadbalancer.md
> +This is the `loadbalancer_metrics` dataset.
It would be good to have a description of what this dataset contains/what it can be used for similar to what is shown for the other datasets.

2022-07-18 00:22 UTC, efd6 commented on packages/gcp/kibana/dashboard/gcp-8f9c6cc0-909d-11ea-8180-7b0dacd9df87.json
> +            "id": "gcp-3f4e9040-909d-11ea-8180-7b0dacd9df87",
This appears to be missing.

2022-07-19 00:59 UTC, efd6 commented
/test

2022-07-19 07:39 UTC, endorama requested changes
The metrics are called `Load balancing` metrics in GCP, so I would keep that naming to help discovery. I also think we should rename the data stream to `loadbalancing` to reflect this. What do you think?

2022-07-19 07:39 UTC, endorama commented on packages/gcp/data_stream/loadbalancer_metrics/fields/base-fields.yml
> +  value: gcp.loadbalancing
I was thinking, given that the event dataset is `loadbalancing` if would be better to name this data stream `loadbalacing` instead of `loadbalancer_metrics`. I'm not sure we have naming guidelines on this, but from my understanding the name of the data stream and the name of the dataset are equal.

2022-07-19 07:39 UTC, endorama commented on packages/gcp/_dev/build/docs/loadbalancer.md
> +The `loadbalancer_metrics` dataset fetches HTTPS, HTTP, and Layer 3 metrics from https://cloud.google.com/load-balancing/[Load Balancing] in Google Cloud Platform. It contains all metrics exported fr
```suggestion
The `loadbalancer_metrics` dataset fetches HTTPS, HTTP, and Layer 3 metrics from [Load Balancing](https://cloud.google.com/load-balancing/) in Google Cloud Platform. It contains all metrics exported from the [GCP Load Balancing Monitoring API](https://cloud.google.com/monitoring/api/metrics_gcp#gcp-loadbalancing).
```

2022-07-19 07:39 UTC, endorama commented on packages/gcp/manifest.yml
> +    description: Collect Load Balancer metrics from Google Cloud Platform (GCP) with Elastic Agent
```suggestion
    description: Collect Load balancing metrics from Google Cloud Platform (GCP) with Elastic Agent
```

2022-07-19 07:39 UTC, endorama commented on packages/gcp/data_stream/loadbalancer_metrics/manifest.yml
> +    description: Collect GCP Load Balancer Metrics
```suggestion
    description: Collect GCP Load balancing metrics
```

2022-07-19 11:15 UTC, legoguy1000 commented
So personally I don't have a preference. Originally I had it as `loadbalancing` but I thought load balancer metrics/logs read better. I can change it back though

2022-07-19 12:41 UTC, endorama commented
I would prefer so, @efd6 what do you think?

2022-07-19 22:03 UTC, legoguy1000 commented
@endorama @efd6 updated

2022-07-19 23:04 UTC, efd6 commented on packages/gcp/manifest.yml
> +    description: Collect Load Balancer metrics from Google Cloud Platform (GCP) with Elastic Agent
The trade mark appears to be "Cloud Load Balancing", so the "b" should probably be capitalised.

2022-07-19 23:04 UTC, efd6 commented
/test

2022-07-20 12:53 UTC, endorama reviewed
There is a leftover `loadbalancer_metrics` in the doc file (requires building the package to update the generated file too) but after that it's good to go!

2022-07-20 12:53 UTC, endorama commented on packages/gcp/_dev/build/docs/loadbalancing.md
> +The `loadbalancer_metrics` dataset fetches HTTPS, HTTP, and Layer 3 metrics from [Load Balancing](https://cloud.google.com/load-balancing/) in Google Cloud Platform. It contains all metrics exported
```suggestion
The `loadbalancing_metrics` dataset fetches HTTPS, HTTP, and Layer 3 metrics from [Load Balancing](https://cloud.google.com/load-balancing/) in Google Cloud Platform. It contains all metrics exported from the [GCP Load Balancing Monitoring API](https://cloud.google.com/monitoring/api/metrics_gcp#gcp-loadbalancing).
```

2022-07-20 14:40 UTC, legoguy1000 commented
fixed

2022-07-26 14:13 UTC, endorama approved these changes

2022-08-02 00:09 UTC, legoguy1000 commented
@endorama can we merge this?

2022-08-09 14:37 UTC, merged