[GCP] Add storage data stream
elastic/integrations pull request #3785
Opened 2022-07-21 11:33 UTC by gpop63

## What does this PR do?

Adds `storage` data stream.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

- Closes: #3717 

## Screenshots

2022-07-21 11:36 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3785/detail/PR-3785/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3785/detail/PR-3785/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3785/detail/PR-3785/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3785/detail/PR-3785/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://null_3785.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-07-21T11:23:51.644Z&rangeTo=2022-07-21T11:43:51.644Z&transactionName=Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=4ba2ddeb21a4834c0d447ed689ff3d48&transactionId=9ab7d1a2ea16c23d)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-07-21T11:33:51.644+0000


* Duration: 3 min 46 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![3](https://img.shields.io/badge/3%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3785/detail/PR-3785/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Check out from version control`
<ul>
<li>Took 0 min 20 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3785/runs/1/steps/10/log/?start=0">here</a></li>
<li>Description: <code>[2022-07-21T11:35:22.549Z] The recommended git tool is: git
[2022-07-21T11:35:31.151Z] using creden</code></l1>
</ul>
  
  
  
  
##### `Check out from version control`
<ul>
<li>Took 0 min 12 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3785/runs/1/steps/14/log/?start=0">here</a></li>
<li>Description: <code>[2022-07-21T11:35:52.262Z] The recommended git tool is: git
[2022-07-21T11:35:52.276Z] using creden</code></l1>
</ul>
  
  
  
  
##### `Check out from version control`
<ul>
<li>Took 0 min 11 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3785/runs/1/steps/18/log/?start=0">here</a></li>
<li>Description: <code>[2022-07-21T11:36:14.702Z] The recommended git tool is: git
[2022-07-21T11:36:14.716Z] using creden</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-07-21 11:50 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`4/4`) | :green_heart: 
Files | 100.0% (`4/4`) | :green_heart: 
Classes | 100.0% (`4/4`) | :green_heart: 
Methods | 98.113% (`52/53`) | :grey_exclamation: 
Lines | 95.21% (`1113/1169`) | :grey_exclamation: 
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-08-01 15:53 UTC, endorama requested changes
Small change but LGTM!

2022-08-01 15:53 UTC, endorama commented on packages/gcp/changelog.yml
> +    - description: Add GCP Storage Data Stream
Please target the most recent version of this package

2022-08-03 19:45 UTC, gpop63 commented on packages/gcp/changelog.yml
> +    - description: Add GCP Storage Data Stream
Fixed.

2022-08-23 09:37 UTC, endorama approved these changes

2022-08-23 15:36 UTC, endorama commented
/test

2022-08-24 08:20 UTC, endorama commented
I cannot reproduce the failure locally, as the same check (`elastic-package check -v`) does not produce any error.

2022-08-24 08:56 UTC, tommyers-elastic requested changes
small typo in metric name

2022-08-24 08:58 UTC, tommyers-elastic approved these changes
LGTM

2022-08-24 13:32 UTC, merged