updated fingerprint with resolved_at
elastic/integrations pull request #3802
Opened 2022-07-22 06:24 UTC by kcreddy

## What does this PR do?
Fixes bug in Github Secret Scanning alerts where events are not getting ingested into ES when an alert is resolved.
- This PR adds `resolved_at` timestamp into `fingerprint` processor to ingest the resolved events

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

2022-07-22 06:25 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2022-07-22 06:36 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3802/detail/PR-3802/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3802/detail/PR-3802/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3802/detail/PR-3802/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3802/detail/PR-3802/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_3802.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-07-22T06:15:11.902Z&rangeTo=2022-07-22T06:35:11.902Z&transactionName=Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=4dd04eaf1d4fa28e50fb7993f21d7489&transactionId=e653dc26319c17fe)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-07-22T06:25:11.902+0000


* Duration: 11 min 16 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3802/detail/PR-3802/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Check integration: github`
<ul>
<li>Took 0 min 1 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3802/runs/1/steps/864/log/?start=0">here</a></li>
<li>Description: <code>../../build/elastic-package check -v</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3802/runs/1/steps/900/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-07-22 10:00 UTC, r00tu53r reviewed
Changes look okay. But the test data does not test the change made. It's missing the `resolved_at` field and value.

2022-07-22 10:12 UTC, kcreddy commented
@r00tu53r Any suggestion where I can add this test? Pipeline tests doesn't seem to contain `_id` field to show that it has changed successfully.

2022-07-22 10:22 UTC, r00tu53r commented
> @r00tu53r Any suggestion where I can add this test? Pipeline tests doesn't seem to contain `_id` field to show that it has changed successfully.

@kcreddy I meant testing the `date` processor with `resolved_at`.

2022-07-22 10:25 UTC, r00tu53r commented
@kcreddy am curious why compute hash to assign it as the document id ? Why not use what elasticsearch generates ?

2022-07-22 11:28 UTC, kcreddy commented
@r00tu53r  The reason why we are using `fingerprint` processor to compute `_id` with these specific fields instead of default is to avoid duplicates. We only want to ingest events when there is some update or resolution to it. If we put it as default, it would create documents for every time the polling happens.

2022-07-22 11:31 UTC, kcreddy commented
> @kcreddy I meant testing the date processor with resolved_at

I tested that `resolved_at` field exists in Kibana with `date` and also the field can be seen in expected json log from pipeline test. I also verified the `_id` functionality manually in Kibana and against the value generated from `_simulate` API with fingerprint processor

2022-07-22 15:20 UTC, adriansr requested changes
Requesting a change for performance

2022-07-22 15:20 UTC, adriansr commented on packages/github/data_stream/secret_scanning/elasticsearch/ingest_pipeline/default.yml
> +
From the testing documents I see that `created_at` is always present, then we can have `updated_at` and finally also `resolved_at`. With the current logic, we will first parse `created_at` and set `@timestamp` from it, then potentially repeat the same for `updated_at` and `resolved_at`. 

Can we update the conditions in these processors so that we only parse one date? Resolved if it exists. Updated if it exists and resolved doesn't, etc.

Also created is parsed twice, one for `event.created` another for `@timestamp`.

2022-07-22 17:18 UTC, kcreddy commented on packages/github/data_stream/secret_scanning/elasticsearch/ingest_pipeline/default.yml
> +
Got it. I updated the logic to run `date` processor only once. Also, changed `event.created` to use `set` instead

2022-07-25 08:24 UTC, adriansr approved these changes
LGTM

2022-07-25 08:37 UTC, merged