[Fortinet] Deprecate original integration & change logfile to filestream
elastic/integrations pull request #3819
Opened 2022-07-25 01:57 UTC by legoguy1000

## What does this PR do?

- Deprecate original Fortinet integration
- Swap the logfile legacy input for the filestream input

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2022-07-25 02:01 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3819/detail/PR-3819/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3819/detail/PR-3819/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3819/detail/PR-3819/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3819/detail/PR-3819/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-07-25T01:47:57.229Z&rangeTo=2022-07-25T02:07:57.229Z&transactionName=Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=e8fc3e4d2fdcea688f547215f922511a&transactionId=b71ce75c6635fa47)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-07-25T01:57:57.229+0000


* Duration: 3 min 59 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![3](https://img.shields.io/badge/3%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3819/detail/PR-3819/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Load a resource file from a shared library`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3819/runs/1/steps/81/log/?start=0">here</a></li>
<li>Description: <code>approval-list/elastic/integrations.yml</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3819/runs/1/steps/117/log/?start=0">here</a></li>

</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3819/runs/1/steps/89/log/?start=0">here</a></li>
<li>Description: <code>githubApiCall: The REST API call https://api.github.com/orgs/elastic/members/legoguy1000 return the message : java.lang.Exception: httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/legoguy1000 : httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/legoguy1000 : Code: 404Error: {"message":"User does not exist or is not a member of the organization","documentation_url":"https://docs.github.com/rest/reference/orgs#check-organization-membership-for-a-user"}</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-07-25 02:17 UTC, efd6 commented on packages/fortinet/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/1
Please update the PR number.

2022-07-25 02:17 UTC, efd6 commented on packages/fortinet_forticlient/data_stream/log/agent/stream/filestream.yml.hbs
> + - {{path}}
Do we need this deletion? (same for the other packages).

2022-07-25 02:17 UTC, efd6 commented on packages/fortinet_forticlient/data_stream/log/agent/stream/filestream.yml.hbs
> +prospector.scanner.exclude_files: ['\.gz$']
Leaving this at the same line as the previous exclude reduces diff noise. (same for the other packages).

2022-07-25 02:17 UTC, efd6 commented
/test

2022-07-25 02:22 UTC, legoguy1000 commented on packages/fortinet_forticlient/data_stream/log/agent/stream/filestream.yml.hbs
> +prospector.scanner.exclude_files: ['\.gz$']
Ya, I copied the config from another integration so I can go back and clean it up.

2022-07-25 02:44 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`1/1`) | :green_heart: 
Files | 100.0% (`1/1`) | :green_heart: 2.913
Classes | 100.0% (`1/1`) | :green_heart: 2.913
Methods | 71.429% (`5/7`) | :-1: -17.952
Lines | 84.615% (`55/65`) | :-1: -5.976
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-07-25 12:01 UTC, legoguy1000 commented
@efd6 comments resolved.

2022-07-27 05:34 UTC, efd6 commented
/test

2022-07-27 05:35 UTC, efd6 approved these changes

2022-08-02 01:44 UTC, efd6 commented
/test

2022-08-02 03:08 UTC, efd6 commented
/test

2022-08-15 03:37 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2022-08-15 03:53 UTC, andrewkroh requested changes
I think changing from `log` to `filestream` will cause problems for users because they will lose their existing state. Much of this is discussed in https://github.com/elastic/integrations/issues/2518. I think we should hold off on this change given the packages are GA. We'll cover making the change with https://github.com/elastic/integrations/issues/2518. 

So I think the filestream changes should be reverted.

2022-08-15 21:48 UTC, legoguy1000 commented
@andrewkroh  Will do.

2022-08-15 22:10 UTC, andrewkroh commented on packages/fortinet/manifest.yml
> +description: Deprecated. Collect logs from Fortinet instances with Elastic Agent.
Can you please check the readme of this package and see if it needs changes to reflect being deprecated. You can look at the microsoft readme to get an idea of what other deprecated pages do. I think it's a "NOTE" and title change.

2022-08-15 22:10 UTC, andrewkroh commented on packages/fortinet_forticlient/changelog.yml
> +      type: enhancement # can be one of: enhancement, bugfix, breaking-change
Let's drop the comment.

2022-08-15 22:14 UTC, andrewkroh approved these changes

2022-08-16 00:00 UTC, legoguy1000 commented
GTG

2022-08-16 00:30 UTC, merged