Update ECS to 8.4.0
elastic/integrations pull request #3865
Opened 2022-07-27 19:58 UTC by leehinman

- cylance
- f5
- fim
- fireeye
- fortinet
- gcp
- gcp_pubsub
- github
- google_workspace
- hashicorp_vault

2022-07-27 20:19 UTC, elasticmachine commented
## :broken_heart: Tests Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3865/detail/PR-3865/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3865/detail/PR-3865/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3865/detail/PR-3865/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3865/detail/PR-3865/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_3865.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-07-27T19:48:44.189Z&rangeTo=2022-07-27T20:08:44.189Z&transactionName=Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=0f596ed40a697680b514487356496ebf&transactionId=1f6ae07c1725091f)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-07-27T19:58:44.189+0000


* Duration: 21 min 36 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 32  |
| Passed       | 78  |
| Skipped      | 0 |
| Total        | 110   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->

  ### Test errors [![32](https://img.shields.io/badge/32%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3865/detail/PR-3865/1//tests)
<details><summary>Expand to view the tests failures</summary><p>
    > Show only the first 10 test failures
    
##### `Check integrations / github / github: check / pipeline test: test-ghas-secret-scanning-json.log – github.secret_scanning`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 null 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 test case failed: Expected results are different from actual ones: --- want
+++ got
@@ -3,7 +3,7 @@
         {
             "@timestamp": "2020-11-07T02:47:13.000Z",
             "ecs": {
-                "version": "8.3.0"
+                "version": "8.4.0"
             },
             "event": {
                 "action": "secret_scanning",
@@ -52,7 +52,7 @@
         {
             "@timestamp": "2020-11-06T18:18:30.000Z",
             "ecs": {
-                "version": "8.3.0"
+                "version": "8.4.0"
             },
             "event": {
                 "action": "secret_scanning",
@@ -80,7 +80,7 @@
         {
             "@timestamp": "2022-07-07T12:56:24.000Z",
             "ecs": {
-                "version": "8.3.0"
+                "version": "8.4.0"
             },
             "event": {
                 "action": "secret_scanning",
@@ -119,7 +119,7 @@
         {
             "@timestamp": "2022-07-07T12:54:02.000Z",
             "ecs": {
-                "version": "8.3.0"
+                "version": "8.4.0"
             },
             "event": {
                 "action": "secret_scanning",
@@ -148,7 +148,7 @@
         {
             "@timestamp": "2022-07-07T12:48:57.000Z",
             "ecs": {
-                "version": "8.3.0"
+                "version": "8.4.0"
             },
             "event": {
                 "action": "secret_scanning",
@@ -177,7 +177,7 @@
         {
             "@timestamp": "2022-07-07T10:52:40.000Z",
             "ecs": {
-                "version": "8.3.0"
+                "version": "8.4.0"
             },
             "event": {
                 "action": "secret_scanning",
@@ -206,7 +206,7 @@
         {
             "@timestamp": "2022-07-07T12:45:43.000Z",
             "ecs": {
-                "version": "8.3.0"
+                "version": "8.4.0"
             },
             "event": {
                 "action": "secret_scanning",
@@ -246,7 +246,7 @@
         {
             "@timestamp": "2022-07-07T09:47:51.000Z",
             "ecs": {
-                "version": "8.3.0"
+                "version": "8.4.0"
             },
             "event": {
                 "action": "secret_scanning",
@@ -275,7 +275,7 @@
         {
             "@timestamp": "2022-07-07T10:13:56.000Z",
             "ecs": {
-                "version": "8.3.0"
+                "version": "8.4.0"
             },
             "event": {
                 "action": "secret_scanning",
 
 ```
</p></details>
</ul>
    
##### `Check integrations / github / github: check / pipeline test: test-audit-json.log – github.audit`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 null 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 test case failed: Expected results are different from actual ones: --- want
+++ got
@@ -3,7 +3,7 @@
         {
             "@timestamp": "2020-03-04T23:24:11.067Z",
             "ecs": {
-                "version": "8.3.0"
+                "version": "8.4.0"
             },
             "event": {
                 "action": "organization_default_label.create",
@@ -36,7 +36,7 @@
         {
             "@timestamp": "2020-03-04T23:24:11.273Z",
             "ecs": {
-                "version": "8.3.0"
+                "version": "8.4.0"
             },
             "event": {
                 "action": "organization_default_label.create",
@@ -69,7 +69,7 @@
         {
             "@timestamp": "2020-03-04T23:24:11.179Z",
             "ecs": {
-                "version": "8.3.0"
+                "version": "8.4.0"
             },
             "event": {
                 "action": "organization_default_label.create",
@@ -107,7 +107,7 @@
                 }
             },
             "ecs": {
-                "version": "8.3.0"
+                "version": "8.4.0"
             },
             "event": {
                 "action": "org.invite_member",
@@ -152,7 +152,7 @@
         {
             "@timestamp": "2020-03-04T23:24:11.101Z",
             "ecs": {
-                "version": "8.3.0"
+                "version": "8.4.0"
             },
             "event": {
                 "action": "organization_default_label.create",
@@ -185,7 +185,7 @@
         {
             "@timestamp": "2020-03-04T23:24:11.214Z",
             "ecs": {
-                "version": "8.3.0"
+                "version": "8.4.0"
             },
             "event": {
                 "action": "organization_default_label.create",
@@ -218,7 +218,7 @@
         {
             "@timestamp": "2020-03-04T23:24:11.364Z",
             "ecs": {
-                "version": "8.3.0"
+                "version": "8.4.0"
             },
             "event": {
                 "action": "organization_default_label.create",
@@ -256,7 +256,7 @@
                 }
             },
             "ecs": {
-                "version": "8.3.0"
+                "version": "8.4.0"
             },
             "event": {
                 "action": "org.invite_member",
@@ -301,7 +301,7 @@
         {
             "@timestamp": "2020-03-04T23:42:30.878Z",
             "ecs": {
-                "version": "8.3.0"
+                "version": "8.4.0"
             },
             "event": {
                 "action": "org.add_member",
@@ -347,7 +347,7 @@
         {
             "@timestamp": "2020-03-04T23:24:11.144Z",
             "ecs": {
-                "version": "8.3.0"
+                "version": "8.4.0"
             },
             "event": {
                 " [...]

2022-07-27 20:19 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 2.868
Classes | 100.0% (`0/0`) | :green_heart: 2.868
Methods | 98.113% (`52/53`) | :+1: 8.852
Lines | 100.0% (`0/0`) | :green_heart: 9.405
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-07-28 18:08 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2022-07-28 18:35 UTC, kcreddy requested changes
Just some minor changes (mainly pipeline test files) which could be added. Rest LGTM

2022-07-28 18:35 UTC, kcreddy commented on packages/fim/data_stream/event/elasticsearch/ingest_pipeline/default.yml
> +      value: '8.4.0'
Missing pipeline test expected log file

2022-07-28 18:35 UTC, kcreddy commented on packages/gcp/data_stream/vpcflow/elasticsearch/ingest_pipeline/default.yml
> +      value: '8.4.0'
There seems to be 3 more data_streams under `gcp` namely `billing`, `compute`, and `firestore`. Not sure if they also need to be udpated?

2022-07-28 18:35 UTC, kcreddy commented on packages/gcp_pubsub/manifest.yml
> +version: "1.2.0"
Probably `generic` datastream pipeline inside `gcp_pub` needs ECS version update

2022-07-28 18:35 UTC, kcreddy commented on packages/hashicorp_vault/data_stream/metrics/elasticsearch/ingest_pipeline/default.yml
> +      value: '8.4.0'
Missing pipeline test expected log file for `metrics` data_stream

2022-07-28 19:55 UTC, taylor-swanson commented
I don't think @elastic/obs-cloud-monitoring should be listed as a code owner here, all of these integrations are owned by @elastic/security-external-integrations?

2022-07-28 19:57 UTC, taylor-swanson commented on packages/fim/data_stream/event/elasticsearch/ingest_pipeline/default.yml
> +      value: '8.4.0'
Adding tests is out of scope for this type of change and should be handled separately. This change only involves updating the ECS version.

2022-07-28 20:04 UTC, taylor-swanson commented on packages/gcp/data_stream/vpcflow/elasticsearch/ingest_pipeline/default.yml
> +      value: '8.4.0'
Those look to be metrics data streams, which don't have ingest pipelines (nor expected files to update).

2022-07-28 20:06 UTC, taylor-swanson commented on packages/hashicorp_vault/data_stream/metrics/elasticsearch/ingest_pipeline/default.yml
> +      value: '8.4.0'
Same comment above regarding metrics data streams.

2022-07-28 20:28 UTC, taylor-swanson approved these changes
LGTM

2022-07-29 03:20 UTC, kcreddy commented on packages/fim/data_stream/event/elasticsearch/ingest_pipeline/default.yml
> +      value: '8.4.0'
Got it, thanks for letting me know 👍🏼

2022-07-29 03:20 UTC, kcreddy commented on packages/gcp/data_stream/vpcflow/elasticsearch/ingest_pipeline/default.yml
> +      value: '8.4.0'
Makes sense

2022-07-29 03:20 UTC, kcreddy approved these changes

2022-07-29 19:30 UTC, merged