Update input types and vars to support runtime config
elastic/integrations pull request #3968
Opened 2022-08-08 11:15 UTC by uri-weisman

## What does this PR do?

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2022-08-08 11:35 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3968/detail/PR-3968/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3968/detail/PR-3968/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3968/detail/PR-3968/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3968/detail/PR-3968/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_3968.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-08-08T11:10:28.744Z&rangeTo=2022-08-08T11:30:28.744Z&transactionName=Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=67ae209ed0fca18d1ca7f9812bd33c94&transactionId=9169e9c371c54832)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-08-08T11:20:28.744+0000


* Duration: 15 min 18 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 2  |
| Skipped      | 0 |
| Total        | 2   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-08-08 11:36 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 2.863
Classes | 100.0% (`0/0`) | :green_heart: 2.863
Methods | 25.0% (`1/4`) | :-1: -64.262
Lines | 100.0% (`0/0`) | :green_heart: 9.359
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-08-08 13:27 UTC, eyalkraft reviewed
let's
```
conditions:
  kibana.version: "^8.4.0"
  ```
  
  So this won't break the current 8.4 release

2022-08-08 13:50 UTC, eyalkraft approved these changes
Merge with the proper changes in Kibana & cloudbeat

2022-08-14 12:20 UTC, kfirpeled approved these changes

2022-08-14 12:20 UTC, kfirpeled commented on packages/cloud_security_posture/manifest.yml
> +    title: Rules Activation
consider changing the title to `List of activated rule ids`

2022-08-14 12:49 UTC, eyalkraft commented on packages/cloud_security_posture/manifest.yml
> +  kibana.version: "^8.4.0"
This has to be 
```suggestion
  kibana.version: "^8.5.0"
```
no?

2022-08-14 14:36 UTC, uri-weisman commented on packages/cloud_security_posture/manifest.yml
> +  kibana.version: "^8.4.0"
Sure, overrode by upstream merge.

2022-08-14 14:42 UTC, oren-zohar requested changes

2022-08-14 14:42 UTC, oren-zohar commented on packages/cloud_security_posture/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/3964
Since 0.0.26 wasn't promoted yet we can unify it under it, no?

2022-08-14 14:45 UTC, uri-weisman commented on packages/cloud_security_posture/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/3964
This pr introduces breaking changes so we want to promote version 0.26 to SNAPSHOT and only then merge this commit.
The Kibana version condition changed to ^8.5.0.

2022-08-14 14:53 UTC, oren-zohar approved these changes

2022-08-14 16:04 UTC, merged