[Spring Boot] Update changelog entry for automatic promotion of package to snapshot
elastic/integrations pull request #3970
Opened 2022-08-08 12:56 UTC by harnish-crest

… by elasticmachine
- Bug

## What does this PR do?

Update changelog entry for automatic promotion of package to snapshot.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2022-08-08 13:00 UTC, yug-elastic commented
CC: @cachedout 
This PR is the outcome of our discussion. Could you please take a look? It just contains a version bump up, and does not contain any other functional/non-functional changes.

2022-08-08 13:00 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3970/detail/PR-3970/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3970/detail/PR-3970/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3970/detail/PR-3970/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3970/detail/PR-3970/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-08-08T12:47:11.909Z&rangeTo=2022-08-08T13:07:11.909Z&transactionName=Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=f945ddd970fca4ed0e56f33a6d08465c&transactionId=da77fefd73c5fa65)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-08-08T12:57:11.909+0000


* Duration: 3 min 45 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![3](https://img.shields.io/badge/3%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-3970/detail/PR-3970/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Load a resource file from a shared library`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3970/runs/1/steps/81/log/?start=0">here</a></li>
<li>Description: <code>approval-list/elastic/integrations.yml</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3970/runs/1/steps/117/log/?start=0">here</a></li>

</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-3970/runs/1/steps/89/log/?start=0">here</a></li>
<li>Description: <code>githubApiCall: The REST API call https://api.github.com/orgs/elastic/members/harnish-crest return the message : java.lang.Exception: httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/harnish-crest : httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/harnish-crest : Code: 404Error: {"message":"User does not exist or is not a member of the organization","documentation_url":"https://docs.github.com/rest/reference/orgs#check-organization-membership-for-a-user"}</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-08-08 13:01 UTC, yug-elastic commented
/test

2022-08-08 13:01 UTC, yug-elastic approved these changes
LGTM

2022-08-08 13:15 UTC, yug-elastic commented
/test

2022-08-08 13:19 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`2/2`) | :green_heart: 
Files | 100.0% (`2/2`) | :green_heart: 2.863
Classes | 100.0% (`2/2`) | :green_heart: 2.863
Methods | 100.0% (`20/20`) | :green_heart: 10.738
Lines | 98.904% (`451/456`) | :+1: 8.263
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-08-08 13:20 UTC, cachedout approved these changes
This looks like what we discussed. Let's see what the CI has to say about it.

2022-08-09 08:30 UTC, jsoriano requested changes

2022-08-09 08:30 UTC, jsoriano commented on packages/ibmmq/changelog.yml
>      - description: IBM MQ integration package with "qmgr" data stream
As this change was not released in 0.1.0, please move this entry to 0.1.1 and remove the current placeholder entry there.

2022-08-09 09:15 UTC, jsoriano approved these changes

2022-08-09 09:17 UTC, harnish-crest commented on packages/ibmmq/changelog.yml
>      - description: IBM MQ integration package with "qmgr" data stream
Thanks a lot for the help!

2022-08-09 09:37 UTC, merged