Fix Office 365 package configuration
elastic/integrations pull request #401
Opened 2020-11-16 14:44 UTC by adriansr

## What does this PR do?

This updates the `o365` package to `0.2.5`. Some configuration was broken, preventing it to work against o365 API.

- Re-writes and reorganizes the vars configurations.
- Split the tenant ID/name list in two separate vars (can't get YAML working).
- Fix broken agent stream.
- Made log (file) input disabled by default.
- Add docs explaining how to configure.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md#tips-for-building-integrations) and this pull request is aligned with them.
- [ ] I have verified that all datasets collect metrics or logs.

## Author's Checklist

- [ ] Review docs

## How to test this PR locally

Ask me for an o365 account for testing.
## Screenshots

<img width="1226" alt="Screen Shot 2020-11-16 at 15 33 50" src="https://user-images.githubusercontent.com/15056957/99265719-48c80800-2822-11eb-924f-592d0b238fc2.png">

<img width="818" alt="Screen Shot 2020-11-16 at 15 37 25" src="https://user-images.githubusercontent.com/15056957/99265738-5087ac80-2822-11eb-8afb-2af19127c576.png">

<img width="818" alt="Screen Shot 2020-11-16 at 15 37 48" src="https://user-images.githubusercontent.com/15056957/99265778-5da49b80-2822-11eb-849c-4284cded3212.png">

2020-11-16 15:01 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-401/detail/PR-401/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-401/detail/PR-401/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-401/detail/PR-401/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-401/detail/PR-401/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_401.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats

* Build Cause: `[Pull request #401 opened]`

* Start Time: 2020-11-16T14:44:40.900+0000

* Duration: 16 min 29 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 8  |
| Skipped      | 0 |
| Total        | 8   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY-->





<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2020-11-16 15:47 UTC, andrewkroh approved these changes
LGTM

2020-11-16 15:47 UTC, andrewkroh commented on packages/o365/data_stream/audit/agent/stream/o365audit.yml.hbs
> +            name: "{{lookup ../tenant_names @index}}"
What happens if the tenants and names are not configured in pairs? I'm just interested to know how this fails. I'm guessing it evaluates to an empty string.

2020-11-16 16:08 UTC, adriansr commented on packages/o365/data_stream/audit/agent/stream/o365audit.yml.hbs
> +            name: "{{lookup ../tenant_names @index}}"
it evaluates to an empty string.

2020-11-16 18:10 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2020-11-17 09:13 UTC, adriansr commented
jenkins, test this please

2020-11-23 08:24 UTC, mtojek requested changes
As there were incompatible changes pushed to the master branch (PR: https://github.com/elastic/integrations/pull/410), please rebase this PR against the master branch.

Long story short: `dev/import-beats-resources/o365/docs/README.md` is `packages/o365/_dev/build/docs/README.md` now.

2020-11-24 09:37 UTC, merged