Update CSP mapping fields
elastic/integrations pull request #4016
Opened 2022-08-17 12:14 UTC by olegsu

## What does this PR do?

Update the mapping CSP uses based on https://github.com/elastic/cloudbeat/pull/346

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2022-08-17 12:25 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4016/detail/PR-4016/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4016/detail/PR-4016/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4016/detail/PR-4016/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4016/detail/PR-4016/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_4016.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-08-17T12:05:03.826Z&rangeTo=2022-08-17T12:25:03.826Z&transactionName=Ingest-manager/integrations/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=3593492408ebfb3720aa691ffcbbd204&transactionId=c34b6ca0a00828dc)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-08-17T12:15:03.826+0000


* Duration: 11 min 32 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4016/detail/PR-4016/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Check integration: cloud_security_posture`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-4016/runs/1/steps/896/log/?start=0">here</a></li>
<li>Description: <code>../../build/elastic-package check -v</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-4016/runs/1/steps/932/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-08-17 13:28 UTC, eyalkraft commented
Note that the change log and the manifest must be updated as well
see for example https://github.com/elastic/integrations/commit/015e88de98c65be95c727f8046f1bd2b8e3e2385

2022-08-17 15:55 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 2.825
Classes | 100.0% (`0/0`) | :green_heart: 2.825
Methods | 25.0% (`1/4`) | :-1: -64.336
Lines | 100.0% (`0/0`) | :green_heart: 9.089
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-08-22 09:14 UTC, kfirpeled requested changes

2022-08-22 09:14 UTC, kfirpeled commented on packages/cloud_security_posture/data_stream/findings/fields/fields.yml
> +- name: event.category
please place these fields' definition in `ecs.yml`
Also, consider adding the actual type they have, otherwise it uses the default which is `keyword`.

for example: `event.created` is of type `date`

2022-09-11 07:09 UTC, olegsu commented
/test

2022-09-12 10:29 UTC, olegsu commented
/test

2022-09-13 11:42 UTC, kfirpeled approved these changes

2022-09-13 12:00 UTC, merged