[AWS] Expose default region config
elastic/integrations pull request #4158
Opened 2022-09-07 20:30 UTC by legoguy1000

## What does this PR do?

Expose default region config

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

- Relates elastic/beats#32921

## Screenshots

2022-09-07 20:34 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4158/detail/PR-4158/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4158/detail/PR-4158/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4158/detail/PR-4158/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4158/detail/PR-4158/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-09-07T20:21:13.729Z&rangeTo=2022-09-07T20:41:13.729Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=b1c72677f3541dcd46a4fbda692e90fe&transactionId=df4014ff7832f895)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-09-07T20:31:13.729+0000


* Duration: 3 min 6 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![3](https://img.shields.io/badge/3%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4158/detail/PR-4158/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Load a resource file from a library`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-4158/runs/1/steps/81/log/?start=0">here</a></li>
<li>Description: <code>approval-list/elastic/integrations.yml</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-4158/runs/1/steps/117/log/?start=0">here</a></li>

</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-4158/runs/1/steps/89/log/?start=0">here</a></li>
<li>Description: <code>githubApiCall: The REST API call https://api.github.com/orgs/elastic/members/legoguy1000 return the message : java.lang.Exception: httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/legoguy1000 : httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/legoguy1000 : Code: 404Error: {"message":"User does not exist or is not a member of the organization","documentation_url":"https://docs.github.com/rest/reference/orgs#check-organization-membership-for-a-user"}</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-09-08 02:34 UTC, aspacca commented
that's amazing @legoguy1000 , thank you very much!

I was just discussing about making this change. :)

If you don't mind I will go further and remove `endpoint` but for where `non_aws_bucket_name` is defined (it should be only in `packages/aws_logs/data_stream/generic/agent/stream/aws-s3.yml.hbs`)

2022-09-08 02:36 UTC, aspacca commented
this should be done also for:
- https://github.com/elastic/integrations/blob/main/packages/cisco_umbrella/data_stream/log/manifest.yml
- https://github.com/elastic/integrations/blob/main/packages/crowdstrike/data_stream/fdr/manifest.yml


thanks!

2022-09-08 02:36 UTC, aspacca commented
/test

2022-09-08 02:46 UTC, aspacca reviewed
missing `packages/aws/data_stream/ecs_metrics/agent/stream/stream.yml.hbs`

2022-09-08 02:46 UTC, aspacca commented on packages/aws/manifest.yml
> +    description: Default region to use prior to connecting to region specific services/endpoints. If not set, `us-east-1` is used. This needs to be set when using regions in non-regular AWS environme
```suggestion
    description: Default region to use prior to connecting to region specific services/endpoints if no AWS region is set from environment variable, credentials or instance profile. If none of the above are set and no default region is set as well, `us-east-1` is used. A region, either from environment variable, credentials or instance profile or from this default region setting, needs to be set when using regions in non-regular AWS environments such as AWS China or US Government Isolated.
```

2022-09-08 02:46 UTC, aspacca commented on packages/aws_logs/manifest.yml
> +    description: Default region to use prior to connecting to region specific services/endpoints. If not set, `us-east-1` is used. This needs to be set when using regions in non-regular AWS environme
```suggestion
    description: Default region to use prior to connecting to region specific services/endpoints if no AWS region is set from environment variable, credentials or instance profile. If none of the above are set and no default region is set as well, `us-east-1` is used. A region, either from environment variable, credentials or instance profile or from this default region setting, needs to be set when using regions in non-regular AWS environments such as AWS China or US Government Isolated.
```

2022-09-08 03:07 UTC, aspacca commented
`kibana.version` must be bumped to _at least_ `^8.0.0`

`default_region` is available since then https://github.com/elastic/beats/blob/v8.0.0/x-pack/libbeat/common/aws/credentials.go#L43

2022-09-08 03:12 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`13/13`) | :green_heart: 
Files | 92.857% (`13/14`) | :-1: -4.334
Classes | 92.857% (`13/14`) | :-1: -4.334
Methods | 84.016% (`205/244`) | :-1: -6.099
Lines | 95.697% (`5204/5438`) | :+1: 4.749
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-09-08 11:50 UTC, aspacca commented
> Do u think I should just remove `endpoint` entirely from the manifest for the AWS integration? As i went through removing endpoint from the agent configs, realized that we shouldn't need it at all in the entire AWS package.

yes, let's go for it. also in the other integrations where is not needed anymore

2022-09-14 01:48 UTC, aspacca approved these changes

2022-09-14 01:50 UTC, aspacca approved these changes

2022-09-16 19:43 UTC, legoguy1000 commented
Seems good to merge??

2022-09-19 05:50 UTC, aspacca commented
@legoguy1000 we need a final approval from @elastic/security-external-integrations

2022-09-19 05:55 UTC, aspacca requested changes

2022-09-19 05:55 UTC, aspacca commented on packages/aws_logs/manifest.yml
> +  kibana.version: ^8.0.0
when dropping previous major kibana version we need to bump the minor version of the package release (to `0.3.0` in this case): otherwise we'll loose possibility to push a bugfix for `kibana.version: ^7.16.0` on a patch release

2022-09-19 05:55 UTC, aspacca commented on packages/crowdstrike/manifest.yml
> +  kibana.version: "^8.0.0"
when dropping previous major kibana version we need to bump the minor version of the package release (to `1.7.0` in this case): otherwise we'll loose possibility to push a bugfix for `kibana.version: ^7.17.0` on a patch release

2022-09-19 06:37 UTC, efd6 approved these changes
Tentatively (and modulo the change in version number); it would be nice to have a more clear PR description with 'what' and 'why' that could be the basis of the commit message.

2022-09-19 18:33 UTC, legoguy1000 commented
@aspacca @efd6 updated.

2022-09-19 19:12 UTC, elasticmachine commented
### :rocket: Benchmarks report

#### Package `aws` :+1:(7) :green_heart:(5) :broken_heart:(1)

<details>
<summary>Expand to view</summary>

Data stream | Previous EPS | New EPS | Diff (%) | Result
----------- | ------------ | ------- | -------- | ------
`route53_resolver_logs` | 6369.43 | 4878.05 | -1491.38 (-30.57%) | :broken_heart:
</details>

#### Package `crowdstrike` :+1:(1) :green_heart:(1) :broken_heart:(0)



To see the full report comment with `/test benchmark fullreport`

<!--COMMENT_GENERATED_WITH_ID_benchmark-report.md-->

2022-09-20 03:27 UTC, aspacca approved these changes

2022-09-20 03:28 UTC, merged