Add agent.* fields to Elastic Agent ecs mapping
elastic/integrations pull request #4301
Opened 2022-09-26 10:33 UTC by AndersonQ

## What does this PR do?

Adds the `agent.*` filed to the Elastic Agent ECS mapping. The mappings are taken from [filebeat](https://github.com/elastic/beats/blob/6a669aac5d95a42b7d6bfaf13d14c79b7fc94361/libbeat/ecs/agent.go#L26).

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally

Install the Elastic Agent integration and verify the fileds `agent.*` in the `logs-*` index are indexed.

## Related issues

- Closes #4191

## Screenshots

2022-09-26 10:47 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4301/detail/PR-4301/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4301/detail/PR-4301/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4301/detail/PR-4301/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4301/detail/PR-4301/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_4301.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2022-09-26T10:23:53.446Z&rangeTo=2022-09-26T10:43:53.446Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=c169ac27b56b3d73cdb619e88992dbe4&transactionId=25f46aead0072aaa)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-09-26T10:33:53.446+0000


* Duration: 14 min 55 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 32  |
| Skipped      | 0 |
| Total        | 32   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-09-26 10:48 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 2.582
Classes | 100.0% (`0/0`) | :green_heart: 2.582
Methods | 33.333% (`22/66`) | :-1: -56.605
Lines | 100.0% (`0/0`) | :green_heart: 8.635
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-09-27 03:40 UTC, leehinman requested changes
It isn't best practice to copy all the field definitions by hand anymore.  You can use references so that every integration has the same definitions (description, example, type etc.)

you will need a `packages/elastic_agent/_dev/build/build.yml` file with the following:

```
dependencies:
  ecs:
    reference: git@v8.4.0-rc1
```

The reference can be any released ECS git tag

Then in the `ecs.yml` file you would have entries like:

```
- name: agent.id
  external: ecs
- name: agent.name
  external: ecs
```

2022-10-20 14:40 UTC, leehinman approved these changes
LGTM

2022-10-24 18:04 UTC, cmacknz approved these changes

2022-10-27 14:43 UTC, merged