[GCP] Add redis data stream
elastic/integrations pull request #4325
Opened 2022-09-27 15:32 UTC by gpop63

## What does this PR do?

Adds `redis` data stream.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

- Closes #4293 

## Screenshots

2022-09-27 15:54 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4325/detail/PR-4325/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4325/detail/PR-4325/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4325/detail/PR-4325/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4325/detail/PR-4325/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_4325.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2022-09-27T15:23:00.816Z&rangeTo=2022-09-27T15:43:00.816Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=08eed873a295b029fab098b219ba97c3&transactionId=a367123b5b5ec1c5)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-09-27T15:33:00.816+0000


* Duration: 21 min 58 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 84  |
| Skipped      | 0 |
| Total        | 84   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-09-27 15:54 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`5/5`) | :green_heart: 
Files | 100.0% (`5/5`) | :green_heart: 2.688
Classes | 100.0% (`5/5`) | :green_heart: 2.688
Methods | 90.099% (`91/101`) | :-1: -0.199
Lines | 95.752% (`1375/1436`) | :+1: 4.367
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-09-28 15:12 UTC, endorama requested changes

2022-09-28 15:12 UTC, endorama commented on packages/gcp/changelog.yml
> +- version: "2.12.6"
```suggestion
- version: "2.12.0"
```

2022-09-28 15:12 UTC, endorama commented on packages/gcp/data_stream/redis/elasticsearch/ingest_pipeline/default.yml
> +processors:
All the fields here should have proper suffixes, like mentioned in https://www.elastic.co/guide/en/beats/devguide/current/event-conventions.html

2022-09-28 15:12 UTC, endorama commented on packages/gcp/data_stream/redis/fields/fields.yml
> +  fields:
Please add `unit`, `metric_type` and `dimension` where appropriate (see https://github.com/elastic/integrations/issues/4099 for more details)

2022-09-28 15:12 UTC, endorama commented on packages/gcp/manifest.yml
> +version: "2.12.6"
```suggestion
version: "2.12.0"
```

2022-09-29 09:23 UTC, endorama commented
@gpop63 please fix the CI (needs a `build`)

2022-09-29 09:29 UTC, endorama approved these changes
Apart from the red CI looks good to me!

2022-10-05 08:36 UTC, endorama commented
/test

2022-10-05 09:38 UTC, gpop63 commented
Tested data stream with new field units etc and works as expected.

2022-10-05 13:11 UTC, merged

2022-10-06 00:20 UTC, efd6 commented on packages/gcp/data_stream/redis/fields/agent.yml
> +  type: group
Some of these fields are duplicates of fields that are defined in ecs.yml.