docs: add eks auth
elastic/integrations pull request #4332
Opened 2022-09-28 11:11 UTC by olegsu

## What does this PR do?
Document the options for cloudbeat the authenticate when running in EKS cluster.

This will close https://github.com/elastic/cloudbeat/issues/403

2022-09-28 11:14 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4332/detail/PR-4332/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4332/detail/PR-4332/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4332/detail/PR-4332/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4332/detail/PR-4332/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://null_4332.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2022-09-28T11:01:31.719Z&rangeTo=2022-09-28T11:21:31.719Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=d1ce9bcde953f0dfb071dc0ad0b5a619&transactionId=fa72806f2971e990)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-09-28T11:11:31.719+0000


* Duration: 3 min 47 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![3](https://img.shields.io/badge/3%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4332/detail/PR-4332/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Check out from version control`
<ul>
<li>Took 0 min 18 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-4332/runs/1/steps/10/log/?start=0">here</a></li>
<li>Description: <code>[2022-09-28T11:13:06.536Z] The recommended git tool is: git
[2022-09-28T11:13:13.573Z] using creden</code></l1>
</ul>
  
  
  
  
##### `Check out from version control`
<ul>
<li>Took 0 min 11 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-4332/runs/1/steps/14/log/?start=0">here</a></li>
<li>Description: <code>[2022-09-28T11:13:34.962Z] The recommended git tool is: git
[2022-09-28T11:13:34.974Z] using creden</code></l1>
</ul>
  
  
  
  
##### `Check out from version control`
<ul>
<li>Took 0 min 11 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-4332/runs/1/steps/18/log/?start=0">here</a></li>
<li>Description: <code>[2022-09-28T11:13:55.771Z] The recommended git tool is: git
[2022-09-28T11:13:55.784Z] using creden</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-09-28 15:21 UTC, kfirpeled commented
@tinnytintin10 can you review this one?

2022-10-02 13:41 UTC, oren-zohar commented
/test

2022-10-04 23:24 UTC, tinnytintin10 requested changes
@olegsu I removed the kustomize example you used out of the readme. We'll cover it in the getting started guide of our docs.

2022-10-04 23:24 UTC, tinnytintin10 commented on packages/cloud_security_posture/docs/README.md
> +To assume a different role, make sure that the target role has a `trusted-entity`
@olegsu as far as i am aware, if the user only provides an ARN role we won't be able to do anything with it since we won't have anything to assume that role with. It's my understanding that this information needs to be provided with the shared credential file and profile name. Does this line up with your thinking? 

So is this section just helping users understand that if they want to use a different role than otherwise specified in the section of the profile they want to use (~/.aws/config) make sure that the target role has a trusted entity? 

```
[profile cspadmin]
role_arn = arn:aws:iam::123456789012:role/cspadmin
source_profile = default 
```

2022-10-04 23:24 UTC, tinnytintin10 commented on packages/cloud_security_posture/docs/README.md
> +2. In case the file has multiple profiles or the profile is not `default` specify the profile name in "Credential Profile Name" field.
@olegsu users can also optionally provide the ARN of the role they'd like to use, right?

2022-10-04 23:24 UTC, tinnytintin10 commented on packages/cloud_security_posture/docs/README.md
> +### Example with Kustomize
@olegsu just to be clear this option just makes sure that the shared credential file is mounted and accessible wherever cloudbeat will be running, right?

2022-10-04 23:24 UTC, tinnytintin10 commented on packages/cloud_security_posture/docs/README.md
>  Note, this integration can only be added to Elastic agents with versions 8.4 or higher.
Let's update the agent version from 8.4 to 8.5

2022-10-05 23:21 UTC, tinnytintin10 commented
@benironside can you please read through the readme here and provide feedback? The goal here is not to include an in-depth getting started guide but instead to point them to the docs that we're updating.

2022-10-05 23:23 UTC, tinnytintin10 commented
@olegsu I left the kustomize example you used out of the readme but we'll cover it in the getting started section of our docs.

2022-10-10 17:52 UTC, benironside reviewed
Looks great overall, left some suggestions for your consideration, I hope they're helpful.

2022-10-10 17:52 UTC, benironside commented on packages/cloud_security_posture/docs/README.md
> +For in-depth, step-by-step, instructions to help you get started with KSPM, please read through [our getting started guide](https://ela.st/getting-started-with-kspm).
this looks good — we'll need to remember to update the shortened link once the 8.5 docs are live.

2022-10-10 17:52 UTC, benironside commented on packages/cloud_security_posture/docs/README.md
> +Then, use the response to provide the following options to the KSPM integration:
```suggestion
Then, use the response to provide the following information to the KSPM integration:
```

2022-10-10 17:52 UTC, benironside commented on packages/cloud_security_posture/docs/README.md
> +Because temporary security credentials are short term, after they expire, you will need
```suggestion
Because temporary security credentials are short term, after they expire you will need
```

2022-10-10 17:52 UTC, benironside commented on packages/cloud_security_posture/docs/README.md
> +you will provide two options to look up the access keys in the shared credentials file:
```suggestion
you will provide the following values to reference the access keys in the shared credentials file:
```

2022-10-10 17:52 UTC, benironside commented on packages/cloud_security_posture/docs/README.md
> +**Note**: If you don't provide values for all keys, the integration will use defaults:
```suggestion
**Note**: If you don't provide values for all keys, the integration will use these defaults:
```

2022-10-10 17:52 UTC, benironside commented on packages/cloud_security_posture/docs/README.md
> +  - For Linux, or Unix, the shared credentials file is located at `~/.aws/credentials`.
```suggestion
  - For Linux or Unix, the shared credentials file is located at `~/.aws/credentials`.
```

2022-10-10 17:52 UTC, benironside commented on packages/cloud_security_posture/docs/README.md
> +An IAM role ARN is an IAM identity that you can create in your AWS account. You determine what the role has permission to do.
```suggestion
An IAM role ARN is an IAM identity that you can create in your AWS account. You define the role's permissions.
```

2022-10-10 17:52 UTC, benironside commented on packages/cloud_security_posture/docs/README.md
> +IAM role ARN can be used to specify which AWS IAM role to assume to generate temporary credentials.
```suggestion
An IAM role's ARN can be used to specify which AWS IAM role to use to generate temporary credentials.
```

2022-10-10 17:52 UTC, benironside commented on packages/cloud_security_posture/docs/README.md
> +To use an IAM role ARN, you need to provide either a [credential profile](#use-a-shared-credentials-file) or
```suggestion
To use an IAM role's ARN, you need to provide either a [credential profile](#use-a-shared-credentials-file) or
```

2022-10-10 17:52 UTC, benironside commented on packages/cloud_security_posture/docs/README.md
> +`role_arn` is used to specify which AWS IAM role to assume for generating temporary credentials.
```suggestion
`role_arn` is used to specify which AWS IAM role to use for generating temporary credentials.
```

2022-10-10 17:52 UTC, benironside commented on packages/cloud_security_posture/docs/README.md
> +Specific AWS permissions are required for an IAM user to make specific AWS API calls.
```suggestion
Specific AWS permissions are required for an IAM user to make the necessary AWS API calls.
```

2022-10-10 17:52 UTC, benironside commented on packages/cloud_security_posture/docs/README.md
> +To enable the KSPM integration to collect metrics and logs from all necssary services,
```suggestion
To enable the KSPM integration to collect metrics and logs from all necessary services,
```

2022-10-10 17:52 UTC, benironside commented on packages/cloud_security_posture/docs/README.md
> +make sure these permissions are given:
```suggestion
make sure to grant the following permissions:
```

2022-10-10 23:29 UTC, benironside reviewed
Left one more comment

2022-10-10 23:29 UTC, benironside commented on packages/cloud_security_posture/docs/README.md
> +For more details see [Create Shared Credentials File](https://docs.aws.amazon.com/sdkref/latest/guide/file-format.html#file-format-creds)
```suggestion
For more details refer to [Create Shared Credentials File](https://docs.aws.amazon.com/sdkref/latest/guide/file-format.html#file-format-creds)
```
we don't use "see" because it's not inclusive language from an accessibility perspective. Please replace it with "refer to" throughout.

2022-10-11 00:32 UTC, benironside reviewed
More comments

2022-10-12 19:38 UTC, tinnytintin10 commented on packages/cloud_security_posture/docs/README.md
> +`role_arn` is used to specify which AWS IAM role to assume for generating temporary credentials.
@benironside, the correct term here is assume. Checkout  :https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html

2022-10-12 19:39 UTC, tinnytintin10 commented on packages/cloud_security_posture/docs/README.md
> +To enable the KSPM integration to collect metrics and logs from all necssary services,
I need to remove the `metrics` and `logs` from this readme, and then I will update the spelling

2022-10-12 20:37 UTC, tinnytintin10 commented
@oren-zohar @olegsu can y'all review the "Requirments" section of the read me for accuracy?

@benironside I made some final updates to the top of the issue- can you review it one last time? 

Thanks all!

2022-10-13 10:01 UTC, olegsu commented on packages/cloud_security_posture/docs/README.md
> +**Note**: If you don't provide values for all keys, the integration will use these defaults:
The integration will use the ec2 attached role if nothing is provided

2022-10-13 10:04 UTC, olegsu reviewed
Few notes about the default attached role

2022-10-13 20:26 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 2.703
Classes | 100.0% (`0/0`) | :green_heart: 2.703
Methods | 25.0% (`1/4`) | :-1: -64.742
Lines | 100.0% (`0/0`) | :green_heart: 8.429
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-10-13 20:26 UTC, tinnytintin10 approved these changes

2022-10-14 14:29 UTC, benironside reviewed
A few minor revisions

2022-10-14 14:29 UTC, benironside commented on packages/cloud_security_posture/docs/README.md
> +The Kubernetes Security Posture Management (KSPM) integration allows you to identify and remediate configuration risks in the various components that make up your Kubernetes cluster. It does this by
```suggestion
The Kubernetes Security Posture Management (KSPM) integration allows you to identify and remediate configuration risks in the various components that make up your Kubernetes cluster. It does this by evaluating the various components of your cluster against secure configuration guidelines, as defined by the Center for Internet Security (CIS), in order to identify configuration risks. When configuration risks are discovered, [findings](https://ela.st/findings-8-5) are generated that tell you exactly what is misconfigured and how you can remediate it. Please read through the [KSPM documentation](https://ela.st/kspm) for an overview of KSPM. 
```

2022-10-14 14:29 UTC, benironside commented on packages/cloud_security_posture/docs/README.md
> +After the installation of this integration, the pages described in the table below will begin to get populated with security posture data. Please read the ["Use Cases"](https://ela.st/kspm-use-cases-
```suggestion
After you install this integration, the pages described in the table below will begin to get populated with security posture data. Please read the ["Use Cases"](https://ela.st/kspm-use-cases-8-5) section of the KSPM documentation for step-by-step instructions on how to use these pages to get insight into and improve the security posture of your Kubernetes clusters. 
```

2022-10-14 14:29 UTC, benironside commented on packages/cloud_security_posture/docs/README.md
> +| Posture Dashboard | The posture dashboard provides an overview of the security posture of all Kubernetes clusters monitored. You can access the posture dashboard via the dashboards section of the s
Is this the right link? It's the same as for the next item in this table.

2022-10-14 17:38 UTC, tinnytintin10 commented on packages/cloud_security_posture/docs/README.md
> +| Posture Dashboard | The posture dashboard provides an overview of the security posture of all Kubernetes clusters monitored. You can access the posture dashboard via the dashboards section of the s
just updated the links

2022-10-14 17:40 UTC, tinnytintin10 commented
> A few minor revisions

Thanks, @benironside! I have applied your suggestion.

2022-10-14 20:41 UTC, oren-zohar approved these changes

2022-10-18 07:32 UTC, merged