Add new cluster name to ecs schema
elastic/integrations pull request #4454
Opened 2022-10-12 19:10 UTC by ofiriro3

## What does this PR do?
This PR adds the `orchestrator.cluster.name` field to the ECS schema and enables the new Cloudbeat processor so Cloudbeat will fetch the cluster name along with each finding.
This version will only support Kubernetes Vanilla, we will add support in EKS in a different PR.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Relates [#123](https://github.com/elastic/cloudbeat/pull/455)
- Implements https://github.com/elastic/cloudbeat/issues/391

2022-10-12 19:25 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4454/detail/PR-4454/2//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4454/detail/PR-4454/2//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4454/detail/PR-4454/2//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4454/detail/PR-4454/2//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_4454.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2022-10-12T19:01:30.341Z&rangeTo=2022-10-12T19:21:30.341Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=02c56eb1a9fda153c47eed128d68cc38&transactionId=05e400a63fb21ed6)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-10-12T19:11:30.341+0000


* Duration: 14 min 13 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 2  |
| Skipped      | 0 |
| Total        | 2   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-10-12 19:25 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 2.496
Classes | 100.0% (`0/0`) | :green_heart: 2.496
Methods | 25.0% (`1/4`) | :-1: -65.334
Lines | 100.0% (`0/0`) | :green_heart: 8.36
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-10-18 19:15 UTC, kfirpeled requested changes

2022-10-18 19:15 UTC, kfirpeled commented on packages/cloud_security_posture/data_stream/findings/agent/stream/vanilla.yml.hbs
> +  - add_environment_metadata: ~
isn't the processor name been changed? `add_orchestrator_metadata`

2022-10-18 19:16 UTC, kfirpeled commented on packages/cloud_security_posture/data_stream/findings/agent/stream/vanilla.yml.hbs
> +  - add_environment_metadata: ~
another question, why don't we use the same processor for eks as well?

2022-10-18 19:17 UTC, kfirpeled commented on packages/cloud_security_posture/changelog.yml
> +  - description: Add cluster name to the ecs schema and enabling the relevant processor in the eks hbs file.
the description points to eks hbs file but the change was in vanilla hbs file.

2022-10-19 10:49 UTC, ChrsMark approved these changes
lgtm

2022-10-19 16:45 UTC, kfirpeled approved these changes
lgtm

2022-10-19 16:46 UTC, kfirpeled commented on packages/cloud_security_posture/changelog.yml
> +  - description: Add cluster name to the ecs schema.
nit: I think a clearer description would be, `Added ecs mapping to orchastrator.cluster.name`

2022-10-20 07:35 UTC, ofiriro3 commented on packages/cloud_security_posture/changelog.yml
> +  - description: Add cluster name to the ecs schema.
NP

2022-10-20 12:25 UTC, merged