[Citrix ADC] Add Integration Package with VPN Data Stream
elastic/integrations pull request #4473
Opened 2022-10-19 10:32 UTC by harnish-crest

- Enhancement

## What does this PR do?

- Added 1 data stream (vpn metrics).
- Added data collection logic for the data streams.
- Added the ingest pipeline for the data streams.
- Mapped fields according to the ECS schema and added Fields metadata in the appropriate yaml files.
- Added dashboards and visualizations.
- Added system test cases for the data stream.

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's changelog.yml file.
- [X] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally

- Clone integrations repo.
- Install elastic-package locally.
- Start elastic stack using elastic-package.
- Move to integrations/packages/citrix_adc directory.
- Run the following command to run tests.
elastic-package test

## Related issues

- Relates #3746 
- Relates #4322
- Relates #4364
- Relates #4418
- Relates #4458  

## Screenshots
![citrix_adc-vpn-dashboard](https://user-images.githubusercontent.com/102945525/196667446-607d3d3a-88ce-4f2b-aa74-b081ccc7a5f6.png)

2022-10-19 10:34 UTC, kush-elastic commented
/test

2022-10-19 10:35 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4473/detail/PR-4473/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4473/detail/PR-4473/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4473/detail/PR-4473/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4473/detail/PR-4473/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2022-10-19T10:22:35.860Z&rangeTo=2022-10-19T10:42:35.860Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=db02ce4e300001ea98ea69d877ae7e29&transactionId=1f5ab7c4ec34a15e)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-10-19T10:32:35.860+0000


* Duration: 3 min 59 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![3](https://img.shields.io/badge/3%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4473/detail/PR-4473/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Load a resource file from a library`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-4473/runs/1/steps/81/log/?start=0">here</a></li>
<li>Description: <code>approval-list/elastic/integrations.yml</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-4473/runs/1/steps/117/log/?start=0">here</a></li>

</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-4473/runs/1/steps/89/log/?start=0">here</a></li>
<li>Description: <code>githubApiCall: The REST API call https://api.github.com/orgs/elastic/members/harnish-crest return the message : java.lang.Exception: httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/harnish-crest : httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/harnish-crest : Code: 404Error: {"message":"User does not exist or is not a member of the organization","documentation_url":"https://docs.github.com/rest/reference/orgs#check-organization-membership-for-a-user"}</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-10-19 10:49 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`

<!--COMMENT_GENERATED_WITH_ID_benchmark-report.md-->

2022-10-19 10:50 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`1/1`) | :green_heart: 
Files | 100.0% (`1/1`) | :green_heart: 2.712
Classes | 100.0% (`1/1`) | :green_heart: 2.712
Methods | 100.0% (`9/9`) | :green_heart: 10.01
Lines | 98.214% (`275/280`) | :+1: 6.65
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-11-08 07:18 UTC, kush-elastic requested changes
Add the dashboard screenshot in view mode rather than adding it in edit mode.

2022-11-08 12:59 UTC, kush-elastic approved these changes
LGTM!

2022-12-14 12:45 UTC, harnish-crest commented on packages/citrix_adc/data_stream/vpn/fields/fields.yml
> +              metric_type: counter
@muthu-mps seems like these fields should be counter. Also here is the official document which shows both fields `metric_type` is  `counter`. 

`client_server.request.hit.count`: https://support.citrix.com/article/CTX133884/citrix-adc-sslvpn-counters#:~:text=Number%20of%20client%20configuration%20requests%20received%20by%20VPN%20server

`configuration_request_served.count`: https://support.citrix.com/article/CTX133884/citrix-adc-sslvpn-counters#:~:text=Number%20of%20client%20configuration%20requests%20received%20by%20VPN%20server

2022-12-14 15:03 UTC, muthu-mps commented on packages/citrix_adc/data_stream/vpn/fields/fields.yml
> +              metric_type: counter
The counters which you refer here is something which captures all the response fields and its different from what we consider as metric_type. The metric_type `gauge` is a single-valued metric which goes up and down. Ex: temperature. The metric_type: `counter` is a cumulative type which only goes up. Ex: Number of requests processed by web server.
I would recommend you to revisit the metric_type for all the fields and make changes wherever applicable.

2022-12-15 05:37 UTC, harnish-crest commented on packages/citrix_adc/data_stream/vpn/fields/fields.yml
> +              metric_type: counter
For the `client_server.request.hit.count` it could be `gauge`. So we can update it as per your suggestions. But for the `configuration_request_served.count`, it seems like a counter as per your example. Also as per our understanding, it aligns more with the counter. But let me know if you still want to change it to counter, we'll change it for this field too.

2022-12-15 05:53 UTC, muthu-mps commented on packages/citrix_adc/data_stream/vpn/fields/fields.yml
> +              metric_type: counter
I would recommend to keep both as gauge values.

2022-12-15 05:56 UTC, muthu-mps commented
@SubhrataK - Please take a look into the changes.

2022-12-19 09:14 UTC, SubhrataK approved these changes

2022-12-20 09:51 UTC, merged

2022-12-20 10:13 UTC, elasticmachine commented
Package citrix_adc - 0.5.0 containing this change is available at https://epr.elastic.co/search?package=citrix_adc