Data Exfiltration Detection (DED) integration package
elastic/integrations pull request #4486
Opened 2022-10-20 15:21 UTC by OMirzaei

## What does this PR do?

This PR contains the assets of the data exfiltration detection integration package. 

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues and docs

https://github.com/elastic/security-team/issues/4606
https://github.com/elastic/security-team/issues/5155
https://docs.google.com/document/d/15k-Jm0AzR34SDTlpgw0A16pKygT5v-ZhdN9TWV4nSv8/edit?usp=sharing
https://docs.google.com/document/d/1qgAulPDzJBoimSxRCvszQH2N-ZwoG9WKv6QI4_tGCvE/edit?usp=sharing

## Screenshots

2022-10-20 15:27 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4486/detail/PR-4486/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4486/detail/PR-4486/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4486/detail/PR-4486/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4486/detail/PR-4486/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_4486.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2022-10-20T15:12:12.627Z&rangeTo=2022-10-20T15:32:12.627Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=48630ba1fcdb3f62b3c1ab4fb8df69e7&transactionId=0a7fa839e21f68ef)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-10-20T15:22:12.627+0000


* Duration: 6 min 42 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4486/detail/PR-4486/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Checks and builds Go sources`
<ul>
<li>Took 0 min 26 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-4486/runs/1/steps/140/log/?start=0">here</a></li>
<li>Description: <code>mage -debug check</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-4486/runs/1/steps/157/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-10-20 19:02 UTC, OMirzaei commented
/test

2022-10-24 19:37 UTC, szeitlin reviewed
Should each of these be called `machine learning job` or `anomaly detection job`? I still find our use of `machine learning job` to be maybe too broad. 

@OMirzaei what else needs to happen before this can get merged? Is this the last step?

2022-10-24 19:37 UTC, szeitlin commented on packages/ded/docs/README.md
> +| high-sent-bytes-destination-geo-city_name | Explain what it does here! |
Looks like you probably need to fill in the `Explain what it does here!` part?

2022-10-25 20:08 UTC, OMirzaei commented on packages/ded/docs/README.md
> +| high-sent-bytes-destination-geo-city_name | Explain what it does here! |
Good point! I forgot to add those explanations. I think we can merge at this stage. The remaining steps are related to publishing.

2022-10-25 20:39 UTC, szeitlin commented on packages/ded/docs/README.md
> +| high-sent-bytes-destination-geo-city_name | Explain what it does here! |
@OMirzaei I'm not sure what you mean re: "related to publishing". Do you mean the docs team does that separately-?

2022-10-26 22:32 UTC, OMirzaei commented on packages/ded/docs/README.md
> +| high-sent-bytes-destination-geo-city_name | Explain what it does here! |
After the testing phase and once this PR is merged, we can proceed to the publishing phase ([see the doc here](https://docs.google.com/document/d/1Z01Ga2VuHuofhf9y26q7UJJRcTrXOVSr4ZlSpbF-lHE/edit?usp=sharing)). I believe this has to be done by myself but I'll double check w/ @ajosh0504 to make sure.

2022-10-31 17:30 UTC, szeitlin approved these changes

2022-10-31 17:56 UTC, ajosh0504 requested changes
Looking great 🥳  

Left some (mostly repetitive) comments that should be easy and quick enough to fix.

2022-10-31 17:56 UTC, ajosh0504 commented on packages/ded/docs/README.md
> +Follow these instructions to ingest data with the ingest pipeline and enrich your indices with inference data. Then use these detection rules and anomaly detection jobs for data exfiltration detectio
You don't have an ingest pipeline or a supervised ML model. I suggest going through these steps and getting rid of whatever doesn't apply to your package.

2022-10-31 17:56 UTC, ajosh0504 commented on packages/ded/kibana/ml_module/ded-ml.json
> +        "query": {
Could you paste a screenshot that shows that this query makes the job module appear automatically?

2022-10-31 17:56 UTC, ajosh0504 commented on packages/ded/kibana/ml_module/ded-ml.json
> +                    "groups": [
Please add the appropriate EA tags here and remove any unnecessary tags.

2022-10-31 17:56 UTC, ajosh0504 commented on packages/ded/kibana/ml_module/ded-ml.json
> +                    "groups": [
Please add the appropriate EA tags here and remove any unnecessary tags.

2022-10-31 17:56 UTC, ajosh0504 commented on packages/ded/kibana/ml_module/ded-ml.json
> +                    "groups": [
Please add the appropriate EA tags here and remove any unnecessary tags.

2022-10-31 17:56 UTC, ajosh0504 commented on packages/ded/kibana/ml_module/ded-ml.json
> +                    "groups": [
Please add the appropriate EA tags here and remove any unnecessary tags.

2022-10-31 17:56 UTC, ajosh0504 commented on packages/ded/kibana/ml_module/ded-ml.json
> +                    "groups": [
Please add the appropriate EA tags here and remove any unnecessary tags.

2022-10-31 17:56 UTC, ajosh0504 commented on packages/ded/kibana/ml_module/ded-ml.json
> +                    "groups": [
Please add the appropriate EA tags here and remove any unnecessary tags.

2022-10-31 17:56 UTC, ajosh0504 commented on packages/ded/kibana/ml_module/ded-ml.json
> +                        "security",
Please add the appropriate EA tags here and remove any unnecessary tags.

2022-10-31 17:56 UTC, ajosh0504 commented on packages/ded/kibana/ml_module/ded-ml.json
> +                    "groups": [
Please add the appropriate EA tags here and remove any unnecessary tags.

2022-10-31 17:56 UTC, ajosh0504 commented on packages/ded/kibana/ml_module/ded-ml.json
> +                    "query": {
You probably want the `exists` clauses from the main query here as well?

2022-10-31 17:56 UTC, ajosh0504 commented on packages/ded/kibana/ml_module/ded-ml.json
> +                    "query": {
You probably want the `exists` clauses from the main query here as well?

2022-10-31 17:56 UTC, ajosh0504 commented on packages/ded/kibana/ml_module/ded-ml.json
> +                    "query": {
You probably want the `exists` clauses from the main query here as well?

2022-10-31 17:56 UTC, ajosh0504 commented on packages/ded/kibana/ml_module/ded-ml.json
> +                    "query": {
You probably want the `exists` clauses from the main query here as well?

2022-10-31 17:56 UTC, ajosh0504 commented on packages/ded/kibana/ml_module/ded-ml.json
> +                    "query": {
You probably want the `exists` clauses from the main query here as well?

2022-10-31 17:56 UTC, ajosh0504 commented on packages/ded/kibana/ml_module/ded-ml.json
> +                    "query": {
You probably want the `exists` clauses from the main query here as well?

2022-10-31 17:56 UTC, ajosh0504 commented on packages/ded/kibana/ml_module/ded-ml.json
> +                    "query": {
You probably want the `exists` clauses from the main query here as well?

2022-10-31 17:56 UTC, ajosh0504 commented on packages/ded/kibana/ml_module/ded-ml.json
> +                    "query": {
You probably want the `exists` clauses from the main query here as well?

2022-10-31 17:56 UTC, ajosh0504 commented on packages/ded/kibana/security_rule/5576098d-650d-4b0f-a3a1-48b5b0ce4f15.json
> +        "name": "Potential Data Exfiltration Activity",
Rule names should ideally be unique.

2022-10-31 17:56 UTC, ajosh0504 commented on packages/ded/kibana/security_rule/68cd785b-9195-4dbb-b7d0-34e375988ad0.json
> +        "name": "Potential Data Exfiltration Activity",
Rule names should ideally be unique.

2022-10-31 17:56 UTC, ajosh0504 commented on packages/ded/kibana/security_rule/8d4e2e5f-982b-4e8d-b765-a10d648efc33.json
> +        "name": "Potential Data Exfiltration Activity",
Rule names should ideally be unique.

2022-10-31 17:56 UTC, ajosh0504 commented on packages/ded/kibana/security_rule/a3419a53-c7cb-4101-bb88-50bc8cfd4ee9.json
> +        "name": "Potential Data Exfiltration Activity",
Rule names should ideally be unique.

2022-10-31 17:56 UTC, ajosh0504 commented on packages/ded/kibana/security_rule/adafc654-fd21-4ebf-9e4e-db4f2a08efd1.json
> +        "name": "Potential Data Exfiltration Activity",
Rule names should ideally be unique.

2022-10-31 17:56 UTC, ajosh0504 commented on packages/ded/kibana/security_rule/b9d01e71-ac5d-4203-82ed-c1246d6c72c8.json
> +        "name": "Potential Data Exfiltration Activity",
Rule names should ideally be unique.

2022-10-31 17:56 UTC, ajosh0504 commented on packages/ded/kibana/security_rule/d115c2fb-1543-4a87-ad84-cec3420fee4a.json
> +        "name": "Potential Data Exfiltration Activity",
Rule names should ideally be unique.

2022-10-31 17:56 UTC, ajosh0504 commented on packages/ded/kibana/security_rule/e33267c8-20ed-4ab9-be4c-9193f20d4cba.json
> +        "name": "Potential Data Exfiltration Activity",
Rule names should ideally be unique.

2022-10-31 19:32 UTC, susan-shu-c commented on packages/ded/kibana/ml_module/ded-ml.json
> +        "query": {
Second this, I also suggest adding more information about how you tested this PR @OMirzaei as well as screenshots to help illustrate how the package is working 👍

2022-11-01 14:34 UTC, susan-shu-c commented on packages/ded/kibana/ml_module/ded-ml.json
> +        "query": {
The package showing up on the UI is important, but also could you explain the details of the testing you did after that?

So far you've only mentioned you've "done testing" but without details to help us understand yet, so that would be helpful.

2022-11-01 14:42 UTC, OMirzaei commented on packages/ded/kibana/ml_module/ded-ml.json
> +        "query": {
> I mean that after installing it locally, is it doing what it's intending to do? Such as, if applicable, writing data from the correct places?

Can you elaborate more on this? Didn't get what you meant by "writing data from correct places".

By testing, I meant all steps that were required to test the package ([according to the doc](https://docs.google.com/document/d/1Z01Ga2VuHuofhf9y26q7UJJRcTrXOVSr4ZlSpbF-lHE/edit?usp=sharing)). The tests were performed before testing the package. Some screenshots are included in the package. I can refer you to the dashboard if you want to have a closer look.

2022-11-01 15:11 UTC, ajosh0504 requested changes
Requested some tag updates in rules.

2022-11-01 15:11 UTC, ajosh0504 commented on packages/ded/kibana/security_rule/5576098d-650d-4b0f-a3a1-48b5b0ce4f15.json
> +            "Elastic",
Remove "ML" and replace with the entity (host/user) that's most relevant for this rule.

2022-11-01 15:11 UTC, ajosh0504 commented on packages/ded/kibana/security_rule/68cd785b-9195-4dbb-b7d0-34e375988ad0.json
> +        "tags": [
Remove "ML" and replace with the entity (host/user) that's most relevant for this rule.

2022-11-01 15:11 UTC, ajosh0504 commented on packages/ded/kibana/security_rule/8d4e2e5f-982b-4e8d-b765-a10d648efc33.json
> +        "tags": [
Remove "ML" and replace with the entity (host/user) that's most relevant for this rule.

2022-11-01 15:11 UTC, ajosh0504 commented on packages/ded/kibana/security_rule/a3419a53-c7cb-4101-bb88-50bc8cfd4ee9.json
> +        "tags": [
Remove "ML" and replace with the entity (host/user) that's most relevant for this rule.

2022-11-01 17:08 UTC, OMirzaei commented on packages/ded/kibana/security_rule/5576098d-650d-4b0f-a3a1-48b5b0ce4f15.json
> +            "Elastic",
Thank you!

2022-11-01 18:13 UTC, OMirzaei commented on packages/ded/docs/README.md
> +Follow these instructions to ingest data with the ingest pipeline and enrich your indices with inference data. Then use these detection rules and anomaly detection jobs for data exfiltration detectio
Thanks @ajosh0504! I revised the README file.

2022-11-02 16:43 UTC, ajosh0504 commented on packages/ded/docs/README.md
> +Create a data view for the indices that are enriched by the pipeline.
I think you can remove this line.

2022-11-02 16:43 UTC, ajosh0504 commented on packages/ded/docs/README.md
> +| DED activity detection to an unusal city | An anomaly detection job has detected an abnormal volume of bytes being sent to an unusual city.|
The "Rule" should typically match the exact rule name. I like the names you've used in your rule files...like "Potential Data Exfiltration Activity to an Unusual Country" etc.

2022-11-02 16:43 UTC, ajosh0504 commented on packages/ded/kibana/security_rule/5576098d-650d-4b0f-a3a1-48b5b0ce4f15.json
> +        "name": "Potential Data Exfiltration Activity (high sent bytes to an unusual region name)",
Considering changing to something like "Potential Data Exfiltration Activity to an Unusual Region".

2022-11-02 16:43 UTC, ajosh0504 commented on packages/ded/kibana/security_rule/68cd785b-9195-4dbb-b7d0-34e375988ad0.json
> +        "name": "Potential Data Exfiltration Activity (high sent bytes to an unusual country)",
Considering changing to something like "Potential Data Exfiltration Activity to an Unusual Country".

2022-11-02 16:43 UTC, ajosh0504 commented on packages/ded/kibana/security_rule/8d4e2e5f-982b-4e8d-b765-a10d648efc33.json
> +        "name": "Potential Data Exfiltration Activity (high sent bytes to an unusual country by its iso code)",
Considering changing to something like "Potential Data Exfiltration Activity to an Unusual ISO Code".

2022-11-02 16:43 UTC, ajosh0504 commented on packages/ded/kibana/security_rule/a3419a53-c7cb-4101-bb88-50bc8cfd4ee9.json
> +        "name": "Potential Data Exfiltration Activity (high sent bytes to an unusual city)",
Considering changing to something like "Potential Data Exfiltration Activity to an Unusual City".

2022-11-02 16:43 UTC, ajosh0504 commented on packages/ded/kibana/security_rule/adafc654-fd21-4ebf-9e4e-db4f2a08efd1.json
> +        "name": "Potential Data Exfiltration Activity (high sent bytes to an unusual destination port)",
Considering changing to something like "Potential Data Exfiltration Activity to an Unusual Destination Port".

2022-11-02 16:43 UTC, ajosh0504 commented on packages/ded/kibana/security_rule/b9d01e71-ac5d-4203-82ed-c1246d6c72c8.json
> +        "name": "Potential Data Exfiltration Activity (high sent bytes to an unusual IP address)",
Considering changing to something like "Potential Data Exfiltration Activity to an Unusual IP Address".

2022-11-02 16:43 UTC, ajosh0504 commented on packages/ded/kibana/security_rule/d115c2fb-1543-4a87-ad84-cec3420fee4a.json
> +        "name": "Potential Data Exfiltration Activity (high sent bytes to an unusual timezone)",
Considering changing to something like "Potential Data Exfiltration Activity to an Unusual Timezone".

2022-11-02 16:43 UTC, ajosh0504 commented on packages/ded/kibana/security_rule/e33267c8-20ed-4ab9-be4c-9193f20d4cba.json
> +        "name": "Potential Data Exfiltration Activity (high sent bytes to an unusual continent)",
Considering changing to something like "Potential Data Exfiltration Activity to an Unusual Continent".

2022-11-02 16:58 UTC, susan-shu-c commented on packages/ded/kibana/ml_module/ded-ml.json
> +        "query": {
Thanks for addressing this today and sharing the dashboard 👍

2022-11-02 17:00 UTC, susan-shu-c commented on packages/ded/docs/README.md
> +In order to maximize the benefit of the DED detection framework, you might consider activating detection rules that are triggered when certain conditions for the anomaly detection jobs are satisfied.
Might be useful to add a little more detail here for people activating detection rules for the first time - e.g., link to an Elastic site documentation

2022-11-02 17:28 UTC, ajosh0504 approved these changes
Wooooo! LGTM! 🚢

2022-11-02 17:53 UTC, susan-shu-c approved these changes
Thanks for adding context and addressing comments 😁

2022-11-02 19:25 UTC, merged