[AWS] Add support for Inspector datastream and Remove duplicate ECS fields
elastic/integrations pull request #4604
Opened 2022-11-09 13:25 UTC by vinit-elastic

## What does this PR do?

- Added a data stream.
- Added data collection logic to the data stream.
- Added the ingest pipeline for the data stream.
- Mapped fields according to the ECS schema and added Fields metadata in the appropriate yml files
- Added dashboards and visualizations.
- Added test for pipeline for the data stream.
- Added system test cases for the data stream.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] If I'm introducing a new feature, I have modified the Kibana version constraint in my package's `manifest.yml` file to point to the latest Elastic stack release (e.g. `^8.4.0`).

## How to test this PR locally

- Clone integrations repo.
- Install elastic package locally.
- Start elastic stack using elastic-package.
- Move to integrations/packages/aws/data_stream directory.
- Run the following command to run tests. 
> elastic-package test 

## Related issues

- Related https://github.com/elastic/integrations/issues/4398

## Screenshots

![image](https://user-images.githubusercontent.com/89848047/200841043-67d4bfdf-9fd6-4b03-a65d-e0d64e35dcd9.png)
![image](https://user-images.githubusercontent.com/89848047/200841116-9551ac4d-f062-44b1-ba97-2110a6cbdce9.png)
![image](https://user-images.githubusercontent.com/89848047/200841183-fd8f7fd7-f9ec-4e42-8043-59b8e1257d47.png)
![image](https://user-images.githubusercontent.com/89848047/200841235-02fd181b-616e-4b70-a633-883cab0513ee.png)
![image](https://user-images.githubusercontent.com/89848047/200841298-b37bae57-b5db-4588-91c5-ccf04fc985d2.png)
![image](https://user-images.githubusercontent.com/89848047/200841398-684ced36-6a84-4bbd-8bff-9be489cd7630.png)
![image](https://user-images.githubusercontent.com/89848047/200841451-2374886f-f8fa-475f-b98b-bd2483f7d4aa.png)

2022-11-09 13:27 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2022-11-09 13:58 UTC, elasticmachine commented
### :rocket: Benchmarks report


#### Package `aws` :+1:(5) :green_heart:(8) :broken_heart:(1)
<details>
<summary>Expand to view</summary>

Data stream | Previous EPS | New EPS | Diff (%) | Result
----------- | ------------ | ------- | -------- | ------
`cloudwatch_logs` | 500000 | 250000 | -250000 (-50%) | :broken_heart:
</details>


To see the full report comment with `/test benchmark fullreport`

<!--COMMENT_GENERATED_WITH_ID_benchmark-report.md-->

2022-11-09 13:58 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`14/14`) | :green_heart: 
Files | 93.333% (`14/15`) | :-1: -4.349
Classes | 93.333% (`14/15`) | :-1: -4.349
Methods | 85.098% (`217/255`) | :-1: -5.938
Lines | 95.949% (`5897/6146`) | :+1: 4.245
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-11-09 23:39 UTC, kaiyan-sheng commented
@vinit-elastic Could we actually remove the duplicate fields from agent.yml and keep them in the ecs.yml instead? Thanks!! I just did this for the ec2 integration: https://github.com/elastic/integrations/pull/4567

2022-11-10 03:25 UTC, vinit-elastic commented
@kaiyan-sheng the reason why I removed fields from ecs.yml is because the agent.yml is a static file and is the same across all the connectors. And the same has been discussed with @P1llus earlier, therefore we didn't change it.

2022-11-10 05:57 UTC, P1llus commented
@vinit-elastic I agree, if we want to change agent.yml we should simply do it in one go for all packages instead @kaiyan-sheng ?

2022-11-10 21:46 UTC, andrewctate requested changes
Hi @vinit-elastic! I'm going to request that we use the new Lens metric vis instead of the TSVB metric on the dashboard since it's a good fit and we're trying to get away from TSVB. Here's a screenshot of how you can configure it in the Lens editor:

<img width="1131" alt="Screen Shot 2022-11-10 at 3 27 39 PM" src="https://user-images.githubusercontent.com/315764/201210676-c4fec06b-7181-4ef3-8ed8-126bc2e4f98f.png">

And a couple "softer" requests: 

1. Could you post a screenshot of this dashboard with data in it?

2. This is a big dashboard (16 visualizations). The concern with these is that they can load really slowly if the customer has a lot of data. All visualizations (including tables) (re)render every time the user navigates to the dashboard/adds a filter/changes the time range, regardless of whether or not they are above the fold. Is there a logical way it could make sense to break this up into smaller dashboards connected by hyperlinks?

2022-11-14 15:29 UTC, andrewctate approved these changes
Thanks for making the visualization type change!

2022-11-14 15:54 UTC, kaiyan-sheng commented
@vinit-elastic How about lets keep the duplicated ECS fields for now, and make a separate PR to remove all the duplicate fields from agent.yml instead?

2022-11-15 11:55 UTC, vinit-elastic commented
> @vinit-elastic How about lets keep the duplicated ECS fields for now, and make a separate PR to remove all the duplicate fields from agent.yml instead?

Hey @kaiyan-sheng, if we keep the duplicate fields as they are, then the elastic-package check command gives an error. because both files have different types of descriptions and there is a type change in the newer Stack version as well as the ECS version. The same has been discussed with @P1llus earlier and we came to a conclusion that keep agent.yml as it is and remove duplicate fields in the ECS file.

2022-11-15 15:14 UTC, kaiyan-sheng commented
@vinit-elastic OK! Thanks for the explanation. I will make a separate PR later after this one gets in to fix the agent.yml and ecs.yml then!

2022-11-15 15:14 UTC, kaiyan-sheng commented on packages/aws/manifest.yml
> +version: 1.27.0
Should we back this one to 1.26.0 for now?

2022-11-15 22:35 UTC, kaiyan-sheng commented
I made the change for removing duplicate fields from agent.yml and use ecs.yml instead in PR: https://github.com/elastic/integrations/pull/4657

2022-11-16 05:50 UTC, vinit-elastic commented
Hey @kaiyan-sheng - I saw your PR, appreciate your effort. 
However, we are doing the opposite in all the connectors. That is, we keep the agent.yml file same and remove the duplicates from ecs.yml. so that agent.yml is the same across all the integrations. So could you please do the same? Thanks!

2022-11-16 15:14 UTC, kaiyan-sheng commented
@vinit-elastic @P1llus Sorry thats the part I don't quite get. Why we are redefining ECS fields in `agent.yml` files? For example `cloud.availability_zone`. Unless we are using `cloud.availability_zone` in a different way than what ECS field defines, we should keep it in `ecs.yml` to leverage ECS as much as we can.

2022-11-17 09:07 UTC, P1llus commented
@kaiyan-sheng Its mostly because all the integrations have been setup like this as far as I know, the fields are simply copied from the other integrations.

We could change it, but I rather keep it out of this PR and do it over all integrations if you want. There is plenty of ECS fields in agent.yml from before.
I am unsure what the difference is, its still an ECS field, we are not redefining it, its simply in another file.

2022-11-17 10:45 UTC, kaiyan-sheng approved these changes
@P1llus and I had a conversation offline and decides to merge my PR for moving all fields into ecs.yml first to resolve this issue. Sorry @vinit-elastic you have to rebase your PR and sorry for blocking it for a while... The part for adding support for inspector data stream looks good to me. Thank you both!!

2022-11-17 12:34 UTC, vinit-elastic commented on packages/aws/manifest.yml
> +version: 1.27.0
Hey @kaiyan-sheng, I have raised another PR related to [AWS Dashboard](https://github.com/elastic/integrations/pull/4596). For that PR, the version was `1.26.0` so I kept version `1.27.0`

2022-11-21 09:35 UTC, merged