Lyve cloud integration
elastic/integrations pull request #4702
Opened 2022-11-23 10:43 UTC by leon-seagate

- Enhancement

## What does this PR do?

- Added new directory under packages for new cloud provider - a.k.a Seagate's Lyve Cloud.
- Added data collection logic for the data streams.
- Added the ingest pipeline for the data streams.
- Mapped fields according to the ECS schema and added Fields metadata in the appropriate yaml files.
- Added dashboards and visualizations.
- Added system test cases for the data stream.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Screenshots
![image](https://user-images.githubusercontent.com/102151302/201077017-11bbd549-c33c-498e-bea6-f07db761b837.png)

2022-11-23 10:47 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4702/detail/PR-4702/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4702/detail/PR-4702/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4702/detail/PR-4702/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4702/detail/PR-4702/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2022-11-23T10:33:51.908Z&rangeTo=2022-11-23T10:53:51.908Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=4c0821c701e2b195f38f80cf590cecf0&transactionId=fafd66b903d589aa)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-11-23T10:43:51.908+0000


* Duration: 3 min 10 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4702/detail/PR-4702/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Load a resource file from a library`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-4702/runs/1/steps/81/log/?start=0">here</a></li>
<li>Description: <code>approval-list/elastic/integrations.yml</code></l1>
</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-4702/runs/1/steps/89/log/?start=0">here</a></li>
<li>Description: <code>githubApiCall: The REST API call https://api.github.com/orgs/elastic/members/leon-seagate return the message : java.lang.Exception: httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/leon-seagate : httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/leon-seagate : Code: 404Error: {"message":"User does not exist or is not a member of the organization","documentation_url":"https://docs.github.com/rest/reference/orgs#check-organization-membership-for-a-user"}</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-11-23 10:48 UTC, leon-seagate commented
Hey @marc-gr  @jamiehynds, can you please verify CLA check ? .

2022-11-29 14:39 UTC, gtback commented
cla/check

2022-11-29 14:41 UTC, marc-gr commented
/test

2022-11-29 14:55 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2022-11-30 09:09 UTC, marc-gr requested changes
Looking good, left a couple comments.

2022-11-30 09:09 UTC, marc-gr commented on packages/lyve_cloud/data_stream/audit/elasticsearch/ingest_pipeline/audit_lc.yml
> +  - remove:
nit: merge all fields to remove in a single `remove` processor at the end (`remove`'s `field` field accepts a list https://www.elastic.co/guide/en/elasticsearch/reference/current/remove-processor.html)

2022-11-30 09:09 UTC, marc-gr commented on packages/lyve_cloud/_dev/build/docs/README.md
> +when using Lyve Cloud example dashboard or in other Analytics search fields inside the filter box.
Would be nice to add the fields and a sample event to the readme.

```suggestion
when using Lyve Cloud example dashboard or in other Analytics search fields inside the filter box.

Exported fields

{{fields "audit"}}

{{event "audit"}}
```

2022-12-05 11:19 UTC, leon-seagate reviewed
Hi, I've changed your requests :)

2022-12-12 08:19 UTC, marc-gr commented
/test

2022-12-12 09:16 UTC, marc-gr requested changes
Added some formatting nits and a couple more things, I think after these changed we are good to go 👍

2022-12-12 09:16 UTC, marc-gr commented on packages/lyve_cloud/data_stream/audit/elasticsearch/ingest_pipeline/audit_lc.yml
> +
```suggestion

```

2022-12-12 09:16 UTC, marc-gr commented on packages/lyve_cloud/data_stream/audit/elasticsearch/ingest_pipeline/audit_lc.yml
> +
```suggestion

```

2022-12-12 09:16 UTC, marc-gr commented on packages/lyve_cloud/data_stream/audit/_dev/test/pipeline/test-audit-events.json-expected.json
> +                "provider": "Seagate's Lyve Cloud"
```suggestion
                "provider": "lyvecloud"
```

This field is a keyword and would be better for searching to stick with the suggested format https://www.elastic.co/guide/en/ecs/current/ecs-cloud.html#field-cloud-provider

2022-12-12 09:16 UTC, marc-gr commented on packages/lyve_cloud/data_stream/audit/_dev/test/pipeline/test-audit-events.json-expected.json
> +                            "X-Real-Ip": "10.213.135.144:28911"
Would be interesting to add these to `related.ip` and `related.hosts` fields if possible as it helps a lot when searching across multiple data sources https://www.elastic.co/guide/en/ecs/current/ecs-related.html

2022-12-12 09:16 UTC, marc-gr commented on packages/lyve_cloud/data_stream/audit/_dev/test/pipeline/test-audit-events.json-expected.json
> +                "name": "sasha-terraform"
Similarly, would be nice to add this information to `related.user`

2022-12-12 09:16 UTC, marc-gr commented on packages/lyve_cloud/data_stream/audit/_dev/test/pipeline/test-audit-events.json-expected.json
> +                        "requestHeader": {},
we could check if empty and delete it

2022-12-12 09:16 UTC, marc-gr commented on packages/lyve_cloud/data_stream/audit/_dev/test/pipeline/test-audit-events.json-expected.json
> +                "email": "",
Same here, we can skip adding empty values

2022-12-12 09:16 UTC, marc-gr commented on packages/lyve_cloud/_dev/build/docs/README.md
> +when using Lyve Cloud example dashboard or in other Analytics search fields inside the filter box.
This can be edited once you embed the query filter in the dashboard.

2022-12-12 09:16 UTC, marc-gr commented on packages/lyve_cloud/kibana/dashboard/lyve_cloud-42d12a00-5852-11ed-a702-0d7be6ba8b3f.json
> +            }
```suggestion
            "searchSourceJSON": {
                "filter": [],
                "highlightAll": true,
                "query": {
                    "language": "kuery",
                    "query": "data_stream.dataset:lyve_cloud.audit"
                },
                "version": true
            }
```

Is better if we embed the query filter with the dashboard

2022-12-12 09:22 UTC, marc-gr commented
PS: still need to add the codeowners entry as mentioned in https://github.com/elastic/integrations/pull/4702#issuecomment-1331841061

2022-12-12 11:35 UTC, leon-seagate commented on packages/lyve_cloud/data_stream/audit/_dev/test/pipeline/test-audit-events.json-expected.json
> +                "provider": "Seagate's Lyve Cloud"
changed

2022-12-12 12:16 UTC, leon-seagate commented on packages/lyve_cloud/data_stream/audit/_dev/test/pipeline/test-audit-events.json-expected.json
> +                        "requestHeader": {},
Not sure what is the best practice in that scenario of empty field,
It shouldn’t be empty, as its a monitoring system.

2022-12-12 12:17 UTC, leon-seagate commented on packages/lyve_cloud/data_stream/audit/_dev/test/pipeline/test-audit-events.json-expected.json
> +                "email": "",
same here about - Not sure what is the best practice in that scenario of empty field,

2022-12-12 12:21 UTC, leon-seagate commented on packages/lyve_cloud/data_stream/audit/_dev/test/pipeline/test-audit-events.json-expected.json
> +                            "X-Real-Ip": "10.213.135.144:28911"
you're suggesting to take part of the ip without the port ( because the list of the [allowd-geo-ip](https://github.com/elastic/elastic-package/blob/main/internal/fields/_static/allowed_geo_ips.txt) doesn’t consist the port) – not sure how it will work because the “set” processor doesn’t allow ignore missing flag
And the ip doesn’t always come up..

2022-12-14 14:30 UTC, marc-gr commented
/test

2022-12-15 09:56 UTC, marc-gr commented
/test

2022-12-15 11:16 UTC, marc-gr commented
/test

2022-12-15 11:30 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`1/1`) | :green_heart: 
Files | 100.0% (`2/2`) | :green_heart: 
Classes | 100.0% (`2/2`) | :green_heart: 
Methods | 85.714% (`18/21`) | :-1: -12.836
Lines | 86.207% (`150/174`) | :-1: -8.132
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2022-12-15 12:35 UTC, marc-gr commented
/test

2022-12-15 12:47 UTC, marc-gr commented
/test

2022-12-15 14:19 UTC, marc-gr commented
/test

2022-12-15 15:31 UTC, marc-gr approved these changes

2022-12-15 15:34 UTC, merged