Lateral movement detection package
elastic/integrations pull request #4833
Opened 2022-12-15 00:18 UTC by sodhikirti07

## What does this PR do?
This PR adds Lateral movement detection assets to the integration packages list.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues and docs

[elastic/security-ml#167](https://github.com/elastic/security-ml/issues/167)
[elastic/security-team#2933](https://github.com/elastic/security-team/issues/2933)
https://docs.google.com/document/d/1aGB55YGVvIhMaa52uLr2CErTiifsRfb7gp2EZAJ1efQ/edit#heading=h.kgcaafk0hh1h
https://docs.google.com/document/d/14qliB7-hevPVNKX5SM1z6_gKhzVrbgb6G8wHZvMBNXs/edit

## Screenshots

2022-12-15 00:24 UTC, sodhikirti07 commented
Tested the package and following are some screenshots for the assets working as expected:

- Package added as an integration

![image](https://user-images.githubusercontent.com/109447885/207743479-77be1016-bfa8-4689-a6fb-50595849b898.png)

- ML jobs installed and started successfully

![image](https://user-images.githubusercontent.com/109447885/207743531-d42f9c25-7583-4291-af62-98d5b0ad2a05.png)

![image](https://user-images.githubusercontent.com/109447885/207743566-b85fc0b1-39b5-44fd-8637-6f1363e65a24.png)

- Detection rules are successfully imported

![image](https://user-images.githubusercontent.com/109447885/207743652-17b0af02-997c-40f1-838a-0838631f64c0.png)

2022-12-15 00:32 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4833/detail/PR-4833/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4833/detail/PR-4833/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4833/detail/PR-4833/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4833/detail/PR-4833/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_4833.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2022-12-15T00:09:00.793Z&rangeTo=2022-12-15T00:29:00.793Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=50c56bbfe09da129a1c78f66824d7cd6&transactionId=ec453e7bd86b30a2)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-12-15T00:19:00.793+0000


* Duration: 14 min 44 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-12-15 15:26 UTC, sodhikirti07 commented
I have kept the version of release as `experimental` based on the discussion I had with Jake yesterday. The idea is to release the package in technical review first to investigate if the rules create a lot of noise. This can be done by tracking the alerts telemetry. Please let me know your thoughts.

2022-12-15 19:01 UTC, susan-shu-c commented on packages/lmd/manifest.yml
> +  - src: /img/sample-screenshot.png
I think we don't need this placeholder Elastic logo screenshot anymore since we have any actual screenshot?

2022-12-15 20:13 UTC, sodhikirti07 commented on packages/lmd/manifest.yml
> +  - src: /img/sample-screenshot.png
Yes, thanks for pointing it out. I meant to delete it earlier.

2022-12-16 17:01 UTC, szeitlin approved these changes
suggested change - someone who knows more about product stuff should also review it and make sure it's ok to use direct instructions, rather than this very soft optional language that was there before.

2022-12-16 17:01 UTC, szeitlin commented on packages/lmd/docs/README.md
> +This model uses both anomaly detection and security rules to detect lateral movement in the network. To maximize the benefit of both frameworks, you should consider enabling the list of all "Security
```suggestion
This model uses both anomaly detection and security rules to detect lateral movement in the network. In order to see all alerts detected by this model, you need to enable all the "Security Detection Rules" in the table, as described below. The first four rules are triggered when certain conditions for the anomaly detection jobs are satisfied. The last two rules are behavioral and independent of anomaly detection jobs. See the [documentation](https://www.elastic.co/guide/en/security/current/detection-engine-overview.html) for more information on importing and enabling the rules.
```

2022-12-16 17:59 UTC, sodhikirti07 commented
@szeitlin Can we ask Sourin about the this when he is back?

2022-12-16 18:49 UTC, szeitlin commented
> @szeitlin Can we ask Sourin about this when he is back? Should we wait for his feedback?

I don't know that we want to wait that long. Maybe @approksiu or @MikePaquette can give us their expert opinion so we can get unblocked sooner?

2022-12-19 16:58 UTC, ajosh0504 reviewed
@sodhikirti07 Overall, looks great! 🥇 

Left some suggestions. Could you also paste screenshots:
- To show that the ML job module shows up as expected based on the query in the module json
- To show that the ML module is installed successfully without errors
- To show that runtime mappings are being added and working as expected
- To show that rules are enabled without errors

2022-12-19 16:58 UTC, ajosh0504 commented on packages/lmd/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/2352
```suggestion
      link: https://github.com/elastic/integrations/pull/4833
```

2022-12-19 16:58 UTC, ajosh0504 commented on packages/lmd/docs/README.md
> +The Lateral movement detection model package contains the lateral movement detection model and the associated assets. This package requires a Platinum subscription. Please ensure that you have a Tria
```suggestion
The Lateral movement detection model package contains assets to detect lateral movement based on file transfer activity. This package requires a Platinum subscription. Please ensure that you have a Trial or Platinum level subscription installed on your cluster before proceeding. This package is licensed under Elastic License v 1.0.
```

2022-12-19 16:58 UTC, ajosh0504 commented on packages/lmd/kibana/security_rule/2577e749-ed63-4b58-ac32-4f8a94d73e60.json
> +        "name": "High size of remote file creations indicating a lateral movement activity",
I'd suggest keeping the rule names to 3-5 words. The `description` can have a more detailed description of what the rules does. Also, use title case for consistency with other rules. 

For example, the rule name here could be `Unusual Remote File Size`.

2022-12-19 16:58 UTC, ajosh0504 commented on packages/lmd/kibana/security_rule/282cd7e6-9d51-421e-93b4-ebc2d422eb44.json
> +        "name": "Potential lateral tool transfer to an unusual directory",
Same comment as above re: rule name.

2022-12-19 16:58 UTC, ajosh0504 commented on packages/lmd/kibana/security_rule/98789aa2-c22a-4ab4-aa6b-d980073f7ca7.json
> +        "name": "Malicious remote file creation indicating a potential lateral tool transfer",
Same comment as above re: rule name.

2022-12-19 16:58 UTC, ajosh0504 commented on packages/lmd/kibana/security_rule/aa00d5db-7732-440a-97fc-8f9a3dc5314b.json
> +        "name": "High influx of remote file creations indicating a potential lateral movement activity",
Same comment as above re: rule name.

2022-12-19 16:58 UTC, ajosh0504 commented on packages/lmd/kibana/security_rule/d4e891de-fe8d-4f19-a9b3-e5f390c7167e.json
> +        "name": "Suspicious remote file creation on a sensitive directory indicating a potential lateral tool transfer",
Same comment as above re: rule name.

2022-12-19 16:58 UTC, ajosh0504 commented on packages/lmd/kibana/security_rule/e5ebb55f-97f0-4815-b05b-59b223b1d4df.json
> +        "name": "Potential lateral tool transfer having a rare extension",
Same comment as above re: rule name.

2022-12-19 16:58 UTC, ajosh0504 commented on packages/lmd/manifest.yml
> +description: "ML package to detect lateral movement activity on a host. Requires a Platinum subscription."
```suggestion
description: "ML package to detect lateral movement based on file transfer activity. Requires a Platinum subscription."
```

2022-12-19 16:58 UTC, ajosh0504 commented on packages/lmd/manifest.yml
> +release: experimental
Did we finally settle on `experimental` instead of `ga`?

2022-12-19 16:58 UTC, ajosh0504 commented on packages/lmd/kibana/ml_module/lmd-ml.json
> +        "description": "Detects lateral movement activity by identifying malicious file transfers to a host.",
```suggestion
        "description": "Detects lateral movement activity by identifying malicious file transfers in an environment.",
```

2022-12-19 16:58 UTC, ajosh0504 commented on packages/lmd/kibana/ml_module/lmd-ml.json
> +        "query": {
I think this query needs to be the bare minimum required to show the module in the Security App. For example, if a job is expected to run on network data, you'd only look for something like `event.category: network`. 

So here, I think you can keep the two exists clauses for `process.name` and `file.name`, the`event.category`, and `event.action` filters in this query, and keep the rest in the datafeeds.

2022-12-19 17:05 UTC, sodhikirti07 commented on packages/lmd/manifest.yml
> +release: experimental
yes, we decided to keep it in `experimental` for 8.6 and then probably change it to `ga` if we don't see much noise in alerts.

2022-12-19 17:18 UTC, sodhikirti07 commented
> Left some suggestions. Could you also paste screenshots:

> To show that the ML job module shows up as expected based on the query in the module json
> To show that the ML module is installed successfully without errors
> To show that runtime mappings are being added and working as expected
> To show that rules are enabled without errors

@ajosh0504 I think I've already covered the 1,2,4 screenshots [here](https://github.com/elastic/integrations/pull/4833#issuecomment-1352396880). Will do the screenshot of runtime mappings. Please let me know if you're implying something else here.

2022-12-19 19:32 UTC, sodhikirti07 commented
- ML module and jobs working properly:

![image](https://user-images.githubusercontent.com/109447885/208504730-5fa99548-2710-4974-89d8-319eec8ad6cb.png)
![image](https://user-images.githubusercontent.com/109447885/208504765-1f190f8b-dfe7-466f-8b25-487b9dd117c7.png)

- Detection rules started without any warnings:

![image](https://user-images.githubusercontent.com/109447885/208504850-f038aa43-3d1a-4799-84a1-7689cb9c5bf3.png)

- Mapping for `file_directory` working as expected in the datafeed

![image](https://user-images.githubusercontent.com/109447885/208504947-d467df18-c170-46c5-b4cd-040ae35a5e36.png)

2022-12-19 21:30 UTC, sodhikirti07 commented
@ajosh0504 made changes as suggested. Please have a look.

2022-12-19 22:01 UTC, ajosh0504 requested changes
Few more minor nits. Sorry! 😬

2022-12-19 22:01 UTC, ajosh0504 commented on packages/lmd/kibana/security_rule/2577e749-ed63-4b58-ac32-4f8a94d73e60.json
> +        "name": "Unusual remote file size",
Please change this to title case i.e. capitalize major words are capitalized, and keep minor words lowercased.

2022-12-19 22:01 UTC, ajosh0504 commented on packages/lmd/kibana/security_rule/282cd7e6-9d51-421e-93b4-ebc2d422eb44.json
> +        "name": "Unusual remote file directory",
Please change this to title case.

2022-12-19 22:01 UTC, ajosh0504 commented on packages/lmd/kibana/security_rule/98789aa2-c22a-4ab4-aa6b-d980073f7ca7.json
> +        "name": "Malicious remote file creation",
Please change this to title case.

2022-12-19 22:01 UTC, ajosh0504 commented on packages/lmd/kibana/security_rule/aa00d5db-7732-440a-97fc-8f9a3dc5314b.json
> +        "name": "High remote file transfers",
Please change this to title case. Also consider calling it "Spike in Remote File Transfers".

2022-12-19 22:01 UTC, ajosh0504 commented on packages/lmd/kibana/security_rule/d4e891de-fe8d-4f19-a9b3-e5f390c7167e.json
> +        "name": "Remote file creation on a sensitive directory",
Please change this to title case.

2022-12-19 22:01 UTC, ajosh0504 commented on packages/lmd/kibana/security_rule/e5ebb55f-97f0-4815-b05b-59b223b1d4df.json
> +        "name": "Unusual remote file extension",
Please change this to title case.

2022-12-20 09:32 UTC, approksiu commented
> > @szeitlin Can we ask Sourin about this when he is back? Should we wait for his feedback?
> 
> I don't know that we want to wait that long. Maybe @approksiu or @MikePaquette can give us their expert opinion so we can get unblocked sooner?

I like the strong language - I see that our users look up to us for recommendations how should they set things up. Let's also see what the docs team thinks.

2022-12-20 14:24 UTC, sodhikirti07 commented on packages/lmd/kibana/security_rule/2577e749-ed63-4b58-ac32-4f8a94d73e60.json
> +        "name": "Unusual remote file size",
Done!

2022-12-20 17:50 UTC, szeitlin commented
@sodhikirti07 do you know who/where to ask re: having the docs team review this?

2022-12-20 19:34 UTC, benironside reviewed
Overall the README looks good. Made a couple of minor suggestions. No problems with the imperative language, that's standard for instructions.

2022-12-20 19:34 UTC, benironside commented on packages/lmd/docs/README.md
> +The Lateral movement detection model package contains assets to detect lateral movement based on file transfer activity. This package requires a Platinum subscription. Please ensure that you have a T
```suggestion
The Lateral movement detection model package contains assets that detect lateral movement based on file transfer activity. This package requires a Platinum subscription. Please ensure that you have a Trial, Platinum, or Enterprise subscription before proceeding. This package is licensed under Elastic License v 1.0.
```

2022-12-20 19:34 UTC, benironside commented on packages/lmd/docs/README.md
> +Then use these detection rules and anomaly detection jobs for lateral movement detection.
```suggestion
```
I suggest removing this line because it isn't part of the configuration instructions, and if I'm understanding correctly, the following sections describe it in more detail anyway.

2022-12-20 21:40 UTC, sodhikirti07 commented
Shipping this package as `experimental` for 8.6. Below are a couple of things to do before moving it to `ga` in 8.7:
- Add dashboard in the package spec
- Attach a blog-post for lateral movement

2022-12-20 21:40 UTC, merged

2022-12-20 22:00 UTC, elasticmachine commented
Package lmd - 0.0.1 containing this change is available at https://epr.elastic.co/search?package=lmd

2022-12-30 21:08 UTC, CyberTaoFlow commented
seems like zeek and/or suricata SMB traffic could be useful for providing the network viewpoint independent of agent telemetry.  
One point to consider is there will be a need to perform correlation with kerberos or ntlm logs from these same tools to obtain the user information used as an influencing attribute in the current jobs.