[Metrics][Kubernetes] Update proxy, scheduler and controller manager fields and dashboards
elastic/integrations pull request #4948
Opened 2023-01-09 11:49 UTC by constanca-m

## What does this PR do?

This PR updates the dashboards and fields of proxy, scheduler and controller manager to match the ones mentioned in https://github.com/elastic/beats/pull/34161.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally

1. Download the changes of this PR.
2. Run command `elastic-package build` inside Kubernetes package.
3. Run `elastic-package stack up`.
4. Using Kibana, add Kubernetes integration.

## Related issues

- Relates to https://github.com/elastic/beats/pull/34161
- Closes https://github.com/elastic/integrations/issues/4607, https://github.com/elastic/integrations/issues/4810 and https://github.com/elastic/integrations/issues/4580.

## Screenshots

The dashboards are just like the ones on the screenshots of https://github.com/elastic/beats/pull/34161.

The cluster overview dashboard was also updated to include a link to the proxy dashboard:
![image](https://user-images.githubusercontent.com/113898685/211299675-c80ff718-0711-4172-83c4-bdf536da73cd.png)

## Problem
When using `metricbeat-*` index, fetching a metric like `node_collector_zone_size{zone=""} 1` would result in a missing value on `kubernetes.controllermanager.zone`. The result would appear on the visualization like this:
![image](https://user-images.githubusercontent.com/113898685/211300060-f2985e1e-361a-419f-b0e5-cf9a26103f50.png)

However, when using the `metrics-*` index, there is no missing value anymore as the metric does not even exist:
![Screenshot from 2023-01-09 11-37-28](https://user-images.githubusercontent.com/113898685/211300227-ce410043-ae2b-4294-9e97-25356e6ab8f6.png)

An empty value like the label `zone` label would be ignored according to [metricbeat code](https://github.com/elastic/beats/blob/main/metricbeat/helper/prometheus/prometheus.go#L303). However, the end results in `metricbeat-*` and `metric-*` indexes are different.

2023-01-09 12:19 UTC, elasticmachine commented
## :broken_heart: Tests Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4948/detail/PR-4948/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4948/detail/PR-4948/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4948/detail/PR-4948/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4948/detail/PR-4948/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_4948.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-01-09T11:40:06.530Z&rangeTo=2023-01-09T12:00:06.530Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=59b2241534d3142bc0f229c1e905fe0d&transactionId=6fb0caac0b57cca1)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-01-09T11:50:06.530+0000


* Duration: 29 min 10 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 3  |
| Passed       | 19  |
| Skipped      | 0 |
| Total        | 22   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->

  ### Test errors [![3](https://img.shields.io/badge/3%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4948/detail/PR-4948/1//tests)
<details><summary>Expand to view the tests failures</summary><p>
    
    
##### `system test: default – kubernetes.proxy`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 null 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 one or more errors found in documents stored in metrics-kubernetes.proxy-ep data stream: [0] field "kubernetes.proxy.client.request.count" is undefined
[1] field "kubernetes.proxy.code" is undefined
[2] field "kubernetes.proxy.host" is undefined
[3] field "kubernetes.proxy.method" is undefined
[4] field "kubernetes.proxy.process.cpu.sec" is undefined
[5] field "kubernetes.proxy.process.fds.open.count" is undefined
[6] field "kubernetes.proxy.process.memory.resident.bytes" is undefined
[7] field "kubernetes.proxy.process.memory.virtual.bytes" is undefined
[8] field "kubernetes.proxy.process.started.sec" is undefined
[9] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.+Inf" is undefined
[10] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.0" is undefined
[11] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.1000000" is undefined
[12] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.10000000" is undefined
[13] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.100000000" is undefined
[14] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.105000000" is undefined
[15] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.11000000" is undefined
[16] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.110000000" is undefined
[17] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.115000000" is undefined
[18] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.12000000" is undefined
[19] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.120000000" is undefined
[20] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.13000000" is undefined
[21] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.14000000" is undefined
[22] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.15000000" is undefined
[23] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.150000000" is undefined
[24] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.16000000" is undefined
[25] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.17000000" is undefined
[26] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.18000000" is undefined
[27] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.180000000" is undefined
[28] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.19000000" is undefined
[29] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.2000000" is undefined
[30] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.20000000" is undefined
[31] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.21000000" is undefined
[32] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.210000000" is undefined
[33] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.22000000" is undefined
[34] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.23000000" is undefined
[35] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.24000000" is undefined
[36] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.240000000" is undefined
[37] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.250000" is undefined
[38] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.25000000" is undefined
[39] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.26000000" is undefined
[40] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.27000000" is undefined
[41] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.270000000" is undefined
[42] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.28000000" is undefined
[43] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.29000000" is undefined
[44] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.3000000" is undefined
[45] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.30000000" is undefined
[46] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.300000000" is undefined
[47] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.31000000" is undefined
[48] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.32000000" is undefined
[49] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.33000000" is undefined
[50] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.34000000" is undefined
[51] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.35000000" is undefined
[52] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.36000000" is undefined
[53] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.37000000" is undefined
[54] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.38000000" is undefined
[55] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.39000000" is undefined
[56] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.4000000" is undefined
[57] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.40000000" is undefined
[58] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.41000000" is undefined
[59] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.42000000" is undefined
[60] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.43000000" is undefined
[61] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.44000000" is un [...]

2023-01-09 12:19 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 33.333
Classes | 100.0% (`0/0`) | :green_heart: 33.333
Methods | 84.615% (`22/26`) | :+1: 4.928
Lines | 100.0% (`0/0`) | :green_heart: 25.735
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-01-09 13:34 UTC, elasticmachine commented
## :broken_heart: Tests Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4948/detail/PR-4948/3//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4948/detail/PR-4948/3//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4948/detail/PR-4948/3//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4948/detail/PR-4948/3//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_4948.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-01-09T12:55:32.497Z&rangeTo=2023-01-09T13:15:32.497Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=18467ffdda0c6000ce1ab435a379dde1&transactionId=fa78676d2fe3fdcc)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-01-09T13:05:32.497+0000


* Duration: 28 min 23 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 3  |
| Passed       | 19  |
| Skipped      | 0 |
| Total        | 22   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->

  ### Test errors [![3](https://img.shields.io/badge/3%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4948/detail/PR-4948/3//tests)
<details><summary>Expand to view the tests failures</summary><p>
    
    
##### `system test: default – kubernetes.controllermanager`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 null 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 one or more errors found in documents stored in metrics-kubernetes.controllermanager-ep data stream: [0] field "kubernetes.controllermanager.client.request.count" is undefined
[1] field "kubernetes.controllermanager.client.request.duration.us.bucket.+Inf" is undefined
[2] field "kubernetes.controllermanager.client.request.duration.us.bucket.100000" is undefined
[3] field "kubernetes.controllermanager.client.request.duration.us.bucket.1000000" is undefined
[4] field "kubernetes.controllermanager.client.request.duration.us.bucket.15000000" is undefined
[5] field "kubernetes.controllermanager.client.request.duration.us.bucket.2000000" is undefined
[6] field "kubernetes.controllermanager.client.request.duration.us.bucket.25000" is undefined
[7] field "kubernetes.controllermanager.client.request.duration.us.bucket.250000" is undefined
[8] field "kubernetes.controllermanager.client.request.duration.us.bucket.30000000" is undefined
[9] field "kubernetes.controllermanager.client.request.duration.us.bucket.4000000" is undefined
[10] field "kubernetes.controllermanager.client.request.duration.us.bucket.5000" is undefined
[11] field "kubernetes.controllermanager.client.request.duration.us.bucket.500000" is undefined
[12] field "kubernetes.controllermanager.client.request.duration.us.bucket.60000000" is undefined
[13] field "kubernetes.controllermanager.client.request.duration.us.bucket.8000000" is undefined
[14] field "kubernetes.controllermanager.client.request.duration.us.count" is undefined
[15] field "kubernetes.controllermanager.client.request.duration.us.sum" is undefined
[16] field "kubernetes.controllermanager.code" is undefined
[17] field "kubernetes.controllermanager.host" is undefined
[18] field "kubernetes.controllermanager.leader.is_master" is undefined
[19] field "kubernetes.controllermanager.method" is undefined
[20] field "kubernetes.controllermanager.name" is undefined
[21] field "kubernetes.controllermanager.node.collector.count" is undefined
[22] field "kubernetes.controllermanager.node.collector.eviction.count" is undefined
[23] field "kubernetes.controllermanager.node.collector.health.pct" is undefined
[24] field "kubernetes.controllermanager.node.collector.unhealthy.count" is undefined
[25] field "kubernetes.controllermanager.process.cpu.sec" is undefined
[26] field "kubernetes.controllermanager.process.fds.max.count" is undefined
[27] field "kubernetes.controllermanager.process.fds.open.count" is undefined
[28] field "kubernetes.controllermanager.process.memory.resident.bytes" is undefined
[29] field "kubernetes.controllermanager.process.memory.virtual.bytes" is undefined
[30] field "kubernetes.controllermanager.process.started.sec" is undefined
[31] field "kubernetes.controllermanager.verb" is undefined
[32] field "kubernetes.controllermanager.workqueue.adds.count" is undefined
[33] field "kubernetes.controllermanager.workqueue.depth.count" is undefined
[34] field "kubernetes.controllermanager.workqueue.longestrunning.sec" is undefined
[35] field "kubernetes.controllermanager.workqueue.retries.count" is undefined
[36] field "kubernetes.controllermanager.workqueue.unfinished.sec" is undefined 
 ```
</p></details>
</ul>
    
##### `system test: default – kubernetes.proxy`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 null 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 one or more errors found in documents stored in metrics-kubernetes.proxy-ep data stream: [0] field "kubernetes.proxy.client.request.count" is undefined
[1] field "kubernetes.proxy.code" is undefined
[2] field "kubernetes.proxy.host" is undefined
[3] field "kubernetes.proxy.method" is undefined
[4] field "kubernetes.proxy.process.cpu.sec" is undefined
[5] field "kubernetes.proxy.process.fds.open.count" is undefined
[6] field "kubernetes.proxy.process.memory.resident.bytes" is undefined
[7] field "kubernetes.proxy.process.memory.virtual.bytes" is undefined
[8] field "kubernetes.proxy.process.started.sec" is undefined
[9] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.+Inf" is undefined
[10] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.0" is undefined
[11] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.1000000" is undefined
[12] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.10000000" is undefined
[13] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.100000000" is undefined
[14] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.105000000" is undefined
[15] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.11000000" is undefined
[16] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.110000000" is undefined
[17] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.115000000" is undefined
[18] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.12000000" is undefined
[19] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.120000000" is undefined
[20] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.13000000" is undefined
[21] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.14000000" is undefined
[22] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.15000000" is undefined
[23] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.150000000" is undefined
[24] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.16000000" is undefined
[25] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.17000000" i [...]

2023-01-09 13:34 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 33.333
Classes | 100.0% (`0/0`) | :green_heart: 33.333
Methods | 84.615% (`22/26`) | :+1: 4.928
Lines | 100.0% (`0/0`) | :green_heart: 25.735
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-01-09 14:26 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4948/detail/PR-4948/4//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4948/detail/PR-4948/4//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4948/detail/PR-4948/4//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4948/detail/PR-4948/4//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_4948.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-01-09T14:05:54.632Z&rangeTo=2023-01-09T14:25:54.632Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=af11d7f09cae213ab3d278b59a14cb5f&transactionId=02981c03bca598dc)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-01-09T14:15:54.632+0000


* Duration: 10 min 25 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![3](https://img.shields.io/badge/3%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4948/detail/PR-4948/4//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Check integration: kubernetes`
<ul>
<li>Took 0 min 2 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-4948/runs/4/steps/1022/log/?start=0">here</a></li>
<li>Description: <code>../../build/elastic-package check -v</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-4948/runs/4/steps/1057/log/?start=0">here</a></li>

</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-4948/runs/4/steps/1070/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-01-09 14:32 UTC, constanca-m commented
/test

2023-01-09 14:47 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 33.333
Classes | 100.0% (`0/0`) | :green_heart: 33.333
Methods | 100.0% (`26/26`) | :green_heart: 20.312
Lines | 100.0% (`0/0`) | :green_heart: 25.735
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-01-09 14:47 UTC, elasticmachine commented
## :broken_heart: Tests Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4948/detail/PR-4948/5//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4948/detail/PR-4948/5//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4948/detail/PR-4948/5//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4948/detail/PR-4948/5//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_4948.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-01-09T14:07:54.653Z&rangeTo=2023-01-09T14:27:54.653Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=3c497a6ecb6158f8791a2f880d3edf90&transactionId=25d699383c58e673)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-01-09T14:17:54.653+0000


* Duration: 30 min 35 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 3  |
| Passed       | 19  |
| Skipped      | 0 |
| Total        | 22   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->

  ### Test errors [![3](https://img.shields.io/badge/3%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4948/detail/PR-4948/5//tests)
<details><summary>Expand to view the tests failures</summary><p>
    
    
##### `system test: default – kubernetes.controllermanager`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 null 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 one or more errors found in documents stored in metrics-kubernetes.controllermanager-ep data stream: [0] field "kubernetes.controllermanager.client.request.count" is undefined
[1] field "kubernetes.controllermanager.client.request.duration.us.bucket.+Inf" is undefined
[2] field "kubernetes.controllermanager.client.request.duration.us.bucket.100000" is undefined
[3] field "kubernetes.controllermanager.client.request.duration.us.bucket.1000000" is undefined
[4] field "kubernetes.controllermanager.client.request.duration.us.bucket.15000000" is undefined
[5] field "kubernetes.controllermanager.client.request.duration.us.bucket.2000000" is undefined
[6] field "kubernetes.controllermanager.client.request.duration.us.bucket.25000" is undefined
[7] field "kubernetes.controllermanager.client.request.duration.us.bucket.250000" is undefined
[8] field "kubernetes.controllermanager.client.request.duration.us.bucket.30000000" is undefined
[9] field "kubernetes.controllermanager.client.request.duration.us.bucket.4000000" is undefined
[10] field "kubernetes.controllermanager.client.request.duration.us.bucket.5000" is undefined
[11] field "kubernetes.controllermanager.client.request.duration.us.bucket.500000" is undefined
[12] field "kubernetes.controllermanager.client.request.duration.us.bucket.60000000" is undefined
[13] field "kubernetes.controllermanager.client.request.duration.us.bucket.8000000" is undefined
[14] field "kubernetes.controllermanager.client.request.duration.us.count" is undefined
[15] field "kubernetes.controllermanager.client.request.duration.us.sum" is undefined
[16] field "kubernetes.controllermanager.code" is undefined
[17] field "kubernetes.controllermanager.host" is undefined
[18] field "kubernetes.controllermanager.leader.is_master" is undefined
[19] field "kubernetes.controllermanager.method" is undefined
[20] field "kubernetes.controllermanager.name" is undefined
[21] field "kubernetes.controllermanager.node.collector.count" is undefined
[22] field "kubernetes.controllermanager.node.collector.eviction.count" is undefined
[23] field "kubernetes.controllermanager.node.collector.health.pct" is undefined
[24] field "kubernetes.controllermanager.node.collector.unhealthy.count" is undefined
[25] field "kubernetes.controllermanager.process.cpu.sec" is undefined
[26] field "kubernetes.controllermanager.process.fds.max.count" is undefined
[27] field "kubernetes.controllermanager.process.fds.open.count" is undefined
[28] field "kubernetes.controllermanager.process.memory.resident.bytes" is undefined
[29] field "kubernetes.controllermanager.process.memory.virtual.bytes" is undefined
[30] field "kubernetes.controllermanager.process.started.sec" is undefined
[31] field "kubernetes.controllermanager.verb" is undefined
[32] field "kubernetes.controllermanager.workqueue.adds.count" is undefined
[33] field "kubernetes.controllermanager.workqueue.depth.count" is undefined
[34] field "kubernetes.controllermanager.workqueue.longestrunning.sec" is undefined
[35] field "kubernetes.controllermanager.workqueue.retries.count" is undefined
[36] field "kubernetes.controllermanager.workqueue.unfinished.sec" is undefined 
 ```
</p></details>
</ul>
    
##### `system test: default – kubernetes.scheduler`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 null 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 one or more errors found in documents stored in metrics-kubernetes.scheduler-ep data stream: [0] field "kubernetes.scheduler.client.request.count" is undefined
[1] field "kubernetes.scheduler.code" is undefined
[2] field "kubernetes.scheduler.host" is undefined
[3] field "kubernetes.scheduler.leader.is_master" is undefined
[4] field "kubernetes.scheduler.method" is undefined
[5] field "kubernetes.scheduler.name" is undefined
[6] field "kubernetes.scheduler.process.cpu.sec" is undefined
[7] field "kubernetes.scheduler.process.fds.open.count" is undefined
[8] field "kubernetes.scheduler.process.memory.resident.bytes" is undefined
[9] field "kubernetes.scheduler.process.memory.virtual.bytes" is undefined
[10] field "kubernetes.scheduler.process.started.sec" is undefined
[11] field "kubernetes.scheduler.result" is undefined
[12] field "kubernetes.scheduler.scheduling.pod.attempts.count" is undefined 
 ```
</p></details>
</ul>
    
##### `system test: default – kubernetes.proxy`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 null 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 one or more errors found in documents stored in metrics-kubernetes.proxy-ep data stream: [0] field "kubernetes.proxy.client.request.count" is undefined
[1] field "kubernetes.proxy.code" is undefined
[2] field "kubernetes.proxy.host" is undefined
[3] field "kubernetes.proxy.method" is undefined
[4] field "kubernetes.proxy.process.cpu.sec" is undefined
[5] field "kubernetes.proxy.process.fds.open.count" is undefined
[6] field "kubernetes.proxy.process.memory.resident.bytes" is undefined
[7] field "kubernetes.proxy.process.memory.virtual.bytes" is undefined
[8] field "kubernetes.proxy.process.started.sec" is undefined
[9] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.+Inf" is undefined
[10] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.0" is undefined
[11] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.1000000" is undefined
[12] field "kubernetes.proxy.sync.networkprogramming.duration.us.bucket.10000000" is undefined
[13] field "kubernetes.proxy.sync.networkprogramming.duration.us.b [...]

2023-01-09 14:47 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 33.333
Classes | 100.0% (`0/0`) | :green_heart: 33.333
Methods | 84.615% (`22/26`) | :+1: 4.928
Lines | 100.0% (`0/0`) | :green_heart: 25.735
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-01-09 15:50 UTC, elasticmachine commented
## :broken_heart: Tests Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4948/detail/PR-4948/7//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4948/detail/PR-4948/7//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4948/detail/PR-4948/7//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4948/detail/PR-4948/7//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_4948.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-01-09T15:11:11.675Z&rangeTo=2023-01-09T15:31:11.675Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=36b85d12cf1cb20394d6796727dbfbde&transactionId=93c9e196daf4c9fc)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-01-09T15:21:11.675+0000


* Duration: 29 min 9 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 1  |
| Passed       | 21  |
| Skipped      | 0 |
| Total        | 22   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->

  ### Test errors [![1](https://img.shields.io/badge/1%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4948/detail/PR-4948/7//tests)
<details><summary>Expand to view the tests failures</summary><p>
    
    
##### `system test: default – kubernetes.scheduler`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 null 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 one or more errors found in documents stored in metrics-kubernetes.scheduler-ep data stream: [0] field "kubernetes.scheduler.scheduling.pod.attempts.count" is undefined 
 ```
</p></details>
</ul>
    
</p></details>


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4948/detail/PR-4948/7//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Test integration: kubernetes`
<ul>
<li>Took 15 min 17 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-4948/runs/7/steps/1062/log/?start=0">here</a></li>
<li>Description: <code>                                eval "$(../../build/elastic-package stack shellinit)"                                ../../build/elastic-package test -v --report-format xUnit --report-output file --test-coverage                                </code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-4948/runs/7/steps/1146/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-01-09 15:50 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 2.044
Classes | 100.0% (`0/0`) | :green_heart: 2.044
Methods | 84.615% (`22/26`) | :-1: -6.365
Lines | 100.0% (`0/0`) | :green_heart: 8.457
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-01-09 16:20 UTC, constanca-m commented
\test

2023-01-10 12:18 UTC, gsantoro approved these changes

2023-01-10 14:13 UTC, tetianakravchenko reviewed
tests are failing with the error:
```
found 0 hits in metrics-kubernetes.state_persistentvolumeclaim-ep data stream: index_not_found_exception: no such index [metrics-kubernetes.state_persistentvolumeclaim-ep] Status=404

found 0 hits in metrics-kubernetes.state_persistentvolumeclaim-ep data stream: search_phase_execution_exception: all shards failed Status=503
```
doesn't seem to be related to your change, could you try to retrigger tests?
did you try to run tests locally?

2023-01-10 14:24 UTC, constanca-m commented
> doesn't seem to be related to your change, could you try to retrigger tests? did you try to run tests locally?

Yes, I can try that, but I don't think it will work. From what I understand, the field `kubernetes.namespace_uid` is undefinied for those datasets like the error says. It is true, it is not present on the `base-fields.yml` of those. The other datatsets have that. maybe that is why there is no complaint.

2023-01-10 14:25 UTC, constanca-m commented on packages/kubernetes/data_stream/proxy/sample_event.json
> +        "proxy": {
You're right, I will update the sample for the 3 datasets on the next commit.

2023-01-10 14:25 UTC, constanca-m commented
/test

2023-01-10 14:28 UTC, tetianakravchenko commented on packages/kubernetes/kibana/dashboard/kubernetes-5e649d60-9901-11e9-ba57-b7ab4e2d4b58.json
> +                                                        "formula": "differences(last_value(kubernetes.proxy.process.memory.resident.bytes))",
looking on https://user-images.githubusercontent.com/113898685/210374382-e14518ad-ac4c-4683-9abb-51a00aefeb3e.png I am not sure that this is a clear representation of memory usage, I would keep memory usage charts consistent

2023-01-10 14:31 UTC, constanca-m commented on packages/kubernetes/kibana/dashboard/kubernetes-5e649d60-9901-11e9-ba57-b7ab4e2d4b58.json
> +                                                        "formula": "differences(last_value(kubernetes.proxy.process.memory.resident.bytes))",
There is no metric for the limit of resident memory usage, so having the average isn't really interesting. I used the rate because it will be easier to detect changes, just like with all the other metrics

2023-01-10 17:09 UTC, tetianakravchenko commented on packages/kubernetes/kibana/dashboard/kubernetes-5e649d60-9901-11e9-ba57-b7ab4e2d4b58.json
> +                                                        "formula": "differences(last_value(kubernetes.proxy.process.memory.resident.bytes))",
> so having the average isn't really interesting.

why?

> I used the rate because it will be easier to detect changes, just like with all the other metrics

I wouldn't say that for monitoring purpose changes like increase/decrease in 50KB provide any value, but it gives a falls impression that smth is wrong

2023-01-10 17:35 UTC, constanca-m commented on packages/kubernetes/kibana/dashboard/kubernetes-5e649d60-9901-11e9-ba57-b7ab4e2d4b58.json
> +                                                        "formula": "differences(last_value(kubernetes.proxy.process.memory.resident.bytes))",
It is very hard to detect spikes on average if we are taking into account many values, while the rate only cares about the last value, which makes it incredibly easier

2023-01-11 10:14 UTC, tetianakravchenko commented on packages/kubernetes/kibana/dashboard/kubernetes-5e649d60-9901-11e9-ba57-b7ab4e2d4b58.json
> +                                                        "formula": "differences(last_value(kubernetes.proxy.process.memory.resident.bytes))",
> It is very hard to detect spikes on average if we are taking into account many values

but are such spikes as on the screenshot - https://user-images.githubusercontent.com/113898685/210374382-e14518ad-ac4c-4683-9abb-51a00aefeb3e.png are important for either overall performance or to highlight problems?

2023-01-11 10:52 UTC, constanca-m commented on packages/kubernetes/kibana/dashboard/kubernetes-5e649d60-9901-11e9-ba57-b7ab4e2d4b58.json
> +                                                        "formula": "differences(last_value(kubernetes.proxy.process.memory.resident.bytes))",
Spikes as the one on the screenshot are not important, but the node on the screenshot only has the essential pods + the metricbeat pod. But it is hard to make a case without giving examples. I will try to make it clear once I open the PR for https://github.com/elastic/observability-docs/issues/2474. In the meantime, we can leave it as it is, or I can change to the average

2023-01-11 14:22 UTC, gizas commented on packages/kubernetes/kibana/dashboard/kubernetes-bf9389f0-0c14-11ed-b760-5d1bccb47f56.json
> +                "version": "8.5.1"
```suggestion
                "version": "8.6.0"
```

2023-01-11 14:23 UTC, gizas commented on packages/kubernetes/manifest.yml
> +  kibana.version: "^8.7.0"
I tested this also with 8.6.0 and works fine.

(with 8.6.0)
![Screenshot 2023-01-11 at 4 17 05 PM](https://user-images.githubusercontent.com/1685415/211829954-2c4c4bdb-7d97-48e3-85f1-197402f850dc.png)

See comment on line https://github.com/elastic/integrations/pull/4948/files#diff-293e076906b24a178d0e026ab430e5289dabc6f425f2113bcbcf6125d68c2524R170 which I guess should be done 8.6.0 ?

2023-01-11 14:26 UTC, gizas commented on packages/kubernetes/kibana/dashboard/kubernetes-f5ab5510-9c94-11e9-94fd-c91206cd5249.json
> +                            "key": "event.dataset",
Please change this filter from event.dataset to:

`datastream.dataset` is `kubernetes.controllermanager`

2023-01-11 14:37 UTC, gizas commented on packages/kubernetes/kibana/dashboard/kubernetes-bf9389f0-0c14-11ed-b760-5d1bccb47f56.json
> +                            "markdown": "### Controller Manager\n\nThis dashboard uses data collected from the metrics endpoint of [kube controller manager](https://kubernetes.io/docs/concepts/overvi
```suggestion
                            "markdown": "### Controller Manager\n\nThis dashboard uses data collected from  [Kube Controller Manager](https://kubernetes.io/docs/concepts/overview/components/#kube-controller-manager) endpoint.  \n\n**WARNING**:   In some managed Kubernetes solutions like [GKE](https://www.elastic.co/guide/en/fleet/current/running-on-gke-standard-managed-by-fleet.html), [EKS](https://www.elastic.co/guide/en/fleet/current/running-on-eks-managed-by-fleet.html)or AKS(https://www.elastic.co/guide/en/fleet/current/install-elastic-agents-in-containers.html), access **is not allowed**, so this dashboard wont function properly.
 \n\n          
Refer [here](https://docs.elastic.co/en/integrations/kubernetes#scheduler-and-controllermanager) for more information",
```

2023-01-11 14:40 UTC, gizas commented on packages/kubernetes/kibana/dashboard/kubernetes-bf9389f0-0c14-11ed-b760-5d1bccb47f56.json
> +                            "markdown": "Cluster nodes",
Maybe Cluster nodes box is not needed? Is it a duplicate because it refers only to one visulaisation? 

Loved the colours for other grouping you did

2023-01-11 14:41 UTC, gizas commented on packages/kubernetes/kibana/dashboard/kubernetes-bf9389f0-0c14-11ed-b760-5d1bccb47f56.json
> +                "title": "Node collector [Metrics Kubernetes]",
```suggestion
                "title": "Node collector",
```

2023-01-11 14:42 UTC, gizas commented on packages/kubernetes/kibana/dashboard/kubernetes-bf9389f0-0c14-11ed-b760-5d1bccb47f56.json
> +                "title": "Node collector [Metrics Kubernetes]",
Consider removing `[Metrics Kubernetes]` from all label titles as not needed anymore.

I think are leftovers from old times where we were saving those visualisations to libraries in order to reuse them

2023-01-11 14:45 UTC, gizas commented on packages/kubernetes/kibana/dashboard/kubernetes-bf9389f0-0c14-11ed-b760-5d1bccb47f56.json
> +                            "markdown": "**NOTE**: The default period to fetch the metrics used in **Requests and responses [Metrics Kubernetes]** visualization is **10s**. The timestamps from the vi
```suggestion
                            "markdown": "**NOTE**: The default period to fetch the metrics used in **Requests and responses ** visualization is **10s**. **.",
```

2023-01-11 14:57 UTC, gizas commented on packages/kubernetes/kibana/dashboard/kubernetes-5e649d60-9901-11e9-ba57-b7ab4e2d4b58.json
> +                            "markdown": "### Proxy\n\nThis dashboard uses data collected from the metrics endpoint of [kube proxy](https://kubernetes.io/docs/concepts/overview/components/#kube-proxy)
```suggestion
                            "markdown": "### Proxy\n\nThis dashboard collects metrics from  [kube proxy](https://kubernetes.io/docs/concepts/overview/components/#kube-proxy) endpoint .",
```

2023-01-11 14:58 UTC, gizas commented on packages/kubernetes/kibana/dashboard/kubernetes-5e649d60-9901-11e9-ba57-b7ab4e2d4b58.json
> +                            "markdown": "### Proxy\n\nThis dashboard uses data collected from the metrics endpoint of [kube proxy](https://kubernetes.io/docs/concepts/overview/components/#kube-proxy)
Add also comment for unavailablity of this dashboard like in controller manager

2023-01-11 15:06 UTC, gizas commented on packages/kubernetes/kibana/dashboard/kubernetes-5e649d60-9901-11e9-ba57-b7ab4e2d4b58.json
> +                "title": "Average SyncProxyRules latency [Metrics Kubernetes]",
```suggestion
                "title": "Average SyncProxyRules latency",
```

2023-01-11 15:14 UTC, gizas commented on packages/kubernetes/kibana/dashboard/kubernetes-5e649d60-9901-11e9-ba57-b7ab4e2d4b58.json
> +                            "markdown": "**NOTE**: The default period to fetch the metrics used in **Requests counter rate [Metrics Kubernetes], Client error responses counter rate [Metrics Kubernete
```suggestion
                            "markdown": "**NOTE**: The default period to fetch the metrics used in **Requests counter rate** , **Client error responses counter rate ** and **Server error responses counter rate ** visualizations is **10s**.",
```

2023-01-11 15:17 UTC, gizas commented on packages/kubernetes/kibana/dashboard/kubernetes-5e649d60-9901-11e9-ba57-b7ab4e2d4b58.json
> +                                                        "formula": "differences(last_value(kubernetes.proxy.process.memory.resident.bytes))",
I would suggest `average(kubernetes.proxy.process.memory.resident.bytes)` 

What do you think?

2023-01-11 15:19 UTC, constanca-m commented on packages/kubernetes/manifest.yml
> +  kibana.version: "^8.7.0"
It only works because some fields existed already on the previous version of metricbeat. But that doesn't happen forl all the fields

2023-01-11 15:26 UTC, gizas commented
Also for scheduler I see top visualisations have no data by default. 
Do you think we should update the notes for this?

![Screenshot 2023-01-11 at 5 20 35 PM](https://user-images.githubusercontent.com/1685415/211845691-bb8a5cff-d546-4cf4-8629-d1473d3c763c.png)

2023-01-11 15:28 UTC, constanca-m commented
> Also for scheduler I see top visualisations have no data by default. Do you think we should update the notes for this?
> 
> ![Screenshot 2023-01-11 at 5 20 35 PM](https://user-images.githubusercontent.com/1685415/211845691-bb8a5cff-d546-4cf4-8629-d1473d3c763c.png)

They have values @gizas on version 8.7.0. Partial intervals were dropped, so you have to wait a few seconds to see them

2023-01-11 15:30 UTC, gizas commented
@constanca-m great work overall and very detailed !!! 

You can update the sections of `related stories` with the one you created (in order someone lets say that will see your PR after sometime to see continuation of work)

And also make sure that in your `How to test` section: You need to enable Proxy,Scheduler, Controller manager datasets in kubernetes policy.

2023-01-11 15:50 UTC, constanca-m commented on packages/kubernetes/kibana/dashboard/kubernetes-bf9389f0-0c14-11ed-b760-5d1bccb47f56.json
> +                            "markdown": "Cluster nodes",
It was on purpose, because every visualization is inside a "section", so I included that one on Cluster Nodes

2023-01-11 15:51 UTC, constanca-m commented on packages/kubernetes/kibana/dashboard/kubernetes-bf9389f0-0c14-11ed-b760-5d1bccb47f56.json
> +                "title": "Node collector [Metrics Kubernetes]",
I will update that for every visualization

2023-01-11 15:53 UTC, constanca-m commented on packages/kubernetes/kibana/dashboard/kubernetes-5e649d60-9901-11e9-ba57-b7ab4e2d4b58.json
> +                                                        "formula": "differences(last_value(kubernetes.proxy.process.memory.resident.bytes))",
Yes, I will update to that. I am still a little skeptical on choosing average over rate, but it will maybe become more clear once we settle on which problems we want to highlight.

2023-01-11 19:33 UTC, andrewctate requested changes
I see 8.7 in the `manifest.yml`.

Changing dashboards and visualizations using an unreleased version of Kibana is unsafe since the App Ex team is still actively making changes to the Kibana code and potentially the data models. In other words, you have no guarantee that your changes won't be broken by the time 8.7 is released.

If this PR can wait until 8.7 is about to be released, that's best. If there's some reason it really has to be merged now, please reach out.

2023-01-12 13:15 UTC, tetianakravchenko commented
@andrewctate 

> Changing dashboards and visualizations using an unreleased version of Kibana is unsafe since the App Ex team is still actively making changes to the Kibana code and potentially the data models. In other words, you have no guarantee that your changes won't be broken by the time 8.7 is released.

main reason of using 8.7 here, is because integration package must be compatible with beats version - https://github.com/elastic/beats/pull/34161, where some new fields were introduced, that we rely on in this PR. What then would be the best approach in this case?

2023-01-12 14:30 UTC, tetianakravchenko commented on packages/kubernetes/kibana/dashboard/kubernetes-5e649d60-9901-11e9-ba57-b7ab4e2d4b58.json
> +                                "datastream.dataset": "kubernetes.proxy"
shouldn't it be `data_stream.dataset` ? 🤔 

comparing to https://github.com/elastic/integrations/pull/4972/files

the same for other dashboards in this PR

2023-01-12 14:33 UTC, constanca-m commented on packages/kubernetes/kibana/dashboard/kubernetes-5e649d60-9901-11e9-ba57-b7ab4e2d4b58.json
> +                                "datastream.dataset": "kubernetes.proxy"
Yes, thanks for pointing that out. I am going to test it now that the changes were backported on metricbeat and I will make the commit for version 8.6 accordingly

2023-01-12 15:05 UTC, andrewctate commented
@tetianakravchenko

> main reason of using 8.7 here, is because integration package must be compatible with beats version - https://github.com/elastic/beats/pull/34161, where some new fields were introduced, that we rely on in this PR. What then would be the best approach in this case?

I understand. Your reasons for using 8.7 are valid. 

If @constanca-m is successful in making the changes to the dashboards on 8.6 instead, that is the most straightforward solution. If not, my suggestion is to wait on merging this PR until at least the day after 8.7 feature freeze (or even a few days before public release). That gives you a chance to verify that your dashboard changes still work before committing them to the main branch.

2023-01-30 07:13 UTC, merged

2023-01-30 07:33 UTC, elasticmachine commented
Package kubernetes - 1.31.1 containing this change is available at https://epr.elastic.co/search?package=kubernetes