Add a note regarding kibana.version
elastic/integrations pull request #4970
Opened 2023-01-11 12:37 UTC by tetianakravchenko

Signed-off-by: Tetiana Kravchenko <tetiana.kravchenko@elastic.co>

## What does this PR do?

Add information about package compatibility with stack/beats version

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2023-01-11 14:07 UTC, gsantoro commented on docs/developer_workflow_design_build_test_integration.md
> +    ```
Can you please add a few words to explain how it behaves if you add a condition on a version of kibana that's hasn't been released yet. That I think it's very important to track from our meeting

2023-01-11 14:08 UTC, gsantoro requested changes
Add a note about future kibana releases

2023-01-11 14:34 UTC, elasticmachine commented
## :broken_heart: Tests Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4970/detail/PR-4970/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4970/detail/PR-4970/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4970/detail/PR-4970/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4970/detail/PR-4970/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_4970.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-01-11T12:28:12.435Z&rangeTo=2023-01-11T12:48:12.435Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=fc04a1c4af03baadb1a963f8c1b4843b&transactionId=1ba9de63fc31b848)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-01-11T12:38:12.435+0000


* Duration: 116 min 42 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 48  |
| Passed       | 4598  |
| Skipped      | 10 |
| Total        | 4656   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->

  ### Test errors [![48](https://img.shields.io/badge/48%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4970/detail/PR-4970/1//tests)
<details><summary>Expand to view the tests failures</summary><p>
    > Show only the first 10 test failures
    
##### `Check integrations / symantec_endpoint / symantec_endpoint: check / pipeline test: test-rfc3164.log – symantec_endpoint.log`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 null 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 test case failed: Expected results are different from actual ones: --- want
+++ got
@@ -1,7 +1,7 @@
 {
     "expected": [
         {
-            "@timestamp": "2022-10-04T10:51:33.000Z",
+            "@timestamp": "2023-10-04T10:51:33.000Z",
             "destination": {
                 "address": "216.160.83.61",
                 "as": {
 
 ```
</p></details>
</ul>
    
##### `Check integrations / hadoop / hadoop: check / pipeline test: test-datanode-metrics.json – hadoop.datanode`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 null 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 test case failed: Expected results are different from actual ones: --- want
+++ got
@@ -29,7 +29,7 @@
                         "remaining": 15825682432
                     },
                     "estimated_capacity_lost_total": 0,
-                    "last_volume_failure_date": "2022-01-01T00:00:00.000Z",
+                    "last_volume_failure_date": "2023-01-01T00:00:00.000Z",
                     "volumes": {
                         "failed": 0
                     }
 
 ```
</p></details>
</ul>
    
##### `Check integrations / hadoop / hadoop: check / pipeline test: test-application-metrics.log – hadoop.application`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 null 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 test case failed: Expected results are different from actual ones: --- want
+++ got
@@ -23,8 +23,8 @@
                     "running_containers": -1,
                     "time": {
                         "elapsed": 35114,
-                        "finished": "2022-01-01T00:00:00.258Z",
-                        "started": "2022-01-01T00:00:00.144Z"
+                        "finished": "2023-01-01T00:00:00.258Z",
+                        "started": "2023-01-01T00:00:00.144Z"
                     },
                     "vcore_seconds": 57
                 }
@@ -56,8 +56,8 @@
                     "running_containers": -1,
                     "time": {
                         "elapsed": 9925,
-                        "finished": "2022-01-01T00:00:00.835Z",
-                        "started": "2022-01-01T00:00:00.910Z"
+                        "finished": "2023-01-01T00:00:00.835Z",
+                        "started": "2023-01-01T00:00:00.910Z"
                     },
                     "vcore_seconds": 7
                 }
 
 ```
</p></details>
</ul>
    
##### `Check integrations / cisco_ios / cisco_ios: check / pipeline test: test-asr920.log – cisco_ios.log`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 null 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 test case failed: Expected results are different from actual ones: --- want
+++ got
@@ -234,7 +234,7 @@
             ]
         },
         {
-            "@timestamp": "2022-08-03T08:11:02.204Z",
+            "@timestamp": "2023-08-03T08:11:02.204Z",
             "cisco": {
                 "ios": {
                     "facility": "LINEPROTO",
@@ -266,7 +266,7 @@
             ]
         },
         {
-            "@timestamp": "2022-08-03T08:08:47.142Z",
+            "@timestamp": "2023-08-03T08:08:47.142Z",
             "cisco": {
                 "ios": {
                     "access_list": "ACL_CE-SECURITY",
@@ -334,7 +334,7 @@
             ]
         },
         {
-            "@timestamp": "2022-08-03T08:04:47.140Z",
+            "@timestamp": "2023-08-03T08:04:47.140Z",
             "cisco": {
                 "ios": {
                     "access_list": "ACL_CE-SECURITY",
@@ -406,7 +406,7 @@
             ]
         },
         {
-            "@timestamp": "2022-08-03T08:09:55.769Z",
+            "@timestamp": "2023-08-03T08:09:55.769Z",
             "cisco": {
                 "ios": {
                     "facility": "SNMP-SW1",
 
 ```
</p></details>
</ul>
    
##### `Check integrations / cisco_ios / cisco_ios: check / pipeline test: test-cisco-ios.log – cisco_ios.log`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 null 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 test case failed: Expected results are different from actual ones: --- want
+++ got
@@ -1,7 +1,7 @@
 {
     "expected": [
         {
-            "@timestamp": "2022-02-08T04:00:47.272Z",
+            "@timestamp": "2023-02-08T04:00:47.272Z",
             "cisco": {
                 "ios": {
                     "access_list": "177",
@@ -55,7 +55,7 @@
             ]
         },
         {
-            "@timestamp": "2022-02-09T04:00:47.272Z",
+            "@timestamp": "2023-02-09T04:00:47.272Z",
             "cisco": {
                 "ios": {
                     "access_list": "INBOUND-ON-F11",
@@ -112,7 +112,7 @@
             ]
         },
         {
-            "@timestamp": "2022-02-10T04:00:47.272Z",
+            "@timestamp": "2023-02-10T04:00:47.272Z",
             "cisco": {
                 "ios": {
                     "access_list": "171",
@@ -165,7 +165,7 @@
             ]
         },
         {
-            "@timestamp": "2022-05-03T19:11:32.619Z",
+            "@timestamp": "2023-05-03T19:11:32.619Z",
             "cisco": {
                 "ios": {
                     "access_list": "ACL-IPv6-E0/0-IN/10",
@@ -238,7 +238,7 @@
             ]
         },
         {
-            "@timestamp":  [...]

2023-01-11 14:34 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`351/351`) | :green_heart: 
Files | 97.959% (`576/588`) | :-1: -2.041
Classes | 97.959% (`576/588`) | :-1: -2.041
Methods | 91.184% (`5689/6239`) | :+1: 66.184
Lines | 91.563% (`120041/131102`) | :-1: -8.437
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-01-11 14:42 UTC, mrodm commented on docs/developer_workflow_design_build_test_integration.md
> +    ```
This list refers to actions when the version of the package needs to be updated with a set of Pull Requests.

What about adding this information as a new subsection in the a generic guideline doc here ? https://github.com/elastic/integrations/blob/main/docs/generic_guidelines.md 

WDYT ? @tetianakravchenko

2023-01-11 17:11 UTC, tetianakravchenko commented on docs/developer_workflow_design_build_test_integration.md
> +    ```
@mrodm generic_guidance seems to provide a more generic information, without manifest examples, would maybe https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md#manifest-files-1 be the better place? WDYT?

2023-01-11 17:13 UTC, tetianakravchenko commented on docs/developer_workflow_design_build_test_integration.md
> +    ```
so you mean smth like https://github.com/elastic/integrations/pull/4970/commits/4bb0c611ec10bc67507a6616e8a77175569ed3a9#diff-7829d8dddd64275f212ffcac52de0d8f8de3f6973c89a385c66be7072d3f75d7R110 ?

2023-01-11 17:38 UTC, gsantoro commented on docs/tips_for_building_integrations.md
> +   > Note: The package version with such condition will be only available in Kibana version >=8.7.0
yes... and personally I would slightly rephrase it something like

```
It's safe to release an integration that is only compatible with a future Kibana version (meaning a release that is not out yet). In that case the integration will be available in the package registry but nobody will be able to upgrade to the new version until that Kibana version has been released.
```

WDYT?

2023-01-12 08:28 UTC, mrodm commented on docs/developer_workflow_design_build_test_integration.md
> +    ```
That doc looks good :+1:

2023-01-12 08:28 UTC, mrodm approved these changes

2023-01-12 09:31 UTC, tetianakravchenko commented on docs/tips_for_building_integrations.md
> +   > Note: The package version with such condition will be only available in Kibana version >=8.7.0
done. https://github.com/elastic/integrations/pull/4970/commits/60202c2265f35ada003ab00e0ea824b495182dba

2023-01-12 13:49 UTC, tetianakravchenko commented on docs/tips_for_building_integrations.md
> +   > Note: The package version with such condition will be only available in Kibana version >=8.7.0
@gsantoro actually I am not sure if it correct looking on https://github.com/elastic/integrations/pull/4948#pullrequestreview-1244499389

2023-01-12 17:28 UTC, constanca-m commented on docs/tips_for_building_integrations.md
> +   > Note: Changing dashboards and visualizations using an unreleased version of Kibana might be unsafe since the Kibana Team might make changes to the Kibana code and potentially the data models. Th
The changes on the beats repository were backported to version 8.6. I will wait until they are available (I'm guessing on 8.6.1), and then I will continue the integrations PR @gsantoro

2023-01-17 11:29 UTC, gsantoro approved these changes

2023-01-17 16:10 UTC, tetianakravchenko commented
@mrodm could you please have a look?

tests are failing because of the packages tests,  and also `Squash and merge` button is inactive for me, I guess because of the failing tests, could you please review/merge it?

maybe it is possible to exclude the `docs/` from the pipeline?

2023-01-17 17:05 UTC, mrodm commented
> @mrodm could you please have a look?
> 
> tests are failing because of the packages tests, and also `Squash and merge` button is inactive for me, I guess because of the failing tests, could you please merge it as a codeowner?
> 
> maybe it is possible to exclude the `docs/` from the pipeline?

@tetianakravchenko those CI errors are unrelated, there is an issue about this 
https://github.com/elastic/integrations/issues/4950

Is this PR already ready to be merged ? As these are docs, I could force the merge it if it is everything ready.

2023-01-17 20:44 UTC, tetianakravchenko commented
@mrodm 
> Is this PR already ready to be merged ? As these are docs, I could force the merge it if it is everything ready.

yes, it is ready

2023-01-18 08:49 UTC, merged