use lens metric instead of TSVB gauge
elastic/integrations pull request #4975
Opened 2023-01-11 23:24 UTC by andrewctate

## What does this PR do?

- system and host metric overview dashboards now use Lens metrics instead of TSVB gauges.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2023-01-11 23:41 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4975/detail/PR-4975/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4975/detail/PR-4975/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4975/detail/PR-4975/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4975/detail/PR-4975/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_4975.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-01-11T23:14:52.582Z&rangeTo=2023-01-11T23:34:52.582Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=0284343b43314c154fd8ad9b955bcc73&transactionId=85ce5db2e1abe8bb)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-01-11T23:24:52.582+0000


* Duration: 16 min 28 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![3](https://img.shields.io/badge/3%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4975/detail/PR-4975/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Boot up the Elastic stack`
<ul>
<li>Took 4 min 48 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-4975/runs/1/steps/1026/log/?start=0">here</a></li>
<li>Description: <code>../../build/elastic-package stack up -d -v --version 8.1.0</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-4975/runs/1/steps/1061/log/?start=0">here</a></li>

</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-4975/runs/1/steps/1074/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-01-12 00:10 UTC, elasticmachine commented
## :broken_heart: Tests Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4975/detail/PR-4975/2//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4975/detail/PR-4975/2//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4975/detail/PR-4975/2//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4975/detail/PR-4975/2//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_4975.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-01-11T23:46:02.824Z&rangeTo=2023-01-12T00:06:02.824Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=7597b7215a8d0b1b69204f1a4d34cb01&transactionId=4af96791b64ce703)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-01-11T23:56:02.824+0000


* Duration: 15 min 42 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 1  |
| Passed       | 244  |
| Skipped      | 0 |
| Total        | 245   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->

  ### Test errors [![1](https://img.shields.io/badge/1%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4975/detail/PR-4975/2//tests)
<details><summary>Expand to view the tests failures</summary><p>
    
    
##### `pipeline test: test-multiline.log – system.auth`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 null 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 test case failed: Expected results are different from actual ones: --- want
+++ got
@@ -1,7 +1,7 @@
 {
     "expected": [
         {
-            "@timestamp": "2022-05-21T21:54:44.000Z",
+            "@timestamp": "2023-05-21T21:54:44.000Z",
             "ecs": {
                 "version": "8.0.0"
             },
@@ -27,7 +27,7 @@
             }
         },
         {
-            "@timestamp": "2022-05-21T21:54:45.000Z",
+            "@timestamp": "2023-05-21T21:54:45.000Z",
             "ecs": {
                 "version": "8.0.0"
             },
 
 ```
</p></details>
</ul>
    
</p></details>


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-4975/detail/PR-4975/2//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Test integration: system`
<ul>
<li>Took 2 min 55 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-4975/runs/2/steps/1051/log/?start=0">here</a></li>
<li>Description: <code>                                eval "$(../../build/elastic-package stack shellinit)"                                ../../build/elastic-package test -v --report-format xUnit --report-output file --test-coverage                                </code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-4975/runs/2/steps/1155/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-01-12 00:10 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`3/3`) | :green_heart: 
Files | 100.0% (`4/4`) | :green_heart: 
Classes | 100.0% (`4/4`) | :green_heart: 
Methods | 75.806% (`47/62`) | :+1: 50.806
Lines | 98.793% (`2702/2735`) | :-1: -1.207
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-01-18 18:17 UTC, andrewctate commented
failure may relate to https://github.com/elastic/integrations/issues/4950

2023-01-25 15:51 UTC, drewdaemon commented
Relevant discussion: https://github.com/elastic/sdh-kibana/issues/3493

2023-01-31 15:33 UTC, leehinman requested changes
Overall looks good, just some questions on the queries, especially "NOT system.network.name : l*"

2023-01-31 15:33 UTC, leehinman commented on packages/system/kibana/dashboard/system-79ffd6e0-faa0-11e6-947f-177f697178b8.json
> +                    "query": "host.name:\"docker-fleet-agent\""
Is this supposed to be here?  I don't think this dashboard is limited to docker-fleet-agent

2023-01-31 15:33 UTC, leehinman commented on packages/system/kibana/dashboard/system-79ffd6e0-faa0-11e6-947f-177f697178b8.json
> +                                "query": "NOT system.network.name : l*"
what is this query for?

2023-01-31 15:33 UTC, leehinman commented on packages/system/kibana/dashboard/system-79ffd6e0-faa0-11e6-947f-177f697178b8.json
> +                                "query": "NOT system.network.name : l*"
what is this query for?

2023-01-31 15:33 UTC, leehinman commented on packages/system/kibana/dashboard/system-79ffd6e0-faa0-11e6-947f-177f697178b8.json
> +                                "query": "NOT system.network.name : l*"
and this query?

2023-01-31 15:33 UTC, leehinman commented on packages/system/kibana/dashboard/system-79ffd6e0-faa0-11e6-947f-177f697178b8.json
> +                                "query": "NOT system.network.name : l*"
same here

2023-01-31 15:33 UTC, leehinman commented on packages/system/kibana/dashboard/system-Metrics-system-overview.json
> -                                "query": "data_stream.dataset : \"system.memory\""
do we still want this query?

2023-01-31 15:33 UTC, leehinman commented on packages/system/kibana/dashboard/system-Metrics-system-overview.json
> +                                "query": ""
do we still want this query?

2023-02-01 07:22 UTC, ruflin commented on packages/system/kibana/dashboard/system-Metrics-system-overview.json
> +                                "query": ""
It is key that we prefilter on dataset. Same above.

2023-02-01 10:25 UTC, gvnmagni commented on packages/system/kibana/dashboard/system-79ffd6e0-faa0-11e6-947f-177f697178b8.json
> +                    "query": "host.name:\"docker-fleet-agent\""
honestly, I don't know. When we updated these visualizations we tried to replicate what was happening with the previous version of them and given my lack of competences on how data is structured behind these chart I had to intensively rely for help on Joe Reuter, who I believe originally made those. So sometimes I just followed instructions and I can't actually remember if these queries came from him or this is just an error (which would be weird, I have been very careful in not creating anything that could be unexpected).

Same happens for the next comments, the ones related to the "NOT system.network.name" query. Is it possible that is was made to avoid having dirty data of some sort? What does happen to the values if we remove these queries?

2023-02-01 14:52 UTC, drewdaemon commented on packages/system/kibana/dashboard/system-79ffd6e0-faa0-11e6-947f-177f697178b8.json
> +                    "query": "host.name:\"docker-fleet-agent\""
Makes sense, @gvnmagni ! Don't worry, I will evaluate the queries here and address this feedback. Thanks for your help. 🙏

2023-09-27 20:51 UTC, drewdaemon commented
Closing in favor of https://github.com/elastic/integrations/pull/6743

2023-09-27 20:51 UTC, closed without merging