Update kube state metrics version
elastic/integrations pull request #5061
Opened 2023-01-19 15:22 UTC by constanca-m

## What does this PR do?

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2023-01-19 15:51 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5061/detail/PR-5061/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5061/detail/PR-5061/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5061/detail/PR-5061/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5061/detail/PR-5061/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_5061.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-01-19T15:12:38.901Z&rangeTo=2023-01-19T15:32:38.901Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=07fa6360af0f6ba069dc9e0ed8941480&transactionId=d5c21e4f88e68d98)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-01-19T15:22:38.901+0000


* Duration: 28 min 18 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 91  |
| Skipped      | 0 |
| Total        | 91   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-01-19 15:51 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 
Classes | 100.0% (`0/0`) | :green_heart: 
Methods | 94.872% (`74/78`) | :+1: 34.112
Lines | 100.0% (`0/0`) | :green_heart: 1.207
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-01-19 15:55 UTC, tetianakravchenko approved these changes

2023-01-19 15:57 UTC, gsantoro requested changes
can we use kustomize here to update the manifests to the latest version?

2023-01-19 15:59 UTC, gsantoro commented
@constanca-m I am thinking of a kustomization.yml file + a taskfile to achieve the following goals:
- Use a taskfile with a command to generate the manifest for a specific version of kube-state-metrics
- have all the resources necessary for kube-state-metrics in a single file so that we can distinguish what is "custom" (specific to this package) and what is off the shelf (aka kube-state-metrics)

2023-01-19 16:37 UTC, constanca-m commented
Changing approach to the one mentioned in https://github.com/elastic/elastic-package/issues/1102.

2023-01-25 12:46 UTC, tetianakravchenko commented
@gsantoro for the kustomize improvements was created this issue https://github.com/elastic/elastic-package/issues/1102, meanwhile we would like to merge this PR to unblock another PR - https://github.com/elastic/integrations/pull/5065

2023-01-25 12:53 UTC, gsantoro approved these changes

2023-01-25 12:54 UTC, merged