Fix parsing error when no client port exists
elastic/integrations pull request #5073
Opened 2023-01-20 21:17 UTC by nicpenning

Pipeline fails to parse Azure Application Gateway logs when the client port field exists with no data.

```
error.message : For input string: \"\" convert
```

## What does this PR do?

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

2023-01-20 21:20 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5073/detail/PR-5073/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5073/detail/PR-5073/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5073/detail/PR-5073/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5073/detail/PR-5073/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-01-20T21:07:34.224Z&rangeTo=2023-01-20T21:27:34.224Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=49f24a7bf3c6c7f1374eed91f23a002f&transactionId=fa5bbabe7ce21081)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-01-20T21:17:34.224+0000


* Duration: 3 min 54 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5073/detail/PR-5073/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Load a resource file from a library`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-5073/runs/1/steps/81/log/?start=0">here</a></li>
<li>Description: <code>approval-list/elastic/integrations.yml</code></l1>
</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-5073/runs/1/steps/89/log/?start=0">here</a></li>
<li>Description: <code>githubApiCall: The REST API call https://api.github.com/orgs/elastic/members/nicpenning return the message : java.lang.Exception: httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/nicpenning : httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/nicpenning : Code: 404Error: {"message":"User does not exist or is not a member of the organization","documentation_url":"https://docs.github.com/rest/reference/orgs#check-organization-membership-for-a-user"}</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-01-24 11:25 UTC, zmoog commented
Hey @nicpenning, thank you for contributing to the Azure Application Gateway integration with this fix!

2023-01-24 11:45 UTC, zmoog commented on packages/azure/data_stream/application_gateway/elasticsearch/ingest_pipeline/default.yml
> +      if: ctx.json.properties?.clientPort != ""
Hey @nicpenning, could you add a sample document to `_dev/test/pipeline`?

I am interested in seeing what value this field has and adding a test to define the expected outcome.

2023-01-24 12:29 UTC, nicpenning commented on packages/azure/data_stream/application_gateway/elasticsearch/ingest_pipeline/default.yml
> +      if: ctx.json.properties?.clientPort != ""
Yes, I can do that.

2023-01-24 13:30 UTC, nicpenning commented on packages/azure/data_stream/application_gateway/elasticsearch/ingest_pipeline/default.yml
> +      if: ctx.json.properties?.clientPort != ""
Do you know if it is wise to use the event.original in the document that contains the error.message or if there is a better way to retrieve the rawest version of the log?

2023-01-25 02:11 UTC, nicpenning commented
When I was going through and trying to provide some example data I stumbled upon another issue which was the timestamp in the I had was using timeStamp so I add that to the pipeline.

2023-01-26 22:24 UTC, zmoog requested changes

2023-01-26 22:24 UTC, zmoog commented on packages/azure/data_stream/application_gateway/elasticsearch/ingest_pipeline/default.yml
>    - rename:
The document must contain a `@timestamp` field — all lowercase. 

This is required by the data stream, see for https://www.elastic.co/guide/en/elasticsearch/reference/current/data-streams.html#backing-indices more details.

Another option is to rename `json.timeStamp` —> `json.timestamp` right after `event.original`.

It is a weird field name: does Azure really produce a JSON document with a `timeStamp` field?

2023-01-26 22:24 UTC, zmoog commented on packages/azure/data_stream/application_gateway/elasticsearch/ingest_pipeline/default.yml
> +      if: ctx.json.properties?.clientPort != ""
I believe `event.original` is okay for this purpose. 

Usually, it the pipeline just [renames](https://github.com/elastic/integrations/blob/bf7ff198341386cfaddfa8c4a5cb77ab595edd8f/packages/azure/data_stream/application_gateway/elasticsearch/ingest_pipeline/default.yml#L16-L19) the `message` field into `event.original` without changes. You get the same JSON document Azure publishes on the Event Hub.

2023-01-26 22:24 UTC, zmoog commented on packages/azure/data_stream/application_gateway/elasticsearch/ingest_pipeline/default.yml
> +      if: ctx.json.properties?.clientPort != ""
@nicpenning, thank you for the sample logs, they're quite interesting.

2023-01-27 01:29 UTC, nicpenning commented on packages/azure/data_stream/application_gateway/elasticsearch/ingest_pipeline/default.yml
>    - rename:
Whoops, yes, you are correct, @timestamp is what it should be. I will adjust the pipeline to lowercase the timestamp. Because the pipeline already had 2 different conversions, I tried to stay consistent and make it a 3rd possibility of what it shows.

Does it make a difference if it is coming from the Gov cloud perhaps?

I would be happy to try and get the raw log in a different way if you have a suggestion on how to do that.

2023-01-27 12:51 UTC, zmoog commented on packages/azure/data_stream/application_gateway/elasticsearch/ingest_pipeline/default.yml
> +      ignore_missing: true
The [lowercase](https://www.elastic.co/guide/en/elasticsearch/reference/current/lowercase-processor.html) processor lowers the case of the field value, not the name. 

You can test the ingest pipeline in the Dev Tools in Kibana. 

For example, if I create a test pipeline like this one:

```
PUT _ingest/pipeline/zmoog-test
{
  "processors": [
    {
      "lowercase": {
        "field": "json.timeStamp",
        "ignore_missing": true,
        "ignore_failure": false
      }
    }
  ]
}
```

I can then send test documents like this one:

```
POST _ingest/pipeline/zmoog-test/_simulate
{
  "docs": [{
    "_source": {
      "json": {
        "timeStamp": "Maurizio Branca"
      }
    }
  }]
}
```

This is the final result:

```
{
  "docs": [
    {
      "doc": {
        "_index": "_index",
        "_id": "_id",
        "_version": "-3",
        "_source": {
          "json": {
            "timeStamp": "maurizio branca"
          }
        },
        "_ingest": {
          "timestamp": "2023-01-27T12:28:56.960504597Z"
        }
      }
    }
  ]
}
```

2023-01-27 12:51 UTC, zmoog commented on packages/azure/data_stream/application_gateway/elasticsearch/ingest_pipeline/default.yml
> +      ignore_missing: true
To rename the field name, you can use the [rename](https://www.elastic.co/guide/en/elasticsearch/reference/current/rename-processor.html) processor.

2023-01-27 12:51 UTC, zmoog commented on packages/azure/data_stream/application_gateway/elasticsearch/ingest_pipeline/default.yml
>    - rename:
> Does it make a difference if it is coming from the Gov cloud, perhaps?

Oh, interesting! Is this sample document coming from Azure Gov cloud?

I experienced different responses from some services hosted on Azure accounts with different contracts (for example, billing data structures for Enterprise Agreement vs. MCA contracts are very different), so it's not out of the question that Gov and Public cloud may have slightly different responses.

2023-01-27 13:07 UTC, nicpenning commented on packages/azure/data_stream/application_gateway/elasticsearch/ingest_pipeline/default.yml
>    - rename:
Yes, this is from the Azure Gov Cloud.

2023-01-27 13:15 UTC, nicpenning commented
Not sure where my comment went, but yes, this data is from the Azure Gov cloud. 😀

2023-01-27 15:17 UTC, zmoog requested changes

2023-01-27 15:17 UTC, zmoog commented on packages/azure/data_stream/application_gateway/elasticsearch/ingest_pipeline/default.yml
> +      ignore_missing: true
We need to use the `rename` processor instead of the `lowercase` processor.

2023-01-27 15:50 UTC, nicpenning commented on packages/azure/data_stream/application_gateway/elasticsearch/ingest_pipeline/default.yml
> +      ignore_missing: true
Got it, I will fix.

2023-01-27 15:53 UTC, nicpenning commented
Okay @zmoog, how is everything looking now?

2023-01-31 21:40 UTC, zmoog approved these changes

2023-01-31 21:41 UTC, zmoog commented
/test

2023-01-31 21:55 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`9/9`) | :green_heart: 
Files | 85.0% (`17/20`) | :-1: -15.0
Classes | 85.0% (`17/20`) | :-1: -15.0
Methods | 80.745% (`130/161`) | :-1: -19.255
Lines | 85.607% (`2510/2932`) | :+1: 9.457
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-02-03 15:19 UTC, zmoog commented
> Any further action needed for this? I don't want this to get too stale.

Yep, someone must check and fix the errors in CI pipeline. I can't merge the PR if they aren't all green.

Let me take a look at the failing one.

2023-02-03 15:19 UTC, zmoog commented
/test

2023-02-03 16:17 UTC, merged

2023-02-03 16:19 UTC, zmoog commented
@nicpenning, the bot will comment on this PR when the new version is available.

Thank you for your contribution and your patience in these back and forth!

2023-02-03 16:37 UTC, elasticmachine commented
Package azure - 1.5.6 containing this change is available at https://epr.elastic.co/search?package=azure