Match logs without junos@ip
elastic/integrations pull request #5125
Opened 2023-01-27 09:01 UTC by ernst-s

Change grok pattern to match SRX logs which don't containt the junos@ip before the other fields. Prevents stripping of the first field.

## What does this PR do?

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

2023-01-27 09:05 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5125/detail/PR-5125/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5125/detail/PR-5125/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5125/detail/PR-5125/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5125/detail/PR-5125/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-01-27T08:52:02.919Z&rangeTo=2023-01-27T09:12:02.919Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=ec7b359693cfc11e628a4f2437e5bcbb&transactionId=936cf06a0c0a56b3)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-01-27T09:02:02.919+0000


* Duration: 3 min 12 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5125/detail/PR-5125/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Load a resource file from a library`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-5125/runs/1/steps/81/log/?start=0">here</a></li>
<li>Description: <code>approval-list/elastic/integrations.yml</code></l1>
</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-5125/runs/1/steps/89/log/?start=0">here</a></li>
<li>Description: <code>githubApiCall: The REST API call https://api.github.com/orgs/elastic/members/ernst-s return the message : java.lang.Exception: httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/ernst-s : httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/ernst-s : Code: 404Error: {"message":"User does not exist or is not a member of the organization","documentation_url":"https://docs.github.com/rest/reference/orgs#check-organization-membership-for-a-user"}</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-01-27 09:56 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2023-01-31 08:11 UTC, kcreddy requested changes
Hey @ernst-s 
Could you please [sign the CLA](https://www.elastic.co/contributor-agreement) and make following changes to the PR:

1. Add `changelog.yml` entry and update version in `manifest.yml`
2. Add your test log sample to[ this file](https://github.com/elastic/integrations/blob/main/packages/juniper_srx/data_stream/log/_dev/test/pipeline/test-flow.log) and [run package tests](https://www.elastic.co/guide/en/integrations-developer/current/pipeline-testing.html)

2023-01-31 13:56 UTC, ernst-s commented
> 

I signed the CLA but for some reason the check keeps failing

2023-01-31 16:27 UTC, ernst-s commented
/test

2023-02-02 15:43 UTC, kcreddy commented on packages/juniper_srx/changelog.yml
> +- version: "1.8.1"
@ernst-s Could you bump the minor instead of patch version? Also change the `manifest.yml`
```suggestion
- version: "1.9.0"
```

2023-02-02 15:43 UTC, kcreddy commented
/test

2023-02-02 16:01 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`1/1`) | :green_heart: 
Files | 100.0% (`7/7`) | :green_heart: 16.667
Classes | 100.0% (`7/7`) | :green_heart: 16.667
Methods | 100.0% (`50/50`) | :green_heart: 10.526
Lines | 70.799% (`1525/2154`) | :-1: -14.965
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-02-02 16:09 UTC, ernst-s commented on packages/juniper_srx/changelog.yml
> +- version: "1.8.1"
Done

2023-02-03 05:53 UTC, kcreddy commented
/test

2023-02-03 10:34 UTC, kcreddy approved these changes
LGTM

2023-02-03 10:34 UTC, merged

2023-02-03 10:54 UTC, elasticmachine commented
Package juniper_srx - 1.9.0 containing this change is available at https://epr.elastic.co/search?package=juniper_srx