adding readme for cspm & kspm policy templates
elastic/integrations pull request #5133
Opened 2023-01-28 14:52 UTC by tinnytintin10

A PR to only provide the content I want us to use for the KSPM and CSPM policy templates. 

cc @oren-zohar @kfirpeled @tehilashn

2023-01-28 15:06 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5133/detail/PR-5133/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5133/detail/PR-5133/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5133/detail/PR-5133/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5133/detail/PR-5133/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_5133.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-01-28T14:42:27.946Z&rangeTo=2023-01-28T15:02:27.946Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=67d14df4ccd5d34859ce3590ccf273ce&transactionId=1ec9f493438d2dc4)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-01-28T14:52:27.946+0000


* Duration: 14 min 34 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 2  |
| Skipped      | 0 |
| Total        | 2   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-01-28 15:06 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 1.937
Classes | 100.0% (`0/0`) | :green_heart: 1.937
Methods | 25.0% (`1/4`) | :-1: -66.852
Lines | 100.0% (`0/0`) | :green_heart: 7.19
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-02-08 11:34 UTC, kfirpeled commented
@tinnytintin10 can you replace the description and names inside manifest.yml as well? we need to remove that placeholder over there

2023-02-11 00:03 UTC, tinnytintin10 commented
@kfirpeled @oren-zohar can you please review and merge? thanks!

2023-02-12 16:07 UTC, oren-zohar requested changes

2023-02-12 16:07 UTC, oren-zohar commented on packages/cloud_security_posture/docs/README.md
> +KSPM discovers and evaluates the components that make up your Kubernetes cluster against hardening guidelines defined by the Center for Internet Security (CIS) to help you identify and remediate conf
maybe link the CIS site?

2023-02-12 16:07 UTC, oren-zohar commented on packages/cloud_security_posture/docs/README.md
> +KSPM discovers and evaluates the components that make up your Kubernetes cluster against hardening guidelines defined by the Center for Internet Security (CIS) to help you identify and remediate conf
```suggestion
KSPM discovers and evaluates the components that make up your Kubernetes cluster against hardening guidelines defined by the [Center for Internet Security](https://www.cisecurity.org/) (CIS) to help you identify and remediate configurations risks like:
```

2023-02-12 16:07 UTC, oren-zohar commented on packages/cloud_security_posture/docs/README.md
> +- Kubelete servers that allow anonymous Auth
```suggestion
- Kubelete servers that allow anonymous auth
```

2023-02-12 16:07 UTC, oren-zohar commented on packages/cloud_security_posture/docs/README.md
> +- Pod Security Policies (PSPs) that enable the admission of privileged containers
PSPs are deprecated, maybe we can a different example

2023-02-12 16:07 UTC, oren-zohar commented on packages/cloud_security_posture/docs/README.md
> +After deploying the CSPM and/or KSPM integration, the pages described in the table below will begin to get populated with security posture data. Please read the respective use cases section for [CSPM
implies that we support them both at the same time?

2023-02-13 12:35 UTC, tinnytintin10 commented on packages/cloud_security_posture/docs/README.md
> +After deploying the CSPM and/or KSPM integration, the pages described in the table below will begin to get populated with security posture data. Please read the respective use cases section for [CSPM
Updated the paragraph to be a bit more clear. 

https://github.com/elastic/integrations/pull/5133/commits/6749cff839ca439d77885bd0a39adce5f866a789

2023-02-13 12:40 UTC, tinnytintin10 commented on packages/cloud_security_posture/docs/README.md
> +- Pod Security Policies (PSPs) that enable the admission of privileged containers
used a different example:

https://github.com/elastic/integrations/pull/5133/commits/6d09e28196bc3e52d384f4511cd3a42e9c6a54b5

2023-02-14 21:54 UTC, bmorelli25 commented on packages/cloud_security_posture/docs/README.md
> +And much more! For a complete overview of CSPM, including step-by-step getting started guidance, check out [CSPM's documentation](https://ela.st/cspm)
```suggestion
And much more! For a complete overview of CSPM, including step-by-step getting started guidance, check out [CSPM's documentation](https://ela.st/cspm).
```

2023-02-15 13:51 UTC, merged

2023-02-15 14:11 UTC, elasticmachine commented
Package cloud_security_posture - 1.2.11 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture