Adding documentationnot not supporting non default namespace
elastic/integrations pull request #5209
Opened 2023-02-08 10:52 UTC by ofiriro3

## What does this PR do?
This PR is adding a paragraph in our integration README, that the cloud security posture plugin support installation only using the `default` namespace.
 

### What does this PR include?
Only readme changes.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues
- Relates https://github.com/elastic/security-team/issues/5831

2023-02-08 10:54 UTC, ofiriro3 commented
I added the new changelog, and run all the tests. 

Screenshot attached:
<img width="1525" alt="image" src="https://user-images.githubusercontent.com/19221736/217503858-ccb8b9cf-c3c8-4276-8e7e-dce34f5c5beb.png">

Ready for review

2023-02-08 11:07 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5209/detail/PR-5209/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5209/detail/PR-5209/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5209/detail/PR-5209/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5209/detail/PR-5209/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_5209.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-02-08T10:42:50.433Z&rangeTo=2023-02-08T11:02:50.433Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=9a0a80797dbc9d5f872ea5c346ac52b5&transactionId=dffa8bfae71a9bd7)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-02-08T10:52:50.433+0000


* Duration: 14 min 7 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 2  |
| Skipped      | 0 |
| Total        | 2   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-02-08 11:07 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 
Classes | 100.0% (`0/0`) | :green_heart: 
Methods | 25.0% (`1/4`) | :grey_exclamation: 
Lines | 100.0% (`0/0`) | :green_heart: 
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-02-08 11:33 UTC, jsoriano approved these changes
:+1:

2023-02-08 11:42 UTC, kfirpeled approved these changes
LGTM

2023-02-08 11:55 UTC, kfirpeled commented on packages/cloud_security_posture/docs/README.md
> +Failing to install the integration using the default namespace will result in an invalid integration state.
_nit_ maybe it is just my english, but I would go with:
`The integration will be invalid if it is not installed using the default namespace`

2023-02-08 12:05 UTC, ofiriro3 commented on packages/cloud_security_posture/docs/README.md
> +Failing to install the integration using the default namespace will result in an invalid integration state.
I don't mind changing it, I am just waiting for @tinnytintin10 to decide 🤖

2023-02-08 17:33 UTC, kfirpeled requested changes

2023-02-08 17:33 UTC, kfirpeled commented on packages/cloud_security_posture/changelog.yml
> +- version: "1.0.9"
the next available version for 1.0.* is 1.0.10 and not 1.0.9

2023-02-08 18:31 UTC, jsoriano approved these changes

2023-02-09 10:58 UTC, kfirpeled approved these changes

2023-02-11 00:10 UTC, tinnytintin10 requested changes

2023-02-11 00:10 UTC, tinnytintin10 commented on packages/cloud_security_posture/docs/README.md
> +Failing to install the integration using the default namespace will result in an invalid integration state.
@ofiriro3 let's update this section to the following:

> KSPM is currently only supported with the default namespace configuration in fleet. Changing the default namespace will result in the integration not working. 

I added the "in fleet" part just in case users get confused about what namespace we're talking about again (k8s or elastic).

2023-02-12 07:31 UTC, ofiriro3 commented
Content was verified:

<img width="1408" alt="image" src="https://user-images.githubusercontent.com/19221736/218298656-8d089d9c-fe39-4eb8-9ea5-50019e20ffad.png">
<img width="838" alt="image" src="https://user-images.githubusercontent.com/19221736/218298672-d1921b57-ce4a-4a1f-b344-4e4e3ad662b1.png">

2023-02-12 08:52 UTC, merged

2023-02-12 09:24 UTC, elasticmachine commented
Package cloud_security_posture - 1.0.10 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture