updating the CSP README.md with the default namespace documentation
elastic/integrations pull request #5211
Opened 2023-02-08 12:49 UTC by ofiriro3

## What does this PR do?

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2023-02-08 13:02 UTC, ofiriro3 commented
Validation finished - 

<img width="1564" alt="image" src="https://user-images.githubusercontent.com/19221736/217537198-9060eb04-12e3-4838-9357-69362c1e1613.png">

<img width="828" alt="image" src="https://user-images.githubusercontent.com/19221736/217537260-6a065624-1858-44f3-b08c-4add84b38a84.png">

2023-02-08 13:04 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5211/detail/PR-5211/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5211/detail/PR-5211/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5211/detail/PR-5211/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5211/detail/PR-5211/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_5211.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-02-08T12:39:56.885Z&rangeTo=2023-02-08T12:59:56.885Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=0094e6219ab7fb2af6cc5bcc96bf552a&transactionId=c41ac003c2a1b215)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-02-08T12:49:56.885+0000


* Duration: 14 min 12 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 2  |
| Skipped      | 0 |
| Total        | 2   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-02-08 13:04 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 
Classes | 100.0% (`0/0`) | :green_heart: 
Methods | 25.0% (`1/4`) | :grey_exclamation: 
Lines | 100.0% (`0/0`) | :green_heart: 
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-02-08 17:35 UTC, kfirpeled requested changes

2023-02-08 17:35 UTC, kfirpeled commented on packages/cloud_security_posture/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/4885
it doesn't look like the correct PR url, 5211

2023-02-09 13:23 UTC, ofiriro3 commented
/test

2023-02-11 00:12 UTC, tinnytintin10 requested changes

2023-02-11 00:12 UTC, tinnytintin10 commented on packages/cloud_security_posture/docs/README.md
> +KSPM is currently only supported with the default namespace configuration.
> KSPM is currently only supported with the default namespace configuration in fleet. Changing the default namespace will result in the integration not working. 

Let's update this section with the text above. I add the "in fleet" part just incase users get confused with what "namespace" we're talking about (k8s or elastic)

2023-02-12 15:14 UTC, ofiriro3 commented
Validation was performed after the text changes:
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/19221736/218319483-2ca54d6e-092b-4fa8-b4c8-627ab89498ac.png">

<img width="814" alt="image" src="https://user-images.githubusercontent.com/19221736/218319464-c08d317c-6642-4595-873a-da01c489d97c.png">

2023-02-12 17:45 UTC, merged

2023-02-12 18:05 UTC, elasticmachine commented
Package cloud_security_posture - 1.1.3 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture