Add vulnerability management integration
elastic/integrations pull request #5266
Opened 2023-02-14 04:48 UTC by amirbenun

## What does this PR do?

Add a new cloud security policy template for vulnerability management that will form as a new integration

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2023-02-14 05:07 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5266/detail/PR-5266/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5266/detail/PR-5266/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5266/detail/PR-5266/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5266/detail/PR-5266/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_5266.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-02-14T04:46:27.629Z&rangeTo=2023-02-14T05:06:27.629Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=144fb2ab34a4f1e46e1d3e46604b4b26&transactionId=0eae914b12ed52aa)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-02-14T04:56:27.629+0000


* Duration: 11 min 36 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![3](https://img.shields.io/badge/3%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5266/detail/PR-5266/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Update the Elastic stack`
<ul>
<li>Took 0 min 8 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-5266/runs/1/steps/1049/log/?start=0">here</a></li>
<li>Description: <code>../../build/elastic-package stack update -v --version 8.8.0</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-5266/runs/1/steps/1084/log/?start=0">here</a></li>

</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-5266/runs/1/steps/1097/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-02-14 19:38 UTC, opauloh commented
Hi @amirbenun,

Here's the icon for vulnerability management in case you want to include it in your PR 

SVG 

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="none" viewBox="0 0 32 32">
  <path fill="#00BFB3" fill-rule="evenodd" d="M11.05 2.086 6.808 6.329 16 15.52l9.192-9.192-4.242-4.243L16 7.036l-4.95-4.95Z" clip-rule="evenodd"/>
  <path fill="#FA744E" d="M4.686 19.764a8 8 0 0 1 0-11.314L16 19.764v11.313L4.686 19.763Z"/>
  <path fill="#343741" d="M27.314 8.45a8 8 0 0 1 0 11.314L16 31.077V19.763L27.314 8.45Z"/>
</svg>
```

File (to add to `packages/cloud_security_posture/img/logo_vulnerability_management.svg`)

![logo_vulnerability_management](https://user-images.githubusercontent.com/19270322/218839257-208e3d0e-1662-4024-acd9-b5f3b355e38f.svg)



Suggested changes to add to manifest.yaml

```yml
    icons:
      - src: /img/logo_vulnerability_management.svg
        title: Vulnerability Management logo
        size: 32x32
        type: image/svg+xml
```

2023-02-14 21:00 UTC, kfirpeled commented on packages/cloud_security_posture/data_stream/vulnerabilities/elasticsearch/ingest_pipeline/default.yml
> +    field: sample_field
please take a look at the ingest pipeline of findings, it should be the same

2023-02-14 21:00 UTC, kfirpeled commented on packages/cloud_security_posture/manifest.yml
> +  - name: vuln
`vuln_mgmt` just to keep it consistent

2023-02-20 13:48 UTC, kfirpeled commented on packages/cloud_security_posture/changelog.yml
> +- version: "1.3.0-next"
```suggestion
- version: "1.3.0-next"
- version: "1.3.0-preview"
```

We've found out that using `next` is not optimal since it is not updatable
Can you switch to `switch`

2023-02-20 13:52 UTC, kfirpeled commented on packages/cloud_security_posture/manifest.yml
> +  kibana.version: "^8.8.0"
make sure `version` is `1.3.0-preview`

2023-02-20 14:11 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 
Classes | 100.0% (`0/0`) | :green_heart: 
Methods | 25.0% (`2/8`) | :-1: -35.759
Lines | 100.0% (`0/0`) | :green_heart: 0.467
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-02-22 09:44 UTC, amirbenun commented
<img width="676" alt="image" src="https://user-images.githubusercontent.com/34831306/220582719-bb198447-9012-47e9-b63b-10594c211d64.png">

2023-02-22 11:12 UTC, kfirpeled approved these changes
LGTM

2023-02-22 11:23 UTC, oren-zohar requested changes

2023-02-22 11:23 UTC, oren-zohar commented on packages/cloud_security_posture/data_stream/vulnerabilities/elasticsearch/ingest_pipeline/default.yml
> +    value: '8.6.0'
shouldn't it be the same version as the ELK version?

2023-02-22 11:23 UTC, oren-zohar commented on packages/cloud_security_posture/data_stream/vulnerabilities/fields/cloudbeat.yml
> +      default_field: false
is this field relevant?

2023-02-22 11:23 UTC, oren-zohar commented on packages/cloud_security_posture/data_stream/vulnerabilities/manifest.yml
> +    description: Scan for Vulnerability Management over AWS account EC2 instances and docker images
Either 
```suggestion
    description: Vulnerability Management over AWS account EC2 instances and docker images
```
Or
```suggestion
    description: Scan for vulnerabilities over AWS account EC2 instances and docker images
```

2023-02-22 11:23 UTC, oren-zohar commented on packages/cloud_security_posture/manifest.yml
> +      - containers
is `containers` relevant for our VM solution? see the discussion [here](https://github.com/elastic/integrations/pull/5123#discussion_r1106513430)

2023-02-22 11:23 UTC, oren-zohar commented on packages/cloud_security_posture/manifest.yml
> +      - containers
We can also add `Vulnerability Management` IMO. See all subcategories [here](https://docs.google.com/spreadsheets/d/1NUR2ypKSjtHvrAq1MVK31SkVnzh7vQN8TptnwsayQmI/edit#gid=1476422042)

2023-02-22 14:51 UTC, amirbenun commented on packages/cloud_security_posture/data_stream/vulnerabilities/elasticsearch/ingest_pipeline/default.yml
> +    value: '8.6.0'
Honestly, I copied it from the findings data-stream. @kfirpeled  what is the reason it points to 8.6?

2023-02-22 16:00 UTC, oren-zohar requested changes

2023-02-22 16:00 UTC, oren-zohar commented on packages/cloud_security_posture/manifest.yml
> +      - Vulnerability Management
```suggestion
      - vulnerability_management
```
It looks like `Credential Management` is `credential_management` [here](https://github.com/elastic/integrations/blob/789938e1e5bdcc5ffc4b968db8eda12882bc25c5/packages/1password/manifest.yml#L10)

2023-02-22 16:02 UTC, oren-zohar commented on packages/cloud_security_posture/manifest.yml
> +      - Vulnerability Management
I think the [CI](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/PR-5266/11/pipeline) didn't like that in any case

2023-02-22 16:04 UTC, oren-zohar commented on packages/cloud_security_posture/manifest.yml
> +      - Vulnerability Management
Should work based on the [latest version](https://github.com/elastic/package-registry/releases/tag/v1.18.0) of the package-registry

2023-02-23 09:27 UTC, oren-zohar commented
Hey @mrodm the CI fails on the new `vulnerability_management` [category](https://github.com/elastic/package-registry/blob/0afd626e91e5525779d128ee4dec02aa3a65af69/categories/categories.yml#L134), wasn't that suppose to be supported in the [latest release](https://github.com/elastic/package-registry/releases/tag/v1.18.0)? are we missing something here?

```
[2023-02-22T18:24:16.518Z]    1. file "/var/lib/jenkins/workspace/est-manager_integrations_PR-5266/src/github.com/elastic/integrations/packages/cloud_security_posture/manifest.yml" is invalid: field policy_templates.2.categories.0: policy_templates.2.categories.0 must be one of the following: "analytics_engine", "application_observability", "app_search", "auditd", "authentication", "aws", "azure", "big_data", "cdn_security", "cloud", "config_management", "connector", "connector_client", "connector_package", "containers", "content_source", "crawler", "credential_management", "crm", "custom", "custom_logs", "database_security", "datastore", "dns_security", "edr_xdr", "elasticsearch_sdk", "elastic_stack", "email_security", "enterprise_search", "firewall_security", "google_cloud", "iam", "ids_ips", "infrastructure", "java_observability", "kubernetes", "language_client", "languages", "load_balancer", "message_queue", "monitoring", "monitoring_infrastructure", "native_search", "network", "network_security", "notification", "observability", "os_system", "process_manager", "productivity", "productivity_security", "proxy_security", "sdk_search", "security", "stream_processing", "support", "threat_intel", "ticketing", "version_control", "virtualization", "vpn_security", "web", "web_application_firewall", "websphere", "workplace_search"
```

2023-02-23 10:53 UTC, oren-zohar approved these changes

2023-02-23 11:03 UTC, merged

2023-02-23 12:09 UTC, mrodm commented
> Hey @mrodm the CI fails on the new `vulnerability_management` [category](https://github.com/elastic/package-registry/blob/0afd626e91e5525779d128ee4dec02aa3a65af69/categories/categories.yml#L134), wasn't that suppose to be supported in the [latest release](https://github.com/elastic/package-registry/releases/tag/v1.18.0)? are we missing something here?

Checking the `elastic-package` version used ([v0.74.0](https://github.com/elastic/elastic-package/releases/tag/v0.74.0)) here in the integrations repository, it does not contain the needed package-spec version ([v2.5.1](https://github.com/elastic/elastic-package/pull/1143)) that includes that new category.

A new release v0.75.0 has been created, once this version is updated in the integrations repository that category could be added in the packages.

2023-02-23 17:35 UTC, kfirpeled commented on packages/cloud_security_posture/data_stream/vulnerabilities/elasticsearch/ingest_pipeline/default.yml
> +    value: '8.6.0'
Because that is the ECS version we support, it is defined here: https://github.com/elastic/integrations/blob/main/packages/cloud_security_posture/_dev/build/build.yml

2023-04-18 20:57 UTC, elasticmachine commented
Package cloud_security_posture - 1.3.0-preview4 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-04-19 23:04 UTC, elasticmachine commented
Package cloud_security_posture - 1.3.0-preview5 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-04-21 08:06 UTC, elasticmachine commented
Package cloud_security_posture - 1.3.0-preview6 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-04-27 19:35 UTC, elasticmachine commented
Package cloud_security_posture - 1.3.0-preview7 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-05-04 07:11 UTC, elasticmachine commented
Package cloud_security_posture - 1.3.0-preview8 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-05-07 16:08 UTC, elasticmachine commented
Package cloud_security_posture - 1.3.0-preview9 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-05-10 07:10 UTC, elasticmachine commented
Package cloud_security_posture - 1.3.0-preview10 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-05-10 23:39 UTC, elasticmachine commented
Package cloud_security_posture - 1.3.0-preview91 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-05-25 01:56 UTC, elasticmachine commented
Package cloud_security_posture - 1.3.0 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-07-09 08:01 UTC, elasticmachine commented
Package cloud_security_posture - 1.3.1 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture