Enable setting condition on Prometheus Collector
elastic/integrations pull request #5317
Opened 2023-02-18 16:18 UTC by BenB196

Enhancement

## What does this PR do?

In the Prometheus Collector, switch from `condition` being a toggle for Leader Election only, to a text field.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

- Closes #5259

## Screenshots

2023-02-18 16:21 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5317/detail/PR-5317/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5317/detail/PR-5317/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5317/detail/PR-5317/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5317/detail/PR-5317/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-02-18T16:08:33.371Z&rangeTo=2023-02-18T16:28:33.371Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=7165c5186f882a0e9e5745c83d90691b&transactionId=a77a8e2c6abb0a8d)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-02-18T16:18:33.371+0000


* Duration: 3 min 54 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5317/detail/PR-5317/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Load a resource file from a library`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-5317/runs/1/steps/81/log/?start=0">here</a></li>
<li>Description: <code>approval-list/elastic/integrations.yml</code></l1>
</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-5317/runs/1/steps/89/log/?start=0">here</a></li>
<li>Description: <code>githubApiCall: The REST API call https://api.github.com/orgs/elastic/members/BenB196 return the message : java.lang.Exception: httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/BenB196 : httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/BenB196 : Code: 404Error: {"message":"User does not exist or is not a member of the organization","documentation_url":"https://docs.github.com/rest/reference/orgs#check-organization-membership-for-a-user"}</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-02-20 03:05 UTC, ChrsMark requested changes
Thanks for your PR!
TBH, I would like to have both options available. 
The leaderelection is quite specific and is quite handy for users to easily enable the integration on a cluster scope. The generic condition you are adding is also useful but should not replace the leaderelection one. Having both is not only better for the UX but is also useful in case one user wants to add a specific condition like "k8s.label == my-app" while having the leaderelection enabled too.

2023-02-20 11:52 UTC, BenB196 commented
Hi @ChrsMark understood. I thought about this being a potential option, but wasn't really sure how to implement it, Would you know if there is an existing integration that does something similar?

2023-02-20 13:01 UTC, BenB196 commented
Thinking about this a bit more, I suppose something like this might work:

```hbs
{{#if (or leaderelection condition)}}
condition: {{#if leaderelection}}${kubernetes_leaderelection.leader} == true{{/if}}{{#if condition}}{{ condition }}{{/if}}
{{/if}}
```

I can't really think of any use-cases that would require a user to set both leaderelection and a condition, but I figure if there is a case, it's probably far enough an edge enough, that a user can just prefix their `condition` statement with an `and` or `or` to allow the 2 to be joined.

(I haven't tested the above yet, so not 100% how it will actually work in practice)

2023-02-21 00:13 UTC, BenB196 commented
Hi @ChrsMark would you be able to take a look at the change to this PR when you have a moment and see if this better aligns with the desired state?

The hbs file becomes a bit messy with the additional logic, but testing appears to work.

<details>
<summary>Integration Before Upgrade (with Leader Election enabled)</summary>

```yaml
inputs:
  - id: prometheus/metrics-prometheus-b7e2f2ce-8b43-4fca-a1bf-c9b9606c9b5a
    name: prometheus-1
    revision: 1
    type: prometheus/metrics
    use_output: default
    meta:
      package:
        name: prometheus
        version: 1.1.0
    data_stream:
      namespace: default
    package_policy_id: b7e2f2ce-8b43-4fca-a1bf-c9b9606c9b5a
    streams:
      - id: >-
          prometheus/metrics-prometheus.collector-b7e2f2ce-8b43-4fca-a1bf-c9b9606c9b5a
        data_stream:
          dataset: prometheus.collector
          type: metrics
        metricsets:
          - collector
        hosts:
          - 'localhost:9090'
        metrics_filters.exclude: null
        metrics_filters.include: null
        metrics_path: /metrics
        period: 10s
        rate_counters: true
        use_types: true
        username: user
        password: secret
        condition: '${kubernetes_leaderelection.leader} == true'
```

![image](https://user-images.githubusercontent.com/8277432/220215751-d3435592-b358-4028-a651-11006cd504d2.png)

</details>

<details>
<summary>Integration After Upgrade</summary>

```yaml
inputs:
  - id: prometheus/metrics-prometheus-b7e2f2ce-8b43-4fca-a1bf-c9b9606c9b5a
    name: prometheus-1
    revision: 2
    type: prometheus/metrics
    use_output: default
    meta:
      package:
        name: prometheus
        version: 1.2.0
    data_stream:
      namespace: default
    package_policy_id: b7e2f2ce-8b43-4fca-a1bf-c9b9606c9b5a
    streams:
      - id: >-
          prometheus/metrics-prometheus.collector-b7e2f2ce-8b43-4fca-a1bf-c9b9606c9b5a
        data_stream:
          dataset: prometheus.collector
          type: metrics
        metrics_filters.exclude: null
        period: 10s
        password: secret
        condition: '${kubernetes_leaderelection.leader} == true'
        hosts:
          - 'localhost:9090'
        metricsets:
          - collector
        use_types: true
        metrics_filters.include: null
        rate_counters: true
        metrics_path: /metrics
        username: user
```

![image](https://user-images.githubusercontent.com/8277432/220215795-cadddac7-4e10-46f1-8964-366c5ad0dbea.png)

</details>

<details>
<summary>Integration After Upgrade (adding a condition)</summary>

```yaml
inputs:
  - id: prometheus/metrics-prometheus-b7e2f2ce-8b43-4fca-a1bf-c9b9606c9b5a
    name: prometheus-1
    revision: 4
    type: prometheus/metrics
    use_output: default
    meta:
      package:
        name: prometheus
        version: 1.2.0
    data_stream:
      namespace: default
    package_policy_id: b7e2f2ce-8b43-4fca-a1bf-c9b9606c9b5a
    streams:
      - id: >-
          prometheus/metrics-prometheus.collector-b7e2f2ce-8b43-4fca-a1bf-c9b9606c9b5a
        data_stream:
          dataset: prometheus.collector
          type: metrics
        metrics_filters.exclude: null
        period: 10s
        password: secret
        condition: '${kubernetes_leaderelection.leader} == true and k8s.label == my-app'
        hosts:
          - 'localhost:9090'
        metricsets:
          - collector
        use_types: true
        metrics_filters.include: null
        rate_counters: true
        metrics_path: /metrics
        username: user
```

![image](https://user-images.githubusercontent.com/8277432/220215818-45164b80-a22e-4e5b-9565-10c23db84fd4.png)

</details>

<details>
<summary>Integration After Upgrade (Disabling leader election)</summary>

```yaml
inputs:
  - id: prometheus/metrics-prometheus-b7e2f2ce-8b43-4fca-a1bf-c9b9606c9b5a
    name: prometheus-1
    revision: 5
    type: prometheus/metrics
    use_output: default
    meta:
      package:
        name: prometheus
        version: 1.2.0
    data_stream:
      namespace: default
    package_policy_id: b7e2f2ce-8b43-4fca-a1bf-c9b9606c9b5a
    streams:
      - id: >-
          prometheus/metrics-prometheus.collector-b7e2f2ce-8b43-4fca-a1bf-c9b9606c9b5a
        data_stream:
          dataset: prometheus.collector
          type: metrics
        metrics_filters.exclude: null
        period: 10s
        password: secret
        condition: k8s.label == my-app
        hosts:
          - 'localhost:9090'
        metricsets:
          - collector
        use_types: true
        metrics_filters.include: null
        rate_counters: true
        metrics_path: /metrics
        username: user
```

![image](https://user-images.githubusercontent.com/8277432/220215866-7d57fd8e-75c9-4f11-b12f-986b26fcb17e.png)

</details>

<details>
<summary>Integration After Upgrade (Removing condition)</summary>

```yaml
inputs:
  - id: prometheus/metrics-prometheus-b7e2f2ce-8b43-4fca-a1bf-c9b9606c9b5a
    name: prometheus-1
    revision: 6
    type: prometheus/metrics
    use_output: default
    meta:
      package:
        name: prometheus
        version: 1.2.0
    data_stream:
      namespace: default
    package_policy_id: b7e2f2ce-8b43-4fca-a1bf-c9b9606c9b5a
    streams:
      - id: >-
          prometheus/metrics-prometheus.collector-b7e2f2ce-8b43-4fca-a1bf-c9b9606c9b5a
        data_stream:
          dataset: prometheus.collector
          type: metrics
        metrics_filters.exclude: null
        period: 10s
        password: secret
        hosts:
          - 'localhost:9090'
        metricsets:
          - collector
        use_types: true
        metrics_filters.include: null
        rate_counters: true
        metrics_path: /metrics
        username: user
```

![image](https://user-images.githubusercontent.com/8277432/220215894-599ce3ac-6399-417e-ac1a-acbaf2d3693d.png)

</details>

A note, after thinking about this for a bit, I've opted to include an `and` operator if both `leaderelection` and `condition`. I think there are some cases where you'd want leader election **and** additional conditions, but I wasn't able to think of any use cases where you'd want leader election **or** condition. I think by automatically adding an `and` operator, it improves the UX for most cases. In the event someone has a "real" use case where they want an `or` operator, they'd just need to manually set leaderelection in the `conditon`

2023-02-21 04:58 UTC, ChrsMark commented
Hey @BenB196 ! You can find a similar PR that adds the `condition` setting at https://github.com/elastic/integrations/pull/4324.

I don't think it's a good idea to mix the `leaderelection`  with the generic `condition` using and/or operators. The `leaderelection` setting should be untouched and you can just add the additional `condition` similarly to https://github.com/elastic/integrations/pull/4324.

So the `stream.yml.hbs` file should be like:

```yml
...
{{#if leaderelection}}
condition: ${kubernetes_leaderelection.leader} == true
{{/if}}
{{#if condition}}
condition: {{ condition }}
{{/if}}
...
```

This means that as a user I can enable the `collector` data_stream only for the leader Agent and at the same point define a condition like `${kubernetes.labels.scrape} == true` to apply the data_stream on Pods with specific label. That's the main usage of the conditions.

2023-02-21 08:55 UTC, tetianakravchenko commented
@ChrsMark but in the case you suggested we might get `condition` repeated twice if `leaderelection` is set to true and `condition` defined:
```
condition: ${kubernetes_leaderelection.leader} == true
condition: k8s.label == my-app
```
I didn't test it, do you know if `condition` will be overwritten by the last value in configuration in this case?

2023-02-21 10:40 UTC, tetianakravchenko commented
@ChrsMark yes, I agree, how it's currently shaped is fine.

I think `else` could be omitted, but it is not required:
```
{{#if leaderelection}}
  {{#if condition }}
    condition: ${kubernetes_leaderelection.leader} == true and {{ condition }}
  {{ else }}
    condition: ${kubernetes_leaderelection.leader} == true
  {{/if}}
{{/if}}
{{#if condition }}
   condition: {{ condition }}
{{/if}}
```

2023-02-21 10:42 UTC, tetianakravchenko commented on packages/prometheus/data_stream/collector/manifest.yml
> +        required: false
what is the reason to change it to false?

2023-02-21 11:39 UTC, BenB196 commented on packages/prometheus/data_stream/collector/manifest.yml
> +        required: false
This was a copy/paste error when I was re-adding back leader election. I've pushed a change to switch this back

2023-02-22 04:14 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 2.206
Classes | 100.0% (`0/0`) | :green_heart: 2.206
Methods | 88.889% (`8/9`) | :-1: -2.436
Lines | 100.0% (`0/0`) | :green_heart: 7.022
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-02-22 06:17 UTC, ChrsMark approved these changes
LGTM, I also tested this branch on my end and the generated policies for each combination look good.

2023-02-22 09:03 UTC, tetianakravchenko approved these changes

2023-02-22 09:09 UTC, merged

2023-02-22 09:30 UTC, elasticmachine commented
Package prometheus - 1.2.0 containing this change is available at https://epr.elastic.co/search?package=prometheus