[Kubernetes][Container Logs] Add ability to configure `data_stream.dataset` & "Custom configuration"
elastic/integrations pull request #5555
Opened 2023-03-15 23:44 UTC by BenB196

Enhancement

## What does this PR do?

This PR does 2 things for the Kubernetes Container Log integration:

1. Adds the ability to configure `data_stream.dataset`.
2. Adds the ability to add custom configurations to container logs

Both changes are intended to bring this closer inline with the [Custom Log](https://github.com/elastic/integrations/tree/main/packages/log) integration.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- ~~[ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).~~

## Author's Checklist

- `data_stream.dataset` is now configurable
- "Custom configuration" section injects additional yaml configuration.

<details>
<summary>Before Upgrade</summary>

```yaml
inputs:
  - id: filestream-container-logs-329e9d5f-dd99-438e-8271-3e3598c8300a
    name: kubernetes-1
    revision: 1
    type: filestream
    use_output: default
    meta:
      package:
        name: kubernetes
        version: 1.32.0
    data_stream:
      namespace: default
    package_policy_id: 329e9d5f-dd99-438e-8271-3e3598c8300a
    streams:
      - id: >-
          kubernetes-container-logs-${kubernetes.pod.name}-${kubernetes.container.id}
        data_stream:
          dataset: kubernetes.container_logs
          type: logs
        paths:
          - '/var/log/containers/*${kubernetes.container.id}.log'
        prospector.scanner.symlinks: true
        parsers:
          - container:
              stream: all
              format: auto
```

</details>

<details>
<summary>After Upgrade (No modifications)</summary>

```yaml
inputs:
  - id: filestream-container-logs-329e9d5f-dd99-438e-8271-3e3598c8300a
    name: kubernetes-1
    revision: 2
    type: filestream
    use_output: default
    meta:
      package:
        name: kubernetes
        version: 1.33.0
    data_stream:
      namespace: default
    package_policy_id: 329e9d5f-dd99-438e-8271-3e3598c8300a
    streams:
      - id: >-
          kubernetes-container-logs-${kubernetes.pod.name}-${kubernetes.container.id}
        data_stream:
          dataset: kubernetes.container_logs
        prospector.scanner.symlinks: true
        paths:
          - '/var/log/containers/*${kubernetes.container.id}.log'
        parsers:
          - container:
              stream: all
              format: auto
```

</details>

**Note:** After the upgrade, the policy configuration no longer is setting `streams.id.data_stream.type: logs`. I don't believe this matters as I check the Custom logs integration and it does the same thing. But if desired, I can have it add `streams.id.data_stream.type: logs`.

<details>
<summary>After Upgrade (With modifications)</summary>

```yaml
inputs:
  - id: filestream-container-logs-329e9d5f-dd99-438e-8271-3e3598c8300a
    name: kubernetes-1
    revision: 4
    type: filestream
    use_output: default
    meta:
      package:
        name: kubernetes
        version: 1.33.0
    data_stream:
      namespace: default
    package_policy_id: 329e9d5f-dd99-438e-8271-3e3598c8300a
    streams:
      - id: >-
          kubernetes-container-logs-${kubernetes.pod.name}-${kubernetes.container.id}
        data_stream:
          dataset: custom.dataset
        prospector.scanner.symlinks: true
        paths:
          - '/var/log/containers/*${kubernetes.container.id}.log'
        file_identity.inode_marker.path: /logs/.filebeat-marker
        parsers:
          - container:
              stream: all
              format: auto
```

</details>

## How to test this PR locally

1. Install current integration
2. Upgrade integration to this PR
3. Observe that policy is similar to before the upgrade and the integration works
4. Change `data_stream.dataset` value, and observe change is reflected in agent policy
5. Change Custom configuration value, and observe change is reflected in agent policy

## Related issues

- Closes #5551

## Screenshots

![image](https://user-images.githubusercontent.com/8277432/225468237-ecf17208-53e3-4b74-8d54-9967cfde9227.png)

2023-03-15 23:47 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5555/detail/PR-5555/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5555/detail/PR-5555/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5555/detail/PR-5555/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5555/detail/PR-5555/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-03-15T23:34:30.515Z&rangeTo=2023-03-15T23:54:30.515Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=484cf55fe7a1f704688a74e531beac66&transactionId=d529b099a06c0072)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-03-15T23:44:30.515+0000


* Duration: 3 min 11 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5555/detail/PR-5555/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Load a resource file from a library`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-5555/runs/1/steps/81/log/?start=0">here</a></li>
<li>Description: <code>approval-list/elastic/integrations.yml</code></l1>
</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-5555/runs/1/steps/89/log/?start=0">here</a></li>
<li>Description: <code>githubApiCall: The REST API call https://api.github.com/orgs/elastic/members/BenB196 return the message : java.lang.Exception: httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/BenB196 : httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/BenB196 : Code: 404Error: {"message":"User does not exist or is not a member of the organization","documentation_url":"https://docs.github.com/rest/reference/orgs#check-organization-membership-for-a-user"}</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-03-21 04:45 UTC, ChrsMark reviewed
These additions look good to me. 
@gizas @tommyers-elastic raising this with you too in case you have any additional comment or objection.

2023-03-21 04:45 UTC, ChrsMark commented on packages/kubernetes/data_stream/container_logs/agent/stream/stream.yml.hbs
> +{{custom}}
How about surrounding this with an `{{if}}` block?

2023-03-21 04:45 UTC, ChrsMark commented on packages/kubernetes/changelog.yml
> +    - description: Add ability to configure additional settings via "Custom configuration" section.
Maybe combine this into one message? Sth like `Add data_stream.dataset setting and custom yaml input`.

@gizas do you maybe know if we prefer spitted messages?

2023-03-21 08:10 UTC, gizas commented
> These additions look good to me. @gizas @tommyers-elastic raising this with you too in case you have any additional comment or objection.

As long as we introduce the dataset change, I would only advise to add the same functionality to all rest datastreams. It would be strange not to have the same experience to all.

2023-03-21 10:19 UTC, gsantoro requested changes

2023-03-21 10:19 UTC, gsantoro commented on packages/kubernetes/data_stream/container_logs/manifest.yml
> +          Set the name for your dataset. Changing the dataset will send the data to a different index. You can't use `-` in the name of a dataset and only valid characters for [Elasticsearch index na
```suggestion
          Set the name for your dataset. Changing the dataset will send the data to a different index. For more info look at [data_stream field](https://www.elastic.co/guide/en/ecs/master/ecs-data_stream.html).
```

2023-03-21 10:19 UTC, gsantoro commented on packages/kubernetes/data_stream/container_logs/agent/stream/stream.yml.hbs
> +{{custom}}
For reference the [fleet_server integration](https://github.com/elastic/integrations/blob/58b500ca847590f1d33fa399cb03f023a2026490/packages/fleet_server/agent/input/agent.yml.hbs#L15) uses

```yaml
{{#if custom}}
{{custom}}
{{/if}}
```

2023-03-21 10:19 UTC, gsantoro commented on packages/kubernetes/data_stream/container_logs/agent/stream/stream.yml.hbs
> +{{custom}}
Like @gizas commented in the PR, if you are doing this, do you mind doing the same for every datastream under the kubernetes package?

2023-03-21 10:44 UTC, BenB196 commented
>

2023-03-21 10:47 UTC, gizas commented
We had another internal round of discussions and I would like to remove my comment of https://github.com/elastic/integrations/pull/5555#issuecomment-1477421219

The scenario that the user might only retrieve logs from specific application/ pods etc and would like to create a specific dataset to only include eg nginx logs is valid. But lets not expose the change to metrics, as those will still be coming from kubernetes and would create more confusion.

Sorry for the mess here.

So also this change https://github.com/elastic/integrations/pull/5555#discussion_r1143152040, to be done only for logs

2023-03-21 10:51 UTC, gsantoro approved these changes

2023-03-21 11:27 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 
Classes | 100.0% (`0/0`) | :green_heart: 
Methods | 96.154% (`75/78`) | :+1: 7.063
Lines | 100.0% (`0/0`) | :green_heart: 10.742
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-03-22 00:22 UTC, ChrsMark approved these changes
lgtm, thanks!

2023-03-22 10:35 UTC, gizas approved these changes

2023-03-22 10:52 UTC, merged

2023-03-22 11:12 UTC, elasticmachine commented
Package kubernetes - 1.33.0 containing this change is available at https://epr.elastic.co/search?package=kubernetes