Update README file
elastic/integrations pull request #571
Opened 2021-01-27 12:54 UTC by mtojek

## What does this PR do?

This PR improves README/docs part of the project.

## Issues

- Resolves https://github.com/elastic/integrations/issues/63

2021-01-27 15:27 UTC, elasticmachine commented
Pinging @elastic/integrations (Team:Integrations)

2021-01-27 18:04 UTC, fearful-symmetry approved these changes
Yay, so much needed knowledge here. LGTM.

2021-01-27 19:06 UTC, ycombinator commented on README.md
> +This repository contains sources of the Elastic Integrations - packages defining data streams to observe the same product (logs, metrics, traces).
```suggestion
This repository contains sources for Elastic Integrations. Each Elastic Integration is an Elastic Package that defines how to observe a specific product with the Elastic Stack.
```

2021-01-27 19:10 UTC, ycombinator commented on README.md
> +images, tests, documentation, etc.
```suggestion
```suggestion
An Elastic Package may define configuration for the [Elastic Agent](https://github.com/elastic/beats/tree/master/x-pack/elastic-agent) as well as assets (such as Kibana dashboards and Elasticsearch index templates) for the Elastic Stack. It should also define documentation about the package. Finally, a package may also define tests to ensure that it is functioning as expected.
```
```

2021-01-27 19:11 UTC, ycombinator commented on README.md
> +The package format is described in the [Package Spec](https://github.com/elastic/package-spec). The repository is also used
```suggestion
Elastic Packages have a certain, well-defined structure. This structure is described by the [Package Specification](https://github.com/elastic/package-spec). The repository is also used
```

2021-01-27 19:12 UTC, ycombinator commented on README.md
> +for discussions/extending the specification (with proposals).
```suggestion
for discussions about extending the specification (with proposals).
```

2021-01-27 19:15 UTC, ycombinator commented on README.md
> +and exposed for [Kibana](https://github.com/elastic/kibana) via the [Package Registry](https://github.com/elastic/package-registry/).
```suggestion
While this repository contains _sources_ for Elastic Integrations, _built_ Elastic Integrations are stored in the [Package Storage](https://github.com/elastic/package-storage) repository and served up via the [Package Registry](https://github.com/elastic/package-registry/). The Fleet UI in Kibana connects to the Package Registry and allows users to discover, install, and configure Elastic Packages.
```

2021-01-27 19:15 UTC, ycombinator commented on README.md
> +Please review the [CONTRIBUTING](CONTRIBUTING.md) guide to learn how to build and develop packages, understand the release procedure and
```suggestion
Please review the [Contributing Guide](CONTRIBUTING.md) to learn how to build and develop packages, understand the release procedure and
```

2021-01-27 19:17 UTC, ycombinator commented on docs/definitions.md
> +An integration is a specific type of a _package_ defining data streams used to observe the same product (logs and metrics).
```suggestion
An integration is a specific type of a _package_ defining data streams used to observe a product using logs, metrics, and traces.
```

2021-01-27 19:18 UTC, ycombinator commented on README.md
> +The official builder tool for the Elastic Integrations is the [elastic-package](https://github.com/elastic/elastic-package).
```suggestion
The official builder tool for Elastic Integrations is [`elastic-package`](https://github.com/elastic/elastic-package).
```

2021-01-27 19:19 UTC, ycombinator commented on docs/definitions.md
> +A package contains the dashboards, visualisations, and configurations to monitor the logs and metrics of a particular technology or group of related services, such as “MySQL”, or “System”.
```suggestion
An Elastic Package, or simply package for short, contains the dashboards, visualisations, and configurations to monitor the logs and metrics of a particular technology or group of related services, such as “MySQL”, or “System”.
```

2021-01-27 19:20 UTC, ycombinator commented on docs/definitions.md
> +* Zero or more data stream templates
```suggestion
* Zero or more data stream index templates
```

2021-01-27 19:30 UTC, ycombinator commented on docs/definitions.md
> +A data stream is part of a package and contains all the assets which are needed to create a data stream. Example for assets are: ingest pipeline, agent policy template, ES index template, ...
```suggestion
A data stream is logical sub-division of an Integration package, dealing with a specific type of observable aspect of the service or product being observed. For example, the `mysql` package defines a data stream for collecting metrics and another data stream for collecting server logs. 

A data stream defines all the assets needed to create an Elasticsearch data stream, for example: index templates and ingest pipelines. These assets are loaded into Elasticsearch when a user installs a package via the Fleet UI in Kibana.

A data stream also defines a policy template. Policy templates include variables that allow users to configure the data stream via the Fleet UI in Kibana. The resulting policy is interpreted by the Elastic Agent to collect relevant information from the product or service being observed.
```

2021-01-27 19:31 UTC, ycombinator commented on docs/definitions.md
> +Data streams are inside the package directory under `data stream`.
```suggestion
Data streams are defined inside the `data_stream` folder located under the package's root directory. Each data stream is defined in it's own sub-folder.
```

2021-01-27 19:32 UTC, ycombinator commented on docs/definitions.md
> +* An alias templates (or the fields.yml to create it)
What did you mean by "alias templates"?

2021-01-27 19:33 UTC, ycombinator commented on docs/definitions.md
> +## Migration from Beats
```suggestion
## Migration from Beats Modules
```

2021-01-27 19:39 UTC, ycombinator commented on docs/definitions.md
> +modules, hence no modules are required to exist anymore.
```suggestion
Filebeat and Metricbeat modules can be migrated over to Elastic Integrations. When migrating over, the same module in Filebeat and Metricbeat, related to the same observed product, can be combined into a single Elastic Integration. 

[Learn more](/docs/import_from_beats.md) about how to migrate Filebeat and Metricbeat modules to Elastic Integrations.

2021-01-27 19:41 UTC, ycombinator commented on CONTRIBUTING.md
> +This page is intended for contributors to the [Package Registry](https://github.com/elastic/package-registry/) and Elastic Integrations.
I think the README does a great job of explaining the relationships between Elastic Integrations (this repository) and other, related repositories. So I think we should point readers to the README over here for a general overview and only focus the CONTRIBUTING guide on contributing to this repository.

2021-01-27 19:43 UTC, ycombinator commented on CONTRIBUTING.md
>  # Contributing
```suggestion
# Contributing Guide
```

2021-01-27 19:47 UTC, ycombinator commented on CONTRIBUTING.md
> +  of Package Storage to include latest release of the Package-Registry
I would consider omitting these last three sections - Package Spec, Package Registry, and Package Storage - from this contributing guide entirely. The README does a great job of tying all these concepts together with the Integrations repo and also links out to the corresponding repositories. So I would focus this contributing guide mainly on contributing to the Integrations repo itself.

2021-01-27 19:48 UTC, ycombinator commented on CONTRIBUTING.md
> +* [Definitions](/docs/definitions.md)
I like how you have added motivations to go with each of the links for the bullet points below. Maybe add a similar motivation for this bullet point as well?

2021-01-27 19:49 UTC, ycombinator commented on CONTRIBUTING.md
> -### Package
If you focus this file on contributing to the integrations repo (per my other comments on this file), then you can get rid of these two headings, I think.

2021-01-27 19:51 UTC, ycombinator commented on docs/definitions.md
> +## Migration from Beats
Also, I wonder if this section belongs in `CONTRIBUTING.md` rather than definitions?

2021-01-27 19:53 UTC, ycombinator commented on docs/developer_workflow_design_build_test_integration.md
> +* `elastic-package` (builder tool) installed - follow the [Getting started](https://github.com/elastic/elastic-package#getting-started) guide to install the tool.
```suggestion
* `elastic-package` (builder tool) installed - follow the [Getting Started Guide](https://github.com/elastic/elastic-package#getting-started) guide to install the tool. 
```

2021-01-27 19:54 UTC, ycombinator commented on docs/developer_workflow_design_build_test_integration.md
> +first interaction with Integrations or packages, I suggest to review existing Integrations in the Fleet UI.
> I suggest to review existing Integrations in the Fleet UI.

The motivation behind this suggestion is a bit unclear to me. Maybe add something about how this suggestion would benefit the reader?

2021-01-27 19:57 UTC, ycombinator commented on docs/developer_workflow_design_build_test_integration.md
> +where `new_package` is the name of your integration.
Some day it would be nice if we had `elastic-package init` (or similar) that setup a basic package structure for new package developers, giving them an option to copy from a donor package. 🙂

2021-01-27 19:58 UTC, ycombinator commented on docs/developer_workflow_design_build_test_integration.md
> +The `elastic-package` tool supports multiple levels of testing - pipeline, system, assets. Follow up on the specific topic
```suggestion
The `elastic-package` tool supports multiple types of tests - pipeline, system, assets. Follow up on the specific topic
```

2021-01-27 19:59 UTC, ycombinator commented on docs/developer_workflow_design_build_test_integration.md
> +Long story short - if you want your changes in the integration to be released, remember to bump up the package version.
```suggestion
Long story short - when you are ready for your changes in the integration to be released, remember to bump up the package version.
```

2021-01-27 20:02 UTC, ycombinator commented on docs/developer_workflow_design_build_test_integration.md
> +### Open a PR
I think this section makes sense before the version bump section?

2021-01-27 20:03 UTC, ycombinator commented on docs/developer_workflow_promote_release_integration.md
> +* There is a PR open to the [Package Storage/snapshot](https://github.com/elastic/package-storage/tree/snapshot/packages) with your built integration.
```suggestion
* There is a PR open to the [Package Storage/snapshot](https://github.com/elastic/package-storage/tree/snapshot/packages) with your built integration. This will be done automatically by the Integrations repository CI when it detects an unreleased version of your package in the Integrations repository.
```

2021-01-27 20:06 UTC, ycombinator commented on docs/testing_and_validation.md
> +5. Enroll the agent and start it:
Since `elastic-package stack up` already provides an enrolled agent (as you have mentioned in step 3.), maybe you should mark this step as optional and explain in it when a user would need to do it?

2021-01-27 20:09 UTC, ycombinator requested changes
Thanks for taking this on, @mtojek. This improves the documentation greatly and provides a solid entry point for all Integrations developers. 

I have left many comments, mostly around organization of the content and a few nitpicks on the language. But on the whole, the content is very good!

2021-01-27 22:55 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-571/detail/PR-571/18//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-571/detail/PR-571/18//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-571/detail/PR-571/18//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-571/detail/PR-571/18//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_571.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Branch indexing`



* * Start Time: 2021-01-27T22:28:16.107+0000


* Duration: 27 min 29 sec


* Commit: d6cff5b5e458f132373634d541c1497fbd51a154



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 1504  |
| Skipped      | 0 |
| Total        | 1504   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->










<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2021-01-28 13:01 UTC, mtojek commented on CONTRIBUTING.md
> +  of Package Storage to include latest release of the Package-Registry
I would be for leaving them here as we need a single place where you can find such information. It's a general problem with our docs as they're relatively scattered. If you see a better place (a different file?), where we can store this information, I can adjust it.

2021-01-28 13:03 UTC, mtojek commented on CONTRIBUTING.md
> +* [Definitions](/docs/definitions.md)
Fixed

2021-01-28 13:06 UTC, mtojek commented on CONTRIBUTING.md
> -### Package
Are you referring to the removing sections other than Integrations from this place? If so, I responded in thread above.

2021-01-28 13:17 UTC, mtojek commented on docs/developer_workflow_design_build_test_integration.md
> +first interaction with Integrations or packages, I suggest to review existing Integrations in the Fleet UI.
I added more information what to look at.

2021-01-28 13:21 UTC, mtojek commented on docs/developer_workflow_design_build_test_integration.md
> +where `new_package` is the name of your integration.
https://github.com/elastic/elastic-package/issues/3

2021-01-28 13:25 UTC, mtojek commented on docs/developer_workflow_design_build_test_integration.md
> +### Open a PR
I changed the order of "Open a PR" and "Remember to bump up the version".

2021-01-28 13:29 UTC, mtojek commented on docs/testing_and_validation.md
> +5. Enroll the agent and start it:
Fixed!

2021-01-28 13:30 UTC, mtojek commented
@ycombinator Big thanks for all suggestions! I addressed your comments in the PR and I think it's ready for re-review.

2021-01-29 10:35 UTC, masci approved these changes
I like the overall concept, I only skimmed the internal docs but I believe we can improve iteratively, let's merge this as soon as we can - we desperately need a functional README 😄

2021-01-29 10:35 UTC, masci commented on README.md
> +```suggestion
I believe this is a leftover from the GH suggestion tool, let's remove it

2021-01-29 12:03 UTC, mtojek commented on README.md
> +```suggestion
I knew I missed this label somewhere. Thanks, fixed!

2021-01-29 12:04 UTC, mtojek commented
Ok, I will merge this one and we can work on this in next iterations.

2021-01-29 12:04 UTC, merged

2021-01-29 13:42 UTC, ycombinator reviewed
Hey @mtojek, thanks for addressing most of my review comments. I think there are still 3 comments that are not yet addressed. If you agree with those suggestions would you mind making a follow up PR to implement them? If you disagree than just reply on the comments and we are good to go as-is!