[AWS] Add number_of_workers and latency to all CloudWatch Logs based integrations
elastic/integrations pull request #5794
Opened 2023-04-05 10:21 UTC by zmoog

All the CloudWatch Logs based integration should have these options available to them.

The `number_of_workers` is essential to increase the workers when users decide to use `log_group_name_prefix`.

The `latency` can be required on the busiest log groups to deal with potential latency.

## What does this PR do?

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2023-04-05 11:08 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5794/detail/PR-5794/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5794/detail/PR-5794/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5794/detail/PR-5794/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5794/detail/PR-5794/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_5794.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-04-05T10:12:07.191Z&rangeTo=2023-04-05T10:32:07.191Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=69fa52c2fa84cb41b90dba13530339c5&transactionId=e3825aac8c92c210)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-04-05T10:22:07.191+0000


* Duration: 46 min 16 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 190  |
| Skipped      | 4 |
| Total        | 194   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-04-05 11:08 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`15/15`) | :green_heart: 
Files | 93.75% (`15/16`) | :-1: -6.25
Classes | 93.75% (`15/16`) | :-1: -6.25
Methods | 85.921% (`238/277`) | :-1: -14.079
Lines | 85.925% (`7387/8597`) | :-1: -12.122
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-04-05 16:26 UTC, endorama approved these changes

2023-04-12 17:40 UTC, merged

2023-04-17 13:21 UTC, elasticmachine commented
Package aws - 1.33.3 containing this change is available at https://epr.elastic.co/search?package=aws

2024-11-22 01:46 UTC, TheLastHarpCo requested changes
I don't know what I am doing or who Harpo is