Add orchestrator.cluster.id to the index mapping
elastic/integrations pull request #5872
Opened 2023-04-12 14:20 UTC by orestisfl

## What does this PR do?

Add `orchestrator.cluster.id` to the index mapping

See https://github.com/elastic/cloudbeat/pull/847

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

2023-04-12 14:23 UTC, kfirpeled requested changes
It is part of ecs.yml. that field is declared by ECS https://www.elastic.co/guide/en/ecs/current/ecs-orchestrator.html

2023-04-12 14:35 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5872/detail/PR-5872/2//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5872/detail/PR-5872/2//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5872/detail/PR-5872/2//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5872/detail/PR-5872/2//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_5872.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-04-12T14:11:21.648Z&rangeTo=2023-04-12T14:31:21.648Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=1ccb3ccbfb7f90fe4d453b0f0788aa4d&transactionId=ffc6ea9be8954117)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-04-12T14:21:21.648+0000


* Duration: 14 min 27 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![3](https://img.shields.io/badge/3%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-5872/detail/PR-5872/2//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Boot up the Elastic stack`
<ul>
<li>Took 3 min 30 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-5872/runs/2/steps/1073/log/?start=0">here</a></li>
<li>Description: <code>../../build/elastic-package stack up -d -v --version 8.8.0-SNAPSHOT</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-5872/runs/2/steps/1108/log/?start=0">here</a></li>

</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-5872/runs/2/steps/1121/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-04-13 07:27 UTC, olegsu approved these changes

2023-04-13 14:56 UTC, kfirpeled approved these changes

2023-04-13 22:29 UTC, kfirpeled commented
/test

2023-04-20 22:25 UTC, kfirpeled approved these changes

2023-04-21 07:13 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 3.146
Classes | 100.0% (`0/0`) | :green_heart: 3.146
Methods | 25.0% (`2/8`) | :-1: -66.542
Lines | 100.0% (`0/0`) | :green_heart: 8.667
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-04-21 07:45 UTC, merged

2023-04-21 08:06 UTC, elasticmachine commented
Package cloud_security_posture - 1.3.0-preview6 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-04-27 19:35 UTC, elasticmachine commented
Package cloud_security_posture - 1.3.0-preview7 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-05-04 07:11 UTC, elasticmachine commented
Package cloud_security_posture - 1.3.0-preview8 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-05-07 16:08 UTC, elasticmachine commented
Package cloud_security_posture - 1.3.0-preview9 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-05-10 07:10 UTC, elasticmachine commented
Package cloud_security_posture - 1.3.0-preview10 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-05-10 23:39 UTC, elasticmachine commented
Package cloud_security_posture - 1.3.0-preview91 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-07-09 08:01 UTC, elasticmachine commented
Package cloud_security_posture - 1.3.1 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture