[Vulnerability Management] Update CloudFormation template ElasticAgentVersion
elastic/integrations pull request #6034
Opened 2023-04-30 11:02 UTC by amirbenun

## What does this PR do?

The meaning of `ElasticAgentVersion` parameter has changed as part of the new cloudformation template.
The template used to expect a value in the form of `elastic-agent-KIBANA_VERSION-linux-arm64`, and as of the new template it only expects `KIBANA_VERSION`.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2023-04-30 11:17 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6034/detail/PR-6034/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6034/detail/PR-6034/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6034/detail/PR-6034/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6034/detail/PR-6034/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_6034.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-04-30T10:52:56.085Z&rangeTo=2023-04-30T11:12:56.085Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=fbb7ff98f94a136b6df0021f03b8f4ba&transactionId=0c54f8fa7145cbfe)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-04-30T11:02:56.085+0000


* Duration: 15 min 54 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 4  |
| Skipped      | 0 |
| Total        | 4   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-04-30 11:18 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 3.035
Classes | 100.0% (`0/0`) | :green_heart: 3.035
Methods | 25.0% (`2/8`) | :-1: -66.693
Lines | 100.0% (`0/0`) | :green_heart: 7.957
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-04-30 12:54 UTC, oren-zohar approved these changes

2023-04-30 14:57 UTC, kfirpeled reviewed
if this change is dedicated for 8.9.0 please introduce a new version of `1.4.0-preview1` and change the condition to 8.9.0

2023-05-02 02:11 UTC, kfirpeled commented
Please do not merge this before the 1st QA cycle is over

2023-05-02 13:14 UTC, kfirpeled requested changes

2023-05-02 13:14 UTC, kfirpeled commented on packages/cloud_security_posture/changelog.yml
> +- version: "1.3.0"
removing the preview from 1.3.0 means it will be published right after this will be merged.
We plan to release the integration on the release date of 8.8.0
please leave the preview suffix for `1.3.0`

2023-05-02 13:34 UTC, kfirpeled approved these changes

2023-05-02 13:36 UTC, merged

2023-05-02 13:58 UTC, elasticmachine commented
Package cloud_security_posture - 1.4.0-preview1 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-05-04 12:43 UTC, elasticmachine commented
Package cloud_security_posture - 1.4.0-preview2 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-06-20 18:41 UTC, elasticmachine commented
Package cloud_security_posture - 1.4.0-preview22 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-07-02 13:26 UTC, elasticmachine commented
Package cloud_security_posture - 1.4.0-preview23 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-07-25 11:24 UTC, elasticmachine commented
Package cloud_security_posture - 1.4.0 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture