Update CNVM index mapping
elastic/integrations pull request #6038
Opened 2023-04-30 19:03 UTC by uri-weisman

## What does this PR do?
Update CNVM findings mapping to be aligned with elastic best practice and ECS.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

- Relates https://github.com/elastic/cloudbeat/pull/912 
- Fixes https://github.com/elastic/security-team/issues/6412

2023-04-30 19:18 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6038/detail/PR-6038/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6038/detail/PR-6038/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6038/detail/PR-6038/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6038/detail/PR-6038/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_6038.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-04-30T18:53:43.688Z&rangeTo=2023-04-30T19:13:43.688Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=91dee9fb2a35f3c27e0c2c36fdd33617&transactionId=fd93ee2fb102eefc)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-04-30T19:03:43.688+0000


* Duration: 14 min 20 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 4  |
| Skipped      | 0 |
| Total        | 4   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-04-30 19:18 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 3.035
Classes | 100.0% (`0/0`) | :green_heart: 3.035
Methods | 25.0% (`2/8`) | :-1: -66.693
Lines | 100.0% (`0/0`) | :green_heart: 7.957
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-05-01 10:51 UTC, uri-weisman commented on packages/cloud_security_posture/data_stream/vulnerabilities/fields/vulnerability.yml
> -    - name: package.fixed_version
I was unsure how to handle `package.fixed_version` since it was mapped, but the package fields have now been moved to ECS and this particular field is not part of ECS.

2023-05-02 02:07 UTC, kfirpeled requested changes
I'm rejecting to hold this change to enter 1.3.0

Currently it is not clear if this change is relevant for 8.8 or for 8.9
If it is intended to be 8.9, open a new version of the integration `1.4.0-preview1` and mark its kibana condition to 8.9.0 as well

If it is 8.8 I'll approve it after the QA cycle is over (otherwise it will break the tests)

2023-05-02 02:08 UTC, kfirpeled commented on packages/cloud_security_posture/data_stream/vulnerabilities/fields/vulnerability.yml
> -    - name: package.fixed_version
in that case, you can add it to fields.yml or package.yml
both options are valid

2023-05-02 13:15 UTC, uri-weisman commented on packages/cloud_security_posture/data_stream/vulnerabilities/fields/vulnerability.yml
> -    - name: package.fixed_version
added to `fields.yml`

2023-05-03 12:19 UTC, uri-weisman commented
It's for 8.8, so it needs to be backported.
Created new [PR](https://github.com/elastic/integrations/pull/6069).

2023-05-03 15:50 UTC, kfirpeled commented
@uri-weisman we can reopen this one

2023-05-05 02:41 UTC, kfirpeled commented on packages/cloud_security_posture/changelog.yml
> +    - description: Update CNVM index mapping
yep, no need to add the change log under 1.4.0

2023-05-07 07:19 UTC, uri-weisman commented on packages/cloud_security_posture/changelog.yml
> +    - description: Update CNVM index mapping
removed

2023-05-07 18:09 UTC, kfirpeled approved these changes
LGTM

2023-05-08 05:17 UTC, merged