[Cloud Security Posture] Add documentation of the version mappings
elastic/integrations pull request #6090
Opened 2023-05-04 12:19 UTC by amirbenun

## What does this PR do?

Add documentation of mapping between integration version to its relevant stack version.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2023-05-04 12:24 UTC, oren-zohar requested changes

2023-05-04 12:24 UTC, oren-zohar commented on packages/cloud_security_posture/changelog.yml
> +# 1.2.11 - 8.7.0
```suggestion
# 1.4.x - 8.9.0
# 1.3.x - 8.8.0
# 1.2.x - 8.7.0
```

2023-05-04 12:35 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6090/detail/PR-6090/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6090/detail/PR-6090/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6090/detail/PR-6090/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6090/detail/PR-6090/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_6090.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-05-04T12:09:42.691Z&rangeTo=2023-05-04T12:29:42.691Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=3fb9c4ea84c006256eaf864f1730a54d&transactionId=3f8124fcc747d7eb)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-05-04T12:19:42.691+0000


* Duration: 15 min 29 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 4  |
| Skipped      | 0 |
| Total        | 4   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-05-05 02:42 UTC, kfirpeled approved these changes

2023-05-05 02:42 UTC, kfirpeled commented on packages/cloud_security_posture/changelog.yml
> +# 1.4.x - 8.9.0
1.4.x - 8.9.x :D

2023-05-07 18:11 UTC, kfirpeled approved these changes

2023-05-08 15:55 UTC, oren-zohar approved these changes

2023-06-15 12:18 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/141)
* Commit: 408de97f9a2f304b5c3a39477c9628cbce0c4596

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/141","number":141,"commit":"408de97f9a2f304b5c3a39477c9628cbce0c4596"}],"number":141}
buildkite-pr-comment-->

2023-06-15 12:46 UTC, merged