[Network Traffic] Convert dashboards and formatting of package
elastic/integrations pull request #6106
Opened 2023-05-05 13:50 UTC by P1llus

## What does this PR do?

This is part of a bigger cleanup that relates to https://github.com/elastic/security-team/issues/5910.

I tried to add as much of the filtering as a separate commit, so most of the changes is in the commit before it, making a review easier.
However the ingest pipeline changes for on_failure was added as a last commit

The tasks, when applicable was:

- [x] Formatting with https://github.com/efd6/fumpt
- [x] Add dynamic ECS template
- [x] Update format_version to 2.6.0+
- [x] Update on_failure to include proper event.kind.
- [x] Update on_failure error message to be more descriptive
- [ ] Add processor tags for on_failure message
- [x] If system/pipeline tests are missing, add them when possible.
- [x] If httpjson, does it have drop processor for empty events?
- [ ] If no dashboards, add them.
- [x] If dashboards exist, replace with lens when needed, update dashboards if applicable.

The PR looks like it is changing more than it is, because most of them are formatting changes.

Dashboard changes:
1. All table of contents.
2. Convert all to lens.
3. Add/remove/rename certain visualizations to fit the layout and usefulness better
4. Changed layout a bit.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2023-05-05 14:11 UTC, P1llus commented
One more commit incoming soon, then ready

2023-05-05 18:53 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6106/detail/PR-6106/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6106/detail/PR-6106/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6106/detail/PR-6106/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6106/detail/PR-6106/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_6106.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-05-05T18:31:59.252Z&rangeTo=2023-05-05T18:51:59.252Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=5606478b532eb09b283d5b3428d5788a&transactionId=5aaca92ff8778fa9)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-05-05T18:41:59.252+0000


* Duration: 11 min 23 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![4](https://img.shields.io/badge/4%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6106/detail/PR-6106/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Check integration: network_traffic`
<ul>
<li>Took 0 min 3 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-6106/runs/1/steps/1094/log/?start=0">here</a></li>
<li>Description: <code>../../build/elastic-package check -v</code></l1>
</ul>
  
  
  
  
##### `Take down the Elastic stack`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-6106/runs/1/steps/1109/log/?start=0">here</a></li>
<li>Description: <code>build/elastic-package stack down -v</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-6106/runs/1/steps/1127/log/?start=0">here</a></li>

</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-6106/runs/1/steps/1140/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-05-07 21:34 UTC, efd6 requested changes
This is a hold purely to allow discussion of the version bump.

2023-05-07 21:34 UTC, efd6 commented on packages/network_traffic/manifest.yml
> +  kibana.version: ^8.7.1
If at all possible I would like to keep this at 8.6.2 and no higher for the short term.

2023-05-07 21:34 UTC, efd6 commented on packages/network_traffic/manifest.yml
>  license: basic
```suggestion
```

2023-05-07 21:34 UTC, efd6 commented on packages/network_traffic/data_stream/amqp/elasticsearch/ingest_pipeline/default.yml
> +      tag: gsub mac
Avoid spaces in tags?

2023-05-07 21:34 UTC, efd6 commented on packages/network_traffic/changelog.yml
> -- version: "1.14.0"
Ideally, non-semantic reformat changes this size would be in a separate PR.

2023-05-08 06:57 UTC, P1llus commented
I will be reopening this in a smaller fashion, the formatting changes caused too much issues, and its going to be easier with handling the conflicts

2023-05-08 06:57 UTC, closed without merging