[System] Add dimensions to system package metrics data_streams only, except core and process data_streams
elastic/integrations pull request #6118
Opened 2023-05-08 14:25 UTC by tetianakravchenko

## What does this PR do?

Add/adjust dimensions fields:
- ⛔ (when adding core.id fields all documents are dropped, need to double-check, will add in different PR) core - add standard fields + core.id
    - Verification of the count of documents (before & after TSDB enablement) in Discover Interface 
    - For every field annotated with `dimension:true`, there exists time_series_dimension: true annotation in the index  
- ✅ cpu - adjust list of fields according to https://github.com/elastic/integrations/issues/5193#issuecomment-1536090359.
    - Verification of the count of documents (before & after TSDB enablement) in Discover Interface ✅ 
    - For every field annotated with `dimension:true`, there exists time_series_dimension: true annotation in the index  ✅ 
- ✅ diskio - add standard fields + `system.diskio.name`
    - Verification of the count of documents (before & after TSDB enablement) in Discover Interface ✅
    - For every field annotated with `dimension:true`, there exists time_series_dimension: true annotation in the index  ✅
- ✅  (retest) filesystem - add standard fields + system.filesystem.device_name and system.filesystem.mount_point
    - Verification of the count of documents (before & after TSDB enablement) in Discover Interface ✅
    - For every field annotated with `dimension:true`, there exists time_series_dimension: true annotation in the index  ✅- 
- ✅ fsstat - add standard fields
    - Verification of the count of documents (before & after TSDB enablement) in Discover Interface ✅ 
    - For every field annotated with `dimension:true`, there exists time_series_dimension: true annotation in the index  ✅  
- ✅ load - adjust list of fields according to https://github.com/elastic/integrations/issues/5193#issuecomment-1536090359.
    - Verification of the count of documents (before & after TSDB enablement) in Discover Interface ✅ 
    - For every field annotated with `dimension:true`, there exists time_series_dimension: true annotation in the index  ✅
- ✅ memory - adjust list of fields according to https://github.com/elastic/integrations/issues/5193#issuecomment-1536090359.
    - Verification of the count of documents (before & after TSDB enablement) in Discover Interface ✅ 
    - For every field annotated with `dimension:true`, there exists time_series_dimension: true annotation in the index  ✅ 
- ✅  network - add standard fields + `system.network.name`
    - Verification of the count of documents (before & after TSDB enablement) in Discover Interface ✅
    - For every field annotated with `dimension:true`, there exists time_series_dimension: true annotation in the index ✅
- ⛔ (due to missing fields - will be added in different PR) process - add standard fields + PID
    - Verification of the count of documents (before & after TSDB enablement) in Discover Interface 
    - For every field annotated with `dimension:true`, there exists time_series_dimension: true annotation in the index  
- ✅ process_summary - add standard fields
    - Verification of the count of documents (before & after TSDB enablement) in Discover Interface ✅ 
    - For every field annotated with `dimension:true`, there exists time_series_dimension: true annotation in the index  ✅ 
- ✅ socket_summary - add standard fields
    - Verification of the count of documents (before & after TSDB enablement) in Discover Interface ✅ 
    - For every field annotated with `dimension:true`, there exists time_series_dimension: true annotation in the index  ✅ 
- ✅ uptime - add standard fields
    - Verification of the count of documents (before & after TSDB enablement) in Discover Interface ✅ 
    - For every field annotated with `dimension:true`, there exists time_series_dimension: true annotation in the index  ✅ 
  
## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2023-05-08 15:10 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`3/3`) | :green_heart: 
Files | 100.0% (`4/4`) | :green_heart: 
Classes | 100.0% (`4/4`) | :green_heart: 
Methods | 60.759% (`48/79`) | :-1: -30.15
Lines | 99.535% (`2780/2793`) | :+1: 10.646
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-05-09 13:24 UTC, agithomas reviewed
`system.process.cmdline` should be considered as a dimension field.

2023-05-09 13:29 UTC, agithomas commented
> `system.process.cmdline` should be considered as a dimension field.

Please ignore the above review comment.

2023-05-10 13:40 UTC, tetianakravchenko commented on packages/system/data_stream/process/fields/agent.yml
> +    - name: pid
NOTE: it implies that new time series will be created when restarting a process, the same for k8s environment since we have this setting in manifest: https://github.com/elastic/elastic-agent/blob/main/deploy/kubernetes/elastic-agent-managed-kubernetes.yaml#L29

2023-05-10 14:03 UTC, lalit-satapathy commented on packages/system/data_stream/process/fields/agent.yml
> +    - name: pid
Is this a field, for which mapping was completely missing before?

2023-05-11 07:47 UTC, ruflin commented on packages/system/docs/README.md
> +| host.os.name.text | Multi-field of `host.os.name`. | text |  |  |
Where is this change coming from?

2023-05-11 07:47 UTC, ruflin commented on packages/system/docs/README.md
> +| host.network.in.packets | The number of packets received on all network interfaces by the host in a given period of time. | scaled_float |  | counter |
This looks off. Why is this suddenly a scaled float but at the same time a counter which I assume is always a `long` ?

2023-05-17 11:12 UTC, tetianakravchenko commented on packages/system/docs/README.md
> +| host.os.name.text | Multi-field of `host.os.name`. | text |  |  |
I didn't touch any ecs fields in this PR, I thought that this is coming from the ecs definition, when running `elastic-package build`
but, you are right - it should still be `match_only_text` from the ecs fields definition - https://github.com/elastic/ecs/blob/8.0/experimental/generated/beats/fields.ecs.yml#L3857-L3866

it appeared that this field is defined in `fields` folder twice - in `agent.yml` https://github.com/elastic/integrations/blob/72dfc88edde2ec318a75c8271c7d97cc9f16521e/packages/system/data_stream/diskio/fields/agent.yml#L159-L169 and in `ecs.yml` - https://github.com/elastic/integrations/blob/72dfc88edde2ec318a75c8271c7d97cc9f16521e/packages/system/data_stream/diskio/fields/ecs.yml#L19-L20

I will remove the custom definition

2023-05-17 11:15 UTC, tetianakravchenko commented on packages/system/docs/README.md
> +| host.network.in.packets | The number of packets received on all network interfaces by the host in a given period of time. | scaled_float |  | counter |
the same here: the same field defined twice: once in `fields.yml`: https://github.com/elastic/integrations/blob/72dfc88edde2ec318a75c8271c7d97cc9f16521e/packages/system/data_stream/network/fields/fields.yml#L56-L62

another one in `agent.yml`: https://github.com/elastic/integrations/blob/72dfc88edde2ec318a75c8271c7d97cc9f16521e/packages/system/data_stream/network/fields/agent.yml#L206-L210

I am not sure what is a correct 😕 Could be that the files evaluation sequence changed that caused this

@elastic/elastic-agent-data-plane I need some help here, what is the correct value for this field?

2023-05-17 11:43 UTC, tetianakravchenko commented on packages/system/docs/README.md
> +| host.os.name.text | Multi-field of `host.os.name`. | text |  |  |
done - https://github.com/elastic/integrations/pull/6118/commits/b762ecc7214ee2b26475644caf03aa3a6572e992

there are lots of duplicated fields, to not mix up fields clean up and tsdb dimensions pr - I am not going to introduce more fields removal here. @elastic/elastic-agent-data-plane could you please take care of it?

I think that `elastic-package check` could verify that there are no duplicated fields to avoid such situations, wdyt? should it be created as a feature request for elastic-package?

2023-05-31 07:44 UTC, ruflin commented on packages/system/docs/README.md
> +| host.network.in.packets | The number of packets received on all network interfaces by the host in a given period of time. | scaled_float |  | counter |
I'm tempted to say the one in `fields.yml` is wrong. Two questions:

* Can you check what is loaded today if you install the package? Hopefully long.
* Can you check what we have in metricbeat for the same?

If we load long today and it is also the one used in Metricbeat, lets fix the `fields.yml` file. Otherwise lets continue the discussion.

2023-05-31 08:38 UTC, ruflin commented
Could we take out the process and network changes to get this in quickly and follow up with the other two separately?

2023-05-31 09:11 UTC, tetianakravchenko commented on packages/system/docs/README.md
> +| host.network.in.packets | The number of packets received on all network interfaces by the host in a given period of time. | scaled_float |  | counter |
> Can you check what is loaded today if you install the package? Hopefully long.

`long`
<img width="634" alt="Screenshot 2023-05-31 at 11 08 05" src="https://github.com/elastic/integrations/assets/28299531/f8fbf096-a732-43b3-b894-245a145b90e1">

> Can you check what we have in metricbeat for the same?

also `long` - https://github.com/elastic/beats/blob/main/metricbeat/module/system/network/_meta/fields.yml#L30-L33

I've reverted network changes for this PR, will create an another one

2023-05-31 09:25 UTC, tetianakravchenko commented
> Could we take out the process and network changes to get this in quickly and follow up with the other two separately?

@ruflin done, process and network data_stream changes were reverted

2023-05-31 09:45 UTC, ruflin approved these changes
LGTM

As this PR does mostly add dimensions + some cleanups, this should be low risk.

2023-05-31 09:45 UTC, ruflin commented on packages/system/docs/README.md
> -| host.mac | Host MAC addresses. The notation format from RFC 7042 is suggested: Each octet (that is, 8-bit byte) is represented by two [uppercase] hexadecimal digits giving the value of the octet as
Not sure where this change is coming from but I assume pulled in from some ECS changes.

2023-05-31 09:45 UTC, ruflin approved these changes
LGTM

As this PR does mostly add dimensions + some cleanups, this should be low risk.

2023-05-31 09:45 UTC, ruflin approved these changes
LGTM

As this PR does mostly add dimensions + some cleanups, this should be low risk.

2023-05-31 09:49 UTC, agithomas commented
Referring to https://github.com/elastic/integrations/issues/5193#issuecomment-1536090359, please include agent.id as the dimension field.

2023-05-31 10:04 UTC, tetianakravchenko commented
@elastic/elastic-agent-data-plane could you please review this PR? I can't merge it since `Code owner review required`

2023-05-31 10:05 UTC, tetianakravchenko commented on packages/system/docs/README.md
> -| host.mac | Host MAC addresses. The notation format from RFC 7042 is suggested: Each octet (that is, 8-bit byte) is represented by two [uppercase] hexadecimal digits giving the value of the octet as
the same issue as above - there are duplication one in ecs file, another in https://github.com/elastic/integrations/blob/13141974c6705c212379b959b28b8e280a5f7c25/packages/system/data_stream/diskio/fields/agent.yml#L134-L138

2023-05-31 10:26 UTC, ruflin commented on packages/system/docs/README.md
> -| host.mac | Host MAC addresses. The notation format from RFC 7042 is suggested: Each octet (that is, 8-bit byte) is represented by two [uppercase] hexadecimal digits giving the value of the octet as
Lets ignore it for now.

2023-05-31 11:07 UTC, lalit-satapathy commented
@tetianakravchenko,

Can we make this beta and update the stack.version as in this PR: https://github.com/elastic/integrations/pull/6129

2023-05-31 11:10 UTC, lalit-satapathy commented
@tetianakravchenko,

Please confirm that system dashboards loading fine (without any errors) in the TSDB mode?

2023-05-31 11:20 UTC, tetianakravchenko commented
> @tetianakravchenko,
Can we make this beta and update the stack.version as in this PR: https://github.com/elastic/integrations/pull/6129

@lalit-satapathy efore doing it - this PR also should be merged https://github.com/elastic/integrations/pull/6395, there are some missing metric_type metadata fields.

after merging this and https://github.com/elastic/integrations/pull/6395, tsdb can be enabled for all except: `core`, `network`, `process` datastream

2023-05-31 12:42 UTC, tetianakravchenko commented
> @tetianakravchenko,
Please confirm that system dashboards loading fine (without any errors) in the TSDB mode?

@lalit-satapathy yes, dashboards and inventory page works (note: tested on linux system only, so the windows dashboard have some errors regarding missing metrics)

2023-05-31 13:28 UTC, leehinman requested changes

2023-05-31 13:28 UTC, leehinman commented on packages/system/data_stream/diskio/fields/agent.yml
> -    - name: os.name
why is just this `host.os.name` definition being removed?  It looks like we have the same duplication in other data_streams.  I'm just thinking if the duplication caused a problem once it probably will again, and we should clean it up for all the data streams.

2023-05-31 13:36 UTC, tetianakravchenko commented on packages/system/data_stream/diskio/fields/agent.yml
> -    - name: os.name
initial question and reply was here: https://github.com/elastic/integrations/pull/6118#discussion_r1196327806
for some reason after running `elastic-agent build` it changed the readme, I've cleaned it up only for relevant for this PR data_streams.

As cleaning up is not related to this PR and to the tsdb effort, I decided not to add it in the this PR

2023-05-31 19:49 UTC, leehinman commented on packages/system/data_stream/diskio/fields/agent.yml
> -    - name: os.name
OK, but please open a new Issue for cleaning up any duplicate field entries, we don't want to forget about them.

2023-05-31 19:49 UTC, leehinman approved these changes

2023-05-31 20:10 UTC, tetianakravchenko commented on packages/system/data_stream/diskio/fields/agent.yml
> -    - name: os.name
In data_stream follow up PRs I am removing duplications - like in https://github.com/elastic/integrations/pull/6407 or https://github.com/elastic/integrations/pull/6405

2023-05-31 20:14 UTC, tetianakravchenko commented on packages/system/data_stream/diskio/fields/agent.yml
> -    - name: os.name
issue - https://github.com/elastic/integrations/issues/6412

2023-05-31 20:14 UTC, merged

2023-05-31 23:45 UTC, elasticmachine commented
Package system - 1.30.0 containing this change is available at https://epr.elastic.co/search?package=system

2023-06-01 06:47 UTC, ruflin commented on packages/system/data_stream/diskio/fields/agent.yml
> -    - name: os.name
I'm in favor of cleaning up but glad to see we didn't mix it into the existing PR. Lets keep PR's small to make it easy for review and have many small follow up PRs to iterate quickly.