Prometheus Input Package
elastic/integrations pull request #6170
Opened 2023-05-11 16:51 UTC by ishleenk17

- Enhancement

## What does this PR do?

The Prometheus Input Package is developed in this PR.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally

Bring up any service pushing metrics to Prometheus Endpoint. Add the Prometheus Input Integration from Kibana. Add the appropriate input configurations. The metrics should be received in Kibana. 

## Related issues

- Closes https://github.com/elastic/integrations/issues/4615

## Screenshots

<img width="1697" alt="Screenshot 2023-05-11 at 10 19 08 PM" src="https://github.com/elastic/integrations/assets/102962586/1bb66411-16f9-472b-a607-dbee118fd684">

2023-05-11 16:56 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6170/detail/PR-6170/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6170/detail/PR-6170/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6170/detail/PR-6170/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6170/detail/PR-6170/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_6170.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-05-11T16:41:36.535Z&rangeTo=2023-05-11T17:01:36.535Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=622ea44b72e0e72c59c2fff4bb7f31ea&transactionId=c629a222fc753e65)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-05-11T16:51:36.535+0000


* Duration: 5 min 14 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6170/detail/PR-6170/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Checks and builds Go sources`
<ul>
<li>Took 0 min 25 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-6170/runs/1/steps/140/log/?start=0">here</a></li>
<li>Description: <code>mage -debug check</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-05-12 08:06 UTC, shmsr requested changes
Left some comments.

2023-05-12 08:06 UTC, shmsr commented on packages/prometheus_input/docs/README.md
> +- the dollar sign $ matches the end of a text.
```suggestion
- caret anchor `^` matches the beginning of a text
- dollar anchor `$` matches the end of a text
```

---

If really want to improve this doc and make it more explicit, we can refer this: https://learn.microsoft.com/en-us/dotnet/standard/base-types/anchors-in-regular-expressions

For multiline mode, we have not written anything. But for regex anchors, it's understood. So should we make it more explicit or not? What do you think?

2023-05-12 08:06 UTC, shmsr commented on packages/prometheus_input/docs/README.md
> +The users of the Prometheus Input Package have the option of adding their own dataset name, to which the events get added. Prometheus Metrics from different services can be collected by adding multip
```suggestion

The users of the Prometheus Input Package have the option of adding their own dataset name, to which the events get added. Prometheus Metrics from different services can be collected by adding multiple instances of the Input package. The metrics can be filtered on the basis of the dataset name.
```

2023-05-12 08:06 UTC, shmsr commented on packages/prometheus_input/fields/input.yml
> +  description: Sample field to be added.
```suggestion
  description: Sample description to be added.
```

2023-05-12 08:06 UTC, shmsr commented on packages/prometheus_input/fields/input.yml
> +    Prometheus rated counter metric
```suggestion
    Prometheus rate counter metric
```

rate or rated?

2023-05-12 08:06 UTC, shmsr commented on packages/prometheus_input/manifest.yml
> +description: "Collects Metrics from Prometheus Servers"
```suggestion
description: "Collects Metrics from Prometheus clients"
```

2023-05-12 08:12 UTC, shmsr requested changes

2023-05-12 08:12 UTC, shmsr commented on packages/prometheus_input/docs/README.md
> +`Use Types` parameter (default: true) enables a different layout for metrics storage, leveraging Elasticsearch
```suggestion
`Use Types` parameter (default: `true`) enables a different layout for metrics storage, leveraging Elasticsearch
```

2023-05-12 08:12 UTC, shmsr commented on packages/prometheus_input/docs/README.md
> +`Rate Counters` parameter (default: true) enables calculating a rate out of Prometheus counters. When enabled, integration stores
```suggestion
`Rate Counters` parameter (default: `true`) enables calculating a rate out of Prometheus counters. When enabled, integration stores
```

2023-05-12 08:12 UTC, shmsr commented on packages/prometheus_input/docs/README.md
> +performance. This parameter can only be enabled in combination with `Use Types`.
> This metric should make some aggregations easier and with better performance

I want to understand this. The addition of this metric make aggregation easier but we get better performance for what? Is it aggregation?

2023-05-12 08:36 UTC, lalit-satapathy commented on packages/prometheus_input/agent/input/input.yml.hbs
> +username: {{username}}
we can remove these two config if not passed by the user?

2023-05-12 08:36 UTC, lalit-satapathy commented on packages/prometheus_input/docs/README.md
> +The Prometheus input package connects to the Prometheus server and pulls metrics using the `/metrics` endpoint.
Metricbeat uses a better/correct description:
> To scrape metrics from a Prometheus exporter

The existing integration says though, is it in-accurate then?
>Prometheus integration collector dataset connects to the Prometheus server

We are scrapping from an exporter or Prometheus end point.

2023-05-12 08:36 UTC, lalit-satapathy commented on packages/prometheus_input/manifest.yml
> +  kibana.version: "^8.8.0"
should we offer user a lower stack version, where input package is supported?

2023-05-12 09:14 UTC, ishleenk17 commented on packages/prometheus_input/agent/input/input.yml.hbs
> +username: {{username}}
These configs (use_types and rate_counters) are booleans, so they can be toggled by user.

2023-05-12 09:15 UTC, ishleenk17 commented on packages/prometheus_input/manifest.yml
> +  kibana.version: "^8.8.0"
The complete functionality of input package has been provided from Fleet side 8.8.0 onwards. Hence we should keep this stack version. 
Infact, I would be upgrading the version for other input packages as well.

2023-05-12 09:28 UTC, ishleenk17 commented on packages/prometheus_input/docs/README.md
> +#### Scraping all metrics from a Prometheus server
Actually I need to remove this line as we are not supporting remote_write in input package.

2023-05-12 09:36 UTC, ishleenk17 commented on packages/prometheus_input/fields/input.yml
> +  description: Sample field to be added.
This is a sample field.

2023-05-12 10:48 UTC, ishleenk17 commented on packages/prometheus_input/manifest.yml
> +description: "Collects Metrics from Prometheus Servers"
I would use exporters here instead

2023-05-12 10:48 UTC, ishleenk17 commented on packages/prometheus_input/docs/README.md
> +The Prometheus input package connects to the Prometheus server and pulls metrics using the `/metrics` endpoint.
We scrape from Prometheus Exporters. So I would rename this to exporter

2023-05-12 10:50 UTC, ishleenk17 commented on packages/prometheus_input/docs/README.md
> +The Prometheus input package connects to the Prometheus server and pulls metrics using the `/metrics` endpoint.
Actually since this is only collector based, I would rather not have this line in the readme, since we are specifying the metrics collected from exporter before this

2023-05-12 11:29 UTC, ishleenk17 commented on packages/prometheus_input/docs/README.md
> +performance. This parameter can only be enabled in combination with `Use Types`.
We know about the better aggregation. So maybe, we can have only that for now for input package

2023-05-12 12:16 UTC, lalit-satapathy commented on packages/prometheus_input/agent/input/input.yml.hbs
> +username: {{username}}
Its about the username and password configs.

2023-05-12 13:29 UTC, ishleenk17 commented on packages/prometheus_input/agent/input/input.yml.hbs
> +username: {{username}}
These can also be passed by the user

2023-05-12 14:06 UTC, ishleenk17 commented on packages/prometheus_input/agent/input/input.yml.hbs
> +username: {{username}}
I have added them to the manifest file now

2023-05-12 17:00 UTC, shmsr requested changes
Left some minor comments. Otherwise, everything else LGTM.

2023-05-15 10:33 UTC, gizas commented on packages/prometheus_input/docs/README.md
> +The users of the Prometheus Input Package have the option of adding their own dataset name, to which the events get added. Prometheus Metrics from different services can be collected by adding multip
Does this mean that if they dont put something in the field, the field has a default value? 
No is not it?

So I guess the dataset name should go up in the Readme and be a required option for the user to fill in

2023-05-15 10:33 UTC, gizas approved these changes

2023-05-15 16:42 UTC, ishleenk17 commented on packages/prometheus_input/docs/README.md
> +The users of the Prometheus Input Package have the option of adding their own dataset name, to which the events get added. Prometheus Metrics from different services can be collected by adding multip
Yes, there is no default value by default. And this is a must field. 
I think to be on safer side we can have a default value for this as well.

2023-05-16 16:19 UTC, merged

2023-05-16 16:40 UTC, elasticmachine commented
Package prometheus_input - 0.0.1 containing this change is available at https://epr.elastic.co/search?package=prometheus_input

2023-05-25 09:52 UTC, ruflin commented
Glad to see this landed. Few follow up questions / thoughts:

* Mappings: The mappings [here](https://github.com/elastic/integrations/pull/6170/files#diff-02275a419a4fdc8b542c97cc539b99011b2af95caa357fc971f98a095def8daa), what dataset are these loaded for? 
* Do we use TSDB data streams by default? What are the default dimensions?
* Do we have routing permissions enabled on this input package. @gsantoro As it is an input package, will it have it by default?

Document based routing has landed in 8.8 and I think prometheus metrics is a prime use case for it. Even though we might not have default routing in place for now, we eventually should have, for example based on a service name field or similar. (@felixbarny ).

Prometheus also have some default mappings that are needed. If we do routing, the target data stream should have the same mappings (@weltenwort ). This implies that potentially we need reusable component templates loaded by input packages that then can be used also by the target data streams. @eyalkoren thinks about the naming of these.

Most folks I pinged above are thinking more about logs then metrics at the moment, but I expect things to work exactly the same in the metrics use case and prometheus is a good example for many discussions we had recently.

2023-05-25 09:54 UTC, ruflin commented
@ishleenk17 Too late but I realised the PR is likely not the right place for all of the discussions above. Where should we take it?

2023-05-25 10:24 UTC, ishleenk17 commented
> @ishleenk17 Too late but I realised the PR is likely not the right place for all of the discussions above. Where should we take it?

Lets track and discuss it as part of the [enhancements](https://github.com/elastic/integrations/issues/6320) for Prometheus Package ticket

2023-05-25 10:58 UTC, ruflin commented
SGTM. Copied it over to https://github.com/elastic/integrations/issues/6320#issuecomment-1562701369 Lets continue the conversation there.