Add API Gateway
elastic/integrations pull request #6188
Opened 2023-05-12 14:54 UTC by lucianpy

## What does this PR do?
Adds API Gateway metrics datastream

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2023-05-12 15:05 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6188/detail/PR-6188/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6188/detail/PR-6188/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6188/detail/PR-6188/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6188/detail/PR-6188/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_6188.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-05-12T14:44:24.555Z&rangeTo=2023-05-12T15:04:24.555Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=fc05300622e057dab3ac0fb0f301a153&transactionId=39e65d5187800482)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-05-12T14:54:24.555+0000


* Duration: 11 min 4 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![4](https://img.shields.io/badge/4%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6188/detail/PR-6188/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Check integration: aws`
<ul>
<li>Took 0 min 4 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-6188/runs/1/steps/1102/log/?start=0">here</a></li>
<li>Description: <code>../../build/elastic-package check -v</code></l1>
</ul>
  
  
  
  
##### `Take down the Elastic stack`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-6188/runs/1/steps/1121/log/?start=0">here</a></li>
<li>Description: <code>build/elastic-package stack down -v</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-6188/runs/1/steps/1141/log/?start=0">here</a></li>

</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-6188/runs/1/steps/1154/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-05-14 23:01 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`15/15`) | :green_heart: 
Files | 93.75% (`15/16`) | :-1: -3.384
Classes | 93.75% (`15/16`) | :-1: -3.384
Methods | 96.667% (`232/240`) | :+1: 4.194
Lines | 85.925% (`7387/8597`) | :-1: -6.06
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-05-16 05:36 UTC, shmsr requested changes
Left some comments.

2023-05-16 05:36 UTC, shmsr commented on packages/aws/data_stream/apigateway_metrics/agent/stream/stream.yml.hbs
> +  name:
If I look at this doc: https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-metrics-and-dimensions.html#:~:text=CloudWatch%20metrics.-,API%20Gateway%20metrics,-Amazon%20API%20Gateway

I do not see `5xx`, `4xx`, etc. Also in the doc, I see `Latency` which is not here. Is there documentation not up to date?

2023-05-16 05:36 UTC, shmsr commented on packages/aws/data_stream/apigateway_metrics/fields/fields.yml
> +              description: The total number API requests in a given period.
```suggestion
              description: The total number of API requests in a given period.
```

2023-05-16 05:36 UTC, shmsr commented on packages/aws/data_stream/apigateway_metrics/fields/fields.yml
> +          description: Each API created in API Gateway is assigned a unique ApiId, which is used to distinguish and reference that specific API within the system.
In the doc, I also don't see this. Can you please link from did you get this dimension?

2023-05-16 05:36 UTC, shmsr commented on packages/aws/data_stream/apigateway_metrics/fields/package-fields.yml
> +        Tag key value pairs from aws resources.
```suggestion
        Tag key-value pairs from AWS resources.
```

2023-05-16 05:36 UTC, shmsr commented on packages/aws/data_stream/apigateway_metrics/sample_event.json
> +                }
See `Latency` is here?

2023-05-16 05:36 UTC, shmsr commented on packages/aws/data_stream/apigateway_metrics/sample_event.json
> +                },
Ah, here I see `4xx` and `5xx`.

2023-05-16 05:36 UTC, shmsr commented on packages/aws/manifest.yml
> +    description: Collect logs and metrics for Amazon API Gateway with Elastic Agent
```suggestion
    description: Collect logs and metrics for Amazon API Gateway with Elastic Agent.
```

2023-05-16 05:36 UTC, shmsr commented on packages/aws/manifest.yml
> +        description: Collect API Gateway metrics using AWS CloudWatch
```suggestion
        description: Collect API Gateway metrics using AWS CloudWatch.
```

2023-05-16 05:36 UTC, shmsr commented on packages/aws/data_stream/apigateway_metrics/sample_event.json
> +                },
Also, saw this: https://github.com/aws/aws-cdk/blob/b885ece7285ebe8219dbe4d62ae80554bd657632/packages/%40aws-cdk/aws-apigatewayv2-alpha/lib/http/stage.ts#L107

2023-05-16 05:36 UTC, shmsr commented on packages/aws/data_stream/apigateway_metrics/sample_event.json
> +                },
Maybe there's no `4xxError` or `5xxError` metric. Maybe a mistake in their doc?

2023-05-16 08:55 UTC, shmsr commented
> Member

Oh, okay. Thanks for sharing!

2023-05-16 08:59 UTC, lucianpy commented on packages/aws/data_stream/apigateway_metrics/fields/package-fields.yml
> +        Tag key value pairs from aws resources.
This one is always the same, if you want, we can improve it starting with this PR.

2023-05-31 05:56 UTC, shmsr requested changes
Looks good to me. 

But as I'm still not much experienced with integrations as of now, I'd like to request you get another pair of eyes to review this PR. I might have missed something.

2023-05-31 05:56 UTC, shmsr commented on packages/aws/docs/apigateway.md
> +The AWS API Gateway integration allows you to monitor [API Gateway](https://aws.amazon.com/api-gateway/)—a centralized API management service.
```suggestion
The AWS API Gateway integration allows you to monitor [API Gateway](https://aws.amazon.com/api-gateway/) — a centralized API management service.
```

2023-05-31 05:56 UTC, shmsr commented on packages/aws/_dev/build/docs/apigateway.md
> +The AWS API Gateway integration allows you to monitor [API Gateway](https://aws.amazon.com/api-gateway/)—a centralized API management service.
```suggestion
The AWS API Gateway integration allows you to monitor [API Gateway](https://aws.amazon.com/api-gateway/) — a centralized API management service.
```

2023-05-31 20:59 UTC, gpop63 commented
LGTM, I'll take a look at the documentation.

2023-06-05 09:58 UTC, zmoog approved these changes
Please considers adding the latency doc from the other PR. 

LGTM.

2023-06-05 09:58 UTC, zmoog commented on packages/aws/data_stream/apigateway_metrics/fields/fields.yml
> +              description: The number of client-side errors captured in a given period.
To check my understanding after reading the comments: `4XXError` and `4xx` have the same semantics, but they come from different API types (REST vs. HTTP) right?

2023-06-05 09:58 UTC, zmoog commented on packages/aws/data_stream/apigateway_metrics/manifest.yml
> +      - name: latency
Stealing the `latency` description from https://github.com/elastic/integrations/pull/6231 

```suggestion
      - name: latency
        description: To address latency issues between certain AWS services and CloudWatch, specify a latency parameter to adjust the collection start time and end time in Metricbeat such as `5m`.
```

2023-06-05 10:29 UTC, lucianpy commented on packages/aws/data_stream/apigateway_metrics/fields/fields.yml
> +              description: The number of client-side errors captured in a given period.
Correct @zmoog

2023-06-05 11:07 UTC, gpop63 approved these changes

2023-06-05 11:17 UTC, shmsr approved these changes

2023-06-05 15:28 UTC, merged

2023-06-05 15:49 UTC, elasticmachine commented
Package aws - 1.39.0 containing this change is available at https://epr.elastic.co/search?package=aws