[Vsphere] Added dimensions field mapping for datastore datastream to …
elastic/integrations pull request #6304
Opened 2023-05-24 08:04 UTC by ritalwar

- Enhancement

## What does this PR do?

This PR adds dimension fields mapping for datastore data stream of Sphere to support TSDB enablement.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Relates #6266

2023-05-24 08:22 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6304/detail/PR-6304/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6304/detail/PR-6304/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6304/detail/PR-6304/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6304/detail/PR-6304/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_6304.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-05-24T07:54:57.598Z&rangeTo=2023-05-24T08:14:57.598Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=11408513147602c20973c80f532ddee7&transactionId=9e847ba61f605667)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-05-24T08:04:57.598+0000


* Duration: 17 min 25 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 17  |
| Skipped      | 0 |
| Total        | 17   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-05-26 08:25 UTC, shmsr requested changes

2023-05-26 08:25 UTC, shmsr commented on packages/vsphere/docs/README.md
> +| container.id | Unique container id. | keyword |  |  |
```suggestion
| cloud.account.id | The cloud account or organization id used to identify different entities in a multi-tenant environment. Examples: AWS account id, Google Cloud org id, or other unique identifier. | keyword |  |  |
| cloud.availability_zone | Availability zone in which host, resource, or service is located. | keyword |  |  |
| cloud.instance.id | Instance ID of the host machine. | keyword |  |  |
| cloud.project.id | The cloud project identifier. Examples: Google Cloud Project id, Azure Project id. | keyword |  |  |
| cloud.provider | Name of the cloud provider. Examples: aws, azure, gcp, or digitalocean. | keyword |  |  |
| cloud.region | Region in which host, resource, or service is located. | keyword |  |  |
| container.id | Unique container id. | keyword |  |  |
```

2023-05-26 08:25 UTC, shmsr commented on packages/vsphere/changelog.yml
> +    - description: Added dimensions field mapping for datastore datastream to support TSDB.
```suggestion
    - description: Add dimensions field mapping for datastore datastream to support TSDB.
```

Same reason: https://github.com/elastic/integrations/pull/6333#discussion_r1206407368

2023-05-26 08:25 UTC, shmsr commented on packages/vsphere/changelog.yml
> +    - description: Added dimensions field mapping for datastore datastream to support TSDB.
Also, PR title needs a similar update i.e., s/Added/Add

2023-05-26 08:54 UTC, ritalwar commented on packages/vsphere/docs/README.md
> +| container.id | Unique container id. | keyword |  |  |
This is auto-generated.

2023-05-26 10:34 UTC, shmsr commented on packages/vsphere/docs/README.md
> +| container.id | Unique container id. | keyword |  |  |
Ah, okay.

2023-05-30 06:17 UTC, agithomas approved these changes
LGTM!

2023-06-01 05:33 UTC, shmsr approved these changes
LGTM

2023-06-01 05:34 UTC, merged

2023-06-01 05:54 UTC, elasticmachine commented
Package vsphere - 1.7.0 containing this change is available at https://epr.elastic.co/search?package=vsphere