[Vsphere] Added dimensions field mapping for virtualmachine datastrea…
elastic/integrations pull request #6333
Opened 2023-05-26 07:36 UTC by ritalwar

- Enhancement

## What does this PR do?

This PR adds dimension fields mapping for virtual machine data stream of Sphere to support TSDB enablement.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Relates #6266

2023-05-26 08:19 UTC, shmsr requested changes

2023-05-26 08:19 UTC, shmsr commented on packages/vsphere/docs/README.md
> +| cloud.region | Region in which this host, resource, or service is located. | keyword |  |  |
```suggestion
| cloud.instance.id | Instance ID of the host machine. | keyword |  |  |
| cloud.project.id | The cloud project identifier. Examples: Google Cloud Project id, Azure Project id. | keyword |  |  |
| cloud.provider | Name of the cloud provider. Examples: aws, azure, gcp, or digitalocean. | keyword |  |  |
| cloud.region | Region in which host, resource, or service is located. | keyword |  |  |
```

2023-05-26 08:19 UTC, shmsr commented on packages/vsphere/changelog.yml
> +    - description: Added dimensions field mapping for virtualmachine datastream to support TSDB.
```suggestion
    - description: Add dimensions field mapping for virtualmachine datastream to support TSDB.
```

Reason: https://git.kernel.org/pub/scm/git/git.git/tree/Documentation/SubmittingPatches?h=v2.36.1#n181

> Describe your changes in imperative mood, e.g. "make xyzzy do frotz" instead of "[This patch] makes xyzzy do frotz" or "[I] changed xyzzy to do frotz", as if you are giving orders to the codebase to change its behavior.

Commit messages, changelog, PR titles, etc. ideally should follow this. This is the most recommended practice.

Also, it will match the tone of most changelog entries (if not all) we have made in the past i.e., `Migrate ...`, `Update ...`, etc.

2023-05-26 08:28 UTC, shmsr commented on packages/vsphere/changelog.yml
> +    - description: Added dimensions field mapping for virtualmachine datastream to support TSDB.
Also, PR title needs a little tweaking i.e., s/Added/Add

These are nit change requests but having a consistent way of writing and doing is definitely recommended.

2023-05-30 16:15 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6333/detail/PR-6333/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6333/detail/PR-6333/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6333/detail/PR-6333/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6333/detail/PR-6333/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_6333.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-05-30T15:46:45.481Z&rangeTo=2023-05-30T16:06:45.481Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=99962137e379f69cb1c157d22e863f72&transactionId=c0c079ff8fc82b7c)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-05-30T15:56:45.481+0000


* Duration: 19 min 31 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 17  |
| Skipped      | 0 |
| Total        | 17   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-05-30 16:15 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`1/1`) | :green_heart: 
Files | 100.0% (`1/1`) | :green_heart: 
Classes | 100.0% (`1/1`) | :green_heart: 
Methods | 100.0% (`18/18`) | :green_heart: 5.882
Lines | 89.13% (`41/46`) | :-1: -4.372
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-05-31 06:07 UTC, agithomas approved these changes
LGTM!

2023-06-01 06:23 UTC, shmsr approved these changes

2023-06-01 06:29 UTC, merged

2023-06-01 06:49 UTC, elasticmachine commented
Package vsphere - 1.7.2 containing this change is available at https://epr.elastic.co/search?package=vsphere