[SentinelOne_Cloud_Funnel] Initial release for the SentinelOne Cloud Funnel
elastic/integrations pull request #6386
Opened 2023-05-31 08:52 UTC by piyush-elastic

## What does this PR do?

- Updated data collection logic for the log data stream.
- Updated the ingest pipeline for the log data stream.
- Mapped fields according to the ECS schema and added Fields metadata in the appropriate yml files.
- Added dashboards and visualizations.
- Updated test for pipeline for the log data stream.
- Updated system test cases for the log data stream.

## Integration release checklist
This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes
- [x] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md)
- [x] Supported versions of the monitoring target is documented
- [x] Supported operating systems are documented (if applicable)
- [x] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [x] Documentation exists
- [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [x] At least a manual test with ES / Kibana / Agent has been performed.
- [x] Required Kibana version set to: ^8.3.0

### New Package
- [x] Screenshot of the "Add Integration" page on Fleet added

### Dashboards changes
- [x] Dashboards exists
- [x] Screenshots added or updated
- [x] Datastream filters added to visualizations

### Log dataset changes
- [x] [Pipeline tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/pipeline_testing.md) exist (if applicable)
- [x] Generated output for at least 1 log file exists
- [x] Sample event (sample_event.json) exists

## How to test this PR locally

- Clone integrations repo.
- Install elastic package locally.
- Start elastic stack using elastic-package.
- Move to integrations/packages/sentinel_one_cloud_funnel directory.
- Run the following command to run tests. 
> elastic-package test 

## Related issues

- Closes https://github.com/elastic/integrations/issues/6145

## Screenshots
![Screenshot 2023-05-29 131348](https://github.com/elastic/integrations/assets/124337008/d9d05177-9e0a-4435-af54-853a77ccc876)
![Screenshot 2023-05-29 131306](https://github.com/elastic/integrations/assets/124337008/bb81334a-04a9-4fdb-adc8-3bd6f128a883)
```2023/05/29 13:05:23 DEBUG Enable verbose logging
2023/05/29 13:05:25 DEBUG Error: can't check latest release, GET https://api.github.com/repos/elastic/elastic-package/releases/latest: 403 API rate limit exceeded for 117.217.127.213. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 3m05s]
Run test suite for the package
Run pipeline tests for the package
--- Test results for package: sentinel_one_cloud_funnel - START ---
╭───────────────────────────┬─────────────┬───────────┬────────────────────────────────────────┬────────┬──────────────╮
│ PACKAGE                   │ DATA STREAM │ TEST TYPE │ TEST NAME                              │ RESULT │ TIME ELAPSED │
├───────────────────────────┼─────────────┼───────────┼────────────────────────────────────────┼────────┼──────────────┤
│ sentinel_one_cloud_funnel │ event       │ pipeline  │ test-command-script.log                │ PASS   │ 190.869803ms │
│ sentinel_one_cloud_funnel │ event       │ pipeline  │ test-cross-process.log                 │ PASS   │  27.770119ms │
│ sentinel_one_cloud_funnel │ event       │ pipeline  │ test-dns.log                           │ PASS   │  34.706417ms │
│ sentinel_one_cloud_funnel │ event       │ pipeline  │ test-file.log                          │ PASS   │  25.355196ms │
│ sentinel_one_cloud_funnel │ event       │ pipeline  │ test-indicator.log                     │ PASS   │  27.550508ms │
│ sentinel_one_cloud_funnel │ event       │ pipeline  │ test-login.log                         │ PASS   │  14.970616ms │
│ sentinel_one_cloud_funnel │ event       │ pipeline  │ test-module.log                        │ PASS   │  15.957612ms │
│ sentinel_one_cloud_funnel │ event       │ pipeline  │ test-network-action.log                │ PASS   │  18.613347ms │
│ sentinel_one_cloud_funnel │ event       │ pipeline  │ test-process.log                       │ PASS   │  14.139338ms │
│ sentinel_one_cloud_funnel │ event       │ pipeline  │ test-registry.log                      │ PASS   │  14.955223ms │
│ sentinel_one_cloud_funnel │ event       │ pipeline  │ test-scheduled-task.log                │ PASS   │  12.350956ms │
│ sentinel_one_cloud_funnel │ event       │ pipeline  │ test-threat-intelligence-indicator.log │ PASS   │   16.33078ms │
│ sentinel_one_cloud_funnel │ event       │ pipeline  │ test-url.log                           │ PASS   │  10.554792ms │
╰───────────────────────────┴─────────────┴───────────┴────────────────────────────────────────┴────────┴──────────────╯
--- Test results for package: sentinel_one_cloud_funnel - END   ---
Done
Run static tests for the package
--- Test results for package: sentinel_one_cloud_funnel - START ---
╭───────────────────────────┬─────────────┬───────────┬──────────────────────────┬────────┬──────────────╮
│ PACKAGE                   │ DATA STREAM │ TEST TYPE │ TEST NAME                │ RESULT │ TIME ELAPSED │
├───────────────────────────┼─────────────┼───────────┼──────────────────────────┼────────┼──────────────┤
│ sentinel_one_cloud_funnel │ event       │ static    │ Verify sample_event.json │ PASS   │ 153.202407ms │
╰───────────────────────────┴─────────────┴───────────┴──────────────────────────┴────────┴──────────────╯
--- Test results for package: sentinel_one_cloud_funnel - END   ---
Done
Run system tests for the package
--- Test results for package: sentinel_one_cloud_funnel - START ---
No test results
--- Test results for package: sentinel_one_cloud_funnel - END   ---
Done
Run asset tests for the package
2023/05/29 13:06:57 DEBUG installing package...
2023/05/29 13:06:57 DEBUG POST https://127.0.0.1:5601/api/fleet/epm/packages/sentinel_one_cloud_funnel-0.1.0
--- Test results for package: sentinel_one_cloud_funnel - START ---
╭───────────────────────────┬─────────────┬───────────┬────────────────────────────────────────────────────────────────────────────────────┬────────┬──────────────╮
│ PACKAGE                   │ DATA STREAM │ TEST TYPE │ TEST NAME                                                                          │ RESULT │ TIME ELAPSED │
├───────────────────────────┼─────────────┼───────────┼────────────────────────────────────────────────────────────────────────────────────┼────────┼──────────────┤
│ sentinel_one_cloud_funnel │             │ asset     │ dashboard sentinel_one_cloud_funnel-008e94d0-facc-11ed-9768-a973b08e03b4 is loaded │ PASS   │      1.793µs │
│ sentinel_one_cloud_funnel │             │ asset     │ dashboard sentinel_one_cloud_funnel-42ecf8a0-fae3-11ed-a771-5bdf1dfe027b is loaded │ PASS   │        162ns │
│ sentinel_one_cloud_funnel │             │ asset     │ dashboard sentinel_one_cloud_funnel-724f8d70-f966-11ed-b51d-ef5658e04999 is loaded │ PASS   │        168ns │
│ sentinel_one_cloud_funnel │             │ asset     │ dashboard sentinel_one_cloud_funnel-afecde30-f966-11ed-b51d-ef5658e04999 is loaded │ PASS   │        190ns │
│ sentinel_one_cloud_funnel │             │ asset     │ dashboard sentinel_one_cloud_funnel-c90a2bc0-fa2e-11ed-b63a-6f5ce39a3d73 is loaded │ PASS   │        190ns │
│ sentinel_one_cloud_funnel │             │ asset     │ dashboard sentinel_one_cloud_funnel-dd209080-f967-11ed-b51d-ef5658e04999 is loaded │ PASS   │        220ns │
│ sentinel_one_cloud_funnel │             │ asset     │ search sentinel_one_cloud_funnel-6a9c9640-fa2e-11ed-b63a-6f5ce39a3d73 is loaded    │ PASS   │        263ns │
│ sentinel_one_cloud_funnel │ event       │ asset     │ index_template logs-sentinel_one_cloud_funnel.event is loaded                      │ PASS   │        643ns │
│ sentinel_one_cloud [...]

2023-05-31 09:52 UTC, jamiehynds commented on packages/sentinel_one_cloud_funnel/_dev/build/docs/README.md
> +
Reworded slightly: This [Sentinel One Cloud Funnel](https://assets.sentinelone.com/training/sentinelone_cloud_fu#page=1) integration enables your security team to securely stream XDR data to Elastic Security, via Amazon S3.  When integrated with Elastic Security, this valuable data can be leveraged within Elastic for threat protection, detection and incident response.

2023-05-31 09:58 UTC, jamiehynds commented on packages/sentinel_one_cloud_funnel/_dev/build/docs/README.md
> +## Setup
The steps below seem to outline how to set everything up on the AWS side. Can we add a section to outline what needs to be done within the integration settings on our side to get data streaming in?

2023-05-31 10:01 UTC, jamiehynds commented on packages/sentinel_one_cloud_funnel/manifest.yml
> +  kibana.version: ^8.3.0
Can we set the version to ^8.7.1, inline with our current Sentinel One integration?

2023-05-31 10:02 UTC, jamiehynds commented on packages/sentinel_one_cloud_funnel/_dev/build/docs/README.md
> +The minimum **kibana.version** required is **8.3.0**.
Can we adjust to 8.7.1, inline with our current Sentinel One integration?

2023-06-06 11:04 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2023-06-08 06:03 UTC, piyush-elastic commented on packages/sentinel_one_cloud_funnel/LICENSE.txt
@efd6  As per new version of elastic-package license file is getting created at package creation level reference - [elastic/elastic-package#898](https://github.com/elastic/elastic-package/pull/898) and before that we had been using old elastic-package version. Had discussion on same before [link](https://github.com/elastic/integrations/pull/5675#discussion_r1154800936)

2023-06-08 06:08 UTC, piyush-elastic commented on packages/sentinel_one_cloud_funnel/_dev/build/docs/README.md
> +Elastic Agent is required to stream data from the S3 bucket and ship the data to Elastic, where the events will then be processed via the integration's ingest pipelines.
I have checked but it's not a bullet list, it's normal text Please find attached.
![image](https://github.com/elastic/integrations/assets/124337008/9a41bf13-f4a1-4c47-9e36-2812cac8b26c)

2023-06-08 06:11 UTC, piyush-elastic commented on packages/sentinel_one_cloud_funnel/_dev/build/docs/README.md
> +You have a few options for installing and managing an Elastic Agent:
Both sentence looks same for me. Can you please highlight what's the suggested change?

2023-06-08 06:28 UTC, piyush-elastic commented on packages/sentinel_one_cloud_funnel/_dev/build/docs/README.md
> +### Install a Fleet-managed Elastic Agent (recommended):
It was done intentionally because 4 (hashes) will make text in capital(kindly look at Kibana) please find first attached. Let me know if that is what you are expecting. Ideally should be less in Bold when we use 4 #(hashes) which is working fine in VS code. Looks like Kibana formatting works in different way compare to VS code please find second attached.
![image](https://github.com/elastic/integrations/assets/124337008/39742b4c-a901-4296-b7c7-1081a3d5935e)
![image](https://github.com/elastic/integrations/assets/124337008/8e95041f-fe94-4132-b963-7cfffe3a8b7e)

2023-06-08 06:29 UTC, piyush-elastic commented on packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-module.log-expected.json
> +                    "command_line": "\"C:\\\\ProgramFiles\\\\SentinelOne\\\\SentinelAgent22.1.4.10010\\\\ranger\\\\SentinelRanger.exe\"\"{\\\"agentVersion\\\":\\\"22.1.4.10010\\\",\\\"authToken\\\":\
We have just kept it as same in input response. Sure will write script to unquote it.

2023-06-08 06:40 UTC, efd6 commented on packages/sentinel_one_cloud_funnel/_dev/build/docs/README.md
> +### Install a Fleet-managed Elastic Agent (recommended):
That's unfortunate. I'll take a look locally. Thanks.

2023-06-08 06:42 UTC, efd6 commented on packages/sentinel_one_cloud_funnel/_dev/build/docs/README.md
> +Elastic Agent is required to stream data from the S3 bucket and ship the data to Elastic, where the events will then be processed via the integration's ingest pipelines.
Yep, I expect that what is there is normal text, but it's split by sentence and the sentences look like they could be bullet list items, so I was wondering what your intention was here. I think a bullet list would be clearer.

2023-06-08 06:43 UTC, efd6 commented on packages/sentinel_one_cloud_funnel/LICENSE.txt
Yep, I know mechanically why it's there, but I'm not convinced that it's needed. It would be good to get another view on this.

2023-06-09 08:16 UTC, jamiehynds approved these changes
LGTM, thanks for implementing my suggested changes.

2023-06-09 08:48 UTC, efd6 requested changes

2023-06-09 08:48 UTC, efd6 commented on packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-module.log-expected.json
> +                                "cmd_line": "C:\\\\ProgramFiles\\\\SentinelOne\\\\SentinelAgent22.1.4.10010\\\\ranger\\\\SentinelRanger.exe\"\"{\\\"agentVersion\\\":\\\"22.1.4.10010\\\",\\\"authToken
I don't think the unquoting is correct for this. We should se a halving of the number of `\`. What we really need is a JSON unquote.

2023-06-13 07:04 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12)
* Commit: 2df3cecad7b0f8d3d21d8f6a18ebe7afa88ee2fa

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/12#0188b390-df43-45a8-a389-7b2a3e45779f)

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12","number":12,"commit":"2df3cecad7b0f8d3d21d8f6a18ebe7afa88ee2fa"}],"number":12}
buildkite-pr-comment-->

2023-06-13 07:34 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/13)
* Commit: a3e19d4c7313a9ceae95ab9cde507da3870eab7f

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/13#0188b3ac-afc6-43c7-8cf2-d8c90021513e)

### History
* :broken_heart: [Build #12](https://buildkite.com/elastic/integrations/builds/12) failed 2df3cecad7b0f8d3d21d8f6a18ebe7afa88ee2fa

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13","number":13,"commit":"a3e19d4c7313a9ceae95ab9cde507da3870eab7f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12","number":12,"commit":"2df3cecad7b0f8d3d21d8f6a18ebe7afa88ee2fa"}],"number":13}
buildkite-pr-comment-->

2023-06-13 09:27 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/22)
* Commit: 7917c1bfad68226fdd69b062de0890f4ca215412

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/22#0188b413-ec6c-41a9-a66c-74b1979add3e)

### History
* :broken_heart: [Build #13](https://buildkite.com/elastic/integrations/builds/13) failed a3e19d4c7313a9ceae95ab9cde507da3870eab7f
* :broken_heart: [Build #12](https://buildkite.com/elastic/integrations/builds/12) failed 2df3cecad7b0f8d3d21d8f6a18ebe7afa88ee2fa

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/22","number":22,"commit":"7917c1bfad68226fdd69b062de0890f4ca215412"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13","number":13,"commit":"a3e19d4c7313a9ceae95ab9cde507da3870eab7f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12","number":12,"commit":"2df3cecad7b0f8d3d21d8f6a18ebe7afa88ee2fa"}],"number":22}
buildkite-pr-comment-->

2023-06-13 10:35 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/28)
* Commit: 84a9e8b97d36b93096fdcf8bf9896f2f8d0f5903

### History
* :broken_heart: [Build #22](https://buildkite.com/elastic/integrations/builds/22) failed 7917c1bfad68226fdd69b062de0890f4ca215412
* :broken_heart: [Build #13](https://buildkite.com/elastic/integrations/builds/13) failed a3e19d4c7313a9ceae95ab9cde507da3870eab7f
* :broken_heart: [Build #12](https://buildkite.com/elastic/integrations/builds/12) failed 2df3cecad7b0f8d3d21d8f6a18ebe7afa88ee2fa

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/28","number":28,"commit":"84a9e8b97d36b93096fdcf8bf9896f2f8d0f5903"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/22","number":22,"commit":"7917c1bfad68226fdd69b062de0890f4ca215412"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13","number":13,"commit":"a3e19d4c7313a9ceae95ab9cde507da3870eab7f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12","number":12,"commit":"2df3cecad7b0f8d3d21d8f6a18ebe7afa88ee2fa"}],"number":28}
buildkite-pr-comment-->

2023-06-14 22:35 UTC, efd6 commented on packages/sentinel_one_cloud_funnel/_dev/build/docs/README.md
> +### Install a Fleet-managed Elastic Agent (recommended):
I have confirmed that kibana doesn't respect H4.

2023-06-15 10:32 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/133)
* Commit: 99bcffcf40710d9b64077a38800efe8c7d4b92b7

### History
* :green_heart: [Build #28](https://buildkite.com/elastic/integrations/builds/28) succeeded 84a9e8b97d36b93096fdcf8bf9896f2f8d0f5903
* :broken_heart: [Build #22](https://buildkite.com/elastic/integrations/builds/22) failed 7917c1bfad68226fdd69b062de0890f4ca215412
* :broken_heart: [Build #13](https://buildkite.com/elastic/integrations/builds/13) failed a3e19d4c7313a9ceae95ab9cde507da3870eab7f
* :broken_heart: [Build #12](https://buildkite.com/elastic/integrations/builds/12) failed 2df3cecad7b0f8d3d21d8f6a18ebe7afa88ee2fa

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/133","number":133,"commit":"99bcffcf40710d9b64077a38800efe8c7d4b92b7"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/28","number":28,"commit":"84a9e8b97d36b93096fdcf8bf9896f2f8d0f5903"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/22","number":22,"commit":"7917c1bfad68226fdd69b062de0890f4ca215412"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13","number":13,"commit":"a3e19d4c7313a9ceae95ab9cde507da3870eab7f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12","number":12,"commit":"2df3cecad7b0f8d3d21d8f6a18ebe7afa88ee2fa"}],"number":133}
buildkite-pr-comment-->

2023-06-15 11:33 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/135)
* Commit: 2cd904c73497d4a6b5dc7475ce5f812a783186db

### History
* :green_heart: [Build #133](https://buildkite.com/elastic/integrations/builds/133) succeeded 99bcffcf40710d9b64077a38800efe8c7d4b92b7
* :green_heart: [Build #28](https://buildkite.com/elastic/integrations/builds/28) succeeded 84a9e8b97d36b93096fdcf8bf9896f2f8d0f5903
* :broken_heart: [Build #22](https://buildkite.com/elastic/integrations/builds/22) failed 7917c1bfad68226fdd69b062de0890f4ca215412
* :broken_heart: [Build #13](https://buildkite.com/elastic/integrations/builds/13) failed a3e19d4c7313a9ceae95ab9cde507da3870eab7f
* :broken_heart: [Build #12](https://buildkite.com/elastic/integrations/builds/12) failed 2df3cecad7b0f8d3d21d8f6a18ebe7afa88ee2fa

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/135","number":135,"commit":"2cd904c73497d4a6b5dc7475ce5f812a783186db"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/133","number":133,"commit":"99bcffcf40710d9b64077a38800efe8c7d4b92b7"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/28","number":28,"commit":"84a9e8b97d36b93096fdcf8bf9896f2f8d0f5903"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/22","number":22,"commit":"7917c1bfad68226fdd69b062de0890f4ca215412"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13","number":13,"commit":"a3e19d4c7313a9ceae95ab9cde507da3870eab7f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12","number":12,"commit":"2df3cecad7b0f8d3d21d8f6a18ebe7afa88ee2fa"}],"number":135}
buildkite-pr-comment-->

2023-06-18 22:03 UTC, efd6 reviewed
Please address these unresolved comments:

- [ ] https://github.com/elastic/integrations/pull/6386/files#r1222318221
- [x] https://github.com/elastic/integrations/pull/6386/files#r1222319727
- [x] https://github.com/elastic/integrations/pull/6386/files#r1222320194
- [x] https://github.com/elastic/integrations/pull/6386/files#r1222320674
- [x] https://github.com/elastic/integrations/pull/6386/files#r1222324255
- [x] https://github.com/elastic/integrations/pull/6386/files#r1222349710
- [ ] https://github.com/elastic/integrations/pull/6386/files#r1222339921
- [ ] https://github.com/elastic/integrations/pull/6386/files#r1222346905
- [ ] https://github.com/elastic/integrations/pull/6386/files#r1222347549
- [ ] https://github.com/elastic/integrations/pull/6386/files#r1222345775
- [ ] https://github.com/elastic/integrations/pull/6386/files#r1222344859
- [ ] https://github.com/elastic/integrations/pull/6386/files#r1222332411

2023-06-19 07:33 UTC, piyush-elastic commented on packages/sentinel_one_cloud_funnel/_dev/build/docs/README.md
> +The minimum **kibana.version** required is **8.7.1**.
It is intended as suggested by @jamiehynds to add all the steps, we follow to mentioned that in requirement para.

2023-06-19 07:36 UTC, piyush-elastic commented on packages/sentinel_one_cloud_funnel/data_stream/event/elasticsearch/ingest_pipeline/default.yml
> +      if: ctx.json?.src?.process?.parent?.pid != ''
No need to handle this explicitly as `ignore_missing` already handles it https://www.elastic.co/guide/en/elasticsearch/reference/current/convert-processor.html

2023-06-19 07:55 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/212)
* Commit: a5d73dcd245f2bc9f16b3fbd7a3fcb69fb9b6b39

### History
* :green_heart: [Build #135](https://buildkite.com/elastic/integrations/builds/135) succeeded 2cd904c73497d4a6b5dc7475ce5f812a783186db
* :green_heart: [Build #133](https://buildkite.com/elastic/integrations/builds/133) succeeded 99bcffcf40710d9b64077a38800efe8c7d4b92b7
* :green_heart: [Build #28](https://buildkite.com/elastic/integrations/builds/28) succeeded 84a9e8b97d36b93096fdcf8bf9896f2f8d0f5903
* :broken_heart: [Build #22](https://buildkite.com/elastic/integrations/builds/22) failed 7917c1bfad68226fdd69b062de0890f4ca215412
* :broken_heart: [Build #13](https://buildkite.com/elastic/integrations/builds/13) failed a3e19d4c7313a9ceae95ab9cde507da3870eab7f
* :broken_heart: [Build #12](https://buildkite.com/elastic/integrations/builds/12) failed 2df3cecad7b0f8d3d21d8f6a18ebe7afa88ee2fa

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/212","number":212,"commit":"a5d73dcd245f2bc9f16b3fbd7a3fcb69fb9b6b39"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/135","number":135,"commit":"2cd904c73497d4a6b5dc7475ce5f812a783186db"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/133","number":133,"commit":"99bcffcf40710d9b64077a38800efe8c7d4b92b7"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/28","number":28,"commit":"84a9e8b97d36b93096fdcf8bf9896f2f8d0f5903"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/22","number":22,"commit":"7917c1bfad68226fdd69b062de0890f4ca215412"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/13","number":13,"commit":"a3e19d4c7313a9ceae95ab9cde507da3870eab7f"}],"number":212}
buildkite-pr-comment-->

2023-06-19 22:02 UTC, efd6 reviewed
Thanks. Only two remaining unresolved queries.

2023-06-20 07:17 UTC, efd6 approved these changes
Thanks

2023-06-20 09:37 UTC, merged