[Docker] Enable TSDB by default
elastic/integrations pull request #6647
Opened 2023-06-21 13:06 UTC by constanca-m

## What does this PR do?

Enable TSDB by default in all metrics data streams, except for events.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

Relates to https://github.com/elastic/integrations/issues/6393

2023-06-21 13:25 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6647/detail/PR-6647/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6647/detail/PR-6647/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6647/detail/PR-6647/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6647/detail/PR-6647/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_6647.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-06-21T12:57:12.339Z&rangeTo=2023-06-21T13:17:12.339Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=8121cae2dc5f53bf723876c92e5d0376&transactionId=2b740358edc7fd87)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-06-21T13:07:12.339+0000


* Duration: 18 min 18 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 38  |
| Skipped      | 0 |
| Total        | 38   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-06-26 14:33 UTC, lalit-satapathy approved these changes
LGTM

2023-06-27 09:05 UTC, tetianakravchenko requested changes

2023-06-27 09:05 UTC, tetianakravchenko commented on packages/docker/changelog.yml
> +- version: "2.7.1"
I think enablement of the feature and setting new stack version restriction should be `2.8.0`, not as a patch version

2023-06-27 09:09 UTC, constanca-m commented on packages/docker/changelog.yml
> +- version: "2.7.1"
Updated it.

2023-06-27 09:35 UTC, merged

2023-06-27 10:03 UTC, elasticmachine commented
Package docker - 2.8.0 containing this change is available at https://epr.elastic.co/search?package=docker