[Cloud Security] Update CloudFormation template
elastic/integrations pull request #6699
Opened 2023-06-26 15:02 UTC by orouz

## What does this PR do?

Updates the cloudformation template to use a new one. see https://github.com/elastic/cloudbeat/pull/1070

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

2023-06-26 15:17 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 
Classes | 100.0% (`0/0`) | :green_heart: 
Methods | 25.0% (`2/8`) | :-1: -62.952
Lines | 100.0% (`0/0`) | :green_heart: 8.989
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-06-27 06:20 UTC, amirbenun commented on packages/cloud_security_posture/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/6699
Since we are using preview versions this section is not required anymore (we tend to add it for major changes).
So in that case you can remove it or leave it, your call.
However, in order to test it you should bump the preview version.

2023-06-27 08:02 UTC, orestisfl requested changes

2023-06-27 08:02 UTC, orestisfl commented on packages/cloud_security_posture/changelog.yml
> +- version: "1.5.0-preview21"
You just need to bump the number, see as an example: https://github.com/elastic/integrations/pull/6622/files

2023-06-27 09:18 UTC, orestisfl approved these changes

2023-06-27 09:24 UTC, merged

2023-06-27 09:45 UTC, elasticmachine commented
Package cloud_security_posture - 1.5.0-preview21 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-07-11 16:53 UTC, elasticmachine commented
Package cloud_security_posture - 1.5.0-preview22 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-07-19 11:55 UTC, elasticmachine commented
Package cloud_security_posture - 1.5.0-preview23 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-07-24 17:29 UTC, elasticmachine commented
Package cloud_security_posture - 1.5.0-preview24 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-07-25 12:37 UTC, elasticmachine commented
Package cloud_security_posture - 1.5.0-preview25 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-07-30 06:19 UTC, elasticmachine commented
Package cloud_security_posture - 1.5.0-preview26 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-07-31 14:35 UTC, elasticmachine commented
Package cloud_security_posture - 1.5.0-preview27 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-08-21 10:51 UTC, elasticmachine commented
Package cloud_security_posture - 1.5.0 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture