Docker package: revert back change to dynamic_dataset/namespace
elastic/integrations pull request #6807
Opened 2023-07-04 10:48 UTC by gsantoro

## What does this PR do?

Revert back changes from issue https://github.com/elastic/kibana/pull/157897. 

Removing the following configs from the system package manifest

```
elasticsearch.dynamic_dataset: true
elasticsearch.dynamic_namespace: true
```

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

- Relates https://github.com/elastic/kibana/pull/157897

## Screenshots

2023-07-04 11:07 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6807/detail/PR-6807/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6807/detail/PR-6807/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6807/detail/PR-6807/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6807/detail/PR-6807/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_6807.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-07-04T10:39:04.724Z&rangeTo=2023-07-04T10:59:04.724Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=f307bb20c9368f197d045d8909083d39&transactionId=93847c79615552f2)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-07-04T10:49:04.724+0000


* Duration: 19 min 31 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 38  |
| Skipped      | 0 |
| Total        | 38   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-07-04 11:07 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 
Classes | 100.0% (`0/0`) | :green_heart: 
Methods | 96.667% (`29/30`) | :+1: 10.952
Lines | 100.0% (`0/0`) | :green_heart: 6.228
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-07-04 14:37 UTC, ruflin reviewed
This one here we should discuss further @felixbarny My understanding is, this reads all logs from the containers. Unfortunately, it does at the same time monitoring of docker itself so we basically mix two things.

2023-07-05 11:54 UTC, felixbarny requested changes
The docker.container_logs data stream still needs to support routing. The other data streams that monitor docker itself have never allowed for routing.

2023-07-06 10:54 UTC, gsantoro commented
@felixbarny and @ruflin ,
can we agree here that I should just close this PR and not merge it since this package is the correct one that route Docker traffic?

2023-07-06 11:50 UTC, felixbarny commented
yes

2023-07-06 11:56 UTC, gsantoro commented
Closing this PR without merging since this package should correctly route traffic from container logs

2023-07-06 11:56 UTC, closed without merging