Kubernetes package: revert back change to dynamic_dataset/namespace
elastic/integrations pull request #6809
Opened 2023-07-04 10:58 UTC by gsantoro

## What does this PR do?

Revert back changes from issue https://github.com/elastic/kibana/pull/157897. 

Removing the following configs from the system package manifest

```
elasticsearch.dynamic_dataset: true
elasticsearch.dynamic_namespace: true
```

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

- Relates https://github.com/elastic/kibana/pull/157897

## Screenshots

2023-07-04 11:30 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6809/detail/PR-6809/2//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6809/detail/PR-6809/2//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6809/detail/PR-6809/2//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6809/detail/PR-6809/2//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_6809.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-07-04T10:50:14.021Z&rangeTo=2023-07-04T11:10:14.021Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=00315f48d51e810424e950ffbdce3f26&transactionId=2d2ab6caa53ec07c)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-07-04T11:00:14.021+0000


* Duration: 30 min 17 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 92  |
| Skipped      | 0 |
| Total        | 92   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-07-04 11:30 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 
Classes | 100.0% (`0/0`) | :green_heart: 
Methods | 96.154% (`75/78`) | :+1: 10.44
Lines | 100.0% (`0/0`) | :green_heart: 6.228
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-07-04 13:03 UTC, ChrsMark commented
I have no objection into merging this however it would be nice if we can have a description in the PR about why this change is needed and what are the related issues/discussions etc. Otherwise it will just be landed with no additional context which makes it hard to understand the why.

2023-07-04 14:39 UTC, ruflin reviewed
This is similar to the conversation around docker logs. I think there should eventually be a separate input package for this.

* Where are the logs shipped by default at the moment?
* Do we have any dashboards, mappings or anything around the destination of these logs at the moment?

2023-07-04 15:54 UTC, gsantoro commented
hello @ruflin , about your questions, 
1. logs are shipped by default to the datastream `logs-kubernetes.container_logs-default`
2. the datastream `container_logs` has mappings that are specific for kubernetes about pods, nodes, etc. There is no ingest pipeline or dashboard.

2023-07-05 06:51 UTC, gizas approved these changes

2023-07-05 08:43 UTC, ruflin commented
> the datastream container_logs has mappings that are specific for kubernetes about pods, nodes, etc. There is no ingest pipeline or dashboard.

How much of these mappings would be covered by the new ECS dynamic mappings created by @eyalkoren I'm curious if there are any fields which would not be mapped correctly by default.

@felixbarny Even though I think we should have a separate package with a new destination for these logs eventually, should we keep the routing permissions here?

2023-07-05 09:58 UTC, felixbarny requested changes
> @felixbarny Even though I think we should have a separate package with a new destination for these logs eventually, should we keep the routing permissions here?

I think we should. And therefore I'm objecting to revert these changes. We should not revert changes for packages that ought to be input packages. We should only revert in packages that monitor the service itself, such as logs that Kafka produces itself, not custom logs that are shipped via Kafka.

2023-07-05 10:53 UTC, ruflin commented
> We should not revert changes for packages that ought to be input packages.

The problem here is we mix input package and the normal package together. But I think we are aligned to keep it for this scenario.

2023-07-05 11:46 UTC, felixbarny commented
> The problem here is we mix input package and the normal package together.

It is but I don't think it's a big issue as the permissions are per data stream, not per package.

> But I think we are aligned to keep it for this scenario.

👍

2023-07-05 11:57 UTC, ruflin commented
> It is but I don't think it's a big issue as the permissions are per data stream, not per package.

Permissions sent down by Fleet are per agent which is the summary of permissions for enabled datasets. But this also is only an issue with Fleet, standalone the user can pick the API key permission they prefer.

2023-07-05 12:08 UTC, felixbarny commented
Right, but if users have enabled the k8s integration and disabled the container_logs data stream, the API key doesn't contain permissions for `logs-*-*`.

2023-07-06 10:56 UTC, gsantoro commented
@felixbarny and @ruflin ,
can we agree here to close this PR and not merge it since this package is correctly routing Kubernetes traffic?

2023-07-06 11:51 UTC, felixbarny commented
👍

2023-07-06 11:58 UTC, gsantoro commented
Closing this PR and not merging it since this package should reroute traffic from kubernetes container logs

2023-07-06 11:58 UTC, closed without merging