Adding vulnerability fields
elastic/integrations pull request #6823
Opened 2023-07-05 12:24 UTC by jeniawhite

## What does this PR do?
Added additional fields to the vulnerability mappings.
Added an ingest upgrade for older vulnerability findings to include type.
This PR is based on changes:
- https://github.com/elastic/cloudbeat/pull/1081

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues
- Relates https://github.com/elastic/cloudbeat/issues/983
- Requires https://github.com/elastic/cloudbeat/pull/1081

2023-07-05 12:36 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6823/detail/PR-6823/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6823/detail/PR-6823/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6823/detail/PR-6823/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6823/detail/PR-6823/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_6823.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-07-05T12:15:08.642Z&rangeTo=2023-07-05T12:35:08.642Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=d06575e65e6443091f601378b2d09ccb&transactionId=04f631eac46c64e4)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-07-05T12:25:08.642+0000


* Duration: 11 min 27 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![4](https://img.shields.io/badge/4%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6823/detail/PR-6823/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Check integration: cloud_security_posture`
<ul>
<li>Took 0 min 1 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-6823/runs/1/steps/1118/log/?start=0">here</a></li>
<li>Description: <code>../../build/elastic-package check -v</code></l1>
</ul>
  
  
  
  
##### `Take down the Elastic stack`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-6823/runs/1/steps/1137/log/?start=0">here</a></li>
<li>Description: <code>build/elastic-package stack down -v</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-6823/runs/1/steps/1157/log/?start=0">here</a></li>

</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-6823/runs/1/steps/1170/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-07-05 12:40 UTC, amirbenun reviewed
ECS compliant fields should go to `ecs.yml`

2023-07-06 08:40 UTC, amirbenun commented
I think that non-ECS fields should also declare type in their mapping, so I thought it will be easier to use `ecs.yml` instead of declaring all the types.
@kfirpeled am I correct here?

2023-07-18 10:01 UTC, amirbenun commented on packages/cloud_security_posture/data_stream/vulnerabilities/fields/cloud.yml
> +      type: keyword
we might want to have `network` and `security` here as well

2023-07-19 11:19 UTC, kfirpeled requested changes
requested changes to move `security` to be under `cloud_security_posture`

2023-07-19 11:19 UTC, kfirpeled commented on packages/cloud_security_posture/data_stream/vulnerabilities/elasticsearch/ingest_pipeline/default.yml
> +      if: ctx.cloud?.service?.name == null
💯

2023-07-19 11:19 UTC, kfirpeled commented on packages/cloud_security_posture/data_stream/vulnerabilities/fields/network.yml
> +    - name: private_ip
consider capitalization for custom fields to avoid future conflicts
see guideline suggestion: https://www.elastic.co/guide/en/ecs/current/ecs-custom-fields-in-ecs.html

2023-07-19 11:19 UTC, kfirpeled commented on packages/cloud_security_posture/data_stream/vulnerabilities/fields/security.yml
> +- name: security
lets avoid top-level custom fields (`security` is not part of ECS)
the current guideline is to move `security` to be under a field that is named with the plugin name. In our case that is `cloud_security_posture`.

So the final field here would be `cloud_security_posture.security.security_groups`

cc: @eyalkraft , @oren-zohar

2023-07-19 11:19 UTC, kfirpeled commented on packages/cloud_security_posture/data_stream/vulnerabilities/fields/cloud.yml
> +- name: cloud
consider capitalization for custom fields to avoid future conflicts
see guideline suggestion: https://www.elastic.co/guide/en/ecs/current/ecs-custom-fields-in-ecs.html

2023-07-19 11:22 UTC, kfirpeled commented
> @amirbenun Notice that I did not update the ECS fields due to this:
> 
> * [Enhance CNVM index cloudbeat#1081 (comment)](https://github.com/elastic/cloudbeat/pull/1081#issuecomment-1621579948)

Currently, using the auto-import is blocked and it is not clear if it will be available for 8.10 release.
@jeniawhite  I suggest to update ECS fields as well

> I think that non-ECS fields should also declare type in their mapping, so I thought it will be easier to use ecs.yml instead of declaring all the types.
@kfirpeled am I correct here?

I would keep the convention of using ecs.yml to declare only ecs fields. And anything else is for custom fields (aka non-ECS).

2023-08-13 21:26 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 3.367
Classes | 100.0% (`0/0`) | :green_heart: 3.367
Methods | 25.0% (`2/8`) | :-1: -66.9
Lines | 100.0% (`0/0`) | :green_heart: 11.692
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-08-15 11:27 UTC, amirbenun approved these changes

2023-08-15 11:27 UTC, amirbenun commented on packages/cloud_security_posture/data_stream/vulnerabilities/fields/resource.yml
> +# Deprecated replaced by cloud and host fields
```suggestion
# Deprecated replaced by cloud.instance fields
```

2023-08-15 14:43 UTC, kfirpeled approved these changes
lgtm

2023-08-15 15:01 UTC, merged