Draft: Add user detail fields for actor, object, and aux_info.
elastic/integrations pull request #6851
Opened 2023-07-06 19:24 UTC by Jin-Dhaliwal

## What does this PR do?

We've added new details fields to the data model that we want to consumed through this integration. An example of the original message would be:

```
                 {
			"uuid": "2CA5O6WU4VOPE225X64BMDJ6M3",
			"timestamp": "2023-06-30T18:02:23.273264Z",
			"actor_uuid": "PPQYFXGORNDIRHFJ43QNOEKZ6A",
			"actor_details": {
				"uuid": "PPQYFXGORNDIRHFJ43QNOEKZ6A",
				"name": "Insights Test",
				"email": "jin.dhaliwal+insightstest@agilebits.com"
			},
			"action": "trvlaway",
			"object_type": "user",
			"object_uuid": "X3TLF2JNIVDKJAXU67SNSHCFBU",
			"object_details": {
				"uuid": "X3TLF2JNIVDKJAXU67SNSHCFBU",
				"name": "Member 7",
				"email": "jin.dhaliwal+m7@agilebits.com"
			},
			"session": {
				"uuid": "RD4MLUQFIZDW5G6MUFFBIYUUBM",
				"login_time": "2023-06-30T18:01:42.300478Z",
				"device_uuid": "gdbhmdzsecieklx5wmgr7qy6oe",
				"ip": "172.19.0.1"
			}
		}
```

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] Integration tests pass 
- [ ] Integration includes the new details fields in processed event data

## How to test this PR locally

Follow the testing steps outlined here: https://developer.1password.com/docs/events-api/reference/#post-apiv1auditevents

1. Get the elastic stack up and running. 
2. Follow the integration steps to set up the 1Password integration. (You will need a 1password business account)
  - You can create a test account on start.b5dev.com and use Stripe test card `4242424242424242` 
  - You'll need to change the URL in the integration setup to events.b5dev.com
3. On your 1Password account add some members/groups/vaults/items. This will generate events that the integration will capture. 
4. Confirm that the audit events dashboard contains those events and the new details fields are present. 

## Screenshots

![Screenshot 2023-07-06 at 12 40 22 PM](https://github.com/elastic/integrations/assets/1211388/59c04611-4c30-4f66-9c5c-64cc35e145d6)
![Screenshot 2023-07-06 at 12 40 03 PM](https://github.com/elastic/integrations/assets/1211388/7104dc89-a1f2-467d-838b-3198240cdfb5)

2023-07-06 19:29 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6851/detail/PR-6851/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6851/detail/PR-6851/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6851/detail/PR-6851/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6851/detail/PR-6851/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-07-06T19:15:10.443Z&rangeTo=2023-07-06T19:35:10.443Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=37052b82f03e8f8a8adf19c1da96df0f&transactionId=0a9c0fea8582aad2)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-07-06T19:25:10.443+0000


* Duration: 4 min 0 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6851/detail/PR-6851/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Load a resource file from a library`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-6851/runs/1/steps/81/log/?start=0">here</a></li>
<li>Description: <code>approval-list/elastic/integrations.yml</code></l1>
</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-6851/runs/1/steps/89/log/?start=0">here</a></li>
<li>Description: <code>githubApiCall: The REST API call https://api.github.com/orgs/elastic/members/Jin-Dhaliwal return the message : java.lang.Exception: httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/Jin-Dhaliwal : httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/Jin-Dhaliwal : Code: 404Error: {"message":"User does not exist or is not a member of the organization","documentation_url":"https://docs.github.com/rest/reference/orgs#check-organization-membership-for-a-user"}</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-07-07 11:57 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2023-07-10 00:38 UTC, efd6 commented
/test

2023-07-10 00:54 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`3/3`) | :green_heart: 
Files | 100.0% (`3/3`) | :green_heart: 12.5
Classes | 100.0% (`3/3`) | :green_heart: 12.5
Methods | 90.909% (`30/33`) | :+1: 7.213
Lines | 87.888% (`283/322`) | :-1: -4.932
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-07-12 09:32 UTC, kcreddy requested changes
Thanks for the contribution! 

Could you also update ingest pipeline to add User ECS mapping? For example, you could add `user.name` field from `actor_details.name` field.

More examples on User ECS field that you could map: https://www.elastic.co/guide/en/ecs/current/ecs-user-usage.html

2023-07-12 09:32 UTC, kcreddy commented on packages/1password/data_stream/audit_events/fields/fields.yml
> +          type: text
```suggestion
          type: keyword
```

2023-07-12 09:32 UTC, kcreddy commented on packages/1password/data_stream/audit_events/fields/fields.yml
> +          type: text
```suggestion
          type: keyword
```

2023-07-12 09:32 UTC, kcreddy commented on packages/1password/data_stream/audit_events/fields/fields.yml
> +          type: text
```suggestion
          type: keyword
```

2023-07-17 13:50 UTC, Jin-Dhaliwal commented
Anything left on this one? Would like to get this out asap because we've released the new version of the API and customers will want to start ingesting the new fields.

2023-07-26 18:57 UTC, Jin-Dhaliwal commented
@kcreddy is there any other changes needed here or is this ready for merge now?

2023-07-27 03:07 UTC, kcreddy commented
/test

2023-07-27 05:39 UTC, kcreddy commented
/test

2023-07-27 14:00 UTC, kcreddy commented
Sincere apologies for the delay 🙏🏼 . 

Looks like the CI is failing due to README being not updated. Can you run below command and commit ?

`elastic-package build && elastic-package format && elastic-package lint && elastic-package check && elastic-package build`

2023-07-27 15:21 UTC, Jin-Dhaliwal commented
@kcreddy done!

2023-07-27 16:48 UTC, kcreddy commented
/test

2023-07-28 06:12 UTC, kcreddy commented
Okay, now the CI is failing on pipeline tests. Looks like after the `user` ECS fields are added, the pipeline tests are not updated.

Can you run pipeline tests after bringing the stack up?
`eval "$(elastic-package stack shellinit)" && elastic-package test pipeline --generate` and then commit.

2023-07-29 13:04 UTC, kcreddy commented
/test

2023-07-29 13:11 UTC, kcreddy commented
/test

2023-07-31 06:51 UTC, kcreddy commented
/test

2023-07-31 06:58 UTC, kcreddy commented
@Jin-Dhaliwal can you please fix the merge conflicts? The CI wouldn't run otherwise. Thanks!

2023-08-02 15:51 UTC, Jin-Dhaliwal commented
/test

2023-08-02 15:57 UTC, Jin-Dhaliwal commented
@kcreddy OK conflicts resolved

2023-08-02 15:57 UTC, kcreddy commented
/test

2023-08-03 05:02 UTC, kcreddy commented
/test

2023-08-03 11:17 UTC, kcreddy approved these changes
LGTM 👍🏼

2023-08-03 11:19 UTC, kcreddy commented
> How can I fix those failures in CI? I'm not sure what happened. Reading at face value seems like service that the test step needed failed to start?
Is there a way to restart those?

Hey, @Jin-Dhaliwal the issue was with the CI system, your changes are good. 
Once again thanks so much for the contribution 😄

2023-08-03 11:19 UTC, merged

2023-08-03 11:41 UTC, elasticmachine commented
Package 1password - 1.18.0 containing this change is available at https://epr.elastic.co/search?package=1password