[IIS] Update document with access_log supported ingest patterns
elastic/integrations pull request #6892
Opened 2023-07-10 10:03 UTC by muthu-mps

- Enhancement

## What does this PR do?

The IIS access_log provides flexibility for the customer to edit the default logging fields and add new fields. The IIS integration currently supports the default and a few custom selection's. The supported patterns are captured in the document.

## How to test this PR locally

Verify the documentation in the access_log section and make sure that the supported patterns are captured.

- Closes #6709

2023-07-10 10:18 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6892/detail/PR-6892/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6892/detail/PR-6892/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6892/detail/PR-6892/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6892/detail/PR-6892/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_6892.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-07-10T09:54:07.947Z&rangeTo=2023-07-10T10:14:07.947Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=b397799483d05e3d5970d4ec78d4ca34&transactionId=736a609122b0f65d)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-07-10T10:04:07.947+0000


* Duration: 14 min 15 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 29  |
| Skipped      | 0 |
| Total        | 29   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-07-10 10:18 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`2/2`) | :green_heart: 
Files | 100.0% (`2/2`) | :green_heart: 11.111
Classes | 100.0% (`2/2`) | :green_heart: 11.111
Methods | 85.714% (`30/35`) | :-1: -1.886
Lines | 93.772% (`271/289`) | :+1: 6.647
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-07-17 21:04 UTC, shmsr requested changes
Please refer to this: https://www.crowdstrike.com/cybersecurity-101/observability/iis-logs/

Did we miss a format (see the blog by Crowdstrike)? And can we elaborate on some points like in this blog? Also, we have not referenced any official document or so. Please add some links so that users can cross-check what's written here.

Also, see: https://github.com/ossec/ossec-hids/blob/7b3e12bc9dddac561da2d10331a482d501af74b0/etc/decoder.xml#L1868

2023-07-17 21:09 UTC, shmsr commented on packages/iis/changelog.yml
> +    - description: Update document with access_log processor patterns supported by default
Please make this description in sync with PR title or more or less similar.

2023-07-17 21:09 UTC, shmsr commented on packages/iis/manifest.yml
> +version: "1.14.0"
For a documentation update, do we do a minor release or a patch release? I'm talking in terms of semver.

2023-07-18 06:33 UTC, muthu-mps commented on packages/iis/manifest.yml
> +version: "1.14.0"
yeah, here we are considering it as documentation enhancement thats why we consider this as a minor release instead of patch.

2023-07-18 17:14 UTC, shmsr commented
Did you check this comment: https://github.com/elastic/integrations/pull/6892#pullrequestreview-1533679653?

2023-07-19 05:56 UTC, muthu-mps commented
> Please refer to this: https://www.crowdstrike.com/cybersecurity-101/observability/iis-logs/
> 
> Did we miss a format (see the blog by Crowdstrike)? And can we elaborate on some points like in this blog? Also, we have not referenced any official document or so. Please add some links so that users can cross-check what's written here.
 
> Also, see: https://github.com/ossec/ossec-hids/blob/7b3e12bc9dddac561da2d10331a482d501af74b0/etc/decoder.xml#L1868

You mean the log format like W3C, We have captured the supported log formats in the document already. Its not necessary to cover the logging formats what IIS provides in detail as of now as we don't support them right now.

We have the IIS logging official document link included.

2023-07-19 06:28 UTC, shmsr requested changes

2023-07-19 06:28 UTC, shmsr commented on packages/iis/_dev/build/docs/README.md
> +The IIS ships logs with few properties by default and if the user is interested in customizing the selection, the IIS Manager provides ability to add new fields for logging.
`fields` and `properties` are used interchangeably. Stick to `field`.

Ref: https://www.crowdstrike.com/cybersecurity-101/observability/iis-logs/

2023-07-19 06:28 UTC, shmsr commented on packages/iis/_dev/build/docs/README.md
> +#### Custom Logging:
Are the custom logging formats listed here supported by default?

2023-07-19 06:55 UTC, muthu-mps commented on packages/iis/_dev/build/docs/README.md
> +#### Custom Logging:
yes, The listed ones are supported by default.

2023-07-19 10:29 UTC, shmsr approved these changes
Looks good.

2023-07-19 10:30 UTC, merged

2023-07-19 10:51 UTC, elasticmachine commented
Package iis - 1.14.0 containing this change is available at https://epr.elastic.co/search?package=iis