Seperate cloud formation templates for CSPM and CNVM
elastic/integrations pull request #6899
Opened 2023-07-10 20:07 UTC by jeniawhite

## What does this PR do?
Direct the user to different cloud formation templates instead of a single template with params

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues
- Closes https://github.com/elastic/cloudbeat/issues/1122
- Relates https://github.com/elastic/cloudbeat/pull/1125

2023-07-10 20:17 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6899/detail/PR-6899/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6899/detail/PR-6899/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6899/detail/PR-6899/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6899/detail/PR-6899/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_6899.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-07-10T19:57:19.010Z&rangeTo=2023-07-10T20:17:19.010Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=5bb1a48f58e9a16a1ddb4969eda8621a&transactionId=63d30ae344974405)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-07-10T20:07:19.010+0000


* Duration: 11 min 31 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![4](https://img.shields.io/badge/4%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6899/detail/PR-6899/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Check integration: cloud_security_posture`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-6899/runs/1/steps/1122/log/?start=0">here</a></li>
<li>Description: <code>../../build/elastic-package check -v</code></l1>
</ul>
  
  
  
  
##### `Take down the Elastic stack`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-6899/runs/1/steps/1141/log/?start=0">here</a></li>
<li>Description: <code>build/elastic-package stack down -v</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-6899/runs/1/steps/1161/log/?start=0">here</a></li>

</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-6899/runs/1/steps/1174/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-07-10 21:13 UTC, oren-zohar commented on packages/cloud_security_posture/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/XXXX
I always like to look at the last PR that was open before submitting the change and predict the right link lol

2023-07-12 11:54 UTC, oren-zohar requested changes

2023-07-12 11:54 UTC, oren-zohar commented on packages/cloud_security_posture/manifest.yml
> +            default: https://console.aws.amazon.com/cloudformation/home#/stacks/quickcreate?templateURL=https://elastic-cspm-cft.s3.eu-central-1.amazonaws.com/cloudformation-cspm-8.10.0-2023-06-26-13
why did you remove `param_Integration`?

2023-07-13 06:44 UTC, jeniawhite commented on packages/cloud_security_posture/manifest.yml
> +            default: https://console.aws.amazon.com/cloudformation/home#/stacks/quickcreate?templateURL=https://elastic-cspm-cft.s3.eu-central-1.amazonaws.com/cloudformation-cspm-8.10.0-2023-06-26-13
Because we do not have a dynamic template anymore, and this variable was being used in order to know what template to generate.
If you notice we now have two separate templates and two separate links.

2023-07-13 07:39 UTC, oren-zohar approved these changes

2023-07-13 07:40 UTC, oren-zohar approved these changes

2023-07-13 07:40 UTC, oren-zohar commented on packages/cloud_security_posture/manifest.yml
need to update the version

2023-07-16 08:25 UTC, amirbenun requested changes
you should only merge it after you merge https://github.com/elastic/cloudbeat/pull/1125/files and trigger a new file upload to S3

2023-07-16 08:25 UTC, amirbenun commented on packages/cloud_security_posture/manifest.yml
> +            default: https://console.aws.amazon.com/cloudformation/home#/stacks/quickcreate?templateURL=https://elastic-cspm-cft.s3.eu-central-1.amazonaws.com/cloudformation-cspm-8.10.0-2023-06-26-13
This won't work since this file does not exist yet in S3

2023-07-16 16:57 UTC, jeniawhite commented on packages/cloud_security_posture/manifest.yml
> +            default: https://console.aws.amazon.com/cloudformation/home#/stacks/quickcreate?templateURL=https://elastic-cspm-cft.s3.eu-central-1.amazonaws.com/cloudformation-cspm-8.10.0-2023-06-26-13
Yeah, this is why this PR is still open.
- https://github.com/elastic/cloudbeat/pull/1125
Is in the related PRs and is blocking the merge of this PR.

2023-07-19 10:47 UTC, amirbenun commented on packages/cloud_security_posture/changelog.yml
>    changes:
```suggestion
```

2023-07-19 10:54 UTC, amirbenun approved these changes

2023-07-19 10:58 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 
Classes | 100.0% (`0/0`) | :green_heart: 
Methods | 25.0% (`2/8`) | :-1: -66.667
Lines | 100.0% (`0/0`) | :green_heart: 3.438
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-07-19 11:33 UTC, merged

2023-07-19 11:55 UTC, elasticmachine commented
Package cloud_security_posture - 1.5.0-preview23 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-07-24 17:29 UTC, elasticmachine commented
Package cloud_security_posture - 1.5.0-preview24 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-07-25 12:37 UTC, elasticmachine commented
Package cloud_security_posture - 1.5.0-preview25 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-07-30 06:19 UTC, elasticmachine commented
Package cloud_security_posture - 1.5.0-preview26 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-07-31 14:35 UTC, elasticmachine commented
Package cloud_security_posture - 1.5.0-preview27 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-08-21 10:51 UTC, elasticmachine commented
Package cloud_security_posture - 1.5.0 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture