Add merge result feature to sql Input package
elastic/integrations pull request #6922
Opened 2023-07-11 18:07 UTC by ishleenk17

- Enhancement

## What does this PR do?

This PR adds the merge_results feature to SQL Input Package. 

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Closes https://github.com/elastic/integrations/issues/6896

## Screenshots
Two queries for MYSQL 
<img width="651" alt="Screenshot 2023-07-11 at 7 24 19 PM" src="https://github.com/elastic/integrations/assets/102962586/0cc2409c-2a62-40a0-ac96-4c603df092bc">

Metrics of both queries merged in single event
<img width="703" alt="Screenshot 2023-07-11 at 7 12 51 PM" src="https://github.com/elastic/integrations/assets/102962586/f914a5f0-59b1-40ea-80fe-a80a3fa38b80">

2023-07-11 18:23 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6922/detail/PR-6922/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6922/detail/PR-6922/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6922/detail/PR-6922/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6922/detail/PR-6922/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_6922.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-07-11T17:57:26.566Z&rangeTo=2023-07-11T18:17:26.566Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=ed3c5604096ab7f2f2b6fdaab64de53b&transactionId=ae75fa22c7a8789b)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-07-11T18:07:26.566+0000


* Duration: 16 min 15 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 4  |
| Skipped      | 0 |
| Total        | 4   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-07-12 05:09 UTC, shmsr requested changes

2023-07-12 05:09 UTC, shmsr commented on packages/sql_input/agent/input/input.yml.hbs
> +  dataset: {{data_stream.dataset}}
```suggestion
  dataset: {{data_stream.dataset}}
```

2023-07-12 05:09 UTC, shmsr commented on packages/sql_input/docs/README.md
> +Merge results feature will create a combined event, where `blks_hit`, `blks_read`, `checkpoints_timed` and `checkpoints_req` are part of same event.
```suggestion
Merge multiple queries into a single event.

Multiple queries will create multiple events, one for each query.  It may be preferable to create a single event by combining the metrics together in a single event.

This feature can be enabled using the `merge_results` config.

`merge_results` can merge queries having response format as "variable". 
However, for queries with a response format as "table", a merge is possible only if each table query produces a single row.

For example, if we have 2 queries as below for PostgreSQL:

sql_queries:
  - query: "SELECT blks_hit,blks_read FROM pg_stat_database limit 1;"
    response_format: table

  - query: "select checkpoints_timed,checkpoints_req from pg_stat_bgwriter;"
    response_format: table

The `merge_results` feature will create a combined event, where `blks_hit`, `blks_read`, `checkpoints_timed` and `checkpoints_req` are part of the same event.
```

2023-07-12 05:09 UTC, shmsr commented on packages/sql_input/manifest.yml
> +        title: Merge_Results
```suggestion
        title: Merge results
```

2023-07-12 05:09 UTC, shmsr commented on packages/sql_input/manifest.yml
> +        description: Merge metrics from multiple queries to a single event
```suggestion
        description: Merge results from multiple queries to a single event
```

2023-07-12 10:20 UTC, ishleenk17 commented
/test

2023-07-12 19:38 UTC, shmsr approved these changes

2023-07-13 04:52 UTC, lalit-satapathy commented on packages/sql_input/manifest.yml
> +        show_user: true
Can we move this as an advanced option?

2023-07-13 04:52 UTC, lalit-satapathy commented on packages/sql_input/manifest.yml
> +        description: Merge results from multiple queries to a single event
May be add something like: Merge results from multiple queries to a single event(**restrictions apply**)

2023-07-13 05:50 UTC, ishleenk17 commented on packages/sql_input/manifest.yml
> +        show_user: true
Yes, we can do this.

2023-07-13 06:39 UTC, muthu-mps commented on packages/sql_input/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/1234
Small change here, Update the PR link.

2023-07-13 06:39 UTC, muthu-mps commented on packages/sql_input/manifest.yml
> +        title: Merge results
nit: Can we change the title as `Merge Results` similar to what we have for the above title ?

2023-07-13 06:39 UTC, muthu-mps commented on packages/sql_input/docs/README.md
> +### Merge Results
Can we add few points around the restrictions. I assume here we cannot combine multiple table queries which provides entirely different response.

2023-07-13 07:58 UTC, ishleenk17 commented on packages/sql_input/docs/README.md
> +### Merge Results
It's already mentioned that it merges only if tables result in a single row. 
Are you mentioning something else here?

2023-07-13 13:26 UTC, muthu-mps approved these changes

2023-07-13 20:35 UTC, shmsr requested changes

2023-07-13 20:35 UTC, shmsr commented on packages/sql_input/manifest.yml
> +        description: Merge results from multiple queries to a single event(restrictions apply)
```suggestion
        description: Merge results from multiple queries to a single event (restrictions apply)
```

2023-07-13 20:40 UTC, shmsr commented on packages/sql_input/manifest.yml
>          default: "- query: SHOW GLOBAL STATUS LIKE 'Innodb_system%'\n  response_format: variables\n        \n"
I just have a question here. Why at the end we have a few whitespaces followed by `\n`:
```
        \n
```

What if I write:
```
- query: <some_query>\n  response_format: variables\n- query: <some_query>\n  response_format: table

2023-07-14 09:23 UTC, ishleenk17 commented
/test

2023-07-14 09:47 UTC, ishleenk17 commented on packages/sql_input/manifest.yml
>          default: "- query: SHOW GLOBAL STATUS LIKE 'Innodb_system%'\n  response_format: variables\n        \n"
This is a default value for yaml format. 
For that, we need these spaces. Else the default value is invalid, as you can see in the screenshot. 
<img width="407" alt="Screenshot 2023-07-14 at 3 16 04 PM" src="https://github.com/elastic/integrations/assets/102962586/eb35a7bb-bac5-4457-b976-8b6644270721">

2023-07-14 09:51 UTC, shmsr approved these changes

2023-07-14 09:52 UTC, merged

2023-07-14 12:14 UTC, elasticmachine commented
Package sql - 0.3.0 containing this change is available at https://epr.elastic.co/search?package=sql