Update docs for IBM MQ.
elastic/integrations pull request #6928
Opened 2023-07-12 06:50 UTC by philippkahr

## What does this PR do?
In the old metricbeat documentation we explicitly list that we only support containerized runtimes for the metricset collection and the reason. [Metricbeat](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-ibmmq.html#_compatibility_23)

I've updated the docs accordingly.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

2023-07-12 07:07 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6928/detail/PR-6928/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6928/detail/PR-6928/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6928/detail/PR-6928/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-6928/detail/PR-6928/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_6928.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-07-12T06:40:33.715Z&rangeTo=2023-07-12T07:00:33.715Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=b116de244ec1e544c1ac31d2f5e9fae4&transactionId=2dacc6c646706275)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-07-12T06:50:33.715+0000


* Duration: 17 min 10 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 14  |
| Skipped      | 0 |
| Total        | 14   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-07-12 07:08 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`2/2`) | :green_heart: 
Files | 100.0% (`2/2`) | :green_heart: 2.819
Classes | 100.0% (`2/2`) | :green_heart: 2.819
Methods | 100.0% (`20/20`) | :green_heart: 7.923
Lines | 98.904% (`451/456`) | :+1: 7.812
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-07-17 11:55 UTC, lalit-satapathy commented
@harnish-elastic, Please review the changes!

2023-07-17 12:09 UTC, harnish-elastic requested changes

2023-07-17 12:09 UTC, harnish-elastic commented on packages/ibmmq/_dev/build/docs/README.md
> +This integration has been tested against `IBM MQ v9.1` and `IBM MQ v9.2`. The ibmmq `qmgr` metricset is compatible with a containerized distribution of IBM MQ (since version 9.1.0).
minor nit: `metricset` -> `data stream`

2023-07-17 13:02 UTC, harnish-elastic commented on packages/ibmmq/_dev/build/docs/README.md
> +This integration has been tested against `IBM MQ v9.1` and `IBM MQ v9.2`. The ibmmq `qmgr` metricset is compatible with a containerized distribution of IBM MQ (since version 9.1.0).
@philippkahr Could you please update `packages/ibmmq/_dev/build/docs/README.md` as well and perform the `elastic-package check` command from `integrations/packages/ibmmq`

2023-07-17 13:05 UTC, harnish-elastic approved these changes
LGTM

2023-07-17 13:19 UTC, lalit-satapathy commented
@philippkahr, Please add a changelog and let's know once the CI is green. @harnish-elastic Please help as needed.

2023-07-18 05:14 UTC, harnish-elastic commented
@lalit-satapathy FYI, CI is green now.

2023-07-18 06:46 UTC, merged