[cloud_security_posture] Ensure event.kind is correctly set for pipeline errors
elastic/integrations pull request #7048
Opened 2023-07-20 16:06 UTC by MakoWish

## What does this PR do?

Modify cloud_security_posture integration to correctly set `event.kind` for pipeline errors and ensure `error.message` is an array.

## Checklist

- [X] I have reviewed tips for building integrations and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [X] I have added an entry to my package's changelog.yml file.
- [ ] I have verified that Kibana version constraints are current according to guidelines.
 
## Author's Checklist

- [ ]  

## How to test this PR locally

## Related issues

* For #6582

## Screenshots

2023-07-24 07:35 UTC, oren-zohar requested changes
Thank you :pray:

2023-07-24 07:35 UTC, oren-zohar commented on packages/cloud_security_posture/manifest.yml
> +version: "1.6.0-preview24"
if we want to include this change in 8.10
```suggestion
version: "1.5.0-preview24"
```

2023-07-24 07:35 UTC, oren-zohar commented on packages/cloud_security_posture/changelog.yml
> +- version: "1.6.0-preview24"
if we want to include this change in 8.10
```suggestion
- version: "1.5.0-preview24"
```

2023-07-24 15:51 UTC, oren-zohar approved these changes

2023-07-24 16:33 UTC, MakoWish commented
@oren-zohar, can you `/test` again? I don't have permissions to.

2023-07-30 10:53 UTC, oren-zohar commented
`/test`

2023-07-30 10:55 UTC, oren-zohar commented
/test

2023-08-10 22:44 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 
Classes | 100.0% (`0/0`) | :green_heart: 
Methods | 25.0% (`2/8`) | :grey_exclamation: 
Lines | 100.0% (`0/0`) | :green_heart: 
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-08-11 00:34 UTC, merged

2023-08-11 00:57 UTC, elasticmachine commented
Package cloud_security_posture - 1.5.0-preview31 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-08-21 10:51 UTC, elasticmachine commented
Package cloud_security_posture - 1.5.0 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture