[Kubernetes] Bump package-spec format_version to 2.9.0
elastic/integrations pull request #7144
Opened 2023-07-25 21:31 UTC by zmoog

## What does this PR do?

Upgrade the integration package-spec format_version from 1.0.0 to 2.9.0

Here're the adjustments needed due to the new validations in place:

- remove the deprecated attributes `license` and `release` from the manifest.yml
- remove duplicated `pod.ip` definitions
- update datasets in `sample_event.json` files

We need this upgrade in preparation for other changes (routing rules) that require a more recent versions of the package-spec.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

 
- Relates #7118

2023-07-25 22:03 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7144/detail/PR-7144/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7144/detail/PR-7144/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7144/detail/PR-7144/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7144/detail/PR-7144/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_7144.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-07-25T21:21:28.906Z&rangeTo=2023-07-25T21:41:28.906Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=0589815ec0ff018bef06d16b1ca0ab29&transactionId=5b779b729ef6ab65)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-07-25T21:31:28.906+0000


* Duration: 32 min 39 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 92  |
| Skipped      | 0 |
| Total        | 92   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-07-25 22:03 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 
Classes | 100.0% (`0/0`) | :green_heart: 
Methods | 96.154% (`75/78`) | :+1: 62.821
Lines | 100.0% (`0/0`) | :green_heart: 
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-07-26 07:12 UTC, ChrsMark commented on packages/kubernetes/data_stream/state_node/sample_event.json
> +        "dataset": "kubernetes.state_node",
Hmmm, I wonder how this change occured? It looks like a breaking change to me 🤔 .

2023-07-26 08:54 UTC, gsantoro commented on packages/kubernetes/data_stream/state_pod/fields/fields.yml
> -    - name: ip
what happened here? don't we have pod.ip anymore?

2023-07-26 08:54 UTC, gsantoro commented on packages/kubernetes/data_stream/pod/fields/fields.yml
> -    - name: ip
same comment as below

2023-07-26 09:13 UTC, zmoog commented on packages/kubernetes/data_stream/state_pod/fields/fields.yml
> -    - name: ip
We already have one, this one is a duplicate. 

I applied my best judgement to pick the one to remove, but maybe it is worth double-check with you. Here's the output of elastic-package when executed on today's `main` branch with the package-spec `format_version: 2.9.0`:

```shell
# elastic-package check -v
....
Error: checking package failed: linting package failed: found 4 validation errors:
   1. file "/Users/zmoog/code/projects/zmoog/integrations/packages/kubernetes/manifest.yml" is invalid: field (root): Additional property release is not allowed
   2. file "/Users/zmoog/code/projects/zmoog/integrations/packages/kubernetes/manifest.yml" is invalid: field (root): Additional property license is not allowed
   3. field "kubernetes.pod.ip" is defined multiple times for data stream "pod", found in: /Users/zmoog/code/projects/zmoog/integrations/packages/kubernetes/data_stream/pod/fields/base-fields.yml, /Users/zmoog/code/projects/zmoog/integrations/packages/kubernetes/data_stream/pod/fields/fields.yml
   4. field "kubernetes.pod.ip" is defined multiple times for data stream "state_pod", found in: /Users/zmoog/code/projects/zmoog/integrations/packages/kubernetes/data_stream/state_pod/fields/base-fields.yml, /Users/zmoog/code/projects/zmoog/integrations/packages/kubernetes/data_stream/state_pod/fields/fields.yml
```

Here's the relevant last two errors, unpacked:

```text
field "kubernetes.pod.ip" is defined multiple times for data stream "pod", found in: 
  .../packages/kubernetes/data_stream/pod/fields/base-fields.yml, 
  .../packages/kubernetes/data_stream/pod/fields/fields.yml

field "kubernetes.pod.ip" is defined multiple times for data stream "state_pod", found in: 
  .../packages/kubernetes/data_stream/state_pod/fields/base-fields.yml, 
  .../packages/kubernetes/data_stream/state_pod/fields/fields.yml
```

@gsantoro do you think updating `fields.yml` is the right choice, or should we update `base-fields.yml`?

2023-07-26 09:46 UTC, zmoog commented on packages/kubernetes/data_stream/state_node/sample_event.json
> +        "dataset": "kubernetes.state_node",
I checked the Metricbeat module, and it seems this metricset is using the `kubernetes.state_node` dataset since the [early days](https://github.com/elastic/beats/blame/16e2989a001afcd5b094e9b5ff0b7540da618eb5/metricbeat/module/kubernetes/state_node/state_node.go#L72). 

Is it possible that we manually edited the `sample_event.json` file, and we never noticed this error until the `elastic-package` validation caught it?

2023-07-26 11:06 UTC, gsantoro commented on packages/kubernetes/data_stream/state_pod/fields/fields.yml
> -    - name: ip
Thanks for the details. I didn't fully understand it until now.

So both pod and state_pod define kubernetes.pod.ip twice each in fields.yml and base-fields.yml. 

That's clearly a mistake. It's crazy that was only caught now. 

I'm not sure which is the preferred file for that property fields or base-fields.yml. I don't think it matters much but maybe @ChrsMark knows better

2023-07-26 11:06 UTC, gsantoro approved these changes

2023-07-26 12:42 UTC, zmoog commented on packages/kubernetes/data_stream/state_node/sample_event.json
> +        "dataset": "kubernetes.state_node",
Adding a reference to the [relevant section](https://github.com/elastic/elastic-package/blob/d334792002bd80a03eee07f615d822e7522e8368/docs/howto/update_major_package_spec.md?plain=1#L76-L103) in the [Troubleshooting upgrades from Package Spec v1 to v2](https://github.com/elastic/elastic-package/blob/d334792002bd80a03eee07f615d822e7522e8368/docs/howto/update_major_package_spec.md?plain=1#L10C4-L10C55) guide.

2023-07-26 12:42 UTC, ChrsMark commented on packages/kubernetes/data_stream/state_node/sample_event.json
> +        "dataset": "kubernetes.state_node",
According to https://github.com/elastic/beats/commit/b3f6632873336dba9c2d3460a0bae3a83bb2cee0#diff-a60c719544b7cf37e25376068d5f8f95c520a6d0d181a1c7a8d7b0d96abdca2eR112 the `state_` prefix should not be there. 
I suggest to wait a bot for @constanca-m and @gizas to double check this.

Not sure what we miss here and when but looks important to me.

2023-07-26 12:44 UTC, ChrsMark requested changes
I think we need to clarify https://github.com/elastic/integrations/pull/7144#discussion_r1274900673 before moving forward (even if not directly related to this patch). 
@gizas @constanca-m could you have a look?

2023-07-26 12:47 UTC, zmoog commented on packages/kubernetes/data_stream/state_node/sample_event.json
> +        "dataset": "kubernetes.state_node",
What  values are we getting for `event.dataset` by running the latest released integration version?

2023-07-26 13:45 UTC, zmoog commented on packages/kubernetes/data_stream/state_node/sample_event.json
> +        "dataset": "kubernetes.state_node",
Quick test running the Kubernetes integration version 1.43.1 on a stack version 8.8.0:

<img width="1814" alt="CleanShot 2023-07-26 at 15 42 52@2x" src="https://github.com/elastic/integrations/assets/25941/d640e7ad-3ba1-4424-baac-aabb594ebaa8">

2023-07-26 13:49 UTC, zmoog commented on packages/kubernetes/data_stream/state_node/sample_event.json
> +        "dataset": "kubernetes.state_node",
And, for the records, here's the error that the elastic-package returns during execution:

```shell
task: [integration:test-static] elastic-package test static -v
2023/07/26 14:36:37 DEBUG Enable verbose logging
Run static tests for the package
--- Test results for package: kubernetes - START ---
FAILURE DETAILS:
kubernetes/state_node Verify sample_event.json:
[0] field "event.dataset" should have value "kubernetes.state_node", it has "kubernetes.node"
kubernetes/state_persistentvolume Verify sample_event.json:
[0] field "event.dataset" should have value "kubernetes.state_persistentvolume", it has "kubernetes.persistentvolume"
kubernetes/state_resourcequota Verify sample_event.json:
[0] field "event.dataset" should have value "kubernetes.state_resourcequota", it has "kubernetes.resourcequota"
kubernetes/state_storageclass Verify sample_event.json:
[0] field "event.dataset" should have value "kubernetes.state_storageclass", it has "kubernetes.storageclass"
```

2023-07-26 13:56 UTC, zmoog commented
> I think we need to clarify [#7144 (comment)](https://github.com/elastic/integrations/pull/7144#discussion_r1274900673) before moving forward (even if not directly related to this patch). @gizas @constanca-m could you have a look?

Yep, it makes sense. I cherry-picked this change from the other PR to discuss it earlier with you. Thanks for checking.

2023-08-02 15:40 UTC, zmoog commented
> I think we need to clarify https://github.com/elastic/integrations/pull/7144#discussion_r1274900673 before moving forward (even if not directly related to this patch). @gizas @constanca-m could you have a look?

 @gizas @constanca-m, let me know what you think when you have time.

2023-08-03 09:13 UTC, gizas commented
Quick tests on myside also prove what you said, it is state_node (8.9.0 and k8s integration version: 1.43.1)

![Uploading Screenshot 2023-08-03 at 12.02.04 PM.png…]()

What still confuses me is that in beats still the dataset is kubernetes.node (see https://github.com/elastic/beats/blob/main/metricbeat/module/kubernetes/state_node/_meta/testdata/ksm.v2.4.2.plain-expected.json#L4). Probably then is a test error?

Another question is regarding this comment: https://github.com/elastic/integrations/pull/7144#discussion_r1274797692

Can we have two datastreams write to same field? What if user decides to enable only one of the two datastreams then we will miss the value is not it?

2023-08-03 10:06 UTC, gizas commented
I think found the reason here: https://github.com/elastic/beats/blob/main/metricbeat/helper/kubernetes/state_metricset.go#L47 

The init function will initialise the metricset as `name = prefix + name` (with prefix="state_")

So that is why all tests have kubernetes.node inside the state_* subfloders as the replacement takes place later.

2023-08-03 10:12 UTC, ChrsMark commented
> I think found the reason here: https://github.com/elastic/beats/blob/main/metricbeat/helper/kubernetes/state_metricset.go#L47
> 
> The init function will initialise the metricset as `name = prefix + name` (with prefix="state_")
> 
> So that is why all tests have kubernetes.node inside the state_* subfloders as the replacement takes place later.

Did you test it? If so what versions does this affect? Which PR introduced this?

Since I believe that is intentional we have a regression and we need to spot where this change was introduced and fix+backport accordingly.

2023-08-03 10:47 UTC, gizas commented
I can see this here: https://github.com/elastic/beats/commit/b3f6632873336dba9c2d3460a0bae3a83bb2cee0#diff-e68559ac427c7449ad78073317eb417a1163be73f47fb249282343130ab43941L86

So before we were passing state_* .

So @constanca-m as your [PR introduced](https://github.com/elastic/beats/pull/34432) this change , could you please open a new issue to track any work that needs fixing this regression?

2023-08-03 11:12 UTC, constanca-m commented
Sorry for being late to the party, but I am confused about what the problem is. @gizas @ChrsMark 

I checked the history of the `data.json` file inside `state_node` metricbeat and there were only two versions. One before and one after this [PR commit](https://github.com/elastic/beats/pull/34432). For both, the `event.dataset` for `kubernetes.state_node` was `kubernetes.node`. Is this not the expected result? Should it be `kubernetes.state_node`? The `state_*` is never added to any `state_*` datasets for `event.dataset`.

2023-08-03 11:26 UTC, ChrsMark commented
Hey @constanca-m ! You are right `event.dataset` should always be `node`, `pod`, `container` etc, not `state_node`, `state_pod`, `state_container` etc.

I'm not sure either how this occured.
See https://github.com/elastic/integrations/pull/7144#discussion_r1274472630 for why we are looking into this. Could you verify that the https://github.com/elastic/beats/pull/34432 did not introduce any change regarding this? 
We need to figure out why we see https://github.com/elastic/integrations/pull/7144/files#diff-84695c89e2b99f9fa927b432447c7635b7abe0d393561472e7e93822d34b3401R84 in this PR.

2023-08-03 11:43 UTC, ChrsMark commented
So I did a quick test with `docker.elastic.co/beats/metricbeat:8.9.0` and I see that the `dataset` field is populated properly:

```console
k -n kube-system logs -f metricbeat-f8gmd | grep dataset
...
   "dataset": "kubernetes.pod"
    "dataset": "kubernetes.pod",
    "dataset": "kubernetes.container"
    "dataset": "kubernetes.pod",
    "dataset": "kubernetes.container",
    "dataset": "kubernetes.pod",
    "dataset": "kubernetes.container",
    "dataset": "kubernetes.container"
    "dataset": "kubernetes.pod",
    "dataset": "kubernetes.pod",
    "dataset": "kubernetes.pod",
    "dataset": "kubernetes.container",
    "dataset": "kubernetes.pod",
    "dataset": "kubernetes.container",
    "dataset": "kubernetes.container",
...
```
So maybe sth has changed on Agent side that overrides that field?

2023-08-03 11:50 UTC, constanca-m commented
I tested directly on metricbeat. This [PR](https://github.com/elastic/beats/pull/34432) was backported in 8.6.0, so I checked 8.5.0. I found this:

![image](https://github.com/elastic/integrations/assets/113898685/726cce6c-fe6b-4585-a41e-632d92d8fd79)

So we already had some `kubernetes.state_node` for the `state_node` metricset before the PR.

2023-08-03 11:57 UTC, constanca-m commented
I checked what was the difference in the documents between `kubernetes.state_node` and `kubernetes.node` event datasets, and the only difference was that `kubernetes.state_node` had the documents with error messages:

![image](https://github.com/elastic/integrations/assets/113898685/4b8ec2a9-83e9-4b59-a375-117143761385)

And `kubernetes.node` has the correct ones. I will check if this happened in 8.6.0 as well, but I find it likely it did. This [PR](https://github.com/elastic/beats/pull/34432) only moved the common code to one single file, it doesn't change what it is doing.

2023-08-03 11:58 UTC, ChrsMark commented
@constanca-m that's weird that you see both 🤔 Is your ES empty? With 8.9 I don't see any `state_*` values.

2023-08-03 11:58 UTC, constanca-m commented
Yes @ChrsMark , I created a new instance just to check Kubernetes module.

2023-08-03 11:59 UTC, constanca-m commented
> @constanca-m that's weird that you see both thinking Is your ES empty? With 8.9 I don't see any state_* values.

What if you delete all KSM deployments to generate documents with error messages? @ChrsMark

2023-08-03 12:11 UTC, constanca-m commented
I tested again with a new instance, this time for 8.6.0. I started metricbeat without KSM and then applied KSM. I saw the same behavior again:
![image](https://github.com/elastic/integrations/assets/113898685/1f47cb30-f09b-44e1-9fe6-d204a8a0fe1e)

If I filter the document with `kubernetes.state_node` event, then all the documents have an `error.message`:
![image](https://github.com/elastic/integrations/assets/113898685/d980413e-5550-4e2e-b4c6-b046bfd3bcb1)

If I filter documents with `kubernetes.node` with an `error.message`, I get 0:
![image](https://github.com/elastic/integrations/assets/113898685/ec94a068-9820-4e0d-b86a-fe8f992a090d)

So the conclusion: when KSM is not deployed, then we receive documents that use `kubernetes.state_node` event. Otherwise, the documents are received as expected.

2023-08-03 12:21 UTC, ChrsMark commented
@constanca-m I can confirm that switching on/off the KSM deployment seems to be the reason. Thanks for spotting this :)!

@zmoog could you verify if the update happens with a running KSM instance or not? In any case it seems that under normal circumstances the dataset values should not be as `state_*` and hence the sample docs should follow accordingly.

2023-08-03 14:51 UTC, zmoog commented
> @zmoog could you verify if the update happens with a running KSM instance or not? In any case it seems that under normal circumstances the dataset values should not be as state_* and hence the sample docs should follow accordingly.

Testing with:

- Stack: 8.9.0
- Kubernetes integration: v1.43.1

I started collecting data with KSM available and received documents with `event.dataset: kubernetes.state_node` only with no `error.message` fields.

After a few minutes, I deleted the KSM replicaset. Without KSM, all documents had an `error.message` field. However, the `event.dataset` field only has `kubernetes.state_node` values.

![CleanShot 2023-08-03 at 16 40 28@2x](https://github.com/elastic/integrations/assets/25941/ebabaac0-3ac1-4658-a489-b7f52fdb1a56)

2023-08-04 12:20 UTC, ChrsMark commented
So we have verified that for Beats the value of `event.dataset` is set to `node` (not `state_node`) when the events are collected properly (== KSM is reachable).
The issue is that in anycase Agent seems to be replacing `node` with `state_node`. @joshdover do you know if this is expected? Also I wonder why we only hit this now and not earlier 🤔 .


I any case @zmoog if you can rollback the changes in the [sample_event.json](https://github.com/elastic/integrations/pull/7144/files/803c9f26ca577b46c13ff7fccbd776444f0df8f0#diff-84695c89e2b99f9fa927b432447c7635b7abe0d393561472e7e93822d34b3401) files I suggest we can unblock this PR and continue the investigation at https://github.com/elastic/beats/issues/36227.

2023-08-04 12:25 UTC, ChrsMark reviewed
Apart from https://github.com/elastic/beats/issues/36227, it looks good to me. if we can roll back those specific changes it's good to go :).

2023-08-04 12:25 UTC, ChrsMark commented on packages/kubernetes/data_stream/state_persistentvolume/sample_event.json
> +        "dataset": "kubernetes.state_persistentvolume"
Can we rollback those changes until we figure out why it's happening?

2023-08-04 12:34 UTC, joshdover commented
> The issue is that in anycase Agent seems to be replacing `node` with `state_node`. @joshdover do you know if this is expected? Also I wonder why we only hit this now and not earlier 🤔 .

I don't have any immediate idea. I'd first suggest looking at an agent diagnostic to figure out exactly what configuration is being passed to metricbeat in this scenario in the `components-actual.yaml` or `computed-config.yaml` files

2023-08-04 12:34 UTC, zmoog commented
> I any case @zmoog if you can rollback the changes in the [sample_event.json](https://github.com/elastic/integrations/pull/7144/files/803c9f26ca577b46c13ff7fccbd776444f0df8f0#diff-84695c89e2b99f9fa927b432447c7635b7abe0d393561472e7e93822d34b3401) files I suggest we can unblock this PR and continue the investigation at [elastic/beats#36227](https://github.com/elastic/beats/issues/36227).

I am not sure I can easily rollback this change, IIRC it comes from a validation error reported by elastic-package after upgrading package-spec from 1.0.0 to 2.9.0.

I’ll check it again to get the exact error message.

2023-08-04 14:20 UTC, zmoog commented
> > I any case @zmoog if you can rollback the changes in the [sample_event.json](https://github.com/elastic/integrations/pull/7144/files/803c9f26ca577b46c13ff7fccbd776444f0df8f0#diff-84695c89e2b99f9fa927b432447c7635b7abe0d393561472e7e93822d34b3401) files I suggest we can unblock this PR and continue the investigation at [elastic/beats#36227](https://github.com/elastic/beats/issues/36227).
> 
> I am not sure I can easily rollback this change, IIRC it comes from a validation error reported by elastic-package after upgrading package-spec from 1.0.0 to 2.9.0.
> 
> I’ll check it again to get the exact error message.

I updated the PR description, adding the failed validations from `elastic-package`. Each change in this PR is only here to address those errors.

2023-08-10 10:26 UTC, merged