[AWS] [API Gateway] Add custom access logging fields
elastic/integrations pull request #7151
Opened 2023-07-26 12:36 UTC by lucian-ioan

## What does this PR do?

Adds `apiId`, `domainName` and `stage` fields which are custom access fields that need manual configuration by the user to be fetched.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] Enhance documentation to reflect added fields and guide users to use the log format we support.

## How to test this PR locally

## Related issues

- Closes #7150

## Screenshots

2023-07-26 12:47 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7151/detail/PR-7151/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7151/detail/PR-7151/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7151/detail/PR-7151/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7151/detail/PR-7151/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_7151.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-07-26T12:26:15.518Z&rangeTo=2023-07-26T12:46:15.518Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=e9e6de2785674c1c9470df3693764d6b&transactionId=88ae2e5ee9d2c2e6)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-07-26T12:36:15.518+0000


* Duration: 11 min 46 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![4](https://img.shields.io/badge/4%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7151/detail/PR-7151/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Check integration: aws`
<ul>
<li>Took 0 min 5 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-7151/runs/1/steps/1142/log/?start=0">here</a></li>
<li>Description: <code>../../build/elastic-package check -v</code></l1>
</ul>
  
  
  
  
##### `Take down the Elastic stack`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-7151/runs/1/steps/1161/log/?start=0">here</a></li>
<li>Description: <code>build/elastic-package stack down -v</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-7151/runs/1/steps/1181/log/?start=0">here</a></li>

</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-7151/runs/1/steps/1194/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-07-26 15:23 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`17/17`) | :green_heart: 
Files | 94.444% (`17/18`) | :-1: -0.556
Classes | 94.444% (`17/18`) | :-1: -0.556
Methods | 85.953% (`257/299`) | :-1: -1.163
Lines | 86.024% (`7509/8729`) | :+1: 0.185
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-07-31 23:23 UTC, zmoog commented on packages/aws/_dev/build/docs/apigateway.md
> +```{"apiId": "$context.apiId", "domainName": "$context.domainName", "stage": "$context.stage"}```
What about adding a JSON with ALL the fields supported by this integration, ready to be copied and pasted?

IIRC, it is essential to have a "core" set of fields that users can extend with additional ones, but users must always include the core fields, right? It can be helpful for the actual testing and as documentation of what's possible.

Can we include some sample documents with apiId and the other additional fields in the tests?

2023-07-31 23:27 UTC, zmoog commented on packages/aws/_dev/build/docs/apigateway.md
> +creating custom pipelines is required.
We should expand this section.

Here's the information we should convey to the users:

- the API Gateway offers a wide array of additional fields you can pick from
- you can leverage the custom pipeline to process the field names or values
- you can leverage the custom mapping to store data efficiently

2023-07-31 23:28 UTC, zmoog requested changes
This PR is looking good; I have a few minor suggested changes.

2023-08-01 13:28 UTC, lucian-ioan commented on packages/aws/_dev/build/docs/apigateway.md
> +```{"apiId": "$context.apiId", "domainName": "$context.domainName", "stage": "$context.stage"}```
1. By enabling Custom Access Logging, users can select only the fields necessary, so it's not required to always have the core fields.

2. By not enabling Custom Access Logging users will fetch the default log format which is as follows per API type:
HTTP:

>   "requestId": "$context.requestId",
>   "ip": "$context.identity.sourceIp",
>   "requestTime": "$context.requestTime",
>   "httpMethod": "$context.httpMethod",
>   "routeKey": "$context.routeKey",
>   "status": "$context.status",
>   "protocol": "$context.protocol",
>   "responseLength": "$context.responseLength"

REST:

>   "requestId": "$context.requestId",
>   "ip": "$context.identity.sourceIp",
>   "caller": "$context.identity.caller",
>   "user": "$context.identity.user",
>   "requestTime": "$context.requestTime",
>   "httpMethod": "$context.httpMethod",
>   "resourcePath": "$context.resourcePath",
>   "status": "$context.status",
>   "protocol": "$context.protocol",
>   "responseLength": "$context.responseLength"

WebSocket:

>   "requestId": "$context.requestId",
>   "ip": "$context.identity.sourceIp",
>   "caller": "$context.identity.caller",
>   "user": "$context.identity.user",
>   "requestTime": "$context.requestTime",
>   "eventType": "$context.eventType",
>   "routeKey": "$context.routeKey",
>   "status": "$context.status",
>   "connectionId": "$context.connectionId"


Since some of the fields are only supported by specific API types, I could include the default log format for each in the documentation so there's no confusion. WDYT @zmoog?

Users are presented with the default log format by default when enabling Custom Access Logging and they can also reset back to it by pressing Insert Example, ex for REST:

<img width="464" alt="REST" src="https://github.com/elastic/integrations/assets/59661554/04dee67a-bf89-4d3d-99c7-6765cbb2bd9d">

<br></br>
> Can we include some sample documents with apiId and the other additional fields in the tests?

They are at the bottom of the logs since I also also kept the original tests 😄

2023-08-02 08:41 UTC, zmoog commented on packages/aws/_dev/build/docs/apigateway.md
> +```{"apiId": "$context.apiId", "domainName": "$context.domainName", "stage": "$context.stage"}```
Let's test my understanding.

When I visit: **REST API > Stages > {stage} > Logs/Tracing**, I can enable the access logs by selecting "Enable Access Logging". Other API types have a similar option.

By default, the "Log Format" is empty; the AWS web console can drop a JSON sample log format by clicking the "JSON" button.

As an alternative, we can provide a similar sample log format with all the fields for each type we currently support in our integration.

> Since some of the fields are only supported by specific API types, I could include the default log format for each in the documentation so there's no confusion.

Since different API types have various fields, having a recommended JSON log format for each API type would be great.

2023-08-02 14:03 UTC, zmoog commented on packages/aws/_dev/build/docs/apigateway.md
> +```{"apiId": "$context.apiId", "domainName": "$context.domainName", "stage": "$context.stage"}```
Got it. Thanks for clarifying!

2023-08-02 15:24 UTC, lucian-ioan commented
/test

2023-08-02 15:29 UTC, lucian-ioan commented
/retest

2023-08-02 15:47 UTC, lucian-ioan commented
It seems changing my github username finally caught up to me (shouldn't have deleted the bot comments, resigned the CLA).

What's your opinion on the new docs @zmoog ?

2023-08-03 08:50 UTC, zmoog commented
@lucian-ioan, do you still have problems with CLA?

2023-08-03 08:55 UTC, zmoog commented on packages/aws/_dev/build/docs/apigateway.md
> +
What about providing an "Elastic Log Format" instead of the default one, based on the default one + the extra variables (`appId`, `domainName`, and `stage`) for each API type to copy and paste?

2023-08-03 08:57 UTC, zmoog commented
> Can the PR not be merged without the CLA passing?

No. 

We need to sort this out.

2023-08-09 16:03 UTC, annamikhailovskaia commented
cla/check

2023-08-10 12:32 UTC, umatiw commented
cla/check

2023-08-10 13:38 UTC, umatiw commented
cla/check

2023-08-11 10:13 UTC, zmoog requested changes

2023-08-11 11:16 UTC, lucian-ioan commented on packages/aws/_dev/build/docs/apigateway.md
> +To leverage the extensive range of additional fields offered by enabling Custom Access Logging, create custom pipelines for processing field names or values, alongside custom mapping to store data ef
good point. how about now @zmoog?

2023-08-11 11:24 UTC, zmoog approved these changes
nit: tiny suggestion on the wording.

2023-08-11 11:24 UTC, zmoog commented on packages/aws/_dev/build/docs/apigateway.md
> +To utilize these fields in the integration, create custom pipelines. These pipelines will process field names or values. You'll also need to create custom mapping to store your data efficiently. For
```suggestion
Beyond the standard Log Formats we provide, you can use a wide range of fields for each API type when enabling Custom Access Logging.

To utilize these fields in the integration, create custom pipelines. These pipelines will process field names or values. You'll also need to create a custom mapping to store your data efficiently. For more information on how to do this, check out our [official documentation](https://www.elastic.co/guide/en/fleet/current/data-streams-pipeline-tutorial.html).
```

2023-08-11 12:03 UTC, bhapas commented on packages/aws/changelog.yml
> +- version: "1.52.2"
May be a minor version bump here as we are adding the fields and it is an `enhancement`

2023-08-11 12:21 UTC, gpop63 approved these changes

2023-08-11 13:08 UTC, merged

2023-08-11 13:31 UTC, elasticmachine commented
Package aws - 1.53.0 containing this change is available at https://epr.elastic.co/search?package=aws