[Azure][Storage_account] Add dimension to the storage account datastream
elastic/integrations pull request #7356
Opened 2023-08-11 05:29 UTC by ritalwar

- Enhancement

## What does this PR do?

This PR add dimension for azure storage_account datastream.
Specified dimension fields are as follows:
                - agent.id
                - azure.dimensions.api_name
                - azure.dimensions.response_type
                - azure.namespace
                - azure.resource.id
                - azure.timegrain
                - cloud.region

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally

## Related issues

- Relates #7215 

## Screenshots

2023-08-11 07:46 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7356/detail/PR-7356/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7356/detail/PR-7356/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7356/detail/PR-7356/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7356/detail/PR-7356/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_7356.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-08-11T07:21:23.444Z&rangeTo=2023-08-11T07:41:23.444Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=20779917be9feb075d8f972b405c02ba&transactionId=b2117557ccba5ed3)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-08-11T07:31:23.444+0000


* Duration: 15 min 21 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 134  |
| Skipped      | 0 |
| Total        | 134   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-08-11 07:47 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`3/3`) | :green_heart: 
Files | 100.0% (`3/3`) | :green_heart: 
Classes | 100.0% (`3/3`) | :green_heart: 
Methods | 73.333% (`22/30`) | :-1: -23.725
Lines | 100.0% (`21/21`) | :green_heart: 4.77
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-08-11 08:14 UTC, ritalwar commented
Azure has additional dimensions for storage accounts, such as GeoType, Authentication, FileShare, BlobType, and tier. However, these dimensions are not currently included in this PR. As in the current Beats implementation, only two dimensions, namely ResponseType and ApiName, are allowed. I've used these two dimensions for enabling TSDB for now.

Although the current set of dimensions doesn't discard any documents, I'm in the process of using Azure Rest APIs to explore the values for the other dimensions defined by Azure.

2023-08-24 07:00 UTC, zmoog commented
> However, these dimensions are not currently included in this PR. As in the current Beats implementation, only two dimensions, namely ResponseType and ApiName, are [allowed](https://github.com/elastic/beats/blob/4506e55d50f9ab72164ff55eae7ec0c19a1fd5d5/x-pack/metricbeat/module/azure/storage/storage.go#L18).

Oh, I see the dimensions list is pretty limited here. 

Expanding the list is not in the scope of this PR, so we should not block this PR. We should open an issue to plan this activity. 

We should also drop the `storage` metricset and switch the agent to use the generic `monitor` metricset. WDYT @kaiyan-sheng ?

2023-08-24 07:01 UTC, zmoog approved these changes

2023-08-24 07:36 UTC, ritalwar commented
> Expanding the list is not in the scope of this PR, so we should not block this PR. We should open an issue to plan this activity.

I merged this pull request [PR](https://github.com/elastic/beats/pull/36331) with the remaining dimensions included. However, I've come to realize that the TransactionType dimension is still pending and may require a separate PR to incorporate it.

> We should also drop the storage metricset and switch the agent to use the generic monitor metricset. 
@zmoog However, if this is under consideration, should we wait before migrating this datastream to the TSDB? 
Alternatively, can I proceed with creating another PR in beats to include the TransactionType dimension? 
We intend to merge this PR after the beats changes are available for use in the integration.

2023-08-25 15:16 UTC, kaiyan-sheng commented on packages/azure_metrics/changelog.yml
> +- version: "1.0.24"
I think we can bump this one to 1.1.0 since this is an enhancement not a bug fix.

2023-08-25 15:22 UTC, kaiyan-sheng commented
I agree with @zmoog, we are not in a hurry to change storage to use the generic `monitor`. I was looking at the code in Beats and we are also not using the generic `monitor` there: https://github.com/elastic/beats/tree/main/x-pack/metricbeat/module/azure/storage

Let's make sure we are not collecting extra data in `storage` that can't be done by `monitor` first 🙂

2023-09-26 17:59 UTC, zmoog commented
@ritalwar I was checking the pending issues/PRs, and I want to recap this one to double-check I'm not overlooking something:

- We were waiting for the https://github.com/elastic/beats/pull/36331 to be available in a Beats release.
- Do we need to bump the required Kibana version to 8.10?
- Any other dependency?

2023-09-27 07:48 UTC, ritalwar commented
> * We were waiting for [Add more dimensions to allowedDimensions for azure storage account to… beats#36331](https://github.com/elastic/beats/pull/36331) to be available in a Beats release.

Yes, now that this is available in release, I've been testing it and now waiting for the TSDB team to provide their feedback.

> * Do we need to bump the required Kibana version to 8.10?

I've observed that for all other similar changes, such as those related to dimensions and metric_type PRs, the version update was done at the patch level rather than the minor version. Should I follow the same approach and update the patch version for consistency?

> * Any other dependency?

I checked if this datastream is affected by the grouping issue seen in other Azure and GCP datastreams. However, it seems unaffected because the implementation for this datastream is separate in the Beats module, and it already groups data based on allowed dimensions. If you think there's anything I missed, please let me know, and I'll test further.

2023-09-27 07:56 UTC, tetianakravchenko requested changes

2023-09-27 07:56 UTC, tetianakravchenko commented on packages/azure_metrics/data_stream/storage_account/fields/agent.yml
> +- name: agent
i think it is better to define this field like:
```
- name: agent.id
  external: ecs
  dimension: true
```
in ecs file, instead of duplicating it here

2023-09-27 07:56 UTC, tetianakravchenko commented on packages/azure_metrics/data_stream/storage_account/elasticsearch/ingest_pipeline/default.yml
> +      fields: ["azure.dimensions"]
correctly I understand that the list of dimensions is actually predefined, if so - why fingerprint is used?

2023-09-27 08:15 UTC, ritalwar commented on packages/azure_metrics/data_stream/storage_account/elasticsearch/ingest_pipeline/default.yml
> +      fields: ["azure.dimensions"]
We're designating each Azure storage account's specified default dimension as a TSDB dimension. Instead of expanding and labelling each individually defined Azure dimension, I opted for a fingerprint processor, similar to how it's done for Prometheus labels.

2023-09-27 08:18 UTC, ritalwar commented on packages/azure_metrics/data_stream/storage_account/fields/agent.yml
> +- name: agent
Updated.

2023-09-27 08:23 UTC, tetianakravchenko commented on packages/azure_metrics/data_stream/storage_account/elasticsearch/ingest_pipeline/default.yml
> +      fields: ["azure.dimensions"]
it is not really similar to the prometheus labels - for prometheus it is not possible to predict the list of labels, as it depends on the endpoint that is scraped. In case of storage account as I see - https://learn.microsoft.com/en-us/azure/azure-monitor/reference/supported-metrics/microsoft-classicstorage-storageaccounts-metrics the list of dimensions is [predefined](https://github.com/ritalwar/beats/blob/main/x-pack/metricbeat/module/azure/storage/storage.go#L18) and limited to 7 fields. Instead of introducing additional processor I think it is better to extend 7 fields

2023-09-27 09:17 UTC, tetianakravchenko commented on packages/azure_metrics/data_stream/storage_account/elasticsearch/ingest_pipeline/default.yml
> +      fields: ["azure.dimensions"]
I think your comment is valid, but for cases when new dimensions are handled by the beat seamlessly. But now new dimension(s) will not be in the document if not explicitly mentioned in the azure api call. 
since adding a new dimension anyway requires extra actions - like adding it in the beats, I think one extra pr to sync list of fields shouldn't be a problem.

I have more concerns about introduction a fingerprint processor for cases where it is not a necessity

2023-09-27 09:35 UTC, ritalwar commented on packages/azure_metrics/data_stream/storage_account/elasticsearch/ingest_pipeline/default.yml
> +      fields: ["azure.dimensions"]
okay, I'll extend the list.

2023-09-27 10:19 UTC, ritalwar commented on packages/azure_metrics/data_stream/storage_account/elasticsearch/ingest_pipeline/default.yml
> +      fields: ["azure.dimensions"]
addressed in [a225cd2](https://github.com/elastic/integrations/pull/7356/commits/a225cd202e284f5e6dfc8f609ed6556bdbf4af42)

2023-09-27 10:43 UTC, tetianakravchenko reviewed
kibana version should be changed to 8.10 I think, since this change is relying on the 8.10 beats release
```
kibana.version: "^8.9.0"
```
I also agree that the package version should be changed to `1.1.0` when the new kibana version restriction will be added.

2023-09-27 11:56 UTC, ritalwar commented
> kibana version should be changed to 8.10 I think, since this change is relying on the 8.10 beats release
> 
> ```
> kibana.version: "^8.9.0"
> ```
> 

Should we consider updating the Kibana version in the TSDB enablement PR, as we've done for some other packages?

> I also agree that the package version should be changed to `1.1.0` when the new kibana version restriction will be added.

I'll follow this in the PR where I update the Kibana version, and we can decide whether it's in this one or the enablement PR.

2023-09-27 12:06 UTC, tetianakravchenko commented
> Should we consider updating the Kibana version in the TSDB enablement PR, as we've done for some other packages?

adding additional fields is not related to the tsdb enablement. Here I've seen similar discussion regarding the handling of kibana constrains - https://github.com/elastic/integrations/pull/6821#discussion_r1254177489 (this is a conclusion, but see the whole discussion) for adding new fields, based on that my understanding was that it is a proper way of handling it.

> Do we need to bump the required Kibana version to 8.10?

@zmoog I've seen your comment regarding the kibana version https://github.com/elastic/integrations/pull/7356#issuecomment-1736023745. Is your understanding the same as in discussion linked above?

2023-09-27 12:25 UTC, tetianakravchenko commented
>  Should we consider updating the Kibana version in the TSDB enablement PR, as we've done for some other packages?

for other packages usually we were introducing the Kibana version constrain together with tsdb enablement, because tsdb is supported starting from ^8.8.0

in this case if TSDB enablement PR would include kibana constrain ^8.10.0, it will not be correct since TSDB enablement itself does not require bumping kibana version to 8.10

2023-09-27 13:56 UTC, ritalwar commented
> in this case if TSDB enablement PR would include kibana constrain ^8.10.0, it will not be correct since TSDB enablement itself does not require bumping kibana version to 8.10

That makes sense. I've made the update and updated both Kibana and package version.

2023-10-03 05:10 UTC, merged

2023-10-03 05:36 UTC, elasticmachine commented
Package azure_metrics - 1.1.0 containing this change is available at https://epr.elastic.co/search?package=azure_metrics