Migration of Azure AD Identity Protection dashboard to Lens
elastic/integrations pull request #7376
Opened 2023-08-14 06:38 UTC by rajvi-elastic

## What does this PR do?

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2023-08-14 06:53 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7376/detail/PR-7376/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7376/detail/PR-7376/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7376/detail/PR-7376/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7376/detail/PR-7376/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_7376.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-08-14T06:28:35.642Z&rangeTo=2023-08-14T06:48:35.642Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=df983698d37f17c17fa58398ef1bedd2&transactionId=608c9a61d5ea65d4)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-08-14T06:38:35.642+0000


* Duration: 15 min 51 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 83  |
| Skipped      | 0 |
| Total        | 83   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-08-14 06:53 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`10/10`) | :green_heart: 
Files | 86.364% (`19/22`) | :-1: -10.214
Classes | 86.364% (`19/22`) | :-1: -10.214
Methods | 83.333% (`155/186`) | :-1: -8.454
Lines | 85.003% (`2817/3314`) | :-1: -3.253
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-08-22 05:17 UTC, kush-elastic approved these changes
LGTM!

2023-08-24 06:30 UTC, zmoog commented
Hey @rajvi-elastic, I know setting up a real Identity Protection is not straightforward and involves enabling an Active Directory Premium P2 license.

However, for the purpose of this PR, we don't have to set up the whole thing; we can send sample event logs to an event hub using a CLI tool:

```text
┌─────────────┐         ┌───────────┐        ┌───────────────┐
│  event hub  │────────▶│   agent   │───────▶│  data stream  │
└─────────────┘         └───────────┘        └───────────────┘
       ▲                                                      
                                                              
       │                                                      
     send                                                     
    sample                                                    
    events                                                    
       │                                                      
┌─────────────┐                                               
│  cli tool   │                                               
└─────────────┘                                               
```

2023-08-24 06:36 UTC, zmoog commented
We have a few [sample events](https://github.com/elastic/integrations/tree/main/packages/azure/data_stream/identity_protection/_dev/test/pipeline) in the repo, and I probably have more on my laptop; we can use these as a template. 

To send data, we'll soon have support for the event hub in https://github.com/elastic/stream, but in the meantime, you can use https://github.com/zmoog/eventhubs to read sample event logs and publish them in the event hub.

Let me know if you need more information. I can put together a short guide if you need it.

2023-08-24 06:52 UTC, zmoog requested changes
We should test the dashboard sending sample events using the CLI tool.

2023-08-28 14:42 UTC, zmoog commented
The problem with this integration is that it's using `azure.identityprotection` for field names and `azure.identity_protection` as dataset. We usually use the same for both. This wasn't a wise choice, and it's on me.

We need to have just one of the two eventually, but the very first change we need to to is to make the dashboard work.

2023-08-28 14:59 UTC, zmoog requested changes
@rajvi-elastic, I added a couple of suggestions to replac `azure.identityprotection` with `azure.identity_protection` as the dataset used for queries in the dashboard.

This makes the dashboard display data.

2023-08-28 14:59 UTC, zmoog commented on packages/azure/kibana/dashboard/azure-5ee36c30-32dc-11ed-a2e6-916b60bbea71.json
> +                                "data_stream.dataset": "azure.identityprotection"
Update dataset to fix the dashboard:

```suggestion
                                "data_stream.dataset": "azure.identityprotection"
```

2023-08-28 14:59 UTC, zmoog commented on packages/azure/kibana/dashboard/azure-5ee36c30-32dc-11ed-a2e6-916b60bbea71.json
> +                                "query": "azure.identityprotection"
Update dataset to fix the dashboard:

```suggestion
                                "query": "azure.identity_protection"
```

2023-08-28 15:01 UTC, zmoog commented
The priority is to make the integration work; after it's merged, I'll resolve the naming inconsistencies.

2023-08-29 06:14 UTC, rajvi-elastic commented on packages/azure/kibana/dashboard/azure-5ee36c30-32dc-11ed-a2e6-916b60bbea71.json
> +                                "data_stream.dataset": "azure.identityprotection"
Here also shouldn't it be `"data_stream.dataset": "azure.identity_protection"`?

2023-08-29 07:59 UTC, zmoog commented on packages/azure/kibana/dashboard/azure-5ee36c30-32dc-11ed-a2e6-916b60bbea71.json
> +                                "data_stream.dataset": "azure.identityprotection"
Yep, definitely! I probably mis-pressed the underscore key! 🤦  Not it is fixed as `azure.identity_protection`.

2023-08-29 08:09 UTC, rajvi-elastic commented
@zmoog, I have updated the filters as per the suggestion and dashboards are also getting populated. I have added screenshot in description.

2023-08-29 08:27 UTC, zmoog approved these changes
LGTM, thanks!

2023-08-31 09:22 UTC, merged

2023-08-31 09:44 UTC, elasticmachine commented
Package azure - 1.5.31 containing this change is available at https://epr.elastic.co/search?package=azure