[Cloud Security] Add support for GCP org
elastic/integrations pull request #7403
Opened 2023-08-16 11:39 UTC by orouz

## What does this PR do?

Adds 2 new input vars: `organization_id` and `account_type`

closes https://github.com/elastic/integrations/issues/7398

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

2023-08-16 11:41 UTC, orouz commented on packages/cloud_security_posture/data_stream/findings/manifest.yml
>        - name: project_id
the UI should indicate we support `project_id` or `organization_id`, not both.

2023-08-16 11:55 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7403/detail/PR-7403/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7403/detail/PR-7403/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7403/detail/PR-7403/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7403/detail/PR-7403/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_7403.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-08-16T11:30:12.112Z&rangeTo=2023-08-16T11:50:12.112Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=fbe68515c7781bc3095328a5ce9cadec&transactionId=365213821ffaa92c)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-08-16T11:40:12.112+0000


* Duration: 16 min 35 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 4  |
| Skipped      | 0 |
| Total        | 4   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-08-16 11:56 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 
Classes | 100.0% (`0/0`) | :green_heart: 
Methods | 25.0% (`2/8`) | :-1: -48.333
Lines | 100.0% (`0/0`) | :green_heart: 
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-08-21 08:27 UTC, maxcold approved these changes

2023-08-21 10:11 UTC, oren-zohar reviewed
@orouz do we need to update the changelog and manifest version? this is for 8.11, right?

2023-08-21 10:11 UTC, oren-zohar requested changes
see my previous comment

2023-08-29 13:06 UTC, oren-zohar requested changes

2023-08-29 13:06 UTC, oren-zohar commented on packages/cloud_security_posture/data_stream/findings/agent/stream/gcp.yml.hbs
> +      {{/if}
```suggestion
      {{/if}}
```

2023-08-30 13:01 UTC, orouz commented on packages/cloud_security_posture/data_stream/findings/agent/stream/gcp.yml.hbs
> +      account_type: {{gcp.account_type}}
`project_id` and `organization_id` depend on the value of `account_type`, so they may be missing. `account_type` is required.

2023-08-30 13:03 UTC, orouz commented on packages/cloud_security_posture/changelog.yml
> +- version: "1.6.0"
should this be a preview version?

2023-08-31 08:24 UTC, oren-zohar commented on packages/cloud_security_posture/changelog.yml
> +- version: "1.6.0"
yes

2023-08-31 09:01 UTC, orestisfl commented on packages/cloud_security_posture/data_stream/findings/manifest.yml
> +        required: false
isn't this required?

2023-08-31 12:12 UTC, orouz commented on packages/cloud_security_posture/data_stream/findings/manifest.yml
> +        required: false
i thought our custom ui required us to not use it but this isn't the case for this var.

2023-09-07 06:05 UTC, uri-weisman requested changes

2023-09-07 06:05 UTC, uri-weisman commented on packages/cloud_security_posture/data_stream/findings/manifest.yml
> +        show_user: true
```suggestion
        show_user: false
```

2023-09-07 06:53 UTC, uri-weisman approved these changes

2023-09-07 08:25 UTC, oren-zohar approved these changes

2023-09-10 07:43 UTC, merged

2023-09-10 08:04 UTC, elasticmachine commented
Package cloud_security_posture - 1.6.0-preview1 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-09-10 10:06 UTC, elasticmachine commented
Package cloud_security_posture - 1.6.0-preview11 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-09-10 14:55 UTC, kfirpeled commented on packages/cloud_security_posture/data_stream/findings/agent/stream/gcp.yml.hbs
> +      account_type: {{gcp.account_type}}
@animehart we would need to have a migration here on fleet to add `account_type` when missing

Reference to fleet migrations that work on variable
https://github.com/elastic/kibana/tree/main/x-pack/plugins/fleet/server/saved_objects/migrations/security_solution

2023-09-14 11:46 UTC, elasticmachine commented
Package cloud_security_posture - 1.6.0-preview12 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-09-21 09:36 UTC, elasticmachine commented
Package cloud_security_posture - 1.6.0-preview13 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-10-02 17:36 UTC, elasticmachine commented
Package cloud_security_posture - 1.6.0-preview14 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-10-03 12:33 UTC, elasticmachine commented
Package cloud_security_posture - 1.6.0-preview15 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-10-04 08:38 UTC, elasticmachine commented
Package cloud_security_posture - 1.6.0-preview16 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-10-04 09:03 UTC, elasticmachine commented
Package cloud_security_posture - 1.6.0 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture