[Azure] [monitore] Add dimension and metric_type metadata to the monitor datastream
elastic/integrations pull request #7473
Opened 2023-08-21 12:44 UTC by tetianakravchenko

## What does this PR do?

Add dimension and metric_type metadata to the monitor datastream

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2023-08-21 12:59 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7473/detail/PR-7473/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7473/detail/PR-7473/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7473/detail/PR-7473/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7473/detail/PR-7473/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_7473.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-08-21T12:34:41.218Z&rangeTo=2023-08-21T12:54:41.218Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=c645ed2f1466b3ebc9f76f4c47a75d08&transactionId=036ca6c50cbf644d)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-08-21T12:44:41.218+0000


* Duration: 14 min 16 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 33  |
| Skipped      | 0 |
| Total        | 33   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-08-21 12:59 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`3/3`) | :green_heart: 
Files | 100.0% (`3/3`) | :green_heart: 
Classes | 100.0% (`3/3`) | :green_heart: 
Methods | 73.333% (`22/30`) | :+1: 40.0
Lines | 100.0% (`21/21`) | :green_heart: 
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-08-23 13:29 UTC, zmoog requested changes
I suggest adding `event.kind: pipeline_error` in case of pipeline failure, I see this behavior adopted more and more.

We should consider using `error.message` as an array, as it has become increasingly common but optional.

2023-08-28 09:34 UTC, tetianakravchenko commented on packages/azure_metrics/data_stream/monitor/elasticsearch/ingest_pipeline/default.yml
> +      value: '{{ _ingest.on_failure_message }}'
Done - https://github.com/elastic/integrations/pull/7473/commits/2216ad901ec1658d39df05b4216131e3fd0ab8cd,

2023-08-28 21:51 UTC, zmoog approved these changes

2023-08-30 13:22 UTC, merged

2023-08-30 13:44 UTC, elasticmachine commented
Package azure_metrics - 1.0.34 containing this change is available at https://epr.elastic.co/search?package=azure_metrics