Create heartbeat datastream for cloud-defend
elastic/integrations pull request #7571
Opened 2023-08-28 16:23 UTC by Tacklebox

## What does this PR do?

This PR introduces a new data stream `heartbeat` to the `cloud_defend` package. It is intended to provide a signal of liveness from `cloud_defend`.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

- Relates https://github.com/elastic/cloud-defend/issues/479

## Screenshots

2023-08-28 16:25 UTC, Tacklebox commented
Should the next version for the `changelog.yml` be `1.2.1-preview` or `1.2.0`?

2023-08-28 16:36 UTC, mitodrummer commented on packages/cloud_defend/data_stream/heartbeat/fields/fields.yml
> +# - name: cloud_defend.blocking
any reason we want this commented out?

2023-08-28 16:37 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7571/detail/PR-7571/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7571/detail/PR-7571/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7571/detail/PR-7571/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7571/detail/PR-7571/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_7571.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-08-28T16:13:19.361Z&rangeTo=2023-08-28T16:33:19.361Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=6395e78dd5c0bcc186a68cc0fb96621a&transactionId=cb3440fc12e81dc4)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-08-28T16:23:19.361+0000


* Duration: 14 min 35 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 8  |
| Skipped      | 0 |
| Total        | 8   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-08-28 16:37 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 
Classes | 100.0% (`0/0`) | :green_heart: 
Methods | 27.778% (`5/18`) | :-1: -47.222
Lines | 100.0% (`0/0`) | :green_heart: 
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-08-28 16:56 UTC, mitodrummer commented on packages/cloud_defend/data_stream/heartbeat/fields/fields.yml
> +# - name: cloud_defend.blocking
maybe call it cloud_defend.block_action_enabled

2023-08-28 19:34 UTC, Tacklebox commented on packages/cloud_defend/data_stream/heartbeat/fields/fields.yml
> +- name: cloud_defend.node_uuid
I intentionally created a new mapping since I thought it was only to be used as a uniqueness key rather than part of the process/cloud data model. Does it make more sense to use an existing mapping?

2023-08-28 19:35 UTC, Tacklebox commented on packages/cloud_defend/data_stream/heartbeat/fields/fields.yml
> +# - name: cloud_defend.blocking
Only because I was going to ask if it was something we wanted in the heartbeat. I assume it is, I'll uncomment it

2023-08-28 20:17 UTC, mitodrummer commented on packages/cloud_defend/data_stream/heartbeat/fields/fields.yml
> +# - name: cloud_defend.blocking
Yep, this is needed to detect if a user uses drift w/o paying for it. Originally we were going to only charge nodes which had drift turned on, but that was walked back, and we just count any D4C node if the user has the "cloud complete" tier. At any rate the info is still needed.

2023-08-28 20:19 UTC, mitodrummer commented on packages/cloud_defend/data_stream/heartbeat/fields/fields.yml
> +- name: cloud_defend.node_uuid
I'd say we'd at least want the agent.id and agent.version above. agent.id is pretty much node id, so I'd rather re-use fields we know about so that we can correlate with other indices if need be.

2023-08-28 21:30 UTC, mitodrummer commented on packages/cloud_defend/data_stream/heartbeat/fields/fields.yml
> +- name: cloud_defend.node_uuid
Though setting cloud.instance.name might be a good thing to do as well (if it's easy to get) since I'm unsure if agent.id equaling "a unique node" is future proof (e.g being deployed as something other than a daemonset?) It's also possible our definition of "d4c cloud asset" might change down the road, so other fields could get added in future. e.g orchestrator.resource.name charging by pod or some other metadata.

The nice thing about using already defined ECS fields is you don't have to  add the mapping for the data stream. Our package has an option enabled to dynamically map fields using ECS. see: https://github.com/elastic/integrations/blob/main/packages/cloud_defend/_dev/build/build.yml#L4

Note the process data stream, we are only specifying our namespaced fields. https://github.com/elastic/integrations/blob/main/packages/cloud_defend/data_stream/process/fields/fields.yml

resource.label and resource.annotation were added in 8.8 so we'll need to remove these when we bump the version to 8.9 or 8.10.

2023-08-31 19:16 UTC, mitodrummer commented on packages/cloud_defend/data_stream/heartbeat/fields/fields.yml
> +- name: cloud_defend.agent.id
this can be removed, and we should populate the top level "agent.id" path (which comes from ECS)

2023-08-31 19:17 UTC, mitodrummer commented on packages/cloud_defend/data_stream/heartbeat/fields/fields.yml
> +- name: cloud_defend.agent.version
same with this.

2023-08-31 19:19 UTC, mitodrummer requested changes
packages/cloud_defend/manifest.yml should be updated to 1.2.1-preview1, with changelog entry added. You'll need to install 'elastic-package' and run 'elastic-package build' from integrations/packages/cloud_defend path to validate your changes.

Let me know if you want me to finish this up, as it's blocking Ido from finishing his D4C billing work.

2023-08-31 22:41 UTC, norrietaylor commented
> Let me know if you want me to finish this up, as it's blocking Ido from finishing his D4C billing work.

That would be great @mitodrummer. @Tacklebox is on PTO

2023-08-31 22:53 UTC, mitodrummer approved these changes

2023-08-31 22:55 UTC, norrietaylor approved these changes
LGTM

2023-08-31 23:17 UTC, merged

2023-08-31 23:40 UTC, elasticmachine commented
Package cloud_defend - 1.2.1-preview containing this change is available at https://epr.elastic.co/search?package=cloud_defend