[Custom Logs] Implement input parameter ignore_older
elastic/integrations pull request #7615
Opened 2023-08-30 16:33 UTC by EmiBruno

- Enhancement

## What does this PR do?

Expose ignore_older option for the Custom Logs integration.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally

1.  Build package and startup test environment:
```
cd package/log
elastic-package build
elastic-package stack up -v -d --services package-registry
```
2.  Add a new "Custom Logs" integration to a policy
3.  Verify if the correct logs are collected by the datastream

## Related issues

- Closes #7614

2023-08-30 16:39 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7615/detail/PR-7615/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7615/detail/PR-7615/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7615/detail/PR-7615/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7615/detail/PR-7615/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-08-30T16:26:25.990Z&rangeTo=2023-08-30T16:46:25.990Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=a44058648bb9e95e05e990a73e8ea105&transactionId=618f5893ba20e9f0)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-08-30T16:36:25.990+0000


* Duration: 3 min 7 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7615/detail/PR-7615/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Load a resource file from a library`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-7615/runs/1/steps/81/log/?start=0">here</a></li>
<li>Description: <code>approval-list/elastic/integrations.yml</code></l1>
</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-7615/runs/1/steps/89/log/?start=0">here</a></li>
<li>Description: <code>githubApiCall: The REST API call https://api.github.com/orgs/elastic/members/EmiBruno return the message : java.lang.Exception: httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/EmiBruno : httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/EmiBruno : Code: 404Error: {"message":"User does not exist or is not a member of the organization","documentation_url":"https://docs.github.com/rest/orgs/members#check-organization-membership-for-a-user"}</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-09-14 08:26 UTC, rdner commented
/test

2023-09-14 08:29 UTC, rdner requested changes

2023-09-14 08:29 UTC, rdner commented on packages/log/manifest.yml
> +        default: 72h
Our documentation states that the default value is `0` (disabled) https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-log.html#filebeat-input-log-ignore-older

Where is this default value coming from?

2023-09-14 09:24 UTC, EmiBruno commented on packages/log/manifest.yml
> +        default: 72h
Hello @rdner,

the value 72h is used in other integrations, for that reason I used that value here (ref: https://github.com/elastic/integrations/issues/3147).

I am going to update the dafault value to 0.

Thank you,
Emilio

2023-09-14 11:32 UTC, rdner commented on packages/log/manifest.yml
> +        default: 72h
@EmiBruno why did you set it to `0`? I just asked where this is coming from. If other packages use `72h` as their default let's use it here as well.

2023-09-14 11:34 UTC, rdner commented on packages/log/manifest.yml
> +        default: 0
```suggestion
        default: 72h
```

2023-09-14 12:11 UTC, EmiBruno commented on packages/log/manifest.yml
> +        default: 72h
@rdner I know it was only a question, but I think it is better to keep consistency between filebeat properties and those declared in the integrations.

Do you prefer the 72h value?

2023-09-14 12:50 UTC, rdner commented on packages/log/manifest.yml
> +        default: 72h
@EmiBruno I'd prefer consistency in the integration package space where all the other integrations have `72h` as their default value:

* IIS https://github.com/elastic/integrations/blob/055917fe54c6d69c644e2bd073f6e148255f0700/packages/iis/data_stream/error/manifest.yml#L42
* winlog https://github.com/elastic/integrations/blob/055917fe54c6d69c644e2bd073f6e148255f0700/packages/winlog/data_stream/winlog/manifest.yml#L50
* Windows https://github.com/elastic/integrations/blob/055917fe54c6d69c644e2bd073f6e148255f0700/packages/windows/data_stream/forwarded/manifest.yml#L36 https://github.com/elastic/integrations/blob/055917fe54c6d69c644e2bd073f6e148255f0700/packages/windows/data_stream/sysmon_operational/manifest.yml#L28
* Sysmon Linux https://github.com/elastic/integrations/blob/055917fe54c6d69c644e2bd073f6e148255f0700/packages/sysmon_linux/data_stream/log/manifest.yml#L30
* System Integration https://github.com/elastic/integrations/blob/055917fe54c6d69c644e2bd073f6e148255f0700/packages/system/data_stream/syslog/manifest.yml#L40 https://github.com/elastic/integrations/blob/055917fe54c6d69c644e2bd073f6e148255f0700/packages/system/data_stream/application/manifest.yml#L29 https://github.com/elastic/integrations/blob/055917fe54c6d69c644e2bd073f6e148255f0700/packages/system/data_stream/security/manifest.yml#L29

2023-09-14 12:54 UTC, rdner approved these changes

2023-09-14 13:43 UTC, merged

2023-09-14 14:06 UTC, elasticmachine commented
Package log - 2.2.0 containing this change is available at https://epr.elastic.co/search?package=log