Problem child documentation link
elastic/integrations pull request #7618
Opened 2023-08-30 17:37 UTC by MakoWish

## Type of change
- Enhancement

## What does this PR do?

This PR updates the blog post link in the ProblemChild integration's docs. 

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have incremented the version in my package's `manifest.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Closes #7617

2023-08-30 20:34 UTC, susan-shu-c approved these changes

2023-08-30 20:34 UTC, susan-shu-c commented
/test

2023-08-31 08:07 UTC, peteharverson approved these changes
LGTM for ML

2023-08-31 09:01 UTC, ajosh0504 requested changes

2023-08-31 09:01 UTC, ajosh0504 commented on packages/problemchild/changelog.yml
>  - version: "1.1.0"
Not sure why we bumped to a major version for this change. Could you please change that to `1.0.2` (not sure if this is possible, I'm trying to confirm) and the blog post update version to `1.0.3`? Also, can we consolidate fixes proposed in [this](https://github.com/elastic/integrations/pull/7521) PR and [this](https://github.com/elastic/integrations/pull/7577) one into the 1.0.3 version bump with a description like "Fixing broken links and bugs"?

2023-08-31 09:36 UTC, ajosh0504 commented on packages/problemchild/changelog.yml
> +      type: enhancement
```suggestion
      type: bugfix
```

2023-08-31 09:40 UTC, ajosh0504 commented on packages/problemchild/changelog.yml
> +- version: "1.2.0"
Since we're only fixing bugs here and not adding new functionality, let's only update patch versions, so `1.1.1` in this case. Also, can we consolidate fixes proposed in [the index fixes](https://github.com/elastic/integrations/pull/7521) PR and [the blocklist label fix](https://github.com/elastic/integrations/pull/7577) PR, into this one, with a description such as "Fixing broken links and bugs"?

2023-08-31 09:41 UTC, ajosh0504 commented on packages/problemchild/manifest.yml
> +version: 1.2.0
```suggestion
version: 1.1.1
```

2023-08-31 16:16 UTC, MakoWish commented on packages/problemchild/changelog.yml
> +      type: enhancement
Since it was just an updated link to a newer blog post, I would have considered it an enhancement, but will change it if you would like.

2023-08-31 16:19 UTC, MakoWish commented on packages/problemchild/changelog.yml
> +- version: "1.2.0"
If that's what you would prefer to do, I can do that. Other teams I have worked with prefer to keep different changes on different PR's for clarity. Let me know if you do want to consolidate, and I will.

2023-08-31 16:24 UTC, ajosh0504 commented on packages/problemchild/changelog.yml
> +- version: "1.2.0"
Since these are relatively smaller bug fixes, let's consolidate them into a single patch version bump. The rule update can be a minor version bump since it's a bigger change.

2023-08-31 16:27 UTC, ajosh0504 commented on packages/problemchild/changelog.yml
> +- version: "1.2.0"
Thank you! 🙏

2023-08-31 17:51 UTC, susan-shu-c commented on packages/problemchild/elasticsearch/ingest_pipeline/problem_child_inference_pipeline.yml
> +        && ctx['problemchild']['prediction'] == '0'
@ajosh0504 does this look good? The rest of these changes are good to me

2023-09-01 11:10 UTC, ajosh0504 approved these changes
Awesome work. Thanks, @MakoWish! 🚀

2023-09-01 11:10 UTC, ajosh0504 commented on packages/problemchild/elasticsearch/ingest_pipeline/problem_child_inference_pipeline.yml
> +        && ctx['problemchild']['prediction'] == '0'
Yep this looks good!

2023-09-01 14:51 UTC, merged

2023-09-01 15:14 UTC, elasticmachine commented
Package problemchild - 1.1.1 containing this change is available at https://epr.elastic.co/search?package=problemchild