[O11y][Azure Metrics] Migrate File Storage Overview dashboard to lens
elastic/integrations pull request #7692
Opened 2023-09-07 04:51 UTC by kush-elastic

### Urgency
- High

### Activity Type
- Enhancement

## What does this PR do?
- Manually migrate `Azure File Storage` visualizations to the lens in the current Kibana version `8.4.0` itself. 

- Statistics for `Azure File Storage` Lens migration:
## Migration stats
  | Before Migration |   |   | After Migration |   |  
-- | -- | -- | -- | -- | -- | --
  | Lens | Visualization | Old Input Controls | Lens | Visualization | New control panels
[Azure Metrics] File Storage Overview | 0 | 11 | 1 | 11 | 0 | 1

## Checklist

- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that panels are populated with data.
- [X] I have verified that panels are not distorted after being migrated to the lens.
- [x] I have updated screenshots of the dashboard.
- [X] I have verified that the data counts are matching and panel aggregations are the same as before.

## Author's Checklist

- [X] Migrated panels should be removed from visualization folder.
- [X] Migrated visualizations are populating in current Kibana version 8.4.0 itself.

## Related issues

- Relates #7434 

Before Migration
![image](https://github.com/elastic/integrations/assets/89848966/7977bc9b-6d7b-4070-ab52-6cbdd68b3394)

After Migration
![image](https://github.com/elastic/integrations/assets/89848966/0100460a-eced-4020-b4b1-68b4dde08d7d)

2023-09-07 05:05 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7692/detail/PR-7692/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7692/detail/PR-7692/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7692/detail/PR-7692/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7692/detail/PR-7692/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_7692.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-09-07T04:41:14.492Z&rangeTo=2023-09-07T05:01:14.492Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=3cf3084fbcc6a09ced6af73abe05a548&transactionId=914275f4408cab5a)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-09-07T04:51:14.492+0000


* Duration: 14 min 4 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 34  |
| Skipped      | 0 |
| Total        | 34   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-09-07 05:05 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`4/4`) | :green_heart: 
Files | 100.0% (`4/4`) | :green_heart: 
Classes | 100.0% (`4/4`) | :green_heart: 
Methods | 75.758% (`25/33`) | :-1: -16.701
Lines | 100.0% (`32/32`) | :green_heart: 8.498
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-09-08 10:56 UTC, zmoog requested changes
The file and share count values have decimals:

![CleanShot 2023-09-08 at 12 54 12@2x](https://github.com/elastic/integrations/assets/25941/a04f56ff-57ce-45d9-bfa5-f4c7a452f20c)

Shouldn't these be integer values?

2023-09-08 11:17 UTC, kush-elastic commented
@zmoog ,
Both the visualizations were already using Average aggregation before migration, we will need to create new tickets to address this issue. As part of this PR scope, our focus will be only on migration.


<img width="1414" alt="Screenshot 2023-09-08 at 4 46 24 PM" src="https://github.com/elastic/integrations/assets/89848966/aa677ff3-9a7c-41c1-89f4-a54988447917">


<img width="1417" alt="Screenshot 2023-09-08 at 4 46 58 PM" src="https://github.com/elastic/integrations/assets/89848966/d9206917-252d-4078-889a-6597be7f89a5">

2023-09-12 13:43 UTC, zmoog approved these changes
As discussed at https://github.com/elastic/integrations/pull/7662#issuecomment-1715672085, @kush-elastic will open a dedicated issue to address the decimals in the count.

2023-09-13 07:01 UTC, merged

2023-09-13 07:24 UTC, elasticmachine commented
Package azure_metrics - 1.0.43 containing this change is available at https://epr.elastic.co/search?package=azure_metrics