Undefined log.file.* fields breaking tests for filestream inputs
elastic/integrations pull request #7716
Opened 2023-09-08 06:12 UTC by bhapas

## What does this PR do?

Issue described in https://github.com/elastic/integrations/issues/7687

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Relates https://github.com/elastic/integrations/issues/7687

2023-09-08 06:24 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7716/detail/PR-7716/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7716/detail/PR-7716/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7716/detail/PR-7716/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7716/detail/PR-7716/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_7716.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-09-08T06:02:21.770Z&rangeTo=2023-09-08T06:22:21.770Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=292005d00176bd081bb9b76886a619c3&transactionId=122b929e518b37ea)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-09-08T06:12:21.770+0000


* Duration: 12 min 8 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![4](https://img.shields.io/badge/4%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7716/detail/PR-7716/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Check integration: apache_tomcat`
<ul>
<li>Took 0 min 2 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-7716/runs/1/steps/1162/log/?start=0">here</a></li>
<li>Description: <code>../../build/elastic-package check -v</code></l1>
</ul>
  
  
  
  
##### `Take down the Elastic stack`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-7716/runs/1/steps/1181/log/?start=0">here</a></li>
<li>Description: <code>build/elastic-package stack down -v</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-7716/runs/1/steps/1201/log/?start=0">here</a></li>

</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-7716/runs/1/steps/1214/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-09-08 06:50 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`9/9`) | :green_heart: 
Files | 100.0% (`9/9`) | :green_heart: 
Classes | 100.0% (`9/9`) | :green_heart: 
Methods | 95.062% (`77/81`) | :-1: -4.938
Lines | 79.846% (`931/1166`) | :-1: -16.308
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-09-27 12:19 UTC, andrewkroh commented on packages/apache_tomcat/data_stream/access/fields/beats.yml
> +      type: long
Usually any sort of identifier will be stored as a keyword. Will users need to perform search operations based on the numeric value (e.g. `inode < 100` or sum agg of all inodes)?

2023-09-27 12:27 UTC, bhapas commented on packages/apache_tomcat/data_stream/access/fields/beats.yml
> +      type: long
I picked them form here . https://github.com/elastic/beats/blob/main/libbeat/common/file/file_other.go#L28-L31

But normally, how do users search using IDs that are numeric values?

2023-09-27 13:29 UTC, andrewkroh commented on packages/apache_tomcat/data_stream/access/fields/beats.yml
> +      type: long
> But normally, how do users search using IDs that are numeric values?

Numbers support the same search operations as keyword _and more_. But if the value will be treated as an identifier then it's likely more optimal to store it as a `keyword`.

Just because the code stores the values as a number does not mean it's the best way to store it in Elasticsearch. It depends on how the values will be used. See this https://www.elastic.co/guide/en/elasticsearch/reference/current/tune-for-search-speed.html#map-ids-as-keyword.

I don't think any of the numerical operations like sum aggs or range queries will be useful for inode or device ID values.

2023-09-27 13:30 UTC, bhapas commented on packages/apache_tomcat/data_stream/access/fields/beats.yml
> +      type: long
Yes.. Makes sense.. Will change it to `keyword`

2023-09-27 13:35 UTC, andrewkroh commented on packages/apache_tomcat/data_stream/access/fields/beats.yml
> +    - name: device_id
> I picked them form here . https://github.com/elastic/beats/blob/main/libbeat/common/file/file_other.go#L28-L31

Since you pointed me at the code, that got me wonder what happens on Windows? The device ID and inode are a *nix concept. Is filestream reporting something similar for Windows? Is the field naming aligned?

2023-09-27 13:39 UTC, bhapas commented on packages/apache_tomcat/data_stream/access/fields/beats.yml
> +    - name: device_id
It has been aligned for windows as it looks here - https://github.com/elastic/beats/pull/36065

```
This includes:

Unix-like:
      device
      inode
Windows:
      idxlo
      idxhi
      vol
```

2023-09-27 13:41 UTC, bhapas commented on packages/apache_tomcat/data_stream/access/fields/beats.yml
> +    - name: device_id
Which means these fields should be added as well?
https://github.com/elastic/beats/pull/36065/files#diff-78518264e9ef2d397f08bcbeb628856d1ce65b62ec2058a914147bd99d02a992R29-R31

2023-09-27 13:58 UTC, andrewkroh commented on packages/apache_tomcat/data_stream/access/fields/beats.yml
> +    - name: device_id
Yes, and `log.file.fingerprint`.

IMO these files should not have been added to `log.file.*` without first going through a change to ECS because this is an ECS namespace. I think we could have established a better format with some discussion about how this information will be used. Additionally we may have been able to establishing field alignment between Windows and unix.

2023-09-27 17:25 UTC, bhapas commented on packages/apache_tomcat/data_stream/access/fields/beats.yml
> +    - name: device_id
Yeah.. I saw that this is an ECS namespace. Should this be a change request in beats?

2023-09-27 20:13 UTC, andrewkroh commented on packages/apache_tomcat/data_stream/access/fields/beats.yml
> +    - name: idxhiKey
```suggestion
    - name: idxhi
```

2023-09-27 20:13 UTC, andrewkroh commented on packages/apache_tomcat/data_stream/access/fields/beats.yml
> +    - name: idxloKey
```suggestion
    - name: idxlo
```

2023-09-27 20:13 UTC, andrewkroh commented on packages/apache_tomcat/data_stream/access/fields/beats.yml
> +    - name: volKey
```suggestion
    - name: vol
```

2023-09-27 20:15 UTC, andrewkroh commented on packages/apache_tomcat/data_stream/access/_dev/test/system/test-default-config.yml
> +  - log.file.inode
```suggestion
  - log.file.inode
  - log.file.idxhi
  - log.file.idxlo
  - log.file.vol
```

Those fields are also numbers.

2023-09-27 21:18 UTC, andrewkroh requested changes
The more I look at this problem I think we need to go back to the ingest team, and talk about changing the field types to be strings for the reason given in https://github.com/elastic/integrations/pull/7716#discussion_r1338613797. Otherwise, this will be an uphill battle to keep a consistent mapping type between integrations. As soon as an integration forgets to map these numeric fields then there will be a conflict with the integrations that do map it as `keyword`. Today there are 22 separate data streams associated with the filestream input that need mappings for these fields.

Secondly, the fields are `uint64`[^1][^2] in Beats. The default mapping will be `long`[^3], and this is not the correct type because a uint64 does not fit into long (i.e. 2^64 > 2^63).

Third, this would be an opportunity to align the definitions between operating systems and propose these to ECS. Like perhaps

|                    | Type   | Unix                    | Windows                                                                                  |
|--------------------|--------|-------------------------|------------------------------------------------------------------------------------------|
| log.file.device_id | string | Device ID               | NTFS volume                                                                              |
| log.file.inode     | string | Inode number in decimal | File index number in decimal (high and low order 32-bit values combined to form a uint64) |

@rdner @ycombinator Would you be open to some changes to these fields in the input?

[^1]: https://github.com/elastic/beats/blob/8ff6894cab0591cc3a898d7abd6a9103e535efdd/libbeat/common/file/file_windows.go#L32-L34
[^2]: https://github.com/elastic/beats/blob/f0215ff5cfdbcb0db8ebc1f07af1b4885081389b/libbeat/common/file/file_other.go#L29-L30
[^3]:https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-field-mapping.html

2023-09-28 06:27 UTC, bhapas commented
> The more I look at this problem I think we need to go back to the ingest team, and talk about changing the field types to be strings for the reason given in [#7716 (comment)](https://github.com/elastic/integrations/pull/7716#discussion_r1338613797). Otherwise, this will be an uphill battle to keep a consistent mapping type between integrations. As soon as an integration forgets to map these numeric fields then there will be a conflict with the integrations that do map it as `keyword`. Today there are 22 separate data streams associated with the filestream input that need mappings for these fields.
> 
> Secondly, the fields are `uint64`[1](#user-content-fn-1-6fabb0a863907aa614d894e6455f3818)[2](#user-content-fn-2-6fabb0a863907aa614d894e6455f3818) in Beats. The default mapping will be `long`[3](#user-content-fn-3-6fabb0a863907aa614d894e6455f3818), and this is not the correct type because a uint64 does not fit into long (i.e. 2^64 > 2^63).
> 
> Third, this would be an opportunity to align the definitions between operating systems and propose these to ECS. Like perhaps
> 
> Type	Unix	Windows
> log.file.device_id	string	Device ID	NTFS volume
> log.file.inode	string	Inode number in decimal	File index number in decimal (high and low order 32-bit values combined to form a uint64)
> @rdner @ycombinator Would you be open to some changes to these fields in the input?
> 
> ## Footnotes
> 1. https://github.com/elastic/beats/blob/8ff6894cab0591cc3a898d7abd6a9103e535efdd/libbeat/common/file/file_windows.go#L32-L34 [↩](#user-content-fnref-1-6fabb0a863907aa614d894e6455f3818)
> 2. https://github.com/elastic/beats/blob/f0215ff5cfdbcb0db8ebc1f07af1b4885081389b/libbeat/common/file/file_other.go#L29-L30 [↩](#user-content-fnref-2-6fabb0a863907aa614d894e6455f3818)
> 3. https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-field-mapping.html [↩](#user-content-fnref-3-6fabb0a863907aa614d894e6455f3818)

Created an issue for this in beats https://github.com/elastic/beats/issues/36695

2023-09-28 08:22 UTC, rdner commented
@andrewkroh I'd like to point out 2 things:

1. initially `log.file.device`, `log.file.inode`, `log.file.idxhi`, `log.file.idxlo` and `log.file.vol` were strings and during the review were [switched to numbers](https://github.com/elastic/beats/pull/36065/commits/abc9643e44385bfd4d74ae69a9c14b9a631b029c) based on the [argument](https://github.com/elastic/beats/pull/36065#issuecomment-1635938924) that someone would like to use a range search on these values.

2. Regarding the `file.device` field in [ECS](https://www.elastic.co/guide/en/ecs/current/ecs-file.html#field-file-device) it's not the same as `log.file.device_id` as I explained during the review here https://github.com/elastic/beats/pull/36065#issuecomment-1638178702

I'm fine with reverting everything back to strings if @ycombinator is fine with it.

I'm surprised adding these fields caused so many issues, apologies. Next time, I will involve integration developers into a review when we add more fields.

2023-09-28 12:28 UTC, ycombinator commented
Yep, I'm good with using strings / keywords for these fields given how they're intended to be used.

2023-09-28 14:11 UTC, andrewkroh reviewed
I think we need better technical descriptions of these fields. I have made suggestions. PTAL

@rdner Can you please also review these descriptions to ensure their accuracy? Where are these field descriptions in Filebeat ([example](https://github.com/elastic/beats/blob/ef457ea2b1046c8283a96e789185a18d29504da7/filebeat/_meta/fields.common.yml#L13-L17))?

2023-09-28 14:11 UTC, andrewkroh commented on packages/apache_tomcat/data_stream/access/fields/beats.yml
> +      description: Fingerprint for the file
```suggestion
      description: The sha256 fingerprint identity of the file when fingerprinting is enabled.
```

2023-09-28 15:18 UTC, andrewkroh approved these changes

2023-09-28 17:09 UTC, rdner commented
@andrewkroh the descriptions you suggested looks perfect to me.

Regarding the [example](https://github.com/elastic/beats/blob/ef457ea2b1046c8283a96e789185a18d29504da7/filebeat/_meta/fields.common.yml#L13-L17) file, should every event field be there? I'm asking because it's missing a few fields, for example, `log.file.path` is not there either.

What's the purpose of this file exactly?

2023-09-28 17:20 UTC, andrewkroh commented
> Regarding the [example](https://github.com/elastic/beats/blob/ef457ea2b1046c8283a96e789185a18d29504da7/filebeat/_meta/fields.common.yml#L13-L17) file, should every event field be there? I'm asking because it's missing a few fields, for example, log.file.path is not there either.

These files drive our documentation and the Elasticsearch index templates. `log.file.path` is not in that file because it is defined in another [file](https://github.com/elastic/beats/blob/74eee5737b93ff21ce61e718b73a7794c93751e3/libbeat/_meta/fields.ecs.yml#L3476-L3483) in the repo that provides the ECS fields. On the website you will see [log.file.path](https://www.elastic.co/guide/en/beats/filebeat/current/exported-fields-ecs.html#_log_4) in the ECS section and [log.file.offset](https://www.elastic.co/guide/en/beats/filebeat/current/exported-fields-log.html) in another section because that predates the existence of ECS.

2023-09-28 20:48 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2023-09-29 18:15 UTC, ishleenk17 commented on packages/apache_tomcat/data_stream/access/fields/beats.yml
> +    - name: inode
Considering that these fields are currently numeric and would be changed to string as per this [comment](https://github.com/elastic/integrations/pull/7716#issuecomment-1739060503), is it fine to use keyword here as of now?

2023-09-29 21:01 UTC, andrewkroh commented on packages/apache_tomcat/data_stream/access/fields/beats.yml
> +    - name: inode
Any JSON numeric value can be mapped as keyword in ES without conversion to a JSON string.

2023-09-30 10:47 UTC, ishleenk17 approved these changes
Looks good!

2023-10-01 09:33 UTC, merged

2023-10-01 10:06 UTC, elasticmachine commented
Package apache_tomcat - 0.13.0 containing this change is available at https://epr.elastic.co/search?package=apache_tomcat

2023-10-01 10:55 UTC, elasticmachine commented
Package coredns - 0.5.0 containing this change is available at https://epr.elastic.co/search?package=coredns