[O11y][Cassandra] fix the type for log.flags field
elastic/integrations pull request #7787
Opened 2023-09-13 06:15 UTC by aliabbas-elastic

- Bug

## What does this PR do?

- This PR changes the incorrect `type` mentioned for `log.flags` field.
- Updated the description for other fields mentioned in `agent.yml`.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Relates #7712

2023-09-13 06:32 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7787/detail/PR-7787/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7787/detail/PR-7787/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7787/detail/PR-7787/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7787/detail/PR-7787/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_7787.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-09-13T06:06:14.545Z&rangeTo=2023-09-13T06:26:14.545Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=139ddf4895d78755797ede85d62a551a&transactionId=6481381693226eb8)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-09-13T06:16:14.545+0000


* Duration: 16 min 21 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 11  |
| Skipped      | 0 |
| Total        | 11   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-09-13 06:32 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`1/1`) | :green_heart: 
Files | 100.0% (`1/1`) | :green_heart: 2.695
Classes | 100.0% (`1/1`) | :green_heart: 2.695
Methods | 100.0% (`13/13`) | :green_heart: 7.737
Lines | 91.228% (`52/57`) | :+1: 2.899
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-09-18 07:21 UTC, kush-elastic approved these changes
LGTM!

2023-09-25 21:42 UTC, andrewkroh approved these changes

2023-09-27 06:01 UTC, aliabbas-elastic commented
/test

2023-09-27 07:04 UTC, shmsr requested changes

2023-09-27 07:04 UTC, shmsr commented on packages/cassandra/docs/README.md
> +If log.flags is shown conflicted under ``logs-*`` data view, then this issue can be solved by reindexing the ``Logs`` data stream's indices.
```suggestion
If log.flags is shown conflicted under the ``logs-*`` data view, then this issue can be solved by reindexing the ``Logs`` data stream's indices.
```

2023-09-27 07:04 UTC, shmsr commented on packages/cassandra/_dev/build/docs/README.md
> +If log.flags is shown conflicted under ``logs-*`` data view, then this issue can be solved by reindexing the ``Logs`` data stream's indices.
```suggestion
If log.flags is shown conflicted under the ``logs-*`` data view, then this issue can be solved by reindexing the ``Logs`` data stream's indices.
```

2023-09-27 11:27 UTC, shmsr approved these changes

2023-09-27 11:59 UTC, merged

2023-09-27 12:22 UTC, elasticmachine commented
Package cassandra - 1.9.2 containing this change is available at https://epr.elastic.co/search?package=cassandra