[TI_AbuseCH] Add IOC expiration support with new datastreams
elastic/integrations pull request #7793
Opened 2023-09-13 09:59 UTC by kcreddy

## What does this PR do?
Adds new datastreams `active_*` using CEL input with IOC expiration support

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

- Closes https://github.com/elastic/integrations/issues/7322

## Screenshots

2023-09-13 10:14 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7793/detail/PR-7793/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7793/detail/PR-7793/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7793/detail/PR-7793/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7793/detail/PR-7793/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_7793.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-09-13T09:50:09.266Z&rangeTo=2023-09-13T10:10:09.266Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=5375d1a2910f44f0185546f26d9f8023&transactionId=a7a567bbb900f6c4)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-09-13T10:00:09.266+0000


* Duration: 14 min 23 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![3](https://img.shields.io/badge/3%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7793/detail/PR-7793/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Test integration: ti_abusech`
<ul>
<li>Took 0 min 8 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-7793/runs/1/steps/1201/log/?start=0">here</a></li>
<li>Description: <code>                                eval "$(../../build/elastic-package stack shellinit)"                                ../../build/elastic-package test -v --report-format xUnit --report-output file --test-coverage                                </code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-7793/runs/1/steps/1290/log/?start=0">here</a></li>

</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-7793/runs/1/steps/1303/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-09-26 08:33 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 
Classes | 100.0% (`0/0`) | :green_heart: 
Methods | 100.0% (`7/7`) | :green_heart: 33.333
Lines | 100.0% (`0/0`) | :green_heart: 
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-12-21 09:44 UTC, mrodm commented
Hi @kcreddy, please update your branch with the latest contents from main branch. There was an important PR merged updating the CI pipelines. Thanks!

2024-03-19 10:21 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/9676)
* Commit: 960ebbd68f4d3ef5d8f50a2d205e275c2e0b0489

### Failed CI Steps
* [Check integrations ti_abusech](https://buildkite.com/elastic/integrations/builds/9676#018e5634-05a7-451b-86d4-d959b4416b63)

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9676","number":9676,"commit":"960ebbd68f4d3ef5d8f50a2d205e275c2e0b0489"}],"number":9676}
buildkite-pr-comment-->

2024-03-21 15:52 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/9734)
* Commit: a362bceb24a87a5c352991a264f48ae636cb9104

### Failed CI Steps
* [Check integrations ti_abusech](https://buildkite.com/elastic/integrations/builds/9734#018e61ae-7fe0-411d-bcdd-c12b0ded8e1a)

### History
* :broken_heart: [Build #9676](https://buildkite.com/elastic/integrations/builds/9676) failed 960ebbd68f4d3ef5d8f50a2d205e275c2e0b0489

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9734","number":9734,"commit":"a362bceb24a87a5c352991a264f48ae636cb9104"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9676","number":9676,"commit":"960ebbd68f4d3ef5d8f50a2d205e275c2e0b0489"}],"number":9734}
buildkite-pr-comment-->

2024-03-21 16:12 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/9735)
* Commit: 00819dab401551695151192ee2e809ff65d40256

### Failed CI Steps
* [Check integrations ti_abusech](https://buildkite.com/elastic/integrations/builds/9735#018e61c0-7e6c-4abb-9c8e-2cb96db9b10d)

### History
* :broken_heart: [Build #9734](https://buildkite.com/elastic/integrations/builds/9734) failed a362bceb24a87a5c352991a264f48ae636cb9104
* :broken_heart: [Build #9676](https://buildkite.com/elastic/integrations/builds/9676) failed 960ebbd68f4d3ef5d8f50a2d205e275c2e0b0489

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9735","number":9735,"commit":"00819dab401551695151192ee2e809ff65d40256"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9734","number":9734,"commit":"a362bceb24a87a5c352991a264f48ae636cb9104"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9676","number":9676,"commit":"960ebbd68f4d3ef5d8f50a2d205e275c2e0b0489"}],"number":9735}
buildkite-pr-comment-->

2024-03-25 14:09 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/9831)
* Commit: 8efb7e4a0442eb0ff1673ca54c44562cc468f84a

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/9831#018e75f1-116f-4fae-bdb8-c014bb420ba7)

### History
* :broken_heart: [Build #9735](https://buildkite.com/elastic/integrations/builds/9735) failed 00819dab401551695151192ee2e809ff65d40256
* :broken_heart: [Build #9734](https://buildkite.com/elastic/integrations/builds/9734) failed a362bceb24a87a5c352991a264f48ae636cb9104
* :broken_heart: [Build #9676](https://buildkite.com/elastic/integrations/builds/9676) failed 960ebbd68f4d3ef5d8f50a2d205e275c2e0b0489

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9831","number":9831,"commit":"8efb7e4a0442eb0ff1673ca54c44562cc468f84a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9735","number":9735,"commit":"00819dab401551695151192ee2e809ff65d40256"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9734","number":9734,"commit":"a362bceb24a87a5c352991a264f48ae636cb9104"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9676","number":9676,"commit":"960ebbd68f4d3ef5d8f50a2d205e275c2e0b0489"}],"number":9831}
buildkite-pr-comment-->

2024-03-28 10:37 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/9942)
* Commit: 61846f07aef379d5d1afe850780289ae5ebb8ead

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/9942#018e84a2-6bdc-4be3-9558-7b36060bfae3)

### History
* :broken_heart: [Build #9831](https://buildkite.com/elastic/integrations/builds/9831) failed 8efb7e4a0442eb0ff1673ca54c44562cc468f84a
* :broken_heart: [Build #9735](https://buildkite.com/elastic/integrations/builds/9735) failed 00819dab401551695151192ee2e809ff65d40256
* :broken_heart: [Build #9734](https://buildkite.com/elastic/integrations/builds/9734) failed a362bceb24a87a5c352991a264f48ae636cb9104
* :broken_heart: [Build #9676](https://buildkite.com/elastic/integrations/builds/9676) failed 960ebbd68f4d3ef5d8f50a2d205e275c2e0b0489

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9942","number":9942,"commit":"61846f07aef379d5d1afe850780289ae5ebb8ead"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9831","number":9831,"commit":"8efb7e4a0442eb0ff1673ca54c44562cc468f84a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9735","number":9735,"commit":"00819dab401551695151192ee2e809ff65d40256"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9734","number":9734,"commit":"a362bceb24a87a5c352991a264f48ae636cb9104"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9676","number":9676,"commit":"960ebbd68f4d3ef5d8f50a2d205e275c2e0b0489"}],"number":9942}
buildkite-pr-comment-->

2024-04-05 05:36 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10162)
* Commit: 9d50fd4799c60c4ec50ae4b41be13be72f7cc6ba

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/10162#018eacc1-a71a-46a0-9474-7ec81651953b)

### History
* :broken_heart: [Build #9958](https://buildkite.com/elastic/integrations/builds/9958) failed fce766e014c0598c5bd6fbffd41a838f79816032
* :broken_heart: [Build #9942](https://buildkite.com/elastic/integrations/builds/9942) failed 61846f07aef379d5d1afe850780289ae5ebb8ead
* :broken_heart: [Build #9831](https://buildkite.com/elastic/integrations/builds/9831) failed 8efb7e4a0442eb0ff1673ca54c44562cc468f84a
* :broken_heart: [Build #9735](https://buildkite.com/elastic/integrations/builds/9735) failed 00819dab401551695151192ee2e809ff65d40256
* :broken_heart: [Build #9734](https://buildkite.com/elastic/integrations/builds/9734) failed a362bceb24a87a5c352991a264f48ae636cb9104
* :broken_heart: [Build #9676](https://buildkite.com/elastic/integrations/builds/9676) failed 960ebbd68f4d3ef5d8f50a2d205e275c2e0b0489

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10162","number":10162,"commit":"9d50fd4799c60c4ec50ae4b41be13be72f7cc6ba"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9958","number":9958,"commit":"fce766e014c0598c5bd6fbffd41a838f79816032"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9942","number":9942,"commit":"61846f07aef379d5d1afe850780289ae5ebb8ead"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9831","number":9831,"commit":"8efb7e4a0442eb0ff1673ca54c44562cc468f84a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9735","number":9735,"commit":"00819dab401551695151192ee2e809ff65d40256"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9734","number":9734,"commit":"a362bceb24a87a5c352991a264f48ae636cb9104"}],"number":10162}
buildkite-pr-comment-->

2024-04-05 10:00 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10170)
* Commit: 50e5b3f57bf188038a4f1a8eda4ca1cf6ea0059b

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/10170#018eadb2-bc4d-43a2-8bea-2fb49c9176cd)

### History
* :broken_heart: [Build #10162](https://buildkite.com/elastic/integrations/builds/10162) failed 9d50fd4799c60c4ec50ae4b41be13be72f7cc6ba
* :broken_heart: [Build #9958](https://buildkite.com/elastic/integrations/builds/9958) failed fce766e014c0598c5bd6fbffd41a838f79816032
* :broken_heart: [Build #9942](https://buildkite.com/elastic/integrations/builds/9942) failed 61846f07aef379d5d1afe850780289ae5ebb8ead
* :broken_heart: [Build #9831](https://buildkite.com/elastic/integrations/builds/9831) failed 8efb7e4a0442eb0ff1673ca54c44562cc468f84a
* :broken_heart: [Build #9735](https://buildkite.com/elastic/integrations/builds/9735) failed 00819dab401551695151192ee2e809ff65d40256
* :broken_heart: [Build #9734](https://buildkite.com/elastic/integrations/builds/9734) failed a362bceb24a87a5c352991a264f48ae636cb9104

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10170","number":10170,"commit":"50e5b3f57bf188038a4f1a8eda4ca1cf6ea0059b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10162","number":10162,"commit":"9d50fd4799c60c4ec50ae4b41be13be72f7cc6ba"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9958","number":9958,"commit":"fce766e014c0598c5bd6fbffd41a838f79816032"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9942","number":9942,"commit":"61846f07aef379d5d1afe850780289ae5ebb8ead"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9831","number":9831,"commit":"8efb7e4a0442eb0ff1673ca54c44562cc468f84a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9735","number":9735,"commit":"00819dab401551695151192ee2e809ff65d40256"}],"number":10170}
buildkite-pr-comment-->

2024-04-06 07:30 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10199)
* Commit: 7c197508b31ad56fa6824f159192a08d2ac646cf

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/10199#018eb24f-fc42-43f0-9a8f-c78b7f26166e)

### History
* :broken_heart: [Build #10170](https://buildkite.com/elastic/integrations/builds/10170) failed 50e5b3f57bf188038a4f1a8eda4ca1cf6ea0059b
* :broken_heart: [Build #10162](https://buildkite.com/elastic/integrations/builds/10162) failed 9d50fd4799c60c4ec50ae4b41be13be72f7cc6ba
* :broken_heart: [Build #9958](https://buildkite.com/elastic/integrations/builds/9958) failed fce766e014c0598c5bd6fbffd41a838f79816032
* :broken_heart: [Build #9942](https://buildkite.com/elastic/integrations/builds/9942) failed 61846f07aef379d5d1afe850780289ae5ebb8ead
* :broken_heart: [Build #9831](https://buildkite.com/elastic/integrations/builds/9831) failed 8efb7e4a0442eb0ff1673ca54c44562cc468f84a
* :broken_heart: [Build #9735](https://buildkite.com/elastic/integrations/builds/9735) failed 00819dab401551695151192ee2e809ff65d40256

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10199","number":10199,"commit":"7c197508b31ad56fa6824f159192a08d2ac646cf"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10170","number":10170,"commit":"50e5b3f57bf188038a4f1a8eda4ca1cf6ea0059b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10162","number":10162,"commit":"9d50fd4799c60c4ec50ae4b41be13be72f7cc6ba"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9958","number":9958,"commit":"fce766e014c0598c5bd6fbffd41a838f79816032"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9942","number":9942,"commit":"61846f07aef379d5d1afe850780289ae5ebb8ead"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9831","number":9831,"commit":"8efb7e4a0442eb0ff1673ca54c44562cc468f84a"}],"number":10199}
buildkite-pr-comment-->

2024-04-06 07:44 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10200)
* Commit: c11c2ccc9ca3807e39cfd2125067a02f46f8c86b

### Failed CI Steps
* [Check integrations ti_abusech](https://buildkite.com/elastic/integrations/builds/10200#018eb256-936c-47fe-8b13-119a49da2bcd)

### History
* :broken_heart: [Build #10199](https://buildkite.com/elastic/integrations/builds/10199) failed 7c197508b31ad56fa6824f159192a08d2ac646cf
* :broken_heart: [Build #10170](https://buildkite.com/elastic/integrations/builds/10170) failed 50e5b3f57bf188038a4f1a8eda4ca1cf6ea0059b
* :broken_heart: [Build #10162](https://buildkite.com/elastic/integrations/builds/10162) failed 9d50fd4799c60c4ec50ae4b41be13be72f7cc6ba
* :broken_heart: [Build #9958](https://buildkite.com/elastic/integrations/builds/9958) failed fce766e014c0598c5bd6fbffd41a838f79816032
* :broken_heart: [Build #9942](https://buildkite.com/elastic/integrations/builds/9942) failed 61846f07aef379d5d1afe850780289ae5ebb8ead
* :broken_heart: [Build #9831](https://buildkite.com/elastic/integrations/builds/9831) failed 8efb7e4a0442eb0ff1673ca54c44562cc468f84a

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10200","number":10200,"commit":"c11c2ccc9ca3807e39cfd2125067a02f46f8c86b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10199","number":10199,"commit":"7c197508b31ad56fa6824f159192a08d2ac646cf"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10170","number":10170,"commit":"50e5b3f57bf188038a4f1a8eda4ca1cf6ea0059b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10162","number":10162,"commit":"9d50fd4799c60c4ec50ae4b41be13be72f7cc6ba"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9958","number":9958,"commit":"fce766e014c0598c5bd6fbffd41a838f79816032"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9942","number":9942,"commit":"61846f07aef379d5d1afe850780289ae5ebb8ead"}],"number":10200}
buildkite-pr-comment-->

2024-04-08 06:09 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10212)
* Commit: 2db2ca26b4fd869c03854703830dcaac42dd0477

### Failed CI Steps
* [Check integrations ti_abusech](https://buildkite.com/elastic/integrations/builds/10212#018ebc4c-c793-4c80-947a-4a86036f3213)

### History
* :broken_heart: [Build #10200](https://buildkite.com/elastic/integrations/builds/10200) failed c11c2ccc9ca3807e39cfd2125067a02f46f8c86b
* :broken_heart: [Build #10199](https://buildkite.com/elastic/integrations/builds/10199) failed 7c197508b31ad56fa6824f159192a08d2ac646cf
* :broken_heart: [Build #10170](https://buildkite.com/elastic/integrations/builds/10170) failed 50e5b3f57bf188038a4f1a8eda4ca1cf6ea0059b
* :broken_heart: [Build #10162](https://buildkite.com/elastic/integrations/builds/10162) failed 9d50fd4799c60c4ec50ae4b41be13be72f7cc6ba
* :broken_heart: [Build #9958](https://buildkite.com/elastic/integrations/builds/9958) failed fce766e014c0598c5bd6fbffd41a838f79816032

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10212","number":10212,"commit":"2db2ca26b4fd869c03854703830dcaac42dd0477"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10200","number":10200,"commit":"c11c2ccc9ca3807e39cfd2125067a02f46f8c86b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10199","number":10199,"commit":"7c197508b31ad56fa6824f159192a08d2ac646cf"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10170","number":10170,"commit":"50e5b3f57bf188038a4f1a8eda4ca1cf6ea0059b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10162","number":10162,"commit":"9d50fd4799c60c4ec50ae4b41be13be72f7cc6ba"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9958","number":9958,"commit":"fce766e014c0598c5bd6fbffd41a838f79816032"}],"number":10212}
buildkite-pr-comment-->

2024-04-08 06:44 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-04-08 06:44 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10213)
* Commit: 3393bc1be6207769e1a5d15e7818e5909c15110c

### History
* :broken_heart: [Build #10212](https://buildkite.com/elastic/integrations/builds/10212) failed 2db2ca26b4fd869c03854703830dcaac42dd0477
* :broken_heart: [Build #10200](https://buildkite.com/elastic/integrations/builds/10200) failed c11c2ccc9ca3807e39cfd2125067a02f46f8c86b
* :broken_heart: [Build #10199](https://buildkite.com/elastic/integrations/builds/10199) failed 7c197508b31ad56fa6824f159192a08d2ac646cf
* :broken_heart: [Build #10170](https://buildkite.com/elastic/integrations/builds/10170) failed 50e5b3f57bf188038a4f1a8eda4ca1cf6ea0059b
* :broken_heart: [Build #10162](https://buildkite.com/elastic/integrations/builds/10162) failed 9d50fd4799c60c4ec50ae4b41be13be72f7cc6ba

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10213","number":10213,"commit":"3393bc1be6207769e1a5d15e7818e5909c15110c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10212","number":10212,"commit":"2db2ca26b4fd869c03854703830dcaac42dd0477"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10200","number":10200,"commit":"c11c2ccc9ca3807e39cfd2125067a02f46f8c86b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10199","number":10199,"commit":"7c197508b31ad56fa6824f159192a08d2ac646cf"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10170","number":10170,"commit":"50e5b3f57bf188038a4f1a8eda4ca1cf6ea0059b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10162","number":10162,"commit":"9d50fd4799c60c4ec50ae4b41be13be72f7cc6ba"}],"number":10213}
buildkite-pr-comment-->

2024-04-08 07:45 UTC, elasticmachine commented
Pinging @elastic/security-service-integrations (Team:Security-Service Integrations)

2024-04-08 07:56 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10220)
* Commit: 261fda5829fc0c23cfd83120d017e47a357a0f41

### History
* :green_heart: [Build #10213](https://buildkite.com/elastic/integrations/builds/10213) succeeded 3393bc1be6207769e1a5d15e7818e5909c15110c
* :broken_heart: [Build #10212](https://buildkite.com/elastic/integrations/builds/10212) failed 2db2ca26b4fd869c03854703830dcaac42dd0477
* :broken_heart: [Build #10200](https://buildkite.com/elastic/integrations/builds/10200) failed c11c2ccc9ca3807e39cfd2125067a02f46f8c86b
* :broken_heart: [Build #10199](https://buildkite.com/elastic/integrations/builds/10199) failed 7c197508b31ad56fa6824f159192a08d2ac646cf
* :broken_heart: [Build #10170](https://buildkite.com/elastic/integrations/builds/10170) failed 50e5b3f57bf188038a4f1a8eda4ca1cf6ea0059b
* :broken_heart: [Build #10162](https://buildkite.com/elastic/integrations/builds/10162) failed 9d50fd4799c60c4ec50ae4b41be13be72f7cc6ba

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10220","number":10220,"commit":"261fda5829fc0c23cfd83120d017e47a357a0f41"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10213","number":10213,"commit":"3393bc1be6207769e1a5d15e7818e5909c15110c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10212","number":10212,"commit":"2db2ca26b4fd869c03854703830dcaac42dd0477"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10200","number":10200,"commit":"c11c2ccc9ca3807e39cfd2125067a02f46f8c86b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10199","number":10199,"commit":"7c197508b31ad56fa6824f159192a08d2ac646cf"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10170","number":10170,"commit":"50e5b3f57bf188038a4f1a8eda4ca1cf6ea0059b"}],"number":10220}
buildkite-pr-comment-->

2024-04-08 11:53 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10235)
* Commit: e345529e0e948cf5f9afc1b2a64f4b786d423edc

### History
* :green_heart: [Build #10220](https://buildkite.com/elastic/integrations/builds/10220) succeeded 261fda5829fc0c23cfd83120d017e47a357a0f41
* :green_heart: [Build #10213](https://buildkite.com/elastic/integrations/builds/10213) succeeded 3393bc1be6207769e1a5d15e7818e5909c15110c
* :broken_heart: [Build #10212](https://buildkite.com/elastic/integrations/builds/10212) failed 2db2ca26b4fd869c03854703830dcaac42dd0477
* :broken_heart: [Build #10200](https://buildkite.com/elastic/integrations/builds/10200) failed c11c2ccc9ca3807e39cfd2125067a02f46f8c86b
* :broken_heart: [Build #10199](https://buildkite.com/elastic/integrations/builds/10199) failed 7c197508b31ad56fa6824f159192a08d2ac646cf
* :broken_heart: [Build #10170](https://buildkite.com/elastic/integrations/builds/10170) failed 50e5b3f57bf188038a4f1a8eda4ca1cf6ea0059b

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10235","number":10235,"commit":"e345529e0e948cf5f9afc1b2a64f4b786d423edc"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10220","number":10220,"commit":"261fda5829fc0c23cfd83120d017e47a357a0f41"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10213","number":10213,"commit":"3393bc1be6207769e1a5d15e7818e5909c15110c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10212","number":10212,"commit":"2db2ca26b4fd869c03854703830dcaac42dd0477"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10200","number":10200,"commit":"c11c2ccc9ca3807e39cfd2125067a02f46f8c86b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10199","number":10199,"commit":"7c197508b31ad56fa6824f159192a08d2ac646cf"}],"number":10235}
buildkite-pr-comment-->

2024-04-09 05:01 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10272)
* Commit: 47eb19bd0536878d1c1ef61a495df278aefe4cb0

### History
* :green_heart: [Build #10235](https://buildkite.com/elastic/integrations/builds/10235) succeeded e345529e0e948cf5f9afc1b2a64f4b786d423edc
* :green_heart: [Build #10220](https://buildkite.com/elastic/integrations/builds/10220) succeeded 261fda5829fc0c23cfd83120d017e47a357a0f41
* :green_heart: [Build #10213](https://buildkite.com/elastic/integrations/builds/10213) succeeded 3393bc1be6207769e1a5d15e7818e5909c15110c
* :broken_heart: [Build #10212](https://buildkite.com/elastic/integrations/builds/10212) failed 2db2ca26b4fd869c03854703830dcaac42dd0477
* :broken_heart: [Build #10200](https://buildkite.com/elastic/integrations/builds/10200) failed c11c2ccc9ca3807e39cfd2125067a02f46f8c86b
* :broken_heart: [Build #10199](https://buildkite.com/elastic/integrations/builds/10199) failed 7c197508b31ad56fa6824f159192a08d2ac646cf

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10272","number":10272,"commit":"47eb19bd0536878d1c1ef61a495df278aefe4cb0"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10235","number":10235,"commit":"e345529e0e948cf5f9afc1b2a64f4b786d423edc"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10220","number":10220,"commit":"261fda5829fc0c23cfd83120d017e47a357a0f41"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10213","number":10213,"commit":"3393bc1be6207769e1a5d15e7818e5909c15110c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10212","number":10212,"commit":"2db2ca26b4fd869c03854703830dcaac42dd0477"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10200","number":10200,"commit":"c11c2ccc9ca3807e39cfd2125067a02f46f8c86b"}],"number":10272}
buildkite-pr-comment-->

2024-04-09 07:55 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10276)
* Commit: 1831703b4f1260e5ca8ce2f386ff0d97b8d47fff

### Failed CI Steps
* [Check integrations ti_abusech](https://buildkite.com/elastic/integrations/builds/10276#018ec1d7-d7d0-40a5-bbb4-4c668de690a1)

### History
* :green_heart: [Build #10272](https://buildkite.com/elastic/integrations/builds/10272) succeeded 47eb19bd0536878d1c1ef61a495df278aefe4cb0
* :green_heart: [Build #10235](https://buildkite.com/elastic/integrations/builds/10235) succeeded e345529e0e948cf5f9afc1b2a64f4b786d423edc
* :green_heart: [Build #10220](https://buildkite.com/elastic/integrations/builds/10220) succeeded 261fda5829fc0c23cfd83120d017e47a357a0f41
* :green_heart: [Build #10213](https://buildkite.com/elastic/integrations/builds/10213) succeeded 3393bc1be6207769e1a5d15e7818e5909c15110c
* :broken_heart: [Build #10212](https://buildkite.com/elastic/integrations/builds/10212) failed 2db2ca26b4fd869c03854703830dcaac42dd0477
* :broken_heart: [Build #10200](https://buildkite.com/elastic/integrations/builds/10200) failed c11c2ccc9ca3807e39cfd2125067a02f46f8c86b

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10276","number":10276,"commit":"1831703b4f1260e5ca8ce2f386ff0d97b8d47fff"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10272","number":10272,"commit":"47eb19bd0536878d1c1ef61a495df278aefe4cb0"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10235","number":10235,"commit":"e345529e0e948cf5f9afc1b2a64f4b786d423edc"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10220","number":10220,"commit":"261fda5829fc0c23cfd83120d017e47a357a0f41"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10213","number":10213,"commit":"3393bc1be6207769e1a5d15e7818e5909c15110c"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10212","number":10212,"commit":"2db2ca26b4fd869c03854703830dcaac42dd0477"}],"number":10276}
buildkite-pr-comment-->

2024-04-09 08:06 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10277)
* Commit: 9e74308de618f923a3ca9b48e3e574748220c1a1

### Failed CI Steps
* [Check integrations ti_abusech](https://buildkite.com/elastic/integrations/builds/10277#018ec1e2-055b-4d91-a719-56a2ee6bb378)

### History
* :broken_heart: [Build #10276](https://buildkite.com/elastic/integrations/builds/10276) failed 1831703b4f1260e5ca8ce2f386ff0d97b8d47fff
* :green_heart: [Build #10272](https://buildkite.com/elastic/integrations/builds/10272) succeeded 47eb19bd0536878d1c1ef61a495df278aefe4cb0
* :green_heart: [Build #10235](https://buildkite.com/elastic/integrations/builds/10235) succeeded e345529e0e948cf5f9afc1b2a64f4b786d423edc
* :green_heart: [Build #10220](https://buildkite.com/elastic/integrations/builds/10220) succeeded 261fda5829fc0c23cfd83120d017e47a357a0f41
* :green_heart: [Build #10213](https://buildkite.com/elastic/integrations/builds/10213) succeeded 3393bc1be6207769e1a5d15e7818e5909c15110c

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10277","number":10277,"commit":"9e74308de618f923a3ca9b48e3e574748220c1a1"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10276","number":10276,"commit":"1831703b4f1260e5ca8ce2f386ff0d97b8d47fff"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10272","number":10272,"commit":"47eb19bd0536878d1c1ef61a495df278aefe4cb0"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10235","number":10235,"commit":"e345529e0e948cf5f9afc1b2a64f4b786d423edc"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10220","number":10220,"commit":"261fda5829fc0c23cfd83120d017e47a357a0f41"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10213","number":10213,"commit":"3393bc1be6207769e1a5d15e7818e5909c15110c"}],"number":10277}
buildkite-pr-comment-->

2024-04-16 07:49 UTC, chrisberkhout commented on packages/ti_abusech/docs/README.md
> +This integration is for [AbuseCH](https://urlhaus-api.abuse.ch/) logs. It includes the following datasets for retrieving indicators from the AbuseCH API:
Would be better to link to the top level page https://urlhaus.abuse.ch/ now that the `url` data set comes from a [database dump](https://urlhaus.abuse.ch/api/#csv) rather than the API.

2024-04-16 07:49 UTC, chrisberkhout commented on packages/ti_abusech/docs/README.md
> +The AbuseCH URL data_stream retrieves full list of active threat intelligence indicators every interval from the Active Indicators URL API endpoint `https://urlhaus.abuse.ch/downloads/json/`.
Active Indicators URL API endpoint -> Active Indicators URL database dump

2024-04-16 07:49 UTC, chrisberkhout commented on packages/ti_abusech/elasticsearch/transform/latest_malware/transform.yml
> +    delay: 60s
I've seen this set to 120s [elsewhere](https://github.com/search?q=repo%3Aelastic%2Fintegrations%20%22Updated%20to%20120s%20because%20of%20refresh%20delay%20in%20Serverless.%22&type=code), "because of refresh delay in Serverless".

Also for other data streams' transformations.

2024-04-16 08:07 UTC, chrisberkhout requested changes
Perhaps the PR screenshot could be added as an integration screenshot, since it doesn't currently have any.

---

I think it would be good to match the names `expiration_duration` (the field) and `ioc_expiration_duration` (the config option).

---

I think that it's much easier to keep the field definitions in transforms aligned with those in the data streams if the present files match exactly and differences are in a separate file. So, instead of having `labels.is_ioc_transform_source` in `data-stream/foobar/fields/fields.yml` and not in `elasticsearch/transform/latest_foobar/fields/fields.yml`, that field could be in a file called `data-stream/foobar/fields/ioc-transform-source.yml`, which doesn't have a corresponding file in the transform.

For `url`'s `ecs.yml`, it looks like there's changes in the data stream that should also be in the transform:
```
diff data_stream/url/fields/ecs.yml \
     elasticsearch/transform/latest_url/fields/ecs.yml
```
```diff
34,35d33
<   name: threat.indicator.url.fragment
< - external: ecs
53,54d50
< - external: ecs
<   name: labels
```

If you split differences out to separate files, you can check that things are in sync as follows:
```
for ds in malwarebazaar malware threatfox url
do
  echo -e "\n$ds\n";
  colordiff -c999 <(cd data_stream/$ds/fields/; md5sum *) \
                  <(cd elasticsearch/transform/latest_$ds/fields/; md5sum *);
done
```

---

Is it good to remove the fingerprint values for `_id`? The transform will handle de-duplication for the destination index, but for these data sets, there will be many duplicates in the source data streams. On the other hand, there's a performance cost to having those non-unique IDs.

---

The `on_failure` handlers used in many places, such as when setting `threat.indicator.name`, seem generic. I think it'd be better to not have those for the individual processors and instead enhance the `on_failure` at the end of the pipeline. This applies across data streams.

---

The dashboards all have some conditions like this (not part of the diff):
```
"should": [
    {
        "match_phrase": {
            "event.dataset": "ti_abusech.malware"
        }
    },
    {
        "match_phrase": {
            "event.dataset": "ti_abusech.malwarebazaar"
        }
    },
    {
        "match_phrase": {
            "event.dataset": "ti_abusech.url"
        }
    }
]
```
I think that means they're not picking up `ti_abusech.threatfox`, so it'd be good to fix that.

---

Changing `abusech.malwarebazaar.code_sign` from nested to group field seems okay, but it would be good to say in the proposed commit message that it's changed and why. It looks like the choice of nested was intentional, according to:
- https://github.com/elastic/integrations/pull/4102
- https://github.com/elastic/beats/pull/31552

---

It would also be good to extend the proposed commit message to list out other changes that aren't strictly part of the already mentioned IOC expiration support and CEL migration, such as:
-  URL data source change
- `tags` field location
- `threat.indicator.name` added
- some other field changes?

---

I read the related issue and understood that we were considering moving from the API to the data downloads for all data sets, but decided in the end to do it only for URL because the files are too big for the others. Was the benefit of the data downloads that we get a complete data set rather than just recent days?

2024-04-16 17:04 UTC, kcreddy commented on packages/ti_abusech/data_stream/malware/elasticsearch/ingest_pipeline/default.yml
> +        if (dur instanceof String){
Updated as suggested.

2024-04-16 17:04 UTC, kcreddy commented on packages/ti_abusech/data_stream/url/elasticsearch/ingest_pipeline/default.yml
> +        - _temp_
Removed

2024-04-16 17:04 UTC, kcreddy commented on packages/ti_abusech/docs/README.md
> +This integration is for [AbuseCH](https://urlhaus-api.abuse.ch/) logs. It includes the following datasets for retrieving indicators from the AbuseCH API:
updated

2024-04-16 17:04 UTC, kcreddy commented on packages/ti_abusech/docs/README.md
> +The AbuseCH URL data_stream retrieves full list of active threat intelligence indicators every interval from the Active Indicators URL API endpoint `https://urlhaus.abuse.ch/downloads/json/`.
updated as suggested

2024-04-16 17:05 UTC, kcreddy commented on packages/ti_abusech/elasticsearch/transform/latest_malware/transform.yml
> +    delay: 60s
updated to `120s`

2024-04-16 17:06 UTC, kcreddy commented on packages/ti_abusech/data_stream/url/agent/stream/cel.yml.hbs
> +        }),
This change is resulting in failure of system tests, not sure if this can is valid without `message`. Is there any example that uses this?

2024-04-16 17:20 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10487)
* Commit: 408f99c7e9825f33f4ae3d96f362fe1e3f2a4d53

### History
* :green_heart: [Build #10279](https://buildkite.com/elastic/integrations/builds/10279) succeeded 8301fa6b4b73d1b5350c0b07d6d0d99852289168
* :broken_heart: [Build #10277](https://buildkite.com/elastic/integrations/builds/10277) failed 9e74308de618f923a3ca9b48e3e574748220c1a1
* :broken_heart: [Build #10276](https://buildkite.com/elastic/integrations/builds/10276) failed 1831703b4f1260e5ca8ce2f386ff0d97b8d47fff
* :green_heart: [Build #10272](https://buildkite.com/elastic/integrations/builds/10272) succeeded 47eb19bd0536878d1c1ef61a495df278aefe4cb0
* :green_heart: [Build #10235](https://buildkite.com/elastic/integrations/builds/10235) succeeded e345529e0e948cf5f9afc1b2a64f4b786d423edc
* :green_heart: [Build #10220](https://buildkite.com/elastic/integrations/builds/10220) succeeded 261fda5829fc0c23cfd83120d017e47a357a0f41

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10487","number":10487,"commit":"408f99c7e9825f33f4ae3d96f362fe1e3f2a4d53"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10279","number":10279,"commit":"8301fa6b4b73d1b5350c0b07d6d0d99852289168"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10277","number":10277,"commit":"9e74308de618f923a3ca9b48e3e574748220c1a1"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10276","number":10276,"commit":"1831703b4f1260e5ca8ce2f386ff0d97b8d47fff"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10272","number":10272,"commit":"47eb19bd0536878d1c1ef61a495df278aefe4cb0"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10235","number":10235,"commit":"e345529e0e948cf5f9afc1b2a64f4b786d423edc"}],"number":10487}
buildkite-pr-comment-->

2024-04-16 17:33 UTC, kcreddy commented
> Perhaps the PR screenshot could be added as an integration screenshot, since it doesn't currently have any.
I think it would be good to match the names expiration_duration (the field) and ioc_expiration_duration (the config option).

The PR had a dashboard screenshot which shows that 4 datastreams streaming data with `NOT is_ioc_transform_source: true` i.e., on destination indices. I added couple more screenshots showing Expiration Duration now as suggested.

2024-04-16 17:56 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10490)
* Commit: cd4f2c25d895b8de27ee8ea80bf8da25d551a085

### History
* :green_heart: [Build #10487](https://buildkite.com/elastic/integrations/builds/10487) succeeded 408f99c7e9825f33f4ae3d96f362fe1e3f2a4d53
* :green_heart: [Build #10279](https://buildkite.com/elastic/integrations/builds/10279) succeeded 8301fa6b4b73d1b5350c0b07d6d0d99852289168
* :broken_heart: [Build #10277](https://buildkite.com/elastic/integrations/builds/10277) failed 9e74308de618f923a3ca9b48e3e574748220c1a1
* :broken_heart: [Build #10276](https://buildkite.com/elastic/integrations/builds/10276) failed 1831703b4f1260e5ca8ce2f386ff0d97b8d47fff
* :green_heart: [Build #10272](https://buildkite.com/elastic/integrations/builds/10272) succeeded 47eb19bd0536878d1c1ef61a495df278aefe4cb0
* :green_heart: [Build #10235](https://buildkite.com/elastic/integrations/builds/10235) succeeded e345529e0e948cf5f9afc1b2a64f4b786d423edc

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10490","number":10490,"commit":"cd4f2c25d895b8de27ee8ea80bf8da25d551a085"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10487","number":10487,"commit":"408f99c7e9825f33f4ae3d96f362fe1e3f2a4d53"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10279","number":10279,"commit":"8301fa6b4b73d1b5350c0b07d6d0d99852289168"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10277","number":10277,"commit":"9e74308de618f923a3ca9b48e3e574748220c1a1"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10276","number":10276,"commit":"1831703b4f1260e5ca8ce2f386ff0d97b8d47fff"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10272","number":10272,"commit":"47eb19bd0536878d1c1ef61a495df278aefe4cb0"}],"number":10490}
buildkite-pr-comment-->

2024-04-16 23:22 UTC, chrisberkhout commented
> > Perhaps the PR screenshot could be added as an integration screenshot, since it doesn't currently have any.
> > I think it would be good to match the names expiration_duration (the field) and ioc_expiration_duration (the config option).
> 
> The PR had a dashboard screenshot which shows that 4 datastreams streaming data with `NOT is_ioc_transform_source: true` i.e., on destination indices. I added couple more screenshots showing Expiration Duration now as suggested.

Sorry, I meant this as two separate points that are different from what you got.

1) Currently this integration doesn't have screenshots listed under `screenshots:` in `manifest.yml`. Since you took one of the dashboard for the PR, maybe it'd be good to add that file to `img/` and the manifest.

2) In the config there is the option `ioc_expiration_duration`, which defaults to `90d`. That value is later stored in a field called `expiration_duration`. I think it would be good to rename the field to match the name of the config option.

2024-04-17 00:08 UTC, efd6 commented on packages/ti_abusech/data_stream/malware/manifest.yml
> +        description: "Indicator is expired after this duration since its last seen timestamp. Use [Elasticsearch time units](https://www.elastic.co/guide/en/elasticsearch/reference/current/api-conven
```suggestion
        description: "Indicator is expired after this duration since its last seen timestamp. Use [Elasticsearch time units](https://www.elastic.co/guide/en/elasticsearch/reference/current/api-conventions.html#time-units) in days, hours, or minutes (e.g 10d). Default `90d`."
```

2024-04-17 00:08 UTC, efd6 commented on packages/ti_abusech/elasticsearch/transform/latest_malware/fields/fields.yml
> +        Malware familiy.
```suggestion
        Malware family.
```

2024-04-17 00:08 UTC, efd6 commented on packages/ti_abusech/elasticsearch/transform/latest_malware/fields/fields.yml
> +        AV detection ration.
```suggestion
        AV detection ratio.
```

2024-04-17 00:08 UTC, efd6 commented on packages/ti_abusech/elasticsearch/transform/latest_malwarebazaar/fields/ecs.yml
> +  name: threat.indicator.provider
Consistent key ordering?

2024-04-17 00:08 UTC, efd6 commented on packages/ti_abusech/elasticsearch/transform/latest_url/fields/fields.yml
> +    #   type: flattened
TODONE?

2024-04-17 00:08 UTC, efd6 commented on packages/ti_abusech/elasticsearch/transform/latest_url/fields/fields.yml
> +        Indicates whether the malware URL has been reported to the hosting provider (true or false)
```suggestion
        Indicates whether the malware URL has been reported to the hosting provider (true or false).
```

2024-04-17 00:08 UTC, efd6 commented on packages/ti_abusech/elasticsearch/transform/latest_url/fields/fields.yml
> +        A list of tags associated with the queried malware URL
```suggestion
        A list of tags associated with the queried malware URL.
```
(there may be others; perhaps check in the rendered README.md)

2024-04-17 00:09 UTC, efd6 commented on packages/ti_abusech/data_stream/malware/elasticsearch/ingest_pipeline/default.yml
> -  - fingerprint:
Just confirming that this is not needed now since we are doing expiration. Is that correct?

2024-04-17 00:10 UTC, efd6 commented on packages/ti_abusech/data_stream/url/agent/stream/cel.yml.hbs
> +        }),
My expectation is that if the object is not encoded, then the pipeline would still work, but would need to be adjusted to expect an object instead of a string. So removing the `json` processor should make that work. Though note that this breaks the possibility of having an `event.original` since that is a keyword.

2024-04-17 03:48 UTC, chrisberkhout commented on packages/ti_abusech/data_stream/url/agent/stream/cel.yml.hbs
> +        }),
Okay. The main point here was to reduce the JSON encoding/decoding. Currently, it's:
1. CEL: decode whole response
2. CEL: encode event
3. pipeline: decode event

One of those can be avoided, as below, but it's less straightforward than I thought so feel free to keep it the way it is.

```diff
diff --git a/packages/ti_abusech/data_stream/url/agent/stream/cel.yml.hbs b/packages/ti_abusech/data_stream/url/agent/stream/cel.yml.hbs
index 97156db1b..520f9380e 100644
--- a/packages/ti_abusech/data_stream/url/agent/stream/cel.yml.hbs
+++ b/packages/ti_abusech/data_stream/url/agent/stream/cel.yml.hbs
@@ -16,18 +16,21 @@ resource.timeout: {{http_client_timeout}}
 
 resource.url: {{url}}
 program: |
-    request("GET", state.url).with({
-            "Header":{
-                "Content-Type": ["application/zip"],
-            }
-        })
-        .do_request()
-        .as(resp, resp.Body.mime("application/zip").File[0].Data.as(data, bytes(data).decode_json().as(body, {
-        "events": body.map(id, {
-            "message": body[id][0].with({"id": id}).encode_json()
-        }),
-        "url": state.url
-    })))
+    request("GET", state.url)
+        .with({ "Header": { "Content-Type": ["application/zip"] } })
+        .do_request().as(resp,
+            resp.Body.mime("application/zip").File[0].Data.as(data,
+                bytes(data).decode_json().as(body, {
+                    "events": body.map(id,
+                        body[id][0].with({ "id": id }).as(bodywithid, {
+                            "message": bodywithid,
+                            "event": { "original": bodywithid.encode_json() }
+                        })
+                    ),
+                    "url": state.url
+                })
+            )
+        )
 
 redact:
   fields: ~
diff --git a/packages/ti_abusech/data_stream/url/elasticsearch/ingest_pipeline/default.yml b/packages/ti_abusech/data_stream/url/elasticsearch/ingest_pipeline/default.yml
index 29af6d70c..0d0217db3 100644
--- a/packages/ti_abusech/data_stream/url/elasticsearch/ingest_pipeline/default.yml
+++ b/packages/ti_abusech/data_stream/url/elasticsearch/ingest_pipeline/default.yml
@@ -26,11 +26,6 @@ processors:
   ######################
   - rename:
       field: message
-      target_field: event.original
-      ignore_missing: true
-      if: ctx.event?.original == null
-  - json:
-      field: event.original
       target_field: abusech.url
   #####################
   # Threat ECS Fields #
```

2024-04-17 03:58 UTC, chrisberkhout commented on packages/ti_abusech/data_stream/threatfox/agent/stream/cel.yml.hbs
> +        },
The first request will get the default of 3 days of data (although 7 days is the maximum). After the first request it will use this parameter and only get 1 day of data, which is the minimum.

It could be clarified on our end by changing to a `cursor.initial_request: true` flag, setting to `false` after the first request, and setting the request parameter based on that flag.

2024-04-17 04:14 UTC, efd6 commented on packages/ti_abusech/data_stream/threatfox/agent/stream/cel.yml.hbs
> +        },
Yeah, that's what I figured out in the next comment.

2024-04-17 15:17 UTC, kcreddy commented
@chrisberkhout Here are the answers and clarifications to your questions.

> Is it good to remove the fingerprint values for _id?

If we dont remove the fingerprint, then source datastream wouldn't be sent latest update to the indicator and the source datastream will always only contain threat.indicator.first_seen and the transform would always delete based on the first_seen values.

> Changing abusech.malwarebazaar.code_sign from nested to group 

It wasn't changed on purpose. This was probably because of format_version or elastic-package version. I changed it back to nested.

> Was the benefit of the data downloads that we get a complete data set rather than just recent days?

Yes, the datasets were documented to contain only the active circulating indicators seen in last X days (say 90d). So, if we could have used other datasets with full downloads, it would be similar logic as current URL dataset. i.e., for every fetch, we delete the existing indicators and consume full active indicators list again.

2024-04-17 15:35 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10544)
* Commit: c5db5d1ca04c8c5a2b993e1fe23c630ba18e70d7

### History
* :green_heart: [Build #10490](https://buildkite.com/elastic/integrations/builds/10490) succeeded cd4f2c25d895b8de27ee8ea80bf8da25d551a085
* :green_heart: [Build #10487](https://buildkite.com/elastic/integrations/builds/10487) succeeded 408f99c7e9825f33f4ae3d96f362fe1e3f2a4d53
* :green_heart: [Build #10279](https://buildkite.com/elastic/integrations/builds/10279) succeeded 8301fa6b4b73d1b5350c0b07d6d0d99852289168
* :broken_heart: [Build #10277](https://buildkite.com/elastic/integrations/builds/10277) failed 9e74308de618f923a3ca9b48e3e574748220c1a1
* :broken_heart: [Build #10276](https://buildkite.com/elastic/integrations/builds/10276) failed 1831703b4f1260e5ca8ce2f386ff0d97b8d47fff
* :green_heart: [Build #10272](https://buildkite.com/elastic/integrations/builds/10272) succeeded 47eb19bd0536878d1c1ef61a495df278aefe4cb0

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10544","number":10544,"commit":"c5db5d1ca04c8c5a2b993e1fe23c630ba18e70d7"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10490","number":10490,"commit":"cd4f2c25d895b8de27ee8ea80bf8da25d551a085"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10487","number":10487,"commit":"408f99c7e9825f33f4ae3d96f362fe1e3f2a4d53"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10279","number":10279,"commit":"8301fa6b4b73d1b5350c0b07d6d0d99852289168"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10277","number":10277,"commit":"9e74308de618f923a3ca9b48e3e574748220c1a1"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10276","number":10276,"commit":"1831703b4f1260e5ca8ce2f386ff0d97b8d47fff"}],"number":10544}
buildkite-pr-comment-->

2024-04-17 18:20 UTC, kcreddy commented on packages/ti_abusech/elasticsearch/transform/latest_url/fields/fields.yml
> +        A list of tags associated with the queried malware URL
updated and also resolved others in README

2024-04-17 18:20 UTC, kcreddy commented on packages/ti_abusech/elasticsearch/transform/latest_url/fields/fields.yml
> +        Indicates whether the malware URL has been reported to the hosting provider (true or false)
updated

2024-04-17 18:20 UTC, kcreddy commented on packages/ti_abusech/elasticsearch/transform/latest_malwarebazaar/fields/ecs.yml
> +  name: threat.indicator.provider
Ordered

2024-04-17 18:21 UTC, kcreddy commented on packages/ti_abusech/elasticsearch/transform/latest_malware/fields/fields.yml
> +        AV detection ration.
updated

2024-04-17 18:21 UTC, kcreddy commented on packages/ti_abusech/elasticsearch/transform/latest_malware/fields/fields.yml
> +        Malware familiy.
updated

2024-04-17 18:21 UTC, kcreddy commented on packages/ti_abusech/data_stream/malware/manifest.yml
> +        description: "Indicator is expired after this duration since its last seen timestamp. Use [Elasticsearch time units](https://www.elastic.co/guide/en/elasticsearch/reference/current/api-conven
updated

2024-04-17 18:21 UTC, kcreddy commented on packages/ti_abusech/data_stream/url/manifest.yml
> +        description: Interval for polling indicators from AbuseCH data dump. As data dump is generated every 5 minutes, it should be greater than 5 minutes. Default `1h`
updated

2024-04-17 18:21 UTC, kcreddy commented on packages/ti_abusech/data_stream/url/fields/fields.yml
> +    #   type: flattened
removed comment

2024-04-17 18:22 UTC, kcreddy commented on packages/ti_abusech/data_stream/url/_dev/test/pipeline/test-abusechurl-dump.log
> +{"id":"2786903","dateadded":"2024-03-19 11:33:08 UTC","url":"http://27.206.236.188:59429/i","url_status":"online","last_online":"2024-03-19 11:33:08 UTC","threat":"malware_download","tags":["32-bit",
added

2024-04-17 18:22 UTC, kcreddy commented on packages/ti_abusech/data_stream/threatfox/agent/stream/cel.yml.hbs
> +    request("POST", state.url, '{ "query": "get_iocs", "days": ' + ((has(state.cursor) && has(state.cursor.days)) ? state.cursor.days : state.initial_interval) + ' }'
updated and yes thats correct understanding.

2024-04-17 18:22 UTC, kcreddy commented on packages/ti_abusech/data_stream/threatfox/agent/stream/cel.yml.hbs
> +        },
updated as per below suggestion instead: https://github.com/elastic/integrations/pull/7793#discussion_r1568046324

2024-04-17 18:23 UTC, kcreddy commented on packages/ti_abusech/data_stream/malware/manifest.yml
> +    title: AbuseCH Malware payloads using CEL input
Makes sense. Updated to Elastic Agent

2024-04-17 18:23 UTC, kcreddy commented on packages/ti_abusech/_dev/deploy/docker/files/config-threatfox.yml
> +    #request_body: /^\{"query":"get_iocs","days":"[1-7]"\}/
removed comment

2024-04-17 18:23 UTC, kcreddy commented on packages/ti_abusech/data_stream/malware/agent/stream/cel.yml.hbs
> +  fields: ~
moved to above program

2024-04-17 18:23 UTC, kcreddy commented on packages/ti_abusech/data_stream/malware/agent/stream/cel.yml.hbs
> +      {
fixed indentation as per suggestion

2024-04-17 19:16 UTC, kcreddy commented on packages/ti_abusech/data_stream/url/agent/stream/cel.yml.hbs
> +        }),
Added this in [fc71508](https://github.com/elastic/integrations/pull/7793/commits/fc715089fb939b38d7364ae7a3d08dca14262fad)

2024-04-17 19:33 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10555)
* Commit: fc715089fb939b38d7364ae7a3d08dca14262fad

### History
* :green_heart: [Build #10544](https://buildkite.com/elastic/integrations/builds/10544) succeeded c5db5d1ca04c8c5a2b993e1fe23c630ba18e70d7
* :green_heart: [Build #10490](https://buildkite.com/elastic/integrations/builds/10490) succeeded cd4f2c25d895b8de27ee8ea80bf8da25d551a085
* :green_heart: [Build #10487](https://buildkite.com/elastic/integrations/builds/10487) succeeded 408f99c7e9825f33f4ae3d96f362fe1e3f2a4d53
* :green_heart: [Build #10279](https://buildkite.com/elastic/integrations/builds/10279) succeeded 8301fa6b4b73d1b5350c0b07d6d0d99852289168
* :broken_heart: [Build #10277](https://buildkite.com/elastic/integrations/builds/10277) failed 9e74308de618f923a3ca9b48e3e574748220c1a1
* :broken_heart: [Build #10276](https://buildkite.com/elastic/integrations/builds/10276) failed 1831703b4f1260e5ca8ce2f386ff0d97b8d47fff

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10555","number":10555,"commit":"fc715089fb939b38d7364ae7a3d08dca14262fad"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10544","number":10544,"commit":"c5db5d1ca04c8c5a2b993e1fe23c630ba18e70d7"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10490","number":10490,"commit":"cd4f2c25d895b8de27ee8ea80bf8da25d551a085"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10487","number":10487,"commit":"408f99c7e9825f33f4ae3d96f362fe1e3f2a4d53"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10279","number":10279,"commit":"8301fa6b4b73d1b5350c0b07d6d0d99852289168"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10277","number":10277,"commit":"9e74308de618f923a3ca9b48e3e574748220c1a1"}],"number":10555}
buildkite-pr-comment-->

2024-04-17 21:37 UTC, efd6 approved these changes
My concerns have been addressed.

2024-04-18 02:23 UTC, chrisberkhout requested changes
Just one thing left.

Keeping fields in sync between a data stream and a related transform is hard. For example, `elasticsearch/transform/latest_malwarebazaar/fields/fields.yml` didn't get the `group` to `nested` change that was done in `data_stream/malwarebazaar/fields/fields.yml`.

Maybe in the future we can have automated checks, but in the mean time I think it'll be easier to keep definitions in sync if a YAML file of a given name has exactly the same content in the data stream fields directory as it does in a transform fields directory. Definitions that are only used in one place can be in a separate file that only exists in one place.

So the changes are:
- Move the `labels.is_ioc_transform_source` field definitions from `fields.yml` files to separate files (e.g. `is-ioc-transform-source.yml`) that are only placed in the data stream field directories.
- Update the transform `fields.yml` files to match the data stream `fields.yml` files exactly.

What do you think?

2024-04-18 08:01 UTC, kcreddy commented
@chrisberkhout I added the new file `is-ioc-transform-source.yml` as per suggestion and also synced the `fields.yml` files.

2024-04-18 08:05 UTC, chrisberkhout approved these changes

2024-04-18 08:14 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10568)
* Commit: 40c08f73a5685ebdfdf98697936d16eded2df185

### Failed CI Steps
* [Check integrations ti_abusech](https://buildkite.com/elastic/integrations/builds/10568#018ef03d-0fe0-4b1d-916a-4dccee9df3c5)

### History
* :green_heart: [Build #10555](https://buildkite.com/elastic/integrations/builds/10555) succeeded fc715089fb939b38d7364ae7a3d08dca14262fad
* :green_heart: [Build #10544](https://buildkite.com/elastic/integrations/builds/10544) succeeded c5db5d1ca04c8c5a2b993e1fe23c630ba18e70d7
* :green_heart: [Build #10490](https://buildkite.com/elastic/integrations/builds/10490) succeeded cd4f2c25d895b8de27ee8ea80bf8da25d551a085
* :green_heart: [Build #10487](https://buildkite.com/elastic/integrations/builds/10487) succeeded 408f99c7e9825f33f4ae3d96f362fe1e3f2a4d53
* :green_heart: [Build #10279](https://buildkite.com/elastic/integrations/builds/10279) succeeded 8301fa6b4b73d1b5350c0b07d6d0d99852289168
* :broken_heart: [Build #10277](https://buildkite.com/elastic/integrations/builds/10277) failed 9e74308de618f923a3ca9b48e3e574748220c1a1

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10568","number":10568,"commit":"40c08f73a5685ebdfdf98697936d16eded2df185"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10555","number":10555,"commit":"fc715089fb939b38d7364ae7a3d08dca14262fad"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10544","number":10544,"commit":"c5db5d1ca04c8c5a2b993e1fe23c630ba18e70d7"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10490","number":10490,"commit":"cd4f2c25d895b8de27ee8ea80bf8da25d551a085"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10487","number":10487,"commit":"408f99c7e9825f33f4ae3d96f362fe1e3f2a4d53"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10279","number":10279,"commit":"8301fa6b4b73d1b5350c0b07d6d0d99852289168"}],"number":10568}
buildkite-pr-comment-->

2024-04-18 08:51 UTC, kcreddy commented
@chrisberkhout Now I remember why this change was made. The system tests are failing in the CI (and locally) to install the package because the destination index's `code_sign` field is `nested`.
Error:
```
Error: can't install the package: could not zip-install package; API status code = 500; response body = {"statusCode":500,"error":"Internal Server Error","message":"illegal_argument_exception\n\tRoot causes:\n\t\tillegal_argument_exception: cannot have nested fields when index sort is activated"}
```
We do need sort on `@timestamp` field in the destination index. 

In the PR: https://github.com/elastic/beats/pull/31552 it is mentioned that in reality all malwarebazaar samples have only single object inside `code_sign` (although could change in the future). So, the question could be do we really require the nested objects inside `code_sign` to be queried independently of each other using `nested` (or) we okay to relax the requirement on independent querying and thus change the field mapping to `group` inside `fields.yml`. 
I am up for changing it, WDYT?

2024-04-18 12:00 UTC, chrisberkhout commented
> I am up for changing it, WDYT?

@kcreddy That sounds good. When I originally saw it I just thought if we're changing it there should be a reason. This is a good reason. :+1:

2024-04-18 12:38 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10576)
* Commit: 97b7a68dd11227815a4ad69083eced134545130e

### History
* :broken_heart: [Build #10568](https://buildkite.com/elastic/integrations/builds/10568) failed 40c08f73a5685ebdfdf98697936d16eded2df185
* :green_heart: [Build #10555](https://buildkite.com/elastic/integrations/builds/10555) succeeded fc715089fb939b38d7364ae7a3d08dca14262fad
* :green_heart: [Build #10544](https://buildkite.com/elastic/integrations/builds/10544) succeeded c5db5d1ca04c8c5a2b993e1fe23c630ba18e70d7
* :green_heart: [Build #10490](https://buildkite.com/elastic/integrations/builds/10490) succeeded cd4f2c25d895b8de27ee8ea80bf8da25d551a085
* :green_heart: [Build #10487](https://buildkite.com/elastic/integrations/builds/10487) succeeded 408f99c7e9825f33f4ae3d96f362fe1e3f2a4d53

cc @kcreddy

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10576","number":10576,"commit":"97b7a68dd11227815a4ad69083eced134545130e"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10568","number":10568,"commit":"40c08f73a5685ebdfdf98697936d16eded2df185"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10555","number":10555,"commit":"fc715089fb939b38d7364ae7a3d08dca14262fad"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10544","number":10544,"commit":"c5db5d1ca04c8c5a2b993e1fe23c630ba18e70d7"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10490","number":10490,"commit":"cd4f2c25d895b8de27ee8ea80bf8da25d551a085"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10487","number":10487,"commit":"408f99c7e9825f33f4ae3d96f362fe1e3f2a4d53"}],"number":10576}
buildkite-pr-comment-->

2024-04-18 13:17 UTC, merged

2024-04-18 13:31 UTC, elasticmachine commented
Package ti_abusech - 2.0.0 containing this change is available at https://epr.elastic.co/search?package=ti_abusech