[O11y][Golang] Fix descriptions in README.md
elastic/integrations pull request #7850
Opened 2023-09-18 16:11 UTC by harnish-elastic

- Bug

## What does this PR do?

- Fix descriptions in README.md 

## Related issues

- Relates #7239

2023-09-18 16:28 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7850/detail/PR-7850/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7850/detail/PR-7850/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7850/detail/PR-7850/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7850/detail/PR-7850/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_7850.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-09-18T16:01:19.915Z&rangeTo=2023-09-18T16:21:19.915Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=7c95256bebe4d0cab3dfd37872c16622&transactionId=824b307c636682d2)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-09-18T16:11:19.915+0000


* Duration: 17 min 0 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 12  |
| Skipped      | 0 |
| Total        | 12   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-09-18 16:28 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`2/2`) | :green_heart: 
Files | 100.0% (`2/2`) | :green_heart: 3.413
Classes | 100.0% (`2/2`) | :green_heart: 3.413
Methods | 100.0% (`16/16`) | :green_heart: 7.729
Lines | 95.833% (`184/192`) | :+1: 7.526
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-09-21 07:30 UTC, shmsr requested changes

2023-09-21 07:30 UTC, shmsr commented on packages/golang/docs/README.md
> +Metric data streams collected by the Golang integration include [expvar](https://pkg.go.dev/expvar) and [Heap](https://go.dev/src/runtime/mstats.go#:~:text=118%20119%20%2F%2F%20HeapAlloc%20is%20bytes
```suggestion
**Metrics** help you keep a record of the state of the Go (Golang) application.
Metric data streams collected by the Golang integration include [expvar](https://pkg.go.dev/expvar) and [Heap](https://go.dev/src/runtime/mstats.go).
```

Read this:  https://go.dev/doc/faq#:~:text=The%20language%20is%20called%20Go,no%20.dev%20domain%20then.)

Try to use Go instead of Golang because the former is correct when referring to applications written in Go.

2023-09-21 09:56 UTC, harnish-elastic commented on packages/golang/docs/README.md
> +Metric data streams collected by the Golang integration include [expvar](https://pkg.go.dev/expvar) and [Heap](https://go.dev/src/runtime/mstats.go#:~:text=118%20119%20%2F%2F%20HeapAlloc%20is%20bytes
@shmsr Updated, thanks for the information!

2023-09-21 09:59 UTC, shmsr requested changes
nitpick

2023-09-21 09:59 UTC, shmsr commented on packages/golang/_dev/build/docs/README.md
> +Metric data streams collected by the Golang integration include [expvar](https://pkg.go.dev/expvar) and [Heap](https://go.dev/src/runtime/mstats.go).
```suggestion
Metric data streams collected by the Golang integration include [expvar](https://pkg.go.dev/expvar) and [heap](https://go.dev/src/runtime/mstats.go).
```

2023-09-21 09:59 UTC, shmsr commented on packages/golang/changelog.yml
> +    - description: Fix descriptions in README.md.
```suggestion
    - description: Fix description in README.md.
```

2023-09-21 13:39 UTC, shmsr commented on packages/golang/manifest.yml
>  description: This Elastic integration collects metrics from Golang applications.
```suggestion
description: This Elastic integration collects metrics from Go (Golang) applications.
```

2023-09-21 13:40 UTC, shmsr commented
I did a small change i.e., `Golang` to `Go (Golang)` in https://github.com/elastic/integrations/pull/7850/commits/9c4c32bba84ac312bf94788f9d8e51d8e583a38d. Now, the changes LGTM.

2023-09-21 13:40 UTC, shmsr approved these changes

2023-09-25 06:40 UTC, muthu-mps approved these changes

2023-09-25 06:41 UTC, merged

2023-09-25 07:03 UTC, elasticmachine commented
Package golang - 0.4.4 containing this change is available at https://epr.elastic.co/search?package=golang