[Salesforce] Add request timeout parameter in configuration
elastic/integrations pull request #7891
Opened 2023-09-20 13:40 UTC by milan-elastic

- Enhancement

## What does this PR do?

- This PR increases the default timeout 30s to 5m for following datastreams: login-rest, logout-rest, setupaudittrail, apex-rest
- If user by any chance still facing timeout issue then they can increase the timeout from the UI advanced option to get unblocked from timeout issue.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] Verified that increase timeout value to 10m/5m works with the mock server where the default 30s was not working.

## Related issues

- Closes https://github.com/elastic/integrations/issues/7880

## Screenshots

![image](https://github.com/elastic/integrations/assets/118723373/26d2faba-bc8a-4729-91e2-ef736025d8a8)

2023-09-20 13:59 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`6/6`) | :green_heart: 
Files | 100.0% (`6/6`) | :green_heart: 
Classes | 100.0% (`6/6`) | :green_heart: 
Methods | 98.649% (`73/74`) | :+1: 0.649
Lines | 96.281% (`1372/1425`) | :+1: 4.276
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-09-21 04:26 UTC, lalit-satapathy reviewed
Can we verify once that the agent has no issue with this high timeout, when it has to wait for 5mins?

2023-09-21 04:26 UTC, lalit-satapathy commented on packages/salesforce/data_stream/login_rest/manifest.yml
> +        description: Duration before declaring that the HTTP client connection has timed out. Valid time units are s and m. Default is 30s.
Should we mention the default value as 5m.

2023-09-21 05:17 UTC, milan-elastic commented
> Can we verify once that the agent has no issue with this high timeout, when it has to wait for 5mins?

Yes, we have checked with 5min, there are no issues we noticed after setting high timeout.

2023-09-21 05:22 UTC, milan-elastic commented on packages/salesforce/data_stream/login_rest/manifest.yml
> +        description: Duration before declaring that the HTTP client connection has timed out. Valid time units are s and m. Default is 30s.
In the input, we are shipping the 5m by default, but if user will remove the value from input and leave it empty then it will inherit the httpjson default 30s timeout. Hence we mentioned 30s here.

2023-09-21 06:45 UTC, lalit-satapathy approved these changes
LGTM

2023-09-21 06:50 UTC, shmsr requested changes
Left a few comments.

2023-09-21 06:50 UTC, shmsr commented on packages/salesforce/data_stream/apex/manifest.yml
> +        description: Duration before declaring that the HTTP client connection has timed out. Valid time units are s and m. Default is 30s.
```suggestion
        description: Duration before declaring that the HTTP client connection has timed out. Valid time units are `s` (seconds) and `m` (minutes). The default is 30s.
```

2023-09-21 06:50 UTC, shmsr commented on packages/salesforce/data_stream/login_rest/manifest.yml
> +        description: Duration before declaring that the HTTP client connection has timed out. Valid time units are s and m. Default is 30s.
```suggestion
        description: Duration before declaring that the HTTP client connection has timed out. Valid time units are `s` (seconds) and `m` (minutes). The default is 30s.
```

2023-09-21 06:50 UTC, shmsr commented on packages/salesforce/data_stream/login_rest/manifest.yml
> +        description: Duration before declaring that the HTTP client connection has timed out. Valid time units are s and m. Default is 30s.
Can you also make similar changes in other *.yml?

2023-09-21 06:50 UTC, shmsr commented on packages/salesforce/data_stream/login_rest/manifest.yml
> +        description: Duration before declaring that the HTTP client connection has timed out. Valid time units are s and m. Default is 30s.
As `show_user` is false, I think this won't even matter to most because only a few advanced users might be playing with `request_timeout`. As default, it'd be 5m, right? Perhaps you can mention if left empty, then `request_timeout` is 30s. What do you think?

2023-09-21 06:50 UTC, shmsr commented on packages/salesforce/_dev/build/docs/README.md
> +In `Apex`, `Login Rest`, `Logout Rest`, or `SetupAuditTrail` datastreams, if the response is getting delayed from the Salesforce server side due to any reason then the following error might occur.
```suggestion
In `Apex`, `Login Rest`, `Logout Rest`, or `SetupAuditTrail` datastreams, if the response is getting delayed from the Salesforce server side due to any reason then the following error might occur:
```

2023-09-21 06:50 UTC, shmsr commented on packages/salesforce/data_stream/apex/manifest.yml
> +        title: Request Timeout
```suggestion
        title: Request timeout
```

As other fields are in "sentence case" I'd suggest this ^^ and "proper case" is being currently used here. Can you make similar changes in README as well as other *.yml

2023-09-21 09:46 UTC, shmsr reviewed
Just a couple more nitpicks

2023-09-21 09:46 UTC, shmsr commented on packages/salesforce/docs/README.md
> +In this case, consider increasing `Request Timeout` configuration from `Advanced options` section of that data stream.
```suggestion
In this case, consider increasing `Request timeout` configuration from `Advanced options` section of that data stream.
```

2023-09-21 09:46 UTC, shmsr commented on packages/salesforce/_dev/build/docs/README.md
> +In this case, consider increasing `Request Timeout` configuration from `Advanced options` section of that data stream.
```suggestion
In this case, consider increasing `Request timeout` configuration from `Advanced options` section of that data stream.
```

2023-09-21 10:16 UTC, shmsr approved these changes

2023-09-21 11:45 UTC, merged

2023-09-21 13:10 UTC, elasticmachine commented
Package salesforce - 0.10.1 containing this change is available at https://epr.elastic.co/search?package=salesforce