Documentation fix darasteam instead of datastream on Prometheus page
elastic/integrations pull request #7914
Opened 2023-09-21 09:47 UTC by limistah

## What does this PR do?
The page https://docs.elastic.co/integrations/prometheus#dashboard states:

> Prometheus integration is shipped including default overview dashboard. Default dashboard works only for remote_write datastream and collector `darastream`, if metrics are scraped from the Prometheus server metrics endpoint.

The `darastream` should be `datastream` and read like

> Prometheus integration is shipped including default overview dashboard. Default dashboard works only for remote_write datastream and collector `datastream`, if metrics are scraped from the Prometheus server metrics endpoint.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [X] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Screenshots
![image](https://github.com/elastic/integrations/assets/30846935/71328161-a743-45c9-bbdb-244521debeeb)

2023-09-21 20:55 UTC, limistah commented
/test

2023-09-22 18:49 UTC, limistah commented
`/test`

2023-09-28 16:08 UTC, constanca-m approved these changes

2023-09-29 08:23 UTC, gizas approved these changes

2023-10-05 20:37 UTC, limistah commented
The CI keeps failing, this is a typo fix. I'm not sure if I am doing anything wrong to cause the CI to fail. Can someone help?

2023-11-18 04:54 UTC, limistah commented
👍🏾

2023-11-18 05:37 UTC, limistah commented
Hi @tetianakravchenko 

Your review is pending on this PR

Thanks

2023-12-18 08:22 UTC, limistah commented
👍🏾

2023-12-18 08:56 UTC, tetianakravchenko approved these changes

2023-12-21 09:44 UTC, mrodm commented
Hi @limistah, please update your branch with the latest contents from main branch. There was an important PR merged updating the CI pipelines. Thanks!

2023-12-22 11:35 UTC, limistah commented
Hi @mrodm I have updated the PR

Thank you for the info

2024-01-21 14:50 UTC, limistah commented
👍

2024-01-21 19:45 UTC, shmsr approved these changes

2024-01-21 19:45 UTC, shmsr commented on packages/prometheus/changelog.yml
> +    - description: Typo Fix darastream instead of datastream
```suggestion
    - description: Fix typo: Replace "darastream" with "datastream"
```

2024-01-21 19:47 UTC, shmsr requested changes
Left one comment.

2024-01-21 20:18 UTC, shmsr approved these changes

2024-01-21 20:18 UTC, shmsr commented
@limistah Thanks for your contribution!

2024-01-21 20:20 UTC, shmsr commented on packages/prometheus/changelog.yml
> +    - description: 'Fix typo: Replace "darastream" with "datastream"'
```suggestion
    - description: Fix typo: Replace "darastream" with "datastream"
```

2024-01-21 20:20 UTC, shmsr commented on packages/prometheus/changelog.yml
> +    - description: 'Fix typo: Replace "darastream" with "datastream"'
remove single quotes

2024-01-21 20:21 UTC, shmsr approved these changes
Thanks for your contribution @limistah!

2024-03-07 12:46 UTC, aliabbas-elastic commented
@limistah Can you resolve the conflicts here?

2024-03-07 12:48 UTC, aliabbas-elastic requested changes

2024-03-07 12:48 UTC, aliabbas-elastic commented on packages/prometheus/changelog.yml
> +- version: "1.14.0"
```suggestion
- version: "1.14.1"
```
As this is a minor fix in documentation bumping the patch version would suffice.

2024-04-08 05:48 UTC, ishleenk17 commented
@limistah : Please fix the comments. We can then retrigger the build and commit the change

2024-05-08 06:48 UTC, ishleenk17 commented
@limistah : Lets take this PR forward!

2024-05-08 09:41 UTC, aliabbas-elastic commented
@limistah Please also bump up the `manifest.yml` version as well

2024-05-08 10:11 UTC, limistah commented
> @limistah Please also bump up the `manifest.yml` version as well

Done with this commit https://github.com/elastic/integrations/pull/7914/commits/70c889566ac399b1d7920205c9478592e72dc4b4

2024-05-08 10:12 UTC, aliabbas-elastic commented
/test

2024-05-08 10:13 UTC, aliabbas-elastic approved these changes
LGTM

2024-05-08 10:22 UTC, aliabbas-elastic commented on packages/prometheus/docs/README.md
> +
Maybe this is causing the build failure. Can you run once `elastic-package build` and `elastic-package check` once?

2024-05-08 15:20 UTC, limistah commented on packages/prometheus/docs/README.md
> +
There was a marshal error with the changelog.yml file. I have fixed this.

<img width="1085" alt="image" src="https://github.com/elastic/integrations/assets/30846935/74614646-c12a-44c5-a11c-2d591f161cbe">

2024-05-08 15:24 UTC, aliabbas-elastic commented
/test

2024-05-08 15:39 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/11279)
* Commit: 654c71c53e5fff4f0363e577e5ae0b05e3ea24ab

### History
* :broken_heart: [Build #11258](https://buildkite.com/elastic/integrations/builds/11258) failed 70c889566ac399b1d7920205c9478592e72dc4b4

cc @limistah

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11279","number":11279,"commit":"654c71c53e5fff4f0363e577e5ae0b05e3ea24ab"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11258","number":11258,"commit":"70c889566ac399b1d7920205c9478592e72dc4b4"}],"number":11279}
buildkite-pr-comment-->

2024-05-08 16:15 UTC, aliabbas-elastic approved these changes
LGTM

2024-05-08 16:15 UTC, merged

2024-05-08 16:49 UTC, elasticmachine commented
Package prometheus - 1.15.2 containing this change is available at https://epr.elastic.co/search?package=prometheus