[System] Remove linux-only field mappings from diskio, memory datastr…
elastic/integrations pull request #7941
Opened 2023-09-22 12:22 UTC by ritalwar

- Bug

## What does this PR do?

This PR eliminates field mappings for Linux-specific metrics that were removed from the beats, as seen in this [PR](https://github.com/elastic/beats/pull/28292). It also revises the documentation to exclude these fields since they are no longer supported, and their presence in our documentation has been causing confusion.

Please note that all of these metrics are duplicated in the Linux module, and users have the option to use Linux integrations for the same metrics.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Closes #7935

## Screenshots

<img width="1208" alt="Screenshot 2023-09-22 at 5 52 05 PM" src="https://github.com/elastic/integrations/assets/102972658/e008107f-f9f0-48d5-bbdb-f1015f85b211">
<img width="1655" alt="Screenshot 2023-09-22 at 5 52 20 PM" src="https://github.com/elastic/integrations/assets/102972658/d8732aeb-063b-401f-97b4-54ad90bc27fb">

2023-09-22 12:39 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7941/detail/PR-7941/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7941/detail/PR-7941/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7941/detail/PR-7941/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7941/detail/PR-7941/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_7941.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-09-22T12:13:02.466Z&rangeTo=2023-09-22T12:33:02.466Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=01ab0c48e2f681e025b1306bfc8beb55&transactionId=17cebfdb62d92e3e)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-09-22T12:23:02.466+0000


* Duration: 16 min 26 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 151  |
| Skipped      | 0 |
| Total        | 151   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-09-22 12:39 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`3/3`) | :green_heart: 
Files | 100.0% (`4/4`) | :green_heart: 29.412
Classes | 100.0% (`4/4`) | :green_heart: 29.412
Methods | 63.415% (`52/82`) | :+1: 6.596
Lines | 99.863% (`2924/2928`) | :+1: 59.903
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-09-22 14:54 UTC, shmsr requested changes
I haven't done a thorough review yet. For now, left a few comments. I'll try to do a thorough review ASAP.

2023-09-22 14:54 UTC, shmsr commented on packages/system/changelog.yml
> +    - description: Remove linux-only field mappings from diskio, memory datastreams.
```suggestion
    - description: Remove Linux-only field mappings from diskio and memory datastreams.
```

2023-09-22 14:54 UTC, shmsr commented on packages/system/docs/README.md
> +
```suggestion
```

2023-09-22 14:54 UTC, shmsr commented on packages/system/data_stream/diskio/fields/fields.yml
> +        The total number of of milliseconds spent doing I/Os.
```suggestion
        Total time spent in doing I/Os in milliseconds.
```

I see there are multiple definitions where "total number of milliseconds" (e.g., total number of a unit of time) is used which is incorrect. If there are only a few errors like this perhaps we can take it up in this PR. If not, create another PR with the fixes.

2023-09-22 14:54 UTC, shmsr commented on packages/system/_dev/build/docs/README.md
> +> Note: For retrieving Linux-specific diskio metrics, use the [Linux](https://docs.elastic.co/integrations/linux) integration.
```suggestion
> Note: For retrieving Linux-specific disk I/O metrics, use the [Linux](https://docs.elastic.co/integrations/linux) integration.
```

2023-09-22 14:54 UTC, shmsr commented on packages/system/_dev/build/docs/README.md
> +
```suggestion
```

2023-09-22 15:20 UTC, ritalwar commented on packages/system/data_stream/diskio/fields/fields.yml
> +        The total number of of milliseconds spent doing I/Os.
I'd prefer not to make changes to any other field in this PR to keep things clean.
Maybe we should create a backlog issue for these errors. Can you do that?

2023-09-22 17:22 UTC, ishleenk17 commented
@ritalwar : In general removal of fields is treated as a breaking change since the customers might have build some viisualizations, queries on it. 
Please see how are such scenarios handled from customer perpective.

Also, since this is a breaking change, this should not be categorized under just a bugfix

2023-09-22 17:54 UTC, ritalwar commented
> In general removal of fields is treated as a breaking change since the customers might have build some viisualizations, and queries on it. Please see how are such scenarios handled from the customer perspective.
> Also, since this is a breaking change, this should not be categorized under just a bugfix

The breaking change was introduced in the 8.0 version of the Beats system module through this [PR](https://github.com/elastic/beats/pull/28292). The system integration relies on the beats input `system/metrics`, and the behavior has remained consistent across integrations. These specific fields have not been supported since version 8.0; however, they were not removed from the integrations and appeared in the exported fields. This situation created confusion for users.
All details are in the PR description and the issue itself. If you have any further questions, feel free to ask. 

Additionally, I verified that none of these fields were being used in any visualizations.

2023-09-24 15:36 UTC, shmsr commented on packages/system/data_stream/diskio/fields/fields.yml
> +        The total number of of milliseconds spent doing I/Os.
#7950

2023-09-26 06:20 UTC, shmsr approved these changes

2023-09-26 09:23 UTC, ishleenk17 approved these changes
Looks good!

2023-09-26 10:24 UTC, P1llus approved these changes
Just a small nit, but else its fine :)

2023-09-26 10:24 UTC, P1llus commented on packages/system/changelog.yml
> +- version: "1.38.3"
Could we bump the minor rather than the hotfix? A bit unsure if this is categorized as a bugfix rather than an enhancement?

2023-09-26 10:35 UTC, ritalwar commented on packages/system/changelog.yml
> +- version: "1.38.3"
@muthu-mps Thoughts?

2023-09-26 10:41 UTC, ishleenk17 commented
> Also, since this is part of a breaking change, this should not be categorized under just a bugfix

I agree to @P1llus , as pointed out in my above comment, since this involves the removal of fields, we should not categorize it as a bugfix, but enhancement.

2023-09-26 10:59 UTC, muthu-mps commented on packages/system/changelog.yml
> +- version: "1.38.3"
@P1llus 
We have created an internal guidelines on the changelog entries. In which the changes like logo updates, documentation updates etc... would go as a patch release instead of minor release. Still there is a catch when we update the patch it should not be of `type: bugfix`. Probably for this PR it could be minor bump as we remove the fields from the datastream.

2023-09-26 11:44 UTC, lalit-satapathy commented
>The breaking change was introduced in the 8.0 version of the Beats system module through this https://github.com/elastic/beats/pull/28292.

None of these removed fields, are populated during a Linux run?

2023-09-26 11:46 UTC, lalit-satapathy commented on packages/system/changelog.yml
> +    - description: Remove linux-only field mappings from diskio and memory datastreams.
Should we mention that these fields are not populated and are being removed from the documentation.

2023-09-26 13:13 UTC, ritalwar commented on packages/system/changelog.yml
> +    - description: Remove linux-only field mappings from diskio and memory datastreams.
updated.

2023-09-26 13:15 UTC, ritalwar commented on packages/system/changelog.yml
> +- version: "1.38.3"
I made a minor version bump and updated its type to "enhancement."

2023-09-27 07:08 UTC, ritalwar commented
> > The breaking change was introduced in the 8.0 version of the Beats system module through this [elastic/beats#28292](https://github.com/elastic/beats/pull/28292).
> 
> None of these removed fields, are populated during a Linux run?

Yes, there is no data being received for these fields.

2023-09-27 07:23 UTC, lalit-satapathy commented
LGTM

2023-09-27 07:24 UTC, merged