Update AWS package to use latest package-spec version
elastic/integrations pull request #7958
Opened 2023-09-25 09:49 UTC by tommyers-elastic

## What does this PR do?

Update AWS package to use latest package-spec version. This is preparation for serverless.

This brings with it some additional validations on duplicate fields - which is why many fields appear to have been removed from `ecs.yaml` files. All these fields are duplicated.

Some fields have been removed from package spec entirely - like `release` in the field definition (it's still present in the dataset level manifest). 

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

2023-09-25 10:01 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7958/detail/PR-7958/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7958/detail/PR-7958/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7958/detail/PR-7958/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7958/detail/PR-7958/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_7958.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-09-25T09:39:40.897Z&rangeTo=2023-09-25T09:59:40.897Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=38d53fd238d2499e1d0d3a7638ae0e9a&transactionId=94887f7884020dbf)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-09-25T09:49:40.897+0000


* Duration: 12 min 56 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![4](https://img.shields.io/badge/4%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-7958/detail/PR-7958/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Check integration: aws`
<ul>
<li>Took 0 min 4 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-7958/runs/1/steps/1162/log/?start=0">here</a></li>
<li>Description: <code>../../build/elastic-package check -v</code></l1>
</ul>
  
  
  
  
##### `Take down the Elastic stack`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-7958/runs/1/steps/1181/log/?start=0">here</a></li>
<li>Description: <code>build/elastic-package stack down -v</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-7958/runs/1/steps/1201/log/?start=0">here</a></li>

</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-7958/runs/1/steps/1214/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-09-25 10:44 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 
Classes | 100.0% (`0/0`) | :green_heart: 
Methods | 100.0% (`40/40`) | :green_heart: 8.333
Lines | 100.0% (`0/0`) | :green_heart: 
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-09-25 20:08 UTC, kaiyan-sheng commented on packages/aws/manifest.yml
> +version: 2.4.0
Just curious is this change big enough to bump the version to 3.0.0 by chance?

2023-09-25 20:39 UTC, taylor-swanson requested changes

2023-09-25 20:39 UTC, taylor-swanson commented on packages/aws/manifest.yml
We added a new field to package-spec to mark the owner type of the package. It was introduced in 2.11.0 and assumes a default of `community` in 2.11.0, but we decided we didn't like that behavior, so we made it required in 3.0.0. Please add the following:

```diff
 owner:
   github: elastic/obs-cloud-monitoring
+  type: elastic
```

More info on owner type tagging: #6569

2023-09-26 07:52 UTC, tommyers-elastic commented on packages/aws/manifest.yml
> +version: 2.4.0
the changes in this PR should result in no behaviour changes at all in the package. i don't think it warrants a major version bump for the package.

2023-09-26 07:53 UTC, tommyers-elastic commented on packages/aws/manifest.yml
thanks for the heads up !

2023-09-26 12:56 UTC, taylor-swanson approved these changes

2023-09-26 15:57 UTC, kaiyan-sheng approved these changes

2023-09-28 15:13 UTC, kaiyan-sheng reviewed
Based on https://github.com/elastic/package-spec/pull/567 kibana.version is equal or greater to 8.10.0?

2023-09-29 14:50 UTC, tommyers-elastic commented
closing since this is being addressed in another PR

2023-09-29 14:50 UTC, closed without merging