[Security]  Add security detection engine package
elastic/integrations pull request #797
Opened 2021-03-22 19:22 UTC by rw-access

## What does this PR do?

Added an integration that contains `security_rule` assets to be used by the Detection Engine in Security. The core idea behind this effort is to use Fleet to update rules for the Detection Engine between releases. This way, users can get the latest released rules and package-relevant rules without needing to wait  for the next stack release.

See the "related issues" section or ping me for more context. I'll be happy to point to additional (internal) design docs and discussions.

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them. (have not tested the package using `elastc-package` yet)
- [ ] ~I have verified that all data streams collect metrics or logs.~
- [ ] I have added an entry to my package's `changelog.yml` file.

## Author's Checklist

We've had a lot of conversations between teams, so I think we're in alignment. The name of the integration is TBD,  and the specifics to install the `security_rule` asset type are also undecided.

## How to test this PR locally

There is a chicken-and-egg issue here. Since it contains a brand new asset type, Kibana doesn't yet know how to install it. So the package will be published first as a pre-release and once this merges and is added to package-storage, then we can start developing the Kibana side to install the package.

There will be more iteration as we go between all of the repositories.

## Related issues

*https://github.com/elastic/package-spec/pull/142: Add `security_rule` asset type
* https://github.com/elastic/package-spec/pull/151: Add `NOTICE.txt` file
* https://github.com/elastic/package-storage/pull/843: Original package for this to power 
* https://github.com/elastic/kibana/pull/91949: Now closed, initially pulled in https://github.com/elastic/package-storage/pull/843, but our design has changed so that EPM will publish the rules as saved objects to an intermediate staging area

## Screenshots

None yet

2021-03-22 19:30 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-797/detail/PR-797/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-797/detail/PR-797/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-797/detail/PR-797/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-797/detail/PR-797/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_797.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #797 opened`



* Start Time: 2021-03-22T19:22:24.013+0000


* Duration: 8 min 2 sec


* Commit: 5b7033134542f7f689732ad221b2367c21a21fad




#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/PR-797/buildTimeGraph/png)



</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->









### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-797/detail/PR-797/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Check integration: security_detection_engine`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-797/runs/1/steps/387/log/?start=0">here</a></li>
<li>Description: <code>../../build/elastic-package check -v</code></l1>
</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-03-22T19:30:02.354Z] go: downloading github.com/AlecAivazis/survey/v2 v2.1.1
[2021-03-22T19:30:02.354Z] go: downloading github.com/elastic/go-ucfg v0.8.4-0.20200415140258-1232bd4774a6
[2021-03-22T19:30:02.354Z] go: downloading github.com/spf13/cobra v1.0.0
[2021-03-22T19:30:02.354Z] go: downloading github.com/elastic/package-spec/code/go v0.0.0-20210310145052-baee4c3da9cc
[2021-03-22T19:30:02.354Z] go: downloading github.com/cespare/xxhash v1.1.0
[2021-03-22T19:30:02.354Z] go: downloading github.com/go-git/go-billy/v5 v5.0.0
[2021-03-22T19:30:02.354Z] go: downloading github.com/go-git/go-git/v5 v5.1.0
[2021-03-22T19:30:02.354Z] go: downloading github.com/cespare/xxhash/v2 v2.1.1
[2021-03-22T19:30:02.354Z] go: downloading github.com/elastic/go-elasticsearch/v7 v7.9.0
[2021-03-22T19:30:02.354Z] go: downloading github.com/google/go-github/v32 v32.1.0
[2021-03-22T19:30:02.354Z] go: downloading gopkg.in/yaml.v3 v3.0.0-20200615113413-eeeca48fe776
[2021-03-22T19:30:02.354Z] go: downloading github.com/aymerick/raymond v2.0.2+incompatible
[2021-03-22T19:30:02.354Z] go: downloading github.com/magefile/mage v1.11.0
[2021-03-22T19:30:02.354Z] go: downloading golang.org/x/crypto v0.0.0-20200820211705-5c72a883971a
[2021-03-22T19:30:02.354Z] go: downloading github.com/kballard/go-shellquote v0.0.0-20180428030007-95032a82bc51
[2021-03-22T19:30:02.354Z] go: downloading gopkg.in/yaml.v2 v2.4.0
[2021-03-22T19:30:02.354Z] go: downloading github.com/jedib0t/go-pretty v4.3.0+incompatible
[2021-03-22T19:30:02.354Z] go: downloading github.com/mgutz/ansi v0.0.0-20200706080929-d51e80ef957d
[2021-03-22T19:30:02.354Z] go: downloading github.com/Masterminds/semver v1.5.0
[2021-03-22T19:30:02.354Z] go: downloading github.com/xeipuuv/gojsonschema v1.2.0
[2021-03-22T19:30:02.616Z] go: downloading golang.org/x/sys v0.0.0-20210119212857-b64e53b001e4
[2021-03-22T19:30:02.616Z] go: downloading github.com/google/go-querystring v1.0.0
[2021-03-22T19:30:02.616Z] go: downloading golang.org/x/text v0.3.3
[2021-03-22T19:30:02.616Z] go: downloading golang.org/x/oauth2 v0.0.0-20200902213428-5d25da1a8d43
[2021-03-22T19:30:02.616Z] go: downloading github.com/Masterminds/semver/v3 v3.1.0
[2021-03-22T19:30:02.616Z] go: downloading github.com/jbenet/go-context v0.0.0-20150711004518-d14ea06fba99
[2021-03-22T19:30:02.616Z] go: downloading github.com/kylelemons/godebug v1.1.0
[2021-03-22T19:30:02.616Z] go: downloading github.com/emirpasic/gods v1.12.0
[2021-03-22T19:30:02.616Z] go: downloading github.com/spf13/pflag v1.0.5
[2021-03-22T19:30:02.616Z] go: downloading github.com/creasty/defaults v1.5.1
[2021-03-22T19:30:02.616Z] go: downloading github.com/kevinburke/ssh_config v0.0.0-20190725054713-01f96b0aa0cd
[2021-03-22T19:30:02.616Z] go: downloading golang.org/x/net v0.0.0-20201021035429-f5854403a974
[2021-03-22T19:30:02.616Z] go: downloading github.com/imdario/mergo v0.3.11
[2021-03-22T19:30:02.616Z] go: downloading github.com/mitchellh/go-homedir v1.1.0
[2021-03-22T19:30:02.616Z] go: downloading github.com/mattn/go-colorable v0.1.7
[2021-03-22T19:30:02.616Z] go: downloading github.com/go-git/gcfg v1.5.0
[2021-03-22T19:30:02.616Z] go: downloading github.com/xanzy/ssh-agent v0.2.1
[2021-03-22T19:30:02.616Z] go: downloading github.com/mattn/go-isatty v0.0.12
[2021-03-22T19:30:02.616Z] go: downloading github.com/go-openapi/strfmt v0.19.6
[2021-03-22T19:30:02.616Z] go: downloading gopkg.in/warnings.v0 v0.1.2
[2021-03-22T19:30:02.616Z] go: downloading github.com/mattn/go-runewidth v0.0.9
[2021-03-22T19:30:02.616Z] go: downloading go.mongodb.org/mongo-driver v1.0.3
[2021-03-22T19:30:02.616Z] go: downloading github.com/mitchellh/mapstructure v1.1.2
[2021-03-22T19:30:02.616Z] go: downloading github.com/sergi/go-diff v1.1.0
[2021-03-22T19:30:02.616Z] go: downloading github.com/xeipuuv/gojsonreference v0.0.0-20180127040603-bd5ef7bd5415
[2021-03-22T19:30:02.616Z] go: downloading github.com/rakyll/statik v0.1.7
[2021-03-22T19:30:02.877Z] go: downloading github.com/xeipuuv/gojsonpointer v0.0.0-20190905194746-02993c407bfb
[2021-03-22T19:30:02.877Z] go: downloading github.com/asaskevich/govalidator v0.0.0-20190424111038-f61b66f89f4a
[2021-03-22T19:30:02.877Z] go: downloading github.com/go-openapi/errors v0.19.2
[2021-03-22T19:30:03.138Z] go: downloading github.com/go-stack/stack v1.8.0
[2021-03-22T19:30:18.191Z] Running in /var/lib/jenkins/workspace/gest-manager_integrations_PR-797/src/github.com/elastic/integrations/packages/security_detection_engine
[2021-03-22T19:30:18.516Z] + ../../build/elastic-package check -v
[2021-03-22T19:30:18.516Z] elastic-package has been installed.
[2021-03-22T19:30:18.516Z] 2021/03/22 19:30:18 DEBUG Enable verbose logging
[2021-03-22T19:30:18.516Z] Format the package
[2021-03-22T19:30:18.516Z] Error: checking package failed: formatting the integration failed (path: /var/lib/jenkins/workspace/gest-manager_integrations_PR-797/src/github.com/elastic/integrations/packages/security_detection_engine, failFast: true): walking through the integration files failed: formatting file failed (path: /var/lib/jenkins/workspace/gest-manager_integrations_PR-797/src/github.com/elastic/integrations/packages/security_detection_engine/kibana/security_rule/rule-000047bb-b27a-47ec-8b62-ef1a5d2c9e19.json): file is not formatted (path: /var/lib/jenkins/workspace/gest-manager_integrations_PR-797/src/github.com/elastic/integrations/packages/security_detection_engine/kibana/security_rule/rule-000047bb-b27a-47ec-8b62-ef1a5d2c9e19.json)
[2021-03-22T19:30:18.606Z] Running in /var/lib/jenkins/workspace/gest-manager_integrations_PR-797/src/github.com/elastic/integrations
[2021-03-22T19:30:18.653Z] Archiving artifacts
[2021-03-22T19:30:18.953Z] ‘build/ [...]

2021-03-23 09:33 UTC, mtojek requested changes
I didn't review JSON files, as I don't have domain knowledge here and can't verify them thoroughly.

Please merge the latest master to load the latest dependency on elastic-package (it should start accepting new Kibana types).

Before merging this PR we need to make sure the PR is green.

2021-03-23 09:33 UTC, mtojek commented on packages/security_detection_engine/changelog.yml
> +- version: "0.0.1" # 0.0.1-dev.1 fails validation
@ycombinator 

In terms of potential release tags - do you think we should improve the spec here?

2021-03-23 09:33 UTC, mtojek commented on packages/security_detection_engine/manifest.yml
> +  github: elastic/protections
FYI: This team should have "write" or "maintainer" permissions to the elastic/package-storage. It's for sending notifications about waiting PRs.

2021-03-23 13:54 UTC, ycombinator commented on packages/security_detection_engine/changelog.yml
> +- version: "0.0.1" # 0.0.1-dev.1 fails validation
Yep, we should make the version pattern allowed in changelog [versions](https://github.com/elastic/package-spec/blob/63e8131ff323c35d756cab2cf062f094106a0de0/versions/1/changelog.spec.yml#L14) the same as the one allowed in package manifest [versions](https://github.com/elastic/package-spec/blob/63e8131ff323c35d756cab2cf062f094106a0de0/versions/1/manifest.spec.yml#L127). Even better would be to share the same pattern for both version definitions. I am making a PR to `package-spec` now to address this inconsistency.

2021-03-23 15:15 UTC, rw-access commented on packages/security_detection_engine/changelog.yml
> +- version: "0.0.1" # 0.0.1-dev.1 fails validation
thanks! i'll try that out

2021-03-23 15:19 UTC, rw-access commented on packages/security_detection_engine/manifest.yml
> +  github: elastic/protections
thanks. what do you think is the ideal team to put in this field?
most likely, `@elastic/protections` or `@elastic/security-intelligence-analytics` will be the team thats publishing this package and the stewards of it. but if the intention of this field is something different, then i'll gladly update

2021-03-23 17:29 UTC, rw-access commented on packages/security_detection_engine/changelog.yml
> +- version: "0.0.1" # 0.0.1-dev.1 fails validation
updated deps in c4745655dfe856ae47278df0283cd92fa96d8300

2021-03-23 19:28 UTC, ycombinator commented on go.mod
> +	gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b // indirect
Could you remove all the indirect dependencies and run `go mod tidy`? It should cut down the size of `go.mod` and `go.sum` significantly.

2021-03-23 19:36 UTC, ycombinator commented on packages/security_detection_engine/manifest.yml
> +  github: elastic/protections
Eventually this package will need to be served up by the Elastic Package Registry. Packages that are to be served by the Elastic Package Registry are stored in the https://github.com/elastic/package-storage repository in one of its three branches (depending on their stability): `snapshot`, `staging`, or `production`.

When this PR is merged, the CI job for the `master` branch of this repo (`elastic/integrations`) will detect that this package version (`security_detection_engine 1.0.0`) does not exist in any of the three branches of the `package-storage` repository and automatically create a PR to the `snapshot` branch of the `package-storage` repository. The team that is specified in this field (`owner.github`) will get pinged on that PR so they know to review it and, if it looks good, merge it.

So it should be a team who would be best fit to review changes to this package and approve new versions of it being added to the Elastic Package Registry.

2021-03-24 20:40 UTC, rw-access commented on packages/security_detection_engine/manifest.yml
> +  github: elastic/protections
Had a few conversations and figured out the most relevant owner. Updated in 3610bcd711e8ab660e8df076d2fa1c59337fdb30

2021-03-24 20:45 UTC, rw-access commented on go.mod
> +	gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b // indirect
Fixed in a8aa2286deef30932ca8bda7c61969e35ee09707

2021-03-24 21:28 UTC, ycombinator approved these changes
LGTM.

2021-03-25 07:55 UTC, ruflin commented on go.mod
> +	github.com/elastic/elastic-package v0.0.0-20210324160257-57698a40f3e3
Could you pull this go mod change into a speparate PR?

2021-03-25 08:24 UTC, mtojek commented
Hm... I spotted some weird issue:

```
[2021-03-24T21:22:19.014Z] Error: checking package failed: linting package failed: found 3 validation errors:
[2021-03-24T21:22:19.014Z]    1. item [test-audit.log-config.json] is not allowed in folder [/var/lib/jenkins/workspace/gest-manager_integrations_PR-797/src/github.com/elastic/integrations/packages/gcp/data_stream/audit/_dev/test/pipeline]
[2021-03-24T21:22:19.014Z]    2. item [test-firewall.log-config.json] is not allowed in folder [/var/lib/jenkins/workspace/gest-manager_integrations_PR-797/src/github.com/elastic/integrations/packages/gcp/data_stream/firewall/_dev/test/pipeline]
[2021-03-24T21:22:19.014Z]    3. item [test-vpcflow.log-config.json] is not allowed in folder [/var/lib/jenkins/workspace/gest-manager_integrations_PR-797/src/github.com/elastic/integrations/packages/gcp/data_stream/vpcflow/_dev/test/pipeline]
```

2021-03-25 08:45 UTC, mtojek commented on go.mod
> +	github.com/elastic/elastic-package v0.0.0-20210324160257-57698a40f3e3
I did it here: https://github.com/elastic/integrations/pull/804 (spotted also a different issue). Once it's merged, please rebase this PR against master.

2021-03-25 09:53 UTC, mtojek commented
@rw-access Please rebase this branch again against the master branch. I merged the update on elastic-package, so above errors should disappear.

2021-03-25 17:16 UTC, rw-access commented on go.mod
> +	github.com/elastic/elastic-package v0.0.0-20210324160257-57698a40f3e3
Merged in master and confirmed the go changes are gone.
Thanks @mtojek

2021-03-25 17:17 UTC, rw-access commented
@mtojek CI is green now. thanks for pulling the deps into a separate PR.
do i have your 👍 to merge?

2021-03-30 21:18 UTC, merged