Update cloudnative packages to format_version 3.0.0
elastic/integrations pull request #8023
Opened 2023-09-29 12:31 UTC by tommyers-elastic

Update cloudnative packages to format_version 3.0.0

Almost all these changes were auto generated by tooling, but this still needs careful review. 

There should be _no functional changes_ to any of the packages here. 

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

2023-09-29 12:36 UTC, gizas approved these changes

2023-09-29 12:43 UTC, gizas commented on packages/istio/manifest.yml
> -license: basic
This should not be removed

2023-09-29 12:48 UTC, gizas commented on packages/prometheus/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/{{ PULL_REQUEST_NUMBER }}
Also the version 1.15 here needs removal

2023-09-29 12:49 UTC, gizas commented on packages/stan/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/{{ PULL_REQUEST_NUMBER }}
Same here

2023-09-29 12:50 UTC, gizas requested changes
Summarising: 
- The license removal is a breaking change and must be fixed
- Also prometheus and packages have a wrong RP number

2023-09-29 12:58 UTC, tommyers-elastic commented on packages/istio/manifest.yml
> -license: basic
license is not in `conditions.elastic.subscription`

2023-09-29 12:59 UTC, tommyers-elastic commented on packages/docker/data_stream/event/fields/fields.yml
> -  release: ga
yeh release tags are no longer allowed in field mappings

2023-09-29 13:18 UTC, tommyers-elastic commented on packages/istio/kibana/dashboard/istio-fed6f500-5941-11ed-bfb8-bbfe5b338339.json
> -        {
these references didn't point to anything. do you know what they are meant to do @gizas ?

2023-09-29 13:42 UTC, tommyers-elastic commented on packages/istio/kibana/dashboard/istio-fed6f500-5941-11ed-bfb8-bbfe5b338339.json
> -        {
hm there is a new tags.yml for tagging saved objects, i wonder if these need migrating there.

2023-09-29 13:43 UTC, tommyers-elastic commented on packages/istio/kibana/dashboard/istio-fed6f500-5941-11ed-bfb8-bbfe5b338339.json
> -        {
but they were flagged up as 'dangling references' by the validation - so i don' tthink they're doing anything

2023-09-29 15:25 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`3/3`) | :green_heart: 
Files | 80.0% (`4/5`) | :-1: -20.0
Classes | 80.0% (`4/5`) | :-1: -20.0
Methods | 90.909% (`110/121`) | :-1: -9.091
Lines | 82.034% (`621/757`) | :+1: 13.556
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-10-02 09:59 UTC, tommyers-elastic commented on packages/kubernetes/manifest.yml
> +    version: ^8.10.1
this is an intentional version bump - 8.10.0 doesn't exist

2023-10-02 10:23 UTC, gizas approved these changes
Looks fine with latest updates

2023-12-11 18:03 UTC, closed without merging