added metrics data streams to fleet_server
elastic/integrations pull request #8145
Opened 2023-10-10 09:43 UTC by juliaElastic

## Proposed commit message

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## How to test this PR locally

## Related issues

- 

## Screenshots

2023-10-10 10:04 UTC, juliaElastic commented
This is the first time I'm adding new data streams to a package. Are these files required under `/fields`?
```
agent.yml
beat-fields.yml
ecs.yml
```

Also I'm getting a few validation errors locally that I don't know how to fix:
```
juliabardi@Julias-MacBook-Pro fleet_server % ../../elastic-package check -v      
2023/10/10 12:02:17  WARN CommitHash is undefined, in both /Users/juliabardi/.elastic-package/version and the compiled binary, config may be out of date.
2023/10/10 12:02:17 DEBUG Enable verbose logging
2023/10/10 12:02:17 DEBUG latest version (cached): v0.89.1. Download from: https://github.com/elastic/elastic-package/releases/tag/v0.89.1 (Timestamp 2023-10-10 11:46:22.456736 +0200 CEST)
2023/10/10 12:02:17  INFO New version is available - v0.89.1. Download from: https://github.com/elastic/elastic-package/releases/tag/v0.89.1
Format the package
Done
Lint the package
Error: checking package failed: linting package failed: found 9 validation errors:
   1. current manifest version doesn't have changelog entry
   2. file "/Users/juliabardi/integrations/packages/fleet_server/data_stream/agent_status_metrics/fields/base-fields.yml" is invalid: field data_stream.type with external key defined ("ecs") but no _dev/build/build.yml found
   3. file "/Users/juliabardi/integrations/packages/fleet_server/data_stream/agent_status_metrics/fields/base-fields.yml" is invalid: field data_stream.dataset with external key defined ("ecs") but no _dev/build/build.yml found
   4. file "/Users/juliabardi/integrations/packages/fleet_server/data_stream/agent_status_metrics/fields/base-fields.yml" is invalid: field data_stream.namespace with external key defined ("ecs") but no _dev/build/build.yml found
   5. file "/Users/juliabardi/integrations/packages/fleet_server/data_stream/agent_status_metrics/fields/base-fields.yml" is invalid: field @timestamp with external key defined ("ecs") but no _dev/build/build.yml found
   6. file "/Users/juliabardi/integrations/packages/fleet_server/data_stream/agent_versions_metrics/fields/base-fields.yml" is invalid: field data_stream.type with external key defined ("ecs") but no _dev/build/build.yml found
   7. file "/Users/juliabardi/integrations/packages/fleet_server/data_stream/agent_versions_metrics/fields/base-fields.yml" is invalid: field data_stream.dataset with external key defined ("ecs") but no _dev/build/build.yml found
   8. file "/Users/juliabardi/integrations/packages/fleet_server/data_stream/agent_versions_metrics/fields/base-fields.yml" is invalid: field data_stream.namespace with external key defined ("ecs") but no _dev/build/build.yml found
   9. file "/Users/juliabardi/integrations/packages/fleet_server/data_stream/agent_versions_metrics/fields/base-fields.yml" is invalid: field @timestamp with external key defined ("ecs") but no _dev/build/build.yml found
```

2023-10-10 11:32 UTC, juliaElastic commented on packages/fleet_server/manifest.yml
> -license: basic
removed `release` and `license` fields as they broke the validation on the new format version:
```
Error: checking package failed: linting package failed: found 2 validation errors:
   1. file "/Users/juliabardi/integrations/packages/fleet_server/manifest.yml" is invalid: field (root): Additional property release is not allowed
   2. file "/Users/juliabardi/integrations/packages/fleet_server/manifest.yml" is invalid: field (root): Additional property license is not allowed
```

2023-10-10 11:44 UTC, juliaElastic commented on packages/fleet_server/data_stream/agent_status_metrics/manifest.yml
> +  index_mode: "time_series"
In order to enable tsds, both data streams need at least one keyword dimension field, `agent_status` doesn't have any keyword fields now, so we have to add one.

2023-10-10 12:03 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 
Classes | 100.0% (`0/0`) | :green_heart: 
Methods | 33.333% (`2/6`) | :-1: -66.667
Lines | 100.0% (`0/0`) | :green_heart: 2.294
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-10-10 13:34 UTC, juliaElastic commented on packages/fleet_server/data_stream/agent_status_metrics/fields/fields.yml
> +- name: fleet
I found `cluster.id` in [logstash](https://github.com/elastic/integrations/blob/4a4e90004d214c79e899d368e9506b8027ef7638/packages/logstash/data_stream/node/fields/fields.yml#L4) and `cluster_uuid` in [elasticsearch](https://github.com/elastic/integrations/blob/4a4e90004d214c79e899d368e9506b8027ef7638/packages/elasticsearch/data_stream/node/fields/package-fields.yml#L4-L6), which is an alias on `elasticsearch.cluster.id`

2023-10-10 13:37 UTC, juliaElastic commented on packages/fleet_server/manifest.yml
> +format_version: 2.10.0
We can, I saw in the validation that it's not released yet, so I wasn't sure if we are ready to use.

2023-10-10 13:44 UTC, juliaElastic commented on packages/fleet_server/data_stream/agent_status_metrics/fields/base-fields.yml
> +  external: ecs
I found this in kibana package, not sure where the alias path is coming from, is it populated automatically by fleet?
https://github.com/elastic/integrations/blob/4a4e90004d214c79e899d368e9506b8027ef7638/packages/kibana/data_stream/background_task_utilization/fields/package-fields.yml#L7-L12

2023-10-10 13:59 UTC, juliaElastic commented on packages/fleet_server/data_stream/agent_status_metrics/fields/base-fields.yml
> +  external: ecs
added

2023-10-10 13:59 UTC, juliaElastic commented on packages/fleet_server/data_stream/agent_status_metrics/fields/fields.yml
> +- name: fleet
added

2023-10-10 13:59 UTC, juliaElastic commented on packages/fleet_server/data_stream/agent_status_metrics/manifest.yml
> +elasticsearch:
enabled time series with cluster.id as dimension

2023-10-10 14:39 UTC, jlind23 commented on packages/fleet_server/manifest.yml
> +format_version: 2.10.0
@juliaElastic you can indeed start using it.

2023-10-10 14:40 UTC, juliaElastic commented on packages/fleet_server/manifest.yml
> +format_version: 2.10.0
updated

2023-10-10 15:48 UTC, mrodm commented on packages/fleet_server/manifest.yml
> -license: basic
About the `license` field it could be moved to `conditions.elastic.subscription` if needed.

Here it is an example in these docs: https://github.com/elastic/elastic-package/blob/main/docs/howto/update_major_package_spec.md#troubleshooting-upgrades-to-package-spec-v2

2023-10-10 15:57 UTC, juliaElastic commented on packages/fleet_server/manifest.yml
> -license: basic
Thanks! Do you know if basic is the default licence? I can add it back to be sure.

2023-10-11 13:27 UTC, juliaElastic commented
Hey @elastic/elastic-agent team, could I have your eyes on this as codeowners? I have updated the codeowners to Fleet team going forward.

2023-10-11 14:14 UTC, michalpristas approved these changes
approving as a codeowner transition of ownership

2023-10-11 14:38 UTC, juliaElastic commented
@joshdover Are you happy with the changes after review? Tested locally that the fields are populated:
![image](https://github.com/elastic/integrations/assets/90178898/1d88fb14-3fb3-4814-9a45-1a0e0260a13c)

2023-10-11 15:09 UTC, joshdover requested changes
Looks pretty close, a few more things

2023-10-11 15:09 UTC, joshdover commented on packages/fleet_server/manifest.yml
> +    version: "^8.8.0"
Should we bump this to 8.12.0? It won't break older clusters but it could create confusion later if this depends on the stack to also be at newer versions to have these data streams populated.

2023-10-11 15:09 UTC, joshdover commented on packages/fleet_server/data_stream/agent_status_metrics/fields/base-fields.yml
> +  external: ecs
Is this the same as cluster.id?

2023-10-11 15:09 UTC, joshdover commented on packages/fleet_server/data_stream/agent_status_metrics/fields/base-fields.yml
> +  external: ecs
Sorry I wasn't clear enough - I meant that we would use the standard ECS `agent.*` fields but populate them with values about Kibana. The thinking here is that Kibana _is_ the agent writing the data. I think something like this would make sense:

```
agent.type: kibana
agent.version: <stack version>
agent.id: <kibana uuid>
```

2023-10-11 15:09 UTC, joshdover commented on packages/fleet_server/data_stream/agent_status_metrics/fields/fields.yml
> +          metric_type: counter
All of these should be `metric_type: gauge` instead of counter. Gauges report whatever the current value is, while counters are always incrementing: https://www.elastic.co/guide/en/elasticsearch/reference/master/tsds.html#time-series-metric

2023-10-12 09:19 UTC, juliaElastic commented on packages/fleet_server/_dev/build/build.yml
> +    reference: git@v8.3.0
no, just copy paste. I'll update

2023-10-12 09:20 UTC, juliaElastic commented on packages/fleet_server/data_stream/agent_status_metrics/fields/base-fields.yml
> +  external: ecs
no, this is kibana instance id

2023-10-12 09:35 UTC, juliaElastic commented on packages/fleet_server/data_stream/agent_status_metrics/fields/fields.yml
> +          metric_type: counter
done

2023-10-12 09:35 UTC, juliaElastic commented on packages/fleet_server/manifest.yml
> +    version: "^8.8.0"
done

2023-10-12 09:35 UTC, juliaElastic commented on packages/fleet_server/_dev/build/build.yml
> +    reference: git@v8.3.0
done

2023-10-12 11:26 UTC, joshdover approved these changes
LGTM 🚀

2023-10-12 11:42 UTC, merged

2023-10-12 12:02 UTC, elasticmachine commented
Package fleet_server - 1.4.0 containing this change is available at https://epr.elastic.co/search?package=fleet_server