slack: fix handling of oldest parameter when paginating
elastic/integrations pull request #8169
Opened 2023-10-12 01:07 UTC by efd6

## Proposed commit message

The cursor does not include the oldest limit information, so this needs to be included in requests when paginating through responses.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## How to test this PR locally

## Related issues

- Fixes #8163
- Depends elastic/stream#59

## Screenshots

2023-10-12 01:10 UTC, elasticmachine commented
## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-10-12 01:34 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`1/1`) | :green_heart: 
Files | 100.0% (`1/1`) | :green_heart: 
Classes | 100.0% (`1/1`) | :green_heart: 
Methods | 100.0% (`13/13`) | :green_heart: 75.0
Lines | 98.715% (`384/389`) | :-1: -1.285
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-10-13 07:22 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2023-10-13 07:26 UTC, efd6 commented on packages/slack/_dev/deploy/docker/files/config.yml
> +      cursor: null
This makes use of a new stream feature in v0.11.0 that allows presence of a parameter to block a rule.

2023-10-13 10:13 UTC, chrisberkhout requested changes
I think the expression for setting `pagination_finished` needs to be changed to not always be false.

Or even better, that variable could actually go away and `next_cursor` could be used directly. If there's no cursor value we're about to request the first page of a sequence.

Note that `.response_metadata.next_cursor` is always present in a successful response, either with a cursor value or an empty string.

2023-10-13 21:22 UTC, efd6 commented
@chrisberkhout That is #7987. This change is focused specifically on the issue that it is fixing.

2023-10-16 09:18 UTC, chrisberkhout approved these changes

2023-10-16 09:29 UTC, merged

2023-10-16 09:52 UTC, elasticmachine commented
Package slack - 1.14.1 containing this change is available at https://epr.elastic.co/search?package=slack