[RedisEnterprise] Enable use_type flag for node and proxy datastreams.
elastic/integrations pull request #8213
Opened 2023-10-16 13:12 UTC by ritalwar

- Enhancement

## Proposed commit message

- WHAT: Enables use_type flag for node and proxy datastreams of RedisEnterprise.
- WHY:  To correctly specify the metric_type mapping, as use_type enables a different layout for metrics storage, leveraging Elasticsearch types.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

- Closes #8149 

## Screenshots

2023-10-16 13:26 UTC, elasticmachine commented
## :broken_heart: Tests Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8213/detail/PR-8213/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8213/detail/PR-8213/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8213/detail/PR-8213/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8213/detail/PR-8213/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_8213.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-10-16T13:02:33.613Z&rangeTo=2023-10-16T13:22:33.613Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=d054f38297a1f67d9bcaf5a0c38191ac&transactionId=8a3ff18fedc30226)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-10-16T13:12:33.613+0000


* Duration: 14 min 19 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 1  |
| Passed       | 4  |
| Skipped      | 0 |
| Total        | 5   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->

  ### Test errors [![1](https://img.shields.io/badge/1%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8213/detail/PR-8213/1//tests)
<details><summary>Expand to view the tests failures</summary><p>
    
    
##### `static test: Verify sample_event.json – redisenterprise.node`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 null 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 one or more errors found in document: [0] field "redisenterprise.node.metrics.cpu_irqs" is undefined
[1] field "redisenterprise.node.metrics.free_memory" is undefined
[2] field "redisenterprise.node.metrics.cpu_nice_min" is undefined
[3] field "redisenterprise.node.metrics.provisional_memory" is undefined
[4] field "redisenterprise.node.metrics.cpu_steal_median" is undefined
[5] field "redisenterprise.node.metrics.cpu_irqs_median" is undefined
[6] field "redisenterprise.node.metrics.ingress_bytes_min" is undefined
[7] field "redisenterprise.node.metrics.cpu_iowait_max" is undefined
[8] field "redisenterprise.node.metrics.ingress_bytes" is undefined
[9] field "redisenterprise.node.metrics.cpu_user_max" is undefined
[10] field "redisenterprise.node.metrics.cpu_idle_min" is undefined
[11] field "redisenterprise.node.metrics.available_memory_no_overbooking" is undefined
[12] field "redisenterprise.node.metrics.ingress_bytes_median" is undefined
[13] field "redisenterprise.node.metrics.cpu_system_min" is undefined
[14] field "redisenterprise.node.metrics.cpu_irqs_max" is undefined
[15] field "redisenterprise.node.metrics.persistent_storage_free" is undefined
[16] field "redisenterprise.node.metrics.cpu_nice" is undefined
[17] field "redisenterprise.node.metrics.ephemeral_storage_free" is undefined
[18] field "redisenterprise.node.metrics.cpu_nice_max" is undefined
[19] field "redisenterprise.node.metrics.cpu_system" is undefined
[20] field "redisenterprise.node.metrics.cpu_iowait_median" is undefined
[21] field "redisenterprise.node.metrics.egress_bytes_min" is undefined
[22] field "redisenterprise.node.metrics.cpu_idle_median" is undefined
[23] field "redisenterprise.node.metrics.cpu_system_max" is undefined
[24] field "redisenterprise.node.metrics.ephemeral_storage_avail" is undefined
[25] field "redisenterprise.node.metrics.cpu_irqs_min" is undefined
[26] field "redisenterprise.node.metrics.available_memory" is undefined
[27] field "redisenterprise.node.metrics.egress_bytes" is undefined
[28] field "redisenterprise.node.metrics.cpu_nice_median" is undefined
[29] field "redisenterprise.node.metrics.cpu_user_median" is undefined
[30] field "redisenterprise.node.metrics.cpu_steal_min" is undefined
[31] field "redisenterprise.node.metrics.cpu_steal" is undefined
[32] field "redisenterprise.node.metrics.cpu_iowait_min" is undefined
[33] field "redisenterprise.node.metrics.total_req" is undefined
[34] field "redisenterprise.node.metrics.ingress_bytes_max" is undefined
[35] field "redisenterprise.node.metrics.cpu_idle" is undefined
[36] field "redisenterprise.node.metrics.cpu_steal_max" is undefined
[37] field "redisenterprise.node.metrics.provisional_memory_no_overbooking" is undefined
[38] field "redisenterprise.node.metrics.conns" is undefined
[39] field "redisenterprise.node.metrics.cpu_iowait" is undefined
[40] field "redisenterprise.node.metrics.egress_bytes_max" is undefined
[41] field "redisenterprise.node.metrics.cpu_user" is undefined
[42] field "redisenterprise.node.metrics.cpu_system_median" is undefined
[43] field "redisenterprise.node.metrics.cpu_user_min" is undefined
[44] field "redisenterprise.node.metrics.egress_bytes_median" is undefined
[45] field "redisenterprise.node.metrics.cur_aof_rewrites" is undefined
[46] field "redisenterprise.node.metrics.persistent_storage_avail" is undefined
[47] field "redisenterprise.node.metrics.cpu_idle_max" is undefined 
 ```
</p></details>
</ul>
    
</p></details>


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8213/detail/PR-8213/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Test integration: redisenterprise`
<ul>
<li>Took 0 min 5 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8213/runs/1/steps/1213/log/?start=0">here</a></li>
<li>Description: <code>                                eval "$(../../build/elastic-package stack shellinit)"                                ../../build/elastic-package test -v --report-format xUnit --report-output file --test-coverage                                </code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8213/runs/1/steps/1323/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-10-16 13:27 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 13.043
Classes | 100.0% (`0/0`) | :green_heart: 13.043
Methods | 66.667% (`4/6`) | :-1: -17.833
Lines | 100.0% (`0/0`) | :green_heart: 13.542
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-11-02 08:36 UTC, lalit-satapathy commented on packages/redisenterprise/changelog.yml
> +    - description: Enable use_type flag for node and proxy datastreams.
Nit: use_types

2023-11-02 08:36 UTC, lalit-satapathy commented on packages/redisenterprise/data_stream/node/agent/stream/stream.yml.hbs
> -rate_counters: false
What is the impact of removing "rate_counters: false"?

2023-11-02 08:36 UTC, lalit-satapathy commented on packages/redisenterprise/data_stream/node/sample_event.json
> +            },
is this a coincidence that all node* metrics are gauge/value?

2023-11-02 08:36 UTC, lalit-satapathy commented on packages/redisenterprise/data_stream/proxy/sample_event.json
> +            "listener_resp2_clients_max": {
Same here, is this a coincidence that all proxy* metrics are counters?

2023-11-02 08:36 UTC, lalit-satapathy commented on packages/redisenterprise/data_stream/node/fields/fields.yml
> +- name: redisenterprise.node.*.value
Assuming the metric_type mapping will be taken in separate PR.

2023-11-02 09:29 UTC, ritalwar commented on packages/redisenterprise/data_stream/node/agent/stream/stream.yml.hbs
> -rate_counters: false
It's disabled by default, so there's no impact unless it was enabled.

2023-11-02 09:33 UTC, ritalwar commented on packages/redisenterprise/data_stream/node/sample_event.json
> +            },
I've already done the metric_type [PR](https://github.com/elastic/integrations/pull/8133) for this datastream and verified then there that all the node datastream metrics are gauges. Also please [refer](https://docs.redis.com/latest/rs/references/rest-api/objects/statistics/node-metrics/).

2023-11-02 09:34 UTC, ritalwar commented on packages/redisenterprise/data_stream/node/fields/fields.yml
> +- name: redisenterprise.node.*.value
Yes, those will be raised separately as part of the TSDB migration.

2023-11-02 09:55 UTC, ritalwar commented on packages/redisenterprise/data_stream/proxy/sample_event.json
> +            "listener_resp2_clients_max": {
I will verify this again.

2023-11-06 08:38 UTC, lalit-satapathy approved these changes
LGTM, Need to follow-up and ensure the TSDB mappings are updated accordingly.

2023-11-06 08:38 UTC, lalit-satapathy commented on packages/redisenterprise/data_stream/node/fields/fields.yml
> +- name: redisenterprise.node.*.counter
Is this entry needed, since node is all gauge? Or is it a fallback if any nodes have counter in the future?

2023-11-06 08:38 UTC, lalit-satapathy commented on packages/redisenterprise/data_stream/node/fields/fields.yml
> +- name: redisenterprise.node.*.value
Assuming the metric type mappsing is: `redisenterprise.node.*.value `will directly map to gauge and  `redisenterprise.proxy.*.counter `to counter.

2023-11-06 08:38 UTC, lalit-satapathy commented on packages/redisenterprise/data_stream/proxy/sample_event.json
> +            "listener_resp2_clients_max": {
Any changes here?

2023-11-09 07:42 UTC, ritalwar commented on packages/redisenterprise/data_stream/proxy/sample_event.json
> +            "listener_resp2_clients_max": {
No, I verified all of them are counter fields, and this has been verified from the Prometheus endpoint where they are collected.
<img width="1006" alt="Screenshot 2023-11-09 at 1 11 06 PM" src="https://github.com/elastic/integrations/assets/102972658/170bd050-aa4a-43ee-a77a-11cd8bafa98e">

2023-11-09 07:43 UTC, ritalwar commented on packages/redisenterprise/data_stream/node/fields/fields.yml
> +- name: redisenterprise.node.*.value
Yes, we do need to explicitly specify the metric_type, and I will address this in the metric_type PR.

2023-11-09 07:45 UTC, ritalwar commented on packages/redisenterprise/data_stream/node/fields/fields.yml
> +- name: redisenterprise.node.*.counter
I believe it's a better idea to remove it. Instead of retaining a fallback, we can update it when a new field is introduced in a new version. I will also make sure to update the tested version for consistency.

2023-11-10 08:59 UTC, agithomas commented on packages/redisenterprise/data_stream/node/fields/fields.yml
> +    Redisenterprise node gauge metric
Can you please reassess the need to mention `gauge` in the description? If there is a reason, why it is needed?

2023-11-10 09:01 UTC, agithomas commented on packages/redisenterprise/data_stream/node/fields/fields.yml
> +- name: redisenterprise.node.labels.*
Is there a possibility these fields become dimension fields in future, as part of TSDB enablement? If yes, these may be expanded.

2023-11-10 09:04 UTC, agithomas reviewed
Please verify if a change in the snapshot image is needed as part of the dashboard change?

2023-11-10 09:07 UTC, agithomas commented
I suppose there is `SVR00002` exclusion (Mandatory filters in dashboard) in the package configuration. Would you be able to overturn this with the dashboard changes ?

2023-11-10 09:10 UTC, agithomas commented on packages/redisenterprise/_dev/build/docs/README.md
> +Redis Enterpise integration is tested with redislabs/redis:7.2.4-72 version.
Please add a title `## Compatibility` above this line.

2023-11-10 10:11 UTC, ritalwar commented on packages/redisenterprise/data_stream/node/fields/fields.yml
> +    Redisenterprise node gauge metric
I did it the same way other Prometheus-based integrations do.
Eg: [Prometheus](https://github.com/elastic/integrations/blob/099f63aa30f6593df1bed63e31cf48804281bd34/packages/prometheus/data_stream/collector/fields/fields.yml#L26), [Istio](https://github.com/elastic/integrations/blob/099f63aa30f6593df1bed63e31cf48804281bd34/packages/istio/data_stream/istiod_metrics/fields/fields.yml#L19), [CockroachDb](https://github.com/elastic/integrations/blob/099f63aa30f6593df1bed63e31cf48804281bd34/packages/cockroachdb/data_stream/status/fields/fields.yml#L7), etc.

2023-11-10 10:13 UTC, ritalwar commented on packages/redisenterprise/data_stream/node/fields/fields.yml
> +- name: redisenterprise.node.labels.*
Yes, it's expanded as part of the TSDB [PR](https://github.com/elastic/integrations/pull/8091), and it will be merged after this one.

2023-11-10 10:18 UTC, agithomas commented on packages/redisenterprise/data_stream/node/fields/fields.yml
> +- name: redisenterprise.node.labels.*
Please confirm, if all these fields are of type `gauge` ?

2023-11-10 10:20 UTC, agithomas commented on packages/redisenterprise/data_stream/node/fields/fields.yml
> +    Redisenterprise node gauge metric
Please confirm, if all these fields are of type gauge ?

2023-11-10 10:31 UTC, ritalwar commented
> Please verify if a change in the snapshot image is needed as part of the dashboard change?

There aren't any major changes, just some adjustments to field names that aren't visible in the snapshot.

2023-11-10 10:33 UTC, ritalwar commented
> I suppose there is `SVR00002` exclusion (Mandatory filters in dashboard) in the package configuration. Would you be able to overturn this with the dashboard changes ?

Sorry, I don't understand why we need to overturn it.

2023-11-10 10:36 UTC, ritalwar commented on packages/redisenterprise/data_stream/node/fields/fields.yml
> +    Redisenterprise node gauge metric
Yes, verified from the Prometheus endpoint where they are collected.


<img width="727" alt="image" src="https://github.com/elastic/integrations/assets/102972658/5daedab6-533d-420f-99ac-71e81f962ff0">

2023-11-10 10:44 UTC, agithomas commented
> Sorry, I don't understand why we need to overturn it.

Ignore it, it can be taken up later in a separate PR and it is a part of package spec V3 issue addressal.

2023-11-10 10:47 UTC, shmsr requested changes

2023-11-10 10:47 UTC, shmsr commented on packages/redisenterprise/data_stream/proxy/fields/fields.yml
> +    Redisenterprise proxy counter metric
```suggestion
    Proxy counter metric
```

2023-11-10 10:47 UTC, shmsr commented on packages/redisenterprise/data_stream/proxy/fields/fields.yml
> +    Redisenterprise proxy counter metric
As Redis Enterprise is not there in the description of other fields, I think we should remove it from here too.

2023-11-10 10:47 UTC, shmsr commented on packages/redisenterprise/_dev/build/docs/README.md
> +Redis Enterpise integration is tested with redislabs/redis:7.2.4-72 version.
Do we usually mention that integration is tested against xyz docker image version? Or just xyz version.

What I mean is isn't just `Redis Enterprise v7.2.4` enough?

Here the docker image is referring to `7.2.4` (version core) and `72` indicates the pre-release version as per semver.
```
valid version :=  |
                  <version core>
                  <version core> "-" <pre-release>
                  <version core> "+" <build>
                  <version core> "-" <pre-release> "+" <build>
```

If we are keeping the Docker image, let's link it or explicitly mention it:

> Redis Enterpise integration is tested against Redis Enterprise's Docker image: redislabs/redis:7.2.4-72.

2023-11-10 11:03 UTC, ritalwar commented on packages/redisenterprise/data_stream/proxy/fields/fields.yml
> +    Redisenterprise proxy counter metric
How about using just "Node metrics" and "Proxy metrics" for their respective datastreams?

2023-11-10 11:05 UTC, ritalwar commented on packages/redisenterprise/_dev/build/docs/README.md
> +Redis Enterpise integration is tested with redislabs/redis:7.2.4-72 version.
hmm, version 7.2.4 is sufficient.

2023-11-10 16:37 UTC, shmsr commented on packages/redisenterprise/data_stream/proxy/fields/fields.yml
> +    Redisenterprise proxy counter metric
I checked https://docs.redis.com/latest/rs/clusters/monitoring/prometheus-metrics-definitions/

> "Node metrics" and "Proxy metrics"

Sounds good to me!

2023-11-10 16:42 UTC, shmsr commented on packages/redisenterprise/data_stream/node/fields/fields.yml
> +    Redisenterprise node gauge metric
Are you sure @ritalwar?

See: https://docs.redis.com/latest/rs/clusters/monitoring/prometheus-metrics-definitions/#node-metrics

For example:

`node_conns: Number of clients connected to endpoints on node` (because sometimes there could be just 1 client, sometimes 2, maybe even 0, maybe even 100, or just any number).

This is usually a gauge. Not a counter. Can we double-check? If it is counter in Prometheus metrics perhaps a bug request should be raised at their end.

2023-11-10 16:43 UTC, shmsr commented
Left one more important comment: https://github.com/elastic/integrations/pull/8213#discussion_r1389638205

2023-11-15 06:13 UTC, ritalwar commented on packages/redisenterprise/data_stream/node/fields/fields.yml
> +    Redisenterprise node gauge metric
Yes, it's gauge and metric_type is taken care in this [PR](https://github.com/elastic/integrations/pull/8133/files).

2023-11-15 06:26 UTC, agithomas approved these changes
LGTM!

2023-11-15 06:40 UTC, shmsr commented on packages/redisenterprise/data_stream/node/fields/fields.yml
> +    Redisenterprise node gauge metric
My bad. I wanted to write about the other counters; don't why I wrote about this at that time.

2023-11-15 06:41 UTC, shmsr approved these changes

2023-11-15 06:46 UTC, merged

2023-11-15 07:09 UTC, elasticmachine commented
Package redisenterprise - 0.7.0 containing this change is available at https://epr.elastic.co/search?package=redisenterprise