[docs] Update MSSQL README to use documentation guidelines
elastic/integrations pull request #8240
Opened 2023-10-18 18:04 UTC by colleenmcginnis

## Proposed commit message

Update README to use documentation guidelines

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] ~~I have verified that all data streams collect metrics or logs.~~
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] ~~I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).~~

## Author's Checklist

- [ ] @colleenmcginnis Initial draft to align with the [documentation guidelines](https://github.com/elastic/integrations/blob/main/docs/documentation_guidelines.md)
- [ ] @SubhrataK to provide an initial review of the structure
- [ ] @colleenmcginnis address initial feedback, remove draft status
- [ ] @\obs-infraobs-integrations technical review 
- [ ] @colleenmcginnis address additional feedback, merge

## How to test this PR locally

View [the README](https://github.com/colleenmcginnis/integrations/blob/mssql-setup/packages/microsoft_sqlserver/docs/README.md).

## Related issues

Related to https://github.com/elastic/observability-docs/issues/3270

2023-10-18 18:23 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8240/detail/PR-8240/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8240/detail/PR-8240/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8240/detail/PR-8240/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8240/detail/PR-8240/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_8240.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-10-18T17:55:12.872Z&rangeTo=2023-10-18T18:15:12.872Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=14745654abd35dc21830465bff129731&transactionId=a71114682c2dccb4)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-10-18T18:05:12.872+0000


* Duration: 18 min 54 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 19  |
| Skipped      | 0 |
| Total        | 19   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-10-18 18:23 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`2/2`) | :green_heart: 
Files | 100.0% (`2/2`) | :green_heart: 
Classes | 100.0% (`2/2`) | :green_heart: 
Methods | 93.75% (`30/32`) | :+1: 3.274
Lines | 100.0% (`1252/1252`) | :green_heart: 2.688
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-10-18 20:20 UTC, colleenmcginnis commented on packages/microsoft_sqlserver/changelog.yml
> +      link: TBD
```suggestion
      link: https://github.com/elastic/integrations/pull/8240
```

2023-10-23 11:19 UTC, SubhrataK approved these changes
Looks good!

2023-10-30 18:00 UTC, shmsr requested changes
Thank you for improving the documentation 🎉

2023-10-30 18:00 UTC, shmsr commented on packages/microsoft_sqlserver/_dev/build/docs/README.md
> +Find more details in [Metrics](#metrics-reference).
```suggestion
* `performance` metrics gather the list of performance objects available on that server. Each server will have a different list of performance objects depending on the installed software.
* `transaction_log` metrics collect all usage stats and the total space usage.

Find more details in [Metrics](#metrics-reference).
```

2023-10-30 18:00 UTC, shmsr commented on packages/microsoft_sqlserver/_dev/build/docs/README.md
> +You can use our hosted Elasticsearch Service on Elastic Cloud, which is recommended, or self-manage the Elastic Stack on your own hardware.
```suggestion
You need Elasticsearch for storing and searching your data and Kibana for visualizing and managing it.
You can use our hosted Elasticsearch Service on Elastic Cloud, which is recommended, or self-manage the Elastic Stack on your hardware.
```

2023-10-30 18:00 UTC, shmsr commented on packages/microsoft_sqlserver/_dev/build/docs/README.md
> +>Note: This integration supports collecting metrics from a single host. For multi-host metrics, each host can be run as a new integration.
```suggestion
> Note: This integration supports collecting metrics from a single host. For multi-host metrics, each host can be run as a new integration.
```

2023-10-30 18:00 UTC, shmsr commented on packages/microsoft_sqlserver/_dev/build/docs/README.md
> +>Note: For the integration package to be able to read and send audit events the event target must be configured to be Windows event log.
Isn't this gonna break the format? Isn't the syntax for blockquote is

```
> text
```

and not

```
>text
```

I'm not sure if `>text` works? Ref: https://www.markdownguide.org/basic-syntax/#blockquotes-1

2023-10-30 18:00 UTC, shmsr commented on packages/microsoft_sqlserver/_dev/build/docs/README.md
```suggestion
The feature `merge_results` has been introduced in 8.4 beats which creates a single event by combining the metrics in a single event. For more details, refer to [SQL module](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-sql.html#_example_merge_multiple_queries_to_single_event).

```

nit: together is redundant

2023-10-30 18:00 UTC, shmsr commented on packages/microsoft_sqlserver/_dev/build/docs/README.md
> +Read more in [Instructions about each performance counter metrics](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-os-performance-counters-transact-sq
```suggestion
Read more in [instructions about each performance counter metrics](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-os-performance-counters-transact-sql?view=sql-server-ver15).
```

2023-10-30 18:00 UTC, shmsr commented on packages/microsoft_sqlserver/_dev/build/docs/README.md
> +Read more in [Instructions and the operations supported by transaction log](https://docs.microsoft.com/en-us/sql/relational-databases/logs/the-transaction-log-sql-server?view=sql-server-ver15).
```suggestion
Read more in [instructions and the operations supported by transaction log](https://docs.microsoft.com/en-us/sql/relational-databases/logs/the-transaction-log-sql-server?view=sql-server-ver15).
```

2023-10-30 18:12 UTC, shmsr commented on packages/microsoft_sqlserver/_dev/build/docs/README.md
> +>Note: For the integration package to be able to read and send audit events the event target must be configured to be Windows event log.
I checked. As per [CommonMark](https://commonmark.org/) spec, the space is optional. So you can ignore this comment other similar ones.

2023-10-30 19:27 UTC, shmsr approved these changes

2023-10-30 19:39 UTC, merged

2023-10-30 20:04 UTC, elasticmachine commented
Package microsoft_sqlserver - 2.3.1 containing this change is available at https://epr.elastic.co/search?package=microsoft_sqlserver

2023-10-31 05:56 UTC, lalit-satapathy reviewed
Should we also keep security team informed on document changes to the audit data-streams (if any?)

2023-10-31 05:56 UTC, lalit-satapathy commented on packages/microsoft_sqlserver/_dev/build/docs/README.md
> +For more information on SQL Server auditing, refer to [SQL Server Audit](https://docs.microsoft.com/en-us/sql/relational-databases/security/auditing/sql-server-audit-database-engine?view=sql-server-v
The line in the beginning paragraph, somewhat looks mis-placed, since it is referring the audit data-stream primarily. It may wrongly infer referring to all data streams.

2023-10-31 05:56 UTC, lalit-satapathy commented on packages/microsoft_sqlserver/_dev/build/docs/README.md
> +Find more details in [Logs](#logs-reference).
Unable to click the #logs-reference, in the generated document. Can we verify the anchors exist?

<img width="706" alt="Screenshot 2023-10-31 at 11 23 41 AM" src="https://github.com/elastic/integrations/assets/69236064/04beb715-27b4-4594-ba9e-2e5a02a75b1f">

2023-10-31 05:56 UTC, lalit-satapathy commented on packages/microsoft_sqlserver/_dev/build/docs/README.md
> +<!-- Additional set up instructions -->
Is this formatting intended: it comes as below:

<img width="734" alt="Screenshot 2023-10-31 at 11 22 49 AM" src="https://github.com/elastic/integrations/assets/69236064/099eba8f-69b4-413d-a292-fe07f192d5a4">

2023-10-31 06:33 UTC, shmsr commented on packages/microsoft_sqlserver/_dev/build/docs/README.md
> +Find more details in [Logs](#logs-reference).
Fix:

s/logs-reference/logs

2023-10-31 06:33 UTC, shmsr commented on packages/microsoft_sqlserver/_dev/build/docs/README.md
> +Find more details in [Metrics](#metrics-reference).
Fix:

s/metrics-reference/metrics

2023-10-31 06:33 UTC, shmsr commented on packages/microsoft_sqlserver/_dev/build/docs/README.md
> +<!-- Additional set up instructions -->
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#hiding-content-with-comments

Ideally, this should have worked. On GitHub it does. Maybe for the website, we are using a different markdown renderer that does not support this?