Extend user.name mapping to Windows Integration Package
elastic/integrations pull request #8289
Opened 2023-10-25 07:10 UTC by ChriZzn

## Proposed commit message
Adding EventID 4662 and 5136, to use the 'winlog.event_data.SubjectUserName' as user.name and related.user

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

2023-10-25 07:14 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8289/detail/PR-8289/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8289/detail/PR-8289/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8289/detail/PR-8289/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8289/detail/PR-8289/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-10-25T07:01:11.888Z&rangeTo=2023-10-25T07:21:11.888Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=8e9f35afea0d31dc616a4b13cd34fea3&transactionId=1e83271fccfa0e8e)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-10-25T07:11:11.888+0000


* Duration: 3 min 16 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8289/detail/PR-8289/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Load a resource file from a library`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8289/runs/1/steps/81/log/?start=0">here</a></li>
<li>Description: <code>approval-list/elastic/integrations.yml</code></l1>
</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8289/runs/1/steps/89/log/?start=0">here</a></li>
<li>Description: <code>githubApiCall: The REST API call https://api.github.com/orgs/elastic/members/ChriZzn return the message : java.lang.Exception: httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/ChriZzn : httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/ChriZzn : Code: 404Error: {"message":"User does not exist or is not a member of the organization","documentation_url":"https://docs.github.com/rest/orgs/members#check-organization-membership-for-a-user"}</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-10-25 07:24 UTC, elasticmachine commented
Pinging @elastic/elastic-agent (Team:Elastic-Agent)

2023-10-25 08:36 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2023-10-25 13:48 UTC, leehinman requested changes
you will need to update the version number in `packages/windows/manifest.yml` as well.

2023-10-25 13:48 UTC, leehinman commented on packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/security.yml
> +              "4781", "4798", "4799", "4817", "4904", "4905", "4907", "4912", "5136", "4662"].contains(ctx.event.code)) {
Can you add this to https://github.com/elastic/integrations/blob/main/packages/system/data_stream/security/elasticsearch/ingest_pipeline/standard.yml as well.  We want to keep these in sync.

Also can you add the ECS categorization fields for these 2 events to the params at https://github.com/elastic/integrations/blob/19ba18733e482303e2a26c040ce5a30014dd87ae/packages/system/data_stream/security/elasticsearch/ingest_pipeline/standard.yml#L9 and https://github.com/elastic/integrations/blob/19ba18733e482303e2a26c040ce5a30014dd87ae/packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/security.yml#L13

2023-10-25 14:23 UTC, ChriZzn commented on packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/security.yml
> +              "4781", "4798", "4799", "4817", "4904", "4905", "4907", "4912", "5136", "4662"].contains(ctx.event.code)) {
Hello, should be done now, Regards

2023-10-30 12:57 UTC, ChriZzn commented
Any Updates on this?

2023-10-30 20:04 UTC, efd6 commented
Sorry this was dropped. Please fix the conflict in the system changelog.

2023-10-31 05:52 UTC, ChriZzn commented
Hello, should be resolved now, Regards

2023-10-31 05:53 UTC, efd6 commented
/test

2023-10-31 06:08 UTC, efd6 reviewed
Are you able to provide test cases for this? If not, let me know and I will construct ones from the MS docs ([here](https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4662) and [here](https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/event-5136), but real cases would be better).

2023-10-31 06:14 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`11/11`) | :green_heart: 
Files | 93.75% (`15/16`) | :+1: 6.793
Classes | 93.75% (`15/16`) | :+1: 6.793
Methods | 77.358% (`164/212`) | :-1: -7.445
Lines | 93.782% (`8853/9440`) | :+1: 8.704
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-10-31 06:37 UTC, ChriZzn commented
> Are you able to provide test cases for this? If not, let me know and I will construct ones from the MS docs ([here](https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4662) and [here](https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/event-5136), but real cases would be better).

Hi, im sorry i cant provide you test data, because they are from active environments...

2023-11-01 03:46 UTC, efd6 commented
Please apply the this patch file and then resolve the conflicts, [0001-add-tests.patch](https://github.com/elastic/integrations/files/13223199/0001-add-tests.patch).

2023-11-01 09:31 UTC, ChriZzn commented
Hi i applied the patch and resolved the conflicts....

2023-11-01 20:53 UTC, efd6 commented
The author you've used to apply the patch is making the CLA checker unhappy. Would you please sign the CLA with that name/email address as well?

2023-11-02 07:35 UTC, ChriZzn commented
> The author you've used to apply the patch is making the CLA checker unhappy. Would you please sign the CLA with that name/email address as well?

Hi, should be signed now with username 'cw', Regards

2023-11-02 07:40 UTC, efd6 commented
It will need to match exactly, including the email address.

2023-11-02 10:34 UTC, ChriZzn commented
so

> It will need to match exactly, including the email address.

Resigned the CLA, please DM me the email/username combo if there are still Problems

2023-11-02 21:56 UTC, efd6 commented
/test

2023-11-02 22:35 UTC, efd6 approved these changes

2023-11-03 14:09 UTC, leehinman approved these changes
LGTM

2023-11-05 20:49 UTC, merged

2023-11-05 21:13 UTC, elasticmachine commented
Package system - 1.48.0 containing this change is available at https://epr.elastic.co/search?package=system

2023-11-05 21:18 UTC, elasticmachine commented
Package windows - 1.42.0 containing this change is available at https://epr.elastic.co/search?package=windows