Making parser configurable for catalina and localhost logs
elastic/integrations pull request #8301
Opened 2023-10-26 11:27 UTC by ishleenk17

- Enhancement

## Proposed commit message

- WHAT: The parsers have been made configurable for catalina and localhost logs
- WHY:  Apache tomcat can have logs through log4j which can be configured to support multiple date formats. Corresponding to that we need to provide support for multiple pattern for multiline parsers, hence providing this option to the customer to configure it as per need. 

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Closes https://github.com/elastic/integrations/issues/7204

## Screenshots

<img width="749" alt="Screenshot 2023-10-26 at 4 50 45 PM" src="https://github.com/elastic/integrations/assets/102962586/8cbfbbac-ca0e-4bd2-9620-d30d6bce9f06">

2023-10-26 11:45 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8301/detail/PR-8301/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8301/detail/PR-8301/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8301/detail/PR-8301/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8301/detail/PR-8301/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_8301.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-10-26T11:18:02.321Z&rangeTo=2023-10-26T11:38:02.321Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=2499d8dc78e0d138ce59731c70b2a372&transactionId=221182d425c2aed0)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-10-26T11:28:02.321+0000


* Duration: 18 min 50 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 9  |
| Skipped      | 0 |
| Total        | 9   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8301/detail/PR-8301/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Test integration: apache_tomcat`
<ul>
<li>Took 3 min 6 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8301/runs/1/steps/1225/log/?start=0">here</a></li>
<li>Description: <code>                                eval "$(../../build/elastic-package stack shellinit)"                                ../../build/elastic-package test -v --report-format xUnit --report-output file --test-coverage                                </code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8301/runs/1/steps/1335/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-10-26 11:46 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 3.837
Classes | 100.0% (`0/0`) | :green_heart: 3.837
Methods | 100.0% (`9/9`) | :green_heart: 7.902
Lines | 100.0% (`0/0`) | :green_heart: 11.391
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-10-26 18:26 UTC, shmsr requested changes

2023-10-26 18:26 UTC, shmsr commented on packages/apache_tomcat/changelog.yml
> +    - description: Making parsers configurable for catalina and localhost logs
```suggestion
    - description: Making parsers configurable for catalina and localhost logs
```

2023-10-26 18:26 UTC, shmsr commented on packages/apache_tomcat/data_stream/catalina/manifest.yml
> +          This option expects a list of parsers that the payload has to go through. For more information see [Parsers](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-filestream
```suggestion
          This option expects a list of parsers that the payload has to go through. For more information, see [Parsers](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-filestream.html#_parsers).
```

2023-10-26 18:29 UTC, shmsr commented on packages/apache_tomcat/data_stream/catalina/manifest.yml
> +          This option expects a list of parsers that the payload has to go through. For more information see [Parsers](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-filestream
Similar changes in other data streams.

2023-10-26 18:30 UTC, shmsr commented
PR title also needs update:

> [apache_tomcat]: Make parser configurable for catalina and localhost logs

2023-10-27 05:28 UTC, harnish-elastic commented
@ishleenk17 If the user updates the multiline parser that we have supported, the logs are still dropped just because they might need to add their log date format in the [pipeline](https://github.com/elastic/integrations/blob/main/packages/apache_tomcat/data_stream/catalina/elasticsearch/ingest_pipeline/default.yml#L56) also. Can we capture these details in the README troubleshooting section for a better experience?

2023-10-30 04:47 UTC, ishleenk17 commented
> @ishleenk17 If the user updates the multiline parser that we have supported, the logs are still dropped just because they might need to add their log date format in the [pipeline](https://github.com/elastic/integrations/blob/main/packages/apache_tomcat/data_stream/catalina/elasticsearch/ingest_pipeline/default.yml#L29) also. Can we capture these details in the README troubleshooting section for a better experience?

Thats correct. The expectation is that we are leaving it upto the customer to have their own date formats through custom pipelines. Multi line parsers will help them to have those date formats being parsed for multiline logs.
But yes we can add this to the documentation.

2023-10-30 05:41 UTC, harnish-elastic approved these changes
LGTM! 🚀

2023-10-30 08:48 UTC, shmsr approved these changes

2023-10-30 08:50 UTC, merged

2023-10-30 09:13 UTC, elasticmachine commented
Package apache_tomcat - 0.17.0 containing this change is available at https://epr.elastic.co/search?package=apache_tomcat