[O11y][Apache Tomcat] Fix pipeline test and rename `header_forwarder` field to `client.ip`
elastic/integrations pull request #8304
Opened 2023-10-26 12:23 UTC by harnish-elastic

## Proposed commit message

- Update pipeline test log file.
- Replace the header_forwarder field with the ECS field `client.ip`.
- Explored the [update_query](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update-by-query.html#docs-update-by-query-api-prereqs) by upgrading the package scenario to rename the field from header_forwarder to client.ip so that existing users can also rename the existing data fields. The update query works fine, hence added the description in the README itself by giving the steps that the user can perform.

### Note
- To explore update_by_query API for renaming fields from the ingested documents, please refer this [issue](https://github.com/elastic/integrations/issues/8365) and perform the mentioned steps.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Closes #7622

2023-10-26 12:36 UTC, milan-elastic approved these changes
LGTM!

2023-10-26 12:48 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8304/detail/PR-8304/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8304/detail/PR-8304/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8304/detail/PR-8304/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8304/detail/PR-8304/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_8304.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-10-26T12:13:46.024Z&rangeTo=2023-10-26T12:33:46.024Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=a8c8a64775f4c5564ef8fc15a353da41&transactionId=25c6878ddf244f9d)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-10-26T12:23:46.024+0000


* Duration: 25 min 41 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 54  |
| Skipped      | 0 |
| Total        | 54   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-10-26 12:48 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`9/9`) | :green_heart: 
Files | 100.0% (`9/9`) | :green_heart: 3.837
Classes | 100.0% (`9/9`) | :green_heart: 3.837
Methods | 97.531% (`79/81`) | :+1: 5.433
Lines | 82.393% (`964/1170`) | :-1: -6.216
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-10-26 18:13 UTC, shmsr requested changes

2023-10-26 18:13 UTC, shmsr commented on packages/apache_tomcat/_dev/build/docs/README.md
> +1. Create a rename processor by performing the following steps in the Dev tools.
`by using an update query` shouldn't this be omitted? as both rename (ingest pipeline) and update by query API are suggested in the following step.

2023-10-26 18:13 UTC, shmsr commented on packages/apache_tomcat/_dev/build/docs/README.md
> +2. Apply the created pipeline to all the existing documents under the index.
```suggestion
2. Apply the created pipeline to all the existing documents under the index using update by query API.
```

2023-10-26 18:17 UTC, shmsr commented on packages/apache_tomcat/_dev/build/docs/README.md
> +1. Create a rename processor by performing the following steps in the Dev tools.
Instead of linking this https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update-by-query.html#docs-update-by-query shouldn't linking https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update-by-query.html#docs-update-by-query-api-ingest-pipeline is more apt here?

2023-10-27 05:49 UTC, muthu-mps commented on packages/apache_tomcat/data_stream/access/elasticsearch/ingest_pipeline/default.yml
>        tag: 'split_header_forwarder'
Can we change the `tag` value to `split_x_forwarded_for` ?

2023-10-27 05:49 UTC, muthu-mps commented on packages/apache_tomcat/docs/README.md
> +POST logs-apache_tomcat.access-default/_update_by_query?conflicts=proceed&pipeline=rename
When we use the `update_by_query` what happens to the existing field? Are we going to have the older field in the index even after `rename` processor is applied?

2023-10-27 06:05 UTC, harnish-elastic commented on packages/apache_tomcat/docs/README.md
> +POST logs-apache_tomcat.access-default/_update_by_query?conflicts=proceed&pipeline=rename
No, the old field (apache_tomcat.access.header_forwarder) will not be present in any document after the update query is applied.

2023-10-27 08:20 UTC, harnish-elastic commented on packages/apache_tomcat/_dev/build/docs/README.md
> +1. Create a rename processor by performing the following steps in the Dev tools.
Updated, thanks!

2023-10-27 08:20 UTC, harnish-elastic commented on packages/apache_tomcat/data_stream/access/elasticsearch/ingest_pipeline/default.yml
>        tag: 'split_header_forwarder'
Updated, thanks!

2023-10-27 08:20 UTC, harnish-elastic commented on packages/apache_tomcat/_dev/build/docs/README.md
> +2. Apply the created pipeline to all the existing documents under the index.
Updated, thanks!

2023-10-30 18:52 UTC, ishleenk17 commented on packages/apache_tomcat/docs/README.md
> +- `apache_tomcat.access.header_forwarder` is renamed to `client.ip` in version `0.16.1` of this integration. Hence please consider changing `apache_tomcat.access.header_forwarder` to `client.ip` fiel
This type of documentation falls under the same category as reindexing documentation.
We should have the example in one common place or use the existing [link](pipeline) to update_by query and just point to that instead of giving the detail steps here.

Integrations readme's should be to the point.

2023-11-01 06:24 UTC, ishleenk17 approved these changes
Looks good!

2023-11-01 07:30 UTC, shmsr commented
I agree that our documentation should be more specific. However, I believe that providing a specific example from our side on how to use update by query would be more helpful for our users, instead of leaving them to research it themselves. Using the wrong processor in the ingest pipeline coupled with update by query API could have serious consequences since all documents in that index could be affected. Therefore, it is important to provide clear guidance to our users.

It would be beneficial to document our troubleshooting steps in this PR, similar to how we have done so in the past. See:

- https://github.com/elastic/integrations/issues/7624
- https://github.com/elastic/integrations/issues/8085

The research done as part of this PR should be documented for future reference. Please update the PR description with a good example and also record those steps in a separate issue.

2023-11-01 07:34 UTC, shmsr approved these changes

2023-11-01 07:53 UTC, ishleenk17 commented
> My two cents on this comment: [#8304 (comment)](https://github.com/elastic/integrations/pull/8304#discussion_r1376676180)
> 
> I agree that our documentation should be more specific. However, I believe that providing a specific example from our side on how to use update by query would be more helpful for our users, instead of leaving them to research it themselves. Using the wrong processor in the ingest pipeline coupled with update by query API could have serious consequences since all documents in that index could be affected. Therefore, it is important to provide clear guidance to our users.
> 
> It would be beneficial to document our troubleshooting steps researched as part of this PR, similar to how we have done so in the past. See:
> 
> * [Reindexing steps for Non-TSDB enabled data streams for conflicting fields #7624](https://github.com/elastic/integrations/issues/7624)
> * [Reindexing steps for TSDB enabled data streams for conflicting fields #8085](https://github.com/elastic/integrations/issues/8085)
> 
> The research done as part of this PR should be documented for future reference. Please update the PR description with a good example and also record those steps in a separate issue. This will ensure our README remains to the point.
> 
> Approving the PR as PR description update and the new issue I asked to file can be done later.

That

> My two cents on this comment: [#8304 (comment)](https://github.com/elastic/integrations/pull/8304#discussion_r1376676180)
> 
> I agree that our documentation should be more specific. However, I believe that providing a specific example from our side on how to use update by query would be more helpful for our users, instead of leaving them to research it themselves. Using the wrong processor in the ingest pipeline coupled with update by query API could have serious consequences since all documents in that index could be affected. Therefore, it is important to provide clear guidance to our users.
> 
> It would be beneficial to document our troubleshooting steps researched as part of this PR, similar to how we have done so in the past. See:
> 
> * [Reindexing steps for Non-TSDB enabled data streams for conflicting fields #7624](https://github.com/elastic/integrations/issues/7624)
> * [Reindexing steps for TSDB enabled data streams for conflicting fields #8085](https://github.com/elastic/integrations/issues/8085)
> 
> The research done as part of this PR should be documented for future reference. Please update the PR description with a good example and also record those steps in a separate issue. This will ensure our README remains to the point.
> 
> Approving the PR as PR description update and the new issue I asked to file can be done later.

Thats right, we should do exactly what we did in Reindexing steps as pointed out in this [comment](https://github.com/elastic/integrations/pull/8304#discussion_r1376676180)

2023-11-01 09:48 UTC, harnish-elastic commented
@ishleenk17 @shmsr As discussed, updated the [description](https://github.com/elastic/integrations/pull/8304#:~:text=user%20can%20perform.-,Note,-To%20explore%20update_by_query) and raised an [issue](https://github.com/elastic/integrations/issues/8365) with all steps mentioned in it for update_by_query API.

2023-11-01 09:50 UTC, merged

2023-11-01 10:14 UTC, elasticmachine commented
Package apache_tomcat - 0.17.1 containing this change is available at https://epr.elastic.co/search?package=apache_tomcat