README update: Vsphere limitations of virtual machine
elastic/integrations pull request #8331
Opened 2023-10-30 11:43 UTC by ishleenk17

- Bug

## Proposed commit message

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Relates https://github.com/elastic/sdh-beats/issues/3977

2023-10-30 12:01 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8331/detail/PR-8331/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8331/detail/PR-8331/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8331/detail/PR-8331/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8331/detail/PR-8331/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_8331.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-10-30T11:33:29.432Z&rangeTo=2023-10-30T11:53:29.432Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=450b3e630240081b035c3979300ed68e&transactionId=b926a26134e927df)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-10-30T11:43:29.432+0000


* Duration: 18 min 15 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 17  |
| Skipped      | 0 |
| Total        | 17   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-10-30 12:02 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`1/1`) | :green_heart: 
Files | 100.0% (`1/1`) | :green_heart: 
Classes | 100.0% (`1/1`) | :green_heart: 
Methods | 100.0% (`18/18`) | :green_heart: 
Lines | 89.13% (`41/46`) | :-1: -6.347
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-10-30 18:10 UTC, shmsr requested changes

2023-10-30 18:10 UTC, shmsr commented on packages/vsphere/docs/README.md
> + Note: vSphere Integration currently supports network names of VM's conecected only to vSS (Virtual Standard Switch) and not vDS (virtual Dustributed Switches).
```suggestion
> Note: vSphere Integration currently supports network names of VMs connected only to vSS (Virtual Standard Switch) and not vDS (virtual Distributed Switches).
```

Notes are usually in blockquote. Also spelling mistakes ^

2023-10-30 18:10 UTC, shmsr commented on packages/vsphere/_dev/build/docs/README.md
> + Note: vSphere Integration currently supports network names of VM's conecected only to vSS (Virtual Standard Switch) and not vDS (virtual Dustributed Switches).
```suggestion
> Note: vSphere Integration currently supports network names of VMs connected only to vSS (Virtual Standard Switch) and not vDS (virtual Distributed Switches).
```

Notes are usually in blockquote. Also spelling mistakes ^

2023-10-30 18:13 UTC, devamanv commented on packages/vsphere/_dev/build/docs/README.md
> + Note: vSphere Integration currently supports network names of VM's conecected only to vSS (Virtual Standard Switch) and not vDS (virtual Dustributed Switches).
Question: Is vSS vSphere Standard Switch or Virtual Standard Switch? Or are they interchangeable? I referred this https://www.vmware.com/in/products/vsphere/distributed-switch.html

2023-10-30 18:17 UTC, shmsr commented on packages/vsphere/_dev/build/docs/README.md
> + Note: vSphere Integration currently supports network names of VM's conecected only to vSS (Virtual Standard Switch) and not vDS (virtual Dustributed Switches).
++

Same Q. I see `v` is `vSphere` (not virtual) in all the places I have checked.

2023-10-30 18:17 UTC, ishleenk17 commented on packages/vsphere/_dev/build/docs/README.md
> + Note: vSphere Integration currently supports network names of VM's conecected only to vSS (Virtual Standard Switch) and not vDS (virtual Dustributed Switches).
Thanks for pointing this out. My latest change didn't get committed properly from repo. 
Its updated now.

2023-10-30 18:19 UTC, shmsr commented on packages/vsphere/_dev/build/docs/README.md
> + Note: vSphere Integration currently supports network names of VM's conecected only to vSS (VSphere Standard Switch) and not vDS (VSphere Dustributed Switches).
```suggestion
 Note: vSphere Integration currently supports network names of VMs connected only to vSS (vSphere Standard Switch) and not vDS (vSphere Distributed Switches).
```

2023-10-30 18:27 UTC, devamanv commented on packages/vsphere/changelog.yml
> +      type: bugfix
Would it make sense to treat it an enhancement? Or is it related to a bugfix, that's why we are calling it a bugfix?

2023-10-30 18:28 UTC, devamanv approved these changes
Just one small comment about the update being an enhancement, rest looks good to me.

2023-10-30 18:28 UTC, ishleenk17 commented on packages/vsphere/changelog.yml
> +      type: bugfix
Its an addition of a missing documentation, so bugfix should be good

2023-10-30 20:13 UTC, shmsr approved these changes

2023-10-31 04:54 UTC, merged

2023-10-31 05:21 UTC, elasticmachine commented
Package vsphere - 1.9.1 containing this change is available at https://epr.elastic.co/search?package=vsphere