elastic/obs-infraobs-integrations: Address SVR00002
elastic/integrations pull request #8348
Opened 2023-10-31 11:36 UTC by shmsr

## Proposed commit message

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## How to test this PR locally

## Related issues

- 

## Screenshots

2023-10-31 11:52 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8348/detail/PR-8348/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8348/detail/PR-8348/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8348/detail/PR-8348/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8348/detail/PR-8348/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_8348.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-10-31T11:27:05.405Z&rangeTo=2023-10-31T11:47:05.405Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=f4334eb119c67e43ed6ac69f091bc87e&transactionId=af54759c6c925eba)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-10-31T11:37:05.405+0000


* Duration: 15 min 2 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 2  |
| Skipped      | 0 |
| Total        | 2   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-10-31 11:52 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 
Classes | 100.0% (`0/0`) | :green_heart: 
Methods | 25.0% (`1/4`) | :grey_exclamation: 
Lines | 100.0% (`0/0`) | :green_heart: 
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-10-31 12:54 UTC, tommyers-elastic reviewed
👍 we also need to remove the SVR0002 check from validations.yml

2023-10-31 12:54 UTC, tommyers-elastic commented on packages/azure_functions/changelog.yml
> +    - description: Address SVR00002 validation skipped during package-spec v3 migration
please can we make the changelog more user-friendly? something like "add global dashboard filter for dataset to improve performance (allows removal of 'SVR00002' validation exception)"

2023-10-31 12:54 UTC, tommyers-elastic commented on packages/cassandra/kibana/dashboard/cassandra-25b7d6d0-1c71-11ec-84f1-e1733c643874.json
> +        {
we can also remove the references which are no longer used after removal of panel-level filter. i think the 'dangling reference' check would flag these up anyway.

2023-10-31 17:25 UTC, shmsr commented on packages/cassandra/kibana/dashboard/cassandra-25b7d6d0-1c71-11ec-84f1-e1733c643874.json
> +        {
I also thought that. But no dangling references errors are shown by elastic-package lint. So seemed risky to do it manually.

2023-10-31 17:25 UTC, shmsr commented on packages/azure_functions/changelog.yml
> +    - description: Address SVR00002 validation skipped during package-spec v3 migration
Ah, cool. I'll do that.

2023-10-31 17:44 UTC, shmsr commented
> 👍 we also need to remove the SVR0002 check from validations.yml

Yeah, I'll run a script at the end that would run lint again and update all validation.yml. Will do that in the end; right before marking this PR ready for review.

2023-10-31 18:45 UTC, shmsr commented on packages/cassandra/kibana/dashboard/cassandra-25b7d6d0-1c71-11ec-84f1-e1733c643874.json
> +        {
Ah, I see. Check this: https://github.com/elastic/package-spec/blob/48461578910c405fcc6a92b97a1e558aeb8fb860/code/go/internal/validator/semantic/validate_kibana_no_dangling_object_ids.go#L24

This is why dangling references when type is index-pattern, is ignored.

2023-10-31 19:17 UTC, shmsr commented on packages/cassandra/kibana/dashboard/cassandra-25b7d6d0-1c71-11ec-84f1-e1733c643874.json
> +        {
I'll see if I can add the filtering logic (new logic for index-pattern needs to be written) to the program I wrote for https://github.com/elastic/integrations/pull/8347

2023-11-02 07:20 UTC, shmsr commented
Rough notes. Please read them once before reviewing.

- [ ] apache_spark 
    - sub-filter
- [ ] citrix_adc
    - sub-filter with different dataset in 1 dashboard
- [ ] ceph 
    - sub-filter with different dataset in 1 dashboard
- [x] coredns 
    - left some viz filter as they are not exactly the same and using minimum_should_match, etc.
- [ ] couchbase 
    - sub-filter with different dataset in 1 dashboard
- [ ] etcd 
    - not sure what to filter with; multiple dataset
- [x] hadoop 
    - test with 8.10.2 stack once
- [x] iis (please test Dashboard for the Logs IIS integration)
    - this dashboard shows process and cache metrics for the IIS server.
    - this dashboard shows metrics for the IIS server.
    - can the description be better?
- [x] golang
    - test golang
- [ ] kafka
    - only 1 out of 2 dashboard taken care of
- [ ] memcached
    - noticed this in the dashboard:
        - part of Bytes Read (Kb)
        - unit is Kilobits and written bytes instead. Confusing? More such examples are there.
- [ ] microsoft_sqlserver
    - take transaction_log for example. Go to fields/fields.yml
    - fields are like this mssql.metrics.<field_name> whereas I expected mssql.transaction_log.<field_name>
- [ ] mongodb (multiple datasets + subfilter)
- [ ] mysql (multiple datasets)
- [ ] nginx (multiple datasets)
- [ ] oracle (multiple datasets)
- [ ] oracle_weblogic (multiple datasets)
- [ ] postgresql
    - found a custom logic to filter with prefix (not a problem; just taking notes)
    - multiple datasets
- [ ] rabbitmq
    - filter by multiple datasets
- [ ] redis
    - filter by multiple datasets
- [ ] redisenterprise
    - multiple datasets
- [ ] salesforce
    - multiple dataset
- [ ] spring_boot
    - access logs dashboard; i don’t see a dataset. is it correct?
- [ ] vsphere
    - multiple dataset

2023-11-02 07:34 UTC, shmsr commented
I'll take care of the other packages in another PR.

2023-11-30 11:30 UTC, lalit-satapathy commented
CC: @harnish-elastic @aliabbas-elastic to review the dashboard changes as part of the filters being added.

2023-12-01 07:26 UTC, harnish-elastic commented
Why the screenshots/images of the dashboard is not updated in all packages? The look of the dashboard changes if we drag the query to the dashboard level!

2023-12-01 07:39 UTC, shmsr commented
> Why the screenshots/images of the dashboard are not updated in all packages? The look of the dashboard changes if we drag the query to the dashboard level!

@harnish-elastic Good point. These changes are not done by opening the dashboard and editing from there and then saving from there. Changes are done by hand directly (manually checking *.json, editing, and elastic-package install to check if there are no obvious errors)  in *.json files. As the fix had to be applied to ~35 packages which is a lot; not all could be addressed though. The screenshot was only possible for every package if I had done it via the normal way which would have taken a lot of time. So, during testing, we're loading the dashboard, can we click the screenshot?

2023-12-06 07:54 UTC, aliabbas-elastic requested changes
Requesting for changes according to this [comment](https://github.com/elastic/obs-infraobs-team/issues/1263#:~:text=Kibana%20version%208.11.0-,Issues%20found,-1.%20Cassandra)

2023-12-21 09:43 UTC, mrodm commented
Hi @shmsr, please update your branch with the latest contents from main branch. There was an important PR merged updating the CI pipelines. Thanks!

2024-01-03 21:44 UTC, shmsr commented
I have resolved the merge conflicts and also addressed the issues pointed out by @aliabbas-elastic in https://github.com/elastic/obs-infraobs-team/issues/1263#:~:text=Kibana%20version%208.11.0-,Issues%20found,-1.%20Cassandra

2024-01-11 06:46 UTC, aliabbas-elastic approved these changes
LGTM

2024-01-11 06:58 UTC, harnish-elastic approved these changes
LGTM! Still concerned about how we can proceed to update the dashboard screenshot as per this [comment](https://github.com/elastic/integrations/pull/8348#issuecomment-1835606920)!

2024-02-07 20:34 UTC, shmsr commented
Looks like there are very complex merge conflicts because of recent changes in listed packages. Have to rework on them from scratch.

Here's a list that needs rework from scratch:

- azure_functions
- hadoop
- iis
- traefik
- websphere_application_server

2024-04-07 21:21 UTC, closed without merging

2024-04-08 03:51 UTC, ishleenk17 commented
@shmsr : Is this still valid ?