Add cloudbeat Azure Credentials config
elastic/integrations pull request #8376
Opened 2023-11-02 08:45 UTC by moukoublen

## Proposed commit message
Add cloudbeat azure credentials configuration.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## How to test this PR locally

## Related issues

- 

## Screenshots

2023-11-02 09:00 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8376/detail/PR-8376/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8376/detail/PR-8376/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8376/detail/PR-8376/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8376/detail/PR-8376/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_8376.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-11-02T08:35:28.858Z&rangeTo=2023-11-02T08:55:28.858Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=dab5eb8185bba5a05367e7fffc5c424c&transactionId=cc3b40462f37da7b)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-11-02T08:45:28.858+0000


* Duration: 15 min 43 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![3](https://img.shields.io/badge/3%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8376/detail/PR-8376/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Boot up the Elastic stack`
<ul>
<li>Took 2 min 53 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8376/runs/1/steps/1235/log/?start=0">here</a></li>
<li>Description: <code>../../build/elastic-package stack up -d -v --version 8.12.0-SNAPSHOT</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8376/runs/1/steps/1283/log/?start=0">here</a></li>

</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8376/runs/1/steps/1296/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-11-02 09:25 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 
Classes | 100.0% (`0/0`) | :green_heart: 
Methods | 25.0% (`2/8`) | :-1: -72.368
Lines | 100.0% (`0/0`) | :green_heart: 4.573
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-11-09 18:54 UTC, JordanSh commented on packages/cloud_security_posture/data_stream/findings/manifest.yml
> +    vars:
we should also have an `azure.account_type` field, similar to the other integrations

2023-11-10 07:44 UTC, orestisfl approved these changes

2023-11-10 07:44 UTC, orestisfl commented on packages/cloud_security_posture/data_stream/findings/manifest.yml
> +    vars:
Sure, but that would be part of the multi-account support ticket

2023-11-10 07:45 UTC, orestisfl requested changes

2023-11-10 07:45 UTC, orestisfl commented on packages/cloud_security_posture/data_stream/findings/manifest.yml
> +      - name: azure.credentials.type
Are we not going to include this in the backend?

2023-11-12 17:35 UTC, kfirpeled commented on packages/cloud_security_posture/data_stream/findings/agent/stream/azure.yml.hbs
> +        {{/if}}
please add `azure.credentials.type` as well to the passed parameters

2023-11-14 09:12 UTC, moukoublen commented on packages/cloud_security_posture/data_stream/findings/agent/stream/azure.yml.hbs
> +        {{/if}}
(answering both @kfirpeled and @orestisfl comment)

I followed the pattern from `gcp` where the client credentials type exists only in `manifest.yml` and not in `gcp.yml.hbs`. I thought this happened because account type is not used in Cloudbeat and only in Kibana (/fleet) side, but I might need clarification here. 

Should I add it to `azure.yml.hbs` as well?

2023-11-14 09:13 UTC, moukoublen commented on packages/cloud_security_posture/data_stream/findings/manifest.yml
> +      - name: azure.credentials.type
Check on this comment:

https://github.com/elastic/integrations/pull/8376#discussion_r1392241583

2023-11-14 10:17 UTC, orestisfl commented on packages/cloud_security_posture/data_stream/findings/agent/stream/azure.yml.hbs
> +        {{/if}}
I feel it's cleaner to explicitly define the credential type but I am fine either way :+1:

2023-11-14 15:45 UTC, moukoublen commented on packages/cloud_security_posture/data_stream/findings/agent/stream/azure.yml.hbs
> +        {{/if}}
Sure. I Added `azure.credentials.type` in `azure.yml.hbs` as well.

I will open a PR in cloudbeat as well to add it in config struct and base the switch on this enum.

2023-11-14 17:12 UTC, kfirpeled commented on packages/cloud_security_posture/data_stream/findings/agent/stream/azure.yml.hbs
> +        type: {{azure.credentials.type}}
💯

2023-11-15 08:43 UTC, orestisfl approved these changes

2023-11-15 10:53 UTC, oren-zohar approved these changes

2023-11-15 12:05 UTC, merged

2023-11-15 12:28 UTC, elasticmachine commented
Package cloud_security_posture - 1.7.0-preview02 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-11-15 14:25 UTC, elasticmachine commented
Package cloud_security_posture - 1.7.0-preview03 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-11-21 12:49 UTC, elasticmachine commented
Package cloud_security_posture - 1.7.0-preview04 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-11-29 14:30 UTC, elasticmachine commented
Package cloud_security_posture - 1.7.0-preview05 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-11-30 15:58 UTC, elasticmachine commented
Package cloud_security_posture - 1.7.0-preview06 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-12-06 09:57 UTC, elasticmachine commented
Package cloud_security_posture - 1.7.0-preview09 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2023-12-06 13:46 UTC, elasticmachine commented
Package cloud_security_posture - 1.7.0 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture