[O11y][Apache Tomcat] Update descriptions in README.md
elastic/integrations pull request #8394
Opened 2023-11-03 12:35 UTC by harnish-elastic

- Enhancement

## Proposed commit message

- Update README with the latest version of Prometheus support and add a line in the troubleshooting section for Timezone.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Relates #7363

2023-11-03 13:01 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8394/detail/PR-8394/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8394/detail/PR-8394/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8394/detail/PR-8394/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8394/detail/PR-8394/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_8394.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-11-03T12:25:48.859Z&rangeTo=2023-11-03T12:45:48.859Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=e4eb8eae6cde07184a721f075d3a7828&transactionId=0f40ae2ac0c51877)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-11-03T12:35:48.859+0000


* Duration: 26 min 39 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 54  |
| Skipped      | 0 |
| Total        | 54   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-11-03 13:01 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`9/9`) | :green_heart: 
Files | 100.0% (`9/9`) | :green_heart: 
Classes | 100.0% (`9/9`) | :green_heart: 
Methods | 97.531% (`79/81`) | :grey_exclamation: 
Lines | 82.393% (`964/1170`) | :grey_exclamation: 
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-11-03 13:19 UTC, aliabbas-elastic approved these changes
LGTM

2023-11-03 18:33 UTC, shmsr requested changes

2023-11-05 14:49 UTC, shmsr commented on packages/apache_tomcat/_dev/build/docs/README.md
> +4. Go to `/etc/systemd/system` and add the following content within the `[Service]` section of the `tomcat.service` file: -
```suggestion
4. Go to `/etc/systemd/system` and add the following content within the `[Service]` section of the `tomcat.service` file:
```

Also, there's another line with `: -`. Could you change that too?

2023-11-05 14:55 UTC, shmsr commented on packages/apache_tomcat/_dev/build/docs/README.md
> +4. Go to `/etc/systemd/system` and add the following content within the `[Service]` section of the `tomcat.service` file: -
Also, change point 5 with this because first of all it is not clear and also there are some spelling mistakes:

>  Run the following commands to  reload the systemd manager configuration and restart the Apache Tomcat service to set the updated environment variable:

2023-11-06 05:32 UTC, harnish-elastic commented on packages/apache_tomcat/_dev/build/docs/README.md
> +4. Go to `/etc/systemd/system` and add the following content within the `[Service]` section of the `tomcat.service` file: -
> Also, there's another line with `: -`. Could you change that too?

For all the points that have coding blocks that the user might need to perform, we have `: -`. So let's keep consistency with the other lines. WDYT?

2023-11-06 07:03 UTC, shmsr commented on packages/apache_tomcat/_dev/build/docs/README.md
> +4. Go to `/etc/systemd/system` and add the following content within the `[Service]` section of the `tomcat.service` file: -
Okay, cool.

2023-11-06 16:55 UTC, shmsr approved these changes

2023-11-06 18:08 UTC, devamanv approved these changes
LGTM

2023-11-07 05:09 UTC, merged

2023-11-07 05:33 UTC, elasticmachine commented
Package apache_tomcat - 0.17.2 containing this change is available at https://epr.elastic.co/search?package=apache_tomcat