Bugfix/windows forwarded
elastic/integrations pull request #8408
Opened 2023-11-06 14:46 UTC by ShourieG

## Type of change
Please label this PR with one of the following labels, depending on the scope of your change:
- Bug

## Proposed commit message
ISSUE: The Windows integration did not parse winlog.event_data.MemberName properly and map it to user.target.name,  when user CN contained extra "," characters. For example CN=Novak\, Jan (FFF),OU=Basic,OU=Domain Users,DC=ddd,DC=ccc,DC=fff will be parsed to user.target.name, "Novak\," which is wrong.

FIX:  Fixed parsing of winlog.event_data.MemberName in forwarded data stream by removing the old splitToken method and replaced it with a custom script that splits the strings only when the combination of a "," followed by two uppercase characters followed by an "=" are found. Example : ,CN=

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## How to test this PR locally

## Related issues

- 

## Screenshots

2023-11-06 14:59 UTC, leehinman requested changes

2023-11-06 14:59 UTC, leehinman commented on packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/security.yml
> +          def memberNameParts = splitString(ctx.winlog.event_data.MemberName);
I think we need to do the same thing in the System integration.  https://github.com/elastic/integrations/blob/a537327779334d94aeb6e91a15d43247dd290501/packages/system/data_stream/security/elasticsearch/ingest_pipeline/standard.yml#L2580

2023-11-06 14:59 UTC, leehinman commented on packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/security.yml
> +              if (Character.compare(input.charAt(i), ",".charAt(0))==0 && i < input.length() - 3 && Character.isUpperCase(input.charAt(i + 1))
does it always have to be 2 Uppercase characters followed by Equals?  Does Windows ever do something like O=Internet,CN=Test User ?

2023-11-06 15:34 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8408/detail/PR-8408/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8408/detail/PR-8408/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8408/detail/PR-8408/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8408/detail/PR-8408/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_8408.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-11-06T14:37:31.978Z&rangeTo=2023-11-06T14:57:31.978Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=c364f66818de0032b15f977b112ec2cf&transactionId=e9bd8bd14f910fb4)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-11-06T14:47:31.978+0000


* Duration: 47 min 1 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 148  |
| Skipped      | 0 |
| Total        | 148   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-11-06 15:34 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`8/8`) | :green_heart: 
Files | 91.667% (`11/12`) | :-1: -8.333
Classes | 91.667% (`11/12`) | :-1: -8.333
Methods | 85.156% (`109/128`) | :+1: 9.399
Lines | 91.574% (`5858/6397`) | :-1: -8.426
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-11-06 20:11 UTC, efd6 reviewed
It seems to me that this could be done with a split processor; something like `{"split": {"if": "ctx.winlog?.event_data?.MemberName != null", "field": "winlog.event_data.MemberName", "target_field": "_temp.MemberNameParts", "separator":"(?<!\\\\),"}` with `_temp.MemberNameParts` being used as the direct source of the script's `memberNameParts` var.

2023-11-07 03:30 UTC, ShourieG commented
> Since the original issue shows that the comma is preceded by a backslash, it seems to me that this could be done with a split processor; something like `{"split": {"if": "ctx.winlog?.event_data?.MemberName != null", "field": "winlog.event_data.MemberName", "target_field": "_temp.MemberNameParts", "separator":"(?<!\\\\),"}` with `_temp.MemberNameParts` being used as the direct source of the script's `memberNameParts` var.

@efd6 true, but we don't know if that's always the case or not, hence more of a generic approach was taken.

2023-11-07 03:38 UTC, ShourieG commented on packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/security.yml
> +              if (Character.compare(input.charAt(i), ",".charAt(0))==0 && i < input.length() - 3 && Character.isUpperCase(input.charAt(i + 1))
@elasticmachine I'm not sure as my knowledge is limited with regards to this, @efd6 do you have any idea ?

2023-11-07 03:39 UTC, ShourieG commented on packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/security.yml
> +          def memberNameParts = splitString(ctx.winlog.event_data.MemberName);
I'll open a separate issue for the system integration as this PR is related to a specific SDH.

2023-11-07 05:44 UTC, efd6 commented
> @efd6 true, but we don't know if that's always the case or not, hence more of a generic approach was taken.

I have asked at the original issue. If it is guaranteed, the simpler approach would be preferable.

2023-11-07 10:55 UTC, ShourieG commented on packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/security.yml
> +          def memberNameParts = splitString(ctx.winlog.event_data.MemberName);
Opened this separate issue: https://github.com/elastic/integrations/issues/8419

2023-11-07 13:13 UTC, andrewkroh commented
https://learn.microsoft.com/en-us/previous-versions/windows/desktop/ldap/distinguished-names

2023-11-07 14:45 UTC, leehinman commented on packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/security.yml
> +              if (Character.compare(input.charAt(i), ",".charAt(0))==0 && i < input.length() - 3 && Character.isUpperCase(input.charAt(i + 1))
Given the doc @andrewkroh linked to, I'm in favor of the approach @efd6 suggested.  It handles the ',' in the attribute value and allows for the attributes to be more than 2 uppercase characters.

2023-11-07 20:52 UTC, efd6 commented
The key is in the table [here](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/ldap/distinguished-names). `,` is reserved, and so MUST be escaped. This means the split processor approach is valid.

2023-11-08 06:08 UTC, ShourieG commented
@efd6, @leehinman I've updated the PR with the split processor logic as suggested.

2023-11-08 14:43 UTC, ycombinator approved these changes
LGTM.

2023-11-08 15:51 UTC, leehinman approved these changes
LGTM

2023-11-09 07:03 UTC, kcreddy approved these changes
LGTM 👍🏼

2023-11-09 07:07 UTC, merged

2023-11-09 07:34 UTC, elasticmachine commented
Package windows - 1.42.1 containing this change is available at https://epr.elastic.co/search?package=windows