elastic/obs-infraobs-integrations: Address skipped validation SVR00004
elastic/integrations pull request #8423
Opened 2023-11-07 17:31 UTC by shmsr

## Proposed commit message

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## How to test this PR locally

## Related issues

- 

## Screenshots

2023-11-07 17:44 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8423/detail/PR-8423/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8423/detail/PR-8423/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8423/detail/PR-8423/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8423/detail/PR-8423/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_8423.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-11-07T17:22:08.162Z&rangeTo=2023-11-07T17:42:08.162Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=1fcca80a73579bc45c2624b27b00015d&transactionId=c64e1181f19c25d5)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-11-07T17:32:08.162+0000


* Duration: 12 min 54 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![16](https://img.shields.io/badge/16%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8423/detail/PR-8423/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


> Show only the first 10 steps failures

  
  
  
  
##### `Check integration: iis`
<ul>
<li>Took 0 min 1 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8423/runs/1/steps/1593/log/?start=0">here</a></li>
<li>Description: <code>../../build/elastic-package check -v</code></l1>
</ul>
  
  
  
  
##### `Take down the Elastic stack`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8423/runs/1/steps/1628/log/?start=0">here</a></li>
<li>Description: <code>build/elastic-package stack down -v</code></l1>
</ul>
  
  
  
  
##### `Check integration: oracle_weblogic`
<ul>
<li>Took 0 min 1 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8423/runs/1/steps/1570/log/?start=0">here</a></li>
<li>Description: <code>../../build/elastic-package check -v</code></l1>
</ul>
  
  
  
  
##### `Take down the Elastic stack`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8423/runs/1/steps/1600/log/?start=0">here</a></li>
<li>Description: <code>build/elastic-package stack down -v</code></l1>
</ul>
  
  
  
  
##### `Check integration: spring_boot`
<ul>
<li>Took 0 min 1 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8423/runs/1/steps/1414/log/?start=0">here</a></li>
<li>Description: <code>../../build/elastic-package check -v</code></l1>
</ul>
  
  
  
  
##### `Take down the Elastic stack`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8423/runs/1/steps/1515/log/?start=0">here</a></li>
<li>Description: <code>build/elastic-package stack down -v</code></l1>
</ul>
  
  
  
  
##### `Check integration: traefik`
<ul>
<li>Took 0 min 1 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8423/runs/1/steps/1468/log/?start=0">here</a></li>
<li>Description: <code>../../build/elastic-package check -v</code></l1>
</ul>
  
  
  
  
##### `Take down the Elastic stack`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8423/runs/1/steps/1550/log/?start=0">here</a></li>
<li>Description: <code>build/elastic-package stack down -v</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8423/runs/1/steps/1687/log/?start=0">here</a></li>

</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8423/runs/1/steps/1700/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-11-07 18:01 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`15/15`) | :green_heart: 
Files | 100.0% (`22/22`) | :green_heart: 
Classes | 100.0% (`22/22`) | :green_heart: 
Methods | 94.836% (`202/213`) | :-1: -5.164
Lines | 97.769% (`1709/1748`) | :-1: -0.952
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-11-09 19:35 UTC, shmsr commented
Please read the full PR description before reviewing.

2023-11-30 11:31 UTC, lalit-satapathy commented
CC: @harnish-elastic @aliabbas-elastic to review the dashboard changes as part of the pass by value is correctly being added.

2023-12-06 07:51 UTC, aliabbas-elastic approved these changes
LGTM for the changes. Please refer [here](https://github.com/elastic/obs-infraobs-team/issues/1263) for testing details

2023-12-21 09:42 UTC, mrodm commented
Hi @shmsr, please update your branch with the latest contents from main branch. There was an important PR merged updating the CI pipelines. Thanks!

2024-01-02 10:05 UTC, lalit-satapathy commented
@shmsr, 

What is pending on this as the [validation](https://github.com/elastic/obs-infraobs-team/issues/1263#issuecomment-1840362846) is complete?

2024-01-02 18:28 UTC, shmsr commented
> @shmsr,
> 
> What is pending on this as the [validation](https://github.com/elastic/obs-infraobs-team/issues/1263#issuecomment-1840362846) is complete?

I have to resolve the merge conflicts. I'll do it ASAP.

2024-01-03 20:18 UTC, shmsr commented
@harnish-elastic @aliabbas-elastic I have resolved the merge conflicts. I had to inline viz in springboot from the checkout of main brain as dashboard changes had been made in the last couple of months. Otherwise, for other packages only manifest and changelog yaml's are touched.

2024-02-07 10:53 UTC, shmsr commented
Fixed merge conflicts.

2024-02-07 10:56 UTC, devamanv approved these changes

2024-02-07 10:57 UTC, harnish-elastic commented on packages/oracle_weblogic/manifest.yml
Please refer to this [comment](https://github.com/elastic/integrations/issues/8938#issuecomment-1907554969). The saved search will throw error if it is inlined in the Kibana <`8.10`.

2024-02-07 10:59 UTC, harnish-elastic requested changes

2024-02-07 10:59 UTC, harnish-elastic commented on packages/oracle_weblogic/manifest.yml
Error is mentioned [here](https://github.com/elastic/integrations/issues/8938#issuecomment-1905712911).

2024-02-07 11:32 UTC, elasticmachine commented
### :rocket: Benchmarks report














To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-02-07 11:33 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/8708)
* Commit: e3a4b9eb5c462035a2a09b5de9630d26cc7a2408

cc @shmsr

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8708","number":8708,"commit":"e3a4b9eb5c462035a2a09b5de9630d26cc7a2408"}],"number":8708}
buildkite-pr-comment-->

2024-02-07 11:33 UTC, shmsr commented
As latest changes in oracle_weblogic includes saved searches; inlining them could be done for 8.10 stack. So leaving out oracle_weblogic.

cc: @harnish-elastic

2024-02-07 11:34 UTC, merged

2024-02-07 11:46 UTC, elasticmachine commented
Package azure_functions - 0.2.1 containing this change is available at https://epr.elastic.co/search?package=azure_functions

2024-02-07 11:46 UTC, elasticmachine commented
Package hadoop - 1.5.2 containing this change is available at https://epr.elastic.co/search?package=hadoop

2024-02-07 11:46 UTC, elasticmachine commented
Package iis - 1.17.4 containing this change is available at https://epr.elastic.co/search?package=iis

2024-02-07 11:46 UTC, elasticmachine commented
Package spring_boot - 1.2.2 containing this change is available at https://epr.elastic.co/search?package=spring_boot

2024-02-07 11:46 UTC, elasticmachine commented
Package traefik - 1.11.1 containing this change is available at https://epr.elastic.co/search?package=traefik

2024-02-07 11:46 UTC, elasticmachine commented
Package websphere_application_server - 1.1.1 containing this change is available at https://epr.elastic.co/search?package=websphere_application_server