Removing "experimental" messaging from LotL docs
elastic/integrations pull request #8473
Opened 2023-11-13 03:11 UTC by ajosh0504

This PR removes any "experimental" messaging for the `problemchild` integration package.

2023-11-13 03:27 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8473/detail/PR-8473/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8473/detail/PR-8473/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8473/detail/PR-8473/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8473/detail/PR-8473/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_8473.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-11-13T03:01:37.462Z&rangeTo=2023-11-13T03:21:37.462Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=b57721baaa134c961185d9a3fbce09ff&transactionId=cf726175922d4073)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-11-13T03:11:37.462+0000


* Duration: 16 min 35 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-11-15 13:51 UTC, sodhikirti07 approved these changes
LGTM!

2023-11-15 14:35 UTC, susan-shu-c requested changes

2023-11-15 14:35 UTC, susan-shu-c commented on packages/dga/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/8473
Did you mean to copy this chunk and then add `version: "2.1.1"`? I only see `version: 
2.0.0
` in this file. Also, the manifest says `2.1.1` so I think you're missing that in this changelog

2023-11-15 14:52 UTC, susan-shu-c commented on packages/dga/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/8473
Is this change in `dga` changelog necessary?

2023-11-15 14:53 UTC, susan-shu-c requested changes

2023-11-15 14:53 UTC, susan-shu-c commented on packages/problemchild/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/8106
I think this isn't the correct PR?

2023-11-27 18:39 UTC, susan-shu-c approved these changes

2023-11-27 18:45 UTC, merged

2023-11-27 19:11 UTC, elasticmachine commented
Package problemchild - 2.1.2 containing this change is available at https://epr.elastic.co/search?package=problemchild