Set frozen/cold tier for Security ML integrations
elastic/integrations pull request #8500
Opened 2023-11-14 16:47 UTC by susan-shu-c

## Proposed commit message

Per discussion brought up by @SourinPaul , here is a draft PR illustrating what the packages would look like with the data frozen tier and data cold tier filtered out. The PR also lints/formats these files with `elastic-package` to make sure the additional field conforms to style guides.

However, we must first discuss with the authors of those respective packages if that is the **expected behavior** before merging. @ajosh0504 @sodhikirti07 [Edit] We've discussed these changes and gotten approval.

Affected packages:
- [x] ProblemChild
- [x] DGA
- [x] LMD
- [x] DED

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

Additional info:
> Apoorva - Agree with the suggestion [...] to exclude cold/frozen tier from the module query. We seem to be doing it in our OOTB jobs in Kibana as well, so looks like the way to go to prevent ML jobs from hitting those tiers. Eg: https://github.com/elastic/kibana/blob/main/x-pack/plugins/ml/server/models/data_recognizer/modules/security_network/manifest.json#L17

## How to test this PR locally

## Related issues

- 

## Screenshots

2023-11-14 17:03 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8500/detail/PR-8500/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8500/detail/PR-8500/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8500/detail/PR-8500/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8500/detail/PR-8500/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_8500.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-11-14T16:37:37.626Z&rangeTo=2023-11-14T16:57:37.626Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=c011eb9a810bcc06d5d7f3d33a9e3343&transactionId=c54b5d7da8690485)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-11-14T16:47:37.626+0000


* Duration: 16 min 1 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 2  |
| Skipped      | 0 |
| Total        | 2   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-11-15 12:21 UTC, ajosh0504 commented
Thanks for getting this started! Changes look good, but you'd have to update the package versions as well, specifically, you'd add a new entry to the changelog and bump the version in the manifest file. See [this](https://github.com/elastic/integrations/pull/8473) PR for reference.

2023-11-15 12:21 UTC, ajosh0504 requested changes
Thanks for getting this started! Changes look good, but you'd have to update the package versions as well, specifically, you'd add a new entry to the changelog and bump the version in the manifest file. See [this](https://github.com/elastic/integrations/pull/8473) PR for reference.

2023-11-15 13:35 UTC, susan-shu-c commented
Re: @ajosh0504 
Ah oops, forgot that! I will do it if the changes look good to Kirti for her packages too

2023-11-15 16:40 UTC, sodhikirti07 commented on packages/lmd/manifest.yml
> +version: 2.1.2
You'll need to add below under `transform.yml` for LMD:
  `fleet_transform_version: 2.1.2`

2023-11-15 16:54 UTC, susan-shu-c commented on packages/lmd/manifest.yml
> +version: 2.1.2
Done!

2023-11-15 17:07 UTC, droberts195 approved these changes
LGTM

Thanks for adding these extra conditions.

2023-11-15 17:17 UTC, sodhikirti07 approved these changes
Changes lgtm!

2023-11-15 19:51 UTC, susan-shu-c commented
/test

2023-11-15 20:38 UTC, susan-shu-c commented
Buildkite's showing this error for DGA:

```

023/11/15 20:00:39 DEBUG Build zipped package
--
  | 2023/11/15 20:00:39 DEBUG Compress using archiver.Zip (destination: /opt/buildkite-agent/builds/bk-agent-prod-gcp-1700078074357728088/elastic/integrations/build/packages/dga-2.0.1.zip)
  | 2023/11/15 20:00:39 DEBUG Create work directory for archiving: /tmp/elastic-package-1799526892/dga-2.0.1
  | 2023/11/15 20:00:39 DEBUG Validating built .zip package (path: /opt/buildkite-agent/builds/bk-agent-prod-gcp-1700078074357728088/elastic/integrations/build/packages/dga-2.0.1.zip)
  | 2023/11/15 20:00:39 DEBUG POST https://127.0.0.1:5601/api/fleet/epm/packages
  | Error: can't install the package: could not zip-install package; API status code = 429; response body = {"statusCode":429,"error":"Too Many Requests","message":"[parent] Data too large, data for [<http_request>] would be [1029186428/981.5mb], which is larger than the limit of [1020054732/972.7mb], real usage: [935794648/892.4mb], new bytes reserved: [93391780/89mb], usages [inflight_requests=93391780/89mb, request=0/0b, fielddata=288/288b, eql_sequence=0/0b, model_inference=246784104/235.3mb]: circuit_breaking_exception\n\tRoot causes:\n\t\tcircuit_breaking_exception: [parent] Data too large, data for [<http_request>] would be [1029186428/981.5mb], which is larger than the limit of [1020054732/972.7mb], real usage: [935794648/892.4mb], new bytes reserved: [93391780/89mb], usages [inflight_requests=93391780/89mb, request=0/0b, fielddata=288/288b, eql_sequence=0/0b, model_inference=246784104/235.3mb]"}
  | [dga] run_tests_package failed
  | Collect Elastic stack logs
  | 2023/11/15 20:00:46  WARN CommitHash is undefined, in both /opt/buildkite-agent/.elastic-package/version and the compiled binary, config may be out of date.
```

When I spin up a local stack to test, I can install DGA however:

![Screenshot 2023-11-15 at 2 58 51 PM](https://github.com/elastic/integrations/assets/23287722/7ef12150-184d-4aaa-be83-9fd98b8c4cf5)

![Screenshot 2023-11-15 at 2 52 30 PM](https://github.com/elastic/integrations/assets/23287722/7cb0560b-ee17-4b95-9c53-1563e05e5e6d)

The other packages are fine as well on Buildkite. Might test again later to see if the tests can succeed.

2023-11-15 20:47 UTC, droberts195 commented
> Buildkite's showing this error for DGA

It looks like BuildKite is testing with a small ES node (1GB JVM heap) and there's too much going on simultaneously for that size of node. I don't think the changes in this PR caused this.

2023-11-15 21:40 UTC, susan-shu-c commented
Sounds good, won't merge today (Nov 14) end of day, but aiming for tomorrow morning (Nov 15) to try again and merge. But otherwise this should be good.

2023-11-16 14:08 UTC, merged

2023-11-17 10:31 UTC, elasticmachine commented
Package ded - 2.1.1 containing this change is available at https://epr.elastic.co/search?package=ded

2023-11-17 10:38 UTC, elasticmachine commented
Package dga - 2.0.1 containing this change is available at https://epr.elastic.co/search?package=dga

2023-11-17 10:43 UTC, elasticmachine commented
Package lmd - 2.1.2 containing this change is available at https://epr.elastic.co/search?package=lmd

2023-11-17 10:48 UTC, elasticmachine commented
Package problemchild - 2.1.1 containing this change is available at https://epr.elastic.co/search?package=problemchild