[apache_tomcat.access] Restructure Grok pattern and ingest pipeline to improve performance
elastic/integrations pull request #8615
Opened 2023-11-30 11:40 UTC by SimonAtElastic

The customer is using this Integration on an ESS and had ~10-14ms per doc average processing Time.
![image](https://github.com/elastic/integrations/assets/145989254/b3938936-386e-470a-8fbf-2cadeff0f8ef)
After taking a look at the pipeline definition I recognised the "inefficient" way how the grok processing is done.
First test of restructuring the grok process (without changing what it is doing, just how it is done) I had an average of 0-5-0.-7ms, so a huge performance improvement with just a little restructuring.
![image](https://github.com/elastic/integrations/assets/145989254/e2a3b9a1-c779-4851-b322-a0e0d2da1aff)

2023-11-30 11:55 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8615/detail/PR-8615/2//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8615/detail/PR-8615/2//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8615/detail/PR-8615/2//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8615/detail/PR-8615/2//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_8615.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-11-30T11:32:47.705Z&rangeTo=2023-11-30T11:52:47.705Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=722d687c26ca0b6a1d667ec8672f4b6e&transactionId=63fd4f018a181336)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-11-30T11:42:47.705+0000


* Duration: 13 min 37 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![5](https://img.shields.io/badge/5%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8615/detail/PR-8615/2//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Load a resource file from a library`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8615/runs/2/steps/81/log/?start=0">here</a></li>
<li>Description: <code>approval-list/elastic/integrations.yml</code></l1>
</ul>
  
  
  
  
##### `Check integration: apache_tomcat`
<ul>
<li>Took 0 min 2 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8615/runs/2/steps/1200/log/?start=0">here</a></li>
<li>Description: <code>../../build/elastic-package check -v</code></l1>
</ul>
  
  
  
  
##### `Take down the Elastic stack`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8615/runs/2/steps/1219/log/?start=0">here</a></li>
<li>Description: <code>build/elastic-package stack down -v</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8615/runs/2/steps/1239/log/?start=0">here</a></li>

</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8615/runs/2/steps/1252/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-11-30 11:56 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`8/8`) | :green_heart: 
Files | 100.0% (`8/8`) | :green_heart: 13.636
Classes | 100.0% (`8/8`) | :green_heart: 13.636
Methods | 95.238% (`40/42`) | :+1: 11.905
Lines | 81.563% (`814/998`) | :-1: -3.458
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-11-30 17:12 UTC, ishleenk17 reviewed
Some nits. Otherwise the change looks good. Thanks

2023-11-30 17:12 UTC, ishleenk17 commented on packages/apache_tomcat/manifest.yml
> +version: "1.0.1"
Since its an enhancement, lets have it as 1.1.0

2023-11-30 17:12 UTC, ishleenk17 commented on packages/apache_tomcat/changelog.yml
> +    - description: Improve apacht_tomcat.access pipeline performance
```suggestion
    - description: Improve apache_tomcat.access pipeline performance
```

2023-11-30 18:39 UTC, shmsr requested changes

2023-11-30 18:39 UTC, shmsr commented on packages/apache_tomcat/data_stream/access/elasticsearch/ingest_pipeline/default.yml
> +        - '(?:%{IP:apache_tomcat.access.ip.local}%{SPACE})?(?:%{CONN_STATUS:apache_tomcat.access.connection_status}%{SPACE})?(?:%{NUMBER:apache_tomcat.access.response_time}%{SPACE})?\"%{DATA:http.req
Shouldn't `X-Forwarded-For ...` be in an optional group? For this one:
```
'^(%{IP:source.ip}|%{DATA:source.user.name}) %{DATA:apache_tomcat.access.http.ident} %{DATA:apache_tomcat.access.http.useragent} \[%{DATA:_tmp.timestamp}\] \"%{DATA:http.request.method} %{DATA:url.original} HTTP\/%{DATA:http.version}\" %{NUMBER:http.response.status_code} %{DATA:destination.bytes} \"%{DATA:http.request.referrer}\" \"%{DATA:user_agent.original}(\")*$'
```

2023-11-30 18:39 UTC, shmsr commented on packages/apache_tomcat/data_stream/access/elasticsearch/ingest_pipeline/default.yml
> +        - '^(%{IP:source.ip}|%{DATA:source.user.name}) %{DATA:apache_tomcat.access.http.ident} %{DATA:apache_tomcat.access.http.useragent} \[%{DATA:_tmp.timestamp}\] \"%{DATA:http.request.method} %{D
```suggestion
        - '^(%{IP:source.ip}|%{DATA:source.user.name}) %{DATA:apache_tomcat.access.http.ident} %{DATA:apache_tomcat.access.http.useragent} \[%{HTTPDATE:_tmp.timestamp}\] \"%{WORD:http.request.method} %{URI:url.original} HTTP\/%{DATA:http.version}\" %{NUMBER:http.response.status_code} %{POSINT:destination.bytes}( %{GREEDYDATA:_tmp_grok})?$'
```

I didn't test it but these changes could further improve perf? 

Ref: https://github.com/hpcugent/logstash-patterns/blob/master/files/grok-patterns

2023-11-30 18:46 UTC, shmsr commented on packages/apache_tomcat/data_stream/access/elasticsearch/ingest_pipeline/default.yml
> +      field: _tmp_grok
What if we rename this field to `_tmp.grok`? Then the `remove` processor for `_tmp` will delete it at once and 1 less call to remove will be made?

```
- remove:
      field:
        - _tmp
      ignore_missing: true
```

Already present.

2023-11-30 21:44 UTC, SimonAtElastic commented on packages/apache_tomcat/data_stream/access/elasticsearch/ingest_pipeline/default.yml
> +        - '(?:%{IP:apache_tomcat.access.ip.local}%{SPACE})?(?:%{CONN_STATUS:apache_tomcat.access.connection_status}%{SPACE})?(?:%{NUMBER:apache_tomcat.access.response_time}%{SPACE})?\"%{DATA:http.req
not sure about that. As i don't know the logs in detail in enough to confidentaly answer this and the Integrations works so far, i would tend to keep it as is it so far.

2023-11-30 21:52 UTC, SimonAtElastic reviewed
fixed/comment all suggestions

2023-12-01 05:50 UTC, shmsr approved these changes

2023-12-01 10:17 UTC, harnish-elastic approved these changes
LGTM!

2023-12-01 10:48 UTC, merged