Add support for tags, processors and the preserve_original_event to mysql
elastic/integrations pull request #8650
Opened 2023-12-05 08:13 UTC by ritalwar

## Proposed commit message

This PR adds tags, processors, and `preserve_original_event` to MySQL's error and slowlog datastreams. 
It also updates pipelines to rename the `message` field to `event.original` and handle cases where tags contain `preserve_original_event`.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Closes #8626 

## Screenshots

2023-12-05 08:30 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8650/detail/PR-8650/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8650/detail/PR-8650/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8650/detail/PR-8650/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8650/detail/PR-8650/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_8650.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-12-05T08:03:29.873Z&rangeTo=2023-12-05T08:23:29.873Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=40258729c73a154680d9db7362a3c961&transactionId=ac97280bcdc3351f)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-12-05T08:13:29.873+0000


* Duration: 17 min 33 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![3](https://img.shields.io/badge/3%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8650/detail/PR-8650/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Test integration: mysql`
<ul>
<li>Took 1 min 5 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8650/runs/1/steps/1229/log/?start=0">here</a></li>
<li>Description: <code>                                eval "$(../../build/elastic-package stack shellinit)"                                ../../build/elastic-package test -v --report-format xUnit --report-output file --test-coverage                                </code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8650/runs/1/steps/1297/log/?start=0">here</a></li>

</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8650/runs/1/steps/1310/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-12-05 09:00 UTC, ritalwar commented
/test

2023-12-06 07:14 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`0/0`) | :green_heart: 
Files | 100.0% (`0/0`) | :green_heart: 
Classes | 100.0% (`0/0`) | :green_heart: 
Methods | 66.667% (`2/3`) | :grey_exclamation: 
Lines | 100.0% (`0/0`) | :green_heart: 
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-12-08 11:55 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2023-12-12 13:20 UTC, muthu-mps approved these changes
LGTM!

2023-12-13 08:35 UTC, ritalwar commented on packages/mysql/data_stream/error/elasticsearch/ingest_pipeline/default.yml
> +    if: 'ctx.event?.original == null'
I modified the code to eliminate the message field when even.original is not null. 
It's better to keep the removal separate since it differs based on the condition.

> If there is a case where 'ctx.event?.original != null' then message field will not be renamed to event.original, and it will be present in the final document since we are removing event.original and not message field. So should we consider removing message field?

Please refer to this [comment](https://github.com/elastic/integrations/pull/8621/files/c2b1455fb30875f2ad7dfe8e2366d6e8132b608a#r1411622915).

2023-12-15 06:41 UTC, niraj-elastic requested changes
Everything else LGTM apart from this [comment](https://github.com/elastic/integrations/pull/8650#discussion_r1425097391).

2023-12-21 09:41 UTC, mrodm commented
Hi @ritalwar, please update your branch with the latest contents from main branch. There was an important PR merged updating the CI pipelines. Thanks!

2023-12-26 12:40 UTC, ritalwar commented on packages/mysql/data_stream/error/elasticsearch/ingest_pipeline/default.yml
> +    if: 'ctx.event?.original == null'
From my understanding, the fields "message" and "event.original" serve the same purpose and contain identical information. To maintain consistency across integrations, we use "event.original" and rename the initial "message" field after data leaves the beat or agent.  ingest pipeline relies on "event.original," allowing us to repurpose the "message" field for other values.

However, here, removing the "message" field could be breaking change for users, so, in line with the suggestion, I agree to add a set processor to duplicate the "message" field into "event.original." 

There's also a helpful discussion [thread](https://github.com/elastic/integrations/issues/4733) regarding "event.original" .

2023-12-26 12:41 UTC, ritalwar commented on packages/mysql/data_stream/error/elasticsearch/ingest_pipeline/default.yml
> +    if: 'ctx.event?.original == null'
@ishleenk17 @lalit-satapathy  Thoughts?

2023-12-28 07:39 UTC, niraj-elastic commented on packages/mysql/data_stream/error/elasticsearch/ingest_pipeline/default.yml
> +    if: 'ctx.event?.original == null'
I see your point. Although the `event.orignal` field is derived from `message` they both are not the same all the time. In scenarios where `message` field is explicitly fetched from the raw log, the purpose for [`event.orignal`](https://www.elastic.co/guide/en/beats/filebeat/current/exported-fields-ecs.html#:~:text=(before%20splitting%20it%20up%20in%20multiple%20parts)) and [`message`](https://www.elastic.co/guide/en/beats/filebeat/current/exported-fields-ecs.html#:~:text=bar%22%2C%20%22env%22%3A%20%22production%22%7D-,message,-For%20log%20events) field would differ. [Here ](https://github.com/elastic/integrations/blob/8d8b2a15235984d36369a6741cb68d68dca45878/packages/aws/data_stream/ec2_logs/sample_event.json#L56C6-L56C14)is one example of AWS package which seems to be similar to our implementation.

2023-12-29 06:21 UTC, niraj-elastic commented on packages/mysql/data_stream/slowlog/elasticsearch/ingest_pipeline/default.json
> -    {
In slowlog data stream `message` is not explicitly fetched from raw log unlike error data stream, so I don't think we need to keep `message` field here since `event.orignal` is more proper for preserving the original log, and keeping both field would result in duplication as the value of both the fields will always be same, unlike error datastream.

2023-12-29 06:44 UTC, ritalwar commented on packages/mysql/data_stream/slowlog/elasticsearch/ingest_pipeline/default.json
> -    {
In that scenario, I believe renaming from "message" to "event.original" would be a better choice, and there might not be a need to remove the "message" field at all.

2023-12-29 06:46 UTC, niraj-elastic commented on packages/mysql/data_stream/slowlog/elasticsearch/ingest_pipeline/default.json
> -    {
Agree

2024-01-02 06:21 UTC, niraj-elastic approved these changes

2024-01-02 06:21 UTC, niraj-elastic commented
LGTM!

2024-01-02 07:01 UTC, merged

2024-01-02 07:14 UTC, elasticmachine commented
Package mysql - 1.17.0 containing this change is available at https://epr.elastic.co/search?package=mysql