Add backport
elastic/integrations pull request #8735
Opened 2023-12-14 10:24 UTC by sharbuz

## What is the problem this PR solves?

Add backport pipeline

## How does this PR solve the problem?

Add backport pipeline with backport script

## Related issues

https://github.com/elastic/integrations/issues/8721

2023-12-14 11:44 UTC, elasticmachine commented
### :rocket: Benchmarks report


























































































































































































































































































































































































To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2023-12-14 12:51 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8735/detail/PR-8735/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8735/detail/PR-8735/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8735/detail/PR-8735/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8735/detail/PR-8735/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_8735.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-12-14T10:15:03.528Z&rangeTo=2023-12-14T10:35:03.528Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=c4e4740038bf26c2a99ea70a32328926&transactionId=5e9c28b07d8e4cea)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-12-14T10:25:03.528+0000


* Duration: 146 min 42 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 5101  |
| Skipped      | 6 |
| Total        | 5107   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![3](https://img.shields.io/badge/3%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8735/detail/PR-8735/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Test integration: aws`
<ul>
<li>Took 65 min 11 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8735/runs/1/steps/22176/log/?start=0">here</a></li>
<li>Description: <code>                                eval "$(../../build/elastic-package stack shellinit)"                                ../../build/elastic-package test -v --report-format xUnit --report-output file --test-coverage                                </code></l1>
</ul>
  
  
  
  
##### `Test integration: vsphere`
<ul>
<li>Took 1 min 47 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8735/runs/1/steps/22270/log/?start=0">here</a></li>
<li>Description: <code>                                eval "$(../../build/elastic-package stack shellinit)"                                ../../build/elastic-package test -v --report-format xUnit --report-output file --test-coverage                                </code></l1>
</ul>
  
  
  
  
##### `elastic-package report benchmark`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8735/runs/1/steps/51117/log/?start=0">here</a></li>
<li>Description: <code>elastic-package report benchmark --fail-on-missing=false --new="build/benchmark-results" --old="build/main/benchmark-results" --threshold=15 --report-output-path="report.md" --full=false</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-12-14 12:51 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`473/473`) | :green_heart: 
Files | 96.076% (`808/841`) | :-1: -0.036
Classes | 96.076% (`808/841`) | :-1: -0.036
Methods | 92.413% (`7856/8501`) | :+1: 0.107
Lines | 88.632% (`185778/209605`) | :-1: -0.112
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-12-18 12:44 UTC, mrodm commented on .buildkite/scripts/backport_branch.sh
> +if ! -z "$BASE_COMMIT"; then
There is an error here in the output:
https://buildkite.com/elastic/integrations-backport/builds/15#018c6d8c-9091-462c-a643-a03e140a6436/71-75

I think it's missing square brackets: 
```suggestion
if [ ! -z "$BASE_COMMIT" ]; then
```

2023-12-18 12:44 UTC, mrodm commented on .buildkite/scripts/backport_branch.sh
> +fi
The version that users need to introduce for the package is just the major and minor numbers, without the patch version. Related docs: https://github.com/elastic/integrations/blob/main/docs/developer_workflow_bug_fix_older_package_version.md

For instance , in this build https://buildkite.com/elastic/integrations-backport/builds/15#018c6d8c-9091-462c-a643-a03e140a6436/71-100 the backport branch would be `backport-vsphere-1.10`

That version for that package is not going to be published. So I would say this check could be removed, WDYT @jsoriano?

2023-12-18 12:44 UTC, mrodm commented on .buildkite/scripts/backport_branch.sh
> +processFifes() {
What about renaming this function to `updateBackportBranch` ?

Currently, this function is updating `.buildkite` and `.ci` folders, and remove (optionally) all the other packages.

2023-12-18 12:44 UTC, mrodm commented on .buildkite/scripts/backport_branch.sh
> +  if git checkout -b $branch_name $source_commit; then
Nit. 
```suggestion
  if git checkout -b "$branch_name" "$source_commit"; then
```

2023-12-18 12:44 UTC, mrodm commented on .buildkite/scripts/backport_branch.sh
> +  local searchResult="$(git branch --contains $commit_sha | grep $branch | awk '{print $2}')"
To avoid hidden errors, this should be separated:

```suggestion
  local searchResult=""
  searchResult="$(git branch --contains "$commit_sha" | grep "$branch" | awk '{print $2}')"
```

2023-12-18 12:44 UTC, mrodm commented on .buildkite/scripts/backport_branch.sh
> +  local responseCode=$(curl -s -o /dev/null -w "%{http_code}" "https://package-storage.elastic.co/artifacts/packages/${packageZip}")
Nit. Separate commands to avoid hidden errors:

```suggestion
  local responseCode
  responseCode=$(curl -s -o /dev/null -w "%{http_code}" "https://package-storage.elastic.co/artifacts/packages/${packageZip}")
```

2023-12-18 12:44 UTC, mrodm commented on .buildkite/scripts/backport_branch.sh
> +  local searchResult="$(git branch | grep $branch | awk '{print $2}')"
Nit. Avoid hidden errors

```suggestion
  local searchResult=""
  searchResult="$(git branch | grep $branch | awk '{print $2}')"
```

2023-12-18 12:44 UTC, mrodm commented on .buildkite/scripts/backport_branch.sh
> +removeAllPackages() {
Nit. I would rename this function to `removeOtherPackages` , since it is not removing all packages.

Probably, it would be better to just add a parameter with the branch instead of using the global variable `PACKAGE_NAME`.

2023-12-18 12:44 UTC, mrodm commented on .buildkite/scripts/backport_branch.sh
> +    buildkite-agent annotate "The backport branch **$BACKPORT_BRANCH_NAME** hasn't created." --style "warning"
Nit.
```suggestion
    buildkite-agent annotate "The backport branch **$BACKPORT_BRANCH_NAME** hasn't been created." --style "warning"
```

2023-12-18 12:44 UTC, mrodm commented on .buildkite/scripts/backport_branch.sh
> +    echo "The backport branch $branch has already exist"
Nit. 
```suggestion
    echo "The backport branch $branch already exists"
```

2023-12-18 12:44 UTC, mrodm commented on .buildkite/scripts/backport_branch.sh
> +    echo "The backport branch $branch hasn't exist"
Nit. 
```suggestion
    echo "The backport branch $branch does not exist"
```

2023-12-18 12:44 UTC, mrodm commented on .buildkite/scripts/backport_branch.sh
> +buildkite-agent annotate "The backport branch: **$BACKPORT_BRANCH_NAME** has created. Folders **.buildkite** and **.ci** have added into the branch." --style "success"
Nit. 
```suggestion
buildkite-agent annotate "The backport branch: **$BACKPORT_BRANCH_NAME** has been created. Folders **.buildkite** and **.ci** are updated into the branch." --style "success"
```

2023-12-18 12:44 UTC, mrodm commented on .buildkite/pipeline.yml
> +        REMOVE_ALL_PACKAGES: "true"
Would it be better to rename this variable to be `REMOVE_OTHER_PACKAGES`? That would be more explicit to what this job would do.

2023-12-18 12:44 UTC, mrodm commented on .buildkite/hooks/pre-command
> +# fi
Indentation
```suggestion
# if [[ "$BUILDKITE_PIPELINE_SLUG" == "integrations-backport" ]]; then
#   if [[ "$BUILDKITE_STEP_KEY" == "create-backport-branch" ]]; then
#     GITHUB_USERNAME_SECRET=$(retry 5 vault kv get -field username ${GITHUB_TOKEN_VAULT_PATH})
#     export GITHUB_USERNAME_SECRET
#     GITHUB_EMAIL_SECRET=$(retry 5 vault kv get -field email ${GITHUB_TOKEN_VAULT_PATH})
#     export GITHUB_EMAIL_SECRET
#     GITHUB_TOKEN_SECRET=$(retry 5 vault kv get -field token ${GITHUB_TOKEN_VAULT_PATH})
#     export GITHUB_TOKEN_SECRET
#   fi
# fi
```

2023-12-18 12:44 UTC, mrodm commented on .buildkite/scripts/backport_branch.sh
> +  buildkite-agent annotate "The package version: **$FULL_PACKAGE_NAME** hasn't published yet." --style "warning"
```suggestion
  buildkite-agent annotate "The package version: **$FULL_PACKAGE_NAME** hasn't been published yet." --style "warning"
```

2023-12-18 12:44 UTC, mrodm commented on .buildkite/scripts/backport_branch.sh
> +  git checkout $SOURCE_BRANCH -- $JENKINS_FOLDER_PATH
Nit. 
```suggestion
  echo "Copying $BUILDKITE_FOLDER_PATH from $SOURCE_BRANCH..."
  git checkout $SOURCE_BRANCH -- $BUILDKITE_FOLDER_PATH
  echo "Copying $JENKINS_FOLDER_PATH from $SOURCE_BRANCH..."
  git checkout $SOURCE_BRANCH -- $JENKINS_FOLDER_PATH
```

2023-12-18 12:44 UTC, mrodm commented on .buildkite/scripts/backport_branch.sh
> +echo "Check if commit exists."
```suggestion
echo "Check if base commit exists."
```

2023-12-18 13:40 UTC, sharbuz commented on .buildkite/scripts/backport_branch.sh
> +if ! -z "$BASE_COMMIT"; then
fixed.

2023-12-18 13:40 UTC, sharbuz commented on .buildkite/scripts/backport_branch.sh
> +processFifes() {
changed

2023-12-18 13:40 UTC, sharbuz commented on .buildkite/scripts/backport_branch.sh
> +  if git checkout -b $branch_name $source_commit; then
fixed.

2023-12-18 13:40 UTC, sharbuz commented on .buildkite/scripts/backport_branch.sh
> +  local searchResult="$(git branch --contains $commit_sha | grep $branch | awk '{print $2}')"
changed

2023-12-18 13:49 UTC, sharbuz commented on .buildkite/scripts/backport_branch.sh
> +removeAllPackages() {
changed
added

2023-12-18 13:49 UTC, sharbuz commented on .buildkite/scripts/backport_branch.sh
> +    buildkite-agent annotate "The backport branch **$BACKPORT_BRANCH_NAME** hasn't created." --style "warning"
canged

2023-12-18 13:50 UTC, sharbuz commented on .buildkite/scripts/backport_branch.sh
> +    echo "The backport branch $branch has already exist"
changed

2023-12-18 13:50 UTC, sharbuz commented on .buildkite/scripts/backport_branch.sh
> +    echo "The backport branch $branch hasn't exist"
changed

2023-12-18 13:50 UTC, sharbuz commented on .buildkite/scripts/backport_branch.sh
> +buildkite-agent annotate "The backport branch: **$BACKPORT_BRANCH_NAME** has created. Folders **.buildkite** and **.ci** have added into the branch." --style "success"
changed to
```suggestion
buildkite-agent annotate "The backport branch: **$BACKPORT_BRANCH_NAME** has been created. Folders **.buildkite** and **.ci** are updated in the branch." --style "success"
```

2023-12-18 13:50 UTC, sharbuz commented on .buildkite/pipeline.yml
> +        REMOVE_ALL_PACKAGES: "true"
changed

2023-12-18 13:53 UTC, sharbuz commented on .buildkite/hooks/pre-command
> +# fi
I'm not sure we have to use it.
I suppose the BK pipeline already has access to the repo. I would finish with the remarks and test it without these lines...
WDYTm @mrodm ?

2023-12-18 13:53 UTC, sharbuz commented on .buildkite/scripts/backport_branch.sh
> +  buildkite-agent annotate "The package version: **$FULL_PACKAGE_NAME** hasn't published yet." --style "warning"
changed

2023-12-18 13:53 UTC, sharbuz commented on .buildkite/scripts/backport_branch.sh
> +  git checkout $SOURCE_BRANCH -- $JENKINS_FOLDER_PATH
added

2023-12-18 13:53 UTC, sharbuz commented on .buildkite/scripts/backport_branch.sh
> +echo "Check if commit exists."
added

2023-12-18 13:57 UTC, sharbuz commented on .buildkite/scripts/backport_branch.sh
> +  local searchResult="$(git branch | grep $branch | awk '{print $2}')"
changed

2023-12-18 15:48 UTC, sharbuz commented on .buildkite/scripts/backport_branch.sh
> +fi
I've fixed the branch naming. Please take a look at it again.
I have only one question:
If we enter the package version 2.22 (not 2.22.0) I'll receive an error of checking the published package, because of the wrong version. 
In this case, we have to enter the full version of the package to check it in EPR.
Am I right or do I have to add additional checking of the version and add extra zeroes to complete the version?
@jsoriano @mrodm WDYT?

2023-12-18 17:32 UTC, mrodm commented on .buildkite/scripts/backport_branch.sh
> +fi
We were talking about this @jsoriano and me.
This depends on what we request to the users to introduce as parameters to run this pipeline:

1. If we request to introduce the base-commit, package name and just the major.minor version (without the third number patch), it cannot be tested if the package is published or not, since version X.Y would not exist (it is missing the third number).
    - Should we require to introduce the complete version to the users ? and, create the backport branch with just the major and minor numbers ?
    - Should we check that the version introduced is the one in `package/<package>/manifest.yml` ? Not tested... 
      ```shell
      # check version and PACKAGE_VERSION are equal
      version=$(cat packages/<package>/manifest.yml | yq -r .version)
      if [[ ${version} != ${PACKAGE_NAME} ]]; then
         # fail
      fi
      
      # check that this changeset is the one creating the version $PACKAGE_NAME
      if ! git show -p ${BASE_COMMIT} packages/$PACKAGE_NAME/manifest.yml | grep -E "^\+version: ${PACKAGE_VERSION}" ; then
        # fail
      fi
      ```
3. If we request to introduce the package and the package version (full version X.Y.Z) where the backport branch is going to be created (without base-commit), then it can be tested. The issue here is that the pipeline would need to look for the changeset where that version X.Y.Z was published and create the backport branch using that commit as base. This option would be easy for the developers since they would not have to look for the commit.

If we try to do this last option (2), would it be possible to get the changeset given the package name and package version ? 

Maybe something like this ? 
```shell
 $ git log -S "^version: 2.9.1" --pickaxe-regex --pretty=format:"%h" packages/aws/manifest.yml 
32100cb9a
98aa53bd2

# 32100cb9a -> update from 2.9.1 to 2.10.0
# 98aa53bd2 -> update from 2.9.0 to 2.9.1

 $ git log -S "^version: 2.9.1" --pickaxe-regex --pretty=format:"%h" packages/aws/manifest.yml | tail -n 1
98aa53bd2
```

Not sure if that would for all the scenarios.


WDYT ? @jsoriano @sharbuz 
What option would it be better ? Maybe starting with (1) adding those checks about being updated the version in the given BASE_COMMIT?

2023-12-19 10:02 UTC, sharbuz commented on .buildkite/scripts/backport_branch.sh
> +fi
I'm not sure about the second suggestion, because the developers should have opportunities to define the `BASE_COMMIT`.  There are risks of wrong defining the `BASE_COMMIT` automatically.
In this case, we have some options:
1. Document the commands to help the developers with defining `BASE_COMMIT`
2. Make the pipeline more interactive: 
 - input step with the defining `package_name` and `package_version`
 - dynamically generated input step with results of looking for the BASE_COMMIT - waiting for the approval. In this step, we can also show the result of checking the `package_name` and `package_version` and propose changing them if they are wrong.
 - work with creating the backport branch.
 @jsoriano @mrodm WDYT?

2023-12-19 11:44 UTC, mrodm commented on .buildkite/scripts/backport_branch.sh
> +fi
There are some steps in the docs to help finding the base commit here
https://github.com/elastic/integrations/blob/main/docs/developer_workflow_bug_fix_older_package_version.md

Maybe this can be improved with some other command ? 

I think we can continue with the approach of having the developers to set the commit now. There are chances to find the wrong commit automatically. @jsoriano ?

2023-12-19 11:45 UTC, mrodm commented on .buildkite/scripts/backport_branch.sh
> +FULL_ZIP_PACKAGE_NAME="${PACKAGE_NAME}-${PACKAGE_VERSION}.zip"
As we rely on having an umber in PACKAGE_VERSION like `X.Y.Z`.
I think it would be needed to ensure that this variable contains an string like that @sharbuz 

If it is introduced for instance just `X.Y` , then the value `TRIMED_PACKAGE_VERSION` would be wrong.

2023-12-19 12:32 UTC, jsoriano commented on .buildkite/scripts/backport_branch.sh
> +fi
> There are some steps in the docs to help finding the base commit here https://github.com/elastic/integrations/blob/main/docs/developer_workflow_bug_fix_older_package_version.md
> 
> Maybe this can be improved with some other command ?
> 
> I think we can continue with the approach of having the developers to set the commit now. There are chances to find the wrong commit automatically. @jsoriano ?

SGTM, we can add the automatic search of the commit later.

2023-12-19 14:31 UTC, sharbuz commented on .buildkite/scripts/backport_branch.sh
> +FULL_ZIP_PACKAGE_NAME="${PACKAGE_NAME}-${PACKAGE_VERSION}.zip"
added

2023-12-19 18:56 UTC, mrodm commented on .buildkite/scripts/backport_branch.sh
> +  if ! isCommitExist "$BASE_COMMIT" "$SOURCE_BRANCH"; then
Nit. I would rename this function

```suggestion
  if ! doesCommitExist "$BASE_COMMIT" "$SOURCE_BRANCH"; then
```

or 
```suggestion
  if ! commitExists "$BASE_COMMIT" "$SOURCE_BRANCH"; then
```

or 
```suggestion
  if ! commitPartofBranch "$BASE_COMMIT" "$SOURCE_BRANCH"; then
```

2023-12-19 18:56 UTC, mrodm commented on .buildkite/scripts/backport_branch.sh
> +if ! isBranchExist "$BACKPORT_BRANCH_NAME"; then
Nit. I would rename the function

```suggestion
if ! doesBranchExist "$BACKPORT_BRANCH_NAME"; then
```
or maybe
```suggestion
if ! branchExists "$BACKPORT_BRANCH_NAME"; then
```

2023-12-19 18:56 UTC, mrodm commented on .buildkite/scripts/backport_branch.sh
> +updateBackportBranch
I recall that I already requested to change this function name, but I would add now also a suffix to it:

```suggestion
updateBackportBranchContents
```

2023-12-19 18:56 UTC, mrodm commented on .buildkite/scripts/backport_branch.sh
> +echo "Check if the package has published"
```suggestion
echo "Check if the package is published"
```

2023-12-19 18:56 UTC, mrodm commented on .buildkite/scripts/backport_branch.sh
> +  buildkite-agent annotate "The package version: **${PACKAGE_NAME}-${PACKAGE_VERSION}** hasn't neen published yet." --style "error"
```suggestion
  buildkite-agent annotate "The package version: **${PACKAGE_NAME}-${PACKAGE_VERSION}** hasn't been published yet." --style "error"
```

2023-12-19 19:10 UTC, sharbuz commented on .buildkite/scripts/backport_branch.sh
> +fi
Yes, I've checked it locally. It looks like it's fine.

2023-12-19 19:10 UTC, sharbuz commented on .buildkite/scripts/backport_branch.sh
> +  if ! isCommitExist "$BASE_COMMIT" "$SOURCE_BRANCH"; then
changed

2023-12-19 19:10 UTC, sharbuz commented on .buildkite/scripts/backport_branch.sh
> +echo "Check if the package has published"
changed

2023-12-19 19:10 UTC, sharbuz commented on .buildkite/scripts/backport_branch.sh
> +updateBackportBranch
changed

2023-12-19 19:10 UTC, sharbuz commented on .buildkite/scripts/backport_branch.sh
> +  buildkite-agent annotate "The package version: **${PACKAGE_NAME}-${PACKAGE_VERSION}** hasn't neen published yet." --style "error"
fixed

2023-12-19 19:10 UTC, sharbuz commented on .buildkite/scripts/backport_branch.sh
> +if ! isBranchExist "$BACKPORT_BRANCH_NAME"; then
changed

2023-12-20 10:55 UTC, mrodm commented on .buildkite/scripts/backport_branch.sh
> +fi
If the branch already exists, which version do the developers need to set as parameter? 

The latest published in that branch or the one in the BASE_COMMIT ?

2023-12-20 10:55 UTC, mrodm commented on .buildkite/scripts/backport_branch.sh
> +fi
These checks should be performed over the BASE_COMMIT, no ? 
As it is now, they are performed in main ?

2023-12-20 11:38 UTC, mrodm commented on .buildkite/scripts/backport_branch.sh
> +fi
Thinking about this, if the backport branch already exists we can dismiss these checks and just execute the function in charge of updating the contents of the branch.

WDYT ? @jsoriano @sharbuz

2023-12-20 11:47 UTC, sharbuz commented on .buildkite/scripts/backport_branch.sh
> +fi
updated the logic

2023-12-20 12:42 UTC, mrodm commented on .buildkite/scripts/backport_branch.sh
> +  MSG="The backport branch: **$BACKPORT_BRANCH_NAME** has been updated."
Probably this `else`  block could be removed, since the function `branchExist` already shows a message about it.

```suggestion
```

If not, I would suggest to change this message since the branch has not been updated at this point.

```suggestion
else
  MSG="The backport branch: **$BACKPORT_BRANCH_NAME** is already created."
```

2023-12-20 15:08 UTC, mrodm commented on .buildkite/scripts/backport_branch.sh
> +fi
Thanks!

2023-12-20 15:41 UTC, jsoriano reviewed
This is looking good, added some small suggestions.

2023-12-20 15:41 UTC, jsoriano commented on .buildkite/scripts/backport_branch.sh
> +  git checkout $branch
Nit. No need to checkout for this?

2023-12-20 15:41 UTC, jsoriano commented on .buildkite/scripts/backport_branch.sh
> +  searchResult="$(git branch --contains $commit_sha | grep $branch | awk '{print $2}')"
Nit. We can control the format so we don't need to parse the output. And we can grep with the regexp delimiters to ensure that the branch name matches exactly.
```suggestion
  searchResult="$(git branch --contains $commit_sha --format=%(refname:short) | grep -E ^${branch}$)"
```

2023-12-20 15:41 UTC, jsoriano commented on .buildkite/scripts/backport_branch.sh
> +    echo "The branch $branch_name has created."
```suggestion
    echo "The branch $branch_name has been created."
```

2023-12-20 15:41 UTC, jsoriano commented on .buildkite/scripts/backport_branch.sh
> +    buildkite-agent annotate "The backport branch **$BACKPORT_BRANCH_NAME** hasn't created." --style "warning"
```suggestion
    buildkite-agent annotate "The backport branch **$BACKPORT_BRANCH_NAME** could not be created." --style "warning"
```

2023-12-20 15:41 UTC, jsoriano commented on .buildkite/scripts/backport_branch.sh
> +    echo "Romoveing $JENKINS_FOLDER_PATH from $BACKPORT_BRANCH_NAME..."
```suggestion
    echo "Removing $JENKINS_FOLDER_PATH from $BACKPORT_BRANCH_NAME..."
```

2023-12-20 15:41 UTC, jsoriano commented on catalog-info.yaml
> +          access_level: BUILD_AND_READ
:+1:

2023-12-20 16:47 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8735/detail/PR-8735/53//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8735/detail/PR-8735/53//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8735/detail/PR-8735/53//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8735/detail/PR-8735/53//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_8735.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-12-20T09:48:16.591Z&rangeTo=2023-12-20T10:08:16.591Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=df3ca5334025c55a63307622f15f3445&transactionId=163c0b30a403aaa1)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-12-20T09:58:16.591+0000


* Duration: 404 min 57 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 4757  |
| Skipped      | 9 |
| Total        | 4766   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![39](https://img.shields.io/badge/39%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8735/detail/PR-8735/53//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


> Show only the first 10 steps failures

  
  
  
  
##### `Take down the Elastic stack`
<ul>
<li>Took 0 min 4 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8735/runs/53/steps/23002/log/?start=0">here</a></li>
<li>Description: <code>build/elastic-package stack down -v</code></l1>
</ul>
  
  
  
  
##### `Read JSON from files in the workspace.`
<ul>
<li>Took 8 min 38 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8735/runs/53/steps/20129/log/?start=0">here</a></li>
<li>Description: <code>[2023-12-20T11:36:00.586Z] fleet-ci-immutable-ubuntu-2004-1703069411062408316 was marked offline: No</code></l1>
</ul>
  
  
  
  
##### `Take down the Elastic stack`
<ul>
<li>Took 0 min 4 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8735/runs/53/steps/23000/log/?start=0">here</a></li>
<li>Description: <code>build/elastic-package stack down -v</code></l1>
</ul>
  
  
  
  
##### `Read yaml from files in the workspace or text.`
<ul>
<li>Took 8 min 42 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8735/runs/53/steps/20144/log/?start=0">here</a></li>
<li>Description: <code>manifest.yml</code></l1>
</ul>
  
  
  
  
##### `Take down the Elastic stack`
<ul>
<li>Took 0 min 3 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8735/runs/53/steps/23014/log/?start=0">here</a></li>
<li>Description: <code>build/elastic-package stack down -v</code></l1>
</ul>
  
  
  
  
##### `Read JSON from files in the workspace.`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8735/runs/53/steps/20163/log/?start=0">here</a></li>
<li>Description: <code>[2023-12-20T11:36:04.512Z] fleet-ci-immutable-ubuntu-2004-1703070270030666614 was marked offline: No</code></l1>
</ul>
  
  
  
  
##### `Take down the Elastic stack`
<ul>
<li>Took 0 min 3 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8735/runs/53/steps/22962/log/?start=0">here</a></li>
<li>Description: <code>build/elastic-package stack down -v</code></l1>
</ul>
  
  
  
  
##### `Read JSON from files in the workspace.`
<ul>
<li>Took 8 min 9 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8735/runs/53/steps/20170/log/?start=0">here</a></li>
<li>Description: <code>[2023-12-20T11:36:04.690Z] fleet-ci-immutable-ubuntu-2004-1703070270030825072 was marked offline: No</code></l1>
</ul>
  
  
  
  
##### `Take down the Elastic stack`
<ul>
<li>Took 0 min 3 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8735/runs/53/steps/23019/log/?start=0">here</a></li>
<li>Description: <code>build/elastic-package stack down -v</code></l1>
</ul>
  
  
  
  
##### `elastic-package report benchmark`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8735/runs/53/steps/49444/log/?start=0">here</a></li>
<li>Description: <code>elastic-package report benchmark --fail-on-missing=false --new="build/benchmark-results" --old="build/main/benchmark-results" --threshold=15 --report-output-path="report.md" --full=false</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-12-20 17:15 UTC, sharbuz commented on .buildkite/scripts/backport_branch.sh
> +  git checkout $branch
I've changed a bit the logic to avoid this.

2023-12-20 17:16 UTC, sharbuz commented on .buildkite/scripts/backport_branch.sh
> +  searchResult="$(git branch --contains $commit_sha | grep $branch | awk '{print $2}')"
changed

2023-12-20 17:17 UTC, sharbuz commented on .buildkite/scripts/backport_branch.sh
> +    echo "The branch $branch_name has created."
added

2023-12-20 17:18 UTC, sharbuz commented on .buildkite/scripts/backport_branch.sh
> +    buildkite-agent annotate "The backport branch **$BACKPORT_BRANCH_NAME** hasn't created." --style "warning"
changed

2023-12-20 17:18 UTC, sharbuz commented on .buildkite/scripts/backport_branch.sh
> +    echo "Romoveing $JENKINS_FOLDER_PATH from $BACKPORT_BRANCH_NAME..."
fixed

2023-12-20 17:23 UTC, sharbuz commented on .buildkite/scripts/backport_branch.sh
> +  MSG="The backport branch: **$BACKPORT_BRANCH_NAME** has been updated."
fixed MSG
I'm not sure about removing the `else `block.
this block prepares the message for BK annotation. the `branchExist `just shows the echo output to console.

2023-12-20 17:25 UTC, sharbuz commented on .buildkite/scripts/backport_branch.sh
> +  MSG="The backport branch: **$BACKPORT_BRANCH_NAME** has been updated."
@mrodm , WDYT?

2023-12-21 09:40 UTC, mrodm commented
Hi @sharbuz, please update your branch with the latest contents from main branch. There was an important PR merged updating the CI pipelines. Thanks!

2023-12-21 09:53 UTC, mrodm commented on .buildkite/scripts/backport_branch.sh
> +updateBackportBranchContents
This method should be just running when creating branches.

2023-12-21 10:18 UTC, mrodm commented on .buildkite/scripts/backport_branch.sh
> +  MSG="The backport branch: **$BACKPORT_BRANCH_NAME** has been updated."
Ok let's keep the message then.

In any case, we were discussing @jsoriano and me and if the branch is already created, it would be better not updating the contents of the branch. If the branch is already created, let's finish the script here without changing the branch.

All the current backport branches have been already updated manually, so it should not be needed to do that. Let's just update the contents when the branch is created.

2024-01-08 10:48 UTC, mrodm commented on .buildkite/scripts/backport_branch.sh
> +TRIMED_PACKAGE_VERSION=""
Could this line be removed ?
In the next line, this variable gets the value from the command.

```suggestion
```

2024-01-08 10:48 UTC, mrodm commented on .buildkite/scripts/backport_branch.sh
> +PACKAGES_FOLDER_PATH="packages"
Nit.
```suggestion
TRIMMED_PACKAGE_VERSION="$(echo "$PACKAGE_VERSION" | cut -d '.' -f -2)"
SOURCE_BRANCH="main"
BACKPORT_BRANCH_NAME="backport-${PACKAGE_NAME}-${TRIMMED_PACKAGE_VERSION}"
PACKAGES_FOLDER_PATH="packages"
```

2024-01-08 14:11 UTC, sharbuz commented on .buildkite/scripts/backport_branch.sh
> +PACKAGES_FOLDER_PATH="packages"
fixed

2024-01-08 14:11 UTC, sharbuz commented on .buildkite/scripts/backport_branch.sh
> +TRIMED_PACKAGE_VERSION=""
removed

2024-01-08 14:15 UTC, sharbuz commented on .buildkite/scripts/backport_branch.sh
> +updateBackportBranchContents
In my opinion, if we move this method inside the `createLocalBackportBranch` method it'll change the logic of the `createLocalBackportBranch` method and it also has to be renamed. In the current view, it looks logical and consistent. 
@mrodm WDYT?

2024-01-08 14:53 UTC, mrodm commented on .buildkite/scripts/backport_branch.sh
> +updateBackportBranchContents
Currently, all backport branches have been already updated with main branch and also some other fixes have been included in those branches (see https://github.com/elastic/integrations/issues/8721#issuecomment-1867588740 and https://github.com/elastic/integrations/pull/8735/files#r1433866781).

If this pipeline is executed in one of these already backport branches, it will undo those fixes added manually. Therefore, talking offline with @jsoriano , we have decided to not do anything if the backport branch was already present. All new branches should be created using this pipeline, and the PR to update the docs should include some of these fixes that I mention.

If I understand this script as it is, currently this script updates also the branch in case it exists. This could cause that some of those fixes could be undone.

One possible option would be to exit the script in this "else" block https://github.com/elastic/integrations/pull/8735/files#diff-c7c7dc4cc37b0f9da50abfcd71ecfcaa2f7478801a2fc1dbec5de2e49f7e261fR187 and not update contents of the branch.

```shell
if ! branchExist "$BACKPORT_BRANCH_NAME"; then
  # logic if branch does not exist
  ...
else
  MSG="The backport branch: **$BACKPORT_BRANCH_NAME** is already created. Not updating contents of the branch."
  buildkite-agent annotate "$MSG" --style "warning"
  exit 0
fi
```

It could also be re-written that if block as:

```shell
if branchExist "$BACKPORT_BRANCH_NAME"; then
  MSG="The backport branch: **$BACKPORT_BRANCH_NAME** is already created. Not updating contents of the branch."
  buildkite-agent annotate "$MSG" --style "warning"
  exit 0
fi

# backport branch does not exist, running checks and create branch
echo "Check the entered version and PACKAGE_VERSION are equal"
version="$(cat packages/${PACKAGE_NAME}/manifest.yml | yq -r .version)"
if [[ "${version}" != "${PACKAGE_VERSION}" ]]; then
  buildkite-agent annotate "Unexpected version found in packages/${PACKAGE_NAME}/manifest.yml" --style "error"
  exit 1
fi

echo "Check that this changeset is the one creating the version $PACKAGE_NAME"
if ! git show -p ${BASE_COMMIT} packages/${PACKAGE_NAME}/manifest.yml | grep -E "^\+version: ${PACKAGE_VERSION}" ; then
  buildkite-agent annotate "This changeset does not creates the version ${PACKAGE_VERSION}" --style "error"
  exit 1
fi

createLocalBackportBranch "$BACKPORT_BRANCH_NAME" "$BASE_COMMIT"
MSG="The backport branch: **$BACKPORT_BRANCH_NAME** is created."
buildkite-agent annotate "$MSG" --style "success"
```

2024-01-08 15:00 UTC, mrodm commented on .buildkite/scripts/backport_branch.sh
> +  MSG="The backport branch: **$BACKPORT_BRANCH_NAME** is already created."
Nit. To emphasize that the branch has been created in this process/pipeline, this message could be rewritten as:
```suggestion
  MSG="The backport branch: **$BACKPORT_BRANCH_NAME** has been created."
```

2024-01-08 16:24 UTC, sharbuz commented on .buildkite/scripts/backport_branch.sh
> +  MSG="The backport branch: **$BACKPORT_BRANCH_NAME** is already created."
changed

2024-01-08 16:24 UTC, sharbuz commented on .buildkite/scripts/backport_branch.sh
> +updateBackportBranchContents
updated

2024-01-08 16:30 UTC, mrodm approved these changes
Great work @sharbuz!

Just left a comment to move where MSG variable is set in case of creating the local branch has been successful.

2024-01-08 16:30 UTC, mrodm commented on .buildkite/scripts/backport_branch.sh
> +    MSG="The backport branch: **$BACKPORT_BRANCH_NAME** has been created."
Nit. Move setting this `MSG` variable after calling `createLocalBackportBranch` at line 194

2024-01-08 16:54 UTC, jsoriano approved these changes
Nice, thanks!

2024-01-08 16:54 UTC, jsoriano commented on .buildkite/hooks/pre-command
> +
Nit. Extra new line?
```suggestion
```

2024-01-08 16:54 UTC, jsoriano commented on .buildkite/scripts/backport_branch.sh
> +fi
Nit. I wonder if we can create some kind of helper for this code that we use to get variables.
```suggestion
DRY_RUN=$(get_buildkite_metadata DRY_RUN "$DRY_RUN" "true")
```

With an implementation like this one:
```
function get_buildkite_metadata() {
  local var_name=$1
  local current="$2"
  local default="$3"

  if buildkite-agent meta-data exists $var_name; then
    echo "$(buildkite-agent meta-data get $var_name)"
  else
    echo ${current:-$default}
  fi
}
```

2024-01-08 16:54 UTC, jsoriano commented on .buildkite/scripts/backport_branch.sh
> +fi
Or, it seems to be possible to pass default values to this command.
```suggestion
DRY_RUN="$(buildkite-agent meta-data get DRY_RUN --default ${DRY_RUN:-"true"})"
```
https://buildkite.com/docs/agent/v3/cli-meta-data#getting-data

2024-01-08 17:13 UTC, mrodm requested changes

2024-01-08 17:13 UTC, mrodm commented on .buildkite/pipeline.backport.yml
> +      key: "REMOVE_ALL_PACKAGES"
According to the script, this variable should be renamed to:
```suggestion
      key: "REMOVE_OTHER_PACKAGES"
```

2024-01-09 11:25 UTC, sharbuz commented on .buildkite/scripts/backport_branch.sh
> +fi
Thanks @jsoriano, great point!
fixed!

2024-01-09 11:26 UTC, sharbuz commented on .buildkite/hooks/pre-command
> +
removed

2024-01-09 11:26 UTC, sharbuz commented on .buildkite/scripts/backport_branch.sh
> +    MSG="The backport branch: **$BACKPORT_BRANCH_NAME** has been created."
moved

2024-01-09 11:27 UTC, sharbuz commented
I suppose, it would be great to test it again after all changes.
WDYT @mrodm @jsoriano ?

2024-01-09 11:34 UTC, mrodm commented
> I suppose, it would be great to test it again after all changes. WDYT @mrodm @jsoriano ?

Yes, it would be good to test once more. :+1:

2024-01-09 13:21 UTC, sharbuz commented
/test

2024-01-09 15:20 UTC, mrodm approved these changes
Thanks @sharbuz!
:rocket:

2024-01-10 10:53 UTC, merged