[Oracle] Document alternate method of adding runtime library path
elastic/integrations pull request #8754
Opened 2023-12-19 12:28 UTC by agithomas

- Enhancement

## Proposed commit message

Setting the runtime library path is essential for Oracle Integration to work. 
Document additional methods of setting the runtime library path by setting values in elastic-agent configuration. 

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

## How to test this PR locally

- elastic-package build
- elastic-package stack up -v -d --services package-registry

## Related issues

Various SDH issues. 

## Screenshots

![Screenshot 2023-12-19 at 5 12 20 PM](https://github.com/elastic/integrations/assets/101976829/5237b13d-9696-4f50-b3b7-f8bb514e9378)

2023-12-19 12:42 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8754/detail/PR-8754/2//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8754/detail/PR-8754/2//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8754/detail/PR-8754/2//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8754/detail/PR-8754/2//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_8754.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2023-12-19T12:21:26.901Z&rangeTo=2023-12-19T12:41:26.901Z&transactionName=BUILD+Ingest-manager%2Fintegrations%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=4abc0662bb7294402e44d672202eaae0&transactionId=ac23a026e9b90716)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-12-19T12:31:26.901+0000


* Duration: 10 min 29 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![4](https://img.shields.io/badge/4%20-red)](https://fleet-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-8754/detail/PR-8754/2//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Check integration: oracle`
<ul>
<li>Took 0 min 1 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8754/runs/2/steps/1193/log/?start=0">here</a></li>
<li>Description: <code>../../build/elastic-package check -v</code></l1>
</ul>
  
  
  
  
##### `Take down the Elastic stack`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8754/runs/2/steps/1212/log/?start=0">here</a></li>
<li>Description: <code>build/elastic-package stack down -v</code></l1>
</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8754/runs/2/steps/1232/log/?start=0">here</a></li>

</ul>
  
  
  
  
##### `Google Storage Download`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://fleet-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-8754/runs/2/steps/1245/log/?start=0">here</a></li>

</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-12-19 13:02 UTC, elasticmachine commented
### :globe_with_meridians: Coverage report

Name | Metrics % (`covered/total`) | Diff
 --- | --- | ---
Packages | 100.0% (`1/1`) | :green_heart: 
Files | 100.0% (`1/1`) | :green_heart: 
Classes | 100.0% (`1/1`) | :green_heart: 
Methods | 100.0% (`29/29`) | :green_heart: 
Lines | 94.424% (`254/269`) | :-1: -3.64
Conditionals | 100.0% (`0/0`) | :green_heart: 

<!--COMMENT_GENERATED_WITH_ID_coverage-->

2023-12-19 13:24 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2023-12-20 07:44 UTC, shmsr requested changes

2023-12-20 07:44 UTC, shmsr commented on packages/oracle/_dev/build/docs/README.md
> +If the Elastic Agent is running as a systemd service and there are limitations in running `ldconfig` command, you can set the library search path using an alternate method. Follow the steps below to
```suggestion
If Elastic Agent is running as a systemd service and using `ldconfig` is not an option to update the links to the shared libraries, you can use the `LD_LIBRARY_PATH` environment variable instead. Follow these steps to ensure Elastic Agent and its spawned processes respect the `LD_LIBRARY_PATH` environment variable.
```

2023-12-20 07:44 UTC, shmsr commented on packages/oracle/_dev/build/docs/README.md
> +Prerequisites: Ensure that you have administrative privileges to make changes to the Elastic Agent systemd service configuration.
```suggestion
> Prerequisites: Ensure that you have administrative privileges to modify the Elastic Agent systemd service configuration.
```

2023-12-20 07:44 UTC, shmsr commented on packages/oracle/_dev/build/docs/README.md
> +Prerequisites: Ensure that you have administrative privileges to make changes to the Elastic Agent systemd service configuration.
For important stuff like `NOTE/PREREQ./etc`, always use blockquotes.

2023-12-20 07:44 UTC, shmsr commented on packages/oracle/_dev/build/docs/README.md
> +2. Open and view the content of the `elastic-agent.service file` using your preferred text editor. Look for the `EnvironmentFile` key, which is usually empty by default. Example path to the Environme
EnvironmentFile is not empty by default. It already comes prepopulated by default. The file itself is not there, it is important to create one if it doesn't exist.

See this generator file that is used to generate the service file: https://github.com/elastic/elastic-agent/blob/ad7e1b5113ba07d39b23eb06f7b300f0d8c58d82/internal/pkg/agent/install/svc.go#L186

2023-12-20 07:44 UTC, shmsr commented on packages/oracle/_dev/build/docs/README.md
> +2. Open and view the content of the `elastic-agent.service file` using your preferred text editor. Look for the `EnvironmentFile` key, which is usually empty by default. Example path to the Environme
So another step is required to instruct to create the file: `/etc/systemd/system/elastic-agent.service`

2023-12-20 07:44 UTC, shmsr commented on packages/oracle/_dev/build/docs/README.md
> +   `LD_LIBRARY_PATH=/opt/oracle/instantclient_21_1`
```suggestion
3. Add the LD_LIBRARY_PATH environment variable to the configured EnvironmentFile. You can set it to the directory where libraries (`libclntsh.so`) are located. For example, if your libraries are in the /opt/oracle/instantclient_21_1 directory, add the following line to the EnvironmentFile (i.e., `/etc/systemd/system/elastic-agent.service`):
   `LD_LIBRARY_PATH=/opt/oracle/instantclient_21_1`
```

2023-12-20 07:44 UTC, shmsr commented on packages/oracle/_dev/build/docs/README.md
> +4. Save the changes made to the `EnvironmentFile`.
```suggestion
4. Save the changes made to the configured `EnvironmentFile`.
```

2023-12-20 07:44 UTC, shmsr commented on packages/oracle/_dev/build/docs/README.md
> +     `systemctl restart elastic-agent.service`
```suggestion
5. Restart the Elastic Agent systemd service to make Elastic Agent and spawned processes respect the environment variable set by running the following command:
   `systemctl restart elastic-agent.service`
```

2023-12-20 07:44 UTC, shmsr commented on packages/oracle/_dev/build/docs/README.md
> +Note: Ensure that you replace /opt/oracle/instantclient_21_1 with the actual path to the directory where your required libraries (`libclntsh.so`) are located. This will set the library search path fo
```suggestion
> NOTE: Please make sure to replace the `/opt/oracle/instantclient_21_1` with the actual path to the directory where your shared libraries (e.g., `libclntsh.so`) are located. This will enable the dynamic link loader to search for the shared libraries in the configured path for the Elastic Agent and the spawned processes by the same, required by the Oracle integration.
```

2023-12-20 07:44 UTC, shmsr commented on packages/oracle/manifest.yml
> +version: "1.24.0"
As this is only a document change and that too a special case which is mostly for clarification; don't you think a patch release also works?

2023-12-20 07:48 UTC, shmsr commented on packages/oracle/_dev/build/docs/README.md
> +If the Elastic Agent is running as a systemd service and there are limitations in running `ldconfig` command, you can set the library search path using an alternate method. Follow the steps below to
Suggest change is clearer IMO as LD_LIBRARY_PATH is the alternative method. So we are helping our users set environment variables for Elastic Agent and the processes spawned by the same.

2023-12-20 07:51 UTC, shmsr commented on packages/oracle/changelog.yml
> +- version: 1.24.0
As this is only a document change and that too a special case which is mostly for clarification; don't you think a patch release also works?

2023-12-20 10:23 UTC, agithomas commented on packages/oracle/_dev/build/docs/README.md
> +Note: Ensure that you replace /opt/oracle/instantclient_21_1 with the actual path to the directory where your required libraries (`libclntsh.so`) are located. This will set the library search path fo
Thanks for the suggestion. 

1. `libclntsh.so` is the mandatory library. Hence it is not added as an example. 
2. Mentioning the internal working such as spawning, how DLL works  may be beyond the scope of a user readme document.

2023-12-20 10:25 UTC, agithomas commented on packages/oracle/_dev/build/docs/README.md
> +     `systemctl restart elastic-agent.service`
I will prefer to keep the original version. Words like `respect`, may cause confusions. Also, not README must not cover the technical implementation details such as 'process spawning'

2023-12-20 11:36 UTC, shmsr commented on packages/oracle/_dev/build/docs/README.md
> +Note: Ensure that you replace /opt/oracle/instantclient_21_1 with the actual path to the directory where your required libraries (`libclntsh.so`) are located. This will set the library search path fo
1. `libclntsh.so` is not just mandatory but there are other libraries too and that's why I used it in `e.g.,`. Also many libraries are symlinked to one another and that's why the directory is required.  But yes, we can present it in a better way. What if just stick to Instant Client? See [this](https://odpi-c.readthedocs.io/en/latest/user_guide/installation.html#:~:text=Instant%20Client%2019.-,If%20there%20is%20no%20other%20Oracle%20software%20on%20the%20machine%20that%20will%20be%20impacted%2C%20permanently%20add%20Instant%20Client%20to%20the%20runtime%20link%20path,-.%20For%20example%2C%20with); this is best doc for ODPI-C.
2. Spawning part could be meaningful for the user as I am talking about Metricbeat here because Agent. Maybe we can stick with just "Agent"? Also, DLL part can be skipped but the library search path is confusing for the user as well. Shared/ Runtime libraries can be used. What do you think?

2023-12-21 09:40 UTC, mrodm commented
Hi @agithomas, please update your branch with the latest contents from main branch. There was an important PR merged updating the CI pipelines. Thanks!

2023-12-22 06:41 UTC, agithomas commented on packages/oracle/changelog.yml
> +- version: 1.24.0
I did a bit of back and forth between the minor and patch versions. 

Finally, I settled for the minor version. 

The missing docs shadow a whole feature or functionality, which is hardly usable without the documentation.

2023-12-22 06:55 UTC, muthu-mps commented on packages/oracle/_dev/build/docs/README.md
> +If Elastic Agent is running as a systemd service and using `ldconfig` is not an option to update the links to the shared libraries, you can use the `LD_LIBRARY_PATH` environment variable instead. Fol
```suggestion
If Elastic Agent is running as a systemd service and not using `ldconfig` as an option to update the links to the shared libraries, you can use the `LD_LIBRARY_PATH` environment variable instead. Follow these steps to ensure Elastic Agent and its spawned processes respect the `LD_LIBRARY_PATH` environment variable.
```

2023-12-22 06:55 UTC, muthu-mps commented on packages/oracle/_dev/build/docs/README.md
> +> Note: Ensure that you replace `/opt/oracle/instantclient_21_1` with the actual path to the directory where  required libraries (`libclntsh.so`) are located. This will set the library search path fo
```suggestion 
> Note: Ensure that you replace `/opt/oracle/instantclient_21_1` with the actual path to the directory where required libraries (`libclntsh.so`) are located. This will set the library search path for the Elastic Agent service to include the specified directory, allowing it to locate the required libraries.
```

2023-12-22 06:55 UTC, muthu-mps commented on packages/oracle/_dev/build/docs/README.md
> +   `systemctl status elastic-agent.service`
nit: Can we make this syntax spacing aligned with point 3 and 5.

2023-12-22 06:55 UTC, muthu-mps commented on packages/oracle/_dev/build/docs/README.md
> +> Note: Ensure that you replace `/opt/oracle/instantclient_21_1` with the actual path to the directory where  required libraries (`libclntsh.so`) are located. This will set the library search path fo
Removed extra space here.

2023-12-22 10:21 UTC, shmsr commented
LGTM. After @muthu-mps's comments are merged, we can merge this.

2023-12-22 12:32 UTC, agithomas commented
All comments are addressed. @muthu-mps , @shmsr , please approve the PR, if no further changes are needed.

2023-12-22 17:06 UTC, shmsr approved these changes

2024-01-04 05:10 UTC, merged

2024-01-04 05:25 UTC, elasticmachine commented
Package oracle - 1.24.0 containing this change is available at https://epr.elastic.co/search?package=oracle