Rollback CIS Azure rules 9.3 and 9.10
elastic/integrations pull request #8799
Opened 2023-12-27 12:24 UTC by jeniawhite

## Proposed commit message
Due to issues with Azure ARG, we are rollbacking rules that do are not being correctly updated in the ARG.
- https://github.com/elastic/cloudbeat/issues/1420
- https://github.com/elastic/cloudbeat/pull/1715

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Relates https://github.com/elastic/cloudbeat/issues/1420
- Relates https://github.com/elastic/cloudbeat/pull/1715

2023-12-27 12:24 UTC, orestisfl approved these changes

2023-12-27 13:54 UTC, oren-zohar requested changes

2023-12-27 13:54 UTC, oren-zohar commented on packages/cloud_security_posture/changelog.yml
> +- version: "1.8.0-preview05"
shouldn't it be to 1.7.x?

2023-12-27 14:23 UTC, oren-zohar approved these changes

2023-12-27 14:26 UTC, merged

2023-12-27 14:36 UTC, elasticmachine commented
Package cloud_security_posture - 1.8.0-preview05 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2024-02-19 14:33 UTC, elasticmachine commented
Package cloud_security_posture - 1.8.0-preview06 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture

2024-03-11 18:15 UTC, elasticmachine commented
Package cloud_security_posture - 1.8.0 containing this change is available at https://epr.elastic.co/search?package=cloud_security_posture