Add Splunk httpjson input to winlog package
elastic/integrations pull request #884
Opened 2021-04-06 08:16 UTC by marc-gr

## What does this PR do?

Adds Splunk input to winlog custom events package.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.

2021-04-06 10:22 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > Either there was a build timeout or someone aborted the build.'}
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-884/detail/PR-884/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-884/detail/PR-884/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-884/detail/PR-884/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-884/detail/PR-884/1//artifacts) 

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #884 opened`



* Start Time: 2021-04-06T08:18:15.920+0000


* Duration: 124 min 51 sec


* Commit: db30e14c2fff9ba13837b0aa762da2f0f33eedd6




#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/PR-884/buildTimeGraph/png)



</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->











<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-04-06T08:24:58.318Z] + git merge-base origin/master db30e14c2fff9ba13837b0aa762da2f0f33eedd6
[2021-04-06T08:24:58.318Z] + git diff --name-only 36e50f838f5bfa2a4b66369f291b3deca2c9f8f7
[2021-04-06T08:24:58.345Z] [squid] PR is not affected
[2021-04-06T08:24:58.710Z] + egrep -v ^packages/
[2021-04-06T08:24:58.710Z] + git merge-base origin/master db30e14c2fff9ba13837b0aa762da2f0f33eedd6
[2021-04-06T08:24:58.710Z] + git diff --name-only 36e50f838f5bfa2a4b66369f291b3deca2c9f8f7
[2021-04-06T08:24:59.028Z] + egrep ^packages/stan/
[2021-04-06T08:24:59.028Z] + git merge-base origin/master db30e14c2fff9ba13837b0aa762da2f0f33eedd6
[2021-04-06T08:24:59.028Z] + git diff --name-only 36e50f838f5bfa2a4b66369f291b3deca2c9f8f7
[2021-04-06T08:24:59.055Z] [stan] PR is not affected
[2021-04-06T08:24:59.379Z] + egrep -v ^packages/
[2021-04-06T08:24:59.379Z] + git merge-base origin/master db30e14c2fff9ba13837b0aa762da2f0f33eedd6
[2021-04-06T08:24:59.379Z] + git diff --name-only 36e50f838f5bfa2a4b66369f291b3deca2c9f8f7
[2021-04-06T08:24:59.696Z] + egrep ^packages/suricata/
[2021-04-06T08:24:59.696Z] + git merge-base origin/master db30e14c2fff9ba13837b0aa762da2f0f33eedd6
[2021-04-06T08:24:59.696Z] + git diff --name-only 36e50f838f5bfa2a4b66369f291b3deca2c9f8f7
[2021-04-06T08:24:59.724Z] [suricata] PR is not affected
[2021-04-06T08:25:00.048Z] + egrep -v ^packages/
[2021-04-06T08:25:00.048Z] + git merge-base origin/master db30e14c2fff9ba13837b0aa762da2f0f33eedd6
[2021-04-06T08:25:00.048Z] + git diff --name-only 36e50f838f5bfa2a4b66369f291b3deca2c9f8f7
[2021-04-06T08:25:00.365Z] + git merge-base origin/master db30e14c2fff9ba13837b0aa762da2f0f33eedd6
[2021-04-06T08:25:00.365Z] + egrep ^packages/system/
[2021-04-06T08:25:00.365Z] + git diff --name-only 36e50f838f5bfa2a4b66369f291b3deca2c9f8f7
[2021-04-06T08:25:00.394Z] [system] PR is not affected
[2021-04-06T08:25:00.716Z] + egrep -v ^packages/
[2021-04-06T08:25:00.716Z] + git merge-base origin/master db30e14c2fff9ba13837b0aa762da2f0f33eedd6
[2021-04-06T08:25:00.716Z] + git diff --name-only 36e50f838f5bfa2a4b66369f291b3deca2c9f8f7
[2021-04-06T08:25:01.034Z] + egrep ^packages/tomcat/
[2021-04-06T08:25:01.034Z] + git merge-base origin/master db30e14c2fff9ba13837b0aa762da2f0f33eedd6
[2021-04-06T08:25:01.034Z] + git diff --name-only 36e50f838f5bfa2a4b66369f291b3deca2c9f8f7
[2021-04-06T08:25:01.061Z] [tomcat] PR is not affected
[2021-04-06T08:25:01.382Z] + egrep+  -v ^packages/
[2021-04-06T08:25:01.382Z] git merge-base origin/master db30e14c2fff9ba13837b0aa762da2f0f33eedd6
[2021-04-06T08:25:01.382Z] + git diff --name-only 36e50f838f5bfa2a4b66369f291b3deca2c9f8f7
[2021-04-06T08:25:01.694Z] + egrep ^packages/traefik/
[2021-04-06T08:25:01.694Z] + git merge-base origin/master db30e14c2fff9ba13837b0aa762da2f0f33eedd6
[2021-04-06T08:25:01.694Z] + git diff --name-only 36e50f838f5bfa2a4b66369f291b3deca2c9f8f7
[2021-04-06T08:25:01.718Z] [traefik] PR is not affected
[2021-04-06T08:25:02.036Z] + egrep -v ^packages/
[2021-04-06T08:25:02.036Z] + git merge-base origin/master db30e14c2fff9ba13837b0aa762da2f0f33eedd6
[2021-04-06T08:25:02.036Z] + git diff --name-only 36e50f838f5bfa2a4b66369f291b3deca2c9f8f7
[2021-04-06T08:25:02.351Z] + git merge-base origin/master db30e14c2fff9ba13837b0aa762da2f0f33eedd6
[2021-04-06T08:25:02.352Z] + egrep ^packages/windows/
[2021-04-06T08:25:02.352Z] + git diff --name-only 36e50f838f5bfa2a4b66369f291b3deca2c9f8f7
[2021-04-06T08:25:02.380Z] [windows] PR is not affected
[2021-04-06T08:25:02.699Z] + git merge-base origin/master db30e14c2fff9ba13837b0aa762da2f0f33eedd6
[2021-04-06T08:25:02.699Z] + egrep -v ^packages/
[2021-04-06T08:25:02.699Z] + git diff --name-only 36e50f838f5bfa2a4b66369f291b3deca2c9f8f7
[2021-04-06T08:25:03.014Z] + + egrep ^packages/winlog/
[2021-04-06T08:25:03.014Z] git merge-base origin/master db30e14c2fff9ba13837b0aa762da2f0f33eedd6
[2021-04-06T08:25:03.014Z] + git diff --name-only 36e50f838f5bfa2a4b66369f291b3deca2c9f8f7
[2021-04-06T08:25:03.014Z] packages/winlog/changelog.yml
[2021-04-06T08:25:03.014Z] packages/winlog/data_stream/winlog/agent/stream/httpjson.yml.hbs
[2021-04-06T08:25:03.014Z] packages/winlog/data_stream/winlog/fields/winlog.yml
[2021-04-06T08:25:03.014Z] packages/winlog/data_stream/winlog/manifest.yml
[2021-04-06T08:25:03.014Z] packages/winlog/manifest.yml
[2021-04-06T08:25:03.040Z] [winlog] PR is affected: found package files
[2021-04-06T08:25:03.363Z] + egrep -v ^packages/
[2021-04-06T08:25:03.363Z] + git merge-base origin/master db30e14c2fff9ba13837b0aa762da2f0f33eedd6
[2021-04-06T08:25:03.363Z] + git diff --name-only 36e50f838f5bfa2a4b66369f291b3deca2c9f8f7
[2021-04-06T08:25:03.683Z] + egrep ^packages/zeek/
[2021-04-06T08:25:03.683Z] + git merge-base origin/master db30e14c2fff9ba13837b0aa762da2f0f33eedd6
[2021-04-06T08:25:03.683Z] + git diff --name-only 36e50f838f5bfa2a4b66369f291b3deca2c9f8f7
[2021-04-06T08:25:03.711Z] [zeek] PR is not affected
[2021-04-06T08:25:04.031Z] + git merge-base origin/master db30e14c2fff9ba13837b0aa762da2f0f33eedd6
[2021-04-06T08:25:04.031Z] + egrep -v ^packages/
[2021-04-06T08:25:04.031Z] + git diff --name-only 36e50f838f5bfa2a4b66369f291b3deca2c9f8f7
[2021-04-06T08:25:04.347Z] + + egrepgit ^packages/zookeeper/ merge-base
[2021-04-06T08:25:04.347Z]  origin/master db30e14c2fff9ba13837b0aa762da2f0f33eedd6
[2021-04-06T08:25:04.347Z] + git diff --name-only 36e50f838f5bfa2a4b66369f291b3deca2c9f8f7
[2021-04-06T08:25:04.373Z] [zookeeper] PR is not affected
[2021-04-06T08:25:04.695Z] + egrep -v ^packages/
[2021-04-06T08:25:04.695Z] + git merge-base origin/master db30e14c2fff9ba13837b0aa762da2f0f33eedd6
[2021-04-06T08:25:04.695Z] + git diff --name-only 36e50f838f5bfa2a4b66369f291b3deca2c9f8f7
[2021-04-06T08:25:05.009Z] + egrep ^packages/zoom/
[2021-04-06T08:25:05.009Z] + git merge-base origin/master db30e14c2fff9ba13837b0aa762da2f0f33eedd6
[2021-04-06T08:25:05.009Z] + git diff --name-only 36e50f838f5bfa2a4b66369f291b3deca2c9f8f7
[2021-04-06T08:25:05.036Z] [zoom] PR is not affected
[2021-04-06T08:25:05.353Z] + egrep -v ^packages/
[2021-04-06T08:25:05.353Z] + git merge-base origin/master db30e14c2fff9ba13837b0aa762da2f0f33eedd6
[2021-04-06T08:25:05.353Z] + git diff --name-only 36e50f838f5bfa2a4b66369f291b3deca2c9f8f7
[2021-04-06T08:25:05.666Z] + egrep ^packages/zscaler/
[2021-04-06T08:25:05.667Z] + git merge-base origin/master db30e14c2fff9ba13837b0aa762da2f0f33eedd6
[2021 [...]

2021-04-06 20:35 UTC, leehinman reviewed
Looking good.  Couple of questions.

2021-04-06 20:35 UTC, leehinman commented on packages/winlog/data_stream/winlog/agent/stream/httpjson.yml.hbs
> +          to: file.path
Is `file.path` still a good mapping for `result.source` on Windows?  I don't have an event in front of me but I'm guessing the `source` is event channel?

2021-04-06 20:35 UTC, leehinman commented on packages/winlog/data_stream/winlog/agent/stream/httpjson.yml.hbs
> +        - '2020-08-03T07:10:20.123456+02:00'
Does the `winlog.yml.hbs` need this as well?

2021-04-07 09:44 UTC, marc-gr commented on packages/winlog/data_stream/winlog/agent/stream/httpjson.yml.hbs
> +        - '2020-08-03T07:10:20.123456+02:00'
The winlog input uses the `record.ToEvent()` method which creates the event from scratch and already does this

2021-04-07 09:57 UTC, marc-gr commented on packages/winlog/data_stream/winlog/agent/stream/httpjson.yml.hbs
> +          to: file.path
right, I think it might make sense to map it to `event.provider`? wdyt?

2021-04-07 10:12 UTC, marc-gr commented
I am not sure how to handle the `custom` bit here, since we already have processors that are required for parsing, and could be fairly easy to mess them up, any ideas?

2021-04-07 14:40 UTC, leehinman commented on packages/winlog/data_stream/winlog/agent/stream/httpjson.yml.hbs
> +          to: file.path
I agree, `event.provider` seems like the right place.

2021-04-07 14:41 UTC, leehinman commented on packages/winlog/data_stream/winlog/agent/stream/httpjson.yml.hbs
> +        - '2020-08-03T07:10:20.123456+02:00'
:facepalm: right, nevermind.

2021-04-07 14:50 UTC, leehinman commented on packages/winlog/data_stream/winlog/agent/stream/httpjson.yml.hbs
> +      default: '[[(now (parseDuration "-{{initial_interval}}")).Unix]]'
I don't have `initial_interval` on the other Splunk inputs, I just used the `interval`.  Because Splunk doesn't do paging for the results on this endpoint you could request something that would be too large to work.  If we need to pull in historical data, I think other approaches would be better.

If we do go with `initial_interval`, I'd like to add it to all the Splunk inputs.

2021-04-07 14:57 UTC, leehinman commented
> I am not sure how to handle the `custom` bit here, since we already have processors that are required for parsing, and could be fairly easy to mess them up, any ideas?

Do we need `Custom` for this?  You could limit the records returned with the search string, and additional processing could happen in an ingest pipeline.  What do you think?

2021-04-07 15:06 UTC, marc-gr commented on packages/winlog/data_stream/winlog/agent/stream/httpjson.yml.hbs
> +      default: '[[(now (parseDuration "-{{initial_interval}}")).Unix]]'
Got it, do you think is better to remove it for now then?

2021-04-07 16:21 UTC, leehinman commented on packages/winlog/data_stream/winlog/agent/stream/httpjson.yml.hbs
> +      default: '[[(now (parseDuration "-{{initial_interval}}")).Unix]]'
I think so, until we get a good way to get historical data.

2021-04-07 16:27 UTC, leehinman requested changes

2021-04-07 16:27 UTC, leehinman commented on packages/winlog/data_stream/winlog/manifest.yml
> +      - name: initial_interval
we will need a variable for `data_stream.dataset`  and then 
```
data_stream:
  dataset: {{data_stream.dataset}}
```
in the httpjson.yml.hbs file

2021-04-08 14:16 UTC, leehinman approved these changes
Looks great.

2021-04-12 07:28 UTC, merged