[Cisco] Parse additional log types
elastic/integrations pull request #896
Opened 2021-04-07 17:31 UTC by legoguy1000

## What does this PR do?

This PR parses additional log types from https://github.com/elastic/beats/pull/24757 to resolve https://github.com/elastic/beats/issues/24642.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.

## Author's Checklist

- [ ]

## How to test this PR locally

```
cd integrations/packages/cisco
elastic-package build && elastic-package stack up -d --services=elasticsearch && $(elastic-package stack shellinit) && elastic-package test pipeline
```

## Related issues

Relates elastic/beats#24642

## Screenshots

2021-04-07 17:34 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-896/detail/PR-896/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-896/detail/PR-896/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-896/detail/PR-896/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-896/detail/PR-896/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://null_896.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #896 opened`



* Start Time: 2021-04-07T17:32:16.949+0000


* Duration: 2 min 13 sec


* Commit: 8968ea822a47f9f31d86683fb3ad2a9bcb0f8587




#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/PR-896/buildTimeGraph/png)



</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->









### Steps errors [![3](https://img.shields.io/badge/3%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-896/detail/PR-896/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Check out from version control`
<ul>
<li>Took 0 min 4 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-896/runs/1/steps/37/log/?start=0">here</a></li>
<li>Description: <code>[2021-04-07T17:33:08.653Z] The recommended git tool is: git
[2021-04-07T17:33:08.665Z] using creden</code></l1>
</ul>
  
  
  
  
##### `Check out from version control`
<ul>
<li>Took 0 min 4 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-896/runs/1/steps/41/log/?start=0">here</a></li>
<li>Description: <code>[2021-04-07T17:33:32.616Z] The recommended git tool is: git
[2021-04-07T17:33:32.629Z] using creden</code></l1>
</ul>
  
  
  
  
##### `Check out from version control`
<ul>
<li>Took 0 min 4 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-896/runs/1/steps/45/log/?start=0">here</a></li>
<li>Description: <code>[2021-04-07T17:34:06.724Z] The recommended git tool is: git
[2021-04-07T17:34:06.740Z] using creden</code></l1>
</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-04-07T17:33:35.865Z] Cleaning workspace
[2021-04-07T17:33:35.885Z] Using shallow fetch with depth 4
[2021-04-07T17:33:35.885Z] Pruning obsolete local branches
[2021-04-07T17:33:36.526Z] Merging remotes/origin/master commit a10ad0b65b61c65d70b852c478bcd6f5ff4d526e into PR head commit 8968ea822a47f9f31d86683fb3ad2a9bcb0f8587
[2021-04-07T17:33:36.583Z] ERROR: Execution failed
[2021-04-07T17:33:36.583Z] hudson.plugins.git.GitException: Command "git checkout -f 8968ea822a47f9f31d86683fb3ad2a9bcb0f8587" returned status code 128:
[2021-04-07T17:33:36.583Z] stdout: 
[2021-04-07T17:33:36.583Z] stderr: fatal: reference is not a tree: 8968ea822a47f9f31d86683fb3ad2a9bcb0f8587
[2021-04-07T17:33:36.583Z] 
[2021-04-07T17:33:36.583Z] 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2450)
[2021-04-07T17:33:36.583Z] 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$1100(CliGitAPIImpl.java:84)
[2021-04-07T17:33:36.583Z] 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2767)
[2021-04-07T17:33:36.583Z] Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from beats-ci-immutable-ubuntu-2004-1617815290596460269.c.elastic-ci-prod.internal/10.224.3.147:38466
[2021-04-07T17:33:36.583Z] 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
[2021-04-07T17:33:36.583Z] 		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
[2021-04-07T17:33:36.583Z] 		at hudson.remoting.Channel.call(Channel.java:1001)
[2021-04-07T17:33:36.583Z] 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
[2021-04-07T17:33:36.583Z] 		at sun.reflect.GeneratedMethodAccessor864.invoke(Unknown Source)
[2021-04-07T17:33:36.583Z] 		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-04-07T17:33:36.583Z] 		at java.lang.reflect.Method.invoke(Method.java:498)
[2021-04-07T17:33:36.583Z] 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
[2021-04-07T17:33:36.583Z] 		at com.sun.proxy.$Proxy98.execute(Unknown Source)
[2021-04-07T17:33:36.583Z] 		at jenkins.plugins.git.MergeWithGitSCMExtension.checkout(MergeWithGitSCMExtension.java:145)
[2021-04-07T17:33:36.583Z] 		at jenkins.plugins.git.MergeWithGitSCMExtension.decorateRevisionToBuild(MergeWithGitSCMExtension.java:111)
[2021-04-07T17:33:36.583Z] 		at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:1164)
[2021-04-07T17:33:36.583Z] 		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1303)
[2021-04-07T17:33:36.583Z] 		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:125)
[2021-04-07T17:33:36.583Z] 		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:93)
[2021-04-07T17:33:36.583Z] 		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:80)
[2021-04-07T17:33:36.583Z] 		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
[2021-04-07T17:33:36.583Z] 		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2021-04-07T17:33:36.583Z] 		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2021-04-07T17:33:36.583Z] 		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2021-04-07T17:33:36.583Z] 		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2021-04-07T17:33:36.583Z] Caused: hudson.plugins.git.GitException: Could not checkout 8968ea822a47f9f31d86683fb3ad2a9bcb0f8587
[2021-04-07T17:33:36.583Z] 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2791)
[2021-04-07T17:33:36.583Z] 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:161)
[2021-04-07T17:33:36.584Z] 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:154)
[2021-04-07T17:33:36.584Z] 	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
[2021-04-07T17:33:36.584Z] 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
[2021-04-07T17:33:36.584Z] 	at hudson.remoting.Request$2.run(Request.java:375)
[2021-04-07T17:33:36.584Z] 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:73)
[2021-04-07T17:33:36.584Z] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2021-04-07T17:33:36.584Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2021-04-07T17:33:36.584Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.jav [...]

2021-04-07 18:14 UTC, P1llus reviewed
You mentioned about this in the other filebeat module issue, and I see its still in draft, is this on purpose?

Here are some initial findings, though the rest seems to be a great first PR to the integrations repo! :)

2021-04-07 18:14 UTC, P1llus commented on packages/cisco/changelog.yml
> +- version: "0.1.1"
This one should be version 0.9.0, and be at the top of the changelog, the newest entry is always at the top.

2021-04-07 18:14 UTC, P1llus commented on packages/cisco/data_stream/ios/_dev/test/pipeline/test-cisco-ios.log-expected.json
> +            "message": "Received (*, 10.36.2.78) Join from 10.4.5.66 for invalid RP 10.3.66.3",
Just out of curiosity, is it meant to have a star(*) sign here?

2021-04-07 18:14 UTC, P1llus commented on packages/cisco/data_stream/ios/elasticsearch/ingest_pipeline/default.yml
> +        - "%%{DATA:cisco.ios.facility}-%{POSINT:event.severity}-%{DATA:event.code}: %{GREEDYDATA:message}"
Does this pattern usually have double percentage sign at the start? (%%)

2021-04-07 18:27 UTC, legoguy1000 commented on packages/cisco/changelog.yml
> +- version: "0.1.1"
whoops went backwards 🤦

2021-04-07 18:30 UTC, legoguy1000 commented on packages/cisco/data_stream/ios/elasticsearch/ingest_pipeline/default.yml
> +        - "%%{DATA:cisco.ios.facility}-%{POSINT:event.severity}-%{DATA:event.code}: %{GREEDYDATA:message}"
The logs start with `%SEC-6-IPACCESSLOGRL`, so there is a % in the log message and then the other % is for the grok variables.

2021-04-07 18:30 UTC, legoguy1000 commented on packages/cisco/data_stream/ios/_dev/test/pipeline/test-cisco-ios.log-expected.json
> +            "message": "Received (*, 10.36.2.78) Join from 10.4.5.66 for invalid RP 10.3.66.3",
that was the sample log I was given.

2021-04-07 18:31 UTC, legoguy1000 commented on packages/cisco/data_stream/ios/_dev/test/pipeline/test-cisco-ios.log-expected.json
> +            "message": "Received (*, 10.36.2.78) Join from 10.4.5.66 for invalid RP 10.3.66.3",
https://github.com/elastic/beats/issues/24642#issuecomment-806052112

2021-04-08 13:38 UTC, P1llus commented
Seems like there is some merge conflicts, would you be able to merge and refresh? looking at the files it would be easier to just checkout the two files from master and update them again.

2021-04-08 17:42 UTC, legoguy1000 commented
> Seems like there is some merge conflicts, would you be able to merge and refresh? looking at the files it would be easier to just checkout the two files from master and update them again.

done

2021-04-08 19:23 UTC, P1llus commented
It seems to still have issues @legoguy1000 . Do you want me to quickly grab the PR and commit the fix? I am sure its just something basic.

2021-04-08 19:24 UTC, P1llus approved these changes
Currently approving to kick off the CI, let's see what it says first.

2021-04-08 19:30 UTC, P1llus commented
jenkins run tests please

2021-04-08 19:46 UTC, P1llus commented
Can you please run `elastic-package format` and `elastic-package check` @legoguy1000 ? Its complaining about some minor formatting things, might be whitespaces etc, the commands will format all your files normally.

2021-04-08 19:54 UTC, legoguy1000 commented
> elastic-package check

I"m also missing a field description, the original issue creator never answered me on what the field was/description

2021-04-08 19:55 UTC, legoguy1000 commented on packages/cisco/data_stream/ios/fields/fields.yml
> +      description: XXX
@P1llus THis is the field i'm missing a description for

2021-04-08 21:35 UTC, dainperkins commented on packages/cisco/data_stream/ios/fields/fields.yml
> +      description: XXX
@P1llus 

%PIM-SW1-6-INVALID_RP_JOIN: Received (*, 10.36.2.78) Join from 10.4.5.66 for invalid RP 10.3.66.3
this is an invalid multicast request from a "leaf" router

1st IP is the multicast (group?) ip
2nd IP is the router attempting to join the multicast group or leaf router (denied due to pim sparse config)
3rd IP is the rendevous point ip (the relevant interface ip of the router denying the request & logging the message)

How about the following, thinking at some point cisco.pim might make its way into either pim, or network.pim:
cisco.pim.source.ip (if the * is an ip address)
cisco.pim.group.ip (multicast group ip/tree ip)
source.ip (router sending the pim join request - pim leaf node)
destination.ip (router denying the pim join request - pim RP)

I think source and destination are semantically correct in this case (the RP is the destination, the join came from the source...)

iirc the whole leaf/tree thing is specific to pim sparse (its been like 20 years tho, so don't quote me on that) and isn't particularly relevant to the connection, but more to the configuration of the router.  

I didn't check out event fields, etc.  but the following would likely be useful
event.
 - action: [multicast join]
 - category: network
 - outcome: failure
 - reason: invalid RP
 - reference: https://www.cisco.com/c/en/us/support/docs/ip/ip-multicast/16450-mcastguide0.html#invalidrp **
 - type: [connection]

** Holy cow - how useful would this be for every Cisco IOS syslog message, or even just the ipsec & ike logs!

2021-04-08 22:54 UTC, legoguy1000 commented on packages/cisco/data_stream/ios/fields/fields.yml
> +      description: XXX
@dainperkins can u provide additional log samples for this log type so we can see the variations? Thats the big issue with some of these and where the pain comes from is not knowing how the logs change to know the best way to parse.

2021-04-20 16:53 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2021-04-20 20:51 UTC, dainperkins commented on packages/cisco/data_stream/ios/fields/fields.yml
> +      description: XXX
sorry, I only have 1 cisco switch and haven't done pim since, errr, 2002 or so.  if you have examples that are causing issues I can take a look at those..

2021-05-03 09:24 UTC, marc-gr requested changes
Looks good, just minor changes and a rebase should do the trick :D

2021-05-03 09:24 UTC, marc-gr commented on packages/cisco/data_stream/ios/_dev/test/pipeline/test-cisco-ios.log-expected.json
> +                "category": "network_traffic",
`network_traffic` is not a valid ECS category, we might want to change it to `network` https://www.elastic.co/guide/en/ecs/current/ecs-allowed-values-event-category.html

from the same reference, seems that event.type is also an unexpected value, for network events is expected to be one of `access, allowed, connection, denied, end, info, protocol, start`.

If we want to keep the `firewall` value, maybe in `event.provider` fits well. cc @dainperkins wdyt?

2021-05-03 09:24 UTC, marc-gr commented on packages/cisco/data_stream/ios/_dev/test/pipeline/test-cisco-ios.log-expected.json
> +                "sequence": "1991217",
this should be of type long https://www.elastic.co/guide/en/ecs/current/ecs-event.html#field-event-sequence

2021-05-03 09:24 UTC, marc-gr commented on packages/cisco/data_stream/ios/elasticsearch/ingest_pipeline/default.yml
> +  - dissect:
```suggestion
  - set:
       field: event.action
       value: "multicast-join"
       if: ctx?.event?.code == "INVALID_RP_JOIN"
  - set:
       field: event.outcome
       value: "failure"
       if: ctx?.event?.code == "INVALID_RP_JOIN"
  - set:
       field: event.reason
       value: "Invalid RP"
       if: ctx?.event?.code == "INVALID_RP_JOIN"
  - dissect:
```

Following suggestion from https://github.com/elastic/integrations/pull/896/files#r610127848

2021-05-03 09:24 UTC, marc-gr commented on packages/cisco/data_stream/ios/_dev/test/pipeline/test-cisco-ios.log-expected.json
>                  "outcome": "deny"
Might be nice to change `deny` to `failure`, since the first is not a valid `event.outcome` value https://www.elastic.co/guide/en/ecs/current/ecs-event.html#field-event-outcome

2021-05-03 12:47 UTC, legoguy1000 commented on packages/cisco/data_stream/ios/_dev/test/pipeline/test-cisco-ios.log-expected.json
>                  "outcome": "deny"
done

2021-05-03 12:48 UTC, legoguy1000 commented on packages/cisco/data_stream/ios/elasticsearch/ingest_pipeline/default.yml
> +  - dissect:
done

2021-05-03 12:48 UTC, legoguy1000 commented on packages/cisco/data_stream/ios/_dev/test/pipeline/test-cisco-ios.log-expected.json
> +                "sequence": "1991217",
done

2021-05-03 12:48 UTC, legoguy1000 commented on packages/cisco/data_stream/ios/_dev/test/pipeline/test-cisco-ios.log-expected.json
> +                "category": "network_traffic",
done

2021-05-03 12:49 UTC, legoguy1000 commented
@marc-gr Changes made

2021-05-03 12:50 UTC, legoguy1000 commented on packages/cisco/data_stream/ios/fields/fields.yml
> +      description: XXX
@marc-gr I still don't know what to put as the description for this line. That should be the last thing needed.

2021-05-03 13:27 UTC, marc-gr commented on packages/cisco/data_stream/ios/fields/fields.yml
> +      description: XXX
I am not familiar with CISCO that much, maybe @dainperkins can give us some ideas here?

2021-05-03 13:33 UTC, marc-gr commented
FYI, there are still some invalid values for outcome and some other ECS fields. Since changing them all is out of scope of this PR, I opened https://github.com/elastic/integrations/issues/965.

2021-05-03 13:43 UTC, legoguy1000 commented
> FYI, there are still some invalid values for outcome and some other ECS fields. Since changing them all is out of scope of this PR, I opened #965.

rog, I can continue to look but most of those we're there previously but I think you already made a note of that.

2021-05-03 13:55 UTC, marc-gr commented
> > FYI, there are still some invalid values for outcome and some other ECS fields. Since changing them all is out of scope of this PR, I opened #965.
> 
> rog, I can continue to look but most of those we're there previously but I think you already made a note of that.

This was unrelated to your changes, just noticed it and wanted to be sure we fix it in the future :) Is probably better if we keep these in a future PR 👍

2021-05-11 11:47 UTC, legoguy1000 commented on packages/cisco/data_stream/ios/_dev/test/pipeline/test-cisco-ios.log-expected.json
> +            "message": "Received (*, 10.36.2.78) Join from 10.4.5.66 for invalid RP 10.3.66.3",
I updated the sample logs with a log with an IP in place of the star as well

2021-05-11 23:13 UTC, legoguy1000 commented
@marc-gr should be GTG now I think

2021-05-12 12:19 UTC, dainperkins commented
on the field description, I suggest something simple for a description for the pim group

- description: fields describing protocol independent multicast (pim) data

I'm not sure duplicating the source w/in the pim fields is necessary (can't think of a situation where the ip source would be different from the "pim" source), but its hardly problematic 

good work!

2021-05-12 12:24 UTC, legoguy1000 commented
> on the field description, I suggest something simple for a description for the pim group
> 
> * description: fields describing protocol independent multicast (pim) data
> 
> I'm not sure duplicating the source w/in the pim fields is necessary (can't think of a situation where the ip source would be different from the "pim" source), but its hardly problematic
> 
> good work!

I'll probably leave it for now and it can always be updated later if needed. @marc-gr thoughts??

2021-05-12 13:38 UTC, marc-gr approved these changes
LGTM! Thanks for the input @dainperkins ❤️ 

Awesome work @legoguy1000 🎉

2021-05-12 13:38 UTC, marc-gr commented
/test

2021-05-13 11:44 UTC, marc-gr commented
/test

2021-05-13 12:07 UTC, merged