[windows.forwarded] Add fields to ECS mappings
elastic/integrations pull request #8976
Opened 2024-01-25 13:00 UTC by monkeyonbranch

Bug

## Proposed commit message

* Add fields error.message and http.request.body.bytes to the ECS mappings
* Data Quality check finds default mapping of these fields (defaults to keyword) incompatible with ECS expected mapping types of match_long_text as well as long respectively.

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [X] I have verified that all data streams collect metrics or logs.
- [X] I have added an entry to my package's `changelog.yml` file.
- [X] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally

1. Add mappings to component template.
2. Ingest data
3. Validate mappings through devtools and correlate with ECS OR run Data Quality check in Security dashboard.

## Screenshots

![error message](https://github.com/elastic/integrations/assets/157019701/b373b9f1-8be8-4568-a6e3-4416e3188a61)
![http request body bytes](https://github.com/elastic/integrations/assets/157019701/6aeb0ac0-3501-4a6d-bc6a-7c0b481d0d48)

2024-01-25 13:45 UTC, elasticmachine commented
Pinging @elastic/elastic-agent (Team:Elastic-Agent)

2024-01-26 07:15 UTC, belimawr requested changes

2024-01-26 07:15 UTC, belimawr commented on packages/windows/changelog.yml
> +       link: https://github.com/elastic/integrations/pull/8975
It seems  you forgot to update the PR link
```suggestion
       link: https://github.com/elastic/integrations/pull/8976
```

2024-01-30 14:10 UTC, belimawr commented
/test

2024-01-30 14:12 UTC, belimawr approved these changes

2024-01-30 14:17 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/8474)
* Commit: bdad43201cb1769b2479ac9f77c789a665496fb4

### Failed CI Steps
* [Check integrations windows](https://buildkite.com/elastic/integrations/builds/8474#018d5ab7-afdb-4b38-86a7-efacb4ee80d4)

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8474","number":8474,"commit":"bdad43201cb1769b2479ac9f77c789a665496fb4"}],"number":8474}
buildkite-pr-comment-->

2024-02-05 21:54 UTC, rdner commented
/test

2024-02-05 22:01 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/8613)
* Commit: d4e79f2086064c1e4eb002b5d29112fbc8c352c8

### Failed CI Steps
* [Check integrations windows](https://buildkite.com/elastic/integrations/builds/8613#018d7b46-e3d4-489f-b246-699edcff938d)

### History
* :broken_heart: [Build #8474](https://buildkite.com/elastic/integrations/builds/8474) failed bdad43201cb1769b2479ac9f77c789a665496fb4

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8613","number":8613,"commit":"d4e79f2086064c1e4eb002b5d29112fbc8c352c8"},{"buildStatus":{"state":"failed","success":false,"hasRetries":true,"hasNonPreemptionRetries":true},"url":"https://buildkite.com/elastic/integrations/builds/8474","number":8474,"commit":"bdad43201cb1769b2479ac9f77c789a665496fb4"}],"number":8613}
buildkite-pr-comment-->

2024-02-06 15:16 UTC, rdner requested changes

2024-02-06 15:16 UTC, rdner commented on packages/windows/changelog.yml
> +- version: "1.44.2"
Please put the same version in the manifest file https://github.com/elastic/integrations/blob/7515c44bb40eeb7f271d12673f259fb739f17b36/packages/windows/manifest.yml#L3

2024-02-07 10:07 UTC, rdner commented
/test

2024-02-07 10:24 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-02-07 10:24 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/8700)
* Commit: baedd40ea98508f304015d35020d53cd45b62afd

### History
* :broken_heart: [Build #8613](https://buildkite.com/elastic/integrations/builds/8613) failed d4e79f2086064c1e4eb002b5d29112fbc8c352c8
* :broken_heart: [Build #8474](https://buildkite.com/elastic/integrations/builds/8474) failed bdad43201cb1769b2479ac9f77c789a665496fb4

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8700","number":8700,"commit":"baedd40ea98508f304015d35020d53cd45b62afd"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8613","number":8613,"commit":"d4e79f2086064c1e4eb002b5d29112fbc8c352c8"},{"buildStatus":{"state":"failed","success":false,"hasRetries":true,"hasNonPreemptionRetries":true},"url":"https://buildkite.com/elastic/integrations/builds/8474","number":8474,"commit":"bdad43201cb1769b2479ac9f77c789a665496fb4"}],"number":8700}
buildkite-pr-comment-->

2024-02-07 10:35 UTC, marc-gr approved these changes

2024-02-07 12:22 UTC, rdner approved these changes

2024-02-07 12:22 UTC, merged