[windows] Add filters to visuals for only AppLocker data to be displated
elastic/integrations pull request #8993
Opened 2024-01-26 23:03 UTC by nicpenning

- Bug

This fixes the visuals in the dashboard for AppLocker so only relevant data is displayed. See: https://github.com/elastic/integrations/issues/8969

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

- Closes #8969

2024-01-27 15:00 UTC, nicpenning commented
This is ready to test.

2024-01-27 17:11 UTC, elasticmachine commented
Pinging @elastic/elastic-agent (Team:Elastic-Agent)

2024-01-30 14:01 UTC, marc-gr submitted a review, later dismissed

2024-01-30 14:14 UTC, belimawr commented
/test

2024-01-30 14:26 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/8475)
* Commit: 0c73f7e60cc347b549ad64832e65ff550ef8ffc7

### Failed CI Steps
* [Check integrations windows](https://buildkite.com/elastic/integrations/builds/8475#018d5abb-a106-4863-875c-73aaa79abfb9)

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8475","number":8475,"commit":"0c73f7e60cc347b549ad64832e65ff550ef8ffc7"}],"number":8475}
buildkite-pr-comment-->

2024-01-30 15:21 UTC, marc-gr commented
I think `elastic-package check` is required to run and commit the changes it does.

2024-01-30 15:53 UTC, nicpenning commented
Okay - So I need to run that command and then push the changes up?

2024-01-30 16:07 UTC, nicpenning commented
elastic-package check has been applied and committed. Please test again!

2024-01-31 08:01 UTC, marc-gr commented
/test

2024-01-31 08:14 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/8509)
* Commit: 90792ba299dd6bfbe2af96ae7fd4e4106cb055b9

### Failed CI Steps
* [Check integrations windows](https://buildkite.com/elastic/integrations/builds/8509#018d5e8d-2446-406a-913e-e65bd7087f99)

### History
* :broken_heart: [Build #8475](https://buildkite.com/elastic/integrations/builds/8475) failed 0c73f7e60cc347b549ad64832e65ff550ef8ffc7

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8509","number":8509,"commit":"90792ba299dd6bfbe2af96ae7fd4e4106cb055b9"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8475","number":8475,"commit":"0c73f7e60cc347b549ad64832e65ff550ef8ffc7"}],"number":8509}
buildkite-pr-comment-->

2024-01-31 13:11 UTC, nicpenning commented
I cannot see the build issues now that it's been moved to buildkite. Any chance this can be opened up to community members contributing?

2024-02-02 03:09 UTC, nicpenning commented
Any updates on why this failed? I am kinda blind over here.

2024-02-02 13:57 UTC, strawgate commented
I see a failure of:

```
Error: can't install the package: could not zip-install package; API status code = 500; response body = {"statusCode":500,"error":"Internal Server Error","message":"Migration function for version 7.11.0 threw an error"}
```

I'll see if we can get someone to comment about plans for access

2024-02-02 14:22 UTC, nicpenning commented
Thank you. Any idea how that issue can be resolved?

2024-02-02 14:35 UTC, pierrehilbert commented
/test

2024-02-05 15:33 UTC, marc-gr commented
> Is this issue sourced from using 8.12.0 when I checked the package?
> 
> @strawgate - is it still the same error?

Could be, I checked and for 8.12 it passes alright, but CI uses the minimum supported version which is 8.8.0. If you used 8.12 to do the changes that might be the issue. I'd suggest doing them with an 8.8.0 stack (`elastic-package stack up -v -d --version=8.8.0`)

2024-02-05 17:11 UTC, nicpenning commented
Bummer - Okay, I can do that. Perhaps it is a deeper issue, but it is concerning we must use such an older version of the stack. In an example of a visualization that only exists in the latest, this would likely then be a blocker and not something we can add until the elastic-package tool can keep up? I can reference this issue there if that will help with this side issue. Please let me know!

2024-02-06 15:20 UTC, rdner requested changes

2024-02-06 15:20 UTC, rdner commented on packages/windows/data_stream/forwarded/_dev/test/pipeline/test-security-4662.json
> +}
All whitespace changes should be reversed, so they don't pollute file history.

2024-02-06 15:20 UTC, rdner commented on packages/windows/manifest.yml
> +version: 1.44.2
This version change will cause a conflict once https://github.com/elastic/integrations/pull/8976 is merged

2024-02-07 10:38 UTC, marc-gr commented
I'll take care of fixing this one since not having access to CI complicates things for @nicpenning . Thanks for the work done @nicpenning will update this PR with the fix. 👍

2024-02-07 11:27 UTC, nicpenning commented on packages/windows/data_stream/forwarded/_dev/test/pipeline/test-security-4662.json
> +}
Thanks, @rdner for the awareness. How should I handle incorrect white space in the future? I believe the elastic-package tool corrected this. 

@efd6 what's your take on this? It seems like I can never win on the whitespace things haha!! 😅

2024-02-07 12:24 UTC, rdner commented on packages/windows/data_stream/forwarded/_dev/test/pipeline/test-security-4662.json
> +}
If it's caused by automation it's okay to leave it. Looks like this code was somehow merged before the tool started taking care of code formatting.

2024-02-07 12:24 UTC, rdner commented on packages/windows/manifest.yml
> +version: 1.44.2
Now merged, we need to bump the version in this PR to 1.44.3.

2024-02-07 12:27 UTC, rdner commented on packages/windows/changelog.yml
> +- version: "1.44.3"
Needs to be set in https://github.com/elastic/integrations/blob/655207ba9c8eff24eb806a06864f181c390d3367/packages/windows/manifest.yml#L3 too

2024-02-07 12:28 UTC, rdner commented on packages/windows/manifest.yml
> +version: 1.44.2
Done by resolving conflicts in https://github.com/elastic/integrations/pull/8993/commits/7b5b2e847593ece9e985925cabb13b474356930c

2024-02-07 12:47 UTC, nicpenning commented on packages/windows/data_stream/forwarded/_dev/test/pipeline/test-security-4662.json
> +}
You caught me 😀 

That's exactly what happened. I will keep that in mind. Thank you!

2024-02-13 03:34 UTC, nicpenning commented
👋 
Any updates here?

2024-02-13 10:41 UTC, marc-gr commented
/test

2024-02-13 10:59 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-02-13 10:59 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/8910)
* Commit: 90505ae5ce5b19c08e70f26effbc9fbb1cc3149f

### History
* :broken_heart: [Build #8584](https://buildkite.com/elastic/integrations/builds/8584) failed 90792ba299dd6bfbe2af96ae7fd4e4106cb055b9
* :broken_heart: [Build #8509](https://buildkite.com/elastic/integrations/builds/8509) failed 90792ba299dd6bfbe2af96ae7fd4e4106cb055b9
* :broken_heart: [Build #8475](https://buildkite.com/elastic/integrations/builds/8475) failed 0c73f7e60cc347b549ad64832e65ff550ef8ffc7

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8910","number":8910,"commit":"90505ae5ce5b19c08e70f26effbc9fbb1cc3149f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":true,"hasNonPreemptionRetries":true},"url":"https://buildkite.com/elastic/integrations/builds/8584","number":8584,"commit":"90792ba299dd6bfbe2af96ae7fd4e4106cb055b9"},{"buildStatus":{"state":"failed","success":false,"hasRetries":true,"hasNonPreemptionRetries":true},"url":"https://buildkite.com/elastic/integrations/builds/8509","number":8509,"commit":"90792ba299dd6bfbe2af96ae7fd4e4106cb055b9"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8475","number":8475,"commit":"0c73f7e60cc347b549ad64832e65ff550ef8ffc7"}],"number":8910}
buildkite-pr-comment-->

2024-02-14 12:27 UTC, rdner approved these changes

2024-02-14 12:45 UTC, marc-gr approved these changes

2024-02-14 12:45 UTC, merged

2024-02-14 12:53 UTC, nicpenning commented
🎉