Support 'preserve_original_event' on kubernetes container logs
elastic/integrations pull request #9036
Opened 2024-02-01 10:56 UTC by ltflb-bgdi

## Proposed commit message

Added support of preserve_original_event on kubernetes container logs based on pod annotations.

This is useful when events are rerouted to specific integrations, since enabling the feature there has no effect on events shipped by the kubernetes integration.

As a workaround and POC I added custom processors to the fleet configuration but I would prefer if it would be generally available. 

## Checklist

- x ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## How to test this PR locally

## Related issues

- 

## Screenshots

2024-02-01 11:05 UTC, ltflb-bgdi commented
CLA signed

2024-02-13 12:59 UTC, gsantoro requested changes
just a couple of optimizations. 

It looks good so far. I need to review the docs and test it end to end though

2024-02-13 12:59 UTC, gsantoro commented on packages/kubernetes/data_stream/container_logs/agent/stream/stream.yml.hbs
> +- add_tags:
```suggestion
- drop_fields:
    fields:
      - kubernetes.annotations.elastic_co/preserve_original_event
    when:
      equals:
        kubernetes.annotations.elastic_co/preserve_original_event: ""
    ignore_missing: true
- add_tags:
    tags: ["preserve_original_event"]
    when:
      and:
        - has_fields: ["kubernetes.annotations.elastic_co/preserve_original_event"]
        - regexp:
            kubernetes.annotations.elastic_co/preserve_original_event:  "^(?i)true$"
```

I haven't test this but if it works it could provide some benefits:
1. we are consistent with the behaviour of other drop_fields above. In case preserve_original_event is not provided as an annotation, we avoid leaving the annotation and we preserve if provided instead.
2. in the add_tags condition, we avoid doing a regex (computationally intensive) if the field is not there (meaning if the annotation is not provided)

2024-02-13 12:59 UTC, gsantoro commented on packages/kubernetes/data_stream/container_logs/fields/base-fields.yml
> +    - name: tags
This shouldn't be here since tags is already defined in ecs.

the following code should be added to packages/kubernetes/data_stream/container_logs/fields/ecs.yml

```
- external: ecs
  name: tags
```

2024-02-13 14:59 UTC, ltflb-bgdi commented
@gsantoro Thanks for reviewing. I have updated the code according to your suggestions.

2024-02-14 16:51 UTC, gsantoro commented
@ltflb-bgdi I'm testing these changes, and there is something wrong with those processors in the container-logs datastream. They are not adding the tags correctly when running the integration tests. I need some time to investigate.

2024-02-14 17:22 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/8959)
* Commit: 77182a6e3d227d1861259d3f51b67d6e5b74a2f7

### Failed CI Steps
* [Check integrations kubernetes](https://buildkite.com/elastic/integrations/builds/8959#018da89b-fc75-4275-bc66-45a74f62454a)

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8959","number":8959,"commit":"77182a6e3d227d1861259d3f51b67d6e5b74a2f7"}],"number":8959}
buildkite-pr-comment-->

2024-02-14 18:17 UTC, ltflb-bgdi commented
> @ltflb-bgdi I'm testing these changes, and there is something wrong with those processors in the container-logs datastream. They are not adding the tags correctly when running the integration tests. I need some time to investigate.

@gsantoro Thanks. FYI the processors are working as expected on our kubernetes dev cluster. Thus I expect the problem is related to the integrated test setup. Please let me know if there is something I can do.

2024-02-15 11:21 UTC, gsantoro commented
> > @ltflb-bgdi I'm testing these changes, and there is something wrong with those processors in the container-logs datastream. They are not adding the tags correctly when running the integration tests. I need some time to investigate.
> 
> @gsantoro Thanks. FYI the processors are working as expected on our kubernetes dev cluster. Thus I expect the problem is related to the integrated test setup. Please let me know if there is something I can do.

do you actually get the tags fields in the output? 

it might be just something to do with the integration tests but if this is not resolved this PR won't be able to merge.

2024-02-15 12:06 UTC, gsantoro commented on packages/kubernetes/data_stream/container_logs/_dev/test/pipeline/test-nginx.log-expected.json
> +            },
do you mind removing any reference to `tags` from this log-expected.json. All the four references.

Our integration tests can't run the processors that add these tags. We decided to make the integration tests pass by removing these tags from the expected file instead.

The real solution would be to fix the integration tests for this test to pass, but it requires a massive rework of our integration test suite, and that's out of scope for now.

2024-02-15 15:09 UTC, gsantoro commented
@ltflb-bgdi do you mind doing the code changes that I asked at https://github.com/elastic/integrations/pull/9036#discussion_r1490912592. 

Otherwise, the Buildkite pipeline won't pass its checks. 

I can't push a commit to your feature branch.

2024-02-15 16:09 UTC, ltflb-bgdi commented
> @ltflb-bgdi do you mind doing the code changes that I asked at [#9036 (comment)](https://github.com/elastic/integrations/pull/9036#discussion_r1490912592).
> 
> Otherwise, the Buildkite pipeline won't pass its checks.
> 
> I can't push a commit to your feature branch.

Done

2024-02-15 16:41 UTC, gsantoro approved these changes

2024-02-15 16:42 UTC, gsantoro commented
/test

2024-02-15 17:19 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-02-15 17:19 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/9016)
* Commit: 794ce49900cb2bc8ba4f76f2dd0edeeca7bf65bc

### History
* :broken_heart: [Build #8959](https://buildkite.com/elastic/integrations/builds/8959) failed 77182a6e3d227d1861259d3f51b67d6e5b74a2f7

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9016","number":9016,"commit":"794ce49900cb2bc8ba4f76f2dd0edeeca7bf65bc"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8959","number":8959,"commit":"77182a6e3d227d1861259d3f51b67d6e5b74a2f7"}],"number":9016}
buildkite-pr-comment-->

2024-02-15 17:19 UTC, merged

2024-02-15 17:28 UTC, gsantoro commented
thanks @ltflb-bgdi for contributing this PR

2024-02-15 17:31 UTC, elasticmachine commented
Package kubernetes - 1.57.0 containing this change is available at https://epr.elastic.co/search?package=kubernetes