[O11y][PHP-FPM] Update README to use documentation guidelines
elastic/integrations pull request #9069
Opened 2024-02-06 11:56 UTC by harnish-elastic

## Proposed commit message

- Updated README as per the [doc template](https://github.com/elastic/integrations/blob/main/docs/documentation_guidelines.md#overview).

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Closes #9034

2024-02-06 12:22 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-02-06 12:22 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/8642)
* Commit: 35efc5e269e90ec608c6717364864cabd4242255

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8642","number":8642,"commit":"35efc5e269e90ec608c6717364864cabd4242255"}],"number":8642}
buildkite-pr-comment-->

2024-02-07 09:32 UTC, niraj-elastic approved these changes
Provided a ingle nit, everything else seems good.

2024-02-07 09:32 UTC, niraj-elastic commented on packages/php_fpm/changelog.yml
> +    - description: Update README to use documentation guidelines.
nit: `to use` -> `to follow`

2024-02-07 09:53 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/8694)
* Commit: 6311110c127a670ccf178189549f76fd5f23c231

### History
* :green_heart: [Build #8642](https://buildkite.com/elastic/integrations/builds/8642) succeeded 35efc5e269e90ec608c6717364864cabd4242255

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8694","number":8694,"commit":"6311110c127a670ccf178189549f76fd5f23c231"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8642","number":8642,"commit":"35efc5e269e90ec608c6717364864cabd4242255"}],"number":8694}
buildkite-pr-comment-->

2024-02-07 11:47 UTC, alaudazzi requested changes
LGTM after comments are integrated.

2024-02-07 11:47 UTC, alaudazzi commented on packages/php_fpm/_dev/build/docs/README.md
> +You need Elasticsearch for storing and searching your data and Kibana for visualizing and managing it. You can use our hosted Elasticsearch Service on Elastic Cloud, which is recommended or self-mana
This section duplicates the "Requirements" section that follows. You can remove it.

2024-02-07 11:47 UTC, alaudazzi commented on packages/php_fpm/_dev/build/docs/README.md
> +After the integration is successfully configured, clicking on the Assets tab of the PHP-FPM Integration should display a list of available dashboards. Click on the dashboard available for your config
```suggestion
After the integration is successfully configured, click on the *Assets* tab of the PHP-FPM Integration to display the available dashboards. Select the dashboard for your configured data stream, which should be populated with the required data.
```

2024-02-07 11:47 UTC, alaudazzi commented on packages/php_fpm/_dev/build/docs/README.md
> +This is the `process` data stream. `process` data stream collects metrics related to the request duration, content length, process state, etc.
```suggestion
The `process` data stream collects metrics related to the request duration, content length, process state, etc.

```

2024-02-07 12:10 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/8712)
* Commit: 53dc41774f3fe8b13dbd9aa2d7c0dd33e66b34fb

### History
* :green_heart: [Build #8694](https://buildkite.com/elastic/integrations/builds/8694) succeeded 6311110c127a670ccf178189549f76fd5f23c231
* :green_heart: [Build #8642](https://buildkite.com/elastic/integrations/builds/8642) succeeded 35efc5e269e90ec608c6717364864cabd4242255

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8712","number":8712,"commit":"53dc41774f3fe8b13dbd9aa2d7c0dd33e66b34fb"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8694","number":8694,"commit":"6311110c127a670ccf178189549f76fd5f23c231"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8642","number":8642,"commit":"35efc5e269e90ec608c6717364864cabd4242255"}],"number":8712}
buildkite-pr-comment-->

2024-02-07 12:16 UTC, alaudazzi commented on packages/php_fpm/_dev/build/docs/README.md
>  ### Troubleshooting
```suggestion
## Troubleshooting
```
Based on the documentation guidelines, the Troubleshooting section should be Level 2

2024-02-07 12:43 UTC, alaudazzi approved these changes
LGTM

2024-02-07 13:01 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/8723)
* Commit: 124ab48ad06f83959d413814e867737e2021f1b9

### History
* :green_heart: [Build #8712](https://buildkite.com/elastic/integrations/builds/8712) succeeded 53dc41774f3fe8b13dbd9aa2d7c0dd33e66b34fb
* :green_heart: [Build #8694](https://buildkite.com/elastic/integrations/builds/8694) succeeded 6311110c127a670ccf178189549f76fd5f23c231
* :green_heart: [Build #8642](https://buildkite.com/elastic/integrations/builds/8642) succeeded 35efc5e269e90ec608c6717364864cabd4242255

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8723","number":8723,"commit":"124ab48ad06f83959d413814e867737e2021f1b9"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8712","number":8712,"commit":"53dc41774f3fe8b13dbd9aa2d7c0dd33e66b34fb"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8694","number":8694,"commit":"6311110c127a670ccf178189549f76fd5f23c231"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8642","number":8642,"commit":"35efc5e269e90ec608c6717364864cabd4242255"}],"number":8723}
buildkite-pr-comment-->

2024-02-12 07:04 UTC, harnish-elastic commented on packages/php_fpm/docs/README.md
> +## Troubleshooting
Please checkout this [comment](https://github.com/elastic/integrations/pull/8304#discussion_r1376676180), the point of that comment was the README should be on point instead of giving the detailed steps in it. Hence removed all the steps and provided the reindexing link so that if anything in future, need to update for reindexing, we can update the details in that linked document.

2024-02-12 07:10 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/8855)
* Commit: d982532c4dc53acce86f4802b331af742ab058b2

### History
* :green_heart: [Build #8723](https://buildkite.com/elastic/integrations/builds/8723) succeeded 124ab48ad06f83959d413814e867737e2021f1b9
* :green_heart: [Build #8712](https://buildkite.com/elastic/integrations/builds/8712) succeeded 53dc41774f3fe8b13dbd9aa2d7c0dd33e66b34fb
* :green_heart: [Build #8694](https://buildkite.com/elastic/integrations/builds/8694) succeeded 6311110c127a670ccf178189549f76fd5f23c231
* :green_heart: [Build #8642](https://buildkite.com/elastic/integrations/builds/8642) succeeded 35efc5e269e90ec608c6717364864cabd4242255

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8855","number":8855,"commit":"d982532c4dc53acce86f4802b331af742ab058b2"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8723","number":8723,"commit":"124ab48ad06f83959d413814e867737e2021f1b9"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8712","number":8712,"commit":"53dc41774f3fe8b13dbd9aa2d7c0dd33e66b34fb"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8694","number":8694,"commit":"6311110c127a670ccf178189549f76fd5f23c231"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8642","number":8642,"commit":"35efc5e269e90ec608c6717364864cabd4242255"}],"number":8855}
buildkite-pr-comment-->

2024-02-12 14:02 UTC, devamanv approved these changes
LGTM!

2024-02-13 09:01 UTC, merged

2024-02-13 09:59 UTC, elasticmachine commented
Package php_fpm - 1.2.1 containing this change is available at https://epr.elastic.co/search?package=php_fpm