[O11y][Spring Boot] Update README to use documentation guidelines.
elastic/integrations pull request #9070
Opened 2024-02-06 11:56 UTC by harnish-elastic

## Proposed commit message

- Updated README as per the [doc template](https://github.com/elastic/integrations/blob/main/docs/documentation_guidelines.md#overview).

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Closes #9035

2024-02-06 12:29 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-02-06 12:29 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/8640)
* Commit: b246304ad35935490f7ef0d259ac2d929500b3a0

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8640","number":8640,"commit":"b246304ad35935490f7ef0d259ac2d929500b3a0"}],"number":8640}
buildkite-pr-comment-->

2024-02-07 07:25 UTC, kush-elastic requested changes

2024-02-07 07:25 UTC, kush-elastic commented on packages/spring_boot/_dev/build/docs/README.md
> +- Create visualizations to monitor, measure and analyze the usage trend and key data, and derive business insights.
```suggestion
- Use dashboards to visualize, monitor, measure, and analyze the usage trend and key data, and derive business insights.
```

2024-02-07 07:25 UTC, kush-elastic commented on packages/spring_boot/_dev/build/docs/README.md
> +- Collect logs related to the auditevents and httptrace and metrics related to the gc, memory and threading.
```suggestion
- Gather logs pertaining to auditevents, httptraces, and metrics associated with garbage collection, memory, and threading.
```

2024-02-07 07:25 UTC, kush-elastic commented on packages/spring_boot/_dev/build/docs/README.md
> +- `threading`: Collects information related to the thread allocations, monitoring and CPU times.
```suggestion
Data streams:
- `auditevents`: Aggregates data on authentication outcomes, client IP addresses, document identifiers, and user principals.
- `gc`: Gathers metrics on garbage collection events, including collector names, memory utilization pre- and post-collection, thread counts, and duration metrics.
- `httptrace`: Captures details of HTTP transactions, including request paths, response statuses, user principals, and session identifiers.
- `memory`: Accumulates data on memory usage, differentiating between heap and non-heap memory spaces, buffer pools, and memory management.
- `threading`: Collects insights into thread creation, runtime monitoring, and CPU utilization metrics.
```

2024-02-07 07:31 UTC, kush-elastic approved these changes
LGTM!

2024-02-07 09:55 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/8692)
* Commit: 30eeef9311406fbc4da4535524899653eb77e592

### History
* :green_heart: [Build #8640](https://buildkite.com/elastic/integrations/builds/8640) succeeded b246304ad35935490f7ef0d259ac2d929500b3a0

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8692","number":8692,"commit":"30eeef9311406fbc4da4535524899653eb77e592"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8640","number":8640,"commit":"b246304ad35935490f7ef0d259ac2d929500b3a0"}],"number":8692}
buildkite-pr-comment-->

2024-02-07 12:00 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/8713)
* Commit: 9e905ed8f2fe3008663257373912157bf951f731

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/8713#018d836f-ed82-42e3-bd73-dbcb6b422722)

### History
* :green_heart: [Build #8692](https://buildkite.com/elastic/integrations/builds/8692) succeeded 30eeef9311406fbc4da4535524899653eb77e592
* :green_heart: [Build #8640](https://buildkite.com/elastic/integrations/builds/8640) succeeded b246304ad35935490f7ef0d259ac2d929500b3a0

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8713","number":8713,"commit":"9e905ed8f2fe3008663257373912157bf951f731"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8692","number":8692,"commit":"30eeef9311406fbc4da4535524899653eb77e592"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8640","number":8640,"commit":"b246304ad35935490f7ef0d259ac2d929500b3a0"}],"number":8713}
buildkite-pr-comment-->

2024-02-07 12:04 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/8714)
* Commit: ed267eeeeafae8d52978b1f0e6031632fcd1020f

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/8714#018d8374-1a21-489d-a9f4-72dec7817e30)

### History
* :broken_heart: [Build #8713](https://buildkite.com/elastic/integrations/builds/8713) failed 9e905ed8f2fe3008663257373912157bf951f731
* :green_heart: [Build #8692](https://buildkite.com/elastic/integrations/builds/8692) succeeded 30eeef9311406fbc4da4535524899653eb77e592
* :green_heart: [Build #8640](https://buildkite.com/elastic/integrations/builds/8640) succeeded b246304ad35935490f7ef0d259ac2d929500b3a0

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8714","number":8714,"commit":"ed267eeeeafae8d52978b1f0e6031632fcd1020f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8713","number":8713,"commit":"9e905ed8f2fe3008663257373912157bf951f731"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8692","number":8692,"commit":"30eeef9311406fbc4da4535524899653eb77e592"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8640","number":8640,"commit":"b246304ad35935490f7ef0d259ac2d929500b3a0"}],"number":8714}
buildkite-pr-comment-->

2024-02-07 12:23 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/8715)
* Commit: 819d20c9c0192f7fd5ccffeeb404f186c44bab21

### History
* :broken_heart: [Build #8714](https://buildkite.com/elastic/integrations/builds/8714) failed ed267eeeeafae8d52978b1f0e6031632fcd1020f
* :broken_heart: [Build #8713](https://buildkite.com/elastic/integrations/builds/8713) failed 9e905ed8f2fe3008663257373912157bf951f731
* :green_heart: [Build #8692](https://buildkite.com/elastic/integrations/builds/8692) succeeded 30eeef9311406fbc4da4535524899653eb77e592
* :green_heart: [Build #8640](https://buildkite.com/elastic/integrations/builds/8640) succeeded b246304ad35935490f7ef0d259ac2d929500b3a0

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8715","number":8715,"commit":"819d20c9c0192f7fd5ccffeeb404f186c44bab21"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8714","number":8714,"commit":"ed267eeeeafae8d52978b1f0e6031632fcd1020f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8713","number":8713,"commit":"9e905ed8f2fe3008663257373912157bf951f731"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8692","number":8692,"commit":"30eeef9311406fbc4da4535524899653eb77e592"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8640","number":8640,"commit":"b246304ad35935490f7ef0d259ac2d929500b3a0"}],"number":8715}
buildkite-pr-comment-->

2024-02-07 12:40 UTC, alaudazzi requested changes
LGTM after comments are integrated.

2024-02-07 12:40 UTC, alaudazzi commented on packages/spring_boot/_dev/build/docs/README.md
> +You need Elasticsearch for storing and searching your data and Kibana for visualizing and managing it. You can use our hosted Elasticsearch Service on Elastic Cloud, which is recommended or self-mana
I would suggest to:
1. Move this content to the section "Requirements"
2. Remove the section Prerequisites.
3. Put a comma after the text `which is recommended`

2024-02-07 12:40 UTC, alaudazzi commented on packages/spring_boot/_dev/build/docs/README.md
> +- Spring-boot-actuator module provides all Spring Boot's production-ready features. So add below dependency in `pom.xml` file.
```suggestion
- Spring-boot-actuator module provides all Spring Boot's production-ready features. You also need to add the following dependency to the `pom.xml` file:
```

2024-02-07 12:40 UTC, alaudazzi commented on packages/spring_boot/_dev/build/docs/README.md
>  ### Troubleshooting
```suggestion
## Troubleshooting
```
As per documentation guidelines, this should be a H2

2024-02-07 12:53 UTC, alaudazzi approved these changes
LGTM

2024-02-07 13:02 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/8722)
* Commit: 2635deba2af854cffe87d89928376a8fe1f903fb

### History
* :green_heart: [Build #8715](https://buildkite.com/elastic/integrations/builds/8715) succeeded 819d20c9c0192f7fd5ccffeeb404f186c44bab21
* :broken_heart: [Build #8714](https://buildkite.com/elastic/integrations/builds/8714) failed ed267eeeeafae8d52978b1f0e6031632fcd1020f
* :broken_heart: [Build #8713](https://buildkite.com/elastic/integrations/builds/8713) failed 9e905ed8f2fe3008663257373912157bf951f731
* :green_heart: [Build #8692](https://buildkite.com/elastic/integrations/builds/8692) succeeded 30eeef9311406fbc4da4535524899653eb77e592
* :green_heart: [Build #8640](https://buildkite.com/elastic/integrations/builds/8640) succeeded b246304ad35935490f7ef0d259ac2d929500b3a0

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8722","number":8722,"commit":"2635deba2af854cffe87d89928376a8fe1f903fb"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8715","number":8715,"commit":"819d20c9c0192f7fd5ccffeeb404f186c44bab21"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8714","number":8714,"commit":"ed267eeeeafae8d52978b1f0e6031632fcd1020f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8713","number":8713,"commit":"9e905ed8f2fe3008663257373912157bf951f731"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8692","number":8692,"commit":"30eeef9311406fbc4da4535524899653eb77e592"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8640","number":8640,"commit":"b246304ad35935490f7ef0d259ac2d929500b3a0"}],"number":8722}
buildkite-pr-comment-->

2024-02-12 05:28 UTC, harnish-elastic commented on packages/spring_boot/docs/README.md
> +- Users can monitor and see the log inside the ingested documents for Spring Boot in the `logs-*` index pattern from `Discover`, and for metrics, the index pattern is `metrics-*`.
Strongly feel to add quotes to highlight keywords like `logs-*`, `Discover`, and `metrics-*`. Other than that accepted suggestions.

2024-02-12 05:52 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/8851)
* Commit: cf48430bce92902a1e6faebda7f8ae9233881ced

### History
* :green_heart: [Build #8722](https://buildkite.com/elastic/integrations/builds/8722) succeeded 2635deba2af854cffe87d89928376a8fe1f903fb
* :green_heart: [Build #8715](https://buildkite.com/elastic/integrations/builds/8715) succeeded 819d20c9c0192f7fd5ccffeeb404f186c44bab21
* :broken_heart: [Build #8714](https://buildkite.com/elastic/integrations/builds/8714) failed ed267eeeeafae8d52978b1f0e6031632fcd1020f
* :broken_heart: [Build #8713](https://buildkite.com/elastic/integrations/builds/8713) failed 9e905ed8f2fe3008663257373912157bf951f731
* :green_heart: [Build #8692](https://buildkite.com/elastic/integrations/builds/8692) succeeded 30eeef9311406fbc4da4535524899653eb77e592
* :green_heart: [Build #8640](https://buildkite.com/elastic/integrations/builds/8640) succeeded b246304ad35935490f7ef0d259ac2d929500b3a0

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8851","number":8851,"commit":"cf48430bce92902a1e6faebda7f8ae9233881ced"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8722","number":8722,"commit":"2635deba2af854cffe87d89928376a8fe1f903fb"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8715","number":8715,"commit":"819d20c9c0192f7fd5ccffeeb404f186c44bab21"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8714","number":8714,"commit":"ed267eeeeafae8d52978b1f0e6031632fcd1020f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8713","number":8713,"commit":"9e905ed8f2fe3008663257373912157bf951f731"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8692","number":8692,"commit":"30eeef9311406fbc4da4535524899653eb77e592"}],"number":8851}
buildkite-pr-comment-->

2024-02-12 15:35 UTC, devamanv approved these changes
LGTM

2024-02-13 09:25 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/8905)
* Commit: 2a776988e257e3e7ba602749e07e2765959eaef2

### History
* :green_heart: [Build #8851](https://buildkite.com/elastic/integrations/builds/8851) succeeded cf48430bce92902a1e6faebda7f8ae9233881ced
* :green_heart: [Build #8722](https://buildkite.com/elastic/integrations/builds/8722) succeeded 2635deba2af854cffe87d89928376a8fe1f903fb
* :green_heart: [Build #8715](https://buildkite.com/elastic/integrations/builds/8715) succeeded 819d20c9c0192f7fd5ccffeeb404f186c44bab21
* :broken_heart: [Build #8714](https://buildkite.com/elastic/integrations/builds/8714) failed ed267eeeeafae8d52978b1f0e6031632fcd1020f
* :broken_heart: [Build #8713](https://buildkite.com/elastic/integrations/builds/8713) failed 9e905ed8f2fe3008663257373912157bf951f731
* :green_heart: [Build #8692](https://buildkite.com/elastic/integrations/builds/8692) succeeded 30eeef9311406fbc4da4535524899653eb77e592

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8905","number":8905,"commit":"2a776988e257e3e7ba602749e07e2765959eaef2"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8851","number":8851,"commit":"cf48430bce92902a1e6faebda7f8ae9233881ced"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8722","number":8722,"commit":"2635deba2af854cffe87d89928376a8fe1f903fb"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8715","number":8715,"commit":"819d20c9c0192f7fd5ccffeeb404f186c44bab21"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8714","number":8714,"commit":"ed267eeeeafae8d52978b1f0e6031632fcd1020f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8713","number":8713,"commit":"9e905ed8f2fe3008663257373912157bf951f731"}],"number":8905}
buildkite-pr-comment-->

2024-02-13 09:25 UTC, merged

2024-02-13 09:59 UTC, elasticmachine commented
Package spring_boot - 1.3.1 containing this change is available at https://epr.elastic.co/search?package=spring_boot