ping_one: fix handling of potentially null method call receivers
elastic/integrations pull request #9076
Opened 2024-02-06 20:39 UTC by efd6

## Proposed commit message

See title.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## How to test this PR locally

## Related issues

- For #8646

## Screenshots

2024-02-06 20:53 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/8668)
* Commit: 9b47a639be25651da750a94a867a7661257ae9f6

cc @efd6

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8668","number":8668,"commit":"9b47a639be25651da750a94a867a7661257ae9f6"}],"number":8668}
buildkite-pr-comment-->

2024-02-06 21:30 UTC, elasticmachine commented
Pinging @elastic/security-service-integrations (Team:Security-Service Integrations)

2024-02-08 14:28 UTC, chrisberkhout requested changes

2024-02-08 14:28 UTC, chrisberkhout commented on packages/ping_one/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
> +      if: ctx.json?.action?.type?.toLowerCase().contains('created') == true
One more after `.toLowerCase()`:
```
ctx.json?.action?.type?.toLowerCase()?.contains('created') == true
```
Below as well.

2024-02-08 22:17 UTC, efd6 commented on packages/ping_one/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
> +      if: ctx.json?.action?.type?.toLowerCase().contains('created') == true
True Thanks.

2024-02-08 22:33 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/8794)
* Commit: 5eb111077093968785e13578dc5e89af40faa27c

### History
* :green_heart: [Build #8668](https://buildkite.com/elastic/integrations/builds/8668) succeeded 9b47a639be25651da750a94a867a7661257ae9f6

cc @efd6

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8794","number":8794,"commit":"5eb111077093968785e13578dc5e89af40faa27c"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8668","number":8668,"commit":"9b47a639be25651da750a94a867a7661257ae9f6"}],"number":8794}
buildkite-pr-comment-->

2024-02-12 09:32 UTC, chrisberkhout approved these changes

2024-02-12 10:03 UTC, merged

2024-02-12 22:48 UTC, elasticmachine commented
Package ping_one - 1.13.2 containing this change is available at https://epr.elastic.co/search?package=ping_one