[O11y][Kubernetes] Rally benchmark `kubernetes.node`
elastic/integrations pull request #9100
Opened 2024-02-08 05:53 UTC by aliabbas-elastic

## Proposed commit message

- This PR adds benchmarking templates to the `node` data stream of `Kubernetes`

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.

## How to test this PR locally

Run this command from package root
- `elastic-package benchmark rally --benchmark performance-benchmark -v`
- `elastic-package benchmark stream --benchmark performance-benchmark -v`

## Related issues

- Relates #8719

## Screenshots

```
--- Benchmark results for package: kubernetes - START ---
╭────────────────────────────────────────────────────────────────────────────────────╮
│ info                                                                               │
├────────────────────────┬───────────────────────────────────────────────────────────┤
│ benchmark              │                                            node-benchmark │
│ description            │           Benchmark 20000 kubernetes.node events ingested │
│ run ID                 │                      513790c7-1c3e-41f8-b30a-a5b4f5666bed │
│ package                │                                                kubernetes │
│ start ts (s)           │                                                1707371473 │
│ end ts (s)             │                                                1707371520 │
│ duration               │                                                       47s │
│ generated corpora file │ /root/.elastic-package/tmp/rally_corpus/corpus-1805158178 │
╰────────────────────────┴───────────────────────────────────────────────────────────╯
╭────────────────────────────────────────────────────────────────────╮
│ parameters                                                         │
├─────────────────────────────────┬──────────────────────────────────┤
│ package version                 │                           1.56.0 │
│ data_stream.name                │                             node │
│ corpora.generator.total_events  │                            20000 │
│ corpora.generator.template.path │ ./node-benchmark/template.ndjson │
│ corpora.generator.template.raw  │                                  │
│ corpora.generator.template.type │                           gotext │
│ corpora.generator.config.path   │      ./node-benchmark/config.yml │
│ corpora.generator.config.raw    │                            map[] │
│ corpora.generator.fields.path   │      ./node-benchmark/fields.yml │
│ corpora.generator.fields.raw    │                            map[] │
╰─────────────────────────────────┴──────────────────────────────────╯
╭───────────╮
│ cluster i │
│ nfo       │
├───────┬───┤
│ name  │   │
│ nodes │ 0 │
╰───────┴───╯
╭───────────────────────────────────────╮
│ disk usage for index .ds-metrics-kube │
│ rnetes.node-ep-2024.02.08-000001 (for │
│ all fields)                           │
├──────────────────────────────┬────────┤
│ total                        │ 9.8 MB │
│ inverted_index.total         │ 181 kB │
│ inverted_index.stored_fields │ 7.1 MB │
│ inverted_index.doc_values    │ 2.0 MB │
│ inverted_index.points        │ 478 kB │
│ inverted_index.norms         │    0 B │
│ inverted_index.term_vectors  │    0 B │
│ inverted_index.knn_vectors   │    0 B │
╰──────────────────────────────┴────────╯
╭───────────────────────────────────────────────────────────────────────────────────╮
│ pipeline metrics-kubernetes.node-1.56.0 stats in node tEXONyPRRWmVq3cURK6CwA      │
├───────────────────────────────────────────┬───────────────────────────────────────┤
│ Totals                                    │ Count: 20000 | Failed: 0 | Time: 27ms │
│ pipeline (global@custom)                  │  Count: 20000 | Failed: 0 | Time: 2ms │
│ pipeline (metrics@custom)                 │  Count: 20000 | Failed: 0 | Time: 2ms │
│ pipeline (metrics-kubernetes@custom)      │  Count: 20000 | Failed: 0 | Time: 2ms │
│ pipeline (metrics-kubernetes.node@custom) │  Count: 20000 | Failed: 0 | Time: 2ms │
╰───────────────────────────────────────────┴───────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│ rally stats                                                                                 │
├────────────────────────────────────────────────────────────────┬────────────────────────────┤
│ Cumulative indexing time of primary shards                     │      4.715483333333333 min │
│ Min cumulative indexing time across primary shards             │                      0 min │
│ Median cumulative indexing time across primary shards          │   0.037233333333333334 min │
│ Max cumulative indexing time across primary shards             │     1.2267000000000001 min │
│ Cumulative indexing throttle time of primary shards            │                      0 min │
│ Min cumulative indexing throttle time across primary shards    │                      0 min │
│ Median cumulative indexing throttle time across primary shards │                    0.0 min │
│ Max cumulative indexing throttle time across primary shards    │                      0 min │
│ Cumulative merge time of primary shards                        │     2.2145333333333337 min │
│ Cumulative merge count of primary shards                       │                       1277 │
│ Min cumulative merge time across primary shards                │                      0 min │
│ Median cumulative merge time across primary shards             │                0.01415 min │
│ Max cumulative merge time across primary shards                │    0.37088333333333334 min │
│ Cumulative merge throttle time of primary shards               │   0.020849999999999997 min │
│ Min cumulative merge throttle time across primary shards       │                      0 min │
│ Median cumulative merge throttle time across primary shards    │                    0.0 min │
│ Max cumulative merge throttle time across primary shards       │   0.020849999999999997 min │
│ Cumulative refresh time of primary shards                      │     2.3700833333333335 min │
│ Cumulative refresh count of primary shards                     │                      45245 │
│ Min cumulative refresh time across primary shards              │                      0 min │
│ Median cumulative refresh time across primary shards           │               0.019675 min │
│ Max cumulative refresh time across primary shards              │     0.5715333333333333 min │
│ Cumulative flush time of primary shards                        │     60.819449999999996 min │
│ Cumulative flush count of primary shards                       │                      39174 │
│ Min cumulative flush time across primary shards                │ 1.6666666666666667e-05 min │
│ Median cumulative flush time across primary shards             │    0.31919166666666665 min │
│ Max cumulative flush time across primary shards                │     11.341466666666667 min │
│ Total Young Gen GC time                                        │                    0.043 s │
│ Total Young Gen GC count                                       │                          5 │
│ Total Old Gen GC time                                          │                        0 s │
│ Total Old Gen GC count                                         │                          0 │
│ Store size                                                     │      0.1532020242884755 GB │
│ Translog size                                                  │    0.001423398032784462 GB │
│ Heap used for segments                                         │                       0 MB │
│ Heap used for doc values                                       │                       0 MB │
│ Heap used for terms                                            │                       0 MB │
│ Heap used for norms                           [...]

2024-02-08 06:28 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-02-08 06:29 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/8774)
* Commit: 0bcd90e486214eaee1f0ce8a715b6ea60bf27fba

cc @aliabbas-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8774","number":8774,"commit":"0bcd90e486214eaee1f0ce8a715b6ea60bf27fba"}],"number":8774}
buildkite-pr-comment-->

2024-02-12 12:13 UTC, tommyers-elastic approved these changes
i don't see any issues here, but it would be useful to see diffs of the generated events for these PRs compared with say the sample event in the package, to quickly verify any missing or significantly different fields.

2024-02-14 13:52 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/8939)
* Commit: 5e3993b23e07d3c21bd1cfd53204447057fe9b2d

### History
* :green_heart: [Build #8774](https://buildkite.com/elastic/integrations/builds/8774) succeeded 0bcd90e486214eaee1f0ce8a715b6ea60bf27fba

cc @aliabbas-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8939","number":8939,"commit":"5e3993b23e07d3c21bd1cfd53204447057fe9b2d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8774","number":8774,"commit":"0bcd90e486214eaee1f0ce8a715b6ea60bf27fba"}],"number":8939}
buildkite-pr-comment-->

2024-02-14 14:20 UTC, gizas commented on packages/kubernetes/_dev/benchmark/rally/node-benchmark/template.ndjson
> +        "pod": {
Pod is not needed in node. Please remove
Same with namespace

2024-02-14 14:22 UTC, gizas commented
I cc a node document from the cluster:
[node.json](https://github.com/elastic/integrations/files/14280701/node.json)

Related to comment here for removal : https://github.com/elastic/integrations/pull/9100#discussion_r1489549003

2024-02-14 14:25 UTC, gizas commented on packages/kubernetes/_dev/benchmark/rally/node-benchmark/template.ndjson
> +        "namespace_labels": {
This as well

2024-02-14 14:31 UTC, gizas requested changes
I cc a node document from the cluster:
[node.json](https://github.com/elastic/integrations/files/14280701/node.json)

Related to comment here for removal : https://github.com/elastic/integrations/pull/9100#discussion_r1489549003

2024-02-14 15:28 UTC, aliabbas-elastic commented
> I cc a node document from the cluster:
[node.json](https://github.com/elastic/integrations/files/14280701/node.json)

Thanks for sharing the sample response @gizas. I have updated it accordingly. Let me know if the set of fields removed are correct.

2024-02-15 07:44 UTC, gizas approved these changes

2024-02-20 07:06 UTC, milan-elastic approved these changes

2024-02-26 10:42 UTC, merged