[AWS Fargate] Update documentation
elastic/integrations pull request #9130
Opened 2024-02-12 17:04 UTC by lucian-ioan

## Proposed commit message

Update documentation and change docs stack version to 8.12.0.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## How to test this PR locally
Run the elastic stack using `elastic-package` and set up the AWS Fargate integration (under beta integrations).

## Related issues

- Closes #9118

2024-02-12 17:19 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/8882)
* Commit: 4ab439fd301055ae7b9be155e77956572be3ddd0

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8882","number":8882,"commit":"4ab439fd301055ae7b9be155e77956572be3ddd0"}],"number":8882}
buildkite-pr-comment-->

2024-02-12 22:17 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/8884)
* Commit: a6703d5a1a4b0b79bee86516d560d323457c270a

### History
* :green_heart: [Build #8882](https://buildkite.com/elastic/integrations/builds/8882) succeeded 4ab439fd301055ae7b9be155e77956572be3ddd0

cc @lucian-ioan

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8884","number":8884,"commit":"a6703d5a1a4b0b79bee86516d560d323457c270a"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8882","number":8882,"commit":"4ab439fd301055ae7b9be155e77956572be3ddd0"}],"number":8884}
buildkite-pr-comment-->

2024-02-13 05:41 UTC, shmsr requested changes

2024-02-13 05:41 UTC, shmsr commented on packages/awsfargate/_dev/build/docs/README.md
> +Follow these steps for a fast deployment on your existing ECS cluster.
```suggestion
To quickly deploy on your existing ECS cluster, follow these steps.
```

2024-02-13 05:41 UTC, shmsr commented on packages/awsfargate/_dev/build/docs/README.md
> +## Getting Started using the AWS web console
```
## Getting Started using the AWS web console
```

Isn't "AWS Management Console" is better than "AWS web console"?

Example: https://docs.aws.amazon.com/awsconsolehelpdocs/latest/gsg/learn-whats-new.html#console-device

If you are making this change, please replace all other usages "AWS web console".

2024-02-13 05:41 UTC, shmsr commented on packages/awsfargate/_dev/build/docs/README.md
>  The AWS Fargate integration helps to retrieve metadata, network metrics, and Docker stats about your containers and the tasks that are a part of an [Amazon Elastic Container Service (Amazon ECS)](htt
```suggestion
The AWS Fargate integration helps to retrieve metadata, network metrics, and Docker stats about your containers and the tasks that are part of an [Amazon Elastic Container Service (Amazon ECS)](https://aws.amazon.com/ecs/?pg=ln&sec=hiw) cluster.
```

2024-02-13 05:42 UTC, shmsr commented on packages/awsfargate/_dev/build/docs/README.md
> +Follow these steps for a fast deployment on your existing ECS cluster.
nitpick: The usage of "fast" seems inappropriate. That's why I suggested the change.

2024-02-13 05:56 UTC, lucian-ioan commented on packages/awsfargate/_dev/build/docs/README.md
> +## Getting Started using the AWS web console
Definitely better, thank you!

2024-02-13 05:56 UTC, shmsr approved these changes

2024-02-13 06:00 UTC, muthu-mps commented on packages/awsfargate/docs/README.md
>  In the step 1 select "Fargate" from the list of available launch types.
Can we update the `steps` in a similar way? The `Step 1` and `Step 2` are not aligned properly.

2024-02-13 06:09 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/8895)
* Commit: 4433ffcc5f73e11217e2555068069f4c6d6ac1f1

### History
* :green_heart: [Build #8884](https://buildkite.com/elastic/integrations/builds/8884) succeeded a6703d5a1a4b0b79bee86516d560d323457c270a
* :green_heart: [Build #8882](https://buildkite.com/elastic/integrations/builds/8882) succeeded 4ab439fd301055ae7b9be155e77956572be3ddd0

cc @lucian-ioan

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8895","number":8895,"commit":"4433ffcc5f73e11217e2555068069f4c6d6ac1f1"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8884","number":8884,"commit":"a6703d5a1a4b0b79bee86516d560d323457c270a"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8882","number":8882,"commit":"4ab439fd301055ae7b9be155e77956572be3ddd0"}],"number":8895}
buildkite-pr-comment-->

2024-02-13 06:18 UTC, lucian-ioan commented on packages/awsfargate/docs/README.md
>  In the step 1 select "Fargate" from the list of available launch types.
Makes sense, thank you!

<img width="501" alt="bullet_point" src="https://github.com/elastic/integrations/assets/59661554/2d7318e7-af42-4483-b541-ef9809dd5126">

2024-02-13 06:31 UTC, muthu-mps approved these changes
LGTM!

2024-02-13 06:32 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/8899)
* Commit: d2be252d14f4a7a3d17b557b1cd31ad9574e2407

### History
* :green_heart: [Build #8895](https://buildkite.com/elastic/integrations/builds/8895) succeeded 4433ffcc5f73e11217e2555068069f4c6d6ac1f1
* :green_heart: [Build #8884](https://buildkite.com/elastic/integrations/builds/8884) succeeded a6703d5a1a4b0b79bee86516d560d323457c270a
* :green_heart: [Build #8882](https://buildkite.com/elastic/integrations/builds/8882) succeeded 4ab439fd301055ae7b9be155e77956572be3ddd0

cc @lucian-ioan

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8899","number":8899,"commit":"d2be252d14f4a7a3d17b557b1cd31ad9574e2407"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8895","number":8895,"commit":"4433ffcc5f73e11217e2555068069f4c6d6ac1f1"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8884","number":8884,"commit":"a6703d5a1a4b0b79bee86516d560d323457c270a"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8882","number":8882,"commit":"4ab439fd301055ae7b9be155e77956572be3ddd0"}],"number":8899}
buildkite-pr-comment-->

2024-02-14 12:07 UTC, alaudazzi approved these changes
Left a very minor edit, otherwise LGTM.

2024-02-14 12:07 UTC, alaudazzi commented on packages/awsfargate/_dev/build/docs/README.md
> +## Getting Started using the AWS CLI
```suggestion
## Getting started using the AWS CLI
```

2024-02-14 15:06 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/8941)
* Commit: 2dae53d58a13bd3c92df4aea254114c2c87c3be7

### History
* :green_heart: [Build #8899](https://buildkite.com/elastic/integrations/builds/8899) succeeded d2be252d14f4a7a3d17b557b1cd31ad9574e2407
* :green_heart: [Build #8895](https://buildkite.com/elastic/integrations/builds/8895) succeeded 4433ffcc5f73e11217e2555068069f4c6d6ac1f1
* :green_heart: [Build #8884](https://buildkite.com/elastic/integrations/builds/8884) succeeded a6703d5a1a4b0b79bee86516d560d323457c270a
* :green_heart: [Build #8882](https://buildkite.com/elastic/integrations/builds/8882) succeeded 4ab439fd301055ae7b9be155e77956572be3ddd0

cc @lucian-ioan

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8941","number":8941,"commit":"2dae53d58a13bd3c92df4aea254114c2c87c3be7"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8899","number":8899,"commit":"d2be252d14f4a7a3d17b557b1cd31ad9574e2407"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8895","number":8895,"commit":"4433ffcc5f73e11217e2555068069f4c6d6ac1f1"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8884","number":8884,"commit":"a6703d5a1a4b0b79bee86516d560d323457c270a"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/8882","number":8882,"commit":"4ab439fd301055ae7b9be155e77956572be3ddd0"}],"number":8941}
buildkite-pr-comment-->

2024-02-14 15:10 UTC, merged

2024-02-14 15:23 UTC, elasticmachine commented
Package awsfargate - 0.5.1 containing this change is available at https://epr.elastic.co/search?package=awsfargate