[cisco_ise] remove duplicate event code number 60077
elastic/integrations pull request #9165
Opened 2024-02-15 06:41 UTC by xtruthx

…9163

## Type of change
- Bug
- Enhancement

## What does this PR do?
Explainend in #9163  

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [] I have added an entry to my package's `changelog.yml` file.
- [] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

## Related issues
- Closes #9163  

Pinging @elastic/integrations (Team:Integrations)

2024-02-15 08:19 UTC, xtruthx commented
Sorry the mess now it should be up2date.

2024-02-20 11:49 UTC, elasticmachine commented
Pinging @elastic/sec-deployment-and-devices (Team:Security-Deployment and Devices)

2024-02-22 18:00 UTC, taylor-swanson requested changes

2024-02-26 05:01 UTC, xtruthx commented on packages/cisco_ise/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/8269
thx resolved

2024-02-26 05:31 UTC, xtruthx commented on packages/cisco_ise/manifest.yml
> +    version: ^8.10.0
Sorry I thought I had to change that the test had criticized a too low version

2024-02-26 14:03 UTC, taylor-swanson approved these changes
LGTM

2024-02-26 14:03 UTC, taylor-swanson commented
/test

2024-02-26 14:07 UTC, taylor-swanson commented on packages/cisco_ise/manifest.yml
> +    version: ^8.10.0
No worries! If you're referring to this message:

```
conditions.kibana.version must be ^8.10.0 or greater to include saved object tags file: kibana/tags.yml (SVR00005)
```

It's a validation error that is being skipped, so it can be ignored for the moment.

2024-02-26 14:18 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/9271)
* Commit: fdbe6403d2fdd36c579de292559bf1a5edaa327d

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9271","number":9271,"commit":"fdbe6403d2fdd36c579de292559bf1a5edaa327d"}],"number":9271}
buildkite-pr-comment-->

2024-02-26 14:22 UTC, merged

2024-02-26 14:33 UTC, elasticmachine commented
Package cisco_ise - 1.21.4 containing this change is available at https://epr.elastic.co/search?package=cisco_ise

2024-02-26 14:49 UTC, xtruthx commented
Thx