Update the Kibana version condition and mongodb documentation.
elastic/integrations pull request #9189
Opened 2024-02-19 06:51 UTC by ritalwar

## Proposed commit message

This PR updates the Kibana version condition for mongodb multihost fix support which is available from version 8.9.0 and it also adds configuration examples for MongoDB `hosts` field to the documentation.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

- Closes #9162 

## Screenshots

2024-02-19 07:13 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/9061)
* Commit: 5dd187c85eedd4c1bfc46ae73394d3e195f1bf1d

cc @ritalwar

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9061","number":9061,"commit":"5dd187c85eedd4c1bfc46ae73394d3e195f1bf1d"}],"number":9061}
buildkite-pr-comment-->

2024-02-19 07:40 UTC, shmsr requested changes

2024-02-19 07:40 UTC, shmsr commented on packages/mongodb/_dev/build/docs/README.md
> +The username and password can either be included in the URL or set using the respective configuration options. If included in the URL, the credentials take precedence over the username and password c
```suggestion
The username and password can either be included in the URL or set using the respective configuration options. If included in the URL, these credentials take precedence over any configured username and password configuration options.
```

2024-02-19 07:40 UTC, shmsr commented on packages/mongodb/_dev/build/docs/README.md
> +When configuring the `hosts` option, MongoDB URLs should adhere to the following formats:
```suggestion
When configuring the `hosts` option, MongoDB URLs must adhere to the following formats:
```

2024-02-19 07:40 UTC, shmsr commented on packages/mongodb/_dev/build/docs/README.md
> +- Basic: `localhost`
```suggestion
- Simple: `localhost`
```

2024-02-19 07:40 UTC, shmsr commented on packages/mongodb/_dev/build/docs/README.md
> +When utilizing the parameter `directConnection=true` in the connection URI, all operations are executed on the specified host. It's important to explicitly include `directConnection=true` in the URI,
```suggestion
When using the `directConnection=true` parameter in the connection URI, all operations are executed on the specified host. It's important to explicitly include `directConnection=true` in the URI as it won't be automatically added.
```

2024-02-19 07:40 UTC, shmsr commented on packages/mongodb/_dev/build/docs/README.md
> +The username and password can either be included in the URL or set using the respective configuration options. If included in the URL, the credentials take precedence over the username and password c
Also, instead of URL, isn't URI is better?

2024-02-19 07:42 UTC, shmsr commented on packages/mongodb/_dev/build/docs/README.md
> +When utilizing the parameter `directConnection=true` in the connection URI, all operations are executed on the specified host. It's important to explicitly include `directConnection=true` in the URI,
URI is used here. I think all other instances of URL should be renamed with URI.

2024-02-19 08:26 UTC, aliabbas-elastic commented on packages/mongodb/_dev/build/docs/README.md
> +- Simple: `[mongodb://][user:pass@]host[:port][?options]`
```suggestion
- Simple: `mongodb://[user:pass@]host[:port][?options]`
```
If this is fixed then can we remove it?

2024-02-19 08:29 UTC, aliabbas-elastic commented on packages/mongodb/docs/README.md
> +- `mongodb://localhost:27017,localhost:27022,localhost:27023/?replicaSet=dbrs`
Does this mean that for all the hosts the metrics would be fetched from `dbrs` replica set?

2024-02-19 08:36 UTC, aliabbas-elastic commented on packages/mongodb/_dev/build/docs/README.md
> +- Complex: `mongodb://myuser:mypass@localhost:40001", "otherhost:40001`
```suggestion
- Complex: `mongodb://myuser:mypass@localhost:40001", "mongodb://otherhost:40002`
```

2024-02-21 08:32 UTC, ritalwar commented on packages/mongodb/docs/README.md
> +- `mongodb://localhost:27017,localhost:27022,localhost:27023/?replicaSet=dbrs`
Specifying the replica set name in the connection string just tells the client which replica set to connect to. In MongoDB, replica sets involve multiple instances replicating data for redundancy and fault tolerance. More on replica sets [here](https://www.mongodb.com/docs/manual/replication/#:~:text=A%20replica%20set%20in%20MongoDB,and%20architecture%20of%20replica%20sets.).

2024-02-21 08:35 UTC, ritalwar commented on packages/mongodb/_dev/build/docs/README.md
> +- Complex: `mongodb://myuser:mypass@localhost:40001", "otherhost:40001`
`mongodb://myuser:mypass@localhost:40001", "otherhost:40001`
This is valid and should work fine.  Please refer to [this](https://www.mongodb.com/docs/manual/reference/connection-string/) for more examples of connection strings.

2024-02-21 08:49 UTC, aliabbas-elastic approved these changes
LGTM

2024-02-21 09:01 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/9126)
* Commit: 5b952676c090204a19de97c73b10f7826719cacb

### History
* :green_heart: [Build #9061](https://buildkite.com/elastic/integrations/builds/9061) succeeded 5dd187c85eedd4c1bfc46ae73394d3e195f1bf1d

cc @ritalwar

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9126","number":9126,"commit":"5b952676c090204a19de97c73b10f7826719cacb"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9061","number":9061,"commit":"5dd187c85eedd4c1bfc46ae73394d3e195f1bf1d"}],"number":9126}
buildkite-pr-comment-->

2024-02-21 11:49 UTC, shmsr approved these changes

2024-02-21 11:50 UTC, merged

2024-02-21 12:02 UTC, elasticmachine commented
Package mongodb - 1.13.1 containing this change is available at https://epr.elastic.co/search?package=mongodb