[cisco_asa] Add grok support for 722022, 722023 logs
elastic/integrations pull request #9222
Opened 2024-02-22 11:07 UTC by jrmolin

## Type of change
- Enhancement

## Proposed commit message
Add grok patterns for Cisco ASA logs with message id 722022 and 722023.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist
- [ ] 

## How to test this PR locally
The pipeline tests were updated to verify this fix works against sample data provided by the customer.

## Related issues
- Closes #9012

## Screenshots

2024-02-22 11:17 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/9197)
* Commit: f1cdea5684b45b6c84544a2d7ee436fbe323f014

### Failed CI Steps
* [Check integrations cisco_asa](https://buildkite.com/elastic/integrations/builds/9197#018dd082-c501-4d90-bc26-4f283446ebbd)

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9197","number":9197,"commit":"f1cdea5684b45b6c84544a2d7ee436fbe323f014"}],"number":9197}
buildkite-pr-comment-->

2024-02-22 13:34 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-02-22 13:35 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/9204)
* Commit: 87a3e9de1b8b46133be1e3d60789e561dd77e1ac

### History
* :broken_heart: [Build #9197](https://buildkite.com/elastic/integrations/builds/9197) failed f1cdea5684b45b6c84544a2d7ee436fbe323f014

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9204","number":9204,"commit":"87a3e9de1b8b46133be1e3d60789e561dd77e1ac"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9197","number":9197,"commit":"f1cdea5684b45b6c84544a2d7ee436fbe323f014"}],"number":9204}
buildkite-pr-comment-->

2024-02-22 17:34 UTC, taylor-swanson requested changes
The grok patterns aren't extracting the inner values when a field is wrapped in angle brackets. I think for now, it is sufficient to have two patterns, one with angle brackets and one without. In theory, the first pattern should exit as soon as it doesn't see the angle bracket and it will try the next one. This happens very early in the string (it's not like it has to get all the way to the end of the pattern to find that out).

The other thing to consider is that there is a pretty well established pattern in the integration with the other grok processors, where they have two patterns, one with angle brackets, one without. I say we stick to that pattern for now. I tried a few different ideas myself, but I can't get it to quite work. If you want to have one pattern with optionals, you'd have to change the `NOTSPACE` pattern to something more restrictive to get it to work (basically something that doesn't include `<` and `>`). 

When testing grok patterns, I like to use the pipeline simulator to do rapid testing:

```
POST /_ingest/pipeline/_simulate?verbose=true
{
  "pipeline" :
  {
    "description": "_description",
    "processors": [
      {
        "grok": {
          "field": "message",
          "tag": "grok_message", 
          "patterns": [
            "^Group <%{NOTSPACE:source.user.group.name}> User <%{NOTSPACE:source.user.name}> IP <%{IP:source.address}> %{GREEDYDATA:event.reason}$",
            "^Group %{NOTSPACE:source.user.group.name} User %{NOTSPACE:source.user.name} IP %{IP:source.address} %{GREEDYDATA:event.reason}$"
          ]
        }
      }
    ]
  },
  "docs": [
    {
      "_index": "index",
      "_id": "id",
      "_source": {
        "message": "Group <MY-MFA> User <src_user@myorg.com> IP <67.43.156.118> TCP SVC connection established without compression"
      }
    },
    {
      "_index": "index",
      "_id": "id",
      "_source": {
        "message": "Group MY-MFA User src_user@myorg.com IP 67.43.156.118 TCP SVC connection established without compression"
      }
    }
  ]
}
```

One other thing to note, it is recommended to add anchors to the patterns (`^` and `$`). I forget the exact reasons why, but it does help with performance.

2024-02-22 17:34 UTC, taylor-swanson commented on packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
> +        OPTIONAL_GTLT: "(?:(<%{NOTSPACE}>)|%{NOTSPACE})"
This pattern won't extract the inner value, so it will still include the `<` and `>`.

2024-02-22 17:34 UTC, taylor-swanson commented on packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
> +        - 'Group (?:%{OPTIONAL_GTLT:source.user.group.name} )??User %{OPTIONAL_GTLT:source.user.name} IP <%{IP:source.address}> %{GREEDYDATA:event.reason}'
Is `Group TOKEN` actually optional here? All the provided example logs include Group with some value (at least the existing ones any way).

2024-02-23 14:47 UTC, jrmolin commented on packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-asa-missing-groups.log-expected.json
> +                        "name": "<MY-MFA>"
Yeah, this is because of the sample data I was working with. The documentation doesn't have any examples, and the sample data has no brackets on user email, though all other examples in the logs have angle brackets. I don't know what to do about this. I can force the angle brackets to be in there, and then get an error otherwise. The fact that they're mixed in the sample data seems weird to me.

2024-02-23 14:49 UTC, jrmolin commented on packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
> +        - 'Group (?:%{OPTIONAL_GTLT:source.user.group.name} )??User %{OPTIONAL_GTLT:source.user.name} IP <%{IP:source.address}> %{GREEDYDATA:event.reason}'
I have no idea if it's optional. I agree that the example logs in the tests have values. The provided sample data did not. I was told that there was an error in sanitizing the logs for the enhancement request.

2024-02-23 15:04 UTC, jrmolin commented on packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
> +        OPTIONAL_GTLT: "(?:(<%{NOTSPACE}>)|%{NOTSPACE})"
I stopped using it. I'm removing it.

2024-02-23 15:06 UTC, taylor-swanson commented on packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
> +        - 'Group (?:%{OPTIONAL_GTLT:source.user.group.name} )??User %{OPTIONAL_GTLT:source.user.name} IP <%{IP:source.address}> %{GREEDYDATA:event.reason}'
Based on the patterns of the other logs, I don't think it's optional, so I wouldn't bother trying to do that (unless we actually have real sample logs that show this behavior).

2024-02-23 15:21 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/9249)
* Commit: 20de3ef5eae12d96f8995c18aa7e714ffb70ff92

### History
* :green_heart: [Build #9204](https://buildkite.com/elastic/integrations/builds/9204) succeeded 87a3e9de1b8b46133be1e3d60789e561dd77e1ac
* :broken_heart: [Build #9197](https://buildkite.com/elastic/integrations/builds/9197) failed f1cdea5684b45b6c84544a2d7ee436fbe323f014

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9249","number":9249,"commit":"20de3ef5eae12d96f8995c18aa7e714ffb70ff92"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9204","number":9204,"commit":"87a3e9de1b8b46133be1e3d60789e561dd77e1ac"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9197","number":9197,"commit":"f1cdea5684b45b6c84544a2d7ee436fbe323f014"}],"number":9249}
buildkite-pr-comment-->

2024-02-23 18:05 UTC, merged

2024-02-23 18:18 UTC, elasticmachine commented
Package cisco_asa - 2.31.0 containing this change is available at https://epr.elastic.co/search?package=cisco_asa