[O11y][AWS] Rally benchmark `aws.waf`
elastic/integrations pull request #9377
Opened 2024-03-18 05:48 UTC by aliabbas-elastic

## Proposed commit message

- This PR adds benchmarking templates to the `waf` data stream of `AWS`

## Sample Response

<details>
  <summary>sample_event.json</summary>

  ```json

  ```
</details>

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.

## How to test this PR locally

Run this command from package root
- `elastic-package benchmark rally --benchmark waf-benchmark -v`
- `elastic-package benchmark stream --benchmark waf-benchmark -v`

## Related issues

- Relates #8636

## Screenshots

```

```

2024-03-18 07:11 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-03-18 07:12 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/9657)
* Commit: 37cdc12dc89ddd51ba4e1ab50f64b763306a0e50

cc @aliabbas-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9657","number":9657,"commit":"37cdc12dc89ddd51ba4e1ab50f64b763306a0e50"}],"number":9657}
buildkite-pr-comment-->

2024-03-27 04:34 UTC, milan-elastic commented
@aliabbas-elastic  Can you update the sample response in the description? It's not loading.

2024-03-27 04:45 UTC, aliabbas-elastic commented
> @aliabbas-elastic Can you update the sample response in the description? It's not loading.

Done

2024-03-28 05:46 UTC, milan-elastic approved these changes

2024-03-30 15:53 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/9977)
* Commit: a2518d53ef56a47486c3e7a892268d0870a720c7

### History
* :green_heart: [Build #9657](https://buildkite.com/elastic/integrations/builds/9657) succeeded 37cdc12dc89ddd51ba4e1ab50f64b763306a0e50

cc @aliabbas-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9977","number":9977,"commit":"a2518d53ef56a47486c3e7a892268d0870a720c7"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9657","number":9657,"commit":"37cdc12dc89ddd51ba4e1ab50f64b763306a0e50"}],"number":9977}
buildkite-pr-comment-->

2024-04-03 07:15 UTC, shmsr requested changes

2024-04-03 07:15 UTC, shmsr commented on packages/aws/_dev/benchmark/rally/waf-benchmark/config.yml
> +    value: "SQL_INJECTION"
https://docs.aws.amazon.com/waf/latest/developerguide/classic-web-acl-create-condition.html

From what I see there are more type of conditions: SQL_INJECTION, XSS_PATH, SIZE_RESTRICTION, GEO_MATCH, IP_MATCH, REGEX_MATCH

2024-04-03 07:15 UTC, shmsr commented on packages/aws/_dev/benchmark/rally/waf-benchmark/fields.yml
> +  type: keyowrd
```suggestion
  type: keyword
```

2024-04-03 07:15 UTC, shmsr commented on packages/aws/_dev/benchmark/rally/waf-benchmark/fields.yml
> +  example: themes/twentynineteen/style
Are you sure the example is correct?

2024-04-03 08:01 UTC, aliabbas-elastic commented on packages/aws/_dev/benchmark/rally/waf-benchmark/fields.yml
> +  example: themes/twentynineteen/style
Thanks for catching this. Actually this is a syntax rather than an exact value so this would give me three random generated words separated by `/`. But currently only [these](https://github.com/elastic/elastic-integration-corpus-generator-tool/blob/main/pkg/genlib/generator_interface.go#L400) ones are supported. After removing the lines here are the values generated under the `uri` field

- /wp-content/dirtqueen.min.css
- /wp-content/bitterthroat.css
- /wp-content/rubyfang.png

2024-04-03 09:19 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10058)
* Commit: 027cafb6cd8a3c558cfee903c7b23f280bbe8d0e

### History
* :green_heart: [Build #9977](https://buildkite.com/elastic/integrations/builds/9977) succeeded a2518d53ef56a47486c3e7a892268d0870a720c7
* :green_heart: [Build #9657](https://buildkite.com/elastic/integrations/builds/9657) succeeded 37cdc12dc89ddd51ba4e1ab50f64b763306a0e50

cc @aliabbas-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10058","number":10058,"commit":"027cafb6cd8a3c558cfee903c7b23f280bbe8d0e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9977","number":9977,"commit":"a2518d53ef56a47486c3e7a892268d0870a720c7"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9657","number":9657,"commit":"37cdc12dc89ddd51ba4e1ab50f64b763306a0e50"}],"number":10058}
buildkite-pr-comment-->

2024-04-03 10:55 UTC, shmsr approved these changes

2024-04-03 10:56 UTC, merged