Update description of Custom Logs input
elastic/integrations pull request #9386
Opened 2024-03-19 14:29 UTC by lucabelluccini

Update description of Custom Logs input to provide details to which settings can be used.

## Proposed commit message

Enhance the Custom Logs input description with a pointer to the docs.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] ~I have verified that all data streams collect metrics or logs.~ N/A
- [x] I have added an entry to my package's `changelog.yml` file.

2024-03-19 14:31 UTC, lucabelluccini commented
Hello, I've not tested it - if someone can check it renders properly it would be great ❤️

2024-03-19 14:37 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/9681)
* Commit: 10687fef5f3e3ffa30ae49b0ff1682360964fbe9

### Failed CI Steps
* [Check integrations log](https://buildkite.com/elastic/integrations/builds/9681#018e5721-a12a-4e9b-af48-8e0b1668d68f)

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9681","number":9681,"commit":"10687fef5f3e3ffa30ae49b0ff1682360964fbe9"}],"number":9681}
buildkite-pr-comment-->

2024-03-19 18:03 UTC, elasticmachine commented
Pinging @elastic/elastic-agent (Team:Elastic-Agent)

2024-03-20 06:56 UTC, belimawr requested changes

2024-03-20 06:56 UTC, belimawr commented on packages/log/manifest.yml
> +          Additional settings to be added to the configuration. Be careful using this as it might break the input as those settings are not validated and can override the settings specified above. Se
The Custom Logs integration uses the [log input](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-log.html)
```suggestion
          Additional settings to be added to the configuration. Be careful using this as it might break the input as those settings are not validated and can override the settings specified above. See [`log` input settings docs](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-log.html) for details.
```

2024-03-20 09:35 UTC, lucabelluccini commented on packages/log/manifest.yml
> +          Additional settings to be added to the configuration. Be careful using this as it might break the input as those settings are not validated and can override the settings specified above. Se
🤦 indeed

2024-03-20 09:41 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/9704)
* Commit: bcf1eabad1e86c3b5c71846d8782870cfc7c93b8

### Failed CI Steps
* [Check integrations log](https://buildkite.com/elastic/integrations/builds/9704#018e5b39-57ca-445e-9883-f7815f2c3af6)

### History
* :broken_heart: [Build #9681](https://buildkite.com/elastic/integrations/builds/9681) failed 10687fef5f3e3ffa30ae49b0ff1682360964fbe9

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9704","number":9704,"commit":"bcf1eabad1e86c3b5c71846d8782870cfc7c93b8"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9681","number":9681,"commit":"10687fef5f3e3ffa30ae49b0ff1682360964fbe9"}],"number":9704}
buildkite-pr-comment-->

2024-03-21 18:58 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/9756)
* Commit: 1a96e5c5ac1f813b1f56f45445a402b59b6cc0e4

### History
* :broken_heart: [Build #9704](https://buildkite.com/elastic/integrations/builds/9704) failed bcf1eabad1e86c3b5c71846d8782870cfc7c93b8
* :broken_heart: [Build #9681](https://buildkite.com/elastic/integrations/builds/9681) failed 10687fef5f3e3ffa30ae49b0ff1682360964fbe9

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9756","number":9756,"commit":"1a96e5c5ac1f813b1f56f45445a402b59b6cc0e4"},{"buildStatus":{"state":"failed","success":false,"hasRetries":true,"hasNonPreemptionRetries":true},"url":"https://buildkite.com/elastic/integrations/builds/9704","number":9704,"commit":"bcf1eabad1e86c3b5c71846d8782870cfc7c93b8"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9681","number":9681,"commit":"10687fef5f3e3ffa30ae49b0ff1682360964fbe9"}],"number":9756}
buildkite-pr-comment-->

2024-03-21 19:25 UTC, rdner approved these changes

2024-03-22 08:08 UTC, belimawr approved these changes

2024-03-22 08:09 UTC, merged

2024-03-22 08:21 UTC, elasticmachine commented
Package log - 2.3.1 containing this change is available at https://epr.elastic.co/search?package=log