etcd: Added ssl options
elastic/integrations pull request #9414
Opened 2024-03-21 18:03 UTC by alstolten

## Proposed commit message

Add `ssl` options to the etcd integration. 

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- some of the formatting changes seemed to have been introduced by `elastic-package build`, they were not made by me

## How to test this PR locally

- This is a little tricky to test. I tested locally with the minikube etcd server and the `elastic-package stack`. The agent deployed with the elastic-package stack needs to be added to the minikube docker network (`docker network connect minikube  elastic-package-stack-elastic-agent-1`)
- the certs to the minikube etcd are in `/var/lib/docker/volumes/minikube/_data/lib/minikube/certs/etcd` by default
- I tested v3 metrics
- data was successfully ingested and the shipped Dashboard did contain data
- agent policy did contain the correct configuration
- integration configuration UI showed the field

## Related issues

This is very related to:
- https://github.com/elastic/integrations/issues/4666
I followed the pattern used in:
- https://github.com/elastic/integrations/pull/4912

- closes https://github.com/elastic/integrations/issues/9408 

## Screenshots

![Screenshot from 2024-03-21 19-01-20](https://github.com/elastic/integrations/assets/47385660/ac99f0b8-2e44-4541-abd2-2aba8dc16be7)

![Screenshot from 2024-03-21 18-40-33](https://github.com/elastic/integrations/assets/47385660/b3454617-35b4-42f6-9103-0556005430a4)

![Screenshot from 2024-03-21 18-43-29](https://github.com/elastic/integrations/assets/47385660/ef043027-85f7-426d-93a5-0a19179632af)

2024-03-21 18:04 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/9753)
* Commit: 1d022434cf96ec2ed98051ec03fe063a8905dc06

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/9753#018e622e-98b4-4bf2-b626-89003d04a565)

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9753","number":9753,"commit":"1d022434cf96ec2ed98051ec03fe063a8905dc06"}],"number":9753}
buildkite-pr-comment-->

2024-03-21 18:10 UTC, alstolten commented
Now also based on the right version...

2024-03-21 18:23 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/9755)
* Commit: e22144330e96ea89c10bc7c6544e7c762f083375

### History
* :broken_heart: [Build #9753](https://buildkite.com/elastic/integrations/builds/9753) failed 1d022434cf96ec2ed98051ec03fe063a8905dc06

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9755","number":9755,"commit":"e22144330e96ea89c10bc7c6544e7c762f083375"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9753","number":9753,"commit":"1d022434cf96ec2ed98051ec03fe063a8905dc06"}],"number":9755}
buildkite-pr-comment-->

2024-03-26 04:43 UTC, aliabbas-elastic requested changes

2024-03-26 04:43 UTC, aliabbas-elastic commented on packages/etcd/changelog.yml
> +      link: https://github.com/elastic/integrations/issues/9408
```suggestion
      link: https://github.com/elastic/integrations/pull/9414
```
Any reason to include the issue link instead of PR?

2024-03-26 04:43 UTC, aliabbas-elastic commented on packages/etcd/changelog.yml
> +    - description: Add `ssl` configuration option for metricsets
```suggestion
    - description: Add `ssl` configuration option for metricsets.
```
minor nit

2024-03-27 08:05 UTC, alstolten commented on packages/etcd/changelog.yml
> +      link: https://github.com/elastic/integrations/issues/9408
No, not really. Was not sure about the convention.

2024-03-27 08:20 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/9900)
* Commit: 9e7fa5169b1518dc7f8c51c5d204a25a5491272b

### Failed CI Steps
* [Check integrations etcd](https://buildkite.com/elastic/integrations/builds/9900#018e7ef7-2229-42d4-bad0-33468f43cba2)

### History
* :green_heart: [Build #9755](https://buildkite.com/elastic/integrations/builds/9755) succeeded e22144330e96ea89c10bc7c6544e7c762f083375
* :broken_heart: [Build #9753](https://buildkite.com/elastic/integrations/builds/9753) failed 1d022434cf96ec2ed98051ec03fe063a8905dc06

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9900","number":9900,"commit":"9e7fa5169b1518dc7f8c51c5d204a25a5491272b"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9755","number":9755,"commit":"e22144330e96ea89c10bc7c6544e7c762f083375"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9753","number":9753,"commit":"1d022434cf96ec2ed98051ec03fe063a8905dc06"}],"number":9900}
buildkite-pr-comment-->

2024-03-27 12:04 UTC, aliabbas-elastic approved these changes
LGTM for rest changes

2024-04-02 15:10 UTC, alstolten commented
/buildkite build

2024-04-02 15:17 UTC, alstolten commented
Hi @aliabbas-elastic, could you let me know how I can re-trigger the build?

2024-04-02 15:22 UTC, aliabbas-elastic commented
/test

2024-04-02 15:36 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10021)
* Commit: 9e7fa5169b1518dc7f8c51c5d204a25a5491272b

### History
* :broken_heart: [Build #9900](https://buildkite.com/elastic/integrations/builds/9900) failed 9e7fa5169b1518dc7f8c51c5d204a25a5491272b
* :green_heart: [Build #9755](https://buildkite.com/elastic/integrations/builds/9755) succeeded e22144330e96ea89c10bc7c6544e7c762f083375
* :broken_heart: [Build #9753](https://buildkite.com/elastic/integrations/builds/9753) failed 1d022434cf96ec2ed98051ec03fe063a8905dc06

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10021","number":10021,"commit":"9e7fa5169b1518dc7f8c51c5d204a25a5491272b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9900","number":9900,"commit":"9e7fa5169b1518dc7f8c51c5d204a25a5491272b"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9755","number":9755,"commit":"e22144330e96ea89c10bc7c6544e7c762f083375"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9753","number":9753,"commit":"1d022434cf96ec2ed98051ec03fe063a8905dc06"}],"number":10021}
buildkite-pr-comment-->

2024-04-07 22:51 UTC, gpop63 approved these changes

2024-04-22 09:34 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10613)
* Commit: 754da9a8986d9221cfb28945c291f8a20441fbf8

### History
* :green_heart: [Build #10021](https://buildkite.com/elastic/integrations/builds/10021) succeeded 9e7fa5169b1518dc7f8c51c5d204a25a5491272b
* :broken_heart: [Build #9900](https://buildkite.com/elastic/integrations/builds/9900) failed 9e7fa5169b1518dc7f8c51c5d204a25a5491272b
* :green_heart: [Build #9755](https://buildkite.com/elastic/integrations/builds/9755) succeeded e22144330e96ea89c10bc7c6544e7c762f083375
* :broken_heart: [Build #9753](https://buildkite.com/elastic/integrations/builds/9753) failed 1d022434cf96ec2ed98051ec03fe063a8905dc06

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10613","number":10613,"commit":"754da9a8986d9221cfb28945c291f8a20441fbf8"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10021","number":10021,"commit":"9e7fa5169b1518dc7f8c51c5d204a25a5491272b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9900","number":9900,"commit":"9e7fa5169b1518dc7f8c51c5d204a25a5491272b"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9755","number":9755,"commit":"e22144330e96ea89c10bc7c6544e7c762f083375"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9753","number":9753,"commit":"1d022434cf96ec2ed98051ec03fe063a8905dc06"}],"number":10613}
buildkite-pr-comment-->

2024-04-25 05:01 UTC, ishleenk17 reviewed
In general, this PR has many files with irrelevant changes. 
Maybe, related to formatting. Please revert those.

2024-05-04 21:41 UTC, gpop63 commented on packages/etcd/data_stream/leader/fields/fields.yml
> +
The changes are from the `elastic-package format` command, do you think we should revert them?

2024-05-17 12:03 UTC, Alphayeeeet commented
Is there also the possibility to specify file system paths instead of certificate content inline? WIth this option, you could use the respective Cert and Key files available on Kubernetes Master Nodes.

2024-05-17 14:21 UTC, gpop63 commented
@Alphayeeeet yes, you can specify path to certs or certs content.

2024-05-28 11:13 UTC, ishleenk17 commented on packages/etcd/data_stream/leader/fields/fields.yml
> +
Let it be then!

2024-05-28 11:34 UTC, ishleenk17 commented on packages/etcd/data_stream/leader/fields/fields.yml
> +
Should be good then.

2024-05-28 11:36 UTC, ishleenk17 commented on packages/etcd/manifest.yml
> +    description: i.e. certificate, certificate_authorities, verification_mode etc. See [SSL](https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-ssl.html#ssl-client-config) for det
yes

2024-05-28 11:38 UTC, ishleenk17 approved these changes
Looks good!

2024-05-28 11:38 UTC, merged

2024-05-28 11:51 UTC, elasticmachine commented
Package etcd - 1.1.0 containing this change is available at https://epr.elastic.co/search?package=etcd