Adding period parameter for counter cache in remote write
elastic/integrations pull request #9424
Opened 2024-03-22 11:58 UTC by gizas

- Bug

## Proposed commit message

- WHAT: Added period parameter for counter cache in remote write dataset of prometheus
- WHY:  The rate calculation of counter metrics in Prometheus remote_write dataset was reporting zero values

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally

1. Checkout this branch
2. `cd packages/prometheus`
3. Run `elastic-package build` command
4. Initiate a new Elastic cluster `elastic-package stack up -d -v --version=8.14.0-SNAPSHOT` 
5. Login to Kibana and **install Prometheus Assets**
6. Install prometheus server with remote write in your kubernetes cluster
7. Configure elastic-agent
```yaml
inputs:
    - name: prometheus
      type: prometheus/metrics
      use_output: default
      meta:
        package:
          name: prometheus
          version: 1.15.1
      data_stream:
        namespace: default
      streams:
        - data_stream:
            dataset: prometheus.remote_write
            type: metrics
          metricsets:
            - remote_write
          host: '0.0.0.0'
          port: 9201
          rate_counters: true
          use_types: true
          period: 1m
```

## Related issues

- Relates #https://github.com/elastic/beats/issues/38458

## Screenshots

For my local kubernetes cluster (40m evidence for correct rate calculation with elastic-agent-standalone manifest)

![Screenshot 2024-03-22 at 12 02 13 PM](https://github.com/elastic/integrations/assets/1685415/68fcab06-1a61-4142-b9b9-753d4e832dbf)

2024-03-22 12:13 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/9795)
* Commit: 2a66345b76cdbe4e380f9fbae2ad0d90e7854920

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9795","number":9795,"commit":"2a66345b76cdbe4e380f9fbae2ad0d90e7854920"}],"number":9795}
buildkite-pr-comment-->

2024-03-22 12:17 UTC, lalit-satapathy approved these changes
LGTM.

2024-03-22 12:17 UTC, lalit-satapathy commented on packages/prometheus/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/9321
Nit: fix the PR number

2024-03-22 12:40 UTC, gizas commented on packages/prometheus/changelog.yml
> +      link: https://github.com/elastic/integrations/pull/9321
Thank you!!!! Missed it, done

2024-03-22 12:53 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/9796)
* Commit: 710893da532cfdce03a6b0d368057ace1bef0ded

### History
* :green_heart: [Build #9795](https://buildkite.com/elastic/integrations/builds/9795) succeeded 2a66345b76cdbe4e380f9fbae2ad0d90e7854920

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9796","number":9796,"commit":"710893da532cfdce03a6b0d368057ace1bef0ded"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9795","number":9795,"commit":"2a66345b76cdbe4e380f9fbae2ad0d90e7854920"}],"number":9796}
buildkite-pr-comment-->

2024-03-25 02:53 UTC, shmsr requested changes

2024-03-25 02:53 UTC, shmsr commented on packages/prometheus/data_stream/remote_write/manifest.yml
> +        description: This is the timeout period of the counter cache used to calculate the counter rates
```suggestion
        description: This is the timeout period for the counter cache, which is used to calculate counter rates.
```

2024-03-25 02:53 UTC, shmsr commented on packages/prometheus/changelog.yml
> +    - description: Add Period parameter for counter cache
```suggestion
    - description: Add a "period" parameter to the counter cache.
```

2024-03-27 09:13 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/9902)
* Commit: 7111b3e02db035b3ca54d69397c4056995e085ed

### History
* :green_heart: [Build #9796](https://buildkite.com/elastic/integrations/builds/9796) succeeded 710893da532cfdce03a6b0d368057ace1bef0ded
* :green_heart: [Build #9795](https://buildkite.com/elastic/integrations/builds/9795) succeeded 2a66345b76cdbe4e380f9fbae2ad0d90e7854920

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9902","number":9902,"commit":"7111b3e02db035b3ca54d69397c4056995e085ed"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9796","number":9796,"commit":"710893da532cfdce03a6b0d368057ace1bef0ded"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9795","number":9795,"commit":"2a66345b76cdbe4e380f9fbae2ad0d90e7854920"}],"number":9902}
buildkite-pr-comment-->

2024-03-27 09:40 UTC, ishleenk17 approved these changes
Looks good!

2024-03-29 10:47 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/9960)
* Commit: 5d5ee2d45d096f8385539a2ac021531d408abe92

### History
* :green_heart: [Build #9902](https://buildkite.com/elastic/integrations/builds/9902) succeeded 7111b3e02db035b3ca54d69397c4056995e085ed
* :green_heart: [Build #9796](https://buildkite.com/elastic/integrations/builds/9796) succeeded 710893da532cfdce03a6b0d368057ace1bef0ded
* :green_heart: [Build #9795](https://buildkite.com/elastic/integrations/builds/9795) succeeded 2a66345b76cdbe4e380f9fbae2ad0d90e7854920

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9960","number":9960,"commit":"5d5ee2d45d096f8385539a2ac021531d408abe92"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9902","number":9902,"commit":"7111b3e02db035b3ca54d69397c4056995e085ed"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9796","number":9796,"commit":"710893da532cfdce03a6b0d368057ace1bef0ded"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/9795","number":9795,"commit":"2a66345b76cdbe4e380f9fbae2ad0d90e7854920"}],"number":9960}
buildkite-pr-comment-->

2024-04-02 08:46 UTC, shmsr approved these changes

2024-04-02 08:57 UTC, merged

2024-04-02 09:10 UTC, elasticmachine commented
Package prometheus - 1.15.1 containing this change is available at https://epr.elastic.co/search?package=prometheus