Update README for osquery-manager
elastic/integrations pull request #948
Opened 2021-04-26 14:10 UTC by james-elastic

Update README for osquery manager.

## What does this PR do?

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.

## Author's Checklist

- [ ]

## How to test this PR locally

## Related issues

-

## Screenshots

2021-04-26 14:24 UTC, melissaburpo approved these changes
I took a last look and saw 2 things that might need an update; but overall it looks like it's ready to go!

2021-04-26 14:24 UTC, melissaburpo commented on packages/osquery_manager/docs/README.md
> +Undefined action query
@james-elastic - can we add a preface here that it's an example of an error response? Maybe even just:

> Error example: Undefined action query

2021-04-26 14:24 UTC, melissaburpo commented on packages/osquery_manager/docs/README.md
> +This integration supports x64_64 bit Windows, Darwin, and Linux platforms.
should this be `x86_64` instead of `x64_64` bit?

2021-04-26 14:40 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-948/detail/PR-948/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-948/detail/PR-948/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-948/detail/PR-948/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-948/detail/PR-948/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_948.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #948 opened`



* Start Time: 2021-04-26T14:10:56.454+0000


* Duration: 30 min 39 sec


* Commit: ff19ab383c0982639fe2fe161a20c43cbb595927



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 410  |
| Skipped      | 0 |
| Total        | 410   |


#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/PR-948/buildTimeGraph/png)


![Image of Tests](https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/PR-948/1/testReport/history/countGraph/png?start=0&amp;end=25)


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->









### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-948/detail/PR-948/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Check integration: osquery`
<ul>
<li>Took 0 min 1 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-948/runs/1/steps/551/log/?start=0">here</a></li>
<li>Description: <code>../../build/elastic-package check -v</code></l1>
</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-04-26T14:39:10.920Z] 2021/04/26 14:39:10 DEBUG creating test policy...
[2021-04-26T14:39:10.920Z] 2021/04/26 14:39:10 DEBUG POST http://127.0.0.1:5601/api/fleet/agent_policies
[2021-04-26T14:39:14.217Z] 2021/04/26 14:39:13 DEBUG adding package data stream to test policy...
[2021-04-26T14:39:14.217Z] 2021/04/26 14:39:13 DEBUG POST http://127.0.0.1:5601/api/fleet/package_policies
[2021-04-26T14:39:16.127Z] 2021/04/26 14:39:15 DEBUG deleting old data in data stream...
[2021-04-26T14:39:16.127Z] 2021/04/26 14:39:15 DEBUG found 0 hits in logs-zeek.x509-ep data stream
[2021-04-26T14:39:16.127Z] 2021/04/26 14:39:15 DEBUG GET http://127.0.0.1:5601/api/fleet/agent_policies/29cb7cd0-a69d-11eb-ac0c-a5f08436547f
[2021-04-26T14:39:16.127Z] 2021/04/26 14:39:15 DEBUG assigning package data stream to agent...
[2021-04-26T14:39:16.127Z] 2021/04/26 14:39:15 DEBUG PUT http://127.0.0.1:5601/api/fleet/agents/65684a74-3ca7-44c8-9c99-04afbd52267a/reassign
[2021-04-26T14:39:17.507Z] 2021/04/26 14:39:17 DEBUG GET http://127.0.0.1:5601/api/fleet/agents/65684a74-3ca7-44c8-9c99-04afbd52267a
[2021-04-26T14:39:17.507Z] 2021/04/26 14:39:17 DEBUG Wait until the policy (ID: 29cb7cd0-a69d-11eb-ac0c-a5f08436547f, revision: 2) is assigned to the agent (ID: 65684a74-3ca7-44c8-9c99-04afbd52267a)...
[2021-04-26T14:39:19.415Z] 2021/04/26 14:39:19 DEBUG GET http://127.0.0.1:5601/api/fleet/agents/65684a74-3ca7-44c8-9c99-04afbd52267a
[2021-04-26T14:39:19.415Z] 2021/04/26 14:39:19 DEBUG Wait until the policy (ID: 29cb7cd0-a69d-11eb-ac0c-a5f08436547f, revision: 2) is assigned to the agent (ID: 65684a74-3ca7-44c8-9c99-04afbd52267a)...
[2021-04-26T14:39:21.342Z] 2021/04/26 14:39:21 DEBUG GET http://127.0.0.1:5601/api/fleet/agents/65684a74-3ca7-44c8-9c99-04afbd52267a
[2021-04-26T14:39:21.342Z] 2021/04/26 14:39:21 DEBUG Wait until the policy (ID: 29cb7cd0-a69d-11eb-ac0c-a5f08436547f, revision: 2) is assigned to the agent (ID: 65684a74-3ca7-44c8-9c99-04afbd52267a)...
[2021-04-26T14:39:23.254Z] 2021/04/26 14:39:23 DEBUG GET http://127.0.0.1:5601/api/fleet/agents/65684a74-3ca7-44c8-9c99-04afbd52267a
[2021-04-26T14:39:23.254Z] 2021/04/26 14:39:23 DEBUG Policy revision assigned to the agent (ID: 65684a74-3ca7-44c8-9c99-04afbd52267a)...
[2021-04-26T14:39:23.254Z] 2021/04/26 14:39:23 DEBUG checking for expected data in data stream...
[2021-04-26T14:39:23.254Z] 2021/04/26 14:39:23 DEBUG found 0 hits in logs-zeek.x509-ep data stream
[2021-04-26T14:39:24.197Z] 2021/04/26 14:39:24 DEBUG found 0 hits in logs-zeek.x509-ep data stream
[2021-04-26T14:39:25.581Z] 2021/04/26 14:39:25 DEBUG found 0 hits in logs-zeek.x509-ep data stream
[2021-04-26T14:39:26.536Z] 2021/04/26 14:39:26 DEBUG found 0 hits in logs-zeek.x509-ep data stream
[2021-04-26T14:39:27.476Z] 2021/04/26 14:39:27 DEBUG found 0 hits in logs-zeek.x509-ep data stream
[2021-04-26T14:39:28.416Z] 2021/04/26 14:39:28 DEBUG found 1 hits in logs-zeek.x509-ep data stream
[2021-04-26T14:39:28.416Z] 2021/04/26 14:39:28 DEBUG reassigning original policy back to agent...
[2021-04-26T14:39:28.416Z] 2021/04/26 14:39:28 DEBUG PUT http://127.0.0.1:5601/api/fleet/agents/65684a74-3ca7-44c8-9c99-04afbd52267a/reassign
[2021-04-26T14:39:29.354Z] 2021/04/26 14:39:29 DEBUG GET http://127.0.0.1:5601/api/fleet/agents/65684a74-3ca7-44c8-9c99-04afbd52267a
[2021-04-26T14:39:29.354Z] 2021/04/26 14:39:29 DEBUG Wait until the policy (ID: 89e8c580-a69a-11eb-ac0c-a5f08436547f, revision: 1) is assigned to the agent (ID: 65684a74-3ca7-44c8-9c99-04afbd52267a)...
[2021-04-26T14:39:31.262Z] 2021/04/26 14:39:31 DEBUG GET http://127.0.0.1:5601/api/fleet/agents/65684a74-3ca7-44c8-9c99-04afbd52267a
[2021-04-26T14:39:31.262Z] 2021/04/26 14:39:31 DEBUG Wait until the policy (ID: 89e8c580-a69a-11eb-ac0c-a5f08436547f, revision: 1) is assigned to the agent (ID: 65684a74-3ca7-44c8-9c99-04afbd52267a)...
[2021-04-26T14:39:33.807Z] 2021/04/26 14:39:33 DEBUG GET http://127.0.0.1:5601/api/fleet/agents/65684a74-3ca7-44c8-9c99-04afbd52267a
[2021-04-26T14:39:33.807Z] 2021/04/26 14:39:33 DEBUG Wait until the policy (ID: 89e8c580-a69a-11eb-ac0c-a5f08436547f, revision: 1) is assigned to the agent (ID: 65684a74-3ca7-44c8-9c99-04afbd52267a)...
[2021-04-26T14:39:35.720Z] 2021/04/26 14:39:35 DEBUG GET http://127.0.0.1:5601/api/fleet/agents/65684a74-3ca7-44c8-9c99-04afbd52267a
[2021-04-26T14:39:35.720Z] 2021/04/26 14:39:35 DEBUG Policy revision assigned to the agent (ID: 65684a74-3ca7-44c8-9c99-04afbd52267a)...
[2021-04-26T14:39:35.720Z] 2021/04/26 14:39:35 DEBUG deleting test policy...
[2021-04-26T14:39:35.720Z] 2021/04/26 14:39:35 DEBUG POST http://127.0.0.1:5601/api/fleet/agent_policies/delete
[2021-04-26T14:39:37.649Z] 2021/04/26 14:39:37 DEBUG tearing down service...
[2021-04-26T14:39:37.649Z] 2021/04/26 14:39:37 DEBUG tearing down service using docker compose runner
[2021-04-26T14:39:37.649Z] 2021/04/26 14:39:37 DEBUG running command: /usr/local/bin/docker-compose -f /var/lib/jenkins/workspace/gest-manager_integrations_PR-948/src/github.com/elastic/integrations/packages/zeek/_dev/deploy/docker/docker-compose.yml -p elastic-package-service down
[2021-04-26T14:39:38.223Z] Removing elastic-package-service_zeek_1 ... 
[2021-04-26T14:39:38.223Z] 
Removing elastic-package-service_zeek_1 ... done
Removing network elastic-package-service_default
[2021-04-26T14:39:38.794Z] 2021/04/26 14:39:38 DEBUG del [...]

2021-04-26 14:55 UTC, james-elastic commented
@melissaburpo Done

2021-04-28 09:40 UTC, mtojek requested changes

2021-04-28 09:40 UTC, mtojek commented on packages/osquery_manager/manifest.yml
> +version: 0.2.2
Please update the changelog file, so it's consistent with manifest.yml.

2021-04-28 09:40 UTC, mtojek commented on packages/osquery_manager/docs/README.md
> +| Field | Description | Type |
Don't you prefer to use README templates? All fields/tables could be generated. Please look at the mysql integration as example: https://raw.githubusercontent.com/elastic/integrations/master/packages/mysql/_dev/build/docs/README.md

2021-04-28 14:19 UTC, mtojek requested changes

2021-04-28 14:19 UTC, mtojek commented on packages/osquery/changelog.yml
> +- version: "0.2.2"
What about the previous version: 0.2.1? Would you mind filling the missing entry too?

2021-04-29 13:25 UTC, james-elastic commented on packages/osquery/changelog.yml
> +- version: "0.2.2"
@mtojek Updated :)

2021-04-29 14:48 UTC, merged