[MongoDB Atlas] Add support of mongodb database datastream
elastic/integrations pull request #9539
Opened 2024-04-08 10:25 UTC by milan-elastic

## Proposed commit message

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## How to test this PR locally

## Related issues

- 

## Screenshots

2024-04-08 10:27 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10231)
* Commit: 2209b625e53635bf96e7c4304d5e94eb9d911411

### Failed CI Steps
* [:white_check_mark: Check go sources](https://buildkite.com/elastic/integrations/builds/10231#018ebd3e-a06f-4a65-9f05-dd38b5067e50)

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10231","number":10231,"commit":"2209b625e53635bf96e7c4304d5e94eb9d911411"}],"number":10231}
buildkite-pr-comment-->

2024-04-10 05:42 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10305)
* Commit: 0f8613efb699446eddaa358499849954b75cdb7d

### Failed CI Steps
* [:white_check_mark: Check go sources](https://buildkite.com/elastic/integrations/builds/10305#018ec686-c24e-4244-ad0f-16dfb61da8ce)

### History
* :broken_heart: [Build #10231](https://buildkite.com/elastic/integrations/builds/10231) failed 2209b625e53635bf96e7c4304d5e94eb9d911411

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10305","number":10305,"commit":"0f8613efb699446eddaa358499849954b75cdb7d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10231","number":10231,"commit":"2209b625e53635bf96e7c4304d5e94eb9d911411"}],"number":10305}
buildkite-pr-comment-->

2024-04-10 06:35 UTC, shmsr requested changes

2024-04-10 06:35 UTC, shmsr commented on packages/mongodb_atlas/_dev/build/docs/README.md
> +[MongoDB Atlas](https://www.mongodb.com/atlas) is a multi-cloud developer data platform. At its core is our fully managed cloud database for modern applications. Atlas is the best way to run MongoDB,
It's like we are selling MongoDB Atlas. I think if we instead use a very crisp one-liner, it should be good enough.

2024-04-10 06:35 UTC, shmsr commented on packages/mongodb_atlas/_dev/build/docs/README.md
> +- Create visualizations to monitor, measure and analyze the usage trend and key data, and derive business insights.
```suggestion
- Create informative visualizations to track usage trends, measure key metrics, and derive actionable business insights.
```

2024-04-10 06:35 UTC, shmsr commented on packages/mongodb_atlas/_dev/build/docs/README.md
> +- Collect Mongod Database logs.
```suggestion
- Collect MongoDB database logs for comprehensive monitoring and analysis.
```

2024-04-10 06:35 UTC, shmsr commented on packages/mongodb_atlas/_dev/build/docs/README.md
> +- Create alerts to reduce the MTTD and also the MTTR by referencing relevant logs when troubleshooting an issue.
```suggestion
- Set up alerts to minimize Mean Time to Detect (MTTD) and Mean Time to Resolve (MTTR) by quickly referencing relevant logs during troubleshooting.
```

2024-04-10 06:35 UTC, shmsr commented on packages/mongodb_atlas/_dev/build/docs/README.md
> +You can use our hosted Elasticsearch Service on Elastic Cloud, which is recommended or self-manage the Elastic Stack on your own hardware.
```suggestion
You can store and search your data using Elasticsearch and visualize and manage it with Kibana. We recommend using our hosted Elasticsearch Service on Elastic Cloud or self-managing the Elastic Stack on your own hardware.
```

2024-04-10 06:35 UTC, shmsr commented on packages/mongodb_atlas/_dev/deploy/docker/mongodb_atlas/main.go
> +}
```go
func generateDigest(username, realm, password, method, uri, nonce, nc, cnonce, qop string) string {
	ha1 := md5.New()
	fmt.Fprintf(ha1, "%s:%s:%s", username, realm, password)
	ha1Hex := fmt.Sprintf("%x", ha1.Sum(nil))

	ha2 := md5.New()
	fmt.Fprintf(ha2, "%s:%s", method, uri)
	ha2Hex := fmt.Sprintf("%x", ha2.Sum(nil))

	response := md5.New()
	fmt.Fprintf(response, "%s:%s:%s:%s:%s:%s", ha1Hex, nonce, nc, cnonce, qop, ha2Hex)
	return fmt.Sprintf("%x", response.Sum(nil))
}
```

I didn't test this but this should work just the same. But this one is small and clear.

2024-04-10 06:35 UTC, shmsr commented on packages/mongodb_atlas/_dev/build/docs/README.md
> +1. Generate programmatic API Keys with project owner permissions using the instructions in the Atlas [documentation](https://www.mongodb.com/docs/atlas/configure-api-access/#create-an-api-key-for-a-p
```suggestion
1. Generate programmatic API keys with project owner permissions by following the instructions in the Atlas [documentation](https://www.mongodb.com/docs/atlas/configure-api-access/#create-an-api-key-for-a-project). Then, copy the public and private keys which function as a username and API key respectively.
```

2024-04-10 06:35 UTC, shmsr commented on packages/mongodb_atlas/_dev/build/docs/README.md
> +2. Enable Database Auditing for the Atlas project for which you want to monitor logs, as described in this Atlas [document](https://www.mongodb.com/docs/atlas/database-auditing/#procedure).
```suggestion
2. Enable Database Auditing for the Atlas project you want to monitor logs. You can follow the instructions provided in this Atlas [document](https://www.mongodb.com/docs/atlas/database-auditing/#procedure).
```

2024-04-10 06:35 UTC, shmsr commented on packages/mongodb_atlas/_dev/build/docs/README.md
> +3. You can find your GroupId(ProjectID) in the Atlas UI. Go to your project, click Settings, and copy the GroupID(ProjectID). You can use the Atlas Admin API or Atlas CLI to find it programmatically.
```suggestion
3. You can find your Project ID (Group ID) in the Atlas UI. To do this, navigate to your project, click on Settings, and copy the Project ID (Group ID). You can also programmatically find it using the Atlas Admin API or Atlas CLI as described in this Atlas [document](https://www.mongodb.com/docs/atlas/app-services/apps/metadata/#find-a-project-id).
```

2024-04-10 06:35 UTC, shmsr commented on packages/mongodb_atlas/_dev/build/docs/README.md
> +### Enabling the integration in Elastic:
```suggestion
### Steps to enable Integration in Elastic
```

2024-04-10 06:35 UTC, shmsr commented on packages/mongodb_atlas/_dev/build/docs/README.md
> +6. Save the integration.
```suggestion
4. To add the integration, click on the "Add MongoDB Atlas" button.
5. Enter all the necessary configuration parameters, including Public Key, Private Key, and GroupId.
6. Finally, save the integration.
```

2024-04-10 06:35 UTC, shmsr commented on packages/mongodb_atlas/_dev/build/docs/README.md
> +- If the user encounters the following error during data ingestion, it is likely due to the data collected through this endpoint covers a long time span. As a result, generating a response may take l
```suggestion
If you encounter an error while ingesting data, it might be due to the data collected over a long time span. Generating a response in such cases may take longer and might cause a request timeout if the `HTTP Client Timeout` parameter is set to a small duration. To avoid this error, it is recommended to adjust the `HTTP Client Timeout` and `Interval` parameters based on the duration of data collection.
```

2024-04-10 06:47 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10306)
* Commit: 65e20e03208dc39935d6b8a6e2a17e271973a006

### Failed CI Steps
* [:white_check_mark: Check go sources](https://buildkite.com/elastic/integrations/builds/10306#018ec6c1-9ad3-41c2-b6cc-6dc015cd19ca)

### History
* :broken_heart: [Build #10305](https://buildkite.com/elastic/integrations/builds/10305) failed 0f8613efb699446eddaa358499849954b75cdb7d
* :broken_heart: [Build #10231](https://buildkite.com/elastic/integrations/builds/10231) failed 2209b625e53635bf96e7c4304d5e94eb9d911411

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10306","number":10306,"commit":"65e20e03208dc39935d6b8a6e2a17e271973a006"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10305","number":10305,"commit":"0f8613efb699446eddaa358499849954b75cdb7d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10231","number":10231,"commit":"2209b625e53635bf96e7c4304d5e94eb9d911411"}],"number":10306}
buildkite-pr-comment-->

2024-04-10 07:21 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10308)
* Commit: 43497c40804c8b85fbc91df2d53186c1058a381e

### Failed CI Steps
* [:white_check_mark: Check go sources](https://buildkite.com/elastic/integrations/builds/10308#018ec6e1-59b5-4f2e-8de6-000d36f3d30d)

### History
* :broken_heart: [Build #10307](https://buildkite.com/elastic/integrations/builds/10307) failed 318d8444a56b19a376866d124b84b9e0c1dc8ae3
* :broken_heart: [Build #10306](https://buildkite.com/elastic/integrations/builds/10306) failed 65e20e03208dc39935d6b8a6e2a17e271973a006
* :broken_heart: [Build #10305](https://buildkite.com/elastic/integrations/builds/10305) failed 0f8613efb699446eddaa358499849954b75cdb7d
* :broken_heart: [Build #10231](https://buildkite.com/elastic/integrations/builds/10231) failed 2209b625e53635bf96e7c4304d5e94eb9d911411

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10308","number":10308,"commit":"43497c40804c8b85fbc91df2d53186c1058a381e"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10307","number":10307,"commit":"318d8444a56b19a376866d124b84b9e0c1dc8ae3"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10306","number":10306,"commit":"65e20e03208dc39935d6b8a6e2a17e271973a006"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10305","number":10305,"commit":"0f8613efb699446eddaa358499849954b75cdb7d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10231","number":10231,"commit":"2209b625e53635bf96e7c4304d5e94eb9d911411"}],"number":10308}
buildkite-pr-comment-->

2024-04-10 13:23 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10334)
* Commit: fe891a7166881a12ff7f492596431c71ade63c41

### Failed CI Steps
* [:white_check_mark: Check go sources](https://buildkite.com/elastic/integrations/builds/10334#018ec82c-6598-408a-b212-212886be98ac)

### History
* :broken_heart: [Build #10308](https://buildkite.com/elastic/integrations/builds/10308) failed 43497c40804c8b85fbc91df2d53186c1058a381e
* :broken_heart: [Build #10307](https://buildkite.com/elastic/integrations/builds/10307) failed 318d8444a56b19a376866d124b84b9e0c1dc8ae3
* :broken_heart: [Build #10306](https://buildkite.com/elastic/integrations/builds/10306) failed 65e20e03208dc39935d6b8a6e2a17e271973a006
* :broken_heart: [Build #10305](https://buildkite.com/elastic/integrations/builds/10305) failed 0f8613efb699446eddaa358499849954b75cdb7d
* :broken_heart: [Build #10231](https://buildkite.com/elastic/integrations/builds/10231) failed 2209b625e53635bf96e7c4304d5e94eb9d911411

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10334","number":10334,"commit":"fe891a7166881a12ff7f492596431c71ade63c41"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10308","number":10308,"commit":"43497c40804c8b85fbc91df2d53186c1058a381e"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10307","number":10307,"commit":"318d8444a56b19a376866d124b84b9e0c1dc8ae3"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10306","number":10306,"commit":"65e20e03208dc39935d6b8a6e2a17e271973a006"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10305","number":10305,"commit":"0f8613efb699446eddaa358499849954b75cdb7d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10231","number":10231,"commit":"2209b625e53635bf96e7c4304d5e94eb9d911411"}],"number":10334}
buildkite-pr-comment-->

2024-04-12 07:18 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10380)
* Commit: 07431d80bb2c5cf7e7bbca4fcbf4c99b5d56855b

### Failed CI Steps
* [:white_check_mark: Check go sources](https://buildkite.com/elastic/integrations/builds/10380#018ed12b-25fd-4491-abb1-1048ad89cf14)

### History
* :broken_heart: [Build #10334](https://buildkite.com/elastic/integrations/builds/10334) failed fe891a7166881a12ff7f492596431c71ade63c41
* :broken_heart: [Build #10308](https://buildkite.com/elastic/integrations/builds/10308) failed 43497c40804c8b85fbc91df2d53186c1058a381e
* :broken_heart: [Build #10307](https://buildkite.com/elastic/integrations/builds/10307) failed 318d8444a56b19a376866d124b84b9e0c1dc8ae3
* :broken_heart: [Build #10306](https://buildkite.com/elastic/integrations/builds/10306) failed 65e20e03208dc39935d6b8a6e2a17e271973a006
* :broken_heart: [Build #10305](https://buildkite.com/elastic/integrations/builds/10305) failed 0f8613efb699446eddaa358499849954b75cdb7d

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10380","number":10380,"commit":"07431d80bb2c5cf7e7bbca4fcbf4c99b5d56855b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10334","number":10334,"commit":"fe891a7166881a12ff7f492596431c71ade63c41"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10308","number":10308,"commit":"43497c40804c8b85fbc91df2d53186c1058a381e"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10307","number":10307,"commit":"318d8444a56b19a376866d124b84b9e0c1dc8ae3"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10306","number":10306,"commit":"65e20e03208dc39935d6b8a6e2a17e271973a006"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10305","number":10305,"commit":"0f8613efb699446eddaa358499849954b75cdb7d"}],"number":10380}
buildkite-pr-comment-->

2024-04-15 07:16 UTC, muthu-mps reviewed
Please add different log samples in the pipeline test.

2024-04-15 10:01 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-04-15 11:01 UTC, milan-elastic commented
> Please add different log samples in the pipeline test.

Done, added more events for pipeline that we are managed to generate!

2024-04-15 11:29 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10429)
* Commit: 76ee648fa9597c25f1ee9aa5a5b3e5f01b83b191

### History
* :green_heart: [Build #10424](https://buildkite.com/elastic/integrations/builds/10424) succeeded 3e248e59247933e9ef1935cf9464d6235519e382
* :broken_heart: [Build #10380](https://buildkite.com/elastic/integrations/builds/10380) failed 07431d80bb2c5cf7e7bbca4fcbf4c99b5d56855b
* :broken_heart: [Build #10334](https://buildkite.com/elastic/integrations/builds/10334) failed fe891a7166881a12ff7f492596431c71ade63c41
* :broken_heart: [Build #10308](https://buildkite.com/elastic/integrations/builds/10308) failed 43497c40804c8b85fbc91df2d53186c1058a381e
* :broken_heart: [Build #10307](https://buildkite.com/elastic/integrations/builds/10307) failed 318d8444a56b19a376866d124b84b9e0c1dc8ae3
* :broken_heart: [Build #10306](https://buildkite.com/elastic/integrations/builds/10306) failed 65e20e03208dc39935d6b8a6e2a17e271973a006

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10429","number":10429,"commit":"76ee648fa9597c25f1ee9aa5a5b3e5f01b83b191"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10424","number":10424,"commit":"3e248e59247933e9ef1935cf9464d6235519e382"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10380","number":10380,"commit":"07431d80bb2c5cf7e7bbca4fcbf4c99b5d56855b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10334","number":10334,"commit":"fe891a7166881a12ff7f492596431c71ade63c41"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10308","number":10308,"commit":"43497c40804c8b85fbc91df2d53186c1058a381e"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10307","number":10307,"commit":"318d8444a56b19a376866d124b84b9e0c1dc8ae3"}],"number":10429}
buildkite-pr-comment-->

2024-04-16 12:20 UTC, SubhrataK commented
Please move the line graphs together.

2024-04-16 17:08 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10486)
* Commit: 297634e87a1200ebd1b31a38ad3c98e5e1a2f428

### History
* :green_heart: [Build #10429](https://buildkite.com/elastic/integrations/builds/10429) succeeded 76ee648fa9597c25f1ee9aa5a5b3e5f01b83b191
* :green_heart: [Build #10424](https://buildkite.com/elastic/integrations/builds/10424) succeeded 3e248e59247933e9ef1935cf9464d6235519e382
* :broken_heart: [Build #10380](https://buildkite.com/elastic/integrations/builds/10380) failed 07431d80bb2c5cf7e7bbca4fcbf4c99b5d56855b
* :broken_heart: [Build #10334](https://buildkite.com/elastic/integrations/builds/10334) failed fe891a7166881a12ff7f492596431c71ade63c41
* :broken_heart: [Build #10308](https://buildkite.com/elastic/integrations/builds/10308) failed 43497c40804c8b85fbc91df2d53186c1058a381e
* :broken_heart: [Build #10307](https://buildkite.com/elastic/integrations/builds/10307) failed 318d8444a56b19a376866d124b84b9e0c1dc8ae3

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10486","number":10486,"commit":"297634e87a1200ebd1b31a38ad3c98e5e1a2f428"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10429","number":10429,"commit":"76ee648fa9597c25f1ee9aa5a5b3e5f01b83b191"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10424","number":10424,"commit":"3e248e59247933e9ef1935cf9464d6235519e382"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10380","number":10380,"commit":"07431d80bb2c5cf7e7bbca4fcbf4c99b5d56855b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10334","number":10334,"commit":"fe891a7166881a12ff7f492596431c71ade63c41"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10308","number":10308,"commit":"43497c40804c8b85fbc91df2d53186c1058a381e"}],"number":10486}
buildkite-pr-comment-->

2024-04-16 17:40 UTC, milan-elastic commented
> Please move the line graphs together.

Done!

2024-04-16 17:50 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10489)
* Commit: 32b34cae6f41bd6a69dafb4e0094c0627ab9a1fa

### Failed CI Steps
* [Publish benchmarks](https://buildkite.com/elastic/integrations/builds/10489#018ee7fb-71a0-461c-a6ba-b73c58de7997)

### History
* :green_heart: [Build #10486](https://buildkite.com/elastic/integrations/builds/10486) succeeded 297634e87a1200ebd1b31a38ad3c98e5e1a2f428
* :green_heart: [Build #10429](https://buildkite.com/elastic/integrations/builds/10429) succeeded 76ee648fa9597c25f1ee9aa5a5b3e5f01b83b191
* :green_heart: [Build #10424](https://buildkite.com/elastic/integrations/builds/10424) succeeded 3e248e59247933e9ef1935cf9464d6235519e382
* :broken_heart: [Build #10380](https://buildkite.com/elastic/integrations/builds/10380) failed 07431d80bb2c5cf7e7bbca4fcbf4c99b5d56855b
* :broken_heart: [Build #10334](https://buildkite.com/elastic/integrations/builds/10334) failed fe891a7166881a12ff7f492596431c71ade63c41
* :broken_heart: [Build #10308](https://buildkite.com/elastic/integrations/builds/10308) failed 43497c40804c8b85fbc91df2d53186c1058a381e

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10489","number":10489,"commit":"32b34cae6f41bd6a69dafb4e0094c0627ab9a1fa"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10486","number":10486,"commit":"297634e87a1200ebd1b31a38ad3c98e5e1a2f428"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10429","number":10429,"commit":"76ee648fa9597c25f1ee9aa5a5b3e5f01b83b191"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10424","number":10424,"commit":"3e248e59247933e9ef1935cf9464d6235519e382"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10380","number":10380,"commit":"07431d80bb2c5cf7e7bbca4fcbf4c99b5d56855b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10334","number":10334,"commit":"fe891a7166881a12ff7f492596431c71ade63c41"}],"number":10489}
buildkite-pr-comment-->

2024-04-17 06:23 UTC, niraj-elastic requested changes

2024-04-17 06:23 UTC, niraj-elastic commented on packages/mongodb_atlas/data_stream/mongod_database/agent/stream/input.yml.hbs
> +program: |
Can we format this script. here is [reference](https://github.com/elastic/integrations/pull/9552#discussion_r1565160368) that might help you.

2024-04-17 06:23 UTC, niraj-elastic commented on packages/mongodb_atlas/data_stream/mongod_database/agent/stream/input.yml.hbs
> +redact:
`~` would be correct value for redact fields than `password`

2024-04-17 07:48 UTC, shmsr requested changes

2024-04-17 07:49 UTC, shmsr commented
Review comment:

```diff
diff --git a/packages/mongodb_atlas/data_stream/mongod_database/elasticsearch/ingest_pipeline/default.yml b/packages/mongodb_atlas/data_stream/mongod_database/elasticsearch/ingest_pipeline/default.yml
index 5b34df3d8..e6ad6f0f1 100644
--- a/packages/mongodb_atlas/data_stream/mongod_database/elasticsearch/ingest_pipeline/default.yml
+++ b/packages/mongodb_atlas/data_stream/mongod_database/elasticsearch/ingest_pipeline/default.yml
@@ -46,25 +46,27 @@ processors:
             value: '{{ _ingest.on_failure_message }}'
   - script:
       lang: painless
-      description: Provides descriptive value to the field.
+      description: Maps log severity levels to descriptive values
       tag: informative_log_level
       on_failure:
         - append:
             field: error.message
             value: 'Processor {{{_ingest.on_failure_processor_type}}} with tag {{{_ingest.on_failure_processor_tag}}} in pipeline {{{_ingest.on_failure_pipeline}}} failed with message: {{{_ingest.on_failure_message}}}'
+      params:
+        severity_levels:
+          F: fatal
+          E: error
+          W: warning
+          I: informational
+          D1: debug 1
+          D2: debug 2
+          D3: debug 3
+          D4: debug 4
+          D5: debug 5
       source: |
-        Map m = new HashMap();
-        m.put("F", "fatal");
-        m.put("E", "error");
-        m.put("W", "warning");
-        m.put("I", "informational");
-        m.put("D1", "debug 1");
-        m.put("D2", "debug 2");
-        m.put("D3", "debug 3");
-        m.put("D4", "debug 4");
-        m.put("D5", "debug 5");
-        if (m.get(ctx.json?.s) != null) {
-          ctx.severity = m.get(ctx.json.s);
+        String severity = ctx.json?.s;
+        if (severity != null) {
+          ctx.log.level = params.severity_levels.getOrDefault(severity, null);
         }
   - rename:
       field: severity
@@ -101,20 +103,27 @@ processors:
   - script:
       lang: painless
       source: |-
-        boolean drop(Object o) {
-          if (o == null || o == '') {
-            return true;
+        /**
+         * Recursively drops null and empty values from the Elasticsearch doc context.
+         *
+         * @param o The object to process (can be a Map, List, or any other type).
+         */
+        void drop(Object o) {
+          if (o instanceof List) {
+            ((List) o).removeIf(item -> {
+              drop(item);
+              return item == null;
+            });
           } else if (o instanceof Map) {
-            ((Map) o).values().removeIf(v -> drop(v));
-            return (((Map) o).size() == 0);
-          } else if (o instanceof List) {
-            ((List) o).removeIf(v -> drop(v));
-            return (((List) o).length == 0);
+            ((Map) o).values().removeIf(item -> {
+              drop(item);
+              return item == null;
+            });
           }
-          return false;
         }
+
         drop(ctx);
-      description: Drops null/empty values recursively.
+      description: Drops null and empty values recursively from the Elasticsearch document context.
   - remove:
       field:
         - event.original
@@ -125,6 +134,7 @@ processors:
       field:
         - json
       ignore_missing: true
+      description: Removes temporary fields.
   - set:
       field: event.kind
       value: pipeline_error
@@ -136,4 +146,4 @@ on_failure:
   - append:
       field: event.kind
       value: pipeline_error
-      allow_duplicates: false
+      allow_duplicates: false
\ No newline at end of file
```

2024-04-17 08:17 UTC, shmsr commented
I think there's scope to make this CEL program better. I might have a few suggestions.

2024-04-18 05:35 UTC, shmsr commented
@milan-elastic Need some clarity on this.

While trying to improve the CEL code, I was reading MongoDB's doc as well. Here's what I saw:

- API that we are using is deprecated. Did we see this? Support is until June of 2025. We should invest some time if there's a new API and if the new API is better. See [this](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/changelog/#:~:text=GET%20/api/atlas/v2/groups/%7BgroupId%7D/clusters/%7BhostName%7D/logs/%7BlogName%7D.gz).
- Also, for `logName` parameter in the API, there are four options. Why did you specifically go for mongodb and not mongodb-audit-log? See [this](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/Monitoring-and-Logs/operation/getHostLogs:~:text=want%20to%20download.-,logName,-required).
- Also, have we mentioned that auditing logs are not there in M0, M2, M5, or the Serverless instances?
- Read [this](https://www.mongodb.com/docs/atlas/database-auditing/?_ga=2.42989794.617436776.1713388189-1062568307.1704220348#:~:text=Due%20to%20these%20noted%20limitations%2C%20you%20must%20use%20a%20combination%20of%20audit%20logs%2C%20the%20mongodb.log%2C%20and%20the%20Project%20Activity%20Feed%20to%20perform%20a%20full%20audit.) full. [This](https://www.mongodb.com/docs/atlas/database-auditing/?_ga=2.42989794.617436776.1713388189-1062568307.1704220348#:~:text=When%20an%20Atlas%20user%20performs%20an%20action%20in%20the%20Atlas%20UI%20on%20a%20cluster%2C%20both%20the%20audit%20logs%20and%20mongodb.log%20file%20log%20the%20mms%2Dautomation%20database%20user%20as%20the%20user%20performing%20the%20auditable%20action.%20However%2C%20the%20Project%20Activity%20Feed%20logs%20the%20actual%20username%20of%20the%20Atlas%20user%20responsible%20for%20the%20action.) too.
- We can take relevant parts of this [doc](https://www.mongodb.com/docs/atlas/database-auditing/?_ga=2.42989794.617436776.1713388189-1062568307.1704220348) to improve our doc.

2024-04-18 11:34 UTC, milan-elastic commented
> @milan-elastic Need some clarity on this.
> 
> While trying to improve the CEL code, I was reading MongoDB's doc as well. Here's what I saw:
> 
> * API that we are using is deprecated. Did we see this? Support is until June of 2025. We should invest some time if there's a new API and if the new API is better. See [this](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/changelog/#:~:text=GET%20/api/atlas/v2/groups/%7BgroupId%7D/clusters/%7BhostName%7D/logs/%7BlogName%7D.gz).

The API itself is not deprecated; only the resource version we specified in the header during API calls will be deprecated. You can find more information about this version schema and the header [here](https://www.mongodb.com/docs/atlas/api/versioned-api-overview/#std-label-api-versioning-schema). To accommodate these changes in the version header, we have implemented a dynamic header that is based on the current year. The code for these changes is specified below.

```
"Header": {
              "Accept": ["application/vnd.atlas." + string(now.getFullYear()) + "-01-01+json"]
            }

```

> * Also, for `logName` parameter in the API, there are four options. Why did you specifically go for mongodb and not mongodb-audit-log? See [this](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/Monitoring-and-Logs/operation/getHostLogs:~:text=want%20to%20download.-,logName,-required).

Yes, that is correct! Currently, we are collecting two types of logs from MongoDB Atlas: mongod_database logs and mongod_audit logs. To collect mongod_database logs, we use the log name mongodb, and for mongod_audit logs, we use mongodb-audit-log file. So both the logs are getting collected but under different datastreams. More bifurcation is provided [here](https://www.mongodb.com/docs/atlas/mongodb-logs/).

> * Also, have we mentioned that auditing logs are not there in M0, M2, M5, or the Serverless instances?

Sure, I will add that in Readme.

> * Read [this](https://www.mongodb.com/docs/atlas/database-auditing/?_ga=2.42989794.617436776.1713388189-1062568307.1704220348#:~:text=Due%20to%20these%20noted%20limitations%2C%20you%20must%20use%20a%20combination%20of%20audit%20logs%2C%20the%20mongodb.log%2C%20and%20the%20Project%20Activity%20Feed%20to%20perform%20a%20full%20audit.) full. [This](https://www.mongodb.com/docs/atlas/database-auditing/?_ga=2.42989794.617436776.1713388189-1062568307.1704220348#:~:text=When%20an%20Atlas%20user%20performs%20an%20action%20in%20the%20Atlas%20UI%20on%20a%20cluster%2C%20both%20the%20audit%20logs%20and%20mongodb.log%20file%20log%20the%20mms%2Dautomation%20database%20user%20as%20the%20user%20performing%20the%20auditable%20action.%20However%2C%20the%20Project%20Activity%20Feed%20logs%20the%20actual%20username%20of%20the%20Atlas%20user%20responsible%20for%20the%20action.) too.
> * We can take relevant parts of this [doc](https://www.mongodb.com/docs/atlas/database-auditing/?_ga=2.42989794.617436776.1713388189-1062568307.1704220348) to improve our doc.

Yes we have already visited this document and captured the information that found useful.

2024-04-18 11:46 UTC, milan-elastic commented
> Review comment:
> 
> ```diff
> diff --git a/packages/mongodb_atlas/data_stream/mongod_database/elasticsearch/ingest_pipeline/default.yml b/packages/mongodb_atlas/data_stream/mongod_database/elasticsearch/ingest_pipeline/default.yml
> index 5b34df3d8..e6ad6f0f1 100644
> --- a/packages/mongodb_atlas/data_stream/mongod_database/elasticsearch/ingest_pipeline/default.yml
> +++ b/packages/mongodb_atlas/data_stream/mongod_database/elasticsearch/ingest_pipeline/default.yml
> @@ -46,25 +46,27 @@ processors:
>              value: '{{ _ingest.on_failure_message }}'
>    - script:
>        lang: painless
> -      description: Provides descriptive value to the field.
> +      description: Maps log severity levels to descriptive values
>        tag: informative_log_level
>        on_failure:
>          - append:
>              field: error.message
>              value: 'Processor {{{_ingest.on_failure_processor_type}}} with tag {{{_ingest.on_failure_processor_tag}}} in pipeline {{{_ingest.on_failure_pipeline}}} failed with message: {{{_ingest.on_failure_message}}}'
> +      params:
> +        severity_levels:
> +          F: fatal
> +          E: error
> +          W: warning
> +          I: informational
> +          D1: debug 1
> +          D2: debug 2
> +          D3: debug 3
> +          D4: debug 4
> +          D5: debug 5
>        source: |
> -        Map m = new HashMap();
> -        m.put("F", "fatal");
> -        m.put("E", "error");
> -        m.put("W", "warning");
> -        m.put("I", "informational");
> -        m.put("D1", "debug 1");
> -        m.put("D2", "debug 2");
> -        m.put("D3", "debug 3");
> -        m.put("D4", "debug 4");
> -        m.put("D5", "debug 5");
> -        if (m.get(ctx.json?.s) != null) {
> -          ctx.severity = m.get(ctx.json.s);
> +        String severity = ctx.json?.s;
> +        if (severity != null) {
> +          ctx.log.level = params.severity_levels.getOrDefault(severity, null);
>          }
>    - rename:
>        field: severity
> @@ -101,20 +103,27 @@ processors:
>    - script:
>        lang: painless
>        source: |-
> -        boolean drop(Object o) {
> -          if (o == null || o == '') {
> -            return true;
> +        /**
> +         * Recursively drops null and empty values from the Elasticsearch doc context.
> +         *
> +         * @param o The object to process (can be a Map, List, or any other type).
> +         */
> +        void drop(Object o) {
> +          if (o instanceof List) {
> +            ((List) o).removeIf(item -> {
> +              drop(item);
> +              return item == null;
> +            });
>            } else if (o instanceof Map) {
> -            ((Map) o).values().removeIf(v -> drop(v));
> -            return (((Map) o).size() == 0);
> -          } else if (o instanceof List) {
> -            ((List) o).removeIf(v -> drop(v));
> -            return (((List) o).length == 0);
> +            ((Map) o).values().removeIf(item -> {
> +              drop(item);
> +              return item == null;
> +            });
>            }
> -          return false;
>          }
> +
>          drop(ctx);
> -      description: Drops null/empty values recursively.
> +      description: Drops null and empty values recursively from the Elasticsearch document context.
>    - remove:
>        field:
>          - event.original
> @@ -125,6 +134,7 @@ processors:
>        field:
>          - json
>        ignore_missing: true
> +      description: Removes temporary fields.
>    - set:
>        field: event.kind
>        value: pipeline_error
> @@ -136,4 +146,4 @@ on_failure:
>    - append:
>        field: event.kind
>        value: pipeline_error
> -      allow_duplicates: false
> +      allow_duplicates: false
> \ No newline at end of file
> ```
> 
> Improvements:
> 
> 1. Use params. Not Hashmaps. (See: https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting-using.html#prefer-params)
> 2. No return value is required by drop as there's no one using it. Changed it to void. Also, made some minor changes.


```
+        /**
+         * Recursively drops null and empty values from the Elasticsearch doc context.
+         *
+         * @param o The object to process (can be a Map, List, or any other type).
+         */
        void drop(Object o) {
         if (o instanceof List) {
            ((List) o).removeIf(item -> {
              drop(item);
              return item == null;
            });
             ((Map) o).values().removeIf(item -> {
              drop(item);
              return item == null;
            });
           }
         }

```
Above function will not work when we have field with empty value. Like field1 = “”. Then this function will not remove this field from the event. It’s only work if field have null value.

2024-04-18 11:56 UTC, shmsr commented
> > While trying to improve the CEL code, I was reading MongoDB's doc as well. Here's what I saw:
> > 
> > * API that we are using is deprecated. Did we see this? Support is until June of 2025. We should invest some time if there's a new API and if the new API is better. See [this](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/changelog/#:~:text=GET%20/api/atlas/v2/groups/%7BgroupId%7D/clusters/%7BhostName%7D/logs/%7BlogName%7D.gz).
> 
> The API itself is not deprecated; only the resource version we specified in the header during API calls will be deprecated. You can find more information about this version schema and the header [here](https://www.mongodb.com/docs/atlas/api/versioned-api-overview/#std-label-api-versioning-schema). To accommodate these changes in the version header, we have implemented a dynamic header that is based on the current year. The code for these changes is specified below.
> 
> ```
> "Header": {
>               "Accept": ["application/vnd.atlas." + string(now.getFullYear()) + "-01-01+json"]
>             }
> ```
> 
> > * Also, for `logName` parameter in the API, there are four options. Why did you specifically go for mongodb and not mongodb-audit-log? See [this](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/Monitoring-and-Logs/operation/getHostLogs:~:text=want%20to%20download.-,logName,-required).
> 
> Yes, that is correct! Currently, we are collecting two types of logs from MongoDB Atlas: mongod_database logs and mongod_audit logs. To collect mongod_database logs, we use the log name mongodb, and for mongod_audit logs, we use mongodb-audit-log file. So both the logs are getting collected but under different datastreams. More bifurcation is provided [here](https://www.mongodb.com/docs/atlas/mongodb-logs/).
> 
> > * Also, have we mentioned that auditing logs are not there in M0, M2, M5, or the Serverless instances?
> 
> Sure, I will add that in Readme.
> 
> > * Read [this](https://www.mongodb.com/docs/atlas/database-auditing/?_ga=2.42989794.617436776.1713388189-1062568307.1704220348#:~:text=Due%20to%20these%20noted%20limitations%2C%20you%20must%20use%20a%20combination%20of%20audit%20logs%2C%20the%20mongodb.log%2C%20and%20the%20Project%20Activity%20Feed%20to%20perform%20a%20full%20audit.) full. [This](https://www.mongodb.com/docs/atlas/database-auditing/?_ga=2.42989794.617436776.1713388189-1062568307.1704220348#:~:text=When%20an%20Atlas%20user%20performs%20an%20action%20in%20the%20Atlas%20UI%20on%20a%20cluster%2C%20both%20the%20audit%20logs%20and%20mongodb.log%20file%20log%20the%20mms%2Dautomation%20database%20user%20as%20the%20user%20performing%20the%20auditable%20action.%20However%2C%20the%20Project%20Activity%20Feed%20logs%20the%20actual%20username%20of%20the%20Atlas%20user%20responsible%20for%20the%20action.) too.
> > * We can take relevant parts of this [doc](https://www.mongodb.com/docs/atlas/database-auditing/?_ga=2.42989794.617436776.1713388189-1062568307.1704220348) to improve our doc.
> 
> Yes we have already visited this document and captured the information that found useful.

Thanks for clarifying the points ++

2024-04-18 12:00 UTC, shmsr commented
> > Review comment:
> > ```diff
> > diff --git a/packages/mongodb_atlas/data_stream/mongod_database/elasticsearch/ingest_pipeline/default.yml b/packages/mongodb_atlas/data_stream/mongod_database/elasticsearch/ingest_pipeline/default.yml
> > index 5b34df3d8..e6ad6f0f1 100644
> > --- a/packages/mongodb_atlas/data_stream/mongod_database/elasticsearch/ingest_pipeline/default.yml
> > +++ b/packages/mongodb_atlas/data_stream/mongod_database/elasticsearch/ingest_pipeline/default.yml
> > @@ -46,25 +46,27 @@ processors:
> >              value: '{{ _ingest.on_failure_message }}'
> >    - script:
> >        lang: painless
> > -      description: Provides descriptive value to the field.
> > +      description: Maps log severity levels to descriptive values
> >        tag: informative_log_level
> >        on_failure:
> >          - append:
> >              field: error.message
> >              value: 'Processor {{{_ingest.on_failure_processor_type}}} with tag {{{_ingest.on_failure_processor_tag}}} in pipeline {{{_ingest.on_failure_pipeline}}} failed with message: {{{_ingest.on_failure_message}}}'
> > +      params:
> > +        severity_levels:
> > +          F: fatal
> > +          E: error
> > +          W: warning
> > +          I: informational
> > +          D1: debug 1
> > +          D2: debug 2
> > +          D3: debug 3
> > +          D4: debug 4
> > +          D5: debug 5
> >        source: |
> > -        Map m = new HashMap();
> > -        m.put("F", "fatal");
> > -        m.put("E", "error");
> > -        m.put("W", "warning");
> > -        m.put("I", "informational");
> > -        m.put("D1", "debug 1");
> > -        m.put("D2", "debug 2");
> > -        m.put("D3", "debug 3");
> > -        m.put("D4", "debug 4");
> > -        m.put("D5", "debug 5");
> > -        if (m.get(ctx.json?.s) != null) {
> > -          ctx.severity = m.get(ctx.json.s);
> > +        String severity = ctx.json?.s;
> > +        if (severity != null) {
> > +          ctx.log.level = params.severity_levels.getOrDefault(severity, null);
> >          }
> >    - rename:
> >        field: severity
> > @@ -101,20 +103,27 @@ processors:
> >    - script:
> >        lang: painless
> >        source: |-
> > -        boolean drop(Object o) {
> > -          if (o == null || o == '') {
> > -            return true;
> > +        /**
> > +         * Recursively drops null and empty values from the Elasticsearch doc context.
> > +         *
> > +         * @param o The object to process (can be a Map, List, or any other type).
> > +         */
> > +        void drop(Object o) {
> > +          if (o instanceof List) {
> > +            ((List) o).removeIf(item -> {
> > +              drop(item);
> > +              return item == null;
> > +            });
> >            } else if (o instanceof Map) {
> > -            ((Map) o).values().removeIf(v -> drop(v));
> > -            return (((Map) o).size() == 0);
> > -          } else if (o instanceof List) {
> > -            ((List) o).removeIf(v -> drop(v));
> > -            return (((List) o).length == 0);
> > +            ((Map) o).values().removeIf(item -> {
> > +              drop(item);
> > +              return item == null;
> > +            });
> >            }
> > -          return false;
> >          }
> > +
> >          drop(ctx);
> > -      description: Drops null/empty values recursively.
> > +      description: Drops null and empty values recursively from the Elasticsearch document context.
> >    - remove:
> >        field:
> >          - event.original
> > @@ -125,6 +134,7 @@ processors:
> >        field:
> >          - json
> >        ignore_missing: true
> > +      description: Removes temporary fields.
> >    - set:
> >        field: event.kind
> >        value: pipeline_error
> > @@ -136,4 +146,4 @@ on_failure:
> >    - append:
> >        field: event.kind
> >        value: pipeline_error
> > -      allow_duplicates: false
> > +      allow_duplicates: false
> > \ No newline at end of file
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Improvements:
> > 
> > 1. Use params. Not Hashmaps. (See: https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting-using.html#prefer-params)
> > 2. No return value is required by drop as there's no one using it. Changed it to void. Also, made some minor changes.
> 
> ```
> +        /**
> +         * Recursively drops null and empty values from the Elasticsearch doc context.
> +         *
> +         * @param o The object to process (can be a Map, List, or any other type).
> +         */
>         void drop(Object o) {
>          if (o instanceof List) {
>             ((List) o).removeIf(item -> {
>               drop(item);
>               return item == null;
>             });
>              ((Map) o).values().removeIf(item -> {
>               drop(item);
>               return item == null;
>             });
>            }
>          }
> ```
> 
> Above function will not work when we have field with empty value. Like field1 = “”. Then this function will not remove this field from the event. It’s only work if field have null value. While the current script is handling mentioned case as well.

Okay, can we modify that program to add that condition? Also, this should also work:

```
void drop(Map map) {
  for (String key : map.keySet()) {
    if (map[key] instanceof Map) {
      drop(map[key]);
    } else if (map[key] == null || map[key].equals("")) {
      map.remove(key);
    }
  }
}

drop(ctx);
```

2024-04-18 12:31 UTC, milan-elastic commented
> void drop(Map map) {
>   for (String key : map.keySet()) {
>     if (map[key] instanceof Map) {
>       drop(map[key]);
>     } else if (map[key] == null || map[key].equals("")) {
>       map.remove(key);
>     }
>   }
> }
> 
> drop(ctx);

It seems like this script might not handle few cases, I need to test it thoroughly. Current script is working fine without any issue as of now so I'm keeping it as it is for the time being. But once I test it thoroughly, I'll update this script in other datastreams as well in separate PR.

2024-04-18 13:23 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10580)
* Commit: e76039059b466783f4ad2048af73ebc182b71b64

### History
* :green_heart: [Build #10492](https://buildkite.com/elastic/integrations/builds/10492) succeeded 087e938e604f7041be1317242904ede8db8928fa
* :broken_heart: [Build #10489](https://buildkite.com/elastic/integrations/builds/10489) failed 32b34cae6f41bd6a69dafb4e0094c0627ab9a1fa
* :green_heart: [Build #10486](https://buildkite.com/elastic/integrations/builds/10486) succeeded 297634e87a1200ebd1b31a38ad3c98e5e1a2f428
* :green_heart: [Build #10429](https://buildkite.com/elastic/integrations/builds/10429) succeeded 76ee648fa9597c25f1ee9aa5a5b3e5f01b83b191
* :green_heart: [Build #10424](https://buildkite.com/elastic/integrations/builds/10424) succeeded 3e248e59247933e9ef1935cf9464d6235519e382
* :broken_heart: [Build #10380](https://buildkite.com/elastic/integrations/builds/10380) failed 07431d80bb2c5cf7e7bbca4fcbf4c99b5d56855b

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10580","number":10580,"commit":"e76039059b466783f4ad2048af73ebc182b71b64"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10492","number":10492,"commit":"087e938e604f7041be1317242904ede8db8928fa"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10489","number":10489,"commit":"32b34cae6f41bd6a69dafb4e0094c0627ab9a1fa"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10486","number":10486,"commit":"297634e87a1200ebd1b31a38ad3c98e5e1a2f428"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10429","number":10429,"commit":"76ee648fa9597c25f1ee9aa5a5b3e5f01b83b191"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10424","number":10424,"commit":"3e248e59247933e9ef1935cf9464d6235519e382"}],"number":10580}
buildkite-pr-comment-->

2024-04-18 13:25 UTC, harnish-elastic approved these changes
LGTM! 🚀

2024-04-18 13:29 UTC, shmsr approved these changes

2024-04-18 16:37 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10588)
* Commit: d3e36f46169ddc2c6a9f4d9337d96fe66f927eb5

### History
* :green_heart: [Build #10580](https://buildkite.com/elastic/integrations/builds/10580) succeeded e76039059b466783f4ad2048af73ebc182b71b64
* :green_heart: [Build #10492](https://buildkite.com/elastic/integrations/builds/10492) succeeded 087e938e604f7041be1317242904ede8db8928fa
* :broken_heart: [Build #10489](https://buildkite.com/elastic/integrations/builds/10489) failed 32b34cae6f41bd6a69dafb4e0094c0627ab9a1fa
* :green_heart: [Build #10486](https://buildkite.com/elastic/integrations/builds/10486) succeeded 297634e87a1200ebd1b31a38ad3c98e5e1a2f428
* :green_heart: [Build #10429](https://buildkite.com/elastic/integrations/builds/10429) succeeded 76ee648fa9597c25f1ee9aa5a5b3e5f01b83b191
* :green_heart: [Build #10424](https://buildkite.com/elastic/integrations/builds/10424) succeeded 3e248e59247933e9ef1935cf9464d6235519e382

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10588","number":10588,"commit":"d3e36f46169ddc2c6a9f4d9337d96fe66f927eb5"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10580","number":10580,"commit":"e76039059b466783f4ad2048af73ebc182b71b64"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10492","number":10492,"commit":"087e938e604f7041be1317242904ede8db8928fa"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10489","number":10489,"commit":"32b34cae6f41bd6a69dafb4e0094c0627ab9a1fa"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10486","number":10486,"commit":"297634e87a1200ebd1b31a38ad3c98e5e1a2f428"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10429","number":10429,"commit":"76ee648fa9597c25f1ee9aa5a5b3e5f01b83b191"}],"number":10588}
buildkite-pr-comment-->

2024-04-18 16:38 UTC, merged

2024-04-18 16:51 UTC, elasticmachine commented
Package mongodb_atlas - 0.0.3 containing this change is available at https://epr.elastic.co/search?package=mongodb_atlas