Fix typo in elastic agent dashboard
elastic/integrations pull request #962
Opened 2021-04-29 14:00 UTC by smith

## What does this PR do?

Fix typo in elastic agent dashboard

## Checklist

- [X] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/master/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.

2021-04-29 14:09 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-962/detail/PR-962/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-962/detail/PR-962/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-962/detail/PR-962/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-962/detail/PR-962/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://integrations_962.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #962 opened`



* Start Time: 2021-04-29T14:00:26.360+0000


* Duration: 9 min 8 sec


* Commit: 857ad187cc589028eef4961334e694839aac4830




#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/PR-962/buildTimeGraph/png)



</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->









### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-962/detail/PR-962/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Check integration: elastic_agent`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-962/runs/1/steps/393/log/?start=0">here</a></li>
<li>Description: <code>../../build/elastic-package check -v</code></l1>
</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-04-29T14:08:53.018Z] go: downloading github.com/hashicorp/golang-lru v0.5.1
[2021-04-29T14:08:53.283Z] go: downloading github.com/golang/protobuf v1.4.3
[2021-04-29T14:08:53.283Z] go: downloading github.com/json-iterator/go v1.1.10
[2021-04-29T14:08:53.283Z] go: downloading github.com/go-logr/logr v0.4.0
[2021-04-29T14:08:53.283Z] go: downloading go.mongodb.org/mongo-driver v1.0.3
[2021-04-29T14:08:53.283Z] go: downloading github.com/google/gofuzz v1.1.0
[2021-04-29T14:08:53.283Z] go: downloading k8s.io/kube-openapi v0.0.0-20201113171705-d219536bb9fd
[2021-04-29T14:08:53.283Z] go: downloading github.com/mitchellh/mapstructure v1.1.2
[2021-04-29T14:08:53.283Z] go: downloading github.com/kylelemons/godebug v1.1.0
[2021-04-29T14:08:53.283Z] go: downloading github.com/go-git/gcfg v1.5.0
[2021-04-29T14:08:53.283Z] go: downloading github.com/modern-go/reflect2 v1.0.1
[2021-04-29T14:08:53.283Z] go: downloading google.golang.org/protobuf v1.25.0
[2021-04-29T14:08:53.283Z] go: downloading github.com/xeipuuv/gojsonreference v0.0.0-20180127040603-bd5ef7bd5415
[2021-04-29T14:08:53.283Z] go: downloading github.com/go-openapi/errors v0.19.2
[2021-04-29T14:08:53.283Z] go: downloading k8s.io/apiextensions-apiserver v0.20.4
[2021-04-29T14:08:53.283Z] go: downloading github.com/imdario/mergo v0.3.11
[2021-04-29T14:08:53.283Z] go: downloading gopkg.in/yaml.v2 v2.4.0
[2021-04-29T14:08:53.283Z] go: downloading gopkg.in/warnings.v0 v0.1.2
[2021-04-29T14:08:53.548Z] go: downloading github.com/evanphx/json-patch v4.9.0+incompatible
[2021-04-29T14:08:53.548Z] go: downloading github.com/liggitt/tabwriter v0.0.0-20181228230101-89fcab3d43de
[2021-04-29T14:08:53.548Z] go: downloading gopkg.in/inf.v0 v0.9.1
[2021-04-29T14:08:53.548Z] go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
[2021-04-29T14:08:53.548Z] go: downloading github.com/go-openapi/spec v0.19.3
[2021-04-29T14:08:53.548Z] go: downloading github.com/ghodss/yaml v1.0.0
[2021-04-29T14:08:53.548Z] go: downloading golang.org/x/time v0.0.0-20200630173020-3af7569d3a1e
[2021-04-29T14:08:53.548Z] go: downloading github.com/xeipuuv/gojsonpointer v0.0.0-20190905194746-02993c407bfb
[2021-04-29T14:08:53.548Z] go: downloading gopkg.in/yaml.v3 v3.0.0-20200615113413-eeeca48fe776
[2021-04-29T14:08:53.548Z] go: downloading github.com/go-openapi/swag v0.19.5
[2021-04-29T14:08:53.813Z] go: downloading k8s.io/kubectl v0.20.4
[2021-04-29T14:08:53.813Z] go: downloading github.com/go-openapi/jsonpointer v0.19.3
[2021-04-29T14:08:53.813Z] go: downloading github.com/mailru/easyjson v0.7.0
[2021-04-29T14:08:53.813Z] go: downloading github.com/xanzy/ssh-agent v0.2.1
[2021-04-29T14:08:53.813Z] go: downloading github.com/go-openapi/jsonreference v0.19.3
[2021-04-29T14:08:53.813Z] go: downloading sigs.k8s.io/structured-merge-diff/v4 v4.0.2
[2021-04-29T14:08:53.813Z] go: downloading github.com/kevinburke/ssh_config v0.0.0-20190725054713-01f96b0aa0cd
[2021-04-29T14:08:53.813Z] go: downloading github.com/google/go-cmp v0.5.2
[2021-04-29T14:08:53.813Z] go: downloading github.com/emicklei/go-restful v2.9.5+incompatible
[2021-04-29T14:08:53.813Z] go: downloading github.com/PuerkitoBio/purell v1.1.1
[2021-04-29T14:08:53.813Z] go: downloading github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578
[2021-04-29T14:08:53.813Z] go: downloading github.com/go-stack/stack v1.8.0
[2021-04-29T14:08:54.390Z] go: downloading github.com/exponent-io/jsonpath v0.0.0-20151013193312-d6023ce2651d
[2021-04-29T14:08:54.390Z] go: downloading k8s.io/component-base v0.20.4
[2021-04-29T14:08:54.390Z] go: downloading github.com/MakeNowJust/heredoc v0.0.0-20170808103936-bb23615498cd
[2021-04-29T14:08:54.390Z] go: downloading github.com/russross/blackfriday v1.5.2
[2021-04-29T14:08:54.390Z] go: downloading github.com/mitchellh/go-wordwrap v1.0.0
[2021-04-29T14:08:54.390Z] go: downloading github.com/moby/term v0.0.0-20200312100748-672ec06f55cd
[2021-04-29T14:08:54.391Z] go: downloading github.com/docker/spdystream v0.0.0-20160310174837-449fdfce4d96
[2021-04-29T14:09:26.661Z] Running in /var/lib/jenkins/workspace/gest-manager_integrations_PR-962/src/github.com/elastic/integrations/packages/elastic_agent
[2021-04-29T14:09:26.993Z] + ../../build/elastic-package check -v
[2021-04-29T14:09:26.994Z] elastic-package has been installed.
[2021-04-29T14:09:26.994Z] 2021/04/29 14:09:26 DEBUG Enable verbose logging
[2021-04-29T14:09:26.994Z] Format the package
[2021-04-29T14:09:26.994Z] Error: checking package failed: formatting the integration failed (path: /var/lib/jenkins/workspace/gest-manager_integrations_PR-962/src/github.com/elastic/integrations/packages/elastic_agent, failFast: true): walking through the integration files failed: formatting file failed (path: /var/lib/jenkins/workspace/gest-manager_integrations_PR-962/src/github.com/elastic/integrations/packages/elastic_agent/kibana/dashboard/elastic_agent-f47f18cc-9c7d-4278-b2ea-a6dee816d395.json): file is not formatted (path: /var/lib/jenkins/workspace/gest-manager_integrations_PR-962/src/github.com/elastic/integrations/packages/elastic_agent/kibana/dashboard/elastic_agent-f47f18cc-9c7d-4278-b2ea-a6dee816d395.json)
[2021-04-29T14:09:27.071Z] Running in /var/lib/jenkins/workspace/gest-manager_integrations_PR-962/src/github.com/elastic/integrations
[2021-04-29T14:09:27.110Z] Archiving artifacts
[2021-04-29T14:09:27.452Z] ‘build/test-results/*.xml’ doesn’t match anything: ‘build’ exists but not ‘build/test-results/*.xml’
[2021-04-29T14:09:27.452Z] No artifacts found that match the file pattern "build/test-results/*.xml". Configuration error?
[2021-04-29T14:09:27.476Z] Recording test results
[2021-04-29T14:09:27.812Z] None of the test reports [...]

2021-04-29 22:39 UTC, kaiyan-sheng approved these changes

2021-04-29 23:03 UTC, ycombinator commented on packages/elastic_agent/kibana/dashboard/elastic_agent-f47f18cc-9c7d-4278-b2ea-a6dee816d395.json
> +}
I suspect this newline change is why the CI build is failing. CI is pretty strict about formatting.

From anywhere under the `packages/elastic_agent` folder, run `elastic-package format`. That should fix up any formatting.

2021-04-30 01:19 UTC, smith commented on packages/elastic_agent/kibana/dashboard/elastic_agent-f47f18cc-9c7d-4278-b2ea-a6dee816d395.json
> +}
I made this change through the GitHub UI. I don't have this project checked out yet.

2021-04-30 03:14 UTC, ycombinator commented on packages/elastic_agent/kibana/dashboard/elastic_agent-f47f18cc-9c7d-4278-b2ea-a6dee816d395.json
> +}
Ah, I see. Let me push up a commit that fixes the formatting.

2021-04-30 12:35 UTC, mtojek requested changes
Could you please bump up the version and update changelog?

2021-04-30 19:51 UTC, smith commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fix typo in elastic agent dashboard #962](https://trello.com/c/PyljzHVn/3-fix-typo-in-elastic-agent-dashboard-962)

2021-05-04 13:59 UTC, mtojek commented
/test

2021-05-04 14:17 UTC, ycombinator approved these changes
LGTM.

2021-05-04 15:41 UTC, mtojek approved these changes

2021-05-04 15:41 UTC, merged