integrations/packages/salesforce: Revamp Salesforce integration
elastic/integrations pull request #9629
Opened 2024-04-17 06:32 UTC by kush-elastic

- Enhancement
- Breaking change

## Description

Enhancing the salesforce integration by introducing a new input method specifically for salesforce. Due to Httpjson's inability to handle the large data from salesforce eventLogFiles, a new input method is being introduced to directly collect data from salesforce using SOQL Queries and manual handling of big data.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Closes https://github.com/elastic/obs-infraobs-team/issues/1278
- Relates https://github.com/elastic/obs-infraobs-team/issues/1248

## Screenshots

### Configurations

**Before**
![screencapture-localhost-5601-app-fleet-integrations-salesforce-0-12-1-add-integration-2024-01-31-14_45_58](https://github.com/elastic/integrations/assets/89848966/2ab3eec3-b56b-4c6b-881a-c3d2c6120ef1)

**After**
![screencapture-localhost-5601-app-fleet-integrations-salesforce-0-13-0-add-integration-2024-01-31-14_40_23](https://github.com/elastic/integrations/assets/89848966/27bccdda-22c2-42b7-ae89-56b6a8b20a2c)

2024-04-17 06:48 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10512)
* Commit: 48dac433acf3445a4c87cf317c266a804cf49119

### Failed CI Steps
* [Check integrations salesforce](https://buildkite.com/elastic/integrations/builds/10512#018eeac9-fe8d-4b68-a198-17d670ab27d4)

### History
* :broken_heart: [Build #10511](https://buildkite.com/elastic/integrations/builds/10511) failed cae52c99e56c93e64b6515fe852aff0f841e2839

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10512","number":10512,"commit":"48dac433acf3445a4c87cf317c266a804cf49119"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10511","number":10511,"commit":"cae52c99e56c93e64b6515fe852aff0f841e2839"}],"number":10512}
buildkite-pr-comment-->

2024-04-30 07:21 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10949)
* Commit: dab8c371dfd15c107f1b8955bb2016eab0bc572a

### Failed CI Steps
* [Check integrations salesforce](https://buildkite.com/elastic/integrations/builds/10949#018f2dda-165f-4d4b-823a-a7b315b88a39)

### History
* :broken_heart: [Build #10512](https://buildkite.com/elastic/integrations/builds/10512) failed 48dac433acf3445a4c87cf317c266a804cf49119
* :broken_heart: [Build #10511](https://buildkite.com/elastic/integrations/builds/10511) failed cae52c99e56c93e64b6515fe852aff0f841e2839

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10949","number":10949,"commit":"dab8c371dfd15c107f1b8955bb2016eab0bc572a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10512","number":10512,"commit":"48dac433acf3445a4c87cf317c266a804cf49119"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10511","number":10511,"commit":"cae52c99e56c93e64b6515fe852aff0f841e2839"}],"number":10949}
buildkite-pr-comment-->

2024-05-06 13:29 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/11150)
* Commit: 2a5ed629fdc4f4116779752feabe047eb849781b

### Failed CI Steps
* [Check integrations salesforce](https://buildkite.com/elastic/integrations/builds/11150#018f4e14-176b-47ed-9d2a-b07ccaa4442e)

### History
* :broken_heart: [Build #11149](https://buildkite.com/elastic/integrations/builds/11149) failed 2707ae66c151f30b631980826adfa603bafcc881
* :broken_heart: [Build #10949](https://buildkite.com/elastic/integrations/builds/10949) failed dab8c371dfd15c107f1b8955bb2016eab0bc572a
* :broken_heart: [Build #10512](https://buildkite.com/elastic/integrations/builds/10512) failed 48dac433acf3445a4c87cf317c266a804cf49119
* :broken_heart: [Build #10511](https://buildkite.com/elastic/integrations/builds/10511) failed cae52c99e56c93e64b6515fe852aff0f841e2839

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11150","number":11150,"commit":"2a5ed629fdc4f4116779752feabe047eb849781b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11149","number":11149,"commit":"2707ae66c151f30b631980826adfa603bafcc881"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10949","number":10949,"commit":"dab8c371dfd15c107f1b8955bb2016eab0bc572a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10512","number":10512,"commit":"48dac433acf3445a4c87cf317c266a804cf49119"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10511","number":10511,"commit":"cae52c99e56c93e64b6515fe852aff0f841e2839"}],"number":11150}
buildkite-pr-comment-->

2024-05-06 14:44 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/11153)
* Commit: f51481c85786da428b99d697566ba6c09b1d29b7

### Failed CI Steps
* [Check integrations salesforce](https://buildkite.com/elastic/integrations/builds/11153#018f4e59-370b-4df5-8cea-4cb41bcd31e9)

### History
* :broken_heart: [Build #11150](https://buildkite.com/elastic/integrations/builds/11150) failed 2a5ed629fdc4f4116779752feabe047eb849781b
* :broken_heart: [Build #11149](https://buildkite.com/elastic/integrations/builds/11149) failed 2707ae66c151f30b631980826adfa603bafcc881
* :broken_heart: [Build #10949](https://buildkite.com/elastic/integrations/builds/10949) failed dab8c371dfd15c107f1b8955bb2016eab0bc572a
* :broken_heart: [Build #10512](https://buildkite.com/elastic/integrations/builds/10512) failed 48dac433acf3445a4c87cf317c266a804cf49119
* :broken_heart: [Build #10511](https://buildkite.com/elastic/integrations/builds/10511) failed cae52c99e56c93e64b6515fe852aff0f841e2839

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11153","number":11153,"commit":"f51481c85786da428b99d697566ba6c09b1d29b7"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11150","number":11150,"commit":"2a5ed629fdc4f4116779752feabe047eb849781b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11149","number":11149,"commit":"2707ae66c151f30b631980826adfa603bafcc881"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10949","number":10949,"commit":"dab8c371dfd15c107f1b8955bb2016eab0bc572a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10512","number":10512,"commit":"48dac433acf3445a4c87cf317c266a804cf49119"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10511","number":10511,"commit":"cae52c99e56c93e64b6515fe852aff0f841e2839"}],"number":11153}
buildkite-pr-comment-->

2024-05-07 06:41 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/11207)
* Commit: e0ae7321390349a0fec5728099f1cba242c3e6cc

### Failed CI Steps
* [Check integrations salesforce](https://buildkite.com/elastic/integrations/builds/11207#018f51c3-c354-4721-bafd-a61549838088)

### History
* :broken_heart: [Build #11153](https://buildkite.com/elastic/integrations/builds/11153) failed f51481c85786da428b99d697566ba6c09b1d29b7
* :broken_heart: [Build #11150](https://buildkite.com/elastic/integrations/builds/11150) failed 2a5ed629fdc4f4116779752feabe047eb849781b
* :broken_heart: [Build #11149](https://buildkite.com/elastic/integrations/builds/11149) failed 2707ae66c151f30b631980826adfa603bafcc881
* :broken_heart: [Build #10949](https://buildkite.com/elastic/integrations/builds/10949) failed dab8c371dfd15c107f1b8955bb2016eab0bc572a
* :broken_heart: [Build #10512](https://buildkite.com/elastic/integrations/builds/10512) failed 48dac433acf3445a4c87cf317c266a804cf49119

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11207","number":11207,"commit":"e0ae7321390349a0fec5728099f1cba242c3e6cc"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11153","number":11153,"commit":"f51481c85786da428b99d697566ba6c09b1d29b7"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11150","number":11150,"commit":"2a5ed629fdc4f4116779752feabe047eb849781b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11149","number":11149,"commit":"2707ae66c151f30b631980826adfa603bafcc881"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10949","number":10949,"commit":"dab8c371dfd15c107f1b8955bb2016eab0bc572a"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10512","number":10512,"commit":"48dac433acf3445a4c87cf317c266a804cf49119"}],"number":11207}
buildkite-pr-comment-->

2024-05-07 13:17 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/11216)
* Commit: 338bcc69909e4fee625c0f40c9733a58d88cabef

### Failed CI Steps
* [Check integrations salesforce](https://buildkite.com/elastic/integrations/builds/11216#018f532f-6342-4637-bfba-b8f437770b5f)

### History
* :broken_heart: [Build #11207](https://buildkite.com/elastic/integrations/builds/11207) failed e0ae7321390349a0fec5728099f1cba242c3e6cc
* :broken_heart: [Build #11153](https://buildkite.com/elastic/integrations/builds/11153) failed f51481c85786da428b99d697566ba6c09b1d29b7
* :broken_heart: [Build #11150](https://buildkite.com/elastic/integrations/builds/11150) failed 2a5ed629fdc4f4116779752feabe047eb849781b
* :broken_heart: [Build #11149](https://buildkite.com/elastic/integrations/builds/11149) failed 2707ae66c151f30b631980826adfa603bafcc881
* :broken_heart: [Build #10949](https://buildkite.com/elastic/integrations/builds/10949) failed dab8c371dfd15c107f1b8955bb2016eab0bc572a
* :broken_heart: [Build #10512](https://buildkite.com/elastic/integrations/builds/10512) failed 48dac433acf3445a4c87cf317c266a804cf49119

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11216","number":11216,"commit":"338bcc69909e4fee625c0f40c9733a58d88cabef"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11207","number":11207,"commit":"e0ae7321390349a0fec5728099f1cba242c3e6cc"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11153","number":11153,"commit":"f51481c85786da428b99d697566ba6c09b1d29b7"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11150","number":11150,"commit":"2a5ed629fdc4f4116779752feabe047eb849781b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11149","number":11149,"commit":"2707ae66c151f30b631980826adfa603bafcc881"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10949","number":10949,"commit":"dab8c371dfd15c107f1b8955bb2016eab0bc572a"}],"number":11216}
buildkite-pr-comment-->

2024-05-15 09:55 UTC, kush-elastic commented
Updates:
- Enhanced Authentication Configuration Flexibility
  Discussions are underway to offer users a more flexible approach to configuring the authentication mechanism. Several issues have been identified in relation to supporting new configuration methods. After assessing the current situation and challenges, the decision has been made to continue with the existing method for now. Future plans include transitioning to support the new configuration method.

- System Test Status
  Currently, system tests are encountering failures due to the absence of the new Salesforce input in the latest elastic-agent images. The resolution is pending the availability of this input in the updated images.

2024-06-11 09:36 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12429)
* Commit: 15763c4da91c6d5e5667aae0604675f503c6072f

### Failed CI Steps
* [Check integrations salesforce](https://buildkite.com/elastic/integrations/builds/12429#019006a3-c2c2-4fcd-99aa-3ba79316c178)

### History
* :broken_heart: [Build #11216](https://buildkite.com/elastic/integrations/builds/11216) failed 338bcc69909e4fee625c0f40c9733a58d88cabef
* :broken_heart: [Build #11207](https://buildkite.com/elastic/integrations/builds/11207) failed e0ae7321390349a0fec5728099f1cba242c3e6cc
* :broken_heart: [Build #11153](https://buildkite.com/elastic/integrations/builds/11153) failed f51481c85786da428b99d697566ba6c09b1d29b7
* :broken_heart: [Build #11150](https://buildkite.com/elastic/integrations/builds/11150) failed 2a5ed629fdc4f4116779752feabe047eb849781b
* :broken_heart: [Build #11149](https://buildkite.com/elastic/integrations/builds/11149) failed 2707ae66c151f30b631980826adfa603bafcc881

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12429","number":12429,"commit":"15763c4da91c6d5e5667aae0604675f503c6072f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11216","number":11216,"commit":"338bcc69909e4fee625c0f40c9733a58d88cabef"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11207","number":11207,"commit":"e0ae7321390349a0fec5728099f1cba242c3e6cc"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11153","number":11153,"commit":"f51481c85786da428b99d697566ba6c09b1d29b7"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11150","number":11150,"commit":"2a5ed629fdc4f4116779752feabe047eb849781b"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11149","number":11149,"commit":"2707ae66c151f30b631980826adfa603bafcc881"}],"number":12429}
buildkite-pr-comment-->

2024-06-11 09:53 UTC, shmsr commented on packages/salesforce/data_stream/apex/manifest.yml
> +        show_user: true
reverted this in my next commit

2024-06-11 10:00 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12431)
* Commit: 698c670616b222ba5ad7d296dff4a819a287f956

### Failed CI Steps
* [Check integrations salesforce](https://buildkite.com/elastic/integrations/builds/12431#019006b9-cf02-4207-8d70-a083d3bc088c)

### History
* :broken_heart: [Build #12429](https://buildkite.com/elastic/integrations/builds/12429) failed 15763c4da91c6d5e5667aae0604675f503c6072f
* :broken_heart: [Build #11216](https://buildkite.com/elastic/integrations/builds/11216) failed 338bcc69909e4fee625c0f40c9733a58d88cabef
* :broken_heart: [Build #11207](https://buildkite.com/elastic/integrations/builds/11207) failed e0ae7321390349a0fec5728099f1cba242c3e6cc
* :broken_heart: [Build #11153](https://buildkite.com/elastic/integrations/builds/11153) failed f51481c85786da428b99d697566ba6c09b1d29b7
* :broken_heart: [Build #11150](https://buildkite.com/elastic/integrations/builds/11150) failed 2a5ed629fdc4f4116779752feabe047eb849781b

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12431","number":12431,"commit":"698c670616b222ba5ad7d296dff4a819a287f956"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12429","number":12429,"commit":"15763c4da91c6d5e5667aae0604675f503c6072f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11216","number":11216,"commit":"338bcc69909e4fee625c0f40c9733a58d88cabef"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11207","number":11207,"commit":"e0ae7321390349a0fec5728099f1cba242c3e6cc"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11153","number":11153,"commit":"f51481c85786da428b99d697566ba6c09b1d29b7"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11150","number":11150,"commit":"2a5ed629fdc4f4116779752feabe047eb849781b"}],"number":12431}
buildkite-pr-comment-->

2024-06-11 12:49 UTC, shmsr commented
@kush-elastic @aliabbas-elastic I have made a lot of changes to login data stream. Do have a look: https://github.com/elastic/integrations/pull/9629/commits/8c805a860e7de55df6187b761971378eb517f2eb

2024-06-11 13:17 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12441)
* Commit: 29038462c1d63f96a86ef033ba2ed75d8cca363d

### Failed CI Steps
* [Check integrations salesforce](https://buildkite.com/elastic/integrations/builds/12441#01900760-9d1d-4454-9f2b-b661559b259e)

### History
* :broken_heart: [Build #12431](https://buildkite.com/elastic/integrations/builds/12431) failed 698c670616b222ba5ad7d296dff4a819a287f956
* :broken_heart: [Build #12429](https://buildkite.com/elastic/integrations/builds/12429) failed 15763c4da91c6d5e5667aae0604675f503c6072f
* :broken_heart: [Build #11216](https://buildkite.com/elastic/integrations/builds/11216) failed 338bcc69909e4fee625c0f40c9733a58d88cabef
* :broken_heart: [Build #11207](https://buildkite.com/elastic/integrations/builds/11207) failed e0ae7321390349a0fec5728099f1cba242c3e6cc
* :broken_heart: [Build #11153](https://buildkite.com/elastic/integrations/builds/11153) failed f51481c85786da428b99d697566ba6c09b1d29b7

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12441","number":12441,"commit":"29038462c1d63f96a86ef033ba2ed75d8cca363d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12431","number":12431,"commit":"698c670616b222ba5ad7d296dff4a819a287f956"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12429","number":12429,"commit":"15763c4da91c6d5e5667aae0604675f503c6072f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11216","number":11216,"commit":"338bcc69909e4fee625c0f40c9733a58d88cabef"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11207","number":11207,"commit":"e0ae7321390349a0fec5728099f1cba242c3e6cc"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11153","number":11153,"commit":"f51481c85786da428b99d697566ba6c09b1d29b7"}],"number":12441}
buildkite-pr-comment-->

2024-06-12 05:44 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12485)
* Commit: 426335ecc1615909071ecb37be640e5504ca806d

### Failed CI Steps
* [Check integrations salesforce](https://buildkite.com/elastic/integrations/builds/12485#01900af6-64fd-47f4-8cfe-2ae540369913)

### History
* :broken_heart: [Build #12441](https://buildkite.com/elastic/integrations/builds/12441) failed 29038462c1d63f96a86ef033ba2ed75d8cca363d
* :broken_heart: [Build #12431](https://buildkite.com/elastic/integrations/builds/12431) failed 698c670616b222ba5ad7d296dff4a819a287f956
* :broken_heart: [Build #12429](https://buildkite.com/elastic/integrations/builds/12429) failed 15763c4da91c6d5e5667aae0604675f503c6072f
* :broken_heart: [Build #11216](https://buildkite.com/elastic/integrations/builds/11216) failed 338bcc69909e4fee625c0f40c9733a58d88cabef
* :broken_heart: [Build #11207](https://buildkite.com/elastic/integrations/builds/11207) failed e0ae7321390349a0fec5728099f1cba242c3e6cc

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12485","number":12485,"commit":"426335ecc1615909071ecb37be640e5504ca806d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12441","number":12441,"commit":"29038462c1d63f96a86ef033ba2ed75d8cca363d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12431","number":12431,"commit":"698c670616b222ba5ad7d296dff4a819a287f956"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12429","number":12429,"commit":"15763c4da91c6d5e5667aae0604675f503c6072f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11216","number":11216,"commit":"338bcc69909e4fee625c0f40c9733a58d88cabef"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11207","number":11207,"commit":"e0ae7321390349a0fec5728099f1cba242c3e6cc"}],"number":12485}
buildkite-pr-comment-->

2024-06-12 05:55 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12486)
* Commit: cffab2d0b581bb360ac0985ea686a9c00e10ceb7

### Failed CI Steps
* [Check integrations salesforce](https://buildkite.com/elastic/integrations/builds/12486#01900b00-8109-4161-827f-de4bfd7a1dfd)

### History
* :broken_heart: [Build #12485](https://buildkite.com/elastic/integrations/builds/12485) failed 426335ecc1615909071ecb37be640e5504ca806d
* :broken_heart: [Build #12441](https://buildkite.com/elastic/integrations/builds/12441) failed 29038462c1d63f96a86ef033ba2ed75d8cca363d
* :broken_heart: [Build #12431](https://buildkite.com/elastic/integrations/builds/12431) failed 698c670616b222ba5ad7d296dff4a819a287f956
* :broken_heart: [Build #12429](https://buildkite.com/elastic/integrations/builds/12429) failed 15763c4da91c6d5e5667aae0604675f503c6072f
* :broken_heart: [Build #11216](https://buildkite.com/elastic/integrations/builds/11216) failed 338bcc69909e4fee625c0f40c9733a58d88cabef

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12486","number":12486,"commit":"cffab2d0b581bb360ac0985ea686a9c00e10ceb7"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12485","number":12485,"commit":"426335ecc1615909071ecb37be640e5504ca806d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12441","number":12441,"commit":"29038462c1d63f96a86ef033ba2ed75d8cca363d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12431","number":12431,"commit":"698c670616b222ba5ad7d296dff4a819a287f956"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12429","number":12429,"commit":"15763c4da91c6d5e5667aae0604675f503c6072f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11216","number":11216,"commit":"338bcc69909e4fee625c0f40c9733a58d88cabef"}],"number":12486}
buildkite-pr-comment-->

2024-06-12 06:35 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12487)
* Commit: 023982f5ccc5f12f573c368335dfbc937762462f

### Failed CI Steps
* [Check integrations salesforce](https://buildkite.com/elastic/integrations/builds/12487#01900b24-0733-40bb-a2fd-86aa759d5ea3)

### History
* :broken_heart: [Build #12486](https://buildkite.com/elastic/integrations/builds/12486) failed cffab2d0b581bb360ac0985ea686a9c00e10ceb7
* :broken_heart: [Build #12485](https://buildkite.com/elastic/integrations/builds/12485) failed 426335ecc1615909071ecb37be640e5504ca806d
* :broken_heart: [Build #12441](https://buildkite.com/elastic/integrations/builds/12441) failed 29038462c1d63f96a86ef033ba2ed75d8cca363d
* :broken_heart: [Build #12431](https://buildkite.com/elastic/integrations/builds/12431) failed 698c670616b222ba5ad7d296dff4a819a287f956
* :broken_heart: [Build #12429](https://buildkite.com/elastic/integrations/builds/12429) failed 15763c4da91c6d5e5667aae0604675f503c6072f

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12487","number":12487,"commit":"023982f5ccc5f12f573c368335dfbc937762462f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12486","number":12486,"commit":"cffab2d0b581bb360ac0985ea686a9c00e10ceb7"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12485","number":12485,"commit":"426335ecc1615909071ecb37be640e5504ca806d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12441","number":12441,"commit":"29038462c1d63f96a86ef033ba2ed75d8cca363d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12431","number":12431,"commit":"698c670616b222ba5ad7d296dff4a819a287f956"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12429","number":12429,"commit":"15763c4da91c6d5e5667aae0604675f503c6072f"}],"number":12487}
buildkite-pr-comment-->

2024-06-18 09:38 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-06-18 09:39 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12609)
* Commit: 0dc1acaea23f5a10b38615fef9e3329c5222b726

### History
* :broken_heart: [Build #12487](https://buildkite.com/elastic/integrations/builds/12487) failed 023982f5ccc5f12f573c368335dfbc937762462f
* :broken_heart: [Build #12486](https://buildkite.com/elastic/integrations/builds/12486) failed cffab2d0b581bb360ac0985ea686a9c00e10ceb7
* :broken_heart: [Build #12485](https://buildkite.com/elastic/integrations/builds/12485) failed 426335ecc1615909071ecb37be640e5504ca806d
* :broken_heart: [Build #12441](https://buildkite.com/elastic/integrations/builds/12441) failed 29038462c1d63f96a86ef033ba2ed75d8cca363d
* :broken_heart: [Build #12431](https://buildkite.com/elastic/integrations/builds/12431) failed 698c670616b222ba5ad7d296dff4a819a287f956

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12609","number":12609,"commit":"0dc1acaea23f5a10b38615fef9e3329c5222b726"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12487","number":12487,"commit":"023982f5ccc5f12f573c368335dfbc937762462f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12486","number":12486,"commit":"cffab2d0b581bb360ac0985ea686a9c00e10ceb7"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12485","number":12485,"commit":"426335ecc1615909071ecb37be640e5504ca806d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12441","number":12441,"commit":"29038462c1d63f96a86ef033ba2ed75d8cca363d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12431","number":12431,"commit":"698c670616b222ba5ad7d296dff4a819a287f956"}],"number":12609}
buildkite-pr-comment-->

2024-06-19 08:50 UTC, milan-elastic commented on packages/salesforce/data_stream/login/_dev/test/pipeline/test-login-eventlogfile.log-expected.json
> +                    "document_id": "_id",
`document_id` field won’t work as `_id` field cannot be longer used in visualization. Hence we should remove it in all the data streams.
**Note** - Also make sure in visualization this filed wont get used.

2024-06-19 09:00 UTC, milan-elastic commented
@shmsr @kush-elastic  I've notcied currently there are some of the ECS fields which are not being seen in pipeline test. But present in the ecs.yml file.
e.g.
- event.id
- event.module
- user.name
	
Please remove these ecs fields or either migrate to ecs@mappings and remove ecs.yml.

2024-06-19 09:02 UTC, ishleenk17 commented
> @shmsr @kush-elastic I've notcied currently there are some of the ECS fields which are not being seen in pipeline test. But present in the ecs.yml file. e.g.
> 
> * event.id
> * event.module
> * user.name
> 
> Please remove these ecs fields or either migrate to ecs@mappings and remove ecs.yml.

For any new Integration please follow the migration to ecs@mapping guidelines. We should not be using ecs.yml

2024-06-20 08:22 UTC, aliabbas-elastic reviewed
These were just some initial issues encountered while testing the field mappings. I think we can make these changes as they are very minor before releasing this PR

2024-06-20 08:22 UTC, aliabbas-elastic commented on packages/salesforce/data_stream/logout/fields/fields.yml
> +        - name: organization_by_id
While testing I found some of the fields which are never received the response. This is one such one. Can we check and drop it if not required

2024-06-20 08:22 UTC, aliabbas-elastic commented on packages/salesforce/data_stream/logout/fields/fields.yml
> +        - name: created_by_id
> While testing I found some of the fields which are never received the response. This is one such one. Can we check and drop it if not required

Another one

2024-06-20 08:22 UTC, aliabbas-elastic commented on packages/salesforce/data_stream/login/_dev/test/pipeline/test-login-object.log-expected.json
> +                    "additional_info": "{}",
I never encountered this field as populated one and always received as `{}`. Should we drop it if in case this is the value?

2024-06-20 09:00 UTC, kush-elastic commented on packages/salesforce/data_stream/login/_dev/test/pipeline/test-login-eventlogfile.log-expected.json
> +                    "document_id": "_id",
Yes, Milan.
I will be removing this.
As document_id was being used in few of the dashbaord to create table with unique entries.
I will be replacing the those panels with saved searches.

2024-06-20 09:02 UTC, kush-elastic commented
> > @shmsr @kush-elastic I've notcied currently there are some of the ECS fields which are not being seen in pipeline test. But present in the ecs.yml file. e.g.
> > 
> > * event.id
> > * event.module
> > * user.name
> > 
> > Please remove these ecs fields or either migrate to ecs@mappings and remove ecs.yml.
> 
> For any new Integration please follow the migration to ecs@mapping guidelines. We should not be using ecs.yml

Thanks for bringing this up, I will move integration to use dynamic mappings instead of ecs.yml

2024-06-20 09:02 UTC, kush-elastic commented on packages/salesforce/data_stream/logout/fields/fields.yml
> +        - name: organization_by_id
Sure

2024-06-20 09:04 UTC, kush-elastic commented on packages/salesforce/data_stream/login/_dev/test/pipeline/test-login-object.log-expected.json
> +                    "additional_info": "{}",
we will be removing this field.

2024-06-20 09:24 UTC, shmsr commented
Currently, taking a look at logout and setupaudittrail. Push commits (if needed) by EOD.

2024-06-20 11:48 UTC, muthu-mps commented on packages/salesforce/_dev/build/docs/README.md
> +### Collecting Data Using Streaming API
- This information is useful but it is good to reference the salesforce [document](https://help.salesforce.com/s/articleView?id=sf.real_time_event_monitoring_enable.htm&type=5) on the permissions setup. If the setup has any specific configuration that needs to be applied for our integrations then that can be added here.
- The same applies to the API permissions and the Event Streaming.

2024-06-20 11:48 UTC, muthu-mps commented on packages/salesforce/changelog.yml
> +- version: "0.14.2"
```suggestion
- version: "0.15.0"
```
As this is a major enhancement.

2024-06-20 11:48 UTC, muthu-mps commented on packages/salesforce/data_stream/apex/elasticsearch/ingest_pipeline/default.yml
> +  - rename:
There are more number of rename processors used to convert the JSON keys. We can use the snake case conversion script which converts the all the keys to snake case. Then we can use the other convert processors for certain fields which needs type conversion. You can find the reference on how to convert the Json keys to snake case [here](https://github.com/elastic/integrations/blob/efff6d2566bdda09f9f85c0bb4f9bac89f238116/packages/azure/data_stream/signinlogs/elasticsearch/ingest_pipeline/default.yml#L15).

2024-06-20 11:48 UTC, muthu-mps commented on packages/salesforce/data_stream/apex/elasticsearch/ingest_pipeline/default.yml
> +      if: (ctx.json?.SUCCESS == "1" && ctx.json?.SUCCESS != null) || (ctx.json?.STATUS == "1" && ctx.json?.STATUS != null)
Can we perform the `null check `before verifying whether the request is success? This applies to the below set processor as well.

2024-06-20 11:48 UTC, muthu-mps commented on packages/salesforce/data_stream/apex/elasticsearch/ingest_pipeline/default.yml
> +      if: ctx.json?.CLIENT_IP != "Salesforce.com IP" && ctx.json?.CLIENT_IP != null
Do the null check as a first validation and then the IP address validation.

2024-06-20 11:48 UTC, muthu-mps commented on packages/salesforce/data_stream/apex/fields/fields.yml
> +      description: The Instance URL of the Salesforce instance.
```suggestion
      description: The Salesforce instance URL.
```

2024-06-20 11:48 UTC, muthu-mps commented on packages/salesforce/data_stream/apex/fields/fields.yml
> +          description: For triggers coming from managed packages, trigger_name includes a namespace prefix separated with a . character. If no namespace prefix is present, the trigger is from an unma
```suggestion
          description: For triggers coming from managed packages, trigger_name includes a namespace prefix separated with a dot character. If no namespace prefix is present, the trigger is from an unmanaged trigger.
```

2024-06-20 11:53 UTC, muthu-mps commented
@kush-elastic - The dashboard files and the images are removed. Is this intentional or you have plans to add in this PR?

2024-06-21 05:39 UTC, shmsr commented
> @kush-elastic - The dashboard files and the images are removed. Is this intentional or you have plans to add in this PR?

It is intentional. We are going to do incremental PR submissions like Lalit suggested. Plan to go with this first and then dashboards. There will be multiple PRs.

Also saw [this](https://github.com/elastic/integrations/blob/927d060c0d1d394c1c05f84520891eee4d780d6c/docs/developer_workflow_design_build_test_integration.md#remember-to-bump-up-the-version) the other day that we can use `-next` tags to push changes without releasing.

2024-06-21 05:48 UTC, muthu-mps commented
> > @kush-elastic - The dashboard files and the images are removed. Is this intentional or you have plans to add in this PR?
> 
> It is intentional. We are going to do incremental PR submissions like Lalit suggested. Plan to go with this first and then dashboards. There will be multiple PRs.
> 
> Also saw [this](https://github.com/elastic/integrations/blob/927d060c0d1d394c1c05f84520891eee4d780d6c/docs/developer_workflow_design_build_test_integration.md#remember-to-bump-up-the-version) the other day that we can use `-next` tags to push changes without releasing.

Thanks @shmsr, While looking into the [issue](https://github.com/elastic/obs-infraobs-team/issues/1278) for tasks it shows update dashboard for datastreams task as completed. Can we link or capture the future tasks?

2024-06-21 05:48 UTC, shmsr commented on packages/salesforce/_dev/build/docs/README.md
> +### Use cases:
I believe it's important to inform users about potential use cases for the dashboard. However, after checking other packages, it seems that none of them include a "Use Cases" section, so I'll remove it. Thanks!

2024-06-21 05:49 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12699)
* Commit: 9bf6f0462e3442c3ac5da12bdf0868311087885f

### Failed CI Steps
* [Check integrations salesforce](https://buildkite.com/elastic/integrations/builds/12699#01903953-c17c-44a8-8d43-fe88d0fd49dd)

### History
* :green_heart: [Build #12609](https://buildkite.com/elastic/integrations/builds/12609) succeeded 0dc1acaea23f5a10b38615fef9e3329c5222b726
* :broken_heart: [Build #12487](https://buildkite.com/elastic/integrations/builds/12487) failed 023982f5ccc5f12f573c368335dfbc937762462f
* :broken_heart: [Build #12486](https://buildkite.com/elastic/integrations/builds/12486) failed cffab2d0b581bb360ac0985ea686a9c00e10ceb7
* :broken_heart: [Build #12485](https://buildkite.com/elastic/integrations/builds/12485) failed 426335ecc1615909071ecb37be640e5504ca806d
* :broken_heart: [Build #12441](https://buildkite.com/elastic/integrations/builds/12441) failed 29038462c1d63f96a86ef033ba2ed75d8cca363d
* :broken_heart: [Build #12431](https://buildkite.com/elastic/integrations/builds/12431) failed 698c670616b222ba5ad7d296dff4a819a287f956

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12699","number":12699,"commit":"9bf6f0462e3442c3ac5da12bdf0868311087885f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12609","number":12609,"commit":"0dc1acaea23f5a10b38615fef9e3329c5222b726"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12487","number":12487,"commit":"023982f5ccc5f12f573c368335dfbc937762462f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12486","number":12486,"commit":"cffab2d0b581bb360ac0985ea686a9c00e10ceb7"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12485","number":12485,"commit":"426335ecc1615909071ecb37be640e5504ca806d"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12441","number":12441,"commit":"29038462c1d63f96a86ef033ba2ed75d8cca363d"}],"number":12699}
buildkite-pr-comment-->

2024-06-21 05:50 UTC, shmsr commented
> > > @kush-elastic - The dashboard files and the images are removed. Is this intentional or you have plans to add in this PR?
> > 
> > 
> > It is intentional. We are going to do incremental PR submissions like Lalit suggested. Plan to go with this first and then dashboards. There will be multiple PRs.
> > Also saw [this](https://github.com/elastic/integrations/blob/927d060c0d1d394c1c05f84520891eee4d780d6c/docs/developer_workflow_design_build_test_integration.md#remember-to-bump-up-the-version) the other day that we can use `-next` tags to push changes without releasing.
> 
> Thanks @shmsr, While looking into the [issue](https://github.com/elastic/obs-infraobs-team/issues/1278) for tasks it shows update dashboard for datastreams task as completed. Can we link or capture the future tasks?

Sure, it definitely needs an update.

2024-06-21 06:00 UTC, shmsr commented on packages/salesforce/_dev/build/docs/README.md
> +In order to find out the version of your Salesforce instance using one of the following methods:
Added new sections.

2024-06-21 06:11 UTC, aliabbas-elastic commented on packages/salesforce/_dev/deploy/docker/docker-compose.yml
> +      - 8010:8010
Is this port mapping to external port required? Ideally, it would make no meaning on which port my service is running on my host machine and the one running inside docker container would make sense

2024-06-21 06:19 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12703)
* Commit: 67936855cb43bd264d88c04ac2a59e8a853dee32

### History
* :broken_heart: [Build #12699](https://buildkite.com/elastic/integrations/builds/12699) failed 9bf6f0462e3442c3ac5da12bdf0868311087885f
* :green_heart: [Build #12609](https://buildkite.com/elastic/integrations/builds/12609) succeeded 0dc1acaea23f5a10b38615fef9e3329c5222b726
* :broken_heart: [Build #12487](https://buildkite.com/elastic/integrations/builds/12487) failed 023982f5ccc5f12f573c368335dfbc937762462f
* :broken_heart: [Build #12486](https://buildkite.com/elastic/integrations/builds/12486) failed cffab2d0b581bb360ac0985ea686a9c00e10ceb7
* :broken_heart: [Build #12485](https://buildkite.com/elastic/integrations/builds/12485) failed 426335ecc1615909071ecb37be640e5504ca806d
* :broken_heart: [Build #12441](https://buildkite.com/elastic/integrations/builds/12441) failed 29038462c1d63f96a86ef033ba2ed75d8cca363d

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12703","number":12703,"commit":"67936855cb43bd264d88c04ac2a59e8a853dee32"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12699","number":12699,"commit":"9bf6f0462e3442c3ac5da12bdf0868311087885f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12609","number":12609,"commit":"0dc1acaea23f5a10b38615fef9e3329c5222b726"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12487","number":12487,"commit":"023982f5ccc5f12f573c368335dfbc937762462f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12486","number":12486,"commit":"cffab2d0b581bb360ac0985ea686a9c00e10ceb7"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12485","number":12485,"commit":"426335ecc1615909071ecb37be640e5504ca806d"}],"number":12703}
buildkite-pr-comment-->

2024-06-21 06:33 UTC, shmsr commented on packages/salesforce/_dev/build/docs/README.md
> +### Collecting Data Using Streaming API
Streaming API is something we do not need. It's from previous Salesforce integration changes.

But, just pointing to the list won't be enough. Salesforce doesn't have good docs; it is scattered. More info is here: https://trailhead.salesforce.com/content/learn/modules/realtime-event-monitoring/set-up-realtime-event-monitoring-quiz

So, a combination of some info and the official link is better. I've pushed the changes; PTAL.

2024-06-21 06:40 UTC, shmsr commented on packages/salesforce/_dev/deploy/docker/docker-compose.yml
> +      - 8010:8010
> Ideally, it would make no meaning on which port my service is running on my host machine and the one running inside the docker container would make sense

I agree with your point. When the [host port is not mentioned](https://docs.docker.com/guides/docker-concepts/running-containers/publishing-ports/#publishing-to-ephemeral-ports); any random ephemeral port is chosen.

Just being explicit here by putting the host_port as well. But the change is not important. I just put it there as mostly host_port:container_port is mentioned. But yes, fine with any (with or without)

2024-06-21 06:50 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12705)
* Commit: 65eb0b0402f2aaa1ac4cb5dc92bca81b3a014289

### History
* :green_heart: [Build #12703](https://buildkite.com/elastic/integrations/builds/12703) succeeded 67936855cb43bd264d88c04ac2a59e8a853dee32
* :broken_heart: [Build #12699](https://buildkite.com/elastic/integrations/builds/12699) failed 9bf6f0462e3442c3ac5da12bdf0868311087885f
* :green_heart: [Build #12609](https://buildkite.com/elastic/integrations/builds/12609) succeeded 0dc1acaea23f5a10b38615fef9e3329c5222b726
* :broken_heart: [Build #12487](https://buildkite.com/elastic/integrations/builds/12487) failed 023982f5ccc5f12f573c368335dfbc937762462f
* :broken_heart: [Build #12486](https://buildkite.com/elastic/integrations/builds/12486) failed cffab2d0b581bb360ac0985ea686a9c00e10ceb7
* :broken_heart: [Build #12485](https://buildkite.com/elastic/integrations/builds/12485) failed 426335ecc1615909071ecb37be640e5504ca806d

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12705","number":12705,"commit":"65eb0b0402f2aaa1ac4cb5dc92bca81b3a014289"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12703","number":12703,"commit":"67936855cb43bd264d88c04ac2a59e8a853dee32"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12699","number":12699,"commit":"9bf6f0462e3442c3ac5da12bdf0868311087885f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12609","number":12609,"commit":"0dc1acaea23f5a10b38615fef9e3329c5222b726"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12487","number":12487,"commit":"023982f5ccc5f12f573c368335dfbc937762462f"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12486","number":12486,"commit":"cffab2d0b581bb360ac0985ea686a9c00e10ceb7"}],"number":12705}
buildkite-pr-comment-->

2024-06-21 08:30 UTC, shmsr commented on packages/salesforce/data_stream/apex/elasticsearch/ingest_pipeline/default.yml
> +      if: ctx.json?.CLIENT_IP != "Salesforce.com IP" && ctx.json?.CLIENT_IP != null
I think this is fine. Either way, we get the same thing.

As we are using `?` operator:

1. If ctx.json is null; whole condition becomes false
2. if ctx.json is true; but CLIENT_IP is null; then first one evaluates to true (as it is != "Salesforce.com IP") but the second condition fails.

2024-06-21 08:30 UTC, shmsr commented on packages/salesforce/data_stream/apex/elasticsearch/ingest_pipeline/default.yml
> +      if: ctx.json?.CLIENT_IP != "Salesforce.com IP" && ctx.json?.CLIENT_IP != null
So, it ensures:

- It excludes the specific "Salesforce.com IP" value
0 It ensures we're only processing non-null CLIENT_IP values

2024-06-21 08:36 UTC, shmsr commented on packages/salesforce/data_stream/apex/elasticsearch/ingest_pipeline/default.yml
> +      if: ctx.json?.CLIENT_IP != "Salesforce.com IP" && ctx.json?.CLIENT_IP != null
Check now.

2024-06-21 08:36 UTC, shmsr commented on packages/salesforce/data_stream/apex/elasticsearch/ingest_pipeline/default.yml
> +      if: (ctx.json?.SUCCESS == "1" && ctx.json?.SUCCESS != null) || (ctx.json?.STATUS == "1" && ctx.json?.STATUS != null)
Check now.

2024-06-21 08:36 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12710)
* Commit: 0feb1c81245e938bed6afa435c9fe2345bd48e80

### Failed CI Steps
* [Check integrations salesforce](https://buildkite.com/elastic/integrations/builds/12710#019039e4-d5e4-4f59-b685-3f35a9c7783a)

### History
* :green_heart: [Build #12705](https://buildkite.com/elastic/integrations/builds/12705) succeeded 65eb0b0402f2aaa1ac4cb5dc92bca81b3a014289
* :green_heart: [Build #12703](https://buildkite.com/elastic/integrations/builds/12703) succeeded 67936855cb43bd264d88c04ac2a59e8a853dee32
* :broken_heart: [Build #12699](https://buildkite.com/elastic/integrations/builds/12699) failed 9bf6f0462e3442c3ac5da12bdf0868311087885f
* :green_heart: [Build #12609](https://buildkite.com/elastic/integrations/builds/12609) succeeded 0dc1acaea23f5a10b38615fef9e3329c5222b726
* :broken_heart: [Build #12487](https://buildkite.com/elastic/integrations/builds/12487) failed 023982f5ccc5f12f573c368335dfbc937762462f
* :broken_heart: [Build #12486](https://buildkite.com/elastic/integrations/builds/12486) failed cffab2d0b581bb360ac0985ea686a9c00e10ceb7

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12710","number":12710,"commit":"0feb1c81245e938bed6afa435c9fe2345bd48e80"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12705","number":12705,"commit":"65eb0b0402f2aaa1ac4cb5dc92bca81b3a014289"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12703","number":12703,"commit":"67936855cb43bd264d88c04ac2a59e8a853dee32"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12699","number":12699,"commit":"9bf6f0462e3442c3ac5da12bdf0868311087885f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12609","number":12609,"commit":"0dc1acaea23f5a10b38615fef9e3329c5222b726"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12487","number":12487,"commit":"023982f5ccc5f12f573c368335dfbc937762462f"}],"number":12710}
buildkite-pr-comment-->

2024-06-21 08:38 UTC, shmsr commented on packages/salesforce/data_stream/apex/elasticsearch/ingest_pipeline/default.yml
> +  - rename:
Not all the keys map directly to their snake_case form. But yes, I've improved the full pipeline in general; combining convert and rename processors in one script. PTAL.

2024-06-21 08:42 UTC, muthu-mps commented on packages/salesforce/data_stream/apex/elasticsearch/ingest_pipeline/default.yml
> +      if: ctx.json?.CLIENT_IP != "Salesforce.com IP" && ctx.json?.CLIENT_IP != null
We need to update the `logout` ingest pipeline as well.

2024-06-21 08:54 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12711)
* Commit: c5034c47386c906e1cdcd3cc3287545abaf2a318

### Failed CI Steps
* [Check integrations salesforce](https://buildkite.com/elastic/integrations/builds/12711#019039f4-89c0-4500-8509-ba78ebc6015e)

### History
* :broken_heart: [Build #12710](https://buildkite.com/elastic/integrations/builds/12710) failed 0feb1c81245e938bed6afa435c9fe2345bd48e80
* :green_heart: [Build #12705](https://buildkite.com/elastic/integrations/builds/12705) succeeded 65eb0b0402f2aaa1ac4cb5dc92bca81b3a014289
* :green_heart: [Build #12703](https://buildkite.com/elastic/integrations/builds/12703) succeeded 67936855cb43bd264d88c04ac2a59e8a853dee32
* :broken_heart: [Build #12699](https://buildkite.com/elastic/integrations/builds/12699) failed 9bf6f0462e3442c3ac5da12bdf0868311087885f
* :green_heart: [Build #12609](https://buildkite.com/elastic/integrations/builds/12609) succeeded 0dc1acaea23f5a10b38615fef9e3329c5222b726
* :broken_heart: [Build #12487](https://buildkite.com/elastic/integrations/builds/12487) failed 023982f5ccc5f12f573c368335dfbc937762462f

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12711","number":12711,"commit":"c5034c47386c906e1cdcd3cc3287545abaf2a318"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12710","number":12710,"commit":"0feb1c81245e938bed6afa435c9fe2345bd48e80"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12705","number":12705,"commit":"65eb0b0402f2aaa1ac4cb5dc92bca81b3a014289"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12703","number":12703,"commit":"67936855cb43bd264d88c04ac2a59e8a853dee32"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12699","number":12699,"commit":"9bf6f0462e3442c3ac5da12bdf0868311087885f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12609","number":12609,"commit":"0dc1acaea23f5a10b38615fef9e3329c5222b726"}],"number":12711}
buildkite-pr-comment-->

2024-06-21 09:08 UTC, ishleenk17 commented
> > > @shmsr @kush-elastic I've notcied currently there are some of the ECS fields which are not being seen in pipeline test. But present in the ecs.yml file. e.g.
> > > 
> > > * event.id
> > > * event.module
> > > * user.name
> > > 
> > > Please remove these ecs fields or either migrate to ecs@mappings and remove ecs.yml.
> > 
> > 
> > For any new Integration please follow the migration to ecs@mapping guidelines. We should not be using ecs.yml
> 
> Thanks for bringing this up, I will move integration to use dynamic mappings instead of ecs.yml

Note: Its not just removal of ecs.yml but any ecs fields under fields folder. Detail steps can be seen in this [Meta].(https://github.com/elastic/observability-dev/issues/3279).

2024-06-21 09:41 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12714)
* Commit: 67be4b14a99c44425dc98d24ed03721a72e2db00

### Failed CI Steps
* [Check integrations salesforce](https://buildkite.com/elastic/integrations/builds/12714#01903a20-b94a-49c4-820d-5af3a30c34ef)

### History
* :broken_heart: [Build #12711](https://buildkite.com/elastic/integrations/builds/12711) failed c5034c47386c906e1cdcd3cc3287545abaf2a318
* :broken_heart: [Build #12710](https://buildkite.com/elastic/integrations/builds/12710) failed 0feb1c81245e938bed6afa435c9fe2345bd48e80
* :green_heart: [Build #12705](https://buildkite.com/elastic/integrations/builds/12705) succeeded 65eb0b0402f2aaa1ac4cb5dc92bca81b3a014289
* :green_heart: [Build #12703](https://buildkite.com/elastic/integrations/builds/12703) succeeded 67936855cb43bd264d88c04ac2a59e8a853dee32
* :broken_heart: [Build #12699](https://buildkite.com/elastic/integrations/builds/12699) failed 9bf6f0462e3442c3ac5da12bdf0868311087885f

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12714","number":12714,"commit":"67be4b14a99c44425dc98d24ed03721a72e2db00"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12711","number":12711,"commit":"c5034c47386c906e1cdcd3cc3287545abaf2a318"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12710","number":12710,"commit":"0feb1c81245e938bed6afa435c9fe2345bd48e80"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12705","number":12705,"commit":"65eb0b0402f2aaa1ac4cb5dc92bca81b3a014289"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12703","number":12703,"commit":"67936855cb43bd264d88c04ac2a59e8a853dee32"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12699","number":12699,"commit":"9bf6f0462e3442c3ac5da12bdf0868311087885f"}],"number":12714}
buildkite-pr-comment-->

2024-06-21 10:19 UTC, shmsr commented on packages/salesforce/data_stream/apex/elasticsearch/ingest_pipeline/default.yml
> +      if: ctx.json?.CLIENT_IP != "Salesforce.com IP" && ctx.json?.CLIENT_IP != null
On it.

2024-06-21 10:53 UTC, aliabbas-elastic commented
@shmsr I was running the apex data stream collection using live environment. There I was facing this error message as shown in below screenshot. Can you check this please?
![image](https://github.com/elastic/integrations/assets/124054599/39758f36-776b-4d73-8c9d-28fcfdd301b6)

2024-06-21 11:36 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12719)
* Commit: 251fe73b1f2529d8d3e927053b583434f0a784bd

### History
* :broken_heart: [Build #12714](https://buildkite.com/elastic/integrations/builds/12714) failed 67be4b14a99c44425dc98d24ed03721a72e2db00
* :broken_heart: [Build #12711](https://buildkite.com/elastic/integrations/builds/12711) failed c5034c47386c906e1cdcd3cc3287545abaf2a318
* :broken_heart: [Build #12710](https://buildkite.com/elastic/integrations/builds/12710) failed 0feb1c81245e938bed6afa435c9fe2345bd48e80
* :green_heart: [Build #12705](https://buildkite.com/elastic/integrations/builds/12705) succeeded 65eb0b0402f2aaa1ac4cb5dc92bca81b3a014289
* :green_heart: [Build #12703](https://buildkite.com/elastic/integrations/builds/12703) succeeded 67936855cb43bd264d88c04ac2a59e8a853dee32

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12719","number":12719,"commit":"251fe73b1f2529d8d3e927053b583434f0a784bd"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12714","number":12714,"commit":"67be4b14a99c44425dc98d24ed03721a72e2db00"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12711","number":12711,"commit":"c5034c47386c906e1cdcd3cc3287545abaf2a318"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12710","number":12710,"commit":"0feb1c81245e938bed6afa435c9fe2345bd48e80"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12705","number":12705,"commit":"65eb0b0402f2aaa1ac4cb5dc92bca81b3a014289"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12703","number":12703,"commit":"67936855cb43bd264d88c04ac2a59e8a853dee32"}],"number":12719}
buildkite-pr-comment-->

2024-06-21 17:19 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12727)
* Commit: 900a6270ed15d8e06d05342701c01c4bcb061ba1

### History
* :green_heart: [Build #12719](https://buildkite.com/elastic/integrations/builds/12719) succeeded 251fe73b1f2529d8d3e927053b583434f0a784bd
* :broken_heart: [Build #12714](https://buildkite.com/elastic/integrations/builds/12714) failed 67be4b14a99c44425dc98d24ed03721a72e2db00
* :broken_heart: [Build #12711](https://buildkite.com/elastic/integrations/builds/12711) failed c5034c47386c906e1cdcd3cc3287545abaf2a318
* :broken_heart: [Build #12710](https://buildkite.com/elastic/integrations/builds/12710) failed 0feb1c81245e938bed6afa435c9fe2345bd48e80
* :green_heart: [Build #12705](https://buildkite.com/elastic/integrations/builds/12705) succeeded 65eb0b0402f2aaa1ac4cb5dc92bca81b3a014289
* :green_heart: [Build #12703](https://buildkite.com/elastic/integrations/builds/12703) succeeded 67936855cb43bd264d88c04ac2a59e8a853dee32

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12727","number":12727,"commit":"900a6270ed15d8e06d05342701c01c4bcb061ba1"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12719","number":12719,"commit":"251fe73b1f2529d8d3e927053b583434f0a784bd"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12714","number":12714,"commit":"67be4b14a99c44425dc98d24ed03721a72e2db00"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12711","number":12711,"commit":"c5034c47386c906e1cdcd3cc3287545abaf2a318"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12710","number":12710,"commit":"0feb1c81245e938bed6afa435c9fe2345bd48e80"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12705","number":12705,"commit":"65eb0b0402f2aaa1ac4cb5dc92bca81b3a014289"}],"number":12727}
buildkite-pr-comment-->

2024-06-21 19:17 UTC, shmsr commented
I checked with:

```
go run github.com/andrewkroh/go-examples/ecs-update@014b35dfe4c9832b51e7c909a39a48257d6a005d \
    -ecs-version=8.11.0 \
    -ecs-git-ref=v8.11.0 \
    -fields-yml-drop-ecs \
    -kibana-version=^8.14.0 \
    -drop-import-mappings \
    -fields-yml-cleanup-attrs \
    -pr=9629 \
    -owner=elastic/obs-infraobs-integrations \
    -v \
    packages/salesforce
2024/06/22 00:45:29 salesforce: No changes.
2024/06/22 00:45:29 Completed. No errors. Details written to /var/folders/jb/qf70hqnx7yd_pxlbn5g7243w0000gn/T/ecs-update-result.json
```

Also, checked for ecs@mapping guidelines; I think we are good now. PTAL.

There was one ecs.yml file that @aliabbas-elastic removed in one of his prior commits. Now I don't see other ecs fields in fields/*

2024-06-24 05:47 UTC, shmsr commented
After the changes done last week, LGTM. Let's discuss whether we want to "just merge" or "merge and release". Currently, CHANGELOG is also committed, but if we want to "just me, "hen we should remove it.

2024-06-24 05:50 UTC, shmsr commented
@kush-elastic Let's swap the JWT and user-password auth we discussed last week as the latter is more popular than the other. What do you think?

2024-06-24 05:54 UTC, kush-elastic commented
> @kush-elastic Let's swap the JWT and user-password auth we discussed last week as the latter is more popular than the other. What do you think?

I have made those changes.
You can check it out.
By default, JWT enabled is `false`.
So User will know that JWT authentication is supported by us and at the same time user-password flow is by default enabled.

2024-06-24 06:03 UTC, shmsr requested changes

2024-06-24 06:03 UTC, shmsr commented on packages/salesforce/manifest.yml
> +    default: client_secret
Do we need a default for this?

2024-06-24 06:03 UTC, shmsr commented on packages/salesforce/manifest.yml
> +    default: client_id
Do we need this default?

2024-06-24 06:21 UTC, kush-elastic commented on packages/salesforce/manifest.yml
> +    default: client_secret
Not exactly, but i think its good practice to put it.
I can change it to something like below:
YOUR_SALESFORCE_CONSUMER_SECRET_HERE

2024-06-24 06:21 UTC, kush-elastic commented on packages/salesforce/manifest.yml
> +    default: client_id
same goes here maybe i can put like:
YOUR_SALESFORCE_CONSUMER_KEY_HERE

2024-06-24 06:44 UTC, shmsr commented on packages/salesforce/manifest.yml
> +    default: client_secret
It is a password type. Anyway, the user can't see it unless the toggle. I was thinking what if we remove the default?

2024-06-24 06:44 UTC, shmsr commented on packages/salesforce/manifest.yml
> +    default: client_id
What if we remove the default? I do remember it exactly; it is okay to remove the default? Or it is always required?

2024-06-24 06:45 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12746)
* Commit: 011100fb568d4c62b0db7d3c2c50137179dd3083

### History
* :green_heart: [Build #12727](https://buildkite.com/elastic/integrations/builds/12727) succeeded 900a6270ed15d8e06d05342701c01c4bcb061ba1
* :green_heart: [Build #12719](https://buildkite.com/elastic/integrations/builds/12719) succeeded 251fe73b1f2529d8d3e927053b583434f0a784bd
* :broken_heart: [Build #12714](https://buildkite.com/elastic/integrations/builds/12714) failed 67be4b14a99c44425dc98d24ed03721a72e2db00
* :broken_heart: [Build #12711](https://buildkite.com/elastic/integrations/builds/12711) failed c5034c47386c906e1cdcd3cc3287545abaf2a318
* :broken_heart: [Build #12710](https://buildkite.com/elastic/integrations/builds/12710) failed 0feb1c81245e938bed6afa435c9fe2345bd48e80
* :green_heart: [Build #12705](https://buildkite.com/elastic/integrations/builds/12705) succeeded 65eb0b0402f2aaa1ac4cb5dc92bca81b3a014289

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12746","number":12746,"commit":"011100fb568d4c62b0db7d3c2c50137179dd3083"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12727","number":12727,"commit":"900a6270ed15d8e06d05342701c01c4bcb061ba1"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12719","number":12719,"commit":"251fe73b1f2529d8d3e927053b583434f0a784bd"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12714","number":12714,"commit":"67be4b14a99c44425dc98d24ed03721a72e2db00"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12711","number":12711,"commit":"c5034c47386c906e1cdcd3cc3287545abaf2a318"},{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12710","number":12710,"commit":"0feb1c81245e938bed6afa435c9fe2345bd48e80"}],"number":12746}
buildkite-pr-comment-->

2024-06-24 06:50 UTC, shmsr requested changes

2024-06-24 06:50 UTC, shmsr commented on packages/salesforce/manifest.yml
> +    description: The token endpoint URL for Salesforce connected app, typically set to https://login.salesforce.com or https://instance-url.salesforce.com, used for OAuth 2.0 authentication flow user
```suggestion
    description: The token endpoint URL for the Salesforce connected app, typically set to https://login.salesforce.com or https://instance-url.salesforce.com, used for OAuth 2.0 authentication flow Username-Password.
```

2024-06-24 06:50 UTC, shmsr commented on packages/salesforce/manifest.yml
> +    description: The password associated with your Salesforce account, used for OAuth 2.0 authentication flow username-password.
```suggestion
    description: The password associated with your Salesforce account, used for OAuth 2.0 authentication flow Username-Password.
```

2024-06-24 06:50 UTC, shmsr commented on packages/salesforce/manifest.yml
> +      Enable JWT-based authentication for secure communication with Salesforce APIs. If disabled, the package will use the username-password authentication flow.
```suggestion
      Enable JWT-based authentication for secure communication with Salesforce APIs. If disabled, the package will use the Username-Password authentication flow.
```

2024-06-24 07:19 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12749)
* Commit: fb7c118012a55f6da0932674d27a77fde59f7e81

### History
* :green_heart: [Build #12746](https://buildkite.com/elastic/integrations/builds/12746) succeeded 011100fb568d4c62b0db7d3c2c50137179dd3083
* :green_heart: [Build #12727](https://buildkite.com/elastic/integrations/builds/12727) succeeded 900a6270ed15d8e06d05342701c01c4bcb061ba1
* :green_heart: [Build #12719](https://buildkite.com/elastic/integrations/builds/12719) succeeded 251fe73b1f2529d8d3e927053b583434f0a784bd
* :broken_heart: [Build #12714](https://buildkite.com/elastic/integrations/builds/12714) failed 67be4b14a99c44425dc98d24ed03721a72e2db00
* :broken_heart: [Build #12711](https://buildkite.com/elastic/integrations/builds/12711) failed c5034c47386c906e1cdcd3cc3287545abaf2a318
* :broken_heart: [Build #12710](https://buildkite.com/elastic/integrations/builds/12710) failed 0feb1c81245e938bed6afa435c9fe2345bd48e80

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12749","number":12749,"commit":"fb7c118012a55f6da0932674d27a77fde59f7e81"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12746","number":12746,"commit":"011100fb568d4c62b0db7d3c2c50137179dd3083"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12727","number":12727,"commit":"900a6270ed15d8e06d05342701c01c4bcb061ba1"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12719","number":12719,"commit":"251fe73b1f2529d8d3e927053b583434f0a784bd"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12714","number":12714,"commit":"67be4b14a99c44425dc98d24ed03721a72e2db00"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12711","number":12711,"commit":"c5034c47386c906e1cdcd3cc3287545abaf2a318"}],"number":12749}
buildkite-pr-comment-->

2024-06-24 07:41 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12754)
* Commit: eacd0a0f6d382b320e4ac2ea1b7fdb6d5920e768

### History
* :green_heart: [Build #12749](https://buildkite.com/elastic/integrations/builds/12749) succeeded fb7c118012a55f6da0932674d27a77fde59f7e81
* :green_heart: [Build #12746](https://buildkite.com/elastic/integrations/builds/12746) succeeded 011100fb568d4c62b0db7d3c2c50137179dd3083
* :green_heart: [Build #12727](https://buildkite.com/elastic/integrations/builds/12727) succeeded 900a6270ed15d8e06d05342701c01c4bcb061ba1
* :green_heart: [Build #12719](https://buildkite.com/elastic/integrations/builds/12719) succeeded 251fe73b1f2529d8d3e927053b583434f0a784bd
* :broken_heart: [Build #12714](https://buildkite.com/elastic/integrations/builds/12714) failed 67be4b14a99c44425dc98d24ed03721a72e2db00
* :broken_heart: [Build #12711](https://buildkite.com/elastic/integrations/builds/12711) failed c5034c47386c906e1cdcd3cc3287545abaf2a318

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12754","number":12754,"commit":"eacd0a0f6d382b320e4ac2ea1b7fdb6d5920e768"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12749","number":12749,"commit":"fb7c118012a55f6da0932674d27a77fde59f7e81"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12746","number":12746,"commit":"011100fb568d4c62b0db7d3c2c50137179dd3083"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12727","number":12727,"commit":"900a6270ed15d8e06d05342701c01c4bcb061ba1"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12719","number":12719,"commit":"251fe73b1f2529d8d3e927053b583434f0a784bd"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12714","number":12714,"commit":"67be4b14a99c44425dc98d24ed03721a72e2db00"}],"number":12754}
buildkite-pr-comment-->

2024-06-24 08:25 UTC, kush-elastic commented on packages/salesforce/manifest.yml
> +    default: client_secret
That's correct.
yeah we should remove this one.

2024-06-24 08:26 UTC, aliabbas-elastic commented on packages/salesforce/data_stream/login/fields/fields.yml
> +          unit: ms
```suggestion
        - name: db_total_time
          type: long
          description: The time in nanoseconds for the database round trip during login, including time spent in the JDBC driver, network, and database CPU time.
          unit: nanos
```

According to [link](https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_eventlogfile_login.htm#:~:text=app%20server%20layer.-,DB_TOTAL_TIME,-Type)

2024-06-24 08:37 UTC, aliabbas-elastic commented
We found this during testing that some of the values (especially for `Apex` data stream) a re received as `-1` in response. For example attaching one field for which this is encountered

![image](https://github.com/elastic/integrations/assets/124054599/bffe87ff-93ca-477a-aa09-69bd4703a4cb)

There was one more field with this value `json.REQUEST_SIZE` mapped to `http.request.bytes`. We don't have any documentation for these `-1` values encountered currently as they are received from the logs only. If it would be given in Salesforce documentation somewhere that gives confidence over dropping/ignoring these field values then we would have ideally done that.

2024-06-24 09:00 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12760)
* Commit: 3ba3461880a29872cefbcbcd4f4a139edc14b22e

### Failed CI Steps
* [Check integrations salesforce](https://buildkite.com/elastic/integrations/builds/12760#01904975-cc38-4403-b9b1-3b6375c4a48f)

### History
* :green_heart: [Build #12754](https://buildkite.com/elastic/integrations/builds/12754) succeeded eacd0a0f6d382b320e4ac2ea1b7fdb6d5920e768
* :green_heart: [Build #12749](https://buildkite.com/elastic/integrations/builds/12749) succeeded fb7c118012a55f6da0932674d27a77fde59f7e81
* :green_heart: [Build #12746](https://buildkite.com/elastic/integrations/builds/12746) succeeded 011100fb568d4c62b0db7d3c2c50137179dd3083
* :green_heart: [Build #12727](https://buildkite.com/elastic/integrations/builds/12727) succeeded 900a6270ed15d8e06d05342701c01c4bcb061ba1
* :green_heart: [Build #12719](https://buildkite.com/elastic/integrations/builds/12719) succeeded 251fe73b1f2529d8d3e927053b583434f0a784bd
* :broken_heart: [Build #12714](https://buildkite.com/elastic/integrations/builds/12714) failed 67be4b14a99c44425dc98d24ed03721a72e2db00

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12760","number":12760,"commit":"3ba3461880a29872cefbcbcd4f4a139edc14b22e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12754","number":12754,"commit":"eacd0a0f6d382b320e4ac2ea1b7fdb6d5920e768"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12749","number":12749,"commit":"fb7c118012a55f6da0932674d27a77fde59f7e81"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12746","number":12746,"commit":"011100fb568d4c62b0db7d3c2c50137179dd3083"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12727","number":12727,"commit":"900a6270ed15d8e06d05342701c01c4bcb061ba1"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12719","number":12719,"commit":"251fe73b1f2529d8d3e927053b583434f0a784bd"}],"number":12760}
buildkite-pr-comment-->

2024-06-24 09:10 UTC, shmsr commented on packages/salesforce/data_stream/login/fields/fields.yml
> +          unit: nanos
nice find.

2024-06-24 13:32 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12781)
* Commit: e770f43c5ca0908c01e501c13f70e960b7c3f6e9

### History
* :broken_heart: [Build #12760](https://buildkite.com/elastic/integrations/builds/12760) failed 3ba3461880a29872cefbcbcd4f4a139edc14b22e
* :green_heart: [Build #12754](https://buildkite.com/elastic/integrations/builds/12754) succeeded eacd0a0f6d382b320e4ac2ea1b7fdb6d5920e768
* :green_heart: [Build #12749](https://buildkite.com/elastic/integrations/builds/12749) succeeded fb7c118012a55f6da0932674d27a77fde59f7e81
* :green_heart: [Build #12746](https://buildkite.com/elastic/integrations/builds/12746) succeeded 011100fb568d4c62b0db7d3c2c50137179dd3083
* :green_heart: [Build #12727](https://buildkite.com/elastic/integrations/builds/12727) succeeded 900a6270ed15d8e06d05342701c01c4bcb061ba1

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12781","number":12781,"commit":"e770f43c5ca0908c01e501c13f70e960b7c3f6e9"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12760","number":12760,"commit":"3ba3461880a29872cefbcbcd4f4a139edc14b22e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12754","number":12754,"commit":"eacd0a0f6d382b320e4ac2ea1b7fdb6d5920e768"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12749","number":12749,"commit":"fb7c118012a55f6da0932674d27a77fde59f7e81"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12746","number":12746,"commit":"011100fb568d4c62b0db7d3c2c50137179dd3083"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12727","number":12727,"commit":"900a6270ed15d8e06d05342701c01c4bcb061ba1"}],"number":12781}
buildkite-pr-comment-->

2024-06-25 06:45 UTC, shmsr approved these changes

2024-06-25 07:25 UTC, muthu-mps commented on packages/salesforce/data_stream/setupaudittrail/manifest.yml
> +        default: 168h
Just so curious to understand that the initial interval is something which we are setting to a default value as `168 hours`?
If we set this value to collect data for the last 1 week. Can we have a mention on the default fetch interval in the README.

2024-06-25 07:33 UTC, muthu-mps commented
@shmsr - As I see this is a breaking change based on the field rename and the dashboard removal. We consider making this change as the integration is still in BETA and I am just looking into the comment in the meta [issue](https://github.com/elastic/obs-infraobs-team/issues/1248#:~:text=are%20making%20a-,BREAKING%20CHANGE,-since%20the%20integration).

@lalit-satapathy - I hope this is fine.

2024-06-25 07:44 UTC, muthu-mps commented on packages/salesforce/data_stream/setupaudittrail/manifest.yml
> +        default: 168h
Just a follow-up, Is this valid statement for [setupAuditTrial](https://github.com/elastic/integrations/blob/e770f43c5ca0908c01e501c13f70e960b7c3f6e9/packages/salesforce/_dev/build/docs/README.md#:~:text=area%20over%20the-,past%20180%20days,-.) ?

2024-06-26 09:07 UTC, kush-elastic commented on packages/salesforce/data_stream/setupaudittrail/manifest.yml
> +        default: 168h
I think initial interval is something we support as part of user configurations so i think it does not need to be reflected in readme and just at the descriptions.
Also, we have added initial interval default value, if user removes it. Integration will collect 180 days of data.
So i think yes it is valid statement.

2024-06-26 09:19 UTC, kush-elastic commented
> To be honest, this seems like the way to go. I personally don't have an example to compare with to weigh the pros and cons here. But for beta (0.x) stuff, it's understandable that there could be breaking changes. I think that's why it seems like a fair decision. Anyway, we're just merging this pull request. Kush isn't going to push the CHANGELOG changes. We will do it after dashboard PR is also merged; it is nearing completion. So, we still have some time. If we find a better alternative, we'll go with that instead.
> 
> @kush-elastic Removing changelog right as we discussed?

Yes @muthu-mps,
I have updated the change log to use next tag and we will release integration once all the PRs are merged.

2024-06-26 09:28 UTC, muthu-mps commented on packages/salesforce/data_stream/setupaudittrail/manifest.yml
> +        default: 168h
@kush-elastic - Thanks for the update.
I agree if the user removes the default values the last 180 days data will get captured. Since we set the `initial_interval` by default to `1 week` and we are saying that this data streams captures the audit data for last 180 days. Do you think its okay to remove the 180 days?

2024-06-26 09:33 UTC, shmsr commented on packages/salesforce/changelog.yml
> +    - description: Revamp Salesforce integration to use new filebeat salesforce input.
```suggestion
    - description: Revamp Salesforce integration to use new filebeat Salesforce input.
```

2024-06-26 09:35 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12904)
* Commit: 74f62f74820bd15838a4471047c1ce25b79e0c97

### History
* :green_heart: [Build #12781](https://buildkite.com/elastic/integrations/builds/12781) succeeded e770f43c5ca0908c01e501c13f70e960b7c3f6e9
* :broken_heart: [Build #12760](https://buildkite.com/elastic/integrations/builds/12760) failed 3ba3461880a29872cefbcbcd4f4a139edc14b22e
* :green_heart: [Build #12754](https://buildkite.com/elastic/integrations/builds/12754) succeeded eacd0a0f6d382b320e4ac2ea1b7fdb6d5920e768
* :green_heart: [Build #12749](https://buildkite.com/elastic/integrations/builds/12749) succeeded fb7c118012a55f6da0932674d27a77fde59f7e81
* :green_heart: [Build #12746](https://buildkite.com/elastic/integrations/builds/12746) succeeded 011100fb568d4c62b0db7d3c2c50137179dd3083
* :green_heart: [Build #12727](https://buildkite.com/elastic/integrations/builds/12727) succeeded 900a6270ed15d8e06d05342701c01c4bcb061ba1

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12904","number":12904,"commit":"74f62f74820bd15838a4471047c1ce25b79e0c97"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12781","number":12781,"commit":"e770f43c5ca0908c01e501c13f70e960b7c3f6e9"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12760","number":12760,"commit":"3ba3461880a29872cefbcbcd4f4a139edc14b22e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12754","number":12754,"commit":"eacd0a0f6d382b320e4ac2ea1b7fdb6d5920e768"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12749","number":12749,"commit":"fb7c118012a55f6da0932674d27a77fde59f7e81"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12746","number":12746,"commit":"011100fb568d4c62b0db7d3c2c50137179dd3083"}],"number":12904}
buildkite-pr-comment-->

2024-06-26 10:08 UTC, kush-elastic commented on packages/salesforce/data_stream/setupaudittrail/manifest.yml
> +        default: 168h
I still think we should keep it because it's necessary info that user might need as API itself is only supporting data of last 180 days. In case user is expecting more older data.
wdyt?

2024-06-26 10:18 UTC, muthu-mps commented on packages/salesforce/data_stream/setupaudittrail/manifest.yml
> +        default: 168h
I suggest to change the description in the README that by default we collect last 1 week data and the salesforce stores data for last 180 days which can be collected by adjusting the interval.

2024-06-26 10:21 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12914)
* Commit: 7f322655c391d4a30796da9c13564f849cac54fe

### History
* :green_heart: [Build #12904](https://buildkite.com/elastic/integrations/builds/12904) succeeded 74f62f74820bd15838a4471047c1ce25b79e0c97
* :green_heart: [Build #12781](https://buildkite.com/elastic/integrations/builds/12781) succeeded e770f43c5ca0908c01e501c13f70e960b7c3f6e9
* :broken_heart: [Build #12760](https://buildkite.com/elastic/integrations/builds/12760) failed 3ba3461880a29872cefbcbcd4f4a139edc14b22e
* :green_heart: [Build #12754](https://buildkite.com/elastic/integrations/builds/12754) succeeded eacd0a0f6d382b320e4ac2ea1b7fdb6d5920e768
* :green_heart: [Build #12749](https://buildkite.com/elastic/integrations/builds/12749) succeeded fb7c118012a55f6da0932674d27a77fde59f7e81
* :green_heart: [Build #12746](https://buildkite.com/elastic/integrations/builds/12746) succeeded 011100fb568d4c62b0db7d3c2c50137179dd3083

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12914","number":12914,"commit":"7f322655c391d4a30796da9c13564f849cac54fe"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12904","number":12904,"commit":"74f62f74820bd15838a4471047c1ce25b79e0c97"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12781","number":12781,"commit":"e770f43c5ca0908c01e501c13f70e960b7c3f6e9"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12760","number":12760,"commit":"3ba3461880a29872cefbcbcd4f4a139edc14b22e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12754","number":12754,"commit":"eacd0a0f6d382b320e4ac2ea1b7fdb6d5920e768"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12749","number":12749,"commit":"fb7c118012a55f6da0932674d27a77fde59f7e81"}],"number":12914}
buildkite-pr-comment-->

2024-06-26 10:39 UTC, kush-elastic commented on packages/salesforce/data_stream/setupaudittrail/manifest.yml
> +        default: 168h
Yes, Got it.

2024-06-26 11:02 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/12916)
* Commit: 2636e8033bf1dfba1ab200bd9bbb455e22138b6e

### History
* :green_heart: [Build #12914](https://buildkite.com/elastic/integrations/builds/12914) succeeded 7f322655c391d4a30796da9c13564f849cac54fe
* :green_heart: [Build #12904](https://buildkite.com/elastic/integrations/builds/12904) succeeded 74f62f74820bd15838a4471047c1ce25b79e0c97
* :green_heart: [Build #12781](https://buildkite.com/elastic/integrations/builds/12781) succeeded e770f43c5ca0908c01e501c13f70e960b7c3f6e9
* :broken_heart: [Build #12760](https://buildkite.com/elastic/integrations/builds/12760) failed 3ba3461880a29872cefbcbcd4f4a139edc14b22e
* :green_heart: [Build #12754](https://buildkite.com/elastic/integrations/builds/12754) succeeded eacd0a0f6d382b320e4ac2ea1b7fdb6d5920e768
* :green_heart: [Build #12749](https://buildkite.com/elastic/integrations/builds/12749) succeeded fb7c118012a55f6da0932674d27a77fde59f7e81

cc @kush-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12916","number":12916,"commit":"2636e8033bf1dfba1ab200bd9bbb455e22138b6e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12914","number":12914,"commit":"7f322655c391d4a30796da9c13564f849cac54fe"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12904","number":12904,"commit":"74f62f74820bd15838a4471047c1ce25b79e0c97"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12781","number":12781,"commit":"e770f43c5ca0908c01e501c13f70e960b7c3f6e9"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12760","number":12760,"commit":"3ba3461880a29872cefbcbcd4f4a139edc14b22e"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/12754","number":12754,"commit":"eacd0a0f6d382b320e4ac2ea1b7fdb6d5920e768"}],"number":12916}
buildkite-pr-comment-->

2024-06-26 11:05 UTC, muthu-mps approved these changes

2024-06-26 12:25 UTC, milan-elastic approved these changes
LGTM

2024-06-26 12:33 UTC, aliabbas-elastic approved these changes
Looks good

2024-06-27 05:41 UTC, merged

2024-07-11 10:47 UTC, elasticmachine commented
Package salesforce - 0.15.0 containing this change is available at https://epr.elastic.co/search?package=salesforce