[Apache] Update grok pattern
elastic/integrations pull request #9632
Opened 2024-04-17 12:55 UTC by niraj-elastic

- Bug

## Changes you made on the PR.
The Apache HTTP Server integration currently does not collect [identity](https://httpd.apache.org/docs/2.4/logs.html#:~:text=the%20originating%20machine.-,%2D%20(%25l),-The%20%22hyphen%22%20in). Currently `-` is hard coded in a grok pattern, so when ever any value will be present in log for identity pipeline will fail. In this PR a new field is introduced to fix the existing grok

## Related issue
- #9144 

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

2024-04-17 13:13 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-04-18 08:25 UTC, kush-elastic approved these changes
LGTM!

2024-04-18 08:56 UTC, muthu-mps commented on packages/apache/data_stream/access/_dev/test/pipeline/test-access-basic.log-expected.json
> +                    "identity": "-",
- In most cases the identity may not exist and this can only be available when the [IdentityCheck](https://httpd.apache.org/docs/2.4/mod/mod_ident.html#identitycheck) flag is set.
- Can we drop the identity fields with - (hyphen) values? 
- Considering that this field will always have hyphen value if the flag is off.

2024-04-19 05:42 UTC, niraj-elastic commented on packages/apache/data_stream/access/_dev/test/pipeline/test-access-basic.log-expected.json
> +                    "identity": "-",
Agree, I thought of doing the same but there are some [fields](https://github.com/elastic/integrations/blob/af36780d5654792f68466c42ddeb95627e464d17/packages/apache/data_stream/access/_dev/test/pipeline/test-access-basic.log-expected.json#L48) which have same kind of behavior and those fields include `-` as value. So to maintain consistency across integration i have not dropped `-`. Still, we can drop `-` if that seems right. let me know your thoughts.

2024-04-19 08:53 UTC, muthu-mps commented on packages/apache/data_stream/access/_dev/test/pipeline/test-access-basic.log-expected.json
> +                    "identity": "-",
@niraj-elastic - The main reason to drop this field is that the identity can be either turned on or off most of the users may not be enabling this. If applicable you can make changes to the other fields to make it consistent.

2024-04-23 06:50 UTC, niraj-elastic commented on packages/apache/data_stream/access/_dev/test/pipeline/test-access-basic.log-expected.json
> +                    "identity": "-",
@muthu-mps I think we can not drop all the `-` values from response since some of them are meaningful. here is one [example](https://httpd.apache.org/docs/2.4/logs.html#:~:text=this%20value%20will%20be%20%22%2D%22.%20To%20log%20%220%22%20for%20no%20content%2C%20use%20%25B%20instead.).

2024-04-26 06:11 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10824)
* Commit: 929449d26fa2a1695586bbc8cfbf557d46695e7b

### History
* :green_heart: [Build #10527](https://buildkite.com/elastic/integrations/builds/10527) succeeded 7afce8949ad813a49cfeef093a66079d3e6ed0be

cc @niraj-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10824","number":10824,"commit":"929449d26fa2a1695586bbc8cfbf557d46695e7b"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10527","number":10527,"commit":"7afce8949ad813a49cfeef093a66079d3e6ed0be"}],"number":10824}
buildkite-pr-comment-->

2024-04-29 05:40 UTC, shmsr requested changes
Protocol is ident not identd?

2024-04-29 05:40 UTC, shmsr commented on packages/apache/docs/README.md
> +| apache.access.identity | The user identity associated with the event, as determined by RFC 1413 identd protocol on the client's machine. | keyword |
```suggestion
| apache.access.identity | The user identity associated with the event, as determined by RFC 1413 ident protocol on the client's machine. | keyword |
```

2024-04-29 05:40 UTC, shmsr commented on packages/apache/data_stream/access/fields/fields.yml
> +        The user identity associated with the event, as determined by RFC 1413 identd protocol on the client's machine.
```suggestion
        The user identity associated with the event, as determined by RFC 1413 ident protocol on the client's machine.
```

2024-04-29 05:44 UTC, niraj-elastic commented on packages/apache/docs/README.md
> +| apache.access.identity | The user identity associated with the event, as determined by RFC 1413 identd protocol on the client's machine. | keyword |
We took this description from oficial [document here](https://httpd.apache.org/docs/2.4/logs.html#:~:text=client%20determined%20by-,identd,-on%20the%20clients).

2024-04-29 05:46 UTC, niraj-elastic commented on packages/apache/data_stream/access/fields/fields.yml
> +        The user identity associated with the event, as determined by RFC 1413 identd protocol on the client's machine.
As mentioned above we took this description from official documentation.

2024-04-29 05:51 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10882)
* Commit: 759f95c9772aa8b30fed043428ca58ef2c4fb126

### History
* :green_heart: [Build #10824](https://buildkite.com/elastic/integrations/builds/10824) succeeded 929449d26fa2a1695586bbc8cfbf557d46695e7b
* :green_heart: [Build #10527](https://buildkite.com/elastic/integrations/builds/10527) succeeded 7afce8949ad813a49cfeef093a66079d3e6ed0be

cc @niraj-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10882","number":10882,"commit":"759f95c9772aa8b30fed043428ca58ef2c4fb126"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10824","number":10824,"commit":"929449d26fa2a1695586bbc8cfbf557d46695e7b"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10527","number":10527,"commit":"7afce8949ad813a49cfeef093a66079d3e6ed0be"}],"number":10882}
buildkite-pr-comment-->

2024-04-29 06:29 UTC, muthu-mps approved these changes
LGTM!

2024-04-29 06:45 UTC, shmsr commented on packages/apache/docs/README.md
> +| apache.access.identity | The user identity associated with the event, as determined by RFC 1413 identd protocol on the client's machine. | keyword |
> In this case, the information that is not available is the RFC 1413 identity of the client determined by identd on the clients machine.

Then the sentence is incorrect here in our README. ident is the protocol. identd is a daemon for providing the ident service.


Remove the protocol from the sentence then.

2024-04-29 06:48 UTC, shmsr commented on packages/apache/docs/README.md
> +| apache.access.identity | The user identity associated with the event, as determined by RFC 1413 identd protocol on the client's machine. | keyword |
So either keep `identd` or make it `ident protocol`. `identd` internally would use `ident protocol` only.

2024-04-29 07:09 UTC, shmsr commented on packages/apache/docs/README.md
> +| apache.access.identity | The RFC 1413 identity of the client determined by identd on the clients machine. | keyword |
```suggestion
| apache.access.identity | The client's identity, as specified in RFC 1413, determined by the identd on the client's machine. | keyword |
```

Better?

2024-04-29 07:13 UTC, shmsr approved these changes

2024-04-29 07:26 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10890)
* Commit: de4fa0d32999b574cfdaa9a33a053089856a490b

### History
* :green_heart: [Build #10882](https://buildkite.com/elastic/integrations/builds/10882) succeeded 759f95c9772aa8b30fed043428ca58ef2c4fb126
* :green_heart: [Build #10824](https://buildkite.com/elastic/integrations/builds/10824) succeeded 929449d26fa2a1695586bbc8cfbf557d46695e7b
* :green_heart: [Build #10527](https://buildkite.com/elastic/integrations/builds/10527) succeeded 7afce8949ad813a49cfeef093a66079d3e6ed0be

cc @niraj-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10890","number":10890,"commit":"de4fa0d32999b574cfdaa9a33a053089856a490b"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10882","number":10882,"commit":"759f95c9772aa8b30fed043428ca58ef2c4fb126"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10824","number":10824,"commit":"929449d26fa2a1695586bbc8cfbf557d46695e7b"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10527","number":10527,"commit":"7afce8949ad813a49cfeef093a66079d3e6ed0be"}],"number":10890}
buildkite-pr-comment-->

2024-04-29 09:15 UTC, merged

2024-04-29 09:29 UTC, elasticmachine commented
Package apache - 1.17.1 containing this change is available at https://epr.elastic.co/search?package=apache