[MongoDB Atlas] Hardware data stream
elastic/integrations pull request #9689
Opened 2024-04-23 17:19 UTC by niraj-elastic

- Enhancement

## What does this PR do?

- Added 1 data stream (Hardware Metrics).
- Added data collection logic for the data streams.
- Added the ingest pipeline for the data streams.
- Mapped fields according to the ECS schema and added Fields metadata in the appropriate yaml files.
- Added dashboards and visualizations.
- Added system test cases for the data stream.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally

- Clone integrations repo.
- Install elastic-package locally.
- Start elastic stack using elastic-package.
- Move to integrations/packages/mongodb_atlas) directory.
- Run the following command to run tests. elastic-package test

## Screenshots
![mongodb-atlas-hardware-dashboard](https://github.com/elastic/integrations/assets/124254029/757af2fd-5db3-43ad-abfc-860d452345de)

2024-04-23 17:36 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-04-23 17:37 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10731)
* Commit: fe50fa700942a9aa2214468246a673c81911be2b

cc @niraj-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10731","number":10731,"commit":"fe50fa700942a9aa2214468246a673c81911be2b"}],"number":10731}
buildkite-pr-comment-->

2024-04-24 11:47 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10760)
* Commit: b80ebf2b1d7c499fc374e2a14925d631b7d68dc8

### History
* :green_heart: [Build #10731](https://buildkite.com/elastic/integrations/builds/10731) succeeded fe50fa700942a9aa2214468246a673c81911be2b

cc @niraj-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10760","number":10760,"commit":"b80ebf2b1d7c499fc374e2a14925d631b7d68dc8"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10731","number":10731,"commit":"fe50fa700942a9aa2214468246a673c81911be2b"}],"number":10760}
buildkite-pr-comment-->

2024-04-24 12:38 UTC, milan-elastic approved these changes

2024-05-03 05:45 UTC, shmsr requested changes

2024-05-03 05:45 UTC, shmsr commented on packages/mongodb_atlas/_dev/build/docs/README.md
> +- `process`: This data stream collects host metrics per process for all the hosts of the specified group. Metrics like measurements for the host, such as CPU usage, number of I/O operations and memor
```suggestion
- `mongod_database`: This data stream collects a running log of events, including entries such as incoming connections, commands run, and issues encountered. Generally, database log messages are useful for diagnosing issues, monitoring your deployment, and tuning performance.
- `process`: This data stream collects host metrics per process for all the hosts in the specified group. Metrics like measurements for the host, such as CPU usage, number of I/O operations, and memory usage are available in this data stream.
```

2024-05-03 05:45 UTC, shmsr commented on packages/mongodb_atlas/_dev/build/docs/README.md
> +This data stream collects hardware and status metrics per process of the specified group. Metrics like measurements for the hardware and status, such as CPU usage and JVM memory usage are available o
```suggestion
This data stream collects hardware and status metrics for each process in the specified group. It includes measurements such as CPU usage, memory consumption, JVM memory usage, disk usage, etc.
```

2024-05-03 05:45 UTC, shmsr commented on packages/mongodb_atlas/changelog.yml
> +    - description: MongoDB Atlas integration package with "hardware" data stream.
```suggestion
    - description: Add "hardware" data stream to MongoDB Atlas package.
```

2024-05-03 05:45 UTC, shmsr commented on packages/mongodb_atlas/data_stream/hardware/elasticsearch/ingest_pipeline/default.yml
> +      value: ["driver"]
```suggestion
      value: ["driver"]
```

shouldn't this category be "database"?

https://www.elastic.co/guide/en/ecs/current/ecs-allowed-values-event-category.html#ecs-event-category-database

accordingly find the correct event.type too.

2024-05-03 05:45 UTC, shmsr commented on packages/mongodb_atlas/data_stream/hardware/elasticsearch/ingest_pipeline/default.yml
> +      ignore_missing: true
Don't you thinking we should stick to `mongodb_atlas.hardware.jvm.max.memory` and `mongodb_atlas.hardware.jvm.current.memory`? I know by definition it is correct but what's the problem to keep the target fields similar to source fields?

Also in the docs there's no mention of the unit. Probably unit could be anything. We shouldn't assume that it is always `mb`. Also, there's difference between {m,M}{b,B} i.e., megabits and megabytes. We should avoid this.

2024-05-03 05:45 UTC, shmsr commented on packages/mongodb_atlas/data_stream/hardware/fields/fields.yml
> +              metric_type: counter
Recheck all counters. Ideally should be guage. Memory usages are always gauge.

2024-05-03 05:45 UTC, shmsr commented on packages/mongodb_atlas/data_stream/hardware/fields/fields.yml
> +              metric_type: counter
Recommend checking all counters. There are more.

2024-05-03 05:45 UTC, shmsr commented on packages/mongodb_atlas/data_stream/hardware/fields/fields.yml
> +      description: Combination of hostname and Internet Assigned Numbers Authority (IANA) port that serves the MongoDB process.
I think we should not use IANA port in the description. Pretty sure, people use it on ports that are not IANA port i.e., 27017.

Bettter use something like: "MongoDB process port"

2024-05-03 05:45 UTC, shmsr commented on packages/mongodb_atlas/data_stream/hardware/fields/fields.yml
> +        - name: jvm
Shouldn't this be under `status` group? page_faults too?

2024-05-03 05:45 UTC, shmsr commented on packages/mongodb_atlas/data_stream/hardware/fields/fields.yml
> +                      description: Amount of memory that the JVM heap is currently using.
units not mentioned here.

2024-05-03 05:45 UTC, shmsr commented on packages/mongodb_atlas/data_stream/hardware/manifest.yml
> +type: logs
I thought it was metrics?

2024-05-03 05:45 UTC, shmsr commented on packages/mongodb_atlas/data_stream/hardware/manifest.yml
> +        show_user: false
Period should ideally shown to user by default?

2024-05-03 10:07 UTC, niraj-elastic commented on packages/mongodb_atlas/data_stream/hardware/elasticsearch/ingest_pipeline/default.yml
> +      ignore_missing: true
Problem with `mongodb_atlas.hardware.jvm.max.memory` is that even though it is similar to source field it's name is very different than definition, the metric it self collects `Total amount of available memory in the JVM heap.` so including `max` in its name and excluding `available` may lead to confusion for users. `mongodb_atlas.hardware.jvm.current.memory` does not have the same problem so we can use something like `mongodb_atlas.hardware.jvm.memory.heap.current.mb`. The main issue with keeping field names similar to source field is that we have our own approach for field names such as using suffix and grouping similar fields together, which results in to  distinction between the source field name and our field name.

We receive the unit type of all the fields in raw response we get from MongoDB Atlas. So we have valid source to identify that these fields are megabytes. but I understand your concern with Mb & MB, to solve that we can add `Megabytes` in description of the fields. 

Let me know your thoughts.

2024-05-06 06:31 UTC, niraj-elastic commented on packages/mongodb_atlas/data_stream/hardware/fields/fields.yml
> +        - name: jvm
I can create one group for `status` under `hardware`.

2024-05-06 06:33 UTC, niraj-elastic commented on packages/mongodb_atlas/data_stream/hardware/fields/fields.yml
> +                      description: Amount of memory that the JVM heap is currently using.
We dont have `mb` as supported [unit](https://github.com/elastic/package-spec/blob/main/spec/integration/data_stream/fields/fields.spec.yml#L137) currently.

2024-05-06 06:37 UTC, niraj-elastic commented on packages/mongodb_atlas/data_stream/hardware/manifest.yml
> +type: logs
Yes, The data we are collecting is metrics, but we are using CEL input here, which falls under filebeat. So unfortunately the type here can not be changed.

2024-05-06 06:44 UTC, shmsr commented on packages/mongodb_atlas/data_stream/hardware/fields/fields.yml
> +                      description: Amount of memory that the JVM heap is currently using.
Probably it should be byte.

As per [this](https://www.elastic.co/guide/en/elasticsearch/reference/current/bytes-processor.html#:~:text=Bytes%20processoredit,%2C%20%22pb%22%20case%20insensitive.), they call it "byte value".

See if you can verify? I did not double-check.

2024-05-06 10:22 UTC, niraj-elastic commented on packages/mongodb_atlas/data_stream/hardware/elasticsearch/ingest_pipeline/default.yml
> +      ignore_missing: true
> But it supports other types too. Did you test it in a setup where GB's of memory is available to JVM?

i agree with your point. let me remove the unit type.

2024-05-06 10:42 UTC, niraj-elastic commented on packages/mongodb_atlas/data_stream/hardware/fields/fields.yml
> +                      description: Amount of memory that the JVM heap is currently using.
I think setting unit to `byte` will create confusion for users, since if the real data is not in bytes, but in read me it will show as byte. Also I can not find any solid documentation which would define unit type `byte` and if it can be used for mb.

2024-05-06 10:59 UTC, shmsr commented on packages/mongodb_atlas/data_stream/hardware/fields/fields.yml
> +                      description: Amount of memory that the JVM heap is currently using.
Okay, cool.

2024-05-06 11:00 UTC, shmsr commented on packages/mongodb_atlas/data_stream/hardware/fields/fields.yml
> +        - name: jvm
Sure.

2024-05-06 13:42 UTC, muthu-mps commented on packages/mongodb_atlas/data_stream/hardware/fields/fields.yml
> +      description: Identifier for the project of the event.
Can we replace the description for the group_id. `Unique identifier that identifies the project.`

2024-05-06 13:42 UTC, muthu-mps commented on packages/mongodb_atlas/_dev/build/docs/README.md
> +- `hardware`: This data stream collects all the Atlas Search hardware and status data series within the provided time range for one process in the specified project.
Can you help me understand the term `Atlas Search hardware and status data series`. While going through the Atlas [documentation](https://www.mongodb.com/docs/atlas/review-atlas-search-metrics/) it has search metrics and hardware metrics. Are we referring to the search metrics and hardware metrics?

2024-05-08 07:01 UTC, elasticmachine commented
## :broken_heart: Build Failed
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/11248)
* Commit: 4e28497936386ddb52de252d3d4bd900ed0921b9

### Failed CI Steps
* [:pipeline::arrow_up: Upload Pipeline: .buildkite/pipeline.yml](https://buildkite.com/elastic/integrations/builds/11248#018f5700-860c-4bb7-8506-f858ae7e68a1)

### History
* :green_heart: [Build #10760](https://buildkite.com/elastic/integrations/builds/10760) succeeded b80ebf2b1d7c499fc374e2a14925d631b7d68dc8
* :green_heart: [Build #10731](https://buildkite.com/elastic/integrations/builds/10731) succeeded fe50fa700942a9aa2214468246a673c81911be2b

cc @niraj-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11248","number":11248,"commit":"4e28497936386ddb52de252d3d4bd900ed0921b9"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10760","number":10760,"commit":"b80ebf2b1d7c499fc374e2a14925d631b7d68dc8"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10731","number":10731,"commit":"fe50fa700942a9aa2214468246a673c81911be2b"}],"number":11248}
buildkite-pr-comment-->

2024-05-08 07:16 UTC, shmsr commented on packages/mongodb_atlas/data_stream/hardware/elasticsearch/ingest_pipeline/default.yml
> +      ignore_missing: true
Thanks for checking.

2024-05-08 07:18 UTC, shmsr commented
@niraj-elastic Hey, let's fix the merge conflicts and rebase with `main` as other changes also came to this PR. Because of the unrelated changes multiple teams are tagged to this. Unassigning them for now to whom I can until this is fixed.

2024-05-08 09:23 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/11252)
* Commit: ad9d9f2c612dd851f7a594f83c468bd4bb26a002

### History
* :broken_heart: [Build #11248](https://buildkite.com/elastic/integrations/builds/11248) failed 4e28497936386ddb52de252d3d4bd900ed0921b9
* :green_heart: [Build #10760](https://buildkite.com/elastic/integrations/builds/10760) succeeded b80ebf2b1d7c499fc374e2a14925d631b7d68dc8
* :green_heart: [Build #10731](https://buildkite.com/elastic/integrations/builds/10731) succeeded fe50fa700942a9aa2214468246a673c81911be2b

cc @niraj-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11252","number":11252,"commit":"ad9d9f2c612dd851f7a594f83c468bd4bb26a002"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11248","number":11248,"commit":"4e28497936386ddb52de252d3d4bd900ed0921b9"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10760","number":10760,"commit":"b80ebf2b1d7c499fc374e2a14925d631b7d68dc8"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10731","number":10731,"commit":"fe50fa700942a9aa2214468246a673c81911be2b"}],"number":11252}
buildkite-pr-comment-->

2024-05-08 09:42 UTC, shmsr commented
Remove review requests for unrelated teams. Also, looks like you have addressed all the review comments. Changes look good.

2024-05-08 09:42 UTC, shmsr approved these changes

2024-05-08 12:03 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/11270)
* Commit: f256f7ebd9e0fd6dc74e0f156d2c094d6bb4974b

### History
* :green_heart: [Build #11252](https://buildkite.com/elastic/integrations/builds/11252) succeeded ad9d9f2c612dd851f7a594f83c468bd4bb26a002
* :broken_heart: [Build #11248](https://buildkite.com/elastic/integrations/builds/11248) failed 4e28497936386ddb52de252d3d4bd900ed0921b9
* :green_heart: [Build #10760](https://buildkite.com/elastic/integrations/builds/10760) succeeded b80ebf2b1d7c499fc374e2a14925d631b7d68dc8
* :green_heart: [Build #10731](https://buildkite.com/elastic/integrations/builds/10731) succeeded fe50fa700942a9aa2214468246a673c81911be2b

cc @niraj-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11270","number":11270,"commit":"f256f7ebd9e0fd6dc74e0f156d2c094d6bb4974b"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11252","number":11252,"commit":"ad9d9f2c612dd851f7a594f83c468bd4bb26a002"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11248","number":11248,"commit":"4e28497936386ddb52de252d3d4bd900ed0921b9"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10760","number":10760,"commit":"b80ebf2b1d7c499fc374e2a14925d631b7d68dc8"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10731","number":10731,"commit":"fe50fa700942a9aa2214468246a673c81911be2b"}],"number":11270}
buildkite-pr-comment-->

2024-05-09 06:27 UTC, muthu-mps approved these changes
LGTM!

2024-05-09 06:36 UTC, merged

2024-05-09 06:49 UTC, elasticmachine commented
Package mongodb_atlas - 0.0.4 containing this change is available at https://epr.elastic.co/search?package=mongodb_atlas