[Oracle] Mark password field as secret
elastic/integrations pull request #9707
Opened 2024-04-25 06:36 UTC by devamanv

## Proposed commit message
The PR contains changes to mark the password field as secret. 

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## How to test this PR locally

## Related issues
- Relates to https://github.com/elastic/obs-infraobs-team/issues/1369

## Screenshots

2024-04-25 07:14 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10800)
* Commit: 0150bc6651cb8b3f4825d7e1973b2b4af138b2f4

### History
* :broken_heart: [Build #10798](https://buildkite.com/elastic/integrations/builds/10798) failed 52986aeedd9af5602b83cffc477c0f3d28e23dbd

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10800","number":10800,"commit":"0150bc6651cb8b3f4825d7e1973b2b4af138b2f4"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10798","number":10798,"commit":"52986aeedd9af5602b83cffc477c0f3d28e23dbd"}],"number":10800}
buildkite-pr-comment-->

2024-05-09 05:20 UTC, shmsr requested changes

2024-05-09 05:20 UTC, shmsr commented on packages/oracle/_dev/build/docs/README.md
> +> Note: If the requirement is to mask the password shown in the DSN, use the `username` and `password` fields under advanced options to configure them. To do this, simply take the username/password p
```suggestion
> Note: To mask the password shown in the DSN, use the `username` and `password` fields under advanced options to configure them. Remove the username and password from the DSN string, and configure the DSN to include only the host address and any additional parameters required for the connection. Specify the username in the username field and the password in the password field under the advanced options.
```

I have a suggestion for you, but you can also consider other options. I wanted to make the tone more direct and concise. In your previous text, you started with the solution by saying "If the requirement..." and the solution ended with a part of the solution. However, in the next sentence, you started with "To do this", which made it feel like the solution had already ended in the previous sentence. You may want to consider rephrasing your previous text to provide a clearer solution.

2024-05-09 05:20 UTC, shmsr commented on packages/oracle/changelog.yml
> +    - description: Enable secret for the password field.
```suggestion
    - description: Enable secret for the `password` field and add `username` and `password` fields.
```

2024-05-10 05:11 UTC, ritalwar commented on packages/oracle/changelog.yml
> +- version: 1.25.1
Since we're updating the Kibana version, it's preferable to upgrade the minor version rather than the patch.
```suggestion
- version: 1.26.0
```

2024-05-10 05:47 UTC, ishleenk17 commented on packages/oracle/changelog.yml
> +- version: 1.25.1
Agree!

2024-05-10 06:12 UTC, agithomas commented on packages/oracle/docs/README.md
> +
Please add examples.

2024-05-10 06:13 UTC, agithomas commented on packages/oracle/docs/README.md
> +
What happens if someone populates username& password field, use the old DSN format?

2024-05-10 06:18 UTC, agithomas commented on packages/oracle/docs/README.md
> +
Please confirm the value of `service.address` remain the same after the change.

2024-05-10 06:19 UTC, agithomas commented on packages/oracle/docs/README.md
> +
Please validate and confirm the support of special characters which may be part of username and password field. Should some encoding be done ?

2024-05-10 06:23 UTC, agithomas commented on packages/oracle/changelog.yml
> +- version: 1.25.1
Are these changes backward incompatible changes?

2024-05-10 06:23 UTC, agithomas reviewed
Review shared.

2024-05-10 06:29 UTC, ishleenk17 commented
@devamanv : I did read your comment on the upgrade scenario testing in the Issue.
Are we saying that both formats will work in the latest integration?

1. The DSN having the host information along with the username/passowrd info.
2. The DSN having the host information and username/password being separate fields? (If the need passwords as secrets).

2024-05-10 06:37 UTC, devamanv commented
> Are we saying that both formats will work in the latest integration?

@ishleenk17 Yes, I think I have pointed that in my previous comments as well. The Beats code(https://github.com/elastic/beats/blob/main/x-pack/metricbeat/module/oracle/connection.go#L38-L45) gives preference to params(i.e. username and passwords are part of the DSN itself) if present. That ensures the backwards compatibility and with the new changes, the password is taken as secret which covers the second point.

2024-05-10 06:41 UTC, devamanv commented on packages/oracle/docs/README.md
> +
@agithomas 
> What happens if someone populates username & password field, use the old DSN format with username and password? Hope this case is validated.

In this case, the Old DSN is used and given preference over the separate fields. 

> Please validate and confirm the support of special characters which may be part of username and password field. Should some encoding be done ?

There hasn't been any changes in the Beats code. If special characters were handled properly before, they will and should continue to work. Do you think this should be handled separately as part of these changes?

2024-05-10 06:45 UTC, agithomas commented on packages/oracle/docs/README.md
> +
> There hasn't been any changes in the Beats code. If special characters were handled properly before, they will and should continue to work. Do you think this should be handled separately as part of these changes?

I am good if all the usecases we are handling currently continue to be handled.

2024-05-10 06:55 UTC, ishleenk17 approved these changes
Please take care of the Kibana version. Upgrade to 1.26.0.
Otherwise looks good!

2024-05-10 13:19 UTC, devamanv commented on packages/oracle/docs/README.md
> +
> Please confirm the value of service.address remain the same after the change.

@agithomas Although that shouldn't have any affect on the `service.address` value, I still went ahead and verified that the value didn't change, please refer the screenshots below.

![image](https://github.com/elastic/integrations/assets/38116245/f5493bd1-2f29-434d-b00a-8cd6e3f5fd7c)

![image](https://github.com/elastic/integrations/assets/38116245/7c2783b9-bd08-4c45-b1e3-93e07e0790d5)

Please note the database DSN.

2024-05-10 13:20 UTC, devamanv commented on packages/oracle/changelog.yml
> +- version: 1.25.1
Yes, they are. The Old DSN would still continue to work. Please refer the comment down below and the details captured in the linked issue.

2024-05-10 13:24 UTC, agithomas commented on packages/oracle/docs/README.md
> +
Thank you for validating this.

2024-05-10 13:24 UTC, agithomas approved these changes
LGTM!

2024-05-10 14:03 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/11342)
* Commit: b28528a818f010b5d49b38f94d861f892b5c8f05

### History
* :green_heart: [Build #10800](https://buildkite.com/elastic/integrations/builds/10800) succeeded 0150bc6651cb8b3f4825d7e1973b2b4af138b2f4
* :broken_heart: [Build #10798](https://buildkite.com/elastic/integrations/builds/10798) failed 52986aeedd9af5602b83cffc477c0f3d28e23dbd

cc @devamanv

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11342","number":11342,"commit":"b28528a818f010b5d49b38f94d861f892b5c8f05"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10800","number":10800,"commit":"0150bc6651cb8b3f4825d7e1973b2b4af138b2f4"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10798","number":10798,"commit":"52986aeedd9af5602b83cffc477c0f3d28e23dbd"}],"number":11342}
buildkite-pr-comment-->

2024-05-10 15:16 UTC, ritalwar approved these changes
LGTM!

2024-05-10 15:34 UTC, devamanv commented on packages/oracle/_dev/build/docs/README.md
> +> Note: If the requirement is to mask the password shown in the DSN, use the `username` and `password` fields under advanced options to configure them. To do this, simply take the username/password p
Done!

2024-05-10 16:08 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/11344)
* Commit: b3463c6bade4b12e20f2fb1edadfdb200f70869d

### History
* :green_heart: [Build #11342](https://buildkite.com/elastic/integrations/builds/11342) succeeded b28528a818f010b5d49b38f94d861f892b5c8f05
* :green_heart: [Build #10800](https://buildkite.com/elastic/integrations/builds/10800) succeeded 0150bc6651cb8b3f4825d7e1973b2b4af138b2f4
* :broken_heart: [Build #10798](https://buildkite.com/elastic/integrations/builds/10798) failed 52986aeedd9af5602b83cffc477c0f3d28e23dbd

cc @devamanv

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11344","number":11344,"commit":"b3463c6bade4b12e20f2fb1edadfdb200f70869d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11342","number":11342,"commit":"b28528a818f010b5d49b38f94d861f892b5c8f05"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10800","number":10800,"commit":"0150bc6651cb8b3f4825d7e1973b2b4af138b2f4"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10798","number":10798,"commit":"52986aeedd9af5602b83cffc477c0f3d28e23dbd"}],"number":11344}
buildkite-pr-comment-->

2024-05-10 17:14 UTC, shmsr approved these changes

2024-05-10 18:23 UTC, merged

2024-05-10 18:36 UTC, elasticmachine commented
Package oracle - 1.26.0 containing this change is available at https://epr.elastic.co/search?package=oracle