adding zerofox integration
elastic/integrations pull request #971
Opened 2021-05-05 14:36 UTC by zf-jedmunds

# Enhancement

Integration to the ZeroFOX alerts API

# Screenshots

![Screen Shot 2021-05-04 at 3 29 17 PM](https://user-images.githubusercontent.com/18575623/117146385-2733ec00-ad82-11eb-9ec1-255fab0e4501.png)
![Screen Shot 2021-05-04 at 3 29 25 PM](https://user-images.githubusercontent.com/18575623/117146386-2733ec00-ad82-11eb-9075-4eaf2c0f3375.png)
![Screen Shot 2021-05-04 at 3 29 38 PM](https://user-images.githubusercontent.com/18575623/117146389-2733ec00-ad82-11eb-9bdb-8d84e1854e0b.png)
![Screen Shot 2021-05-04 at 3 29 47 PM](https://user-images.githubusercontent.com/18575623/117146390-27cc8280-ad82-11eb-9ecd-fe8f5d9e3273.png)
![Screen Shot 2021-05-04 at 4 05 13 PM](https://user-images.githubusercontent.com/18575623/117146391-27cc8280-ad82-11eb-8f08-efc0497077fe.png)

2021-05-05 14:40 UTC, zf-jedmunds commented
@marc-gr - i just signed the contributor agreement

2021-05-05 14:41 UTC, elasticmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-971/detail/PR-971/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-971/detail/PR-971/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-971/detail/PR-971/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-971/detail/PR-971/1//artifacts) 

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #971 opened`


* Reason: `The PR is not allowed to run in the CI yet`


* Start Time: 2021-05-05T14:36:45.185+0000


* Duration: 4 min 25 sec


* Commit: d5ce9e89a1c761aec716632ba1544bdce9a45ee0




#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/PR-971/buildTimeGraph/png)



</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->









### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations%2FPR-971/detail/PR-971/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Load a resource file from a shared library`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-971/runs/1/steps/80/log/?start=0">here</a></li>
<li>Description: <code>approval-list/elastic/integrations.yml</code></l1>
</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/pipelines/PR-971/runs/1/steps/83/log/?start=0">here</a></li>
<li>Description: <code>githubPrCheckApproved: The PR is not allowed to run in the CI yet. (Only users with write permissions can do so.)</code></l1>
</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-05-05T14:40:34.038Z]  > git config core.sparsecheckout # timeout=10
[2021-05-05T14:40:34.046Z]  > git checkout -f d5ce9e89a1c761aec716632ba1544bdce9a45ee0 # timeout=15
[2021-05-05T14:40:34.854Z] Merge succeeded, producing d5ce9e89a1c761aec716632ba1544bdce9a45ee0
[2021-05-05T14:40:34.855Z] Checking out Revision d5ce9e89a1c761aec716632ba1544bdce9a45ee0 (PR-971)
[2021-05-05T14:40:34.818Z]  > git remote # timeout=10
[2021-05-05T14:40:34.824Z]  > git config --get remote.origin.url # timeout=10
[2021-05-05T14:40:34.828Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-05-05T14:40:34.832Z]  > git merge 4ec7f680a36f2efa0f1a498434fc9b2713dbb012 # timeout=10
[2021-05-05T14:40:34.844Z]  > git rev-parse HEAD^{commit} # timeout=10
[2021-05-05T14:40:34.857Z]  > git config core.sparsecheckout # timeout=10
[2021-05-05T14:40:34.862Z]  > git checkout -f d5ce9e89a1c761aec716632ba1544bdce9a45ee0 # timeout=15
[2021-05-05T14:40:40.517Z] Commit message: "adding zerofox integration"
[2021-05-05T14:40:40.518Z] First time build. Skipping changelog.
[2021-05-05T14:40:40.518Z] Cleaning workspace
[2021-05-05T14:40:40.520Z]  > git rev-parse --verify HEAD # timeout=10
[2021-05-05T14:40:40.525Z] Resetting working tree
[2021-05-05T14:40:40.525Z]  > git reset --hard # timeout=10
[2021-05-05T14:40:40.562Z]  > git clean -fdx # timeout=10
[2021-05-05T14:40:40.681Z]  > git --version # timeout=10
[2021-05-05T14:40:40.684Z]  > git --version # 'git version 2.25.1'
[2021-05-05T14:40:40.689Z] fatal: bad object 4a6c0b76112d1b0647f8ac8e56a03914692b2d3d
[2021-05-05T14:40:41.308Z] Timeout set to expire in 2 hr 0 min
[2021-05-05T14:40:41.337Z] The timestamps step is unnecessary when timestamps are enabled for all Pipeline builds.
[2021-05-05T14:40:41.959Z] [INFO] 'shallow' is forced to be disabled when running on PullRequests
[2021-05-05T14:40:41.980Z] Running in /var/lib/jenkins/workspace/gest-manager_integrations_PR-971/src/github.com/elastic/integrations
[2021-05-05T14:40:42.017Z] [INFO] gitCheckout: Checkout SCM PR-971 with default customisation from the Item.
[2021-05-05T14:40:42.052Z] [INFO] Override default checkout
[2021-05-05T14:40:42.115Z] Sleeping for 10 sec
[2021-05-05T14:40:52.151Z] The recommended git tool is: git
[2021-05-05T14:40:52.293Z] using credential f6c7695a-671e-4f4f-a331-acdce44ff9ba
[2021-05-05T14:40:52.301Z] Wiping out workspace first.
[2021-05-05T14:40:52.311Z] Cloning the remote Git repository
[2021-05-05T14:40:52.312Z] Using shallow clone with depth 4
[2021-05-05T14:40:52.312Z] Avoid fetching tags
[2021-05-05T14:40:52.370Z] Cloning repository git@github.com:elastic/integrations.git
[2021-05-05T14:40:52.489Z]  > git init /var/lib/jenkins/workspace/gest-manager_integrations_PR-971/src/github.com/elastic/integrations # timeout=10
[2021-05-05T14:40:52.495Z] Fetching upstream changes from git@github.com:elastic/integrations.git
[2021-05-05T14:40:52.495Z]  > git --version # timeout=10
[2021-05-05T14:40:52.499Z]  > git --version # 'git version 2.25.1'
[2021-05-05T14:40:52.500Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-05-05T14:40:52.503Z]  > git fetch --no-tags --force --progress -- git@github.com:elastic/integrations.git +refs/heads/*:refs/remotes/origin/* # timeout=15
[2021-05-05T14:40:55.903Z] Cleaning workspace
[2021-05-05T14:40:55.917Z] Using shallow fetch with depth 4
[2021-05-05T14:40:55.917Z] Pruning obsolete local branches
[2021-05-05T14:40:55.888Z]  > git config remote.origin.url git@github.com:elastic/integrations.git # timeout=10
[2021-05-05T14:40:55.891Z]  > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
[2021-05-05T14:40:55.898Z]  > git config remote.origin.url git@github.com:elastic/integrations.git # timeout=10
[2021-05-05T14:40:55.905Z]  > git rev-parse --verify HEAD # timeout=10
[2021-05-05T14:40:55.908Z] No valid HEAD. Skipping the resetting
[2021-05-05T14:40:55.908Z]  > git clean -fdx # timeout=10
[2021-05-05T14:40:55.919Z] Fetching upstream changes from git@github.com:elastic/integrations.git
[2021-05-05T14:40:55.920Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-05-05T14:40:55.923Z]  > git fetch --no-tags --force --progress --prune -- git@github.com:elastic/integrations.git +refs/pull/971/head:refs/remotes/origin/PR-971 +refs/heads/master:refs/remotes/origin/master # timeout=15
[2021-05-05T14:40:56.517Z] Merging remotes/origin/master commit 4ec7f680a36f2efa0f1a498434fc9b2713dbb012 into PR head commit d5ce9e89a1c761aec716632ba1544bdce9a45ee0
[2021-05-05T14:40:57.236Z] Merge succeeded, producing d5ce9e89a1c761aec716632ba1544bdce9a45ee0
[2021-05-05T14:40:57.236Z] Checking out Revision d5ce9e89a1c761aec716632ba1544bdce9a45ee0 (PR-971)
[2021-05-05T14:40:57.483Z] Commit message: "adding zerofox integration"
[2021-05-05T14:40:57.483Z] Cleaning workspace
[2021-05-05T14:40:56.519Z]  > git config core.sparsecheckout # timeout=10
[2021-05-05T14:40:56.522Z]  > git checkout -f d5ce9e89a1c761aec716632ba1544bdce9a45ee0 # timeout=15
[2021-05-05T14:40:57.209Z]  > git remote # timeout=10
[2021-05-05T14:40:57.212Z]  > git config --get remote.origin.url # timeout=10
[2021-05-05T14:40:57.215Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-05-05T14:40:57.2 [...]

2021-05-06 14:42 UTC, marc-gr requested changes
It is looking good! 🎉 

Some of the fields under `zerofox` that could be mapped to ECS fields, and maybe would be nice to have some extra test logs to see some of the empty fields in use. LMK if you need any help to move forward.

2021-05-06 14:42 UTC, marc-gr commented on packages/zerofox/data_stream/alerts/_dev/test/pipeline/test-alert.json-expected.json
> +                "offending_content_url": "hxxp://abc.biz?entity=123456",
This could be mapped to `event.reference` instead, along with adding `event.kind: alert`. https://www.elastic.co/guide/en/ecs/current/ecs-event.html#field-event-reference

2021-05-06 14:42 UTC, marc-gr commented on packages/zerofox/data_stream/alerts/_dev/test/pipeline/test-alert.json-expected.json
> +                "rule_id": "38160",
I think some of these could be mapped to `rule.*`. https://www.elastic.co/guide/en/ecs/current/ecs-rule.html

2021-05-26 13:51 UTC, marc-gr commented
hey @zf-jedmunds ! Thanks for the changes.

One thing I noticed in your pipeline is that the majority of it is dedicated to renaming fields from `json` to `zerofox`. I think it could be rewritten to simplify it by doing the renaming at an early stage. I rewrote it taking this into account and adding some bits at the end to get rid of empty arrays and strings that were being generated.

```yaml
---
description: Pipeline for parsing zerofox alerts
processors:
  - set:
      field: event.ingested
      value: '{{_ingest.timestamp}}'

  - set:
      field: ecs.version
      value: 1.9.0

  - rename:
      field: message
      target_field: event.original

  - json:
      field: event.original
      target_field: zerofox

  - set:
      field: zerofox.severity
      value: info
      if: ctx?.zerofox?.severity == 1
  - set:
      field: zerofox.severity
      value: low
      if: ctx?.zerofox?.severity == 2
  - set:
      field: zerofox.severity
      value: medium
      if: ctx?.zerofox?.severity == 3
  - set:
      field: zerofox.severity
      value: high
      if: ctx?.zerofox?.severity == 4
  - set:
      field: zerofox.severity
      value: critical
      if: ctx?.zerofox?.severity == 5

  - convert:
      field: zerofox.id
      type: string
      ignore_missing: true
      ignore_failure: true

  - convert:
      field: zerofox.asset_term.id
      type: string
      ignore_missing: true
      ignore_failure: true

  - convert:
      field: zerofox.entity.id
      type: string
      ignore_missing: true
      ignore_failure: true

  - convert:
      field: zerofox.entity.entity_group.id
      type: string
      ignore_missing: true
      ignore_failure: true

  - convert:
      field: zerofox.entity_term.id
      type: string
      ignore_missing: true
      ignore_failure: true

  - convert:
      field: zerofox.perpetrator.id
      type: string
      ignore_missing: true
      ignore_failure: true

  - convert:
      field: zerofox.rule_id
      type: string
      ignore_missing: true
      ignore_failure: true

  - convert:
      field: zerofox.rule_group_id
      type: string
      ignore_missing: true
      ignore_failure: true

  - convert:
      field: zerofox.asset.id
      type: string
      ignore_missing: true
      ignore_failure: true

  - convert:
      field: zerofox.asset.entity_group.id
      type: string
      ignore_missing: true
      ignore_failure: true

  - json:
      field: zerofox.metadata
      ignore_failure: true

 ## Cleanup.

  - remove:
      field:
        - zerofox.logs
        - zerofox.entered_by
        - zerofox.asset_term
        - zerofox.entity_term
        - zerofox.business_network
        - zerofox.entity_email_receiver_id
      ignore_missing: true
      ignore_failure: true
  - script:
      description: Remove all empty values from zerofox.perpetrator.
      lang: painless
      if: ctx?.zerofox?.perpetrator != null
      source: ctx.zerofox.perpetrator?.entrySet().removeIf(entry -> entry.getValue() == null || entry.getValue().equals("") || (entry.getValue() instanceof List && entry.getValue().length == 0) || (entry.getValue() instanceof Map && entry.getValue().size() == 0));
  - script:
      description: Remove all empty values from zerofox.metadata.
      lang: painless
      if: ctx?.zerofox?.metadata != null
      source: ctx?.zerofox?.metadata?.entrySet().removeIf(entry -> entry.getValue() == null || entry.getValue().equals("") || (entry.getValue() instanceof List && entry.getValue().length == 0) || (entry.getValue() instanceof Map && entry.getValue().size() == 0));
  - script:
      description: Remove all empty values from zerofox.
      lang: painless
      if: ctx?.zerofox != null
      source: ctx?.zerofox?.entrySet().removeIf(entry -> entry.getValue() == null || entry.getValue().equals("") || (entry.getValue() instanceof List && entry.getValue().length == 0) || (entry.getValue() instanceof Map && entry.getValue().size() == 0));

on_failure:
  - set:
      field: error.message
      value: "{{ _ingest.on_failure_message }}"
```

Please take a look and feel free to change anything you need in case I messed it up :) If you end up using it remember to re-generate the test golden files.

On top of that, would be nice if some ECS mappings could be done and just keep under the `zerofox.*` namespace anything that is not possible to map to ECS fields.  LMK if you need anything from our side to move forward :) 

Thanks for the work!

2021-05-27 08:42 UTC, marc-gr commented
/test

2021-06-09 13:49 UTC, elasticmachine commented
Pinging @elastic/security-external-integrations (Team:Security-External Integrations)

2021-07-22 10:25 UTC, marc-gr commented
/test

2021-07-29 13:13 UTC, marc-gr commented
/test

2021-07-29 14:07 UTC, marc-gr approved these changes

2021-07-29 14:25 UTC, marc-gr commented on packages/zerofox/manifest.yml
> +  kibana.version: ^7.12.1
```suggestion
  kibana.version: ^7.14
```

2021-07-29 14:38 UTC, merged