[Mongodb Atlas] Organization Log Datastream
elastic/integrations pull request #9754
Opened 2024-04-30 12:22 UTC by milan-elastic

Create the package for Mongodb Atlas Integration and Provide the support of **Organization logs**.

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

Along with the organization PR, resolved the following issue for process, mongod_audit and mongod_database as well.
- https://github.com/elastic/obs-infraobs-team/issues/1372

### All changes

- [x] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/main/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [x] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [x] Documentation exists, [useful guidelines](https://github.com/elastic/integrations/blob/main/docs/documentation_guidelines.md) to follow
- [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [x] At least a manual test with ES / Kibana / Agent has been performed.
- [x] Required Kibana version set to: 8.12.0
- [ ] TSDB enablement for the data stream

### Data dataset changes

_This entry is currently only recommended. It will be mandatory once we provide better support for it._

- [x] Sample event (`sample_event.json`) exists

### Related Issue
- Relates https://github.com/elastic/obs-infraobs-team/issues/1375

### Screenshots

### Known Issues:
Currently Following challenges are still open to solve for this PR:
- https://github.com/elastic/obs-infraobs-team/issues/1350
- https://github.com/elastic/obs-infraobs-team/issues/1351
- https://github.com/elastic/obs-infraobs-team/issues/1372

2024-04-30 12:39 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-04-30 12:40 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/10963)
* Commit: 1e93b620bdc2304fad7969de0c7c171531959662

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10963","number":10963,"commit":"1e93b620bdc2304fad7969de0c7c171531959662"}],"number":10963}
buildkite-pr-comment-->

2024-04-30 16:07 UTC, niraj-elastic commented on packages/mongodb_atlas/data_stream/organization/manifest.yml
> +      - name: preserve_original_event
We have not handled `preserve orignal` in pipeline, so we can either remove it from here, or add it in pipeline.

2024-05-02 10:29 UTC, niraj-elastic approved these changes
LGTM

2024-05-02 10:32 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/11050)
* Commit: 85189d59ccdcdb95cc2aa3d160a7d97099d09d0d

### History
* :green_heart: [Build #10966](https://buildkite.com/elastic/integrations/builds/10966) succeeded 5f2976da107996aa16ed2ee66bb5806efc32aaad
* :green_heart: [Build #10963](https://buildkite.com/elastic/integrations/builds/10963) succeeded 1e93b620bdc2304fad7969de0c7c171531959662

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11050","number":11050,"commit":"85189d59ccdcdb95cc2aa3d160a7d97099d09d0d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10966","number":10966,"commit":"5f2976da107996aa16ed2ee66bb5806efc32aaad"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10963","number":10963,"commit":"1e93b620bdc2304fad7969de0c7c171531959662"}],"number":11050}
buildkite-pr-comment-->

2024-05-07 07:31 UTC, shmsr requested changes

2024-05-07 07:31 UTC, shmsr commented on packages/mongodb_atlas/data_stream/organization/fields/fields.yml
> +      description: Name of the collection on which the event occurred.
```suggestion
      description: Name of the collection where the event occurred.
```

2024-05-07 07:31 UTC, shmsr commented on packages/mongodb_atlas/data_stream/organization/fields/fields.yml
> +      description: Name of the database on which the event occurred.
```suggestion
      description: Name of the database where the event occurred.
```

2024-05-07 07:31 UTC, shmsr commented on packages/mongodb_atlas/data_stream/organization/fields/fields.yml
> +      description: Indicates name of the event.
```suggestion
      description: Name of the event type.

```

2024-05-07 07:31 UTC, shmsr commented on packages/mongodb_atlas/data_stream/organization/fields/fields.yml
> +          description: ID of the host on which this event occurred.
```suggestion
          description: ID of the host where this event occurred.
```

2024-05-07 07:31 UTC, shmsr commented on packages/mongodb_atlas/data_stream/organization/fields/fields.yml
> +      description: Indicates name of the event.
Probably avoid the word "Indicates" as we are not using this for other fields. Only a few are using "Indicates".

2024-05-07 07:34 UTC, muthu-mps commented on packages/mongodb_atlas/data_stream/organization/sample_event.json
> +                "orgName": "Integrations - 2023-05-25",
Can we convert the JSON keys to snake_case?

**Reference:** https://github.com/elastic/integrations/blob/8fad2d63b9a38c89f64e0edc8a0f4af367fc692f/packages/azure/data_stream/signinlogs/elasticsearch/ingest_pipeline/default.yml#L15

2024-05-07 12:02 UTC, alaudazzi approved these changes
Left a few minor editing suggestions, otherwise LGTM.

2024-05-07 12:02 UTC, alaudazzi commented on packages/mongodb_atlas/_dev/build/docs/README.md
> +2. From the Atlas UI with `project owner` permission, go to Project Settings > Access Manager > API Keys and then click on Invite To Project to add the API key created above, as described in this Atl
UI text and components are bold
```suggestion
2. From the Atlas UI with `project owner` permission, go to *Project Settings* > *Access Manager* > *API Keys* and then click *Invite To Project* to add the API key created above, as described in the Atlas [documentation](https://www.mongodb.com/docs/atlas/configure-api-access/#invite-an-organization-api-key-to-a-project).
```

2024-05-08 10:24 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/11261)
* Commit: f73b97d4929bcad60fefe15c60b6ca3a503d459f

### Failed CI Steps
* [Check integrations mongodb_atlas](https://buildkite.com/elastic/integrations/builds/11261#018f57b7-cb0c-45db-8ac1-20cc3df9a1bf)

### History
* :green_heart: [Build #11050](https://buildkite.com/elastic/integrations/builds/11050) succeeded 85189d59ccdcdb95cc2aa3d160a7d97099d09d0d
* :green_heart: [Build #10966](https://buildkite.com/elastic/integrations/builds/10966) succeeded 5f2976da107996aa16ed2ee66bb5806efc32aaad
* :green_heart: [Build #10963](https://buildkite.com/elastic/integrations/builds/10963) succeeded 1e93b620bdc2304fad7969de0c7c171531959662

cc @milan-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11261","number":11261,"commit":"f73b97d4929bcad60fefe15c60b6ca3a503d459f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11050","number":11050,"commit":"85189d59ccdcdb95cc2aa3d160a7d97099d09d0d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10966","number":10966,"commit":"5f2976da107996aa16ed2ee66bb5806efc32aaad"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10963","number":10963,"commit":"1e93b620bdc2304fad7969de0c7c171531959662"}],"number":11261}
buildkite-pr-comment-->

2024-05-08 11:07 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/11264)
* Commit: 141aa4d54cf751631ade9f3606befcd409ed99eb

### History
* :broken_heart: [Build #11261](https://buildkite.com/elastic/integrations/builds/11261) failed f73b97d4929bcad60fefe15c60b6ca3a503d459f
* :green_heart: [Build #11050](https://buildkite.com/elastic/integrations/builds/11050) succeeded 85189d59ccdcdb95cc2aa3d160a7d97099d09d0d
* :green_heart: [Build #10966](https://buildkite.com/elastic/integrations/builds/10966) succeeded 5f2976da107996aa16ed2ee66bb5806efc32aaad
* :green_heart: [Build #10963](https://buildkite.com/elastic/integrations/builds/10963) succeeded 1e93b620bdc2304fad7969de0c7c171531959662

cc @milan-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11264","number":11264,"commit":"141aa4d54cf751631ade9f3606befcd409ed99eb"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11261","number":11261,"commit":"f73b97d4929bcad60fefe15c60b6ca3a503d459f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11050","number":11050,"commit":"85189d59ccdcdb95cc2aa3d160a7d97099d09d0d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10966","number":10966,"commit":"5f2976da107996aa16ed2ee66bb5806efc32aaad"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10963","number":10963,"commit":"1e93b620bdc2304fad7969de0c7c171531959662"}],"number":11264}
buildkite-pr-comment-->

2024-05-08 15:18 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/11278)
* Commit: 863d5ef903d590f77fd55fd810ad9674a2222d70

### History
* :green_heart: [Build #11264](https://buildkite.com/elastic/integrations/builds/11264) succeeded 141aa4d54cf751631ade9f3606befcd409ed99eb
* :broken_heart: [Build #11261](https://buildkite.com/elastic/integrations/builds/11261) failed f73b97d4929bcad60fefe15c60b6ca3a503d459f
* :green_heart: [Build #11050](https://buildkite.com/elastic/integrations/builds/11050) succeeded 85189d59ccdcdb95cc2aa3d160a7d97099d09d0d
* :green_heart: [Build #10966](https://buildkite.com/elastic/integrations/builds/10966) succeeded 5f2976da107996aa16ed2ee66bb5806efc32aaad
* :green_heart: [Build #10963](https://buildkite.com/elastic/integrations/builds/10963) succeeded 1e93b620bdc2304fad7969de0c7c171531959662

cc @milan-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11278","number":11278,"commit":"863d5ef903d590f77fd55fd810ad9674a2222d70"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11264","number":11264,"commit":"141aa4d54cf751631ade9f3606befcd409ed99eb"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11261","number":11261,"commit":"f73b97d4929bcad60fefe15c60b6ca3a503d459f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11050","number":11050,"commit":"85189d59ccdcdb95cc2aa3d160a7d97099d09d0d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10966","number":10966,"commit":"5f2976da107996aa16ed2ee66bb5806efc32aaad"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10963","number":10963,"commit":"1e93b620bdc2304fad7969de0c7c171531959662"}],"number":11278}
buildkite-pr-comment-->

2024-05-09 08:51 UTC, muthu-mps commented
@milan-elastic - The header values for the table visualisation can be updated to make it more readable. Check whether we could rename those values.

<img width="953" alt="Screenshot 2024-05-09 at 2 14 40 PM" src="https://github.com/elastic/integrations/assets/101238137/1d67f700-daab-4d1d-bc90-9ba7b57f1bab">

2024-05-09 09:03 UTC, shmsr approved these changes

2024-05-09 10:18 UTC, milan-elastic commented
> @milan-elastic - The header values for the table visualisation can be updated to make it more readable. Check whether we could rename those values.
> 
> <img alt="Screenshot 2024-05-09 at 2 14 40 PM" width="953" src="https://private-user-images.githubusercontent.com/101238137/329185828-1d67f700-daab-4d1d-bc90-9ba7b57f1bab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNDk3NzMsIm5iZiI6MTcxNTI0OTQ3MywicGF0aCI6Ii8xMDEyMzgxMzcvMzI5MTg1ODI4LTFkNjdmNzAwLWRhYWItNGQxZC1iYzkwLTliYTdiNTdmMWJhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQxMDExMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMTYyMWIyMWNhNTE2NzdmYThkOTIxZDgyYzFjYzM1M2RjZWUyYzliZjk3ZDcyM2MwOGI5YjlhOTdiYzcwNTY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wQz7x4PCX8KT3sPeWg6CnuYFAgHjgqZ0t6XwXkGAd88">

@muthu-mps It is saved search, hence we can not change the header of it!

2024-05-09 10:24 UTC, muthu-mps approved these changes
@ishleenk17 - Please have a second view on dashboards. We can think of adding a overview dashboard later.
Change looks good to me!

2024-05-09 12:47 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/11304)
* Commit: e2584b5d9570d5980dd0d4b9e79342ea7e3a86b6

### History
* :green_heart: [Build #11278](https://buildkite.com/elastic/integrations/builds/11278) succeeded 863d5ef903d590f77fd55fd810ad9674a2222d70
* :green_heart: [Build #11264](https://buildkite.com/elastic/integrations/builds/11264) succeeded 141aa4d54cf751631ade9f3606befcd409ed99eb
* :broken_heart: [Build #11261](https://buildkite.com/elastic/integrations/builds/11261) failed f73b97d4929bcad60fefe15c60b6ca3a503d459f
* :green_heart: [Build #11050](https://buildkite.com/elastic/integrations/builds/11050) succeeded 85189d59ccdcdb95cc2aa3d160a7d97099d09d0d
* :green_heart: [Build #10966](https://buildkite.com/elastic/integrations/builds/10966) succeeded 5f2976da107996aa16ed2ee66bb5806efc32aaad
* :green_heart: [Build #10963](https://buildkite.com/elastic/integrations/builds/10963) succeeded 1e93b620bdc2304fad7969de0c7c171531959662

cc @milan-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11304","number":11304,"commit":"e2584b5d9570d5980dd0d4b9e79342ea7e3a86b6"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11278","number":11278,"commit":"863d5ef903d590f77fd55fd810ad9674a2222d70"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11264","number":11264,"commit":"141aa4d54cf751631ade9f3606befcd409ed99eb"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11261","number":11261,"commit":"f73b97d4929bcad60fefe15c60b6ca3a503d459f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11050","number":11050,"commit":"85189d59ccdcdb95cc2aa3d160a7d97099d09d0d"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/10966","number":10966,"commit":"5f2976da107996aa16ed2ee66bb5806efc32aaad"}],"number":11304}
buildkite-pr-comment-->

2024-05-09 13:36 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/11307)
* Commit: ec92a91458c423501e1aa8779ba00964bdc7d3b5

### History
* :green_heart: [Build #11304](https://buildkite.com/elastic/integrations/builds/11304) succeeded e2584b5d9570d5980dd0d4b9e79342ea7e3a86b6
* :green_heart: [Build #11278](https://buildkite.com/elastic/integrations/builds/11278) succeeded 863d5ef903d590f77fd55fd810ad9674a2222d70
* :green_heart: [Build #11264](https://buildkite.com/elastic/integrations/builds/11264) succeeded 141aa4d54cf751631ade9f3606befcd409ed99eb
* :broken_heart: [Build #11261](https://buildkite.com/elastic/integrations/builds/11261) failed f73b97d4929bcad60fefe15c60b6ca3a503d459f
* :green_heart: [Build #11050](https://buildkite.com/elastic/integrations/builds/11050) succeeded 85189d59ccdcdb95cc2aa3d160a7d97099d09d0d
* :green_heart: [Build #10966](https://buildkite.com/elastic/integrations/builds/10966) succeeded 5f2976da107996aa16ed2ee66bb5806efc32aaad

cc @milan-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11307","number":11307,"commit":"ec92a91458c423501e1aa8779ba00964bdc7d3b5"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11304","number":11304,"commit":"e2584b5d9570d5980dd0d4b9e79342ea7e3a86b6"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11278","number":11278,"commit":"863d5ef903d590f77fd55fd810ad9674a2222d70"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11264","number":11264,"commit":"141aa4d54cf751631ade9f3606befcd409ed99eb"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11261","number":11261,"commit":"f73b97d4929bcad60fefe15c60b6ca3a503d459f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11050","number":11050,"commit":"85189d59ccdcdb95cc2aa3d160a7d97099d09d0d"}],"number":11307}
buildkite-pr-comment-->

2024-05-15 05:46 UTC, ishleenk17 approved these changes
Looks good!

2024-05-15 05:48 UTC, merged

2024-05-15 06:00 UTC, elasticmachine commented
Package mongodb_atlas - 0.0.5 containing this change is available at https://epr.elastic.co/search?package=mongodb_atlas