cloudflare: allow user configuration of results per page
elastic/integrations pull request #9776
Opened 2024-05-02 22:31 UTC by efd6

## Proposed commit message

See title.

## Checklist

- [ ] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ] I have verified that all data streams collect metrics or logs.
- [ ] I have added an entry to my package's `changelog.yml` file.
- [ ] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Author's Checklist

- [ ] 

## How to test this PR locally

## Related issues

- 

## Screenshots

2024-05-02 22:49 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-05-02 22:50 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/11076)
* Commit: a7e969d2eb14221ba16dc5c991bd1faa79d461d3

cc @efd6

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11076","number":11076,"commit":"a7e969d2eb14221ba16dc5c991bd1faa79d461d3"}],"number":11076}
buildkite-pr-comment-->

2024-05-07 06:30 UTC, chrisberkhout requested changes
Aside: the API docs mention "Logpush", but not "Logpull". However, the `/client/v4/zones/{zone_identifier}/logs/received` endpoint is documented under "Logs Received -> Get logs received".

2024-05-07 06:30 UTC, chrisberkhout commented on packages/cloudflare/data_stream/audit/agent/stream/httpjson.yml.hbs
> +request.url: {{api_url}}/client/v4/accounts/{{account}}/audit_logs?page=1&per_page={{per_page}}&direction=desc
Looks good, matches API doc https://developers.cloudflare.com/api/operations/audit-logs-get-account-audit-logs

2024-05-07 06:30 UTC, chrisberkhout commented on packages/cloudflare/data_stream/logpull/agent/stream/httpjson.yml.hbs
> +      target: url.params.per_page
For this endpoint, it looks like it should be `count`, not `per_page`.
https://developers.cloudflare.com/api/operations/logs-received-get-logs-received

2024-05-07 08:11 UTC, efd6 commented on packages/cloudflare/data_stream/logpull/agent/stream/httpjson.yml.hbs
> +      target: url.params.per_page
Changing the param target, but leaving the rest as `per_page` for consistency with the other data stream.

2024-05-07 08:31 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/11208)
* Commit: f85223dd3b19777365f16885a4e222a1b98c91d3

### History
* :green_heart: [Build #11076](https://buildkite.com/elastic/integrations/builds/11076) succeeded a7e969d2eb14221ba16dc5c991bd1faa79d461d3

cc @efd6

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11208","number":11208,"commit":"f85223dd3b19777365f16885a4e222a1b98c91d3"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11076","number":11076,"commit":"a7e969d2eb14221ba16dc5c991bd1faa79d461d3"}],"number":11208}
buildkite-pr-comment-->

2024-05-07 23:28 UTC, chrisberkhout approved these changes

2024-05-08 00:39 UTC, merged