[O11y][Redis] Support authentication with username and ssl
elastic/integrations pull request #9777
Opened 2024-05-03 05:45 UTC by harnish-elastic

## Proposed commit message

- Support authentication with username and SSL for key, keyspace and info data streams.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Relates #5427

2024-05-03 06:05 UTC, elasticmachine commented
### :rocket: Benchmarks report


#### Package `redis` :&#43;1:(0) :green_heart:(0) :broken_heart:(1)
<details>
<summary>Expand to view</summary>

Data stream | Previous EPS | New EPS | Diff (%) | Result
----------- | ------------ | ------- | -------- | ------
`log` | 4115.23 | 3236.25 | -878.98 (-21.36%) | :broken_heart:
</details>


To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-05-03 06:05 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/11085)
* Commit: 427740455621309e2f4c5ce249312e706b361408

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11085","number":11085,"commit":"427740455621309e2f4c5ce249312e706b361408"}],"number":11085}
buildkite-pr-comment-->

2024-05-06 06:28 UTC, niraj-elastic commented on packages/redis/changelog.yml
> +    - description: Support authentication with username and ssl.
```suggestion
    - description: Add Support of username and ssl in authentication.
```

2024-05-06 06:49 UTC, shmsr approved these changes

2024-05-06 06:50 UTC, shmsr requested changes

2024-05-06 06:50 UTC, shmsr commented on packages/redis/manifest.yml
> +            description: i.e. certificate_authorities, supported_protocols, verification_mode etc.
Can we improve the description?

2024-05-06 06:50 UTC, shmsr commented on packages/redis/manifest.yml
> +            description: i.e. certificate_authorities, supported_protocols, verification_mode etc.
Looks weird. How does it show up on Kibana? Can you please see?

2024-05-06 07:10 UTC, harnish-elastic commented on packages/redis/manifest.yml
> +            description: i.e. certificate_authorities, supported_protocols, verification_mode etc.
It will show up on kibana as below, Please let me know your thoughts on what should we show up to improve the description. FYI, all the packages currently having the same SSL descriptions!

![image](https://github.com/elastic/integrations/assets/118714680/d15e510c-aa4d-4910-9872-5ecd124b2bfd)

2024-05-06 07:28 UTC, shmsr commented on packages/redis/manifest.yml
> +            description: i.e. certificate_authorities, supported_protocols, verification_mode etc.
Let's change it to something like this:

https://www.elastic.co/guide/en/beats/filebeat/current/configuration-ssl.html#:~:text=Common%20SSL%20configuration%20options%20can%20be%20used%20in%20both%20client%20and%20server%20configurations.%20You%20can%20specify%20the%20following%20options%20in%20the%20ssl%20section%20of%20each%20subsystem%20that%20supports%20SSL.

From ^^, we can probably do this?

> This section allows for the configuration of SSL settings to enable secure communication between the client and server. Both common and specific SSL options can be customized to ensure a secure and reliable connection. Example: [certificate_authorities](https://github.com/elastic/beats/edit/8.13/libbeat/docs/shared-ssl-config.asciidoc), [supported-protocols](https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-ssl.html#supported-protocols), [verification-mode](https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-ssl.html#client-verification-mode), [key](https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-ssl.html#client-key), [certificate](https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-ssl.html#client-certificate), etc.

2024-05-06 07:41 UTC, harnish-elastic commented on packages/redis/manifest.yml
> +            description: i.e. certificate_authorities, supported_protocols, verification_mode etc.
For the [certificate_authorities](https://github.com/elastic/beats/edit/8.13/libbeat/docs/shared-ssl-config.asciidoc), links looks broken to me! Can you have a look and update?

![image](https://github.com/elastic/integrations/assets/118714680/13725517-523f-407d-8a38-240d2ebcb4f2)

2024-05-06 07:43 UTC, harnish-elastic commented on packages/redis/manifest.yml
> +            description: i.e. certificate_authorities, supported_protocols, verification_mode etc.
Is this link that you are suggesting to be there for [certificate_authorities](https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-ssl.html#client-certificate-authorities)?

2024-05-06 08:12 UTC, shmsr commented on packages/redis/manifest.yml
> +            description: i.e. certificate_authorities, supported_protocols, verification_mode etc.
Here: https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-ssl.html#client-certificate-authorities

2024-05-06 08:13 UTC, shmsr commented on packages/redis/manifest.yml
> +            description: i.e. certificate_authorities, supported_protocols, verification_mode etc.
> Is this link that you are suggesting to be there for [certificate_authorities](https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-ssl.html#client-certificate-authorities)?

Yep!

2024-05-06 08:16 UTC, harnish-elastic commented on packages/redis/manifest.yml
> +            description: i.e. certificate_authorities, supported_protocols, verification_mode etc.
Here is the screenshot of how it will show up in kibana.

![image](https://github.com/elastic/integrations/assets/118714680/0c1e2c15-ec85-4a87-8753-bc76a11eb680)

2024-05-06 08:25 UTC, shmsr approved these changes

2024-05-06 08:31 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/11137)
* Commit: 3a98b3f93e868875276f705f0fc1265524cb523b

### History
* :green_heart: [Build #11130](https://buildkite.com/elastic/integrations/builds/11130) succeeded eaff5af9e698220c712df54c8283269f28418d5c
* :green_heart: [Build #11085](https://buildkite.com/elastic/integrations/builds/11085) succeeded 427740455621309e2f4c5ce249312e706b361408

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11137","number":11137,"commit":"3a98b3f93e868875276f705f0fc1265524cb523b"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11130","number":11130,"commit":"eaff5af9e698220c712df54c8283269f28418d5c"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11085","number":11085,"commit":"427740455621309e2f4c5ce249312e706b361408"}],"number":11137}
buildkite-pr-comment-->

2024-05-06 08:41 UTC, niraj-elastic approved these changes
LGTM

2024-05-06 08:44 UTC, merged

2024-05-06 09:14 UTC, elasticmachine commented
Package redis - 1.15.0 containing this change is available at https://epr.elastic.co/search?package=redis