[O11y][Cassandra] Add documentation for Jolokia setup in the README
elastic/integrations pull request #9817
Opened 2024-05-08 09:29 UTC by harnish-elastic

## Proposed commit message

- Added detailed instructions for jolokia setup in Cassandra README.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Closes #9749

2024-05-08 09:46 UTC, elasticmachine commented
### :rocket: Benchmarks report




To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-05-08 09:46 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/11255)
* Commit: fd54ee5edacd21a1f0d90b48b995fb1f68169290

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11255","number":11255,"commit":"fd54ee5edacd21a1f0d90b48b995fb1f68169290"}],"number":11255}
buildkite-pr-comment-->

2024-05-08 18:17 UTC, shmsr requested changes

2024-05-08 18:17 UTC, shmsr commented on packages/cassandra/_dev/build/docs/README.md
> +
```suggestion
Replace `/path/to/cassandra/lib/` with the actual path to Cassandra's library directory.

```

2024-05-08 18:17 UTC, shmsr commented on packages/cassandra/_dev/build/docs/README.md
> +   To enable the Jolokia agent, modify the `cassandra-env.sh` by adding the following line at the bottom of file:
```suggestion
   Open the `cassandra-env.sh` file, located in the Cassandra configuration directory, using a text editor, and add the following line at the bottom of the file:
```

2024-05-08 18:17 UTC, shmsr commented on packages/cassandra/_dev/build/docs/README.md
> +
```suggestion
Replace `/path/to/jolokia-jvm-<version>-agent.jar` with the actual path to the Jolokia agent JAR file copied in Step 2. Save the changes and close the `cassandra-env.sh` file.

```

2024-05-08 18:17 UTC, shmsr commented on packages/cassandra/_dev/build/docs/README.md
> +To monitor Cassandra with Jolokia, need to set up the Jolokia JVM agent.
```suggestion
Follow these steps to set up Jolokia for monitoring Apache Cassandra:
```

2024-05-08 18:17 UTC, shmsr commented on packages/cassandra/_dev/build/docs/README.md
> +   After configuring Cassandra with the Jolokia agent, restart the Cassandra service to apply the changes.
```suggestion
4. Restart Cassandra:

   Restart the Apache Cassandra service to apply the changes made to the configuration.
```

2024-05-08 18:17 UTC, shmsr commented on packages/cassandra/_dev/build/docs/README.md
> +   - Ensure no cluster maintenance tasks are in progress during the restart to prevent any unintended consequences.
```suggestion
  > Note:
 - Restarting the Apache Cassandra service will temporarily disrupt database connectivity. Ensure that dependent services are designed to handle such interruptions gracefully.
 - Immediately after a restart, Cassandra's performance may be impacted due to cold caches and commit log replay. Allow some time for the system to stabilize.
 - Before restarting Cassandra, ensure that no cluster maintenance tasks are in progress to prevent any unintended consequences.
```

2024-05-08 18:17 UTC, shmsr commented on packages/cassandra/_dev/build/docs/README.md
> +
Do you think we add something like:

**Verifying the setup**

After restarting Cassandra, you can verify that Jolokia is properly set up by accessing the Jolokia endpoint:

```
http://<cassandra-host>:7777/jolokia/
```

Replace <cassandra-host> with the hostname or IP address of your Cassandra server.

If the setup is successful, you should see a JSON response containing information about the available Jolokia operations and the Cassandra instance.

You can now use Jolokia to monitor and manage your Apache Cassandra cluster.

2024-05-08 18:17 UTC, shmsr commented on packages/cassandra/changelog.yml
> +    - description: Add documentation for Jolokia setup in the README.
```suggestion
    - description: Add documentation for setting up Jolokia to monitor Apache Cassandra in the README file.
```

2024-05-08 18:18 UTC, shmsr commented
Left some comments to make the tone of the doc consistent. Also suggested some improvements and clarified some parts where paths need to be changed. Please check.

2024-05-09 07:47 UTC, lalit-satapathy commented on packages/cassandra/_dev/build/docs/README.md
> +
Agree, this step will be useful.

2024-05-09 07:47 UTC, lalit-satapathy commented on packages/cassandra/_dev/build/docs/README.md
> +   - Ensure no cluster maintenance tasks are in progress during the restart to prevent any unintended consequences.
Please note the exact steps will vary based on the installation type. For example: if cassandra is installed via kkubernetes, the steps above could be different,. 

We could mention, this is representative example only and can provide minimal guideline on restart scenario.

2024-05-09 13:14 UTC, harnish-elastic commented
> Left some comments to make the tone of the doc consistent. Also suggested some improvements and clarified some parts where paths need to be changed. Please check.

Addressed, thanks! 🙌

2024-05-09 13:26 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/11306)
* Commit: 9c33cf3debb9e7b08da97fdce30aca6074224999

### History
* :green_heart: [Build #11255](https://buildkite.com/elastic/integrations/builds/11255) succeeded fd54ee5edacd21a1f0d90b48b995fb1f68169290

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11306","number":11306,"commit":"9c33cf3debb9e7b08da97fdce30aca6074224999"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11255","number":11255,"commit":"fd54ee5edacd21a1f0d90b48b995fb1f68169290"}],"number":11306}
buildkite-pr-comment-->

2024-05-13 05:10 UTC, harnish-elastic commented on packages/cassandra/_dev/build/docs/README.md
> +
Updated, thanks!

2024-05-13 05:38 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/11372)
* Commit: 0b3a469171c177471477dccd885e3059aa30e9b4

### History
* :green_heart: [Build #11306](https://buildkite.com/elastic/integrations/builds/11306) succeeded 9c33cf3debb9e7b08da97fdce30aca6074224999
* :green_heart: [Build #11255](https://buildkite.com/elastic/integrations/builds/11255) succeeded fd54ee5edacd21a1f0d90b48b995fb1f68169290

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11372","number":11372,"commit":"0b3a469171c177471477dccd885e3059aa30e9b4"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11306","number":11306,"commit":"9c33cf3debb9e7b08da97fdce30aca6074224999"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11255","number":11255,"commit":"fd54ee5edacd21a1f0d90b48b995fb1f68169290"}],"number":11372}
buildkite-pr-comment-->

2024-05-13 06:33 UTC, milan-elastic approved these changes
LGTM

2024-05-14 05:16 UTC, harnish-elastic commented on packages/cassandra/_dev/build/docs/README.md
> +
Updated, thanks!

2024-05-14 05:17 UTC, harnish-elastic commented on packages/cassandra/_dev/build/docs/README.md
> +
Updated, thanks!

2024-05-15 18:21 UTC, shmsr commented on packages/cassandra/changelog.yml
> +    - description: Add documentation for setting up Jolokia to monitor Apache Cassandra in the README file.
```suggestion
    - description: Add documentation for setting up Jolokia to monitor Apache Cassandra.
```

2024-05-15 18:21 UTC, shmsr approved these changes
Left one comment. Else, LGTM.

2024-05-16 05:33 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/11527)
* Commit: f4da7dcc49501d2c2aa3537dfcfcf8abe6874cf1

### History
* :green_heart: [Build #11372](https://buildkite.com/elastic/integrations/builds/11372) succeeded 0b3a469171c177471477dccd885e3059aa30e9b4
* :green_heart: [Build #11306](https://buildkite.com/elastic/integrations/builds/11306) succeeded 9c33cf3debb9e7b08da97fdce30aca6074224999
* :green_heart: [Build #11255](https://buildkite.com/elastic/integrations/builds/11255) succeeded fd54ee5edacd21a1f0d90b48b995fb1f68169290

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11527","number":11527,"commit":"f4da7dcc49501d2c2aa3537dfcfcf8abe6874cf1"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11372","number":11372,"commit":"0b3a469171c177471477dccd885e3059aa30e9b4"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11306","number":11306,"commit":"9c33cf3debb9e7b08da97fdce30aca6074224999"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11255","number":11255,"commit":"fd54ee5edacd21a1f0d90b48b995fb1f68169290"}],"number":11527}
buildkite-pr-comment-->

2024-05-16 09:47 UTC, merged