[O11y][Couchbase] Fix system tests
elastic/integrations pull request #9896
Opened 2024-05-16 13:05 UTC by aliabbas-elastic

## Proposed commit message

Fixes the flaky tests which result in error message `one or more errors found in documents stored in metrics-couchbase.xdcr-ep data stream: [0] found error.message in event: [invalid character 'R' looking for beginning of value]`

### Checklist

- [x]  I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [ ]  I have added an entry to my package's changelog.yml file. 
  - Not updating the `changelog` as this change doesn't relate to the changes that should be visible at user's end
- [x]  I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## How to test this PR locally

1. elastic-package check
2. elastic-package stack up -d -v
3. elastic-package test -v

## Related issues

- Relates #9824

## Screenshots

```
--- Test results for package: couchbase - START ---
╭───────────┬─────────────────┬───────────┬───────────────────────────┬────────┬─────────────────╮
│ PACKAGE   │ DATA STREAM     │ TEST TYPE │ TEST NAME                 │ RESULT │    TIME ELAPSED │
├───────────┼─────────────────┼───────────┼───────────────────────────┼────────┼─────────────────┤
│ couchbase │ bucket          │ system    │ default (variant: v7.1.0) │ PASS   │   54.538326822s │
│ couchbase │ cache           │ system    │ default (variant: v7.1.0) │ PASS   │ 1m13.962378817s │
│ couchbase │ cbl_replication │ system    │ default (variant: v7.1.0) │ PASS   │ 1m14.540847808s │
│ couchbase │ cluster         │ system    │ default (variant: v7.1.0) │ PASS   │   52.595722263s │
│ couchbase │ database_stats  │ system    │ default (variant: v7.1.0) │ PASS   │ 1m16.059139553s │
│ couchbase │ miscellaneous   │ system    │ default (variant: v7.1.0) │ PASS   │ 1m18.292679447s │
│ couchbase │ node            │ system    │ default (variant: v7.1.0) │ PASS   │   1m0.69584239s │
│ couchbase │ query_index     │ system    │ default (variant: v7.1.0) │ PASS   │   57.233809413s │
│ couchbase │ resource        │ system    │ default (variant: v7.1.0) │ PASS   │   54.237537472s │
│ couchbase │ xdcr            │ system    │ default (variant: v7.1.0) │ PASS   │   57.845970643s │
╰───────────┴─────────────────┴───────────┴───────────────────────────┴────────┴─────────────────╯
--- Test results for package: couchbase - END   ---
Done
```

2024-05-16 13:38 UTC, elasticmachine commented
### :rocket: Benchmarks report


#### Package `couchbase` :&#43;1:(4) :green_heart:(3) :broken_heart:(3)
<details>
<summary>Expand to view</summary>

Data stream | Previous EPS | New EPS | Diff (%) | Result
----------- | ------------ | ------- | -------- | ------
`miscellaneous` | 16949.15 | 14285.71 | -2663.44 (-15.71%) | :broken_heart:
`node` | 9090.91 | 7692.31 | -1398.6 (-15.38%) | :broken_heart:
`query_index` | 9523.81 | 7092.2 | -2431.61 (-25.53%) | :broken_heart:
</details>


To see the full report comment with `/test benchmark fullreport`
<!--COMMENT_GENERATED_WITH_ID_benchmark-report-->

2024-05-16 13:39 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/11555)
* Commit: 378b00d9d81d95a238ff9da380c8aefc07b1af29

cc @aliabbas-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11555","number":11555,"commit":"378b00d9d81d95a238ff9da380c8aefc07b1af29"}],"number":11555}
buildkite-pr-comment-->

2024-05-16 17:16 UTC, aliabbas-elastic commented
/test

2024-05-16 17:51 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/11581)
* Commit: 378b00d9d81d95a238ff9da380c8aefc07b1af29

### History
* :green_heart: [Build #11555](https://buildkite.com/elastic/integrations/builds/11555) succeeded 378b00d9d81d95a238ff9da380c8aefc07b1af29

cc @aliabbas-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11581","number":11581,"commit":"378b00d9d81d95a238ff9da380c8aefc07b1af29"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11555","number":11555,"commit":"378b00d9d81d95a238ff9da380c8aefc07b1af29"}],"number":11581}
buildkite-pr-comment-->

2024-05-17 06:47 UTC, shmsr requested changes

2024-05-17 06:47 UTC, shmsr commented on packages/couchbase/_dev/deploy/docker/files/setup.sh
> +until [ "$(curl -v -u Administrator:password -X POST http://localhost:8091/sampleBuckets/install -d '["beer-sample"]' -o /dev/null -w '%{http_code}')" -eq 202 ]
A lot of variables are repeating. Let's rewrite this script to be more readable, robust and maintainable.

```
ADMIN_USER="Administrator"
ADMIN_PASSWORD="password"
CB_HOST="localhost"
CB_PORT="8091"
BUCKET_NAME="beer-sample"
XDCR_CLUSTER_NAME="cluster"
XDCR_HOSTNAME="127.0.0.1"
REPLICATION_FROM_BUCKET="beer-sample"
REPLICATION_TO_CLUSTER="cluster"
REPLICATION_TO_BUCKET="travel-sample"
```

We can also use a single var for the host i.e., localhost or 127.0.0.1. Currently, both are there.

Also, if you wrap it in functions, this scripts looks cleaner.

```sh
is_couchbase_ready() {
  curl --silent --fail "http://${ADMIN_USER}:${ADMIN_PASSWORD}@${CB_HOST}:${CB_PORT}/pools/default" >/dev/null 2>&1
}

# To call the function
is_couchbase_ready
```

As no output from curl is necessary, redirect the standard streams to /dev/null. Health checks are typically written in this manner to avoid unnecessary actions.

Another sample function to make it more readable:

```sh
# Function to add sample bucket
add_cb_sample_bucket() {
  local bucket_name="$1"
  local http_code
  http_code=$(curl --silent --output /dev/null --write-out "%{http_code}" \
    --user "${ADMIN_USER}:${ADMIN_PASSWORD}" \
    --header "Content-Type: application/json" \
    --request POST \
    --data "[\"${bucket_name}\"]" \
    "http://${CB_HOST}:${CB_PORT}/sampleBuckets/install")

  if [[ "${http_code}" -eq 202 ]]; then
    return 0
  else
    return 1
  fi
}
```

And call it like:
```sh
while ! add_cb_sample_bucket "${BUCKET_NAME}"; do
  sleep 5
done
```

With this approach, the script looks much cleaner and also maintainable. Let me know what you think?

2024-05-17 06:47 UTC, shmsr commented on packages/couchbase/_dev/deploy/docker/files/setup.sh
>  # wait till the xdcr-setup creates cluster
Probably it is better to write that you are waiting for bucket to be ready. Comment is not clear here.

2024-05-17 06:47 UTC, shmsr commented on packages/couchbase/_dev/deploy/docker/docker-compose.yml
> +      test: ["CMD", "curl", "-f", "http://Administrator:password@localhost:8091/pools/default/buckets/beer-sample/stats"]
let's add -s as well here. silent and fail to all `curl`

2024-05-18 08:42 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/11661)
* Commit: b5165e170dcd667f237373e0c3a80038c8b3be0f

### History
* :green_heart: [Build #11581](https://buildkite.com/elastic/integrations/builds/11581) succeeded 378b00d9d81d95a238ff9da380c8aefc07b1af29
* :green_heart: [Build #11555](https://buildkite.com/elastic/integrations/builds/11555) succeeded 378b00d9d81d95a238ff9da380c8aefc07b1af29

cc @aliabbas-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11661","number":11661,"commit":"b5165e170dcd667f237373e0c3a80038c8b3be0f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11581","number":11581,"commit":"378b00d9d81d95a238ff9da380c8aefc07b1af29"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11555","number":11555,"commit":"378b00d9d81d95a238ff9da380c8aefc07b1af29"}],"number":11661}
buildkite-pr-comment-->

2024-05-18 10:04 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/11662)
* Commit: 503368920f9769f66b2efc46d099fbd60c545b46

### Failed CI Steps
* [Check integrations couchbase](https://buildkite.com/elastic/integrations/builds/11662#018f8b08-26b5-4d32-bfd4-748d4e6027c8)

### History
* :green_heart: [Build #11661](https://buildkite.com/elastic/integrations/builds/11661) succeeded b5165e170dcd667f237373e0c3a80038c8b3be0f
* :green_heart: [Build #11581](https://buildkite.com/elastic/integrations/builds/11581) succeeded 378b00d9d81d95a238ff9da380c8aefc07b1af29
* :green_heart: [Build #11555](https://buildkite.com/elastic/integrations/builds/11555) succeeded 378b00d9d81d95a238ff9da380c8aefc07b1af29

cc @aliabbas-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11662","number":11662,"commit":"503368920f9769f66b2efc46d099fbd60c545b46"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11661","number":11661,"commit":"b5165e170dcd667f237373e0c3a80038c8b3be0f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11581","number":11581,"commit":"378b00d9d81d95a238ff9da380c8aefc07b1af29"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11555","number":11555,"commit":"378b00d9d81d95a238ff9da380c8aefc07b1af29"}],"number":11662}
buildkite-pr-comment-->

2024-05-20 05:56 UTC, shmsr approved these changes
Script could still be better but let's do it some other time. For now, this is good. Thanks for addressing the comments.

2024-05-20 06:26 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/11676)
* Commit: 1aeacfc501ff7ed3f30eea4f498c0cb7e69e72f9

### History
* :broken_heart: [Build #11662](https://buildkite.com/elastic/integrations/builds/11662) failed 503368920f9769f66b2efc46d099fbd60c545b46
* :green_heart: [Build #11661](https://buildkite.com/elastic/integrations/builds/11661) succeeded b5165e170dcd667f237373e0c3a80038c8b3be0f
* :green_heart: [Build #11581](https://buildkite.com/elastic/integrations/builds/11581) succeeded 378b00d9d81d95a238ff9da380c8aefc07b1af29
* :green_heart: [Build #11555](https://buildkite.com/elastic/integrations/builds/11555) succeeded 378b00d9d81d95a238ff9da380c8aefc07b1af29

cc @aliabbas-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11676","number":11676,"commit":"1aeacfc501ff7ed3f30eea4f498c0cb7e69e72f9"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11662","number":11662,"commit":"503368920f9769f66b2efc46d099fbd60c545b46"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11661","number":11661,"commit":"b5165e170dcd667f237373e0c3a80038c8b3be0f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11581","number":11581,"commit":"378b00d9d81d95a238ff9da380c8aefc07b1af29"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11555","number":11555,"commit":"378b00d9d81d95a238ff9da380c8aefc07b1af29"}],"number":11676}
buildkite-pr-comment-->

2024-05-20 11:03 UTC, aliabbas-elastic commented
/test

2024-05-20 11:38 UTC, kush-elastic approved these changes
LGTM!

2024-05-21 04:23 UTC, aliabbas-elastic commented
/test

2024-05-21 04:54 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/11705)
* Commit: 1aeacfc501ff7ed3f30eea4f498c0cb7e69e72f9

### History
* :green_heart: [Build #11676](https://buildkite.com/elastic/integrations/builds/11676) succeeded 1aeacfc501ff7ed3f30eea4f498c0cb7e69e72f9
* :broken_heart: [Build #11662](https://buildkite.com/elastic/integrations/builds/11662) failed 503368920f9769f66b2efc46d099fbd60c545b46
* :green_heart: [Build #11661](https://buildkite.com/elastic/integrations/builds/11661) succeeded b5165e170dcd667f237373e0c3a80038c8b3be0f
* :green_heart: [Build #11581](https://buildkite.com/elastic/integrations/builds/11581) succeeded 378b00d9d81d95a238ff9da380c8aefc07b1af29
* :green_heart: [Build #11555](https://buildkite.com/elastic/integrations/builds/11555) succeeded 378b00d9d81d95a238ff9da380c8aefc07b1af29

cc @aliabbas-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11705","number":11705,"commit":"1aeacfc501ff7ed3f30eea4f498c0cb7e69e72f9"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11676","number":11676,"commit":"1aeacfc501ff7ed3f30eea4f498c0cb7e69e72f9"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11662","number":11662,"commit":"503368920f9769f66b2efc46d099fbd60c545b46"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11661","number":11661,"commit":"b5165e170dcd667f237373e0c3a80038c8b3be0f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11581","number":11581,"commit":"378b00d9d81d95a238ff9da380c8aefc07b1af29"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11555","number":11555,"commit":"378b00d9d81d95a238ff9da380c8aefc07b1af29"}],"number":11705}
buildkite-pr-comment-->

2024-05-21 05:14 UTC, aliabbas-elastic commented
/test

2024-05-21 05:35 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/11709)
* Commit: 1aeacfc501ff7ed3f30eea4f498c0cb7e69e72f9

### Failed CI Steps
* [Check integrations couchbase](https://buildkite.com/elastic/integrations/builds/11709#018f9995-7c99-4f99-b537-9ca09ea10662)

### History
* :green_heart: [Build #11705](https://buildkite.com/elastic/integrations/builds/11705) succeeded 1aeacfc501ff7ed3f30eea4f498c0cb7e69e72f9
* :green_heart: [Build #11676](https://buildkite.com/elastic/integrations/builds/11676) succeeded 1aeacfc501ff7ed3f30eea4f498c0cb7e69e72f9
* :broken_heart: [Build #11662](https://buildkite.com/elastic/integrations/builds/11662) failed 503368920f9769f66b2efc46d099fbd60c545b46
* :green_heart: [Build #11661](https://buildkite.com/elastic/integrations/builds/11661) succeeded b5165e170dcd667f237373e0c3a80038c8b3be0f
* :green_heart: [Build #11581](https://buildkite.com/elastic/integrations/builds/11581) succeeded 378b00d9d81d95a238ff9da380c8aefc07b1af29
* :green_heart: [Build #11555](https://buildkite.com/elastic/integrations/builds/11555) succeeded 378b00d9d81d95a238ff9da380c8aefc07b1af29

cc @aliabbas-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11709","number":11709,"commit":"1aeacfc501ff7ed3f30eea4f498c0cb7e69e72f9"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11705","number":11705,"commit":"1aeacfc501ff7ed3f30eea4f498c0cb7e69e72f9"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11676","number":11676,"commit":"1aeacfc501ff7ed3f30eea4f498c0cb7e69e72f9"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11662","number":11662,"commit":"503368920f9769f66b2efc46d099fbd60c545b46"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11661","number":11661,"commit":"b5165e170dcd667f237373e0c3a80038c8b3be0f"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11581","number":11581,"commit":"378b00d9d81d95a238ff9da380c8aefc07b1af29"}],"number":11709}
buildkite-pr-comment-->

2024-05-21 06:27 UTC, shmsr commented on packages/couchbase/_dev/deploy/docker/files/setup.sh
> +#!/bin/bash
```suggestion
#!/bin/bash

```

2024-05-21 06:27 UTC, shmsr approved these changes

2024-05-21 06:44 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/11712)
* Commit: 5abb57984555019d1c7288d7d936c2293aec4456

### Failed CI Steps
* [Check integrations couchbase](https://buildkite.com/elastic/integrations/builds/11712#018f99e0-77d0-4fc7-be54-5c4d54af8f5b)

### History
* :broken_heart: [Build #11709](https://buildkite.com/elastic/integrations/builds/11709) failed 1aeacfc501ff7ed3f30eea4f498c0cb7e69e72f9
* :green_heart: [Build #11705](https://buildkite.com/elastic/integrations/builds/11705) succeeded 1aeacfc501ff7ed3f30eea4f498c0cb7e69e72f9
* :green_heart: [Build #11676](https://buildkite.com/elastic/integrations/builds/11676) succeeded 1aeacfc501ff7ed3f30eea4f498c0cb7e69e72f9
* :broken_heart: [Build #11662](https://buildkite.com/elastic/integrations/builds/11662) failed 503368920f9769f66b2efc46d099fbd60c545b46
* :green_heart: [Build #11661](https://buildkite.com/elastic/integrations/builds/11661) succeeded b5165e170dcd667f237373e0c3a80038c8b3be0f

cc @aliabbas-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11712","number":11712,"commit":"5abb57984555019d1c7288d7d936c2293aec4456"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11709","number":11709,"commit":"1aeacfc501ff7ed3f30eea4f498c0cb7e69e72f9"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11705","number":11705,"commit":"1aeacfc501ff7ed3f30eea4f498c0cb7e69e72f9"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11676","number":11676,"commit":"1aeacfc501ff7ed3f30eea4f498c0cb7e69e72f9"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11662","number":11662,"commit":"503368920f9769f66b2efc46d099fbd60c545b46"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11661","number":11661,"commit":"b5165e170dcd667f237373e0c3a80038c8b3be0f"}],"number":11712}
buildkite-pr-comment-->

2024-05-21 13:25 UTC, aliabbas-elastic commented
/test

2024-05-21 13:56 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/11722)
* Commit: 5abb57984555019d1c7288d7d936c2293aec4456

### History
* :broken_heart: [Build #11712](https://buildkite.com/elastic/integrations/builds/11712) failed 5abb57984555019d1c7288d7d936c2293aec4456
* :broken_heart: [Build #11709](https://buildkite.com/elastic/integrations/builds/11709) failed 1aeacfc501ff7ed3f30eea4f498c0cb7e69e72f9
* :green_heart: [Build #11705](https://buildkite.com/elastic/integrations/builds/11705) succeeded 1aeacfc501ff7ed3f30eea4f498c0cb7e69e72f9
* :green_heart: [Build #11676](https://buildkite.com/elastic/integrations/builds/11676) succeeded 1aeacfc501ff7ed3f30eea4f498c0cb7e69e72f9
* :broken_heart: [Build #11662](https://buildkite.com/elastic/integrations/builds/11662) failed 503368920f9769f66b2efc46d099fbd60c545b46

cc @aliabbas-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11722","number":11722,"commit":"5abb57984555019d1c7288d7d936c2293aec4456"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11712","number":11712,"commit":"5abb57984555019d1c7288d7d936c2293aec4456"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11709","number":11709,"commit":"1aeacfc501ff7ed3f30eea4f498c0cb7e69e72f9"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11705","number":11705,"commit":"1aeacfc501ff7ed3f30eea4f498c0cb7e69e72f9"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11676","number":11676,"commit":"1aeacfc501ff7ed3f30eea4f498c0cb7e69e72f9"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11662","number":11662,"commit":"503368920f9769f66b2efc46d099fbd60c545b46"}],"number":11722}
buildkite-pr-comment-->

2024-05-22 10:31 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/11758)
* Commit: 45d726e60159824be4460984daed7ce0cce7c337

### History
* :green_heart: [Build #11722](https://buildkite.com/elastic/integrations/builds/11722) succeeded 5abb57984555019d1c7288d7d936c2293aec4456
* :broken_heart: [Build #11712](https://buildkite.com/elastic/integrations/builds/11712) failed 5abb57984555019d1c7288d7d936c2293aec4456
* :broken_heart: [Build #11709](https://buildkite.com/elastic/integrations/builds/11709) failed 1aeacfc501ff7ed3f30eea4f498c0cb7e69e72f9
* :green_heart: [Build #11705](https://buildkite.com/elastic/integrations/builds/11705) succeeded 1aeacfc501ff7ed3f30eea4f498c0cb7e69e72f9
* :green_heart: [Build #11676](https://buildkite.com/elastic/integrations/builds/11676) succeeded 1aeacfc501ff7ed3f30eea4f498c0cb7e69e72f9
* :broken_heart: [Build #11662](https://buildkite.com/elastic/integrations/builds/11662) failed 503368920f9769f66b2efc46d099fbd60c545b46

cc @aliabbas-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11758","number":11758,"commit":"45d726e60159824be4460984daed7ce0cce7c337"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11722","number":11722,"commit":"5abb57984555019d1c7288d7d936c2293aec4456"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11712","number":11712,"commit":"5abb57984555019d1c7288d7d936c2293aec4456"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11709","number":11709,"commit":"1aeacfc501ff7ed3f30eea4f498c0cb7e69e72f9"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11705","number":11705,"commit":"1aeacfc501ff7ed3f30eea4f498c0cb7e69e72f9"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11676","number":11676,"commit":"1aeacfc501ff7ed3f30eea4f498c0cb7e69e72f9"}],"number":11758}
buildkite-pr-comment-->

2024-05-22 11:38 UTC, merged