[O11y][Airflow] Update documentation
elastic/integrations pull request #9950
Opened 2024-05-23 05:08 UTC by harnish-elastic

- Enhancement

## Proposed commit message

- Update README as per documentation_guidelines.

## Checklist

- [x] I have reviewed [tips for building integrations](https://github.com/elastic/integrations/blob/main/docs/tips_for_building_integrations.md) and this pull request is aligned with them.
- [x] I have verified that all data streams collect metrics or logs.
- [x] I have added an entry to my package's `changelog.yml` file.
- [x] I have verified that Kibana version constraints are current according to [guidelines](https://github.com/elastic/elastic-package/blob/master/docs/howto/stack_version_support.md#when-to-update-the-condition).

## Related issues

- Closes #9805

## Screenshots

<details>
  <summary>Airflow Integration Page</summary>

   ![image](https://github.com/elastic/integrations/assets/118714680/28435458-5f57-4e03-ae95-049f5a318321)

</details>

2024-05-23 05:23 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/11797)
* Commit: ad26e2f50f57842357df912329544d5e0463fb88

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11797","number":11797,"commit":"ad26e2f50f57842357df912329544d5e0463fb88"}],"number":11797}
buildkite-pr-comment-->

2024-05-23 07:11 UTC, niraj-elastic commented on packages/airflow/_dev/build/docs/README.md
> +- Users can monitor and view metrics within the ingested documents for Airflow in the `metrics-*` index pattern from `Discover`.
Do we need this note? generally we use this note when there is mismatch between type of data we are collecting (i.e. Metrics) and Type of index pattern (I.e. logs-*) reason being type of input we use to fetch the data. for example, when we use `httpjson input` to fetch metric type of data. In that case `Metrics` will be indexed under `logs-*` index. But here I don't think this note is needed.

2024-05-28 04:42 UTC, harnish-elastic commented on packages/airflow/_dev/build/docs/README.md
> +- Users can monitor and view metrics within the ingested documents for Airflow in the `metrics-*` index pattern from `Discover`.
Yes, we need this note. If the new user want to see what is the default index of a particular package, then by reading this note they have idea where my logs/metrics actually indexed. Also we have done the same thing in other integrations as well.

2024-05-28 06:30 UTC, shmsr requested changes

2024-05-28 06:30 UTC, shmsr commented on packages/airflow/_dev/build/docs/README.md
> +- Keep track of your workflows performance and status with real-time monitoring capabilities.
```suggestion
- Collect detailed metrics from Airflow using StatsD to gain insights into system performance.
- Create informative visualizations to track usage trends, measure key metrics, and derive actionable business insights.
- Monitor your workflows' performance and status in real-time.
```

2024-05-28 06:30 UTC, shmsr commented on packages/airflow/_dev/build/docs/README.md
> +[Airflow](https://airflow.apache.org/docs/apache-airflow/stable/logging-monitoring/metrics.html) is a platform to programmatically author, schedule and monitor workflows. Airflow is used to author wo
```suggestion
[Airflow](https://airflow.apache.org/docs/apache-airflow/stable/logging-monitoring/metrics.html) is an open-source platform for programmatically authoring, scheduling, and monitoring workflows. It allows users to define workflows as Directed Acyclic Graphs (DAGs) of tasks, which are then executed by the Airflow scheduler on an array of workers while following the specified dependencies.
```

2024-05-28 06:30 UTC, shmsr commented on packages/airflow/_dev/build/docs/README.md
> +Metrics give you insight into the statistics of the Airflow. The `Metric` data stream collected by the Airflow integration is `statsd` so that the user can monitor and troubleshoot the performance of
```suggestion
The Airflow integration gathers metric data.

Metrics provide insight into the statistics of Airflow. The `Metric` data stream collected by the Airflow integration is `statsd`, enabling users to monitor and troubleshoot the performance of the Airflow instance.
```

2024-05-28 06:30 UTC, shmsr commented on packages/airflow/_dev/build/docs/README.md
> +In order to ingest data from the Airflow, user must have [statsd](https://github.com/statsd/statsd) to receive statsd metrics.
```suggestion
Users require Elasticsearch to store and search user data, and Kibana to visualize and manage it. They can utilize the hosted Elasticsearch Service on Elastic Cloud, which is recommended, or self-manage the Elastic Stack on their own hardware.

To ingest data from Airflow, users must have [StatsD](https://github.com/statsd/statsd) to receive the same.
```

2024-05-28 06:30 UTC, shmsr commented on packages/airflow/_dev/build/docs/README.md
> +Add the following lines to user's Airflow configuration file e.g. `airflow.cfg` ensuring `statsd_prefix` is left empty and replace `%HOST%` with the address agent is running:
```suggestion
Be sure to follow the official [Airflow Installation Guide](https://airflow.apache.org/docs/apache-airflow/stable/installation/index.html) for the correct installation of Airflow.

Include the following lines in the user's Airflow configuration file (e.g. `airflow.cfg`). Leave `statsd_prefix` empty and replace `%HOST%` with the address where the Agent is running:
```

2024-05-28 06:30 UTC, shmsr commented on packages/airflow/_dev/build/docs/README.md
> +After the integration is successfully configured, clicking on the Assets tab of the Airflow integration should display a list of available dashboards. Click on the dashboard available for user's conf
```suggestion
Once the integration is set up, you can click on the Assets tab in the Airflow integration to see a list of available dashboards. Choose the dashboard that corresponds to your configured data stream. The dashboard should be populated with the required data.
```

The tone of the full sentence is the same now.

2024-05-28 06:30 UTC, shmsr commented on packages/airflow/_dev/build/docs/README.md
> +- In case Airflow metrics are not being emitted, confirm that the `[metrics]` section in the `airflow.cfg` file is properly configured as per the instructions above.
```suggestion
- Check if the StatsD server is receiving data from Airflow by examining the logs for potential errors.
- Make sure the `%HOST%` placeholder in the Airflow configuration file is replaced with the correct address of the machine where the StatsD server is running.
- If Airflow metrics are not being emitted, confirm that the `[metrics]` section in the `airflow.cfg` file is properly configured as per the instructions above.
```

2024-05-28 06:30 UTC, shmsr commented on packages/airflow/_dev/build/docs/README.md
> +This is the `statsd` data stream. This data stream collects metrics related to scheduler activities, pool usage, task execution details, executor performance, and worker states in Airflow.
```suggestion
This is the `statsd` data stream, which collects metrics related to scheduler activities, pool usage, task execution details, executor performance, and worker states in Airflow.
```

2024-05-28 10:58 UTC, harnish-elastic commented on packages/airflow/_dev/build/docs/README.md
> +This is the `statsd` data stream. This data stream collects metrics related to scheduler activities, pool usage, task execution details, executor performance, and worker states in Airflow.
@devamanv I think the format that we are following across all the package is containing `This is the `statsd` data stream`. So I think we can keep consistency with the other packages!

2024-05-28 11:00 UTC, shmsr approved these changes

2024-05-28 11:02 UTC, devamanv approved these changes

2024-05-28 11:02 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/integrations/builds/11984)
* Commit: 0be1ff6d02dcf6a56ec23c4ee93561e7636408b0

### History
* :green_heart: [Build #11797](https://buildkite.com/elastic/integrations/builds/11797) succeeded ad26e2f50f57842357df912329544d5e0463fb88

cc @harnish-elastic

<!--buildkite-pr-comment-integrations
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11984","number":11984,"commit":"0be1ff6d02dcf6a56ec23c4ee93561e7636408b0"},{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/integrations/builds/11797","number":11797,"commit":"ad26e2f50f57842357df912329544d5e0463fb88"}],"number":11984}
buildkite-pr-comment-->

2024-05-28 11:03 UTC, niraj-elastic approved these changes

2024-05-28 12:28 UTC, merged

2024-05-28 12:42 UTC, elasticmachine commented
Package airflow - 0.7.0 containing this change is available at https://epr.elastic.co/search?package=airflow